### ISSUE TITLE
[Feature] Run script after request

### ISSUE THREAD

**Issue by OmgImAlexis** [caddyserver/caddy#1603]
Nginx has [post_action](http://mailman.nginx.org/pipermail/nginx/2008-April/004524.html) which allows a script after a request is finished.
Hopefully [this link](http://mailman.nginx.org/pipermail/nginx/2008-April/004524.html) explains the reason I want this added.

Here's some documentation for how Nginx handles it.
https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/

Looks like this may be related in way to https://github.com/mholt/caddy/issues/979

**Comment by lbguilherme** [comment]
You can do this with https://caddyserver.com/docs/http.cgi
But this way your script must also answer the request itself, then close stdout and continue (or launch another process and close)

**Comment by OmgImAlexis** [comment]
For requests to my own servers that would work fine but for example if I wanted to use that to hit google analytics to track downloads, etc. I'm not sure it'd work as suggested.

**Comment by goku321** [comment]
I would like to work on this if it's okay.

**Comment by mholt** [comment]
@goku321 That would be fine! I would suggest creating a new repo and following this guide to get you started: https://caddyserver.com/docs/extending-caddy

I will close this then since it will be implemented as a plugin -- feel free to link to your repo here so we can follow along! :+1:

**Comment by KaKi87** [comment]
Hello,
Where's the plugin ?
Thanks

**Comment by mholt** [comment]
https://caddyserver.com/docs/modules/http.handlers.exec
