### ISSUE TITLE
proxy: Rewrite the proxy middleware

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#1639]
The `proxy` middleware needs to be rewritten, building upon the fabulous work already put in by contributors to date. These plans are tentative and subject to change.

It will be rewritten from scratch, but with very few (if any) Caddyfile syntax changes (hopefully). This is a "guided rewrite", meaning that the current proxy code (which is very intricate) will be used as a reference for the rewrite. My hope is that we can accomplish these goals to make Caddy into a more competitive, useful reverse proxy:

- Continue supporting "static" backends (which is the only kind of backend currently supported)
- Add support for "dynamic" backends (backends based on parameters of the request on-the-fly or based on external environment, see #564, #1630 (?), #1894, #199, #990, and its related PR #998)
- Make the list of supported protocols extensible by plugins (fastcgi, uwsgi, etc.) -- all protocols share same core proxy code, but each can do the RoundTrip their own way. This could even work for the [`websocket` directive](https://caddyserver.com/docs/websocket), potentially -- note that this is _different from proxy's websocket preset!_ (#1638)
- _Potentially_ lay the ground work for DNS-based load balancing (?) #1545 
- Ability to proxy to error pages (#753)
- Ability to have the `errors` directive handle errors from upstream (rather than only errors connecting to upstream)
- _Potentially_ custom health checks (#324)
- Straighten out the retry logic (#1135, also see #1314 and #1460) - ideally we never buffer the response unless explicitly configured/required to do so
- Cf. #1772 and #606

This may take a few weeks once work commences. 

/cc @abiosoft @nemosupremo - I will probably have questions as I go through this, so expect to hear from me. :)

**Comment by jrobeson** [comment]
would this help achieve https://github.com/mholt/caddy/issues/1460 too?

**Comment by mholt** [comment]
@jrobeson Quite likely, yes. If I can do it right.

**Comment by Stonedestroyer** [comment]
Would this be implemented as well? https://github.com/mholt/caddy/issues/606 considering it pertains to the proxy plugin.

**Comment by mholt** [comment]
@Stonedestroyer Yes, I think it definitely could be.

**Comment by lvhuat** [comment]
so，what the issue going on now？

**Comment by yura8** [comment]
This would help https://github.com/mholt/caddy/issues/1891 too.

**Comment by mholt** [comment]
I won't have time to work on this for the coming year or so. If anyone is skilled in writing proxies and would like to take the lead at rewriting it, please chime in!

**Comment by mholt** [comment]
This rewrite is done in v2. It's not feature-complete but should be able to support all the features that have been requested, one way or another. (Contributions welcomed!)

**Comment by mholt** [comment]
Caddy 2 now allows a dynamic address for upstreams, as implemented in 1e31be8.

I think that pretty much finishes up this rewrite. There's still one matter related to error handling that I want to attend to but that's another open issue (#1447).

Go try it out!
