### ISSUE TITLE
Adding a noLatencyWriter to reverseproxy

### ISSUE THREAD

**Issue by laszbalo** [caddyserver/caddy#1972]
At the moment Caddy flushes its buffers in every 250 ms via the maxLatencyWriter. I want to stream HTML snippets from my upstream servers, as fast as possible. Having to wait a maximum of 250 ms for the flusher gorutine just seems unnecessary. Is there any reason why a noLatencyWriter has not been added to Caddy, yet? This is my current implementation(pretty much just renaming and deletion of a few lines):

```golang
type noLatencyWriter struct {
  dst     writeFlusher
}

func (m *noLatencyWriter) Write(p []byte) (int, error) {
  n, err := m.dst.Write(p)
  if err != nil {
     m.dst.Flush()
  }
  return n, err
}


// usage:
func (rp *ReverseProxy) copyResponse(dst io.Writer, src io.Reader) {
  if wf, ok := dst.(writeFlusher); ok {
    nlw := &noLatencyWriter {
      dst: wf,
    }
    dst = nlw
  }
  pooledIoCopy(dst, src)
}


```

With thanks,
Laszlo

**Comment by mholt** [comment]
It's been so long, I'm not even sure anymore, ha. I dunno if @nemosupremo has any thoughts on this (it's been even longer since he contributed it, if I recall correctly!) but I would be open to this idea. I agree it would be useful.

**Comment by tw4452852** [comment]
Maybe we could make this option configurable.

**Comment by My1** [comment]
on that whole no latency write thing, something similar for PHP would be honestly awesome. that way someone could start a page, do some processing in the background (like crazy password hashing) and then complete the site.

**Comment by mholt** [comment]
#1460 seems to suggest one reason for the periodic flushing.

**Comment by mholt** [comment]
I'll repost what I said in the linked issue, if someone could try this out with the v2 branch? I think we're in a much better place now.

Caddyfile documentation: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#reverse_proxy

Or native JSON docs: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy

**Comment by mholt** [comment]
Possible in v2 by setting flush_interval to -1.
