### ISSUE TITLE
Redirect to remove trailing slash

### ISSUE THREAD

**Issue by jakelucas** [caddyserver/caddy#2011]
One thing that I think is quite a common requirement for a lot of websites is to redirect to remove a trailing slash from the URL.

This is most likely done for SEO reasons or because an application expects that URLs for pages don't have trailing slashes.

Adding a trailing slash is simple since you can just match a `{path}` that doesn't end in `/` and just redirect to the desired path with a `/` added onto the end, but removing a trailing slash is a little more involved and there isn't an immedietly obvious solution in the docs unless you connect the dots and realise that you can use request placeholders like `{rewrite_uri}` in the `redir` directive after a rewrite has taken place.

Currently it's possible to remove trailing slashes by using the `rewrite` directive in combination with the `redir` directive, for example:

```txt
rewrite {
    if {path} not /
    if {path} ends_with /
    r ^/(.*)/$
    to /{1}
}

redir 301 {
    if {path} not /
    if {path} ends_with /
    / {rewrite_uri}
}
```

My only real problem with this is the use of a regular expression, since the non-obvious solution can just be documented as an example if needed.

The docs say:

> Extremely high-load servers should avoid using regular expressions.

Which makes perfect sense.

While this regular expression is only run for paths that end in a `/` I think that removing a trailing slash is a common enough use case that it would be useful to have some built in way to do this without a regular expression, especially since the faster alternative code would just be something as simple as `p =
 p[:len(p)-1]`.

If this is a feature that would be welcome then I'm not really sure of the best way to implement it since I'm not familiar at all with the Caddy code base or what kind of changes would be ok to make to existing directives.

My initial thought was to just add some new placeholders that don't include the trailing slash, but this might be overkill for such a simple feature request.

Some request placeholders seem to have a special character that comes before them to denote a special meaning, such as `{~cookie}` to get the value of a cookie, or `{?key}` for the argument value of a query string parameter. Perhaps it would be worth thinking about a modifier that can trim a certain character from the value, for example `{!/uri}`?

The problem with the modifier example is that it could open up expectations of modifiers working for any characters which might make the scope of the change too broad, unless one modifier was chosen to only trim slashes and that's all it does.

Another option might be to introduce another sub-directive in the `redir` directive that just tells Caddy the redirect is for the sole purpose of removing a trailing slash, for example:

```txt
redir 301 {
    remove_slash
}
```

Or it could work like the presets in things like the `proxy` directive where it could expand out to some `if` sub-directives plus some other sub-directive that allows you to trim characters without the need for regular expressions.

If this is something that you think should be implemented then I'm willing to get to know the Caddy code base and try to add it in, but that should of course come after some discussion on how it should be implemented or if it's even really needed, since it might be covered by some other more general feature request anyway.

Of course it could also be argued that this kind of redirect won't be run enough to warrant adding it into Caddy in the first place, and the solution might just be to document an example of using `rewrite` with `redir` to remove the trailing slash, along with a note about the potential downside of regular expressions for high traffic sites.

Please let me know what you think. Either way is fine for me, it just seemed like a common use case that was worth looking at.

**Comment by mholt** [comment]
The very, very first version of Caddy (like, v0.5.0) had `ext` which is a directive that is a special case of rewrite. Sure, you can use rewrite to match URLs without a file extension. It's just so common that it merited its own directive. I'm OK with that -- I prefer small, simple directives that are intuitive.

So if stripping the trailing slash is common enough, we can just make it its own directive.

I don't suppose there's a clever way of using `ext /` (i.e. treat the slash as if it were a file extension) to do what you want?

In the meantime, let's gauge demand for this by counting the :+1: reactions to your post. (I personally have not used a redirect to remove trailing slashes...)

**Comment by martpie** [comment]
@jakelucas I am trying to add your snippet to my config, but restarting Caddy gives me infinite redirects.

I typically have this website:

```
index.html
blog/index.html // I cannot change that to blog.html, this is the way the framework I use generates this page
```

When trying to access `./blog`, Caddy 301 redirects to `/blog/`, which does not really look clean.

Looking at Caddy's code [here](https://github.com/mholt/caddy/blob/master/caddyhttp/staticfiles/fileserver.go#L114), I see that it looks like an intentional behavior, but I do not understand why.

Nginx does that with `try_files` directive, but it seems Caddy is more restrictive/opinionated here, could you explain this choice @mholt? And is there any way to bypass it?

**Comment by abiosoft** [comment]
@martpie 

The snippet you pointed to only has effect when the request is handled by the file server, not when rewrite has previously handled the request.

This should work for your use case.
```
rewrite {
  if {path} is /blog 
  to /blog/index.html?{query}
}
```

**Comment by martpie** [comment]
Thank you for the tip. It unfortunately does not scale (I potentially have dozens of pages like that).

It is a quite common architecture for static-generated websites, a web server should be as agnostic as possible regarding the file architecture of a website.

Not quite urgent though, I can go back to nginx + certbot in the meantime, but I just wanted to point that problem and explain my usecase :)

**Comment by whitestrake** [comment]
A generic version of the above rewrite might look like:

```
rewrite {
  to {path}/index.html?{query} {path}
}
```

Where, for every request, it will check if the requested path has an index file inside the directory, and fall back to the original requested path if that isn't the case.

**Comment by whitestrake** [comment]
Ahh... The static file server doesn't care about the rewrite, it redirects canonically regardless. On top of that, with the generic rewrite, the request to `/blog/` gets rewritten to `/blog//index.html?{query}`, which gets cleaned up to `/blog/index.html?`, which gets redirected again. Both approaches will not work.

You will have to rewrite to the canonical index - just drop the `index.html` entirely, from either the specific or generic version.

```
rewrite {
  to {path}/index.html?{query} {path}
}
```

**Comment by mholt** [comment]
(All development work is now focused on Caddy 2, so...)

There was some similar discussion recently about an easy way to strip a prefix from the path as well: https://github.com/caddyserver/caddy/issues/2813

I wonder if we should introduce quick, non-regex-based ways to do this in Caddy 2. Right now it can be done using regex in the `rewrite` handler, but that seems tedious when all we have to do is call `strings.TrimPrefix()` or `strings.TrimSuffix()`, which is much faster than any regex.

And I bet trimming beginnings and ends of paths will be a common need.

Am open to proposals that can find a general, elegant way of implementing this into v2!

**Comment by mholt** [comment]
@jakelucas @whitestrake I just implemented this as an experiment (Caddy 2):

```
{
    "handler": "rewrite",
    "strip_path_suffix": "/",
    "http_redirect": 307
}
```

And it works great, super easy, very convenient and fast.

I figure there will be certain rewrites that are more common than others, and this is one of them: stripping prefixes and suffixes.

The only weird thing is the `http_redirect` property, which allows you to immediately issue an HTTP redirect to the updated path. The `rewrite` handler is primarily used for internal rewrites, but this is just a convenient/quick way to issue an HTTP response that only redirects to an updated path. Is that a good idea or should we leave it separate do you think?

Let me know what you think in general too and I can push this.

**Comment by jakelucas** [comment]
@mholt I actually quite like the `http_redirect` property being bundled in with the `rewrite`, mostly because it stops your redirects being scattered across different handlers that you'd need to be careful to read in order to understand why a certain rewrite/redirect might be happening.

I understand what you mean about it being a little weird having the `http_redirect` in a `rewrite`, but typically this kind of redirect is something you want to do as early on in the request as possible, so I think it's a nice convinience to have and makes the purpose of the `rewrite` clearer.

That being said, it's not difficult to read a few handlers in a caddy file to figure out what's going on, and I haven't had much time to play around with Caddy 2 yet, so I could be talking rubbish, but those are my thought at a glance at least :)

**Comment by mholt** [comment]
@jakelucas Good enough for me, fixed in 208f2ff93c1bd2c009e4b96f664c1808ede79f3a. Thanks!

**Comment by MatthiasKunnen** [comment]
For anyone that needs to address this issue, the `http_redirect` option that was supposed to solve this, has been removed in https://github.com/caddyserver/caddy/commit/25dea2903e613534e00a2a4e305e0c8f2daeea8d.

As an alternative, the regex hot path can be avoided using the AND-ness of matchers, like this:

```json
{
	"match": [
		{
			"path": ["*/"],
			"path_regexp": {
				"name": "trailing_slash_removal",
				"pattern": "^(/.*)/$"
			}
		}
	],
	"handle": [
		{
			"handler": "static_response",
			"status_code": 308,
			"headers": {
				"Location": ["{http.regexp.trailing_slash_removal.1}"]
			}
		}
	]
},
```

This way, it performs the faster path match first and then the more expensive regex to perform the replace. I checked using a debugger that `path` actually executes first and `path_regexp` is not executed when `path` does not match.

A small bench I performed did not show a major increase in speed, just 0.66 % more rps, between adding or removing the faster `path` match to route. I might do more rigorous benchmarks later, there were too many uncontrolled variables in this one.

If there were a simple "trim" handler, this solution could be improved.

**Comment by whitestrake** [comment]
> If there were a simple "trim" handler, this solution could be improved.

How performant is simply using rewrite to strip the suffix?

```
              "handle": [
                {
                  "handler": "rewrite",
                  "strip_path_suffix": "/"
                },
                {
                  "handler": "static_response",
                  "status_code": 308,
                  "headers": {
                    "Location": [
                      "{http.request.uri}"
                    ]
                  }
                }
              ]
```

**Comment by francislavoie** [comment]
This issue was for Caddy v1. Caddy v2 was a complete rewrite, so this issue is not at all relevant.
