### ISSUE TITLE
Syslog - request logs and errors are both logged at error, request logs should be info

### ISSUE THREAD

**Issue by chrisvanderpennen** [caddyserver/caddy#2019]
It looks like in #1301 when the logger for the log and errors directives were merged, the difference in log level between the two was missed and all syslog messages are sent as errors.  This is making it difficult to differentiate between the two types of logs when shipping them to an elk instance for analysis.

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.10 (unofficial)

### 2. What are you trying to do?
Log requests and errors to an elk instance via remote syslog, parsing the combined log format into structured data and leaving error messages unmodified

### 3. What is your entire Caddyfile?
```text
https://{$PUBLIC_HOST_NAME}
log / syslog://logstash:5000 "{combined} {latency_ms}"
errors syslog://logstash:5000

[snip 200 lines of reverse-proxy mapping]
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Environment: Docker container based on `alpine:3.6` and `abiosoft/caddy:builder`, hosted on ubuntu 16.04
Command line is `/usr/bin/caddy --conf /etc/Caddyfile --log stdout --agree`

### 5. Please paste any relevant HTTP request(s) here.
n/a

### 6. What did you expect to see?
Request logs at severity info, errors at severity error

### 7. What did you see instead (give full error messages and/or log)?
Request logs and errors are both logged at severity error

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
```text
http://localhost
log / syslog "{combined}"
errors syslog

proxy /fail/ host.that.doesnt.exist
```
navigate to http://localhost/fail/

**Comment by mholt** [comment]
@wendigo What do you think about this? Is it possible to differentiate the two levels per-directive for the syslog?

@chrisvanderpennen For what it's worth, Caddy doesn't have "log levels" officially; on some messages we control we usually output "ERROR" or "INFO" or whatever, but we'll have to see if it's feasible to separate these with our syslog package.

**Comment by chrisvanderpennen** [comment]
Fair enough.  Prior to the update `log` and `errors` used different syslog severity levels, passing `gsyslog.LOG_INFO` and `gsyslog.LOG_ERROR` to `gsyslog.NewLogger`, but not having any actual Go experience I'm not sure how hard it's going to be to tell which directive is requesting a logger instance [here](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/logger.go#L131) and [here](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/logger.go#L137).

Meanwhile I can probably open up a second port on logstash and direct errors to it.  That should let me process them separately <sup>why didn't i think of that earlier</sup>

**Comment by mholt** [comment]
Ah, I see; so we need a way, when we get a logger for the log directive and another one for the errors directive, to specify log level.

**Comment by narthollis** [comment]
In other applications, when specifying syslog output, its generally possible to pass additional arguments, eg. level, and facility. It would be great to be able to do this in Caddy also.

Nginx syslog config page for example of passing additional parameters http://nginx.org/en/docs/syslog.html

**Comment by susannepeng** [comment]
+1, would really love to see this change. Unfortunately I'm unable to offer anything of more value as this is an area outside of my expertise but just felt I should add another voice here!

**Comment by mholt** [comment]
This should be resolved now in Caddy 2's logs. Give it a try!
