### ISSUE TITLE
Missing redirect to slashed url if using templates

### ISSUE THREAD

**Issue by natrim** [caddyserver/caddy#2114]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.12

### 2. What are you trying to do?
when i navigate to domain.com/folder
i see only white page instead of getting redirected to domain.com/folder/
happens only if templates are on

### 3. What is your entire Caddyfile?
```text
errors stderr

templates {
   path    /
   ext     .html
   between {| |}
}
```

### 6. What did you expect to see?
when i navigate to domain.com/folder
i expect to be redirected to domain.com/folder/
and see the page (index.html)

### 7. What did you see instead (give full error messages and/or log)?
when i navigate to domain.com/folder
i see only white page instead of getting redirected to domain.com/folder/

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
just folder with subfolder with index.html and templates set to /

**Comment by jimjimovich** [comment]
I just checked this on version 0.10.14 (official) and can confirm the original bug.

In addition, this also is the case for /index.html
Without using templates, going to /index.html will redirect you to /
When using templates, /index.html gives you a blank screen.

I think it has something to do with PR #1649 
I'm running into the same problem with the rewrite of the markdown plugin. I'm not sure where this 301 redirect is normally coming from and why template plugin is breaking this redirect.

Configs used
```
0.0.0.0:8080
root /path/to/public
gzip
templates / .html
```

```
0.0.0.0:8080
root /path/to/public
gzip
markdown /test/ {
    ext         .html
    template    templates/default.html
}
```

**Comment by miekg** [comment]
will this be only fixed in 2.0? Or is it easy enough of a fix to be backported to caddy 1?

**Comment by mholt** [comment]
I don't know how to fix it in Caddy 1, without a change in the design. Hence Caddy 2. PRs welcome I suppose, but I don't spend much time on Caddy 1 anymore.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddyserver/caddy] Missing red..." ]
>I don't know how to fix it in Caddy 1, without a change in the design. Hence Caddy 2. PRs welcome I suppose, but I don't spend much time on Caddy 1 anymore.

ah, ok, so it goes deep. No worries. Any custom plugins written for caddy 1 work 
in caddy 2? Or does this need source changes?

**Comment by mholt** [comment]
Yeah, sorry :( Maybe there's a hacky fix that's pretty simple but I haven't made it a priority...

> Any custom plugins written for caddy 1 work in caddy 2? Or does this need source changes?

Caddy 2's architecture is different. Depending on the plugin, it might be pretty simple to adapt it. For example, HTTP handlers can probably keep most of their core logic the same. But a few things have changed: how plugins are registered, the fact that plugins don't need to do their own request matching anymore, and the caddyfile integration is a bit different (though most of the Caddyfile token parsing logic can be brought over to v2). I'll write a How-To for that when v2 RC1 gets closer.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddyserver/caddy] Missing red..." ]
>Caddy 2's architecture is different. Depending on the plugin, it might be pretty simple to adapt it. For example, HTTP handlers can probably keep most of their core logic the same. But a few things have changed: how plugins are registered, the fact that plugins don't need to do their own request matching anymore, and the caddyfile integration is a bit different (though most of the Caddyfile token parsing logic can be brought over to v2). I'll write a How-To for that when v2 RC1 gets closer.

Ok, that's fine, but I can't make time to do this right now.

Thanks for the info!
