### ISSUE TITLE
plugins: don't replace a HTTP response code 204 with 200

### ISSUE THREAD

**Issue by wmark** [caddyserver/caddy#2202]
With Caddy 0.11.0 (and `HEAD`) I've noticed using my plugin http.upload that something inside `caddy` changes my response **code 204** with no content (`StatusNoContent`).

Instead, the response code served **becomes 200** (`StatusOk`). Which is wrong, because the response does not contain a body or anything describing the response itself.

Proof, with *HTTP method* `DELETE`:
* [step 1 within the plugin](https://github.com/wmark/caddy.upload/blob/df37404c760d4f206beddffc7b58b9a5ff2391db/upload.go#L136)
* [step 2 and final step wwithin the plugin](https://github.com/wmark/caddy.upload/blob/df37404c760d4f206beddffc7b58b9a5ff2391db/upload.go#L324-L340) (yes, the comment is wrong; I'll fix that)
* [tests pass](https://github.com/wmark/caddy.upload/blob/df37404c760d4f206beddffc7b58b9a5ff2391db/upload_test.go#L574-L578) — test of the *happy path*

Steps from my README (Github won't allow to link to lines within a *Markdown* file; see below) show the infringing response:
```bash
$ curl -vX DELETE http://localhost:8000/web/path/to-release

* Connected to localhost (::1) port 8000 (#0)
> DELETE /web/path/to-release HTTP/1.1
> Host: localhost:8000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Caddy
< Content-Length: 0
< 
```

You can reproduce this like this (with *http.upload* being the only external plugin):
```bash
cat <<EOF >/tmp/Caddyfile
*:8000
upload / {
  to "/tmp"
}
EOF

TARGET="http://localhost:8000/web/path/to-release"
curl -T /etc/os-release "${TARGET}"
curl -vX DELETE "${TARGET}" |& grep -F "HTTP/"
```

I suggest adding a test with a mock plugin that serves a 204 as first step when addressing this.

**Comment by francislavoie** [comment]
Is it possible that this is related to https://github.com/mholt/caddy/issues/2168?

**Comment by francislavoie** [comment]
@wmark do you think you could help with PR #2252 to write the test as you suggested?

**Comment by mholt** [comment]
I'm 99.9% sure this isn't a problem in v2, so -- fixed. Probably :) Feel free to try it out!
