### ISSUE TITLE
FastCGI programs get incorrect values of environment variables when ran under Caddy

### ISSUE THREAD

**Issue by CMB** [caddyserver/caddy#2212]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.11.0 (+e263566) (unofficial)

### 2. What are you trying to do?

Run a FastCGI application under Caddy.

### 3. What is your entire Caddyfile?
```text
http://localhost:8080 {
root /home/chris/web
fastcgi /fcgi /home/chris/fcgi.sock
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

    caddy -conf /home/chris/Caddyfile

I am running Void Linux.
I ran my FastCGI program under spawn-fcgi.  The executable name is fcgiecho.

    spawn-fcgi -s /home/chris/fcgi.sock -- /home/chris/web/fcgi/fcgiecho

fcgiecho is built from the following source file:
[echo.c](http://the-brannons.com/echo.c).
It is linked against libfcgi.
Actually this is one of the example programs in the libfcgi source distribution;
it is the FastCGI equivalent to printenv.

### 5. Please paste any relevant HTTP request(s) here.

    curl http://localhost:8080/fcgi/fcgiecho/extra/path/info

### 6. What did you expect to see?

    SCRIPT_NAME=/fcgi/fcgiecho
    SCRIPT_FILENAME=/home/chris/web/fcgi/fcgiecho
    PATH_INFO=/extra/path/info

### 7. What did you see instead (give full error messages and/or log)?

    SCRIPT_NAME=/
    SCRIPT_FILENAME=/home/chris/web/fcgi/fcgiecho/extra/path/info
    PATH_INFO=/fcgi/fcgiecho/extra/path/info

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

    Install the package spawn-fcgi.  Install libfcgi (sometimes packaged as
fcgi).  You'll need the associated development package if your operating
system splits out development files.  Compile the fcgiecho program I linked.
Run it under spawn-fcgi as I described.

**Comment by mholt** [comment]
@CMB Thanks for the report; can you see if this is still an issue in Caddy 2? (currently in beta; use the v2 branch and check the wiki for documentation)

**Comment by mholt** [comment]
@CMB Any update? Otherwise, will close this.

**Comment by CMB** [comment]
Sorry, I haven't had a chance to look.  I filed this well over a year ago,
and I've long since forgotten a lot of the context here.

**Comment by mholt** [comment]
Okay. Hmm. I'll see if anyone else has time to look into this before we nix it.

**Comment by mholt** [comment]
Will reopen if it's still an issue in Caddy 2. I think this happens because, by default, the path is split at ".php" but that isn't present in this URI so it just uses `/` for PATH_INFO, maybe could be fixed simply by changing the SplitPath option.
