### ISSUE TITLE
Support for TLS client authentication under the proxy directive.

### ISSUE THREAD

**Issue by luke-park** [caddyserver/caddy#2228]
As far as I am aware, it is currently not possible to provide a TLS client certificate and key while using the proxy directive to authenticate with the upstream server.

The situation I am experiencing requires that a third-party piece of software contact a remote host that is behind Caddy.  This instance of Caddy requires TLS client authentication (intentionally).  I'd like to use *another* instance of Caddy to facilitate the client authentication on behalf of the third-party software that currently doesn't support TLS client auth.

Has this feature been discussed/implemented/dropped?

**Comment by tobya** [comment]
I'm not sure I understand the requirement here.  Perhaps it could be discussed on https://caddy.community/ and if a concrete feature request comes out of it it could be bounced back here.

**Comment by mholt** [comment]
@luke-park This is now implemented in https://github.com/caddyserver/caddy/pull/2737.
