### ISSUE TITLE
Using client certificates and wildcard Letsencrypt is not working

### ISSUE THREAD

**Issue by maciekish** [caddyserver/caddy#2251]
See thread here: https://caddy.community/t/client-certificates-together-with-wildcard-letsencrypt-not-working-with-authentication-ambiguously-configured-error/4205

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 3e0695e 

### 2. What are you trying to do?
Use client certificates together with wildcard letsencrypt.

### 3. What is your entire Caddyfile?
```
(tls) {
  tls {
    dns cloudflare
    wildcard
    clients testca.pem
  }
}

test1.whitestrake.net {
  import tls
}

test2.whitestrake.net {
  import tls
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`/usr/local/bin/caddy -log stdout -agree=true -conf=/mnt/user/appdata/caddy/conf/Caddyfile -root=/var/tmp`

### 6. What did you expect to see?
Caddy should run.

### 7. What did you see instead (give full error messages and/or log)?
Caddy failing with `incompatible TLS configurations for the same SNI name (*.domain.com) on the same listener: multiple hosts requiring client authentication ambiguously configured
`

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Use the above config and generate a ca cert.

**Comment by maciekish** [comment]
Hi, any news on this please? It's really problematic.

**Comment by mholt** [comment]
I've been busy, but pull requests to address this are welcome in the meantime!

**Comment by mholt** [comment]
Upon reviewing this further, I believe this is not a problem in v2's design.
