### ISSUE TITLE
Latency timer should stop early for websocket, text/event-stream connections

### ISSUE THREAD

**Issue by sundbry** [caddyserver/caddy#2268]
As mentioned in issue #593, "latency" should be measured as the time to first response for streaming connections, such as websockets or EventSource connections, and the current behavior should probably be called "duration" instead.

The issue comes up when analyzing access logs; event source and websocket connections show as being abnormally slow to respond.

EventSource connections can be identified with "text/event-stream" as the response content-type.

**Comment by mholt** [comment]
Somehow I never saw this issue until now but you make a good point. Will fix in Caddy 2.

**Comment by mholt** [comment]
@sundbry This is implemented in #4013: `{http.reverse_proxy.upstream.latency}` which tells you the time for the backend to write the headers, and `{http.reverse_proxy.upstream.duration}` gives you total streaming time.
