### ISSUE TITLE
Allow users to provide default values for unset environment variables

### ISSUE THREAD

**Issue by aioobe** [caddyserver/caddy#2313]
Reading up on [Environment Variables](https://caddyserver.com/docs/caddyfile#env) I don't see a way to specify default values for environment variables. This is a common feature in similar types of configuration files. Docker for example supports the standard bash syntax:

> `${variable:-word}` indicates that if variable is set then the result will be that value. If variable is not set then word will be the result.

I would very much like to have a self contained `Caddyfile` with sane defaults so you can safely do `caddy` in prod. (I don't want to say "oh, when you deploy in prod you need to follow instruction A, B and C", I would like it to be "Just run `caddy`".) And then something like `DOMAIN=staging caddy` / `DOMAIN=dev caddy` to override relevant parts in staging and dev.

**Comment by mholt** [comment]
Will look into this for Caddy 2, probably for all placeholder values spawning from the new Replacer type.

**Comment by aioobe** [comment]
Where can I follow the work on Caddy 2? Is there a list of features, breaking changes, estimated release date, etc somewhere?

**Comment by mholt** [comment]
@aioobe It's not public yet, but when we get around to the public beta period, we'll move it into this repo! That's the plan as of now, anyway.

Watch for announcements at OpenGo 2019.

**Comment by mholt** [comment]
Related to / same as #1793

**Comment by francislavoie** [comment]
Actually, derp, they're not really the same. #1793 is for defaults for placeholders in general, whereas this is defaults for environment variables.

I'll reopen this but I'm also submitting a PR for this specific issue now 😛
