### ISSUE TITLE
Feature request: notify out-of-date version

### ISSUE THREAD

**Issue by m13253** [caddyserver/caddy#2321]
### 0. Feature request

Hello Caddy dev,

Although we have discussed (#576) that we currently can't find a suitable method to auto upgrade Caddy, since Caddy now has a telemetry system, can we implement an out-of-date notification (so the administrator can upgrade Caddy manually)?

We might need to repeat the notification every X minutes or when every Y lines of logs are print to avoid being ignored.

Thanks.

**Comment by brink668** [comment]
I would like this as well.

**Comment by mholt** [comment]
This is a good idea. The Caddy version _is_ reported in telemetry already. I guess we just need to show it on the stats page for your instance, then you can set up an alert to monitor for that. How does that sound?

(Actually, if you look at the network tab, it should already return the version information in JSON -- it's just not rendered on the page yet. I'm trying to remember from the top of my head so I'm not positive but give it a look.)

**Comment by theel0ja** [comment]
PowerDNS checks updates anonymously via DNS, see: https://doc.powerdns.com/authoritative/security.html#security-polling

**Comment by francislavoie** [comment]
Oooh, that's clever @theel0ja, thanks for pointing that out!

**Comment by francislavoie** [comment]
@mholt is this something you'd be willing to implement?

We could do this as part of our release CI job with a little Go program that uses whatever `libdns` plugin necessary for the `caddyserver.com` domain, it could write a TXT record with the current version number.

**Comment by mholt** [comment]
Mmm, lemme think about it. It's definitely weird...

**Comment by francislavoie** [comment]
I think this is unlikely to happen any time soon. I'll close this as stale for now. We might come back to this later.
