### ISSUE TITLE
feature request: encrypted SNI

### ISSUE THREAD

**Issue by Lennie** [caddyserver/caddy#2327]
Not sure if this is the right place, I'm probably early to request this anyway.

If I understand correctly, this needs:
- an extra TLS extension
- the webserver should understand 2 or more 'SNI names' for the same name, the plain text name plus a number of encrypted names.
- generate a new key regularly
- needs a way to tell DNS about what key clients can use

https://tools.ietf.org/html/draft-rescorla-tls-esni-00

Sounds to me like if there are multiple web servers, you'd might want to have a centralized program pushing updates to the servers and DNS.

**Comment by Avamander** [comment]
> Unless you want to dump a base64-encoded "put this into your TXT record now" in the logs, a mechanism for updating DNS entries must be implemented.

Even with that it'd be kind-of okay.

**Comment by tankerkiller125** [comment]
I know this is quite old but in regards to an "export to log option" couldn't we just create a new file located where the caddy file is called "site.tld-esni.txt" or something that people could use. Exactly the same way 99% of Email DMARC and DKIM providers do?

**Comment by mholt** [comment]
It's more and more likely that ESNI will be superceded by ECH: https://blog.cloudflare.com/encrypted-client-hello/

It's been a couple of years and ESNI hasn't seen wide adoption among clients yet. With its likely deprecation looming, I'll close this issue now and wait and see if ECH will become mainstream.

If I'm wrong and ESNI ends up mainstream instead, we can reopen this.

**Comment by Avamander** [comment]
Isn't it just a rename? @mholt
