### ISSUE TITLE
Resources for Caddy BrandKit.

### ISSUE THREAD

**Issue by nitroin** [caddyserver/caddy#2335]
That's not a **issue**.

Consider adding an SVG icon in the [BrandKit](https://caddyserver.com/brand).

That will be useful for extensions like:
- https://github.com/vscode-icons/vscode-icons/pull/1769
- https://marketplace.visualstudio.com/items?itemName=zamerick.vscode-caddyfile-syntax

Thanks ♥️!

**Comment by mholt** [comment]
Did you try clicking any of the SVG links?

**Comment by nitroin** [comment]
Sorry, did not clarify enough.

Was looking for something similar:

 ![logo](https://caddyserver.com/resources/images/favicon.png)
