### ISSUE TITLE
Add events for On Demand Certificates

### ISSUE THREAD

**Issue by oliverdunk** [caddyserver/caddy#2344]
In my blog post [here](https://oliverdunk.com/2018/07/06/https-custom-domains-sass), I explain how I added two new events to Caddy:

- `OnDemandCertObtainedEvent`
- `OnDemandCertFailureEvent`

I'm opening this issue to ask if this is something that is worth PRing to introduce upstream? It seems like a minor change, and I can't see any downsides, but I wasn't sure if there was a reason for these not existing already.

**Comment by francislavoie** [comment]
Nothing to lose by making a PR. Go for it!

Events are relatively new and it's really dependent on what kind of features plugin authors would like to implement.

**Comment by mholt** [comment]
Implemented in #4984
