### ISSUE TITLE
Improve releases for linux

### ISSUE THREAD

**Issue by TomHetmer** [caddyserver/caddy#2370]
Hi, 

right now when you unpack the tgz it goes into .

There's two improvements for that:

1) unpack into a separate folder, ie. caddy_v0.11.1_linux_arm7/
It's better because it doesn't mess up my /home folder, if I decide to unpack there.

2) Fix the permissions.
-rw-r--r-- 1  501 staff  23K Nov 13 19:51 CHANGES.txt

501 is not cool, root:root would be better.

**Comment by francislavoie** [comment]
Our current releases via GoReleaser fix `2`, but not `1`. 

See https://github.com/caddyserver/caddy/releases for current releases

```
$ tar -xvf caddy_2.0.0-rc.3_linux_amd64.tar.gz
LICENSE
README.md
caddy

$ ls -la
total 45108
drwxr-xr-x  2 francis francis     4096 Apr 20 04:25 .
drwxr-xr-x 13 francis francis     4096 Apr 20 04:25 ..
-rw-r--r--  1 francis francis    11358 Apr 13 14:56 LICENSE
-rw-r--r--  1 francis francis     8068 Apr 13 14:56 README.md
-rwxr-xr-x  1 francis francis 34177024 Apr 13 15:00 caddy
-rw-r--r--  1 francis francis 11984297 Apr 20 04:24 caddy_2.0.0-rc.3_linux_amd64.tar.gz
```

To solve `1`, I recommend just using the `-C` option of `tar`, e.g.

```
$ mkdir caddy-2.0.0-rc.3
$ tar -xvf caddy_2.0.0-rc.3_linux_amd64.tar.gz -C caddy-2.0.0-rc.3
```
