### ISSUE TITLE
Proxy support for rewriting cookie path

### ISSUE THREAD

**Issue by jalaziz** [caddyserver/caddy#2381]
When implementing a Caddyfile for Artifactory, I noticed the need to rewrite the path of a Cookie in an HTTP response.

Apache supports this via the [`ProxyPassReverseCookiePath`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreversecookiepath) directive and nginx via [`proxy_cookie_path`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path).

In Artifactory's case, we want to host it at the root of the hostname. However, Artifactory assumes it's hosted under `/artifactory`. Even when configuring a different custom base URL, it still sets cookies with the `/artifactory` path.

While I realize that this is something Artifactory could fix themselves, I think it could still be useful for Caddy to support similar functionality to Apache and nginx.

**Comment by francislavoie** [comment]
@jalaziz I think https://github.com/mholt/caddy/pull/2144 will solve this for you once it's merged. It's currently in a bit of a limbo stage though.

**Comment by mholt** [comment]
Rewriting headers using a regex is supported in Caddy 2 (see the v2 branch). Will close this, but feel free to reopen it if it does not meet your needs.

**Comment by joanbm** [comment]
I don't know if I'm not using the right keywords to search for it, but I couldn't find any example for the usual case of rewriting the cookie path of the Set-Cookie header when reverse-proxying to a subpath.

Here's a full Caddyfile example, tested with Caddy 2.4.3:

```
example.com {
  reverse_proxy mainapplication:80

  handle_path /subapplication/* {
    reverse_proxy subapplication:80 {
      header_down Set-Cookie "path=/" "path=/subapplication/"
    }
  }
}
```

**Comment by francislavoie** [comment]
@joanbm please read this article https://caddy.community/t/the-subfolder-problem-or-why-cant-i-reverse-proxy-my-app-into-a-subfolder/. I have to recommend that you use a subdomain instead for this. Much simpler.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
