### ISSUE TITLE
max_conns with fastcgi

### ISSUE THREAD

**Issue by sheychen290** [caddyserver/caddy#2411]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1

### 2. What are you trying to do?
With nextcloud (php-fpm) on nginx, file uploads (= fastcgi connections) where limited to 3.
On caddy, fastcgi isn't limited but (my) php-fpm only have 5 workers.
So when i upload ~10 big files, everthing goes bad.
I think php-fpm upload cache overflow then workers can't do anything.

### 3. What is your entire Caddyfile?
Something like
```text
fastcgi / fpm:9000
```

### 6. What did you expect to see?
```text
fastcgi / fpm:9000 {
  max_conns 5
}
```
Then return 502 to others

**Comment by tobya** [comment]
Thank you for the issue.  IF someone would like to discuss a PR that would be appreciated.

**Comment by mholt** [comment]
Oh, this is done in Caddy 2, because fastcgi is part of the reverse proxy. Please try the v2 branch!
