### ISSUE TITLE
Add placeholder to indicate where the certs are stored for the `on certrenew` directive

### ISSUE THREAD

**Issue by CosmicToast** [caddyserver/caddy#2421]
### 1. What version of Caddy are you using (`caddy -version`)?
`Caddy 0.11.1 (unofficial)`

### 2. What are you trying to do?
It's a common use-case to reuse http SSL certs for non-http services (a simple example is ZNC's web interface and irc).
This requires either having a cron entry that would hardcode the current certificate location and then copy/concatenate them, or an `on` directive that would... still hardcode the current certificate location.

### 3. What is your entire Caddyfile?
```text
my.web.site
on certrenew cat /var/lib/caddy/.caddy/acme/acme-v02.api.letsencrypt.org/sites/my.web.site/my.web.site.key /var/lib/caddy/.caddy/acme/acme-v02.api.letsencrypt.org/sites/my.web.site/my.web.site.crt > /var/lib/znc/znc.pem
```
(note: I do not currently have this, since it's a pain to modify in case of, and am currently using a similarly hardcoded script in cron, as mentioned in 2).

### 4. What should the Caddyfile look like?
```text
my.web.site
on certrenew cat {tlskey} {tlscrt} > /var/lib/znc/znc.pem
```

This would avoid issues where acme gets updated (e.g we already had v02 come out, which would require a rewrite of all formats mentioned in 2), as well as greatly simplify the configuration.

### 5. Additional notes
It seems like the groundwork for this already exists (i.e #1499 is a whole 2-line diff).
If this is to be implemented, I see the bulk of the work being in adding placeholder support to `on` at all.

**Comment by francislavoie** [comment]
I think this might be tricky due to how Caddy handles certificates. I'm not sure it would always be immediately obvious which singular cert/key pair to use as a replacement for the placeholder because there could be more than one valid cert, e.g. if the site label has a wildcard and has certs on demand.

Maybe the best way to implement it would be as an argument to the certrenew event (@elcore thoughts?) which could be used in replacement rather than as a placeholder proper (because those are basically global).

**Comment by elcore** [comment]
I don't have any specific thoughts on that, a placeholder could be used for many different use cases, while an argument would be specific to `on certevent` (and maybe out of scope).

**Comment by tobya** [comment]
I want to clarify what is being requested here.  Please let me know if I'm correct or not

- Add a {cert_location} placeholder which would contain the on disk location of the server certs
- Allow this to be used  in on certrenew

This would allow the following

on certrenew c:\caddy\scripts\CertRenewScript.bat {host} {cert_location} renew

You could then do whatever you like in the script to copy certs etc. Is this correct?

**Comment by 5paceToast** [comment]
@tobya this is roughly correct, but there needs to be some deterministic way to select specifically the `.key` and specifically the `.cert` (and so on).
If you simply pass the directory they're in, the script will still be guessing as to the internal structure, and thus not meet the goal of being version-independent (besides >= release with that feature).

**Comment by tobya** [comment]
We’ll presumably the directory  will contain files with a .key and .cert extension

You can do what you like with them. 

Anything further I think. Is out of scope of a webserver.

**Comment by nrosier** [comment]
I've got some scripts that handle renewals from certbot through the deploy- and post-hook options. The provide the certificate path and the domains that were renewed through environment variables. Very handy to update TLSA records in my DNS-server and restart mail-server.

**Comment by francislavoie** [comment]
Caddy v1 is no longer actively maintained, and Caddy v2 didn't inherit the `on` directive, so I'll close this.
