### ISSUE TITLE
Upgrade QUIC to HTTP/3

### ISSUE THREAD

**Issue by rugk** [caddyserver/caddy#2450]
You know, HTTP/3 is the new name for QUIC, also (previously?) called "HTTP over QUIC" as it seems.

AFAIK it is not yet standardized and no one supports it yet, (seems there are still some technical differences to QUIC, see test site below) but it may soon… :smile: 
And Caddy can be one of the first to support it. :smiley: 

There is even already a test site:
https://http3.info/

**Comment by elcore** [comment]
According to the test site, Caddy does support HTTP/3 (HTTP over QUIC)

**Comment by rugk** [comment]
Really? I've actually tried https://caddyserver.com/ to be sure that it fails and the test failed…

**Comment by mholt** [comment]
QUIC is an experimental feature, and we don't use it on the Caddy site. You'll have to test it on a Caddy server instance that has QUIC enabled.

And I'm pretty sure ours is not the IETF-standard QUIC.

**Comment by elcore** [comment]
> And I'm pretty sure ours is not the IETF-standard QUIC.

That might be the case, Lucas Clemente apparently is working on it (https://github.com/lucas-clemente/quic-go/issues/1241)

**Comment by rugk** [comment]
BTW https://github.com/lucas-clemente/quic-go/issues/1241 has been fixed.

**Comment by marten-seemann** [comment]
As long as there's no browser support, it doesn't make sense to have server support.
I'll send a PR once it actually makes sense to support HTTP/3.

**Comment by mholt** [comment]
Hm, darn:
<img width="1071" alt="Screen Shot 2019-11-06 at 12 31 02 AM" src="https://user-images.githubusercontent.com/1128849/68277629-d2989f00-002c-11ea-9b14-01632c221fd7.png">

This site works though: https://www.http3check.net/
