### ISSUE TITLE
Ideas for log output clarity

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#2458]
This came out of a discussion with @whitestrake about some common confusion by many new users of Caddy as to some configuration defaults, or the way the Caddyfile was interpreted. If the user hasn't read enough of the documentation, they likely would have missed some important information.

---

Here's some possible use cases. Some might seem like a stretch, but similar situations have come up on the forums:

- User starts up Caddy with no config. User sees the following in the log output. User raises an eyebrow, unsure why port 2015 was chosen.
    ```
    http://localhost:2015
    ```
- User starts up Caddy with domain configured (which triggers Automatic HTTPS), having read that the default port is 2015. User sees the following in the log output and assumes that this means that port 2015 is used for HTTP. In this case, `http://` implies port 80 unless otherwise specified with a port suffix like `:2015`.
    ```
    https://example.com
    http://example.com
    ```

There's some ambiguity when it comes to the output currently, entirely dependent on the user's level of experience with networking and how much (or little) they read the documentation. Users may be coming in with partial information.

To help resolve these issues, to help new users along, I suggest that Caddy is more verbose about the port mapping. From our discussion, @whitestrake came up with a pretty good idea for output of the sites being served. To disambiguate the ports used, the sites served could be grouped by listener (i.e. scheme + port), maybe also mentioning that 2015 was used as a default:

```
Serving HTTP on port 80:
http://example.com
http://foo.example.com

Serving HTTP on port 2015 (default):
http://bar.example.com:2015

Serving HTTPS on port 443:
https://example.com
https://foo.example.com
```

Potential consideration to be had here: are people using these lines for scripting? Or do we care about supporting that? Also, an implementer's note: the default ports can be changed with the `-http-port` and `-https-port` flags, so that may come into play for this change.

---

Another related issue I foresee is with this message in the output: `Activating privacy features... done.` Users might not know what "privacy features" means. The documentation uses the term "Automatic HTTPS" for this feature. There's a bunch of preconditions that need to be met for this to be enabled, which isn't inherently transparent. This isn't the easiest thing to solve, because the feature is technically per-site, not global. The message really means "for every site that passes the preconditions, attempting to activate HTTPS", i.e. Let's Encrypt cert issuance and using port 80/443 by default instead.

I'm not sure what the best option is here to make it clearer without making it too verbose. I think it would be helpful to also mention what conditions were not met. The problem with that though is that if it was intentional for the user to not want it enabled, i.e. for local development or whatever, then it would be too verbose. It's a tricky balance.

Currently, there's no `-v/vv/vvv` flags (commonly used for logging verbosity), so this extra information about Automatic HTTPS (and/or other things) could be added when verbose mode is enabled. On the other hand, there is already the `-quiet` option, which users could use if they think it's too verbose.

**Comment by tobya** [comment]
I am all on for additional logging particularly for things that routinely cause confusion.

**Comment by whitestrake** [comment]
Just gonna add my voice to this too, I'd like to see both implemented.

I think grouping site outputs by listener will definitely help human readability and understanding, especially in less experienced Caddy users.

I like the idea of disambiguating "Activating privacy features", especially in cases where there's no privacy features to activate (i.e. not hosting any HTTPS sites).

Perhaps while we're looking at this, we could also have Caddy not double up on site list output when `-log stdout` is set. You might consider it a corner case - Caddy _always_ outputs the startup to stdout, and _optionally_ logs to a specified output - but for those of us who capture `stdout` for logging anyway (e.g. Docker, systemd output redirection), it'd be nice and neat to have a bit of logic detect that and maybe suppress the regular output in favour of the `-log stdout` output.

**Comment by francislavoie** [comment]
@mholt just FYI the "Activating privacy features" bit wasn't addressed in that PR.

**Comment by mholt** [comment]
Good point

**Comment by mholt** [comment]
Caddy 2's output is different now, so closing this.
