### ISSUE TITLE
Make using LetEncrypt Staging Environment easier

### ISSUE THREAD

**Issue by tobya** [caddyserver/caddy#2460]
This has been discussed before but I would like to suggest it again and have a PR ready to go if it is approved.

I think using the [LetEncrypt staging environment](https://letsencrypt.org/docs/staging-environment/) when testing a configuration is more complicated than it needs to be.  

You may say how could it be too complicated, all you need to do is provide the url to the staging server in your command line.  This is true, but in order to do that you need to.

1. Remember that you should use the staging server when testing a new configuration 
1. Try to remember where you saw the url on the caddyserver.com website
1. Realise you need to follow the link to the LetsEncrypt website.
1. Figure out if you need to use the V1 or V2 staging endpoint.
1. Copy it and paste it onto your command line options for caddy

I would like to propose the following 

    caddy -ca Sandbox

This will use the correct Staging url for the version of acme that Caddy is using.  It simplifies the process and will reduce the number of new users who bash up against the rate limits when only testing out their site, which leads to frustration.

I would like to have this included before 1.0 but if there are some reasons why this is not a good idea perhaps we can discuss here.  I think this will add to ease of use.

The docs could then be updated to provide a much more direct recommendation that `-ca Sandbox` should be used when testing.

ps.
--

Of course `Sandbox` could be replace with any of  
 - dev
 - Staging
 - debug
 - dryrun
 
etc.

**Comment by mholt** [comment]
But what about other ACME CAs? I don't think it's right to assume that a user is using Let's Encrypt. There are plenty of privately-hosted ACME servers and even other commercial CAs are starting to implement ACME too.

**Comment by francislavoie** [comment]
How about something like `-ca LESandbox` for example? Prefix it with `LE` to try and indicate it's Let's Encrypt's endpoint. Caddy (well, certmagic I guess) already defaults to LE, so I don't think it's too crazy to just define some presets for ease of use. Plus if LE releases a V3, Caddy can just change what the preset points to and everyone's happy, no need to do manual work of fixing their `-ca` flag on their tests (admittedly that's an edgecase, but still)

**Comment by francislavoie** [comment]
Maybe this should actually be an issue for the certmagic repo? Does `-ca` just get passed through?

**Comment by tobya** [comment]
Well lets see: we have the main live LetsEncrypt environment literally hard coded into the source.  I think it is safe to assume (and we do) that the substantial majority of the users of caddy are using LetsEncrypt to issue their certs and therefore would be interested in using LetsEncrypt staging environment for testing.  

We are not taking any decision away from users.  This is like us providing a `php` or `transparent` shortcut which we do in `fastcgi` and `proxy` to aid ease of use.  This is the same concept but for the `-ca` command line param.  

I'm sure LetsEncrypt would be happy if we used this shortcut, potentially cutting down on the number of users they get hitting rate limits on live servers.

**Comment by tobya** [comment]
> Maybe this should actually be an issue for the certmagic repo? Does `-ca` just get passed through?

I think it makes more sense for this to be a preset in caddy than in CertMagic

**Comment by francislavoie** [comment]
> I think it makes more sense for this to be a preset in caddy than in CertMagic

That's fine, but I was just thinking, where is the live LE env configured? I think it's in CertMagic... so I think it would make the most sense to have both the live and staging envs in the same repo, rather than having them split up, the live in CertMagic and the staging in Caddy.

**Comment by tobya** [comment]
CertMagic defines a constant in its code to the staging environment.  I use this in my Caddy PR.

**Comment by mholt** [comment]
If we did make a change, the right place would be in Caddy. CertMagic does not set any CLI flags.

You both make good points about Let's Encrypt already being the default CA in Caddy, however: I'm not convinced that it will solve the problem of people accidentally hitting rate limits. They'd still need to enable the staging endpoint one way or another. All this proposal does is shorten the length of the flag value, but I think a better solution may simply to be to improve documentation.

**Comment by tobya** [comment]
I'm going to open this again as again I found myself just wanting to specify 

> caddy -ca sandbox 

without haveing to go look up the website and find the url.  

We can close again but I still dont get why this is not able to be implemented.

**Comment by mholt** [comment]
I think, with recent improvements in Caddy, CertMagic, and the upcoming v2 release, this will be a non-issue. :)
