### ISSUE TITLE
caddy silently fails with multiple vhosts, no errors when starting from command line.

### ISSUE THREAD

**Issue by jhdulaney** [caddyserver/caddy#2462]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1

### 2. What are you trying to do?
Use multiple virtual hosts.

### 3. What is your entire Caddyfile?
```
bestpuppers.com {
    errors /var/log/caddy/bestpuppers.com.error.log {
        rotate_size 2
        rotate_age 10
        rotate_keep 5
        rotate_compress
    }

    gzip {
        level 7
        min_length 2000
    }
    header / {
        X-Frame-Options "DENY"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
        X-UA-Compatible "IE=Edge"
        vary "Accept-Encoding"
    }
    log / /var/log/caddy/bestpuppers.com.access.log "{combined} l{latency_ms} {mitm}"  {
        rotate_size 2
        rotate_age 10
        rotate_keep 5
        rotate_compress
    }
    mime {
        .swf application/x-shockwave-flash
        .pdf application/pdf
    }
    proxy / static-bestpuppers.com:80
}
seattlebus.space {
    errors /var/log/caddy/seattlebus.space.error.log {
        rotate_size 2
        rotate_age 10
        rotate_keep 5
        rotate_compress
    }

    gzip {
        level 7
        min_length 2000
    }
    header / {
        X-Frame-Options "DENY"
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
        X-UA-Compatible "IE=Edge"
        vary "Accept-Encoding"
    }
    log / /var/log/caddy/seattlebus.space.access.log "{combined} l{latency_ms} {mitm}"  {
        rotate_size 2
        rotate_age 10
        rotate_keep 5
        rotate_compress
    }
    mime {
        .swf application/x-shockwave-flash
        .pdf application/pdf
    }
    proxy / static-seattlebus.space:80
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/bin/caddy -agree -conf /etc/caddy/caddy.conf -quic -email jdulaney@fedoraproject.org

### 5. Please paste any relevant HTTP request(s) here.
curl seattlebus.space

### 6. What did you expect to see?
html

### 7. What did you see instead (give full error messages and/or log)?
curl: (7) Failed to connect to seattlebus.space port 80: Connection refused

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
By running with a single vhost configured, caddy works.  It does not matter which one I go with.  Add the second vhost, and caddy fails.

This precise config worked well for many months without incident.

**Comment by mholt** [comment]
If you add `-log stderr` (or a filename) to the command, what is the output then?

**Comment by jhdulaney** [comment]
Activating privacy features... 2019/02/11 17:34:22 [WARNING] Stapling OCSP: invalid: OCSP response for [example.com] valid after certificate expiration (-168h23m43s)                                       
2019/02/11 17:34:22 [INFO] Certificate for [example.com] expires in -1329h58m5.390940924s; attempting renewal                                                                                               
2019/02/11 17:34:22 [INFO] Certificate for example.com is already being renewed elsewhere and stored; waiting

**Comment by francislavoie** [comment]
Looks like a lock file that hasn't been cleared out for clustering purposes. This is a relatively new feature, see https://caddyserver.com/docs/automatic-https#fleet

I'm not sure why it might not have been cleared out. Maybe Caddy died in the middle of doing a renewal at some point in the past? Regardless, you could look in your `$HOME/.caddy` dir, you might find a `.lock` file in there. If you shut down all your Caddy instances and that file is still there, it should be safe to delete, and should get rid of that `is already being renewed elsewhere and stored; waiting` message next time you start up Caddy.

**Comment by mholt** [comment]
Looks like a stale lock -- probably caused by some interruption like a process exit or crash during the obtaining operation. It will expire soon enough, or you can delete it manually as suggested.

**Comment by tobya** [comment]
Would a -clear-lock cli option be worth considering for this if it happens occasionally?

Perhaps a note.

> if problem persists clear cert cache by running caddy -clear-locks

**Comment by mholt** [comment]
Maybe, but removing locks could lead to races -- let's see if this pops up more often. If so, I'd rather fix the root cause.

**Comment by miguemely** [comment]
I too also have this issue. Version 0.11.1 running off of Docker. I'll see if I can force a new build to use the latest version.

**Comment by mholt** [comment]
@miguemely Probably because lock files expire after a few hours.

Caddy 2 handles this a little better, but there's still little/nothing it can do if it's forcefully terminated during ACME operation.
