### ISSUE TITLE
http.log path not effective

### ISSUE THREAD

**Issue by zhuohan** [caddyserver/caddy#2475]
## 1. Which version of Caddy are you using (`caddy -version`)?

0.11.4

## 2. What are you trying to do?

use http.log to log requests with a certain path
e.g: https://xxx.com/css

## 3. What is your Caddyfile?
```text
xxx.com {
    tls xxx@xxx.com
    root /var/www/html
    gzip
    timeouts none
    log / /var/log/caddy/access.log "{combined}"
    log /css /var/log/caddy/css.log "{combined}"
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

use hook.service to run caddy as a system service

## 5. Please paste any relevant HTTP request(s) here.

https://xxx.com/css/plugins.css

## 6. What did you expect to see?

both access.log and css.log contain logs to show this request

## 7. What did you see instead (give full error messages and/or log)?

only access.log logs this request

## 8. Why is this a bug, and how do you think this should be fixed?

based on documentation, path should be meaningful param.

## 9. What are you doing to work around the problem in the meantime?

work around: use multiple "except" to filter all other requests expect css

## 10. Please link to any related issues, pull requests, and/or discussion.

Question: if I wanna log requests that are only to my root path (path "/" is for all paths, not for root path), is there a way to do that? If not, will this become a new feature?

## Bonus: What do you use Caddy for? Why did you choose Caddy?

personal website, reverse proxy server.

**Comment by tobya** [comment]
Thanks for the issue.

**Comment by mholt** [comment]
Hmm, maybe we are only logging on the first matching path? Shouldn't be too hard to fix, if so.

**Comment by zhuohan** [comment]
> Hmm, maybe we are only logging on the first matching path? Shouldn't be too hard to fix, if so.

removing the first logging rule, still I cannot see anything in css.log

**Comment by mholt** [comment]
Caddy 2 does logging a little differently, so this is not an issue in v2 (or is solved differently).
