### ISSUE TITLE
can't get index.html if use php fastcgi and index.php exist, it always get index.php

### ISSUE THREAD

**Issue by shynome** [caddyserver/caddy#2493]
## 1. Which version of Caddy are you using (`caddy -version`)?
`0.11.4`

## 2. What are you trying to do?

get `index.html` when  use php fastcgi  and `index.php` exist

`index.html`
```html
index.html
```
`index.php`
```php
<?="index.php"?>
```

## 3. What is your Caddyfile?
```text
http://:8080 {

  root D:/www/test/
  index index.html index.php index.htm

  fastcgi / 127.0.0.1:9072 php

}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy.exe --log stdout`

## 5. Please paste any relevant HTTP request(s) here.
```sh
curl http://127.0.0.1:8080/
-> index.php
-------------
curl http://127.0.0.1:8080/index.html
-> <a href="/">Moved Permanently</a>.
------------
curl http://127.0.0.1:8080/index.html -L
-> index.php
```

## 6. What did you expect to see?

```sh
curl http://127.0.0.1:8080/
-> index.html
```

## 8. Why is this a bug, and how do you think this should be fixed?

it should give me `index.html` content , not `index.php` content

## 9. What are you doing to work around the problem in the meantime?

I can't resolve the problem.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

auto ssl

**Comment by mholt** [comment]
This is likely fixed in v2, depending on the config being used. Please try out v2 and see how it goes!
