### ISSUE TITLE
Undocumented: default keepalive number in http.proxy

### ISSUE THREAD

**Issue by imba-tjd** [caddyserver/caddy#2503]
https://caddyserver.com/docs/proxy

> keepalive is the maximum number of idle connections to keep open to the backend. Enabled by default; set to 0 to disable keepalives. Set to a higher value on busy servers that are properly tuned.

It only says "Enabled by default", but not tells us the default number.

**Comment by mholt** [comment]
I think our default was the same as Go's, and in case it changed I didn't want to document it in our documentation too and have it be out-of-date.
