### ISSUE TITLE
Add read/write timeouts for proxy module

### ISSUE THREAD

**Issue by akawhy** [caddyserver/caddy#2514]
## 1. What would you like to have changed?

Add read/write timeouts for proxy module. At this time, `time` directive in proxy module just set the connection timeout.   

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

The backend server maybe buggy or broken.  

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

undef

## 4. Please link to any relevant issues, pull requests, or other discussions.

undef

**Comment by mholt** [comment]
Done in v2: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersreverse_proxy
