### ISSUE TITLE
Hang when POST request using http2

### ISSUE THREAD

**Issue by taoxinyi** [caddyserver/caddy#2535]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy 0.11.5

## 2. What are you trying to do?

I have  2 subdomains, `api.xxx.com` and `h.xxx.com`, they are on different servers. The web is `h.xxx.com`, which will post to `api.xxx.com` to get data. However, if http2 is enabled on `api.xxx.com`, the request will hang forever.
 
For example, I open `h.xxx.com` in my browser, it send POST request to `api.xxx.com/add` and will hang forever. 
If I use http1.1 on `api.xxx.com`, it works perfectly and no problem at all.

## 3. What is your Caddyfile?
Caddyfile·of `api.xxx.com`
```text
api.xxx.com {
	proxy /add localhost:9094 
	errors /var/www/err
	log /var/www/log
}
```
Caddyfile·of `h.xxx.com`
```text
h.xxx.com {
    root /var/www
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy in linux terminal

## 6. What did you expect to see?

No hang when post to `api.xxx.com/add` when using http2

## 7. What did you see instead (give full error messages and/or log)?

![hang1](https://user-images.githubusercontent.com/22277258/54747924-29bb4200-4c0b-11e9-81a8-d11098c860c0.png)
![hang2](https://user-images.githubusercontent.com/22277258/54747927-2d4ec900-4c0b-11e9-9f9b-049f7ac17396.png)
hang when post to `api.xxx.com/add` when using http2

## 9. What are you doing to work around the problem in the meantime?

Using http1.1

**Comment by tobya** [comment]
Are you using PHP or another server backend?  Could you post your full unedited caddyfile or a verison of it you know is causing the same issue.

I have found a similar issue using a PHP backend where 2 hosts share the same php fastcgi endpoint.

**Comment by taoxinyi** [comment]
@tobya This is my full caddyfile. The 9094 port of server of `api.xxx.com` runs an ipfs cluster rest api, I believe the its backend is go.

**Comment by tankerkiller125** [comment]
@taoxinyi It seems that this may be something with the application serving HTTP2. I've been able to test caddy with Gitlab, Gitea, Matmo, Wordpress, Sentry and lots of custom API's written in PHP, Ruby, Go, and NodeJS some of which are very post heavy without issues from Caddy. I would recommend contacting the IPFS team about a possible fix as it seems that they aren't handling the HTTP2 connection properly.
