### ISSUE TITLE
Log flooded by "Superfluous response.WriteHeader call" entries

### ISSUE THREAD

**Issue by fr33tux** [caddyserver/caddy#2537]
Hello,

## 1. Which version of Caddy are you using (`caddy -version`)?
`Caddy 0.11.5 (unofficial)`

## 2. What are you trying to do?
Use Caddy as usual.

## 3. What is your Caddyfile?

It consists of 10 snippets exactly like this one, with a different php pool and root path for each:

```text
http://website.net:8080 {

        log /var/log/caddy/access.log
        errors /var/log/caddy/errors.log

        root /mnt/data/www/prod/public

        index index.php
        rewrite / {
                regexp .*
                to {path} {path}/ /index.php
        }

        fastcgi / unix:/run/php/php7.2-fpm.sock php
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

Using Systemd with the following unit file:
```
[Unit]
Description=Caddy HTTP/2 webserver
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
;Restart=on-failure
;StartLimitInterval=86400
;StartLimitBurst=5

User=www-data
Group=www-data

Environment=CADDYPATH=/etc/ssl/caddy

ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
ExecReload=/bin/kill -USR1 $MAINPID

KillMode=mixed
KillSignal=SIGQUIT
TimeoutStopSec=5s

LimitNOFILE=8192
;LimitNPROC=4

PrivateTmp=true
PrivateDevices=true
ProtectHome=true
ProtectSystem=full
ReadWriteDirectories=/etc/ssl/caddy

CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

## 7. What did you see instead (give full error messages and/or log)?
I'm seeing a lot of those lines in my logfile:

```
mars 27 10:37:51 caddy-01 caddy[15640]: 2019/03/27 10:37:51 http: superfluous response.WriteHeader call from github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseRecorder).WriteHeader (recorder.go:61)
mars 27 10:37:57 caddy-01 caddy[15640]: 2019/03/27 10:37:57 http: superfluous response.WriteHeader call from github.com/mholt/caddy/caddyhttp/httpserver.(*ResponseRecorder).WriteHeader (recorder.go:61)
```

## 8. Why is this a bug, and how do you think this should be fixed?
I don't use any header specific directives and my Caddy file is pretty simple and shouldn't throw those errors.

## 9. What are you doing to work around the problem in the meantime?
Nothing.

**Comment by ferdypruis** [comment]
This happens when you `WriteHeader` after a `Write`, which already flushes the headers.

I see this being done at https://github.com/mholt/caddy/blob/8f7a1d6a2561bb45489430236a27b5dcb655e00c/caddyhttp/errors/errors.go#L58

**Comment by lin4you** [comment]
I have the same problem. I'm downloading files from S3 using the PHP library maennchen/ZipStream-PHP. The request always aborts after 60 seconds. As a workaround Im using nginx on my local system to download the zip. Is there a better workaround than using a different web server?

**Comment by mholt** [comment]
Could you please confirm whether you experience this issue with Caddy 2? (Currently in beta on the v2 branch, there are releases available as well.) I would be surprised if you did, because of how we've redesigned the whole application.

**Comment by mholt** [comment]
This should be fixed in v2, please give it a shot -- builds are available on our releases page.

**Comment by lin4you** [comment]
I have now tried version 2 rc1 and the bug is fixed for me.

**Comment by mholt** [comment]
That's great! Thank you for confirming.
