### ISSUE TITLE
Default cipher suite list in docs needs to be updated

### ISSUE THREAD

**Issue by virtualdxs** [caddyserver/caddy#2546]
## 1. Which version of Caddy are you using (`caddy -version`)?
```text
Caddy 0.11.5 (+80dfb8b Wed Mar 27 23:26:46 UTC 2019) (unofficial)
2 files changed, 7 insertions(+), 1 deletion(-)
caddy/caddymain/run.go
caddyhttp/httpserver/replacer.go
```
Patches attached:
[0001-Add-tls_client_provided_cert-placeholder.patch.txt](https://github.com/mholt/caddy/files/3031840/0001-Add-tls_client_provided_cert-placeholder.patch.txt)
[0002-Disable-telemetry.patch.txt](https://github.com/mholt/caddy/files/3031841/0002-Disable-telemetry.patch.txt)

## 2. What are you trying to do?
Receive a REST message from an external partner 

## 3. What is your Caddyfile?
```text
https://staging.goldblattsystems.com {
        tls {
                clients verify_if_given gs-ca.crt partnerabcd-ca.crt
        }
        log /var/log/caddy.log {
                rotate_size 50  # Rotate after 50 MB
                rotate_age  30  # Keep rotated files for 30 days
                rotate_keep 20  # Keep at most 20 log files
        }
        proxy / http://localhost:8080 {
                transparent
                header_upstream X-Tls-Client-Authenticated {tls_client_provided_cert}
                header_upstream X-Tls-Client-Name {tls_client_s_dn}
                header_upstream X-Tls-Issuer-Name {tls_client_i_dn}
        }
}

http://* {
        redir https://{host}{uri}
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
Running under systemd, but replicated without. Command:
`/usr/bin/caddy -conf /etc/caddy/caddy.conf -log stdout -root /tmp -agree`

Environment:
```text
SHELL=/bin/bash
USER=caddy
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
PWD=/var/lib/caddy
CADDYPATH=/var/lib/caddy
LANG=en_US.UTF-8
SHLVL=1
HOME=/var/lib/caddy
LOGNAME=caddy
_=/usr/bin/env
```

## 5. Please paste any relevant HTTP request(s) here.
[Pcap attached](https://github.com/mholt/caddy/files/3031837/caddy.pcap.gz); doesn't even get to the HTTP stage

## 6. What did you expect to see?
TLS gets negotiated

## 7. What did you see instead (give full error messages and/or log)?
```
2019/04/01 12:24:04 http: TLS handshake error from 69.25.46.11:63617: tls: no cipher suite supported by both client and server
```
No other messages were generated upon the request, either on stdout or in caddy.log.

## 8. Why is this a bug, and how do you think this should be fixed?
Because the following ciphersuites were offered:
```text
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009d)
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009c)
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
```
And there is overlap with what Caddy's tls docs says it supports.

I have absolutely no clue where to start with fixing this.

## 9. What are you doing to work around the problem in the meantime?
Using Caddy v0.11.4

## 10. Please link to any related issues, pull requests, and/or discussion.
None I saw

## Bonus: What do you use Caddy for? Why did you choose Caddy?
Reverse proxy and Let's Encrypt client for our application. Chose caddy because its configuration simplicity is mind-blowing.

## Note
I anonymized two things:

1. partnerabcd-ca.crt was changed, but the original is also purely alpha and is the exact same length.
2. The partner IP address in the attached pcap was replaced using 
`tcprewrite -N<ip>/32:12.34.56.78/32 --infile=caddy.pcap.bak --outfile=caddy.pcap`. It follows the exact same pattern of `/(\d{2}\.){3}\d{2}` as the replacement `12.34.56.78`.

**Comment by fanste** [comment]
I think I had a similar problem. In our case (internal company server only) a C# browser module is too old to work caddy's default TLS settings. I've changed my settings to
```
tls X-FullChain.cer X.key {
    protocols tls1.0 tls1.3
    ciphers ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-AES256-CBC-SHA ECDHE-RSA-AES128-CBC-SHA ECDHE-ECDSA-AES256-CBC-SHA ECDHE-ECDSA-AES128-CBC-SHA
}
``` 
and it worked again.

Maybe you can try something similar.

**Comment by virtualdxs** [comment]
@fanste I'll try some permutations of that to see if it fixes anything. The thing is, if the partner upgrades from TLS1.2 to 1.3, we're back at square 1 because the Go devs decided that you shouldn't be able to choose what ciphers you use in TLS1.3.

**Comment by vcsjones** [comment]
According to the source, the default cipher list (assuming you have AES-NI) is this:

https://github.com/mholt/caddy/blob/9d767e768ac0d1d421fc16d4f9895ff7581f3d8b/caddytls/config.go#L486-L493

Your cipher list from section 8 doesn't have any overlap with the default set (though you can enable them). Your default set does not offer RSA+ECDHE+AESGCM.

**Comment by virtualdxs** [comment]
@vcsjones Yep, you're right. Looks like the documentation needs to be updated.
