### ISSUE TITLE
Caddy logs HTTP status 502 when client disconnects before fastcgi is able to serve response

### ISSUE THREAD

**Issue by gunnarbeutner** [caddyserver/caddy#2547]
## 1. Which version of Caddy are you using (`caddy -version`)?

f6e6a6be0446a8455001d6202032b20b64b37569

## 2. What are you trying to do?

I'm trying to serve a PHP application using Caddy's fastcgi module.

## 3. What is your Caddyfile?
```text
http://abyss.local https://abyss.local {
    root /Users/gunnar/shop-test

        fastcgi / 127.0.0.1:9000 php

        push

        gzip {
                level 1
        }

        tls /Users/gunnar/shop-test/certs/abyss.local.pem /Users/gunnar/shop-test/certs/abyss.local.key {
                protocols tls1.0 tls1.3
                ciphers ECDHE-RSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-CBC-SHA ECDHE-RSA-AES256-CBC-SHA
        }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```
/usr/local/bin/caddy -default-sni=abyss.local -agree=true -log=/tmp/caddy.log -conf=/Users/gunnar/shop-test/conf/Caddyfile
```

## 5. Please paste any relevant HTTP request(s) here.

I used the following Python script to reproduce this problem:

```python
#!/usr/bin/env python2
import socket
import ssl

# SET VARIABLES
packet, reply = "GET /test.php HTTP/1.1\nHost: abyss.local\n\n", ""
HOST, PORT = 'abyss.local', 443

# CREATE SOCKET
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(10)

# WRAP SOCKET
wrappedSocket = ssl.wrap_socket(sock)

# CONNECT AND PRINT REPLY
wrappedSocket.connect((HOST, PORT))
wrappedSocket.send(packet)
#print wrappedSocket.recv(128)

# CLOSE SOCKET CONNECTION
wrappedSocket.close()
```

Note that the client disconnects before the fastcgi module has a chance to send the HTTP response.

Here's my test.php script:

```php
<?php
/* We need to sleep long enough to give the client a chance to disconnect. */
sleep(5);
```

## 6. What did you expect to see?

I would have expected Caddy to log the original HTTP status it got from PHP, i.e. 200.

## 7. What did you see instead (give full error messages and/or log)?

Instead Caddy logged HTTP status 502 which confused me because I thought that my PHP application had failed.

## 8. Why is this a bug, and how do you think this should be fixed?

I believe this to be a bug because client connectivity issues should not result in a change of the HTTP response status.

## 9. What are you doing to work around the problem in the meantime?

I'm ignoring the log for now, however it makes diagnosing other problems harder because these errors are indistinguishable from real application errors.

## 10. Please link to any related issues, pull requests, and/or discussion.

None that I could find.

However, upon cursory examination I believe the problem originates from https://github.com/mholt/caddy/blob/master/caddyhttp/fastcgi/fastcgi.go#L179 .

**Comment by mholt** [comment]
This should be fixed in Caddy 2 now.
