### ISSUE TITLE
Adds support for distributed tracing

### ISSUE THREAD

**Issue by jcchavezs** [caddyserver/caddy#2557]
## 1. What would you like to have changed?
Enable support for distributed tracing in Caddy so I can start a trace and propagate it downstream.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
Debugging issues in production requires tools that allows users to understand the many unknown unknowns that a distributed environment comes with. Since caddy is a webserver it is the right place to start a trace. In my opinion it is important to include it in caddy core similarly as go-kit does (https://github.com/go-kit/kit/tree/master/tracing) tho it could also be a plugin.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
None yet but I started this: https://github.com/caddyserver/caddy/pull/2558

**Comment by mholt** [comment]
I think I'll close this, since in the linked PR it seems like it's best to have this as a separate plugin rather than part of the standard distribution.
