### ISSUE TITLE
Docs: Rewrite / matches everything

### ISSUE THREAD

**Issue by AndreKR** [caddyserver/caddy#2585]
This is a documentation bug.

On https://caddyserver.com/docs/rewrite it says:

> Examples
> Rewrite everything to /index.php. **_(rewrite / /index.php will only match /)_**
> ```rewrite .* /index.php```

The part highlighted by me seems to be untrue. `rewrite / /index.php` seems to have exactly the same effect as `rewrite .* /index.php`.

Looking at the code seems to confirm this: the match is unanchored, `regexpMatches()` does not add `^` or `$`.

https://github.com/mholt/caddy/blob/15fecbc16151308959674a5ce3843efb9e66bd5f/caddyhttp/rewrite/rewrite.go#L249-L259

By the way, in the section "Syntax" it also says:

> **from** is _**the exact path to match**_ or a regular expression to match

While technically "exact" does not mean "anchored", sometimes it is (erroneously) used synonymous, which strengthened the misconception to me.

**Comment by whitestrake** [comment]
Some background info: this behaviour was implemented in PR #2082, and discussed since in issue #2219 (discussion died down immediately after the issue was closed).

I kind of like the idea of reverting to exact path matching if it doesn't look like regex and does look like a path, but correcting the docs seems more straightforward in the short term.

**Comment by AndreKR** [comment]
The problem is that "looks like regex" is kind of ill-defined, as a Caddyfile doesn't use any special syntax for regexes so any simple path is also a valid regex.

Following the reasoning from https://github.com/mholt/caddy/issues/2219#issuecomment-403635452 the regex syntax is here to stay and if we want an exact match we should surround it with `^` and `$` and escape special characters.

I think we should remove the "the exact path to match or" so that it just says: "from is a regular expression to match" and adjust the examples so that there is one SimpleRule example for an exact match (with `^` and `$` and an escaped character), maybe one with a prefix match (with just `^`) and one with a regex match.

I would prepare a MR, but I don't think the docs source is public?

**Comment by whitestrake** [comment]
Yeah, making that kind of determination is indeed not simple at all. Just say "it's regex only here" and be done with it so there's no confusion.

And, yeah, the docs repo used to be at https://github.com/caddyserver/website, but the developer is currently handling all the documentation updates themselves.

**Comment by AndreKR** [comment]
@mholt Seems this is yours then.

While you're editing that page, could you please clarify that with the complex syntax the `base path` **is** trimmed from the URL before the `regex` is matched, but it is **not** prepended to the `to` after the rewrite. This was not at all clear to me.

**Comment by mholt** [comment]
@AndreKR Sure, I'm ready to make those changes. It's a little hard to match which changes exactly you'd like from what you've said: any chance you could suggest a diff of the text on the page and I will make it today?

**Comment by AndreKR** [comment]
That was my original intention but I couldn't find the source for that page. Would you like me to save the HTML of the page in the browser and edit that to create a patch?

**Comment by mholt** [comment]
Or just copy + paste the text you want changed, doesn't have to be anything too proper in this case. :)

**Comment by mholt** [comment]
Since v1 is phasing out soon... closing. We've definitely fixed this in v2.
