### ISSUE TITLE
Templating breaks mime type of other files (only with some Caddy builds)

### ISSUE THREAD

**Issue by renaudguerin** [caddyserver/caddy#2602]
## 1. Which version of Caddy are you using (`caddy -version`)?

`Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)`

## 2. What are you trying to do?

Enabling templates for HTML files and serving other files with the appropriate mime type.

## 3. What is your Caddyfile?
```
:2015
templates
mime .json application/json
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -conf Caddyfile-test`
(Through Docker)

## 5. Please paste any relevant HTTP request(s) here.

```
curl -I localhost:2015/config.json
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Server: Caddy
Date: Wed, 08 May 2019 17:50:35 GMT
```

## 6. What did you expect to see?

`Content-Type: application/json`

## 7. What did you see instead (give full error messages and/or log)?

`Content-Type: text/plain; charset=utf-8`

## 8. Why is this a bug, and how do you think this should be fixed?

Enabling `templates` for .html (or just with default settings) breaks the mime types of JSON files in the paths it is enabled for. They're all served as `text/plain; charset=utf-8`

Plot twist : I can't reproduce this with Caddy 1.0.0 on my Mac, I only have this problem with the popular `abiosoft/caddy-docker` Docker image (so, I don't know if it's a Linux specific problem or due to the way it's built)

Repro steps: very simple Caddyfile with 
```
:2015
templates
mime .json application/json
```

- ` curl -I localhost:2015/` (templated index.html) correctly returns  `Content-Type: text/html; charset=utf-8`
- ` curl -I localhost:2015/config.json` (plain JSON file) **wrongly** returns  `Content-Type: text/plain; charset=utf-8`

What I've tried:
- Rebuilding the container without any plugins, to match the vanilla Caddy I'm using on Mac (using `docker build --build-arg plugins="" github.com/abiosoft/caddy-docker.git` and they now both output the exact same version and plugins). **Didn't work.**
- Forcing/not forcing the type with the `mime` directive. **Didn't work.**
- Explicitly setting `templates / .html` and using the long form with `path` / `ext` / `between`. **Didn't work.**
- Restricting `templates` to a subpath like this : `templates /subdir .html`. **This works** : JSON files outside of that path are now served correctly. **But I can't use that** because I need my index templated !

Any help greatly appreciated !

## 9. What are you doing to work around the problem in the meantime?

I don't have a workaround at the moment.

## 10. Please link to any related issues, pull requests, and/or discussion.

I've also opened an issue in the Docker container's repo : https://github.com/abiosoft/caddy-docker/issues/182

**Comment by renaudguerin** [comment]
I finally have a workaround : the only thing that worked was adding `RUN apk --no-cache add mailcap` to the Dockerfile. This was probably the only difference between my Linux/Docker environment and the Mac one.

Again, forcing the type with the `mime` directive was **not** enough in my case ! Maybe this code path is bypassed when `templates` is enabled and it falls back to the default case that relies on a `mailcap` file to determine the type ?

**Comment by mholt** [comment]
Perhaps. Since it's not reproducible with v1.0.0, I'm not sure why... and am not sure if this is a bug in Caddy core or something else.

I don't think this is a problem in Caddy 2 either. If it is, or if we confirm this is a bug in Caddy 1's core/standard directives, we can reopen this. Thanks for the investigating!
