### ISSUE TITLE
QUIC: can only serve 30M/s bandwidth output

### ISSUE THREAD

**Issue by cnkedao** [caddyserver/caddy#2621]
config:
wellcdn.com:4433 {
root /data
tls /data/fullchain.pem /data/privkey.pem
}

testing:
./quicbench -rt quic -c 100 -d 10 -u https://wellcdn.com:4433/10m

bandwidth:
dstat -nf -N bond0
-net/bond0-
 recv  send
1260k   34M
1291k   33M
1279k   32M
1265k   32M
1259k   32M
1242k   32M
1234k   32M
1298k   32M
1335k   32M
1275k   32M
1305k   32M

**Comment by magikstm** [comment]
Which version of Caddy are you using?

What are the OS on the Caddy server and testing machine?

Did you try other parameters for quicbench?

On which machine are you testing? Is it a local machine or a server?

What bandwidth results do you get if you don't test with QUIC? Or with other benchmarking tools?

What is the maximum bandwidth of both machines? (Caddy server and testing)

**Comment by cnkedao** [comment]
Use the latest gquic branch.

Both server and client use Centos7. Two client machine and one server machine.  32G MEM,24 cores CPU, 1000Mbps bandwidth.

Yes,various parameters have been tested many times.

quicbench: [https://github.com/cnkedao/quicbench](https://github.com/cnkedao/quicbench)

Testing Caddy's http2, the bandwidth result is 960 Mbps.

The maximum bandwidth of both machines is 1000Mbps.

**Comment by lib-xdown** [comment]
After my test, quic does have a very small transmission bandwidth. As for why, I don't know.

**Comment by mholt** [comment]
Probably should be reported here instead: https://github.com/lucas-clemente/quic-go

Although Caddy 2 supports HTTP/3, so QUIC will be fading from use.
