### ISSUE TITLE
Add raw markdown data to template's metadata, to support frontend markdown rendering.

### ISSUE THREAD

**Issue by forewing** [caddyserver/caddy#2632]
## 1. What would you like to have changed?

Add an attribute to markdown template that contain the raw markdown text of a .md file, then the use of front(browser) rendering will be possible.

E.g. for a markdown file:

```
---
title: Sample Title
---
# Heading 1
content 1
```

Then in template, `{{ .Doc.raw }}` will hold the data:

```
# Heading 1
content 1
```

Then it will be possible to use:

```
<textarea id="source">
    {{ .Doc.raw }}
</textarea>
<script>
    // Render the raw data store in textarea to a slide show in the browser
    var slideshow = remark.create();
</script>
```

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

Sometime one may want to customize the markdown rendering engin or render their .md file in frontend(browser), then they need the raw data of the markdown file excluding the Front Matter in YAML, TOML or JSON.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Add

```
mdata.Variables["raw"] = string(markdown)
```

in line 70 of `caddyhttp/markdown/process.go`

Then in markdown template,  `{{ .Doc.raw }}` will hold the raw markdown text excluding the Front Matter.

## 4. Please link to any relevant issues, pull requests, or other discussions.

[https://github.com/mholt/caddy/pull/2633](https://github.com/mholt/caddy/pull/2633)

**Comment by mholt** [comment]
Thanks for the feature request and PR. If all you need is to render markdown client-side, why not just use `{{.Include "example.md"}}` to include the markdown file in its raw form?

**Comment by mholt** [comment]
I think we cover this in v2, more or less.
