### ISSUE TITLE
Print Caddy Version to Log on Startup

### ISSUE THREAD

**Issue by Mohammed90** [caddyserver/caddy#2635]
## 1. What would you like to have changed?

Print the version of Caddy to log when started

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

It makes it easy to track the Caddy version running at different points in time while looking at the logs. 

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

The startup command be `caddy -version && caddy [...etc]`, I guess. 

## 4. Please link to any relevant issues, pull requests, or other discussions.

N/A

**Comment by Inconnu08** [comment]
@Mohammed90 I would love to work on this.
