### ISSUE TITLE
Caddy should still try path with extensions if request path contains dot but file doesn't exist

### ISSUE THREAD

**Issue by habibalamin** [caddyserver/caddy#2649]
## 1. Which version of Caddy are you using (`caddy -version`)?

```
$ caddy -version
Caddy 0.11.5 (unofficial)
```

This is installed through Homebrew.

## 2. What are you trying to do?

I want to be able to have a file, such as `example.1.html`, allow the user to request `/example.1`, and rewrite the request to `/example.1.html`.

Example scenario: I have a technical blog and some posts have a version number in the title or other things with a dot, which I don't necessarily want to slugify as `-dot-` or `-point-` (since different ones make sense in different contexts).

## 3. What is your Caddyfile?

I use `localhost` and `tls off` for testing locally, but that will be different in production.

```text
localhost {
  tls off
  root _site

  index index.html index.xml index.txt

  # I go through quite a workaround process to allow clean URLs, and
  # disallow the dirty equivalents.
  #
  # There's an open issue for a proposed `hide` directive; make sure
  # to try it out when (or if) it's released:
  #
  # https://github.com/mholt/caddy/issues/370

  # If path lacks extension, try requesting path with HTML then XML.
  ext .html .xml

  # If path has HTML or XML extension, request `404.html`.
  rewrite {
    ext .html .xml
    to /404.html
  }

  # If requesting `404.html`, set status to `404`. This incidentally
  # forces the `404` page to be requested, so…
  status 404 {
    /404.html
  }

  # …set `404.html` as the `404` page, i.e. the page to be displayed
  # when a requested path cannot be found.
  errors {
    404 404.html
  }

  gzip
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```
$ caddy -conf Caddyfile
Activating privacy features... done.

Serving HTTP on port 2015
http://localhost:2015

WARNING: File descriptor limit 256 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.
```

```
$ curl 'localhost:2015/example.1'
```

## 6. What did you expect to see?

I expect Caddy to respond with the HTML file `example.1.html` that I've placed in the site root.

## 7. What did you see instead (give full error messages and/or log)?

Caddy responds with the configured 404 page.

## 8. Why is this a bug, and how do you think this should be fixed?

I think the request path should be allowed to contain suffixes that _look_ like extensions (but may not be).

The extensions configured for `http.ext` should serve as fallbacks for when the file cannot be found with a name of the literal form, not for when the request path has no extension.

I created a small patch on a fork last night, which I haven't yet tested but will in a bit.

## 9. What are you doing to work around the problem in the meantime?

I have no workaround.

## 10. Please link to any related issues, pull requests, and/or discussion.

I couldn't find any related issues from a quick search.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

I'd like to use it for my blog for the easy/automated Let's Encrypt certificate setup and renewal.

**Comment by habibalamin** [comment]
😞 Ah, I'm not going to test this tonight. I can't even get the project building and I don't have time for this.

The diff is simple enough that I'm just going to post it here inline if anyone wants to test it themselves.

```diff
diff --git a/caddyhttp/extensions/ext.go b/caddyhttp/extensions/ext.go
index b78f5792c..35922794f 100644
--- a/caddyhttp/extensions/ext.go
+++ b/caddyhttp/extensions/ext.go
@@ -45,12 +45,16 @@ type Ext struct {
 // ServeHTTP implements the httpserver.Handler interface.
 func (e Ext) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error) {
 	urlpath := strings.TrimSuffix(r.URL.Path, "/")
-	if len(r.URL.Path) > 0 && path.Ext(urlpath) == "" && r.URL.Path[len(r.URL.Path)-1] != '/' {
-		for _, ext := range e.Extensions {
-			_, err := os.Stat(httpserver.SafePath(e.Root, urlpath) + ext)
-			if err == nil {
-				r.URL.Path = urlpath + ext
-				break
+	if len(r.URL.Path) > 0 && r.URL.Path[len(r.URL.Path)-1] != '/' {
+		_, requestPathDoesntExist := os.Stat(httpserver.SafePath(e.Root, urlpath))
+		
+		if requestPathDoesntExist {
+			for _, ext := range e.Extensions {
+				_, err := os.Stat(httpserver.SafePath(e.Root, urlpath) + ext)
+				if err == nil {
+					r.URL.Path = urlpath + ext
+					break
+				}
 			}
 		}
 	}
```

**Comment by habibalamin** [comment]
I found a workaround:

```
rewrite {
  to {path} {path}.html {path}.xml
}
```

I still feel that the `ext` directive should essentially be a short-form of the `rewrite` directive for a list of extensions, without any `if {file} has \.` condition.

Docs are fine, I'd just forgotten that the `to` option tries each form in order. Perhaps an example could be given that makes specific reference to nginx's `try_files` if you want to make it maximally easy.

**Comment by mholt** [comment]
> Perhaps an example could be given that makes specific reference to nginx's try_files if you want to make it maximally easy.

... easy for people who are familiar with NGINX, maybe. :wink:

There are several examples already for the `to` parameter: https://caddyserver.com/docs/rewrite

**Comment by habibalamin** [comment]
Yes, you're right. I suspect a lot of people will probably be coming from nginx, though.

That said, I can definitely understand not wanting to make ‘docs by comparison’; it can become a bit of a crutch to explain things.

And as I said, the docs are fine, it was more me being stupid/distracted than the docs being badly written.

**Comment by mholt** [comment]
This is now possible in Caddy 2 (you can try it on the v2 branch if you'd like).
