### ISSUE TITLE
error setting up azure DNS provider

### ISSUE THREAD

**Issue by vbap** [caddyserver/caddy#2651]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy v1.0.0

## 2. What are you trying to do?
Run caddy on a windows 2019 server (as a VM on unraid), using azure as DNS provider for DNS challenge
I used Windows 64bit caddy with tls.dns.azure plugin.

## 3. What is your Caddyfile?
```
sub.domain.net {
  proxy / localhost:8081
  tls {
     dns azure
  }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy

(Note, I have set the appropriate system environment variables for Azure DNS challenge)

## 6. What did you expect to see?
DNS challenge performed successfully and caddy started

## 7. What did you see instead (give full error messages and/or log)?
`Caddyfile:5 - Error during parsing: Setting up DNS provider 'azure': azure: Get http://169.254.169.254/metadata/instance/compute/resourceGroupName?api-version=2017-12-01&format=text: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.`

## 8. Why is this a bug, and how do you think this should be fixed?
Due to the error caddy is not serving the host

## Bonus: What do you use Caddy for? Why did you choose Caddy?
Reverse proxy for various apps and services running on an unrid server in a home network environment

**Comment by mholt** [comment]
We recently updated all the DNS providers, it may have been fixed then. But in this case it looks like your network was simply down.
