### ISSUE TITLE
url support at proxy health_check

### ISSUE THREAD

**Issue by iatsiuk** [caddyserver/caddy#2653]
In my case all backends contain "/public" path that should be visible to the rest of the world and private "/ping" path. The last one should not be proxied by caddy.

It would be nice to be able to use placeholders and url in the `health_check` directive:

```
domain.ltd {
    proxy /service 192.168.1.100/public 192.168.1.101/public 192.168.1.102/public {
        health_check {host}/ping
    }
}
```

Right now it is possible to pass only url path but not the full url to the `health_check` directive

**Comment by mholt** [comment]
I believe this is now implemented in Caddy 2.
