### ISSUE TITLE
v2: caddy stop does not stop on windows

### ISSUE THREAD

**Issue by tobya** [caddyserver/caddy#2657]
## 1. Which version of Caddy are you using (`caddy -version`)?
 fdd871e1775d1b6d85de43e8ecf7ddc71a72c503
dev build V2

## 2. What are you trying to do?
Stop Caddy

## 3. What is your Caddyfile?
I dont think its relevant but here it is.

```text
{
  "apps": {
    "http": {
      "servers": {
        "example": {
          "listen": [
            "127.0.0.1:2082",
            "127.0.0.1:2182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "browse": {}
              }
            }
          ]
        },"example2": {
          "listen": [
            "127.0.0.1:3082",
            "127.0.0.1:3182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "root" : "d:\\godev\\bin",
                "browse": {}
              }
            }
          ]
        },"example3": {
          "listen": [
            "127.0.0.1:4082",
            "127.0.0.1:4182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "root" : "d:\\godev\\src",
                "browse": {}
              }
            }
          ]
        }
      }
    }
  }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy start --config caddyfile.txt

## 5. Please paste any relevant HTTP request(s) here.
NA

## 6. What did you expect to see?
When running 

> caddy stop

the following is shown

> pid=21924                                                                                                                                     > Graceful stop...2019/07/07 17:00:35 taskkill: exit status 1     

Caddy doesnt stop it needs to be stopped manually using /f

taskkill /PID /f 21924 

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill

if /f is left out caddy wont terminate.

## 7. What did you see instead (give full error messages and/or log)?

caddy stops

## 8. Why is this a bug, and how do you think this should be fixed?

Caddy shoudl stop

## 9. What are you doing to work around the problem in the meantime?

Manually stop

**Comment by tobya** [comment]
I have a PR for this

**Comment by mholt** [comment]
Does /f do a forceful stop though?

Ideally, Caddy would be notified that it is shutting down; i.e. send an "interrupt" (os.SIGINT or in other words, Ctrl+C) so it can shut down gracefully.

**Comment by tobya** [comment]
/f does do a forceful shutdown, but /f doesnt work!

Since caddy are initiating the shutdown presumably it could notify itself?

If I was to submit a PR do I do it same as normal and they you can merge to V2 when accepted?

**Comment by mholt** [comment]
I just got my method from https://superuser.com/questions/959364/on-windows-how-can-i-gracefully-ask-a-running-program-to-terminate 🤷‍♂ 

A forceful shutdown is not what we want, since it may leave stale locks behind if it happens to be terminated during an ACME operation.

Why is taskkill failing in the first place? I don't understand why /f is an option if that is the only way it will work. Something else must be afoot.

> Since caddy is initiating the shutdown presumably it could notify itself?

Yeah, totally, if we know the address of the admin API.

> If I was to submit a PR do I do it same as normal and they you can merge to V2 when accepted?

Just make sure the PR is against the v2 branch, not master.

**Comment by tobya** [comment]
Ok - I'll investigate further

**Comment by mholt** [comment]
Or really, any pure-Windows way of sending a Ctrl+C to a specific process will do.

**Comment by tobya** [comment]
This is not a straightforward issue and I dont think there is a pure-Windows way of doing it (even in 2019).  

When I try to kill caddy manually using `taskkill` from a terminal window I get the following error  (administrator or not)

> ERROR: The process with PID 9300 could not be terminated.                                                                                     > Reason: This process can only be terminated forcefully (with /F option).

Searching for that on google provides very little, except a few stackoverflow answers.  Sending a good solid Ctrl-C seems to be a perenial problem on windows.  There is a windows app called `windows-kill` that seems to try but it is C++ and unless someone wanted to look at it and reimplement in Go I'm not sure how useful it is.

I'm not sure why taskkill fails in the first place, perhaps its to do with listening on ports or something but thats only a guess.  Whatever the reason it seems consistent.

I think we have a few options

1. Use `taskkill /f` and accept a forced shutdown.
1. When stop request is recieved find a way of communiating with original caddy process and ask it to shut down via admin / api /  rather than sending a signal.  
1. as above but send a windows message to the origional caddy process

**Comment by mholt** [comment]
Interesting... Thanks for the added info.

If nothing else, maybe I'm ok with a forced shutdown on Windows, with the caveat noted in the docs.

But today someone showed me this: https://docs.microsoft.com/en-us/previous-versions/ms811896(v=msdn.10)#ucmgch09_topic3

It has a table which compares Unix signals to their rough windows equivalent. SIGINT is akin to WM_CHAR. And then it says:

> you can use the PostMessage(WM_TIMER) call. This is analogous to using the kill function to send a signal in UNIX.

I don't know how to call PostMessage in Go, but maybe it is similar to this flow? https://github.com/mattn/goreman/blob/e9150e84f13c37dff0a79b8faed5b86522f3eb8e/proc_windows.go#L16-L51

**Comment by tobya** [comment]
I dont think this PostMessage(WM_TIMER) can be usesd to send a terminate message in windows `kill` here is used in the more generic context.

I think on windows we can either send a tidyup and shutdown signal via the admin console, but as you say we need to know the url or we can use another mechanism to signal the origional caddy process that it needs to tidy up before shutdown then `taskkill /f`  the process.

**Comment by tobya** [comment]
An alternative in the short term might be to force kill the process on windows and document it as suggested, but provide a mechanism through the admin that can be used to issue a shutdown.

eg - call these in succession

curl https://localhost:2019/admin/shutdownkill

caddy stop
