### ISSUE TITLE
v2: Duplicate ports are allowed

### ISSUE THREAD

**Issue by tobya** [caddyserver/caddy#2658]
## 1. Which version of Caddy are you using (`caddy -version`)?

v2 dev head

## 2. What are you trying to do?

caddy should refuse to start if 2 servers use the same host:port combination

## 3. What is your Caddyfile?
```text
{
  "apps": {
    "http": {
      "servers": {
        "example": {
          "listen": [
            "127.0.0.1:2082",
            "127.0.0.1:2182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "browse": {}
              }
            }
          ]
        },"example2": {
          "listen": [
            "127.0.0.1:3082",
            "127.0.0.1:2182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "root" : "d:\\godev\\bin",
                "browse": {}
              }
            }
          ]
        }
      }
    }
  }
}
```

note the duplicate use of 
 > 127.0.0.1:2182

## 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy start --config=caddyfileb.txt

## 5. Please paste any relevant HTTP request(s) here.

na

## 6. What did you expect to see?

error  telling me caddy cant start due to reuse of port

## 7. What did you see instead (give full error messages and/or log)?

caddy started

also behaviors is unpredicable on each load as Example is used sometimes and example2 other times.

also on  some restarts or config reloads this appears in the log

````
2019/07/07 18:50:50 [INFO][cache:0xc00042af50] Stopped certificate maintenance routine
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 5ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 10ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 10ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 20ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 20ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 40ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 40ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 80ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 80ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 160ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 160ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 320ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 320ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 640ms
2019/07/07 18:50:50 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 640ms
2019/07/07 18:50:51 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:51 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:52 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:52 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:53 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:53 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:54 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:54 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:55 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:55 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:56 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
2019/07/07 18:50:56 http: Accept error: accept tcp 127.0.0.1:2182: i/o timeout; retrying in 1s
````

**Comment by mholt** [comment]
Thanks @tobya. Will look into this. Do those I/o errors only appear if the listeners are duplicated? Or do they appear with non duplicated listeners as well.

And this is on Windows, I imagine?

**Comment by mholt** [comment]
@tobya I've pushed a fix for the validation of the listener addresses in 42acdad; thanks for the report.

Still really curious about the i/o errors though; there shouldn't be that many. Does it happen only for listeners that are repeated (i.e. does it happen even with the latest commit)?

**Comment by tobya** [comment]
The io errors only happen with the duplicated listener and not every time.  Sometime the listener will start fine and just serve one of 2 duplicated sites but after serveral restarts sometimes I get these io errors.  

They keep going until post a new config with new ports entirely or shut down the server.

Very possibly windows only but I wasnt sure so I didnt use the label.

**Comment by mholt** [comment]
@tobya Okay, excellent. I think I know what's going on there. I definitely patched the duplicate listeners (the check was already in place but the error handling was bad, causing it to be ignored) and that will also resolve the i/o timeout errors in this case. (However, I know what is causing those in the case of duplicate listeners, which isn't intended either, even if it was allowed. I'll see if I can come up with a fix for that too.)

Thanks again! Let me know tomorrow if the patch works for you.

PS. Even with the patch, it is possible that you will see _occasional_ i/o timeouts; these are benign however and expected -- they go away almost instantly -- due to the way we do graceful reloads in Caddy 2.

**Comment by tobya** [comment]
I updated to latest code and go an error 'http: json: unknown field "respond" ' which I presume means you've updated the caddyfile syntax could you let me know what I should change here

````
{
  "apps": {
    "http": {
      "servers": {
        "example": {
          "listen": [
            "127.0.0.1:2082",
            "127.0.0.1:2182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "browse": {}
              }
            }
          ]
        },"example2": {
          "listen": [
            "127.0.0.1:3082",
            "127.0.0.1:2182"

          ],
          "routes": [
            {
              "respond": {
                "responder": "file_server",
                "root" : "d:\\godev\\bin",
                "hide" : [".txt",".bat"],
                "browse": {}
              }
            }
          ]
        }
      }
    }
  }
}
````

**Comment by tobya** [comment]
That seems to fix that issue.

**Comment by mholt** [comment]
Oookie so, for the record, I was able to reproduce the endless `i/o timeout; retrying` errors as I was upgrading the admin endpoint this week.

... and got it fixed!

There was a race (not a data race) between SetDeadline() to set a deadline in the past and the SetDeadline() call that clears the deadline. This has been synchronized and flows really gracefully now under load and for a very long time: https://twitter.com/mholt6/status/1191243190734426112

Will be pushing that commit this week.
