### ISSUE TITLE
markdown Table of Content [TOC] support

### ISSUE THREAD

**Issue by blenderman-de** [caddyserver/caddy#2660]
## 1. What would you like to have changed?
Would be great if you parse `[TOC]` and generate the table of content from headlines. 

Perfect if the anchor to the headline would be named by headline text instead of cheap ID. Like `https:\\SEVER.PATH.md#HEADLINETEXT `

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
This would be a great addition to your markdown support. Even for intranet applications and documentation. 

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
We convert manually our HTML with the editor VCStudio and Markdown Preview Enhanced Addon or with Pandoc CLI.

**Comment by mholt** [comment]
I think we need to be careful not to make the Markdown middleware more than it is, and a content generator it is not -- we want to make sure it does not creep closer to being a static site generator.
