### ISSUE TITLE
markdown ==highlight== support

### ISSUE THREAD

**Issue by blenderman-de** [caddyserver/caddy#2661]
## 1. What would you like to have changed?
Would be great if your parser supports: `==highlight==`. 

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
This would be a great addition to your markdown support. Even for intranet applications and documentation.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
We convert manually our HTML with the editor VCStudio and Markdown Preview Enhanced Addon or with Pandoc CLI.

**Comment by mholt** [comment]
What is `==highlight==`?

In any case, feature requests for the markdown renderer should probably go upstream in our Markdown library of choice, blackfriday: https://github.com/russross/blackfriday/issues
