### ISSUE TITLE
HTTP/2 Push doesn't work with cache plugin

### ISSUE THREAD

**Issue by waaayfar3r** [caddyserver/caddy#2666]
Enabling _cache_ plugin breaks HTTP/2 pushing

## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy v1.0.1 (h1:oor6ep+8NoJOabpFXhvjqjfeldtw1XSzfISVrbfqTKo=)

## 2. What are you trying to do?
Enable cache while pushing resources via HTTP/2

## 3. What is your Caddyfile?
```text
example.com {
  redir https://www.example.com{uri}
}

www.example.com {
  root /var/www/example.com/
  errors {
    404 /var/www/example.com/404.html
  }
  push / {
    /css/style.min.css
    /fonts/HelveticaNeueMedium.woff
    /fonts/HelveticaNeueBold.woff
    /logo.svg
    /favicon.ico
  }
  cache {
    match_path /css
    match_path /fonts
    match_path /logo.svg
    match_path /favicon.ico
    default_max_age 5m
  }
  gzip
  ratelimit * / 5 10 second
  header / Strict-Transport-Security "max-age=31536000; preload; includeSubDomains"
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
via systemd, on Ubuntu 18.04

## 5. Please paste any relevant HTTP request(s) here.
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Length: 684
Content-Type: text/html; charset=utf-8
Date: Thu, 11 Jul 2019 22:09:34 GMT
Etag: W/"puhyjk17d"
Last-Modified: Thu, 11 Jul 2019 21:33:20 GMT
Server: Caddy
Strict-Transport-Security: max-age=31536000; preload; includeSubDomains
Vary: Accept-Encoding
X-Cache-Status: miss

## 6. What did you expect to see?
HTTP/2 push is working
![Screenshot from 2019-07-12 01-14-16](https://user-images.githubusercontent.com/49662783/61089348-7db09780-a443-11e9-9e3e-85047383264a.jpg)

## 7. What did you see instead?
Resources are not pushed
![Screenshot from 2019-07-12 01-11-37](https://user-images.githubusercontent.com/49662783/61089357-81dcb500-a443-11e9-8959-6c8b976b1940.jpg)

There are no errors in log files, so I presume this issue is somehow related to middleware order

**Comment by mholt** [comment]
Hi there, thanks for the issue and for filling out the issue template! This is an issue regarding a third-party plugin, so it seems like this is something that will need to be resolved by the plugin's author. My suggestion for you to get this fixed more quickly is to open this issue in the plugin's repository instead of this one. The author of the plugin will best know how to handle this. Thank you!
