### ISSUE TITLE
reinvigoration of caddyserver/caddy docker image

### ISSUE THREAD

**Issue by grooverdan** [caddyserver/caddy#2667]
I noticed on your main download site the options for cross compiled images are extensive. Wondering if you'd consider extending concept to bring multiarch base images to https://hub.docker.com/r/caddyserver/caddy. This would help simplify some use rather than some [convoluted builds](https://github.com/Netflix/vector/blob/master/Dockerfile).

The below script based on github released images generates a multiarch manifest http://soaphub.org/imagehub/?q=caddy&n=danielblack&p=0 with the intent that a user would extend the image with `FROM caddyserver/caddy:v1.0.1` and this would fetch the architecture image required. The `caddyserver/caddy:latest` is also pushed with this image and this is usually a mature release rather than a bleeding edge.

Notes:
* Windows image generation on Linux seem to fail at the base image (even with `docker pull --platform windows/amd64 mcr.microsoft.com/windows/servercore`) maybe need to need [azure](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/Dockerfile-nanoserver-1803)
* Arm(32) variants can use the `--variant` with v3 .. v8 identifiers (https://github.com/containerd/containerd/blob/master/platforms/cpuinfo.go#L99)
* Individual base images are autotagged with amd64/linux as the base system as `docker push` can't specify a platform.

script: https://gist.github.com/grooverdan/136f7cec0cedf67d13608c797d9eccca

**Comment by francislavoie** [comment]
I recommend using https://github.com/abiosoft/caddy-docker. It's maintained quite diligently by @abiosoft and is quite flexible. It's as close to an official docker image as you'll get for the time being.

**Comment by grooverdan** [comment]
Thanks for the tip. I might get around to looking cross-building there. We'll see if the outstanding PR gets merged.

**Comment by mholt** [comment]
We're trying to publish official images for v2, but Docker has been silent to our support emails and this forum thread: https://forums.docker.com/t/organization-name-already-exists-but-is-empty/82483

**Comment by pataquets** [comment]
What a pity. FWIW, they have done it in the past. See openresty/docker-openresty#4. Good luck with it.

**Comment by mholt** [comment]
We finally got the name and are now finishing up the Docker image. @Ilyes512 would probably have an update on that!

**Comment by k2589** [comment]
> We finally got the name and are now finishing up the Docker image. @Ilyes512 would probably have an update on that!

Please provide documentation about using inside docker (like examples of Dockerfile, commands to execute, docker-compose,  swarm & k8s)

**Comment by mannp** [comment]
I've been looking without much success to find an official docker image for caddy.

Is there perhaps an update to this thread, or direction to which is the preferred docker to use?

Thanks.

**Comment by francislavoie** [comment]
Yep! https://github.com/caddyserver/caddy-docker

There's also an open PR to add it as official image! https://github.com/docker-library/official-images/pull/7574

**Comment by francislavoie** [comment]
I'll close this now - nothing actionable left here.
