### ISSUE TITLE
v2: Docker Image - Non daemon process (feature)

### ISSUE THREAD

**Issue by rlweb** [caddyserver/caddy#2669]
## 1. Which version of Caddy are you using (`caddy -version`)?
v2 branch which gives undefined

## 2. What are you trying to do?
Build a docker image containing v2 so I can test it out within our staging environment

## 3. What is your Caddyfile?
```text
{
  "apps": {
    "http": {
      "servers": {
        "myserver": {
          "listen": [":80"]
        }
      }
    }
  }
}

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
```
docker-compose up --build caddy
```
or remove the dependency of docker-compose
```
docker build -t caddy . && docker run caddy -v "./docker/caddyv2/config.json:/etc/caddy.json"
```

## 5. Please paste any relevant HTTP request(s) here.
N/a

## 6. What did you expect to see?
The container to continue running and that I can access localhost on port 80.

## 7. What did you see instead (give full error messages and/or log)?
```
Building caddy
Step 1/12 : FROM golang:1.12-alpine3.10 as builder
 ---> 6b21b4c6e7a3
Step 2/12 : LABEL maintainer="Rhys Laval <rhyslaval@gmail.com>"
 ---> Using cache
 ---> 7074b1b61c42
Step 3/12 : RUN apk add --no-cache ca-certificates git
 ---> Using cache
 ---> 6189754137e8
Step 4/12 : WORKDIR /src
 ---> Using cache
 ---> c1ddd805044d
Step 5/12 : RUN git clone -b v2 "https://github.com/caddyserver/caddy.git" /src
 ---> Using cache
 ---> 805aea4ee08e
Step 6/12 : RUN cd cmd/caddy &&     CGO_ENABLED=0 go build     -installsuffix 'static'     -o /caddy .
 ---> Using cache
 ---> 0f6fc6f15324
Step 7/12 : FROM scratch AS final
 ---> 
Step 8/12 : COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 ---> Using cache
 ---> 02b51027abec
Step 9/12 : COPY --from=builder /caddy /caddy
 ---> Using cache
 ---> 4594cce85df9
Step 10/12 : VOLUME /etc/caddy.json
 ---> Using cache
 ---> 5331bcd1494b
Step 11/12 : ENTRYPOINT ["/caddy"]
 ---> Using cache
 ---> dc50e241009c
Step 12/12 : CMD ["start"]
 ---> Using cache
 ---> 1e8a26bb04a1
Successfully built 1e8a26bb04a1
Successfully tagged caddy:latest
Starting caddy_1 ... done
Attaching to caddy_1
caddy_1   | 2019/07/13 18:01:51 Caddy 2 admin endpoint listening on localhost:2019
caddy_1   | Successfully started Caddy
caddy_1 exited with code 0
```

## 8. Why is this a bug, and how do you think this should be fixed?

Since the way docker works we need the thread to be non-deamoned to continue the container to be held open. 

## 9. What are you doing to work around the problem in the meantime?
Run the thread with supervisor

## 10. Please link to any related issues, pull requests, and/or discussion.
Here is the Dockerfile being used: https://github.com/rlweb/docker-caddy-v2/blob/master/Dockerfile

## Bonus: What do you use Caddy for? Why did you choose Caddy?
Cause it's so simple and easy to use for lets encrypt!

**Comment by rlweb** [comment]
Oops, I've realized its a demon'd thread. Modified the above to state this but this now is a feature request, oops!

**Comment by mholt** [comment]
Thanks for filling out the issue template!

Caddy start doesn't run caddy I'm daemon mode. Use caddy run instead. That will block indefinitely.

Let me know how that goes!
