### ISSUE TITLE
v2: Improve placeholder performance

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2673]
Placeholders in v2 have a much simpler implementation than in v1, but their performance is not great on busy servers.

We should avoid allocating strings unless necessary. In other words, instead of building a full map of all possible replacements and calling `strings.ReplaceAll()`, we should only obtain string values for placeholders that are used. I suspect this will help speed things up quite a bit.

**Comment by aligator** [comment]
I would like to contribute to caddy. Do you think this is a good starting point?

**Comment by mholt** [comment]
@aligator I would say so, since it would get you familiar with several parts of the v2 code base. I would rate this task as moderate. It requires doing some performance testing before starting, and probably some profiling. Then any changes will need to be tested again with the same tests to ensure they are faster.

**Comment by aligator** [comment]
Ok, great. Do you already have something for performance tests?

**Comment by mholt** [comment]
Yes, but my results will be different on my machine than they are on yours. So you'll need to set up your own tests (you can use wrk, for example, to do some high-level load testing) and see how they compare on your own system.

First, here's a simple config I used to get a baseline:

```
{
	"apps": {
		"http": {
			"servers": {
				"myserver": {
					"listen": [":8080"],
					"routes": [
						{
							"handle": [{
								"handler": "static_response",
								"body": "Method: GET URI: '/' Path: '/' Query: ''"
							}]
						}
					]
				}
			}
		}
	}
}
```

I started Caddy with that config then used wrk:

```
$ wrk -t12 -c400 -d10s http://127.0.0.1:8080
```

(all the caveats of performance testing apply here; for example make sure your machine is in a consistent state every time, such as plugged in to power, not running energy-intensive apps, etc. etc.)

Then I used an equivalent config with several placeholders:

```
{
	"apps": {
		"http": {
			"servers": {
				"myserver": {
					"listen": [":8080"],
					"routes": [
						{
							"handle": [{
								"handler": "static_response",
								"body": "Method: {http.request.method} URI: '{http.request.uri}' Path: '{http.request.uri.path}' Query: '{http.request.uri.query}'"
							}]
						}
					]
				}
			}
		}
	}
}
```

And did the same load test again.

To ascertain the specific reason for the performance drop, some profiling is needed. pprof can help with that: 

- https://golang.org/pkg/net/http/pprof/
- https://blog.golang.org/profiling-go-programs

**Comment by aligator** [comment]
Thank you, I'll look into it.

**Comment by mholt** [comment]
Great!

Just so you know, I've made some progress last night already. But some help testing for both correctness and better performance (along with additional profiling) is very needed! I'll push a PR soon.
