### ISSUE TITLE
v2: DNS TLS challenge not working

### ISSUE THREAD

**Issue by blattersturm** [caddyserver/caddy#2676]
https://github.com/caddyserver/caddy/blob/b44a22a9d45443aa736a04495dfe716b62b58adc/modules/caddytls/acmemanager.go#L69-L73

This should probably check `DNSRaw`, not `DNS`. Also, the error message below seems to mention storage modules, not DNS providers.

**Comment by mholt** [comment]
Oops, copy+pasta mistake. Thanks for the report. Will fix this up in a jiffy.
