### ISSUE TITLE
v2: Logging

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2678]
Version 2 needs a flexible logging module.

Main goals:

- Performance: zero allocation loggers would be ideal in the hot paths. Consider using https://github.com/uber-go/zap
- Structure: logs should be programmable.
- Modular backends: logs should be able to go to anywhere, whether it be a file, stdout/stderr, a system log, or over the network to some third-party logging service.
- Customizable output formats: logs should be able to be customized as to how they look and what information they include; for example the standard Apache log format should be possible as well as JSON or binary log formats.
- Customizable emissions: choose specifically what gets emitted, even beyond just log levels. Do we want to emit errors about clients closing a connection, or just ACME certificate errors instead?
- Standard process log: most/all dependencies use the standard logger or won't integrate specifically with our logging system, so we need a way to dump those (secondary) logs to a file or a stream of the user's choice.
- Reduce repetition considering tracing/metrics/telemety: if logs use logic similar to tracing/metrics (which tracks a connection or request through various handlers / parts of the config) or telemetry (which helps understand global caddy usage), it should reuse the same code or infrastructure when possible. (If we add telemetry, it will be a very watered-down version of what Caddy 1 had, which was too expensive to maintain.)

**Comment by tobya** [comment]
This looks like as good a place to discuss this as any.

At this point in Caddy v2 Development should we wrap calls to `fmt.Printf` so we can also redirect these?

These calls obviously go directly to the console whereas `log.Printf` will sometimes but not always get redirected to a system log file etc.  This led to some slightly funny output in Caddy v1 (eg #2497 )

Even if we just wrapped all calls to `fmt.Printf` at this stage it would give us options.

**Comment by tobya** [comment]
I found this which seems to be an evolution of uber/zap, and may be good https://github.com/rs/zerolog

**Comment by mholt** [comment]
Basically done in #2831. Just some loose ends to finish up. Pretty much all of the above points have been reached.
