### ISSUE TITLE
v2: Brief instructional/demo videos

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2683]
A series of short videos that can be easily shared and viewed to gain understanding of Caddy 2. We're talking like 60 seconds or less.

Some ideas:

- What is Caddy 2, and why is different or better than Caddy 1 and the competition
- Quick start: setting up a production static file server with HTTPS in 1 minute
- Quick start: dynamic config (Caddy Enterprise) - e.g. adding a proxy backend
- Architecture overview
- Summary of modules
- Starlark demos (@dannav)
- Ingress controller demos (@dannav)
- Tour of individual modules, esp. HTTP handlers and TLS configuration

**Comment by bigman-rgb** [comment]
> A series of short videos that can be easily shared and viewed to gain understanding of Caddy 2. We're talking like 60 seconds or less.
> 
> Some ideas:
> 
> * What is Caddy 2, and why is different or better than Caddy 1 and the competition
> * Quick start: setting up a production static file server with HTTPS in 1 minute
> * Quick start: dynamic config (Caddy Enterprise) - e.g. adding a proxy backend
> * Architecture overview
> * Summary of modules
> * Starlark demos (@dannav)
> * Ingress controller demos (@dannav)
> * Tour of individual modules, esp. HTTP handlers and TLS configuration

Where can I find the specific video? I can't seem to find a video of caddy2.

**Comment by mholt** [comment]
We haven't made any yet. :) First priority is getting the Caddyfile adapter working, then I'll make some videos!

**Comment by mholt** [comment]
The videos are being posted here: https://www.youtube.com/playlist?list=PLdnO1_NRAWW0HyPMBJ86teR1RUikQBOAY
