### ISSUE TITLE
http: TLS handshake error from x.x.x.x:y: no certificate available for ''

### ISSUE THREAD

**Issue by GreatFireWall** [caddyserver/caddy#2684]
I'm using AlibabaCloud CDN.

![image](https://user-images.githubusercontent.com/4510984/61584068-6c1e6c80-ab74-11e9-8fb5-251eed3a6d1c.png)

**Comment by francislavoie** [comment]
Unfortunately, you didn't provide enough information here for us to help you. Please ask for help on https://caddy.community with as much detail as you can provide.
