### ISSUE TITLE
release a v2 alpha version

### ISSUE THREAD

**Issue by coderafei** [caddyserver/caddy#2685]
## 1. What would you like to have changed?
release a v2 alpha version

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
so we can import v2 code from other codebase

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
find no way...

## 4. Please link to any relevant issues, pull requests, or other discussions.
no

**Comment by coderafei** [comment]
or how to import v2 code?

**Comment by abiosoft** [comment]
One does not simply release until it is time for a release.

The code is in active development, some level of stability is required before any sort of release can be done. Those of us running it right now are more or less working with the source code.

If you're really anticipating and can't wait anymore, kindly work with the [v2](https://github.com/caddyserver/caddy/tree/v2) branch. And thanks to go modules, you can import specific branch.

Thanks.

**Comment by coderafei** [comment]
@abiosoft thx!
could you provide some code for how to import v2 code at readme?
i can not find it out...

**Comment by mholt** [comment]
Are you using Go modules?

**Comment by coderafei** [comment]
yes, go modules
`go get github.com/caddyserver/caddy@v2`
it say no matching versions for query "v2"

**Comment by mholt** [comment]
@coderafei Ah, yes, you've hit one of the pain points / limitations of Go modules. I already reported it in https://github.com/golang/go/issues/33010.

The workaround -- though slightly annoying -- is to `go get github.com/caddyserver/caddy/v2@COMMIT` where `COMMIT` is the latest commit sha on the v2 branch. Then your import path will be `github.com/caddyserver/caddy/v2`.
