### ISSUE TITLE
Is the Extension API stable for Caddy v2?

### ISSUE THREAD

**Issue by IvanDelsinne** [caddyserver/caddy#2689]
I'm waiting for the stable release of Caddy v2, and I'm planning to work on an extension for it.

I'd like to already start working on it.

Is the Caddy extension API spec/connector stable yet?

**Comment by elcore** [comment]
Hello Ivan,

> I'm waiting for the stable release of Caddy v2

This might take a while, as Caddy 2 is currently under heavy development, but I can assure you that there will be pre-releases sooner or later.

> Is the Caddy extension API spec/connector stable yet?

The last time I have asked the answer was no, so I will leave that to Matt.

**Comment by mholt** [comment]
Hi @IvanDelsinne - thanks for your question!

It's not 100% stable yet but it's likely not going to change much, either. I'd say go for it, and I'll help with integrating it as you go along. Writing extensions ("modules") isn't well-documented yet but this is a good opportunity for me to start doing that. What kind of module are you building? What will it do?

**Comment by mholt** [comment]
@IvanDelsinne I spent some time today writing up some ad-hoc module developer docs: https://github.com/caddyserver/caddy/wiki/v2:-Writing-a-Module

I hope you find them at least a little bit helpful! Let us know if you have any questions.

Will close this issue for now, but if there is a technical problem, feel free to open a new issue.
