### ISSUE TITLE
v2: Use yeagi for scripting

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [caddyserver/caddy#2690]
Hi there,
Traefik project just released their yeagi(https://github.com/containous/yaegi) Go interpreter, and I do think it would be awesome if Caddy v2 supports its native language, instead of new (and unknown) Starlark. 

Thanks

**Comment by mholt** [comment]
I don't think we're interested in using it unless there is compelling evidence that it is objectively better than Starlark. For one thing, performance is a huge factor. Starlark, for example, doesn't use reflection, and we already have evidence that Starlark performs faster than nginx+Lua after optimizations. Can yaegi do better? Is it easier to write expressions and dynamic routes in a Go script? Is strong typing a benefit or an inconvenience in an embedded scripting envionment? Until we can answer questions like these in yaegi's favor, we'll stick with Starlark.

**Comment by diyism** [comment]
"Starlark-go python" is cool, but as a web developer, I prefer "yaegi go script" as my web server language, I'll give it a try
