### ISSUE TITLE
mitm.watch displays "Likely Mitm!" when using Firefox' Private Mode

### ISSUE THREAD

**Issue by Darkspirit** [caddyserver/caddy#2691]
Please see
https://bugzilla.mozilla.org/show_bug.cgi?id=1569395#c14
https://bugzilla.mozilla.org/show_bug.cgi?id=1569395#c15
> Look at what Caddy does in order to identify Firefox, it expects to see TLS extension type 35: https://github.com/caddyserver/caddy/blob/f5720fecd663f521d832c1bca69e52ece43dc2b1/caddyhttp/httpserver/mitm.go#L406 But for TorBrowser which disables TLS session tickets (similar to what we do for private browsing contexts now) it [doesn't expect that](https://github.com/caddyserver/caddy/blob/f5720fecd663f521d832c1bca69e52ece43dc2b1/caddyhttp/httpserver/mitm.go#L631). Looks like Caddy needs to be updated here, since their MITM detection is based on detecting the expected characteristics of the TLS traffic generated by browsers.

**Comment by mholt** [comment]
Thanks. Can you please provide the following:

> To report a false positive, please file an issue with your real, unmodified User-Agent string, browser version, OS/platform details, the raw ClientHello bytes, and any other relevant build information.

**Comment by Darkspirit** [comment]
All available information is provided in https://bugzilla.mozilla.org/show_bug.cgi?id=1569395:
Firefox' UA string looks like this:
`Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0`
Every Firefox version since 68 (current stable release) has this new behavior. OS does not matter.
I can't remember when I last captured raw network bytes, it might be far easier for you. :/

STR:
a) Open Firefox, open a private window, load insecure http://mitm.watch.
b) Open Firefox, open about:config, set privacy.firstparty.isolate to true, open a private window, load https://mitm.watch.

**Comment by artus** [comment]
This issue is related to the one I'm having (#2697).

**Comment by mholt** [comment]
Closing, since this feature is no longer being developed. V2 can have this feature, but that development is being tracked in https://github.com/caddyserver/caddy/issues/2530.
