### ISSUE TITLE
About problems when compiling third-party plugins

### ISSUE THREAD

**Issue by bigman-rgb** [caddyserver/caddy#2692]
At present, what I hope is to add third-party plug-ins through the source code, but unfortunately I have encountered some problems. Since I am still a super novice, I would like to ask you how to solve it?

As an example to restore the problem, I will show the process of my compilation:

Set the transitional environment variable for Go modules
```
export GO111MODULE=on
```
Create a file called caddy.go in the opt/ directory.
```
touch caddy.go
```
Edit the caddy.go file，Join the cloudflare plugin
```
package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"

	// plug in plugins here, for example:
	// _ "import/path/here"
        _ "github.com/caddyserver/dnsproviders/cloudflare"
)

func main() {
	// optional: disable telemetry
	// caddymain.EnableTelemetry = false
	caddymain.Run()
}
```
Then execute "go mod init caddy"
```
go mod init caddy
```
Run 
```
go get github.com/caddyserver/caddy
```
Run 
```
go install
```
But found the following problem
```
root@ip:/opt# go install
go: github.com/caddyserver/dnsproviders@v0.3.0 requires
        github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
root@ip:/opt# 
```

what should I do? Can you tell me the solution? I am still a newbie

**Comment by mholt** [comment]
What is your go.mod?

Try removing $GOPATH/pkg/mod and also try `go get github.com/caddyserver/dnsproviders@c2e7db47dc629b8813286b70ff106a4fc55bfb3b` (the latest commit, instead of latest release).

**Comment by bigman-rgb** [comment]
> Edit: I just saw your [forum post](https://caddy.community/t/about-problems-when-compiling-third-party-cloudflare-plugins/6051?u=matt) of the same thing, and I think it'd be better to discuss it there since this isn't exactly a bug or feature request for Caddy.

I did see the reply in that post, but I found that I still failed, but I can't reply to the post.

**Comment by mholt** [comment]
The system keeps flagging your posts:

> New user typed their first post suspiciously fast, suspected bot or spammer behavior.

How fast are you typing them? Try typing them at a normal speed, I guess.
