### ISSUE TITLE
v2. get module instance from other module

### ISSUE THREAD

**Issue by coderafei** [caddyserver/caddy#2693]
## 1. What would you like to have changed?
get other module instance like caddyhttp, so i can get it configs

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
like some cross module actions

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
hard code ...

**Comment by mholt** [comment]
Er... I don't follow. Can you be more precise about what you're requesting please?

**Comment by mholt** [comment]
Is this what you mean? https://github.com/caddyserver/caddy/blob/c8b0a97b1c2524f7486aef38b2cf78a93d7b98b0/modules/caddyhttp/caddyhttp.go#L203-L207

**Comment by coderafei** [comment]
wow yes! thx!

**Comment by mholt** [comment]
Just make sure to do it _after_ Provision and Validate - in other words, after the app's Start method has been called.

Whatcha building? :)

**Comment by coderafei** [comment]
a hosts module for caddy, auto update local hosts file depend on match hosts
caddy v2 code design is very easy to understand, even a go beginner like me

**Comment by mholt** [comment]
Oohh, that sounds really interesting! Keep me posted. If you have code published, link me up. :) I would be happy to provide feedback when you're ready.

**Comment by coderafei** [comment]
oops.
![image](https://user-images.githubusercontent.com/4183342/62517984-124bc100-b85b-11e9-90eb-9fd0d7f2367f.png)
Can not get matcherSets outside caddyhttp package

**Comment by mholt** [comment]
@coderafei Ah, yeah... I've debated how much to export. I started conservatively by not exporting things that weren't explicitly in the JSON config -- i.e. exporting only what the encoding/json package needs to access -- but maybe I should just export everything.

I will work on that, hopefully I'll have a chance soon to take a break from the Caddyfile adapter and export things. Be aware that type and field names may change slightly (to be expected in pre-beta stage anyway, right?).

In the meantime, if you could confirm that exporting that field gives you the ability you need, that would be helpful!

**Comment by coderafei** [comment]
yes, it's about module design, i think a module exports `rich` `readonly` props, and few useful function will be helpfully for develop other modules, especially `caddyhttp` module

**Comment by mholt** [comment]
@coderafei I opened https://github.com/caddyserver/caddy/issues/2695

**Comment by mholt** [comment]
@coderafei I have exported those fields in the latest v2 branch.
