### ISSUE TITLE
OpenBSD - Caddy immediately dies on http requests

### ISSUE THREAD

**Issue by jungle-boogie** [caddyserver/caddy#2694]
Hello,

## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy v1.0.1 (h1:oor6ep+8NoJOabpFXhvjqjfeldtw1XSzfISVrbfqTKo=)

## 2. What are you trying to do?
I would like to use Caddy to serve a 404 page.

## 3. What is your Caddyfile?
```
$ cat Caddyfile
localhost:8080
log access.log
log err.log
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
`$ ./Downloads/caddy -log err2.log`

## 5. Please paste any relevant HTTP request(s) here.
```
$ curl http://localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

## 6. What did you expect to see?
The default 404 not found page.

## 7. What did you see instead (give full error messages and/or log)?
See curl response above.
```
$ cat err.log err2.log
2019/08/05 07:56:52 [INFO] Serving http://localhost:8080
2019/08/05 07:56:52 [INFO][cache:0xc000092730] Started certificate maintenance routine
```
(note err.log is blank, but err2 contains the text above.)

## 8. Why is this a bug, and how do you think this should be fixed?
This is a bug because Caddy is dying each time there is an http request. I see no reason why it should be dying.

## 9. What are you doing to work around the problem in the meantime?
I know of know work around for this.

You didn't ask about the OS or go version, so I will provide that...

```
$ sysctl kern.version
kern.version=OpenBSD 6.5-current (GENERIC.MP) #171: Sun Aug  4 11:11:52 MDT 2019
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

```
$ go version
go version go1.12.7 openbsd/amd64
```

**Comment by mholt** [comment]
Does this still happen if you remove one of the log directives?

**Comment by jungle-boogie** [comment]
```
$ cat Caddyfile
localhost:8080
```
```
$ ./Downloads/caddy
Activating privacy features... done.

Serving HTTP on port 8080
http://localhost:8080
```
```
$ curl http://localhost:8080
curl: (52) Empty reply from server
```
# Second try

```
$ cat Caddyfile
localhost:8080
```

```
$ ./Downloads/caddy -log err.log
Activating privacy features... done.

Serving HTTP on port 8080
http://localhost:8080
```

```
$ curl http://localhost:8080
curl: (56) Recv failure: Connection reset by peer
```

```
$ cat err.log
2019/08/05 12:36:22 [INFO] Serving http://localhost:8080
2019/08/05 12:36:22 [INFO][cache:0xc000092690] Started certificate maintenance routine
```

Do I need to disable TLS in someway?

**Comment by jungle-boogie** [comment]
On a raspberry pi, a blank, non-existing `Caddyfile` will allow curl connects to the default 2015 port.

```
$ caddy -version
v0.0.0-00010101000000-000000000000
```

**Comment by jungle-boogie** [comment]
This may or may not be useful...
1. You can get an OpenBSD shell account at https://tilde.institute

2. When I run caddy (v0.0.0-00010101000000-000000000000) on there for port 8080 (since I know that's an open port), the same error occurs:
```
$ cat err.log
2019/08/05 15:50:31 [INFO] Serving http://:8080
2019/08/05 15:50:31 [INFO][cache:0xc0000307d0] Started certificate maintenance routine
```

```
$ ./caddy -port 8080 -log err.log
Activating privacy features... done.

Serving HTTP on port 8080
http://:8080

WARNING: File descriptor limit 512 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.
```

URL: https://tilde.institute:8080 (won't work, since the process is dead)

However, TLS is enabled so Firefox shows "Secure Connection Failed".

I still would not expect the caddy process to die when it gets an http request.

**Comment by jungle-boogie** [comment]
A quick test of a few other go programs function:
1. `gopass`: https://github.com/gopasspw/gopass
2. `aerc`: https://aerc-mail.org/
3. `termshark`: https://github.com/gcla/termshark
4. `rclone`: https://github.com/rclone/rclone

**Comment by mholt** [comment]
Is there anything in Caddy's process log? (e.g. `caddy -log process.log`)

**Comment by jungle-boogie** [comment]
Doesn't look like it...
```
$ ./Downloads/caddy -log process.log
Activating privacy features... done.

Serving HTTP on port 8080
http://localhost:8080


$ cat process.log
2019/08/05 14:08:41 [INFO] Serving http://localhost:8080
2019/08/05 14:08:41 [INFO][cache:0xc0000a6730] Started certificate maintenance routine
````

**Comment by mholt** [comment]
Oh, sorry, I somehow missed that you already specified `-log` above. 🤦‍♂ 

As soon as I get a hot second, I'll try to set up an account there. In the meantime, if you want to debug it sooner, you can start by putting print statements in the code starting in this function, which is the base entry point of all HTTP requests (coming from the standard lib) into Caddy: https://github.com/caddyserver/caddy/blob/0ba427a6f44edb5169e022e3cbc23f7b6de35a81/caddyhttp/httpserver/server.go#L352

See how far the execution gets before something bad happens...

**Comment by jungle-boogie** [comment]
Sorry, I haven't had time to try debugging this yet.

**Comment by jungle-boogie** [comment]
Just reporting that your latest caddy releases also appear to die when the first http request is made.
https://github.com/caddyserver/caddy/releases/tag/v1.0.3

**Comment by mholt** [comment]
If it is a bug in Caddy, it probably won't get fixed until someone has a chance to debug it. Would you be able to take a look at it in more detail this weekend? I never got that account I requested, so it's up to you or someone else with BSD.

**Comment by jungle-boogie** [comment]
Hi,

Thanks. I understand and I will try to debug it.

Meanwhile, was mholt the account you requested? I see the home directory
was created, which probably means the account was also created:

https://mholt.tilde.institute/

Thanks for the reply,
Jb

**Comment by mholt** [comment]
Yep, that'd be it. I never got an email about it or anything, but I'll give it a try when I have a chance. But, it may not be for a while given some life things happening soon.

**Comment by jungle-boogie** [comment]
Just some notes, not asking you to debug...

**good:**
$ caddy -version
Caddy 0.11.1 (+6f580c6 Tue Nov 13 19:51:49 UTC 2018) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go

$ ./caddy -version
Caddy 0.11.4 (+c1d6c92 Fri Feb 15 19:06:26 UTC 2019) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go

$ ./caddy -version
Caddy 0.11.5 (+80dfb8b Mon Mar 04 19:51:23 UTC 2019) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go

$ ./caddy -version
Caddy 1.0.0-beta1 (+657780b Tue Apr 09 19:29:34 UTC 2019) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go

$ ./caddy -version
caddy_v1.0.0-beta2_openbsd_amd64


**broken:**
./caddy_v1.0.0_openbsd_amd64

**Comment by jungle-boogie** [comment]
So something in this commit breaks it and causes caddy to die immediately:
https://github.com/caddyserver/caddy/commit/c32a0f5f712f0dee7b473946fcee65e826501e56

**Comment by mholt** [comment]
@jungle-boogie Thanks for the investigation so far. Is the broken command (`./caddy_v1.0.0_openbsd_amd64`) also running `-version` and still fails?

**Comment by jungle-boogie** [comment]
Hi @mholt,

I downloaded OpenBSD build: https://github.com/caddyserver/caddy/releases/tag/v1.0.0
which generates this for `-version`:

```
$ ./caddy -version
v0.0.0-00010101000000-000000000000
```

**Comment by mholt** [comment]
Okay, so `-version` works, I was just confused because you used `-version` for all the "good" binaries above but not for the "bad" one.

**Comment by jungle-boogie** [comment]
Sorry about that. That version of Caddy will startup, but will immediately die on the first http request to the server.

**Comment by jungle-boogie** [comment]
This has been fixed by the wonderful @didil in pull request https://github.com/caddyserver/caddy/pull/2787

A million thanks to didil for taking the time to track this down.

Thanks to @mholt for committing to trunk for easier testing.

**Comment by didil** [comment]
@jungle-boogie thanks for the tilde institute shell account tip. definitely recommend to others who want to debug or triage an issue on openbsd.
