### ISSUE TITLE
Go Modules Broken Due to Rename

### ISSUE THREAD

**Issue by gabrielhartmann** [caddyserver/caddy#2696]
## 1. Which version of Caddy are you using (`caddy -version`)?
I'm not using caddy.  It's getting imported as an indirect dependency.

## 2. What are you trying to do?
I'm trying to build my go project which uses some kubernetes module

## 3. What is your Caddyfile?
N/A

## 4. How did you run Caddy (give the full command and describe the execution environment)?
N/A

## 5. Please paste any relevant HTTP request(s) here.
N/A

## 6. What did you expect to see?
I expected the module to import

## 7. What did you see instead (give full error messages and/or log)?
```
$ goreleaser --snapshot --skip-publish --rm-dist

   • releasing using goreleaser 0.110.0...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
      • running go mod download
      • running go generate ./...
   ⨯ release failed after 0.88s error=hook failed: go generate ./...
go: finding github.com/mholt/caddy/caddyfile latest
go: finding k8s.io/cloud-provider/features latest
go: finding k8s.io/cloud-provider latest
go: github.com/mholt/caddy@v1.0.1: parsing go.mod: unexpected module path "github.com/caddyserver/caddy"
go: error loading module requirements
```

## 8. Why is this a bug, and how do you think this should be fixed?
It's a bug because I can't import the module.  The solution is to keep the old repository name around for awhile while fixing go's module system to handle this case.

## 9. What are you doing to work around the problem in the meantime?
I'll probably fork the project and fix the module name.  Attempting to do go module `replace` operations lead me down a dark dependency hell path.

## 10. Please link to any related issues, pull requests, and/or discussion.
N/A

**Comment by mholt** [comment]
Caddy works fine with modules, just be sure to follow the instructions in the readme. I'm not sure what this "goreleaser" binary is doing but I would try opening an issue there, as this isn't really a bug in Caddy or its repo.
