### ISSUE TITLE
systemd caddy.service cannot work in systemd version 219 due to #2620 changes

### ISSUE THREAD

**Issue by sqrthree** [caddyserver/caddy#2698]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy v1.0.1

## 2. What are you trying to do?

Configure systemd Service Unit for Caddy with https://github.com/caddyserver/caddy/blob/master/dist/init/linux-systemd/caddy.service

## 3. What is your Caddyfile?

It's irrelevant.

## 4. How did you run Caddy (give the full command and describe the execution environment)?

sudo systemctl start caddy.service

## 6. What did you expect to see?

Caddy works as expected.

## 7. What did you see instead (give full error messages and/or log)?

```
Aug 09 13:39:52 instance-h0u8070m systemd[1]: [/etc/systemd/system/caddy.service:41] Unknown lvalue 'ReadWritePaths' in section 'Service'
Aug 09 13:39:52 instance-h0u8070m systemd[1]: Started Caddy HTTP/2 web server.
Aug 09 13:39:52 instance-h0u8070m caddy[2146]: Activating privacy features... 2019/08/09 13:39:52 [INFO][cache:0xc0000a06e0] Started certificate maintenance routine
Aug 09 13:39:53 instance-h0u8070m caddy[2146]: Your sites will be served over HTTPS automatically using Let's Encrypt.
Aug 09 13:39:53 instance-h0u8070m caddy[2146]: By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
Aug 09 13:39:53 instance-h0u8070m caddy[2146]: https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Aug 09 13:39:53 instance-h0u8070m caddy[2146]: Please enter your email address to signify agreement and to be notified
Aug 09 13:39:53 instance-h0u8070m caddy[2146]: in case of issues. You can leave it blank, but we don't recommend it.
Aug 09 13:39:55 instance-h0u8070m caddy[2146]: Email address: 2019/08/09 13:39:55 [ERROR] Making new certificate manager: could not save user: mkdir /etc/ssl/caddy/acme: read-only file system (attempt 1/3)
Aug 09 13:39:55 instance-h0u8070m caddy[2146]: 2019/08/09 13:39:55 [ERROR] Making new certificate manager: registration error: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:  (attempt 2/3)
Aug 09 13:39:55 instance-h0u8070m systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE
Aug 09 13:39:55 instance-h0u8070m systemd[1]: Unit caddy.service entered failed state.
Aug 09 13:39:55 instance-h0u8070m systemd[1]: caddy.service failed.
```

## 8. Why is this a bug, and how do you think this should be fixed?

Changes in #2620 makes it unable to work with systemd version 219(CentOS Linux release 7.6.1810 (Core)). But [previous version](https://github.com/caddyserver/caddy/tree/f5720fecd663f521d832c1bca69e52ece43dc2b1/dist/init/linux-systemd) is fine. Maybe it should be noted in the document.

## 9. What are you doing to work around the problem in the meantime?

Use [previous version](https://github.com/caddyserver/caddy/tree/f5720fecd663f521d832c1bca69e52ece43dc2b1/dist/init/linux-systemd)

**Comment by mholt** [comment]
Hi, thanks for filing an issue. However, as the readme states, the init scripts and stuff are not something we/I maintain. Feel free to submit a PR to improve the documentation around this, if you like!

**Comment by GeonChen** [comment]
my error log same as sqrthree, i try to use previous version but didn't work fine, 
Until systemctl stop caddy, i got the key error info:
 `systemd[1]: [/etc/systemd/system/caddy.service:41] Unknown lvalue 'ReadWritePaths' in section 'Service'`. 
Changed `ReadWritePaths=/etc/ssl/caddy` to `ReadWriteDirectories=/etc/ssl/caddy` is work for my Centos7.4 system.
