### ISSUE TITLE
v2: reverse proxy: make health checks optional or change defaults

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2701]
## 1. What would you like to have changed?

Currently, Caddy 2's reverse proxy requires an endpoint to return a 200 status at "/", but not all backends respond at this path.

We should evaluate what the defaults are for the reverse proxy. Maybe no passive health checks by default? Only active ones by default? If there is a single backend only, health checks don't even make sense, right?

I propose:

- All active health checks disabled by default
- All implicit health checks (whether active or passive) are disabled if there's only 1 backend
- Passive health checks enabled by default if there is more than one backend

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

It'll make it easier to set up reverse proxies with Caddy 2. Caddy 1 does not have this requirement and it's more convenient that way.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Modify the backend to respond with 200 at "/".

## 4. Please link to any relevant issues, pull requests, or other discussions.

n/a

**Comment by francislavoie** [comment]
I think a health check for a single backend still makes sense as a confirmation that the config is correct on startup. I think we could emit a warning if the backend isn't reachable at startup. It would save a bit of time in debugging some things, I'd think.

**Comment by mholt** [comment]
@francislavoie That's fine, but it should be explicitly configured. There's no good way for the proxy to know what a proper health check is. For example, right now it assumes that "GET /" is a valid HTTP request, but we've seen several cases already where backends don't reply with a 200.

So health checks for a single backend are fine, but I think all passive health checks need to be explicitly configured.
