### ISSUE TITLE
Specify root certificate(s) to use for ACME

### ISSUE THREAD

**Issue by mmalone** [caddyserver/caddy#2702]
## 1. What would you like to have changed?

It's currently possible to tell Caddy to connect to a specific ACME server using the `tls.ca` directive, like this:

```
foo.internal {
  root /var/run/www
  tls {
    ca https://acme.internal/acme/directory
  }
}
```

but there doesn't appear to be any way to specify which root certificate(s) are trusted when Caddy connects to the specified server. I would like this to be configurable.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

This is useful if you're connecting to an ACME server whose certificate is not issued by a CA in your system's default trust store. This is likely to be the case for an internal ACME server that's connected to an internal CA (in which the ACME server's certificate is likely issued by the internal CA, not by a public CA). An internal CA is useful for internal service-to-service mTLS and in development & other pre-prod environments.

More specifically, I'm working on [an open source certificate authority](https://github.com/smallstep/certificates). We're adding ACME support and would like to support issuing internal certificates to Caddy. We ran into this issue during testing with Caddy.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

This is *only* necessary if the relevant root certificate is not already trusted by default (i.e., its certificate isn't in the default system trust store). For example, this isn't necessary for Let's Encrypt's staging server because that server uses a certificate issued by (non-staging) Let's Encrypt, which is trusted by default. However, an internal ACME server is likely to use a certificate issued by an internal CA. In that case, the internal CA's root certificate likely isn't in the system's trust store and won't be trusted by Caddy by default.

It's possible to work around this limitation by adding your internal root certificate to your system's default trust store. But this is a global operation: it affects most TLS communication on a machine. There are lots of situations where this is not desirable.

**Comment by mholt** [comment]
Thanks for the request! I think we can add this to Caddy 2 pretty easily. In fact, if I give you some pointers, would you like to contribute a PR? That'd probably be faster. 😅

Do you think trusting the custom root cert should be an operation specific only to ACME operations or all of Caddy's outbound requests (including? or excluding? reverse proxying)?

**Comment by mmalone** [comment]
Awesome. I'm a lot better at opening issues these days than I am at closing them, but I can take a look if you point me in the right direction. If I can't get to it someone else on our team might be able to.

> Do you think trusting the custom root cert should be an operation specific only to ACME operations or all of Caddy's outbound requests (including? or excluding? reverse proxying)?

Hard to answer in general. It depends on which use cases you want to support easily. For the most flexibility I think you want the root certificate to apply narrowly to ACME here. If I'm using caddy as an ingress proxy into a network segment it's not unlikely that the ACME certificate exposed outside the network segment will come from a different CA than certs used for mTLS within the network segment. That's basically what happens if you use HTTPS for your API with a cert from Let's Encrypt and use mTLS service-to-service with your own internal CA.

> PS. Are you using Caddy in smallstep? (That'd be super cool, and fitting...)

Not at the moment. All we're serving at the moment is a marketing website and we have our own super secret special-sauce proxy thing that we're dogfooding for that (don't think it's really competitive :). We might be in the market for something new soon. We often end up having weird quirky requirements though, since we're dealing with slightly different use cases. The next thing I'm testing on caddy is how it handles super short-lived certificates (e.g., expiring after 5 minutes). So stay tuned for an issue around that maybe... Also, I see that caddy can verify client certs, but can it use a client cert to speak mTLS to an upstream?

Do you have a slack or gitter or something? Might be better to ask some of these questions there. Or maybe I should start a thread on your community forum?

I'm writing a blog post about our ACME support and I'm explaining how to integrate with Caddy and a few other things. That's how all of this came up. Caddy is definitely the easiest to get started with, by the way. Good stuff.

> `LEGO_CA_CERTIFICATES`

After I posted this I learned about [the `LEGO_CA_CERTIFICATES` environment variable](https://github.com/go-acme/lego/blob/bc4b57accc090b9c61bde051c99fcb14e952f6e6/lego/client_config.go#L18-L28). This appears to work with caddy. But weirdly, only if I specify my email in the `tls` config or if I already have an ACME account in `~/.caddy/` from a previous run. There must be some code outside of `lego` that does the initial interactive setup that doesn't respect this environment variable.

In any case, I'm not sure an environment variable is the best interface to this functionality. Still, it does seem to be a viable workaround.

**Comment by mholt** [comment]
> For the most flexibility I think you want the root certificate to apply narrowly to ACME here. If I'm using caddy as an ingress proxy into a network segment it's not unlikely that the ACME certificate exposed outside the network segment will come from a different CA than certs used for mTLS within the network segment. That's basically what happens if you use HTTPS for your API with a cert from Let's Encrypt and use mTLS service-to-service with your own internal CA.

Okay, cool. Let's scope it to just ACME ops.

> I can take a look if you point me in the right direction. If I can't get to it someone else on our team might be able to.

Do you want to authorize a root CA by filename or the actual bytes (file contents) in your Caddy config? (We won't use an env variable; all of Caddy 2's config goes into a single JSON document.)

Either way, we should probably add a field in certmagic.Config, here: https://github.com/mholt/certmagic/blob/7b64d461c004b7083c582e8b832f748dea8041c5/config.go#L34 - which allows specifying an optional trust store.

As you've seen, lego uses an env var to configure its cert pool... so I guess we should call `os.Setenv()` accordingly (using `cfg.YourNewField`) before calling `lego.NewConfig()` here: https://github.com/mholt/certmagic/blob/7b64d461c004b7083c582e8b832f748dea8041c5/client.go#L129

Then we just expose that CA store configuration in Caddy here, in the ACMEManager: https://github.com/caddyserver/caddy/blob/4950ce485f7d931890fcfd2ee287b6df1b5db435/modules/caddytls/acmemanager.go#L45

It propagates down into certmagic lower in that file, here: https://github.com/caddyserver/caddy/blob/4950ce485f7d931890fcfd2ee287b6df1b5db435/modules/caddytls/acmemanager.go#L158

Hope this makes sense. There's some layers but it's better this way I think.

I've invited you to our Slack so you can have a tighter feedback loop during development. For everything else, feel free to use these issues or the [forum](https://caddy.community) for support-related questions.

> Not at the moment. All we're serving at the moment is a marketing website and we have our own super secret special-sauce proxy thing that we're dogfooding for that (don't think it's really competitive :). We might be in the market for something new soon. We often end up having weird quirky requirements though, since we're dealing with slightly different use cases.

Not really competitive, huh? We'll see. :) We have an ingress controller coming around the corner that's pretty awesome. What is the difference between your proxy and what Caddy does? (Again, not being spiteful or anything! I want to see how our products are related and see how they can be used together if nothing else.) When you're in the market for a web server, let's see how we can make Caddy (version 2, preferably) useful to you -- I'm all ears.

> The next thing I'm testing on caddy is how it handles super short-lived certificates (e.g., expiring after 5 minutes). So stay tuned for an issue around that maybe... Also, I see that caddy can verify client certs, but can it use a client cert to speak mTLS to an upstream?

Making the renewal ticker more frequent is an easy thing to expose in the configuration. I can get around to that very soon. Caddy still defaults to 12 hour checks because in practice most certs don't live less than 90 days, but we definitely want to support and encourage shorter-lived certificates.

**Comment by mholt** [comment]
Actually! We don't need to use `os.Setenv()`, we can probably access the HTTPClient directly and set its CertPool: https://github.com/go-acme/lego/blob/bc4b57accc090b9c61bde051c99fcb14e952f6e6/lego/client_config.go#L49

**Comment by mmalone** [comment]
> Do you want to authorize a root CA by filename or the actual bytes (file contents) in your Caddy config?

Filename is probably easier for folks.

> Caddy 2's config goes into a single JSON document

❤️

> Pointers

I'm following. Looks easy enough. I'll need to build and test with Caddy 2 first! :)

> Not really competitive, huh? We'll see. :)

HEH. We'll see, indeed! Srsly let's talk though.

> Making the renewal ticker more frequent ... Caddy still defaults to 12 hour checks

Oh well that answers one of my questions. 12 hour tick should at least *work* for our demo, since `step-ca` issues 24 hour certs by default. Ideally it'd be shorter though.

What we do as defaults with our renewal stuff on the command line, and what I think works well, is to base the renewal frequency off of the certificate lifetime. Our default is that we start attempting renewal after the certificate is 2/3 expired. So for a 24 hour cert, we'll try after 16 hours. For a 90 day cert, we'll try after 60 days. That seems to work pretty much always, for super long-lived & super short-lived certs, with no configuration required.

Ideally though you have a couple attempts before expiry, in case the CA has availability issues. So I'm curious: why not set the tick *way* shorter and just make it a no-op if the cert isn't about to expire (for some definition of "about to expire")?

> we can probably access the HTTPClient directly

@dopey made this, which I think demonstrates what we want to do: https://gist.github.com/mmalone/abce3c30df96972ed47f3298543be345

**Comment by mholt** [comment]
> What we do as defaults with our renewal stuff on the command line, and what I think works well, is to base the renewal frequency off of the certificate lifetime. Our default is that we start attempting renewal after the certificate is 2/3 expired. So for a 24 hour cert, we'll try after 16 hours. For a 90 day cert, we'll try after 60 days. That seems to work pretty much always, for super long-lived & super short-lived certs, with no configuration required.

Cool, Caddy essentially does the same thing: 90 day certs get renewed 30 days out. It's not yet dynamic based on cert lifetime but that's easy too; again, just not many use cases yet with shorter cert lifetimes. That'd be a change for CertMagic (and something to make configurable in Caddy, again, very easy).

> Ideally though you have a couple attempts before expiry, in case the CA has availability issues.

Yeah, again, this is why Caddy ticks every 12 hours and starts attempting renewal ~30 days out.

> So I'm curious: why not set the tick way shorter and just make it a no-op if the cert isn't about to expire (for some definition of "about to expire")?

That's what Caddy does already.

> @dopey made this, which I think demonstrates what we want to do: https://gist.github.com/mmalone/abce3c30df96972ed47f3298543be345

Yep, that looks exactly right -- and most of that scaffolding already exists in CertMagic/Caddy, so it should be literally just a matter of configuring/setting that one field, HTTPClient.

**Comment by mholt** [comment]
@mmalone On a related note, I've opened https://github.com/smallstep/certificates/issues/104 which might end up intersecting with this (but it's not blocking this).

**Comment by mholt** [comment]
@mmalone I've pushed a PR that adds this feature, #2756. Would you try it out?

You can specify the PEM files to trust in your Caddy config like so:

```
{
	"apps": {
		"tls": {
			"automation": {
				"policies": [
					{
						"management": {
							"module": "acme",
							"ca": "<SMALLSTEP CA HERE>",
							"trusted_roots_pem_files": ["/path/to/ca.crt"]
						}
					}
				]
			}
		},
		// ...
	}
}
```

We can expose this to the Caddyfile later, but for now go ahead and stand up a server with this config and let me know how it goes!
