### ISSUE TITLE
Cannot build from source, "unexpected module path" error on `go build`

### ISSUE THREAD

**Issue by kddlb** [caddyserver/caddy#2703]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0.2

## 2. What are you trying to do?

Trying to build Caddy from source fails due to an unexpected module path error during `go build`.

## 3. What is your Caddyfile?
Not applicable, but I'll paste the caddy.go file:

```go
package main

import (
        "github.com/mholt/caddy/caddy/caddymain"


        // plug in plugins here, for example:
        // _ "import/path/here"

        _ "github.com/nicolasazrak/caddy-cache"
        _ "github.com/jung-kurt/caddy-cgi"
        _ "github.com/epicagency/caddy-expires"
        _ "github.com/echocat/caddy-filter"
        _ "github.com/kodnaplakal/caddy-geoip"
        _ "github.com/pyed/ipfilter"
        _ "github.com/BTBurke/caddy-jwt"
        _ "github.com/simia-tech/caddy-locale"
        _ "github.com/tarent/loginsrv/caddy"
        _ "github.com/SchumacherFM/mailout"
        _ "github.com/xuqingfeng/caddy-rate-limit"
        _ "github.com/captncraig/caddy-realip"
)

func main() {
        // optional: disable telemetry
        // caddymain.EnableTelemetry = false
        caddymain.Run()
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

Not applicable.

## 5. Please paste any relevant HTTP request(s) here.

Not applicable.

## 6. What did you expect to see?

Not applicable.

## 7. What did you see instead (give full error messages and/or log)?

```
$ go build
go: finding github.com/captncraig/caddy-realip latest
go: finding github.com/tarent/loginsrv/caddy latest
go: finding github.com/mholt/caddy/caddy/caddymain latest
go: finding github.com/mholt/caddy/caddy latest
go: finding github.com/kodnaplakal/caddy-geoip latest
go: finding github.com/simia-tech/caddy-locale latest
go: github.com/mholt/caddy@v1.0.2: parsing go.mod: unexpected module path "github.com/caddyserver/caddy"
go: error loading module requirements
```

**Comment by gamalan** [comment]
You should remove `github.com/mholt/caddy@v1.0.2` from your go.mod and replace it to `github.com/caddyserver/caddy@v1.0.2`. The caddy in the import line also should be changed. After you change it, it should be fine.

**Comment by mholt** [comment]
Yep, that's probably it, thanks @gamalan !
