### ISSUE TITLE
Single command to migrate TLS data

### ISSUE THREAD

**Issue by gamalan** [caddyserver/caddy#2705]
## 1. What would you like to have added?

The ability to migrate TLS data from one storage type to another storage type. Example: migrating from `file` to `consul`/`redis`.
But because this process only running one time(most probably), after the process is running completely, it should close the process.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

So we can use the existing certificates when changing to other storage.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

No known alternative, and as far I can see in the docs, this feature is also not provided.

How to do it:
1. Instantiate both `to` and from `storage`
2. List all available keys using wildcard prefix (*) in the `from` storage interface
3. Get all data
4. Store in `to` storage interface

Others option:
Separate the migrate command as other package/plugin.(?)

## 4. Please link to any relevant issues, pull requests, or other discussions.

After making plugin for tls cluster storage which I post to https://caddy.community/t/new-plugin-redis-storage-for-caddy-tls-data/6090/4 I think it will be nice to have this feature to help others migrate their existing certificate.

**Comment by mholt** [comment]
Hm, that may indeed be a nice feature, but I think it falls outside the scope of what the web server's role is. It's also just a one-time thing, and would only be used by a few users I think. Maybe a separate command/utility to do this?

Will close the issue but feel free to continue the discussion, especially if any tool is written to do this!

**Comment by gamalan** [comment]
True, but to implement it as a different command, the storage interface might need an additional interface to get all current data as key-value pair, or at least a standard in List function to get all keys. 

Does the FileStorage in https://github.com/mholt/certmagic/blob/master/filestorage.go when the prefix is empty string or "*" will return all keys?

**Comment by mholt** [comment]
> True, but to implement it as a different command, the storage interface might need an additional interface to get all current data as key-value pair, or at least a standard in List function to get all keys.

I think that's irrespective of the command that is running it; see next part of my post.

> Does the FileStorage in https://github.com/mholt/certmagic/blob/master/filestorage.go when the prefix is empty string or "*" will return all keys?

The godoc for `List()` says:
```go
    // List returns all keys that match prefix.
    // If recursive is true, non-terminal keys
    // will be enumerated (i.e. "directories"
    // should be walked); otherwise, only keys
    // prefixed exactly by prefix will be listed.
```

**Comment by gamalan** [comment]
I see, I think it should work like that. I'll try to make the command later.

**Comment by mholt** [comment]
Cool, keep me posted!

**Comment by masipcat** [comment]
Last week I needed this and I ended writing this app: https://github.com/masipcat/caddy-storage-migrator. Right now only supports the redis storage but the other implementations should work as well. Any feedback will be appreciated!
