### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by sjatsh** [caddyserver/caddy#2708]
![image](https://user-images.githubusercontent.com/16359798/63033254-e62ee080-bee9-11e9-8e03-33ee33ffa68f.png)
![image](https://user-images.githubusercontent.com/16359798/63033278-f2b33900-bee9-11e9-9321-5433004d3400.png)

**Comment by mholt** [comment]
Those errors just mean that the client is closing (or technically, resetting) the connection; don't think it has anything to do with your DNS challenge configuration.
