### ISSUE TITLE
Ability to set request IDs to nonstandard UUIDs.

### ISSUE THREAD

**Issue by LogalDeveloper** [caddyserver/caddy#2709]
## 1. What would you like to have changed?
The request ID middleware should be able to use nonstandard UUIDs when getting request IDs from an existing header.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
The request ID middleware requires a valid UUID to be used when reusing request IDs from an existing header. The problem with this is that not all services use UUIDs for request IDs. A good example of this is Cloudflare, which instead uses what they call Ray IDs.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Logging the request ID header value directly instead of using the `{request_id}` placeholder since the request ID middleware rejects the header values.

## 4. Please link to any relevant issues, pull requests, or other discussions.
["Adding the CF-RAY header to your logs"](https://support.cloudflare.com/hc/en-us/articles/200169746-Adding-the-CF-RAY-header-to-your-logs) - A document from Cloudflare that contains a little information about the `CF-RAY` header.
[The code.](https://github.com/caddyserver/caddy/blob/master/caddyhttp/requestid/requestid.go#L39-L43) - This is the code that rejects any existing request ID value from the configured header when it is not a valid UUID.

**Comment by tobya** [comment]
Could you outline a scenario where you would do this?  Please include the mock caddyfile and an outline of the flow

**Comment by LogalDeveloper** [comment]
```
https://cloudflare.protected.example.com {
    tls /path/to/origin-cert.pem /path/to/origin-key.key {
        clients /path/to/cloudflare-origin-ca.pem
    }

    fastcgi / /path/to/fastcgi.sock php {
        env REQUEST_ID {request_id}
    }

    request_id CF-RAY

    log / /path/to/log.log "[{request_id}] [{when}] <whatever other info you want> . . ."
}
```

In this Caddyfile example, I am using the `request_id` directive exactly as documented: it accepts a header name and it will read request IDs from there instead of generating new ones. The limitation, however, is that the values of the header must be a valid UUID. In the case of Cloudflare Ray IDs, that is never the case, so it instead generates new UUIDs and logs `INFO` errors.

Because of this, I would need to update my usages of `{request_id}` to `{>CF-RAY}`. In this feature request, I am requesting that the valid UUID requirement be removed or changed so that I can use the `{request_id}` placeholder with request IDs from services that don't use UUIDs. It also has the added benefit in the case the header name changes: only a single change of the `request_id` directive's argument is needed instead of a bunch of changes to individual references to the header name.

**Comment by tobya** [comment]
Thank you for the issue.  I'll mark it as a feature request but since there is a very simple work around `{>CF-RAY}` I think it will not be high priority.  If anyone else is interested in this issue perhaps they could +1 here.  

If anyone would like to submit a PR they are always welcome.

**Comment by mholt** [comment]
Caddy 2 / Enterprise will take care of this, no problem.

**Comment by francislavoie** [comment]
Caddy v1 is no longer actively maintained. Caddy v2 didn't inherit the `request_id` directive from Caddy v1, but it is available as a plugin: https://github.com/lolPants/caddy-requestid

If you still need this feature, I recommend asking for it on that project.
