### ISSUE TITLE
Can't rewrite "not"

### ISSUE THREAD

**Issue by AndreKR** [caddyserver/caddy#2713]
This isn't exactly a critical bug, but it's an inconsistency and easy to fix (add a length check [here](https://github.com/caddyserver/caddy/blob/bff2469d9d76ba5924f6d9affcf60bf44dcfa06c/caddyhttp/rewrite/setup.go#L115) or extend the `switch`).

Caddy version bff2469d

Caddyfile:
```text

localhost:80 localhost.local:80
root C:\htdocs
errors stderr
rewrite bar foo.html
rewrite not foo.html
```

Expected result:  
Both http://localhost/bar and http://localhost/not show the contents of foo.html.

Actual result:
http://localhost/bar shows the contents of foo.html, but http://localhost/not shows `404 Not Found`.

**Comment by mholt** [comment]
Shouldn't it be `rewrite /not`?

**Comment by AndreKR** [comment]
It's just a regex, it would still match... the `bar` rewrites matches.

**Comment by mholt** [comment]
I see... yes, I suppose the regex cannot be exactly "not" in this case. Is this an actual use case you've encountered that is hindering your site?

FWIW, in Caddy 2 this is not a problem...
