### ISSUE TITLE
HTTP/2 Denial of Service Advisory

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#2714]
Hi.

Have anyone seen this and maybe have some information about it if caddyserver is vulnerable against this attacks?

https://github.com/Netflix/security-bulletins/blob/master/advisories/third-party/2019-002.md

On HN are also some Info's available.

https://news.ycombinator.com/item?id=20688178

Looks like there is a issue in golang about this topic https://github.com/golang/go/issues/33631

**Comment by Henrocker** [comment]
Please see: https://github.com/caddyserver/caddy/blob/master/dist/CHANGES.txt

Use released precompiled binaries from v1.0.2 or compile source from go-1.12.8 onwards.

**Comment by git001** [comment]
thanks
