### ISSUE TITLE
error loading module requirements

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [caddyserver/caddy#2716]
I followed the instructions for building caddy:

1. `export GO111MODULE=on`
2. `mkdir caddy`
3. `cd caddy`
4. create `.go` file:
```go
package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"
	
	// plug in plugins here, for example:
	// _ "import/path/here"
)

func main() {
	// optional: disable telemetry
	// caddymain.EnableTelemetry = false
	caddymain.Run()
}
```
5. `go mod init caddy`
6. `go get github.com/caddyserver/caddy`
7. `go build`

This is the result:

```
go: finding github.com/mholt/caddy/caddy/caddymain latest
go: finding github.com/mholt/caddy/caddy latest
go: github.com/mholt/caddy@v1.0.3: parsing go.mod: unexpected module path "github.com/caddyserver/caddy"
go: error loading module requirements
```

Arch Linux, `go version go1.12.8 linux/amd64`

**Comment by brownjohnf** [comment]
I just successfully followed these same steps in an alpine linux Docker image. What is your `.go` file named? It should have a name like `main.go`, not just `.go`. That's the only thing I see different about what you're doing. The directory should also not be in the caddy source tree. Not sure where you've created it.

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
> I just successfully followed these same steps in an alpine linux Docker image. What is your `.go` file named? It should have a name like `main.go`, not just `.go`. That's the only thing I see different about what you're doing. The directory should also not be in the caddy source tree. Not sure where you've created it.

Oh my god, that was exactly it. I guess I didn't read carefully enough. Thanks. I'm not familiar with go so I thought `.go` was the standard config file name or something.

**Comment by mholt** [comment]
Ah, wow. Glad you figured that out. :)

The docs say (emphasis added):

> create a Go file (_**extension**_ .go)

Sorry if that wasn't clear. It's a file extension, not a file name.
