### ISSUE TITLE
Incorrect Zone parsing in the Caddyfile

### ISSUE THREAD

**Issue by jgsqware** [caddyserver/caddy#2719]
## 1. Which version of Caddy are you using (`caddy -version`)?
Latest

## 2. What are you trying to do?

Hello, when in my Corefile, I have a server block no space between the end of the name and the `{`, the server block is wrongly interpreted.

## 3. What is your Caddyfile?

Corefile who is working:
```
www.mydomain.com:1053 {
  cache 30
  forward . 8.8.8.8
}
```

CoreDNS logs:

```
# /coredns -conf ./c/Corefile
www.mydomain.com.:1053
2019-08-21T10:44:02.806Z [INFO] plugin/reload: Running configuration MD5 = 6740acee942add7a7ad7a726502e6ab4
2019-08-21T10:44:02.806Z [INFO] CoreDNS-1.6.2
2019-08-21T10:44:02.806Z [INFO] linux/amd64, go1.12.7, 25632d6a
CoreDNS-1.6.2
linux/amd64, go1.12.7, 25632d6a
^C[INFO] SIGINT: Shutting down
```

Corefile who's not working:
```
www.mydomain.com:1053{
  cache 30
  forward . 8.8.8.8
}
```

CoreDNS logs:

```
# /coredns -conf ./c/Corefile
www.mydomain.com:1053{.:53
2019-08-21T10:44:02.806Z [INFO] plugin/reload: Running configuration MD5 = 6740acee942add7a7ad7a726502e6ab4
2019-08-21T10:44:02.806Z [INFO] CoreDNS-1.6.2
2019-08-21T10:44:02.806Z [INFO] linux/amd64, go1.12.7, 25632d6a
CoreDNS-1.6.2
linux/amd64, go1.12.7, 25632d6a
^C[INFO] SIGINT: Shutting down
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
It use CoreDNS. But related to Caddyfile Parser

## 6. What did you expect to see?
If i use block separator `{` at the end of a line, I would expect a space before the zone, if not I would raise a parsing error.

## 7. What did you see instead (give full error messages and/or log)?

Corefile:
```
www.mydomain.com:1053{
  cache 30
  forward . 8.8.8.8
}
```

CoreDNS logs:

```
# /coredns -conf ./c/Corefile
www.mydomain.com:1053{.:53
2019-08-21T10:44:02.806Z [INFO] plugin/reload: Running configuration MD5 = 6740acee942add7a7ad7a726502e6ab4
2019-08-21T10:44:02.806Z [INFO] CoreDNS-1.6.2
2019-08-21T10:44:02.806Z [INFO] linux/amd64, go1.12.7, 25632d6a
CoreDNS-1.6.2
linux/amd64, go1.12.7, 25632d6a
^C[INFO] SIGINT: Shutting down
```

## 8. Why is this a bug, and how do you think this should be fixed?
The problem is without the space before the `{`, the zone token is parsed incorrectly and then the full Corefile is wrongly parsed

## 10. Please link to any related issues, pull requests, and/or discussion.

https://github.com/coredns/coredns/issues/3164

https://github.com/coredns/coredns/pull/3165#issuecomment-523534407

**Comment by jgsqware** [comment]
I wonder if the lexer, parser or dispender should handled this?

as Lexer parse only on white space, for me it's not the right, or you think a token cannot end by a `{` and then the lexer would fail

**Comment by mholt** [comment]
One possible solution is for `caddy fmt` to automatically separate out any `{`s trailing at the end of a token into its own token.

Anyway... closed due to inactivity.
