### ISSUE TITLE
Configurable delay before SIGTERM is processed.

### ISSUE THREAD

**Issue by yannh** [caddyserver/caddy#2729]
Hello!

When running Caddy-based software within Kubernetes, one hit the "SIGTERM / Kube-proxy" race condition - that is, the server will continue getting requests for some short amount of time *after* receiving SIGTERM. 

This is described in several blog posts / Github issues, such as:
 * https://opensource.zalando.com/skipper/kubernetes/ingress-backends/
 * https://stackoverflow.com/questions/40545581/do-kubernetes-pods-still-receive-requests-after-receiving-sigterm
 * https://hackernoon.com/graceful-shutdown-in-kubernetes-435b98794461

A common work-around is to add a preStop lifecycle hook that would delay SIGTERM from reaching the application. This is difficult when the application that is using Caddy however, is using a "Scratch" container, that does not ship sleep (such as CoreDNS).

I am proposing to add a configurable delay between the moment Caddy receives SIGTERM, and the moment Caddy processes it. This would default to 0, so people not setting this would be not affected - but this could be set to a number of seconds when run in Kubernetes, hopefully working around the issue.

Would you accept such a patch? Thanks!

**Comment by mholt** [comment]
Hmm, I don't think Caddy should arbitrarily wait before responding to a command. I think this should be fixed in Kubernetes.
