### ISSUE TITLE
Caddy seems to leak memory after SIGUSR1

### ISSUE THREAD

**Issue by lukenowak** [caddyserver/caddy#2734]
## 1. Which version of Caddy are you using (`caddy -version`)?
```
caddy -version
Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)
```

## 2. What are you trying to do?

I am serving a lot of hosts with often sending `SIGUSR1` to Caddy in order to reload configuration

## 3. What is your Caddyfile?

My Caddyfile is quite massive (174501 lines), here are extracts which repeats.
```text

# below repeats ~2600 times
https://[fd46::8587]:4443/_<endpoint-A>, https://10.0.0.90:4443/_<endpoint-A> {
  bind 10.0.0.90
  root /my/root
  browse
  tls fd46::8587-10.0.0.90.crt fd46::8587-10.0.0.90.crt
  basicauth "_<user-A>" <password> {
    "Log Access _<user-A>"
    /
  }
  log / frontend-access.log "{remote} - {>REMOTE_USER} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\" {latency_ms}" {
    rotate_size 0
  }
  errors frontend-error.log {
    rotate_size 0
    * notfound.html
  }
}

# below repeats 2600 times
https://hostN:4443 {
  bind 10.0.0.90
  tls certN.pem certN.pem {
    # Allow HTTP2
    alpn h2 http/1.1
  }
  log / N_access_log "{remote} - {>REMOTE_USER} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\" {latency_ms}" {
    rotate_size 0
  }

  errors N_error_log {
    rotate_size 0
  }

  rewrite {
    regexp (.*)
    to {1}
  }

  # Default configuration
  # Default proxy configuration
  proxy / https://[::1]:2101 {
    try_duration 30s
    try_interval 250ms
    transparent
    timeout 600s
    insecure_skip_verify
  }
}

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
I am using a shell script which is run by supervisord:
```shell
#!/bin/sh
export CADDYPATH=var/frontend_cluster
exec $1 \
        -conf etc//Caddyfile \
        -log var//log/frontend-error.log \
        -log-roll-mb 0 -http2=true -grace 5s -disable-http-challenge \
        -disable-tls-alpn-challenge \
        -pidfile var//run/httpd.pid
```

## 6. What did you expect to see?

I expect to not see rss memory increase of Caddy process after each SIGUSR1.

## 7. What did you see instead (give full error messages and/or log)?

Each time after I send SIGUSR1 to Caddy it increases in rss, according to `ps -p `cat ~slapuser2/var/run/httpd.pid` -o pid= -o rss= | sed 's/ /;/g'`:
```
2019-08-30 09:56:30;18905;387012 # just started
2019-08-30 09:56:52;18905;656724 # just after SIGUSR1 sent
2019-08-30 09:56:54;18905;794736
2019-08-30 09:56:58;18905;815172
# time passes, small amount of requests happens
2019-08-30 09:58:57;18905;815952
2019-08-30 09:58:59;18905;816408
2019-08-30 10:10:43;18905;897972 # again SIGUSR1 sent
2019-08-30 10:13:00;18905;905300
2019-08-30 10:13:39;18905;906016
2019-08-30 10:14:13;18905;906016
```

What you can see above that rss memory consumption stays stable, but after each SIGUSR1 it increases and does not drop down.

## 8. Why is this a bug, and how do you think this should be fixed?

Caddy shall not consume more memory on ecah SIGUSR1, as it results in its filling the memory and hanging the server or bing OOM-killed.

## 9. What are you doing to work around the problem in the meantime?

OOM kills caddy, and in short time our system starts it back automatically. The period is quite short, so users do not complain.

## 10. Please link to any related issues, pull requests, and/or discussion.

This issue happened since we started to use Caddy v0.11.5 in May 2019, it got under our radar because of the workaround.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

We use Caddy for everyday operations in massive hosting scenarios, and it's great, thank you :)

**Comment by lukenowak** [comment]
One more thing.

The system is running with `-quic`, I forgot to add this info here.

**Comment by mholt** [comment]
Thanks for the detailed report!

This is actually a known issue: https://github.com/caddyserver/caddy/issues/2466

It's a tricky one to fix, and I haven't narrowed down exactly what is causing it... and my development effort is focused on Caddy 2 for now.

The good news is that Caddy 2 doesn't have this problem. I was very careful to minimize the possibility of leaks in Caddy 2. I have put it through the wringer with regards to config reloads and can't find any leaks (so far). I'll try to keep doing that profiling each time I make significant changes.

**Comment by lukenowak** [comment]
> This is actually a known issue: #2466

Oh! Somehow I missed that issue while reporting this. Thanks for marking duplicate.
