### ISSUE TITLE
Config adapters for JSON-C and JSON-5

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2735]
## 1. What would you like to have changed?

We might as well make it possible for people to use JSON with Comments (JSON-C) or [JSON 5](https://json5.org) to configure Caddy, since they can be easily translated to standard JSON.

Config adapter names could be: `jsonc` and `json5`.

Like other config adapters, these can be used to POST config to Caddy's API.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

This would make writing and maintaining Caddy configs much easier to do by hand.

It should only take a few minutes to implement, which is good when I find myself with a spare hour but no more.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

None really; if you want to comment your Caddy JSON config you're kinda toast.

## 4. Please link to any relevant issues, pull requests, or other discussions.

Libs we could use:

- https://github.com/muhammadmuzzammil1998/jsonc
- https://github.com/json5/json5-go (maybe more updated here: https://github.com/ilibs/json5)

**Comment by mholt** [comment]
Added in 8e821b5.

**Comment by muhammadmuzzammil1998** [comment]
Thank you Matt 😊
