### ISSUE TITLE
Clearer manual TLS / reverse proxy docs

### ISSUE THREAD

**Issue by lmeyerov** [caddyserver/caddy#2738]
## 1. What would you like to have changed?

Typical big company use of Caddy is pretty undocumented: How top setup manual certs, reverse proxy, and test with static file serving. We ended up walking some users (for the Docker mode) and documenting https://github.com/graphistry/graphistry-cli/blob/master/docs/configure.md#setup-custom-certs . But we had to do quite a bit of Googling and experimenting for that config, and would love to see this in the main repo.

Some particular stumbling blocks we hit:

* FQDN with port on first line was important for triggering specific config happy paths
* Precise syntax for specify certs, and at a specific path
* The actual reverse proxy, including for web sockets
* How to test & debug various configs, e.g., a static file server

So, for the examples repo, consider reusing the above for:

* Manual TLS, including the comment on gotchas
* Reverse proxy with some common options, e.g., websockets
* I bet a couple more of 80% case examples will pop out when considered by the more experienced folks here

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

Bigco admins are already in a tricky boat, and not necessarily in a position to go far with Caddy, so every of docs bit helps. 

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

We Googled, experimented, and wrote our own docs.

**Comment by mholt** [comment]
Hi @lmeyerov - thanks for the feedback about documentation. Can you help me understand which examples specifically are missing from these pages that you would find useful:

> Reverse proxy with some common options, e.g., websockets
- https://caddyserver.com/docs/proxy#examples

> Precise syntax for specify certs, and at a specific path
- https://caddyserver.com/docs/tls#examples

> How to test & debug various configs, e.g., a static file server
- https://caddyserver.com/docs/root & https://caddyserver.com/docs/browse

Looking through your own linked docs, it seems we've covered them all in our own as well. If we know the specifics of what is still lacking, we can improve on them better.

In any case, I think it's great that you took the time to learn how the software works, rather than just copying+pasting examples like a lot of people do, so, kudos.

**Comment by lmeyerov** [comment]
RE:TLS - it seems that either "https" or ":443" must be explicitly set in the enclosing context. I think that was intentional for some reason so not considered a bug (differentiate between auto vs manual?), but that meant the TLS docs would benefit from more explicitly calling out the gotcha. Or maybe there is a bug report here.

RE:Static server, similar to ^^^, unclear if that's the entire file or not, and would probably help as an encapsulated package in https://github.com/caddyserver/examples . 

Hope that helps!

**Comment by mholt** [comment]
@lmeyerov Neither `https://` nor `:443` need to be specified per-se (unless you have a "catch-all" site, which is serving all hosts on a particular port); this is described at https://caddyserver.com/docs/automatic-https.

> RE:Static server, similar to ^^^, unclear if that's the entire file or not,

I'm not sure what you mean by "the entire file or not". 

Anyway, feel free to submit an example to that examples repo if you think one is missing!

**Comment by lmeyerov** [comment]
The user-reported scenario was that they had to switch from

```
your.site.ngo {
  tls /root/.caddy/my.crt /root/.caddy/my.key
  proxy / nginx:80 {
    websocket
  }
}```

=>

```
https://your.site.ngo:443 {
  tls /root/.caddy/my.crt /root/.caddy/my.key
  proxy / nginx:80 {
    websocket
  }
}
```

I can check with them in a few weeks to-reconfirm this. It sounds like you believe the former should work.

RE:Static server, clicking around the website and examples did not reveal obvious hits for "static file server". Maybe two things, especially from the perspective of searchability:

1. In the github, add an explicit example with a discoverable folder name like "static_file_server":
*Caddyfile*
```
site.com {
    root static_files/
}
```
*/static_files*
`/static_files/index.html`

2. Somewhere on the docs menu or tutorial menu, call out that example. Less critical because someone already fills this docs gap from an SEO perspective ("caddy static file server" => https://www.baty.net/2018/using-caddy-for-serving-static-content/ ).  

I'm not sure if there's more to the "getting started". Already knowing to search for directive `root` definitely assumes too much for wanting to learn how to do a static file server. There may be other similar onboarding tasks that should also be more discoverable -- helping the users debug their TLS issues took longer than I'd hope.

**Comment by mholt** [comment]
> It sounds like you believe the former should work.

This is altered by automatic HTTPS logic: https://caddyserver.com/docs/automatic-https. If you provide your own certificates, automatic HTTPS is switched off because you're taking control of HTTPS. So the ports aren't changed for you.

**Comment by lmeyerov** [comment]
Great -- so then if using the TLS directive disables `:443` being auto-handled , for the 99% case, the TLS directive docs ought to guide users. The examples section of that page does not show the typical case, and I didn't see a clearly called out section spelling out how to do the typical case here.

**Comment by lmeyerov** [comment]
Ex, adding to `Examples`, and most likely, **as the first one**:



Serve a site with HTTPS on port 443 and manually specified certificates:

```
site.com:443 {
    tls ./folder/x.crt ./folder/x.pem
}
```

**Comment by mholt** [comment]
Okay, yeah. I can see how mentioning that in the docs for the tls directive would be useful. I will try to do that next time I update the docs!

**Comment by TheChilliPL** [comment]
> Hi @lmeyerov - thanks for the feedback about documentation. Can you help me understand which examples specifically are missing from these pages that you would find useful:
> 
> > Reverse proxy with some common options, e.g., websockets
> 
> * https://caddyserver.com/docs/proxy#examples
> 
> > Precise syntax for specify certs, and at a specific path
> 
> * https://caddyserver.com/docs/tls#examples
> 
> > How to test & debug various configs, e.g., a static file server
> 
> * https://caddyserver.com/docs/root & https://caddyserver.com/docs/browse
> 
> Looking through your own linked docs, it seems we've covered them all in our own already. If we know the specifics of what is still lacking, we can improve on them better.
> 
> In any case, I think it's great that you took the time to learn how the software works, rather than just copying+pasting examples like a lot of people do, so, kudos.

All of these links give HTTP 500, Internal Server Error

**Comment by mholt** [comment]
This issue is very old, and those links are for caddy v1 which is no longer supported.
