### ISSUE TITLE
Caddy not responding to requests

### ISSUE THREAD

**Issue by Cyan101** [caddyserver/caddy#2739]
## 1. Which version of Caddy are you using (`caddy -version`)?
1.0.3

## 2. What are you trying to do?
I have a domain `cyan101.stream` pointed at my home IP, I have a local media server running on port 8096.
I'm attempting to have any http/https requests to cyan101.stream to be directed to my local media server.

This was working for the last few weeks, I'm on windows 1903 (updated a few days ago) still worked even after updating windows but this morning it has stopped.

I've run my local media server on port 80 and it works fine (so my port forwarding is working) but when caddy is open on port 80 is does nothing and I get no logs.

## 3. What is your Caddyfile?
```
https://cyan101.stream {
  tls crazyandroid101@gmail.com
  log access.log
  proxy / localhost:8096 {
    websocket
  }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
I run caddy in a simple bat script
```
START /B G:\Programs\Jellyfin\Caddy\caddy.exe -conf "G:\Programs\Jellyfin\Caddy\Caddyfile" -log access.log
START /B G:\Programs\Jellyfin\jellyfin.exe
```

## 6. What did you expect to see?
Caddy should listen on the port (windows says it is using the port) but it doesnt do anything or give any logs when trying to contact the port via browser

## 7. What did you see instead (give full error messages and/or log)?
No errors, nothing in logs, browser says failed to receive a response
"cyan101.stream took too long to respond." is the error from the browser

## Bonus: What do you use Caddy for? Why did you choose Caddy?
SSL Certification and https for my url

**Comment by Cyan101** [comment]
I tried making a static browser with it (with 10.10.10.10 being my actual IP) in a seperate caddy file
```
http://10.10.10.10, http://cyan101.stream {
  root G:\Files\Downloads
  gzip
  browse
}
```

I'm assuming something like this should allow me to browse my files, but when trying to I don't get anything just like with my main caddyfile. My terminal output seems correct but I just dont think caddy is actually doing anything?

**Comment by francislavoie** [comment]
Check your windows firewall? The rules may have been reset with a windows update for whatever reason.

**Comment by Cyan101** [comment]
> Check your windows firewall? The rules may have been reset with a windows update for whatever reason. There might be a rule blocking caddy.exe or just lacking a rule to allow caddy.exe

I... I don't even know how this got past me....

Does windows randomly reset its firewall rules now and then? I did update to 1903 but my computer has been turned on/off at least 5+ times and have had caddy/jellyfin working every time.
