### ISSUE TITLE
v2: Add configurable (auto)-adding of trailing slash for directories in path

### ISSUE THREAD

**Issue by Henrocker** [caddyserver/caddy#2741]
## 1. What would you like to have changed?
Since I enjoy the behaviour of Caddy v1 rewriting the url when accessing a directory in the webpath, I really like Caddy v2 to be able to do this, too. It would be awesome to have this configurable for when a webapp breaks.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
This makes configuration of Caddy v2 easier for users that would otherwise need to add specific rewrite rules. Making this a configurable option, one could turn on or off the automatic rewrite if issues appear using a specific app. 

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Caddy v1 automatically adds a trailing slash to the request in case the path is a directory. This should be the most common behaviour for most apps, users and setups. 

## 4. Please link to any relevant issues, pull requests, or other discussions.
https://github.com/caddyserver/caddy/pull/2737#issuecomment-529115073 and https://github.com/caddyserver/caddy/pull/2737#issuecomment-529141600

**Comment by mholt** [comment]
@Henrocker I've pushed this to the `v2` branch; URL canonicalization is enabled by default but it can be disabled in the file server. I've also updated the docs in the wiki. Thanks!
