### ISSUE TITLE
Android/iOS App request Error=1200

### ISSUE THREAD

**Issue by Ansen** [caddyserver/caddy#2742]
## 1. Which version of Caddy are you using (`caddy -version`)?

v1.0.3 `b869b4574c47ecab42a24e86778373a0`

## 3. What is your Caddyfile?
```text
www.exmple.com {
    gzip
    log /var/log/caddy/www.log
    proxy / http://127.0.0.1:8080 {
        transparent
    }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

> CentOS Linux release 7.6.1810 (Core)
> Linux xxx 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```bash
/usr/local/bin/caddy -log stdout -agree=true -email xxx@exmple.com -conf=/etc/caddy/Caddyfile -root=/var/tmp
```

## 7. What did you see instead (give full error messages and/or log)?

In Android App https request error:
```java
javax.net.ssl.SSLHandshakeException: Chain validation failed
```
![image](https://user-images.githubusercontent.com/676412/64531566-6b1ee580-d342-11e9-8bcb-85b250cf4c38.png)

## 8. Why is this a bug, and how do you think this should be fixed?

use: lets-encrypt-x3-cross-signed.pem
do not use : lets-encrypt-x1-cross-signed.pem

## 9. What are you doing to work around the problem in the meantime?

I manually generated the certificate with lets-encrypt-x3-cross-signed.pem:

`https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem`

**Comment by Ansen** [comment]
I created a hello world Android project, the connection could not be established.
Log image:
![image](https://user-images.githubusercontent.com/676412/64533214-96570400-d345-11e9-8fec-5189eda1333b.png)

**Comment by francislavoie** [comment]
Which android version are you using?

**Comment by Ansen** [comment]
> Which android version are you using? Which phone?

` MIUI 10.3.6.0(PEACNXM)`
`Android Version: 9`

**Comment by mholt** [comment]
Not really enough information to ascertain this as a bug in Caddy; looks more of an Android/Java issue.
