### ISSUE TITLE
header_upstream Host {host} cause "Domain not configured" error

### ISSUE THREAD

**Issue by CristianCantoro** [caddyserver/caddy#2745]
## 1. Which version of Caddy are you using (`caddy -version`)?

`Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)`

## 2. What are you trying to do?

Proxy many Wikipedia [en.wikipedia.org](https://en.wikipedia.org), [en.m.wikipedia.org](https://en.m.wikipedia.org), etc. See the project: [wikiproxy](https://github.com/CristianCantoro/wikiproxy),

## 3. What is your Caddyfile?

```text
*.vikiansiklopedi.org {
    tls {
        dns ovh
    }
}

vikiansiklopedi.org {
    redir {
        / https://github.com/CristianCantoro/wikiproxy 303
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile
}


en.vikiansiklopedi.org {
    tls {
        wildcard
    }
    redir {
        if {uri} is /
        /wiki/${main_page}
    }


    proxy / https://${lang}.wikipedia.org {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Port {server_port}
        header_upstream X-Forwarded-Proto {scheme}

        header_downstream Location en.wikipedia.org en.vikiansiklopedi.org
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile

}

en.m.vikiansiklopedi.org {
    tls {
        wildcard
    }
    redir {
        if {uri} is /
        /wiki/${main_page}
    }

    proxy / https://${lang}.m.wikipedia.org {
        header_upstream Host {host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Port {server_port}
        header_upstream X-Forwarded-Proto {scheme}

        header_downstream Location en.m.wikipedia.org en.m.vikiansiklopedi.org
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile
}

[304 more languages]
```

Note that I am sure that the offending line is
```
header_upstream Host {host}
```
without that everything works as expected. I have the same problem if I use the `transparent` shortcut (which includes the directive above).

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```bash
$ ./caddy -conf ./Caddyfile -validate
Caddyfile is valid
```

```bash
$ sudo -E ./caddy -log stdout -agree=true -conf=./Caddyfile -root=/var/tmp
```

## 5. Please paste any relevant HTTP request(s) here.

Request any page, e. g. https://en.vikiansiklopedi.org/wiki/Main_Page

## 6. What did you expect to see?

The actual proxies Wikipedia page, i.e. the content of https://en.wikipedia.org/wiki/Main_Page

## 7. What did you see instead (give full error messages and/or log)?

```text
Domain not configured

This domain points to a Wikimedia Foundation server,
but is not configured on this server.
```

![screenshot](https://user-images.githubusercontent.com/367272/64790884-1d3ef300-d577-11e9-846c-c75873f332f8.png)

No errors were reported on Caddy's side.

## 8. Why is this a bug, and how do you think this should be fixed?

To be fait, I am not sure this is a Caddy bug, a Wikimedia bug, or a legitimate configuration choice.

## 9. What are you doing to work around the problem in the meantime?

I am using the following directive:
```text
header_upstream Host {>Host}
```
I was not able to find any documentation explaining the difference between `{host}` and `{>Host}`

```text
*.vikiansiklopedi.org {
    tls {
        dns ovh
    }
}

vikiansiklopedi.org {
    redir {
        / https://github.com/CristianCantoro/wikiproxy 303
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile
}


en.vikiansiklopedi.org {
    tls {
        wildcard
    }
    redir {
        if {uri} is /
        /wiki/${main_page}
    }


    proxy / https://${lang}.wikipedia.org {
        header_upstream Host {>Host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Port {server_port}
        header_upstream X-Forwarded-Proto {scheme}

        header_downstream Location en.wikipedia.org en.vikiansiklopedi.org
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile

}

en.m.vikiansiklopedi.org {
    tls {
        wildcard
    }
    redir {
        if {uri} is /
        /wiki/${main_page}
    }

    proxy / https://${lang}.m.wikipedia.org {
        header_upstream Host {>Host}
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Port {server_port}
        header_upstream X-Forwarded-Proto {scheme}

        header_downstream Location en.m.wikipedia.org en.m.vikiansiklopedi.org
    }

    ratelimit * / 50 100 second
    import config.d/log.Caddyfile
}

[304 more languages]
```

(see the [Caddyfile template](https://github.com/CristianCantoro/wikiproxy/blob/master/config/template.Caddyfile))

## 10. Please link to any related issues, pull requests, and/or discussion.

See also [issue T232213](https://phabricator.wikimedia.org/T232213#5471445) on Wikimedia Phabricator for context.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Because @mholt tweeted about the idea [once](https://twitter.com/mholt6/status/858356637937016832) :D

**Comment by mholt** [comment]
It looks like you got this resolved in https://github.com/caddyserver/caddy/pull/2144#issuecomment-530809059

**Comment by CristianCantoro** [comment]
This is a different issue, The problem here is that if I add either the directive:
```
header_upstream Host {host}
```
to my proxy configuration, I get a "Domain not configured" error.

**Comment by mholt** [comment]
Then I would not add that subdirective, since wikipedia is configured to only receive requests for its specific hostname.

**Comment by CristianCantoro** [comment]
Thanks @mholt!

One last question, I have seen some people ([example on StackOverflow][1]) using the following config:
```
header_upstream Host {>Host}
```
instead of:
```
header_upstream Host {host}
```

What is the difference between the two? In the [example above][1] they say that using `{host}` is "likely a little more reliable" using `{>Host}`. I didn't find any reference in the documentation.

[1]: https://stackoverflow.com/questions/43598655/caddy-header-upstream

**Comment by mholt** [comment]
`{>Host}` uses the Host: header of the incoming request, but Go moves the Host header to a struct field separate from the other headers for some reason, so that's what `{host}` is for. Doesn't really matter which you use in most cases, I think.
