### ISSUE TITLE
Misleading error message when CADDYPATH is not writable

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [caddyserver/caddy#2746]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0.3

## 2. What are you trying to do?

Just a basic letsencrypt setup test.

## 3. What is your Caddyfile?

None.

## 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -host REDACTED -ca https://acme-staging-v02.api.letsencrypt.org/directory 

## 5. Please paste any relevant HTTP request(s) here.

n.a.

## 6. What did you expect to see?

In this case, the default path for CADDYPATH was not writable for some reason.

In hindsight, I wish Caddy would have said something about that to point me in the right direction, like: "failed to write file in /XYZ".

## 7. What did you see instead (give full error messages and/or log)?

```
2019/09/12 20:17:48 [INFO] acme: Registering account for XXX
2019/09/12 20:17:49 [INFO] acme: Registering account for XXX
2019/09/12 20:17:49 [INFO] acme: Registering account for XXX
2019/09/12 20:17:54 registration error: acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:
```

## 8. Why is this a bug, and how do you think this should be fixed?

The message above makes it very hard to "guess" it's a filesystem permission issue.

Should be fixed by either:

 * doing a startup sanity (permission) check on CADDYPATH
 * or capturing the correct exception when trying to write (and failing), and output a message reflecting that

Thanks for Caddy!

**Comment by mholt** [comment]
Hmm yeah that doesn't look too helpful. Thanks for the report. I'll look into it!

**Comment by mholt** [comment]
The latest beta should have a better error because the latest CertMagic does a test to make sure storage is functional before anything else. Can you try it out?

**Comment by dubo-dubon-duponey** [comment]
@mholt still the same behavior on master (99914d22043f707f3f69bb5ee509d3353d75e943) 

I assume the fix is for v2 only? (fine if it is - looking forward moving to v2!)

**Comment by mholt** [comment]
@dubo-dubon-duponey To clarify, the latest betas are on the `v2` branch, not master.

**Comment by barbalex** [comment]
I am having this too and it is very frustrating: Lots of documentation seems wrong. For instance, adhering to https://caddyserver.com/docs/caddyfile/concepts only leads to bad errors which seem to mean that the structure documented is not correct. Or may be correct for v2  but not for v1.

So I keep reading this misleading message and wondering what could be wrong. Following dozens of leads that lead to lots of contradicting or just different information.

:-(

**Comment by francislavoie** [comment]
@barbalex Caddy v2 is a complete rewrite, and the v1 and v2 documentation are not compatible. If you're still using v1, you're looking for the documentation here: https://caddyserver.com/v1/docs

FYI there's a header at the top of the page in the v2 site that is meant to alert people of where to go for the v1 site.

**Comment by barbalex** [comment]
@francislavoie yeah, you're right - I tunnel visioned. Living through my personal dose of coding fatigue 🙄

**Comment by mholt** [comment]
Closing, since CertMagic for a while now checks to make sure storage is writeable before doing any cert operations.
