### ISSUE TITLE
v2: basicauth feature

### ISSUE THREAD

**Issue by Henrocker** [caddyserver/caddy#2747]
## 1. What would you like to have changed?
I really liked Caddy v1 basicauth and would like to see this feature in Caddy v2, too.
For little private projects or testing purposes, quickly "securing" them via basicauth is convenient and I used it a lot in Caddyfile v1.
If possible keeping the simple syntax just like in Caddy v2 would be awesome.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
Restrict access to specific webfolders quickly and convenient just like in Caddy v1. 

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
In the meantime, I run a second instance of Caddy which binds to localhost on a different port to work on some projects in private, but having them online in one instance allows for specific people to access the files if necessary to test, etc.

## 4. Please link to any relevant issues, pull requests, or other discussions.
https://caddy.community/t/v2-basicauth-feature/

**Comment by mholt** [comment]
I've actually got this mostly working locally, but I need to figure out how to design the more general authentication module before I'm ready to commit basic auth (which is just one form of authentication).

Hm, I can probably get this out next week, but the design may change in a breaking way before the final version. Just be aware of that.

**Comment by francislavoie** [comment]
@mholt https://github.com/tarent/loginsrv/blob/master/caddy/README.md covers a lot of the typical needs, maybe something along those lines built into v2 could be nice

**Comment by mholt** [comment]
Implemented in f8366c2. Updated the wiki with documentation.
