### ISSUE TITLE
v2: php_fastcgi: 301 redirect if path is a directory (add trailing slash at the end)

### ISSUE THREAD

**Issue by Henrocker** [caddyserver/caddy#2752]
## 1. What would you like to have changed?
Caddy v2 currently requires the user to redirect the request manually via additional config when requesting a subfolder of the webroot via /subfolder with a PHP file as index (as opposed to directly request /subfolder/index.php). I really like the behaviour of Caddy v1, redirecting with a 301 and adding a trailing slash to the request automatically, if the requested uri is a folder with php files as index.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
This makes configuration of Caddy v2 much easier and avoids tricky request redirects. In Caddy v1 this worked perfectly fine and `php_fastcgi <upstream>` would then do all that the Caddy v1 equivalent does in one configuration line.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Using redir in Caddyfile syntax or static_response for json equivalent, one can redirect or add the trailing slash for php webapps if required, but that is inconvenient and adds unnecessary size to Caddyfile.

## 4. Please link to any relevant issues, pull requests, or other discussions.
Maybe related to https://github.com/caddyserver/caddy/issues/1732 for Caddy v1.
https://caddy.community/t/v2-redirect-path-to-path-index-php-with-assets/6196/

**Comment by mholt** [comment]
Thanks @Henrocker. Would you please try the branch at https://github.com/caddyserver/caddy/pull/2754? I would appreciate your feedback whether it works or not!
