### ISSUE TITLE
v2: Caddyfile markdown directive

### ISSUE THREAD

**Issue by Henrocker** [caddyserver/caddy#2757]
## 1. What would you like to have changed?
I would really like to have a simple `markdown` directive for Caddyfile in Caddyfile-style syntax that will set:
```
{
      "handle": [
            {
                    "handler": "markdown"
            }
      ]
},
```
in the converted JSON Caddyfile.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
This might be useful in case the user uses a Caddyfile style config file and likes to setup Caddy to output proper rendered markdown without touching the converted Caddyfile.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
Alternatively, I add the lines mentioned above manually to every server block in Caddyfile in JSON, but using e.g. a simple `markdown` to Caddyfile style Caddyfile, it will be very convenient because after configadapter conversion, the JSON style Caddyfile already is configured to output proper markdown and doesn't have to be touched at all.

## 4. Please link to any relevant issues, pull requests, or other discussions.
None, yet.

**Comment by mholt** [comment]
See also #2736

**Comment by Henrocker** [comment]
Thanks, I'll close this then, mine is a duplicate.
