### ISSUE TITLE
v2: configure storage from Caddyfile

### ISSUE THREAD

**Issue by aitva** [caddyserver/caddy#2758]
## 1. Which version of Caddy are you using (`caddy -version`)?

v2.0.0-beta1

## 2. What are you trying to do?

I want to configure Caddy `storage` using a Caddyfile. But I cannot find the correct directive and the `$CADDYPATH` variable does not seem to work.

## 3. What is your Caddyfile?

```text
{
        storage {
                module file_system
                root /var/ssl/caddy
        }
}
example.com
tls me@example.com
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy run -config Caddyfile -config-adapter caddyfile`

## 6. What did you expect to see?

I expected `$CADDYPATH` to work or a `storage` directive.

## 7. What did you see instead (give full error messages and/or log)?

I cannot configure Caddy storage without reverting to JSON.

## 8. Why is this a bug, and how do you think this should be fixed?

Adding a `storage` directive to the Caddyfile or reverting to the `$CADDYPATH` variable.

## 9. What are you doing to work around the problem in the meantime?

I wrote a JSON configuration by hand.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Thank you for Caddy, I loved the simplicity of the v1. I am using it as a reverse proxy and sometime as a file server.

**Comment by mholt** [comment]
Wish granted. See ba29f9d.
