### ISSUE TITLE
WebAuthn?

### ISSUE THREAD

**Issue by Urheberrecht** [caddyserver/caddy#2759]
## 1. What would you like to have changed?

Maybe more a question than a true feature request, but would it make sense to integrate WebAuthn into Caddy directly? Or should this be / remain external?

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

FIDO2 and Webauthn seem to be supported by many organizations, including Google, Mozilla etc.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

n/a

## 4. Please link to any relevant issues, pull requests, or other discussions.

https://webauthn.io/

https://github.com/duo-labs/webauthn

https://github.com/duo-labs/webauthn.io

**Comment by francislavoie** [comment]
Hmm, I think this is probably a better candidate for a plugin or for apps themselves than something that's built-in to caddy.

In particular, there's a lot of things to manage to get this right - you still need to allow a way to revoke registered tokens if you lose one for example, and registering tokens is more of an opt-in action. The user would have to know the special URL to go access the login management page, or the app being covered by login would need to provide links in its UI to do that.

That's all to say, it's a tricky UX issue. Like technically caddy could be a webauthn server but I don't think it's that easy as just a drop-in feature.

**Comment by mholt** [comment]
Thanks for the request, but I think it's better as a plugin than as part of Caddy core. Since this issue tracker is just for Caddy itself, feel free to suggest this on our [forums](https://caddy.community) if you would like to discuss the idea with other developers!
