### ISSUE TITLE
command error, installation failed...

### ISSUE THREAD

**Issue by vircloud** [caddyserver/caddy#2760]
## 1. Which version of Caddy are you using (`caddy -version`)?

none

## 2. What are you trying to do?

Install using the commands 'https://caddyserver.com/download' provided,

```
PLATFORM:Linux 64-bit
PLUGINS:http.cache,http.expires,http.filter,http.forwardproxy,http.realip
PLAN:Personal (free)
```

Direct link to download, server reponse 404, message is

```
building caddy: exit status 2
```

One-step installer script (bash), server reponse 500, message is

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0  12019      0 --:--:-- --:--:-- --:--:-- 12058
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
The command '/bin/sh -c curl https://getcaddy.com | bash -s personal http.cache,http.expires,http.filter,http.forwardproxy,http.realip' returned a non-zero code: 1
```

**Comment by mholt** [comment]
I don't have a chance to check the logs right now, but if you remove each plugin until it builds, which plugin breaks the build?

**Comment by marpada** [comment]
Same problem here. I don't think it's related to any specific plugin (I'm trying with the http.prometheus and tls.dns.route53) but with some upstream server. I tried several times from my workstation until it worked, but still failing to download from our build server.

**Comment by aslrousta** [comment]
@mholt `http.filter` seems to be broken.

**Comment by mholt** [comment]
As this seems to be issues with third-party plugins, you will have to ask the plugin maintainers about that, I actually can't since I do not have access to their repositories. Thanks

**Comment by CryoRig** [comment]
I don't think this is a problem with a specific plugin...
if for example i try to get caddy with either http.cache OR http.cgi it works fine
but as soon as i combine two or more the downloads fails with above error

**Comment by mholt** [comment]
Hmm, that could be because a recent successful build with either (but not both) of them is cached, but combining them is not cached so a new build is attempted but failing.

I'm away from my machine most of this week but I'll see if I can look into it more

**Comment by adrianmihalko** [comment]
I am trying to install http.log, http.login, http.geoip (separately too) and doesn't work.

**Comment by mholt** [comment]
Ah, the build server ran out of disk space, which was filled up by the go module cache. ☹️

Should be working again.

(I'm going to rewrite the build server for v2, will hopefully avoid this in the future.)
