### ISSUE TITLE
proxy for multiple https domain

### ISSUE THREAD

**Issue by lilarcor** [caddyserver/caddy#2765]
Hello,
I am using caddy docker version v1.0.3. And I have following setting in my Caddyfile

`a.exA.com, a.exB.com {
gzip
tls admin@exA.com
tls /shared/crt/exA.com.cer /shared/crt/exA.com.key
proxy /  https://192.168.6.98:806  {
    insecure_skip_verify
    websocket
    transparent
   }
}
`
when I use a.exA.com to access , everything is fine. But when I use a.exB.com to access, log said

`2019/09/26 03:39:16 http: TLS handshake error from 192.168.6.111:60146: no certificate available for 'b.exB.com'`

**Comment by mholt** [comment]
It means that your certificate, exA.com.cer, doesn't have a SAN for b.exB.com, so Caddy has no certificates that qualify to satisfy the TLS handshake's ClientHello.

**Comment by lilarcor** [comment]
Is there a way to force exB.com to use that cert as a self signed cert?

**Comment by mholt** [comment]
Hmm, what is your use case for serving an invalid certificate (one that doesn't even match the ServerName)?

**Comment by lilarcor** [comment]
Some isp can’t resolve one of the domain, so I need to use both. For the certs, I use free service for exB.com, seems that doesn’t support letsencrypt. Now I split them to two sections , and use self_signed for exB. So far so good.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
