### ISSUE TITLE
Browse directive for v2

### ISSUE THREAD

**Issue by pgporada** [caddyserver/caddy#2766]
Per your explicit in-person permission to bypass the template :P

It would be nice to set folders like this
```
    browse /imgs/garden/
    browse /imgs/porch-swing/
    browse /imgs/arcade-cabinet/

```

or like this
```
    file_server /imgs/garden /imgs/porch-swing /imgs/arcade-cabinet {
        browse
    }
```

**Comment by mholt** [comment]
Ah, I just remembered, you can use the [`matcher`](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#matcher) directive to specify all your paths in one:

```
matcher browseable {
    path imgs/garden /imgs/porch-swing /imgs/arcade-cabinet
}
file_server match:browseable {
    browse
}
```

Or one per line:

```
matcher browseable {
    path imgs/garden \
         /imgs/porch-swing \
         /imgs/arcade-cabinet
}
file_server match:browseable {
    browse
}
```

Is that satisfactory? I'd prefer just using this if that's okay. 😅 

(Make sure to add another `file_server` directive if you just want a regular file server for everything else.)

**Comment by Henrocker** [comment]
Since I've got just one path served browsable, I did:
```
file_server /md browse
file_server
```

**Comment by pgporada** [comment]
Using the following match block throws an error
```
    matcher browseable {
        path /imgs/garden \
             /imgs/porch-swing \
             /imgs/arcade-cabinet
    }
    file_server match:browseable browse
```
```
2019/09/27 14:20:27 adapting config using caddyfile: getting matcher module '/imgs/porch-swing': module not registered: http.matchers./imgs/porch-swing
```

The condensed version does not throw an error and caddy starts up just fine.
```
    matcher browseable {
        path /imgs/garden /imgs/porch-swing /imgs/arcade-cabinet
    }
    file_server match:browseable browse
```

**Comment by mholt** [comment]
@Henrocker Ah, true, that could also work, for easy one-liners. I didn't think of that. 😅 

@pgporada There's a wee bug in the lexer (escaping newlines is kind of a new thing), so I'm fixing that now and adding a test case for it. Stay tuned!

**Comment by mholt** [comment]
Just pushed commit c12bf40 which fixes escaped newlines in the Caddyfile.

I still like @Henrocker's solution:

```
file_server /imgs/garden browse
file_server /imgs/porch-swing browse
file_server /imgs/arcade-cabinet browse
file_server
```

Is that doable?

A separate `browse` directive like v1 has is possible, but kinda complicated and has limited flexibility.

**Comment by mholt** [comment]
Closing, since I believe this is resolved! Feel free to continue the conversation if needed though.

**Comment by Henrocker** [comment]
Hi @mholt, idk when this happened but with the latest v2 and the following config:

<details><summary>V2: CONFIG</summary>
<p>

```sh
hnrk.io, www.hnrk.io {
        root * /etc/caddy/html
        tls /etc/caddy/hnrk.io.crt /etc/caddy/hnrk.io.key
        encode brotli zstd gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        file_server /md browse
        file_server
}
```

</p>
</details>

browsing a specific directory using [this method](https://github.com/caddyserver/caddy/issues/2766#issuecomment-536244571) no longer works (I receive 404). Website is live, so you can see the current behaviour.

Can you tell me how to setup file browsing with Caddy v2 correctly?

Thanks!

**Comment by Henrocker** [comment]
Hi @mholt, idk when this happened but with the latest v2 and the following config:

<details><summary>V2: CONFIG</summary>
<p>

```sh
hnrk.io, www.hnrk.io {
        root * /etc/caddy/html
        tls /path/to/cert /path/to/key
        encode brotli zstd gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        file_server /md browse
        file_server
}
```

</p>
</details>

browsing a specific directory using [this method](https://github.com/caddyserver/caddy/issues/2766#issuecomment-536244571) no longer works (I receive 404). Website is live, so you can see the current behaviour.

Can you tell me how to setup file browsing with Caddy v2 correctly?

Thanks!

**Comment by mholt** [comment]
@Henrocker Using which version, exactly? Beta 12 or are you building from source.

**Comment by Henrocker** [comment]
I've built Caddy v2 from source (including 372540f)

**Comment by mholt** [comment]
@Henrocker path matching is no longer prefix by default; please see #2981.

**Comment by Henrocker** [comment]
Ahh thank you! Adding a '*' after /md solved it.

My config looks like this now:

<details><summary>V2: CONFIG</summary>
<p>

```sh
hnrk.io, www.hnrk.io {
        root * /etc/caddy/html
        tls /path/to/cert /path/to/key
        encode brotli zstd gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        file_server /md* browse
        file_server
}
```

</p>
</details>
