### ISSUE TITLE
Add version parameter to getcaddy.com

### ISSUE THREAD

**Issue by hazcod** [caddyserver/caddy#2772]
Would be nice to add a `version` parameter to getcaddy.com for reproducible Docker builds.

**Comment by francislavoie** [comment]
https://getcaddy.com isn't meant to be used for this purpose. If you want reproducible builds, just write a Dockerfile that targets a specific commit from git. To get you started, check out https://github.com/abiosoft/caddy-docker which includes a builder image which you can use to make builds with the plugins you need.

**Comment by mholt** [comment]
Yeah. The new website (and improved getcaddy.com) will support more customizable builds, I think, after v2.0. (Thanks to Go modules, it should be easier to do this. You might even be able to specify versions for plugins individually!)
