### ISSUE TITLE
TLS handshake error: no certificate available

### ISSUE THREAD

**Issue by eddiejibson** [caddyserver/caddy#2773]
## 2. What are you trying to do?

Using a simple caddyfile, upon the attempt of caddy trying to obtain a certificate for several different domains, this error is spat out: ` TLS handshake error from ip: no certificate available for 'domain.com'` 

## 3. What is your Caddyfile?
```text
:443 {
      proxy / localhost:8080 {
        transparent
      }

      tls {
        max_certs 10
      }
}

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
Used systemd. All correct permissions have been set to directories.
```text
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target systemd-networkd-wait-online.service

[Service]
Restart=on-abnormal

; User and group the process will run as.
User=www-data
Group=www-data

; Letsencrypt-issued certificates will be written to this directory.
Environment=CADDYPATH=/etc/ssl/caddy

; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
ExecStart=/usr/local/bin/caddy -conf /etc/caddy/Caddyfile  -log /var/log/caddy/service.log -agree -root=/var/tmp
ExecReload=/bin/kill -USR1 $MAINPID

; Use graceful shutdown with a reasonable timeout
KillMode=mixed
KillSignal=SIGQUIT
TimeoutStopSec=5s

; Limit the number of file descriptors; see `man systemd.exec` for more limit settings.
LimitNOFILE=1048576
; Unmodified caddy is not expected to use more than that.
LimitNPROC=512

; Use private /tmp and /var/tmp, which are discarded after caddy stops.
PrivateTmp=true
; Use a minimal /dev (May bring additional security if switched to 'true', but it may not work on Raspberry Pi's or other devices, so it has been disabled in this dist.)
PrivateDevices=false
; Hide /home, /root, and /run/user. Nobody will steal your SSH-keys.
 ProtectHome=true
; Make /usr, /boot, /etc and possibly some more folders read-only.
ProtectSystem=full
; … except /etc/ssl/caddy, because we want Letsencrypt-certificates there.
;   This merely retains r/w access rights, it does not add any new. Must still be writable on the host!
ReadWritePaths=/etc/ssl/caddy

; The following additional security directives only work with systemd v229 or later.
; They further restrict privileges that can be gained by caddy. Uncomment if you like.
; Note that you may have to add capabilities required by any plugins in use.
;CapabilityBoundingSet=CAP_NET_BIND_SERVICE
;AmbientCapabilities=CAP_NET_BIND_SERVICE
;NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

**Comment by francislavoie** [comment]
Hello. First of all, this is the issue board for bugs/feature requests, questions should be directed to https://caddy.community as noted in the issue template.

The main issue is in your Caddyfile. You don't specify a domain in the host label, so [Automatic HTTPS](https://caddyserver.com/docs/automatic-https) is not enabled. I see you specified `max_certs`, that's now a deprecated option as of [v1.0.1](https://github.com/caddyserver/caddy/releases/tag/v1.0.1). If you're trying to use on-demand TLS, you should now use the `ask` directive instead.

**Comment by mholt** [comment]
Hm, yeah, you should receive an error or at least a warning about max_certs being deprecated (@francislavoie made me aware that it's erroneously still referenced in a page in our docs, I'll fix that soon)... if one is not emitted, that would certainly be a bug.

**Comment by eddiejibson** [comment]
This was not the issue, I also used the ask directive. Either way it's not just a warning, the whole thing (on demand TLS) has broken.


29 Sep 2019, 03:39 by notifications@github.com:

**Comment by eddiejibson** [comment]
Because of this, that's why I listed as a bug

**Comment by mholt** [comment]
> Sadly this was not the issue, I also used the ask directive. Either way it's not just a warning, the whole thing (on demand TLS) has broken.

Can you explain more? The issue template is missing several questions and saying "it has broken" doesn't really help, because it _does_ work, it's probably just misconfigured. We'll need more specifics in order to narrow it down. For example you say you used the `ask` subdirective but your post doesn't show that. You say it's "not just a warning" but does that mean you received a warning about its deprecation or not?

**Comment by focux** [comment]
I'm experiencing this same issue,  this is my Caddyfile:
```
* {
    root ./www
    browse
    log stdout
    errors stdout
    gzip
    tls {
       max_certs 10
    }
}

*.another.com:443 {
    root ./www
    browse
    gzip
    log stdout
    errors stdout
    tls /etc/letsencrypt/live/thridea.com/fullchain.pem /etc/letsencrypt/live/thridea.com/privkey.pem
}
```

And this is the error I'm getting:
```
http: TLS handshake error from 179.53.91.106:58897: no certificate available for 'bookme.rocks'
```

I'm running Caddy in a Ubuntu 18 VPS with a root user. If you need more info, I'd be happy to provide it.

**Comment by mholt** [comment]
@focux `max_certs` has been deprecated in favor of `ask` to enable on-demand TLS.

**Comment by focux** [comment]
Ya I know but I also tried using `ask http://www.google.com` which return an http 200 status code and it isn't working either. Thanks for answering.

**Comment by focux** [comment]
And what is also weird is that Caddy didn't even ask me for my e-mail or to agree to the LE TOS. It's a new Caddy setup btw.

**Comment by francislavoie** [comment]
Please open a new issue and provide as much detail as possible, following the issue template.

**Comment by focux** [comment]
Done #2895
