### ISSUE TITLE
Request forward proxy for v2.

### ISSUE THREAD

**Issue by Tsukimeizi** [caddyserver/caddy#2774]
## 1. What would you like to have changed?

Add forward proxy

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

I use forward proxy plugin in v1 while I don't find it in v2.
Would you please also add forward proxy for v2?

**Comment by mholt** [comment]
It's on our list, yeah. Will hopefully get around to this after v2 has reached RC or stable status.

(Closing, since it's on our list.)
