### ISSUE TITLE
Cannot enable QUIC on localhost

### ISSUE THREAD

**Issue by KevinRSX** [caddyserver/caddy#2778]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0.3

## 2. What are you trying to do?

I would like to test experimental QUIC support of caddy on localhost

## 3. What is your Caddyfile?
```text
localhost:443 {
  log stdout
  tls self_signed
  gzip
}

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

Run by `caddy -quic`

## 5. Please paste any relevant HTTP request(s) here.

N/A

## 6. What did you expect to see?

I expected to see QUIC enabled in chrome developer tool. The client that I used is an old chrome version which supports quic43.

## 7. What did you see instead (give full error messages and/or log)?

No QUIC appeared. Instead, only HTTP/2.0 showed. I used `chrome://net-internals/#quic` to check if anything was transported through QUIC but failed.

## 10. Please link to any related issues, pull requests, and/or discussion.

https://github.com/caddyserver/caddy/issues/2194

**Comment by elcore** [comment]
As described in the linked issue, QUIC requires a valid, and trusted certificate. Additionally, the QUIC library might not be up-to-date, but that's another question.

**Comment by mholt** [comment]
I'm actually not sure the status of the quic branch (required for using gQUIC in browsers). For IETF QUIC ("HTTP/3"), we are actively developing its support on the v2 branch.

**Comment by elcore** [comment]
That's right, I've said that too, but the the underlying issue is that it requires a valid, and trusted certificate, even if it was up-to-date... 🙈
