### ISSUE TITLE
v2: Decide which plugins are standard and which stay in this repo

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2780]
With Go modules and Caddy 2, we have the opportunity of versioning individual plugins for each build. Caddy 2 can be aware of their versions and print them out in association with the Caddy plugin name.

(Note: Caddy modules are distinct from Go modules, but they may be implemented by Go modules. The naming for both was decided around the same time, which is unfortunate. For clarity in this discussion, I'm going to refer to Caddy modules as "plugins" so that "modules" means Go modules in this context.)

This is a really promising capability with regards to stable builds, deployments, and unattended upgrades, however: it requires a Caddy plugin to be its own Go module, otherwise it gets versioned with the other plugins in the same module.

We do not want to have more than one module in the Caddy repo because [that's complicated and tedious](https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories). So, any plugins that we want to version differently from Caddy itself should live in a separate repo.

Right now, Caddy 2 imports a lot of standard plugins by default, and all of them are contained in this repository. It seems unnecessary to have EVERY SINGLE PLUGIN in its own repo (there are a lot of plugins and some are just a few lines of code), but perhaps the larger plugins should be independent, such as:

- `http`
- `tls`
- `http.handlers.reverse_proxy`
- `http.handlers.file_server`

This would allow us to use different versions of the reverse proxy or file server per Caddy build, rather than tying their versions to the specific version of Caddy. This of course has pros and cons. Pros: flexibility in remaining stable and getting the exact functionality you want. Cons: now you need to know your Caddy version _and_ the versions of relevant plugins.

Is this something we want to do?

Also, regardless of which repo they live in, which plugins should be imported by default, i.e. for a "standard" build?

**Comment by tobya** [comment]
While I think fundamentally it is a good idea for modules to be able to be seperate repos, I think we should have a good reason to pull them out as seperate code.  While personally I like the idea of being able to specify the version of TLS (see previous discussions!) I'm not sure what practical benefit it provides as I would over time fall further being the up to date version, which leads to the possibility of bugs based on non standard sets of versioned modules.

If this is an attempt to try to provide a 'stable' branch by another means, I think we should instead create a stable release and a development release.   I know the argument is that someone may want a feature in TLS on the dev branch, but keep everything else at stable, however I am unsure if the overhead is worth this edge case.

I definitely think we should keep all 3rd party plugins as modules (taking some of the most popular under the Caddy core such as GIT ) but keep the core caddy modules core and part of the main code block.  We should investigate having an official release, a stable dev release and a development release.  

Having a development release which will be downloaded and used by some will give us valuable feedback on possible bugs before merging with stable release branch.
