### ISSUE TITLE
failed to copy buffer xxxx use of closed network connection

### ISSUE THREAD

**Issue by aiyijing** [caddyserver/caddy#2783]
This is my Caddyfile
```shell
xxxx.xx
{
  log ./caddy.log
  proxy /ws 172.17.0.2:80 {
    websocket
    header_upstream -Origin
  }
}
```
It always reports errors when I connect to websocket
```shell
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  write tcp 172.17.0.3:443->123.118.24.241:16050: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:49656->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:49654->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:50836->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:49636->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:50838->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:49648->172.17.0.2:80: use of closed network connection
2019/10/02 08:06:14 [ERROR] failed to copy buffer:  read tcp 172.17.0.3:51142->172.17.0.2:80: use of closed network connection
```

**Comment by aiyijing** [comment]
What causes this? Sometimes I can connect normally

**Comment by HarrisonLauK** [comment]
I am suffering some issue!!! looking for the resloution.

**Comment by Mohammed90** [comment]
Are you experiencing connectivity issue or just seeing this in the logs? I've seen this in the logs, and can only be explained if the client disconnects before end of stream from upstream server, hence the "use of closed network connection".

**Comment by aiyijing** [comment]
I check  these logs，because of caddy proxy is instable。but i added a configuration item to solve this problem.
```shell
xxxx.xx
{
  log ./caddy.log
  proxy /ws 172.17.0.2:80 {
    websocket
    header_upstream -Origin
    timeout 10m # to increase this time
  }
}
```

**Comment by mholt** [comment]
That sounds like a reasonable solution.

**Comment by chacha20** [comment]
以前看到一份文档说修改.service文件里头的caddy启动参数，有一个类似buffer的参数设置一下就好了，但是找不到参数文档，我找找

**Comment by francislavoie** [comment]
For ref, google translate:

> Previously I saw a document that said to modify the caddy startup parameters in the .service file, there is a buffer-like parameter setting just fine, but I can't find the parameter file, I look for

**Comment by joyoner** [comment]
> I check these logs，because of caddy proxy is instable。but i added a configuration item to solve this problem.
> 
> ```shell
> xxxx.xx
> {
>   log ./caddy.log
>   proxy /ws 172.17.0.2:80 {
>     websocket
>     header_upstream -Origin
>     timeout 10m # to increase this time
>   }
> }
> ```

the issue is not solved, the logs appear again.

**Comment by francislavoie** [comment]
@joyoner Unfortunately that's enough information for us to go on. We can't do anything to fix the issue without clear, reproduceable steps.

Did you consider using Caddy v2? Caddy v1 is no longer under active maintenance.

**Comment by mrmuli** [comment]
I may not be the only one still facing this and I hope this at least helps someone, I'm running Caddy as a web server for a docker-compose setup and I circled around this issue for days.
```
[ERROR] failed to copy buffer:  readfrom tcp 172.18.0.9:43074->172.18.0.20:4001: read tcp 172.18.0.9:443->IPADDR:33053: use of closed network connection
```
Essentially, the server I was running this on (CentOS) had some strict firewall rules that weren't playing well with Docker.
I didn't want to stop the firewall daemon so this command got recommended by a colleague.
`firewall-cmd --set-default-zone=trusted`
