### ISSUE TITLE
packaging for Red Hat ecosystem (Fedora/CentOS/RHEL)

### ISSUE THREAD

**Issue by carlwgeorge** [caddyserver/caddy#2788]
Continuing the conversation from https://github.com/caddyserver/caddy/issues/2786#issuecomment-538593323.

> Ideally, we'd like to have packages in distro default repositories

I've been maintaining a [caddy package](https://src.fedoraproject.org/rpms/caddy) in Fedora for the last two years.  I also build it in the EPEL repository for RHEL/CentOS 7.  This package includes the realip and geoip plugins, along with several dns plugins.  It integrates with systemd and selinux and follows Fedora packaging guidelines.

> which we can update at will

Fedora packages follow the [Fedora update policy](https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/).  EPEL packages have a [similar policy](https://fedoraproject.org/wiki/EPEL_Updates_Policy).  The goal of these policies is to prevent stable releases from getting breaking changes.  It's not quite "at will".

Fedora's build system does not allow unrestricted internet access.  You have to upload your source tarball(s) and can install other packages as build requirements.  Not all of Caddy's dependencies are packaged in all Fedora and EPEL branches.  With Caddy v0, this wasn't too big a deal since the dependencies were vendored, which [is allowed](https://docs.fedoraproject.org/en-US/fesco/Bundled_Software_policy/).  Since vendored dependencies were removed in v1, that has limited which branches I was able to update to v1.  Here is the current version state:

| branch | version |
| --- | --- |
| epel7 | 0.11.4 |
| f29 | 0.11.4 |
| f30 | 0.11.4 |
| f31 | 1.0.3 |
| rawhide | 1.0.3 |

I would like to see the epel7 branch at least updated to v1, but without the vendored dependencies it will be difficult.  In order of difficulty, it would require: 1) tarballs from the project with the vendored dependencies, 2) manually adding all the dependencies as additional sources in the package, or 3) creating new packages for all the missing dependencies.  Fedora 31 (currently in beta) made it much easier with new go RPM packaging macros and many more dependencies packaged (and I added the missing ones).

I'm not sure what the backwards compatibility for v2 will look like, but if a user can't just update to v2 using the same config and get the same result in most use cases, we may only be allowed to update caddy to v2 in the rawhide branch, which will eventually become Fedora 32.  We can request an exception, but that will depend on how bad the breaking changes are and if there are security implications.

If you really want to be able to update the package at will without concern for distro guidelines, running your own repository will be necessary.  Fedora makes this easy with [COPR](https://copr.fedorainfracloud.org), which functions similar to Ubuntu PPA.  COPR also allows you to optionally permit internet access during the build, which means it's not strictly necessary to have all dependencies packages since `go build` can download them during the build.  Maintaining packages in both the default repos (newest version possible within guidelines) and COPR (always the latest version) is a common approach.

**Comment by Conan-Kudo** [comment]
The [openSUSE Build Service](https://build.opensuse.org/) is probably a good option here. You can build for a wide range of RPM and Debian distributions in one place, and it produces working repositories in a similar structure to Fedora's COPR or Ubuntu's Launchpad PPA system.

However, unlike COPR and PPA, OBS does not allow you to configure for internet access.

For example, I build snapshots of [dattobd](https://github.com/datto/dattobd) this way in [a personal OBS project for testing](https://build.opensuse.org/package/show/home:Pharaoh_Atem:dattobd/dattobd) using a unified RPM spec for RPM and Debian distributions. A similar strategy would be possible for caddy, if you so wish.

**Comment by carlwgeorge** [comment]
I've gotten a caddy FAS group created, and activated copr for it.

https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/

Nothing has been built yet, but I have a work-in-progress spec file that will download dependencies during the build, to avoid having to have all dependencies packaged.  Other considerations:

* el8 is enabled for the copr, but el8 doesn't yet have golang 1.13 (the minimum required version).  8.1 beta is supposed to add 1.12, and hopefully 1.13 follows soon after.
* el6 has a new enough version of golang, but it goes EOL in just over a year, and it would be easier to just focus on distros with systemd.

**Comment by carlwgeorge** [comment]
caddy-2.0.0~beta6-1 has been built in the copr.  I was only able to build it for distros with golang 1.13.

- RHEL/CentOS 7
- Fedora 31
- Fedora Rawhide

This is using the proposed systemd unit file from https://github.com/caddyserver/dist/pull/1.  I haven't testing this package myself yet.  Eventually I want to maintain the spec file in [caddyserver/dist](https://github.com/caddyserver/dist), but for now it can be [viewed in the build results directory on copr](https://copr-be.cloud.fedoraproject.org/results/@caddy/caddy/fedora-rawhide-x86_64/01065445-caddy/caddy.spec).

**Comment by mholt** [comment]
Oh, and I'm interested in making an official rpm for Caddy 2 (thus no breaking changes) as soon as possible as well!

**Comment by Conan-Kudo** [comment]
@carlwgeorge Would it make sense to set up [Packit](https://packit.dev/) for continuous delivery of new releases into Fedora?

**Comment by carlwgeorge** [comment]
@Conan-Kudo 

This spec file won't work in Koji, because it downloads all the sources during the build.

```
# In order to build Caddy with version information, we need to create this file
# and have it import the Caddy go module.  This is in lieu of a traditional
# source tarball.  This method requires that we allow networking in our build
# environment.
Source0:        main.go
```

**Comment by carlwgeorge** [comment]
Just tested on CentOS 7 and Fedora 31.  These packages appear to work as intended.

**Comment by carlwgeorge** [comment]
@Conan-Kudo Got any interest in helping maintain the caddy RPMs in Fedora and the copr?  I got a caddy FAS group created that will have access to both.

**Comment by carlwgeorge** [comment]
Here are the package sources.

https://github.com/caddyserver/dist/tree/rpm/rpm

There is a pull request to merge them from the rpm branch to master.

**Comment by Conan-Kudo** [comment]
> @Conan-Kudo Got any interest in helping maintain the caddy RPMs in Fedora and the copr? I got a caddy FAS group created that will have access to both.

Sure.

**Comment by mholt** [comment]
@Conan-Kudo Thanks for being willing! I've sent you an invite to collaborate on the dist repo.

I'm also sending you a Slack invite

**Comment by thebetterjort** [comment]
yum install caddy doesn't bare fruit on rhel. What is best way to get caddy on production rhel?

**Comment by francislavoie** [comment]
@thebetterjort the instructions are all listed here: https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/
