### ISSUE TITLE
packaging for Debian ecosystem (Debian/Ubuntu)

### ISSUE THREAD

**Issue by carlwgeorge** [caddyserver/caddy#2789]
Continuing the conversation from https://github.com/caddyserver/caddy/issues/2786#issuecomment-538593323.  I'm not as well versed in the Debian packaging ecosystem, but this is a place for those that are to discuss getting Caddy into the default Debian and Ubuntu repositories.  I do know that if Caddy gets added to Debian, it will eventually get rebuilt automatically into Ubuntu.

Similar to Fedora, Debian and Ubuntu have guidelines that restrict what updates can occur in which release.  Similar to Fedora's COPR, [Ubuntu PPA](https://help.launchpad.net/Packaging/PPA) is a service that would allow delivering the latest Caddy versions for Ubuntu regardless of distro policies.  I don't believe Debian is compatible with PPA however.

**Comment by Conan-Kudo** [comment]
The [openSUSE Build Service](https://build.opensuse.org/) is probably a good option here. You can build for a wide range of RPM and Debian distributions in one place, and it produces working repositories in a similar structure to Fedora's COPR or Ubuntu's Launchpad PPA system.

However, unlike COPR and PPA, OBS does not allow you to configure for internet access.

For example, I build snapshots of [dattobd](https://github.com/datto/dattobd) this way in [a personal OBS project for testing](https://build.opensuse.org/package/show/home:Pharaoh_Atem:dattobd/dattobd) using a unified RPM spec for RPM and Debian distributions. A similar strategy would be possible for caddy, if you so wish.

**Comment by mholt** [comment]
We are progressing with other packages/distros and have set up this repo with some official resources: https://github.com/caddyserver/dist

**Comment by Immortalin** [comment]
An official snap and flatpak would be great too.

The unofficial ones are all outdated: 

https://snapcraft.io/caddy

**Comment by mholt** [comment]
@Immortalin Sure, we'd like to do that. Can you help us make them?

**Comment by Immortalin** [comment]
One thing to note is that snap updates automatically in the background. Is graceful upgrades working for Caddy 2?

**Comment by mholt** [comment]
There is a plan for Caddy 2 to have commands like `add-module` and `remove-module` and `upgrade` and eventually, automatic upgrades for patches and security releases -- by having package managers install a command that manages another command, instead of the package manager installing the command directly.

I'm still trying to convince the rest of the collaborators on the packages that this is a good idea. :) But once we're in agreement, or at least reach some consensus, yes, that'll happen.

**Comment by popey** [comment]
FWIW I filed a bug against the caddy snap to request them to update it or hand it over to someone else who will maintain it. https://github.com/nixberg/caddy/issues/2
