### ISSUE TITLE
Add integration name to User-Agent?

### ISSUE THREAD

**Issue by jsha** [caddyserver/caddy#2795]
## 1. What would you like to have changed?

It would be great to have a field in Caddyfiles that could act like a User-Agent, but would be prepended to Caddy's built-in User-Agent. This would be useful for integrations that build on top of Caddy to identify themselves.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

At https://community.letsencrypt.org/t/need-unblock-ip/103584, we're debugging an issue that seems to be related to the V2Ray bundle. That bundle happens to configure a fake email address automatically. That fake email address has been really useful in distinguishing V2Ray users from other Caddy users, but I'd still like to submit a PR changing the default template to not include an email address by default. I'd love to be able to suggest an alternate config field that would continue to help identify V2Ray traffic for debugging.

**Comment by mholt** [comment]
This is a good idea. I'll make sure this gets into v2.

**Comment by daiaji** [comment]
It's a complete digression. Is v2ray surprisingly popular?

**Comment by francislavoie** [comment]
Right now we're setting the UserAgent for ACME requests here:

https://github.com/caddyserver/caddy/blob/5376e5113e25d85725e1f64d06a288700a50bbaa/cmd/main.go#L44

We could make this an option on the `tls` app (plus global option in the Caddyfile) to add a user-defined suffix which is set at Provision time of the `tls` app.

Is this still something we want to do @mholt?

**Comment by mholt** [comment]
@francislavoie Sure, that sounds good. I'm not sure I want to expose it in the Caddyfile though unless there's a specific need for it.

The more I think about it, the less I'm sure it will help. I bet most integrators will not set it, just like how most people don't specify an email address.

**Comment by jsha** [comment]
In the specific v2ray case, I'm thinking that we (Let's Encrypt) would actually send them a PR to add it to their default template. That would allow us to remove the junk email address they automatically create, without losing visibility into which clients are v2ray vs which clients are other Caddy users.

**Comment by mholt** [comment]
Alrighty. I just need to decide if a custom User-Agent is something that should be configured by the user in Caddy's `admin` config, or if it's specific to the `tls` app.

**Comment by mholt** [comment]
@jsha Long lost but not forgotten. Caddy will prepend the value of the `$USERAGENT` environment variable to the UA string sent with ACME requests. Hope that is helpful!
