### ISSUE TITLE
TLS handshake error from 10.244.0.1:63189: EOF every 5 seconds

### ISSUE THREAD

**Issue by pascalgn** [caddyserver/caddy#2800]
## 1. Which version of Caddy are you using (`caddy -version`)?

v2, ce1205239a7c2300932d0d6819085586660fcce9

## 2. What are you trying to do?

Running Caddy in Kubernetes on Azure (AKS)

## 3. - 10.

Irrelevant to this issue. I just want to post it so that others can find it :)

## Unexpected output

```
2019/10/08 16:35:21 http: TLS handshake error from 10.244.0.1:63189: EOF
2019/10/08 16:35:26 http: TLS handshake error from 10.244.0.1:63249: EOF
2019/10/08 16:35:31 http: TLS handshake error from 10.244.0.1:63299: EOF
2019/10/08 16:35:36 http: TLS handshake error from 10.244.0.1:63349: EOF
2019/10/08 16:35:41 http: TLS handshake error from 10.244.0.1:63413: EOF
2019/10/08 16:35:46 http: TLS handshake error from 10.244.0.1:63465: EOF
2019/10/08 16:35:51 http: TLS handshake error from 10.244.0.1:63516: EOF
2019/10/08 16:35:56 http: TLS handshake error from 10.244.0.1:63574: EOF
2019/10/08 16:36:01 http: TLS handshake error from 10.244.0.1:63646: EOF
```

**Comment by pascalgn** [comment]
This is caused by https://github.com/kubernetes/kubernetes/issues/76657 because the Azure loadbalancer sends a TCP health probe every 5 seconds. This is just an empty packet, so the TLS engine does not receive the correct handshake.

This is not an error in Caddy!

**Comment by morph027** [comment]
We are running into the same issue with AWS Network Load Balancers.

Right now we're working on migration from licensed v1 to v2 (we will sponsor caddy v2 after migration) and thesse logs are flooding our systems (yesterday 318895 entries).

Right now we're thinking about a wrapper for systemd like

`/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile 2>&1 | grep -v 'http: TLS handshake error from.*EOF'` but this is not our favourite solution.

I was thinking about some kind of health-check plugin which listens for TCP packets on a specific port but is able to handle/ignore empty packets.

**Comment by morph027** [comment]
Okay,, we've managed to get around by using port 80 as healthcheck port ;)

**Comment by Vineeth-varma** [comment]
How you have resolved this issue, can you guide me I am facing the similar issue "TLS handshake error from 10.244.0.1:35154: EOF"

**Comment by francislavoie** [comment]
@Vineeth-varma please ask your usage questions on the Caddy forums https://caddy.community, and not on a long-since-closed issue.
