### ISSUE TITLE
lost bind port 80 after process started for serial days on freebsd

### ISSUE THREAD

**Issue by sharljimhtsin** [caddyserver/caddy#2804]
## 1. Which version of Caddy are you using (`caddy -version`)?
root@iZt4nbvac3vpa6uqd0l17kZ:~ # caddy -version
unknown

bin tgz: caddy_v1.0.3_freebsd_amd64.tar.gz

## 2. What are you trying to do?

start caddy with below cfg:
````
xxx.xzx.im yyy.xzx.im {
        root /root
        proxy /caonima 127.0.0.1:9700 {
                websocket
                header_upstream -Origin
        }
        proxy / 127.0.0.1:88 {
                transparent
        }
}
````
and run it by:
> nohup caddy -agree -log web.log -conf cfg/Caddyfile &
on freeBSD 

sys info:
>FreeBSD iZt4nbvac3vpa6uqd0l17kZ 11.3-RELEASE-p1 FreeBSD 11.3-RELEASE-p1 #0: Tue Jul 23 18:21:16 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

it binds the 80 and 443 port at starter, but while some days past, it only bind 443 port.

>root@iZt4nbvac3vpa6uqd0l17kZ:~ # sockstat | grep caddy
> root     caddy      80376 3  tcp46  *:443                 *:*

## 3. What is your Caddyfile?
```
xxx.xzx.im yyy.xzx.im {
        root /root
        proxy /caonima 127.0.0.1:9700 {
                websocket
                header_upstream -Origin
        }
        proxy / 127.0.0.1:88 {
                transparent
        }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

nohup caddy -agree -log web.log -conf cfg/Caddyfile &

## 5. Please paste any relevant HTTP request(s) here.

root@iZt4nbvac3vpa6uqd0l17kZ:~ # curl https://xxx.xzx.im -I
HTTP/2 200
content-type: text/html; charset=utf-8
date: Fri, 11 Oct 2019 07:13:06 GMT
server: Caddy
server: nginx/1.16.0

root@iZt4nbvac3vpa6uqd0l17kZ:~ # curl http://xxx.xzx.im -I
curl: (7) Failed to connect to sgp.xzx.im port 80: Connection refused
root@iZt4nbvac3vpa6uqd0l17kZ:~ #

## 6. What did you expect to see?

access http from port 80 works ok likes https on port 443.

## 7. What did you see instead (give full error messages and/or log)?

80 port related:
2019/10/04 19:12:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/04 19:14:30 [INFO] 47.74.133.151 - No such site at :80 (Remote: 202.160.147.182, Referer: )
2019/10/04 19:21:37 [INFO]  - No such site at :80 (Remote: 187.135.115.116, Referer: )
2019/10/04 19:38:11 [INFO]  - No such site at :80 (Remote: 157.245.184.21, Referer: )
2019/10/04 21:24:34 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:35 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:35 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:36 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:38 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:39 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:39 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:55:10 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/04 22:34:28 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.56.106.4, Referer: )
2019/10/04 22:34:30 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.56.106.4, Referer: )
2019/10/04 23:58:22 [INFO] www.google.com - No such site at :80 (Remote: 107.172.15.10, Referer: )
2019/10/04 23:58:23 [INFO] www.google.com - No such site at :80 (Remote: 107.172.15.10, Referer: )
2019/10/05 00:40:32 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 02:23:58 [INFO] 47.74.133.151 - No such site at :80 (Remote: 197.254.91.98, Referer: )
2019/10/05 03:02:47 [INFO] 47.74.133.151 - No such site at :80 (Remote: 138.97.224.145, Referer: )
2019/10/05 03:27:37 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 03:28:29 [INFO] 47.74.133.151 - No such site at :80 (Remote: 181.196.240.74, Referer: )
2019/10/05 05:01:15 [INFO] 47.74.133.151 - No such site at :80 (Remote: 183.129.160.229, Referer: )
2019/10/05 05:03:18 [INFO] 47.74.133.151 - No such site at :80 (Remote: 36.89.17.189, Referer: )
2019/10/05 06:30:33 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 09:02:17 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.111.126.250, Referer: )
2019/10/05 09:02:17 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.111.126.250, Referer: )
2019/10/05 09:28:40 [INFO]  - No such site at :80 (Remote: 95.222.17.192, Referer: )
2019/10/05 09:40:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 10:15:49 [INFO] 47.74.133.151 - No such site at :80 (Remote: 112.126.95.71, Referer: )
2019/10/05 10:15:49 [INFO] 47.74.133.151 - No such site at :80 (Remote: 112.126.95.71, Referer: )
2019/10/05 10:57:25 [INFO] 47.74.133.151 - No such site at :80 (Remote: 104.211.216.163, Referer: )
2019/10/05 12:00:31 [INFO] 47.74.133.151 - No such site at :80 (Remote: 171.67.70.80, Referer: )
2019/10/05 12:32:50 [INFO] 47.74.133.151 - No such site at :80 (Remote: 173.249.60.176, Referer: )
2019/10/05 12:37:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 15:27:14 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 15:46:15 [INFO] 47.74.133.151 - No such site at :80 (Remote: 94.222.113.146, Referer: )
2019/10/05 17:41:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 213.129.163.236, Referer: )
2019/10/05 18:15:42 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 18:52:02 [INFO] 47.74.133.151 - No such site at :80 (Remote: 182.74.195.242, Referer: )
2019/10/05 20:58:11 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 21:54:04 set tcp 172.21.31.111:80->95.215.0.232:61082: setsockopt: connection reset by peer

last occur of 80 port:
2019/10/04 19:12:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/04 19:14:30 [INFO] 47.74.133.151 - No such site at :80 (Remote: 202.160.147.182, Referer: )
2019/10/04 19:21:37 [INFO]  - No such site at :80 (Remote: 187.135.115.116, Referer: )
2019/10/04 19:38:11 [INFO]  - No such site at :80 (Remote: 157.245.184.21, Referer: )
2019/10/04 21:24:34 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:35 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:35 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:36 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:38 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:39 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:24:39 [INFO] 47.74.133.151 - No such site at :80 (Remote: 51.83.234.52, Referer: )
2019/10/04 21:55:10 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/04 22:34:28 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.56.106.4, Referer: )
2019/10/04 22:34:30 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.56.106.4, Referer: )
2019/10/04 23:58:22 [INFO] www.google.com - No such site at :80 (Remote: 107.172.15.10, Referer: )
2019/10/04 23:58:23 [INFO] www.google.com - No such site at :80 (Remote: 107.172.15.10, Referer: )
2019/10/05 00:40:32 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 02:23:58 [INFO] 47.74.133.151 - No such site at :80 (Remote: 197.254.91.98, Referer: )
2019/10/05 03:02:47 [INFO] 47.74.133.151 - No such site at :80 (Remote: 138.97.224.145, Referer: )
2019/10/05 03:27:37 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 03:28:29 [INFO] 47.74.133.151 - No such site at :80 (Remote: 181.196.240.74, Referer: )
2019/10/05 05:01:15 [INFO] 47.74.133.151 - No such site at :80 (Remote: 183.129.160.229, Referer: )
2019/10/05 05:03:18 [INFO] 47.74.133.151 - No such site at :80 (Remote: 36.89.17.189, Referer: )
2019/10/05 06:30:33 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 09:02:17 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.111.126.250, Referer: )
2019/10/05 09:02:17 [INFO] 47.74.133.151 - No such site at :80 (Remote: 47.111.126.250, Referer: )
2019/10/05 09:28:40 [INFO]  - No such site at :80 (Remote: 95.222.17.192, Referer: )
2019/10/05 09:40:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 10:15:49 [INFO] 47.74.133.151 - No such site at :80 (Remote: 112.126.95.71, Referer: )
2019/10/05 10:15:49 [INFO] 47.74.133.151 - No such site at :80 (Remote: 112.126.95.71, Referer: )
2019/10/05 10:57:25 [INFO] 47.74.133.151 - No such site at :80 (Remote: 104.211.216.163, Referer: )
2019/10/05 12:00:31 [INFO] 47.74.133.151 - No such site at :80 (Remote: 171.67.70.80, Referer: )
2019/10/05 12:32:50 [INFO] 47.74.133.151 - No such site at :80 (Remote: 173.249.60.176, Referer: )
2019/10/05 12:37:29 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 13:41:46 [INFO] 47.74.133.151 - No such site at :80 (Remote: 123.56.245.155, Referer: )
2019/10/05 15:27:14 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 15:46:15 [INFO] 47.74.133.151 - No such site at :80 (Remote: 94.222.113.146, Referer: )
2019/10/05 17:41:37 [INFO] 47.74.133.151 - No such site at :80 (Remote: 213.129.163.236, Referer: )
2019/10/05 18:15:42 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 18:52:02 [INFO] 47.74.133.151 - No such site at :80 (Remote: 182.74.195.242, Referer: )
2019/10/05 20:58:11 [INFO]  - No such site at :80 (Remote: 103.59.156.16, Referer: )
2019/10/05 21:54:04 set tcp 172.21.31.111:80->95.215.0.232:61082: setsockopt: connection reset by peer

## 8. Why is this a bug, and how do you think this should be fixed?

i deploy the cfg on GNU/Linux CentOS,it works ok.
i think it is a system-related bug of caddy on freebsd.

## 9. What are you doing to work around the problem in the meantime?

i have no idea now, i have to restart it with days intervals.

## 10. Please link to any related issues, pull requests, and/or discussion.

not now.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

it provides great solution for https. i like it.

**Comment by mholt** [comment]
Thank you for filling out the issue template! But why did you redact your domain names? :( Now this will be harder.

These logs happen when Caddy receives requests with a Host header that is not in your Caddyfile. In this case, 47.74.133.151 may be your machine's IP address (maybe, but maybe not), but Caddy is only configured to serve the sites xxx.xzx.im yyy.xzx.im.

So some bot or something is just making lots of requests to your server that it isn't configured to handle. That's good news, it's not really an issue with Caddy.

**Comment by mholt** [comment]
Hmm upon a closer read I wonder if it's more related to https://github.com/caddyserver/caddy/pull/2787 which is fixed on master? Can you try the latest on master and see?

**Comment by sharljimhtsin** [comment]
> Hmm upon a closer read I wonder if it's more related to https://github.com/caddyserver/caddy/pull/2787 which is fixed on master? Can you try the latest on master and see?

ok,i will try the latest master code,and report later.

**Comment by sharljimhtsin** [comment]
after days watching,it looks good.thx
