### ISSUE TITLE
v2: reverse proxy HTTPTransport may need add param MaxIdleConnsPerHost

### ISSUE THREAD

**Issue by yzongyue** [caddyserver/caddy#2805]
## 1. Which version of Caddy are you using (`caddy -version`)?

branch v2

## 2. What are you trying to do?

measure reverse proxy latency

## 3. What is your Caddyfile?
```text
http://127.0.0.1:8081 {
    reverse_proxy / 127.0.0.1:8080 {
    }
}

```

a simple hello world app run on :8080, 
helloworld app avg latency: 365us
caddy avg latency: 2.94ms
caddy with param `MaxIdleConnsPerHost` avg latency: 679us

after use pprof debug caddy v2, i realized that there's too many sycall/connect, 
so i try to add  `MaxIdleConnsPerHost: 1000` in `HTTPTransport` , it works, the
avg latency fallen from 2.94ms to 679us

modules/caddyhttp/reverseproxy/reverseproxy.go:95

![image](https://user-images.githubusercontent.com/6824651/66642783-f7793c80-ec4f-11e9-94ee-897e02b6739b.png)

![image](https://user-images.githubusercontent.com/6824651/66642828-12e44780-ec50-11e9-884d-9f3cec0f6d80.png)

**Comment by mholt** [comment]
Ohh this looks great! Thank you for testing this. Do you want to submit a pull request?
