### ISSUE TITLE
multi sites, php not resolve

### ISSUE THREAD

**Issue by sharoue** [caddyserver/caddy#2816]
my Caddyfile like this, but php only work at the first site, the site ooxx.net turns out Access denied.
How to make php works at all sites? Is there any way to make settings like fastcgi and gzip to be public for all sites?

```
http:// {
    root /var/www/html
    gzip
    fastcgi / /run/php-fpm/www.sock php {
         ext .php
         split .php
         index index.php
    }
}

ooxx.net {
    root /var/www/ooxx.net
    gzip
    tls mail@ooxx.net
    fastcgi / /run/php-fpm/www.sock php {
         ext .php
         split .php
         index index.php
    }
}
```

**Comment by sharoue** [comment]
i added error log in the ooxx.net settings using
```
errors /var/log/caddy/error.log
```
 log file show that
Unable to open primary script /var/www/ooxx.net/xxoox.php

my php-fpm and the listen user run as the same user as caddy with www-data 
and /var/www/html and /var/www/ooxx.net has change the owner to www-data
seems that all of them is correct

**Comment by francislavoie** [comment]
Please ask on https://caddy.community, this is the board for bugs/feature requests.
