### ISSUE TITLE
OpenBSD pledge

### ISSUE THREAD

**Issue by gsquire** [caddyserver/caddy#2817]
## 1. What would you like to have changed?
I think it would be beneficial to add a call to [`pledge`](https://man.openbsd.org/pledge.2) at startup for OpenBSD servers.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
`pledge` would restrict the caddy process to only being able to invoke the system calls that it needs to function. This would in turn reduce the chances of any errant system calls that could potentially cause issues on the host. It is an easy way to reduce the attack vector and has been implemented in several [OpenBSD](https://www.openbsd.org/plus65.html) [releases](https://www.openbsd.org/plus66.html).

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
This isn't strictly necessary to add to caddy and could pose problems. If the pledge promises are incorrect, functionality could be limited and cause issues for OpenBSD users. It would require some investigation at first to ensure that the correct subset of promises gets implemented.

It would also add another dependency to the binary to be able to abstract the call via Go's [sys package](https://github.com/golang/sys/blob/master/unix/pledge_openbsd.go). Of course this would be conditionally compiled but there is no way to conditionally add it to the list of modules as far as I know.

**Comment by jungle-boogie** [comment]
hi,

I support this feature.
There are some events/presentations regarding pledge available here:

https://www.openbsd.org/events.html
