### ISSUE TITLE
Why remove support for tls1.1 in caddy 2.0

### ISSUE THREAD

**Issue by liuxingbaoyu** [caddyserver/caddy#2819]
Tls1.1 still has many users in use, why it was deleted in 2.0?
Is it possible to add an option to enable tls1.1 in 2.0?
Thanks.

**Comment by mholt** [comment]
Because TLS 1.1 is over 13 years old and is insecure.

What do you need TLS 1.1 for?

**Comment by liuxingbaoyu** [comment]
I have a website for non-browser users, my customers even want me to support winhttp with winxp.

I want to keep the default minimum version to tls1.2, but keep tls1.0 and tls1.1 in the support list.

It does not affect other users, and people who need it like me can also use it conveniently.

**Comment by jungle-boogie** [comment]
You have to draw the line somewhere. If TLS1.1 support is continued in Caddy v2, when would you think it needs to die? Caddy v3?

**Comment by liuxingbaoyu** [comment]
> You have to draw the line somewhere. If TLS1.1 support is continued in Caddy v2, when would you think it needs to die? Caddy v3?

I think it can be kept all the time, because it won't affect other users, it will not cause additional development costs, and there are always some users who need these things.

**Comment by mholt** [comment]
I would just continue using Caddy 1 then, I don't think introducing weak protocols into brand new software is a good idea.

**Comment by liuxingbaoyu** [comment]
I also hate these old things, but sometimes I have to support them.

**Comment by liuxingbaoyu** [comment]
> I would just continue using Caddy 1 then, I don't think introducing weak protocols into brand new software is a good idea.

Will caddy1 continue to be maintained? Otherwise I think it will be even worse.
These old things will not affect any other users, only the people who need it will modify it in the configuration file.

**Comment by jungle-boogie** [comment]
> I think it can be kept all the time

Do you expect golang to always support TLS1.1? Do they still have support for 1.0?

> there are always some users who need these things.

Yes, but that generally means they're stuck on old versions of hardware and software. Sounds like that's the case your users are in, for better or worse.

**Comment by liuxingbaoyu** [comment]
> > I think it can be kept all the time
> 
> Do you expect golang to always support TLS1.1? Do they still have support for 1.0?
> 
> > there are always some users who need these things.
> 
> Yes, but that generally means they're stuck on old versions of hardware and software. Sounds like that's the case your users are in, for better or worse.

Yes, they should upgrade to the updated version, but I can't make them change.
In fact, I am very interested in http3.0, but I have to support these old things.
I don't know when golang will remove it, but I hope to continue supporting it without additional development costs.

**Comment by mholt** [comment]
I don't know how long Caddy 1 will be maintained. Microsoft no longer supports Windows XP, and [even GitHub doesn't use TLS 1.1 anymore](https://www.ssllabs.com/ssltest/analyze.html?d=github.com).

@jungle-boogie is right... we cannot continue to support weak protocols forever, especially when you can still get this yourself by using Caddy 1, or after it is not maintained, just building Caddy 2 from source and adding 1 line to the code to enable it.

Sorry, but we won't turn on TLS 1.1 in Caddy 2. The incentives just are not good enough, and the alternatives aren't bad.

**Comment by francislavoie** [comment]
Just to clarify, this is the commit where it was removed in v2: https://github.com/caddyserver/caddy/commit/2cb01d43cf1647bc46e2c7a114c952925524ebe1 You should be able to just revert this change in your fork to allow 1.1 support.

**Comment by morpig** [comment]
Hi, I know this is not supported anymore, but I tried recompiling by adding back those values https://github.com/caddyserver/caddy/commit/2cb01d43cf1647bc46e2c7a114c952925524ebe1. 

However, after adding tls1.0 (even tried as far to ssl3.0) as tls minimum version in Caddyfile, it still wont establish any handshakes. Any ideas why?

```
domain {
	tls {
		protocols ssl3.0
		ca_root /opt/ssl/root.pem
	}
	reverse_proxy proxy.local:8080
}
```

openssl result:
```
CONNECTED(00000003)
139777225025176:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1626285483
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Any help would be much appreciated.

**Comment by mholt** [comment]
@morpig Please ask your questions on the forums, with enough details to reproduce the behavior, and someone will be happy to help you: https://caddy.community
