### ISSUE TITLE
A equivalent for nginx map module

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#2824]
## 1. What would you like to have changed?
This is the issue for https://caddy.community/t/whats-a-equivalent-for-nginx-map-module/6111/2

We use the [nginx map](http://nginx.org/en/docs/http/ngx_http_map_module.html) for some dynamic directory decisions.

That's the config snipped.

```
# configuration file /home/nginx/server/conf/global_map_data_storage.conf:
map $camid_date $storageid {
  default 3;

  include /home/nginx/server/conf/global_map_data_storage_data.conf;
}

# configuration file /home/nginx/server/conf/global_map_data_storage_data.conf:
'7/2010/08/10' 10;
'7/2010/08/11' 10;
'7/2010/08/12' 10;
'7/2010/08/13' 10;
'7/2010/08/14' 10;
...
536491 more lines
11M file size

# configuration file /home/nginx/nginx.conf

    location ~ /cams/(\d+)/\w+\.(jpg|xml)$ {
      set  $camid $1;
      root /web/data/data$storageid;
   }
```

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

With the map is it possible to create dynamically routing decisions.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

I still use nginx as webserver.

## 4. Please link to any relevant issues, pull requests, or other discussions.

https://caddy.community/t/whats-a-equivalent-for-nginx-map-module/6111

**Comment by mholt** [comment]
Is a literal map lookup all that is needed? Or do we have to consider fancy types of lookups like IP ranges? I ask because at scale the data structure matters _significantly_. Iterating a list of CIDR ranges for example is not efficient like a map lookup, but a hashmap lookup won't really do for CIDR ranges.

Do you just need to map a string to some value?

**Comment by git001** [comment]
> Do you just need to map a string to some value?

Exactly, well it's like a string or regex search. That's the exact definition for the map module

"The ngx_http_map_module module creates variables whose values depend on values of other variables."

That's the config signature.
`map string $variable { ... }`

Have you seen the doc  
http://nginx.org/en/docs/http/ngx_http_map_module.html#map

**Comment by mholt** [comment]
Yep, I've seen it. But I frankly don't care what nginx does :wink: I want to know what your actual needs are.

**Comment by mholt** [comment]
Excellent, thank you for the details!! I am excited to work on this more, but right now my priorities are finishing up logging, some needed enhancements to the TLS app, working on the admin endpoint, and adding more tests.

In the meantime, feel free to continue discussion here and even submit a PR after that. Especially welcome would be specific implementation details for this feature.

**Comment by git001** [comment]
any update on this issue?

**Comment by mholt** [comment]
Nope. It's not a priority right now, but we can get it implemented right away if you're able to fund its development. Right now our primary goal is to get 2.0 released.

Let me know if you'd like us to develop this for you!

**Comment by git001** [comment]
Thank you for your offer, it's not as important as the last funded feature ( #2012 ) , therefore I will close the issue.

**Comment by mholt** [comment]
I still want it eventually though so I'll keep this open :)
