### ISSUE TITLE
Reverse proxy using client certificates?

### ISSUE THREAD

**Issue by Askill** [caddyserver/caddy#2832]
## 1. What would you like to have changed?

Is there a way to redirect traffic and send client certificates with the request?

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

I would like to use this in a easy to configure service mesh as the side car proxy.

**Comment by Askill** [comment]
It's called forward proxy and already a thing...

**Comment by mholt** [comment]
@Askill Did you mean to close this?

**Comment by Askill** [comment]
Yes, I am new to the topic and didn't know what I wanted.
