### ISSUE TITLE
error after change the path of root

### ISSUE THREAD

**Issue by maomosi** [caddyserver/caddy#2838]
The original Caddyfile is something like this:
````original
example.com {
    gzip
    root /etc/caddy
}
````
And everything was fine ,I can access to example.com by HTTPS.
Then I want to redirect the site to another folder ,so I change to root path to another folder make the Caddyfile like this:
````after
example.com {
    gzip
    root /etc/caddy/test
}
````
After I restart the caddy service by `systemctl restart caddy`,the status of caddy is failed and there is an error: **error inspecting server blocks: duplicate site key: example.com** .
This error google me to the [caddy/caddyhttp/httpserver/plugin.go page](https://github.com/caddyserver/caddy/blob/8c860641b9fa48704d5fe707187968419621c85c/caddyhttp/httpserver/plugin.go#L145).The error still remains when I change back the root path to the original one.I am not familiar with the go language and newbie to caddy, could you give me some tips about what the problem is and how can I fix the error?

**Comment by mholt** [comment]
Hi, can you please revise your post and fill out the issue template? Currently there is not enough information to help you.
