### ISSUE TITLE
error after changing the path of root

### ISSUE THREAD

**Issue by maomosi** [caddyserver/caddy#2839]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy v1.0.3 (h1:i9gRhBgvc5ifchwWtSe7pDpsdS9+Q0Rw9oYQmYUTw1w=)

## 2. What are you trying to do?

After building a  website www.example.com  using a Caddyfile as below,I want to test a new html page in another folder(/etc/caddy/newfolder).So I change the  the root path in Caddyfile.

## 3. What is your Caddyfile?
**Caddyfile before changing**
```text
example.com {
    tls myemail@gmail.com
    gzip
    timeouts none
    proxy / https://google.com{
        except /test
    }
    proxy /test 127.0.0.1:10240 {
        without /test
        websocket
    }
}
www.example.com {
    gzip
    root /etc/caddy
}

```
**Caddyfile after changing**
```text
example.com {
    tls myemail@gmail.com
    gzip
    timeouts none
    proxy / https://google.com {
        except /test
    }
    proxy /test 127.0.0.1:10240  {
        without /test
        websocket
    }
}
www.example.com {
        gzip
        root /etc/caddy/newfolder
}

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp

## 6. What did you expect to see?

I  want the www.example.com refer to the index.html in folder /etc/caddy/newfolder

## 7. What did you see instead (give full error messages and/or log)?

Cannot browser www.example.com now.And when I check the status of caddy,it show an error: **error inspecting server blocks: duplicate site key: www.example.com** .And when I change the root path back to /etc/caddy,the error seems remaining.

## 8. Why is this a bug, and how do you think this should be fixed?

I thought the error is related to  referring  a site to different root folders,And I do not think this is a bug,it may becauses  I misconfigure the Caddyfile.I goolge this error message,and it refer to  the https://github.com/caddyserver/caddy/blob/8c860641b9fa48704d5fe707187968419621c85c/caddyhttp/httpserver/plugin.go#L145

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Maybe because it can automatically register certification,and configure easily,but when I get an error,I have no idear how to start.

**Comment by Mohammed90** [comment]
To start, you're missing a closing brace `}` for the first website.

**Comment by maomosi** [comment]
> To start, you're missing a closing brace `}` for the first website.

Yeah,you are right,I have copied that by mistake.Have updated,Thanks

**Comment by maomosi** [comment]
Got the reason why...Before I change the root path,I backup the Caddyfile into another name Caddyfile.bak,but put them in the same folder /etc/caddy.That is why the caddy say there are duplicate site key.Move the backup file into another folder,everything go well.
