### ISSUE TITLE
New grace period to continue allowing new connections before shutting down

### ISSUE THREAD

**Issue by mxrlkn** [caddyserver/caddy#2843]
## 1. What would you like to have changed?

Be able to define a ping healtcheck url that'll return a 200 status code when caddy is running, and return another status code when caddy is about to go down, via http. And also a grace period of x seconds caddy should keep running before shutting down. In this period, the healthcheck should not return a 200 status code.

An added bonus would be that you can only reach the healthcheck url if you're hitting the ip without a domain. That would then not block other virtual hosts to use that path themselves.

xxx.xxx.xxx.xxx/ping -> 200
example.com/ping -> normal request

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

If you're running several caddy instances behind a load balancer then this will allow the load balancer to know when to stop routing traffic to that instance, before caddy goes down.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Living with the very few seconds of downtime. I guess I could manually remove and add servers that I know will go down temporarily. But it's a hassle.

## 4. Please link to any relevant issues, pull requests, or other discussions.

https://caddy.community/t/ping-url-healthcheck/6427

**Comment by mholt** [comment]
Yeah that's a good point. If caddy is shutting down then why should it continue to accept new connections in order to say "I'm shutting down"?

**Comment by mxrlkn** [comment]
In the grace period it should keep accepting all requests (and new ones) _except_ the health check endpoint. So you set the grace period to 5 seconds, and then your load balancer to say: if this health check endpoint is not returning a 200 every second for 5 seconds, disable the server from the load balancer.

I don't know how all load balancers work, but this is how Digital Oceans work. So you get 0 downtime if you tell caddy to shutdown. Then you don't have to manually remove the server from the load balancer before you shutdown caddy.

I'm kinda surprised not more people are interested in this issue. I thought this was pretty common in the load balancer world.

**Comment by francislavoie** [comment]
> In the grace period it should keep accepting all requests (and new ones) except the health check endpoint.

But if Caddy allowed new connections late in the grace period, then when Caddy shut down it would just terminate those connections without having a chance to respond. That doesn't seem like a good idea.

**Comment by mxrlkn** [comment]
Oh right, I forgot that part. I just now remember that Traefik has this feature and just looked it up. https://docs.traefik.io/routing/entrypoints/#lifecycle

It has a graceTimeOut and a requestAcceptGraceTimeout. I guess that's how they combat that.

**Comment by francislavoie** [comment]
v1 definitely had the same grace period concept: https://github.com/caddyserver/caddy/blob/v1/caddy.go#L65

**Comment by mxrlkn** [comment]
Oh okay, It's been a while :)

But yeah I remember the way traefik does it worked really well.

**Comment by mholt** [comment]
I am almost finished with this. It's working -- and I even have new placeholders `{http.shutting_down}` and `{http.time_until_shutdown}` that reveal this information in handlers like for simple health check endpoints!

But on config reloads, the "shutdown delay" (period of time before the grace period starts, where server stops accepting connections) happens after the new config is already running, so new connections will randomly either get the old server or the new one.

So perhaps a more proper implementation of this requires that it happens before the config change even begins. Which is a little trickier. I may need to implement a new hook or something that can be called on apps before a config reload takes place.

**Comment by mxrlkn** [comment]
I'll check it out soon! I can't comment on config reloads as I never used that part. But I will test healthcheck :)

**Comment by mholt** [comment]
Yeah, so I'm really thinking this should only be enforced on actual shutdown, not config reload.

The problem is that a config reload could still be shutting down the listener if the port is no longer being used.

I might see if we can be clever about this, since we do keep counts as to how many consumers there are of a listener socket. Hmm.

**Comment by mholt** [comment]
I've updated the PR and am pretty happy with its implementation now. Will merge soon.
