### ISSUE TITLE
How to conver .htaccess file

### ISSUE THREAD

**Issue by ddvcx** [caddyserver/caddy#2847]
htaccess file  like this.
how make this work in caddy

Options -Indexes
order deny,allow

<Files ~ "^.(htaccess|htpasswd)$">
deny from all
</Files>

<Files ~ "^database.db">
deny from all
</Files>

RewriteEngine On
RewriteCond $1 !^(api|asset)
RewriteRule ^(\d+|\w+)$ index.php?id=$1

**Comment by francislavoie** [comment]
You've already closed this, but for next time, this sort of question is best asked on https://caddy.community
