### ISSUE TITLE
v2: Access controls for admin API

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#2850]
It's time to implement the access controls promised for Caddy's API.

# Proposal

By default, there will be no access controls, as the default listener binds to the loopback interface; we do not offer any guarantees if untrusted code is running on the machine. Even if the listener is configured more openly, Caddy 2 can also be started with an initial config with access controls so that an exposed admin endpoint is never unprotected for any period of time.

Access controls consist of users or accounts. Users have a list of tokens and permissions. Tokens are secret credentials. By having each user associated with tokens, this allows tokens to be rotated while preserving permissions, which are pinned to individual users.

Consider this structure:

```go
// AdminConfig configures the admin endpoint.
type AdminConfig struct {
	Listen string               `json:"listen,omitempty"`
	Access map[string]AdminUser `json:"access,omitempty"`
}

// AdminUser is an admin user account.
type AdminUser struct {
	Tokens      []AdminToken               `json:"tokens,omitempty"`
	Permissions map[string]AdminPermission `json:"permissions,omitempty"`
}

// AdminToken is a credential used for accessing the admin
// endpoint. It consists of a non-secret ID and a secret key.
type AdminToken struct {
	ID    string `json:"id"`
	Token string `json:"token"`
}

// AdminPermission represents permission to do requests
// with the given path using the listed methods.
type AdminPermission struct {
	Methods     []string `json:"methods,omitempty"`
	MaxBodySize int      `json:"max_body_size,omitempty"`
	Path        string   `json:"path,omitempty"`
}
```

An example of this config structure:

```go
"admin": {
	"access": {
		"userID": {
			"tokens": ["tkn_id"],
			"permissions": {
				"/config/apps/http/servers/customer1": ["GET"]
			}
		}
	}
}
```

This would allow user "userID" to only perform GET requests to the HTTP server named "customer1".

Because tokens are sensitive and unhashed, they are stored outside the config. By default, Caddy can store them in the storage configured with its config. The default storage is the same as with certificates and other assets: file storage at `$HOME/.local/share/caddy`, unless changed by the user or `$XDG_DATA_HOME`.

Tokens will exist in a secrets file in storage, consisting of one token per line (ID and secret key are separated by whitespace):

```
token_id   token_key
...
```

We may provide a CLI to help manage tokens:

```
$ caddy admin create-token
{"id": "...","secret":"..."}

$ caddy admin delete-token --id "token_id"
```

If the storage to be used is not the default, a config can be passed in with the `--config` flag that configures storage.

A configuration would be invalid if tokens overlap for any user, since that would allow those users to authenticate as each other.

**Comment by tobya** [comment]
This seems an interesting idea.  Is the primary use case for this Large Shared hosting solutions where users would update their own config on a running server?

Is there likely to be the necessity for a user based admin controls rather than simply a single username password  restriction.  Surely there only user that should have access to the admin console is the administrator of the webserver?

I'm just curious as to the real use case for this.

**Comment by mholt** [comment]
We may not need this feature to be so advanced right out of the gate, you're right.

I think the main concern is that some users can't trust all clients that have access to the admin socket.

On Unix systems, you can use a unix socket to control permissions regarding other users of the same computer. This is _slightly_ obscure to some newer users and can be difficult to set up properly sometimes. You wouldn't think of using unix file system features to control permissions to your web server process. (But that is what unix is good at!)

On Windows, you can't do that at all AFAIK because ports are not files.

Even so, it makes sense that the application itself should have some access controls for the few edge cases where you can't trust code or users on the same machine as your web server.

Granted, this _is_ a pretty niche use case, especially if the server is actually important or sensitive.

So the obvious answer is, "OK: we make it so that all requests have to be authenticated with some secret key." Easy enough with bearer authentication. How do you set the key? Env variable? Maybe. But Caddy 2 is trying to consolidate as much configuration as possible. So we put it in the JSON document. Secrets in a web server config... hm, not awesome. Okay. So maybe the secret is in an env variable, but the explicit use of that env variable is in the JSON config so that it's still clear what is going on and we don't introduce a hidden factor.

Do we need anything more than a secret/API key? Probably not for starters. And maybe that's what I should just implement for now.

But, yes, the hope is that this would make it easier to use Caddy as a _platform_ rather than "merely" a single-user web server.

**Comment by Lemmmy** [comment]
> By default, there will be no access controls, as the default listener binds to the loopback interface; we do not offer any guarantees if untrusted code is running on the machine.

![](https://i.lemmmy.pw/5Ll6.png)

:clown_face:

**Comment by steamp0rt** [comment]
> By default, there will be no access controls, as the default listener binds to the loopback interface; we do not offer any guarantees if untrusted code is running on the machine.

Wouldn't it be entirely possible for a malicious user to abuse an application's caching/thumbnailing function to make it connect to localhost, therefore compromising the admin API?

**Comment by mholt** [comment]
You'll have to be more specific.

In general -- and this goes for most threat models -- if the machine is running untrusted code, all bets are off; i.e. protecting against a system that has already been compromised is outside the scope of the threat model.

So yes, with the default configuration, if malicious code is allowed to connect to the a socket on the loopback interface, you've already been popped, regardless of what you can do with those requests. That's why web browsers prohibit cross-origin requests unless the server specifically allows them. And Caddy does not, by default.

If your production server is running untrusted code or applications which can be abused, then yes, I recommend turning on the access controls which are available.

**Comment by steamp0rt** [comment]
The point is, the default is _less secure_ than it should be. Any talk of "don't run abusable code/applications" is just dodging the issue. While I understand that this default may make it easier to manage the server for the host, but this is still an insecure default.

**Comment by mholt** [comment]
> the default is less secure than it should be. Any talk of "don't run abusable code/applications" is just dodging the issue.

I disagree. If your machine is already compromised then there's nothing a web server can do to protect you. Get an IDS instead.

If you can back up your opinion and provide a convincing demonstration of a practical attack on the admin endpoint that runs on a production server using the default settings without arbitrary code running on the machine, then let's see what we can do to patch it up. But until then, this is pointless banter.

**Comment by steamp0rt** [comment]
> If you can back up your opinion and provide a convincing demonstration of a practical attack on the admin endpoint that runs on a production server using the default settings without arbitrary code running on the machine, then let's see what we can do to patch it up. But until then, this is pointless banter.

My SSH server is unhackable!

Meanwhile... `iptables -A INPUT -p tcp --destination-port 22 -j DROP`

**Comment by mholt** [comment]
@steamp0rt 

> My SSH server is unhackable!

You're being facetious. I'm not claiming that Caddy is "unhackable" -- I'm claiming that this particular risk is outside the scope of its threat model.

Locking this thread for now until participants are willing to show that this conversation can stay on-topic and productive.
