### ISSUE TITLE
v2: Integrated scheduler for polling tasks in extensions

### ISSUE THREAD

**Issue by Arteneko** [caddyserver/caddy#2853]
I have an extension which may be configured to execute tasks every x minute - hour - day, and I wanted to know if Caddy integrated and provided a scheduler for said tasks, as to not bundle / stack yet another scheduler on top of a possibly existing one.

**Comment by francislavoie** [comment]
Just to clarify the terminology, you're talking about [Caddy modules](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#caddy-modules), right?

**Comment by mholt** [comment]
Hi @Arteneko ! I assume you mean that you extended Caddy by writing a module for it? Or that you want to write one? Either way, awesome! 😁👍 

Caddy does not have any built-in, generic scheduler. For long-running services like this, I recommend writing an _app module_ (one which gets `Start()`ed and `Stop()`ed by Caddy when a config is loaded/unloaded). When it is started, it can start the scheduler. When it is stopped, stop the scheduler.

In fact, if the scheduler app module is designed generic and flexible enough, it could make an excellent replacement for cron, and other apps could even use it if they wanted to schedule something. For example, the `tls` app solely manages certificates, and the `http` app actually loads and uses the `tls` app as a dependency. (Caddy 2 works well with shallow app dependencies, more than 1 deep isn't recommended, but 1 is usually okay!)

Anyway, I really like this idea. I would be happy to review any proposals or drafts you have!

**Comment by francislavoie** [comment]
There doesn't seem to be anything actionable here, so I'll close this for now.

Feel free to continue discussion though, if you want to come back to this.
