### ISSUE TITLE
v2: dns provider

### ISSUE THREAD

**Issue by wenerme** [caddyserver/caddy#2855]
## 1. What would you like to have changed?

add v2 dns provider modules

v1 support [dnsproviders](https://github.com/caddyserver/dnsproviders)

this is no `tls.dns.provider` module exists yet, need something like

```go
_ "github.com/caddyserver/caddy/v2/modules/dnsproviders" // general dns provider plugin
_ "github.com/caddyserver/caddy/v2/modules/dnsproviders/pdns" // specific dns provider
```

```go
func init() {
	caddy.RegisterModule(DnsProvider{})
}

type DnsProvider struct {
	Type     string `json:"type,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	Key      string `json:"key,omitempty"`

	provider challenge.ProviderTimeout `json:"-"`
}
```

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

use dns for tls challenge

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

use v1

**Comment by mholt** [comment]
Ah, yeah, I need to make these. Will probably work on that in the next few weeks.

**Comment by moqmar** [comment]
Will you support all DNS providers supported by LEGO? I missed `hostingde` on Caddy v1

**Comment by mholt** [comment]
That's the plan.

**Comment by wenerme** [comment]
https://caddyserver.com/ already use v2 as default, but dns acme provider still not ready? when can we expected this ?

**Comment by craigary** [comment]
This is the main reason prevent me from using CaddyServer 2, is there any plans to make it available in next beta release?

**Comment by mholt** [comment]
As soon as I can. I'm extremely resource-constrained right now. I was lucky enough to be able to extend the dev runway for a couple of months but right now it's all riding on either sponsorships or company funding. If your company is able to sponsor the development of these plugins, I will be able to work on them sooner!

**Comment by mcfedr** [comment]
Seems that some of these are available in https://github.com/caddyserver/tls.dns - i had this confused with https://github.com/caddyserver/dnsproviders/ which seems to be the same thing but for caddy 1

**Comment by mholt** [comment]
All DNS provider modules for v2 are now available at https://github.com/caddy-dns.

Until more DNS providers are ported over, you can use this shim module to support all 75+ of lego's DNS providers: https://github.com/caddy-dns/lego-deprecated

You can help implement DNS providers for Caddy 2 with this information here: https://caddy.community/t/writing-new-dns-provider-modules-for-caddy/7786
