### ISSUE TITLE
using caddy v2 and entering caddyfile config like in the website

### ISSUE THREAD

**Issue by x4080** [caddyserver/caddy#2856]
```
example.com # Your site's domain name

# Load balance between three backends with custom health checks
reverse_proxy 10.0.0.1:9000 10.0.0.2:9000 10.0.0.3:9000 {
	lb_policy       random_choose 2
	health_path     /ok
	health_interval 10s
}
```

And the result is 

```
run: adapting config using : parsing caddyfile tokens for 'reverse_proxy': Caddyfile:5 - Error during parsing: load balancing policy module 'http.handlers.reverse_proxy.selection_policies.random_choose' is not a Caddyfile unmarshaler
```

I'm trying caddy and immediately like it, but confuse how to set the reverse_proxy with multiple servers, I tried below and works but not with the above

```
reverse_proxy / localhost:3000
```

Did I do something wrong ?

BTW I'm using windows

**Comment by mholt** [comment]
Oops, lemme look into that real quick

**Comment by mholt** [comment]
Ah, it's because I haven't yet implemented the unmarshalers for the load balancing policies.

For now, you can remove the `lb_policy` line and just use the default (or you can drop down to Caddy's native JSON and have full control of its config there).

I'll update this issue once I've pushed the fix!

**Comment by x4080** [comment]
@mholt  Thanks

**Comment by mholt** [comment]
@x4080 Thanks for your patience. Fixed in bf363f0. Stay tuned for beta 9 in a little bit!

**Comment by mholt** [comment]
@x4080 Beta 9 has been released with this fix: https://github.com/caddyserver/caddy/releases/tag/v2.0.0-beta9

Please give it a try now and let me know how it goes! :+1:

**Comment by x4080** [comment]
@mholt Thanks, I'll try it
