### ISSUE TITLE
v2 Markdown Testing Feedback

### ISSUE THREAD

**Issue by gh-jwhite** [caddyserver/caddy#2860]
I have a use case, which is essentially I want to be able to write in markdown, run it across a template and serve largely static docs.  Search across the markdown content is also a nice-to-have for sure. As testing/feedback/help is desired on this (https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersmarkdown) ... here we go.

I have looked/am looking at Gatsby (too complex for my basic goal) and Hugo (looks good so far, also written in Go), but figured I should give Caddy a shot ... as I like it's https-by-default stance and general focus on being secure and performant by default.

So, that's my basic goal/needs and why I'm looking at it ... First, I've got to make sure I get my config sane ... will comment on that next if I am unable to get there quickly and otherwise post my feedback (and links to other pertinent issues) here as I go.

**Comment by mholt** [comment]
Cool!

First, have you seen the [templates](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#templates) handler? It has a lot of functions you might find helpful: https://github.com/caddyserver/caddy/wiki/v2:-Templates -- including a [`.Markdown`](https://github.com/caddyserver/caddy/wiki/v2:-Templates#markdown) function to render markdown.

Related issues would be: https://github.com/caddyserver/caddy/issues/2632 and https://github.com/caddyserver/caddy/issues/2736

#2736 seems especially relevant. I would like to find a way to merge the two handlers, but the question is how to know whether to execute a page as markdown containing templates, or templates containing markdown?

**Comment by gh-jwhite** [comment]
Haha ... wasn't paying attention to my windows and opened this in my test account. Going to self-close with my proper account. Sorry for the noise!
