### ISSUE TITLE
v2 Markdown Testing and Feedback

### ISSUE THREAD

**Issue by misfir3** [caddyserver/caddy#2861]
I have a use case, which is essentially I want to be able to write in markdown, run it across a template and serve largely static docs.  Search across the markdown content is also a nice-to-have for sure. As testing/feedback/help is desired on this (https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httphandlersmarkdown) ... here we go.

I have looked/am looking at Gatsby (too complex for my basic goal) and Hugo (looks good so far, also written in Go), but figured I should give Caddy a shot ... as I like its https-by-default stance and general focus on being secure and performant by default.

So, that's my basic goal/needs and why I'm looking at it ... First, I've got to make sure I get my config sane ... will comment on that next if I am unable to get there quickly and otherwise post my feedback (and links to other pertinent issues) here as I go.

**Comment by misfir3** [comment]
So, first question is ... 
does the v2 take any of the additional config [as does v1] (https://caddyserver.com/v1/docs/markdown)

namely ... ??
```
markdown [basepath] {
	ext         extensions...
	[css|js]    file
	template    [name] path
	templatedir defaultpath
}
```

**Comment by mholt** [comment]
Repasting from the previous issue...

First, have you seen the [templates](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#templates) handler? It has a lot of functions you might find helpful: https://github.com/caddyserver/caddy/wiki/v2:-Templates -- including a [`.Markdown`](https://github.com/caddyserver/caddy/wiki/v2:-Templates#markdown) function to render markdown.

Related issues would be: https://github.com/caddyserver/caddy/issues/2632 and https://github.com/caddyserver/caddy/issues/2736

#2736 seems especially relevant. I would like to find a way to merge the two handlers, but the question is how to know whether to execute a page as markdown containing templates, or templates containing markdown?

**Comment by mholt** [comment]
@misfir3 FYI, I got rid of the markdown handler and am using the templates handler for our new documentation site, which I'll be publishing in the next few days or weeks.

Basically, all URLs within `/docs/` are rewritten to `/docs/index.html`, and each markdown file is prefixed with "front matter" (structured metadata). The templated HTML page renders it:

```
{{$pathParts := splitList "/" .OriginalReq.URL.Path}}
{{$markdownFilename := default "index" (slice $pathParts 2 | join "/")}}
{{$markdownFilePath := printf "/docs/markdown/%s.md" $markdownFilename}}
{{$markdownFile := (include $markdownFilePath | splitFrontMatter)}}
<!DOCTYPE html>
<html>
<head>
     <title>{{default $markdownFilename $markdownFile.Meta.title}} &mdash; Caddy Documentation</title>
    ...
    {{markdown $markdownFile.Body}}
    ...
</html>
```

Or something like that.

So, I will close this for now, but feel free to continue the discussion! If this isn't what you had in mind, we can continue discussing it or even reopen the issue.

**Comment by casperdcl** [comment]
FYI my approach is:

- URL: `https://domain.com/some/prefix/some/path/to/file.md`
- disk: `/www/assets/some/path/to/file.md`

```caddy
domain.com {
  tls casperdcl@domain.com
  @datamd path_regexp /some/prefix/(.*\.md)$
  handle @datamd {
    root * /www/assets
    header Content-Type text/html
    templates
    respond <<HTML
    <!DOCTYPE html>
    <html>
    <head><title>{re.datamd.1}</title></head>
    <body>
    {{slice (splitList "/" .OriginalReq.URL.Path) 2 | join "/" | readFile | markdown}}
    </body>
    </html>
    HTML 200
  }
}
```

advantages:

- no need for separate [html templates](https://github.com/caddyserver/website/blob/master/src/docs/index.html) and [`rewrite`s](https://github.com/caddyserver/website/blob/master/Caddyfile)

notes:

- despite #3324, `{{placeholder "re.datamd.1" | readFile | markdown}}` doesn't work, presumably because `re` isn't captured.

**Comment by mholt** [comment]
That's very clever! Thanks for sharing.

**Comment by francislavoie** [comment]
> note: `{{placeholder "re.datamd.1" | readFile | markdown}}` doesn't work

That's because `{re.*}` is a [Caddyfile shortcut](https://caddyserver.com/docs/caddyfile/concepts#placeholders) (the braces matter) but if you use it in a template that shortcut replacement (done via a textual regexp on the Caddyfile content before parsing) doesn't happen. So you need to use the long form, `http.regexp.*` instead.
