### ISSUE TITLE
Possible bug ?

### ISSUE THREAD

**Issue by x4080** [caddyserver/caddy#2863]
Hi, I'm not sure if its a bug but here's my situation :

I have folder public/static with files in it

Here's my .json config that works with http://localhost:3000/static/

```
{
   "apps": {
      "http": {
         "servers": {
            "srv0": {
               "listen": [
                  ":3000"
               ],
               "routes": [
                  {
                     "match": [
                        {
                           "host": [
                              "localhost"
                           ],
                           "path": [
                              "/static"
                           ]
                        }
                     ],
                     "handle": [
                        {
                           "handler": "file_server",
                           "browse":{},
                           "root": "../public"
                        }
                     ]
                  }   
                          
               ]
            }
         }
      }
   }
}
```

but if we change the root to

```
"root": "../public/static"
```

It wont work, because http://localhost:3000/static/ need to go to folder static which is not exists in the folder ../public/static

I thought that the root folder dont need path to be included to go to that folder, so wouldnt it be nicer if 

```
"root": "../public/static"
```

already mappped to public/static and the  http://localhost:3000/static/ dont go to
 public/static/static ?

Thanks

If thats what the behaviour expected, how can I map http://localhost:3000/static/  directly to /public/static and not  /public/static/static ? 

Hope its not confusing

**Comment by x4080** [comment]
Nevermind, I read that its by design to include path into the file_server

**Comment by francislavoie** [comment]
FYI for next time, best to ask this type of question in https://caddy.community first if you're unsure on how to configure the server!

Thanks for following up once you figured out your issue.
