### ISSUE TITLE
It would be nice if `caddy adapt` printed errors to stderr rather than stdout

### ISSUE THREAD

**Issue by jfly** [caddyserver/caddy#2865]
I'm playing around with `caddy` 2, and am using `caddy adapt`. I'm basically running the server by doing this:

```
caddy adapt --config Caddyfile > caddy-config.json
caddy run --config caddy-config.json
```

When `caddy adapt` finds a problem with my `Caddyfile`, it exits nonzero, which is great. However, I don't end up seeing the reason why the config was bad, because it gets printed to stdout and ends up in `caddy-config.json`. If errors instead went to stderr, I would have seen the error, which would have made it easier for me to figure out what I'm doing wrong.

**Comment by mholt** [comment]
Thank you for trying Caddy 2 while we're still in beta! :+1:

That's interesting, why not just use `caddy run` (no flags needed)?

The Caddyfile is in the current directory, so it will automatically be used. 

`caddy adapt` is meant to be used interactively, hence printing errors to stdout.

But I guess we could print those to stderr? I don't have much of a preference either way. I just am intrigued by your workflow, which is unusual.

**Comment by jfly** [comment]
Oh neat! This is my first time using caddy, I did not know that `caddy run` would read a `Caddyfile`. I had gotten the (apparently wrong) sense from reading the docs that you had to feed caddy a json file.

**Comment by mholt** [comment]
No worries, it's in that suuper long temporary docs page we have on our wiki, [under the `run` command](https://github.com/caddyserver/caddy/wiki/v2:-Documentation#run):

> As a special case, if the current working directory has a file called "Caddyfile" and the caddyfile config adapter is plugged in (default), then that file will be loaded and used to configure Caddy, even without any command line flags.

I'll take a look at printing errors to stderr tomorrow!

**Comment by mholt** [comment]
@jfly Done in e4a2add73f2ed5e0f6c24ae1231bb73b2fcc72c1

Thank you!

**Comment by jfly** [comment]
Thank you for the quick turnaround!
