### ISSUE TITLE
Logger for admin module doesn't use "default" settings

### ISSUE THREAD

**Issue by pascalgn** [caddyserver/caddy#2868]
## 1. Which version of Caddy are you using (`caddy -version`)?

v2.0.0-beta9

## 2. What are you trying to do?

Format log output as JSON

## 3. What is your Caddyfile?

```json
{
  "logging": {
    "sink": {
      "writer": {}
    },
    "logs": {
      "default": {
        "level": "debug",
        "encoder": {
          "format": "json"
        }
      }
    }
  },
  "apps": {
    "http": {
      "servers": {
        "server-1": {
          "listen": [":443"],
          "routes": [
            {
              "match": [
                {
                  "host": ["localhost"]
                }
              ],
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "upstreams": [
                    {
                      "dial": "localhost:8080"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

Docker, `caddy run --config /etc/caddy/caddy.json`

## 5. Please paste any relevant HTTP request(s) here.

--

## 6. What did you expect to see?

Logging from "admin" module should be printed as JSON

## 7. What did you see instead (give full error messages and/or log)?

```
2019/11/08 16:34:34.253	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
{"level":"info","ts":1573230874.2566211,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1573230874.2566211,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1573230874.256688,"logger":"admin","msg":"Caddy 2 serving initial configuration"}
```

## 8. Why is this a bug, and how do you think this should be fixed?

First line in 7. should have been JSON

## 9. What are you doing to work around the problem in the meantime?

--

## 10. Please link to any related issues, pull requests, and/or discussion.

--

**Comment by mholt** [comment]
Thank you for filling out the issue template!

This is working, actually. Notice the last log line:

```
{"level":"info","ts":1573230874.256688,"logger":"admin","msg":"Caddy 2 serving initial configuration"}
```

That comes from the admin logger, and it is in JSON format.

The reason the first line is not in JSON format is because it is emitted before the config is loaded.

**Comment by pascalgn** [comment]
OK, but the specific line (`admin endpoint started`) seems to come from `replaceAdmin` and there we have a Config (unless it's nil), so maybe we could use it, if possible

**Comment by mholt** [comment]
This is a symptom of config updates being transactional: the new config is not "available" until the whole thing has completed. This is a good thing, allowing for many rapid config changes with some consistency (it's not 100% perfect I admit, but it's pretty good). But it also means that until the config is fully loaded, the old config remains the boss.
