### ISSUE TITLE
V2: Cannot load valid Caddyfile

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [caddyserver/caddy#2874]
## 1. Which version of Caddy are you using (`caddy -version`)?

7ff02f37b6cbdf8e73a47d94604672ca2f1f1aa7

## 2. What are you trying to do?

Start Caddy V2 with a valid Caddyfile

## 3. What is your Caddyfile?
```text
abdelmalek.ihdene.com
redir /portfolio permanent
reverse_proxy /portfolio {
	to node-one:8080 node-two:8080
	health_path /health
	health_status 200
	lb_policy random_choose 2
	transport http {
		read_buffer 4096
		tls
	}
}
```
Note: node-one and node-two are the valid but private IPV4 addresses of my nodes.

## 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy validate --config ~/Caddyfile --adapter caddyfile
caddy start --config ~/Caddyfile

## 6. What did you expect to see?

caddy validate --config ~/Caddyfile --adapter caddyfile
2019/11/09 21:53:39.399	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
Valid configuration
2019/11/09 21:54:01.199	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
Successfully started Caddy (pid=11577)

## 7. What did you see instead (give full error messages and/or log)?

2019/11/09 21:53:39.399	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
Valid configuration
run: loading initial config: decoding request body: invalid character 'a' looking for beginning of value
start: caddy process exited with error: exit status 1

## 8. Why is this a bug, and how do you think this should be fixed?

I can't get Caddy V2 to load a valid Caddyfile, self-explanatory.

## 9. What are you doing to work around the problem in the meantime?

Nothing so far.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

I would like to use Caddy V2 as a reverse-proxy/load-balancer in front of my Golang webservers.

**Comment by mholt** [comment]
Thanks for trying Caddy 2 while we're still in beta!

Your `start` command is missing the `--adapter` flag.

You need: `caddy start --config ~/Caddyfile --adapter caddyfile`

Notice that your `validate` command has it, so that's why it works.

Without it, Caddy is trying to parse your Caddyfile as JSON.

(Note that if your Caddyfile is in the current working directory, it will be used automatically without needing to specify either `--config` or `--adapter` flags)

**Comment by cweagans** [comment]
@mholt out of curiosity, is there a reason that the caddyfile adapter isn't the default? part of the initial draw to caddy for me was the simplicity, and this new json config format is definitely not that IMO.

**Comment by mholt** [comment]
@cweagans 

> is there a reason that the caddyfile adapter isn't the default

It actually _is_ the default -- if you run Caddy 2 in a folder with a file called `Caddyfile`, it will be used automatically, you don't even need to specify `--config` or `--adapter` flags: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#run

> As a special case, if the current working directory has a file called "Caddyfile" and the caddyfile config adapter is plugged in (default), then that file will be loaded and used to configure Caddy, even without any command line flags.

The Caddyfile will get converted to JSON for you under the hood.

> part of the initial draw to caddy for me was the simplicity, and this new json config format is definitely not that IMO.

Then don't use it :) Use the Caddyfile instead! That's why it's there.

**Comment by tobya** [comment]
I would support `--adapter caddyfile` being the default rather than `--adapter json`

**Comment by mholt** [comment]
@tobya But `json` isn't an adapter -- you don't need an adapter if you use JSON input.

**Comment by francislavoie** [comment]
This issue is totally getting offtopic but FWIW I would like if `--adapter` was an optional override, and the adapter would be guessed from the file extension/filename/contents, with `--adapter` overriding the guessing.

Some pseudocode:

```
if filename.endsWith('.json')
    use json
else if filename.endsWith('.json5')
    use json5
else if filename.endsWith('.jsonc')
    use jsonc
else if filename.toLowerCase().beginsWith('caddyfile')
    use caddyfile
else
    hasError = jsonParse(filename)
    if ! hasError
        use json
    else
        use caddyfile
```

**Comment by mholt** [comment]
I could get behind guessing by file name, when the `--adapter` flag is not specified.

But probably not so far as to parse the contents. JSON has too many similar variants that I'm scared to trust our guess simply by parsing.

We could generalize the if-then-else logic to simply check if the file ends in `"."+adapterName` (current adapters have names like `json5`, `jsonc`, and `yaml`). This won't work for all of them (e.g. nginx config files often end in `.conf` not `.nginx`), and we'll need to hard-code a special case for the Caddyfile, which I'm fine with.
