### ISSUE TITLE
caddy --version unknown

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#2875]
## 1. Which version of Caddy are you using (`caddy -version`)?

```
$ caddy --version
unknown
```

```
$ git describe
v1.0.3-14-gcc63eca
```

## 2. What are you trying to do?

I am building a server and want to receive `caddy --version` other than `unknown`.

I used to set it via `-X github.com/mholt/caddy/caddy/caddymain.gitTag=${PROJECT_VERSION}"`. Now, the project migrated to `caddyserver` and it does not work.

```
go get github.com/caddyserver/caddy
cd $GOPATH/src/github.com/caddyserver/caddy
PROJECT="github.com/caddyserver/caddy"
PROJECT_VERSION=`git describe`
mkdir -p ./bin
CGO_ENABLED=0 go build -v -o ./bin/caddy \
    -ldflags="-w -s \
    -X github.com/caddyserver/caddy/caddy.gitTag=${PROJECT_VERSION}" \
    -gcflags="all=-trimpath=${GOPATH}/src" \
    -asmflags="all=-trimpath=${GOPATH}/src" \
    ./caddy/main.go
```

## 3. What is your Caddyfile?

N/A.

## 4. How did you run Caddy (give the full command and describe the execution environment)?

N/A.

## 5. Please paste any relevant HTTP request(s) here.

N/A.

## 6. What did you expect to see?

Previously, my compiled binary output was:

```
# caddy.old --version
Caddy 0.11.4-6-g8a51198 (unofficial)
```

## 7. What did you see instead (give full error messages and/or log)?

```
# caddy --version
unknown
```

## 8. Why is this a bug, and how do you think this should be fixed?

I don't know whether it is a bug. I think it might be a good idea to spell out how to set it up.

## 9. What are you doing to work around the problem in the meantime?

N/A.

## 10. Please link to any related issues, pull requests, and/or discussion.

N/A.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Why do I use caddy:
* It is written in Go and the code is easily readable
* The community is great
* The project's contributors and the maintainer are responsible and promptly answer questions
* The documentation is all in Github (I don't like JIRA based systems)

**Comment by Mohammed90** [comment]
The variable `gitTag` went away as Caddy moved into Go's module way. What you can do now is to create a new Go module, have Caddy dependency, then delegate to `caddymain.Run` in your main func. That shall preserve the correct module version.

https://github.com/caddyserver/caddy/blob/cc63eca0c88da9de606aab8fda044e588222c8c5/caddy/caddymain/run.go#L290-L309

**Comment by mholt** [comment]
Yeah, and the step-by-step instructions (there are only like 3 steps) to build Caddy with version information are in the readme: https://github.com/caddyserver/caddy#build

**Comment by iddq** [comment]
caddy_v1.0.4_linux_386.tar.gz is still affected

**Comment by samuller** [comment]
Same issue seems to be happening with the current `alpine` package of Caddy. If you have this `Dockerfile`:

```Dockerfile
FROM python:3.8.18-alpine3.18

RUN apk update && apk add caddy
```
Build it with `docker build -t test-caddy:0.0.1 .` and then run and check the version - then it does the same:
```console
$ docker run test-caddy:0.0.1 caddy version
unknown
```

**Comment by mohammed90** [comment]
> Same issue seems to be happening with the current `alpine` package of Caddy. If you have this `Dockerfile`:
> 
> ```Dockerfile
> FROM python:3.8.18-alpine3.18
> 
> RUN apk update && apk add caddy
> ```
> Build it with `docker build -t test-caddy:0.0.1 .` and then run and check the version - then it does the same:
> ```console
> $ docker run --rm test-caddy:0.0.1 caddy version
> unknown
> ```
> (although the version can still be figured out from the package with `apk info caddy` )

This issue is 4 years old and isn't applicable anymore. It was reported for Caddy v1. The Alpine distribution of Caddy reports the version as `unknown` due to how Alpine builds the packages and not an issue with Caddy itself, see [here](https://caddy.community/t/caddy-service-wont-stay-running-or-start-with-boot-alpine-openrc/20912/10) for brief explanation by the maintainer of Caddy package on Alpine.

FYI, there's a [caddy Docker image](https://hub.docker.com/_/caddy) with Alpine base.
