### ISSUE TITLE
Does latest caddy v1 support tcp fast open (tfo)?

### ISSUE THREAD

**Issue by emiyalee1005** [caddyserver/caddy#2887]
If caddy support tfo, is it already enabled by default or need to add some config to let it work? Thanks.

**Comment by mholt** [comment]
It does not, currently: https://github.com/golang/go/issues/4842

Though it could be implemented: https://github.com/bradleyfalzon/tcp-fast-open/blob/be08570f28d00269d89d527e82db01697461780b/server.go#L31

Is this a feature request then?

**Comment by emiyalee1005** [comment]
Thanks,just a question
