### ISSUE TITLE
Content-Length is incorrect when using gzip on static files with HEAD

### ISSUE THREAD

**Issue by puckipedia** [caddyserver/caddy#2892]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0.3

## 2. What are you trying to do?

use gzip compression in combination with HEAD and static file hosting

## 3. What is your Caddyfile?
```text
localhost:2015
gzip
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy` on nixpkgs

## 5. Please paste any relevant HTTP request(s) here.

`curl -I --compressed http://localhost:2015/test.txt` (or any other file that exists and would be gzipped normally)

## 6. What did you expect to see?

a `Content-Encoding` of `gzip` and a `Content-Length` of about 13000, which is the size of the gzipped text file

## 7. What did you see instead (give full error messages and/or log)?

a `Content-Encoding` of `gzip` and a `Content-Length` of ... 23, always, no matter what file i try to read (presuming it gets gzip'd)

## 8. Why is this a bug, and how do you think this should be fixed?

The `Content-Length` does not match the gzip'd content, and instead matches the size of a gzip'd empty file, which is not what this is.

## 9. What are you doing to work around the problem in the meantime?
disabling compression :(

## 10. Please link to any related issues, pull requests, and/or discussion.
(N/A)

**Comment by mholt** [comment]
Pretty sure this is not an issue in v2.

**Comment by Erchoc** [comment]
@

> Pretty sure this is not an issue in v2 (meaning, if it is a bug in v1, we've fixed it in v2).

In fact, the V2 version also has this problem, you can see the Latest version v2.5.2

<img width="677" alt="image" src="https://user-images.githubusercontent.com/19908809/180418594-19e4fece-4016-43b9-b0f6-54bfd91a9f5b.png">

I only see v1.x handle this problem.

**Comment by mholt** [comment]
@Erchoc This issue is about v1 returning the wrong Content-Length value. We fixed it in v2 by removing the Content-Length header, I will explain in your more relevant issue.
