### ISSUE TITLE
unexpected address type

### ISSUE THREAD

**Issue by paniy** [caddyserver/caddy#2893]
## 1. Which version of Caddy are you using (`caddy -version`)?

2.0.0 beta 10

## 2. What are you trying to do?

only listen udp in port 443

## 3. What is your Caddyfile?
```
"srv0": {
				    "listen": ["udp/:443"],
				    "experimental_http3": true
            }
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy start --config ./caddy-conf.json` on Windows server 2019

## 5. Please paste any relevant HTTP request(s) here.

(N/A)

## 6. What did you expect to see?

only use udp not tcp

## 7. What did you see instead (give full error messages and/or log)?

```
run: loading initial config: loading new config: http app module: start: udp: listening on :443: listen udp :443: address :443: unexpected address type
start: caddy process exited with error: exit status 1
```

## 8. Why is this a bug, and how do you think this should be fixed?

sorry, i don't know.

## 9. What are you doing to work around the problem in the meantime?

not use caddy:(

## 10. Please link to any related issues, pull requests, and/or discussion.

(N/A)

## Bonus: What do you use Caddy for? Why did you choose Caddy?

because it's COOL!!!

**Comment by mholt** [comment]
That is because HTTP < 3 still needs TCP, and so does the upgrade to HTTP/3. Sorry, you will have to use TCP in the meantime.
