### ISSUE TITLE
No certificate available

### ISSUE THREAD

**Issue by focux** [caddyserver/caddy#2895]
## 1. Which version of Caddy are you using (`caddy -version`)?

 Caddy v1.0.4 

## 2. What are you trying to do?

I've been trying for two days to make the TLS on-demand to work and I haven't had any luck.

## 3. What is your Caddyfile?
```text
* {
    log stdout
    root ./www
    browse
    gzip
    tls {
     ask https://www.google.com
    }
}

*.domain.com:443 {
    root ./www
    browse
    gzip
    log stderr
    errors stderr
    tls /etc/letsencrypt/live/thridea.com/fullchain.pem /etc/letsencrypt/live/thridea.com/privkey.pem
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -log stdout

## 6. What did you expect to see?

I expect first, to be asked what's my email, then to agree to the LE TOS and then to see the TLS succeed.

## 7. What did you see instead (give full error messages and/or log)?

```
Nov 22 19:47:16 production-app caddy[13291]: [INFO] Serving https://*
Nov 22 19:47:16 production-app caddy[13291]: Serving HTTP on port 80
Nov 22 19:47:16 production-app caddy[13291]: http://*
Nov 22 19:47:16 production-app caddy[13291]: [INFO] Serving http://*
Nov 22 19:47:16 production-app caddy[13291]: [INFO][cache:0xc0000a07d0] Started certificate maintenance routine
Nov 22 19:47:17 production-app caddy[13291]: [INFO] Sending telemetry: success
Nov 22 19:47:22 production-app caddy[13291]: http: TLS handshake error from 179.53.91.106:49397: no certificate available for 'www.domain.com'
Nov 22 19:47:22 production-app caddy[13291]: http: TLS handshake error from 179.53.91.106:49398: no certificate available for 'www.domain.com'
Nov 22 19:47:23 production-app caddy[13291]: http: TLS handshake error from 179.53.91.106:46429: no certificate available for 'www.domain.com'
Nov 22 19:47:34 production-app caddy[13291]: http: TLS handshake error from 179.53.91.106:49428: no certificate available for 'www.domain.com'
```

## 8. Why is this a bug, and how do you think this should be fixed?

It's a new DO VPS that I bought to test and play with Caddy, I don't have anything else in front of it. In case you need it, I can provide credentials to the VPS for you to test it.

## 9. What are you doing to work around the problem in the meantime?

I don't really know what I can do as a workaround.

## 10. Please link to any related issues, pull requests, and/or discussion.

Related to #2773

**Comment by mholt** [comment]
>     tls /etc/letsencrypt/live/thridea.com/fullchain.pem /etc/letsencrypt/live/thridea.com/privkey.pem

I believe `thridea.com` is not a valid certificate for `www.domain.com`. The solution is simple: you have to provide a certificate that is valid for `www.domain.com`.

**Comment by focux** [comment]
Actually `thridea.com` is a valid certificate, and it works perfectly. What doesn't work is the first block:
```
* {
    log stdout
    root ./www
    browse
    gzip
    tls {
     ask https://www.google.com
    }
}
```

**Comment by mholt** [comment]
@focux 

> Actually thridea.com is a valid certificate, and it works perfectly.

What do you mean "it works perfectly"? I thought you were getting ` no certificate available for 'www.domain.com'`. How is that working perfectly?

**Comment by focux** [comment]
@focux I think I made a dumb mistake when trying to censor my domain name, sorry. The error is complaining about another domain that is not `*.domain.com:443 `. Sorry for bringing confusion.

**Comment by mholt** [comment]
Please update your issue with the complete and unredacted information then, please, as the issue template instructions state:

> paste entire Caddyfile here - DO NOT REDACT ANYTHING (except credentials)

Also fill out question 4, that will help relieve the ambiguity in your report. Right now this is not actionable or reproducible.

**Comment by focux** [comment]
Alright, I added more context to the issue. Sorry for the inconvenient.

**Comment by mholt** [comment]
Can you please use real domain names? That is essential to solving the problem.

**Comment by focux** [comment]
Sure, just change back the names.

**Comment by mholt** [comment]
Okay, thanks. We're finally making some progress.

`www.bookme.rocks` does not match any site you have configured, and thus does not match any TLS certificate configuration you've given. You will need to change either `*` or `*.thridea.com:443` (you can drop the `:443` by the way) or add a new site to match `www.bookme.rocks`.

**Comment by focux** [comment]
What I want to do it's to generate SSL certificates on-demand for custom domains, without having to create a new site for each domain. I'm working on a multi-tenant product and I want to allow the customers to map his domain to his product URL.

**Comment by focux** [comment]
```
* {
    log stdout
    root ./www
    browse
    gzip
    tls {
     ask https://www.google.com
    }
}
```
I thought that this block was for this, to generate TLS certificates on the flight, using LE.

**Comment by mholt** [comment]
According to [the docs](https://caddyserver.com/v1/docs/http-caddyfile):

> A site defined as `*` matches only one-label names like "localhost" but not "example.com". To match all hosts, leave the hostname empty.

This is because the relevant RFC (I forget its number right now, but it's mentioned several times on the issues here previously) restricts wildcards in this manner as they pertain to TLS certificates, and this same string value is what Caddy uses in its TLS certificate logic.

**Comment by focux** [comment]
Thank you so much, now it works perfectly. I had two days trying to find what I had wrong in my conf and it was as simple as that. Thank you again!

**Comment by ThayalanGR** [comment]
> According to [the docs](https://caddyserver.com/v1/docs/http-caddyfile):
> 
> > A site defined as `*` matches only one-label names like "localhost" but not "example.com". To match all hosts, leave the hostname empty.
> 
> This is because the relevant RFC (I forget its number right now, but it's mentioned several times on the issues here previously) restricts wildcards in this manner as they pertain to TLS certificates, and this same string value is what Caddy uses in its TLS certificate logic.

hey @mholt @focux do you have any idea about, how we can replicate this feature in kubernetes ingress controller as caddy ingress?
![image](https://user-images.githubusercontent.com/35830033/96738380-4669be00-13dc-11eb-9edf-6af9a6c9727a.png)

i'm catching all the domain of my multi-tendant app using the default backend of the ingress controller like this
![image](https://user-images.githubusercontent.com/35830033/96738565-7b761080-13dc-11eb-9132-931154e5f915.png)
![image](https://user-images.githubusercontent.com/35830033/96738635-8a5cc300-13dc-11eb-9f6b-b1f614f2e712.png)
in this scenario how i could omit the hostname as said in the caddy documentation?
Thanks in advance.
