### ISSUE TITLE
v2: query matcher

### ISSUE THREAD

**Issue by sarge** [caddyserver/caddy#2899]
Edit: removed "quotes" from query matcher as quotes in the config are not recommended.

## 1. Which version of Caddy are you using (`caddy -version`)?
v2 beta 10

## 2. What are you trying to do?
I am attempting to use a query parameter from the url and rewrite the request

```
matcher debug {
    query show=1
}

rewrite match:debug /debug/index.html
```

Extension: I would also like to add an extension to the query matcher to allow wildcards, this would allow matching on just the show parameter the value is irrelevant.

```
matcher debug {
    query show=*
}

rewrite match:debug /debug/index.html
```

Extension: use case 2 - passing a variable upstream if it exists

```
matcher debug {
    query version=*
}

rewrite match:debug /debug/{http.request.uri.query.version}/index.html
```

## 3. What is your Caddyfile?
```text
http://localhost:8099
tls off
root * . 

matcher debug {
  query "showdebug=1"
}

# redirect to the specified installer version
rewrite match:debug /debug/index.html

file_server
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
Fedora 31

caddy run --config Caddyfile2 --adapter caddyfile

## 5. Please paste any relevant HTTP request(s) here.
N/A

## 6. What did you expect to see?
The Caddyfile should  parse

## 7. What did you see instead (give full error messages and/or log)?
2019/11/27 09:52:32 run: adapting config using caddyfile: Caddyfile2:6 - Error during parsing: malformed query matcher token: query; must be in param=val format

## 8. Why is this a bug, and how do you think this should be fixed?
The syntax is valid

## 9. What are you doing to work around the problem in the meantime?
Avoid using the query matcher

## 10. Please link to any related issues, pull requests, and/or discussion.
MR to come :)

## Bonus: What do you use Caddy for? Why did you choose Caddy?
Clean extension model

**Comment by francislavoie** [comment]
Did you try without quotes? Reading the docs leads me to believe quotes should be excluded.

**Comment by sarge** [comment]
@francislavoie Thanks, I have just rechecked and it also fails without quotes. I have fixed the parsing locally, which does trigger another bug. So I am pretty sure no one is using the caddyfile with a query matcher.

**Comment by mholt** [comment]
Aha, indeed, I have yet to write tests for most (all?) of the matchers -- would definitely love to accept and review pull requests for this! Thanks!

**Comment by sarge** [comment]
@mholt I will make a start on the tests.
Any thoughts on the wildcard on the presence of a parameter in the query string? `showdebug=*` would match for any value of showdebug.

**Comment by mholt** [comment]
> `showdebug=*` would match for any value of showdebug.

Sure, that sounds good.

**Comment by francislavoie** [comment]
Is this ok to close now? Are your issues resolved? Thanks for the PR!

**Comment by mholt** [comment]
Yep, I believe this is resolved. If not let us know.
