### ISSUE TITLE
v2: IDs in JSON doesn't work properly

### ISSUE THREAD

**Issue by FrankGiesecke** [caddyserver/caddy#2902]
## 1. Which version of Caddy are you using (`caddy -version`)?
8de1a762273323608d9d9080c42057d1814070b6

## 2. What are you trying to do?
I'll try to use IDs in JSON to identify the objects in a servers 'routes' section.

**Base configuration JSON:**
```json
{
  "admin": {
    "disabled": false,
    "listen": ":2019",
    "enforce_origin": false,
    "origins": []
  },
  "apps": {
    "http": {
      "http_port": 8080,
      "https_port": 8443,
      "servers": {
        "proxy": {
          "listen": [
            ":8080",
            ":8443"
          ],
          "routes": [
          ]
        }
      }
    },
    "tls": {
      "automation": {},
      "session_tickets": {}
    }
  }
}
```

**Add first route using the API:**
```bash
$ curl -X POST -H 'Content-Type: application/json; charset=utf-8' http://localhost:2019/config/apps/http/servers/proxy/routes/ -d @- << EOF
{
  "@id": "foo",
  "match": [
    {
      "host": [
        "foo.localhost"
      ]
    }
  ],
  "handle": [
    {
      "handler": "reverse_proxy",
      "upstreams": [
        {
          "dial": "test.example.com:80"
        }
      ]
    }
  ]
}
EOF
```

**Add second route using the API:**
```bash
$ curl -X POST -H 'Content-Type: application/json; charset=utf-8' http://localhost:2019/config/apps/http/servers/proxy/routes/ -d @- << EOF
{
  "@id": "bar",
  "match": [
    {
      "host": [
        "bar.localhost"
      ]
    }
  ],
  "handle": [
    {
      "handler": "reverse_proxy",
      "upstreams": [
        {
          "dial": "test.example.com:80"
        }
      ]
    }
  ]
}
EOF
```

*Removing first route using the API:*
```bash
curl -X DELETE http://localhost:2019/id/foo/
```
But it results in:
```json
{"error":"unknown object ID 'foo'"}
```

## 3. What is your Caddyfile?
_All configurations are already shown in 2._

## 4. How did you run Caddy (give the full command and describe the execution environment)?
``` bash
$ caddy run --config /etc/caddy/config.json
```

## 5. Please paste any relevant HTTP request(s) here.
_none_

## 6. What did you expect to see?
The expectation is, that I can remove the route element form the list by using it's ID.

## 7. What did you see instead (give full error messages and/or log)?
```json
{"error":"unknown object ID 'foo'"}
```
It seems that only the last ID will be stored.

## 8. Why is this a bug, and how do you think this should be fixed?
It seems that only the last ID will be stored.

## 9. What are you doing to work around the problem in the meantime?
Currently, I'll fetch the whole `routes` list, search the entry I want to remove.
```bash
curl http://localhost:2019/config/apps/http/servers/proxy/routes/
```
Then I call delete using the index of the element.
```bash
curl -X DELETE http://localhost:2019/config/apps/http/servers/proxy/routes/1
```

## 10. Please link to any related issues, pull requests, and/or discussion.
_none_

**Comment by mholt** [comment]
Ah, thanks for the report. Working on a fix...

**Comment by mholt** [comment]
@FrankGiesecke Thanks to your detailed report and very easy reproduce instructions, I was able to find and fix the bug pretty easily. We were wiping out previous ID's, oops.

Now we preserve them, so you'll see them in your GET requests for current config. We just strip them out of the JSON internally using a regex. :joy: It works though. There is one other way we could do it... by deleting the `"@id"` fields as we find and index them (like we were before), then JSON-encode, then re-add the `"@id"` fields into our stored internal representation (`rawCfg`). We just have to make sure the resulting JSON doesn't have them, but our internal representation does. I just opted for the regex cause it's a quicker fix and seems to work pretty well.

Can you build from source (v2 branch) and try again and let me know how it goes for you?

**Comment by FrankGiesecke** [comment]
@mholt It works great 👍 
Thanks for the fast fix.

**Comment by mholt** [comment]
It's because your issue was so well-written. I will probably refer to it as a model for others.
