### ISSUE TITLE
v2: API changes gets lost during restart

### ISSUE THREAD

**Issue by FrankGiesecke** [caddyserver/caddy#2903]
## 1. Which version of Caddy are you using (`caddy -version`)?
8de1a762273323608d9d9080c42057d1814070b6

## 2. What are you trying to do?
A running instance of Caddy gets updates over the admin API.  
The instance will be restarted (shutdown, start). 

**Start caddy server**
```bash
$ caddy run --config /etc/caddy/config.json
```

**Fetch config after first start**
```bash
$ curl "http://localhost:2019/config/"
```
```json
{
  "admin": {
    "disabled": false,
    "enforce_origin": false,
    "listen": ":2019",
    "origins": []
  },
  "apps": {
    "http": {
      "http_port": 8080,
      "https_port": 8443,
      "servers": {
        "proxy": {
          "listen": [
            ":8080",
            ":8443"
          ],
          "routes": []
        }
      }
    },
    "tls": {
      "automation": {},
      "session_tickets": {}
    }
  }
}
```

**Add some configuration using the API**
```bash
$ curl -X POST -H "Content-Type: application/json; charset=utf-8" "http://localhost:2019/config/apps/http/servers/proxy/listen" -d '":8081"'
```

**Fetch new config**
```bash
$ curl "http://localhost:2019/config/"
```
```json
{
  "admin": {
    "disabled": false,
    "enforce_origin": false,
    "listen": ":2019",
    "origins": []
  },
  "apps": {
    "http": {
      "http_port": 8080,
      "https_port": 8443,
      "servers": {
        "proxy": {
          "listen": [
            ":8080",
            ":8443",
            ":8081"
          ],
          "routes": []
        }
      }
    },
    "tls": {
      "automation": {},
      "session_tickets": {}
    }
  }
}
```

**Restart caddy server**
```bash
$ curl -X POST "http://localhost:2019/stop"                                              
$ caddy run --config /etc/caddy/config.json
```

**Fetch config after restart**
```bash
$ curl "http://localhost:2019/config/"
```
```json
{
  "admin": {
    "disabled": false,
    "enforce_origin": false,
    "listen": ":2019",
    "origins": []
  },
  "apps": {
    "http": {
      "http_port": 8080,
      "https_port": 8443,
      "servers": {
        "proxy": {
          "listen": [
            ":8080",
            ":8443"
          ],
          "routes": []
        }
      }
    },
    "tls": {
      "automation": {},
      "session_tickets": {}
    }
  }
}
```

## 3. What is your Caddyfile?
```json
{
  "admin": {
    "disabled": false,
    "listen": ":2019",
    "enforce_origin": false,
    "origins": []
  },
  "apps": {
    "http": {
      "http_port": 8080,
      "https_port": 8443,
      "servers": {
        "proxy": {
          "listen": [
            ":8080",
            ":8443"
          ],
          "routes": [
          ]
        }
      }
    },
    "tls": {
      "automation": {},
      "session_tickets": {}
    }
  }
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
``` bash
$ caddy run --config /etc/caddy/config.json
```

## 5. Please paste any relevant HTTP request(s) here.
_none_

## 6. What did you expect to see?
In my expectation, all API changes will be available after a restart.

## 7. What did you see instead (give full error messages and/or log)?
The initial configuration

## 8. Why is this a bug, and how do you think this should be fixed?
Which sense makes an API to configure a server when the configuration gets lost during a restart?

## 9. What are you doing to work around the problem in the meantime?
I'll export the whole configuration using a cron script and use these configuration for the next start.

## 10. Please link to any related issues, pull requests, and/or discussion.
_none_

**Comment by mholt** [comment]
Caddy stores its config in memory, so if you restart the process, the config will be cleared.

It's in the plans to persist config to storage somewhere, somehow, and reuse it automatically when coming back up next time. Do you have any preferences regarding that, and how it should work?

**Comment by mholt** [comment]
FWIW, these were my thoughts:

By default, Caddy should persist its current configuration to the default storage, which is the local file system. It will persist the updated config every time it is updated/changed.

If Caddy is started without a config file, it should check storage to see if a previous config is stored there. If so, load and use it.

However, if Caddy is started with a config file, that config file overrides anything previously stored, and that config overwrites the previous one in storage. The storage defined in the config (if any) will be used; if not defined, the default will be used.

Nuance: The storage is configurable. How does Caddy know where to load its config from when starting without a config file? Solution: It doesn't know, so it just uses the default storage config. However, perhaps a config file can be provided which tells Caddy to load its config from somewhere. This is a good opportunity for us to make modules that tell Caddy how to get its config. In other words, you can give Caddy a config, but it's mostly empty: all it really does is say how to get the actual config it should use.

**Comment by FrankGiesecke** [comment]
Persisting the configuration in a configurable place sounds good.

It might be good, to define the storage in the config file.
This part of the configuration should always be used to find the persisted configuration.

It might be great, if the config file and the persisted configuration will be merged (the content of a key in the JSON File should replace the persisted information.
This will add the possibility, to start with a minimal config (only containing the storage and the admin API config). All further configuration can be done using the API.

If there is any need to reset some config parts, this can be done by adding them into the config file.

**Comment by mholt** [comment]
(FYI) I plan to revisit this soon

**Comment by mholt** [comment]
This is now implemented.

When a config is loaded or changed, it gets saved to disk. You can then resume from the last running config if you use `caddy run --resume`. (The `--resume` flag overrides any `--config` flag **if** a saved config exists.)

Be careful not to forget the `--resume` flag if making heavy use of the API in conjunction with an initial config from `--config`, or you might overwrite your changes! If entering these commands manually, I'd recommend just running without `--config` and using a POST for your initial config, then there's less risk you can accidentally overwrite all your incremental changes via the API.

**Comment by douglasg14b** [comment]
What is the resolution here? All config changes get lost when caddy is reloaded, which seems.... wrong?

Running as a service on Ubuntu server, after following the getting started guide. If the service is reloaded, all config items are lost, why is this?

**Comment by francislavoie** [comment]
The debian package comes with two service files, `caddy.service` and `caddy-api.service`. If you plan to use Caddy primarily with the API, you should disable the `caddy` service and enable the `caddy-api` service. The difference is that `caddy-api` uses the `--resume` argument, which makes it start up again using an autosaved version of your config (saved on every change). See here for more details about the services: https://caddyserver.com/docs/install#linux-service

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by douglasg14b** [comment]
Hi @francislavoie  Thanks for the reply! For better or for worse Github threads are highly prioritized by search engines, with forum threads being somewhat hidden.

<hr>

I solved the problem, or rather identified it's cause to be a set of awkward defaults:

The apt install of caddy sets the starting flag of `--config /etc/caddy/Caddyfile`, which seems to mean that whenever it's started any configuration changes made during runtime are lost, as the configuration is overridden to match that file when the service is started. Changes made via the API, `adapt`, or by `curl`ing a caddy file are all lost when the service is reloaded.

<hr>

For the purpose of this board, I believe this may be a big, or at the very least a significant lacking in the documentation. Almost the entirety of the getting started guide and other guides lead to frustration with this set of defaults.

This is further compounded by the message at the top of the install doc page:

> If you downloaded Caddy using a package manager such as apt or dnf, then Caddy is already installed, and you should jump to Getting Started.

**Comment by francislavoie** [comment]
> The effect being that ANY configuration performed is not persisted to the user, upon reload.

Actually, any config change will cause Caddy to write the active config to the config storage in an `autosave.json` file (probably `/var/lib/caddy/.config/caddy/autosave.json` unless you changed the storage location). See https://caddyserver.com/docs/conventions#configuration-directory. This behaviour can be turned off by setting `admin.config.persist` to false: https://caddyserver.com/docs/json/admin/config/

The `caddy.service` has `ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile` which says "reload Caddy using this config file".

The `caddy-api.service` does not have this, because the expectation is that you push any config changes you want to make yourself, via the API. `ExecStart` instead has `--resume`, which tells Caddy to use the `autosave.json` as the initial config, if one exists.

> For the purpose of this board, I believe this may be a bug

It's definitely not. It's just two distinct modes of operation.

> This is further compounded by the message at the top of the install doc page:

You're right, we can clarify the messaging. We'll work on that.

Again, let's please move any further questions to the forums, so that we stop alerting people who were involved in this long-since-closed issue.

**Comment by coolaj86** [comment]
`--resume` is not at all referenced in the documentation:
https://caddyserver.com/docs/json/admin/config/persist/

**Comment by francislavoie** [comment]
Feel free to open a PR to fix it @coolaj86. The JSON docs are generated from godoc comments.

**Comment by touhidurrr** [comment]
I think any change the user made to the config file should persist. When you install caddy with a package manager globally, the intent should be that it restarts and retains its config on server reboot. Otherwise it has mostly no meaning.
Anyways, for me the file was rewriting the caddy default config file with my caddyfile and doing any future edit on default caddyfile.
```bash
sudo mv Caddyfile /etc/caddy/Caddyfile
# in future
sudo nano /etc/caddy/Caddyfile
sudo systemctl restart caddy
```

**Comment by mohammed90** [comment]
You're commenting on an issue created during the **beta** versions of v2.0.0. The issue isn't applicable anymore.

> I think any change the user made to the config file should persist. When you install caddy with a package manager globally, the intent should be that it restarts and retains its config on server reboot.

That's already the case.
