### ISSUE TITLE
Build Caddy Docker image with WebDAV plugin

### ISSUE THREAD

**Issue by pataquets** [caddyserver/caddy#2904]
I know I can build it from source, but AFAIK, that would involve also chasing upstream changes and rebuilding each time to keep it up to date.
However, if the plugin was built-in, it could be used right away without worrying about keeping it up to date.
Caddy makes it a very handy tool to deploy easy web based file browsers, and having an out-of-the-box WebDAV server would be awesome.

**Comment by mholt** [comment]
I believe the [official v2 Docker image](https://github.com/caddyserver/caddy-docker/) allows customizing with plugins -- even though we don't plan to make WebDAV support standard, it should be pretty easy in v2 when a WebDAV plugin does surface!
