### ISSUE TITLE
Add ability to overwrite Caddy's name and version in modules

### ISSUE THREAD

**Issue by erbesharat** [caddyserver/caddy#2910]
## 1. What would you like to have changed?

Currently, it's possible to overwrite [`appVersion`](https://github.com/caddyserver/caddy/blob/c0190a3460f7188db6ed2dc580fdf524b99261d0/caddy/caddymain/run.go#L588) using `-ldflags` but since [appName](https://github.com/caddyserver/caddy/blob/c0190a3460f7188db6ed2dc580fdf524b99261d0/caddy/caddymain/run.go#L567) is a const, it's not possible to overwrite it.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

Letting the modules to have their own name and version instead of inheriting them from Caddy.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

No alternatives

## 4. Please link to any relevant issues, pull requests, or other discussions.

None

**Comment by mholt** [comment]
Thanks for the feature request! Sorry I never got around to it.

Closing, as this does not apply to v2, which will be the new actively maintained version soon.
