### ISSUE TITLE
Modify status code of reverse proxy response 

### ISSUE THREAD

**Issue by hackwaly** [caddyserver/caddy#2920]
Could it be done by only config?
And are there reverse_proxy response placeholders? Such as headers, status_code, body etc.

**Comment by mholt** [comment]
Hi, welcome to the issue tracker!

I am not entirely sure that I understand your post. Do you have 2 questions here?

1. How to modify the response status code from an upstream?
2. Whether there are placeholders for reverse proxy? Can you explain more what you mean?

**Comment by AbdelmalekIhdene** [comment]
Arguably, you'd say that those configurations should be the responsibility of the upstreams you are passing the request to, i.e. a proxy would only act as a middle-man in a request transaction.
If you want conditionals for different responses then caddy would not be the right answer for you since I'm sure @mholt is steering away from directives like [if](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/)

**Comment by mholt** [comment]
Hmmm no I believe this should be possible with Caddy 2, without imperative syntax -- if it's not possible already, then we should implement it. I just need to know exactly what needs to be implemented. So first, we need some clarification from @hackwaly.

**Comment by hackwaly** [comment]
I need to use config to achieve:

* Rewrite headers and status_code of reverse_proxy response

**Comment by mholt** [comment]
I almost understand -- can you give an actual example of one such configuration you're trying to accomplish?

**Comment by hackwaly** [comment]
BTW: I already wrote a go program to get what i want.

Config may like this:

```json
{
  "apps": {
    "proxy_app": {
      "servers": {
        "proxy_server": {
          "routes": [
            {
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "upstreams": [
                    {
                      "dial": "{host}"
                    }
                  ],
                  "headers": {
                    "handler": "headers",
                    "response": {
                      "delete": ["Set-Cookie"],
                      "set": {
                        "X-Set-Cookie": ["{http.handlers.reverse_proxy.response.header.Set-Cookie}"],
                        "Access-Control-Allow-Origin": ["*"]
                      },
                      "set_status_code": "{http.handlers.reverse_proxy.response.status_code >= 400 ? 500 : 200}"
                    }
                  }
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```

**Comment by mholt** [comment]
@hackwaly Neat, is the source anywhere?

**Comment by mholt** [comment]
Ping @hackwaly  -- how did you implement that feature?

**Comment by hackwaly** [comment]
@mholt 
clarify: I haven't implement that for caddy. I implement my need in plain go program.

**Comment by fahrradflucht** [comment]
Chiming in here since I want to feature that is in the title even though the issue kind of derailed:

My use case is the following. I have a MinIO backend where I serve a static website from. In case it responds with 404 I have an error handler that rewrites the request to `/404.html` and reverse proxies again to the same minio backend. Tada 🎉  404-page gets rendered.

The problem is that this will result in a 200 status code for the 404 page which is arguably not ideal. So overwrite the status code would be great.

**Comment by mholt** [comment]
@fahrradflucht So, in your use case, you don't actually want to _overwrite_ the status code, but you just want Caddy's error handler routes to be invoked on whatever error status is returned from the backend, right? Kind of like nginx's `intercept_errors` directive?

**Comment by fahrradflucht** [comment]
Maybe I don't fully understand you, but I think I actually want to overwrite the status code. Let me make an example.

Given a Caddyfile like this:
```Caddyfile
example.com {
	handle_errors {
		@404 {
			expression {http.error.status_code} == '404'
		}

		rewrite @404 /404.html
	}

	reverse_proxy https://minio.example.com {
		header_up Host {http.reverse_proxy.upstream.hostport}
        }
}
```

The `404.html` page will be returned for `https://example.com/unknown`. The problem is that it will be returned with a `200` status code which is not what you usually want. This is why I thought "Well, I need something to tell the `reverse_proxy` directive to overwrite the status code if the path is `/404.html`".

Does that make sense? Or am I approaching this totally wrong?

**Comment by francislavoie** [comment]
For the sake of correctness, I'm pretty sure the CEL expression should be the following:

```
expression {http.error.status_code} == 404
```

Status codes are ints

**Comment by fahrradflucht** [comment]
> For the sake of correctness, I'm pretty sure the CEL expression should be the following:
> 
> ```
> expression {http.error.status_code} == 404
> ```
> 
> Status codes are ints

Corrected, sorry. I typed this from memory because I don't have the file where I actually had a config like this at hand.

**Comment by mholt** [comment]
@fahrradflucht Is the backend originating the 404 error? I.e. does `minio.example.com` return a 404 to Caddy for a request to `/unknown`?

**Comment by fahrradflucht** [comment]
> @fahrradflucht Is the backend originating the 404 error? I.e. does `minio.example.com` return a 404 to Caddy for a request to `/unknown`?

Yes, exactly.

**Comment by mholt** [comment]
@fahrradflucht Okay, then you don't actually want to "overwrite" the status code, you want Caddy to handle the response from the backend as an error, rather than passing it through to the client.

**Comment by mholt** [comment]
This is possible with commit https://github.com/caddyserver/caddy/commit/7a99835dab64f7864186185761bbf5194216f8b6

**Comment by m90** [comment]
@fahrradflucht Sorry for hijacking this issue but I am trying to use the exact same setup (Caddy reverse proxying to MinIO) and have everything working __but__ custom 404 pages.

I tried using the snippet you provided here:

```
	handle_errors {
		@404 {
			expression {http.error.status_code} == 404
		}

		rewrite @404 /404.html
	}
```

but it's not having any effect. Did you ever get that setup working?

For the record, this is my complete config:

```
example.com {
  handle_errors {
    @404 {
      expression {http.error.status_code} == 404
    }

    rewrite @404 /404.html
  }

  reverse_proxy minio:9000

  @document {
    expression {uri}.endsWith("/")
  }

  @noslash {
    not expression {uri}.endsWith("/")
    path_regexp ^[a-z\-/]*$
  }

  handle @noslash {
    redir {uri}/
  }

  handle {
    route @document {
      rewrite {uri}index.html
    }

    rewrite * /static{uri}
  }

  log
}
```

**Comment by francislavoie** [comment]
@m90 it's not currently possible from the Caddyfile (but it is via JSON). Follow the progress on https://github.com/caddyserver/caddy/pull/3712, where Caddyfile support is being worked on.

**Comment by francislavoie** [comment]
FYI #3710 is merged, Caddyfile support will be in v2.4.0.

**Comment by wlcx** [comment]
Sorry to comment in an old issue, but this seemed to be the best place for this.

I am in the same situation as @fahrradflucht's [comment above](https://github.com/caddyserver/caddy/issues/2920#issuecomment-616109382): I am reverse proxying to a minio backend serving a static site. This site has a custom `404.html` which we want to return in case of an actual 404 from the backend. I've managed to achieve this with the below config, which also alters the final status code to 404 (else the 404 page would be returned with 200!) 

However, this feels a little messy so I was wondering if there was a better approach, perhaps involving `handle_errors`?

```
reverse_proxy 10.13.37.1:9000 {
    @404 status 404
    handle_response @404 {
        rewrite * /404.html
        reverse_proxy 10.13.37.1:9000 {
            @200 status 200
            handle_response @200 404  # if we get a 200 back (i.e. the 404 page exists) alter our status code to 404
        }
    }
}
```

**Comment by francislavoie** [comment]
@wlcx that's the correct way to do it. `handle_errors` does not get invoked for `reverse_proxy` responses, because they aren't errors _to Caddy_. The `handle_errors` routes are for errors that happen _in Caddy_.

**Comment by mholt** [comment]
In the future, we could probably introduce some convenience wrapper over that syntax to make it a little simpler to serve custom error pages.
