### ISSUE TITLE
(v1 website) DDL and script still has personal parameter

### ISSUE THREAD

**Issue by My1** [caddyserver/caddy#2926]
couldnt the new links/scripts just omit the parameter or ignore if present, as after all, the split is kinda dead now?

![image](https://user-images.githubusercontent.com/6696524/70623161-cac8ad80-1c1d-11ea-9880-270e94c6bb7b.png)

**Comment by tobya** [comment]
I think the licencing remains the same for V1.  V2 will have no licencing.

**Comment by My1** [comment]
But the actual download page selection doesn't even contain any info about the free only for personal or the switch between personal and business, even the pricing page completely vanished.

**Comment by mholt** [comment]
The different licensing for the binaries is done away with, the site isn't updated because we're working on a new one instead. Just ignore it.
