### ISSUE TITLE
v2: Testing Parsing

### ISSUE THREAD

**Issue by sarge** [caddyserver/caddy#2930]
Wondering about the expectations that plugin writers should have around testing.

Currently looking at porting a cors library to v2. It has a bunch of nice tests to validate the caddyfile parsing.

I can appreciate keeping a bunch of implementation details hidden but access perhaps to this function would be a nice compromise?

```
func newTestDispenser(input string) *Dispenser {
	tokens, err := allTokens("Testfile", strings.NewReader(input))
	if err != nil && err != io.EOF {
		log.Fatalf("getting all tokens from input: %v", err)
	}
	return NewDispenser(tokens)
}
```

**Comment by mholt** [comment]
Good point, I need to spend some time and figure out what to expose for convenient testing in v2.

**Comment by mholt** [comment]
@sarge I've exported NewTestDispenser in 6fe04a3.

@roblabla , as far as end-to-end integration testing, I believe @sarge can give you some pointers on that. :smiley:

**Comment by JokerQyou** [comment]
Sorry to comment in a closed issue, but how are plug-in authors supposed to use this function? I don't think it can be referenced since it's defined in a test file.

**Comment by francislavoie** [comment]
@JokerQyou we have some discussion about that here: https://github.com/caddyserver/caddy/issues/3402, it's possible we'll move NewTestDispenser elsewhere.
