### ISSUE TITLE
v2: Wrong argument count or unexpected line ending after [...] {http.request.uri}

### ISSUE THREAD

**Issue by jayfk** [caddyserver/caddy#2932]
Using the following v1 Caddyfile fails on Caddy 2

```
*.foo.bar.com {
    root /data/foo/{label1}{uri}
    tls {
        dns cloudflare
        ca https://acme-staging-v02.api.letsencrypt.org/directory
    }
}
```

with the error

```
run: adapting config using caddyfile: parsing caddyfile tokens for 'root': /etc/caddy/Caddyfile:2 - Error during parsing: Wrong argument count or unexpected line ending after '/data/foo/{label1}{http.request.uri}'
```

Is this expected? From my limited knowledge about the transition I assumed that there's backward compatibility. Is this not the case?

**Comment by francislavoie** [comment]
No, Caddyfiles are not backwards compatible. There's quite a few slight changes. The documentation is found here for the time being https://github.com/caddyserver/caddy/wiki/v2:-Documentation
