### ISSUE TITLE
A workaround to test HTTP/3 with Caddy 2 in localhost

### ISSUE THREAD

**Issue by K9A2** [caddyserver/caddy#2934]
As we have discussed in [#2194](https://github.com/caddyserver/caddy/issues/2194#issuecomment-452041759), Caddy 1/2 can not use self-signed TLS certificate to test HTTP/3 support. But if we have a valid certificate from well-konwn CAs, and a domain, we can enable HTTP/3 on Caddy 2 or HTTP/2+QUIC/43 on Caddy 1.0.3.

Below is the steps to set up a HTTP/3 or HTTP2/+QUIC/43 server on local machine:
- Prepare the required certificate and domain (e.g., www.example.com)
- Modify the host file, setting your domain to a local host's IP
- Start the Caddy server on that host, 2 alternative ways for your preference:
   - Use Caddy 1.0.3 to enable HTTP/2+QUIC/43, my Caddyfile is as below:
      ```caddyfile
        localhost_ip:443 {
          tls cert.pem cert.key
        }
      ```
      run with `./caddy -quic -log stdout`
   - Use Caddy 2.0 beta 10 to enable HTTP/3, my config.json file is as below:
      ```json
        {
          "apps": {
            "tls": {
              "certificates": {
                "load_files": [{
                  "certificate": "cert.pem",
                  "key": "cert.key"
                }]
              }
            },
            "http": {
              "http_port": 80,
              "https_port": 443,
              "servers": {
                "myserver": {
                  "listen": [ "localhost_ip:443" ],
                  "routes": [{
                    "handle": [{ "handler": "file_server", "root": "./" }]
                  }],
                  "tls_connection_policies": [{}],
                  "experimental_http3": true
                }
              }
            }
          }
        }
      ```
      run with `./caddy run -config config.json`
- Firefox Nightly 73.0a1 (December 2, 2019) provides only unstable support to HTTP/3, while Chrome Canary only supports HTTP/2+QUIC/43 mode (no HTTP/3 support).

**Comment by marten-seemann** [comment]
That’s not correct. Chrome supports HTTP/3, and Caddy v2 doesn’t support gQUIC (that includes QUIC 43).

**Comment by francislavoie** [comment]
Since there's nothing actionable in this issue, I'm going to close this. This issue board isn't really the best place for documentation-style issues. It's meant mostly for bugs and feature requests.

Feel free to continue any discussion here though.

**Comment by K9A2** [comment]
> That’s not correct. Chrome supports HTTP/3, and Caddy v2 doesn’t support gQUIC (that includes QUIC 43).

But I use Chrome Canary `81.0.3996.0 (Official Build) canary (64-bit)` to visit my website, it still presented as h2, instead of desired http/2+quic/99. This situation continues even I start it with `--enable-quic --quic-version=h3-23` or `--enable-quic --quic-version=h3-24`.

**Comment by vishnutm** [comment]
hi guys, I would like to know about the QUIC version support caddy 2? if possible could you please guide me.
