### ISSUE TITLE
Documentation request: import directive can now be used within other directives

### ISSUE THREAD

**Issue by gilbsgilbs** [caddyserver/caddy#2935]
#2428 implemented imports at the directive level and has been released for a while now, but [current version of the documentation](https://caddyserver.com/v1/docs/import) still states:

> Like other directives, however, it cannot be used inside of other directives.

which is no longer correct. It should rather be:

> Unlike other directives, it can be used inside of other directives.

I wanted to make a PR for such a tiny change but I wasn't able to find the documentation source code. Is it on GitHub?

Thanks.

**Comment by mholt** [comment]
Think we got this cleared up in the new docs. Thanks

**Comment by francislavoie** [comment]
Also for ref, the docs are here: https://github.com/caddyserver/website

I think at the time that this was asked, the docs weren't in a public github repo yet.
