### ISSUE TITLE
Planar loop of odd number of cogs will not work

### ISSUE THREAD

**Issue by chloekek** [caddyserver/caddy#2949]
The following image can be found on the website:

![image](https://user-images.githubusercontent.com/50083900/71477236-3186c300-27e9-11ea-8fd2-46c6fa7649fe.png)

While the caption is “Fewer moving parts”, ironically, there are _no_ moving parts here. These gears cannot turn, because there is an odd number of them in a loop on a plane.

You could fold them along a [Möbius strip](https://www.youtube.com/watch?v=nWQwrU1qUrc) though, or just insert or remove one cog.

Either way this project looks exciting, I’m gonna give it a try!

**Comment by mholt** [comment]
Indeed, zero moving parts is fewer moving parts!

...

Well that's embarrassing. I can't believe they didn't teach me this in college. 🙄

I've updated the graphic to the one attached, and it will go out with the next site deploy (when the new docs site is ready). Thanks!

![moving-parts](https://user-images.githubusercontent.com/1128849/71485914-c7622400-27d0-11ea-9609-c9db4fdfd988.png)
