### ISSUE TITLE
Dynamic per-site configuration on site root

### ISSUE THREAD

**Issue by Arteneko** [caddyserver/caddy#2958]
Right now, I'm using Netlify to host a few websites.

Each website has some specific configuration, e.g. headers set for some given paths.

I'd like to be able to continue using a per-site configuration file for headers / redirections / path matching with a file located in the website's root, much like how Apache or Netlify works.

Is there a way to do that, either in Caddy v2 or Caddy v1?

**Comment by mholt** [comment]
(This implies that...) you want Caddy to load the configuration on every HTTP request?

Why do you need a config file in every site folder?

**Comment by Arteneko** [comment]
Either on every request (like Apache, and probably like Netlify), or on caddy process load, with a way to ping the daemon so it hot-reloads the configuration.

The goal is to be able to manage some rules right from the website build, without needing manual intervention on the server.

**Comment by mholt** [comment]
Ah... we'd probably want to avoid going to disk for every HTTP request.

But have you seen Caddy 2's API? https://caddyserver.com/docs/api

All config changes are on-line, without needing any config files at all.

**Comment by Arteneko** [comment]
Does caddy allow "importing" configurations from some pre-defined paths?

That would mean I'd only need a curl ping to reload it.

Else, I'll need to look into how caddy v2's config system works.

Any release ETA?

**Comment by mholt** [comment]
Are you committed to needing your config in files spread throughout your file system? What I'm proposing still involves just a single API request.

**Comment by Arteneko** [comment]
Yes, as much as possible, as they're managed by a git repository, and no build task is run *on the server* itself.

The `POST /config/[name]` may do the trick, though. 

Would POSTing the configuration file on every deploy automatically persist the changes in Caddy's own internal config?

**Comment by mholt** [comment]
> Would POSTing the configuration file on every deploy automatically persist the changes in Caddy's own internal config?

Yep (from the linked page):

> The latest configuration will be saved to disk after any changes (unless disabled). You can resume the last working config after a restart with `caddy run --resume`.

So you can always pick up where you left off if the server restarts, but you don't need to restart or reload anything when using the API; there's no downtime and changes are immediate.

**Comment by Arteneko** [comment]
Once caddy v2 is released as stable, it may be my best bet, indeed.

Still, while it isn't yet released, does Caddy v1 provide an equivalent
feature?

**Comment by mholt** [comment]
No, Caddy doesn't reload configuration for each HTTP request. You can import many files with globular patterns but they're loaded statically, you'd have to issue USR1 signal to reload them. https://caddyserver.com/v1/docs/import
