### ISSUE TITLE
prevent automatic HTTPS from being activated, documentation broken

### ISSUE THREAD

**Issue by Kofl** [caddyserver/caddy#2961]
Hi,

for technical reasons we have to disable automatic https for the first phase of the go-live of caddy.

The documentation https://caddyserver.com/docs/automatic-https states that it can be done via JSON, located here: https://caddyserver.com/docs/json/apps/http/servers/automatic_https/

But the website is not loading or broken?

Thanks,
Thomas

**Comment by mholt** [comment]
Fixed, thanks. Apparently the DB process crashed O.o
