### ISSUE TITLE
cannot find package "github.com/cenkalti/backoff/v3" 

### ISSUE THREAD

**Issue by acbekoac** [caddyserver/caddy#2964]
Hi,

I tried to build caddy using attached script
[build_update_caddy.txt](https://github.com/caddyserver/caddy/files/4029797/build_update_caddy.txt)

Whle executing I get the following error:

Saving to: ‘go1.13.5.linux-amd64.tar.gz’

100%[==========================================================================================================================================>] 120,074,076 10.5MB/s   in 10s    

2020-01-07 10:12:59 (11.0 MB/s) - ‘go1.13.5.linux-amd64.tar.gz’ saved [120074076/120074076]

package github.com/cenkalti/backoff/v3: cannot find package "github.com/cenkalti/backoff/v3" in any of:
	/tmp/tmp.Pfn68KbzPD_caddy/go/src/github.com/cenkalti/backoff/v3 (from $GOROOT)
	/tmp/tmp.Pfn68KbzPD_caddy/src/github.com/cenkalti/backoff/v3 (from $GOPATH)

--> problem seem to be 
    https://github.com/go-acme/lego/issues/1022

**Comment by Mohammed90** [comment]
Don't build it dn GOPATH. The latest Caddy uses Go modules.
- Remove
`GOPATH="${CADDY_TEMP}"`
- Change this
`cd ${CADDY_TEMP}`
- Download Caddy source (git clone or compressed), then build it from there.
