### ISSUE TITLE
v2: try_files-like functionality

### ISSUE THREAD

**Issue by atonse** [caddyserver/caddy#2966]
I'm having a really tough time getting through the v2 documentation. 

This is what I'm trying to do:

My root dir has only two files:
`logout.html`
`index.html`

I want `/logout.html` to serve `logout.html`
I want _every other path_ to serve `index.html`

This is my current config which doesn't work:
```
example.com {
  file_server / {
    root /var/www/example/qa/static
  }

  rewrite /logout.html /logout.html
  rewrite /* /index.html
}
```

**Comment by francislavoie** [comment]
FYI, questions are typically best asked on https://caddy.community

I think you're just looking for `try_files /logout.html /index.html`

**Comment by atonse** [comment]
Thanks for the quick reply. I'll move this to caddy.community.

PS: That solution didn't work – it served logout.html but not index.html for other paths.
