### ISSUE TITLE
v2: http -> https redirect not working

### ISSUE THREAD

**Issue by sarge** [caddyserver/caddy#2972]
Using this configuration the automatic http->https does not appear to work.

Running on v2 branch.

```caddyfile
{
  http_port     9080
  https_port    9443
}
{$APP_HOST}:9443  {
  tls {$CERT_PATH}/ccp-gateway-app.ssl.cer {$CERT_PATH}/ccp-gateway-app.ssl.key {
  }
}
```
```
2020/01/11 09:16:12 http: panic serving 127.0.0.1:37914: runtime error: invalid memory address or nil pointer dereference
goroutine 113 [running]:
net/http.(*conn).serve.func1(0xc0008b08c0)
        /home/fedora/go/src/net/http/server.go:1767 +0x139
panic(0x1334fa0, 0x2227160)
        /home/fedora/go/src/runtime/panic.go:679 +0x1b2
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc00056d7a0, 0x182f7a0, 0xc00056dc00, 0xc0005ba500)
        /home/fedora/workspaces/gallagher/third-party/caddy/modules/caddyhttp/server.go:195 +0x8ad
net/http.serverHandler.ServeHTTP(0xc00056da40, 0x182f7a0, 0xc00056dc00, 0xc0005ba300)
        /home/fedora/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0008b08c0, 0x1835de0, 0xc0007f3c40)
        /home/fedora/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /home/fedora/go/src/net/http/server.go:2927 +0x38e
```

The `primaryHandlerChain` is null
https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/server.go#L192

I have followed the creation of the http->https redirect and the new server is created.
https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go#L543

I don't see where the `primaryHandlerChain` should be set.

**Comment by mholt** [comment]
@sarge Thanks for catching this, and for the good report. It's late here, but I've pushed a hopeful fix in 8be1f0e. Can you try it out?

**Comment by sarge** [comment]
@mholt this has the affect of all routes failing to match, even the https routes. I will update with more details as I investigate.

**Comment by mholt** [comment]
Shoot, thanks for pointing that out. This is the kind of mistake that happens when I write code while I'm sick and tired. :( I have pushed a fix for the fix. 🙄 Sorry about that. fe5a531c58f9714bf379962c51d086a14661cfdb

**Comment by sarge** [comment]
@mholt thanks!
Interestingly the redirect is not working for me - the route matcher on the protocol works but the static response created at https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go#L488 does not. I haven't put my finger on where in the plumbing it has stopped.

As an aside I tend to write integration tests to verify that my gateway (caddy) config works as expected. Do we need some tests to cover this kind of thing? I generally prefer to have lots of unit tests and a few integration tests to capture the high level intent

**Comment by mholt** [comment]
> Interestingly the redirect is not working for me - the route matcher on the protocol works but the static response created at https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go#L488 does not.

What is happening instead? Just an empty response again? I'm mobile right now but will try to repro when I get back if you haven't already figured it out.

> As an aside I tend to write integration tests to verify that my gateway (caddy) config works as expected. Do we need some tests to cover this kind of thing? I generally prefer to have lots of unit tests and a few integration tests to capture the high level intent

Yah, more tests are on my list... when things settle down a bit and stop changing so rapidly. So probably after the betas.

**Comment by sarge** [comment]
Yes just an empty response. My hunch is that because the redirect route is being added late in the process it is missing one of the processing steps. Do handlers get mapped/compiled to middleware?

**Comment by mholt** [comment]
Ah, I bet you're right! Automatic HTTPS happens in Start(), but the handler routes are compiled earlier in Provision.

I will rework this a bit and push a commit shortly.

**Comment by mholt** [comment]
@sarge Okay, I think I've fixed this. I had to split automatic HTTPS into two phases to avoid repeating a bunch of steps. Can you pull the latest and give it a try?

**Comment by sarge** [comment]
@mholt looking good. I created a couple of sites with both http and https and it all worked well.
