### ISSUE TITLE
v2: Caddyfile `file_server` hidden files should include the actual filename used for the config

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#2974]
While experimenting with Caddy v2, I noticed that when adapting my config to JSON, using the `file_server` directive gets a `"hide": ["Caddyfile"]` added. This is to ensure that the config isn't accidentally leaked if someone is running a file server for the current working directory.

When I use a Caddyfile named something like `Caddyfile-v2`, this file doesn't get added to the `hide` list, so it would get leaked.

This feature could probably be a bit more clever and use the filename from the `--config` option and possibly that to the list as well.

**Comment by mholt** [comment]
Thanks. Just forgot to set a property in a map; the commit I just pushed fixed it for me. Can you verify?

**Comment by francislavoie** [comment]
Alright, I'm seeing this now: `{"handler":"file_server","hide":["/etc/Caddyfile-v2"]}`
