### ISSUE TITLE
not enough arguments in call to certmagic.NewDefault().RevokeCert

### ISSUE THREAD

**Issue by yoursunny** [caddyserver/caddy#2975]
```
$ go get github.com/caddyserver/caddy/caddy
# github.com/caddyserver/caddy/caddytls
go/src/github.com/caddyserver/caddy/caddytls/tls.go:80:42: not enough arguments in call to certmagic.NewDefault().RevokeCert
	have (string, bool)
	want (context.Context, string, bool)
```

caddy version: caddyserver/caddy@a976629174bc1f831f889c2c475db7f98ea89579
certmagic version: mholt/certmagic@7311b4680c76370b489f847c901e29eac18c9eb8

It seems that they had a breaking change:
https://github.com/mholt/certmagic/commit/1c70bb8ce48a7b09a98ef43f03c6bcf56550d559#diff-b4bda758a2aef091432646c354b4dc59R482

Reverting to mholt/certmagic@32e52d625259ceb3254d291a3d0ba78ff1a7ac9b can fix the error for now.

**Comment by mholt** [comment]
Yep, hence 0.9 instead of 0.8.

Just pass in a context (either context.TODO or context.Background if you don't have one). Always try to stay up-to-date though, as the latest will have performance and bug fixes.

I'm hoping to tag a stable 1.0 this year.
