### ISSUE TITLE
tcp/udp  Port forwarding ?

### ISSUE THREAD

**Issue by f4nff** [caddyserver/caddy#2979]
nginx
```
stream {
    server {
        listen 3000;
        proxy_pass 127.0.0.1:3306;

    # 也支持socket
    # proxy_pass unix:/var/lib/mysql/mysql.socket;
    }
}
```
I use nginx to perform tcp / udp port forwarding. How do I use caddy for tcp / udp port forwarding?

**Comment by francislavoie** [comment]
If you're using Caddy v1, you're looking for https://caddyserver.com/v1/docs/net

If you're using Caddy v2, I don't think this has been implemented yet. Someone will probably write a plugin for it eventually.
