### ISSUE TITLE
Caddy v0.11.5+ breaks compatibility with NodeJS application that communicates over WebSockets

### ISSUE THREAD

**Issue by whalehub** [caddyserver/caddy#2987]
I've been using a NodeJS application called [MeshCentral](https://github.com/Ylianst/MeshCentral) behind Caddy on my server since December 2018. After updating Caddy from v0.11.4 to v0.11.5 last year, MeshCentral's Windows agents stopped being able to connect to the MeshCentral server component over WebSockets. This issue is still present in the latest version of Caddy, which is v1.0.4 as of the time of this writing.

@mholt @tobya I managed to figure out that the problem was introduced in v0.11.5 of Caddy by testing the release binaries of v0.11.4 and v0.11.5 on a VPS (https://github.com/Ylianst/MeshCentral/issues/838#issuecomment-575954491).

However, I was unable to determine which of the 13 commits that were made between v0.11.4 and v0.11.5 introduced this breaking change because the repository paths of Caddy and some of its dependencies have changed since then which means that these versions of Caddy can no longer (easily?) be built from source.

Any help with this issue would be welcome.

**Comment by Mohammed90** [comment]
Hi, thanks for the report!

The only potentially relevant commit is this https://github.com/caddyserver/caddy/commit/72d0debde6bf01b5fdce0a4f3dc2b35cba28241a . [Searching MeshCentral's source code shows](https://github.com/Ylianst/MeshCentral/search?q=ciphers&unscoped_q=ciphers) it's configuring the ciphers `RSA+AES:!aNULL:!MD5:!DSS` and `HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA`. I'm not versed in node.js' nor MeshCentral, so I'm not sure which of those results is relevant. Is it possible to have verbose logging on both sides and see what it says?

**Comment by whalehub** [comment]
@Mohammed90 Thanks for the pointer! After some testing, it turns out that the issue is indeed on MeshCentral's side. The MeshAgent component needs to be updated to support TLS 1.3, which has been enabled in Caddy by default since v0.11.5.

**Comment by tobya** [comment]
Does MeshAgent need to use 1.3 (which is still pretty rare) or do you just need to add additional Ciphers to the list in TLS

https://caddyserver.com/v1/docs/tls

Try adding all the ciphers listed

````
tls {
  ciphers xxx xxx  xxx
}
````

This may solve your problem without ever going to MeshCentral.

**Comment by whalehub** [comment]
@tobya The dev found the issue by now and submitted a fix, but I appreciate the help!
