### ISSUE TITLE
v2+windows+php-cgi: Display index when file does not exist

### ISSUE THREAD

**Issue by fu-sen** [caddyserver/caddy#2989]
My Windows is in this situation:
https://gist.github.com/fu-sen/490442e1a1b832c5623ef7c8168a3925
https://caddy.community/t/caddy-v2-php-cgi-on-windows/6825

At this time, When referring to a file that does not exist, the index is displayed without issuing 404.
Returns 404 normally when `php_fastcgi` is removed.

This bug has been confirmed with Caddy v2 + Windows + php-cgi.

**Comment by fu-sen** [comment]
As a workaround, put the following **index.php** in root.
```
<?php
$uri = $_SERVER['REQUEST_URI'];

if ( strcmp($uri, "/") != 0 &&
     strcmp($uri, "/index.html") != 0 &&
     strcmp($uri, "/index.php") != 0 )
{
    http_response_code(404);

    print "404 Not Found\n";

    exit;
}
// Here is the original PHP
?>
<!-- or here is the original HTML. -->
```

**Comment by mholt** [comment]
Under the hood, `php_fastcgi` does a `try_files {path} {path}/index.php index.php`, so if the file does not exist, it defaults to index.php.

This has seemed to be the most useful case for PHP applications so far. What do you need instead?

**Comment by mholt** [comment]
@fu-sen Would you be able to try with #2990 and see if that does what you want?

**Comment by fu-sen** [comment]
> Under the hood, `php_fastcgi` does a `try_files {path} {path}/index.php index.php`, so if the requested path does not exist, it defaults to index.php.
> 
> This has seemed to be the most useful case for PHP applications so far.

This is a specification.
I use PHP 7 on Google App Engine so I can understand how it works. 😄
This will also benefit WordPress and CMS.
I was happy to get a custom 404 with this. 😁

But if you just use PHP on your web server, this can be confusing.


> @fu-sen Would you be able to try with #2990 and see if that does what you want?

Thank you for the quick response! When it is released, I will try it.

**Comment by mholt** [comment]
@fu-sen Unfortunately, I don't think we'll release it in a beta at this point unless it's tried in the wild first.

In that case, I'll close the PR and recommend that you just use the expanded form, except adjusted slightly so it does not try `index.php` as a last resort:

```
# canonicalize URI trailing slash when index file present
@indexFiles {
    not {
        path */
    }
    file {
        try_files {path}/index.php
    }
}
redir @indexFiles {path}/  # internally rewrite directory URIs to index.php files

try_files {path} {path}/index.php

# proxy any requests for PHP files to backend via FastCGI
@phpFiles {
    path *.php
}
reverse_proxy @phpFiles php-fpm:9000 {
    transport fastcgi {
        split .php
    }
}
```

The php_fastcgi directive is just a short form of that, so you can customize it like that if you need to.

**Comment by fu-sen** [comment]
I understood it with # 2990. At least I am satisfied with the current specifications. Thank you.

**Comment by francislavoie** [comment]
@fu-sen Just to be clear, most PHP frameworks (including Wordpress) use `index.php` as the entrypoint for all requests, and use internal routing to determine if a request path is valid. If it's not, then the framework returns a 404 response.

The code you added at the top of your index.php is probably the way you want to go, but instead you should use a proper router in your app. A good library to use as a router would be https://github.com/nikic/FastRoute

**Comment by fu-sen** [comment]
> @fu-sen Just to be clear, most PHP frameworks (including Wordpress) use `index.php` as the entrypoint for all requests, and use internal routing to determine if a request path is valid. If it's not, then the framework returns a 404 response.

Oh, I understand the specification well. It is a modern implementation.
