### ISSUE TITLE
Support binding on port 0

### ISSUE THREAD

**Issue by allentian** [caddyserver/caddy#2992]
Binding on port 0 means the kernel will select an unused port.
It seems Caddy does not support it.
Do you have plan to support it?
Thanks.

**Comment by francislavoie** [comment]
Strange. Could you describe a use-case where this would be useful?

Which version of Caddy are you using? It's very unlikely a change to this would land in v1, but it's possible that it could be supported in v2.

**Comment by allentian** [comment]
Thanks for quick reply.
I hope to specify port 0 for Caddy server, then it can assign random unused port for use.
If I specify any number such as 55555 which is used by another process, I will get compaint like `Listen: listen tcp 127.0.0.1:55555: bind: address already in use`.
If I can speciy port 0 and caddy server helps to choose any unused port for use, I won't worry about such issue any more.

**Comment by francislavoie** [comment]
I understand that, but why would you want to use a random port instead of a specific well-known port, especially for a webserver?

I think a random port does makes sense in a situation where you have some development tool, for example `npm`'s built-in server, where you just need to spin something up for local usage. Is this the kind of situation you're thinking of?

More information about how and why this would be used would be helpful.

**Comment by mholt** [comment]
We can do this, but I also want to know a compelling use case.

**Comment by allentian** [comment]
Thanks for your response .
I have given the use case to you in the first reply.
It is only used for development instead of production.
For example another process is using port 55555. 
If I choose 55555 as Caddy Server's port at the same time, I get complaint lit `Listen: listen tcp 127.0.0.1:55555: bind: address already in use.`
If I can specify port 0 and caddy server helps to choose any unused port,  I won't have such issue.
I am not sure if it is a resonalble use case for you.

**Comment by mholt** [comment]
Okay. No problem, but I think if there is enough demand for this feature, we should definitely do it.

**Comment by mholt** [comment]
So, this already works actually. I just added a log message that prints the port so you can know it without having to netstat or whatever.
