### ISSUE TITLE
API PUT doesn't want to insert to array

### ISSUE THREAD

**Issue by spaceglace** [caddyserver/caddy#2995]
Heya! I've been ramping up on Caddy 2, which has been a lifesaver for me so far. Currently I'm trying to control the order of routes in a server handler, and want to use PUT to insert new routes at the beginning of the list. Try as I might, it always fails with the same error "`key already exists: routes`"

The documentation provides an example here: https://caddyserver.com/docs/api#put-configpath
When I try the same call, I the same error:
```
[root@Glaceon ~]# curl -X PUT \
> -H "Content-Type: application/json" \
> -d '":8080"' \
> "http://localhost:2019/config/apps/http/servers/aether/listen"
{"error":"[/config/apps/http/servers/aether/listen] key already exists: listen"}
```
I'm using the latest docker image pushed to the caddy/caddy:alpine tag, which was 9 days ago so I'm guessing it's based on 2.0 beta 12.

Let me know if there's something I'm missing here, or something you'd like me to try!

**Comment by mholt** [comment]
Oops, that example should have a `/0` at the end of the path. That inserts the value at index 0 in the array. I've fixed the docs and it will go out with the big site update today. Thanks!
