### ISSUE TITLE
v2: Caddyfile adapter should support `flush_interval -1`

### ISSUE THREAD

**Issue by sirthias** [caddyserver/caddy#2996]
As discussed in https://github.com/caddyserver/caddy/issues/1460 a `flush_interval` value of `-1` is sometimes required.
As of [this commit](https://github.com/caddyserver/caddy/commit/db4293cb5fce33b467b50ef77698f69a4a066215) the Caddyfile adapter also supports the `flush_interval` setting of the `reverse_proxy` section but so far doesn't appear to allow for setting a value of `-1`.

From looking at the code [here](https://github.com/caddyserver/caddy/blob/db4293cb5fce33b467b50ef77698f69a4a066215/modules/caddyhttp/reverseproxy/caddyfile.go#L334) the value of `-1` probably needs to be handled specially.

**Comment by mholt** [comment]
Thanks for the reminder! Fixed.

**Comment by sirthias** [comment]
Awesome! Thank you for the extremely quick turn-around, @mholt!
