### ISSUE TITLE
proxy passing connection to wrong socket

### ISSUE THREAD

**Issue by mfoncho** [caddyserver/caddy#3000]
os: Arch GNU/Linux
kernel: 5.4.3-arch1-1
caddy v1: 1.0.4

setup: local php project
setup: nodejs socket.io echo script
no tls
no lxc
no docker
just bear metal

Read the docs and wrote my first caddy file. nothing extra

Caddyfile
```
0.0.0.0:8000

gzip

log stdout

errors stdout

root ./public

fastcgi / /var/run/php-fpm/php-fpm.sock php

rewrite {
        to {path} {path}/ /index.php?{query}
}

proxy /ws 0.0.0.0:8080 {
        websocket
        transparent
}
```
 While the php project always works as expected. The first time i ran ```caddy``` the proxy just worked and a websocket connection was established, then i refreshed the page and i never got the proxy to work again. Instead now i get this from my logs

```
2020/01/25 01:47:53 192.168.1.2 - - [25/Jan/2020:01:47:53 -0600] "GET /ws HTTP/1.1" 404 581
2020/01/25 01:47:56 192.168.1.2 - - [25/Jan/2020:01:47:56 -0600] "GET /ws HTTP/1.1" 404 581
2020/01/25 01:47:59 192.168.1.2 - - [25/Jan/2020:01:47:59 -0600] "GET /ws HTTP/1.1" 404 581
```
The proxy keeps forwarding everything to php index.php  i tried hoisting the proxy block at the top
to no avail. then when i take out the php config blocks
```
0.0.0.0:8000

gzip

log stdout

errors stdout

root ./public

proxy /ws 0.0.0.0:8080 {
        websocket
        transparent
}
```
And try reconnecting the websocket the connection works..... 
This is my first time using caddy with my project so i might be missing something. Please someone let me know what i should be doing or what i'm doing wrong

**Comment by tobya** [comment]
try this
````
rewrite {
        to {path} /{path} /index.php?{query}
}
````
with  /{path} rather than {path}/

If you are still haveing difficulty, the caddy forum https://caddy.community is the place to go

**Comment by mfoncho** [comment]
@tobya Thanks for the support.  Though I'm no longer interested in a solution, still no success with the new rewrite.
