### ISSUE TITLE
V2: incorrect documentation for original uri placeholders

### ISSUE THREAD

**Issue by gilbsgilbs** [caddyserver/caddy#3001]
Hi,

Just to let you know that [this documentation page](https://caddyserver.com/docs/json/apps/http/) indicates that the request's original URI placeholder is `{http.request.orig.uri}`, but it happens to be wrong. It is actually `{http.request.orig_uri}`.

Thanks for the amazing work :pray: .

**Comment by francislavoie** [comment]
Thanks, that documentation is generated from the comments here: 

https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/caddyhttp.go#L65-L67

and the actual replacers are here:

https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/replacer.go#L112-L128

So you're correct! I'll open a quick PR.

**Comment by gilbsgilbs** [comment]
I'd have done the PR myself if I knew it was open-source. Thank you for the blazing fast response and PR @francislavoie :tada: .

**Comment by francislavoie** [comment]
For future ref, [most of the docs are here](https://github.com/caddyserver/website) (only published yesterday!) but some of the docs (mostly the JSON stuff) are generated from code. @mholt did some clever stuff to get that to work.
