### ISSUE TITLE
v2: Expose IP and TCP layer

### ISSUE THREAD

**Issue by kjiregt845gj** [caddyserver/caddy#3006]
Hey,
At the moment Caddy uses GO's _listen_ function from the _net_ library which takes care of everything until, and including, the TCP handshake, and enables reading the TCP data from the socket.
So the "lowest" I can get to is the raw data from the TCP socket.

I'd like to know it'd be possible for Caddy to use another function\library that would enable access to the raw socket itself, and to the IP and TCP level, including the TCP SYN packets for example.

This would enable implementation of IP\TCP fingerprinting, which can be performed by accessing values such as ip.ttl and tcp.window_size.
Moreover, it can potentially be used for implementing defenses for some DoS\DDoS attacks such as SYN flood.

**Comment by Mohammed90** [comment]
Hi there! To confirm my understanding, you want something that's at a lower level than #2890 , right?

**Comment by kjiregt845gj** [comment]
Hey,
I'm not too familiar with the TCP\UDP server type plugin but, yes, it's lower than that.
From my understanding in case of TCP, this proxy plugin creates a new session with the destination host in order to forward the TCP data, and is not able to get the IP\TCP-level-properties of the initial session with the source host (the only data which is usually passed to higher levels is src-dst IP and ports).

BTW I think that it can be tagged as a feature request

**Comment by mholt** [comment]
This is indeed possible, but will need some work to be implemented. It's a fairly significant change. Proposals and discussion are welcome in the meantime!

**Comment by mholt** [comment]
I have never done it before, but I _think_ Caddy modules implementing this functionality (approx. layer 3 of the OSI model) would make heavy use of [net.IPConn](https://golang.org/pkg/net/#IPConn).

Helpful resource:
- https://ipfs.io/ipfs/QmfYeDhGH9bZzihBUDEQbCbTc5k5FZKURMUoUvfmc27BwL/socket/raw_sockets_and_the_type_ipconn.html

**Comment by francislavoie** [comment]
I think we can close this, https://github.com/mholt/conncept implements support for this (as of this writing, for sponsors only).

**Comment by mholt** [comment]
I believe this feature request is for a layer lower than what a Project Conncept supports.

**Comment by mholt** [comment]
But as this will likely be implemented as a separate module, I don't think we need to keep this issue open in this repo. Anyone who wants to implement such a module may do so in their own repo!
