### ISSUE TITLE
Add code coverage badge and enforce min coverage (without sacrificing privacy)

### ISSUE THREAD

**Issue by x448** [caddyserver/caddy#3008]
This would make Caddy's pull requests and commits indicate whether the specified minimum code coverage is satisfied by using GitHub Actions (no external service required).

I created ci-go-cover.yml and put it on [github.com/x448/workflows](https://github.com/x448/workflows) because codecov.io asked permission to read private project boards and private email addresses:

* their "application will be able to read your organization, team membership, and private project boards."
* their "application will be able to read your private email addresses."

By comparison, nothing is uploaded or downloaded by ci-go-cover.yml. All the code in ci-go-cover.yml is embedded and easy-to-read with MIT License. The only external "action" script is provided by GitHub Inc. (actions/checkout@v2). It runs `go test -short -cover` -> `grep` -> `python`.

Example project using this for code coverage badge is [fxamacker/cbor](https://github.com/fxamacker/cbor).

I hope you find this useful.  Cheers!

**Comment by JalonSolov** [comment]
In more recent versions of Go, you can add the "-cover" switch to "go test" to get a coverage report.  No need for an external go-cover, etc.

**Comment by x448** [comment]
@JalonSolov yes, that is why I propose this solution (to avoid external services beyond GitHub).  The Go feature you mentioned is used by GitHub when commits are pushed:  
`go test -short -cover` -> `grep` -> `python ...`

GitHub will mark the commit with a big red x instead of green check if the python script exits with error.  This is helpful for reviewing pull requests. 

GitHub will also automaticall generate badge.svg with percent required + passing/failing.

[![](https://github.com/x448/float16/workflows/cover%20100%25/badge.svg)](https://github.com/x448/float16/actions?query=workflow%3A%22cover+100%25%22)

Clicking on badge will go to GitHub generated page showing more info about what happened as well as the script that was used.

**Comment by JalonSolov** [comment]
Excellent.  Very handy thing.

I just hope nobody is silly enough to set 100% as the required... it is a waste of your time to test compiler related things like having the line "x:=2" and then test "Does x = 2?".  75 - 80% is a much more realistic goal.

Either that or have a way to mark lines as not required to have tests, and then go for 100% on the rest.

**Comment by mholt** [comment]
Thanks for letting us know! If we feel compelled to add code coverage to our CI, we'll consider this.
