### ISSUE TITLE
v2: Support for .env files

### ISSUE THREAD

**Issue by RecuencoJones** [caddyserver/caddy#3009]
In v1 `.env` files were supported through `-envfile` switch, will this be ported on to v2?

I have been able to workaround this by using `set -a` before sourcing the env file, and there are also tools that enable this like [ruby's dotenv](https://github.com/bkeepers/dotenv), [npm's dotenv-cli](https://www.npmjs.com/package/dotenv-cli) or [godotenv](https://github.com/joho/godotenv)

Reference links:
- Original v1 issue: https://github.com/caddyserver/caddy/issues/1941
- https://caddy.community/t/caddy-v2-environment-variables/6736

**Comment by jimen0** [comment]
Hi,

I hit this issue yesterday evening and I'd like to contribute a patch for it. Would something like this work for you?

```patch
diff --git a/cmd/main.go b/cmd/main.go
index bdc95a45..833189c4 100644
--- a/cmd/main.go
+++ b/cmd/main.go
@@ -81,6 +81,14 @@ func Main() {
 		os.Exit(caddy.ExitCodeFailedStartup)
 	}

+	// check if there is an .env file in the directory where the user
+	// lauched Caddy. If so, parse it and os.Setenv for each of the existing variables.
+	// If .env contains any invalid entry, an error is reported:
+	// if err != nil {
+	// 	fmt.Printf("[ERROR] could not parse .env contents: %v\n", err)
+	// 	os.Exit(caddy.ExitCodeFailedStartup)
+	// }
+
 	exitCode, err := subcommand.Func(Flags{fs})
 	if err != nil {
 		fmt.Fprintf(os.Stderr, "%s: %v\n", subcommand.Name, err)
```

I'm still not used to v2 codebase, so maybe that's not the best place to read it. Also, where should the `KEY=VALUE` split + validate logic be placed? I want to contribute tests too for the logic. What's the desired testing approach? (std library testing, assert, require, etc).

cc @mholt 

Thanks!
