### ISSUE TITLE
caddy copr 404

### ISSUE THREAD

**Issue by naizhao** [caddyserver/caddy#3011]
```
$ curl -I https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/repo/epel-7/group_caddy-caddy-epel-7.repo                                                                                          130 ↵  

HTTP/1.1 404 NOT FOUND
Date: Fri, 31 Jan 2020 04:35:36 GMT
Server: Apache/2.4.41 (Fedora) OpenSSL/1.1.1d mod_wsgi/4.6.4 Python/3.7
Strict-Transport-Security: max-age=31536000; preload
Content-Length: 6269
Content-Type: text/html; charset=utf-8

```

**Comment by carlwgeorge** [comment]
Originally we had the EL7 buildroot enabled for that copr, but 2.0.0-beta12 exposed a build issue with the stock version of git.  I temporarily disabled the EL7 buildroot until we can find a workaround.

Thanks for mentioning this, it reminded me to update the installation instructions to clarify the situation.

**Comment by francislavoie** [comment]
Thanks for answering @carlwgeorge 

I'll close this, I figure discussion about distribution is best had on https://github.com/caddyserver/dist

**Comment by carlwgeorge** [comment]
@naizhao I've re-enabled the EL7 buildroot in copr and built the v2.0.0-beta.13 tag there.  Please try it out and let us know if you see any issues.
