### ISSUE TITLE
v2: Expose a caddyfile directive ordering API to modules

### ISSUE THREAD

**Issue by roblabla** [caddyserver/caddy#3019]
Currently, when building a Caddy module that provides a caddyfile directive, module authors have to modify caddy's [directiveOrder](https://github.com/caddyserver/caddy/blob/v2/caddyconfig/httpcaddyfile/directives.go#L29). This sort makes building out-of-tree caddy modules a bit of a pain.

Maybe we should have some broad directive categories instead (say, Authentication, Routing, ServeContent, ErrorHandling...) that would have a fixed order, and then directives can register in one of those categories? Or maybe allow directives to specify they want to register "before" another directive?

**Comment by mholt** [comment]
Use the `order` global option: https://caddyserver.com/docs/caddyfile/options

You can change or add directives in any place in the list using it, without changing any source code.

I looked into the buckets/bins idea about a year ago when I was designing it, but they are not sufficient and are too unwieldy in practice.

**Comment by roblabla** [comment]
Ah, that does work! Maybe the `order` global option should be mentioned in the [extending caddy](https://caddyserver.com/docs/extending-caddy) guide though?

**Comment by mholt** [comment]
Definitely. It's a newer thing. I need to expand the Extending Caddy guide too, so I'll swing around and do that at some point.
