### ISSUE TITLE
browse: allow filter init via `filter` query param

### ISSUE THREAD

**Issue by jjlin** [caddyserver/caddy#3025]
It would be nice to be able to create links that initialize the file browsing filter so only certain files are displayed by default. For example, if a directory contains many .png and .jpg files, `https://example.com/photos/?filter=.png` would show just the ones with the `.png` substring.

**Comment by mholt** [comment]
Why not just use the in-page filter? Simpy type `.png` and you'll get only the png files.

**Comment by jjlin** [comment]
It does use the in-page filter; it's just initializing it from the query param so you can link people to a directory where the filter is already preset and they don't have to type it in themselves.

**Comment by mholt** [comment]
Ohhh okay, gotcha. Lemme take a closer look when I have a minute. Thanks!

**Comment by mholt** [comment]
Thanks again for the contributions. Sorry I got mixed up

**Comment by jjlin** [comment]
No worries, thanks!
