### ISSUE TITLE
Plugin download error

### ISSUE THREAD

**Issue by AttorneyFan** [caddyserver/caddy#3032]
tried to download caddy with http.forwardproxy, tls.dns.cloudflare plugins many times, but failed.
curl https://getcaddy.com | bash -s personal http.forwardproxy, tls.dns.cloudflare

![image](https://user-images.githubusercontent.com/588329/74118998-ac206c00-4bf8-11ea-979c-0d9ae15e8539.png)

**Comment by tobya** [comment]
If you are still getting this error you may find it easier to get help at https://caddy.community which is a forum for issues such as this.

Thank you for using Caddy.
