### ISSUE TITLE
Q v2: Will "tls ask" and redis clustering be implemented?

### ISSUE THREAD

**Issue by tobiasmuehl** [caddyserver/caddy#3036]
We're using Caddy v1 and make use of the `tls ask` directive and also the redis plugin to keep our deployments "stateless". Presumably both are not very popular features, but for us a crucial reason for the adoption of Caddy.

Are there plans to port both to v2? Is it already ported but just not documented yet?

**Comment by francislavoie** [comment]
On-demand TLS is supported via the JSON config currently https://caddyserver.com/docs/json/apps/tls/, Caddyfile support will come eventually.

Plugins are maintained by third parties, so it's up to the community to port it to v2.

**Comment by mholt** [comment]
@tobiasmuehl Francis is right, but if this is something your company needs, let's talk. At this point it's just a matter of funding.
