### ISSUE TITLE
V2 missing documentation on capture groups for matchers

### ISSUE THREAD

**Issue by mbernasocchi** [caddyserver/caddy#3041]
I'm trying to do 
`redir /ows/* /demo.html?{query}&match={1}`
expecting 
`example.com/ows/test/hello?name=marco` to redirect to `example.com/demo.html?name=marco&match=/test/hello`

But I can't find any documentation on how to do such a thing, best I can find is this forum https://caddy.community/t/v2-having-trouble-with-rewrite/6466/6 and an old revision of the wiki (https://github.com/caddyserver/caddy/wiki/v2:-Documentation/cc3c37cdb5ac823beef842e8091b3d1402570416) that mentions using Named matchers, but the  syntax has changed since from 

```
matcher mymatch {
     path_regexp ....
}
```
to

```
@mymatch {
     path_regexp ....
}
```

Is ther something that I'm blatantly missing?

**Comment by mholt** [comment]
`redir /ows/* /demo.html?{query}&match={1}` uses a regular expression, so you need a named matcher, as described at https://caddyserver.com/docs/caddyfile/concepts#named-matcher. That will expose regexp capture groups by the name you provide.

**Comment by mbernasocchi** [comment]
hi @mholt thanks a lot for the info,as soon as I found the JSON docs, I figured it out.
I'd be great if that part of the documentation would be more visible

**Comment by mholt** [comment]
Yeah, I'll see what I can do!

**Comment by mholt** [comment]
Added here: https://github.com/caddyserver/website/commit/668d145ecc1d136a6e2e14e3fca7186883f7421a -- and it is live here: https://caddyserver.com/docs/caddyfile/matchers
