### ISSUE TITLE
update QUIC to draft-26

### ISSUE THREAD

**Issue by marten-seemann** [caddyserver/caddy#3043]
draft-26 will (probably) be released next week or the week after. This draft version is intended for deployment.

I'm planning to send a PR adding support for draft-26 as soon as I ship the quic-go update. Hopefully this will be in time for the Caddy 2 release.

**Comment by mholt** [comment]
That's exciting! I will be looking forward to it, and I will let others know when it goes out in a release.

Do you foresee being able to work on https://github.com/lucas-clemente/quic-go/issues/2103#issuecomment-529950063 again? As far as I know, we still have issues with the HTTP/3 server during config reloads. Our [current solution](https://github.com/caddyserver/caddy/blob/f42b138fb18d080861f70e831c479738e3cdcd14/modules/caddyhttp/caddyhttp.go#L325-L340) is to not stop the server when we start the new one, which I'm sure must be a leak?

I can probably make some time during nights/weekends to help debug it, just let me know! (We'll need to figure it out before the feature leaves experimental phase, even if both the HTTP/3 spec and its quic-go implementions are done.)
