### ISSUE TITLE
How to write logging???Can you give a full caddy.json example???

### ISSUE THREAD

**Issue by amColinzzz** [caddyserver/caddy#3045]
Now,your example just include app{},but the logging ,no example!!!
I have search all the google ,no one example how to write the logging { } config.
This my setting :
`
		"sink": {
			"writer": {
				"file":{
					"output": "file",
					"filename": "/etc/caddy/logs/sink.log",
					"roll": true,
					"roll_size_mb": 50,
					"roll_gzip": true,
					"roll_local_time": false,
					"roll_keep": 10,
					"roll_keep_days": 90
				}
			}
		}
`
it will wrong :
`
2020/02/16 05:53:42.395	INFO	using provided configuration	{"config_file": "/etc/caddy/caddy.json", "config_adapter": ""}
2020/02/16 05:53:42.398	INFO	admin	admin endpoint started	{"address": "localhost:1000", "enforce_origin": false, "origins": [""]}
run: loading initial config: loading new config: setting up sink log: loading sink log writer module: module name not specified with key 'output' in map[file:map[filename:/etc/caddy/logs/sink.log output:file roll:true roll_gzip:true roll_keep:10 roll_keep_days:90 roll_local_time:false roll_size_mb:50]]

`

**Comment by francislavoie** [comment]
For questions about usage of Caddy, please ask on the forums: https://caddy.community
