### ISSUE TITLE
v2: can't use header_regexp directive against Host header

### ISSUE THREAD

**Issue by gilbsgilbs** [caddyserver/caddy#3059]
Hi,

I'd want to use a `header_regexp` directive against the `Host` header, but apparently the `Host` header is popped out during the matching phase:

```
localhost:80 {
    @matcher {
        # This matcher never matches
        header_regexp Host ^localhost$
    }

    respond @matcher "matched"
}
```

Other headers than `Host` do not present this issue. My ultimate use-case would be to capture the lowest-level domain to reverse-proxy somewhere:

```
*.my-very-own-website.com:80 {
    @matcher {
        header_regexp host Host ^(?P<dest>left|right)\.
    }

    reverse_proxy @matcher {http.regexp.host.dest}.my-very-own-server.io:8080
}
```

On top of the aforementioned problem, this second Caddyfile is invalid because [despite what's in the doc](https://caddyserver.com/docs/caddyfile/matchers#header_regexp), `header_regexp` directive doesn't allow a `name` parameter (`Error during parsing: Wrong argument count or unexpected line ending after ^(?P<dest>left|right)\.`). Should I open another issue for this?

I can look into fixing both issues if you will, but it would really help me should you gave me some pointers to the relevant source files.

Thanks for all the work on caddy. :pray:

**Comment by mholt** [comment]
Ah, that's because Go (the standard lib) treats the Host header separately... causes kind of a pain here, where we handle it separately: https://sourcegraph.com/github.com/caddyserver/caddy@v2/-/blob/modules/caddyhttp/headers/headers.go#L273-275

I would greatly appreciate your help, yes!

The header_regexp matcher and Caddyfile parsing logic is here: https://github.com/caddyserver/caddy/blob/0b09b070e54bca82ba399f43062c689a3d921f24/modules/caddyhttp/matchers.go#L409-L434

**Comment by francislavoie** [comment]
FWIW, I think you can avoid looking at the Host header directly by using the label placeholders like `{http.request.host.labels.2}`, see https://caddyserver.com/docs/json/apps/http/

**Comment by gilbsgilbs** [comment]
Thanks for the pointers @mholt, that'll help. I'll try to look into it sometimes.

> FWIW, I think you can avoid using a regex on the Host header by using the label placeholders like {http.request.host.labels.2}, see https://caddyserver.com/docs/json/apps/http/

That's neat. I didn't knew this placeholder, thanks. Yet my real-world use-case is slightly more complex than what I indicated in the original post. In practice, I need to match something like `^(left|right)--(\d+)\.` where I don't think labels can't help.
