### ISSUE TITLE
why not decrease the size of release assets?

### ISSUE THREAD

**Issue by yu-chenxi** [caddyserver/caddy#3062]
Currently, all release assets have **debug info** and they are **uncompressed**. I think it is very necessary to decrease the size of them. Here are some ways:

1.  the original
![image](https://user-images.githubusercontent.com/29013148/74909580-93cc0080-53f3-11ea-826e-cd32c1d1f75e.png) your can see, the debug info of asset is not stripped, which size is **30M**.

2. strip the debug info
![image](https://user-images.githubusercontent.com/29013148/74915073-8bc58e00-53fe-11ea-9d34-d2f44494032d.png) Decreased by 7M, about 23% of the original size. And it is safe to strip the debug info when build . you can use go build -ldflags="-s -w" to achieve this goal. Just add -ldflags="-s -w" to azure pipeline file.
**see also**: [https://golang.org/cmd/link/](url) to know the meaning of arguments above. 

3.  compress it
![image](https://user-images.githubusercontent.com/29013148/74916008-1064dc00-5400-11ea-816f-ecbb59648fc7.png) Only 6M, about 20% of the original size.

4.  or use **[UPX](https://github.com/upx/upx)** to pack it
![image](https://user-images.githubusercontent.com/29013148/74920441-1f9b5800-5407-11ea-8f0e-08a4f6741584.png) A standalone executable file only  7.2M, so fantastic!

**Comment by Mohammed90** [comment]
Currently the release binaries aren't produced by the azure-pipelines.yml flow. I think Matt hand-rolls them for now while v2 is still in beta.

**Comment by yu-chenxi** [comment]
Thanks

**Comment by mholt** [comment]
For the record, I think we need to keep debug info, so that panics and other stack traces contain useful information.

**Comment by Mohammed90** [comment]
For future reference, these are the links sources exchanged in our conversation:

https://dominik.honnef.co/posts/2016/10/go-and-strip/

https://groups.google.com/forum/#!topic/Golang-nuts/6K5Ca3GZF5k
