### ISSUE TITLE
Replace in response content

### ISSUE THREAD

**Issue by scalp42** [caddyserver/caddy#3065]
Hi folks,

Is there something matching the functionality of http://nginx.org/en/docs/http/ngx_http_sub_module.html?

Thanks in advance

**Comment by mholt** [comment]
v1 has this: https://caddyserver.com/v1/docs/http.filter

So I assume this is about v2. I don't know of any implementation of such a module for v2 yet, but I would happily entertain a design discussion / proposal and PR!

**Comment by scalp42** [comment]
I'm using v1 right now and it doesn't seem to work:

```
0.0.0.0
browse
log stdout
errors stdout

filter rule {
  content_type text/html.*
  search_pattern Connections
  replacement blabla
}

proxy / srv://something.service.consul
```

Yet the HTML is returning:

```
<li class=""><a href="/pghero/connections">Connections</a></li>
```

Not sure if I'm missing something.

I tried many different things like passing a path `/pghero` and what not but can't get it to work.

**Comment by mholt** [comment]
Well, I dunno, you'll have to file an issue with that plugin.

But we can write a new one for v2, given time or funding.

**Comment by scalp42** [comment]
I understand, closing.

**Comment by mholt** [comment]
@scalp42 Would you like to help us build it? Then your request would be answered!

**Comment by jlelse** [comment]
I'm interested in a similar option in v2. I currently successfully use the plugin with v1 to append a script tag to HTML files.

**Comment by mholt** [comment]
@jlelse Would be happy to see it built! Maybe not in this repo, but if you make a repo we can continue the discussion there, maybe a design doc.
