### ISSUE TITLE
v2: stripped `Server` header present in error pages

### ISSUE THREAD

**Issue by hayalci** [caddyserver/caddy#3071]
Found in latest beta version: v2.0 Beta 10.

Using a simple configuration like below, the present & accessible files are served without the `Server` header, but if the file is not present, or accessible, 404/403 errors are still served with the `Server header. They should be stripped from in-build server responses, too.

```
:80
[...]
header -Server
```

There's a prior bug for v1 here: https://github.com/caddyserver/caddy/issues/1183

**Comment by mholt** [comment]
Caddy 2's error handlers are a completely different chain of middleware than the primary handlers. If the primary handlers return an error, the error handlers are executed.

Soon, there will be a way to define error routes in the Caddyfile. It's already committed on the v2 branch and will go out with the next beta tag, beta15:

```
handle_errors {
    header -Server
}
```

Although, I might change the directive name to just `errors` or something. Not sure yet.
