### ISSUE TITLE
eol for v1

### ISSUE THREAD

**Issue by cweagans** [caddyserver/caddy#3073]
How long will v1 be supported? I still need http.git and that doesn't appear to be a thing for v2 yet.

**Comment by mholt** [comment]
Good question... I've already stopped developing for it -- will probably tag anything if there's a significant security fix for a while, but not sure yet how long!

AFAIK though, it's stable and working, so there's not much else to do on it.

I also hope to see a git module for v2, but written in pure Go! That should be possible now that the Go ecosystem has advanced significantly in the last ~5 years.

(Closing, but feel free to continue discussion.)

**Comment by tobya** [comment]
V1 is the primary stable version of Caddy.  It should be used in production until such time as V2 is stable for production.

**Comment by adriens** [comment]
https://caddy.community/t/caddy-version-1-end-of-life-date/7835/10

So is it reasonable to say it's eol since 2020-07-01 ?

**Comment by francislavoie** [comment]
Yes. Very super mega dead.
