### ISSUE TITLE
v2: Caddyfile  file server not work in win7

### ISSUE THREAD

**Issue by tiantian1645** [caddyserver/caddy#3076]
### 1a. Operating system and version

```
Win7 x64
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.0.0-beta.14 h1:QX1hRMfTA5sel53o5SuON1ys50at6yuSAnPr56sLeK8=
```

### 2a. What happens (briefly explain what is wrong)

caddy run from Caddyfile with file_server conf
Here is Caddyfile
```
:8080

root * E:\WebServer
file_server
```

curl config output
```
E:\Caddy_Test>curl localhost:2019/config/
{"apps":{"http":{"servers":{"srv0":{"listen":[":8080"],"routes":[{"handle":[{"handler":"vars","root":"E:\\WebServer"},{"handler":"file_server","hide":["Caddyfile"]}]}]}}}}}
```

But could not get anything in http://127.0.0.1:8080/

### 2c. Log output

```
paste terminal output or logs here
```

**Comment by mholt** [comment]
Thanks for finding the bug report template! But I think there was a mistake, it's only half filled out. Feel free to finish filling it out and we can take a look.

**Comment by CHN-STUDENT** [comment]
@mholt hello i want to know which version can work on windows7, my company has some old version, i need use caddy as proxy webserver/

**Comment by mholt** [comment]
I'm not sure, sorry. You'll need to use the latest version of Caddy that compiles with Go 1.20, but I'm not exactly sure which Caddy version still compiles with Go 1.20. Look for Caddy versions around the end of 2022.

**Comment by CHN-STUDENT** [comment]
hey, i download and use caddy 2.3, now it can work normally as proxy webserver on windows7. thanks!
