### ISSUE TITLE
v1: Download URL obtained from the offical website returns error

### ISSUE THREAD

**Issue by ericpai** [caddyserver/caddy#3084]
Hi，I tried to download Caddy v1 from the offical site with `tls.dns.dnspod` and `http.forwardproxy` plugins installed but failed. 

The download link:  https://caddyserver.com/download/linux/amd64?plugins=http.forwardproxy,tls.dns.dnspod&license=personal&telemetry=on
The page output:

![image](https://user-images.githubusercontent.com/3821212/75403535-fcaaff80-5942-11ea-81b2-c8fe72a5962c.png)

Is there something happend during the build process?

**Comment by mholt** [comment]
Yeah, it's probably broken :(

I don't have time to fix it right now (without extra funding/sponsorship for that) esp. with a rewrite for the v2 build server pending, and v2 betas to roll out the door. Sorry. But  you can always build from source!
