### ISSUE TITLE
reverse_proxy throws 500 when proxying next.js application

### ISSUE THREAD

**Issue by harshzalavadiya** [caddyserver/caddy#3102]
*Caddy2 looks amazing thank you for making this*

while proxying nextjs application through `caddy@2.0-beta-15` webserver throws 500 with below error message
```log
2020/02/28 21:30:29.014 ERROR   http.log.error  html/template:/: "'" in attribute name: "'r\xd8\"\xad\xb8\x04\xb7\xcd\v0\xfcM\xd3,acrD\xbd#\x01\x1bh\x10n\t\x9c\xa9\xadI\x87"       {"request": {"method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "103.57.81.159:60506", "host": "staging.foobars.in", "headers": {"User-Agent": ["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Sec-Fetch-Site": ["none"], "Sec-Fetch-User": ["?1"], "Accept-Encoding": ["gzip, deflate, br"], "Upgrade-Insecure-Requests": ["1"], "Sec-Fetch-Dest": ["document"], "Sec-Fetch-Mode": ["navigate"], "Accept-Language": ["en-US,en;q=0.9,la;q=0.8,so;q=0.7,hi;q=0.6,id;q=0.5,nb;q=0.4"], "Dnt": ["1"]}, "tls": {"resumed": false, "version": 772, "ciphersuite": 4867, "proto": "h2", "proto_mutual": true, "server_name": "staging.foobars.in"}}, "status": 500, "err_id": "3n7rjvxex", "err_trace": "templates.(*Templates).executeTemplate (templates.go:282)"}
```

**Caddyfile**
```Caddyfile
staging.foobars.in {
    templates
    encode zstd gzip
    tls email@example.com

    reverse_proxy {
        to localhost:3000 # or online version sdfdasdfd-inmswkmfy.now.sh
    }
}
```

**OS**
Ubuntu 18.04.3 LTS

**Node**
v12.16.0 LTS

- `curl localhost:3000` works fine and sends appropriate response but caddy throws 500 instead of proxying it transparently
- strangly copying content into html and serving that html also proxies properly

also link to barebones nextjs application sample used for reproducing this issue can be found at https://github.com/harshzalavadiya/nextjs-barebones/tree/master

**Comment by mholt** [comment]
Thanks for the report - is that the minimum config necessary to replicate the problem? Can you reduce it even further?

**Comment by harshzalavadiya** [comment]
Do you mean caddyfile or Barebones application barebones application is minimal let me check for caddyfile if i can remove anything else

**Comment by harshzalavadiya** [comment]
@mholt 
- while investigating more on this issue i found that having `templates` is breaking the output and breaks the response
- While checking random output from view source *I wasn't exactly reproduce this response but once i got something like this in view-source response* but i got something like below output as well
```html
  | <!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="widtta charS:xEdevice-arS:x,minimum-scale=1,initial-scale=1name="viewport"-fouc=e d-count="widtta ch2namelink rel="preload" href="/_-founosatic/developmta /pages/index.js?ts=7=a:xT82926944074" as="charSelink rel="preload" href="/_-founosatic/developmta /pages/inde_appts=7=a:xT82926944074" as="charSelink rel="preload" href="/_-founosatic/deverEa:xTCme/webpack=7=a:xT82926944074" as="charSelink rel="preload" href="/_-founosatic/deverEa:xTCme/main=7=a:xT82926944074" as="charSelink rext-hide-id="_osati_css__DO_NOT_USE__"ta charSet="u/a-nextock}><div-id="_osati"><div>Here be 🐉</div></div><t-hide-srcounosatic/developmta /pages/dll/dll_88bfe47d29by-ynprel_
-- | --

```

p.s. basically removing `templates` fixes the issue I am no expert in caddy configuration

**Comment by mholt** [comment]
Right, well... `templates` is seeing malformed HTML in the response, which is why it's throwing an error.

Are you even using [Caddy templates](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/templates/) in your HTML? If not, just remove `templates`.

(Closing, since I don't think this is a bug in Caddy, but feel free to continue discussion... maybe on the forum if you just have questions about how to use it.)

**Comment by mindon** [comment]
> Right, well... `templates` is seeing malformed HTML in the response, which is why it's throwing an error.
> 
> Are you even using [Caddy templates](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/templates/) in your HTML? If not, just remove `templates`.
> 
> (Closing, since I don't think this is a bug in Caddy, but feel free to continue discussion... maybe on the forum if you just have questions about how to use it.)

that means with templates, using **reverse_proxy** is risky in caddy2. 
could there any method to turn templates off only under a **reverse_proxy**?

**Comment by mholt** [comment]
It's not "risky" -- if you're enabling templates on a route, it means that the response is expected to be a template document to be evaluated (for text content-type anyway). Just enable templates for routes where templates will be used. Don't enable them "just because" or "just in case" you might use them or something.

**Comment by mindon** [comment]
> It's not "risky" -- if you're enabling templates on a route, it means that the response is expected to be a template document to be evaluated (for text content-type anyway). Just enable templates for routes where templates will be used. Don't enable them "just because" or "just in case" you might use them or something.

i see. in this case, a not-match-regexp route for templates may help. (complex but works)

**Comment by francislavoie** [comment]
You can already do that with request matchers @mindon, there's nothing for us to do here. https://caddyserver.com/docs/caddyfile/matchers#syntax

**Comment by mindon** [comment]
> 

thank you, yes it's the proper way to use templates. I just tried, it work great.

**Comment by francislavoie** [comment]
@mindon you write it like this:

```
@named not path_regexp ...
```

**Comment by mindon** [comment]
should proper using templates like

```
route @proxy {
	reverse_proxy 127.0.0.1:9000
}

route {
	templates
}
```

instead of 

```
templates

route @proxy {
	reverse_proxy 127.0.0.1:9000
}
```

**Comment by francislavoie** [comment]
@mindon I don't understand what you're trying to say.

But either way, you're commenting on an issue that was closed over two years ago. Please don't do that. Open a new issue if you think there's a bug, or ask a question on the forums https://caddy.community
