### ISSUE TITLE
Caddy 1.0.4 appears to not support RSA-AES256-CBC-SHA RSA-AES128-CBC-SHA unless the server is using a RSA certificate/key

### ISSUE THREAD

**Issue by CMCDragonkai** [caddyserver/caddy#3113]
Not sure if v1 is important anymore, but I discovered this while trying to enable the ciphers `RSA-AES256-CBC-SHA RSA-AES128-CBC-SHA`.

These ciphers did not appear in various TLS test suites like ssllabs and testssl.sh.

However as soon as I changed my server cert and key to RSA based, these 2 ciphers appeared.

This seemed strange, there's nothing indicating that the server's certificate and key type impacts what kind of ciphers that the server supports.

For now, I'm sticking to using RSA TLS certs and keys for caddy 1.0, as I need to support those ciphers for iPXE.

**Comment by mholt** [comment]
I think that's expected (and, obvious if you think about how the handshakes work) -- you can't offer EC signatures from an RSA key, for example. So it makes sense that only compatible suites are given.

**Comment by CMCDragonkai** [comment]
There should be a warning or an error if caddy is configured this way.
