### ISSUE TITLE
value of `admin` option in Caddyfile isn't validated

### ISSUE THREAD

**Issue by OmgImAlexis** [caddyserver/caddy#3126]
My current `Caddyfile`. I'm using the caddy/caddy docker container.

```Caddyfile
{
    admin {
        disabled false
        listen :2018
    }
}

:80 {
    respond "Please setup this site!"
}
```

```bash
INGRESS_SERVICE_NAME="ingress-controller"
INGRESS_HTTP_PORT="80"
INGRESS_HTTPS_PORT="443"

docker service create \
        --quiet \
        --name $INGRESS_SERVICE_NAME \
        --restart-condition any \
        --mount type=volume,source=caddy-data,target=/data \
        --mount type=volume,source=caddy-config,target=/config \
        --mount type=bind,source=/etc/caddy/Caddyfile,target=/etc/caddy/Caddyfile \
        --network internal \
        --publish $INGRESS_HTTP_PORT:80 \
        --publish $INGRESS_HTTPS_PORT:443 \
        caddy/caddy
```

```
root@docker-s-1vcpu-1gb-tor1-01:/repos/demo.git# docker logs ingress-controller.1.wsxehkpbknnnzwi68qfthyyb6 
2020/03/08 05:02:48.876	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
2020/03/08 05:02:48.889	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2020/03/08 05:02:48.890	INFO	http	server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server	{"server_name": "srv0", "http_port": 80}
2020/03/08 05:02:48.890	INFO	tls	cleaned up storage units
2020/03/08 05:02:48.893	INFO	autosaved config	{"file": "/config/caddy/autosave.json"}
2020/03/08 05:02:48.893	INFO	serving initial configuration
2020/03/08 05:02:48 [INFO][cache:0xc00020a5a0] Started certificate maintenance routine
```

`/config/caddy/autosave.json`
```json
{
  "admin": {
    "listen": "localhost:2019"
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "handle": [
                {
                  "body": "Please setup this site!",
                  "handler": "static_response"
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by Mohammed90** [comment]
In Caddyfile, the [`admin` config](https://caddyserver.com/docs/caddyfile/options) takes either `off` or an dress to listen on, without opening braces. So your Caddyfile should be:
```
{
    admin :2018
}

:80 {
    respond "Please setup this site!"
}
```

**Comment by OmgImAlexis** [comment]
It’d be nice if that was shown in the docs. Everywhere the admin section is mentioned I can only find links back to the json version of the caddy file.

**Comment by Mohammed90** [comment]
> It’d be nice if that was shown in the docs.

It is. See here https://caddyserver.com/docs/caddyfile/options

**Comment by OmgImAlexis** [comment]
Yeah and look at where the admin section links to. The v1 docs were never this hard to work out.

**Comment by mholt** [comment]
> Yeah and look at where the admin section links to.

What do you mean by this? It links to the API docs, as expected.

> The v1 docs were never this hard to work out.

v1 was about 10% as capable as v2.

(Closing, as this seems to be resolved)

**Comment by OmgImAlexis** [comment]
The main section at the top links to how to configure the admin section which leads to the json only config. Caddy also throws no errors with what I passed instead it just ignores it. This isn’t resolved. 

The v1 docs were a lot easier to understand. I’m a dev and I’m even having trouble navigating the new docs.

**Comment by OmgImAlexis** [comment]
Also on the note of the docs it’s nothing todo with how it’s got more stuff added. Yeah I get that but the docs are still really really hard to navigate. Yeah you might find it easy as you actually work on caddy. I bet if you ask users they’ll come back with the same answer.

**Comment by francislavoie** [comment]
> The main section at the top links to how to configure the admin section which leads to the json only config.

I don't understand what you're referring to. https://caddyserver.com/docs/caddyfile/options doesn't link to any JSON config.

Please give us links and quote the actual part in the docs you find confusing.

> Caddy also throws no errors with what I passed instead it just ignores it.

That's valid, it's surprising that it didn't give an error when parsing the admin config you gave.

> Yeah you might find it easy as you actually work on caddy. I bet if you ask users they’ll come back with the same answer.

That's not a very helpful comment, we need specific examples of what needs improving. It's not constructive to just say "it's bad, fix it". You're not the first person to complain about information clarity in the docs. Most of the time, people haven't been able to (or weren't willing to) point to any specific examples of things that aren't clear, so it makes it hard for us to improve things.

**Comment by francislavoie** [comment]
For reference, this is the bit of code that is parsing the `admin` config for the Caddyfile.

https://github.com/caddyserver/caddy/blob/v2/caddyconfig/httpcaddyfile/httptype.go#L333-L338

It should probably verify that `adminConfig` is a valid address, and return an error otherwise.

**Comment by Mohammed90** [comment]
Ok, I'll work on adding the validation this coming weekend.

Editing the issue subject to: value of `admin` option in Caddyfile isn't validated

**Comment by logbhai126** [comment]
``
