### ISSUE TITLE
How to configure forwardproxy for multiple websites？

### ISSUE THREAD

**Issue by ysbreh** [caddyserver/caddy#3135]
Caddyfile：

domain1.net
{
root /var/www/html1
tls xxxxx@gmail.com
forwardproxy {
basicauth user1 pass1
hide_ip
hide_via
probe_resistance
upstream http://127.0.0.1:1080
}
}
domain2.net
{
root /var/www/html2
tls xxxxx@gmail.com
forwardproxy {
basicauth user2 pass2
hide_ip
hide_via
probe_resistance
upstream http://127.0.0.1:1081
}
}

Configure the second Web site does not work！

**Comment by francislavoie** [comment]
Please ask your usage questions on https://caddy.community! This is the issue board for bugs and feature requests.
