### ISSUE TITLE
fmt: Brace opening global options block is wrongly indented

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#3144]
@vrongmeal Got another one for you!

```
{
debug
}
```

I expect that to format to:

```
{
	debug
}
```

but the output is:

```
 	{
	debug
}
```

Would you have a chance to help us fix it? :+1:

**Comment by vrongmeal** [comment]
Yeah, I don't have my laptop with me right now. Will be reaching home in a couple of days and then I can look into this.

**Comment by mholt** [comment]
No hurry :) Thanks!
