### ISSUE TITLE
Add domain ip info into logs.

### ISSUE THREAD

**Issue by Fi1osof** [caddyserver/caddy#3154]
Enhancment.

When server try to get LE certs, i see same info:
'''
proxy_1   | [domain-xxxxxxxx] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://domain-xxxxxxxx/.well-known/acme-challenge/hFV4ygnqqq7vOIXXXXXXXXXXXXXXX: Timeout during connect (likely firewall problem), url: 
proxy_1   |  (attempt 1/3; challenge=http-01)
'''

My problem: i change domain ip (A-record), but LE still use old ip (event for new CNAME records). But i sis not see this in debug log. I can see this only when open LE links in browser.

Can you add ip info in debug info at least for errors?

Thanks!

**Comment by mholt** [comment]
We just print the errors that LE gives us, you might want to ask [on the LE forum](https://community.letsencrypt.org/) instead.

**Comment by Fi1osof** [comment]
OK. Thanks
