### ISSUE TITLE
please update download link

### ISSUE THREAD

**Issue by xdaniel9** [caddyserver/caddy#3156]
the download page's latest version is still 1.0.4 but 1.0.5 is released 19 days ago

**Comment by mholt** [comment]
Hi, thanks for your concern. Unfortunately macOS Catalina broke the release program for Caddy 1 and I'm not sure how to fix it, without investing hours into it, which I don't have time to do right now. I could do things manually but that might take even _more_ time (releases used to take on the order of ~1 day), so for now, just build from source or download from GitHub. Thanks!
