### ISSUE TITLE
linux-systemd/caddy.service is not working correctly

### ISSUE THREAD

**Issue by jmaister** [caddyserver/caddy#3158]
On the guide for systemd on page https://github.com/caddyserver/caddy/tree/master/dist/init/linux-systemd
The https://raw.githubusercontent.com/caddyserver/caddy/master/dist/init/linux-systemd/caddy.service file is not configured properly and shows this error when the service is started:

```
-- Logs begin at Sat 2019-12-14 10:37:34 UTC. --
Mar 19 20:21:39 calamardo systemd[1]: Started Caddy HTTP/2 web server.
Mar 19 20:21:39 calamardo caddy[26520]: [ERROR] first argument must be a subcommand; see 'caddy help'
Mar 19 20:21:39 calamardo systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Mar 19 20:21:39 calamardo systemd[1]: caddy.service: Failed with result 'exit-code'.
```

I am using caddy version: v2.0.0-beta.17 h1:x+Ur3uX83j+STerOWsrLDlknXe7z71VnO5xD+H2OwAw=

**Comment by mholt** [comment]
Looks like you're using the service file for v1 with Caddy 2. See https://github.com/caddyserver/dist for v2 resources!

**Comment by jmaister** [comment]
Thanks @mholt 

Is there another guide like this https://github.com/caddyserver/caddy/tree/master/dist/init/linux-systemd
for Caddy 2 ?

**Comment by mholt** [comment]
See the comments: https://github.com/caddyserver/dist/blob/master/init/caddy.service

Also: https://caddyserver.com/docs/install#manually-installing-as-a-linux-service
