### ISSUE TITLE
Get an error when I build Caddy

### ISSUE THREAD

**Issue by ghhk** [caddyserver/caddy#3165]
go get github.com/caddyserver/caddy/caddy

# github.com/caddyserver/caddy/caddytls
github.com/caddyserver/caddy/caddytls/config.go:119:4: cannot use func literal (type func(certmagic.Certificate) (certmagic.Config, error)) as type certmagic.ConfigGetter in field value
github.com/caddyserver/caddy/caddytls/setup.go:135:19: config.Manager.Email undefined (type *certmagic.Config has no field or method Email)
github.com/caddyserver/caddy/caddytls/setup.go:153:19: config.Manager.CA undefined (type *certmagic.Config has no field or method CA)
github.com/caddyserver/caddy/caddytls/setup.go:160:19: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
github.com/caddyserver/caddy/caddytls/setup.go:257:19: config.Manager.DNSProvider undefined (type *certmagic.Config has no field or method DNSProvider)
github.com/caddyserver/caddy/caddytls/setup.go:269:9: undefined: certmagic.HostQualifies
github.com/caddyserver/caddy/caddytls/setup.go:361:27: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
github.com/caddyserver/caddy/caddytls/tls.go:74:4: undefined: certmagic.HostQualifies
github.com/caddyserver/caddy/caddytls/tls.go:80:42: not enough arguments in call to certmagic.NewDefault().RevokeCert
	have (string, bool)
	want (context.Context, string, bool)
# github.com/lucas-clemente/quic-go
github.com/lucas-clemente/quic-go/interface.go:54:2: duplicate method StreamID
github.com/lucas-clemente/quic-go/stream.go:44:2: duplicate method StreamID

I have followed every steps from README.md and tried it in my other server.However,there is still the same error . Pls help me. I have spent a lot time on it......

First I used GO 1.14 on ubuntu 16.04 (Follow the steps from https://golang.org/doc/install)，it give me an error
then I used GO 1.13 on debian 9, it still give me an error，I am almost going crazy.....

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by ghhk** [comment]
I'm sorry to bother you, but I really spent a lot of time, and now I'm stuck here and going crazy, can you help me with some suggestions

**Comment by ghhk** [comment]
> 感谢您的提问，让您使用Caddy感到很高兴！这看起来更像是关于如何使用Caddy的问题，而不是错误报告或功能请求。由于此问题跟踪器仅用于可行的开发项目，因此我将结束本节，但是我们有一个[社区论坛](https://caddy.community)，在该[论坛上](https://caddy.community)，更多的人可以接触到您的问题，包括可能对您所遇到的特定问题更专业或有经验的人重新面对。希望您在这里提出您的问题，并感谢您的理解！



> Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

I'm sorry to bother you, but I really spent a lot of time, and now I'm stuck here and going crazy, can you help me with some suggestions

**Comment by ghhk** [comment]
> Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

I'm sorry to bother you, but I really spent a lot of time, and now I'm stuck here and going crazy, can you help me with some suggestions

**Comment by ghhk** [comment]
`# github.com/caddyserver/caddy/caddytls
go/src/github.com/caddyserver/caddy/caddytls/config.go:119:4: cannot use func literal (type func(certmagic.Certificate) (certmagic.Config, error)) as type certmagic.ConfigGetter in field value
go/src/github.com/caddyserver/caddy/caddytls/setup.go:135:19: config.Manager.Email undefined (type *certmagic.Config has no field or method Email)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:153:19: config.Manager.CA undefined (type *certmagic.Config has no field or method CA)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:160:19: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:257:19: config.Manager.DNSProvider undefined (type *certmagic.Config has no field or method DNSProvider)
go/src/github.com/caddyserver/caddy/caddytls/setup.go:269:9: undefined: certmagic.HostQualifies
go/src/github.com/caddyserver/caddy/caddytls/setup.go:361:27: config.Manager.KeyType undefined (type *certmagic.Config has no field or method KeyType)
go/src/github.com/caddyserver/caddy/caddytls/tls.go:74:4: undefined: certmagic.HostQualifies
go/src/github.com/caddyserver/caddy/caddytls/tls.go:80:42: not enough arguments in call to certmagic.NewDefault().RevokeCert
	have (string, bool)
	want (context.Context, string, bool)`

**Comment by Mohammed90** [comment]
@ghhk , do:
`git clone https://github.com/caddyserver/caddy caddy-v1`
`cd caddy-v1/caddy`
`go build`

**Comment by ghhk** [comment]
> @ghhk , do:
> `git clone https://github.com/caddyserver/caddy caddy-v1`
> `cd caddy-v1/caddy`
> `go build`
Thank you for your help,after I type the command you said，when I type any about caddy it give me  caddy: command not found.......

`root@Nathosts-201925624:~/caddy-v1/caddy# go build
go: downloading gopkg.in/natefinch/lumberjack.v2 v2.0.0
go: downloading github.com/jimstudt/http-authentication v0.0.0-20140401203705-3eca13d6893a
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/gorilla/websocket v1.4.0
go: downloading github.com/russross/blackfriday v0.0.0-20170610170232-067529f716f4
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/flynn/go-shlex v0.0.0-20150515145356-3f9db97f8568
go: downloading github.com/mholt/certmagic v0.8.3
go: downloading github.com/hashicorp/go-syslog v1.0.0
go: downloading github.com/klauspost/cpuid v1.2.0
go: downloading github.com/lucas-clemente/quic-go v0.13.1
go: downloading github.com/naoina/toml v0.1.1
go: downloading github.com/go-acme/lego/v3 v3.3.0
go: downloading golang.org/x/net v0.0.0-20191027093000-83d349e8ac1a
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading github.com/onsi/ginkgo v1.7.0
go: downloading github.com/marten-seemann/qpack v0.1.0
go: downloading github.com/cheekybits/genny v1.0.0
go: downloading github.com/cenkalti/backoff/v3 v3.0.0
go: downloading github.com/miekg/dns v1.1.15
go: downloading github.com/marten-seemann/qtls v0.4.1
go: downloading github.com/marten-seemann/chacha20 v0.2.0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading github.com/golang/protobuf v1.3.2
go: downloading golang.org/x/text v0.3.2
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading gopkg.in/fsnotify.v1 v1.4.7
root@Nathosts-201925624:~/caddy-v1/caddy# caddy
caddy: command not found
root@Nathosts-201925624:~/caddy-v1/caddy# caddy version
caddy: command not found
`

**Comment by ghhk** [comment]
Thx for your help, I used To build Caddy with plugins (and with version information) which from README.md and now succefully install Caddy v1.0.5 (h1:5B1Hs0UF2x2tggr2X9jL2qOZtDXbIWQb9YLbmlxHSuM=)  

However, I get an dnspod json error when I run caddy Caddyfile. I remenber that the issue has been solved in v1.0.5 but why I use it and still get the error? 

I find that when I run go build then it still downloading the lego v3.2.0 instead of v3.3.0 which solve the issue

Can you just help me how to upgrade the lego to v3.3.0 and tell me why it download v3.3.0 while my caddy's version is v1.0.5?   Thank you!

**Comment by Mohammed90** [comment]
Let's move the discussion to the forum.

**Comment by ghhk** [comment]
> Let's move the discussion to the forum.

Ok, thank you very much!
