### ISSUE TITLE
Any chance for ARMv7 beta build? (RPi)

### ISSUE THREAD

**Issue by microcreators** [caddyserver/caddy#3175]
Just trying to find a decent, yet simple rev proxy for RPi and it seems caddy v2 is 'round the corner, so would love to try it instead of v1. Thanks in advance.

**Comment by mholt** [comment]
Yeah actually, that seems to be the kind of thing #3173 will help with. /cc @Mohammed90

**Comment by microcreators** [comment]
Building and ... (1000 years later) 
`go: verifying github.com/smallstep/certinfo@v1.0.0/go.mod: checksum mismatch`
:)

**Comment by Mohammed90** [comment]
It builds fine for me. I'm suspecting your go.mod file was inadvertently altered somehow. Anyways, I've built it on my machine, gzipped it, and attached here.

sha512sum of the executable: `fcb5ad563535be2c4b68730ec907b6a27642da11b99576150f0a52c7e59bf14f5b9a321c920da48be72dbd62e3dfbbf4a7437290ee798fde44d005710c4face7`

sha512sum of the gzipped file:
`f0ca7b49756acb076491102f4ebc29ff0c6aef5c6963eccf2a09a6082af3ab3891c2bce644d560583d54a8d1ed24b557fcf2140b72cc325cb07b9effb99cc271`

[caddy.gz](https://github.com/caddyserver/caddy/files/4369352/caddy.gz)

**Comment by microcreators** [comment]
Thanks a lot @Mohammed90! I'll try building again the new beta few days from now.
