### ISSUE TITLE
v2: file-server response has no Content-Type ?

### ISSUE THREAD

**Issue by humbinal** [caddyserver/caddy#3190]
Previously， I used V1 version，file-server HTTP response Headers has "Content-Type: text/plain; charset=utf-8", my text file is open in browser is OK.

But now I use the version v2-bata20 ，the HTTP response Headers  has no Content-Type key and value. Now my text file is open in browser, and there is **Garbled character**.

I use the following command to start the file-server:
`./caddy2_beta20_linux_amd64 file-server -browse -listen 0.0.0.0:2015 -root /home`

What should I do?

**Comment by mholt** [comment]
In v2, MIME sniffing is off by default for security reasons (a researcher complained about a plausible vulnerability in combination with bad clients and apps in a conference talk). Caddy can infer Content-Type from file extension, but if that is missing or unknown, you can always set the header manually using the [header](https://caddyserver.com/docs/caddyfile/directives/header) directive.

**Comment by humbinal** [comment]
@mholt  thank you, I found the cause of the problem, because my linux has no '/etc/mime.types' file.

**Comment by francislavoie** [comment]
Very interesting! Thanks for following up, I don't think we would've ever guessed that being the issue.

**Comment by mholt** [comment]
That does make sense, though, the std lib uses a MIME table from the system: https://golang.org/pkg/mime/#TypeByExtension

**Comment by tribor** [comment]
> @mholt thank you, I found the cause of the problem, because my linux has no '/etc/mime.types' file.

So how did you fix it?
I'm using a docker container (caddy/caddy:alpine) and installed the package 'mailcap' for the file '/etc/mime.types' but still have no content-type while serving font/js files.

**Comment by evenreven** [comment]
I had this issue too and installed mailcap, which fixed it. I posted about it on COPR since my install was from there (CentOS): https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/

As a novelty, here's the 14 year old (!) very similar bug report afflicting httpd on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=249223 :D 
I think they solved it by adding mailcap as dependency.
