### ISSUE TITLE
Fix race/inconsistent results in integration tests

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#3191]
Opening an issue to track the inconsistent results of integration tests, especially on Windows, in our CI workflow. /cc @sarge

It's not a data race per-se, but does appear to fail sometimes or another.

**Comment by mholt** [comment]
(Also, if a config fails to load, the test should not continue as if the loading succeeded, which will actually use the config from the previous test.)

**Comment by sarge** [comment]
Just an update on this, I would need a windows machine to load the https://hub.docker.com/_/microsoft-windows-servercore as the os of the container and the os of the docker image must match.

**Comment by francislavoie** [comment]
@sarge Amazon does have Windows images if you're willing to try that, shouldn't be too expensive. You can RDP into them and mess around.

**Comment by francislavoie** [comment]
I think this is solved by https://github.com/caddyserver/caddy/pull/3966 /cc @Mohammed90
