### ISSUE TITLE
single or double dashed flags? "caddy -quic" or "caddy --quic"?

### ISSUE THREAD

**Issue by phlinhng** [caddyserver/caddy#3203]
This question might sounds stupid but I couldn't find answer online easily...
In most tutorial of caddy, flag `conf` was used as double dashed `--conf`. For example:
```s
caddy --conf /etc/caddy/Caddyfile
```
But in tutorial about enabling `quic`, even the caddy official wiki, use single dashed `-quic`, for example:
```s
caddy -quic
```
This made me confused, are single dashed flags work equally with double dashed flags? I've tried to mixed them like `caddy --conf /etc/caddy/Caddyfile -quic` and caddy still works fine.

**Comment by mholt** [comment]
Go's flag parser accepts either: https://golang.org/pkg/flag
