### ISSUE TITLE
Ddd origin as a variable for CORS settings

### ISSUE THREAD

**Issue by mikevalstar** [caddyserver/caddy#3206]
Can we have something like `http.request.origin` for the origin of the request for use with things like CORS.

See help request here: https://caddy.community/t/cors-origin-getting-referrer/7377

**Comment by mikevalstar** [comment]
This can be closed as you can get this from the Origin header. However it still may be useful to have a function / alias to restrict the list of origins for the CORS headers.

**Comment by mholt** [comment]
Okie dokie!

> However it still may be useful to have a function / alias to restrict the list of origins for the CORS headers.

I am curious what you mean by this, if you could elaborate that'd be great!

**Comment by titpetric** [comment]
@mholt I generally define trusted origins via a regexp in my own configs for one client, e.g.:

~~~
if ($http_origin ~* (https?://[^/]*(\.domain\.com|\.lan)(:[0-9]+)?)$) {
	set $cors "true";
}
~~~

The api lives on `api.domain.com`, and the allowed origins are basically `*.domain.com` and `*.lan` (development). I think the original reporter wanted a quick way to do an ACL over what he knows are valid domains for CORS origins. I'd like that too :)

**Comment by mholt** [comment]
@titpetric You can already match requests on their Origin header with a regex like this (assuming Caddyfile, but same thing can obviously be done in JSON):

```
@allowedOrigin {
    header_regexp Origin https?://[^/]*(\.domain\.com|\.lan)(:[0-9]+)?)$
}
header @allowedOrigin Access-Control-Allow-Origin {http.request.header.Origin}
```

^ Above is untested. But that's the basic idea!

**Comment by titpetric** [comment]
Great, I figured you might have something like it. I think it's resolved :)
