### ISSUE TITLE
v2: Wildcard host: Respond directive is ignored

### ISSUE THREAD

**Issue by lukasbestle** [caddyserver/caddy#3211]
**Caddy version:** `v2.0.0-beta9.0.20200401064340-809e72792c50 h1:r0vSakzB/zmOVhKZINtlCNi1NfaagKG2NP7oAZUSjL4=`

**Caddyfile:**

```
http://*, http://example.test {
  respond 404 {
    body "Host Not Found"
    close
  }
}
```

**Expected behavior:** Requests to `http://example.test/`, `http://example.test/test`, `http://another.test/` and `http://another.test/test` should all respond with the "Host Not Found" message and HTTP 404.

**Actual behavior**: While requests to `example.test` work (which is the host explicitly mentioned in the Caddyfile), all requests to `another.test` respond with an empty HTTP 200 response instead.

**Comment by mholt** [comment]
As mentioned in #3212, a `*` only matches a single label of a hostname. It's the same logic as here: https://caddyserver.com/docs/automatic-https#wildcard-certificates because host matchers influence the governance of TLS certificates.

I'll update the host matcher docs to clarify this.
