### ISSUE TITLE
specify ACME account ID

### ISSUE THREAD

**Issue by gsmachado** [caddyserver/caddy#3213]
How can I specify the ACME account ID in Caddy?

For example, the [Let's Encrypt Rate Limit Adjustment Request Form](https://docs.google.com/forms/d/e/1FAIpQLSetFLqcyPrnnrom2Kw802ZjukDVex67dOM2g4O8jEbfWFs3dA/viewform) provides the option to increase rate limits for a single ACME account ID.

I could not find this information in the [Caddyfile Directive TLS](https://caddyserver.com/docs/caddyfile/directives/tls).

**Comment by mholt** [comment]
It's not something you specify, it's something your account is assigned.

Your account ID is in your [data directory](https://caddyserver.com/docs/conventions#data-directory). Similar to the [Let's Encrypt docs here](https://letsencrypt.org/docs/account-id/), it's in the registration JSON file, for example:

```
"uri": "https://acme-v02.api.letsencrypt.org/acme/acct/12345678"
```

The account ID is "12345678"

In the future, questions like this can go on [our forums](https://caddy.community) - thank you!
