### ISSUE TITLE
v2 Caddyfile feature request: Exclude files from glob import

### ISSUE THREAD

**Issue by dbohdan** [caddyserver/caddy#3215]
The `import` directive isn't documented yet, but the [current Caddyfile parser code](https://github.com/caddyserver/caddy/blob/169883868503c809c9ac9c8c1fe93c7deff9cd2e/caddyconfig/caddyfile/parse.go#L286) shows that it takes a single argument, either a file path or a glob pattern.  It would be convenient to be able to do something more subtle: import files that match one pattern but _do not match_ another.

For example, you may want to `import Caddyfile.d/*` with the exception of `Caddyfile.d/*.old`.  During a Debian package upgrade you may want to `import` everything from a directory but not the temporary/backup `*.dpkg*` files.  (This is a real problem I have encountered.)

One way to express this in a Caddyfile could be with an optional "negative" regular expression argument to `import`.  Files matching the regular expression would be excluded.  For example:

    import Caddyfile.d/* old$

**Comment by mholt** [comment]
Why not just do `import Caddyfile.d/*.conf` or something? (i.e. give your files an extension)

**Comment by dbohdan** [comment]
You can do that.  It's the workaround I used in my Debian package.

I've just tried implementing my proposal and realized it was a poor substitute for what I actually wanted, which is more advanced glob  patterns than `filepath.Glob()` understands — not really viable here.   Never mind!

**Comment by mholt** [comment]
@dbohdan Do you maintain Debian packages? Would you like to help us maintain an official one?

**Comment by dbohdan** [comment]
Turning my internal packages into something I'd be happy to share with other Caddy users would be an amount of ongoing work I can't commit to.  Sorry.

Maybe instead of providing your own packages you could get Caddy into Debian?  There was at one point an [ITP (Intent to Package) for Caddy](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810890).  You could contact those who proposed and discussed it.

**Comment by dbohdan** [comment]
If anyone is interested, I have cleaned up and open-sourced the build script for my Caddy deb package: https://github.com/dbohdan/caddy-deb-opt.  The package differs from the official Caddy package:
* It installs Caddy to the directory `/opt/caddy/` and uses a `*/opt/*` path where possible.
* It keeps the configuration in `/etc/opt/caddy/Caddyfile.d/*.conf`, which is similar to the config directory the Debian package for Apache and for Nginx sets up.  This allows other packages to install their individual site configuration as `/etc/opt/caddy/Caddyfile.d/foo.conf` without conflicts over the main `Caddyfile`.
