### ISSUE TITLE
Disabling http-to-https redirect from Caddyfile

### ISSUE THREAD

**Issue by sqs** [caddyserver/caddy#3219]
Is it possible to [disable the HTTP-to-HTTPS redirects](https://caddyserver.com/docs/json/apps/http/servers/automatic_https/disable_redirects/) in Caddyfile?

My Caddyfile is:

```
sourcegraph.test:3443
tls internal
reverse_proxy localhost:3080
```

When I run `caddy` (as a non-root user), I get an error because it can't bind to port 80:

```
$ caddy run --config=dev/Caddyfile
2020/04/03 05:14:29.418	INFO	using provided configuration	{"config_file": "dev/Caddyfile", "config_adapter": ""}
2020/04/03 05:14:29.419	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2020/04/02 22:14:29 [INFO][cache:0xc0009afc20] Started certificate maintenance routine
2020/04/03 05:14:29.427	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2020/04/03 05:14:29.468	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
2020/04/03 05:14:29.468	INFO	tls	cleaned up storage units
run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: permission denied
```

I don't want it to try to bind to port 80. I believe it's doing so to enable HTTP-to-HTTPS redirects, so disabling those would suffice to solve my problem.

I can see how to disable them in JSON, but I like using Caddyfile because it's simple. I would like to not have to switch everything to JSON just for this one directive.

(Ref: https://github.com/sourcegraph/sourcegraph/issues/9536)

**Comment by mholt** [comment]
Hi Quinn! 👋 

It's not possible in the Caddyfile yet -- probably will be in 2.1 -- but for now you can set the HTTP port to something higher that has permission:

```
{
    http_port 8080
}
```

**Comment by sqs** [comment]
Thanks, that works for now! And thank you for Caddy overall. :smile:

**Comment by silmace** [comment]
> Hi Quinn! 
> 
> It's not possible in the Caddyfile yet -- probably will be in 2.1 -- but for now you can set the HTTP port to something higher that has permission, by putting an options block at the top of your Caddyfile:
> 
> ```
> {
>     http_port 8080
> }
> ```

Hello.😊
Can you add an Caddyfile option to disable https/tls,because I have another program listening at 443.Json can do this,but I've been using Caddyfile.....

**Comment by silmace** [comment]
> > 嗨奎因！
> > 在Caddyfile中尚不可能（可能在2.1中），但是现在您可以通过在Caddyfile的顶部放置一个options块，将HTTP端口设置为具有许可权限的更高端口：
> > ```
> > {
> >     http_port 8080
> > }
> > ```
> 
> 你好。
> 您是否可以添加Caddyfile选项来禁用https / tls，因为我有另一个程序正在监听443。Json可以做到这一点，但是我一直在使用Caddyfile ..

Okay,don't need this .I find it.
![IMG_20200415_160328](https://user-images.githubusercontent.com/62671124/79313449-f1cc1e80-7f32-11ea-847e-704bf4a4e0df.jpg)

**Comment by silmace** [comment]
> > Hi Quinn!
> > It's not possible in the Caddyfile yet -- probably will be in 2.1 -- but for now you can set the HTTP port to something higher that has permission, by putting an options block at the top of your Caddyfile:
> > ```
> > {
> >     http_port 8080
> > }
> > ```
> 
> Hello.
> Can you add an Caddyfile option to disable https/tls,because I have another program listening at 443.Json can do this,but I've been using Caddyfile.....

Okay,don't need ,I find it...
![IMG_20200415_160328](https://user-images.githubusercontent.com/62671124/79313629-33f56000-7f33-11ea-875c-f14dbe2466b9.jpg)

**Comment by mholt** [comment]
Version 2.1 will let you turn off automatic HTTPS or just the redirects with a global option:

```
auto_https off
```

to disable it entirely, or:

```
auto_https disable_redirects
```

to turn off only the redirects.

**Comment by NightMachinary** [comment]
[**@mholt**](https://github.com/mholt) commented on [May 20, 2020, 3:30 AM GMT+4:30](https://github.com/caddyserver/caddy/issues/3219#issuecomment-631131568 "2020-05-19T23:00:35Z - Replied by Github Reply Comments"):
> Version 2.1 will let you turn off automatic HTTPS or just the redirects with a global option:
> 
> ```
> {
>     auto_https off
> }
> ```
> 
> to disable it entirely, or:
> 
> ```
> {
>     auto_https disable_redirects
> }
> ```
> 
> to turn off only the redirects.

I have several subdomains on my caddyfiles, and only one of them uses the basic auth. I think allowing the HTTP to HTTPS redirects might compromise security there? Is it possible to disable the redirect for only a subdomain, say `https://secure.example.com`?

**Comment by francislavoie** [comment]
I don't see how a redirect would compromise security. Could you elaborate on what you mean?

**Comment by NightMachinary** [comment]
> I don't see how a redirect would compromise security. Could you elaborate on what you mean?

@francislavoie If HTTP redirect is on, clients can mistakenly connect to it and send the secret info over HTTP. If the redirection is off, they’ll still send the secret the first time, but then their request fails and they notice they had messed up.

**Comment by francislavoie** [comment]
Caddy won't prompt for `basicauth` over `HTTP`, it will only prompt if a proper TLS handshake has occurred. There's no risk here.

**Comment by NightMachinary** [comment]
[**@Francis Lavoie**](https://github.com/francislavoie) commented on [Jul 28, 2020, 12:35 AM GMT+4:30](https://github.com/caddyserver/caddy/issues/3219#issuecomment-664610265 "2020-07-27T20:05:16Z - Replied by Github Reply Comments"):
> Caddy won't prompt for `basicauth` over `HTTP`, it will only prompt if a proper TLS handshake has occurred. The redirect happens before `basicauth`. There's no risk here.
> 
> If you can prove that it's possible, then yes we can consider it a security issue, and you should open a new github issue with replication steps.

I only use this service myself, and I use it via CURL and other programmatic tools. So if I mistakenly use HTTP, I will have sent the necessary auth. (The mistake can also get hardcoded in my scripts, and that would be really bad.) It's not a big deal, but I like my stuff to break when I make a mistake.

**Comment by mholt** [comment]
@NightMachinary 

> I have several subdomains on my caddyfiles, and only one of them uses the basic auth. I think allowing the HTTP to HTTPS redirects might compromise security there?

This is not a security issue in the server.

> Is it possible to disable the redirect for only a subdomain, say https://secure.example.com?

This is a closed, unrelated issue. Please post on our forums for help instead: https://caddy.community

> clients can mistakenly connect to it and send the secret info over HTTP

![rob pike don't do that](https://user-images.githubusercontent.com/1128849/88592953-0e8ced80-d01c-11ea-8470-10a8ce87b5e3.gif)

**Comment by marga-kinvolk** [comment]
Regardless of the basic auth and whether or not this is a security issue, I think it would be nice if this option could be set per subdomain. I'm using a few different domains and in only one of them I need to disable the redirect (because it's queried by automatic processes that don't have SSL). In the other domains, I'd like to keep the redirection enabled because it's the right thing to do. Could this be made per-subdomain?

**Comment by francislavoie** [comment]
@marga-kinvolk just make a site block starting with `http://` to override the the redirect.

This is not a security issue unless proven otherwise. Like I said earlier:

> If you can prove that it's possible, then yes we can consider it a security issue, and you should open a new github issue with replication steps.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by marga-kinvolk** [comment]
Sorry that it wasn't clear, I was not trying to ask a usage question, but rather trying to make the point that disabling the redirect on a per-subdomain basis can be nice even when it's *not* a security issue. Anyway, yes, I solved my issue by repeating the block, although its quite ugly that I need to duplicate the whole entry.

Sorry about the noise.

**Comment by mholt** [comment]
(I knew this would happen, but...)

This is what the JSON is for. The Caddyfile is just a nice, convenient wrapper over the fine-grained control of the underlying JSON structure. If you need that full control, you can actually write really concise JSON files that do what you need, usually.

Going to lock this issue since it's off-topic and I'm sure our friends at Sourcegraph don't want to be bothered by something that was resolved ~6 months ago. Feel free to open a discussion on our forum, or a specific proposal as a new issue that we can act on if necessary.
