### ISSUE TITLE
v2: {http.request.port} is empty

### ISSUE THREAD

**Issue by w00kie** [caddyserver/caddy#3225]
Hello,

Using caddy version **v2.0.0-rc.1**

I'm setting up a Wordpress site with Jetpack plugin. The Wordpress site health tool complains that loopback is broken and to fix this I should add a `X-Forwarded-Port` header to pass the host port back to PHP-FPM. So I added the following to my CaddyFile:

```
(phpsite) {
        encode          gzip
        request_header  X-Forwarded-Port {http.request.port}
        php_fastcgi     unix//run/php/php7.4-fpm.sock
        file_server
}

mysite.com {
        root    * /var/www/mysite.com
        import  phpsite
}
```

But this just give me an empty value in `$_SERVER['HTTP_X_FORWARDED_PORT']`. Seems `{http.request.port}` is empty when not specifically specified.

Now I can just workaround this by fixing the value to 443 in the CaddyFile and it fixes my error in Wordpress, but that means I'll have to to some more custom directives if I ever want to serve a site on another port.

Shouldn't `{http.request.port}` always show the port caddy is serving the request on?

**Comment by mholt** [comment]
Off the top of my head, that placeholder puts the port in the Host header of the request. If it is omitted by the client, there won't be a value in that placeholder.

**Comment by helmut72** [comment]
Still empty for me. Doesn't matter if I try `{http.request.port}`, `"443"` or `443`.
