### ISSUE TITLE
Cannot use `caddy reload` if admin endpoint is turned off

### ISSUE THREAD

**Issue by qlaffont** [caddyserver/caddy#3234]
Hello everyone,
I installed caddy with success. Actually, I have changed my Caddy file so I want to reload my configuration but I have this error :

```
Apr 07 08:27:05 myvps caddy[21735]: {"level":"info","ts":1586240825.466126,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Apr 07 08:27:05 myvps caddy[21735]: reload: sending configuration to instance: performing request: Post "http://localhost:2019/load": dial tcp [::1]:2019: connect: connection refused
Apr 07 08:27:05 myvps systemd[1]: caddy.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecReload= process belonging to unit caddy.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Apr 07 08:27:05 myvps systemd[1]: Reload failed for Caddy Web Server.
-- Subject: A reload job for unit caddy.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A reload job for unit caddy.service has finished.
-- 
-- The job identifier is 8200 and the job result is failed.
Apr 07 08:27:05 myvps sudo[21732]: pam_unix(sudo:session): session closed for user root
```

And this is my caddy file

<img width="415" alt="Capture d’écran 2020-04-07 à 08 30 34" src="https://user-images.githubusercontent.com/10044790/78637239-4b38ab80-78aa-11ea-8554-a440d3c0c92e.png">

Caddy version
```sh
$ caddy version
v2.0.0-rc.1 h1:DxUlg4kMisXwXVnWND7KEPl1f+vjFpIOzYpKpfmwyj8=
```

Thanks ^^

**Comment by francislavoie** [comment]
If you turn off the admin endpoint with the `admin off` global option, you're also turning off the ability to reload configuration.

**Comment by qlaffont** [comment]
Okay I will try thanks

**Comment by qlaffont** [comment]
Is not working :
``` 
reload: sending configuration to instance: performing request: Post "http://unix//run/caddy.sock/load": dial tcp: lookup unix on 213.186.33.99:53: no such host
```

**Comment by francislavoie** [comment]
What is the exact command you used?

**Comment by qlaffont** [comment]
```
 1521  sudo service caddy stop
 1522  sudo service caddy start
 1523  sudo service caddy restart
 1524  sudo service caddy reload
```

i have set admin to `admin: 127.0.0.1:2019`
and i'm stuck ...
(i have disabled ufw)

**Comment by mholt** [comment]
I think @francislavoie meant, what are your `caddy` commands?

**Comment by qlaffont** [comment]
Actually I use Caddy Service specify in the doc :
```
# This service file requires the following:
#
# 1) Group named caddy:
#      $ groupadd --system caddy
#
# 2) User named caddy, with a writeable home folder:
#      $ useradd --system \
#           --gid caddy \
#           --create-home \
#           --home-dir /var/lib/caddy \
#           --shell /usr/sbin/nologin \
#           --comment "Caddy web server" \
#           caddy
#
# 3) Caddyfile at /etc/caddy/Caddyfile that is
#    readable by the caddy user
#

[Unit]
Description=Caddy Web Server
Documentation=https://caddyserver.com/docs/
After=network.target

[Service]
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --config /etc/caddy/Caddyfile --resume --environ
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

**Comment by mholt** [comment]
Thanks; a few things:

- I checked the code of the `caddy reload` command, and it expects a TCP address because it just uses Go's standard `net/http.DefaultClient` to send the HTTP request, which doesn't support Unix sockets without some extra hurdles to jump through. Theoretically we can add support for it, but it's more complicated, so it needs to be worth it.
- Stopping the server will not reload the configuration, it will take your site offline. Use `reload` instead, where possible.
- If you can't use reload because you need the admin endpoint disabled, you'll have to use stop and start, but your ExecStart uses the `--resume` flag which will resume the last active configuration. (This is important for durability in the event of system reboots, like for security updates, without inadvertently changing your server's config and breaking things.)

Everything appears to be working as expected, though!

I've clarified a few relevant points in the docs.

**Comment by qlaffont** [comment]
Okay I understand.

So if i want to fix my service, i just need to remove "--resume" flag forever. (Actually i want to bring back Caddy API)

I tried to run my Exec Start command without resume and after that try to do a `service caddy start` without success. it load previous configuration with `admin off`.

**Comment by qlaffont** [comment]
Maybe you have an option to clean config cache ? @mholt

**Comment by mholt** [comment]
@qlaffont 

> So if i want to fix my service, i just need to remove "--resume" flag forever.

Only so long as you want to change the config using the config file when you stop and restart the server. This can lead to data loss if using the API though, so be careful.

**Comment by pungotoken** [comment]
Still a noob, but actually solved this issue by using adapt instead of reload. It rebuilds the caddyfile.
so, for me:

1) stop caddy service
2) ./caddy adapt or sudo ./caddy adapt
3) chown if needed
4) start caddy service again

**Comment by zQueal** [comment]
I have no idea why, but I followed the steps above (as well as I could, as my `caddy.service` file wasn't using `--resume`), and it seems to have worked.

🤷‍♂️
