### ISSUE TITLE
Question: Is there a way to display environment variables with Caddy2 templates

### ISSUE THREAD

**Issue by patricksimonian** [caddyserver/caddy#3237]
There is no clear guide in the docs for printing environment variables in templates. 

In caddy v1 you could add
```
{{ Env.Foo }} 
```
and run that through the template directive. 

This appears to not be the case anymore. Has this functionality been replaced by using the lower  level Go api? `os.getEnv`?

**Comment by francislavoie** [comment]
It's now `{{ env.FOO }}` in v2, unless I'm mistaken.

**Comment by mholt** [comment]
I don't think it is, but it's super easy to add this.

**Comment by mholt** [comment]
There ya go. `{{env VAR_NAME}}` should do the trick.

**Comment by patricksimonian** [comment]
amazing you guys rock
