### ISSUE TITLE
Slow response using reverse proxy

### ISSUE THREAD

**Issue by thenewguy** [caddyserver/caddy#3238]
Reference: https://caddy.community/t/help-caddy-reverse-proxy-introduces-long-delay-in-response/7464/16

I have attached the profile requested

[profile (2).zip](https://github.com/caddyserver/caddy/files/4446893/profile.2.zip)

**Comment by mholt** [comment]
Hm, I think I'll close this since it's not really actionable as an issue right now, but was mostly created to post an attachment (which is fine, it will still be available). Discussion can continue on the forum I guess! Unless someone really wants to get serious about investigating this.
