### ISSUE TITLE
v2: request for nonexistent favicon.ico served via PHP reverse proxy: 'operation was cancelled'

### ISSUE THREAD

**Issue by DavidOliver** [caddyserver/caddy#3241]
Sometimes, when I load a PHP site which does not have a favicon.ico, Caddy 2 RC1 (and previous versions) logs the following:

`2020/04/08 16:09:37.341 ERROR   http.log.error  dialing backend: dial unix /run/php/php-fpm.sock: operation was canceled        {"request": {"method": "GET", "uri": "/favicon.ico", "proto": "HTTP/1.1", "remote_addr": "[::1]:52822", "host": "www.example.localhost", "headers": {"Accept-Encoding": ["gzip, deflate"], "Dnt": ["1"], "Connection": ["keep-alive"], "Cookie": [SNIPPED], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Accept": ["image/webp,*/*"], "Accept-Language": ["en-GB,en;q=0.5"]}}, "status": 502, "err_id": "na71xp4rv", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}`

I haven't yet managed to get this to happen when requesting `/favicon.ico` directly via the browser address bar; so far, when I do that, I get the PHP app's 404 page with no error logged by Caddy.

I don't know if this is unexpected or cause for concern, but thought I'd submit it here in case it is.

My Caddyfile:

```
http://www.example.localhost
root * /m/projects/example/project/web
try_files {path} /index.php?{query}&p={path}
php_fastcgi unix//run/php/php-fpm.sock
file_server
```

**Comment by francislavoie** [comment]
That is a bit strange. From what you're saying, sometimes it goes through fastcgi and sometimes it doesn't?

Basically `try_files` will check if `favicon.ico` exists on disk, if not, I think it rewrites to `/index.php?&p=/favicon.ico` which hits fastcgi.

Feels to me like it should always get routed to fastcgi. I'm not sure why there would be a dial error though. Do you have any error logs in `php-fpm` that might indicate some issue?

**Comment by DavidOliver** [comment]
It looks to me like requests for `/favicon.ico` (which doesn't exist) are always going to PHP - it's just that, rarely, they result in the dial error.

I'll look for PHP-FPM error logs.

**Comment by francislavoie** [comment]
Out of curiosity, maybe you could use a tool like `ab` and hammer `/favicon.ico`, see what kind of error rate you get? Maybe there's a pattern in the errors

**Comment by mholt** [comment]
I can confirm that the "operation was canceled" error does not originate from Caddy directly, but it does from the Go standard library when the dialing context is canceled: https://golang.org/src/net/net.go?h=operation+was+canceled#L409

**Comment by mholt** [comment]
Any more information available @DavidOliver ?

**Comment by DavidOliver** [comment]
I haven't managed to get PHP-FPM to show anything in its log.

It seems that it mostly only happens the first time I load the site after a boot. Even stopping and starting Caddy doesn't seem to result in the error being logged by Caddy again upon reloading the site.

I'm going to have another go Tuesday when I'm back in the office.

**Comment by mholt** [comment]
Sounds good, thanks! Will look forward to that.

**Comment by DavidOliver** [comment]
Sorry for the delay.

I've just tried Caddy RC3 and haven't yet seen the error. I'll try periodically over the next few days to see if it pops up again. (Feel free to close this in the meantime if you like?)

**Comment by mholt** [comment]
Thanks for the update! Sounds good, please let us know if you find out more.

**Comment by DavidOliver** [comment]
After having worked on the PHP site this afternoon, I noticed Caddy had logged some more 'dialing backend' errors, and this time not for requests to 'favicon.ico'.

```
2020/04/28 11:53:05.159 INFO    using provided configuration    {"config_file": "Caddyfile2", "config_adapter": "caddyfile"}
2020/04/28 11:53:05.160 INFO    admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2020/04/28 11:53:05.160 INFO    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv0", "http_port": 80}
2020/04/28 13:53:05 [INFO][cache:0xc000536690] Started certificate maintenance routine
2020/04/28 11:53:05.160 INFO    tls     cleaned up storage units
2020/04/28 11:53:05.161 INFO    autosaved config        {"file": "/home/david/.config/caddy/autosave.json"}
2020/04/28 11:53:05.161 INFO    serving initial configuration
2020/04/28 14:02:04.735 ERROR   http.log.error  dialing backend: dial unix /run/php/php7.3-fpm.sock: operation was canceled     {"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:39484", "host": "myhostname.localhost", "headers": {"Accept-Encoding": ["gzip, deflate"], "Referer": ["http://myhostname.localhost/blog"], "Dnt": ["1"], "Connection": ["keep-alive"], "Cookie": ["__distillery=158d266_b5bd0b29-e797-4bd9-8a23-187c9c6bd8db-78e5f2c68-d2e334f95fe4-d112; storageBannerDismissed=1"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Accept-Language": ["en-GB,en;q=0.5"], "Upgrade-Insecure-Requests": ["1"]}}, "status": 502, "err_id": "2h5caess9", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}
2020/04/28 14:03:53.500 ERROR   http.log.error  dialing backend: dial unix /run/php/php7.3-fpm.sock: operation was canceled     {"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:39688", "host": "myhostname.localhost", "headers": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Accept-Language": ["en-GB,en;q=0.5"], "Referer": ["http://myhostname.localhost/blog"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Accept-Encoding": ["gzip, deflate"], "Dnt": ["1"], "Connection": ["keep-alive"], "Cookie": ["__distillery=158d266_b5bd0b29-e797-4bd9-8a23-187c9c6bd8db-78e5f2c68-d2e334f95fe4-d112; storageBannerDismissed=1"]}}, "status": 502, "err_id": "hset7nunk", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}
2020/04/28 14:24:38.025 ERROR   http.log.error  dialing backend: dial unix /run/php/php7.3-fpm.sock: operation was canceled     {"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:40286", "host": "myhostname.localhost", "headers": {"Accept-Encoding": ["gzip, deflate"], "Connection": ["keep-alive"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Accept-Language": ["en-GB,en;q=0.5"], "Referer": ["http://myhostname.localhost/blog"], "Dnt": ["1"], "Cookie": ["__distillery=158d266_b5bd0b29-e797-4bd9-8a23-187c9c6bd8db-78e5f2c68-d2e334f95fe4-d112;
storageBannerDismissed=1"], "Upgrade-Insecure-Requests": ["1"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"]}}, "status": 502, "err_id": "jbk8bfnif", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}
2020/04/28 15:31:30.911 ERROR   http.log.error  dialing backend: dial unix /run/php/php7.3-fpm.sock: operation was canceled      {"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:42486", "host": "myhostname.localhost", "headers": {"Connection": ["keep-alive"], "Cookie": ["__distillery=158d266_b5bd0b29-e797-4bd9-8a23-187c9c6bd8db-78e5f2c68-d2e334f95fe4-d112; storageBannerDismissed=1; CRAFT_CSRF_TOKEN=8dfcda817c2c5b06abd0c4375ffc80311b9e6cf00469da209bb4e334641c2553a%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A40%3A%22DHX_FXQpKkUT7zpJRii7UiLJ5SrjSZuj0V8motsM%22%3B%7D"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Dnt": ["1"], "Accept-Language": ["en-GB,en;q=0.5"], "Accept-Encoding": ["gzip, deflate"], "Referer": ["http://myhostname.localhost/learn/course/basics/start-here"], "Upgrade-Insecure-Requests": ["1"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"]}}, "status": 502, "err_id": "asvhfdtiq", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}
^C2020/04/28 16:08:12.236       INFO    shutting down   {"signal": "SIGINT"}
2020/04/28 18:08:12 [INFO][cache:0xc000536690] Stopped certificate maintenance routine
2020/04/28 16:08:12.246 INFO    shutdown done   {"signal": "SIGINT"}
```

If it weren't for the error output at the terminal, I wouldn't have suspected anything had gone wrong as I didn't notice any failures to return pages in responses to my reloads while working on the site.

This is still with RC3.

**Comment by mholt** [comment]
@DavidOliver Interesting, thanks... 🤔 

So, as mentioned before, that appears to be the error returned by the std lib when the context is canceled: https://golang.org/src/net/net.go?h=return%20errCanceled#L421

The fastcgi code is a bit frankenstein-like, since I brought it over from v1 without many modifications. I don't suppose it has anything to do with https://github.com/caddyserver/caddy/blob/10db57027df6925c1afc82db1e7ddd0ff2cc53a2/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L101-L107 since I believe DialTimeout is zero? (In fact, there's a TODO to do timeouts differently, here: https://github.com/caddyserver/caddy/blob/10db57027df6925c1afc82db1e7ddd0ff2cc53a2/modules/caddyhttp/reverseproxy/fastcgi/client.go#L207)

One difference I see is that in v1, we just used context.Background() -- i.e. an empty/default context: https://github.com/caddyserver/caddy/blob/3b4f7a3c817d57e9faf3e4e70768c3c556ebd771/caddyhttp/fastcgi/fastcgi.go#L123

But in v2, we use the request's context (see first snippet).

Would you be able to tinker with that and see if the error can reproduce if, say, using a background context instead of the request's context? (I'm not really sure that's _correct_ but it'd be interesting to know if it still happens.)

One of the log lines:

```
2020/04/28 14:03:53.500 ERROR   http.log.error  dialing backend: dial unix /run/php/php7.3-fpm.sock: operation was canceled     {"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:39688", "host": "myhostname.localhost", "headers": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"], "Accept-Language": ["en-GB,en;q=0.5"], "Referer": ["http://myhostname.localhost/blog"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"], "Accept-Encoding": ["gzip, deflate"], "Dnt": ["1"], "Connection": ["keep-alive"], "Cookie": ["__distillery=158d266_b5bd0b29-e797-4bd9-8a23-187c9c6bd8db-78e5f2c68-d2e334f95fe4-d112; storageBannerDismissed=1"]}}, "status": 502, "err_id": "hset7nunk", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:362)"}
```

suggests that the user was at /blog and then went to / but then the request was canceled. I wonder if the client just canceled the request, i.e. closed their browser tab before the PHP connection was made?

Can you reproduce the error by closing the tab before the connection succeeds?

(As a side note, I'll see about adding latency to the error logs as well; right now only the access logs have that number.)
