### ISSUE TITLE
v2: on_demand tls for unknown domains

### ISSUE THREAD

**Issue by cisco87** [caddyserver/caddy#3247]
Hi guys, 
I was wondering if you could help me.  I am trying to set up caddy with on_demand tls certificates but I can't seem to understand what is wrong in this configuration

It only works when I add something like 
```         
"routes": [
            {
              "match": [
                {
                  "host": [
                    "DOMAIN"
                  ]
                }
              ],
``` 
 
Maybe I misunderstood what's on_demand is for, but I thought it would allow us to have TLS on unspecified domains at build time (we handle some customer custom domains on our SaaS, so this feature for us would be great.

Anyway the configuration I am using now:
```
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [{
            "handle": [{
              "handler": "reverse_proxy",
              "transport": {
                "protocol": "http"
              },
              "upstreams": [{
                "dial": "webapp.internal.com:80"
              }]
            }]
          }]
        }
      }
    },
    "tls": {
      "automation": {
              "on_demand": {
                  "ask": "https://some-domain/"
              }
      },
      "session_tickets": {},
      "certificates": {
         "automate": []
      }
    }
  }
}
```

Thank you for reading and for any help you could offer ^^

**Comment by cisco87** [comment]
Hi guys, again thank you, I've solved with my issue with this caddyfile

```
{
	admin off
	debug
	acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
	email MYMAIL

	on_demand_tls {
		ask https://www.google.com/
	}
}

:443 {
	log stdout

	reverse_proxy webapp.webinternal.com:80
        tls {
		on_demand
	}
}
```

**Comment by francislavoie** [comment]
Glad you figured out a solution!

For next time, I suggest you post on https://caddy.community for any usage questions, we prefer to leave github issues for feature requests and bugs.

**Comment by mholt** [comment]
And to clarify, your JSON was really close! All you had to do was create an automation policy that set `on_demand` to true: https://caddyserver.com/docs/json/apps/tls/automation/policies/

Your JSON config customized how on-demand works, but didn't enable it for any names.

**Comment by cisco87** [comment]
Hi @mholt thank you! and sorry @francislavoie will be more law abiding next time ^^
