### ISSUE TITLE
v2: Caddyfile errors directive

### ISSUE THREAD

**Issue by fmarcia** [caddyserver/caddy#3261]
I'm on my way to migrate from v1 to v2 with this (converted) Caddyfile:
```Caddyfile
0.0.0.0:80 {
	root * /srv/http/www
	header -server
	#errors
}

code.xxxxx.net {
	reverse_proxy /favicon.ico https://www.xxxxx.net
	reverse_proxy localhost:3000
	header -server
	tls franck@xxxxx.net
	#errors
}

auth.xxxxx.net {
	...
}

...
```

... but I could not find an equivalent to [v1 errors directive](https://caddyserver.com/v1/docs/errors) in [v2 documentation](https://caddyserver.com/docs/caddyfile/directives).

Is it a planned feature?

**Comment by mholt** [comment]
Yes, but for now there's the `handle_errors` directive. https://caddyserver.com/docs/caddyfile/directives/handle_errors

The inside of the handle_errors block looks just like the outside of it, except that the directives used within it are only applied if a server handler returns an error. So, there's a lot more flexibility in what you can do; there's just not a simple 1:1 mapping of error code to static file anymore (for now, anyways).

**Comment by fmarcia** [comment]
Thanks for the explanation

**Comment by francislavoie** [comment]
@mholt I'm not sure there's anything actionable here, what exactly is the feature request? We can serve an error file pretty easily with a CEL matcher:

```
handle_errors {
    @404 {
        expression {http.response.status_code} == 404
    }
    rewrite @404 /404.html
    file_server
}
```

And logging is completely redesigned in v2, so I'm not sure there's much to do in terms of that aspect of the v1 `errors` directive either.

**Comment by fmarcia** [comment]
@francislavoie My request was **not** about serving specific file for http errors, it was about  logging errors to stdin/sdterr, caught by systemd, just like v1 errors directive allows to.

If I understood the doc correctly, it looks like something like:
```
log {
    level warn
}
```
... would do the job.

If so, there is indeed no need for a new errors directive.

**Comment by mholt** [comment]
Oh. I didn't pick up that intention at all from the original post.

The log directive is only for access logs. Error logs are already printed to stderr by default.

**Comment by fmarcia** [comment]
I guess I can close this issue.
