### ISSUE TITLE
Wordpress + Caddy V2

### ISSUE THREAD

**Issue by harryy2510** [caddyserver/caddy#3277]
I can't find a perfect example of Caddy v2 + wordpress.

**Comment by francislavoie** [comment]
Please ask for help in the [Caddy forums](https://caddy.community)! This is the bug and feature requests board.

**Comment by mholt** [comment]
To add to what @francislavoie said, when you do get the perfect WordPress config, would you mind posting it to our [wiki category](https://caddy.community/c/wiki/13) on the forums, @harryy2510 ? I'm sure that would help a lot of people!
