### ISSUE TITLE
placeholder outside http.proxy

### ISSUE THREAD

**Issue by BioEvo** [caddyserver/caddy#3279]
Hi,  i got a internal dns server to resolve hostname and use caddy as an api gateway, is it possible to implement something like below?

```
https://*.example.com {
    gzip {
        ext    *
        level  4
    }

    log /var/log/caddy/{hostonly}

    tls admin@example.com

    proxy / http://{remote} {
    #proxy / https://{remote} {
        #insecure_skip_verify
        transparent
        websocket
    }

}

```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests.

Also, I see you're using Caddy v1, I strongly recommend you give Caddy v2 a try! Caddy v1 is no longer being actively developed.
