### ISSUE TITLE
broken two links in the README.md

### ISSUE THREAD

**Issue by kanagawa41** [caddyserver/caddy#3282]
There are broken links in the `README.md`.

* `https://caddyserver.com/api`
  * Maybe this one -> `https://caddyserver.com/docs/api`
* `https://github.com/caddyserver/caddy/blob/master/caddyserver/caddy/issues`
  * This is 404 page.(but I don't know right page.)

PS: Thank you so much for your work!

**Comment by mholt** [comment]
Thanks for the report!
