### ISSUE TITLE
Should path matcher exclude the matched portion of URI when passing to handler?

### ISSUE THREAD

**Issue by lexpierce** [caddyserver/caddy#3304]
Here is an example. I didn't want to use a rewrite, so I had a file in a folder, and tried to match the path for the request 1 level down from the hostname in the URI, and set the root for the file_server handler to the folder containing the file:

```
{
                      "handle": [
                        {
                          "handler": "headers",
                          "response": {
                            "set": {
                              "Strict-Transport-Security": [
                                "max-age=63072000; includeSubDomains; preload"
                              ]
                            }
                          }
                        },
                        {
                          "encodings": {
                            "gzip": {},
                            "zstd": {}
                          },
                          "handler": "encode"
                        },
                        {
                          "handler": "file_server",
                          "root": "/var/www/mta-sts"
                        }
                      ],
                      "match": [
                        {
                          "path": [
                            "/.well-known/*"
                          ]
                        }
                      ]
                    }
```

I was expecting it to be able to server the file directly from the root of the file_server, but it still required the .well-known/ path element.  Do path matchers not affect the handler? Would this need a rewrite? I mean, the easy solution is to put it in a .well-known directory, but that makes file management on the server harder.

**Comment by francislavoie** [comment]
As mentioned here on the forum thread, matchers don't modify anything about requests, they're just filters (just clarifying in case someone spots this thread at some point in the future)

https://caddy.community/t/using-caddy-to-serve-mta-sts-files/7668

**Comment by mholt** [comment]
Yeah, matchers don't modify requests. You can modify them using the `rewrite` or `uri` directives, though, like: `uri strip_prefix /.well-known`.
