### ISSUE TITLE
Missing pieces from previous version

### ISSUE THREAD

**Issue by rainerborene** [caddyserver/caddy#3306]
After reading the documentation I couldn't figure out how to translate the following `Caddyfile` to the latest version, things like `{request_id}`, `{when_unix_ms}` and `internal` are some examples. How would you translate these to the new directives? 

```
:80 {
  log / stdout "[{when_iso}] [{request_id}] ip={remote} method={method} host={host} path={uri} status={status} size={size} latency={latency} duration={<X-Runtime}"
  root ./public
  internal /cache
  header / -Server
  request_id

  proxy / web:3000 {
    transparent
    header_upstream X-Request-Id "{request_id}"
    header_upstream X-Request-Start "{when_unix_ms}"
  }

  errors {
    400 404.html
    422 422.html
    503 maintenance.html
    * 500.html
  }

  limits 20mb
  gzip
  pprof
}
```

**Comment by francislavoie** [comment]
You can set `time_format` on the logger, the possible values are: `unix_seconds_float`, `unix_milli_float`, `unix_nano`, `iso8601`, `rfc3339`, `rfc3339_nano`, `wall`, `wall_milli`. Unfortunately those aren't documented yet, but they're implemented. You can see these here: https://github.com/caddyserver/caddy/blob/master/modules/logging/encoders.go#L327-L356

You're right that `request_id` isn't implemented yet.

`internal` is easily replaced by a matcher and the [`respond` directive](https://caddyserver.com/docs/caddyfile/directives/respond), which lets you return an arbitrary status code and response body.

**Comment by francislavoie** [comment]
Please ask usage questions on the forums! https://caddy.community

We prefer to leave the GitHub issues board for bugs and feature requests.

**Comment by mholt** [comment]
For what it's worth, request IDs is something we'll tackle later in combination with tracing.

If you have a specific feature request that's not already discussed in an issue, feel free to open a new issue to propose the feature!
