### ISSUE TITLE
No certificate available

### ISSUE THREAD

**Issue by klaasgeldof** [caddyserver/caddy#3311]
I'm trying to use a specific wildcard certificate for one domain + all its subdomains, and automatic https for all other domains connecting to the server.

This is my Caddyfile (the real domain is replaced by 'mydomain.com'):

```
{
        debug
        email info@blacklion.be
}

mydomain.com, *.mydomain.com {
        file_server
        encode gzip
        root * /var/www/html
        php_fastcgi * unix//run/php/php7.4-fpm.sock

        tls /etc/ssl/mydomain/mydomain.crt /etc/ssl/mydomain/server.key {
                ca_root /etc/ssl/mydomain/ca_root.crt
        }
}

:443 {
        tls info@blacklion.be
        respond "Test"
}
```

Everything with mydomain.com (and subdomains of mydomain.com) works perfectly. But when I point another domain to the server, say otherdomain.com, I get this error in Chrome:

```
This site can’t provide a secure connection
```

And this in the Caddy log:

```
Apr 26 12:23:16 ip-172-30-1-134 caddy[21953]: 2020/04/26 12:23:16 http: TLS handshake error from 91.181.56.11:54951: no certificate available for 'otherdomain.com'
```

When I replace `:443` in my Caddyfile by `otherdomain.com` it works...

Thanks in advance for any help!

**Caddy version:** v2.0.0-rc.3

**Comment by mholt** [comment]
You need to enable [on-demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls) if the hostnames are not present in the config.

**Comment by klaasgeldof** [comment]
Thank you!
