### ISSUE TITLE
Add a handler to allow modifying the HTTP status code of a response

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#3312]
Currently, we have a `respond` (or `static_response` in JSON) handler which can serve an arbitrary request body with an arbitrary status code, and we have a `file_server` handler which can serve arbitrary files from disk, but no way to serve a file with an arbitrary status code.

This would be particularly useful in situations where users want to serve specific files on error or as a fallback, for example a `/404.html` file should be combined with status code 404.

I propose we add a `status_code` handler which would simply set the status code of the response as a request middleware.

For example, in JSON it might look like this:
```
{
    "handler": "status_code",
    "status_code": 404
}
```

In Caddyfile:
```
status_code [<matcher>] 404
```

In the Caddyfile directive ordering, I suggest adding it under `encode` and before `templates`.

Example usage:
```
# Try to serve the requested file at {path}, fallback to 404.html otherwise
try_files {path}.php {path} 404.html

# Change the status code to 404 if the file being served is 404.html
status_code /404.html 404

file_server
```

**Comment by francislavoie** [comment]
This isn't really the right approach for this. We're working on something better.

**Comment by dbohdan** [comment]
@francislavoie 

>We're working on something better.

Is there an issue where I can track the progress on this?

My [project](https://github.com/dbohdan/caddy-markdown-site) would benefit from the ability to override the status code when there is a 404 error and `handle_errors` finds a fallback file.  I will probably implement a different solution, but the following seems the most natural.

```caddyfile
handle_errors {
	file_server
	templates

	@markdown_index_exists_404 {
		file {path}/index.md
		expression `{http.error.status_code} == 404`
	}

	handle @markdown_index_exists_404 {
		map {path} {caddy_markdown_site.append_to_path} {
			default index
		}
		# It would be nice to able to say
		# status_code 200
		# here.
		rewrite * /templates/index.html
	}
	handle {
		rewrite * /templates/error.html
	}
}
```

**Comment by francislavoie** [comment]
This is done, `file_server` has a status code override option now. Add a `file_server` to your `handle` to explicitly change the status code.

**Comment by dbohdan** [comment]
Thanks a lot!  (And I've registered on the forum.)
