### ISSUE TITLE
 hello.SupportsCertificate undefined

### ISSUE THREAD

**Issue by jiangkang** [caddyserver/caddy#3326]
when I am building by `go build`:

error occurs:

```
.../go/pkg/mod/github.com/caddyserver/certmagic@v0.10.12/handshake.go:201:18: hello.SupportsCertificate undefined (type *tls.ClientHelloInfo has no field or method SupportsCertificate)

```

**Comment by francislavoie** [comment]
Is that from a fresh clone of the repo? What platform/OS are you running it on? What directory did you run `go build` from?

**Comment by jiangkang** [comment]
I have found the result : the project needs Go 1.14 ,but I used Go 1.13
