### ISSUE TITLE
gzip encoding doesn't seem to work

### ISSUE THREAD

**Issue by yann-soubeyrand** [caddyserver/caddy#3333]
Hi,

Running Caddy container with this Caddyfile

```
localhost:80 {
	root * /usr/share/caddy
	encode gzip zstd
	file_server
}
```

and running `curl -I -H 'Accept-Encoding: gzip' localhost` returns

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 12256
Content-Type: text/html; charset=utf-8
Etag: "q9aol59gg"
Last-Modified: Fri, 24 Apr 2020 13:39:05 GMT
Server: Caddy
Date: Sat, 02 May 2020 11:03:44 GMT
```

Shouldn't we see `Content-Encoding: gzip` here? Also, `Content-Length` is the same as when not requesting compression.

**Comment by mholt** [comment]
Caddy does not compress HEAD responses because there is no response body.

**Comment by yann-soubeyrand** [comment]
Yes, stupid me… Sorry for the inconvenience ;-)
