### ISSUE TITLE
How to disable automatic https in Caddyfile?

### ISSUE THREAD

**Issue by a1029563229** [caddyserver/caddy#3337]
I want to config custom reverse_proxy by caddy, to help me development.
But I can't use caddy to config a custom hostname, it cause an error `no certificate available for [custom hostname]`.

So, can I disable automatic_https in Caddyfile not use `json` config？
I think  the Caddyfile is easy to config for me, `json` file is too complex for me.
thanks!

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

This sounds like a bit of an [XY problem](https://en.wikipedia.org/wiki/XY_problem). Why do you need to disable it? There's probably a better solution than disabling it.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community) and don't forget to fill out the thread template! We prefer to keep the GitHub issue board for bugs and feature requests.

**Comment by mholt** [comment]
Our docs do explain how to disable it very easily: https://caddyserver.com/docs/automatic-https#activation

**Comment by a1029563229** [comment]
@francislavoie @mholt Thanks!!
