### ISSUE TITLE
Caddyfile: The default `host` attribute causes the server's caddy to be unrecognized the request correctly.

### ISSUE THREAD

**Issue by a1029563229** [caddyserver/caddy#3338]
I have a problem that was solved with the help of the official team, thank you very much.

I have a FR.

I use `Caddyfile` to configure my caddy, as shown below.

![caddy](http://shadows-mall.oss-cn-shenzhen.aliyuncs.com/images/blogs/caddy/5.png)

Then, I request the `http://proxy.dev-api-mall.jt-gmall.com`, as shown below.

![caddy](http://shadows-mall.oss-cn-shenzhen.aliyuncs.com/images/blogs/caddy/6.png)

Finally, I caught the request body, as shown below.

![caddy](http://shadows-mall.oss-cn-shenzhen.aliyuncs.com/images/blogs/caddy/4.png)

The default `host` attribute causes the server's caddy to be unrecognized the request correctly.

Why the default `host` not upstream?

**Comment by francislavoie** [comment]
Your link and images are broken, we can't help you unfortunately.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests.

**Comment by mholt** [comment]
@francislavoie They load for me...

**Comment by mholt** [comment]
@a1029563229 Try losing the `{ }` around your hostname.

Please see the documentation for reverse proxy: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

> By default, Caddy passes thru incoming headers to the backend—including the Host header—without modifications

That should answer your question :)

**Comment by francislavoie** [comment]
I just see images with like 10 pixel rows visible at the top and blank for the rest (no useful information). 🤷‍♂️

**Comment by mholt** [comment]
Weird!

@a1029563229 Would you be so kind as to post your question using only text please?
