### ISSUE TITLE
Replacement for the 'import' directive

### ISSUE THREAD

**Issue by kayg04** [caddyserver/caddy#3339]
Hello! I'm used to having reusable snippets at the top of the block and importing them wherever required as you can see in my Caddyfile: https://git.kayg.org/infra/caddy/src/branch/master/Caddyfile#L88

I tried looking in the documentation but I couldn't find an import directive in Caddy v2. Are there plans to implement this or is there a replacement functionality for this?

**Comment by francislavoie** [comment]
Imports are supported! They're just not technically a directive because they don't operate on the final config, it's just a helper to help with code reuse.

https://caddyserver.com/docs/caddyfile/concepts#snippets

**Comment by mholt** [comment]
Our docs could probably also give an example for using import with files.

**Comment by kayg04** [comment]
Thank you. I somehow missed the snippet section.

May 4, 2020 19:50:21 Matt Holt <notifications@github.com>:
