### ISSUE TITLE
Caddy added to https://webinstall.dev

### ISSUE THREAD

**Issue by solderjs** [caddyserver/caddy#3342]
Just wanted to let you know that we've added caddy to https://webinstall.dev/caddy, and we now depend on your "release API", as it were.

- Github Releases: https://github.com/caddyserver/caddy/releases
- API Transform: https://github.com/webinstall/packages/blob/master/caddy/releases.js
- webinstall.dev: https://webinstall.dev/api/releases/caddy@stable.tab?limit=25&pretty=true

Do you think that that will be "stable"? Anything to be aware of in the near future that might break things? (i.e. naming conventions, tar.gz unarchives without a prefix)

Also, would love feedback on the installation. I'm thinking to make `setcap` a default action on Linux.

Install script:
- Bare: https://github.com/webinstall/packages/blob/master/caddy/caddy.bash
- Templated: https://webinstall.dev/api/installers/caddy.bash?os=linux&arch=amd64

**Comment by francislavoie** [comment]
Cool!

You can take a look at the existing installation methods for comparison if you like: https://caddyserver.com/docs/install

We have https://github.com/caddyserver/dist which has all the default service files, default config, etc.

**Comment by mholt** [comment]
Hi AJ! Very cool.

Uhhh I dunno how stable those "APIs" are going to be, but the GitHub releases should be fairly stable since we use goreleaser to automate those. The rest I can't really speak for. I would just keep an eye on your error logs for a while. 😅
