### ISSUE TITLE
Gate access to static files via backend

### ISSUE THREAD

**Issue by toraora** [caddyserver/caddy#3347]
This is basically `X-Accel-Redirect` in Nginx, and it used to exist as `http.internal` in Caddy 1, but I don't seem to be able to find a way to implement this behavior in Caddy 2

**Comment by toraora** [comment]
I've written a plugin that I'm using for a toy site, but don't know enough about Caddy or its design principles to feel comfortable putting it up as a PR yet. If you can provide some feedback or guidance, I'd be happy to submit it, but for now I'll just put it here for other people to use:

https://gist.github.com/toraora/76016ef1fed9b551121ce41672c001bd

**Comment by francislavoie** [comment]
Neat! You could take a look at some of the other Caddy v2 modules in this list to see how the organize their github repos as plugins: https://caddy.community/t/list-of-caddy-2-modules/7839

The one thing that I think is glaringly missing is Caddyfile support, which is pretty easy to implement. There's a doc here that explains the process: https://caddyserver.com/docs/extending-caddy/caddyfile

**Comment by mholt** [comment]
Nice work @toraora ! But, this can be done using Caddy's built-in reverse proxy: https://github.com/caddyserver/caddy/commit/538ddb85876001976fa0c76f10b912c0870fe6d7#diff-3820b4f14e2fee163a1894dbf2560bd9R109

It'll go out with 2.1 so it'll be documented on the website around that time.

Still needs Caddyfile support. But it should do the trick! And is way more flexible than working only with X-Accel-Redirect.

**Comment by maxatome** [comment]
Hi @mholt, do you have an ETA for the Caddyfile support? at least an issue we can follow?
Thanks!

**Comment by mholt** [comment]
I don't yet; feel free to submit a PR to expedite the change!

**Comment by maxatome** [comment]
Do you have a spec of what you want to expose and how in Caddyfile? An example of final Caddyfile and what it should produce would be very appreciated before implementing anything \:)

**Comment by mholt** [comment]
Sure, I can come up with something -- can you open a new issue to request that feature?

**Comment by mholt** [comment]
Maybe something like this:

```
reverse_proxy ... {
	...
	handle_response header X-Accel-Redirect {
		... 
	}
	handle_response status 4xx {
		...
	}
	handle_response {
		...
	}
}
```

(Responses can be matched by headers or status code. Just showing a few examples here.)
