### ISSUE TITLE
Caddy 2 Configuration for WordPress

### ISSUE THREAD

**Issue by bestpaydeals** [caddyserver/caddy#3353]
Can I get Caddy 2 Caddyfile sample configuration for WordPress? The old one didn't work! Actually, I was working to make it work for 2 websites on different folders.

**Comment by mholt** [comment]
There is a discussion on the forum about this: https://caddy.community/t/caddy-2-wordpress-config/7487/16?u=matt

We try to keep the issue tracker focused on bug reports and feature requests please :) Thanks!
