### ISSUE TITLE
Recommended method for blocking hosts?

### ISSUE THREAD

**Issue by Immortalin** [caddyserver/caddy#3354]
https://medium.com/@alex_kuznetsov/how-to-fix-django-error-invalid-http-host-with-nginx-d0183a1ca753

^what is the suggested way for whitelisting host domains in Caddy 2? I don't think ipfilter supports hosts

**Comment by francislavoie** [comment]
We're going to need more information to answer your question. It's unclear exactly what you're asking.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests.
