### ISSUE TITLE
Logging not working in Caddy 2.0.0

### ISSUE THREAD

**Issue by jimsalterjrs** [caddyserver/caddy#3358]
Caddyfile:

```
sitename.com
root * /var/www/html
log /var/log/caddy/caddy.log
try_files {path} /index.php?{query}&p={path}
php_fastcgi unix//run/php/php7.4-fpm.sock
file_server

```

No logfile is produced at /var/log/caddy/caddy.log. Did `chown -R caddy /var/log/caddy` and `systemctl restart caddy`, still no log.

There also does not appear to be an error logging directive anymore; IDK if errors are supposed to show up in the normal caddy log now, but I'm not getting any logging, period...?

Caddy was installed from the github releases page, and is otherwise operating normally.

**Comment by francislavoie** [comment]
Please review the [`log` directive](https://caddyserver.com/docs/caddyfile/directives/log) documentation, the syntax you used it not currently supported.

**Comment by mholt** [comment]
We probably could throw a parse error there.
