### ISSUE TITLE
[Feature Request] File Metadata

### ISSUE THREAD

**Issue by CraigI** [caddyserver/caddy#3362]
Looking to see if file version info could be placed into the caddy executable. I'm would like to build a process that allows me to do limited testing with the latest version of Caddy and have it version protected so that our deployment scripts wont overwrite a higher version. I use Windows Server for the OS.

https://caddy.community/t/caddy-file-metadata/7948

Thank you!

**Comment by francislavoie** [comment]
Resolved by using the `caddy version` command instead.

See https://caddy.community/t/caddy-file-metadata/7948/5
