### ISSUE TITLE
Add support in hash-password for reading from terminals/stdin

### ISSUE THREAD

**Issue by 0az** [caddyserver/caddy#3365]
I have an initial implementation in my fork, in the improve-hash-password branch.

We only read from stdin if plaintext is not specified via argument. If stdin doesn't belong to a controlling terminal, we just hash everything up to the first newline. Otherwise, we ask the user to confirm the entered plaintext. This matches htpasswd's behavior, or at least the version I have access to.

**Comment by 0az** [comment]
The implementing commit: https://github.com/0az/caddy/commit/c5bafbb75c092f7c368d3323d44886ae18038e95.

**Comment by francislavoie** [comment]
Thanks, that's interesting!

Could you make a pull request with that change?
