### ISSUE TITLE
/etc/caddy/Caddyfile:2: unrecognized directive: - Syntax error help

### ISSUE THREAD

**Issue by dbrennand** [caddyserver/caddy#3370]
Hi everyone 😄 
I cannot work out for the life of me where the syntax error/mistake is in my caddyfile. Can anyone see it? Thanks everyone.

```caddyfile
{
    email example@example.com
    ca https://acme-staging-v02.api.letsencrypt.org/directory
    admin off
}

example.com {
    header {
        X-Content-Type-Options nosniff

        X-Frame-Options DENY

        Referrer-Policy no-referrer-when-downgrade
    }
    reverse_proxy example:10000
}
example.com {
    redir https://example.com
}
```

**Comment by Mohammed90** [comment]
Thanks for your question, and we're thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by dbrennand** [comment]
Why doesn't Caddy show which directive isn't recognised?

**Comment by francislavoie** [comment]
You redacted parts of your Caddyfile so we can't properly replicate your issue. Please ask on the forums and fill out the thread template so we can fully understand what's going on.

**Comment by dbrennand** [comment]
Ok thanks @francislavoie 
I was going off of what I found here: https://caddyserver.com/docs/caddyfile/options

**Comment by Mohammed90** [comment]
@dbrennand , I just used your Caddyfile locally to test (with modification, i.e. remove duplicate hostname and change domain to localhost). Caddy says exactly which directive is unrecognized:

`run: adapting config using caddyfile: unrecognized parameter name: ca`

The directive you're looking for is `acme_ca`. It's listed in the [`Global options`](https://caddyserver.com/docs/caddyfile/options) section.

**Comment by dbrennand** [comment]
I have the following config now. Still experiencing the same error:
I am using container image: `caddy:2.0.0-alpine`
`run: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized directive:`
```caddyfile
{
    acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    admin   off
    email   example@example.com
}
example.com {
    header {
        X-Content-Type-Options nosniff

        X-Frame-Options DENY

        Referrer-Policy no-referrer-when-downgrade
    }
    reverse_proxy exampleservicename:10000
}
example.com {
    redir https://example.com
}
```

**Comment by francislavoie** [comment]
That config as given adapts and validates correctly. You must not have your docker volume set up correctly.

**Comment by dbrennand** [comment]
I am using a bind mount to mount the Caddyfile to the container.
From `docker-compose.yml`
```docker-compose
  ...
  caddy:
    image: "caddy:2.0.0-alpine"
    container_name: "caddy"
    ports: 
      - "80:80"
      - "443:443"
    networks: 
      - "frontend"
      - "backend"
    volumes:
      # Persistent data in the caddydata directory
      - "./caddydata:/data"
      # Mount Caddyfile
      - "./Caddyfile:/etc/caddy/Caddyfile"
```

**Comment by francislavoie** [comment]
Do `docker-compose exec caddy /bin/sh -c 'cat /etc/caddy/Caddyfile'`, does it look right?

**Comment by dbrennand** [comment]
The container exists immediately so I cannot run the command in time😞

**Comment by Mohammed90** [comment]
Run:

`docker-compose run caddy /bin/sh -c 'cat /etc/caddy/Caddyfile'`

**Comment by dbrennand** [comment]
Hey guys,
Really appreciate all the help you have provided 👍 . I was using git bash to create an SSH session to the host I was using. Not really sure what caused the issue but when switching to another terminal and running `cat` on the file I could see the output was completely messed up 😖 
![image](https://user-images.githubusercontent.com/52419383/81319118-19705b80-9087-11ea-8f4f-6c5f781fe6b2.png)

**Comment by Mohammed90** [comment]
@francislavoie whitespace!! 😄
