### ISSUE TITLE
how to replace insecure_skip_verify in caddyfile v1 to v2 ?

### ISSUE THREAD

**Issue by changchichung** [caddyserver/caddy#3374]
v1 caddy file
```
vpn.abc.com {
    proxy / 192.168.11.4:44301 {
    transparent
    }
}

mail.abc.com {
     proxy   /   https://192.168.11.173 {
     transparent
     insecure_skip_verify
     }
 }

gitea.abc.com {
    proxy   /   192.168.11.201:3000 {
    transparent
    }
    #tls self_signed
}

```

I create another instance and install caddy v2 then create caddy file like
```
gitea.abc.com {
        reverse_proxy 192.168.11.201:3000
}
```
this one works , but this one does not work
mail.abc.com use a self-sign certification for nginx
```
mail.abc.com {
        reverse_proxy / {
                to 192.168.11.173:443
        #       transport http {
        #               tls
        #               tls_insecure_skip_verify
        #               }
                }

        #transparent
        #insecure_skip_verify
        }
```

the error message
```
"msg":"x509: cannot validate certificate for 192.168.11.173 because it doesn't contain any IP SANs"
```
I can not find documents about how to upgrade insecure_skip_verify to v2 .

any suggestions ?? thanks !

**Comment by francislavoie** [comment]
I'm confused, did you use that Caddyfile with the transport commented? That should be (mostly) correct. Note that in Caddy v2, path matchers are exact-match, meaning that `/` would only match requests to the root of your app. Instead, you should simply omit the `/` which instead is an implicit `*`, meaning matching all requests. You can also specify `https://` on your proxy address to avoid needing to specify `tls` in the transport.

```
mail.abc.com {
	reverse_proxy https://192.168.11.173 {
		transport http {
			tls_insecure_skip_verify
		}
	}
}
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
