### ISSUE TITLE
caddytest: dumps current server config only if config was loaded during the test

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#3383]
Hi @sarge , I have the following test:

```
func TestPlugin(t *testing.T) {
    tester := caddytest.NewTester(t)
    // Define URL
    baseURL := "https://127.0.0.1:3443"

    // Load configuration file
    configFile := "assets/conf/Caddyfile.json"
    configContent, err := ioutil.ReadFile(configFile)
    if err != nil {
        t.Fatalf("Failed to load configuration file %s: %s", configFile, err)
    }
    rawConfig := string(configContent)

    tester.InitServer(rawConfig, "json")
```

When running the test, it fails:

```
=== RUN   TestPlugin
2020/05/09 12:38:36 caddytest: config load time took 2.806408ms
    TestPlugin: caddytest.go:96: failed to load config: {"error":"loading config: loading new config: loading tls app module: provision tls: loading certificates: open /home/greenpau/dev/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0/caddytest/caddy.localhost.crt: permission denied"}
2020/05/09 12:38:36 caddytest: redirecting the dialer from 127.0.0.1:3443 to 127.0.0.1:3443
    TestPlugin: caddytest.go:397: failed to call server Get "https://127.0.0.1:3443/version": dial tcp 127.0.0.1:3443: connect: connection refused
    TestPlugin: caddytest.go:128: ----------- failed with config -----------
        {
          "apps": {
            "http": {
              "http_port": 8480,
              "https_port": 8443,
              "servers": {
```

The config referred in the test uses port 3443, but the "failed with config" is not the one referred in the test. The test fails with some other config. Looks like cached one.

**Comment by greenpau** [comment]
@sarge , perhaps, during the test it falls back to the latest working version of config. If that is so, then it makes sense to disable that in the `Tester`.

It looks like the real issue is that the test tries doing something with `/home/greenpau/dev/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0/caddytest/caddy.localhost.crt`.

**Comment by greenpau** [comment]
I opened a separate issue to track `permission denied` error: https://github.com/caddyserver/caddy/issues/3384

**Comment by sarge** [comment]
@greenpau Thanks for issue. The way that caddy loads new config is that if there is a problem loading the config it will then not apply the new config. It isn't a case of reverting, but a case of not applying.
This a nice property of caddy and it prevents you making a typo and taking down your server.

What the tests currently do is on error load the current config (which was the last good config), I think we could make that clearer by tracking if the config was loaded correctly. If it wasn't don't dump the current config as it isn't relevant. It has caught others out so I think it is worth fixing.

**Comment by greenpau** [comment]
> What the tests currently do is on error load the current config (which was the last good config), I think we could make that clearer by tracking if the config was loaded correctly

@sarge , makes sense! 👍
