### ISSUE TITLE
Caddy 2 empty body

### ISSUE THREAD

**Issue by yene** [caddyserver/caddy#3388]
I migrated from v1 to v2. Requests return 200, HTTPs works, but no content in the body.

```
macguide.org {
  root * /path/to/www
}
```

**Comment by francislavoie** [comment]
In Caddy v2, a file server is not enabled by default see the upgrade guide: https://caddyserver.com/docs/v2-upgrade

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
