### ISSUE TITLE
Can't get Snippets to Work

### ISSUE THREAD

**Issue by silverbp** [caddyserver/caddy#3392]
I must be losing my mind. I'm using caddy:2.0.0-alpine docker images and have the following caddy file.

```
http://localhost

root * /etc/caddy/root

# (testing_snippet) {
#     respond "hello"
# }

handle * {
    import testing_snippet_file
}
```

where inside the testing_snippet_file is:

```
respond "hello"
```

If I switch the import to the below and uncomment the snipped
```
import testing_snippet
```

I get import file can't be found. Actually, just uncommenting the snippet says, the directive can't be found. I feel like I'm missing some fundamental thing here.

**Comment by silverbp** [comment]
this always happens to me, I fight with something until I finally give in and post the question and then I figure it out..

I moved the snippet above the site and it worked. (above http://localhost)

**Comment by francislavoie** [comment]
For reference, that's explained in the docs here: https://caddyserver.com/docs/caddyfile/concepts#structure

Glad you figured it out!

**Comment by silverbp** [comment]
Thanks @francislavoie
