### ISSUE TITLE
API config traversal to overwrite array configuration fails

### ISSUE THREAD

**Issue by rosswilson** [caddyserver/caddy#3395]
Given a Caddy configuration of:

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "myhost.mydomain.com"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "load_balancing": {
                            "selection_policy": {
                                "policy": "round_robin"
                            }
                          },
                          "upstreams": [
                            {
                              "dial": "127.0.0.1:9010"
                            },
                            {
                              "dial": "127.0.0.1:9011"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "issuer": {
              "email": "myemail@mydomain.com",
              "module": "acme"
            }
          }
        ]
      }
    }
  }
}
```

A `GET` request to the API using config traversal returns the reverse proxy upstreams, as expected:

```bash
$ curl localhost:2019/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/0/upstreams

[{"dial":"127.0.0.1:9010"},{"dial":"127.0.0.1:9011"}]
```

However, I expected the below POST request to update the reverse proxy upstreams:

```bash
$ curl http://localhost:2019/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/0/upstreams -H "Content-Type: application/json" -d '[{"dial":"127.0.0.1:9010"}]'

{"error":"loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'reverse_proxy': decoding module config: http.handlers.reverse_proxy: json: cannot unmarshal array into Go struct field Handler.upstreams of type reverseproxy.Upstream"}
```

If there were zero upstreams configured then the above POST _does_ work.

Additionally, a DELETE to `http://localhost:2019/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/0/upstreams` removes all upstreams.

The documentation around config traversal isn't very comprehensive: https://caddyserver.com/docs/api-tutorial#config-traversal

I'm happy to work on a PR to extend the documentation if someone could help me understand the expected API behaviour. How can I programmatically update my upstreams (add, update, remove) individually, and in bulk (e.g. replace all upstreams with a new list of upstreams)?

**Comment by mholt** [comment]
@rosswilson It's neat to see people making use of the API! I don't think this is a bug.

> The documentation around config traversal isn't very comprehensive: https://caddyserver.com/docs/api-tutorial#config-traversal

I feel like the API is clearly documented on the [documentation page for the API](https://caddyserver.com/docs/api). Obviously a beginner tutorial won't go into detail about every aspect of it.

The doc says:

> Changes Caddy's configuration at the named path to the JSON body of the request. If the destination value is an array, POST appends; if an object, it creates or replaces.

Your request body:

> `-d '[{"dial":"127.0.0.1:9010"}]'`

is trying to POST (append) an array into an array. You probably want the body to be `{"dial":"127.0.0.1:9010"}`.

To replace, use PATCH:

> PATCH strictly replaces an existing value or array element.

> Additionally, a DELETE to http://localhost:2019/config/apps/http/servers/srv0/routes/0/handle/0/routes/0/handle/0/upstreams removes all upstreams.

Correct, because that refers to the array of upstreams. To delete just one of them, you need `/N` at the end of your path.

**Comment by rosswilson** [comment]
@mholt ahh, I hadn't spotted the detailed API documentation 🤦

Thank you for everything you're doing with Caddy!
