### ISSUE TITLE
Content does not changes immediately

### ISSUE THREAD

**Issue by zjgcjy** [caddyserver/caddy#3400]
I use docker for caddy with some simple configs, It runs well. However the web page doesn't change when I modify it. What's go wrong? I use the default file server.

I mean that isn't caddy a real time web server ? Or maybe I use static html which cause some no real time problem like cache ?

But even I do `rm -rf ./site` the default web site folder, the site is still alive...

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
