### ISSUE TITLE
TLS handshake error from <ipaddress>:<port>: EOF

### ISSUE THREAD

**Issue by escalate** [caddyserver/caddy#3412]
Hello

I am using Caddy v2.0.0.0 as a reverse proxy to extend various Prometheus exporters with Basic Auth, IP whitelist and SSL encryption.

I use the following Caddyfile for configuration.

```
{
  http_port 80
  https_port 7000
}

MYHOSTNAME:7000 {
  route /node_exporter/* {
    uri strip_prefix /node_exporter
    reverse_proxy 127.0.0.1:9100 {
      transport http {
      }
    }
  }
  route /blackbox_exporter/* {
    uri strip_prefix /blackbox_exporter
    reverse_proxy 127.0.0.1:9115 {
      transport http {
      }
    }
  }
  basicauth {
    USERNAME BASE64SECRET
  }
  log
}
```

I would like to check about 200 targets using the Blackbox Exporter.
With BasicAuth and Let's Encrypt SSL encryption a maximum of 30 targets can be checked via the Blackbox Exporter.
If the number of targets increases I get the following error in the caddy logfile:

`caddy[28139]: 2020/05/14 10:15:39 http: TLS handshake error from <ipaddress>:<port>: EOF`

And I get the following error message from Prometheus for all targets:

`Get "https://MYHOSTNAME:7000/blackbox_exporter/probe?xxx": context deadline exceeded`

If I deactivate Basic Auth all 200 targets can be checked by Prometheus without problems.

I would be happy if you could find the error.

Many greetings
Felix

**Comment by mholt** [comment]
This error:

> caddy[28139]: 2020/05/14 10:15:39 http: TLS handshake error from <ipaddress>:<port>: EOF

is actually an error on the client-side: they didn't send any bytes during the TLS handshake.

> Get "https://MYHOSTNAME:7000/blackbox_exporter/probe?xxx": context deadline exceeded

That seems like it timed out, so maybe something in the middle is stopping bytes from flowing.

> If I deactivate Basic Auth all 200 targets can be checked by Prometheus without problems.

So it sounds like the client isn't doing the basicauth properly.

I'll close this, but feel free to continue discussion if you can show that it's a Caddy bug.
