### ISSUE TITLE
Link broken on Website

### ISSUE THREAD

**Issue by sidharthramesh** [caddyserver/caddy#3415]
On the page https://caddyserver.com/docs/download, the command 
```
curl -OL "https://github.com/caddyserver/caddy/releases/latest/download/ASSET"

```
does not work because the link is broken

**Comment by francislavoie** [comment]
That isn't meant to work on its own. It's just a command stub for you to fill in with the exact release you need. Follow the link to the release page on GitHub and pick a file to download!

That could be clarified though @mholt

**Comment by sidharthramesh** [comment]
Yes. Mentioning the latest version in URL would be nice for a faster installation.

**Comment by francislavoie** [comment]
That's not really possible because the download is different for every platform/architecture combo. We would have to list out every single one, every time we make a release. Those docs pages are meant to be evergreen and not require changes on release.

**Comment by sidharthramesh** [comment]
Alright! Makes sense

**Comment by francislavoie** [comment]
Thanks for understanding!
