### ISSUE TITLE
Caddy2 "log /my/path { ... }" seems to log for any path, e.g. /hello, not just /my/path

### ISSUE THREAD

**Issue by Ahnfelt** [caddyserver/caddy#3418]

**Comment by francislavoie** [comment]
The log directive doesn't support matchers:

https://caddyserver.com/docs/caddyfile/directives/log

If a directive supports matchers, it'll mention it in its documentation with `[<matcher>]` in the syntax.

**Comment by Ahnfelt** [comment]
Ah - thank you. Hmm - maybe a bit implicit in the documentation.

Shouldn't it cause some kind of error from `caddy run` then?

**Comment by Ahnfelt** [comment]
Oh, great - thank you.
