### ISSUE TITLE
Zero-Length 200 TLS Responses [Reverse-Proxy]

### ISSUE THREAD

**Issue by LanceMcCarthy** [caddyserver/caddy#3420]
If you're running beta 10 or earlier, the Caddyfile with a reverse_proxy may start blocking js and json file after updating to Caddy  v2.0

The best way to explain this would be to share my broken config and what fixed it. In the end it's a simple change, but can be very difficult to discover.

## Problematic config

In beta-=10 and earlier, this Caddyfile works to setup a reverse_proxy to an internal IP address

```
my.domain.com {
	reverse_proxy / {
		to internal.my.domain:xxxx
		transport http {
			read_buffer 4096
			tls
		}
		header_up Host {http.request.host}
		header_up X-Real-IP {http.request.remote.host}
		header_up X-Forwarded-For {http.request.remote.host}
		header_up X-Forwarded-Port {http.request.port}
		header_up X-Forwarded-Proto {http.request.scheme}
		header_down Strict-Transport-Security "max-age=31536000;"
		header_down X-XSS-Protection "1; mode=block"
		header_down X-Content-Type-Options "SAMEORIGIN"
		header_down X-Frame-Options "sameorigin"
		header_down Referrer-Policy "strict-origin-when-cross-origin"
	}
}
```

After updating to 2.0 release, you will see that javascript and json source were returning 200 OK but have zero-length content.
![image](https://user-images.githubusercontent.com/3520532/82107487-1ebc4e80-96f6-11ea-8d9e-cd2ffa46a56c.png)

![image](https://user-images.githubusercontent.com/3520532/82107477-04827080-96f6-11ea-98e9-dc766928c12c.png)

## Solution

Remove the `/` after **reverse_proxy** and add the protocol to the `to`.

Here is the working version with the successful changes

```
my.domain.com {
    reverse_proxy {
        to https://internal.my.domain.com:xxxx
        transport http {
            read_buffer 4096
        }
        header_up Host {http.request.host}
        header_up X-Real-IP {http.request.remote.host}
        header_up X-Forwarded-For {http.request.remote.host}
        header_up X-Forwarded-Port {http.request.port}
        header_up X-Forwarded-Proto {http.request.scheme}
        header_down Strict-Transport-Security "max-age=31536000;"
        header_down X-XSS-Protection "1; mode=block"
        header_down X-Content-Type-Options "SAMEORIGIN"
        header_down X-Frame-Options "sameorigin"
        header_down Referrer-Policy "strict-origin-when-cross-origin"
    }
}
```

## Post-Mortem Takeaways

To the Caddy team, please consider updating the documentation with an example config version that we can always look to for guidance (especially after Caddy releases). https://caddyserver.com/docs/json/apps/tls/certificates/automate/

![image](https://user-images.githubusercontent.com/3520532/82107666-80c98380-96f7-11ea-9f87-b7a84ed70cb8.png)

**Comment by mholt** [comment]
Thanks for the info, it will probably help anyone else upgrading from such an old version with a similar question.

Your updated Caddyfile looks good. :+1:

Next time, please refer to our upgrade guide, it will help 🙂  https://caddyserver.com/docs/v2-upgrade

It explains that path matching is exact, not prefix.

> To the Caddy team, please consider updating the documentation with an example config version that we can always look to for guidance (especially after Caddy releases).

We... do... what do you still want? We've had 10 beta releases after beta 10, along with 3 release candidates, before the stable release: each one has release notes describing the changes. The screenshot you linked to doesn't have anything to do with the problem described. And it omits the documentation part, so it's not really a fair representation:

> a no-op certificate loader module that is treated as a special case: it uses this app's automation features to load certificates for the list of hostnames, rather than loading certificates manually.

Meaning, that list is a list of hostnames for which to automate certificates for.

We'll keep improving our docs, we only barely tagged v2. But we have good docs, we work very hard on them.
