### ISSUE TITLE
Clarify the use of placeholders in "HTTP routes"

### ISSUE THREAD

**Issue by rgl** [caddyserver/caddy#3425]
At https://caddyserver.com/docs/json/apps/http/#docs this is written:

> In HTTP routes, additional placeholders are available (replace any *):

Can you please clarify where exactly they can be used?

I think I've tried to use them inside the "HTTP routes" to have a reverse proxy from the public hosts `https://s1.example.com` and `https://s2.example.com` to the internal hosts `https://*.example.local`, but it doesn't seem to work, as the the upstream server is returning 502 (but works fine when I remove the placeholders and use hard-coded values).

Can you please clarify if the following configuration should have worked?

```json
{
  "apps": {
    "http": {
      "servers": {
        "public": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "s1.example.com",
                    "s2.example.com"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "transport": {
                    "protocol": "http",
                    "tls": {
                      "server_name": "{http.request.host.labels.2}.example.local",
                      "root_ca_pem_files": [
                        "/etc/caddy/example-ca.pem"
                      ]
                    }
                  },
                  "headers": {
                    "request": {
                      "set": {
                        "Host": [
                          "{http.request.host.labels.2}.example.local"
                        ]
                      }
                    }
                  },
                  "upstreams": [
                    {
                      "dial": "10.10.10.10:443"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}
```

**Comment by francislavoie** [comment]
I feel like what you're trying to do should work.

To help us debug, could you add this to your config:

```json
{
	"logging": {
		"logs": {
			"default": {
				"level": "DEBUG"
			}
		}
	}
}
```

This should force some extra logging to take place during the proxying, should show what Caddy is actually trying to do.

**Comment by mholt** [comment]
I don't believe I've implemented placeholder support on the ServerName field of the TLS config.

I don't think we can support them there, either, since TLS configs are provisioned once at config load and then reused for performance.

**Comment by rgl** [comment]
I understand that it might have performance implications, and I'm fine with it staying as is. But can we please have the documentation clarify where exactly we can(not) use placeholders? Maybe have some annotation that says whether a property supports placeholders or not.

Is the use-case that I'm trying (reverse proxy *.example.com to *.example.local) to archive reasonable? Does caddy provide other way (without creating multiple routes) of implementing it?

**Comment by rgl** [comment]
@francislavoie

> ```json
> {
> 	"logging": {
> 		"logs": {
> 			"default": {
> 				"level": "DEBUG"
> 			}
> 		}
> 	}
> }
> ```
> 
> This should force some extra logging to take place during the proxying, should show what Caddy is actually trying to do.

The logs are not useful in this case, as they only output the original request (they do not log the upstream request by default, but maybe there's a way of doing that?):

```json
{
    "level": "error",
    "ts": 1589800778.9948533,
    "logger": "http.log.error",
    "msg": "read tcp y.y.y.y1:38950->y.y.y.y2:443: read: connection reset by peer",
    "request": {
        "method": "GET",
        "uri": "/",
        "proto": "HTTP/1.1",
        "remote_addr": "x.x.x.x:35798",
        "host": "s1.example.com",
        "headers": {
            "User-Agent": [
                "Wget/1.19.4 (linux-gnu)"
            ],
            "Accept": [
                "*/*"
            ],
            "Accept-Encoding": [
                "identity"
            ],
            "Connection": [
                "Keep-Alive"
            ]
        }
    },
    "duration": 0.001058012,
    "status": 502,
    "err_id": "6j37qpee6",
    "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:380)"
}
```

**Comment by mholt** [comment]
Indeed, our debug log doesn't print if there's an error. Maybe we should move the debug log to before the error check.

**Comment by rgl** [comment]
@mholt can the `zap.Int("status", res.StatusCode)` crash with nil when there's an error?

https://github.com/caddyserver/caddy/commit/812278acd8a5c46b44fdf92ea5df4d6a51eff7be#diff-3820b4f14e2fee163a1894dbf2560bd9R473

**Comment by francislavoie** [comment]
Yeah, he made a commit immediately after to fix it https://github.com/caddyserver/caddy/commit/9ee01dceac0a3e9f71c3b37dfbe3ae04e2f54986

**Comment by mholt** [comment]
As a quick note, I think we might be able to allow placeholders in the `server_name` property if we `Clone()` the `tls.Config` value at each request. It's another allocation, but we might be able to optimize so it's only done if a placeholder is used there.

**Comment by francislavoie** [comment]
I don't think there's anything actionable here anymore, as a fix was merged in https://github.com/caddyserver/caddy/pull/4836 to make `tls_server_name` placeholders work! Thanks @kresike
