### ISSUE TITLE
Feature: define lifetime of local pki root and intermediate certificates

### ISSUE THREAD

**Issue by rvf148** [caddyserver/caddy#3427]
Add lifetime configuration properties for internal CA pki certificates

Currently [lifetime](https://caddyserver.com/docs/json/apps/tls/automation/policies/issuer/internal/lifetime/)  can only be configured for subject certificates, which can be longer then its CA chain certificates.
- root CA 5days
     - intermediate CA 5days
          - subject 30 days
If intermediate is trusted in stores on devices, it needs to be updated every 5 days.
Current workaround is to configure the root and intermidate certs yourself with a longer lifetime than 5 days.

**Comment by mholt** [comment]
What is your use case for such long-lived leaf certs?

**Comment by rvf148** [comment]
I want to use Caddy as local CA for my LAN reverse proxy, if the intermediate and root certificates change every 5 days, I need to update the trusted CA certificates on all my devices. While it is possible to supply your own, it would be nice if Caddy allowed this parameters. It is not so much the 'subject' certificates lifetime, they can be very short indeed. It is the CA root and intermediate that are important to configure.

**Comment by mholt** [comment]
>  if the intermediate and root certificates change every 5 days, I need to update the trusted CA certificates on all my devices.

The root doesn't change, it is currently good for 10 years. The root is what you install into trust stores, not the intermediate. So you shouldn't need to worry about the lifetimes of the signing certs.

**Comment by rvf148** [comment]
Ok, thank for clearing this out. Somehow I set the lifetime for the leaf certificate and the intermediate didn't seem to have a parent root CA cert. I have cleared the lifetime setting, installed the root ca cert into my trusted store, and removed the leaf certificates. After restart the leaf had a correct chain with a 10 year root CA. Thanks.
