### ISSUE TITLE
how to get websocket  data size on caddy v2

### ISSUE THREAD

**Issue by sy2un** [caddyserver/caddy#3432]
I'm developing a cdn service based on caddy2, and proxy websocket request,  i want to count websocket data size, but i don't know how to get websocket data, Has anyone ever done this before? i need  some suggestion, thank you

caddy version:v2

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

I don't think this is currently possible, but it should be soon with the TCP transport plugin!

https://twitter.com/mholt6/status/1261007112647270401?s=19

**Comment by mholt** [comment]
If you want to count the number of bytes transmitted, you need to get beneath the HTTP layer. As Francis suggested, this Caddy app should do the trick: https://github.com/mholt/conncept
