### ISSUE TITLE
How do I use reverse_proxy with except

### ISSUE THREAD

**Issue by amir20** [caddyserver/caddy#3435]
I want to proxy everything except `robots.txt` and `/static`.

In v1, I currently have:

```
proxy / unix:/tmp/gunicorn.sock {
      transparent
      except /favicon.ico /robots.txt /static
}
```

I am not able to find any example on how to negate the `reverse_proxy`

I did

```
file_server /static/* 
file_server /robots.txt  
reverse_proxy /* unix//tmp/gunicorn.sock   
```

But that seems to still proxy everything. 

I think I need to [use](https://caddyserver.com/docs/caddyfile/matchers#not) `not()` but I am not sure and there no examples. 

Any help would be appreciated. 

Thanks!

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

You'll want to make a [named matcher](https://caddyserver.com/docs/caddyfile/matchers#named-matchers) that contains a `not` matcher chained with a `path` matcher.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by amir20** [comment]
Sounds good. I thought I had to use `path` but wasn't sure. I'll close this and move topic to forums if it doesn't work.
