### ISSUE TITLE
Caddy with LetsEncrypt on Kubernetes with Helm

### ISSUE THREAD

**Issue by stepin** [caddyserver/caddy#3441]
I'm tried to deploy Caddy on Kubernetes. As there is no helm chart in the default Helm repo, I'm created a new one using "helm new" command. It worked but https certificate creation failed with error:

`[ERROR] error: one or more domains had a problem:
[example.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://example.com/.well-known/acme-challenge/Dyk0YHknHimKq0l57HhI4DcVhqy3OxKS732yp73iZZo: Connection refused, url:
 (challenge=http-01 remaining=[tls-alpn-01])`

I spend significant amount of time investigating why it's not working. It turned out that K8s service uses a readiness check by default, and it's just not ready at that moment. So, adding of "publishNotReadyAddresses: true" to the K8s service fixes this problem.

So, maybe it will be useful for other people. Also, maybe it will be a good idea to document this somehow (and maybe add Helm chart to default repo).

**Comment by mholt** [comment]
Thanks for letting us know! Appreciate it.

/cc @caddyserver/kubernetes -- FYI, maybe?

**Comment by stepin** [comment]
Also, second similar issue: after few minutes pod is terminated by SIGTERM. It's liveness check. It tries to connect to http://ip/, and receives response 301. Follows it, and receives error (as there is no correct certificate for the internal IP address). From Caddy logs:

`http: TLS handshake error from 127.0.0.1:43170: EOF`

There is issue for this in K8s: https://github.com/kubernetes/kubernetes/issues/73172 They decided that it's expected behaviour. So, simple workaround is to check by tcp port:

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 120
          readinessProbe:
            tcpSocket:
              port: http

**Comment by hairyhenderson** [comment]
@stepin You may want to try using the `respond` directive to respond specifically to those checks:

(in a Caddyfile):
```
:80 {
  respond /live 200
  respond /ready 200
}
```

Or in JSON:

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [ ":80" ],
          "routes": [
            {
              "match": [ { "path": [ "/ready" ] } ],
              "handle": [ {
                  "handler": "static_response",
                  "status_code": 200
                } ]
            },
            {
              "match": [ { "path": [ "/live" ] } ],
              "handle": [ {
                  "handler": "static_response",
                  "status_code": 200
                } ]
            }
          ]
        }
      }
    }
  }
}
```
