### ISSUE TITLE
Flag to enable file-server access log

### ISSUE THREAD

**Issue by rgl** [caddyserver/caddy#3452]
The caddy file-server would be even more useful to me if it had a way to enable the access log.

Can this be added to caddy? e.g. with a `--log-access` flag?

I would gladly submit a PR if this is welcomed :-)

**Comment by mholt** [comment]
@rgl Sure, feel free to submit a PR. Preferably just the minimal config to enable the default access log -- don't want much code/complexity involved with customizing it.

**Comment by rgl** [comment]
Its at https://github.com/caddyserver/caddy/pull/3454. This was pretty straightforward to add :-)
