### ISSUE TITLE
Header directive doesn't remove headers originating from proxy backends

### ISSUE THREAD

**Issue by ztjuh** [caddyserver/caddy#3455]
I am running version 2.0.0 on Windows 10 and have `header -Server` on top. It still shows the Caddy header when I test it. I am using `redir` .

```
domain1.com, domain2.net, domain3.org {
  header -Server
  tls ema@il.address
  basicauth /foo/* {
    test p@s$w0rd
  }
  basicauth /bar/* {
    test p@s$w0rd
  }
  redir /foo /foo/ 308
  redir /bar /bar/ 308
  reverse_proxy /foo/* 127.0.0.1:1337
  reverse_proxy /bar/* 127.0.0.1:7331
  log stdout
}
```
https://caddy.community/t/header-server-ignored/8383
https://github.com/caddyserver/caddy/issues/3148

**Comment by mholt** [comment]
Thanks for the issue.

To summarize, we're not sure if this is a bug or if this is correct.

As it stands right now, the `header` directive reportedly does not remove response headers that originate from proxy backends. (I have not confirmed this myself, but OP has.) The `header_down` subdirective of the `reverse_proxy` directive does. This allows you to control which header origins you allow/keep.

The question is whether `header` should manipulate response headers that originate from the proxy backends or only from the local Caddy instance. If we change the behavior to act the way OP expects, then removing a header from the proxy will also remove the header from the local server, so it will be impossible to only remove headers originating from the local server while keeping any of the same name that come from the proxy backends.

I'm inclined to think the current behavior is the correct and most flexible behavior. Will think on it for a few days, and probably close it unless there's compelling reasons to the contrary.

**Comment by francislavoie** [comment]
I feel like if you wanted to not remove the header from the upstream you could just use a matcher on the header directive to exclude it from the same routes as the proxies. I think the default should work in the way most users would expect, I think the header directive should manipulate headers from any matched request and not only non-proxy requests.

That said, the amount of edgecases that exist around users wanting to remove the Server header (also needs to be removed within handle_errors for example) makes me think we should add a global option to turn off the header from being added entirely if users don't want it.

**Comment by mholt** [comment]
After thinking on this some more, I'm going to leave it as-is, I think the current behavior is correct / best for maximizing flexibility. As stated above, if we change it to what is requested, it becomes impossible to preserve a header from the backend but remove the same header that was set from the current machine. Also, as discussed, manipulating headers is much easier in Caddy than in other web servers, which often require extra modules (especially for the Server header!).
