### ISSUE TITLE
reverse_proxy upstream dial to a hostname, how to set resolver for the hostname?

### ISSUE THREAD

**Issue by sharego** [caddyserver/caddy#3459]
Is there a way to set a custom resolver for a server or reverse_proxy handler?

And DNS Resolver maybe not use the standard port like 53, or support DNS over HTTP?

**Comment by mholt** [comment]
[It's a TODO in the code.](https://github.com/caddyserver/caddy/blob/881b826fb59a25102fd14ae3b420639479f2d6bf/modules/caddyhttp/reverseproxy/httptransport.go#L149) Right now Caddy just uses the system resolver. 

Pull requests welcomed!

**Comment by sharego** [comment]
Ok, Thank you very much

**Comment by mholt** [comment]
@sharego Would you be willing to contribute a pull request with the enhancement?

**Comment by sharego** [comment]
Ok, Thanks. But i do not know details about this feature, Like nginx resolver is ok?

This is [nginx resolver directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver)
```
Syntax:  resolver address ... [valid=time] [ipv6=on\|off] [status_zone=zone];
Default: --
Context: http, server, location
```
