### ISSUE TITLE
How to implement QUIC protocol using caddy ?

### ISSUE THREAD

**Issue by vishnutm** [caddyserver/caddy#3461]
Hey guys, I am pretty new in the caddy, so I would like to implement QUIC protocol in my project. Do you guys have any good documentation to implement that? because I can not find it yet. kindly needed for your help.

**Comment by francislavoie** [comment]
You're looking for the `experimental_http3` global option. QUIC is now being standardized as HTTP3.

https://caddyserver.com/docs/caddyfile/options

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
