### ISSUE TITLE
ACME staging overrides custom ACME endpoints

### ISSUE THREAD

**Issue by p3lim** [caddyserver/caddy#3466]
I've set a custom ACME endpoint because I'm using internal domains, like so:
```
my.domain {
    tls {
        ca https://acme.domain/...
        ca_root /etc/pki/ca.crt
    }
    ...
}
```
If the renew fails (e.g. my custom ACME endpoint is down or fails), Caddy switches over to start using Let's Encrypt staging endpoints instead. Once it's done this switch, the LE staging endpoint is now the default for that domain, my custom ACME server is never queried again. I've verified this from the logs, and from looking at the traffic between the two hosts.

Logs from Caddy where the initial renewal to my internal ACME endpoint failed and Caddy switched to using LE staging:
```
2020/06/01 13:50:11 [ERROR] attempt 1: [my.domain] Renew: [my.domain] acme: error: 0 :: POST :: https://acme.domain/acme/acme/new-order :: urn:ietf:params:acme:error:serverInternal :: <some long error message>
2020/06/01 13:51:11 [INFO][my.domain] Renew: 7h58m55.746709066s remaining
2020/06/01 13:51:11 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 1/2)
2020/06/01 13:51:13 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 2/2)
2020/06/01 13:51:13 [ERROR] attempt 2: [my.domain] Renew: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority - retrying in 2m0s (1m6.846932063s/720h0m0s elapsed)...
2020/06/01 13:53:13 [INFO][my.domain] Renew: 7h56m53.034904112s remaining
2020/06/01 13:53:14 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 1/2)
2020/06/01 13:53:16 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 2/2)
2020/06/01 13:53:16 [ERROR] attempt 3: [my.domain] Renew: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority - retrying in 2m0s (3m9.470162215s/720h0m0s elapsed)...
2020/06/01 13:55:16 [INFO][my.domain] Renew: 7h54m50.408537844s remaining
2020/06/01 13:55:16 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 1/2)
2020/06/01 13:55:19 [ERROR] Making new ACME client: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority (attempt 2/2)
2020/06/01 13:55:19 [ERROR] attempt 4: [my.domain] Renew: get directory at 'https://acme-staging-v02.api.letsencrypt.org/directory': Get "https://acme-staging-v02.api.letsencrypt.org/directory": x509: certificate signed by unknown authority - retrying in 5m0s (5m12.157596263s/720h0m0s elapsed)...
```

This log goes on for another couple of hours, but the last time my custom ACME server saw any renewal requests for this domain, or from the Caddy at all, was at 13:50:09 (which corresponds with the first line from that log snippet). My certificates have now expired and I have to manually restart Caddy for it to retry renewal from my ACME server instead of LE staging.

Running Caddy 2.0.0 from @caddy/caddy copr repo on CentOS 8.1.1911.

**Comment by mholt** [comment]
> If the renew fails (e.g. my custom ACME endpoint is down or fails), Caddy switches over to start using Let's Encrypt staging endpoints instead. Once it's done this switch, the LE staging endpoint is now the default for that domain, my custom ACME server is never queried again. I've verified this from the logs, and from looking at the traffic between the two hosts.

This is actually a failsafe mechanism in CertMagic: it falls back to a test CA endpoint during exponential backoff + retry in order to avoid rate limits on production CA endpoints.

But, I don't think it should be activating in the case that the test CA is the same as the default test CA and the configured primary CA is different from the default primary CA.

Would you be willing to build Caddy with a custom version of CertMagic to test a fix?

**Comment by p3lim** [comment]
Sure, just let me know when you have it.

**Comment by mholt** [comment]
@p3lim Thanks! Can you please try building Caddy with this commit of CertMagic: https://github.com/caddyserver/certmagic/commit/5b5ac32a857d238654fd99be0fbc25d92c1a37e1 (A `go get` command for certmagic at that version should do the trick.)

It worked for me but since you have an actual set up I want to confirm with you too.

**Comment by p3lim** [comment]
Done, just for clarity's sake:
- installed go 1.14.4 & gcc
- `git clone https://github.com/caddyserver/caddy`
- `cd caddy`
- `go get github.com/caddyserver/certmagic@5b5ac32`
- `cd cmd/caddy`
- `go build`
- `cp caddy /usr/local/bin/`
- added systemd drop-in unit for caddy.service:
	```
	# /etc/systemd/system/caddy.service.d/override.conf
	[Service]
	ExecStart=
	ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile
	ExecReload=
	ExecReload=/usr/local/bin/caddy reload --config /etc/caddy/Caddyfile
	```
- `systemctl daemon-reload && systemctl restart caddy`

Also, in my opinion, this is a candidate for 2.0.1.

**Comment by mholt** [comment]
@p3lim Thanks! That's helpful. But, uh, does it work? 😅  Like, does it fix the problem?

> Also, in my opinion, this is a candidate for 2.0.1.

2.1 beta is rolling out soon enough :)

**Comment by p3lim** [comment]
> But, uh, does it work?

Will have to wait for my ACME endpoint to fail, which it will in under 24 hours (there's currently a bug with it storing registrations that led me to finding this issue with Caddy).

> 2.1 beta is rolling out soon enough

👍

**Comment by mholt** [comment]
@p3lim Any chance you could accelerate the breaking of your ACME endpoint? 😜  Maybe just turn it off for a minute and trigger an ACME transaction? Hoping to merge in the fix before 2.1 beta this week.

**Comment by p3lim** [comment]
Sorry for the delay, everything looks to be working correctly now 👍.

**Comment by mholt** [comment]
@p3lim Okay, excellent, thank you for confirming!
