### ISSUE TITLE
bug: stopping admin endpoint when it is disabled

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#3470]
I am running an instance of caddy with admin interface disabled:

```
{
  "admin": {
    "disabled": true
  },
```

When stopping the server, I see the following error message.

```
2020/06/02 21:25:29 [INFO][cache:0xc000813950] Stopped certificate maintenance routine
2020/06/03 01:25:29.908 ERROR   stopping admin endpoint {"signal": "SIGINT", "error": "no admin server"}
```

The expectation is that it should not try stopping admin endpoint if it is not enabled in the the first place.

**Comment by mholt** [comment]
Is this causing a problem?

**Comment by greenpau** [comment]
@mholt , low priority. Just makes CloudWatch buzz a bit 😄
