### ISSUE TITLE
Reverse proxy and static files config

### ISSUE THREAD

**Issue by valbendan** [caddyserver/caddy#3481]
THIS MAY BE A NOOB QUESTION

There do is an example config for reverse proxy

https://caddyserver.com/docs/caddyfile/patterns#reverse-proxy

```caddy
example.com

root * /var/www
reverse_proxy /api/* localhost:5000
file_server
```

But I need a `reverse` config:

Serve static files having a path starting with `/static/` and proxy requests for everything else 

I use the follow config:

```caddy
example.com

root /static/* /var/www
file_server

reverse_proxy /* localhost:5000
```

but it seems dosen't work.

**Comment by MechanisM** [comment]
Please, use https://caddy.community/ for questions.

**Comment by valbendan** [comment]
caddy community link: 
https://caddy.community/t/reverse-proxy-and-static-files-config/8571
