### ISSUE TITLE
Try h2c with caddyfile, it warns "unrecognized subdirective versions". (v2.1 beta 1) 

### ISSUE THREAD

**Issue by mdlenoir** [caddyserver/caddy#3487]
There's no docs about how to use h2c with caddyfile, so I copied it from someone [#3289](https://github.com/caddyserver/caddy/pull/3289). But it always warns "unrecognized subdirective versions". I don't understand what's wrong. Please teach me, thank you. :)

my caddyfile:
---
{
    admin off
    email xxxx@xxxx.com
    key_type p256
}

xxxxx.com {
    tls {
        protocols tls1.3
        curves    secp256r1
    }

    header {
        Strict-Transport-Security max-age=31536000;
	      X-Content-Type-Options nosniff
	      X-Frame-Options DENY
	      Referrer-Policy no-referrer-when-downgrade
    }

    reverse_proxy /xxxx localhost:12345 {
        transport http {
            versions h2c
        }
    }

    reverse_proxy /yyyy localhost:23456

    reverse_proxy localhost:34567

    encode zstd gzip

    log {
        output file   /var/log/caddy/access.log {
        roll_size     50MiB
        roll_keep     10
        roll_keep_for 720h
        }
    }
}

**Comment by francislavoie** [comment]
Are you sure you're actually using v2.1 beta 1? What does running `caddy version` say?

**Comment by mdlenoir** [comment]
Yes, it is v2.1.0-beta.1
=====================================
/usr/bin/caddy adapt --config /etc/caddy/Caddyfile
adapt: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:22 - Error during parsing: unrecognized subdirective versions
====================================
line 22 is:
versions h2c
===================================
If I remove this reverse_proxy part, everything is fine...

reverse_proxy /xxxx localhost:12345 {
    transport http {
        versions h2c
    }
}

**Comment by mdlenoir** [comment]
hahaha, I find out I'm running 2 caddies and using one caddyfile, surely will get error messages. You don't see me...😳
