### ISSUE TITLE
splitFrontMatter fails when YAML metadata is terminated with ...

### ISSUE THREAD

**Issue by gpanders** [caddyserver/caddy#3497]
When using YAML front matter in the following form:

```markdown
---
title: Hello world!
author: Greg Anders
...
```

Caddy's template engine throws the following error:

```
executing "/" at <splitFrontMatter>: error calling splitFrontMatter: unterminated front matter 
```

While less common, using `...` as the closing delimiter for YAML front matter is valid [as defined by the spec](https://yaml.org/spec/1.0/#l-l-after-document) and is also used in e.g. Pandoc.

(I personally prefer to use the `...` closing syntax as it degrades more gracefully than `---` in Markdown parsers that don't support YAML front matter.)

**Comment by francislavoie** [comment]
Interesting! Thanks for bringing this up, I wrote a quick PR that should fix this. https://github.com/caddyserver/caddy/pull/3498

Could you give it a try to make sure it works for you? You can find the CI artifact here to try it out: https://github.com/caddyserver/caddy/actions/runs/135425356

**Comment by gpanders** [comment]
That *almost* works, it looks like there is an errant `.` at the beginning of the body content. For example:

**index.md**
```markdown
---
title: Hello world
...

This is a test
```

**Caddyfile**
```
localhost

file_server
templates

rewrite /* template.html
```

**template.html**
```html
{{ $pathParts := splitList "/" .OriginalReq.URL.Path }}
{{ $markdownFilename := default "index" (slice $pathParts 1 | join "/") }}
{{ $markdownFilePath := printf "%s.md" $markdownFilename }}
{{ $markdownFile := (include $markdownFilePath | splitFrontMatter) }}
{{ $title := default $markdownFilename $markdownFile.Meta.title }}
<!DOCTYPE html>
<html>
  <body>
    <h1>{{ $title }}</h1>
    {{ markdown $markdownFile.Body }}
  </body>
</html>
```

Results in:
```html
<!DOCTYPE html>
<html>
  <body>
    <h1>Hello world!</h1>
    <p>.</p>
<p>This is a test note.</p>

  </body>
</html>
```

**Comment by francislavoie** [comment]
Huh, interesting. Thanks, I'll look into it 👍
