### ISSUE TITLE
I can't get socket.io proxy to work on v2

### ISSUE THREAD

**Issue by vaaski** [caddyserver/caddy#3499]
Hey, I wanted to switch to caddy v2, but I can't get my socket.io reverse proxy to work.
This is how I configured it in v1 (working): 
```
example.com {
  proxy /path localhost:3515/socket.io {
    header_upstream Host {host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    websocket
  }
  header /path {
    Access-Control-Allow-Origin https://app.example.com
    Access-Control-Allow-Credentials true
  }
}
```
and here is the configuration I've tried in v2 (not working):
```
https://example.com {
  reverse_proxy /path {
    to localhost/socket.io:3515{uri}
    header_up Host {host}
    header_up X-Real-IP {remote}
    header_up X-Forwarded-For {remote}
  }
  header /path/* {
    Access-Control-Allow-Origin http://example.com
    Access-Control-Allow-Credentials true
  }
}
```

I've tried many small adjustments and changes for the v2 config, such as adding `/*` to the end of the reverse_proxy matcher, adding and removing `{uri}` to the upstream, moving the port around in the upstream, but I can't get it to work.
With the config above it just sends an empty 200 OK instead of some upgrade data, but with `/*` added to the matcher I run into a 500 error with caddy telling me something along the lines of `ERROR   http.log.error  making dial info: upstream localhost/socket.io:3515{http.request.uri}: invalid dial address localhost/socket.io:3515/light/?EIO=3&transport=polling&t=NAwZ_lA`

I'd be happy to provide example socket.io server files (nodejs) and any more info about my setup.
I'd love to switch to caddy v2, because it seems like support for v1 is phasing out soon.

Thank you.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by vaaski** [comment]
okay sorry, will do.
you should maybe add this to a comment in the issue template here on github so other people wont make this mistake :)

**Comment by liujunandzhou** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： Francis Lavoie <notifications@github.com>日期： 2020年6月16日周二 10:24收件人： caddyserver/caddy <caddy@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [caddyserver/caddy] I can't get socket.io proxy to work on v2 (#3499)
Hi! Thanks for trying Caddy!
Please ask your usage questions on the Caddy community forums. We prefer to keeh没有p the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by francislavoie** [comment]
> you should maybe add this to a comment in the issue template here on github so other people wont make this mistake :)

FWIW I agree, but the best I can do is point you to the discussion here: https://github.com/caddyserver/caddy/pull/3437

**Comment by vaaski** [comment]
@francislavoie thank you for the help, [I just now posted it](https://caddy.community/t/i-cant-get-socket-io-proxy-to-work-on-v2/8703?u=vaaski) :)
