### ISSUE TITLE
auto_https not working on Mac

### ISSUE THREAD

**Issue by kaitwalla** [caddyserver/caddy#3500]
**Version**: v2.1.0-beta.1 h1:nG+Y2NuoqGvJEnHlVO5PXtTxuc2yHsjr2nU+dJ5yETk=  
**OS**: Mac 10.15.5 

```
192.168.1.21 {
        auto_https off
        reverse_proxy 127.0.0.1:4533
}
```

Per [this](https://github.com/caddyserver/caddy/issues/3219#issuecomment-631131568) and [this commit](https://github.com/caddyserver/caddy/commit/fae064262d9c40393d634660b94d36ce6703aa1c)

**Caveat**: I rarely know what I'm doing and may have screwed something up.
**Logs**:

```
kaitlyn@Syncs caddy % ./caddy start
2020/06/16 14:11:49.901	INFO	using adjacent Caddyfile
run: adapting config using caddyfile: Caddyfile:2: unrecognized directive: auto_https
start: caddy process exited with error: exit status 1
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

`auto_https` is a global option, not a directive.

https://caddyserver.com/docs/caddyfile/options

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
