### ISSUE TITLE
v2: Subfolder requests redirecting to / 

### ISSUE THREAD

**Issue by danlsgiga** [caddyserver/caddy#3504]
I have the following Caddyfile running on `v2.1.0b1`

```caddy-d
{
  http_port 3000
  auto_https off
  admin off
}

(global-log) {
  log {
    output stdout
    format single_field common_log
  }
}

(global-encode) {
  encode zstd gzip
}

(global-headers) {
  header {
    Cache-Control no-cache
    X-Content-Type-Options nosniff
  }
}

http://localhost:3000 {
  import global-log
  import global-encode
  import global-headers

  redir /app1 /app1/
  redir /app2 /app2/
  route {
    handle_path /app1/* {
      root * /opt/jenkins/static/app1
      file_server browse
      try_files {path} {dir}/index.html
    }

    handle_path /app2/* {
      root * /opt/jenkins/static/app2
      file_server browse
      try_files {path} {dir}/index.html
    }

    handle {
      root * /opt/jenkins/static/global
      file_server browse
      try_files {path} {dir}/index.html
    }
  }
}
```

Navigating to `http://localhost:3000/app1` works just fine, but whenever I try to open a subfolder under `app1`, for example `http://localhost:3000/app1/img`, Caddy do a redirect to `http://localhost:3000/img`.

If I visit the same url adding the slash, `http://localhost:3000/app1/img/` everything works.

**Comment by mholt** [comment]
Ah, that's because `handle_path` is stripping the `/app1/` from the path so it doesn't know that is part of the URL.

**Comment by danlsgiga** [comment]
So... sorry for all the noise.

I finally found a working solution for my very specific multibranch usecase.

Here's what I need to do to have multiple paths being served from multiple project builds inside a Jenkins box

```caddy-d
{
  http_port 3000
  auto_https off
  admin off
}

(global-log) {
  log {
    output stdout
    format single_field common_log
  }
}

(global-encode) {
  encode zstd gzip
}

(global-headers) {
  header {
    Cache-Control no-cache
    X-Content-Type-Options nosniff
  }
}

http://localhost:3000 {
  import global-log
  import global-encode
  import global-headers

  redir /app1 /app1/
  redir /app2 /app2/

  @app1 path_regexp branch ^/app1/([^/]*)/?(.*)?$
  @app2 path_regexp branch ^/app2/([^/]*)/?(.*)?$
  @global path_regexp branch ^/([^/]*)/?(.*)?$

  handle @app1 {
    uri strip_prefix /app1
    root * /opt/jenkins/static/app1
    try_files {path} /{re.branch.1}/index.html
    file_server browse
  }

  handle @app2 {
    uri strip_prefix /app2
    root * /opt/jenkins/static/app2
    try_files {path} /{re.branch.1}/index.html
    file_server browse
  }

  handle @global {
    root * /opt/jenkins/static/global
    try_files {path} /{re.branch.1}/index.html
    file_server browse
  }
}
```

Very complex but this only shows the power of Caddy and how many use cases it cover (the sky is the limit).

In my case, the complexity factor is that our root folders are not normalized to follow the same naming convention of the jenkins projects folders, otherwise a single `handler` with a `path_regexp` matcher would be sufficient.

> Note: Obviously this config is just for troubleshooting purposes, so please be advised this Caddyfile disable HTTPS entirely. 😄

**Comment by francislavoie** [comment]
Huh? I'm really confused. Does it work if you do `handle_path /app1*` instead?

**Comment by danlsgiga** [comment]
@francislavoie nope! This is a very subtle use case. We have dynamic folders being created all the time under the jenkins root folders and I had to run the regex because I need to know which "branch" folder is being opened to work with the react router (I have to pass the exact folder/index.html to `try_files`) or React routing won't work.

**Comment by francislavoie** [comment]
Okay, I guess I'm confused as to what a "branch" folder is.

**Comment by mholt** [comment]
Glad you figured out a working config @danlsgiga ! 

> In my case, the complexity factor is that our root folders are not normalized to follow the same naming convention of the jenkins projects folders

That is rather complicated :(
