### ISSUE TITLE
Implement combined log format

### ISSUE THREAD

**Issue by cuu508** [caddyserver/caddy#3505]
Caddy 1 used to support the "combined" log format, and it looks like Caddy 2 does not any more.

If I understand correctly, the recommended way is now to use the structured JSON log entries and feed them into another system which can then filter, reformat etc.

However I think there's still a common use case where you have a standalone, low traffic caddy server with static configuration, and all you want is to see the logs in syslog or in an access.log file, on the same box, for casual inspection. For that use case, it would be nice if we could avoid an external component for formatting the logs.

**Comment by mholt** [comment]
As described in https://caddyserver.com/docs/logging, this is not in the scope of Caddy. It is not Caddy's job to process logs (unless an app is written for it, which nobody has done yet).

You can do this with the custom log format encoder plugin: https://github.com/caddyserver/format-encoder

**Comment by cuu508** [comment]
> You can more or less craft the CombinedLF with the custom log format encoder plugin: https://github.com/caddyserver/format-encoder

Thanks for the suggestion! Can it be configured in Caddyfile? Is there an example somewhere?

**Comment by Mohammed90** [comment]
> > You can more or less craft the CombinedLF with the custom log format encoder plugin: https://github.com/caddyserver/format-encoder
> 
> Thanks for the suggestion! Can it be configured in Caddyfile? Is there an example somewhere?

Yes. In the Caddyfile, its configuration looks like this:
```
log {
	format formatted <template>
}
```
The template traverses the JSON structure [here](https://caddyserver.com/docs/logging#structured-logs) (more or less, as more fields get added). For example, if you want to print the method and URI, the config is:
```
log {
	format formatted "{request>method} {request>uri}"
}
```

I'll add more examples to the README, hopefully, later today.

**Comment by cuu508** [comment]
Awesome, thank you!
