### ISSUE TITLE
New lines in Markdown are rendered as <br>

### ISSUE THREAD

**Issue by gpanders** [caddyserver/caddy#3508]
Hello,

I've noticed that when using the `markdown` parser in a template, newlines in the Markdown source are rendered as `<br/>` in the HTML output:

```markdown
This should be
one line.
```

becomes
```html
<p>This should be<br>
one line.</p>
```

I realize there is not an "official" Markdown spec, and I don't know what Markdown parser Caddy is using, but I do know that the most common implementations ([CommonMark](https://spec.commonmark.org/0.29/#example-366), GFM, and Pandoc) treat newlines as simple whitespace, so that the Markdown fragment above should be rendered simply as

```html
<p>This should be one line.</p>
```
or
```html
<p>This should be
one line.</p>
```

I looked through the docs but I don't see any way to configure the Markdown parser to change this. ~~Would it be possible to either 1) update Caddy's `markdown` implementation to conform to the CommonMark standard or 2) add some kind of configuration option to treat newlines as whitespace?~~ **EDIT**: I dug into the source code a bit and it looks like hard wraps are [explicitly enabled](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/templates/tplcontext.go#L257). I'm curious why this decision was made, and if it's possible to add a configuration option to disable this?

Thanks!

**Comment by Mohammed90** [comment]
Caddy uses [yuin/goldmark](https://github.com/yuin/goldmark). The behavior you see is because Caddy uses the render option [`WithHardWraps`](https://github.com/yuin/goldmark#html-renderer-options) here:

https://github.com/caddyserver/caddy/blob/9770ce7c9ff79f8dc2286a07992168cbcc82b6cc/modules/caddyhttp/templates/tplcontext.go#L256-L259

I wonder if @mholt has a reason to take that route.

**Comment by mholt** [comment]
I believe our docs use it. We'll need to check what happens with the docs site if that option is disabled.

**Comment by solt87** [comment]
I wonder why hard-wrapping is needed? Isn't the [markdown method for forcing a newline](https://daringfireball.net/projects/markdown/syntax#p) (i.e. two or more spaces at the end of a line) sufficient?

**Comment by mholt** [comment]
Okay, well, I tried our docs without hard breaks and couldn't find any significant differences, so maybe we don't need it. I don't remember why I added it. We can remove it. (Pull request?)
