### ISSUE TITLE
Size of directories not shown in static file browser

### ISSUE THREAD

**Issue by NightMachinary** [caddyserver/caddy#3514]
![A79C784A-A026-449C-AC2A-2CA0F195AD4A](https://user-images.githubusercontent.com/36224762/85265769-01626900-b488-11ea-87b2-8d4b0e0d525b.jpeg)

**Comment by francislavoie** [comment]
We use `os.FileInfo`'s `Size()` function to display this information, but that only returns values for regular files. https://golang.org/pkg/os/#FileInfo

The definition of sizes for directories is a bit nebulous. It could either mean the total size of the files directly inside the directory, or it could mean the recursive total including all subdirectories. The former is cheap to calculate, but still requires additional work, and is not necessarily accurate. The later can be very expensive (i.e. getting the size of `/` in your filesystem would take a long time).

Because it's ambiguous, just not showing a size is the best option, and there's no performance concern.

**Comment by NightMachinary** [comment]
@francislavoie I think building a simple index (preferably in the background) should solve the performance problem of recursively determining size? I know there will be inaccuracies, but why let the perfect be the enemy of the good? Not showing the sizes is just erasing the problem. I think most users will benefit from an incomplete solution. This is especially true for users with modest directories, who can even go along with an on-the-fly calculation of recursive size.

**Comment by hairyhenderson** [comment]
Is this actually an expected/desired behaviour?

I've done a bit of googling to see what other webservers do. It appears that neither Apache nor nginx show directory sizes.

Also, in the macOS Finder, no sizes are shown in the Size column. And it's the same story on in the Windows File Explorer.

TBH I think an empty size column is the only correct approach.

> I know there will be inaccuracies, but why let the perfect be the enemy of the good?

This isn't a case where it'll be "a little" wrong, but instead a case where things can be _vastly_ wrong and lead to poor decisions. Imagine a highly nested set of thousands of directories, with hundreds of thousands of files of varying sizes...

What is the _actual_ problem you'd like to solve with this feature? What sorts of decisions would you make differently if the browser showed directory sizes?

**Comment by NightMachinary** [comment]
@hairyhenderson I personally, in this instance, want the directory sizes so that I can sort by it, because I have a lot of unimportant files/directories with small sizes. This usecase can benefit from inaccurate info. This can be made into an optional feature to enable in the config, so only people who benefit from it enable it.

In my case, I have so few files that I am happy to just pay the performance penalty for a complete calculation of size. So there will be no inaccuracies. This can be another option in the config.

The solution of indexing the sizes also works pretty accurately. The inaccuracies will be if the user changed files after the index was created. Perhaps this can be fixed by hooking into appropriate OS events? (I’m no expert on this.)

On the topic of mainstream tools not having this feature; Well, if they did have all the features, there would be no point in having new contenders like Caddy.

**Comment by hairyhenderson** [comment]
> On the topic of mainstream tools not having this feature; Well, if they did have all the features, there would be no point in having new contenders like Caddy.

My point was that there's a good reason that _nobody_ else does this 😉

> The solution of indexing the sizes also works pretty accurately. The inaccuracies will be if the user changed files after the index was created. Perhaps this can be fixed by hooking into appropriate OS events? (I’m no expert on this.)

This _is_ possible, but TBH it'd be relatively expensive and would still risk being wrong some of the time.

A package like https://github.com/fsnotify/fsnotify could be used to trigger updates, but there are challenges: no recursive directory watching (yet), and there are OS-specific limits to how many files can be watched by a process as well.

Anyway, there's no reason someone couldn't fork the static file server module and enhance the browsing to add directory sizes!

**Comment by mholt** [comment]
Calculating the size of a directory on _most_ file systems is expensive, so we will not be implementing this into Caddy's static file web server.
