### ISSUE TITLE
Inconsistent behaviour of handle directive

### ISSUE THREAD

**Issue by averri** [caddyserver/caddy#3515]
I'm using Docker image 2.0.0 for running this example.

Suppose the following desired behavior:

> If the browser requests a JavaScript resource, like `/js/app.js`, along with a header `Accept-Encoding: gzip` and if the same resource exist in a compressed gzip format in the disk, Caddy should serve the compressed version. If the compressed version does not exist, so serve the original resource.

For implementing the referred behaviour I'm using the following Caddyfile:

```
:8383
root * /usr/share/caddy

@gzip {
  header Accept-Encoding *gzip*
  file {
      try_files {path}.gz
  }
}

handle /js/* {
  file_server
  header Content-Type text/javascript

  handle @gzip {
    header Content-Encoding gzip
    rewrite {path}.gz
  }

  # Serve non-compressed JS files otherwise.
}


handle {
  file_server
  # Support for SPA.
  try_files {path} /index.html
}
```

The above Caddyfile is not working as intended. The file `/js/app.js` is served instead of the compressed file `/js/app.js.gz`. But if I change the config from:

```
  handle @gzip {
    header Content-Encoding gzip
    rewrite {path}.gz
  }
```

... to:
```
  handle @gzip {
    header Alex compressed
    rewrite {path}.gz
  }
```

... it does work, Caddy will serve the compressed file `/js/app.js.gz`, though the response comes with the header `Alex: compressed` which is just for testing purposes, it does not have any meaning.

So this is the inconsistent behavior, the execution of the `handle` block is influenced by the directive `header` inside it.

**Comment by francislavoie** [comment]
What do you mean by "is not working as intended" and "it does work"? You aren't clear about the exact behaviour you're seeing. Please use `curl -v` to show the response returned to compare.

As-is, I can't consider this a bug because we don't have enough information.

**Comment by averri** [comment]
I thought it was clear here:

> The above Caddyfile is not working as intended. The file /js/app.js is served instead of the compressed file /js/app.js.gz

**Comment by francislavoie** [comment]
No, it's not clear. The only thing in the codebase that deals with `Content-Encoding` is the `encode` handler, which you don't have enabled in your config. We don't have enough evidence to go on here. We need a minimally reproducible example.

**Comment by averri** [comment]
The Caddyfile I have posted above is indeed working. The problem is that I was using Intellij HTTP Requests for testing, and frustratingly, Caddy is not working as intended when handling requests from Intellij HTTP Request.

This is the summary I have done.

### Scenario 1: Using IntelliJ HTTP Requests to validate the Caddyfile
This request returns a non-compressed JavaScript file (not the intended behavior):

```
GET http://localhost:8383/js/vendor.a560d488.js
Accept-Encoding: gzip
```
Returned headers:
```
Accept-Ranges: bytes
Content-Type: text/javascript
Etag: "qcbnly3ojc"
Last-Modified: Mon, 22 Jun 2020 09:56:22 GMT
Server: Caddy
Date: Mon, 22 Jun 2020 13:49:49 GMT
Transfer-Encoding: chunked
```

### Scenario 2: Using curl to validate the Caddyfile

This request returns the compressed JavaScript file (the intended behavior):
```
 curl  -H "Accept-Encoding: gzip" -D - http://localhost:8383/js/vendor.a560d488.js
```
Returned headers:
```
Accept-Ranges: bytes
Content-Encoding: gzip
Content-Type: text/javascript
Etag: "qcbnly3ojc"
Last-Modified: Mon, 22 Jun 2020 09:56:22 GMT
Scenario: js
Server: Caddy
Date: Mon, 22 Jun 2020 13:59:13 GMT
Transfer-Encoding: chunked
```

The only possible way to find the root cause is to debug the HTTP call using Wireshark, possibly the Intellij HTTP request has some issues. I'll close this issue because the aforementioned Caddyfile is working as intended when tested via browser and also curl.

**Comment by francislavoie** [comment]
Thanks - I think IntelliJ must be ignoring the Accept-Encoding header or stripping it before requesting then. You can enable request logging in Caddy (just add `log` to your config to get access logs in stdout) and see what request headers Caddy sees.

**Comment by averri** [comment]
Thanks @francislavoie for helping.
