### ISSUE TITLE
Configurable data directory

### ISSUE THREAD

**Issue by p3lim** [caddyserver/caddy#3516]
Currently the only place Caddy will save its data is in $HOME, would be nice if this can be customized (by other means than changing the user's home directory), e.g. with a flag.

Also, if/when you do implement this, please don't treat the directories within like hidden files when this option is provided, e.g. instead of this:
```
/var/lib/caddy
├── .config/
│   └── caddy/
│       └── autosave.json
└── .local/
    └── share/
        └── caddy/
            ├── acme/
            ├── certificates/
            ├── locks/
            └── ocsp/
```
then this:
```
/var/lib/caddy
├── autosave.json
├── acme/
├── certificates/
├── locks/
└── ocsp/
```

The current implementation is understandable when it's being run as a user, but not as a service by the system, as it mostly is.

(Extra awesome if this could make it to 2.1 😃)

**Comment by p3lim** [comment]
Figured it's _kind of_ possible by setting both `XDG_CONFIG_HOME` and `XDG_DATA_HOME` to `/var/lib`, but that's not a good solution.

**Comment by mholt** [comment]
Thanks for the question. You can change Caddy's storage to _anything_, any folder on your disk, or even a database or any other backend storage module, with or without environment variables: https://caddyserver.com/docs/json/storage/

This has been configurable since the very beginning.

**Comment by p3lim** [comment]
I fail to see how to use this, could you elaborate with an example?

**Comment by mholt** [comment]
```json
{
    "storage": {
        "module": "file_system",
        "root": "/foo/bar"
    }
}
```

Any further questions about how to use Caddy should go on our forums: https://caddy.community

**Comment by p3lim** [comment]
For anyone finding this in the future, this is how you configure this in a Caddyfile:
```
{
    storage file_system {
        root /var/lib/caddy
    }
}

# rest of your Caddyfile
```

**Comment by Mohammed90** [comment]
> For anyone finding this in the future, this is how you configure this in a Caddyfile:
> 
> ```
> {
>     storage file_system {
>         root /var/lib/caddy
>     }
> }
> 
> # rest of your Caddyfile
> ```
> 
> The autosave.json file will still be using $HOME though.

Correction, [Caddy adheres to the XDG convention](https://caddyserver.com/docs/conventions#data-directory) and uses `XDG_DATA_HOME`, not necessarily $HOME.

**Comment by jmellicker** [comment]
@mohammed90 if you set `XDG_DATA_HOME` to a certain directory (let's say `/caddy-config`, and update Caddy through the Caddy API, is Caddy expected to update the `autosave.json` file in the `/caddy-config` directory?

**Comment by mholt** [comment]
@jmellicker Assuming Caddy's environment reflects the changed XDG_DATA_HOME value somehow, then yes. A process can only read its current environment, so if you change that variable you'll have to restart the Caddy process.
