### ISSUE TITLE
basicauth not working with builder

### ISSUE THREAD

**Issue by firedrow** [caddyserver/caddy#3519]
I ran a docker builder earlier today to add the webdav plugin, and while doing testing with converting my v1 config to v2 I ran across the issue that basicauth isn't working.  Firefox and Chrome headers show `Www-Authenticate: Basic realm="restricted"`, but I'm not getting any credentials request.  If I take the `basicauth` directive out of the my static.homelab.zt or dav.homelab.zt, I get the file browser from static and XML output from dav.

My builder Dockerfile:
_tagged as caddy:2.0.0-custom_
```
FROM caddy:2.0.0-builder AS builder

RUN caddy-builder \
    github.com/mholt/caddy-webdav

FROM caddy:2.0.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

Relevant Caddyfile:
_Used the hiccup password listed in docs_
```
{
    order webdav last
}

(global) {
  encode gzip zstd
  log {
    output file /data/logs/caddy_access.log
  }
  handle_errors /data/logs/caddy_errors.log
  php_fastcgi phpfpm:9000
}

http://dav.homelab.zt {
  import global

  basicauth /* {
    secureguy JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
  }

  webdav / {
    root /usr/share/caddy/webdav
  }

  header {
    Access-Control-Allow-Origin *
    Access-Control-Allow-Credentials true
    Access-Control-Allow-Methods GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK
    Access-Control-Allow-Headers Authorization,DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Accept-Charset,X-Accept,origin,accept,if-match,destination,overwrite
    Access-Control-Expose-Headers ETag
    Access-Control-Max-Age 1728000
  }
}

http://static.homelab.zt {
  import global

  root * /usr/share/caddy/static
  file_server /* browse

  basicauth /* {
    secureguy JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
  }
}
```

**Comment by mholt** [comment]
Hi, thanks for opening an issue.

To make sure I understand correctly, are you asking for help with your Caddyfile / why the browser isn't showing a prompt? Or are you reporting a bug in Caddy? We like to keep the issue tracker focused on bugs and features, and we have the forum for help here: https://caddy.community

**Comment by firedrow** [comment]
I will post over to the community before I call this a bug.  Thanks.
