### ISSUE TITLE
Need better config file.

### ISSUE THREAD

**Issue by initdc** [caddyserver/caddy#3527]
Hello

I am a user of Caddy, Caddy is a great software. But for a while time, I switch to use nginx. I was trying use Caddy v2, use its plugin: filebrowser. I can boot it by command but can't boot it by configuration file. That makes me confused.

I think,  it is not the best way that transforming the config file of the  v1 version to the json file. It has to many symbols, and it is not easy to edit.

I am learning golang, I am so excited that we have a web server written by go. I also used LiteSpeed for trying before, it is another great software, its config file is compatible with apache2. Nginx also has simple config file, now and always. So I think, could the config file be compatible with nginx ? 

It might not be a good idea, but config file become clearly to read and edit.

This is just my thought, so sorry for my rudeness. I highly wish caddy becomes better.

**Comment by mholt** [comment]
What "filebrowser" plugin? That's not one I'm familiar with.

Anyway, if you don't like using JSON, then use the [Caddyfile](https://caddyserver.com/docs/caddyfile). Or any other [config adapter](https://caddyserver.com/docs/config-adapters) of your choice. Or [write your own](https://caddyserver.com/docs/extending-caddy/config-adapters).

You have a _lot_ of options here -- more than any other web server will offer you -- so take advantage of that.

If you have a question about how to use Caddy, you can always ask on our forums: https://caddy.community - this issue tracker is reserved for bug reports and tracking feature development.
