### ISSUE TITLE
How can i look for my ssl key

### ISSUE THREAD

**Issue by smallfus** [caddyserver/caddy#3528]
if i use automatic https and ssl in Ubuntu20.04,where are those private key or public key storage??

**Comment by op01** [comment]
Please see [Data directory](https://caddyserver.com/docs/conventions#data-directory)

**Comment by smallfus** [comment]
> Please see [Data directory](https://caddyserver.com/docs/conventions#data-directory)

I try that,but still can't look for.
can i assign storage directory??and syntax is what??

thank all.

**Comment by tullo** [comment]
`ls  /var/lib/caddy/.local/share/caddy/`
acme  certificates  locks  ocsp

**Comment by francislavoie** [comment]
The `caddy` user's home directory is `/var/lib/caddy`.

You can see that in the `.deb` post-install script here: https://github.com/caddyserver/dist/blob/master/scripts/postinstall.sh#L13

**Comment by mholt** [comment]
You can also run `caddy environ` to know where things are at.
