### ISSUE TITLE
Config changes not picked up

### ISSUE THREAD

**Issue by tullo** [caddyserver/caddy#3530]
Hi there

I decided to move a few sites using caddy v2.1.0 and API based configuration.

The sites work okay, but configuration updates result in surprising outcomes.

For example:  updating the "Content-Security-Policy" has no effect.

I performed the update as follows:
1. `wget https://raw.githubusercontent.com/tullo/tullo.net/master/caddy.json`
1. `curl localhost:2019/load -X POST -H "Content-Type: application/json" -H "Cache-Control: must-revalidate"   -d @caddy.json`
https://github.com/tullo/tullo.net/blob/master/caddy.json

But a quick check for the updated header shows unchanged values.

```
curl -I https://amstutz-it.dk/
HTTP/2 200 
accept-ranges: bytes
content-security-policy: default-src 'self'; style-src 'nonce-KFOVYFCJmQHFbx'
content-type: text/html; charset=utf-8
etag: "okvjyt13s"
last-modified: Sat, 04 Feb 2017 23:59:17 GMT
strict-transport-security: max-age=31536000;
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
content-length: 1432
date: Sun, 28 Jun 2020 21:41:52 GMT
```
I also updated one of the sites index.html file's meta tags. The updated file is not being served.

It is probably my wrong doing. But it's just not obvious to me, where to look!

on ubuntu focal (20.04 lts)
```
caddy version
2020/06/29 00:13:15 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

v2.1.0 h1:MC4d65RCVaEKy1iOFjsD51mybOwS8qdEVBi7ESDhUfE=

```

**Comment by tullo** [comment]
```
cat /etc/systemd/system/caddy-api.service

[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target

[Service]
User=caddy
Group=caddy
ExecStart=/usr/local/bin/caddy run --environ --resume
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

```

**Comment by francislavoie** [comment]
Does it work with Caddy v2.0? Just to narrow things down.

**Comment by tullo** [comment]
There are no config errors in the logs.

I'm going to rollback to caddy v1.0.3

**Comment by mholt** [comment]
@tullo 

> I'm going to rollback to caddy v1.0.3

Why are you rolling back to such an old version? (There is v1.0.5.) The feature you're having trouble with isn't even available in v1, so rolling back to v1 won't help you (or help us fix any problem).

Just so you know, by doing that, it makes this look more like user error. If it's a bug, you would help us reproduce the bug so we can fix it. (Or you could submit a patch in a PR.) How can we reproduce the error you're seeing?

**Comment by tullo** [comment]
@mholt I gave it another go today.  Converted the v1.0.3 config with `caddy adapt -validate` and fixed the reported errors.
The result of that work can be found here https://github.com/tullo/tullo.net/blob/master/caddy.json
Running the two mini sites with that config will not send the security headers in the respons. Same for the cache control headers.

Do the handlers have to appear in a specific order, maybe?

**Comment by tullo** [comment]
```
curl -I https://tullo.net/
HTTP/2 200 
accept-ranges: bytes
content-type: text/html; charset=utf-8
etag: "qcoohj8w"
last-modified: Mon, 29 Jun 2020 10:44:07 GMT
server: Caddy
content-length: 320
date: Mon, 29 Jun 2020 23:06:27 GMT

anda@anda-G750JS:~/code/tmp/dddddd (master)$ curl -I https://amstutz-it.dk
HTTP/2 200 
accept-ranges: bytes
content-type: text/html; charset=utf-8
etag: "qcp2ne15k"
last-modified: Mon, 29 Jun 2020 15:50:02 GMT
server: Caddy
content-length: 1496
date: Mon, 29 Jun 2020 23:06:53 GMT

```

**Comment by mholt** [comment]
@tullo

> I gave it another go today. Converted the v1.0.3 config with caddy adapt -validate and fixed the reported errors.

To be clear, you know that v1 Caddyfile is not compatible with v2, right? And you don't _have_ to use JSON with v2, you can still use the Caddyfile (it's just not compatible with v1's Caddyfile). There's an upgrade guide here: https://caddyserver.com/docs/v2-upgrade

You can read how routing works and how handler order is significant here in the docs: https://caddyserver.com/docs/json/apps/http/#servers/errors/routes/handle

This is not a Caddy bug, so closing. :)

If you have further questions about how to use Caddy, you can ask on our forums: https://caddy.community
