### ISSUE TITLE
Feature: Experimental QuicTransport Support

### ISSUE THREAD

**Issue by dhannyz** [caddyserver/caddy#3533]
I have been using caddy for a while now, enjoying the experimental features of http/quic and now http/3.

WebTransport is a new proposal to fill some holes (and maybe take over from) Websockets and WebRTC for client-server use cases.
Chrome has committed to implementing QuicTransport first and is currently in an origin trial.

The following link contains some reasoning as well as links to a working test server (in python)
https://web.dev/quictransport/

**Comment by francislavoie** [comment]
QUIC/HTTP3 support is provided by https://github.com/lucas-clemente/quic-go so it would need to support it before Caddy could offer it.

**Comment by gedw99** [comment]
See https://github.com/pion/webrtc/pull/1294

**Comment by francislavoie** [comment]
It's unclear what exactly this would mean for Caddy. Would this just be a quic proxy? What would Caddy be streaming if it supported this?

QuicTransport is cool, but we need more info/discussion before this issue can be actionable.

Closing for now, but feel free to discuss and elaborate, we could reopen this later.
