### ISSUE TITLE
我可能是个弱智

### ISSUE THREAD

**Issue by mbcc2006** [caddyserver/caddy#3538]
我高高兴兴研究了半天,你们的文档真的打败了我.导致我连英文都不想说.只想给你们-1分.fuck you

**Comment by francislavoie** [comment]
Sorry, all the maintainers of this project are English speakers, we can't provide support in Chinese.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
English is hard. So is Chinese.

If any Chinese speakers would like to translate the docs into Chinese, we can discuss that in a new issue that doesn't use profanities.
