### ISSUE TITLE
Allow tailing comma in Caddyfile same definition

### ISSUE THREAD

**Issue by CaselIT** [caddyserver/caddy#3545]
Currently when specifying that one definition is shared by more than one site they can be listed together in the caddyfile.
From the [documentation](https://caddyserver.com/docs/caddyfile/concepts#addresses)
```
localhost:8080, example.com {
  ...
}
```

Currently a tailing comma is not supported: if I add a comma after `example.com` caddy has returns this error:
`Error during parsing: Expected another address but had '{' - check for extra comma`

I have a configuration that can take another address from an environment variable, that is filled in a deploy but that can be empty in testing, like in the example below.
```
localhost, {$PUBLIC_ADDRESS} {
  ...
}
```
Supporting a tailing comma would make this kind of configuration easier to use.

**Comment by francislavoie** [comment]
Actually for site labels, the comma is optional, you can have space separated site labels. That means you can do this instead and avoid the error:

```
localhost {$PUBLIC_ADDRESS} {
  ...
}
```

**Comment by CaselIT** [comment]
Thanks, I did not know you could avoid the comma.
The documentation does not mention it, so maybe it should be mentioned there?

**Comment by francislavoie** [comment]
Yeah, you're right. There's allusions to it in other sections of the docs, i.e. that whitespace is significant for tokenizing, but it's not mentioned in the addresses section.

https://github.com/caddyserver/website/pull/61

**Comment by CaselIT** [comment]
Thanks!
