### ISSUE TITLE
No update of Caddy available on CentOS

### ISSUE THREAD

**Issue by bestpaydeals** [caddyserver/caddy#3548]
I am not getting update of Caddy 2.1.1 on Centos 7 and 8. It had installed Caddy from the following command:

```
yum install yum-plugin-copr
yum copr enable @caddy/caddy
yum install caddy -y
```

However when I try:

`yum update caddy -y`

I don't get the latest version.

This problem is happening all the time when new update arrives on Github and I try updating Caddy 2.

If you fix this please consider keeping latest version of Caddy for CentOS evertime you update.

Thanks!

**Comment by francislavoie** [comment]
Duplicate of https://github.com/caddyserver/dist/issues/39
