### ISSUE TITLE
How to log request_body with version v2.1.1

### ISSUE THREAD

**Issue by GraysMile** [caddyserver/caddy#3552]
I want to get request_body in http.access.log. How do i write Caddyfile with  version v2.1.1?

**Comment by mholt** [comment]
Not currently implemented, as there is no known way to do this efficiently.

**Comment by mholt** [comment]
Implemented in https://github.com/caddyserver/caddy/commit/6f0f159ba56adeb6e2cbbb408651419b87f20856 -- note that it is very inefficient for production environments. You will need to use a custom log encoder such as the [format-encoder](https://github.com/caddyserver/format-encoder) to print the body.
