### ISSUE TITLE
MIPS builds

### ISSUE THREAD

**Issue by p3lim** [caddyserver/caddy#3554]
1.x had builds for MIPS (ref #1319), but with 2.x it seems they have been forgotten.
Would be nice to see them again so Caddy can continue to run on embedded systems that favor this architecture.

**Comment by p3lim** [comment]
If possible, it would be extra awesome if these builds can be included in the repos.

**Comment by mholt** [comment]
We didn't forget, more like we trimmed down our officially supported platforms _initially_ and will ramp them up based on demand instead.

I'll point out that it's easy to build Caddy from source for any platforms, even if we don't do the builds for you in our CI.

What is your use case for automated MIPS builds?

**Comment by p3lim** [comment]
Routers and other embedded hardware, using Caddy either for load balancing or exposing internal services directly on the edge, and also being able to use Caddy to proxy and secure the web interfaces to the embedded hardware itself.

**Comment by mholt** [comment]
Interesting -- tell me more. What routers / hardware are you embedding Caddy into?

**Comment by p3lim** [comment]
Pretty much anything that runs OpenWRT, Ubiquiti stuff also run on MIPS architecture (their EdgeOS is just Debian).

**Comment by mholt** [comment]
The new website's download page (which will be visible whenever the domain admin updates DNS records) will make MIPS downloads easily available, hopefully it launches today or this weekend!
