### ISSUE TITLE
configuring application data location

### ISSUE THREAD

**Issue by panva** [caddyserver/caddy#3559]
**Feature description**

I would like to be able to configure the app data folder location. Looking at the [current](https://github.com/caddyserver/caddy/blob/master/storage.go#L122-L154) code it seems I can abuse the presence of `XDG_DATA_HOME` environment variable but it doesn't seem to be its intended use.

**Comment by mholt** [comment]
You can already configure this by configuring storage: https://caddyserver.com/docs/json/#storage

Or with a Caddyfile global option: https://caddyserver.com/docs/caddyfile/options

**Comment by panva** [comment]
@mholt how might one use those when running simple `caddy reverse-proxy --to 443 --from 3000`?

**Comment by mholt** [comment]
@panva Set XDG_DATA_HOME. Subcommands like reverse-proxy and file-server are meant for quick/simple use cases only. If you need to customize anything, you'll obviously need to configure Caddy.

**Comment by panva** [comment]
So, is `XDG_DATA_HOME` going to remain a stable means of doing so? because from the name and origin of that environment variable name it doesn't look like it.

**Comment by mholt** [comment]
@panva Insofar as our documentation covers, v2 is intended to be stable, yes. Our documentation mentions this: https://caddyserver.com/docs/conventions#data-directory

It's not a variable we just made up, this is a pseudo-standard variable used across many Linux environments. You can google it to get more information.

**Comment by panva** [comment]
@mholt answered, thank you, sorry for the noise
