### ISSUE TITLE
Udp dtls server ,using Caddy2 generated certs possible ?

### ISSUE THREAD

**Issue by extremety1989** [caddyserver/caddy#3560]
Hey all,
i have VPS and i want use it as UDP server.
i use Caddy2 to automate my certs. 
Can i use generated certs by Caddy2  or do i need to generate my own to be able to use in my udp application ?

i do not know where are certs located ..

var _key = preload("generated.key")
var _cert = preload("generated.crt")

**Comment by mholt** [comment]
Caddy's certificates work for basically any kind of TLS connections. However, Caddy does not support DTLS out of the box.

A third-party module could easily do this, though. There's Go packages that implement it: https://github.com/pion/dtls

Anyone is welcome to implement such a module!

In the future, please ask questions in our forum: https://caddy.community -- this issue tracker is reserved for actionable feature requests and bug reports. Thanks!
