### ISSUE TITLE
[FEATURE][v2]: Add support to load client authentication CA certs from file

### ISSUE THREAD

**Issue by danlsgiga** [caddyserver/caddy#3563]
Right now we need to hardcode the `trusted_ca_certs` in base64 format in the config. Just as we are able to load certificates from files in the `apps.tls.certificates.load_files`, it would be nice to do the same for the `trusted_ca_certs` when using client authentication. 

```json
"tls_connection_policies": [{			
    "client_authentication": {
        "trusted_ca_certs": [""],
        "trusted_leaf_certs": [""],
        "mode": ""
    },
}]
```

**Comment by danlsgiga** [comment]
Hey @mholt, not sure how hard would be to have this in 2.3?

**Comment by francislavoie** [comment]
Think you could write a PR @danlsgiga?

**Comment by mholt** [comment]
Sure, I think this can be done before 2.3. I'm starting on the flagship feature of 2.3 today so I can probably work this in at some point too.

**Comment by danlsgiga** [comment]
I can totally help on this one... if you guys have suggestions where should I look for and I can try to figure it out here.

**Comment by mholt** [comment]
Sure, you'll want to look at connpolicy.go and add a field like `TrustedCACertFiles` that takes a list of file names, then load them below; see where `TrustedCACerts` is used; it's pretty similar. But I think Go has some helper functions for loading certs into a pool.
