### ISSUE TITLE
Don’t set SERVER_PORT to empty string (reverse proxy)

### ISSUE THREAD

**Issue by sorbits** [caddyserver/caddy#3568]
I ran into an issue with a PHP framework that got confused about `SERVER_PORT` being set to an empty string.

Assuming this framework has been used with many other web servers, it implies that the de facto standard is to either have a value, or not set it at all, which I therefore propose that Caddy does as well.

That said, I did open an issue with the PHP framework in question (bcosca/fatfree#1194) as I believe their code should be updated, but the problem may also affect other frameworks, which is why I am also opening an issue with Caddy.

**Comment by sorbits** [comment]
Update: I checked [RFC3875](https://tools.ietf.org/html/rfc3875#section-4.1.15) which makes it clear that Caddy *must* set `SERVER_PORT` to a value:

    The SERVER_PORT variable MUST be set to the TCP/IP port number on
    which this request is received from the client.  This value is used
    in the port part of the Script-URI.

        SERVER_PORT = server-port
        server-port = 1*digit

    Note that this variable MUST be set, even if the port is the default
    port for the scheme and could otherwise be omitted from a URI.

**Comment by francislavoie** [comment]
Interesting.

@mholt I think we should look at `r.URL` and guess the port based on the scheme if it can't be split from the Host maybe?

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L223

**Comment by francislavoie** [comment]
Actually wait, what's your Caddyfile? Are you using a unix socket? In that case there's no server port. If you're using a TCP socket (i.e. port 9000 for php-fpm typically) then that's what `SERVER_PORT` would be, I think.

If that's the case, we can skip that env for compliance.

**Comment by francislavoie** [comment]
https://github.com/caddyserver/caddy/pull/3570 should fix both of the issues, I think.

Could you give it a shot? You can use the CI artifact from here: https://github.com/caddyserver/caddy/actions/runs/165314958

**Comment by sorbits** [comment]
> #3570 should fix both of the issues, I think.

Awesome, thanks!

I can confirm that it fixes both issues, furthermore you are correct that I am using a unix socket for FastCGI (so there is no port).
