### ISSUE TITLE
Respond error 404 to 410 not working

### ISSUE THREAD

**Issue by bestpaydeals** [caddyserver/caddy#3579]
I have been trying to respond all 404 errors to 410 from a month. I tried starting from respond to rewrite as for example:

```
@404 {
expression {http.error.status_code} == 404
}
respond @404 410
```

And also tried using handle_errors. Nothing is working but the Caddyfile shows valid.

Is there any other syntax to denote http error as 404? This syntax expression {http.error.status_code} == 404 is absolutely not working. Please help me!

**Comment by francislavoie** [comment]
You were already given an answer on the forums.

https://caddy.community/t/respond-all-404-to-410/8964/3

**Comment by bestpaydeals** [comment]
No that didn't work. So, I am asking here on Github.

**Comment by francislavoie** [comment]
We don't have enough information about your problem to go any further. On that community thread, you completely skipped filling out the thread template which is _necessary_ for us to give you effective help. Please help yourself by helping us understand your problem. We can't just magically know the answers if we don't understand the problem. You need to bring clear evidence.

**Comment by mholt** [comment]
I am wondering, @bestpaydeals, why do you think asking for help here will be any different?
