### ISSUE TITLE
Explain how to adapt the alias concept in Caddy

### ISSUE THREAD

**Issue by fedelibre** [caddyserver/caddy#3586]
More than two years ago I [suggested adding a brief explanation of how to have alias in Caddy](https://caddy.community/t/doc-explain-how-alias-works-in-caddy/3255).
This is both a doc feature request and also a support request, since I cannot get it working as I used to do in v1.

I haven't used Caddy for a while. I'm now using v2 and tried again to serve some files in a different directory from the main one. However, I cannot make it work. Perhaps there's some new v2 issue I'm not aware of.

My Caddyfile (for a local server) is basically something like this:

```
{
  debug
}

:80 {
  root * /home/me/www
  file_server browse
}

:80/foo/ {
  root * /home/me/foo
  file_server
}
```

If I try opening localhost/foo/, I don't get any error but the page is completely empty.

I don't see any information in `journalctl -u caddy` or `journalctl -f`. It seems Caddy configuration is Ok.
I'm sure the paths are correct. What else could I check?

I'm on Fedora 32 with SELinux enabled.

```
$ caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

**Comment by mholt** [comment]
Did you know that path matchers in v2 are exact? So if you want to match a prefix, you need to suffix the path with `*`. Like `:80/foo/*`.

**Comment by fedelibre** [comment]
Ok, now I can see `/foo/`, but any child path, like `/foo/bar/`, is returning a blank page.
I  thought the * wildcard implied recursivity... what I'm missing?

**Comment by mholt** [comment]
How can we reproduce the issue?

Here's a template to help give us the necessary information:

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by fedelibre** [comment]
While trying a minimal example, I cannot make work even the main match foo/ (which worked in my previous attempt). I haven't tried foo/bar/ yet.
Here's the full info to reproduce it.

## 1. Environment

### 1a. Operating system and version

```
 lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
$ caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

Caddy installed from Fedora COPR.


## 2. Description

### 2a. What happens (briefly explain what is wrong)

Cannot serve files using a request matcher.


## 3. Tutorial (minimal steps to reproduce the bug)

Create the following file structure in your home:

```
$ tree --noreport caddy
caddy
└── index.html

$ tree --noreport foo
foo
├── bar
│   └── index.html
└── index.html
```

Caddyfile (adapt the paths to your real home path):

```
{
  debug
}

:8080 {
  root * /home/fede/caddy
  file_server
}

:8080/foo/* {
  root * /home/fede/foo
  file_server
}
```

Run caddy in the same dir as the Caddyfile:

    caddy start 

Open http://localhost:8080/. It works fine.
Now try http://localhost:8080/foo. I get a blank page.

**Comment by mholt** [comment]
@fedelibre Thanks! That is helpful, and reveals the problem.

> Now try http://localhost:8080/foo. I get a blank page.

That's because there is no file `/home/fede/foo/foo/<index file>` (where `<index file>` is usually `index.html` but it can be a couple other things too IIRC).

The [file server docs](https://caddyserver.com/docs/caddyfile/directives/file_server) explain how it works:

> It works by appending the request's URI path to the site's root path.

If you run `caddy adapt` on your Caddyfile you'll see the resulting JSON which gives you another way of looking at what is happening. Basically, request matchers don't change or rewrite requests.

**Comment by fedelibre** [comment]
> @fedelibre Thanks! That is helpful, and reveals the problem.
> 
> (Edited to clear up a confusing point in my initial post)
> 
> > Now try http://localhost:8080/foo. I get a blank page.
> 
> That's because there is no file `/home/fede/caddy/foo`.
> 
> Do you indent to use the second site block? That one only matches requests in `/foo/`, not `/foo`.
> 

Sorry, I  should have written http://localhost:8080/foo/ (with trailing slash).
This is not working while it should as there is `/home/fede/foo/index.html`.
The second site block is **meant to serve files in a different directory than the main one**. How can I do this?

> The [file server docs](https://caddyserver.com/docs/caddyfile/directives/file_server) explain how it works:
> 
> > It works by appending the request's URI path to the site's root path.

Isn't this what I did in the second site block?

> 
> If you run `caddy adapt` on your Caddyfile you'll see the resulting JSON which gives you another way of looking at what is happening. Basically, request matchers don't change or rewrite requests.

I'm afraid I'm still missing the point.

Here's a beautified version of the json. IIUC it represents what I want to achieve, but not what I see on the browser:

```
{
  "logging": {
    "logs": {
      "default": {
        "level": "DEBUG"
      }
    }
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":8080"
          ],
          "routes": [
            {
              "match": [
                {
                  "path": [
                    "/foo/*"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "vars",
                          "root": "/home/fede/foo"
                        },
                        {
                          "handler": "file_server",
                          "hide": [
                            "Caddyfile"
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            },
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "vars",
                          "root": "/home/fede/caddy"
                        },
                        {
                          "handler": "file_server",
                          "hide": [
                            "Caddyfile"
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```

**Comment by mholt** [comment]
> This is not working while it should as there is /home/fede/foo/index.html.

Ah, but there's no `/home/fede/foo/foo/index.html`.

Your request is (equivalently) to `/foo/index.html` and your site root is `/home/fede/foo`, so it is lookin for `/home/fede/foo/foo/index.html`, which does not exist.

**Comment by fedelibre** [comment]
Thanks for the patience!
I think I got it eventually.

Here's the workaround:

```
$ tree --noreport foo
foo
└── foo
    ├── bar
    │   └── index.html
    └── index.html
```

Don't know if  there's a better one.

**Comment by mholt** [comment]
You should read this: https://caddy.community/t/composing-in-the-caddyfile/8291?u=matt

There are several ways to handle this better, IMO. You could use `uri strip_prefix` to remove the extra `/foo` from the path. You could also just use a single site block and use `handle_path` which strips the prefix for you. You can have multiple root directives in the same site block.
