### ISSUE TITLE
reverse-proxy CLI with internal TLS

### ISSUE THREAD

**Issue by p3lim** [caddyserver/caddy#3589]
I really like being able to use `caddy reverse-proxy` for development purposes, and it would be incredibly useful if it could also serve over HTTPS without LE ACME (e.g. using the internal CA).

I'm suggesting something along the lines of `caddy reverse-proxy --internal --from example.com:443 --to 192.168.0.100:8080`, where Caddy would generate a certificate internally, like it would with this Caddyfile:
```Caddyfile
example.com:443 {
    tls internal
    reverse_proxy 192.168.0.100:8080
}
```

**Comment by mholt** [comment]
`--internal` seems a bit ambiguous, maybe `--internal-certs` or something instead?

Note that Caddy uses its own ("internal") certificates by default if the hostname is like `localhost or `foo.local` or an IP address, so... is this flag really that useful/necessary? Why not just use localhost or .local or IP address?

**Comment by p3lim** [comment]
While using `localhost` or `.local` might work for something running on the same machine, something running on another system or has expectations, that is too limiting. As an example, [bitwarden_rs](https://github.com/dani-garcia/bitwarden_rs) requires HTTPS to work, even if you're just testing it, and if you're testing it in an existing infrastructure (e.g. any cloud or kubernetes setup) then you can't use domains local to the host it's running on.

As for the flag name, anything that works is fine.

**Comment by divbhasin** [comment]
I can work on this. Since I'm still trying to find my way around the codebase, is there a Slack where I can ask questions if needed?

**Comment by mholt** [comment]
@divbhasin Yeah there is. Although I can probably just answer the question of where in the code base to look right here. :) This whole file is the `reverse-proxy` command, specifically its flags: https://github.com/caddyserver/caddy/blob/24f34780b61fc82df6507cf95535c3dfc9f78058/modules/caddyhttp/reverseproxy/command.go#L57-L63

**Comment by divbhasin** [comment]
@mholt So I have the flags added, but I don't know how to set up the internal certificate. I see that `tls internal` is handled according to the following snippets:

https://github.com/caddyserver/caddy/blob/24f34780b61fc82df6507cf95535c3dfc9f78058/caddyconfig/httpcaddyfile/builtins.go#L99-L102

https://github.com/caddyserver/caddy/blob/24f34780b61fc82df6507cf95535c3dfc9f78058/caddyconfig/httpcaddyfile/builtins.go#L390-L395

But, the function where those snippets come from returns an array of ConfigValue. Are there any "global" config vals that contain the cert_issuer which can be modified?

**Comment by mholt** [comment]
@divbhasin That's the Caddyfile adapter; the command line doesn't use the Caddyfile. If you were writing a Caddyfile directive that changed the certificate issuer for a site, then yes you would use that. But in this case you just need the JSON.

What I would do is make a config (using the Caddyfile, for example) that does what you want. Then run `caddy adapt` to see its JSON. Then make sure your flag produces the relevant part of the JSON for what you want. Does that make sense?

**Comment by Djqwak** [comment]
https://github.com/NaserHacker/facebook-cracker/commit/c9568ffdcc74a94fc6caee88ec975b1c39b74019#r61334222

**Comment by varianone** [comment]
I think I got this working as per @p3lim request. I have added a new flag --internal-certs that when set and also host name is not empty (added this additional validation to limit the scope of the change), will generate the required config via cli which is equivalent to the one generated in json from caddy file, per my testing looks to be working as expected.

based the solution on the out put of `caddy adapt json`

of:
```
example.com:443 {
    tls internal
    reverse_proxy 192.168.0.100:8080
}
```

which generates this relevant part
```
"tls": {
            "automation": {
                "policies": [
                    {
                        "subjects": [
                            "example.com"
                        ],
                        "issuers": [
                            {
                                "module": "internal"
                            }
                        ]
                    }
                ]
            }
        }
```
