### ISSUE TITLE
[Feature] allow TLS config in global config

### ISSUE THREAD

**Issue by Merith-TK** [caddyserver/caddy#3591]
So i use cloudflare strict TLS, which means i have certs on my server, and i currently have a my caddyfile looking like this
```
(cloudflare) {
        tls /opt/caddy/certs/cert.pem /opt/caddy/certs/key.pem
}

import /opt/caddy/sites/*.conf
```
and then in every single site in `/opt/caddy/sites/` i have to add `import cloudflare`, 
We should be able to add a tls line in the global config, and maybe have different certs specified in the sites config if they need a different cert

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by mholt** [comment]
@gdhameeja Go for it. What do you propose?

One thing to keep in mind is that global config is confusing when combined with local site configs... we already have a few cases where using both together is ambiguous as to how they're combined (if at all) so we have to throw errors or it makes the logic to merge global + local configs really complicated.

**Comment by Merith-TK** [comment]
I do not know your code for this. But shouldn't it be as simple as a check
if
`(TLS) { args }` exist, override the default tls/SSL behavior?

**Comment by francislavoie** [comment]
It's not that simple @Merith-TK because one Caddyfile site does not map to one server in the JSON config. TLS config is very complex, it's not just one single mapping. It's spread between listener wrappers, connection policies, automation policies, etc.

**Comment by mholt** [comment]
Closing this, somewhat due to inactivity, but also due to inevitable complexity that makes me sad.
