### ISSUE TITLE
Is there a breaking changes list from caddy 1.0 to 2.x?

### ISSUE THREAD

**Issue by GF-Huang** [caddyserver/caddy#3592]
In other words, can I use caddy 1 Caddyfile directly for caddy 2?

**Comment by mholt** [comment]
Yes, Caddy 2 is a breaking change and complete rewrite, which is why it's called v2: https://semver.org/#spec-item-8

Here is an upgrade guide to help you out: https://caddyserver.com/docs/v2-upgrade
