### ISSUE TITLE
Hostname from env causes "tls internal" to be ignored

### ISSUE THREAD

**Issue by bananer** [caddyserver/caddy#3598]
Using the latest `caddy:2-alpine` Docker image.

I used to have a a fixed domain name in my Caddyfile with internal tls, this worked fine:
```
philip.mainframe {
    tls internal
    root * /var/www/philip
    file_server
}
```

I'm trying to have the root domain configurable, like this:
 
```
philip.{env.DOMAIN} {
    tls internal
    root * /var/www/philip
    file_server
}
```

I'm running Caddy with the env variable `DOMAIN` set to `mainframe`, expecting no changed behaviour.

However, SSL connection fails with error SSL_ERROR_INTERNAL_ERROR_ALERT

I can find this line in the caddy logs indicating it is trying to get a letsencrypt certificate instead of using internal tls:

    [ERROR] acme: error: 400 :: POST :: https://acme-staging-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "philip.mainframe": Domain name does not end with a valid public suffix (TLD), url:  (challenge=http-01 remaining=[])

I switched back and forward between the two configs and am very confident that it is the env placeholder causing caddy to go for letsencrypt instead of internal tls.

**Comment by bananer** [comment]
After digging through the v1 docs a bit more I found this working solution:

```
philip.{$DOMAIN} {
    tls internal
    root * /var/www/philip
    file_server
}
```

Not sure what the difference is here actually...

**Comment by francislavoie** [comment]
The problem is that `{env.*}` style environment variables are read at runtime (as in after the config is loaded and provisioned), while the `{$*}` style env are parsed and replaced at config adapt time, i.e. before Caddy starts running.

This is working as expected, glad you found the solution! :+1:
