### ISSUE TITLE
caddyhttp: support X-Forwarded-Host

### ISSUE THREAD

**Issue by kennethklee** [caddyserver/caddy#3599]
Noticed `X-Forwarded-Host` isn't used to match the Host.

I've got a caddy server behind a gateway that terminates SSL and forwards the Host header via the `X-Forwarded-Host` header.

The workaround I'm using looks like this:

```
@app {
  Header X-Forwarded-For app.example.com
}
reverse_proxy @app node1:80
```

Would be nice to just use `app.example.com` as an address.

**Comment by mholt** [comment]
Thanks for the feature request. I've just commented on the PR, where I guess the discussion will move to. In summary, I'm not convinced this is a good idea, just to save 1 line of config, especially in a way that is irreversable.

**Comment by kennethklee** [comment]
Closing this as per PR discussion.

Also noticed this is related #3262 since it's dealing with Forwarded headers.

Not sure if it's a good idea, but might I suggest opening an issue to create a guide on how to support forwarded headers like nginx -- https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
