### ISSUE TITLE
on plugin gone

### ISSUE THREAD

**Issue by hoshsadiq** [caddyserver/caddy#3604]
Hi, I noticed the `on` plugin has disappeared (implemented in #1864 and #1879), presuming since v2. Is there a reason for not implementing it in v2, and if there's no reason, would it be possible to ask for it as a feature request? Same use case, as previously, that is, ensure other applications are restarted properly when certs are renewed.

I did have a look at extending caddy, but I can't seem to find a good entry point for when such a plugin should be running.

EDIT: also previous feature request: #1698

**Comment by francislavoie** [comment]
The replacement in v2 is this plugin: https://github.com/abiosoft/caddy-exec

**Comment by hoshsadiq** [comment]
@francislavoie thanks! I found that one, however, I don't see a method to actually run that post certificate renewals. I did raise it as an issue, but on further inspection of the caddy source, I didn't see any way of running a command after the certificate renews.

**Comment by mholt** [comment]
@hoshsadiq Feel free to open a new issue to request that feature if you need it!
