### ISSUE TITLE
Caddy v2 GoDaddy module for DNS challenge

### ISSUE THREAD

**Issue by DOFfactory** [caddyserver/caddy#3605]
Would love to run Caddy with DNS challenge on GoDaddy. There used to be a module, but since v2 not anymore.

**Comment by francislavoie** [comment]
For the time being, you'll need to use this plugin, until one is made with the new DNS interface https://github.com/caddy-dns/lego-deprecated

**Comment by DOFfactory** [comment]
Just a quick follow-up, is there an easy way how to add this quickly to the existing caddy docker container?

**Comment by francislavoie** [comment]
Yes, read the docs here: https://hub.docker.com/_/caddy/ specifically the section "Adding custom Caddy modules"

**Comment by DOFfactory** [comment]
Thanks, I was checking them main documentation on https://caddyserver.com/docs

**Comment by francislavoie** [comment]
FYI https://caddyserver.com/docs/download#docker links to the docker hub page which has those docs
