### ISSUE TITLE
V2 how caddyfile reverse_proxy to JSON

### ISSUE THREAD

**Issue by Schr0dingerCat** [caddyserver/caddy#3609]
example 
        reverse_proxy /follow ohseemedia.com:443 {
                transport http {
                }
        }

how to transform a JSON????

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
