### ISSUE TITLE
V2: Can't access file in webdav

### ISSUE THREAD

**Issue by dhdgves** [caddyserver/caddy#3613]
I built a webdav server. I can log in to the service. But after I log in it, I can't access any file. ("Method Not Allowed")
My Caddyfile below:

{
        http_port 80
        https_port 90
        experimental_http3
        order webdav last
}
www.dasdasd.com
    {
    root * ./
    encode gzip
    webdav /dav {
    root ./
    prefix /dav
    }
    tls /mnt/sdb5/ssl/uhttpd.crt /mnt/sdb5/ssl/uhttpd.key
     basicauth {
       qewqw  JDJhJDEwJGlSb0RFdWdMZUlydThuMC55L2s4RS4uTk1DNk1XWG9SV1hzUW42SUlyc043dXZPVWE1YzZt
       }
    reverse_proxy / http://127.0.0.1:808

    }

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
