### ISSUE TITLE
Caddy 2.1 - reverse proxy issue - large response

### ISSUE THREAD

**Issue by nchagrass-bud** [caddyserver/caddy#3614]
### 1. Environment
**1a. Operating system and version**

alpine3.11

**1b. Caddy version (run caddy version or paste commit SHA)**
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=

**1c. Go version (if building Caddy from source; run go version)**
golang:1.14.5

### 2. Description
**2a. What happens (briefly explain what is wrong)**

Caddy reverse proxy to nginx with a php app delivering large json output

Calling directly the php service through nginx delivers the full output
Calling it through caddy respond with truncated output, a 200 response code and the following logs errors

**2b. Why it's a bug (if it's not obvious)**
Output is truncated

caddy logs: `"bytes_received":32768`
nginx logs: `"bytes_sent":38953`

**2c. Log output**
```
# caddy
2020/07/28 15:46:05.363	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "short write"}
{,"time":"2020-07-28T16:46:05+01:00","duration":388,"status":200,"request_id":"fa551a34-016d-4493-8073-4fc7491b7a9c","request_method":"GET","request_uri":"/api/v1/clients","remote_addr":"[::1]:55435","bytes_sent":0,"bytes_received":32768,"upstream_host":"my-php-service-behind-nginx","http_user_agent":"PostmanRuntime/7.25.0"}
```
```
# nginx
{"time":"2020-07-28T16:24:27+00:00","total_duration":0.182,"service_duration":0.183,"status":200,,"request_method":"GET","request_uri":"/api/v1/clients","request_version":"","remote_addr":"10.28.1.92","bytes_sent":38953,"bytes_received":250,"upstream_host":"unix:/sock/php-fpm.sock","http_user_agent":"PostmanRuntime/7.25.0"}
```

**2d. Workaround(s)**
None that I am aware of.
Maybe upgrade to latest version of Caddy? (I saw some changes on master)

**2e. Relevant links**

issue seems to be traced to this function [https://github.com/caddyserver/caddy/blob/v2.1.1/modules/caddyhttp/reverseproxy/reverseproxy.go#L607](https://github.com/caddyserver/caddy/blob/v2.1.1/modules/caddyhttp/reverseproxy/reverseproxy.go#L607)

**3. Tutorial (minimal steps to reproduce the bug)**
Install Caddy 2.1.1.
Run Caddy as a reverse proxy to a service that deliver a large json response.

**Comment by nchagrass-bud** [comment]
I seem to have gone to point of this buffer 
https://github.com/caddyserver/caddy/blob/d7dbf8552562edcfb53ab2024d8ceccc33823021/modules/caddyhttp/reverseproxy/streaming.go#L125

Should it extend while streaming?

**Comment by mholt** [comment]
Thanks for diving into the code! This will help a lot. :)

Not extend it -- that means it reads at most 32 KB into memory from the upstream while it writes it to downstream. If we make it larger, a high amount of load can deplete memory faster. (If we make it too small, it can slow down transmissions.)

That is somewhat suspicious though that it's exactly the size of one buffer that gets received.

Where does this log come from? `caddy logs: "bytes_received":32768`

"Short write" means that Caddy was unable to write the full body down to the client. (Maybe the client closed the connection?) I'm not sure what causes that as I've never seen it before. Is this reproducible to you? I would love it if you could drill down more and find out why it is happening.

**Comment by nchagrass-bud** [comment]
Thanks @mholt !

I have a custom caddy logger that replicates this output, 

I can try to provide a very large json payload + nginx + php code to reproduce easily (probably tomorrow)

Drilling down into the issue, I got my hands on this issue https://github.com/caddyserver/caddy/issues/1460 it looks like the code hasn't changed much since then.

Im now trying to change the content type from `application/json` to `text/event-stream` on the php response to see if it makes a difference

**Comment by mholt** [comment]
@nchagrass-bud FWIW our reverse proxy streaming logic is the same as in the Go standard library's ReverseProxy type.

Might be worth seeing if the issue can be reproduced with that too: https://golang.org/pkg/net/http/httputil/#ReverseProxy

**Comment by nchagrass-bud** [comment]
a recent experiment with a clear caddy (no custom modules) seems to not have this behaviour, I will close this and hopefully not re-open it ; )

Thanks for your time!
