### ISSUE TITLE
reverse_proxy "connect: no route to host" error

### ISSUE THREAD

**Issue by ministryofsillywalks** [caddyserver/caddy#3622]
I'm currently trying to migrate from v1 to v2.
I was using v1 as a bog standard reverse_proxy

Old caddyfile (changed the domain obviously due to privacy)
`sub.domain.de {
	proxy / 10.10.10.3:6789
}
`

New caddyfile
`sub.domain.de {
	reverse_proxy 10.10.10.3:6789
}
`

However it doesn't work and I get the following error:
`{"level":"error","ts":1596176339.3956597,"logger":"http.log.error","msg":"dial tcp 10.10.10.3:8989: connect: no route to host","request":{"method":"GET","uri":"/","proto":"HTTP/2.0","remote_addr":"84.167.87.99:56136","host":"sub.domain.de","headers":{"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"Te":["trailers"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"]},"tls":{"resumed":false,"version":772,"ciphersuite":4865,"proto":"h2","proto_mutual":true,"server_name":"sub.domain.de"}},"duration":3.085374592,"status":502,"err_id":"80hfh8yu6","err_trace":"reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:411)"}`

Ports are forwarded correctly and calling the following works fine:
`sub2.domain.de {
	respond "Hello, world!"
	}
`

So the issue seems to be the no route to host. The service I am calling at 10.10.10.3:6789 does operate on a different IP than the caddyserver (10.10.10.101) but it is the same subnet.
Calling 10.10.10.3:6789 directly gives me the requested service.
Both services are running in docker containers on the same machine but caddy got it's own IP as not to conflict with other port requirements.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

I think this is clearly a networking issue, I don't think it's a problem with Caddy specifically. With docker, it's typically easiest to use the container name instead of the IP. Try that instead?

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
I agree, this error is not one that is generated within Caddy -- it originates from the OS' networking stack. Make sure your new Caddy process has access to the same network that the old one did. It could be different from your v1 and from your shell, depending on many environmental/system factors. Our forum will be a good place to get further help.
