### ISSUE TITLE
Caddy exits with 'panic: runtime error: invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by lowercasename** [caddyserver/caddy#3627]
Caddy 2 has been running flawlessly on my server for a few months, serving about 10 websites. A few hours ago it exited with the following output (apologies for the screenshot, I don't have access to a text console at the moment):

![Screenshot 2020-08-02 at 19 43 17](https://user-images.githubusercontent.com/1748384/89129839-954c3980-d4f8-11ea-9f31-d993b1f18262.png)

For searching, the relevant output is:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2d8 pc=0x8be0e1]
goroutine 778762 [running]:
github.com/caddyserver/certmagic.(*Cache).updateOCSPStaples
[...]
github.com/caddyserver/certmagic.(*Cache).maintainAssets
[...]
github.com/caddyserver/certmagic.NewCache
[...]
caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The server is running Ubuntu 20.04, and I installed Caddy from the Ubuntu package.

I restarted the service and it's working absolutely fine now, so it seems like it was a once-off, but I'd like to prevent it from happening again!

**Comment by mholt** [comment]
Which version are you running? I think this was fixed a while ago. I'll need the exact version in order to look up the stack trace.

**Comment by mholt** [comment]
I just had a great idea, we should be printing the Caddy version in the logs (pictured above)!

**Comment by lowercasename** [comment]
Ah, good catch, caddy was being held back from updating for some reason! I was running 2.0.0! Now updated to 2.1.1.

**Comment by francislavoie** [comment]
Thanks for confirming, I'll close this for now, I figure @mholt doesn't need this issue open to remind him to add that extra log line 😅

**Comment by mholt** [comment]
Yeah, thanks, simple enough.

And the bug was fixed upstream back in May: https://github.com/caddyserver/certmagic/commit/5ed364019bb7bad1b8ccef4398f584c94923497c#diff-52c596c82713259b4527325d2a6c2846 - first by fixing the actual cause of the panic, then adding `recover()` everywhere so that even if there are other crashes it won't cause the server to go down. So this can't happen again.
