### ISSUE TITLE
Support h2c URI scheme for reverse proxy upstream address

### ISSUE THREAD

**Issue by otbutz** [caddyserver/caddy#3628]
caddy 2.1.0 added support for HTTP2 cleartext connections but the syntax is a bit cumbersome:

```
https://grpc-api.example.com {
    reverse_proxy localhost:8080 {
        transport http {
            versions h2c 2
        }
    }
}
```

It would be nice if we could use `h2c://` instead:
```
https://grpc-api.example.com {
    reverse_proxy h2c://localhost:8080
}
```
Traefik is using the same syntax: https://docs.traefik.io/user-guides/grpc/

**Comment by francislavoie** [comment]
This looked easy so I took a quick shot at it with #3629. Since `h2c` is still considered an experimental feature, this might not be accepted, FYI.

**Comment by otbutz** [comment]
@mholt any objections? This would make the Caddyfile a lot more readable when using caddy as a reverseproxy for GRPC services.
