### ISSUE TITLE
Synlinks is not working in Caddy V2

### ISSUE THREAD

**Issue by milewski** [caddyserver/caddy#3631]
Hi I have the following configuration:

```
:80 {

    root * /srv/public
    file_server

    php_fastcgi php:9000

}
```

acessing `http://docker.localhost/somefile.txt` works

however acessing: `http://docker.localhost/somefolder/somefile.txt` where `somefolder` is a synlink doesnt work..

confirmed that it does work in V1 without any change

**Comment by francislavoie** [comment]
This is fixed by https://github.com/caddyserver/caddy/pull/3587 which is slated to be released with Caddy v2.2

For now, you can build from master or use one of the build artifacts from https://github.com/caddyserver/caddy/actions/runs/194178338 until v2.2 is released.

Closing as a duplicate.

**Comment by milewski** [comment]
Is there any ETA for the release of v2.2? that is the only issue is preventing me to use caddy to in prod since the v2 release... I can't change my ci/build system right now to compile this from source

**Comment by francislavoie** [comment]
We're hoping for later this week, but it depends on a few factors.

Can you not use v2.2.0-rc.1? It has the fix.

https://github.com/caddyserver/caddy/releases/tag/v2.2.0-rc.1

**Comment by milewski** [comment]
Uhm, I did not find the `-rc` on docker hub https://hub.docker.com/_/caddy?tab=tags&page=1 has it been published there yet?

I know how easy it is to build it from the source I have built it locally and tested it already, the problem doing this on my prod env is that I have to go through a process to get approval to 1 week then get approval again to revert it back... So I'd rather wait is available on the docker hub (even as RC is fine)

**Comment by francislavoie** [comment]
Ah, yeah we tend to not publish beta/rc builds to Docker/package managers.

So yeah, probably just a week or two away from 2.2 🙂
