### ISSUE TITLE
Allow `file_server browse` templates to use the same functions as `templates`

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#3637]
See the discussion here: https://caddy.community/t/v2-http-handlers-templates-functions-in-file-server-browse-template/9214

The [`file_server` directive](https://caddyserver.com/docs/caddyfile/directives/file_server) has a `browse` option which enables a directory index to be served when a directory is requested. By default, this index is rendered using a template which can be [found in the code](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/fileserver/browsetpl.go). The default can be overridden with a template provided by the user.

It seems that the `file_server browse` template doesn't use the same code paths as the [`templates` directive](https://caddyserver.com/docs/caddyfile/directives/templates), which means that the [functions documented here](https://caddyserver.com/docs/modules/http.handlers.templates) cannot also be used.

The code should be refactored such that the logic for the templates is shared between these two such that all the template functions Caddy provides works both for the general templates _and_ for the file server directory index.

**Comment by divbhasin** [comment]
Hi, new contributor here 👋.  I can work on this issue.

**Comment by francislavoie** [comment]
Cool! Go for it @divbhasin 😄

**Comment by divbhasin** [comment]
Here is what I am thinking: I need to make the `executeTemplateInBuffer` function in `templates/tplcontext.go` accessible to fileserver browse. This is because that function attaches the other functions like `httpInclude` to a template, and returns a template that has been executed on a buffer.

Am I on the right track @francislavoie?

**Comment by francislavoie** [comment]
Yeah, that sounds about right. Maybe the `templateContext` should be shared to allow `browse` to use it.

**Comment by vojkuv** [comment]
``https://www.facebook.com/tom.zdrali/about?section=relationship&lst=100001658457086%3A100036018322527%3A1598790302 #3691

**Comment by vojkuv** [comment]
[](https://www.facebook.com/tom.zdrali/about?section=relationship&lst=100001658457086%3A100036018322527%3A1598790302[](url))

**Comment by mholt** [comment]
Hmm, this is tricky though because in order to support of all of `templates` functions you'd need to import the `modules/caddyhttp/templates` package and use its `Templates` type, because `templateContext` depends on it.

This will need more consideration/discussion; I think there'll need to be some sort of new function or method that is exported to wrap all the unexported logic needed for this, without having to create a whole HTTP handler or something.

**Comment by divbhasin** [comment]
@mholt yeah I have been struggling with how to incorporate the Templates type into browse.

**Comment by 0xbzho** [comment]
Until this is resolved, what's the best workaround? A fork? A Caddy module? Thanks.

**Comment by princemaple** [comment]
@0xbzho I think this one is just waiting for a proper PR. If you have the capability to make a working fork or a functionally equivalent module, maybe just send a PR.

**Comment by francislavoie** [comment]
There's an open but incomplete PR here: https://github.com/caddyserver/caddy/pull/3982

If you wish to help finish it, feel free to contribute.

**Comment by princemaple** [comment]
FYI all, #3982 (the PR) is closed due to inactivity.

**Comment by xdu31** [comment]
Hi @francislavoie and @princemaple , I can help on this, I actually already have patches locally. If this feature is still needed, I can raise a PR in a few days. I have been working with Caddy in my recent project.

**Comment by francislavoie** [comment]
Yes, PRs welcome 👍

**Comment by xdu31** [comment]
> Yes, PRs welcome 👍

Going to provide the detailed test cases done on the PR and the test caddyfile soon.

**Comment by xdu31** [comment]
> > Yes, PRs welcome 👍
> 
> Hi @francislavoie, going to provide the detailed test cases done on the PR and the test caddyfile soon.

@francislavoie @mholt https://github.com/caddyserver/caddy/pull/4093#issuecomment-812679843

**Comment by xdu31** [comment]
> > > Yes, PRs welcome 👍
> > 
> > 
> > Hi @francislavoie, going to provide the detailed test cases done on the PR and the test caddyfile soon.
> 
> @francislavoie @mholt [#4093 (comment)](https://github.com/caddyserver/caddy/pull/4093#issuecomment-812679843)

@francislavoie @mholt @princemaple https://github.com/caddyserver/caddy/pull/4093#issuecomment-812799770

**Comment by princemaple** [comment]
I'm not a maintainer :) Just a random guy patiently waiting on this feature.

**Comment by xdu31** [comment]
> I'm not a maintainer :) Just a random guy patiently waiting on this feature.

@mholt @francislavoie I tested with both html & json modes, also included a test on the templates plugin.
