### ISSUE TITLE
Question about snippets & import

### ISSUE THREAD

**Issue by EngelPika32** [caddyserver/caddy#3645]
It took me a while to figure out what goes wrong with my snippets. I first thought I can't use everything within a snippet. 
But the result is: `(snippet){}` does not work. Only `(snippet) {}` (with space) works - Why?

```
# Full-Caddyfile
# Requires Caddy 2.1+
{
    http_port 8080
}

(aaa){
    @noV1 not path /{args.0}/*
    redir @noV1 /{args.0}{path}
}

localhost:7100 {
    import aaa v1
    try_files {path} {path}.html
    file_server
}

```
Using `caddy run` results in:
```
run: adapting config using caddyfile: Caddyfile:12 - Error during parsing: File to import not found: aaa
```

Which leads me to some more questions:
- How does caddy handle the incorrect snippet internally? Is it loaded; Is it removed? (Should I worry when I have some unused incorrect snippets.)
- Do I have to care about indentation? (tabs/spaces)
- Anything else I should take care of when using snippets/import?
- Can I use imports within snippets? (I guess so. But I'm adding this here for safety :) )

Docs as reference: [Concepts#snippets](https://caddyserver.com/docs/caddyfile/concepts#snippets).

**Comment by mholt** [comment]
It's because white space is significant in the Caddyfile: https://caddyserver.com/docs/caddyfile/concepts#tokens-and-quotes

> The Caddyfile is lexed into tokens before being parsed. Whitespace is significant in the Caddyfile, because tokens are separated by whitespace.

So the space is necessary :)

Also we like clean-looking, tidy config files.

**Comment by EngelPika32** [comment]
Ah, thanks. Didn't know that this applies here too. (Because it's so common to omit out space between different brackets.)

> Also we like clean-looking, tidy config files.

I guess you say that because the snippet is so unnecessary in the example^ xD 
Thought it would be better to trim down the problem as much as I can. Instead of posting my actual Caddyfile(s). 

I only have things in snippets which I use multiple times or where the usage of arguments cleans up the file. 

To not open a new issue again: 
Is it possible to set the path for an import statement dynamically?
I would like to do the following (which isn't working):
```
(loader){
  import {args.0}/siteName
}

import loader path/to/site
```
This would help when switching between development and production paths.
But I can write multiple 'loader' with different paths and switch between them too.

**Comment by francislavoie** [comment]
I would suggest using environment variables for that purpose instead. You can use the `--envfile` argument to `caddy run` and put the paths you need in a `.env` file.

There's two env variable syntaxes in Caddy. `{$VAR}` and `{env.VAR}`. The first is replaced before the Caddyfile is parsed, the second is replaced at runtime. You'll want the first syntax.

**Comment by EngelPika32** [comment]
Alright, will do :)

Guess I will move my next question then. As it's still not working with the snippets. (some work, some don't.) 
However, if I use files then it works. (I don't even have to remove the snippets.)

**Comment by mholt** [comment]
We removed the issue template here because nobody used it. Now we only reply with a template if it's needed.
