### ISSUE TITLE
Cannot define named matchers inside of route blocks

### ISSUE THREAD

**Issue by lolPants** [caddyserver/caddy#3646]
## Context
I created a cors snippet that I want to be conditionally applied based on route matchers, so I can re-use the same snippet and not have to copy-paste and tweak the individual header matchers. It works when used in a top-level host block, but not when inside a `route` block.

I am unsure if this is a bug or merely a limitation with the syntax. If it is the latter, then some pointers on possible workarounds would be appreciated.

## Error
`parsing caddyfile tokens for 'route': Caddyfile:2 - Error during parsing: unrecognized directive: @options`

## My Caddyfile
```
(cors) {
  @options {
    method OPTIONS
  }

  header @options Access-Control-Allow-Methods GET

  header * {
    Access-Control-Allow-Origin {header.origin}
    Vary Origin
  }
}

localhost {
  route /api/* {
    # The error happens on the next line
    import cors
    respond "api" 200
  }

  respond * "hello" 200
}
```

**Comment by lolPants** [comment]
Upon further inspection, this seems to have nothing to do with snippets. When manually expanding the snippet contents into the route block the same error is applied. It looks like you cannot define named matchers inside of route blocks altogether.

**Comment by mholt** [comment]
Actually you can now, as of yesterday.

(Am mobile so don't have link handy. But it's a recent commit, should be easy to find.)

**Comment by lolPants** [comment]
Oh awesome! Sorry for the dupe 😄
