### ISSUE TITLE
Update DataDog ZSTD to 1.4.5

### ISSUE THREAD

**Issue by tetragir** [caddyserver/caddy#3649]
Depending on zstd with version 1.4.1 breaks the build on FreeBSD if the user had zstd installed (more on this in this bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248547)
Would it be possible to depend on zstd 1.4.5 (the newset release)?
Thank you!

**Comment by mholt** [comment]
Hmm, I'm not sure I understand entirely (since Caddy's zstd library is pure embedded Go with no external dependencies): https://github.com/klauspost/compress/tree/master/zstd

You'll probably need to take this issue upstream to @klauspost  as Caddy has no C dependencies.

**Comment by francislavoie** [comment]
`DataDog/zstd` is an indirect dependency that comes from `smallstep/nosql` -> `dgraph-io/badger`.

```
$ go mod why github.com/DataDog/zstd
# github.com/DataDog/zstd
github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver
github.com/smallstep/nosql
github.com/smallstep/nosql/badger/v2
github.com/dgraph-io/badger/v2
github.com/dgraph-io/badger/v2/y
github.com/DataDog/zstd
```

It would need to be updated upstream. Caddy doesn't use that library directly.

**Comment by tetragir** [comment]
Thank you for the clarification!

**Comment by francislavoie** [comment]
Hmm... Is Caddy not being built with `CGO_ENABLED=0`? Shouldn't it prevent any bindings to C code to happen if that's specified?

**Comment by francislavoie** [comment]
Also FWIW, badger has an open PR to remove the dependency on `DataDog/zstd`: https://github.com/dgraph-io/badger/pull/1383
