### ISSUE TITLE
Feature Request: Client TLS authentication, log CN of client certificate. 

### ISSUE THREAD

**Issue by utilitynerd** [caddyserver/caddy#3650]
When using client TLS authentication, I would like to be able to log the Common Name of the client certificate used.

**Comment by mholt** [comment]
You're in luck, I literally just merged this two days ago and it'll be released this week, probably: https://github.com/caddyserver/caddy/commit/65a09524c3926547ed0b8515da211173df4fe379

**Comment by utilitynerd** [comment]
Fantastic!
