### ISSUE TITLE
Get Certificate without domain

### ISSUE THREAD

**Issue by dr-mcgillicuddy** [caddyserver/caddy#3652]
Caddy doesn’t appear to secure itself unless using a specific domain in the Caddyfile. (E.g. ssl doesn’t get enabled if you leave `:80` as the first line of your caddyfile)

Is it possible to still automate an SSL configuration when running with only an IP address?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Unfortunately, that's not possible. A domain name is necessary to get a valid TLS certificate issued.

See the documentation: https://caddyserver.com/docs/automatic-https

Also, by convention, HTTPS is on port 443. I'd highly recommend not trying to serve HTTPS on port 80. It's weird and confusing.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
