### ISSUE TITLE
qtls via quic-go breaks when building with Go 1.15

### ISSUE THREAD

**Issue by jwkohnen** [caddyserver/caddy#3654]
Currently Caddy (no Caddyfile, just `caddy version`) terminates with a panic at startup time if built with Go 1.15.  The cause is a [check in quic-go that compares](https://github.com/lucas-clemente/quic-go/blob/d7c2169c55bd0ab0ce4724bcab270a6ec902534f/internal/handshake/unsafe.go#L18-L44) some TLS types from the standard library with modified (for quic) TLS types from https://github.com/marten-seemann/qtls.

Caddy can't directly do anything about this. A bunch of other software that link in quic is broken with Go 1.15. As of now lucas-clemente/quic-go/issues/2614 seems to be the best place to track progress of this issue. 

```
jb@ibuti:~/git/gh/caddyserver/caddy/cmd/caddy$ go version
go version go1.15 linux/amd64
jb@ibuti:~/git/gh/caddyserver/caddy/cmd/caddy$ git describe 
v2.2.0-rc.1-1-ge385be92
jb@ibuti:~/git/gh/caddyserver/caddy/cmd/caddy$ go install
jb@ibuti:~/git/gh/caddyserver/caddy/cmd/caddy$ caddy version
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.2()
	/home/jb/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.3/internal/handshake/unsafe.go:26 +0x205```

**Comment by Mohammed90** [comment]
Thanks for creating the issue. It's been known since #3642.
