### ISSUE TITLE
reverse_proxy domain/data to datadomain/  issues

### ISSUE THREAD

**Issue by Mon-ius** [caddyserver/caddy#3659]
I have two sites: 

- exampledomain.com 
- datadomain.com

**exampledomain.com**  run caddy v2 has such config exampledomain.com/data point to datadomain.com.

**datadomain.com** also run caddy v2 with file_server config. There are also some folders called dataFolder_A, dataFolder_B, etc.

When click into datadomain.com and select dataFolder_A. You will enter datadomain.com/dataFolder_A to access some files on it.

However, I would like to use `exampledomain.com/data`, `exampledomain.com/data/dataFolder_A`, `exampledomain.com/data/dataFolder_B`   to access  `datadomain.com`, `datadomain.com/dataFolder_A`, `datadomain.com/dataFolder_B`, etc.

with config 

```
exampledomain.com{
  handle_path  /data {
      reverse_proxy datadomain.com
  }
}
```
or

```
exampledomain.com/data {
  uri strip_prefix /data
  reverse_proxy datadomain.com
}
```

I can only access the exampledomain.com/data to  the root path for datadomain.com. When entering exampledomain.com/data/dataFolder_A. It failed and turn back to exampledomain.com/dataFolder_A instead of exampledomain.com/data/dataFolder_A.

I've tried all these thress solutions for it: None of them works.

- https://github.com/caddyserver/caddy/issues/2813
- https://github.com/caddyserver/caddy/issues/3266
- https://github.com/caddyserver/caddy/pull/3281

**Comment by mholt** [comment]
Thanks for your question, and we're glad that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by Mon-ius** [comment]
I didn't find such feature on caddy v2. Like this config below for Nginx:
```

	location ~ ^/data(.*)$ {
    		proxy_pass http://datadomain.com/$1;  
	}
```

**Comment by francislavoie** [comment]
Caddy v2 can absolutely do this. Please make a post on the forums as requested.

At a glance, you seem to have missed that path matching is exact-match in Caddy v2 https://caddyserver.com/docs/caddyfile/matchers#path-matchers

**Comment by mholt** [comment]
Following up, this seems to be answered in the forums: https://caddy.community/t/reverse-proxy-domain-data-to-datadomain-issues/9484/2

**Comment by Mon-ius** [comment]
Got solution!

```
exampledomain.com {
	handle_path /data* {
		reverse_proxy datadomain.com
	}
}
```
