### ISSUE TITLE
remote error: tls: unknown certificate / TLS handshake error: EOF

### ISSUE THREAD

**Issue by Mischosch** [caddyserver/caddy#3660]
Hi there,

somehow Caddy `v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=` broke my internal tls setup for testing.

OS is OSX Mojave 10.14.6

Caddyfile before:
```
munki.local:8081 {
    root * /Users/Shared/munki_repo
    encode gzip
    tls internal
    log {
        output file /usr/local/var/log/caddy/munki.log {
            roll_size 2
            roll_keep 5
        }
        format json
        level info
    }
    file_server / browse
}
```

worked fine for Caddy v2.0.0

changed now some settings to get back running on http

Caddyfile:
```
{
    http_port 8080
    https_port 8081
    local_certs
    auto_https disable_redirects
}

munki.local:8080 {
    root * /Users/Shared/munki_repo
    encode gzip
    tls internal
    log {
        output file /usr/local/var/log/caddy/munki.log {
            roll_size 2
            roll_keep 5
        }
        format json
        level info
    }
    file_server / browse
}
```

stderr output
```
bash-3.2$ sudo caddy run --config /usr/local/etc/Caddyfile
2020/08/17 00:18:15.363	INFO	using provided configuration	{"config_file": "/usr/local/etc/Caddyfile", "config_adapter": ""}
2020/08/17 00:18:15.366	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["[::1]:2019", "127.0.0.1:2019", "localhost:2019"]}
2020/08/17 02:18:15 [INFO][cache:0xc000755200] Started certificate maintenance routine
2020/08/17 00:18:15.374	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 8081}
2020/08/17 00:18:15.374	INFO	tls	setting internal issuer for automation policy that has only internal subjects but no issuer configured	{"subjects": ["munki.local"]}
2020/08/17 00:18:15.483	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
2020/08/17 00:18:15.485	INFO	tls	cleaned up storage units
2020/08/17 00:18:15.485	INFO	http	enabling automatic TLS certificate management	{"domains": ["munki.local"]}
2020/08/17 02:18:15 [WARNING] Stapling OCSP: no OCSP stapling for [munki.local]: no OCSP server specified in certificate
2020/08/17 00:18:15.485	INFO	autosaved config	{"file": "/Users/foo/Library/Application Support/Caddy/autosave.json"}
2020/08/17 00:18:15.485	INFO	serving initial configuration
```

If I change to munki.local:8080 { ... } I get following errors inside stderr:
```
2020/08/17 02:20:04 http: TLS handshake error from 127.0.0.1:58909: remote error: tls: unknown certificate
2020/08/17 02:20:13 http: TLS handshake error from 127.0.0.1:58911: EOF
```
First one is Chromium, second Safari.

Found this issue: https://github.com/caddyserver/caddy/issues/3571 - this looks similar to my problem. The intermediate cert is not accepted and in Safari tells me, the cert itself does not comply with standards. 

Chromium says: 
```
NET::ERR_CERT_INVALID
Subject:

Issuer: Caddy Local Authority - ECC Intermediate

Expires on: 17.08.2020

Current date: 17.08.2020
```

Is there anything I could provide you to better understand my problem (fixing it would be great, too ;))?

Regards

**Comment by mholt** [comment]
Can you try the latest build from master? (CI artifacts are available too.) v2.1.1 doesn't have the fix. Make sure to delete the existing local CA certs in your `<data folder>/pki/authorities/local`.

**Comment by Mischosch** [comment]
Tried with `v2.2.0-rc.1` and the attached binary there (not sure where to find CI artifacts).

This version does not work, too. Removed everything inside `/pki/authorities/local` - files got created after running new caddy binary. I removed cert inside my keychain, too, and called the `trust` command again.

Chrome says: `NET::ERR_CERT_AUTHORITY_INVALID`
stderr/output says: `2020/08/18 01:57:34 http: TLS handshake error from 127.0.0.1:65525: remote error: tls: unknown certificate`
Safari tries to load but never finishes.

Is the fix already included inside that release? Code changes in the last 4 commits inside master does not look like connected to my problem - but I could be wrong on that.

**Comment by mholt** [comment]
You usually have to restart your browsers before they'll pick up the new trust settings.

**Comment by Mischosch** [comment]
Restarting Browser does not change the behaviour. Tried Firefox, too: Error code: `SEC_ERROR_BAD_SIGNATURE`

```
02:22:40 http: TLS handshake error from 127.0.0.1:55518: remote error: tls: unknown certificate
2020/08/18 02:22:48 http: TLS handshake error from 127.0.0.1:55524: remote error: tls: unknown certificate
2020/08/18 02:23:10 http: TLS handshake error from 127.0.0.1:55555: remote error: tls: bad certificate
2020/08/18 02:23:21 http: TLS handshake error from 127.0.0.1:55559: remote error: tls: unknown certificate
2020/08/18 02:24:34 http: TLS handshake error from 127.0.0.1:55584: remote error: tls: unknown certificate
```

**Comment by mholt** [comment]
What does `curl -vvv` say?

**Comment by Mischosch** [comment]
Was switching back from 2.0 to latest beta release to get debug info of curl - and it worked, like it should. In Chrome/Safari, too. Not sure, why it worked now. Did exactly the same things I tried before (and didn't worked - just started getting used to all the steps). To be honest, I have no idea if I missed something the first try, or why it worked now.

Sorry for that :/ - seems like the new beta release does work again for local ssl and the "bugfix" /refactor is fine for my setup, too. Thanks a lot.


Caddy v2 is quite challenging compared to Caddy v1. Quite some work to get a local dev environment based on a Caddyfile over to Caddy v2. Documentation and Google search results are often, let's say, misleading. And using the Caddyfile feels like: I should start using the API or that json settings stuff instead. But working local SSL certs in v2.0 was a huge +++. I'm really loving that - it never worked for me with Caddy v1 and mkcert foo was not an easy go, too.

But I had struggles with Caddy v2 PHP setup debugging. A curl request by PHP to external server broke everything. Removing `https` from the url to send the request to made it work again. I missed the fpm error log instructions (known from nginx) and caddy log did not tell anything of interest. Quite some time needed, to isolate the source of not error output anywhere.


Thanks for your work! Much appreciated. I really do love Caddy for it's easy to use appeal. Hope we can get back to that a little bit again - on top of that new tech base on steriods now. :)

**Comment by mholt** [comment]
This issue is very common among browsers, and I can't explain it. I keep telling people browsers are just not good for testing. Use `curl` instead.

Anyway, thanks for the great feedback!

> Caddy v2 is quite challenging compared to Caddy v1. 

Yep, our biggest mistake in v1 was pretending that serving the Web is easy. It's not. Caddy 2 is a professional's tool, and it can take time and training to master.

> Documentation and Google search results are often, let's say, misleading. 

I'm not sure there's much we can do about this. I don't really know what "misleading" means anyway. We're certainly not misleading anyone, at least as far as I know. Our [docs](https://caddyserver.com/docs/) are accurate for the most part -- if you notice anything _misleading_ in them please report it on our website repo.

> And using the Caddyfile feels like: I should start using the API or that json settings stuff instead.

I honestly prefer JSON + API, it's way more powerful and expressive. I only use and recommend the Caddyfile for really simple stuff (either dev or prod, but in either case: simple stuff only).

> But working local SSL certs in v2.0 was a huge +++. I'm really loving that - it never worked for me with Caddy v1 and mkcert foo was not an easy go, too.

Yes, this was a great (and hard) feature! We're still fine-tuning it, but there's only so much we can do against system restrictions and client... bugs... I guess.

> But I had struggles with Caddy v2 PHP setup debugging. A curl request by PHP to external server broke everything. Removing https from the url to send the request to made it work again. I missed the fpm error log instructions (known from nginx) and caddy log did not tell anything of interest. Quite some time needed, to isolate the source of not error output anywhere.

Hm, if you can drum up more details about this we can help understand what happened. It's _probably_ not a bug since I know most PHP deployments work fine from what I hear. But am willing to look into it if you provide the full (unredacted) logs and full (unredacted) config in a new issue. Or maybe forum post, if you pose it more as a question instead of a bug.

> Thanks for your work! Much appreciated. I really do love Caddy for it's easy to use appeal. Hope we can get back to that a little bit again - on top of that new tech base on steriods now. :)

Thanks for the kind words! Caddy 2's goal will never be "easy to use" in terms of "not having to read documentation" -- it's a powerful tool, period -- but it can only get better at least, right?

**Comment by AlexBasile123** [comment]
My 2 cents. This problem can usually be resolved by granting permission to the backend from your browser.
Let's say your website url is "www.mywebsite.com" and your frontend calls your backend domain "api.mywebsite.com", then call "api.mywebsite.com" from your browser. The browser will warn you that it's untrusted. Go through the safety links to proceed; thereby telling your browser to trust the backend domain. Then call your frontend via browser "www.mywebsite.com". Should resolve the issue!

**Comment by JR59588** [comment]
ERRO 03e Server TLS handshake failed in 1.709235ms with error remote error: tls: bad certificate server=PeerServer remoteaddress=192.168.32.1:41068

**Comment by francislavoie** [comment]
@JR59588 please don't post on long-since-closed issues. If you need help, open a topic on the forums, and fill out the help topic template. https://caddy.community
