### ISSUE TITLE
X-Forwarded-For does not contain the IP of the original caller

### ISSUE THREAD

**Issue by wsw70** [caddyserver/caddy#3661]
_Note: this was initially a [question posted in the Caddy community](https://caddy.community/t/how-to-set-x-forwarded-for-so-that-it-contains-the-ip-of-the-original-caller/9459) but the more I test, the less I see the right IP address_

### 1. Caddy version (`caddy version`): 
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=

### 2. How I run Caddy:

Standard docker image

#### a. System environment:

Docker host: Ubuntu 18.04

#### d. My complete Caddyfile or JSON config:

```
{
	admin 0.0.0.0:2015
	email xxx@xxx.xxx
	# acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
}

https://nextcloud.mydomain.eu {
	reverse_proxy nextcloud:80
}
```

### 3. The problem I'm having:

**Summary:** it seems that the wrong `X-Forwarded-For` header is set when reverse-proxyfing.

**Details:** I run docker on `192.168.10.2`. One of the containers is the official caddy image (it gets the `172.19.0.31` IP) and another one is Nextcloud (`172.19.0.23`).

The logs of Nexcloud show all incoming connections from `172.19.0.31`, despite using the  `X-Forwarded-For` header.

To check at the source, I logged into the Nextcloud container and ran a `tcpdump` from there to see the details of the incoming HTTP packets. What I see is

    X-Forwarded-For: 172.19.0.1\r\n

`172.19.0.1` is the docker bridge gateway, that is `192.168.10.2` as seen from the other side of the bridge.

Anyway, this means that `X-Forwarded-For` does not contain the IP of the host that made the call (which would be in that case a host on `192.168.10.0/24`. What Nexcloud reports caddy as the caller is another thing - but the IP I am looking for is not in the  `X-Forwarded-For` header anyway.

Now, the Caddy reverse proxy docs states that:

> By default, Caddy passes thru incoming headers to the backend—including the  `Host`  header—without modifications, with two exceptions:
> 
> * It adds or augments the [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header field.
> * It sets the [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header field.

Note that manually setting `X-Forwarded-For` in the Caddyfile **does propagate** the right IP (the one set). It looks like the issue (if there is one) is that caddy does not set it automatically.

**Comment by francislavoie** [comment]
The code where Caddy does this is here:

https://github.com/caddyserver/caddy/blob/e385be922569c07a0471a6798d4aeaf972facb5b/modules/caddyhttp/reverseproxy/reverseproxy.go#L473-L481

Caddy just sets the header to whatever RemoteAddr it sees from the incoming request. If the request doesn't have the right client IP, then it's definitely an issue downstream, either at the client or somewhere in between.

Have you enabled the `debug` global option on Caddy and checked the logs to see what it receives?

**Comment by mholt** [comment]
Is there a way to reproduce this without Docker?

**Comment by francislavoie** [comment]
I'm pretty sure you're running into this (shoutout to @Mohammed90 for pointing that out to me): https://github.com/moby/moby/issues/25526

I think you're running your Docker container in Docker Swarm mode. Can you confirm?

**Comment by wsw70** [comment]
@francislavoie : no, I am not in Swarm mode:
```
~ # docker info --format '{{.Swarm.LocalNodeState}}'
inactive
```

I did the test mentioned in https://github.com/moby/moby/issues/25526#issuecomment-582392484 and I get the **correct** `X-Forwarded-For` header.

I ran a `tcpdump` in the Nextcloud container and, again, the wrong one is received:

```
    caddy.srv.60374 > 5daf1cc002c4.80: Flags [P.], cksum 0x5a54 (incorrect -> 0x93be), seq 2338:2803, ack 204733, win 2815, options [nop,nop,TS val 2135925762 ecr 1715510075], length 465: HTTP, length: 465
        GET /login HTTP/1.1
        Host: nextcloud.xxx.eu
        User-Agent: python-requests/2.23.0
        Accept: */*
        Accept-Encoding: gzip, deflate
        Cookie: oc..y=5..ec; oc_sessionPassphrase=3D.....Wrc; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true
        X-Forwarded-For: 172.19.0.1
        X-Forwarded-Proto: https
```

I got into another, unrelated container and did another  `tcpdump`. Again, I get the **correct** `X-Forwarded-For` header.

I am at loss - it seems that the only container where the header is wrong is the Nextcloud one - but I verify at the packet level so I do not understand what can modify this value.

I will close the bug for now and look further, thanks for all the help.

**Comment by wsw70** [comment]
I believe I was wrong. This must be a problem with Nextcloud.

I spun up a `whoami` container and the header is correct. In another container that logs the client IP the IP is correct as well.

@mholt @francislavoie  **Apologies for the noise** - I thought that the `tcpdump` test was enough to confirm that the IP is incorrect but I will deep dive into the Nextcloud container to understand where the problem is.
