### ISSUE TITLE
[Feat]: TLS 1.3 0-RTT

### ISSUE THREAD

**Issue by polarathene** [caddyserver/caddy#3663]
Unclear if this belongs as a request to Caddy or one of it's packages. Possibly relies on Golang itself? ([they seem to mention a lack of support for 0-RTT](https://golang.org/src/crypto/tls/handshake_server_tls13.go))

There are [some concerns](https://www.ssl.com/faqs/security-concerns-0-rtt-mode/) with using 0-RTT, but as long as it's opt-in and the documentation cautions the reader about enabling it, it should be fine.

**Comment by francislavoie** [comment]
Some more background on the topic: https://github.com/cloudflare/tls-tris/issues/139 (i.e. the original TLS 1.3 implementation before it was included in Go stdlib)

I don't think 0-RTT in Caddy will happen unless `crypto/tls` adds support, and even then, I don't think we would enable it by default, especially because of the security implications.

**Comment by polarathene** [comment]
> I don't think we would enable it by default, especially because of the security implications.

It's definitely not meant to be something you enable by default. It should only be used with idempotent requests.

> I don't think 0-RTT in Caddy will happen unless `crypto/tls` adds support

Fair enough. So for cases where 0-RTT is desirable, an alternative to Caddy would be required? I guess a proxy layer with 0-RTT may not make sense? (Caddy wouldn't be handling TLS then right?)

---

Should I leave this open, or close as it due to upstream dependency?

**Comment by daiaji** [comment]
That sounds terrible.

**Comment by polarathene** [comment]
@daiaji could you be a little more specific?

**Comment by daiaji** [comment]
@polarathene  It seems that the lack of 0-RTT support for golang has been around for quite a while, maybe this will last longer?

**Comment by polarathene** [comment]
> maybe this will last longer?

Someone has to implement it, and likely a strict review process. 

I don't know how much work or skill is required to implement it. It would likely be sponsored/funded by some company eventually, but it would need to be seen as worthwhile enough to prioritize which may restrict that to larger organizations such as enterprises. 

However enterprises are often slower to adopt newer technology, often happy to pay for proprietary solutions or other alternatives that resolve their requirements. If it's for CDN usage, many CDNs already off it, which leaves APIs, that could alternatively be served by say nginx or the service itself handling the TLS.

Best we can do is wait until someone who leverages Go for TLS wants 0-RTT bad enough for their usecase and has the skills to contribute it. It's not exactly a deal breaker, just a nice to have.

Another area Go lacks with TLS is a session ID cache for resumption, there's only session ticket support which is why I assume Caddy is limited on that front as well. That's [presently a problem for Safari and iOS apps apparently](https://github.com/golang/go/issues/25228), or at least at present don't support session tickets for resumption, among a few other projects like some FTP software. That's more chicken and egg situation, in that Go could add the support, or Apple could update their software instead to use session tickets.

**Comment by daiaji** [comment]
@polarathene In fact, I suspect that because TCP itself has enough RTTS and TCP is too old, they don't have enough motivation to complete TLS 1.30-rtt for TCP.

**Comment by mholt** [comment]
0-RTT is an optional feature of TLS, and as such needs to be done by the TLS implementation, so this'll need to be implemented by the crypto/tls package in the standard lib.

There's already an open issue for it upstream, and we can't do anything until that is solved; so I'll close this and we can revisit this if Go implements 0-RTT.

As noted, however, the feature is somewhat dangerous and offers very little overall benefit.

**Comment by CoiaPrant233** [comment]
Hey guy
I'm extending the functionality of go crypto/tls

Currently, compressed certificate, application layer protocol settings and 0-RTT on the server side have been implemented

If you want to know more, please click [here](https://gitlab.com/go-extension/tls)

**Comment by francislavoie** [comment]
We have no plans to use unofficial `crypto/tls` implementations in Caddy.
