### ISSUE TITLE
No way of enabling TLS1.0 and TLS1.1 in Caddy2 anymore?

### ISSUE THREAD

**Issue by noqqe** [caddyserver/caddy#3667]
Hi,

I recently upgraded to caddy2 and there is no way of enabling ssl3, tls1.0, tls1.1 anymore. 

The docs clearly state it

> protocols specifies the minimum and maximum protocol versions. Default min: tls1.2. Default max: tls1.3
Source: https://caddyserver.com/docs/caddyfile/directives/tls

```
tls /root/.caddy/cert.crt /root/.caddy/cert.key {
  protocols tls1.0 tls1.2
  ciphers ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 [...]
}
```

Protocols List:

https://github.com/caddyserver/caddy/blob/d322de6b429e9f0bc589880b53373975dabcb997/modules/caddytls/values.go#L116-L128

And in the Code:

https://github.com/caddyserver/caddy/blob/e385be922569c07a0471a6798d4aeaf972facb5b/caddyconfig/httpcaddyfile/builtins.go#L165-L181

Is this intended behaviour? There is no value of the `protocols` directive if you have no other choice than what the default is (-> `protocol tls1.2 tls1.3`).

**Comment by francislavoie** [comment]
That's correct. Those older protocol versions are insecure, so Caddy no longer supports them.

**Comment by mholt** [comment]
> Is this intended behaviour? There is no value of the protocols directive if you have no other choice than what the default is (-> protocol tls1.2 tls1.3).

Of course you have other choices; for example you can disable TLS 1.3 or disable TLS 1.2. Just depends what you need. But we don't support obsolete, insecure protocols, and Caddy's defaults serve 99.99%+ of clients.

**Comment by polarathene** [comment]
I was also a bit surprised to learn about this. I had seen the docs and assumed the min/max config was about sane defaults especially when using Caddy for serving websites. 

Just realized it cannot be used for supporting legacy clients (which we all know should get with the times and be replaced with modern clients) that only support TLS 1.1/1.0 (Android only supported 1.0 until 2014 for example, it's not only deployed to smartphones). 

If only using Caddy for websites, TLS 1.2 as a minimum makes sense and I think it's great to set it as a default. Often the issue in the past is from leaving on bad defaults or copy/pasting outdated configuration. Allowing to explicitly enable TLS when needed for those niche scenarios that still need the support (eg internal use with some legacy clients in enterprise environment) at least Caddy can still be an option. 

I can understand not wanting to support that though and directing anyone who needs that to an alternative solution such as nginx.

**Comment by mholt** [comment]
@omnjpa27516 No need to drop Caddy -- I'd be happy to accommodate [sponsors](https://github.com/sponsors/mholt) with requirements like this. Custom branches/patches of the software is one of the main perks of higher tiers. I do something similar for Stripe (but to clarify, for them, it's not to support obsolete/insecure protocols) -- and I'm willing to do it for your company too. Let's talk about what your requirements are and get you on a sponsorship plan that fits!

You can email me if you want to discuss that privately: matt - at - dyanim dot com.

**Comment by mholt** [comment]
It's even better for business use! Could be saving your company thousands of dollars.

**Comment by conistuffwow** [comment]
Not to revive a dead thread, but having people pay to enable TLS 1.0/1.1 is absurd. I'm a legacy iOS developer, and I need my site to run on TLS1.0/1.1 to support older iOS and OS X versions.

**Comment by mohammed90** [comment]
> Not to revive a dead thread, but having people pay to enable TLS 1.0/1.1 is absurd. I'm a legacy iOS developer, and I need my site to run on TLS1.0/1.1 to support older iOS and OS X versions.

The ask is to re-enable and support a [deprecated and _insecure_](https://techcommunity.microsoft.com/blog/windows-itpro-blog/tls-1-0-and-tls-1-1-soon-to-be-disabled-in-windows/3887947) protocol, which is not supported by many operating systems that receive updates, adds maintenance load on maintainers. Users who require those deprecated protocols can either own the effort buy building from source after making the necessary code changes (check the discussion linked by Francis), or offload it to a vendor (Matt) who will do it for you. It's not unreasonable.

**Comment by conistuffwow** [comment]
It actually is quite unreasonable, considering a "completely configurable
out of the box" software cannot be configured with the protocols.

**Comment by mohammed90** [comment]
It's more than configuration.

Anyways, locking the thread because any discussion here from this point onwards isn't going to add a point that hasn't been made already or answered.
