### ISSUE TITLE
Invalid dial adress

### ISSUE THREAD

**Issue by wouterverduin** [caddyserver/caddy#3672]
Dear developers of Caddy!

First of: Love the V2; great job!

However, I ran into (possibly) a bug or misunderstanding. I want to reverse proxy something using "subdomain.domain.com" to 192.168.1.161:8080/site

However I get this error: 

{"level":"error","ts":1597926160.917917,"logger":"http.log.error","msg":"making dial info: upstream 192.168.1.161:8080/site: invalid dial address 192.168.1.161:8080/site: address site: missing port in address",

Is this expected behaviour or a bug?

Thanks in advance!

**Comment by wouterverduin** [comment]
Fixed it; just a configuration thing:

domain.com {
    redir / /site/ 308
    reverse_proxy 192.168.1.161:8080 {
        flush_interval -1
    }
}

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy! Glad you figured out the issue.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
