### ISSUE TITLE
handle_path is not stripping prefix, or root is using the wrong path

### ISSUE THREAD

**Issue by ranisalt** [caddyserver/caddy#3675]
I want to have static images served by a file_server in a subdirectory. I tried several variations of this:

```
handle_path /static/* {
  root * /static
  file_server
}
```
```
handle_path /static/* {
  file_server {
    root /static
  }
}
```
```
handle /static/* {
  uri strip_prefix /static
  root * /static
  file_server
}
```
```
handle /static/* {
  uri strip_prefix /static
  file_server {
    root /static
  }
}
```

The files are correctly there:
```
$ docker-compose exec proxy ls /static -R
/static:
img

/static/img:
image.png
```

However, the file is NOT accessible in `/static/img/image.png`. Instead, it is not stripping the prefix, and serving at `/static/static/img/image.png`. So either `handle_path` is not stripping `/static`, or `root` does not use whatever variable `handle_path` stores the path at.

**Comment by ranisalt** [comment]
```
handle_path /static/* {
  root * /static
  try_files {path}
}
```
Does not work too...

[Documentation for `file_server` is very lacking](https://caddyserver.com/docs/caddyfile/directives/file_server), by the way. I find it unclear what the `[<matcher>]` part is about. If I use `file_server /static/*`, what paths will match? Where will it look for files? Will it modify the path in some way?

**Comment by mholt** [comment]
Hi, thanks for opening an issue.

> However, the file is NOT accessible in /static/img/image.png. Instead, it is not stripping the prefix, and serving at /static/static/img/image.png. So either handle_path is not stripping /static, or root does not use whatever variable handle_path stores the path at.

`handle_path` works as expected for me. What is your full, unmodified/unredacted config file? And what are the exact requests and responses? (Use `curl`) I want to get the same behavior you're seeing.

> Documentation for file_server is very lacking, by the way. I find it unclear what the [<matcher>] part is about.

That's all explained [here on the Directives Syntax](https://caddyserver.com/docs/caddyfile/directives#syntax) section of the docs.

>  If I use file_server /static/*, what paths will match?

This is explained [here in the Matchers](https://caddyserver.com/docs/caddyfile/matchers) page of the docs.

> Where will it look for files? Will it modify the path in some way?

This is explained [on that very page](https://caddyserver.com/docs/caddyfile/directives/file_server) you linked to:

> It works by appending the request's URI path to the [site's root path](https://caddyserver.com/docs/caddyfile/directives/root).

**Comment by ranisalt** [comment]
The unmodified, unredacted configuration is:

```
www.{$API_URL} {
	redir https://{$API_URL}{uri} permanent
}

{$API_URL} {
	log {
	    output file /var/log/api.{$API_URL}.log
	    format logfmt
	}

	handle /api/* {
		header {
			access-control-allow-origin {http.request.header.origin}
			defer
		}

		uri strip_prefix /api
		reverse_proxy http://backend:8080
	}

	# this is the problematic block
	handle_path /static/* {
		root * /static
		file_server
	}

	handle {
		root * /app
		try_files {path} /index.html
		file_server
	}

	encode zstd gzip
}
```

This is all running in a Docker container. I mounted a directory `static` with an image in `img/image.png` inside it to `/static`. If I `curl https://$API_URL/static/img/image.png`, I get the `index.html` file for the `handle` block right below it. If I access `curl https://$API_URL/static/static/img/image.png`, I then get the image as expected.

The `/api/*` block works as expected, and the service listening to `http//backend:8080` does get the correct path with `/api` stripped e.g. if I `curl https://$API_URL/api/login` I get the same result to `curl http://backend:8080/login`.

> It's all there in the docs. Please give them a read!

**Comment by francislavoie** [comment]
Oh, that's funky. What happened for you is that you got "unlucky" with the [directive order](https://caddyserver.com/docs/caddyfile/directives#directive-order) in the Caddyfile.

If you run `caddy adapt` on your config, you'll see that the JSON looks like this:

```json
{
	"logging": {
		"logs": {
			"default": {
				"exclude": [
					"http.log.access.log0"
				]
			},
			"log0": {
				"writer": {
					"filename": "/var/log/api.foo.log",
					"output": "file"
				},
				"encoder": {
					"format": "logfmt"
				},
				"include": [
					"http.log.access.log0"
				]
			}
		}
	},
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"www.foo"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"handler": "static_response",
													"headers": {
														"Location": [
															"https://foo{http.request.uri}"
														]
													},
													"status_code": 301
												}
											]
										}
									]
								}
							],
							"terminal": true
						},
						{
							"match": [
								{
									"host": [
										"foo"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"encodings": {
														"gzip": {},
														"zstd": {}
													},
													"handler": "encode"
												}
											]
										},
										{
											"group": "group5",
											"handle": [
												{
													"handler": "subroute",
													"routes": [
														{
															"handle": [
																{
																	"handler": "headers",
																	"response": {
																		"deferred": true,
																		"set": {
																			"Access-Control-Allow-Origin": [
																				"{http.request.header.origin}"
																			]
																		}
																	}
																},
																{
																	"handler": "rewrite",
																	"strip_path_prefix": "/api"
																},
																{
																	"handler": "reverse_proxy",
																	"upstreams": [
																		{
																			"dial": "backend:8080"
																		}
																	]
																}
															]
														}
													]
												}
											],
											"match": [
												{
													"path": [
														"/api/*"
													]
												}
											]
										},
										{
											"group": "group5",
											"handle": [
												{
													"handler": "subroute",
													"routes": [
														{
															"handle": [
																{
																	"handler": "vars",
																	"root": "/app"
																}
															]
														},
														{
															"handle": [
																{
																	"handler": "rewrite",
																	"uri": "{http.matchers.file.relative}"
																}
															],
															"match": [
																{
																	"file": {
																		"try_files": [
																			"{http.request.uri.path}",
																			"/index.html"
																		]
																	}
																}
															]
														},
														{
															"handle": [
																{
																	"handler": "file_server",
																	"hide": [
																		"Caddyfile"
																	]
																}
															]
														}
													]
												}
											]
										},
										{
											"handle": [
												{
													"handler": "subroute",
													"routes": [
														{
															"handle": [
																{
																	"handler": "rewrite",
																	"strip_path_prefix": "/static"
																}
															]
														},
														{
															"handle": [
																{
																	"handler": "vars",
																	"root": "/static"
																},
																{
																	"handler": "file_server",
																	"hide": [
																		"Caddyfile"
																	]
																}
														}
													]
												}
											],
											"match": [
												{
													"path": [
														"/static/*"
													]
												}
											]
										}
									]
								}
							],
							"terminal": true
						}
					],
					"logs": {
						"logger_names": {
							"foo": "log0"
						}
					}
				}
			}
		}
	}
}
```

You'll notice that your handle with the `/static/*` path matcher was sorted to the bottom. This means that the `handle` with no matcher is always taking precedence over the one with the `/static/*` matcher.

There's a few different ways to fix this, but the easiest would be to just remove the `handle` around your last bit of config, because the existing `handle` and `handle_path` directives will be handled first anyways due to the directive order (`file_server` comes after `handle` and `handle_path`).

**Comment by ranisalt** [comment]
> I consider this a bug actually, I think they should be considered the "same" when sorting.

Would it be possible to have some specificity ordering around `handle` directives, as Nginx does with `location`? e.g. `handle /something/ {` ranks higher than `handle {` because it is more specific (in this case, is a subset of).

**Comment by francislavoie** [comment]
Yes that's already how it works, we sort same-directives based on the length of their path matchers. It's just that `handle_path` and `handle` are different directives, so they were not getting sorted _together_. See #3676, now `handle_path` will be considered the same as `handle` after the initial round of parsing, before the sorting happens.
