### ISSUE TITLE
fmt: support for reading from stdin

### ISSUE THREAD

**Issue by matthewpi** [caddyserver/caddy#3679]
Currently `caddy fmt` only supports reading from files which is perfectly fine for most cases, however I am using it to format files for my [`vscode-caddyfile-support`](https://github.com/matthewpi/vscode-caddyfile-support) extension where the file is not written to disk before calling the formatter.

My proposal is to add a `-stdin` flag to the `caddy fmt` command which will force reading from `os.Stdin` and printing the output of the formatter (no overwrite option).

I have already implemented this logic here https://github.com/matthewpi/caddy/commit/31cd74e767c1c3a3c4fa182d99b58b2f4b7eda75

Just to keep track, this was changed so instead of using `-stdin` as a flag you use `-` as a file name. ([ref](https://github.com/caddyserver/caddy/pull/3680#discussion_r475123239))

**Comment by mholt** [comment]
Thanks @matthewpi for writing this feature!

If you have any interest in doing the same thing for `caddy adapt`, I think it'd be really helpful! (Although that one will have to accept flags too.)
