### ISSUE TITLE
https://getcaddy.com is down due to SSL cert issue 

### ISSUE THREAD

**Issue by sshivaji** [caddyserver/caddy#3681]
I get the NET::ERR_CERT_COMMON_NAME_INVALID exception in Chrome and in firefox the exception is 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

I am not sure if this is the right place to report it. However, this will impact all caddy v1 download scripts. Is caddy v1 no longer available for download from sites?

![Screenshot from 2020-08-23 02-11-20](https://user-images.githubusercontent.com/1430554/90975082-f6f33880-e4e5-11ea-8094-4185f4bc1a80.png)

**Comment by francislavoie** [comment]
Yeah Caddy v1 is no longer maintained. The best way to download Caddy v1 is either directly from the github releases tab https://github.com/caddyserver/caddy/releases/tag/v1.0.4 or by building from source, from the v1 branch: https://github.com/caddyserver/caddy/tree/v1#build

We recently set the EOL date to October 1st 2020: https://github.com/caddyserver/caddy/security/policy#supported-versions
