### ISSUE TITLE
Can I add basic auth for redir?

### ISSUE THREAD

**Issue by daiaji** [caddyserver/caddy#3685]
```
example.com {
                basicauth /* {
*** ******
                }
                redir https://a2.example.com
}
```
It seems that basicauth is not valid for redir.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
