### ISSUE TITLE
unrecognized directive: log. caddy v2.1.1

### ISSUE THREAD

**Issue by liesislukas** [caddyserver/caddy#3686]
caddy version: v2.1.1
ubuntu v18.04

in Caddyfile: 

```
logs {
  level WARN
}
```

error:

reload: adapting config using caddyfile: Caddyfile:6: unrecognized directive: level

Question: how to set default log level at Caddyfile?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
