### ISSUE TITLE
Serve http and https  connections over the same port

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#3687]
`caddyfile` 

```
{
	debug
	
}

https://localhost:16800 {
	respond "hello world https"
	
}

http://localhost:16800 {
	respond "hello world http"
	
}

```

```
caddy start
```
```
2020/08/26 05:11:33.936 [34mINFO[0m   using adjacent Caddyfile
run: adapting config using caddyfile: server listening on [:16800] is configured for HTTPS and cannot natively multiplex HTTP and HTTPS: http://localhost:16800
start: caddy process exited with error: exit status 1
```

how about  provide automatic redirection from http -> https ?

Serve http and https  connections over the same port:

https://github.com/lvgithub/blog/blob/master/http_and_https_over_same_port/README.MD

https://github.com/mscdex/httpolyglot/issues/3

**Comment by francislavoie** [comment]
Caddy doesn't support this out of the box, but https://github.com/mholt/conncept would be the solution for this. Multiplexing is a complicated topic and it's not something Caddy aims to solve by default.
