### ISSUE TITLE
I want a simple webdav server!!

### ISSUE THREAD

**Issue by maryjeck** [caddyserver/caddy#3688]
my caddyfile like this
############
{
	order webdav last
}

http://localhost:2015 {
  
  encode gzip
  webdav /webdav/* {
    root /Systemtools
    prefix /webdav/
  }
  
  log {
    output stdout
  }
  
}
###############

but ,it's not work 
who can help me??

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
