### ISSUE TITLE
Add filter encoder support to caddyfile log directive 

### ISSUE THREAD

**Issue by utilitynerd** [caddyserver/caddy#3694]
I would like to be able to prevent certain headers (Authorization: X-Auth-Token:, etc ) from being included in the caddy logs. 

I found https://github.com/caddyserver/caddy/issues/3562, which is asking to be able to set an allowlist of headers, which makes sense for their use case.

In my case, a blocklist, makes more sense, as I only want to prevent a single header from being included in the logs.  

As a workaround, I'm current using "format single_field common_log", but the documentation mentions this is depreciated and I would like all the additional logging available, aside from security sensitive auth tokens.

**Comment by utilitynerd** [comment]
Looking deeper, I'm wondering if this is already possible with the caddy.logging.encoders.filter.delete module.  I can't find any documentation on how to use this in a caddyfile nor if this module would support deleting a single header.

**Comment by mholt** [comment]
Thanks for looking deeper! Indeed, this is already possible with that module: https://caddyserver.com/docs/modules/caddy.logging.encoders.filter.delete

There is not currently Caddyfile support for the filter encoder: https://caddyserver.com/docs/caddyfile/directives/log -- however, adding it probably won't be too difficult. Pull requests welcomed!

**Comment by utilitynerd** [comment]
Thank you for the quick response!  

I've updated the subject to reflect that this is a feature request for caddyfile support, since the capability already exists in the caddy codebase.  

I'll look into moving to the JSON config and / or possibly a PR

**Comment by francislavoie** [comment]
I have a WIP PR for this already, but I haven't had the time to finish it yet. It's nearly done but I wanted to implement another requested feature at the same time to preserve certain keys instead of deleting everything at a certain key.

https://github.com/caddyserver/caddy/pull/3578

**Comment by jbritton916** [comment]
https://www.instagram.com/p/CE5TrxaJWs254qJVnCRZZD29uqPkiBt8oHXu_U0/?igshid=1no6w4tr6fco5

**Comment by mholt** [comment]
Thanks Francis! The PR has been merged so it should go out with 2.2 rc 2.
