### ISSUE TITLE
support X-HTTP-Method-Override?

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#3699]
support request header X-HTTP-Method-Override?

**Comment by mholt** [comment]
You can do this already: https://caddyserver.com/docs/modules/http.handlers.rewrite#method

Set the `"method"` property to, say, `{http.request.header.X-HTTP-Method-Override}`.

**Comment by masx200** [comment]
```txt
@override{
header X-HTTP-Method-Override *
}
rewrite {
method {http.request.header.X-HTTP-Method-Override}
}
```

**Comment by mholt** [comment]
I don't think there's a `method` subdirective in the Caddyfile unmarshaler yet, but this could be proposed and implemented (in a separate issue probably).
