### ISSUE TITLE
When will brotli compression be supported?

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#3704]
When will brotli compression be supported?

https://caddyserver.com/docs/caddyfile/directives/encode#encode

https://github.com/caddyserver/caddy/issues/3692

https://github.com/google/brotli

**Comment by francislavoie** [comment]
It won't be, as noted in https://github.com/caddyserver/caddy/issues/3692#issuecomment-683976794, unless a much much faster pure-go implemention is made. It was too expensive to run on the fly, so it was scrapped.

Brotli is more ideal for precompressed assets at the moment, so follow those linked issues for discussion on content negotiation, etc.

**Comment by BioEvo** [comment]
> It won't be, as noted in [#3692 (comment)](https://github.com/caddyserver/caddy/issues/3692#issuecomment-683976794), unless a much much faster pure-go implemention is made. It was too expensive to run on the fly, so it was scrapped.
> 
> Brotli is more ideal for precompressed assets at the moment, so follow those linked issues for discussion on content negotiation, etc.
> 
> To be clear, the https://github.com/google/brotli project is a C implementation, and we can't use that because we need Caddy to have zero C dependencies so that we produce completely static binaries.
> 
> https://github.com/andybalholm/brotli does exist, but it's still too slow for use in a web server.

Here comes a pure-go implemention brotli which was translated by c2go: https://github.com/andybalholm/brotli

**Comment by francislavoie** [comment]
We've seen it, but it's too slow. As I've said in the last line of my comment.
