### ISSUE TITLE
Wrong translation on the It Works page

### ISSUE THREAD

**Issue by milewski** [caddyserver/caddy#3705]
Hi if this is Portugues it should have been `Parabéns!` instead of `Felicidades!`

![image](https://user-images.githubusercontent.com/2874967/91958904-8694b480-ed3a-11ea-8f53-07c3b720fda9.png)

**Comment by francislavoie** [comment]
Felicidades is "Congratulations" in Spanish 😉

**Comment by milewski** [comment]
I see Portuguese and Spanish are almost the same... the same word in these two languages sometimes has a different meaning or are used at different situations, in Brasil we would never think of using Felicidades as congratulations although Felicidades is also a valid word in Portugues which means Happiness, Cheers etc.. closer meaning

**Comment by francislavoie** [comment]
Interesting! Thanks for asking!
