### ISSUE TITLE
Support "TLS" raw reverse proxy? based on the "servername" in the 'TLS' handshake protocol?.

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#3708]
Support "TLS" raw reverse proxy?

**Comment by masx200** [comment]
Can it determine which server to reverse proxy to based on the "servername" in the TLS handshake protocol?.

**Comment by masx200** [comment]
It should be said that the original TLS packet is directly forwarded to the upstream server.

**Comment by masx200** [comment]
This can allow upstream servers to use their own TLS certificates.

**Comment by masx200** [comment]
https://github.com/dlundquist/sniproxy

**Comment by masx200** [comment]
1. Principle

RFC4366 defines the server name indication extension for TLS. Using this we can construct a TCP proxy that detects server name in the client handshake and proxies to the appropriate HTTPS server. This has the advantage over Nginx or Apache HTTPS SNI virtual hosting that the proxy does not need to the servers private key. This could be useful as we exhaust IPv4 addresses and HTTPS virtual hosting becomes necessary: a proxy could listen on an IPv4 address and proxy to HTTPS servers on separate IPv6 addresses.

2. Features
Name-based proxying of HTTPS without decrypting traffic. No keys or certificates required.
Supports both TLS and HTTP protocols.
Supports IPv4, IPv6 and Unix domain sockets for both back end servers and listeners.
Supports multiple listening sockets per instance.

Because it is based on sni, so if the site does not support https, you can not use sniproxy proxy to proxy.

**Comment by masx200** [comment]
Can the function of'sniproxy' be integrated into'caddy'?

**Comment by francislavoie** [comment]
That's exactly the purpose of https://github.com/mholt/conncept.
