### ISSUE TITLE
Feature Request: Operating system interface for file server

### ISSUE THREAD

**Issue by ss098** [caddyserver/caddy#3720]
Currently, File server module only support file system.

I think the File server module could support more data sources, such as S3 or elsewhere.

This could be done by implementing a Certmagic storage interface, or roughly an OS compatible interface.

**Comment by francislavoie** [comment]
Did a bit of googling, https://github.com/spf13/afero/ looks like a pretty solid option for a filesystem abstraction layer.

The S3 support doesn't look super certain though, from what I'm reading, but this is the most recent iteration: https://github.com/fclairamb/afero-s3

If you'd like to give a shot at implementing this (maybe separate from the existing `file_server` handler; if it pans out well and ends up backwards compatible, we could potentially swap it in replacing the existing one), that would be cool.

**Comment by mholt** [comment]
I think I'd like to wait and see if the Go team continues to develop a mature FS abstraction: https://go.googlesource.com/proposal/+/master/design/draft-iofs.md

**Comment by francislavoie** [comment]
This has landed in Go 1.16! https://golang.org/doc/go1.16#fs

We'll need to wait until we bump Caddy's minimum Go version to 1.16. We just bumped to minimum of 1.15, so if we go by that pattern of supporting the past two versions of Go, then that might be 6 months from now after 1.17 is released. TBD.

**Comment by francislavoie** [comment]
Now that we've bumped to minimum of Go 1.16, this is now a refactor we could do!

This isn't a top priority, so if some enterprising individual wants to give us a hand, this would be a good issue to pick up!

**Comment by mholt** [comment]
@ss098 You will like this: https://github.com/caddyserver/caddy/pull/4909

**Comment by ss098** [comment]
@mholt I'm excited about the implementation of this feature!!!

**Comment by hairyhenderson** [comment]
FYI - https://github.com/hairyhenderson/go-fsimpl provides some useful (IMO) filesystems for `io/fs` 😉

**Comment by mholt** [comment]
@hairyhenderson That's very cool!
