### ISSUE TITLE
308 http to https redirect does not work with some ISPs

### ISSUE THREAD

**Issue by m90** [caddyserver/caddy#3722]
I am seeing an issue where some ISPs (9 Mobile in Nigeria for example) do not correctly handle the `308 Permanent Redirect` that Caddy responds with when upgrading an http Request to https. Clients will instead see a blank page saying `Service unavailable` and a ISP Logo that got MITMed. Upgrading a request via `301 Moved Permanently` works as expected on such connections.

This is not really Caddy's fault (9 Mobile also injects ads into everything sent over http and similar), yet it means we can't really use Caddy in such markets as it cuts off everyone from our product that does not provide the https protocol in the URL. I can see the status code for this redirect is hard coded and not configurable here: https://github.com/caddyserver/caddy/blob/66863aad3beb480a26664c77b73eb2ff7fcab754/modules/caddyhttp/autohttps.go#L324

Is there any way for us to make Caddy respond with a 301 instead?

**Comment by francislavoie** [comment]
Strange. That's unfortunate.

You can override the existing redirects by setting up a site block like this:

```
http:// {
    redir https://{hostport}{uri} 301
}
```

**Comment by lscgzwd** [comment]
solved my problem

**Comment by m90** [comment]
In case anyone comes across this issue in 2022 or later, the above snippet does not work with newer versions of Caddy anymore. In addition, you will need to configure `auto_https disable_redirects`: https://caddy.community/t/cant-get-non-default-https-upgrade-to-work/14836/4

```
{
  auto_https disable_redirects
}

http:// {
    redir https://{hostport}{uri} 301
}
```

**Comment by mholt** [comment]
I admit, that is a bit confusing :thinking: (It's not obvious why you'd have to disable the auto-redirects when you're manually overriding them anyway.) This might deserve a special note in our docs, @francislavoie  -- what do you think?

**Comment by francislavoie** [comment]
Sure, we can make some docs adjustments for this.

**Comment by JayTechX** [comment]
> In case anyone comes across this issue in 2022 or later, the above snippet does not work with newer versions (post 2.4.3 if I'm correct) of Caddy anymore. To get it working you will need to configure `auto_https disable_redirects` in addition: https://caddy.community/t/cant-get-non-default-https-upgrade-to-work/14836/4
> 
> ```
> {
>   auto_https disable_redirects
> }
> 
> http:// {
>     redir https://{hostport}{uri} 301
> }
> ```

Strange error, but this is a perfect fix.
