### ISSUE TITLE
How to prohibit caddy from automatically occupying IPv6 port 80?

### ISSUE THREAD

**Issue by lxhao61** [caddyserver/caddy#3724]
The caddy2 configuration does not enable port 80, but caddy has automatically enabled port 80 for IPv6. How to prohibit it from occupying this port?
![QQ图片20200913231336](https://user-images.githubusercontent.com/24571146/93213722-d2ae1300-f796-11ea-93ab-416a84504b87.png)

**Comment by francislavoie** [comment]
Caddy uses port 80 for the ACME HTTP challenge as part of the Automatic HTTPS feature.

https://caddyserver.com/docs/automatic-https

If you don't want this, you can either turn off `auto_https` with the global option, or change the default HTTP port to something else with the `http_port` global option.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
Specifically, assuming you are using the Caddyfile, to use only a specific interface, use the `bind` directive: https://caddyserver.com/docs/caddyfile/directives/bind
