### ISSUE TITLE
Update an logging level for reverse_proxy to Debug from Error

### ISSUE THREAD

**Issue by xnaas** [caddyserver/caddy#3732]
https://github.com/caddyserver/caddy/blob/3ee663dee195e5f8ead7879b31131f46cd0fba13/modules/caddyhttp/reverseproxy/reverseproxy.go#L644-L653

As [discussed on Reddit](https://www.reddit.com/r/PleX/comments/iu50ho/plex_and_caddy_v2_reverse_proxy_log_spam/g5jmpc0/?context=10000), it seems that reverse proxying some applications (in this case Plex) can lead to some extensive error log spamming. Requesting this log level be updated to Debug instead of Error.

I'd submit a PR, but I'm not sure what to change other than `h.logger.Error` to `h.logger.Debug`, but I'm sure there's a *lot* more to it than that.

**Comment by francislavoie** [comment]
Actually that should be all there is to it (`Error` -> `Debug`) :smile:

**Comment by xnaas** [comment]
The `zap.Error(err)` part doesn't need to be altered or anything?

**Comment by francislavoie** [comment]
No, that just encodes the actual `err` into something `zap` (the logging lib we use) will know how to serialize.

**Comment by xnaas** [comment]
Well I can submit a super ugly, github-created PR if you're ok with that. 😄  (I've found some devs *really* hate them.)

**Comment by francislavoie** [comment]
Sure, if you do that, you can then grab the CI artifact generated from the PR to test it out and confirm that it works as you expect.

**Comment by mholt** [comment]
The _only_ thing I would mention here is that we don't _know_ whether it's a server error or not; I think usually they are client errors (or errors caused by context cancellation, for example an admin-invoked config reload that expended out the grace period) which probably aren't "error-worthy". If there are any situations that could be errors though, if we switch this to debug level, we'll never see the errors (on the server) without enabling debug logging.

I think it's probably a safe change, but just be aware of the potential tradeoff that could be irritating down the road.

**Comment by xnaas** [comment]
In that case: before submitting a messy github-produced PR, I'll monitor the logs for few more days and see if the same log spam as before resurfaces during remote streams. If not, then I'll close out this issue without submitted a PR.

**Comment by mholt** [comment]
When you say "spam" how many are we talking about, and in what timeframe? Any reason you can't just filter out those logs? Caddy's logs are structured which makes this very easy to automate.

Also, note that clients have control over whether errors happen here; for example if they close the connection before reading the response, I believe that is one case where you get a log/error. (This is one reason why having them as debug level would probably be preferable; but again, I'm not sure whether that's the exclusive cause.)

**Comment by xnaas** [comment]
> When you say "spam" how many are we talking about, and in what timeframe?

It was consistently sending ~5-10 error messages per second, though.

> Any reason you can't just filter out those logs? Caddy's logs are structured which makes this very easy to automate.

I haven't looked into this at all, honestly. Is there a page [other than this](https://caddyserver.com/docs/caddyfile/directives/log) I should be looking at?

**Comment by mholt** [comment]
> It was consistently sending ~5-10 error messages per second.

For how long? How many clients, etc?

> I haven't looked into this at all, honestly. Is there a page other than this I should be looking at?

Eh, I'd probably just read this: https://caddyserver.com/docs/logging - and then use whatever log tooling you prefer.

**Comment by xnaas** [comment]
Per https://caddy.community/t/context-cancelled-when-webpack-hmr-sends-updates-fix/9850/ my particular case is basically solved. I'll leave it up to y'all on if this issue/change is still worth anything or not.

**Comment by xnaas** [comment]
No need to re-open this, but just as a general note for future readers: while the linked changes did not *completely* remove those things from my logs, it **significantly** reduced the quantity.

**Comment by mholt** [comment]
Cool, thanks for following up. And yep, those logs are not a problem: it just means the client connected, made a request, and was like "Actually I don't need this response" and then hung up.
