### ISSUE TITLE
How to forward backend server header to downstream clients, without prepending Caddy?

### ISSUE THREAD

**Issue by pims** [caddyserver/caddy#3750]
Hi there 👋 ,

I’ve been trying to configure Caddy to _not_ add the `"Server: Caddy"` header in a reverse_proxy mode but wasn't able to.

```
caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

Caddyfile:
```
{
  http_port 8000
}
https://example.com

reverse_proxy localhost:7777 {
  header_down +Server
}
```
The server on running on `localhost:7777` sets the `Server: teapot` header in the http response:

```
curl -i http://localhost:7777/v1/foo

Content-Type: text/plain; charset=utf-8
Server: teapot
X-Content-Type-Options: nosniff
Date: Thu, 24 Sep 2020 04:36:41 GMT
Content-Length: 30
```

I've tried to follow the directions listed in the [documentation](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) but haven't achieved my goal.
What I'm seeing right now is `Server=[Caddy teapot ]`, what I'd like to see `Server=[teapot ]`

Setting ` header_down -Server` in the Caddyfile drops that header entirely, but I'm unable to drop `Caddy` and preserve whatever the backend has set: `Server: teapot`. Adding `Server: teapot` in the Caddyfile is easy, but I would like to get this value from the backend and not set a static value.

My guess is that:
```go
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Server", "Caddy")
        …
}
```
is not respecting the header substitution directives, but that's just a guess at this point.
Is there a way of setting the `Server` header response to whatever the backend sets and only set `Server: Caddy` if that header is not present?

Thanks in advance for taking a look at this issue and thank you for all the great work you're doing on Caddy ✨

**Comment by mholt** [comment]
Using `header_down +` will _append_ a header (with an empty value, hence the results you're seeing).

To remove Caddy's `Server` header, use the `header` directive: https://caddyserver.com/docs/caddyfile/directives/header

**Comment by pims** [comment]
I wasn't aware of the community forum, so thanks for pointing it out.

While this issue is phrased as a question, I believe it is indeed an issue with Caddy: it does not look like it is possible to use the backend provided `server: teapot` response header without having `server: Caddy` included in the downstream response headers.

The header directive does not support _remove if match_
Using:
```
header {
    -Server
}
```
also drops the `server` header from upstream.

Ideally, we could:
```
header {
    -Server Caddy
}
```
to remove the header `server` header if it exists and its value matches `Caddy`.

I understand you might not be interested in changing this behavior, so feel free to keep this issue closed, but if you think it's a worthwhile addition, I'd be happy to submit a PR.

**Comment by francislavoie** [comment]
Does `header Server Caddy ""` work for you? i.e. replace Caddy with an empty string

**Comment by pims** [comment]
I tried that but it didn’t work.

**Comment by mholt** [comment]
If I recall correctly the Caddyfile sets `deferred: true` on header operations because it's what most people need. Yours is a bit of a niche requirement, but you can easily accomplish what you need in the JSON by not setting `deferred` to true: https://caddyserver.com/docs/json/apps/http/servers/routes/handle/headers/#response/deferred -- which should do exactly what you need since it will delete the Server header created by Caddy at the very beginning and then keep the one created later by the proxy, as opposed to deleting it later.

**Comment by pims** [comment]
Great, thanks @mholt and @francislavoie, I’ll switch from Caddyfile to JSON config.
