### ISSUE TITLE
upgrade to v2.2.0 break SRV Caddyfile 

### ISSUE THREAD

**Issue by waiyip-aquabyte** [caddyserver/caddy#3753]
I have an entry in Caddyfile like this

```
auto-keypoints.ml-service.aquabyte.ai {
    reverse_proxy srv+auto-keypoints-bridge-mode.local
}
```

It works great in v2.1.1. After I upgraded, it does not pass validation

```
validate: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 1: loading module 'reverse_proxy': provision http.handlers.reverse_proxy: missing port in address
```

I should not need a port. Caddy used to be able to find it from the SRV record. I added it just in case. But the validation error remains the same.

**Comment by mholt** [comment]
Coulda sworn we had a test for this. My bad for overlooking that.

/cc @Mohammed90 - I think he was looking into this already, in fact! Oh, and @danlsgiga.

**Comment by Mohammed90** [comment]
Yeah, I found the culprit and currently assessing the damage and figuring out the fix.

**Comment by waiyip-aquabyte** [comment]
Wow, super fast response. Thanks!
