### ISSUE TITLE
Caddy stop returns an error 

### ISSUE THREAD

**Issue by xd003** [caddyserver/caddy#3759]
Whenever i am trying to stop the caddy server i am getting the following error
```
root@xd003:~# caddy stop                                         
2020/09/28 02:55:52.733 WARN    failed using API to stop instanc{
"error": "performing request: Post \"http://localhost:2019/stop\"
: dial tcp 127.0.0.1:2019: connect: connection refused"}         
stop: performing request: Post "http://localhost:2019/stop": dial
 tcp 127.0.0.1:2019: connect: connection refused
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

That just means that Caddy wasn't running, or did not have the admin API enabled. The Caddy CLI uses the admin API to send signals to the running instance.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
