### ISSUE TITLE
Server Sent Events are not working in a nodejs/express app

### ISSUE THREAD

**Issue by thunder7553** [caddyserver/caddy#3765]
With Caddy 2.2.0, the responses from the server are only sent unbuffered when the content type is `text/event-stream`. NodeJS express sends out a Content Type of `text/event-stream; charset=utf-8`. 

I am not so deep in the specs to know if caddy or express is at fault. I would expect caddy to gracefully accept any arguments to the `content-type: text/event-stream`.

# Workaround 1
It is possible to get it working with express (by not using express, but the underlaying nodejs function calls directly).

```
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'X-Accel-Buffering': 'no',
      'Transfer-Encoding': 'chunked',
    });
```

# Workaraound 2
Setting `flush_interval` to `-1` in the Caddyfile works as well.

**Comment by francislavoie** [comment]
I think https://github.com/caddyserver/caddy/pull/3758 is likely the fix you will need

**Comment by cmfcmf** [comment]
> I think #3758 is likely the fix you will need

Yes, indeed. I stumbled across this issue when using Next.js, which adds the same charset parameter to its event streams. A temporary 'fix' is to set `flush_interval` to `-1`:

```
reverse_proxy {
	... 
	flush_interval -1
}
```
