### ISSUE TITLE
Add an upstream for reverse_proxy handler dynamicly?

### ISSUE THREAD

**Issue by yflau** [caddyserver/caddy#3768]
Refer to https://caddy.community/t/custom-select-policy-for-reverse-proxy-module/9963
If caddy can provide a public method to add upstream dynamic, then we can just configure just one reverse_proxy handler, and the upstream info will be passed from previous stage（which maybe a API gateway and get upstream information from database or some others).

**Comment by mholt** [comment]
You can already do this by using a placeholder such as `{http.request.header.X-Caddy-Upstream-Dial}` -- just be aware of the implications with health checks if those are configured.

**Comment by francislavoie** [comment]
@mholt I think you missed the point of the discussion in the forum thread, that's not enough for what they're looking for.

**Comment by francislavoie** [comment]
Hmm, well I guess you're right. I suppose the only difference is that `MaxRequests` can't be placeholder'd, but that probably doesn't matter.

**Comment by yflau** [comment]
Cool, but there is another problem, it seems that the port must be specified like this, for example, 

`Dial: {http.request.header.X-Caddy-Upstream-Dial}:80`

thus, if the upstream uses  different ports, then this solution not work, if we can use a default port 80 when not specified in Dial?

**Comment by mholt** [comment]
@yflau Why is the gateway setting a dial address without a port? That seems like a bug. Dial addresses necessarily have ports. If not, it's not an address to dial. (or it's a unix socket)

> Second, all different upstreams become one upstream in such solution, and the health check and circuit breaker will become a global switch, which is not meet the need.

Please note [the documentation](https://caddyserver.com/docs/modules/http.handlers.reverse_proxy#upstreams/dial) which addresses this:

> The network address to dial to connect to the upstream. Must represent precisely one socket (i.e. no port ranges). A valid network address either has a host and port or is a unix socket address.
>
> Placeholders may be used to make the upstream dynamic, but be aware of the health check implications of this: a single upstream that represents numerous (perhaps arbitrary) backends can be considered down if one or enough of the arbitrary backends is down. Also be aware of open proxy vulnerabilities.

**Comment by yflau** [comment]
@mholt 
First problem, what I mean is this: 

`
upstreams": [{
    "dial": "{http.request.header.X-Caddy-Upstream-Dial}"
}
`

Then in Provision phase, will get the error:

`
provision http.handlers.reverse_proxy: address {http.request.header.X-Caddy-Upstream-Dial}: missing port in address"
`

so we must specify a fixed port in configuration, thus the dynamic port can not be passed dynamic.

**Comment by mholt** [comment]
Ah I see, that is tricky. We don't know whether the placeholder will expand to include a port.

Maybe as a special case we can remove this check if the entire value is a placeholder, but you won't know if the replaced value is invalid until request-time... is that acceptable?

**Comment by yflau** [comment]
Yes, it's tricky, but I think it's acceptable because we can implement the dynamic upstream with different ports, or we can only use a fixed port is too restrictive.

**Comment by mholt** [comment]
Based on comments by @Mohammed90 it seems this might be a recent regression (and come to think of it, I do seem to remember your use case working! so I think it should still). See linked PR #3776.

**Comment by yflau** [comment]
Ah, good news, thank you for your quick response
