### ISSUE TITLE
Migrating proxy config (with more complex paths) from Caddy v1 to v2 

### ISSUE THREAD

**Issue by briangershon** [caddyserver/caddy#3773]
Hello,

I've been trying to migrate a small proxy config from Caddy v1 to v2.

## Overview

I'm using Caddy to setup a subdomain that points to a Google Cloud function. Caddy supports automatic TLS and SNI so this worked well.

I want to convert this one line `proxy /add https://us-central1-abc123.cloudfunctions.net/myCloudFunction` from v1 to v2. Notice `/myCloudFunction` is a path after the domain.

I haven't been able to get it to work in v2. I assume it's a combination of `reverse_proxy` and `rewrite` but haven't found the right one yet.

## Details

I've read through the v2 docs, but I can't find an example that's a bit more complex than `reverse_proxy /api/* localhost:9005` example.

I'd be happy to add solution to the Caddy docs afterwards.

This works well in Caddy v1:

```
https://myfunction.mydomain.com {
  tls myemail@gmail.com
  proxy /add https://us-central1-abc123.cloudfunctions.net/myCloudFunction
  errors /log/myfunction.mydomain.com.errors.log
  log / /log/myfunction.mydomain.com.log "{combined}" {
    rotate_size 100
    rotate_keep 10
  }
}
```

I could then `curl -d '{"name": "joe"}' https://myfunction.mydomain.com/add` which would run `myCloudFunction`. Notice mapping `/add` path, so I can support multiple cloud functions on different paths on same subdomain.

In v2, based on errors and reading, `proxy /add https://us-central1-abc123.cloudfunctions.net/myCloudFunction` (v1) no longer works in v2, and I have to use a combination of `reverse_proxy` and `rewrite` afaik.

I tried a bunch of things (added `rewrite`, added various headers) but can't get it to work in v2, here's an example of combinations I tried (commented out).

```
https://myfunction.mydomain.com {
  reverse_proxy /myCloudFunction {
    to https://us-central1-abc123.cloudfunctions.net
    #header_up X-Real-IP {http.reverse_proxy.upstream.remote}
    #header_up X-Forwarded-For {http.reverse_proxy.upstream.remote}
    #header_up X-Forwarded-Port {http.reverse_proxy.upstream.hostport}
    #header_up X-Forwarded-Proto {http.reverse_proxy.upstream.scheme}
  }

  # tls myemail@gmail.com
  # reverse_proxy /add https://us-central1-abc123.cloudfunctions.net/myCloudFunction
  # rewrite /add /myCloudFunction
  # rewrite /myCloudFunction
  # reverse_proxy /add https://us-central1-abc123.cloudfunctions.net
  # reverse_proxy /myCloudFunction https://us-central1-abc123.cloudfunctions.net
  log {
  	output file         /log/myCloudFunction.mydomain.com.log
  }
}
```

What's the proper way to convert my v1 config to v2?

**Comment by francislavoie** [comment]
You're looking for `handle_path` (which strips the matched path) plus `rewrite` to change the base path:

```
handle_path /add* {
    rewrite * /myCloudFunction{uri}
    reverse_proxy https://us-central1-abc123.cloudfunctions.net
}
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by briangershon** [comment]
Thanks so much for your help @francislavoie and I'll ask on forum next time. Cheers!

**Comment by briangershon** [comment]
I just wrote up a **[Caddy your Serverless Functions](https://www.briangershon.com/blog/caddy-your-serverless-functions/)** blog post highlighting this example for others wanting to do this.

Here's also the final config with the changes you recommended above along with a `header-up Host` directive so this worked properly with Google Cloud functions.

```
https://myfunction.mydomain.com {
  tls myemail@gmail.com
  handle_path /add* {
    rewrite * /myCloudFunction{uri}
    reverse_proxy {
      header_up Host "us-central1-abc123.cloudfunctions.net"
      to https://us-central1-abc123.cloudfunctions.net
    }
  }
  log {
    output file /logs/myfunction.mydomain.com.log
   }
}
```
