### ISSUE TITLE
hash_cache in Caddyfile

### ISSUE THREAD

**Issue by maximedb** [caddyserver/caddy#3775]
Is there a way to include [hash_cache](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/authentication/providers/http_basic/#hash_cache) with [basicauth](https://caddyserver.com/docs/caddyfile/directives/basicauth#basicauth) in a `Caddyfile` ?

Thank you!

**Comment by francislavoie** [comment]
The hash cache is always enabled when using the Caddyfile:

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/caddyauth/caddyfile.go#L38
