### ISSUE TITLE
httpcaddyfile: respond with error page from handle_errors

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/caddy#3782]
It looks like it is not currently possible to directly [`respond`](https://caddyserver.com/docs/caddyfile/directives/respond) with an error page defined by [`handle_errors`](https://caddyserver.com/docs/caddyfile/directives/handle_errors) (Like the Nginx [`return`](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return).

An example use case where this could be useful:
```caddyfile
respond /subpath/ 404 # <- I want to return an error page defined in handle_errors
rewrite /subpath/* /subpath/index.html
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Are the examples in https://caddyserver.com/docs/caddyfile/directives/handle_errors#examples not sufficient?

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by segevfiner** [comment]
@francislavoie 

They are sufficient. I'm talking about something else, returning an explicit error from some other route so as to trigger the registered error handlers.

Looking into the JSON config, I think the [`error`](https://caddyserver.com/docs/json/apps/http/servers/errors/routes/handle/error/) handler achieves that. But it's yet another feature not available in the Caddyfile.

**Comment by francislavoie** [comment]
Ah, okay.

**Comment by francislavoie** [comment]
Opened PR https://github.com/caddyserver/caddy/pull/4034 for this.
