### ISSUE TITLE
Support using html/template for HTML templates rendered by the templates handler

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/caddy#3786]
Caddy currently uses `text/template` for rendering templates. Using this for rendering HTML quickly leads to XSS vulnerabilities due to the lack of escaping by default, manual escaping of every template action is hard and error prone.

The `html/template` package was designed for this, handling escaping in a smart context sensitive way. It would be useful to have a way to configure Caddy to use it instead when rendering HTML templates.

On the other hand, sometimes you will need to opt out of escaping, Go includes special types for that (e.g. `template.HTML`) that won't be escaped, but since you have no control over the template context, unlike when using the package directly from Go, Caddy might have to add functions to cast values to those types to exempt them from escaping.

### Example
```
localhost

header Content-Type text/html
respond `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <p>Path: {{.Req.URL.Path}}</p>
</body>
</html>`
templates
```

And navigate to https://localhost/%3Cscript%3Ealert(%22XSS%22)%3C/script%3E

**Comment by mholt** [comment]
![rob pike don't do that](https://user-images.githubusercontent.com/1128849/95606892-3a632100-0a18-11eb-9795-0fdd9f81f8cb.gif)

This is known. The template handler is designed to render HTML -- as HTML, not escaped HTML. Have you tried using the templates handler with the html/templates package to build a whole website? I have: the new Caddy website started that way, and it was not only tedious but almost impossible to get anything useful done, since the times you want to render HTML are more frequent than the times you want to escape it.

It's well-known that rendering untrusted, user-controlled content is unsafe; so... don't do that. You, the site owner, are in control of templates, not users. Use `{{html}} when rendering user-controlled content. Only you can know when that is, really. You also need to consider your own specific threat model.

**Comment by segevfiner** [comment]
`html/template` does render HTML, not escaped HTML. It simply escapes all inputs by default,, which is what all modern web frameworks do to err on the side of safety. Coming from other go projects that use it, it felt weird to me that it was not used or supported.

The trick for using it when you do want to render HTML is to wrap the stuff you want to be HTML in one of its wrapper structs (e.g. `html/template.HTML`) or add appropriate functions to cast them in the template, e.g. `safeHTML`. For example, [Hugo](https://gohugo.io/) does that.

Of course that rendering untrusted content is unsafe, its just that it is a ridiculously easy thing to forget, and when you do, BAM! XSS vulnerability. Which is why frameworks preferred to escape by default, that way you just get a bug rather than a vulnerability.

Beginners very often make this mistake, but I have seen time and time again experienced developers fail to notice and handle it properly, especially. coming from frameworks that escape by default.

But I guess you did have a bad experience of using it with your own site for Caddy (Curious what you are doing that you have so much HTML that needs to be embedded?), which is why I suggested as an option or maybe even a non-default caddy module.

(P.S. Let's not get into a *heated* argument over this 😉 Just throwing my ideas out there and not trying to force this on anyone)

**Comment by francislavoie** [comment]
> (Curious what you are doing that you have so much HTML that needs to be embedded?)

Markdown.

**Comment by segevfiner** [comment]
> Markdown

Makes sense.

> Also suppose someone wanted to serve non-HTML content (say some JSON, or YAML, or whatever), but rendered via templates. How do you suggest they'd do that if we used html/template? It would just be a hinderance.

Exactly why it needs to be optional. Either by making it an option of the handler, or a separate handler, and using caddy matchers, or some builtin match in the handler for HTML `Content-Type`s, as some frameworks do, or some other idea.
As you obviously can't use `html/template` to render non-HTML files.
