### ISSUE TITLE
The https://getcaddy.com/ website has an invalid TLS configuration

### ISSUE THREAD

**Issue by Bartvelp** [caddyserver/caddy#3788]
Hi,

So I am not sure this is the right place to say, but this should at least get some exposure.
I am not sure if [getcaddy.com](https://getcaddy.com/) is maintained, but it gives the following error in curl:
```
curl https://getcaddy.com
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```
In both Chrome and Firefox I am also getting TLS protocol errors, which is kind of ironic.
Please close if this is not the correct repo and let me know which one is.
I am located in The Netherlands if that makes any difference.

**Comment by francislavoie** [comment]
Yeah, that's a no longer maintained feature.

Caddy v2 has all kinds of better ways to install it now: https://caddyserver.com/docs/download

**Comment by Bartvelp** [comment]
Since there still is a lot of random guides on the internet referencing it, it would be nice if there was a script at getcaddy.com that just echo's it is not maintained and it should be installed using https://caddyserver.com/docs/download
