### ISSUE TITLE
curl https://getcaddy.com | bash -s personal tls.dns.cloudflare   ERROR

### ISSUE THREAD

**Issue by os9sur** [caddyserver/caddy#3789]
Is there anyone can help me please?  
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
![image](https://user-images.githubusercontent.com/6024166/95669398-fce6cb00-0bb2-11eb-85f3-0886309b624e.png)

**Comment by francislavoie** [comment]
That script is no longer supported. It was for v1 only.

For v2, please follow the instructions in the docs: https://caddyserver.com/docs/build#xcaddy
