### ISSUE TITLE
Php $_SERVER['REQUEST_URI'] ignores rewrite rules

### ISSUE THREAD

**Issue by prosperoking** [caddyserver/caddy#3795]
$_SERVER['REQUEST_URI'] does not pick the value of a rewrite rule 

```caddy
api.example.com {
    root * /var/www/
    rewrite * /api{uri}
    php_fastcgi unix//run/php/php7.4-fpm.sock
    file_server
    encode gzip
}
```
visiting api.example.com/test
```php
 echo $_SERVER['REQUEST_URI'];
// echoes /test instead of /api/test

```

caddy version: v2.2.0 h1:sMUFqTbVIRlmA8NkFnNt9l7s0e+0gw+7GPIrhty905A=

**Comment by francislavoie** [comment]
This is working as intended. REQUEST_URI is supposed to be the original URI before rewrites, and DOCUMENT_URI is the final URI after rewrites. https://github.com/caddyserver/caddy/blob/e34d9f1244439a01a195febd966c7c5d88c98d33/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L237
