### ISSUE TITLE
Virustotal says caddy_2.2.1_windows_amd64.zip is infected

### ISSUE THREAD

**Issue by ealib** [caddyserver/caddy#3798]
According to [Virustotal](https://www.virustotal.com/gui/file/c7a495ccee546d664ea1892e16fbb322495bd4d4cd68c2e566e60abacf14cb80), `caddy_2.2.1_windows_amd64.zip` contains **TrojanDropper.Dapato.acbs**.

Downloaded file has correct checksum

`e5c5fba6af33a0e1b48cbabc106e907dc7171c2cc337ee5c7cbbad07587dc4970c3f49812b3938dee43209b7fe293c74b36274fd809730ecec0041dd6b1fa93d`.

**Comment by francislavoie** [comment]
That's definitely a false positive. The releases are built with our CI job in GitHub Actions https://github.com/caddyserver/caddy/runs/1249044390

**Comment by mholt** [comment]
Virus total and other scanners are known to be garbage with Go binaries in general...
