### ISSUE TITLE
V2: sub sub domain issues

### ISSUE THREAD

**Issue by chrisroyall** [caddyserver/caddy#3799]
Hi there, 
I have an issue where I have configured a wildcard (several actually) using cloudflare dns as well as using on_demand for everything not matching the wildcard. On_demand works for the catchall as not too many domains point to our servers and the wildcard works great on subdomain level i.e. sub.domain.com, however, we are getting illegitimate requests on sub sub domains i.e. spam.sub.domain.com which application wise is not an issue as we handle these requests by redirecting them to a 404 page. The issue is that we are getting rate limited as these sub sub domain requests are not picked up by the wildcard (which I get is by design) but they are being picked up by the on_demand catch-all and therefore getting us rate limited. Is there a way I can block/deny/redirect or even configure another wildcard for the sub subdomains? 

This is my first time submitting a case so apologies if not done it correctly - I've seen other posts have formatted responses but couldn't find a template for this so not sure how to submit that. 
Thanks for help.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

You're meant to use the `ask` global option to prevent this:

https://caddyserver.com/docs/caddyfile/options

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
