### ISSUE TITLE
feature request: add header only if not already set

### ISSUE THREAD

**Issue by gilbsgilbs** [caddyserver/caddy#3804]
I'm in a case where I'd like the header directive to set the header only if it wasn't already set by an upstream server. Think it as a default value for headers. This would be useful for e.g. setting `Cache-Control` to `no-store` by default, except if the upstream server defines a specific `Cache-Control` value. I don't think it is possible yet (at least with the Caddyfile adapter).

The syntax could be inspired from the syntax used to append/delete headers:

```caddyfile
#      ↓
header ?Cache-Control "no-store" {
  defer
}
```

or alternatively using an explicit parameter (but that wouldn't make much sense when used in combination with +/- IMHO):

```caddyfile
header Cache-Control "no-store" {
  if_not_set
  defer
}
```

Would you accept such contribution? Or is it out of scope?

**Comment by mholt** [comment]
Sorry I'm just getting around to this now. Thank you for your time to contribute this!

One question, why won't this work?

```json
{
	"handler": "headers",
	"response": {
		"require": {
			"headers": {
				"Cache-Control": [""]
			}
		},
		"set": {
			"Cache-Control": ["no-store"]
		}
	}
}
```

The `headers` handler already has a mechanism for conditionally applying operations to response headers, so why add more complexity here?
