### ISSUE TITLE
Template delimiters

### ISSUE THREAD

**Issue by cyclecraze** [caddyserver/caddy#3808]
Documentation states that the directive "delimiters" controls the start and end of template code. It turns out the proper word is "between" based on reading/testing the code (Line #44 in cadyfile.go, as of commit '95ed603'. 

Also, should one decide to use single curly brackets, an error ensues. Alternatively, same error does not happen if single square brackets are used:

Caddyfile line: between "{" "}"
Error:  Caddyfile:40 - Error during parsing: Wrong argument count or unexpected line ending after 'between'

caddy version: v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=

platform: MacOS Catalina

**Comment by mholt** [comment]
Hmmm, where do you see that in the documentation? It says "between" here: https://caddyserver.com/docs/caddyfile/directives/templates

![Screenshot from 2020-10-29 14-42-42](https://user-images.githubusercontent.com/1128849/97630313-09618500-19f5-11eb-8b76-5bc63a9a7abc.png)

What is your full Caddyfile, how can we reproduce the bug?
