### ISSUE TITLE
How to serve different static sites using different path

### ISSUE THREAD

**Issue by SylleoYr** [caddyserver/caddy#3817]
Caddy version: v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
OS version: Windows 10 2004 (19041.572)

I want to use Caddy as a static server on my local machine, but the problem is that I cannot serve them using different path. I have tried the following three ways, but all failed:

**1.** 

```Caddyfile
:80 {
    encode gzip

    handle /nav/* {
        root public
        file_server
    }

    handle /nav2/* {
        root public2
        file_server
    }
}
```

**2.** 

```Caddyfile
:80 {
    encode gzip

    route /nav/* {
        root public
        file_server
    }

    route /nav2/* {
        root public2
        file_server
    }
}
```

**3.** 

```Caddyfile
:80 {
    encode gzip

    root /nav/* public
    root /nav2/* public2

    file_server
}
```

All the dirs of static sites and Caddyfile are in the same dir.

Did I misunderstand something with Caddy? 

An additional question is what the difference between `handle` and `route` directives? (I am confused with the docs and this issue #3738 )

_(May look like elementary questions, but appreciate for any answers.)_

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Caddy appends the request path to the root when looking for files on disk. I think you need to strip the path prefix after matching, which is what `handle_path` can do for you.

https://caddyserver.com/docs/caddyfile/directives/handle_path

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by SylleoYr** [comment]
I'm sorry to put my confusion here. Thanks a lot again.
