### ISSUE TITLE
use case of caddy

### ISSUE THREAD

**Issue by matty111** [caddyserver/caddy#3830]
i have three application in running in the following ports:

-  8080/*
-  8081/*
-  8082/*

i want to use caddy to call these application on the port 80:
-  80/app1/*
-  80/app2/*
-  80/app3/*

How i must write the caddyfile?

**Comment by ranisalt** [comment]
Along these lines:
```
handle_path /app1/* {
	reverse_proxy localhost:8080
}
handle_path /app2/* {
	reverse_proxy localhost:8081
}
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
