### ISSUE TITLE
consider enabling QUIC by default

### ISSUE THREAD

**Issue by marten-seemann** [caddyserver/caddy#3833]
[Chrome has enabled QUIC](https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html) for a large fraction of Chrome Stable. quic-go has been supporting draft-29 for a while now, and will add support for draft-32 in the next release (in case Chrome adds support for that version, which, as far as I know, they don't plan at this point).
quic-go has been the [default transport in IPFS](https://github.com/ipfs/go-ipfs/releases/tag/v0.6.0) and Filecoin for a few months already.

We might want to find a solution for #3055 first (or disable Retry entirely), so users will actually enjoy the reduced handshake latency (1 round-trip instead of 2 in the case of TLS 1.3 over TCP).

**Comment by Y-A-K-E** [comment]
If quic is enabled by default, AJAX or pjax requests PHP sites to not work

**Comment by marten-seemann** [comment]
@Y-A-K-E Why would that be? If so, that would be a bug. Can you share some more details?

**Comment by mholt** [comment]
Overall I'm open to this. Maybe later, once HTTP/3 is finalized and has broad client support.

As a data point, here's one case study where not binding to UDP by default is preferred: https://twitter.com/itstelesphoreo/status/1333457155324846085

**Comment by francislavoie** [comment]
We'll definitely want to add a `disable_http3` option, to flip it from opt-in (currently) to opt-out.

**Comment by marten-seemann** [comment]
> Overall I'm open to this. Maybe later, once HTTP/3 is finalized and has broad client support.

@mholt HTTP/3 is (basically) finalized. The QUIC transport documents have completed IETF Last Call a while back. The documents are now in the RFC editor queue, so it will still take a few months until the final RFCs are published. However, nobody expects any protocol changes at this point.
Chrome has enabled IETF QUIC by default, see https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html.

> As a data point, here's one case study where not binding to UDP by default is preferred: https://twitter.com/itstelesphoreo/status/1333457155324846085

This boils down to how to configure the `address:port` in the Caddyfile. Currently, saying `domain:443` means listen on TCP port 443, and with HTTP/3 enabled to also listen on port 443 for QUIC. Do we need a way to specify an alternative UDP port?
As QUIC support is advertised via Alt-Svc, any port would be discoverable by browsers after the first visit to the site. Of course, in the future, browsers might race a TCP and QUIC connection to the respective 443 ports, so having QUIC default to 443 definitely makes sense.

> We'll definitely want to add a disable_http3 option, to flip it from opt-in (currently) to opt-out.

@francislavoie +1

**Comment by mholt** [comment]
> Do we need a way to specify an alternative UDP port?

That might be useful sooner or later. Does the quic-go API have that ability? If so, we can find a way to expose it in Caddy.

> so having QUIC default to 443 definitely makes sense.

I agree; am just noting that there are cases where it will need to be configurable.

Thanks!

**Comment by marten-seemann** [comment]
> Does the quic-go API have that ability? If so, we can find a way to expose it in Caddy.

quic-go doesn't really care about the port. You pass a `net.PacketConn` to quic-go, so this entirely in the caller's responsibility.

**Comment by sagudev** [comment]
QUIC is now finalised as Proposed Standard in https://datatracker.ietf.org/doc/html/rfc9000

**Comment by awfulcooking** [comment]
:eyes:

**Comment by francislavoie** [comment]
We still need to solve https://github.com/caddyserver/caddy/issues/3055, https://github.com/caddyserver/caddy/issues/4348, and https://github.com/caddyserver/caddy/issues/4372 first, I think.

**Comment by mholt** [comment]
Yeah, probably no way this is going to happen until the feature is no longer experimental. But, sometime in the future, I do think it can happen.

**Comment by bt90** [comment]
Looks like there is only a single showstopper left: #3055

As the final HTTP/3 core specs are [very very very close](https://lists.w3.org/Archives/Public/ietf-http-wg/2022JanMar/0234.html), it would be cool if caddy would be one of the first to officially support it :wink:

**Comment by mholt** [comment]
@bt90 I agree. @marten-seemann can you please review #4707? It's not done yet, but I want to make sure I'm on the right track with AcceptToken().

Can people also please test that branch (`http3-default`). It'd be good to know how many things this will break before we release it sometime after v2.5.0.

**Comment by francislavoie** [comment]
There's also https://github.com/caddyserver/caddy/issues/4294 btw, i.e. `strict_sni_host` and client authentication not working with HTTP3

**Comment by mholt** [comment]
Good point; we probably won't be able to enable HTTP/3 if client auth is configured.

**Comment by masx200** [comment]
https://www.rfc-editor.org/rfc/rfc9114.html

**Comment by francislavoie** [comment]
What are you trying to say @masx200 ? We know about the RFC.

**Comment by masx200** [comment]
https://github.com/caddyserver/caddy/issues/4876

**Comment by otbutz** [comment]
With #4819 being fixed in the latest release, these are the missing bits:

- [ ] #4294
- [ ] #3055

**Comment by bt90** [comment]
Possibly #4849

**Comment by mholt** [comment]
Finally done in #4707. HTTP/3 will be enabled by default in Caddy 2.6.
