### ISSUE TITLE
reverseproxy: Add read_timeout/send_timeout options for HTTP transport

### ISSUE THREAD

**Issue by RussellLuo** [caddyserver/caddy#3841]
Per the doc of [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) directive, the timeout options available for transports are:
- HTTP: dial_timeout, tls_timeout
- FastCGI: dial_timeout, read_timeout, write_timeout (not documented, but found [in code](https://github.com/caddyserver/caddy/blob/937ec342010894f7a6239883b10f6a107ff82c9f/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L68-L75))

For the same reason listed [here](https://github.com/caddyserver/caddy/issues/2113#issuecomment-408840525), the read_timeout (like Nginx's [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout)) and send_timeout (like Nginx's  [proxy_send_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout)) options are also very useful for HTTP transport.

**Comment by francislavoie** [comment]
It is documented, see here:

- https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy/transport/http/
- https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy/transport/fastcgi/

But we haven't wired up those timeouts up yet in the Caddyfile adapter for the `fastcgi` transport yet, true.

The timeouts we have available to us for the `http` transport are driven by what's available in Go's stdlib https://golang.org/pkg/net/http/#Transport. We have no plans to override internal behaviour to provide more timeouts. It's non-trivial and risky, could have some unintended side-effects.

I'll mark this as a feature request for the `fastcgi` timeouts, because it's true, that could be wired up, and I see no reason not to.

**Comment by francislavoie** [comment]
Actually I realized the `http` transport has a few options missing from the Caddyfile as well:

- `dial_fallback_delay`
- `response_header_timeout`
- `expect_continue_timeout`
- `max_response_header_size`

So I'll wire those up as well.

**Comment by RussellLuo** [comment]
Yes, Go's [http.Transport](https://golang.org/pkg/net/http/#Transport) provides no read/write timeouts.

After googling, I found these two solutions:
- [Use context.Context with time.Timer to control read timeout](https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/) 
- [Implement a dialer to set read and write timeouts](https://gist.github.com/c4milo/275abc6eccbfd88ad56ca7c77947883a)

**Comment by mholt** [comment]
Yeah, read/write timeouts in a transport require overriding the Dialer if I recall correctly. We haven't done this (yet) because, well, you're in control of your reverse_proxy backends (or at least, you should be -- most of the time) and it hasn't come up before.

What do you need them for?

**Comment by RussellLuo** [comment]
While using Nginx, we usually leverage read/write timeouts to protect HTTP connections from being occupied too long by some SLOW requests or responses, when their corresponding upstream behaves badly.

In this way, before we take action, the total concurrent connections opened by Nginx (or Caddy) can be controlled effectively, without heavily affecting other upstreams (maybe more important) reversely proxied by the same Nginx (or Caddy) instance.

**Comment by RussellLuo** [comment]
After digging into the docs, I think setting the [upstreams/max_requests](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy#upstreams/max_requests) option can address the connection number problem I mentioned above.

Maybe there are other use-cases of Nginx's [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout) and [proxy_send_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout), looking forward to thoughts from other folks :-)

**Comment by mholt** [comment]
@RussellLuo I had a few minutes while triaging issues today so I went ahead and implemented this real quickly. Can you try it out? #4905
