### ISSUE TITLE
Strange log behavior

### ISSUE THREAD

**Issue by tobyliu415** [caddyserver/caddy#3858]
### 1a. Operating system and version
CentOS Linux release 8.2.2004 (Core)

### 1b. Caddy version (run `caddy version` or paste commit SHA)
[toby@homerouter ~]$ caddy version
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=

### 2a. What happens (briefly explain what is wrong)
Some of logs goes the wrong way.

## 3. Tutorial (minimal steps to reproduce the bug)
*** always reproduce on my system ***
Content of Caddyfile:
------------Cut Here---------------
http://isatap:8087 {
        reverse_proxy http://127.0.0.1:9999
        log {
                output file /home/toby/isatap.access.log
        }
}
------------Cut Here---------------
1. Start caddy
2. set browser proxy to http://{IP}:8087
3. browse isatap
4. caddy reverse_proxy the content, but not logged to /home/toby/isatap.access.log

**Comment by Mohammed90** [comment]
Not able to reproduce it at all. I've tested to the extent of validating Caddy logs an error if it isn't able to open/write to the designated location, so it prints something like:
`2020-11-08 21:33:44.67734 +0300 +03 m=+7.787276712 write error: can't make directories for new logfile: mkdir /forbidden/path: operation not supported`

Are you sure stdout/stderr do not print that line? Otherwise, I'm suspecting this step is not as innocent as it seems:
`set browser proxy to http://{IP}:8087`. What do you mean by "set browser proxy"?

**Comment by tobyliu415** [comment]
### 1. It's really complex.
### 2. Consider configuration like this
-------------------------
http://isatap:8087 {
reverse_proxy {realservice}
log {
output file /home/toby/isatap.access.log
}
}
-------------------------
### 3. set browser's setting let it use the server **IP address** as **HTTP proxy**
so that everything you are trying to browse will redirected to **the caddy server** no mater what you typed in the browser.
### 4. browse the realservice using http://isatap as host 
if you browse **http://isatap:8087** everything goes well, but if you browse **http://isatap**, the caddy server will serve it, but not logged the the specified file.

**Comment by mholt** [comment]
How is Caddy serving `http://isatap` on port 80? The only site in your config is for port 8087.

**Comment by tobyliu415** [comment]
Caddy is listening only on port 8087. but the browser uses http://caddyip:8087 as **http proxy**. So the traffic of http://caddy will also goes to http://caddyip:8087. 

Consider the following code:
curl http://isatap -x http://127.0.0.1:8087
---------------------
The server will output log to stderr:

2020/11/09 06:01:34.157 INFO    http.log.access handled request {"request": {"remote_addr": "127.0.0.1:34832", "proto": "HTTP/1.1", "method": "GET", "host": "isatap", "uri": "http://isatap/", "headers": {"Accept": ["*/*"], "Proxy-Connection": ["Keep-Alive"], "User-Agent": ["curl/7.61.1"]}}, "common_log": "127.0.0.1 - - [09/Nov/2020:14:01:34 +0800] \"GET http://isatap/ HTTP/1.1\" 302 93", "duration": 0.032788429, "size": 93, "status": 302, "resp_headers": {"X-Permitted-Cross-Domain-Policies": ["none"], "Content-Type": ["text/html; charset=utf-8"], "X-Gitlab-Feature-Category": ["projects"], "X-Request-Id": ["vC0Owl3yyB3"], "X-Xss-Protection": ["1; mode=block"], "Set-Cookie": ["experimentation_subject_id=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVm1PVEF4TXpZNExUVXlaak10TkRaa1pTMWlaVGRpTFdNNU16RTVOamszTm1Jd09TST0iLCJleHAiOm51bGwsInB1ciI6ImNvb2tpZS5leHBlcmltZW50YXRpb25fc3ViamVjdF9pZCJ9fQ%3D%3D--88e0565c1322a30fa5fa15c1e6f5b21c49e0ba8b; path=/; expires=Fri, 09 Nov 2040 06:01:34 GMT; HttpOnly"], "X-Content-Type-Options": ["nosniff"], "X-Download-Options": ["noopen"], "X-Ua-Compatible": ["IE=edge"], "X-Runtime": ["0.018667"], "Strict-Transport-Security": ["max-age=31536000"], "Cache-Control": ["no-cache"], "Content-Length": ["93"], "Server": ["Caddy", "nginx"], "Referrer-Policy": ["strict-origin-when-cross-origin"], "X-Frame-Options": ["DENY"], "Date": ["Mon, 09 Nov 2020 06:01:34 GMT"], "Location": ["http://isatap/users/sign_in"]}}

**Comment by mholt** [comment]
Ok. Well, that makes sense then... the `Host` header is `isatap` not `isatap:8087` because the proxying is hiding the true host from Caddy in the request, so it doesn't know it should log that request. I can see how this is counter-intuitive but that's what happens when you use a proxy. This can be tuned in the JSON config, however (use `caddy adapt` as your starting point).

(Closing, as it's not a bug in Caddy.)

**Comment by tobyliu415** [comment]
-----------The corrected config file is like this-----------------
{
 "logging": {
  "logs": {
   "default": {
    "writer": {
     "filename": "/home/toby/isatap.access.log",
     "output": "file"
    }
   }
  }
 },
 "apps": {
  "http": {
   "servers": {
    "srv0": {
     "listen": [
      ":8087"
     ],
     "routes": [
      {
       "match": [
        {
         "host": [
          "isatap"
         ]
        }
       ],
       "handle": [
        {
         "handler": "subroute",
         "routes": [
          {
           "handle": [
            {
             "handler": "reverse_proxy",
             "upstreams": [
              {
               "dial": "127.0.0.1:9999"
              }
             ]
            }
           ]
          }
         ]
        }
       ],
       "terminal": true
      }
     ],
     "automatic_https": {
      "skip": [
       "isatap"
      ]
     },
     "logs": {
      "logger_names": {
       "isatap": "default"
      }
     }
    }
   }
  }
 }
}
