### ISSUE TITLE
Implementing a "pass-through" option in a handler

### ISSUE THREAD

**Issue by rayjlinden** [caddyserver/caddy#3864]
I've had a feature request to add a "pass-through" option in my S3 proxy.  The idea being if a 404 would occur then just pass on such that the next directive could serve the item.  (I think his intent is to load S3 with requested items basically making a cache for large objects.)

I had seen the "file serve" directive in CaddyV1 had such an option.  However, the file serve directive in Caddy2 does not?!?

In any case, I'm not sure what I need to do to "pass through" to the next directive?  Any guidance would be appreciated.

**Comment by mholt** [comment]
> I had seen the "file serve" directive in CaddyV1 had such an option. However, the file serve directive in Caddy2 does not?!?

Hm? Caddy v1 had no file_server directive. Only caddy 2 has it, and it has the option:

https://github.com/caddyserver/caddy/blob/95af4262a8adf12e0c5eb178d9e521903eb8b0e4/modules/caddyhttp/fileserver/staticfiles.go#L76-L79

Implementing pass-thru is really easy:

https://github.com/caddyserver/caddy/blob/95af4262a8adf12e0c5eb178d9e521903eb8b0e4/modules/caddyhttp/fileserver/staticfiles.go#L423-L425

**Comment by mholt** [comment]
Anyway if you have any other questions feel free to ask.
