### ISSUE TITLE
Default settings with proxy server cert error

### ISSUE THREAD

**Issue by kpvf** [caddyserver/caddy#3869]
Hi thanks for the great software first and foremost.
So i have nodejs in the backend, set up on Intranet server in my company. From the documentation what I understand is after setting up Caddy and running caddy trust then running proxy it should automatically gives me tls which works great but I have a little problem with this as in chrome, Firefox and edge it says ERR_CERT_AUTHORITY_INVALID.
I will add that I have this over IP not host name or so as I did not have a time yet to set up dns but either way it should not matter as ip in intranet can be validated as trusted? I did before quick run on my localhost and everything run as it should after few restarts.
Can someone please point me out where I make/made mistake or is it expected behaviour.
Thanks

**Comment by mholt** [comment]
You usually have to restart the browser, and sometimes the trust commands don't work depending on the platform and other factors; so just make sure the Caddy root certificate is in whatever trust store the browser is using.
