### ISSUE TITLE
Caddy doesn't currently notify systemctl when it is properly loaded

### ISSUE THREAD

**Issue by eip618** [caddyserver/caddy#3876]
Could this be implemented by calling `sd_notify(0, "READY=1");` when initial config has loaded and is being served/requests can be accepted?

**Comment by francislavoie** [comment]
Looks simple enough:

https://github.com/coreos/go-systemd/blob/master/daemon/sdnotify.go

It would need to only be done on Linux though.

**Comment by gdhameeja** [comment]
I'd like to work on this.

**Comment by gdhameeja** [comment]
Hey All, sorry for not being able to work on this so far. Will raise a pull for this shortly.

**Comment by mholt** [comment]
Implemented in #3963, for some reason it didn't link
