### ISSUE TITLE
Multiple servers with the same port produces no logs with log handler

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/caddy#3878]
The following configuration:
```
http://localhost:2020 {
    log
    file_server
}

:2020 {
    respond 404
}
```

Doesn't produce any access logs when trying to access any existing file served by the `file_server`.

**Comment by mholt** [comment]
Thanks; fixed in 63afffc. Please try it out to confirm!

**Comment by segevfiner** [comment]
Looks working.

P.S. It looks like the order of some things like response headers in log messages is not deterministic, that's kinda confusing, should I open a separate issue about that?

**Comment by mholt** [comment]
Great!

The order of header fields has to do with the implemention of Go maps, which are not sorted. We use a zero-allocation logger so yes, performance is one benefit of the unsorted fields. We probably won't sacrifice performance just to sort JSON fields. You can use a different log format if you want something less efficient and/or sorted.

**Comment by mholt** [comment]
(Apparently my fix had bugs, fixed in https://github.com/caddyserver/caddy/pull/5102.)
