### ISSUE TITLE
  Where does Caddy2 keep their TLS certificates?

### ISSUE THREAD

**Issue by brianler** [caddyserver/caddy#3887]
i can't find website's '.crt .key' files.

**Comment by francislavoie** [comment]
It's mentioned here in the docs: https://caddyserver.com/docs/conventions#file-locations

**Comment by brianler** [comment]
> locations

can u help? i still can't find the '.crt' & '.key' files in the path '$HOME/.local/share/caddy'. 
my system is debian9, using 'dpkg -i' line to install caddy2.2.1, using 'systemctl start caddy' line to run.

**Comment by francislavoie** [comment]
The .deb creates a `caddy` user and installs the systemd service file which uses that user. The home for the `caddy` user is `/var/lib/caddy`

**Comment by brianler** [comment]
> The .deb creates a `caddy` user and installs the systemd service file which uses that user. The home for the `caddy` user is `/var/lib/caddy`

i found it. thank you so much!
