### ISSUE TITLE
Simplify skipping file_server when static files do not exist?

### ISSUE THREAD

**Issue by EmmanuelOga** [caddyserver/caddy#3890]
Hi!

As a first time user of Caddy, I was trying to setup a way to setup a service plus static files serving:

* If there's a file on /static, serve it (ex: serve `/index.css` if `./static/index.css` exists)
* If no file was served, route to another service.

My first attempt:
```
host
root * ./static
file_server
reverse_proxy 127.0.0.1:3000
```

... to me, the natural thing to happen would be that the `file_server` would attempt a match and if not it would proceed to the reverse_proxy. But it seems if `file_server` was selected to serve a request it would be the end of it, even if the file did not exist!

I learnt through hours of reading the docs and finding [articles like this one](https://caddy.community/t/composing-in-the-caddyfile/8291) that routing can be pretty intricate, but all that reading did not get me closer to solve my problem: the actual solution involved a directive I did not even think about, `try_files` !.

Finally, I was lucky enough to find these two posts:
* https://caddy.community/t/v2-try-file-server-first/6440/6
* https://caddy.community/t/v2-unrecognized-directive-not/6815 

My final config looks something like:
```
host {
	root * ./static

	# Check if the file exists.
	@notStatic {
		not {
			file {
				try_files {path}
			}
		}
	}

	# Serve the app if there's not a static file.
	reverse_proxy @notStatic 127.0.0.1:3000

	# Serve the static file otherwise.
	file_server
}
```

This got me thinking, people stumbled with this before, and here I'm again having trouble with the same issue. Would it be possible to add a parameter to file_server to only match if a static file is found? It would simplify the config and hopefully could be made to be backward compatible to avoid messing with existing configs.

I'm thinking something like:

```
host 
root * ./static
reverse_proxy 127.0.0.1:3000
file_server if-matches-path
```
... I'm not sure what a good syntax would be for this but you get the idea.

Thank you!

**Comment by francislavoie** [comment]
You can shorten it to this:

```
host {
	root * ./static
	@notStatic not file
	reverse_proxy @notStatic 127.0.0.1:3000
	file_server
}
```

This uses single-line matcher syntax, and the shortcut for the `file` matcher which defaults to doing `try_files {path}`, because it's a common need.

It's not a good idea to move request matching logic into handlers. This was a problem Caddy v1 had, where each handler would all have their own ways of matching requests, and it became a mess when trying to follow how a particular request would be handled.

Caddy v2 solved a major problem by separating the two concepts - that way you can match requests in any way you want instead of just the few specific ways the handler might implement.

For next time, please first ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by EmmanuelOga** [comment]
This was a **feature request** actually, I was asking for something like `file_server if-matches-path`, using info from the docs and existing forum posts to inform my request.

I guess next time I can ask the question "should this be a feature request?" in the forums before filling a bug, just in case.

You provide great details on why the feature I'm asking for is not good though! (plus the shortcut I did not find myself on the docs or the forums). The things you mention sound like a good candidate for addition on https://caddyserver.com/docs/caddyfile/patterns.

Thank you!

**Comment by EmmanuelOga** [comment]
Hi again,

Just a note that the proposed "short" solution doesn't seem to work so I went back to the longer version for now (which does work). I made sure to reload the `Caddyfile` and I even stop and restarted the server just in case to no avail.

Win10,
````
❯ caddy version
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
```

**Comment by francislavoie** [comment]
I don't see how the short version wouldn't work. I have to assume you made a mistake in your config. They both adapt to the same thing with `caddy adapt` aside from the `file` matcher which doesn't have `try_files`, but logic makes it default to the request path.

https://github.com/caddyserver/caddy/blob/4afcdc49d14855c0c3a4fd4558d0f81906db3ffb/modules/caddyhttp/fileserver/matcher.go#L178

You'll need to elaborate. What "doesn't seem to work"? Be specific.

**Comment by EmmanuelOga** [comment]
This is my exact Caddyfile:

```
localhost {
	root * ./static

	# Verbose Check.
	@notStatic {
		not {
			file {
				try_files {path}
			}
		}
	}

        # Short check.
	# @notStatic not file

	# Serve the app if there's not a static file.
	reverse_proxy @notStatic 127.0.0.1:3000

	# Serve the static file otherwise.
	file_server
}
```

These are the steps to replicate:

Win10, caddy version v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
File structure:
```
./Caddyfile
./static/plain.text
```
* Run a service serving a response "Hello world" no matter the request, on `http://localhost:3000`
* Uncomment either the verbose or the short check on the Caddy file and reload the configuration.

### With verbose check
* Request `https://localhost/plain.text`: Caddy serves the file
* Request any other path, example, root path: `https://localhost`: Caddy serves "Hello world"

### With short check
* Request `https://localhost/plain.text`: Caddy serves the file
* Request any other path, example, root path: `https://localhost`: **Caddy serves a 404** (expected: "Hello world")

**Comment by francislavoie** [comment]
`@notStatic not file try_files {path}` is not correct, it would need to be `@notStatic not file {path}`. It still works because it looks for a file on disk named exactly `try_files` and doesn't find it, so it moves on every time. Wastes an IO cycle on every request.

Still not sure why `not file` isn't working for you though... that is meant to work. Will take a closer look.

Also, @mholt mentioned to me a few minutes ago that https://caddyserver.com/docs/modules/http.handlers.file_server#pass_thru is already a thing, so I think we already have what you wanted implemented, but only in JSON right now. Forgot it was a thing.

I'll re-open this since we can add that option to the Caddyfile trivially, and we'll need to take a look at the `file` matcher behaviour.

**Comment by mholt** [comment]
Hey, so I finally read through the whole issue so far, and even tried your instructions (with minor changes, I replaced `reverse_proxy` with `respond` and am just serving the root of my current directory, which is the cmd/caddy subfolder of this repo), but I can't reproduce the behavior you're describing.

Caddyfile:

```
localhost {
	#root * ./static

	# Verbose Check.
	@notStatic {
		not {
			file {
				try_files {path}
			}
		}
	}

	# Short check.
	#@notStatic not file

	# Serve the app if there's not a static file.
	#reverse_proxy @notStatic 127.0.0.1:3000
	respond @notStatic "Yahaha! You found me!"

	# Serve the static file otherwise.
	file_server
}
```

Command:

```
$ curl -v "https://localhost/main.go"
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Nov 30 19:13:26 2020 GMT
*  expire date: Dec  1 07:13:26 2020 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b49ca55db0)
> GET /main.go HTTP/2
> Host: localhost
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< accept-ranges: bytes
< etag: "qj8pai11w"
< last-modified: Tue, 03 Nov 2020 21:35:06 GMT
< server: Caddy
< content-length: 1364
< date: Mon, 30 Nov 2020 19:25:31 GMT
< 
... (file contents here, as expected) ...


$ curl -v "https://localhost/notfound"
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Nov 30 19:13:26 2020 GMT
*  expire date: Dec  1 07:13:26 2020 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x556387c29db0)
> GET /notfound HTTP/2
> Host: localhost
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< server: Caddy
< content-length: 21
< date: Mon, 30 Nov 2020 19:25:56 GMT
< 
* Connection #0 to host localhost left intact
Yahaha! You found me!
```

Then changing the Caddyfile to use the short form:

```
localhost {
	#root * ./static

	# Verbose Check.
	# @notStatic {
	# 	not {
	# 		file {
	# 			try_files {path}
	# 		}
	# 	}
	# }

	# Short check.
	@notStatic not file

	# Serve the app if there's not a static file.
	#reverse_proxy @notStatic 127.0.0.1:3000
	respond @notStatic "Yahaha! You found me!"

	# Serve the static file otherwise.
	file_server
}
```

These commands:

```
$ curl -v "https://localhost/main.go"
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Nov 30 19:13:26 2020 GMT
*  expire date: Dec  1 07:13:26 2020 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x559778ed2db0)
> GET /main.go HTTP/2
> Host: localhost
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< accept-ranges: bytes
< etag: "qj8pai11w"
< last-modified: Tue, 03 Nov 2020 21:35:06 GMT
< server: Caddy
< content-length: 1364
< date: Mon, 30 Nov 2020 19:28:23 GMT
< 
... (file contents here, as expected) ...

$ curl -v "https://localhost/notfound"
*   Trying 127.0.0.1:443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Nov 30 19:13:26 2020 GMT
*  expire date: Dec  1 07:13:26 2020 GMT
*  subjectAltName: host "localhost" matched cert's "localhost"
*  issuer: CN=Caddy Local Authority - ECC Intermediate
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b1f1391db0)
> GET /notfound HTTP/2
> Host: localhost
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200 
< server: Caddy
< content-length: 21
< date: Mon, 30 Nov 2020 19:29:03 GMT
< 
* Connection #0 to host localhost left intact
Yahaha! You found me!
```

All is working as expected. (Unless I am totally misunderstanding your question/instructions? Which is possible.)

**Comment by mholt** [comment]
Closing due to irreproducibility and inactivity.
