### ISSUE TITLE
Looks like header directive is broken

### ISSUE THREAD

**Issue by dtelyukh** [caddyserver/caddy#3891]
On current master-branch such configuration fails:

```
https://caddytest.localhost {
    tls internal
    @staticAssets {
        path /img/*
    }
    header @staticAssets {
        Cache-Control "public, max-age=3600, stale-while-revalidate=86400"
    }
}
```

The error message: `run: adapting config using caddyfile: parsing caddyfile tokens for 'header': Caddyfile:7 - Error during parsing: cannot specify headers in both arguments and block`

On v2.2.1 it is OK.

**Comment by francislavoie** [comment]
Thanks, I can confirm it broke in b0d5c2c8ae076393e7a3ad59ce875027f4c29304. Taking a look.

**Comment by francislavoie** [comment]
Wrote a fix in https://github.com/caddyserver/caddy/pull/3892

Thanks so much for reporting! Glad to catch it before our v2.3 release 😄

**Comment by mholt** [comment]
Thank you both! Really appreciate it :) Thanks for using the master branch @dtelyukh !
