### ISSUE TITLE
Caddyfile encoder

### ISSUE THREAD

**Issue by libesz** [caddyserver/caddy#3893]
I would like to manipulate Caddyfiles (actually CoreDNS configurations) with the `caddyfile` package. There are several ways to parse with the package, but the only way to encode the content back after manipulation is the one where the parsed content is represented as JSON text. So I went ahead and tried to use that one, but if the parsed content contains imports, it fails in `ToJSON` as I can not pass a filename (with a path) for the parser, where it could find the imported content in the same directory.
The current manipulation what I try to achieve is basically to find a specific ServerBlock, change the key of it and write back to a new, imported file. This means I actually don't care about the parsed content, I just want to encode it back the way it was originally.
Assuming there is no existing way for what I try to achieve, would it be possible to:
* Either pass a suspected filepath to the `ToJSON` function, similarly how `Parse' gets it
* Or create an encoder function pair for the existing `Parse` function.

**Comment by hairyhenderson** [comment]
> I would like to manipulate Caddyfiles (actually CoreDNS configurations)

CoreDNS actually builds on top of a stripped-down fork of Caddy v1 - https://github.com/coredns/caddy. In Caddy v2 the Caddyfile format changed significantly, such that it probably wouldn't work for your CoreDNS use-case...

**Comment by libesz** [comment]
Thanks for the fast response. Yes, I am aware that CoreDNS uses it's own copy, actually I wanted to use their fork. However I was not aware that the file format changed from v1 to v2.
Is there any chance for v1 enhancements then?

**Comment by francislavoie** [comment]
>  Is there any chance for v1 enhancements then?

No, we no longer maintain Caddy v1. We've marked it EOL as of Oct 1st.
