### ISSUE TITLE
Remove certificate migration code

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#3894]
Caddy and CertMagic contain code that converts certificates from older formats and folder structures to newer ones. It only needed to be run one time, if upgrading from (really) old versions. Most of this code has been in place for years already, and most of it caters to v1-and-v2-beta-era Caddy and its contemporary CertMagic, which has not been in use for quite some time, and the v2 beta versions were never realeased (stable) in the first place. So I think pretty much everyone who needs it has used it already.

This extra code can be removed to simplify the code base, and it'll be easy enough to put up the source code for a simple CLI tool that can do the conversion manually if anyone else still needs it. I've already created such a tool for a customer's deployment so I just need to polish it a little and post the code when I remove it from Caddy and CertMagic.

**Comment by tobya** [comment]
I'm still on 1.04x if I upgrade to v2 will this removal affect my migration.

I presume the worst that happens is that LE needs to issue new certs all in one go?

**Comment by mholt** [comment]
Don't miss the part where I said I'll post the migration code in a `main()` so you can run it as a CLI tool, so it will still be possible to automate. You'll want to double-check that everything worked properly. But yeah, if you don't move the certs over, Caddy will just get new certificates. If you have in the range of, say, 10-100 certs, this won't be a problem.

You should upgrade to v2 ASAP anyway though.

**Comment by tobya** [comment]
> You should upgrade to v2 ASAP anyway though.

Yes I know. I was waiting for the `on` directive to be migrated, but I dont think it is going to be, so I'll take another look at it.

**Comment by mholt** [comment]
@tobya Ah yes, that's right. I just need to make some time and sit down and figure out a design for the eventing system. That's kind of related to #2344.

**Comment by francislavoie** [comment]
Reminder about this @mholt, still want to do it in v2.4.0?

**Comment by mholt** [comment]
Yeah. I'm still extracting the code into a separate `main()`. Maybe I'll just finish that now.

**Comment by mholt** [comment]
Ad-hoc migration program can be found here: https://gist.github.com/mholt/f3a7277e54b26938401638d5786cd0d6

Tested it a couple times, seemed to work alright. **Be sure to back up your files before using it!!** Also, I don't have a ton of time to support it, so you're on your own (unless you're sponsoring, I guess) -- but for anyone finding this later, it's probably OK for the vast majority of you to just let Caddy regenerate needed assets the one time. If you find and fix a bug in the program, feel free to comment on the gist. Otherwise, you can get help in our forums: https://caddy.community
