### ISSUE TITLE
how to rewrite for crawler 

### ISSUE THREAD

**Issue by erwzqsdsdsf** [caddyserver/caddy#3899]
aaa.xxx.com {
@bot {
header User-Agent *bot*
#header User-Agent *yandex*
#header User-Agent *baiduspider*
#header User-Agent *facebookexternalhit*
#header User-Agent *embedly*
#header User-Agent *quora\slink\spreview*
#header User-Agent *outbrain*
#header User-Agent *pinterest*
}

      root * /root/data/hadi
        rewrite /auth/* /index.html
 
        rewrite @bot  http://172.16.1.1xx:1337/{uri}
}

not work. 

 curl --user-agent "Googlebot/2.1 (+http://www.google.com/bot.html)"  https://aaaa.xxxx.com/ 
return empty

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
