### ISSUE TITLE
Placeholder for directives `log`

### ISSUE THREAD

**Issue by 1-1-2** [caddyserver/caddy#3900]
I try to use a Snippets to simplify the log setting
```Caddyfile
(logging) {
    log {
        output file /path/to/log/{host}/access.log {
            roll_size 10MiB
            roll_keep 10
        }
        format console
        level INFO
    }
}
```
then i enable it in my website configuration
``` Caddyfile
my.domain.com {
    ...
    import logging
    ...
}
```

However, it turns out that the  `log` directives doesn't support placeholder {host} and causes an error `run: loading initial config: loading new config: setting up custom log 'log1': loading log writer module: loading module 'file': provision caddy.logging.writers.file: invalid filename for log file: unrecognized placeholder {http.request.host}` .

It might be a good idea to have the `log` support placeholder or just some of them like {host} so i can have different path for each website i host with just a line `import logging` in the configuration.

**Comment by francislavoie** [comment]
Sorry, it's not possible. Files are opened when the server starts up, not on every request.
