### ISSUE TITLE
caddy certificates letsenscrypt

### ISSUE THREAD

**Issue by InfRandomness** [caddyserver/caddy#3905]
Hello, I am new to caddy and use caddy 2 as a reverse proxy towards some sites on my homelab (redirected by cloudflare with proxying enabled).

I have gotten my own ssl certificate and private key from cloudflare but yet, it looks like caddy is still trying to pull an ssl certificate from letsencrypt and tries to solve a challenge still.

Is this a normal behavior ? How to prevent it from using letsencrypt since I am using my own certificate ?

caddy version = v2.2.1
os = fedora server 33
kernel = 5.9.11-200.fc33.x86_64

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
