### ISSUE TITLE
Add support for dynamic upstream path

### ISSUE THREAD

**Issue by gucki** [caddyserver/caddy#3914]
In nginx variables can be used in the upstream's path, for example:

    server_name ~^(?<subdomain>.+?)\..+$;
    proxy_pass http://unix:/sockets/$subdomain/app.sock:$request_uri;

Would be great if Caddy would support that too.

**Comment by mholt** [comment]
You can already manipulate both the upstream address and the path of the request in Caddy 2. There is nothing to do here.

If you still have questions, please feel free to ask on our forums! https://caddy.community
