### ISSUE TITLE
Feature Request: Automatic Fallback to HTTP

### ISSUE THREAD

**Issue by shibumi** [caddyserver/caddy#3921]
It would be nice if it would be possible to configure a fallback to HTTP if HTTPS runs into errors with Let's Encrypt. In my case I hit the Let's Encypt rate limit and my whole server was down, I had to reconfigure the server and redeploy it. With an automated fallback to HTTP this wouldn't happen. 

I have to admit that this is a rare scenario, because normally rate limit violations should not happen and every website should have HSTS.

**Comment by mholt** [comment]
Sorry, we will not automatically fall back to an insecure protocol.
