### ISSUE TITLE
Caddy validate fails with custom storage module

### ISSUE THREAD

**Issue by masipcat** [caddyserver/caddy#3926]
I'm using Caddy 2.3.rc1 with [tlsredis](https://github.com/gamalan/caddy-tlsredis) (and other plugins). This is a simplified version of the Caddyfile I'm using:

```
{
	storage redis {
	  host          "redis-caddytls"
	  port          6379
}
```

## The problem

I run `caddy validate` on CI job and the command fails with:

```
{"level":"info","ts":1608032286.5366383,"msg":"using provided configuration","config_file":"-","config_adapter":"caddyfile"}
{"level":"info","ts":1608032286.640901,"logger":"caddy.storage.redis","msg":"TLS Storage are using Redis, on redis-caddytls:6379"}
validate: loading storage module: loading module 'redis': provision caddy.storage.redis: dial tcp: lookup redis-caddytls on 213.133.100.100:53: no such host
```

The plugin is initiating the redis connection in [`Provision()` method](https://github.com/gamalan/caddy-tlsredis/blob/26bbcc8c3e979ffe5e26ef2d7228f7a6bb2218ef/storageredis.go#L252). I think it's the correct place to do it with the current Module interface and that's why opening the issue here.

Thank you in advance! :)

**Comment by francislavoie** [comment]
Looks like your DNS server at `213.133.100.100:53` isn't able to resolve `redis-caddytls` to a real IP address. This doesn't look like a problem with Caddy, but instead something wrong with your environment causing it to not be able to resolve that name.

Also, it looks like you're missing a `}` in your config, make sure to fix that!

**Comment by masipcat** [comment]
> Looks like your DNS server at `213.133.100.100:53` isn't able to resolve `redis-caddytls` to a real IP address. This doesn't look like a problem with Caddy, but instead something wrong with your environment causing it to not be able to resolve that name.

But this is totally expected. I don't have a redis while I run `caddy validate` in the CI pipeline. The point is that  it should be a way to validate the Caddyfile without trying to connect to the storage.

**Comment by mholt** [comment]
Perhaps -- although we do not maintain the redis module, so there's not really anything we can do with this. You should probably open an issue with the plugin developer.

**Comment by francislavoie** [comment]
IMO it does make sense to try to connect during validation though, because the point of validation is to confirm whether the config as-is _would work_ if run.

**Comment by masipcat** [comment]
> Perhaps -- although we do not maintain the redis module, so there's not really anything we can do with this. You should probably open an issue with the plugin developer.

I opened the issue here because this also happens with others modules, like s3. I thought that maybe it would make sense to add a new method to explicitly `Prepare/Init` (with a better name) the Module.

> Provision() is the right place for it, as the point of validate is to tell you as sure as possible whether the config will run when loaded. If your storage backend is down, that'll be a problem you should fix. I think this is fine, personally.

Yeah, given the current interface I understand it's the right place (and the only possible one) to do the initialization, but I thought the purpose of the command validate was just checking the syntax without doing any other side-effect, as it says in the doc:

> This command deserializes the config, then loads and provisions all of its modules as if to start the config, but the config is not actually started.

Anyway, I understand your point of view. It's a bit inconvenient if the storage it's only accessible inside the cluster, because this means I can't validate the config without running the command inside the cluster or starting a redis to simulate cluster.

**Comment by masipcat** [comment]
To clarify my point of view: I was thinking of `caddy validate` as a "syntax linter" or a `caddy run --dry-run`. And for the same reason that Caddy doesn't try to resolve the upstream in a `reverse_proxy` directive, I was expecting the same for the `storage`.

You will say that this is implemented in the plugin so I should open the issue there, but I think that the only place that this initialization can be done right now is in the `Provision()` so that's why I said that maybe a new method would help to split the logic.

Sorry if I sound a bit rude, english it's not my main language

**Comment by francislavoie** [comment]
Well, Caddy cannot successfully run if storage is non-functional, but Caddy can run if a proxy is not reachable (will just return error 502), so those are definitely different classes of problems.

The `caddy adapt` command is likely more useful for you here to validate that the Caddyfile at least maps to a JSON config. That won't attempt to provision modules though. It should probably be enough for your needs.

**Comment by mholt** [comment]
>  thought the purpose of the command validate was just checking the syntax without doing any other side-effect, as it says in the doc:

To be fair -- and I understand English is not your primary language -- the docs don't mention anything about syntax or side-effects. They literally say that the point of validate is to "load and provision" the modules. What a module considers a provisioning step is up to each individual module. IMO provisioning should avoid side-effects, but what is defined as a "side-effect" is unclear too. Dialing a network connection might not be considered a side-effect because it... doesn't have any side-effects, like, there's no state change or anything there.

If a module can't be provisioned, then something is wrong and it needs to be fixed. It's as simple as that. If you try to run Caddy in the wrong environment for iits given configuration, it won't work.

**Comment by masipcat** [comment]
> The `caddy adapt` command is likely more useful for you here to validate that the Caddyfile at least maps to a JSON config. That won't attempt to provision modules though. It should probably be enough for your needs. You can also use the `caddy fmt` command to make sure your config is using good indentation etc.

Ok, thank you! I'll try that

**Comment by masipcat** [comment]
> To be fair -- and I understand English is not your primary language -- the docs don't mention anything about syntax or side-effects. They literally say that the point of validate is to "load and provision" the modules. What a module considers a provisioning step is up to each individual module. IMO provisioning should avoid side-effects, but what is defined as a "side-effect" is unclear too. Dialing a network connection might not be considered a side-effect because it... doesn't have any side-effects, like, there's no state change or anything there.

Thank you for the clarification

> If a module can't be provisioned, then something is wrong and it needs to be fixed. It's as simple as that. 

Ok, that makes sense.

Thank you for your time!
