### ISSUE TITLE
consider allowing use of an alias for the key name of the `routes` array in Caddy JSON

### ISSUE THREAD

**Issue by jmellicker** [caddyserver/caddy#3927]
Would anyone consider it a good idea to allow Caddy users to use an alias (different key name) in the JSON for the `routes` array (like `rules`, `blocks`, `server_blocks`, etc.)?

The key name "routes" has been confusing, since the question arises "when you say 'route', are you talking about the Caddy route, or the route (e.g., `/account`) inside the Caddy route 🥺 ?

**Comment by francislavoie** [comment]
That's not really viable. The way JSON serialization/deserialization works in Go is using struct tags: https://golang.org/pkg/encoding/json/#Marshal. It would significantly complicate things to have "aliases".

Routes are a set of rules (matchers and handlers) that determine how a request will be handled. https://caddyserver.com/docs/json/apps/http/servers/routes/

What you call a route, i.e. `/account`, is just the request URI's path.
