### ISSUE TITLE
Caddy < 1.0 fails to build.

### ISSUE THREAD

**Issue by mmlb** [caddyserver/caddy#3929]
Hi again,

I'm back with my super weird case of wanting to build ancient versions of caddy. This first came up in https://caddy.community/t/please-bring-back-github-com-caddyserver-builds/5552/6 and the solution back then was fine and we've been doing fine in github.com/tinkerbell/osie since. But recently our CI broke again, but this time because mholt/caddy is now private. Anyway to somehow make things work again?

I'm happy to say I'll most likely get of off 0.10 anyway, but wanted to raise the issue anyway.

**Comment by mholt** [comment]
It's private because I set up a temporary repo to test something. But the repo was deleted before that.

If you're still needing to build such old versions, make sure you resolve all the errors the compiler gives you and it will compile again. Good luck!
