### ISSUE TITLE
Am I able to use my own certificate?

### ISSUE THREAD

**Issue by McFranko** [caddyserver/caddy#3934]
I have a certificate for my domain that was given to me by my domain name registrar. Is there any way I can use that instead of the one caddy generates?

**Comment by francislavoie** [comment]
Yes. https://caddyserver.com/docs/caddyfile/directives/tls

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
