### ISSUE TITLE
incorrect localhost cert

### ISSUE THREAD

**Issue by axifive** [caddyserver/caddy#3937]
**1. Caddy version?**
v2.2.2 h1:Ha3bvEvkb/GLGEX648/qI5zTt6uJCnfQhZHmZBxhzDY=

**2. Caddyfile?**
```
localhost {
    route {
        respond "Test"
    }
}
```

Tried running a simple local server and get incorrect certificate. The browser refuses to load page if the Subject name in cert is not specified.

![Screen Shot 2020-12-25 at 05 04 15](https://user-images.githubusercontent.com/844963/103114352-3df96200-466f-11eb-925d-a247600ce3f8.png)

**Comment by mholt** [comment]
v2.2.2 does not exist; please try upgrading to v2.3.0-rc.1. thanks!

**Comment by axifive** [comment]
For v2.3.0-rc.1 get same result. v2.2.2 I downloaded from [https://caddyserver.com/download](https://caddyserver.com/download) with **http.handlers.trace** module.

**Comment by mholt** [comment]
Hmm, make sure to delete the existing cert in your data directory so Caddy can generate a new one. What browser and version are you using?

**Comment by axifive** [comment]
I have tried in latest chrome, opera and safari. OS: macOS 10.15. Apple changed trust requirements from this version https://support.apple.com/en-us/HT210176

**Comment by mholt** [comment]
I'm unable to reproduce this error. Can you please post the full PEM contents of the cert?

**Comment by flwrchild42** [comment]
Merry Christmas 🎄

**Comment by flwrchild42** [comment]
Happy new year

**Comment by flwrchild42** [comment]
[]()

**Comment by flwrchild42** [comment]
Thanks

**Comment by axifive** [comment]
[Caddy.zip](https://github.com/caddyserver/caddy/files/5742494/Caddy.zip)

[X509 Certificate_caddy.pem.txt](https://github.com/caddyserver/caddy/files/5742501/X509.Certificate_caddy.pem.txt)

**Comment by mholt** [comment]
Thanks!

Running `openssl x509 -in X509.Certificate_caddy.pem.txt -text` yields:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            2a:f9:ad:21:be:5d:d2:02:af:f1:98:c5:38:64:93:4e
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = Caddy Local Authority - ECC Intermediate
        Validity
            Not Before: Dec 25 22:27:45 2020 GMT
            Not After : Dec 26 10:27:45 2020 GMT
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:18:a3:e9:3b:3d:fe:1f:c8:e9:50:9b:63:b5:bf:
                    91:f9:09:18:f8:e5:42:32:f7:c0:47:d1:ad:eb:6b:
                    63:d3:fc:29:5b:e6:66:2b:ac:ab:ae:96:c1:15:31:
                    67:a3:cb:f7:3f:94:6f:83:b2:05:86:1a:e2:b3:44:
                    b9:c6:da:7e:89
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Subject Key Identifier: 
                3F:35:78:6B:59:5A:12:60:77:42:3D:08:F6:A5:CE:8E:71:CD:D0:D1
            X509v3 Authority Key Identifier: 
                keyid:0F:1C:C3:02:E7:FA:23:1F:48:74:45:F9:51:9B:A2:C9:EE:06:0C:6D

            X509v3 Subject Alternative Name: critical
                DNS:localhost
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:56:39:fc:73:10:82:90:2f:57:f9:8e:e4:d2:9a:
         93:c0:74:41:01:cc:3d:d6:c1:45:d1:28:f0:fd:3b:0f:df:dd:
         02:20:0a:e8:dc:6f:8e:f2:0e:f6:3a:23:68:e4:e0:03:e6:95:
         80:78:f4:1e:c1:20:93:6c:a2:a5:f9:95:5e:04:fc:88
-----BEGIN CERTIFICATE-----
MIIBvDCCAWOgAwIBAgIQKvmtIb5d0gKv8ZjFOGSTTjAKBggqhkjOPQQDAjAzMTEw
LwYDVQQDEyhDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSBFQ0MgSW50ZXJtZWRpYXRl
MB4XDTIwMTIyNTIyMjc0NVoXDTIwMTIyNjEwMjc0NVowADBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABBij6Ts9/h/I6VCbY7W/kfkJGPjlQjL3wEfRretrY9P8KVvm
Ziusq66WwRUxZ6PL9z+Ub4OyBYYa4rNEucbafomjgYswgYgwDgYDVR0PAQH/BAQD
AgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUPzV4
a1laEmB3Qj0I9qXOjnHN0NEwHwYDVR0jBBgwFoAUDxzDAuf6Ix9IdEX5UZuiye4G
DG0wFwYDVR0RAQH/BA0wC4IJbG9jYWxob3N0MAoGCCqGSM49BAMCA0cAMEQCIFY5
/HMQgpAvV/mO5NKak8B0QQHMPdbBRdEo8P07D9/dAiAK6NxvjvIO9jojaOTgA+aV
gHj0HsEgk2yipfmVXgT8iA==
-----END CERTIFICATE-----
```

As we can see here, the SAN extension is marked "critical" which is correct.

This appears to be a bug in the macOS verifier. I believe it is known in the CABF circles but hasn't been fixed yet.

**Comment by aduzsardi** [comment]
@axifive it's nothing wrong with your OS verifier , they just don't want to fix it because it's easier to just say No
Some bs that the CN is not mandatory , yet you can't find a valid/public certificate out there without a CN.
https://github.com/caddyserver/caddy/issues/3755

P.S. just create your certs outside of caddy and use those

**Comment by Bawa75** [comment]
Après avoir exporté mon certificat racine dans mon navigateur Firefox , voici ce que le navigateur me renvois : MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

**Comment by Bawa75** [comment]
@mholt voici mon Caddyfile :                                                                                                                                                  localhost:8003 {
    root * /usr/share/caddy
    file_server
    tls /var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt/var/lib/caddy/.local/share/caddy/pki/authorities/local/root.key
}

**Comment by francislavoie** [comment]
@Bawa75 please don't ask for help on a 3 year old closed issue.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). Don't forget to fill out the thread template so we can help you!
