### ISSUE TITLE
POST'ing route using @id adds new route to array instead of replacing.

### ISSUE THREAD

**Issue by cammurray** [caddyserver/caddy#3949]
JSON configuration

`                        {
"routes": [
                            "@id": "route_dGVzdDQuY2FkZHkubG9jYWwv",
                            "handle": [
                                {
                                    "handler": "reverse_proxy",
                                    "transport": {
                                        "protocol": "http",
                                        "tls": null
                                    },
                                    "upstreams": [
                                        {
                                            "dial": "google.com:80"
                                        }
                                    ]
                                }
                            ],
                            "match": [
                                {
                                    "host": [
                                        "test4.caddy.local"
                                    ]
                                }
                            ]
                        }
]`

If you POST to /id/route_dGVzdDQuY2FkZHkubG9jYWwv you end up adding a new route to the routes array,

Documentation says though that a POST should set/replace.

There is therefor no API option to do this, as PATCH will only change variables that have been changed - it does not blot the existing object.

Workaround is to DELETE and then to POST, but this shouldn't be neccesary.

**Comment by mholt** [comment]
(Did you mean to close this?) Your JSON is malformed. You have a key-value pair inside of an array.

**Comment by cammurray** [comment]
Thanks @mholt

I meant to close it as I found PATCH and POST were in fact working, it’s just my id’s were so closely related I thought they were duplicates but weren’t. Soon as I found it was my error I closed, cheers.
