### ISSUE TITLE
caddy v2 proxy Rstudio, how to config the caddyfile

### ISSUE THREAD

**Issue by ixxmu** [caddyserver/caddy#3950]
In **caddy v1**, config like following contents

proxy /rstudio rstudio:8787 {
    without /rstudio
    header_upstream Host {host}/rstudio
    transparent
    websocket
  }
  redir /rstudio /rstudio/ 307

how to did same in **caddy v2** ? 

Thank you!

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
