### ISSUE TITLE
unrecognized directive: cache

### ISSUE THREAD

**Issue by gitty-git-git** [caddyserver/caddy#3951]
Is caching available for Caddy2 yet? I tried to use the Caddy1 version:
```
cache {
    match_path /mypath
    default_max_age 10m
    path /tmp/caddy-cache
  }
```
but I get `unrecognized directive: cache`

If it isn't built-in is there an adaptor that can do it?

**Comment by francislavoie** [comment]
It's not built-in, you can find the list of built-in directives here: https://caddyserver.com/docs/caddyfile/directives

This plugin is what you're looking for: https://github.com/caddyserver/cache-handler

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
