### ISSUE TITLE
mydomain.com: obtaining certificate: EOF

### ISSUE THREAD

**Issue by TrieBr** [caddyserver/caddy#3954]
I'm trying to set up caddy using docker image `caddy:2.2.1-alpine`. My Caddyfile is below (my actual domain replaced with mydomain.com):

```
{
    debug
}
mydomain.com

reverse_proxy server:5000
```

I receive an error "obtaining certificate: EOF" with no other information, even with debug mode enabled.
I confirmed my server is open on port 443 and 80 and my domain resolves to the IP of my server. How can I troubleshoot this issue with no other information being logged about the error?

```
{"level":"info","ts":1609737694.43828,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"info","ts":1609737694.4443681,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1609737694.4484055,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0002d1180"}
{"level":"info","ts":1609737694.4759352,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1609737694.4760537,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"debug","ts":1609737694.4804416,"logger":"http","msg":"starting server loop","address":"[::]:443","http3":false,"tls":true}
{"level":"debug","ts":1609737694.4807186,"logger":"http","msg":"starting server loop","address":"[::]:80","http3":false,"tls":false}
{"level":"info","ts":1609737694.4808028,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["mydomain.com"]}
{"level":"info","ts":1609737694.4855857,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1609737694.485909,"msg":"serving initial configuration"}
{"level":"info","ts":1609737694.4901412,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1609737694.6138184,"logger":"tls.obtain","msg":"acquiring lock","identifier":"mydomain.com"}
{"level":"error","ts":1609737694.6279685,"logger":"tls","msg":"job failed","error":"mydomain.com: obtaining certificate: EOF"}
{"level":"debug","ts":1609738224.809364,"logger":"http.stdlib","msg":"http: TLS handshake error from 76.102.51.62:56385: no certificate available for 'mydomain.com'"}
{"level":"debug","ts":1609738224.924671,"logger":"http.stdlib","msg":"http: TLS handshake error from 76.102.51.62:56387: no certificate available for 'mydomain.com'"}
{"level":"debug","ts":1609738224.925654,"logger":"http.stdlib","msg":"http: TLS handshake error from 76.102.51.62:56386: no certificate available for 'mydomain.com'"}
{"level":"debug","ts":1609738225.0172453,"logger":"http.stdlib","msg":"http: TLS handshake error from 76.102.51.62:56388: no certificate available for 'mydomain.com'"}
```

**Comment by francislavoie** [comment]
Do you have something like Cloudflare in front of Caddy?

**Comment by mholt** [comment]
Are there any files in your `$HOME/.local/share/caddy/locks` folder (`ls -la`)? And if so, what are the contents of the files?

```
cat $HOME/.local/share/caddy/locks/*
```

**Comment by TrieBr** [comment]
Thanks, looks like it was a filesystem problem. I think the file was able to be read, but was somehow empty or corrupt and I suspect the error was being thrown here in the json parsing.
caddyserver/certmagic/blob/81657a23377cad89ed4c08d3741b40b3cda055c5/filestorage.go#L150

I'm using AWS EFS and I noticed the data directory I was mounting was owned by root instead of ec2-user. I cleared the directory and set the correct owner a group and launched the container again and now it's working.

**Comment by mholt** [comment]
@TrieBr  Thanks for digging in! Indeed, that is what I am suspecting. I've seen this before, when a file system has some weird problem.

> and I suspect the error was being thrown here in the json parsing of the lock acquisition:
caddyserver/certmagic/blob/81657a23377cad89ed4c08d3741b40b3cda055c5/filestorage.go#L150

In this case, you should see an error in your logs (even if it doesn't have an explanation or context, you should see SOME error message, which we do return to the callers, and eventually print out). I have never been able to find one in the one case that I examined before, which leads me to believe that the file system is not reporting errors when writing?

I just realized we don't `Sync()` the file before closing it. Normally this is not a problem but maybe we need to do that? There's only like 1 place ever where I've found syncing to be useful. But maybe this is one of those places.

> I'm using AWS EFS and I noticed the data directory I was mounting was owned by root instead of ec2-user.

Aha, the other use case I examined was also using EFS. Although, their permissions were correct.

I wonder if this is some weakness of AWS EFS.

I will try adding a `Sync()` call when I get around to it and see if that helps in future versions. If you want to try adding it in the meantime yourself, and see if the problem re-occurs, that could be helpful I suppose!
