### ISSUE TITLE
Git configuration for caddy server

### ISSUE THREAD

**Issue by abdounikarim** [caddyserver/caddy#3961]
Hello, how can we configure git to work with the caddy server ? 

I work with Docker with two containers : 
- one with PHP-FPM
- one with Caddy

Thanks

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
