### ISSUE TITLE
How to use basicauth with filters

### ISSUE THREAD

**Issue by loeffel-io** [caddyserver/caddy#3962]
Trying out caddy for one of our SPA projects and getting in trouble with the following configuration: 

```
localhost
try_files {path} /index.html
file_server
tls /etc/ssl/certs/server.crt /etc/ssl/certs/server.key

@auth {
    not path /*
}

basicauth @auth {
    amzv JDJ5JDEyJFYvVXVyWXFIemNsUjlwMUlZdGJ4di5hTkxSUDZHd2JTekRVdUgvR0dKdkN0RGdDSXFqUmhlIA==
}
```

Rules: 

- Open file if exists, otherwise use the index.html file ✅ 
- Use basicauth for all routes including /js/app.js etc, but not for /{slug} ❌ 

Current state: 

- Basic auth is not working for any route

Shouldn't be that hard, maybe someone can suggest a quick and easy answer

**Comment by francislavoie** [comment]
You've already posted on the forums, which is the right place to ask, so I'm closing this 👍 

https://caddy.community/t/how-to-use-basicauth-with-filters/11055
