### ISSUE TITLE
Unknown field api_token for custom dns provider

### ISSUE THREAD

**Issue by cammurray** [caddyserver/caddy#3975]
I've been spending hours on this and I verified my configuration with documentation that i'm almost sure now this has to be a bug?

My caddy is built with my recommended provider. It was built using xcaddy.

root@caddypm:/caddy# /app/api/Caddy/linux_amd64/caddy list-modules
...
dns.providers.vultr
...

My configuration has the following:

`{
    "apps": {
        "tls": {
            "automation": {
                "policies": [
                    {
                        "issuer": {
                            "module": "acme",
                            "challenges": {
                                "dns": {
                                    "provider": {
                                        "api_token": "REMOVEDMYACTUALKEY",
                                        "name": "vultr"
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        }
    }
}`

However, when caddy loads i get the following..

{"level":"error","ts":1610691973.9730911,"logger":"admin.api","msg":"request error","error":"loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: position 0: loading module 'acme': provision tls.issuance.acme: loading DNS provider module: loading module 'vultr': decoding module config: dns.providers.vultr: json: unknown field \"api_token\"","status_code":500}

**Comment by francislavoie** [comment]
The JSON key is actually `auth_token`, apparently:

https://github.com/libdns/vultr/blob/master/provider.go#L17

Anyways, this isn't an issue with Caddy, but rather with the vultr DNS plugin and/or libdns package.
