### ISSUE TITLE
Caddyfile: subject does not qualify for certificate with http://*

### ISSUE THREAD

**Issue by 0az** [caddyserver/caddy#3977]
Caddy v2.3.0 errors on the previously-valid http-only wildcard site `http://*`, which is a regression from v2.2.0 behavior.

### Example Caddyfile

```conf
http://* {
	respond "Hello, world!"
}
```

(I might get around to figuring out how `git bisect run` works in the morning: should be fun.)

**Comment by francislavoie** [comment]
Wildcard characters only match a single domain segment. Just remove the * to match all domains.

**Comment by 0az** [comment]
> Wildcard characters only match a single domain segment. Just remove the * to match all domains.

I'm 50% sure that the wildcard matching single segments was intentional, since this was deployed with a collection of HTTPS sites that I wanted auto-HTTPS for.

```
# 1.Caddyfile
{
	# Just for local replication
	local_certs
}

http://* {
	respond "Hello, world!"
}

localhost.internal {
	respond "Hello, https!"
}
```

If you drop the wildcard, in v2.2.0, it catches `http://localhost.internal`, and does not force the wildcard. In v2.3.0, it errors with
```
run: loading initial config: loading new config: loading tls app module: tls: invalid configuration: automation policy 1 is the second policy that acts as default/catch-all, but will never be used
```

Poking at the adapted JSON, it looks like there's two repeated blocks:

<details>
<summary>

`caddy adapt` output of 1.Caddyfile, with wildcard removed

</summary>

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "localhost.internal"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "body": "Hello, https!",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        },
        "srv1": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "handle": [
                {
                  "body": "Hello, world!",
                  "handler": "static_response"
                }
              ]
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "issuers": [
              {
                "module": "internal"
              }
            ]
          },
          {
            "issuers": [
              {
                "module": "internal"
              }
            ]
          }
        ]
      }
    }
  }
}
```
</details>

This seems like a different bug, though.

**Comment by francislavoie** [comment]
> I'm 50% sure that the wildcard matching single segments was intentional, since this was deployed with a collection of HTTPS sites that I wanted auto-HTTPS for.

To clarify, cause I'm not certain we're on the same page on this, "single-segment" means a domain like "localhost", but not "localhost.internal", because that's two segments (separated by `.`). This is also known as "labels" (Caddy uses that terminology in the docs for the placeholders as well, I probably should have used that word instead)

**Comment by 0az** [comment]
> To clarify, cause I'm not certain we're on the same page on this, "single-segment" means a domain like "localhost", but not "localhost.internal", because that's two segments (separated by `.`). This is also known as "labels" (Caddy uses that terminology in the docs for the placeholders as well, I probably should have used that word instead)

Yeah, I'm aware of that, and I abuse that to ensure that only single-segment sites (localhost, and a couple others) have that wildcard block applied, and not anything public facing. `localhost.internal` is a poorly chosen stand-in for a """production""" domain.

**Comment by mholt** [comment]
@0az Thanks for the report, I'm looking into this.

Meanwhile:

Does this commit fix the [repeated automation policies bug](https://github.com/caddyserver/caddy/issues/3977#issuecomment-762372877) for you? It's recent, you'll have to get the latest build artifacts from our CI or use xcaddy on the latest commit/master: https://github.com/caddyserver/caddy/commit/7846bc1e06b2de97906cd562d16db4b2aafbd74b

**Comment by mholt** [comment]
@0az I _think_ the commit I just pushed, d68cff8, is a good way to fix the bug. We shouldn't be trying to create TLS automation policies for servers that are HTTP-only. (Right? I keep feeling like there's some edge case in here I'm not considering. Oh well... guess we'll see.)

Please try the latest commits and let me know if there are any further problems. Thanks!

**Comment by 0az** [comment]
Tested 3366384. LGTM.

**Comment by mholt** [comment]
Great, thanks!
