### ISSUE TITLE
Is this a bug or documentation problem: running caddy on unprivileged ports with "localhost:port" address setup?   

### ISSUE THREAD

**Issue by benibilme** [caddyserver/caddy#3978]
I have posted a question at [Caddy Forum](https://caddy.community/t/newbie-question-caddy-file-vs-cli-documentation-is-misleading/11145). The long story is in the form.  To make long story short  

Below simple configuration suggested in caddy documentation gives  

     localhost:2020
     file_server

following error 

`pki.ca.local    root certificate is already trusted by system   {"path": "storage:pki/authorities/local/root.crt"} run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: permission denied`  

However following does not give any error and works properly. 

    :2020
    file_server 

I have found  [Arch Caddy Wiki](https://wiki.archlinux.org/index.php/Caddy)  following notation which also works.

    {
       http_port 2020
    }

    localhost:2020
    file_server

There is definetely a behaviour difference with  `:port` and `localhost:port`

If this is not a bug, the documentation should clear this issue. `localhost:port` does not work in my manjaro system. I tested in two different manjaro system.  

The documentation should provide a clear example of how to run caddy on unprivileged ports. IMHO a simple configuration as this

     localhost:2020
     file_server

should work straight out of the box without any tweaking such as disabling auto_https etc. if caddy claims being simple.

**Comment by francislavoie** [comment]
This is not a bug. By default, linux users on most distros do not have permissions to bind to low ports (i.e. ports under 1024). This permission is controlled by the `CAP_NET_BIND_SERVICE` capability, which you can grant to the `caddy` process. Or you can run caddy with `sudo` to run as root, which has those permissions. But typically users run Caddy as a systemd service, with a user named `caddy` which has the appropriate permissions.

As noted in the docs. Automatic HTTPS is activated when you use a domain such as `localhost`, providing you with a locally managed CA with automatically renewed certificates (which are only trusted by your system, which Caddy sets up automatically for you, doing the equivalent of the `caddy trust` command, when local certificates are to be used).

If you specify `http://localhost:2020` as your site address instead, Caddy will know to not set up HTTPS for your site.

**Comment by benibilme** [comment]
Why does not  `localhost:2020` automatically state to the caddy that an unpriviledge port is being used, while `:2020` does that? 

**I do not receive the permission denied error for `:2020`.  Doesn't it an inconsistency?**  

The documantation at [Caddy Documentation Static Files Caddy File Section](https://caddyserver.com/docs/quick-starts/static-files#caddyfile) clearly states 

> In the root of your site, create a file called Caddyfile with these contents:
>   localhost
>   file_server
> If you don't have permission to bind to low ports, replace localhost with localhost:2015 (or some other high port). Then, from the same directory, run:

**The above explanation is clearly againts what you state here.**

**Either the documentation must be improved or the behaviour. IMHO the behavoiur must be in compliance to the documentation since it clearly shows the most simple setup which is expected to work out of the box**  

**The caddy does not behave as stated in the documentation.**

**Comment by benibilme** [comment]
Why don't you just update the documentation?  Just closing this issue will give trouble many new users...

**Comment by mholt** [comment]
Our Caddyfile tutorial clearly says, near the top:

> If the HTTP and HTTPS ports (80 and 443, respectively) are privileged ports on your OS, you will either need to run with elevated privileges or use a higher port. To use a higher port, just change the address to something like localhost:2015 and change the HTTP port using the http_port Caddyfile option.

As you found, this works in your case, and is already in the documentation.

> IMHO a simple configuration as this should work straight out of the box without any tweaking such as disabling auto_https etc.

That's an unreasonable expectation, and the docs are very clear that this may not be the case depending on your operating system. If you don't like that it doesn't work on your OS, file a bug with your OS. For example, macOS will not give you a permissions error with that config (even though Arch does).

> It seems, caddy2 have changed some basic behavior.

This was the same in Caddy 1.

I am not sure that there is anything actionable from this issue. After the discussion in the forum, this comes across more as complaining than contributing to a constructive discussion. To prevent duplication, I'm going to lock this and refer any readers to [the forum thread](https://caddy.community/t/newbie-question-caddy-file-vs-cli-documentation-is-misleading/11145).
