### ISSUE TITLE
IP TLS / SANs?

### ISSUE THREAD

**Issue by lmeyerov** [caddyserver/caddy#3993]
Does Caddy support manual TLS for IPs, and/or an IP in the SAN list? 

We're confused on a manual TLS config where curl/openssl successfully access the domain named in the cert... but fails when accessing by an IP  in the cert's SANs list. When we open in a browser by domain name, and check the SAN list, the IP does show up as a valid option, and we can serve by IP for HTTP, so we suspect it is on our caddy config (or caddy itself) for either IP-for-TLS or IP-in-SANs.

We've tried a few permutations of

```yml
the.site.ngo:443, 10.10.10.10:443, :443 {
  tls /root/.caddy/my.crt /root/.caddy/my.key
  proxy / app:80 {
    websocket
  }
}
```

Our next steps were going to be:
* Try making the IP as the main cert name, instead of a SAN entry
* Try upgrading caddy 1 -> caddy 2
* Do more googling. Ex: 2016/2017 thread suggesting no SAN support: https://github.com/caddyserver/caddy/issues/831 

Any guidance on whether this is expected to work, or what to attempt/examine, would be appreciated!

**Comment by mholt** [comment]
> Try upgrading caddy 1 -> caddy 2

Please do this first. Caddy 1 is no longer supported. (But it does support IP subjects. The issue you linked to is about automatically managed certs, not manually provided ones.)

Your equivalent config in Caddy 2 would be:

```
the.site.ngo, 10.10.10.10, :443 {
    tls /root/.caddy/my.crt /root/.caddy/my.key
    reverse_proxy app:80
}
```

**Comment by lmeyerov** [comment]
@mholt  I wanted to follow up on this one in case may help doing IP SANs for future Caddy 2 users.  Happy to try alternative configs & diagnostics.

We ported to Caddy 2 and ran few config variants and tests, ultimately with http fine and FQDN/shortnames SANs fine, but mixed success with IP SANs.

### Setup:

Docker caddy 2:  `2.3.0`

Cert:

* `CN`:  `my.fqdn.ngo`
* `SANs`: `my.fqdn.ngo`, `myshortname`, `10.10.10.10` <-- Google Chrome successfully shows these

Not shown, same cert except `CN` uses the IP

Tests run `curl` from the same host that docker is running on

----

### Caddyfile config 1 - :443

```
:443 {

    tls /root/.caddy/my.crt /root/.caddy/my.key

    log
    
    root * /usr/share/caddy
    file_server

}
```

Autosaved config json:

```json
{"apps":{"
    http":{
        "servers":{
            "srv0":{
                "listen":[":443"],
                "logs":{},
                "routes":[
                    {"handle":[
                        {"handler":"vars","root":"/usr/share/caddy"},
                        {"handler":"file_server","hide":["/etc/caddy/Caddyfile"]}]}],
                "tls_connection_policies":[
                    {"certificate_selection":{"any_tag":["cert0"]}}
                ]}}},
    "tls":{
        "certificates":{
            "load_files":[{
                "certificate":"/root/.caddy/shortname.cer",
                "key":"/root/.caddy/shortname.key",
                "tags":["cert0"]}]}}}}
```

Curl test sequence:
- [x] `curl -v https://my.fqdn.ngo` -> `200`
- [x] `curl -v https://myshortname` -> `200`
- [ ] `curl -v https://10.10.10.10` -> TLS error

On the commandline, `curl -v https://10.10.10.10` fails with:

```
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
...
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_****
* ALPN, server accepted to use h2
* Server certificate:
*   subject: .... CN=my.fqdn.ngo
*   subjectAltName does not match 10.10.10.10
* Closing connection 0
...
curl: (51) SSL: no alternative certificate subject name matches target host name '10.10.10.10'
```



In the caddy container logs:
* Start: `no OCSP stapling for [my.fqdn.ngo myshortname 10.10.10]` <- unimportant warning, but usefully, confirms IP SAN is readable
*  `info`-level logs for `GET host my.fqdn.ngo` then `GET host myshortname`
* .. no info/error log for the `curl -v https://10.10.10` <- **should caddy say something / can we make it?** One thought is we may be getting MITM'd somehow, but were unsure how to check.

Also strange, `openssl s_client -connect 10.10.10.10:443` seems to get the cert and successfully starts a connection. 

----

### Caddyfile for explicit hosts

We then did a similar setup, except trying variants like:

* `my.fqdn.ngo, 10.10.10.10 { ...` 
* `10.10.10.10, my.fqdn.ngo { ...` <- different init errors than prev line's config!
* `10.10.10.10 { ...`
* `10.10.10.10:443 { `
 
We saw surprising caddy init logs mostly similar to:

```
skipping automatic certificate management because one or more matching certificates are already loaded
enabling automatic HTTP->HTTPS redirects 
installing root certificate (you might be prompted for password)`
 "certutil" is not available, install ...
certificate installed properly in linux trusts
```

Running `curl -v https://10.10.0.10` gives a different error than when doing the `:443` config:

```
* Rebuilt URL to https://10.10.10.10/
...
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
* CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, internal error (592):
* error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
* Closing connection 0
* curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

Still not seeing `GET host 10.10.10.10` in caddy logs, just GET for the `my.fqdn.ngo` / `myshortname` curl variants

**Comment by mholt** [comment]
@lmeyerov Can you please post the PEM-encoded certificate that you're using? I will dig into it more.

As for:

> installing root certificate (you might be prompted for password)`
> "certutil" is not available, install ...
> certificate installed properly in linux trusts

that just means Caddy is installing its root CA into your local trust store. Is probably unrelated.

Also, please enable debug-level logging and try again. With the Caddyfile, just put at the top:

```
{
    debug
}
```

**Comment by lmeyerov** [comment]
RE:`debug`, will do

RE:root CA install, Good to know. I was surprised because running as `:443 {` does not emit that log line, but `10.10.10.10 {` does . 

RE:PEM data exfil, that'll be tough. If there is anything I can manually report, like dialog values in the cert in Google Chrome, or result of running an openssl command on it and get a particular output, that's easier. 

One idea is adding to `sni_test.go` a smoketest like `*:443` for a cert with CN fqdn / SAN IP + shortname + fqdn2 and making sure all 4 names give a 200. We didn't get TLS for IP-as-the-CN working either, so maybe that too..

**Comment by mholt** [comment]
> RE:root CA install, Good to know. I was surprised because running as :443 { does not emit that log line, but 10.10.10.10 { does .

That's because Caddy will try to obtain a certificate for 10.10.10.10 if a loaded certificate doesn't already have that SAN.

> RE:PEM data exfil, that'll be tough.

To clarify, I mean, just paste it here, or attach the file. Not difficult. The certificate does not have any private key material in it. Right now I suspect something is wrong with your certificate.
