### ISSUE TITLE
use a net.UDPConn in fakeClosePacketConn

### ISSUE THREAD

**Issue by marten-seemann** [caddyserver/caddy#3998]
Caddy should use a `*net.UDPConn` instead of a `net.PacketConn` in
https://github.com/caddyserver/caddy/blob/e2940c8c03818f1227aa2c103e05fb5664635e11/listeners.go#L205-L210

This will allow quic-go to set the receive buffer size, see https://caddy.community/t/udp-receive-buffer-size-quic/11244 and https://github.com/lucas-clemente/quic-go/issues/3024.

**Comment by francislavoie** [comment]
Is that safe to change though? Does that code path use TCP too? 🤔

**Comment by marten-seemann** [comment]
I don't think that's possible. `net.TCPConn` doesn't implement `net.PacketConn`.
