### ISSUE TITLE
How do I set log level of default logger in Caddyfile?

### ISSUE THREAD

**Issue by mrnugget** [caddyserver/caddy#4000]
Hey! I've been reading through the [forum](https://caddy.community/t/how-to-set-the-default-log-level/9298/4), the [reference](https://caddyserver.com/docs/json/logging/logs/) and the [docs](https://caddyserver.com/docs/logging) on logging because I want to set the log level of the default logger in the Caddyfile.

Our `Caddyfile` looks like this:

```
{
  http_port 3088
}

{$SOURCEGRAPH_HTTPS_DOMAIN}:{$SOURCEGRAPH_HTTPS_PORT} {
  tls internal
  reverse_proxy localhost:3080
  
  log {
    level ERROR
  }
}
```

As far as I can understand that only configures the log level for our site, but I also want to set the log level for the _global_ `default` logger.

Is there any way to do this in the Caddyfile? As far as I could tell, that's only possible in the JSON configuration, but that doesn't support reading from ENV vars, which is why I want to avoid switching to JSON config.

Edit: I know about the global debug flag, but what I want is _less_ log output.

**Comment by francislavoie** [comment]
There's currently no way to do this from the Caddyfile. See #3958

**Comment by francislavoie** [comment]
FWIW I recommend using `jq` for making any modifications to your config that you can't otherwise do with the Caddyfile. Basically, `caddy adapt --config /path/to/Caddyfile | jq 'make some modification' > caddy.json` then `caddy run --config config.json`

**Comment by francislavoie** [comment]
Hah, also, you're lucky number #4000 😅

**Comment by mrnugget** [comment]
I thought about that but `caddy adapt` doesn't seems to expand the environment variables in the `Caddyfile` before exporting it.

Aside from that, even with a `.json` config there doesn't seem to be a way to set the log level.

Given this config:

```json
{
  "logging": {
    "logs": {
      "default": {
        "level": "FATAL"
      }
    }
  }
}
```

`caddy run` still prints `info` log lines:

```
$ ./caddy_2.3.0 run --config caddy.config.json                                                                                                                     -1-
2021/01/29 14:19:22.091 INFO    using provided configuration    {"config_file": "caddy.config.json", "config_adapter": ""}
2021/01/29 14:19:22.092 INFO    admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
```
![image (1)](https://user-images.githubusercontent.com/1185253/106285823-39633300-6245-11eb-9d99-ec5ba900386c.png)

**Comment by francislavoie** [comment]
I'm pretty sure both those messages will always appear because it's before the config is actually loaded. You can compare by setting it to DEBUG and seeing how much it outputs, compared to FATAL. You'll see "serving initial configuration" when using a level below INFO, but you won't when above that.
