### ISSUE TITLE
Option for pki/certificate_authorities/local/install_trust in Caddyfile

### ISSUE THREAD

**Issue by takerukoushirou** [caddyserver/caddy#4002]
Currently the `install_trust` option for CAs from the `pki` module can only be configured via JSON/API.

Setting TLS to `internal` with option `on_demand` is easily possible with a Caddyfile and allows for a quick and simple internal setup. Trust store installation on the machine itself is not necessary and only leads to startup errors being logged from both `sudo` and `caddy`.

Therefore it would be great if the trust installation could be disabled for the `local` CA without the need to switch to JSON just for this one option.
Maybe as a single global Boolean option `ca_local_install_trust` for the `local` CA only or `ca_install_trust ` to set a default for every CA.

**Comment by Blackpower1972** [comment]
Currently the install_trust option for CAs from the pki module can only be configured via JSON/API.

Setting TLS to internal with option on_demand is easily possible with a Caddyfile and allows for a quick and simple internal setup. Trust store installation on the machine itself is not necessary and only leads to startup errors being logged from both sudo and caddy.

Therefore it would be great if the trust installation could be disabled for the local CA without the need to switch to JSON just for this one option.
Maybe as a single global Boolean option ca_local_install_trust for the local CA only or ca_install_trust to set a default for every CA.
Currently the install_trust option for CAs from the pki module can only be configured via JSON/API.

Setting TLS to internal with option on_demand is easily possible with a Caddyfile and allows for a quick and simple internal setup. Trust store installation on the machine itself is not necessary and only leads to startup errors being logged from both sudo and caddy.

Therefore it would be great if the trust installation could be disabled for the local CA without the need to switch to JSON just for this one option.
Maybe as a single global Boolean option ca_local_install_trust for the local CA only or ca_install_trust to set a default for every CA.

**Comment by Blackpower1972** [comment]
printf "\n========= ALICE'S NODE ========="
printf "\nAlice's balance: "
alice-cli accounts balance alice --auth hi_alice
printf "Bob's balance: "
alice-cli accounts balance bob --auth hi_alice

printf "\n========= BOB'S NODE ========="
printf "\nAlice's balance: "
bob-cli accounts balance alice --auth hi_bob
printf "Charlie's balance: "
bob-cli accounts balance charlie --auth hi_bob

printf "\n========= CHARLIE'S NODE ========="
printf "\nBob's balance: "
charlie-cli accounts balance bob --auth hi_charlie
printf "Charlie's balance: "
charlie-cli accounts balance charlie --auth hi_charlie

**Comment by Blackpower1972** [comment]
gh auth login
Authenticate with a GitHub host

Synopsis
Authenticate with a GitHub host.

The default authentication mode is a web-based browser flow.

Alternatively, pass in a token on standard input by using --with-token. The minimum required scopes for the token are: "repo", "read:org".

The --scopes flag accepts a comma separated list of scopes you want your gh credentials to have. If absent, this command ensures that gh has access to a minimum set of scopes.

gh auth login [flags]
Examples
# start interactive setup
$ gh auth login

# authenticate against github.com by reading the token from a file
$ gh auth login --with-token < mytoken.txt

# authenticate with a specific GitHub Enterprise Server instance
$ gh auth login --hostname enterprise.internal

Options
  -h, --hostname string   The hostname of the GitHub instance to authenticate with
  -s, --scopes strings    Additional authentication scopes for gh to have
  -w, --web               Open a browser to authenticate
      --with-token        Read token from standard input

**Comment by Blackpower1972** [comment]
Option for pki/certificate_authorities/local/install_trust in Caddyfile
