### ISSUE TITLE
Caddyfile site with "0.0.0.0" produces a bad host matcher

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4004]
Since `0.0.0.0` isn't really ever a useful hostname to match against, the Caddyfile should probably deal with it a bit better.

Maybe it should use a remote_ip matcher instead to limit it to only IPv4 addresses? Seems like a weird solution. Or maybe it should work just the same as `http://:1234` for example, i.e. no host matcher at all.

I'm not sure what solution is best, but it's clear the current behaviour is probably wrong.

Minor problem though, but maybe we should at least warn if we can't figure out a good fix.

```
http://0.0.0.0:1234
respond "foo"
```

👇 

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":1234"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "0.0.0.0"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "body": "foo",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ],
          "automatic_https": {
            "skip": [
              "0.0.0.0"
            ]
          }
        }
      }
    }
  }
}
```

**Comment by rajat315315** [comment]
I'm able to get a response as `foo` without any error with above Caddyfile..

**Comment by mholt** [comment]
@rajat315315 What curl command are you using? And what is its output? (please use `curl -v`)

**Comment by francislavoie** [comment]
@rajat315315 yes, `$ curl -v http://0.0.0.0:1234` does work, but the problem is that if you make a request from elsewhere, like `curl -v http://192.168.2.10` if you were on another device, would fail to respond with `foo`. Try `$ curl -v http://127.0.0.1:1234` for example, you get an empty response.

**Comment by mholt** [comment]
Thinking on this more, I actually don't think this is broken.

This is expected, given how the Caddyfile works: the site address becomes the matchers for the route.

This is not so surprising. If the user is actually trying to confine the socket binding, they should use the bind directive. For example, this would accept connections only on IPv4 (theoretically; actual implementation probably depends on OS):

```
:1234
bind 0.0.0.0
```

**Comment by francislavoie** [comment]
Sure, but I don't think it's ever valid to have a `0.0.0.0` host matcher, so either we warn/error cause it doesn't make sense, in the Caddyfile adapter, or we make it do something else? I'm leaning towards warn/error.

**Comment by mholt** [comment]
> Sure, but I don't think it's ever valid to have a 0.0.0.0 host matcher,

I think it clearly is, as `curl -v http://0.0.0.0:1234 ` works great. Granted, I'm not sure why, or how it's useful, but I'd like to avoid more hidden magic / edge cases in Caddy where possible.

I could get behind a warning though.

**Comment by francislavoie** [comment]
You're right - I meant "useful", not "valid".
