### ISSUE TITLE
Reload TLS certificates from disk via API

### ISSUE THREAD

**Issue by hholst80** [caddyserver/caddy#4005]
Feature request to v2.3

I did not find a way to via the API do a `caddy reload [...]` is it possible? Just reload to rehash the TLS certificates.

**Comment by francislavoie** [comment]
You can [`GET /config/`](https://caddyserver.com/docs/api#get-configpath) then [`POST /load`](https://caddyserver.com/docs/api#post-load) with the `Cache-Control: must-revalidate` header. That's effectively the same thing.

**Comment by mholt** [comment]
Yep, that's the way: just force a reload of the config. I suppose we could add a `--force` flag to the `caddy reload` command?
