### ISSUE TITLE
Question: How to uninstall Caddy in linux?

### ISSUE THREAD

**Issue by prayag17** [caddyserver/caddy#4006]
Hello, I was looking for different ways for reverse proxy and found caddy but I am not very comfortable with caddy so I have to remove it but I can't. Pls, give me the command line code to remove caddy.

**Comment by francislavoie** [comment]
Depends how you installed it, and on which distro.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
