### ISSUE TITLE
Reuse named matchers inside another matchers

### ISSUE THREAD

**Issue by borgius** [caddyserver/caddy#4007]
The goal for this feature to reuse matches and to combine them with custom logic.

Dummy example:
```Caddyfile
@css {
  path /assets/css/*
}
@js {
  path /assets/css/*
}
@api {
  path /api/*
}
# Combine OR and AND logic
@client {
  # match js OR css files
  @js @css
  # AND not api
  not @api
}
```

Thank you!

**Comment by francislavoie** [comment]
You can use [`import`](https://caddyserver.com/docs/caddyfile/directives/import) for this.

This would be a very complex feature to support, and I don't think it's worth it at all. It would add a significant amount of complexity to the parsing which doesn't bring much value.
