### ISSUE TITLE
Win 10 64 Bit Installer does nothing

### ISSUE THREAD

**Issue by jamesta696** [caddyserver/caddy#4010]
Hi,
When trying to install the 64bit win installer, it opens a command prompt very quickly and closes in 1sec, doesn't install the package. How do I fix this or to get this installed? I tried running the .exe as Administrator as well and does the same thing.

I also put the .exe in my file path where I have my projects and ran this command in the same path in command prompt 
"`caddy file-server`" and says `'caddy' is not recognized as an internal or external command`

Your help is appreciated,
Thanks

**Comment by francislavoie** [comment]
Installer? There's no installer for Caddy. It's just a static binary. On windows, you need to type `.\caddy.exe` when running it as a file, when not added to your PATH.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
