### ISSUE TITLE
Feature Request: Placeholders (at header time) for request time & upstream time.

### ISSUE THREAD

**Issue by MarioIshac** [caddyserver/caddy#4012]
Hello all,

This feature request is stemming from [Any equivalent of $request_time and $upstream_header_time from nginx?](https://caddy.community/t/any-equivalent-of-request-time-and-upstream-header-time-from-nginx/11418). To summarize, there are two placeholders that I'm using in nginx now that would be very useful to me in caddy:

1) [request_time](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_time):

> request processing time in seconds with a milliseconds resolution; time elapsed since the first bytes were read from the client.

2) [upstream_header_time](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_header_time):

> keeps time spent on receiving the response header from the upstream server; the time is kept in seconds with millisecond resolution.

Note that nginx does have an [upstream_response_time](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_response_time), but this isn't available at header time because nginx forwards the headers returned by upstream before it receives the response body. I don't know if Caddy does this, or if it instead buffers the response and only computes headers after response is fully received (and fully timed), but for this feature request, `upstream_header_time` and `upstream_response_time` are close enough where a port of either one would be great.

I would use these placeholders to signify to our client how much of the latency they observed was due to their upload speeds vs. our processing speeds. For example, if I returned `X-Trip-Time == 5` (where 5 is the equivalent of `request_time`) and `X-Process-Time == 3` (where 3 is the equivalent of `upstream_header_time` / `upstream_response_time`), then they would know that they spent roughly 2 seconds uploading.

If this is a feature request that the maintainers are okay with and it's a good first issue, I might be able to take a shot at this. Just would need a pointer on where to start.

**Comment by mholt** [comment]
We can implement this with one slight variation:

> time elapsed since the first bytes were read from the client.

Ours would be "time elapsed since the header bytes were read from the client and decoded" (since the Go standard library does this for us). I bet that in 99.99% of requests, this difference is negligible, and can always have an upper-bound anyway with a configurable timeout.

**Comment by mholt** [comment]
@MarioIshac Can you please give the code in https://github.com/caddyserver/caddy/pull/4013? I think it should do what you want. There will be build artifacts you can download momentarily.

**Comment by francislavoie** [comment]
Build artifacts at the bottom of the page here: https://github.com/caddyserver/caddy/actions/runs/549124082

**Comment by mholt** [comment]
Yep, or you can use `header_down` in the `reverse_proxy` block I think.

**Comment by MarioIshac** [comment]
Thank you guys for the lightning fast implementation, downloaded the build artifacts but will have a good chunk of time to test this out later in the week once work dies down for me. Will post an update here as soon as possible.
