### ISSUE TITLE
how to configure Caddy to sign with the root CA directly

### ISSUE THREAD

**Issue by finnef** [caddyserver/caddy#4018]
Hi,
In the docs https://caddyserver.com/docs/automatic-https#ca-intermediates
it says 'Caddy can be configured to sign with the root directly (to support non-compliant clients), this is disabled by default, and the root key is only used to sign intermediates.'

How do I configure caddy to sign with root CA directly?

**Comment by francislavoie** [comment]
This can be done by setting `sign_with_root` to `true` via JSON config. This option isn't available via Caddyfile.

https://caddyserver.com/docs/json/apps/tls/automation/policies/issuers/internal/

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
