### ISSUE TITLE
Reverse proxy with multiple different upstreams, with paths

### ISSUE THREAD

**Issue by ScuttleSE** [caddyserver/caddy#4019]
I've been trying to figure this one out, but either I have found solutions that only worked with v1, or I have found stuff that straight up does not work.

I have example.com facing publicly.

Caddy is acting as a reverse proxy that sends the traffic to my backend-server example.local
I want to be able to serve example.com/abc that I want to point to example2.local:8888/abc and example.com/def that I want to point to example2.local:8888/def

 It seems like I can't use rewrite on the request to the upstream server?

**Comment by francislavoie** [comment]
Like this:

```
example.com {
	handle /abc* {
		reverse_proxy example.local:8888
	}

	handle /def* {
		reverse_proxy example2.local:8888
	}

	handle {
		# Fallback for anything not otherwise handled
	}
}
```

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
