### ISSUE TITLE
Proxy not being able to connect to your php-fpm service led to 502

### ISSUE THREAD

**Issue by whitesn** [caddyserver/caddy#4025]
Hi, so I was using Caddy 1 before with no problem. I moved to Caddy 2 recently when migrating to a new server and frequently (multiple times a week) got this error.

`ERROR http.log.error.log0 dialing backend: dial unix /run/php/php7.4-fpm.sock: connect: resource temporarily unavailable`

at this point the server would be inaccessible and keep returning 502 until the Caddy is manually restarted. Here is my Caddyfile for more clarity

```
www.site.test site.test {
        tls admin@site.test

        root * /var/www/html/test/public

        log {
                output file /var/logs/Caddy/access.log
                format single_field common_log
        }

        php_fastcgi unix//run/php/php7.4-fpm.sock {
                env HTTP_HOST "site.test"
                env HTTP_MOD_REWRITE "On"
        }

        file_server
        encode gzip
}
```

I'm not sure myself if this is related to : https://github.com/caddyserver/caddy/issues/3896

caddy version returns v2.3.0 h1:fnrqJLa3G5vfxcxmOH/+kJOcunPLhSBnjgIvjXV/QTA=

**Comment by francislavoie** [comment]
Some detail about that error: https://stackoverflow.com/questions/30228482/golang-unix-socket-error-dial-resource-temporarily-unavailable

I think the socket might be getting in a bad state for some reason. How much traffic is your server getting?

**Comment by whitesn** [comment]
Checking from Caddy access log, roughly 5000 HTTP request per day (active working time) from multiple users, although this includes images, icons, css, and some other media files from a single user from 1 page.

**Comment by whitesn** [comment]
I'll try to turn on the timeouts and if it doesn't work I guess I'll go revert back to v1.

**Comment by francislavoie** [comment]
I'd rather we track down the issue instead of you going back to v1. Caddy v1 is EOL and will not receive any updates. It's not a good idea to run outdated software.

**Comment by whitesn** [comment]
What would be an appropriate value for the timeouts (dial, read, write)? Mind you I don't do much sysadmin works, so these things are outside my expertise.

**Comment by francislavoie** [comment]
Something like `5m` (5 minutes) is probably fine. Basically the idea is just to avoid some of the bad connections sticking around and piling up. None of your requests should ever take longer than 5 minutes so it should be plenty of time for any good request to properly complete, but it should prevent stale/bad connections from sticking around. Hopefully.

**Comment by whitesn** [comment]
Thanks @francislavoie! I'll update in couple days if the issue still persists

**Comment by francislavoie** [comment]
Another thing you could do is keep an eye on the metrics in the meantime. You can run this on your server:

```
$ curl localhost:2019/metrics | grep caddy_http_requests_in_flight
```

**Comment by whitesn** [comment]
Haven't gotten the issue since the timeouts were set in config. So that's probably the issue, thanks for the help! @francislavoie

**Comment by francislavoie** [comment]
@mholt since fastcgi timeouts seem to solve problems for some people, should we set some reasonably lengthy defaults instead of having them off by default? We set idle timeouts already, I figure we should set fastcgi ones as well.

**Comment by mholt** [comment]
I still want to better understand what is happening before we set defaults...
