### ISSUE TITLE
X-Forwarded-Proto not set if passed by client

### ISSUE THREAD

**Issue by jasco** [caddyserver/caddy#4031]
I was testing how the proxy headers were set in Caddy 2.3.0.  I noticed that `X-Forwarded-Proto` is forwarded unchanged if passed from the client meaning I do not have a trusted value for this header.  [Code ref.](https://github.com/caddyserver/caddy/blob/5ef76ff3e6e73282deb59df8b1a14bb966de36be/modules/caddyhttp/reverseproxy/reverseproxy.go#L510)

In contrast, for `X-Forwarded-For` the server appends the server read remote host to the header.  [Code ref.](https://github.com/caddyserver/caddy/blob/5ef76ff3e6e73282deb59df8b1a14bb966de36be/modules/caddyhttp/reverseproxy/reverseproxy.go#L504)  Is there some reason the same behavior does not occur for the scheme?

**Comment by francislavoie** [comment]
The reason is that `X-Forwarded-Proto` is not a list of values like `X-Forwarded-For`, but instead a single value, so Caddy just adds it if it wasn't there. If you can't trust your client, you can explicitly set it with `header_up X-Forwarded-Proto {scheme}`

**Comment by jasco** [comment]
@francislavoie thanks for the  response and explanation.  I just now discovered I could override it just as you suggested. That will suffice for my current use-case.
