### ISSUE TITLE
Feature Request: Deleting entry form hosts

### ISSUE THREAD

**Issue by suchwerk** [caddyserver/caddy#4035]
To add  a host via api on a specific id i use
```
curl -X POST \
    -H "Content-Type: application/json" \
    -d "[\"some.host.name\"]" \
    "http://caddy:2019/id/app-hosts/host/..."
```
I would expect to be able to delete the entry by value like
```
curl -X DELETE \
    -H "Content-Type: application/json" \
    -d "[\"some.host.name\"]" \
    "http://caddy:2019/id/app-hosts/host/..."
```
in stead of that i have to determine the index of the specific host entry to delete the host:
```
curl -X DELETE \
    "http://caddy:2019/id/app-hosts/host/4"
```

**Comment by jumpersdevice** [comment]
any update about this? @mholt 

thanks!

**Comment by mholt** [comment]
I'm not sure how feasible this is. What if the array contains objects or other arrays? That can't be easily represented by a single string in the URL. What if there are multiple of the same values - what if you only want to delete one of them, some of them, or all of them?

I think this logic is best precomputed by the client using whatever logic suits the use case the best.
