### ISSUE TITLE
Empty caddyfile prevents caddy from starting

### ISSUE THREAD

**Issue by Dialga** [caddyserver/caddy#4036]
While testing my caddy config I received `reload: adapting config using caddyfile: /etc/caddy/Caddyfile:40 - Error during parsing: Could not read tokens while importing /etc/caddy/conf.d/custom: EOF` when performing a systemctl reload.
Expected result: caddy to ignore empty caddyfile.

**Comment by mholt** [comment]
An empty Caddyfile is usually a mistake, and we decided to keep treating that as an error. (See https://github.com/caddyserver/caddy/pull/3414)
