### ISSUE TITLE
Can I get help with this?

### ISSUE THREAD

**Issue by brown7477** [caddyserver/caddy#4041]
I am trying to get Caddy installed so I can use it in front of Owncast.
I am really struggling with this.
Can someone please help me??

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
