### ISSUE TITLE
Make Caddy tolerant to spaces in environment properties

### ISSUE THREAD

**Issue by BarYamin** [caddyserver/caddy#4047]
When providing Caddy with a custom environment file (using the --envfile flag),
Caddy fails to start if there is a property in the file with spaces like the following:
Property = Value

It only accepts
Property=Value

Please make caddy tolerant of spaces

**Comment by francislavoie** [comment]
I'm not aware of any other projects that accept spaces in env files. It's standard to have the syntax not trim spaces.

We'll need evidence that it makes sense to make any change here.

**Comment by mholt** [comment]
@BarYamin This: "Property = Value" does not even work to set environment variables:

```
$ export "FOO = bar"
bash: export: `FOO = bar': not a valid identifier
```

Spaces are significant, and we don't actually parse the environment; the system does when when we make the system call to get the environment. You'd have to file a bug with your OS kernel I guess.
