### ISSUE TITLE
Feature request: log filter - request>remote_addr  and common_log

### ISSUE THREAD

**Issue by udf2457** [caddyserver/caddy#4053]
Hi,

Surely:
```
format filter {
    wrap json
    fields {
      request>remote_addr ip_mask {
        ipv4 24
        ipv6 32
      }
    }
```

Should also truncate the IP in the `common_log` part of the JSON output, otherwise its kind of pointless ? Maybe I'm missing something but what's the point of the default behaviour truncating `remote_addr` but not truncating `common_log` ?

I know I can take a hammer to the proverbial nail with `common_log delete` but that's not really the real answer to the problem, its more of a hack.

Also the docs (https://caddyserver.com/docs/caddyfile/directives/log#format-modules) should not really be making a suggestion for something that only half-works.  Many people operating under GDPR jurisdiction will need a fully-functional IP truncating function, and the docs should not really be giving them false-hope of a "quick fix" if the IP is actually still left in the logs.  The docs are silent on `request>remote_addr ip_mask` leaving the full IP in `common_log` (I note you previously promised enhancing the docs in this area #3837 .... obviously never happened since I just fell into the same trap despite looking in the section of the docs where I might have expected this to be made clear )

**Comment by mholt** [comment]
The plan is to remove common_log: see #4148.

This issue should be resolved by that.
