### ISSUE TITLE
Feature request:  Improve log consistency (or provide an easy way to add missing fields)

### ISSUE THREAD

**Issue by udf2457** [caddyserver/caddy#4054]
I noticed there is inconsistency between fields extracted into JSON and what's tagged onto the end in `common_log`, for example, in the "JSON-native" section there is no:

- `duration`
- `size`
- `status`
- Divisor element of `Content-Range`
- `Content-Length`
- `Content-Type`

The reason for this inconsistency unclear, with no mention of it in the docs.

Indeed, many examples in the docs (https://caddyserver.com/docs/caddyfile/directives/log) have `common_log delete` in them, which puts people under the unsafe assumption that everything potentially useful from `common_log` is already parsed into JSON when it is not.

The docs also make no mention as to whether it is possible to add extra fields to the standard json output and how this might be done ?  e.g. no "standard json output plus these extra fields from `common_log` " configuration option.

**Comment by mholt** [comment]
> in the "JSON-native" section there is no:
>
> - duration
> - size
> - status

That's not true, they do exist in the JSON logs:

https://github.com/caddyserver/caddy/blob/ce5a45db458166ff71cb776d70fd63e28196aafa/modules/caddyhttp/server.go#L192-L194

> - Divisor element of Content-Range

Where is that in CLF? 

> - Content-Length
> - Content-Type

Also not true, as all response headers are logged:

https://github.com/caddyserver/caddy/blob/ce5a45db458166ff71cb776d70fd63e28196aafa/modules/caddyhttp/server.go#L195

> The docs also make no mention as to whether it is possible to add extra fields to the standard json output and how this might be done ?

No, for performance reasons. But a plugin can do that: https://github.com/caddyserver/format-encoder

Thanks for the issue, but going to close as it seems based on a false premise. We can reopen it if there was just a misunderstanding though and there really is a bug or problem here.
