### ISSUE TITLE
404 not found with demo index.html

### ISSUE THREAD

**Issue by aliujunyuan** [caddyserver/caddy#4059]
my Caddyfile  as following shows :
` www.go*******tokyo.xyz

{

root */www/demo
file_server browse
tls 73******77@qq.com
}`

and then ,comand:
`caddy stop
caddy start`
after restarting caddy, i open www.go*******tokyo.xyz,but it shows 404 not found.im sure there is index.html in /www/demo
whats wrong with my caddy?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
