### ISSUE TITLE
Caddy crashes in ubuntu 20.04 because of a resolv.conf parsing error in the imported dns module.

### ISSUE THREAD

**Issue by DigiDr** [caddyserver/caddy#4061]
Hello,

I think i've spotted and found resolution for a bug that is preventing some people with ubuntu 20.04 LTS using caddy. This may only apply to docker users, though this seems unlikely.

See https://github.com/stefanprodan/dockprom/issues/205

The basic issue is that as of ubuntu 20.04 a ```trust-ad``` is added to the end of /etc/resolv.conf.

https://launchpad.net/ubuntu/+source/systemd/245.4-4ubuntu3.3

The dns module you import has a bug in it that was fixed in a later version, which means parsing resolv.conf is broken with this new addition.

https://github.com/miekg/dns/commit/906238edc6eb0ddface4a1923f6d41ef2a5ca59b

Because of this we get the following error when starting caddy:

```
goroutine 1 [running]:
github.com/mholt/caddy/vendor/github.com/miekg/dns.ClientConfigFromFile(0xbb4739, 0x10, 0x0, 0x0, 0x0)
src/github.com/mholt/caddy/vendor/github.com/miekg/dns/clientconfig.go:86 +0xad6
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers(0xbb4739, 0x10, 0xfeaf20, 0x2, 0x2, 0xf77460, 0xc4200402c0, 0xc420037f50)
src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:40 +0x4d
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.init()
src/github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme/dns_challenge.go:33 +0x12d
github.com/mholt/caddy/caddy/caddymain.init()
:1 +0x75
main.init()
:1 +0x44
panic: runtime error: slice bounds out of range
```
Fix is probably as simple as updating dependencies. In the meantime if using docker see the top link for a work around. The other option would be to edit resolv.conf on ubuntu directly, but this requires a bit of messing around.

**Comment by francislavoie** [comment]
Interesting. I'm surprised this is the first we're hearing of this problem though, it wasn't brought to our attention on any of the caddyserver repos nor on the community forums https://caddy.community.

So I think we need to bump the version of miekg/dns that certmagic uses: https://github.com/caddyserver/certmagic/blob/7550222c4a6a390cb0b91426d059f1ec5bda59b3/go.mod#L9 FYI @mholt

**Comment by mholt** [comment]
This stack trace:

```
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acme.getNameservers
```

looks like Caddy v1, which is no longer supported. Please upgrade to Caddy 2. Thanks!

**Comment by francislavoie** [comment]
Right, my bad - I misread github and read the tags on miekg/dns@906238e as meaning the fix was included in https://github.com/miekg/dns/releases/tag/v1.1.40 but that's actually the latest version. It's been fixed since https://github.com/miekg/dns/releases/tag/v1.0.5 which is a very very long time ago. Certmagic in v2 uses v1.1.30 so the problem doesn't apply with Caddy v2.
