### ISSUE TITLE
Empty page in docs

### ISSUE THREAD

**Issue by strowk** [caddyserver/caddy#4067]
https://caddyserver.com/docs/json/
This should be either deleted or filled

**Comment by mholt** [comment]
Huh? It is not empty...

**Comment by francislavoie** [comment]
Looks fine to me:

![image](https://user-images.githubusercontent.com/2111701/111329871-d63b2d80-8645-11eb-9824-b65dcd21706c.png)

Check your browser's inspector, you might see a request to `https://caddyserver.com/api/docs/config/`, that's how Caddy loads the data for the JSON docs, via its API. Did that request fail for you, for some reason? That could give the effect of an empty page.

**Comment by strowk** [comment]
It's still reproducing for me in Firefox. Though the page works ok in chromium. Here are errors in the console:
![image](https://user-images.githubusercontent.com/25692644/114866384-c4d77380-9df3-11eb-9a64-41f299bb6631.png)
As you can see from network tab there was no request to api/docs/config:
![image](https://user-images.githubusercontent.com/25692644/114866517-f3554e80-9df3-11eb-8cc1-cbe32097f229.png)

@mholt  , would you be so kind to reopen the ticket? I think the issue is still persist. I'm using firefox 87.0, which is the newest and if the site does not work there it's a lot of users, who get the wrong impression from documentation

**Comment by francislavoie** [comment]
Still works fine for me. Make sure you're not blocking JavaScript from running with an extension of something.

**Comment by mholt** [comment]
Must be something weird on your end; our JSON docs don't currently set CSPs relevant to those errors.
