### ISSUE TITLE
Caddy macOS binary should be built using CGO_ENABLED=1 to support macOS DNS resolving

### ISSUE THREAD

**Issue by aeneasr** [caddyserver/caddy#4069]
The macOS binary appears to be built with `CGO_ENABLED=0` which causes Go to use the go-internal DNS resolver instead of the macOS one. The macOS DNS resolver however is required to get custom DNS entries under `/etc/resolver` working, which popular amongst developers using local environments.

See https://github.com/golang/go/issues/12524#issuecomment-138134749

**Comment by Mohammed90** [comment]
All of the binaries across all platforms are built with `CGO_ENABLED=0`, which allows for uniform binaries across platforms, and we avoid the C runtime and its inherent unsafe memory bugs. There are workarounds for those who want to and/or don't mind CGO. You can build Caddy with `CGO_ENABLED-1` using github.com/caddyserver/xcaddy. You can also configure your system to use custom DNS resolvers, e.g. locally running CoreDNS, for more advanced setup.

I'll close the issue, but feel free to continue discussing it if you have more pressing arguments.
