### ISSUE TITLE
Feature Request: support placeholders in tls_server_name

### ISSUE THREAD

**Issue by mdegat01** [caddyserver/caddy#4079]
I was doing some testing and I noticed that the `tls_server_name` directive does not seem to support placeholders. I had a configuration like this that I was trying to use:

```
*.my-app.my-domain.com {
   reverse_proxy https://localhost:4443 {
      transport http {
         tls
         tls_server_name {http.request.host}
      }
   }
}
```

As you can probably guess I had the other application set to serve up the same certificate as Caddy itself. I did this because the application also handles encrypted UDP traffic which I wasn't proxying through Caddy. It needed to serve up the same wildcard certificate to the UDP clients since they were connecting to it directly.

What I was hoping to do was set up tls passthrough with the wildcard by using the `{http.request.host}` placeholder instead of hard-coding the value for `tls_server_name`. But when I tried that I got this error:

```json
{
    "level": "error",
    "ts": 1616341358.1952667,
    "logger": "http.log.error.log0",
    "msg": "x509: certificate is valid for <redacted>, not {http.request.host}",
    "request": {
        <redacted>
    },
    "duration": 0.011851497,
    "status": 502,
    "err_id": "qugh1gw7d",
    "err_trace": "reverseproxy.statusError (reverseproxy.go:783)"
}
```

So it looks like placeholders aren't supported for this directive.

I don't have that many subdomains to handle so I'm just going to work around this by getting a certificate that lists them all. But figured I would open the feature request since it would be nice if Caddy supported this.

**Comment by francislavoie** [comment]
I took a peek at the code to see what it would take to support this -- the trouble is that this value is only currently used during the provisioning phase when setting up the `http.Transport` and the `tls.Config` inside of it, which are the Go stdlib APIs we're using to do the proxy connection.

I think we would need to provide a custom DialTLSContext, see https://golang.org/src/net/http/transport.go#L144, which would do the placeholder replacement on the `tls.Config.ServerName` before using it... or something like that. Reading the stdlib HTTP transport code is not that easy; I'm not certain if it's even possible.

**Comment by mdegat01** [comment]
Oof, that sounds problematic. Well if it can't be done it's not the end of the world, I did find a workaround that works for me. I just figured I should open it since not being able to use placeholders seemed like a deviation from expected behavior from a user's perspective. I'm sure its an edge case though.

**Comment by mholt** [comment]
Just realized this idea was referenced here in this comment: https://github.com/caddyserver/caddy/issues/3425#issuecomment-678818159

**Comment by francislavoie** [comment]
This is now fixed in https://github.com/caddyserver/caddy/pull/4836! Thanks @kresike
