### ISSUE TITLE
request_header directive broken with matcher

### ISSUE THREAD

**Issue by silverbackdan** [caddyserver/caddy#4084]
If I try to use the `request_header` with a directive such as
`request_header @internal x-custom caddy something`

I will receive the error message 
```
Error during parsing: Wrong argument count or unexpected line ending after 'something'
```

I came across this because I cannot use a matcher with this directive. As soon as I add one, the directive will never be applied.

The documentation seems to state that the `request_header` should be able to be used with matchers, and a brief look into the source suggests to me that you are trying to parse matchers as well.

My current matcher is
```
@internal {
    path *
}
```

But I get the same result no matter what I configure in the named matcher.

**Comment by silverbackdan** [comment]
I'm not sure but I think this is where any tests should be and are missing https://github.com/caddyserver/caddy/tree/master/caddytest/integration/caddyfile_adapt

**Comment by francislavoie** [comment]
Yep you're right, the matcher token isn't correctly being skipped. You can see `@internal` in the JSON which shouldn't happen.

```
$ cat Caddyfile
:80

@internal path *
request_header @internal x-custom caddy

$ caddy adapt
2021/03/23 21:58:27.394	INFO	using adjacent Caddyfile
{"apps":{"http":{"servers":{"srv0":{"listen":[":80"],"routes":[{"handle":[{"handler":"headers","request":{"replace":{"@internal":[{"replace":"caddy","search_regexp":"x-custom"}]}}}]}]}}}}}
```

**Comment by silverbackdan** [comment]
Wow thank you for such a quick fix! I'd go and explain the use-case but it hardly seems necessary to use your time further haha. I'll keep an eye on when it's merged.
