### ISSUE TITLE
Feature Request: Ability to change variables from config file

### ISSUE THREAD

**Issue by nmr50** [caddyserver/caddy#4086]
Hello Authors,
I am asking you to implement feature that will give user ability to change some needed variables like here:
caddyserver/caddy/v2@v2.3.0>diff replacer.go.orig replacer.go
289c289,290
// return nowFunc().Format("02/Jan/2006:15:04:05 -0700"), true
return nowFunc().Format("2006-01-02 15:04:05"), true
-- in config file - like this one:
log {
myDateTimeFormat "2006-01-02 15:04:05"
}
-- so myDateTimeFormat will change **time.now.common_log** variable into needed one.

Another variable to redefine is a **commonLogFormat** in modules/caddyhttp/server.go - in log{} section - myLogFormat with all those variables like {http.request.remote.host} {http.auth.user.id} [{time.now.common_log}] etc - user will be able to re-arrange them like needed, include those were not, or remove not need.

Thanks in advance !:)

-t

**Comment by Mohammed90** [comment]
Setting internal variables via config file is basically what config is. You intend to change the time format, which is already achievable via the `time_format` directive/config parameter. One workaround is to use the [github.com/caddyserver/format-encoder](https://github.com/caddyserver/format-encoder) like this:

```
log {
	format formatted `{request>remote_addr} - {request>headers>authorization>[0]} [{ts}] "{request>method} {request>uri} {request>proto}" {status} {size}` {
		time_format "2006-01-02 15:04:05"
		placeholder "-"
	}
}
```
which prints logs like this:
```
127.0.0.1:58552 - - [2021-03-24 17:13:51] "GET / HTTP/2.0" 200 87197
```
The only downside here is the presence of the remote port. That aside, doesn't the existing functionality achieve the purpose?

**Comment by nmr50** [comment]
As I see you've described how to use format-encoder plugin... but what about my question ?
You said "Setting internal variables via config file is basically what config is." - it is nice, and - how to do that ?:)

Once again - I want to redefine existing variable time.now.common_log (or nowFunc().Format ?) which contains  "02/Jan/2006:15:04:05 -0700" with my own desired format "2006-01-02 15:04:05".

Is it possible to do in config file ? If - yes - please tell me HOW to do that, w/o format-encoder at start :) I am asking about basic go functionality...

Thanks in advance !

**Comment by Mohammed90** [comment]
You want to override a [standard format](https://httpd.apache.org/docs/2.4/logs.html#common) with your own. For that you don't go changing private variables in source codes. You didn't need to dig through Caddy's code, find the variable defining the time format, edit it, and compile Caddy from scratch.  You use the provided tools and config parameters, which in this case are:
- The `time_format` config parameter
- Using the `format-encoder` module

This takes less effort than wanting the ability to dig through Caddy's code for variables.

**Comment by nmr50** [comment]
Of course digging through the source files, altering them and recompiling Caddy is not what I wanted, and this is why I opened this issue. ONCE AGAIN - I am still waiting for EXAMPLES - how to exactly I can modify variables' data ("02/Jan/2006:15:04:05 -0700") in config file ? Like log {
time_format "2006-01-02 15:04:05"
} - or not ? Tell me, please:)

Thanks in advance !

**Comment by Mohammed90** [comment]
You're trying to define your own format, so there's no way around having to use the `format-encoder` to define your own custom format.

**Comment by nmr50** [comment]
OK, so I cannot use my own variables to redefine static ones from GO files, so I need to use this format-encoder instead...

Let's imagine I recompiled Caddy with format-encoder plugin enabled... Can you tell exact config entry for the date/time syntax in output file like this: 2006-01-02 15:04:05 ?

Thanks in advance!

**Comment by francislavoie** [comment]
Did you read this comment? https://github.com/caddyserver/caddy/issues/4086#issuecomment-806018310

This has gone in circles long enough. You've been given the information you require multiple times but seem to be ignoring it. We can't spend any more time on this particular issue without increasing the frustrating levels of everyone involved. I'm locking this issue.
