### ISSUE TITLE
Feature request: Option to stall the client connection until backend is responsive again

### ISSUE THREAD

**Issue by sunebeck** [caddyserver/caddy#4088]
Two use-cases:

1) I have a legacy service that will sometimes give ECONNREFUSED due to being buggy / crashing. This happens for a few seconds every hour or so. I'd like to put Caddy in front and just stall the client connection until the backend works again.

2) When developing, I might restart a service. I'd like for the clients (or just my own browser) to hang on, until the backend is available again, by having Caddy stall the request.

In my nginx config I currently have a "fake" backend set as the second backend, which stalls for a few reconds before 301 redirecting back to the same URL. But it's kind of a hack.

**Comment by francislavoie** [comment]
I think this is exactly what `lb_try_duration` is for: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy
