### ISSUE TITLE
Cannot delete "Set-Cookie" response header from log entry

### ISSUE THREAD

**Issue by thomaskonrad** [caddyserver/caddy#4089]
I have the following log configuration:

    log {
        output file /logs/caddy/access.log {
            roll_size 100MiB
            roll_keep_for 14d
        }

        format filter {
            wrap json {
                message_key short_message
            }

            fields {
                request>headers>Cookie delete
                response>headers>Set-Cookie delete
            }
        }
    }

While the request `Cookie` header is omitted from the log, the response `Set-Cookie` headers are still there. I have tried a few variations (like `resp_headers_Set-Cookie` to resemble the JSON format), but had no success.

Does anyone know how to delete HTTP response headers from logs?

**Comment by francislavoie** [comment]
It should be `resp_headers>Set-Cookie delete`, I'm pretty sure.
