### ISSUE TITLE
[Feature request] Read from .htaccess file 

### ISSUE THREAD

**Issue by androidacy** [caddyserver/caddy#4091]
Most server side applications expect something like .htaccess to be accessible and respected.

However, Caddy neither reads nor respects .htaccess. Many of these applications  use .htaccess at runtime, meaning just adding it to Caddyfile is completely impractical, and most aren't aware of Caddy's API.

My current use case is several wordpress plugins that rely on .htaccess in one way or another. Wordpress itself will use php redirects, but those tend to be less efficient than doing them at the server level.

Please add support for this existing standard. Thanks!

**Comment by francislavoie** [comment]
There are no plans to support Apache configuration.

**Comment by androidacy** [comment]
It's not just apache, it'd litespeed and nginx but ok whatever

**Comment by francislavoie** [comment]
Nginx does not support `.htaccess`. They even have an article explaining why it's an antipattern: https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

For the same reasons, Caddy will not support this. Also what you're asking is by no means a small ask, it would require implementing an Apache configuration parser in Go, implement recursively reading directories to find such files, having dynamic behaviour, etc. It's not feasible and is counter to the goals of Caddy.

You should move any relevant rewrite rules and such to your Caddyfile, as needed.

**Comment by androidacy** [comment]
I. Can't. Move. Them.

As I already said, it's server side code that _expects htaccess to be respected_ and as such has absolutely no idea about Caddyfile  or API. In addition, restarting caddy every time something needs to have new redirection just isn't practical (I refuse to use the api for my own reasons, and stick to Caddyfile)

Nginx was my mistake; I have no idea where I got that tbh.

**Comment by androidacy** [comment]
Nginx is using specifically supported although I'm not really sure on the details but Caddy, being a lesser known server, isn't.

**Comment by francislavoie** [comment]
> In addition, restarting caddy every time something needs to have new redirection

You don't need to restart Caddy, simply reload for zero-downtime configuration changes. This isn't exclusive to the API, it works for any method of configuring Caddy.

It's not Caddy's job to support every wacky usecase that may exist, nor is it our job as open source maintainers to implement support for anything users ask. If you _absolutely need this_ then consider writing a plugin for Caddy to do it: https://caddyserver.com/docs/extending-caddy

Your expectations are unreasonable here.

**Comment by francislavoie** [comment]
The user decided to delete their comments.
