### ISSUE TITLE
How to use basicauth and tls?

### ISSUE THREAD

**Issue by do-web** [caddyserver/caddy#4092]
If i use basicauth with tls i get an error 

```
"logger":"tls.issuance.acme.acme_client","msg":"deactivating authorization",

{"level":"error","ts":1616969230.677829,"logger":"tls","msg":"job failed","error":"domain.com: obtaining certificate: [domain.com] Obtain: [domain.com] solving challenges: [domain.com] context canceled (order=https://acme-v02.api.letsencrypt.org/acme/order/111281218/8727418911) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
```

How can i solve this?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
