### ISSUE TITLE
OpenBSD release link?

### ISSUE THREAD

**Issue by neezer** [caddyserver/caddy#4095]
I don't see a link to download any OpenBSD [releases in the assets page on GH](https://github.com/caddyserver/caddy/releases/tag/v2.3.0):

<img width="1051" alt="Screen Shot 2021-03-29 at 11 01 52 AM" src="https://user-images.githubusercontent.com/29997/112879729-659d0380-907e-11eb-8857-9ca2d873af19.png">

The downloader on the website works:

<img width="1038" alt="Screen Shot 2021-03-29 at 11 02 52 AM" src="https://user-images.githubusercontent.com/29997/112879744-6b92e480-907e-11eb-9129-7fa208a18e6a.png">

but with a URL of:

> https://caddyserver.com/api/download?os=openbsd&arch=amd64&idempotency=3749599437417

which doesn't allow me to specify a version AFAICT. 

I'm looking for a deterministic way to download a specific version as part of a set of Ansible scripts I'm working on. 

Seems like an oversight that it's not included in the GH release?

**Comment by francislavoie** [comment]
We tend to only build combinations that are popular for releases on Github.

You can use a link like this:

https://caddyserver.com/api/download?os=openbsd&arch=amd64&p=github.com%2Fcaddyserver%2Fcaddy%2Fv2%40v2.3.0&idempotency=49780288454034

i.e. a module replacement of `github.com/caddyserver/caddy/v2@v2.3.0` (with url encoding)

This uses https://github.com/caddyserver/xcaddy under the hood, I'd recommend using that in your pipelines instead.

**Comment by mholt** [comment]
OpenBSD is our least popular platform (well, other than solaris and a few others we don't build for). Yours is the first request we've had for it.

**Comment by neezer** [comment]
@francislavoie Thanks, that link should work for my use case for now. Are binaries built on-the-fly from this link? Is that what you meant by "uses xcaddy under the hood"?

**Comment by francislavoie** [comment]
Yes they are built on the fly, but cached. It uses `xcaddy` to build them as requested. The reason for this is adding plugins to Caddy requires compiling them in. The download page is a "build server as a service". The build server does not have unlimited resources, so it would be best if you used your own resources to build when you need it, especially if you're going to be running that in CI.

**Comment by neezer** [comment]
Not planning on running this on CI; just one-off for setting up a dev workstation. Thanks for the info!
