### ISSUE TITLE
Can you please complete your ASF license template file (LICENSE) on github

### ISSUE THREAD

**Issue by tgelite** [caddyserver/caddy#4100]
Howdy... we are gathering up licensing we are using for legal review for our open source licensing... Can someone from the Caddy committers update the ASF license template to be for your organization/product.

Thanks!

**Comment by tgelite** [comment]
https://github.com/caddyserver/caddy/blob/e68dbe9cf8cfd06d9205e4346412c90691f78e60/LICENSE#L190

**Comment by thaJeztah** [comment]
That part must be left empty; it's a template to use when applying the license, and should not be modified in the LICENSE file, which must be included as-is

To _apply_ the  license (see the instructions in the license file);

```
To apply the Apache License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "[]"
replaced with your own identifying information. (Don't include
the brackets!)  The text should be enclosed in the appropriate
comment syntax for the file format. (...)
```

Which is what was done in this repository; https://github.com/caddyserver/caddy/blob/2772ede43c852fa50f3527dbd94ae747b6f64365/cmd/commands.go#L1-L13

**Comment by tgelite** [comment]
Ok thanks for that answer, I'll present that instead.

**Comment by thaJeztah** [comment]
Note that technically, each file can have a different copyright / license header; so it's possible that some files have different copyright holders (or a different license); also be sure to check if repositories have a `NOTICE` or `COPYING` file, which may contain additional information about that, e.g. https://github.com/containerd/containerd/blob/master/NOTICE

**Comment by tgelite** [comment]
Thank you so much, yes, indeed we are going to have to figure out how to scan all of this appropriately, I think I'm going to point SNYK licensing scan at an instance of our repo to mine what we are missing.
