### ISSUE TITLE
Cannot locate the tls files

### ISSUE THREAD

**Issue by devItGym** [caddyserver/caddy#4110]
Used these commands to install Caddy.
```
 curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/cfg/setup/config.deb.txt?distro=debian&version=any-version' | sudo tee -a /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install caddy
```
The version of caddy installed is: 2.3.0

Trying to locate the actual tls cert files. The documentation says it would be at 
` ~/.caddy`
or in 
`~/.local/share/caddy`

Cannot find them in any of these places. They must be somewhere because the https is working.  

Thanks for the help...

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

When running as a service, Caddy runs as the `caddy` user. It's home is `/var/lib/caddy`.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
