### ISSUE TITLE
Feature: Allow 'named matchers' inside 'not' matcher

### ISSUE THREAD

**Issue by fanste** [caddyserver/caddy#4112]
According to my testing it is currently not possible to do something like
```
@specialHandling {
    path /App1/* /App2/* /App3/*
}

@anotherSpecialHandling {
    not @specialHandling 
}

<ANY_MATCHER_BASED_DIRECTIVE> @specialHandling {
    ...
}

<ANY_MATCHER_BASED_DIRECTIVE> @anotherSpecialHandling {
    ...
}
```

In my setup I use caddy as a TLS enabled reverse proxy for my application server. We have to use multiple application servers as there are some legacy apps, that are not yet upgraded to the newer technologies. But every app should be available from the same host:port, so users don't have to change bookmarks or links referenced in other documents once the legacy apps are upgraded.

Additionally we use the filter module to fix some path/host/port issues that this setup introduces:
- http -> https
- pathes to some assets
- ...

The requested change would allow us to only specify the legacy apps in `@specialHandling` which runs some specific filter rules for those legacy apps while all other apps should have its own filter rules - therefore the `@anotherSpecialHandling `.
Currently we have to write
```
@specialHandling {
    path /App1/* /App2/* /App3/*
}

@anotherSpecialHandling {
    not path /App1/* /App2/* /App3/*
}
```
which is a bit error prone. That will get worse if more complex matchers are required.

**Comment by thedadams** [comment]
I have an implementation for this that also allows for named matchers to contain other named matchers like:
```
@AppPath {
    path /App/*
}

@HeaderFoo {
    header Foo bar
}

@specialHandling {
    @AppPath
    @HeaderFoo
}

@anotherSpecialHandling {
    not @specialHandling
}
```

I am figuring out where the tests should go, and then I can submit a PR.

**Comment by francislavoie** [comment]
Interesting @thedadams! Generally we use adapt tests for any Caddyfile changes https://github.com/caddyserver/caddy/tree/master/caddytest/integration/caddyfile_adapt

**Comment by francislavoie** [comment]
@thedadams did you make any progress on this?

**Comment by thedadams** [comment]
Yes, the tests revealed an issue with my implementation and then I went on vacation. I have a potential fix, but now I am touching more of the unmarshal code, so I want to get it right.

**Comment by thedadams** [comment]
@francislavoie I have submitted the PR for this change. I understand that a documentation update is also necessary for this update. I would be happy to do that as well when the PR is close to being merged.

**Comment by mholt** [comment]
Thank you for working on this @thedadams -- however as noted in the PR the implementation is extremely difficult. I'm going to close this, but am marking this as deferred so we can optionally come back to it later. Really appreciate it!

**Comment by Tmpod** [comment]
> (As a workaround for now, we have the [CEL matcher](https://caddyserver.com/docs/caddyfile/matchers#expression) which allows flexible expressions to be written.)

You can't use/include named matchers in expressions, can you?
Something like

```caddyfile
@foo not `@bar || @baz || @bork`
reverse_proxy @foo ...
```

**Comment by francislavoie** [comment]
@Tmpod no, named matchers are Caddyfile sugar, they don't exist in the adapted JSON config so they don't exist to be referenced by expression matchers.

**Comment by Tmpod** [comment]
I see. Is there a way to combine multiple named matchers then (for example, to negate them)?

Even if they're just sugar, maybe the Caddyfile processor could just expand them into their values when referenced in other marchers.

**Comment by francislavoie** [comment]
No, it's not possible to combined named matchers. We tried implementing it with https://github.com/caddyserver/caddy/pull/4264 but we had to abandon it because it was unreasonably complicated and had many edgecases we couldn't resolve.

**Comment by Tmpod** [comment]
Right, I saw that issue as well, it's a pitty...

What do you suggest I do instead? Just duplicate the marchers' code?

**Comment by francislavoie** [comment]
Use the expression matcher, which now supports all other matchers as pseudo-functions.

**Comment by Tmpod** [comment]
Yeah, should be trivial, as I'm already using expression matchers in the named ones. It's just a shame you have to duplicate the code.

**Comment by andoks** [comment]
@francislavoie sorry for necroing this already closed issue, but by

> Use the expression matcher, which now supports all other matchers as pseudo-functions.

Is there some way to call our own custom named matchers this way?

**Comment by francislavoie** [comment]
Yes @andoks you need to implement the https://pkg.go.dev/github.com/caddyserver/caddy/v2/modules/caddyhttp#CELLibraryProducer interface. Unfortunately it's really gnarly to implement, but you can copy-paste examples from caddy source which implements those. Look at a matcher that has similar config layout to yours, then copy that code.
