### ISSUE TITLE
Feature: Allow executing command post TLS cert renewal

### ISSUE THREAD

**Issue by FantasyCookie17** [caddyserver/caddy#4114]
It would be nice if there was a directive that allowed one to automatically execute a command (that is forked into the background) whenever a certificate is renewed. This would be useful for various purposes:
* One may distribute the cert to other machines if those run other things on the same domain
* One may check that the CT chain is valid so far and no other certs have been issued for the domain other than the ones one issued oneself (while I'm not aware of such a tool existing, I'm considering writing a program or script that does this)
* One may update TLSA records

So, what I'm picturing is something like this:
```
somedomain.com {
    # Some other config
    tls {
        post_renewal_exec /path/to/myscript.sh
    }
}
```

It may be that this requires changes to the CertMagic  library. I'm not too familiar with the entire architecture myself, so I thought I'd ask here first.

**Comment by francislavoie** [comment]
Duplicate of https://github.com/caddyserver/caddy/issues/3643

**Comment by FantasyCookie17** [comment]
Oh. I just searched for `tls` in the issues, so didn't see that one. I'll close this, then.
