### ISSUE TITLE
panic: qtls.CertificateRequestInfo doesn't match

### ISSUE THREAD

**Issue by hongyi-zhao** [caddyserver/caddy#4118]
On Ubuntu 20.04, I compiled the git master version of caddy but failed to start it as shown below:
```
$ ./caddy 
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
	/home/werner/go/pkg/mod/github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x28a
```
Any hints for fixing this problem?

Regards,
HY

**Comment by francislavoie** [comment]
Which version of Go are you using? How can we replicate this? Our tests are all green.

**Comment by hongyi-zhao** [comment]
```
$ go version
go version devel go1.17-776d8d387c Sun Apr 4 00:01:03 2021 +0000 linux/amd64

$ git clone https://github.com/caddyserver/caddy.git caddy.git
$ cd caddy.git
$ git log -1
commit 96bb3659299ae5ef28ffb3f9a23e16417c570924 (HEAD -> master, origin/master, origin/HEAD)
Author: Matthew Holt <mholt@users.noreply.github.com>
Date:   Fri Apr 16 11:17:15 2021 -0600

    httpcaddyfile: Take into account host scheme/port (fix #4113)

$ cd cmd/caddy/
$ go build
$ ./caddy 
panic: qtls.CertificateRequestInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-16.init.0()
	/home/werner/go/pkg/mod/github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x28a
```

**Comment by francislavoie** [comment]
We don't build for Go 1.17 yet. Please try with 1.16 for now. We'll add support for 1.17 when it's closer to release.

**Comment by hongyi-zhao** [comment]
If so, I think that I should use some golang version management tool, e.g., [goenv](https://github.com/syndbg/goenv), to facilitate the testing.

**Comment by francislavoie** [comment]
I'm not seeing anything actionable here, so I'll close this.

**Comment by Anibal150420** [comment]
150420any

**Comment by dtbartle** [comment]
go1.17 was recently released and this is still an issue, can we reopen?

**Comment by francislavoie** [comment]
@dtbartle what commit are you building from? What's your build output? We've merged in Go 1.17 support on the master branch recently.

**Comment by dtbartle** [comment]
Ah, didn't realize it was fixed already!

**Comment by jauderho** [comment]
Looks like there is a different repo for 1.17.  

See https://github.com/marten-seemann/qtls-go1-17  instead of https://github.com/marten-seemann/qtls-go1-16

**Comment by francislavoie** [comment]
No @jauderho, see https://github.com/caddyserver/caddy/pull/4297. The main quic-go version must be updated.

**Comment by jauderho** [comment]
@francislavoie Just missed seeing your prior message. =)

**Comment by overflowingd** [comment]
@francislavoie I found the same issue when built with go1.18

**Comment by francislavoie** [comment]
@overflowingd how are you trying to build?

This is definitely no longer a problem. Make sure you're building the latest version of Caddy.

**Comment by overflowingd** [comment]
> @overflowingd how are you trying to build?
> 
> This is definitely no longer a problem. Make sure you're building the latest version of Caddy.

I apologize. There was my mistake.
The problem raised when I ran a build for another package that uses previous version of Caddy.
