### ISSUE TITLE
Usage of 'error' directive in Caddyfile has no effect

### ISSUE THREAD

**Issue by noelforte** [caddyserver/caddy#4119]
Unsure if the error directive either hasn't been implemented fully in the latest beta, or if I'm missing something configuration-wise. Either way, it appears that using it in a Caddyfile has no effect, regardless if the path is matched.

### Reproducible in both:
- Current beta: `v2.4.0-beta.2 h1:DUaK4qtL3T0/gAm0fVVkHgcMN04r4zGpfPUZWHRR8QU=`
- `master@96bb365` : `v2.4.0-beta.2.0.20210416171722-96bb3659299a h1:7WPBfXThY9LVFv0OKS3PnS0cXpVAqxuGNMOp6aDA9jQ=`

### Caddyfile configuration:

Taken from: https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/directives/error.md 

```
localhost {
  error /private* 403
  file_server

  handle_errors {
    rewrite * /error.html
    file_server
  }
}
```

### What I expected would happen:

After running caddy with `caddy run`, an http request to `/private/<anything>` would throw a 403 error even if an `index.html` file was present there. 

### What actually happened:

Hitting `/private/` or `/private/index.html` with a request doesn't throw an error and returns `200 OK` instead.

![image](https://user-images.githubusercontent.com/2560683/115126151-14a46f00-9f9b-11eb-9cbd-63248b209642.png)

---

### Follow-up:

I thought I remembered reading somewhere that the directive order was still up for debate. Wrapping the `error` and `file_server` directive in a `route` directive appears to get `error` to function as expected. I'll keep this issue open for now in case someone else runs into similar issues pre-2.4.0 release or if this behavior is unintended and is a bug.

**Comment by francislavoie** [comment]
Yeah, the `error` directive is ordered last. This is working as expected. https://github.com/caddyserver/caddy/tree/master/caddyconfig%2Fhttpcaddyfile%2Fdirectives.go#L73

**Comment by mholt** [comment]
We could order it earlier, but the question really boils down to which is more common: error handling in the "fallback" case, or error handling in the "specific" case (and how do you define specificity?) -- see _Composing in the Caddyfile_ from our wiki: https://caddy.community/t/composing-in-the-caddyfile/8291

We opted for the fallback case with the `error` directive.
