### ISSUE TITLE
Feature: introduce an option to disable access logs for the respond directive

### ISSUE THREAD

**Issue by weisdd** [caddyserver/caddy#4120]
It would be great to have an option to disable access logs for the `respond` directive.

For example, let's say we want to have a healthcheck probe in Kubernetes environment and also send logs to stdout for incoming requests. Caddyfile might look like this:

```
{
    admin off
    auto_https off
}

http://:8080

respond /healthz 200

log {
 format json
}

reverse_proxy http://127.0.0.1:8196
```

Logs for the `/healthz` are useless, and we'll have lots of records if healthchecks are frequent enough. Currently, you cannot configure the `respond` directive to turn off the logs for it.

Thanks!

**Comment by francislavoie** [comment]
You can instead move your health check to a different site (different hostname or port) and not enable access logs there.

I don't think we want to add complexity to the logging facilities. Instead, you should use some tooling to filter out any logs you don't want to see.

**Comment by mholt** [comment]
Yep, I think that is the best approach: Caddy emits logs (for efficiency and simplicity), but you can control them before they go anywhere.
