### ISSUE TITLE
How does caddy2 adjust the number of support threads so that more people can access it?

### ISSUE THREAD

**Issue by weew2** [caddyserver/caddy#4126]
I found that my caddy server encountered an access bottleneck, but I have no way to know how to check the number of threads supported by caddy. Can you give a way to view caddy support threads? And how to adjust the parameters?

**Comment by mholt** [comment]
I saw you posted on the forum also: https://caddy.community/t/how-to-check-the-maximum-number-of-threads-supported-by-the-caddy-server/12228

Will close that since it's a better fit on the forum.
