### ISSUE TITLE
Apache mod_substitute to Caddy

### ISSUE THREAD

**Issue by StrangeRanger** [caddyserver/caddy#4127]
I find that I use Caddy a lot as a reverse proxy for web applications that of which I'm unable to directly modify the HTML. I found that Apache can use the substitute module, to say, add the necessary code for Matomo Analytics to work (an example of it is below). Though I noticed that Caddy doesn't have any feature similar to this. 

```conf
AddOutputFilterByType SUBSTITUTE text/html
Substitute "s|</head>|<script type=\"text/javascript\" src=\"https://example.com/scripts/tracking.js\"></script><noscript><p><img src=\"https://analytics.example.com/matomo.php?idsite=1&amp;rec=1\" style=\"border: 0\" alt=\"\" /></p></noscript></head>|in"
```

---

It'd be really nice to have the ability to substitute things such as HTML, similar to how you can in Apache.

**Comment by francislavoie** [comment]
I think you're looking for this plugin: https://github.com/caddyserver/replace-response

**Comment by StrangeRanger** [comment]
Oh, thank you.
