### ISSUE TITLE
Defining default values for headers doesn't work if the server returns a header

### ISSUE THREAD

**Issue by Crocmagnon** [caddyserver/caddy#4130]
The documentation of the header directive teaches us we can define default values for headers, which will be used if the server doesn't already provide one. Neat! So given the following configuration:

```
(common_headers) {
    header * {
        ?Strict-Transport-Security max-age=31536000
        ?Referrer-Policy "strict-origin-when-cross-origin"
    }
}
site.example.com {
    import common_headers
    reverse_proxy 127.0.0.1:8000
}
```

I'd expect to get responses including both headers with either the default value or a value provided by Caddy.
The current behavior though is to return both default value when *none* of these headers appear in the server response and to *not include any default value* if *any of the headers* appear in the response.

So in other terms, considering the following proxied response headers:
```
Date: Fri, 23 Apr 2021 14:53:49 GMT
Expires: Fri, 23 Apr 2021 14:53:49 GMT
```

Caddy will produce the following headers:
```
Date: Fri, 23 Apr 2021 14:53:49 GMT
Expires: Fri, 23 Apr 2021 14:53:49 GMT
Strict-Transport-Security: max-age=31536000
Referrer-Policy: strict-origin-when-cross-origin
```

But with these proxied response headers:
```
Date: Fri, 23 Apr 2021 14:53:49 GMT
Expires: Fri, 23 Apr 2021 14:53:49 GMT
Referrer-Policy: no-referrer
```

Caddy will produce the following headers (it doesn't add the expected default for `Strict-Transport-Security`) :
```
Date: Fri, 23 Apr 2021 14:53:49 GMT
Expires: Fri, 23 Apr 2021 14:53:49 GMT
Referrer-Policy: no-referrer
```

I'd say the issue is linked to code from PR #3807 but I'm not sure.

**Comment by francislavoie** [comment]
How it works is that when you specify a `?` header, it sets up a "require" response matcher. When you specify more than one header, then it will only match if all of those headers are not present.

If you want to set them individually, then you need to split it up into multiple `header` handlers:

```
header ?Strict-Transport-Security max-age=31536000
header ?Referrer-Policy "strict-origin-when-cross-origin"
```

I'm not really sure if this can be considered a bug or not, but anyways that's how it works right now.

**Comment by Crocmagnon** [comment]
Thanks for your quick answer! Maybe we only need to update the documentation then? 😊

**Comment by francislavoie** [comment]
I opened a docs PR to try and clarify this https://github.com/caddyserver/website/pull/155, but FYI @mholt we may want to consider rejecting a Caddyfile config that uses `?` along with other operations (i.e. maybe only allow it on the same-line, not within braces), or warn about it at least.

**Comment by mholt** [comment]
I think a mention in the Caddyfile docs is good enough for now; if this mistake keeps happening, we can see about adding a warning.
