### ISSUE TITLE
Caddyfile: Setting health_status for reverse proxy to a specific code does not work.

### ISSUE THREAD

**Issue by Timbus** [caddyserver/caddy#4133]
Hi,
It looks like if you set `health_status` to something like 401, it parses it into a single number HTTP code class as if it were set to 4xx.
The documentation is quite vague about this:
>health_status is the HTTP status code to expect from a healthy backend. Can be a 3-digit status code or a status code class ending in xx, for example: 200 (default) or 2xx.

I think it should be fixed to parse exact numbers when setting expect_status, or the documentation might want to be more clear. A 404 is extremely different to a 401 in the context of a health check..

**Comment by Timbus** [comment]
Ack, fixed in a recent-ish commit. I only searched issues, should have checked commits.

**Comment by francislavoie** [comment]
Yep; for reference, it was fixed in https://github.com/caddyserver/caddy/commit/75f797debdd6c4294497edba9889c6251a8542e7

Thanks for looking at the commits! It's a step further than most people go 😊
