### ISSUE TITLE
[Bug] reverse_proxy can skip hosts when using any hashing policy

### ISSUE THREAD

**Issue by Timbus** [caddyserver/caddy#4135]
TLDR: https://github.com/caddyserver/caddy/blob/a8d45277ca387ca4769fb4e881d242a5896cca5a/modules/caddyhttp/reverseproxy/selectionpolicies.go#L526 this will skip hosts if it loops, because you're incrementing `i` as well as `index`. Please avoid mutating things in a loop..

Anyway just replace `+=` with `+` I guess, and just throw it inline or something.

Learned about this in the worst possible way (in production), because our one healthy host wasn't getting traffic some of the time.

**Comment by Timbus** [comment]
Long version (was too tired to elaborate): When a host isn't healthy/available, the hash selector tries to move on to the next healthy host in the pool array. The issue is the code is incrementing the index 'pointer' by `i` each time, instead of by 1. So it's looping through each host in some fibbonacci-esque.. triangle number way. Which is just weird and won't work.
There are a few ways to improve this, such as changing the loop to a `while (i != start_i)`, or statically calculating the offset as 'index + i'

An easy testcase for this is to have a pool of 3 hosts, two unavailable: [Dead, Dead, Ok], and if you start at i = 0, index = 0, and use the above code I linked you'll miss the last element, thus returning nil and logging to the user that no healthy hosts are available.

**Comment by francislavoie** [comment]
PRs welcome! :slightly_smiling_face:

**Comment by simaotwx** [comment]
I proposed a fix that does not break existing tests, however I haven't added specific tests that replicate the reported behavior (yet)

**Comment by mholt** [comment]
Thank you for the report, and for the fix, respectively!
