### ISSUE TITLE
Caddy reverse_proxy directive tampers with tcp streams

### ISSUE THREAD

**Issue by nunogt** [caddyserver/caddy#4136]
This could be a duplicate of https://github.com/caddyserver/caddy/issues/3584 but it was never reproduced properly so raising again. Admittedly I haven't had time to fully diagnose this because I'm working with tcp protocols and and lacking the tooling to debug at the moment. 

In any case, describing the problem is fairly straightforward: configuring caddy:2 to behave as a tcp reverse proxy as per [this link](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) results in corruption.

Caddyfile:
```
localhost
reverse_proxy tcp/10.0.0.1:1234
``` 

Result: client complains about invalid protocol

nginx.conf:
```
stream {
	server {
		listen 80;
		proxy_pass 10.0.0.1:1234;
	}
}
```

Result: TCP connection is correctly and transparently forwarded upstream

I've also tried the following variation to the Caddyfile:
```
localhost
reverse_proxy tcp/10.0.0.1:1234 {
    header_up -X-Forwarded-For
    header_up -X-Forwarded-Proto
}
```

Yielding the same results (corrupted stream)

**Comment by mholt** [comment]
The reverse_proxy directive is an HTTP proxy, not a TCP proxy. So yes, it tampers with streams of packets. :)

To proxy TCP, use the l4 module: https://github.com/mholt/caddy-l4

**Comment by nunogt** [comment]
OK, thanks @mholt. Given that caddy-l4 exists now you might want to make the the [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) documentation more explicit. I've read it thoroughly and it mentions that "upstream addresses can take the form of a conventional Caddy network address", going as far as offering special syntax for tcp, udp, and unix sockets without mentioning the http transport limitation.

Thanks for your work and quick response to this issue
