### ISSUE TITLE
Fowarding to target website via a socks5 proxy. 

### ISSUE THREAD

**Issue by hongyi-zhao** [caddyserver/caddy#4144]
I want to do the following with caddy: Suppose caddy is running on a host with the FQDN `x.y.z`, when I access x.y.z:8080, it can redirect me to the target website, say, `a.b.c` via a specific socks5 proxy, say, `x.y.z:21080`.

Any hints for this problem will be highly appreciated.

Regards,
HY

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
