### ISSUE TITLE
"caddy upgrade" should only upgrade if needed

### ISSUE THREAD

**Issue by Caligatio** [caddyserver/caddy#4159]
The `caddy upgrade` functionality released in v2.4.0 appears to always replace the `caddy` binary regardless of whether it actually needs to be upgraded. It would be ideal if the `caddy upgrade` command either only upgraded when necessary or returned a non-zero exit code if the old+new versions matched.  My end goal would be able to add a cron job like `@weekly /path/to/caddy upgrade && systemctl restart caddy` and have that restart the caddy service only when it was actually upgraded.

I coded up an [upgrade script](https://gist.github.com/Caligatio/f97ba88dad586ed2a0423f34ce67106b) that accomplishes this by comparing the hashes of the old and new binary but it's non-ideal in that it has to download the binary every time to do the comparison.  As an aside, it would also be useful if the download page/service somehow made the hashes of the various bundles available.   For instance, I need to download https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare so it would be handy to have something like https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare.digest (note the .digest at the end) or something.

EDIT: Something like certbot's `--deploy-hook` would also satisfy this need: you could specify a hook that would be called iff an upgrade took place.

**Comment by francislavoie** [comment]
I think this is a duplicate of https://github.com/caddyserver/caddy/issues/4057

**Comment by Caligatio** [comment]
I did originally see that issue but didn't realize it was the same core problem that was encountered two different ways.  Closing this issue.
