### ISSUE TITLE
Fabulous Work !

### ISSUE THREAD

**Issue by LordPraslea** [caddyserver/caddy#4162]
Just wanted to say that you guys are doing some fabulous work with caddy.

I was searching for something like Caddy for quite some time. I've always managed to find suboptimum solutions which required a lot of fiddling  and energy.

I'm impressed with only 1 hour of experimentation on my pc and on a raspberrypi.

It seems to be able to do everything I want from a server.

Thanks and keep up the good work!

**Comment by mholt** [comment]
Thank you :blush: We love to hear it.

It's refreshing to get an issue that is the opposite of a problem, once in a while. :clinking_glasses:

**Comment by bartvanhoutte** [comment]
+1
