### ISSUE TITLE
2.4.0 experimental_http3 Invalid error

### ISSUE THREAD

**Issue by aybru** [caddyserver/caddy#4166]
```
{
 experimental_http3
}
```

{"level":"info","ts":1620867576.0386837,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
run: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized global option: experimental_http3

```
https://domain {
 protocol {
  experimental_http3
 }
}
```

{"level":"info","ts":1620868408.139266,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
run: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized directive: protocol

**Comment by francislavoie** [comment]
In v2.3.0, the `experimental_http3` was moved to under the `servers` global option. https://github.com/caddyserver/caddy/releases/tag/v2.3.0

See the docs https://caddyserver.com/docs/caddyfile/options#server-options

```
{
	servers {
		protocol {
			experimental_http3
		}
	}
}
```
