### ISSUE TITLE
Caddy responds with 200 when no address matched

### ISSUE THREAD

**Issue by jtyr** [caddyserver/caddy#4173]
I have this config:

```caddyfile
http://localhost:8084 {
  respond 204
}
```

When I run:

```shell
curl -I localhost:8084
```

I get `204`. When I run:

```shell
curl -I 127.0.0.1:8084
```

I get `200`. I believe I shouldn't get `200` but `404` or some other error code.

**Comment by mholt** [comment]
200 is correct. 404 is when a file isn't found, or similar. There was nothing configured to not find.

**Comment by francislavoie** [comment]
The problem is that you specified `localhost` as your hostname to match, but then made a request with `127.0.0.1`. If you want to handle all requests on that port the same, then use `http://:8084` as your site address instead.

**Comment by jtyr** [comment]
I find this very confusing. If I have config:

```
http://nothing:8080 {
  respond 204
}
```

And then run:

```shell
curl -I localhost:8080
```

I get `200`. Why is the default server response `200`? Another good example is `http://0.0.0.0:8080` which I would expect to match any IP.

**Comment by francislavoie** [comment]
Run `caddy adapt --pretty`, and you'll see what it does. There's a `nothing` host matcher. If that doesn't match, then it falls through and returns `200` like I said.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
