### ISSUE TITLE
SRV lookups only use first response

### ISSUE THREAD

**Issue by sorenisanerd** [caddyserver/caddy#4174]
https://github.com/caddyserver/caddy/blob/e3c369d4526e44f23efb10aaad8a60ce519720a0/modules/caddyhttp/reverseproxy/hosts.go#L152

Even if the the DNS randomizes the order of entries (while still observing priorities), it's still perfectly possible for all the top-priority servers to be at capacity, in which case the we should move on to entries with lower priority.

**Comment by francislavoie** [comment]
Please elaborate, I don't think there's really enough detail to make this actionable.

PRs welcome, if you know the fix that needs to be made.

**Comment by sorenisanerd** [comment]
An SRV lookup returns all SRV entries. Each entry has a priority and a weight.

A correct use of that response should group the entries by priority and attempt to use the top (numerically lowest) priority entries first. Their respective weights should define their odds of getting picked. Once the top priority group is exhausted with no succesful reply, only then should we move on to the next group.

However, Caddy will only use a single entry, namely the first one. Even with many SRV entries, an incoming request will fail to be served correctly if the first entry happens to be one for a server that is unhealthy.

**Comment by francislavoie** [comment]
I think you need to enabled `lb_try_duration` for the retry logic to kick in.

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing

**Comment by sorenisanerd** [comment]
The gold plated way to address this would be:
1) The addition of a selection policy that (independent of SRV lookups) allows specifying both priority and weight to backends.
2) An incoming request triggers an SRV lookup which populates the backend data for the above mentioned selection policy which then proceeds as usual.

**Comment by sorenisanerd** [comment]
`lb_try_duration` will do me little good if it'll only ever try the first entry. There's no guarantee that the DNS will randomize responses and even if it did, I don't see how Caddy would ever fall back to an entry that does not have top priority.

**Comment by sorenisanerd** [comment]
For clarity, I understand that most people probably have Consul or something similar maintaining their SRV records, so you should never get SRV entries for unhealthy backends. In that case, everything is fine. My use case is somewhat different.

**Comment by francislavoie** [comment]
This kinda goes hand-in-hand with https://github.com/caddyserver/caddy/issues/1545

**Comment by Mohammed90** [comment]
Jotting down thoughts as I took glances at the code to understand what it could touch:

- The module implementing this will most likely be in the [`http.reverse_proxy.selection_policies` namespace](https://github.com/caddyserver/caddy/blob/e3c369d4526e44f23efb10aaad8a60ce519720a0/modules/caddyhttp/reverseproxy/reverseproxy.go#L864-L893), and the body of the logic is an implementation of the [Selector interface](https://github.com/caddyserver/caddy/blob/e3c369d4526e44f23efb10aaad8a60ce519720a0/modules/caddyhttp/reverseproxy/reverseproxy.go#L895-L898).
https://github.com/caddyserver/caddy/blob/e3c369d4526e44f23efb10aaad8a60ce519720a0/modules/caddyhttp/reverseproxy/reverseproxy.go#L895-L898

- The `Upstream` struct needs to be extended with members representing weight and priority as received via the SRV lookup. It already has commented fields for `HeaderAffinity` and `IPAffinity`, which have similar concept.
https://github.com/caddyserver/caddy/blob/e3c369d4526e44f23efb10aaad8a60ce519720a0/modules/caddyhttp/reverseproxy/hosts.go#L65-L98

**Comment by mholt** [comment]
I'm working on this.

**Comment by mholt** [comment]
@sorenisanerd Would you like to give my PR, #4470, a try? It only supports JSON config for now, but you can just use `caddy adapt` and then tweak your config to use the new dynamic upstreams feature.

**Comment by sorenisanerd** [comment]
I would love to, but I discarded the experiment I was doing and canned the project, so I don't have backend servers, name servers, or anything else that I'd need to try it out. Sorry :(

**Comment by mholt** [comment]
Done in #4470.
