### ISSUE TITLE
fuzz-parse-duration: Timeout in fuzz-parse-duration

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#4175]
Detailed Report: https://oss-fuzz.com/testcase?key=5709450890575872

Project: caddy
Fuzzing Engine: libFuzzer
Fuzz Target: fuzz-parse-duration
Job Type: libfuzzer_asan_caddy
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address: 
Crash State:
  fuzz-parse-duration
  
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_caddy&revision=202105210615

Reproducer Testcase: [clusterfuzz-testcase-minimized-fuzz-parse-duration-5709450890575872](https://github.com/caddyserver/caddy/files/6526383/clusterfuzz-testcase-minimized-fuzz-parse-duration-5709450890575872.txt)

Issue on oss-fuzz tracker: [Issue 34547](https://crbug.com/oss-fuzz/34547)

**Comment by Mohammed90** [comment]
[Update from the Fuzz Overlords](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34547#c4):

> ClusterFuzz testcase 5709450890575872 is flaky and no longer crashes, so closing issue.

**Comment by mholt** [comment]
Dangit, I put the wrong issue number in that commit

**Comment by mholt** [comment]
Ok, actually fixed in f1f7a22, where we return an error for duration strings longer than 1024. Can't imagine why one would need to be any longer than that.

(Also note that duration inputs are typically trusted.)
