### ISSUE TITLE
Reverse proxy rewrite of X-Accel-Redirct for static files doesn't decode url for use as a file path

### ISSUE THREAD

**Issue by jshcrm** [caddyserver/caddy#4180]
Using the X-Accel-Redirect example [here](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) works fine for files that don't contain spaces. However, if the file contains a space, then the url is encoded with spaces replaced with %20. When rewriting the header the spaces are still encoded, so Caddy is unable to find the file to serve. This comes on the heels of [this community ticket](https://caddy.community/t/empty-http-response-header-x-accel-redirect/12447/13) fixed in 2.4.1. 

### Caddy Version
Caddy Docker image v2.4.1

### How to Reproduce
Using the X-Accel-Redirect code found in the examples [here](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy), send a request with the X-Accel-Redirect header set to the path of a file on Caddy Server. 

The path `/files/my_filename.txt` will return the file as expected because the filename has no spaces.

The path `/files/my%20filename%20.txt`, which is how sendfile will encode the url, returns a 404.

### Logs

**Here are the logs from a working request if i remove all spaces from the filename:**

```
caddy | {"level":"debug","ts":1622056417.8628917,"logger":"http.handlers.rewrite","msg":"rewrote request","request":{"remote_addr":"192.168.192.1:34612","proto":"HTTP/2.0","method":"GET","host":"app.localhost","uri":"/attachments/retrieve/274894/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Dnt":["1"],"Te":["trailers"],"X-Forwarded-For":["192.168.192.1"],"Cookie":["csrftoken=HWrKYeuvbneF6TvtQkwdZl2tHQztRjO7Xyk8dD5HhWVGNDOoWcdwRyQpCeOa2jeM; sessionid=asq6kld8llryhr5fedvp5lqcsz682zzt"],"Upgrade-Insecure-Requests":["1"],"X-Forwarded-Proto":["https"],"Referer":["https://app.localhost/p/kelly-chopin/ft-myers-fl-building-urgent-care-and-bank/final-reports/"],"Sec-Gpc":["1"],"If-Modified-Since":["Wed, 26 May 2021 13:05:17 GMT"],"If-None-Match":["\"qtptot1744q\""],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"app.localhost"}},"method":"GET","uri":"/my_dir/211699CostSegReport05-20-210719.pdf"}

caddy | {"level":"debug","ts":1622056417.862949,"logger":"http.handlers.file_server","msg":"sanitized path join","site_root":"/","request_path":"/my_dir/211699CostSegReport05-20-210719.pdf","result":"/my_dir/211699CostSegReport05-20-210719.pdf"}

caddy | {"level":"debug","ts":1622056417.86298,"logger":"http.handlers.file_server","msg":"opening file","filename":"/my_dir/211699CostSegReport05-20-210719.pdf"}

caddy | {"level":"error","ts":1622056417.8630593,"logger":"http.handlers.reverse_proxy","msg":"reading from backend","error":"http: read on closed response body"}

caddy | {"level":"error","ts":1622056417.8630683,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"http: read on closed response body"}
```

**Here are the logs from a broken request when the filename contains spaces:**

```
caddy| {"level":"debug","ts":1622056649.8914535,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"app:8080","request":{"remote_addr":"192.168.192.1:34754","proto":"HTTP/2.0","method":"GET","host":"app.localhost","uri":"/attachments/retrieve/274890/","headers":{"Te":["trailers"],"X-Forwarded-For":["192.168.192.1"],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Dnt":["1"],"Sec-Gpc":["1"],"X-Forwarded-Proto":["https"],"Accept-Encoding":["gzip, deflate, br"],"Cookie":["csrftoken=HWrKYeuvbneF6TvtQkwdZl2tHQztRjO7Xyk8dD5HhWVGNDOoWcdwRyQpCeOa2jeM; sessionid=asq6kld8llryhr5fedvp5lqcsz682zzt"],"Upgrade-Insecure-Requests":["1"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"app.localhost"}},"headers":{"X-Accel-Redirect":["/my_dir/211699%20Cost%20Seg%20Report%2005-22-21%2013%3A03.pdf"],"Content-Disposition":["inline; filename=\"211699 Cost Seg Report 05-22-21 13:03.pdf\""],"Server-Timing":["TimerPanel_utime;dur=279.3689999999991;desc=\"User CPU time\", TimerPanel_stime;dur=11.874000000000162;desc=\"System CPU time\", TimerPanel_total;dur=291.24299999999926;desc=\"Total CPU time\", TimerPanel_total_time;dur=300.1978397369385;desc=\"Elapsed time\", SQLPanel_sql_time;dur=8.519411087036133;desc=\"SQL 11 queries\", CachePanel_total_time;dur=0;desc=\"Cache 0 Calls\""],"Vary":["Cookie"],"Server":["gunicorn"],"Connection":["keep-alive"],"Content-Type":["application/pdf"],"Content-Length":["2011562"]},"status":200}

caddy | {"level":"debug","ts":1622056649.8915482,"logger":"http.handlers.reverse_proxy","msg":"handling response","handler":0}

caddy  | {"level":"debug","ts":1622056649.8915887,"logger":"http.handlers.rewrite","msg":"rewrote request","request":{"remote_addr":"192.168.192.1:34754","proto":"HTTP/2.0","method":"GET","host":"app.localhost","uri":"/attachments/retrieve/274890/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Cookie":["csrftoken=HWrKYeuvbneF6TvtQkwdZl2tHQztRjO7Xyk8dD5HhWVGNDOoWcdwRyQpCeOa2jeM; sessionid=asq6kld8llryhr5fedvp5lqcsz682zzt"],"Upgrade-Insecure-Requests":["1"],"Dnt":["1"],"Sec-Gpc":["1"],"Te":["trailers"],"X-Forwarded-For":["192.168.192.1"],"User-Agent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"X-Forwarded-Proto":["https"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"app.localhost"}},"method":"GET","uri":"/my_dir/211699%2520Cost%2520Seg%2520Report%252005-22-21%252013%253A03.pdf"}

caddy | {"level":"debug","ts":1622056649.891666,"logger":"http.handlers.file_server","msg":"sanitized path join","site_root":"/","request_path":"/my_dir/211699%20Cost%20Seg%20Report%2005-22-21%2013%3A03.pdf","result":"/my_dir/211699%20Cost%20Seg%20Report%2005-22-21%2013%3A03.pdf"}
```

**Comment by francislavoie** [comment]
Hmm, I'm not sure this is a problem with Caddy. I think your app should be updated to not URL encode the path component when setting the `X-Accel-Redirect` header.

**Comment by francislavoie** [comment]
Hmm, @jshcrm could you try this?

```
uri replace {path} {http.reverse_proxy.header.X-Accel-Redirect}
```

This should do a direct string replacement of the path (query will be untouched), while running `url.PathUnescape` on the replacement value.

**Comment by mholt** [comment]
I'm not particularly keen on changing rewrite's behavior. It is pretty well-tested and works _as intended_ as far as I know. (Sure, there may be bugs, but I don't feel comfortable changing the existing behavior that, as far as we know, isn't buggy.) I do think it is the responsibility of the application setting the header to form a properly encoded URI, it's not Caddy's job to fix that.

**Comment by jshcrm** [comment]
I tried the uri replace, not sure if I did it incorrectly but it didn't seem to make a difference. Heres what I tried:

```
@accel header X-Accel-Redirect *
handle_response @accel {
    root * /
    uri replace {path} {http.reverse_proxy.header.X-Accel-Redirect}
    rewrite {path}
    file_server
}
```

Regardless, mholt's answer pointed me in the right direction, it wasn't a caddy issue. I needed to change my backend. I was using django_sendfile with the "nginx" backend before we switched to caddy/docker, switching to the "simple" backend fixed it right away, removing the need for the X-Accel-Redirect header altogether.

**Comment by francislavoie** [comment]
> I tried the uri replace, not sure if I did it incorrectly but it didn't seem to make a difference. Heres what I tried:

I think you should remove `rewrite {path}`, it's redundant. But debug logs should show what the rewrites are doing :thinking: 

> Regardless, mholt's answer pointed me in the right direction, it wasn't a caddy issue. I needed to change my backend. I was using django_sendfile with the "nginx" backend before we switched to caddy/docker, switching to the "simple" backend fixed it right away, removing the need for the X-Accel-Redirect header altogether.

Just so I better understand, what does this `simple` backend do? Are you still using `handle_response`? How do you have it working now?

**Comment by jshcrm** [comment]
Correct, Django will stream the file from disk instead of sending the filepath in the X-Accel-Redirect Header. [Here's the package I'm using for this](https://github.com/johnsensible/django-sendfile), the backend descriptions are in the first section.

**Comment by francislavoie** [comment]
You could try with `X-Sendfile` maybe? Same idea, different header name, I think.

I don't think `simple` is really a fix cause this makes Django handle the file serving. The point of `X-Accel` is to let the server in front handle it, which it might be better suited to do.

> The debug logs showed the same result as rewrite, the url was still encoded after being modified.

Bummer. Looks like like that package is pluggable, so you could make a `caddy` backend which returns the header not URL encoded? https://github.com/johnsensible/django-sendfile/blob/master/sendfile/backends/nginx.py

**Comment by francislavoie** [comment]
Which version of Caddy are you on? There was a regression with `file_server`'s canonicalization redirects in `v2.4.2`. Try on `v2.4.3`.

**Comment by jshcrm** [comment]
That fixed it :) Awesome! Thanks for you help

**Comment by francislavoie** [comment]
Great, so to confirm, `X-Sendfile` is working for you now? Including whitespace in files?

**Comment by jshcrm** [comment]
Yep confirmed, X-Sendfile works even with whitespace in filenames
