### ISSUE TITLE
DEB repo doesn't work for RPi 1B Rev 1

### ISSUE THREAD

**Issue by prochac** [caddyserver/caddy#4183]
Hi, I'm having old scrap called Raspberry Pi B (2012).
I did follow instructions from website:
https://caddyserver.com/docs/install#debian-ubuntu-raspbian
but I'm getting `Illegal instruction` error.

Directly downloaded binary works fine:
```shell
$ wget -O caddy "https://caddyserver.com/api/download?os=linux&arch=arm&arm=6"
```
But I'm losing the comfort of service script and automatic updates.
My current workaround is to install from repo and replace binary.
But it causes error when caddy binary is updated and must be replaced.

```shell
$ pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17+ #1414 Fri Apr 30 13:16:27 BST 2021 armv6l GNU/Linux
```
```shell
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor  : 0
model name : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS : 697.95
Features : half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part : 0xb76
CPU revision : 7

Hardware : BCM2835
Revision : 0003
Serial  : 00000000a4c1deb7
Model   : Raspberry Pi Model B Rev 1
```

**Comment by francislavoie** [comment]
Known issue, we can't fix it. See https://github.com/caddyserver/dist/issues/62

**Comment by cinderblock** [comment]
In case anyone comes by here looking for the easy way to install the ARMv6 version of caddy:

1. Get the latest `.deb` file from releases
   - https://github.com/caddyserver/caddy/releases/download
2. Install it

#### Example

```bash
wget https://github.com/caddyserver/caddy/releases/download/v2.4.5/caddy_2.4.5_linux_armv6.deb
# Tell dpkg about it, will install if a different version is already installed
sudo dpkg -i caddy_2.4.5_linux_armv6.deb
# Only necessary if not yet installed
sudo apt-get install -y caddy
```
