### ISSUE TITLE
caddy2 is an unprecedented huge failure.

### ISSUE THREAD

**Issue by caomingjiang** [caddyserver/caddy#4190]
I don't understand why caddy1 was discarded. Caddy2 is completely in the wrong direction! Isn't the simple configuration its most popular aspect?

**Comment by Mohammed90** [comment]
Please refrain from trolling and being inflammatory. If you have constructive criticism, do share in the proper outlets, otherwise keep the remarks elsewhere on your own channels.

**Comment by francislavoie** [comment]
I'm going to guess that you misunderstood the changes. The Caddyfile still exists, but is now an adapter to JSON, and JSON is the underlying config language for Caddy. The Caddyfile is still there for simple configuration. See the upgrade guide for details: https://caddyserver.com/docs/v2-upgrade

That said, comments like this are _not ok_. It's disrespectful to the effort of all the contributors, and it is not constructive.
