### ISSUE TITLE
Update go dependencies

### ISSUE THREAD

**Issue by vincentchalamon** [caddyserver/caddy#4200]
A Trivy analysis show a security issue on a dependency:
![caddy](https://user-images.githubusercontent.com/407859/121494376-fa09d780-c9d8-11eb-81cb-269cc5ac13eb.png)

Is there any way to update this dependency in the caddy server?

**Comment by francislavoie** [comment]
Duplicate of https://github.com/caddyserver/caddy/issues/4199

Just fetch the latest version of Go then rebuild Caddy.

https://caddyserver.com/docs/build
