### ISSUE TITLE
file_server: race condition in browse

### ISSUE THREAD

**Issue by diamondburned** [caddyserver/caddy#4202]
This line of code inside `modules/caddyhttp/fileserver/browse.go` is causing a race condition:

https://github.com/caddyserver/caddy/blob/05656a60b3b089ce1735a1ebb02539cca9f68fb4/modules/caddyhttp/fileserver/browse.go#L183

The line of code is inside the function `makeBrowseTemplate`, which is called on every request. This means the field is set into a shared object concurrently on every request, which is racy.

With the help of @francislavoie, we found out that this bug was apparently introduced in commit https://github.com/caddyserver/caddy/commit/637fd8f67b7ff6191673ff13e94825a4ec896891.

**Comment by mholt** [comment]
That would be helpful since I'm swamped with another bug fix right now. Thanks for the report, @diamondburned  :+1:

**Comment by princemaple** [comment]
Hi, random user here. I don't code go. After a quick scan through the go/http/request documentation I think `request.context` is where the template reference should be stored at.

In Elixir/Erlang world there is another place that might be appropriate - the process dictionary. (This is VM process, not OS process, think go routine). I don't know if go has it, but `request.context` could still be more appropriate.

**Comment by xdu31** [comment]
Hi @mholt, thanks for the fix, I'm sorry I just saw this, would like to fix if there are other issues.
