### ISSUE TITLE
How to use caddy to terminate ssl on the client side

### ISSUE THREAD

**Issue by vdwees** [caddyserver/caddy#4210]
I have a client that does not support https and a server that only does https. I was thinking I could use caddy running locally to bridge this gap. Something like this:

```caddy
localhost:80

reverse_proxy https://google.com
```
However, all I get is 404, similar to the above:

```<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>
```

Does what I am doing make sense? What could I be doing wrong?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
