### ISSUE TITLE
Add/remove plugins on caddy upgrade?

### ISSUE THREAD

**Issue by excid3** [caddyserver/caddy#4213]
I'm managing a bunch of servers and they're running Caddy v2. The upgrade command works great for upgrading with the packages previously chosen. In the future, it's likely I'll want to add/remove packages from that list over time. 

Would it make sense to add flags to add and remove packages from the caddy build on upgrade?

```bash
caddy upgrade --add-package github.com/caddy-dns/cloudflare
caddy upgrade --remove-package github.com/caddy-dns/cloudflare
```

**Comment by mholt** [comment]
Yeah, this is something I had also thought about: https://github.com/caddyserver/caddy/pull/3972#issuecomment-759782630

> I suppose we could extend this to add and remove plugins too:
> `--add <package>` / `--remove <package>`
> 
> Or maybe that should be a separate subcommand:
> `caddy add-package <package>` / `caddy remove-package <package>`
> 
> Or even just:
> `caddy add <package>` / `caddy remove <package>`

Not a high priority for me to work on personally, but pull requests would certainly be welcomed.

**Comment by calebikhuohon** [comment]
Hi @mholt, I'm interested in taking this up

**Comment by francislavoie** [comment]
@calebikhuohon go for it!

**Comment by mholt** [comment]
Yeah, that'd be great. I'm still not sure which CLI approach is the best -- so just be aware I might change my mind in reviews.

**Comment by musinit** [comment]
@calebikhuohon are you working on it?) I also want to try this out

**Comment by musinit** [comment]
Guys, I am totally new in that project, but I tried to add some **adding-package**, if you tell me that it's absolute wrong I will remove it as quick as possible😄
https://github.com/caddyserver/caddy/pull/4226

**Comment by calebikhuohon** [comment]
> @calebikhuohon are you working on it?) I also want to try this out

Sure :+1: Go for it

**Comment by mholt** [comment]
All done, thanks very much @musinit!

**Comment by excid3** [comment]
Awesome work @musinit 🙏
