### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values '*, *'

### ISSUE THREAD

**Issue by ermiaqasemi** [caddyserver/caddy#4219]
Hi there, 

I am using caddy:2.4.2-alpine docker image and I wanna enable CORS for one of my domains but I get an error from a browser that is said `The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`
    route /graphql {
  
        # CORS headers
        header Access-Control-Allow-Origin "*"
        header Access-Control-Allow-Methods "GET, POST, OPTIONS"
        header Access-Control-Allow-Credentials true

        reverse_proxy http://gateway.default.svc.cluster.local
    }
`

With CURL it works the problem is just in browser

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
