### ISSUE TITLE
Caddyfile adapter wraps localhost into automation policy for public names

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#4220]
This minimal Caddyfile:

```
{
	email foo@bar
}

localhost {
}

example.com {
}
```

yields automation policies in JSON:

```json
[
  {
    "subjects": [
      "example.com",
      "localhost"
    ],
    "issuers": [
      {
        "email": "foo@bar",
        "module": "acme"
      },
      {
        "email": "foo@bar",
        "module": "zerossl"
      }
    ]
  }
]
```

which is clearly wrong, because `localhost` can't get a cert from Let's Encrypt or ZeroSSL (or any publicly-trusted CA).

Already have a fix incoming. Just making this issue for future reference.

(Edit: Looks like we have a test that is actually enforcing this behavior, [global_options_preferred_chains.txt](https://github.com/caddyserver/caddy/blob/2de7e14e1c5fcc8c846b341583597ab65eaf7156/caddytest/integration/caddyfile_adapt/global_options_preferred_chains.txt) - but there's no way that's intentional, right?)

**Comment by francislavoie** [comment]
Yeah - that test is incorrect. 👍
