### ISSUE TITLE
Active health check not working with reverse proxy to unix domain socket

### ISSUE THREAD

**Issue by ctsrc** [caddyserver/caddy#4231]
Hi,

I am running Caddy v2.4.3 on FreeBSD 12.2

I have an entry in my Caddyfile that looks like this (obviously the domain names and the Cloudflare key have been substituted with placeholder values here, but other than that I am showing exactly what I have):

```text
api.example.com {
    reverse_proxy {
        to 10.13.37.7 unix//var/www/com.example.api/example-http-api/run/public.sock
        lb_policy first
	health_uri /status
        health_interval 5s
        health_timeout 450ms
    }

    tls hostmaster@example.com {
        dns cloudflare OwYPs2n3yPpmLwwOGM6ufn4gQwDRmYAl9BaqL0AS
    }
}
```

However, in `/var/log/caddy.log`, I get errors that look like the following:

```
{"level":"info","ts":1625231212.875412,"logger":"http.handlers.reverse_proxy.health_checker.active","msg":"HTTP request failed","host":"localhost","error":"Get \"http://localhost/status\": dial unix localhost: connect: no such file or directory"}
```

Somehow when it tries to perform active health check, it tries to connect to `http://localhost/status`, instead of talking to the Unix domain socket.

Whereas with passive health checks instead of active health checks, I am able to service requests both with the primary destination and with falling back to the Unix domain socket destination when the primary returns an empty response.

```text
api.example.com {
    reverse_proxy {
        to 10.13.37.7 unix//var/www/com.example.api/example-http-api/run/public.sock
        lb_policy first
        fail_duration 30s
    }

    tls hostmaster@example.com {
        dns cloudflare OwYPs2n3yPpmLwwOGM6ufn4gQwDRmYAl9BaqL0AS
    }
}
```

However, I need active health checks because when the primary is not responding then the passive health checks do not trigger.

Am I doing something wrong here? I am not able to tell from the documentation at https://caddyserver.com/docs/caddyfile/directives/reverse_proxy

**Comment by ctsrc** [comment]
As a temporary workaround I came up with the following. But be warned that this workaround is a bit ugly.

```text
http://localhost:8087 {
    request_header Host api.example.com
    reverse_proxy 10.13.37.7
}

http://localhost:8088 {
    request_header Host api.example.com
    reverse_proxy unix//var/www/com.example.api/example-http-api/run/public.sock
}

api.example.com {
    request_header -X-Forwarded-For
    request_header Host localhost

    reverse_proxy {
        to localhost:8087 localhost:8088
        lb_policy first
        health_uri /status
        health_interval 5s
        health_timeout 450ms
        fail_duration 30s
    }

    tls hostmaster@example.com {
        dns cloudflare OwYPs2n3yPpmLwwOGM6ufn4gQwDRmYAl9BaqL0AS
    }
}
```

**Comment by Mohammed90** [comment]
> `{"level":"info","ts":1625231212.875412,"logger":"http.handlers.reverse_proxy.health_checker.active","msg":"HTTP request failed","host":"localhost","error":"Get \"http://localhost/status\": dial unix localhost: connect: no such file or directory"}`
> Somehow when it tries to perform active health check, it tries to connect to http://localhost/status, instead of talking to the Unix domain socket.

Although it says `http:`, we override the Dialer in the `http.Client` to call the Unix socket. What's going wrong here is this line:
https://github.com/caddyserver/caddy/blob/4245ceb67d1a40ce7a691bcf85e143218e5c458c/modules/caddyhttp/reverseproxy/healthchecks.go#L228-L235

We should be appending the `health_uri` to the path of the unix socket rather than override the whole thing, which ends up looking for a nonexisting file/socket.

**Comment by francislavoie** [comment]
Merged! Thanks for the fix @elnoro and thanks @ctsrc for confirming 🚀
