### ISSUE TITLE
Incorrect determination of gRPC protocol

### ISSUE THREAD

**Issue by hmol233** [caddyserver/caddy#4234]
Hi guys,

I have found that Caddy can't determine gRPC protocol correctly in some cases.

In Caddy, gRPC protocol is identified by `Content-Type`:

https://github.com/caddyserver/caddy/blob/e4a22de9d1c4d7aa83126ee13e40b61e7b0e9df0/modules/caddyhttp/matchers.go#L670

According to the [document of gRPC](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests), the value of `Content-Type` header could be `application/grpc` or **`application/grpc+<codec>`**. But the latter one can't be identified by Caddy's `MatchProtocol` matcher.

Thanks for your work, and sorry for my bad english.

**Comment by francislavoie** [comment]
Are you suggesting that we change it to this?

```go
strings.HasPrefix(r.Header.Get("content-type"), "application/grpc")
```
