### ISSUE TITLE
Feature Request: Customize status code of autohttps

### ISSUE THREAD

**Issue by jeremylowery** [caddyserver/caddy#4239]
I'm testing out caddy, and have run into an issue where older IE11 browsers on Windows 7 do not support http.StatusPermanentRedirect 308 redirects and they just white screen when making a http request to caddy. Would it be possible to customize this status code to 301 or some other value using configuration?

I see the line on modules/caddyhttp/autohttps.go:411 StatusCode: WeakString(strconv.Itoa(http.StatusPermanentRedirect)). I might be able to work on a pull request for this if it's something the maintainers are amenable to., though it would be my first shot.

**Comment by francislavoie** [comment]
You can simply add this to your config:

```
http:// {
	redir https://{hostport}{uri} 301
}
```

Since IE11 is very much EOL, I don't think there's any appetite for adding features specifically to support it.
