### ISSUE TITLE
Single hyphen for flags - should be two hyphens -- in help/usage output

### ISSUE THREAD

**Issue by rugk** [caddyserver/caddy#4240]
Consider this command:
```
$ podman run --rm -v $PWD:/test:z caddy caddy help validate 
Loads and provisions the provided config, but does not start running it.
This reveals any errors with the configuration through the loading and
provisioning stages.

usage:
  caddy validate --config <path> [--adapter <name>]

flags:
  -adapter string
    	Name of config adapter
  -config string
    	Input configuration file

Full documentation is available at:
https://caddyserver.com/docs/command-line
```

Or this horrible typo I made:
```
$ podman run --rm --name caddyformat -v $PWD:/test:z caddy caddy fmt -override /test/Caddyfile  
flag provided but not defined: -override
Usage of format:
  -overwrite
    	Overwrite the input file with the results
```

## Problem

In the short summary you are writing `--config` e.g., but in the full flag (usually also called parameter, but that is irrelevant IMHO) list below, you list it as `-config`, i.e. a single hyphen. Even when your software can handle both, it is somewhat inconsistent and confusing IMHO.

## Solution

It is a very common pattern to use one hyphen for single-letter (short parameters) and two for longer arguments,

See e.g.
https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html
[various](https://askubuntu.com/a/813312/606016) [Stackexchange](https://superuser.com/a/372261/522670) [questions](https://serverfault.com/q/387935/350103) (on literally any platform of them :stuck_out_tongue_winking_eye: )
https://en.wikipedia.org/wiki/Command-line_interface#Option_conventions_in_Unix-like_systems

As such, I'd propose to always use `--the-two-hypens` when referring to a flag in the help output.

## System
Fedora Workstation 34
Caddy v2.4.3 h1:Y1FaV2N4WO3rBqxSYA8UZsZTQdN+PwcoOcAiZTM8C0I=

**Comment by francislavoie** [comment]
That "usage of" error message comes from the Go stdlib. We just tell the `flag` package what we want to accept, and it does the rest of the validation/parsing for us.

https://github.com/golang/go/blob/27015152ec769aeed2ab92533772b97c0ef96b11/src/flag/flag.go#L571

https://github.com/golang/go/blob/27015152ec769aeed2ab92533772b97c0ef96b11/src/flag/flag.go#L963

**Comment by rugk** [comment]
Okay, thanks, fine, reported upstream: https://github.com/golang/go/issues/47114

**Comment by rugk** [comment]
Coming [back from the Go project](https://github.com/golang/go/issues/47114#issuecomment-877509021), I see you can actually adjust that.
> If you think caddy should do something different, you can ask them to override `flag.Usage` and not use `flag.PrintDefaults`.

Given [how you write the arguments on your website](https://caddyserver.com/docs/command-line), IMHO you should go with `--` being displayed. Then it is consistent/matches what you describe on the website.

**Comment by rugk** [comment]
Ah, and now here is the actual root cause:
> Caddy has chosen to write out the flags using two hyphens in the prose section but it's using flag.PrintDefaults, which uses one hyphen
> […]
> That is, Caddy is the source of the inconsistency here. Either Caddy should use the `flag` convention of referring to flag names with one hyphen everywhere, or it should not use `flag.PrintDefaults` to print the flag names and instead handle printing them itself using two hyphens.

https://github.com/golang/go/issues/47114#issuecomment-877510417

So IMHO either:
* follow Go's convention and use a single dash `-` everywhere
* or follow the other convention and use `--` (as indicated multiple times, I'd prefer that)

Due to this new discovery, which really shows the issue is on not really in Go, 'd ask you to reopen this issue here please. :slightly_smiling_face:

**Comment by rugk** [comment]
From https://github.com/golang/go/issues/47114#issuecomment-877589052, @francislavoie:

> Perhaps you can point them to https://pkg.go.dev/rsc.io/getopt. It should play well with the flag package.

**Comment by mholt** [comment]
I realize there's an inconsistency between the online docs and the `-h` docs, but frankly, that's something I care next-to-nothing about... in v1 more people were confused by just single-hyphen docs and in v2 I don't want to add code complexity or dependencies to show a second hyphen, especially since _they behave exactly the same_.

**Comment by rugk** [comment]
Could you at least reopen the issue? As it seems, this seems to be fairly trivial to fix (also for contributors, if wanted).

**Comment by francislavoie** [comment]
Like Matt said:

> I don't want to add code complexity or dependencies to show a second hyphen, especially since they behave exactly the same.

We don't consider this to be something we actually want to fix, or merge. Any new code merged to the project means we need to maintain it thereafter, and this isn't worth the time or effort for anyone involved.

**Comment by mholt** [comment]
Yeah, sorry. It's just of so little consequence (none at all, really) and the only known fixes are either to make the docs confusing or to add complexity/dependencies to the code, neither of which are appealing. Thanks for the discussion though.

**Comment by rugk** [comment]
> either to make the docs confusing

The docs currently are confusing… hmm…

Yeah, it is a tradeoff sure, but I still consider that an issue. If so, maybe tag it with "help wanted" if you are seeking better solutions than that third-party package or custom help text output…
