### ISSUE TITLE
proxy load balancing doesn't handle Connection reset by peer.

### ISSUE THREAD

**Issue by fantomfp** [caddyserver/caddy#4249]
Hi,
I'm having an issue with php_fastcgi, but the issue is global to reverse_proxy and php_fastcgi modules.
The issue is between caddy and its upstream backend servers, if there is more than one upstream backend.

Version:
caddy 2.2.1 on Fedora 33 x86_64

Config:
```
nextcloud.domain.tld {
    file_server
    header {
        Strict-Transport-Security "max-age=31536000;"
        X-XSS-Protection "1; mode=block"
        X-Content-Type-Options "nosniff"
        X-Download-Options "noopen"
        X-Permitted-Cross-Domain-Policies "none"
        -server
        -x-powered-by
    }
    root * /media/nfs3

    redir /.well-known/carddav /remote.php/dav 301
    redir /.well-known/caldav /remote.php/dav 301

    php_fastcgi * localhost:9062 localhost:9063 {
        root /var/www/html
        env modHeadersAvailable true
        lb_policy first
    }

    @forbidden {
        path /.htaccess
        path /data/*
        path /config/*
        path /db_structure
        path /.xml
        path /README
        path /3rdparty/*
        path /lib/*
        path /templates/*
        path /occ
        path /console.php
    }
    respond @forbidden 404
}
```
As you can see in the config file, there is 2 backends (localhost:9062 and localhost:9063), it is 2 separate instances of php-fpm. The "localhost" host is not relevant in this case, because I use a TLS tunnel between caddy server and php-fpm servers.

In the load balancing policy, I configured to use everytime the first server in the list, so the first php-fpm server is main, and the second is fallback.

Because it is php-fpm, I didn't configured active or passive health checks, due of lack of http error code.

In my case, when backend server is offline, the tunnel between caddy and the backend server is responding to caddy "Connection reset by peer." The tunnel is reacheable at the address localhost:9062.

Issue:
caddy doen't handle the error, and write in the log:
```
Jul 22 17:43:34 machinename caddy[815]: {"level":"error","ts":1626968614.7494366,"logger":"http.log.error","msg":"EOF","request":{"remote_addr":"XXX.XXX.XXX.XXX:54378","proto":"HTTP/2.0","method":"GET","host":"nextcloud.domain.tld","uri":"/ocs/v2.php/apps/notifications/api/v2/notifications", ... "tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"nextcloud.domain.tld"}},"duration":0.090915151,"status":502,"err_id":"nu3zsqnam","err_trace":"reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:441)"}

```
I can reproduce the error made by the tunnel on the machine running caddy, when php-fpm server come offline:
```
# nc localhost 9062
Ncat: Connection reset by peer.
```

Expected:
caddy handles the Connection reset by peer error and switch on the second upstream backend in the list.

Thank you for your help.

**Comment by fantomfp** [comment]
This issue is not related to a lb_try_duration issue (or a misconfigured timeout issue) because the answer "Connection reset by peer" comes in few milliseconds.

**Comment by francislavoie** [comment]
Retries are not enabled at all unless you specify `lb_try_duration` with a non-zero value. Set it to something like 2s and it should be enough.

Also, please upgrade to Caddy v2.4.3, there are important fixes since the version you're using.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
