### ISSUE TITLE
Caddy 2.43 log is not working?

### ISSUE THREAD

**Issue by uranus829** [caddyserver/caddy#4250]
Hello,My Caddyfile config:
`
:9999 {
        # Set this path to your site's directory.
        root * /usr/share/caddy

        # Enable the static file server.
        file_server browse
       log {
        output file    /usr/share/caddy/access.log
    }
        # Another common task is to set up a reverse proxy:
        # reverse_proxy localhost:8080

        # Or serve a PHP site through php-fpm:
        # php_fastcgi localhost:9000
}
`
But No access.log file is generated in the /usr/share/caddy/ directory.
May I ask what is the reason? Other file access services are normal, that is, no logs are generated.

![image](https://user-images.githubusercontent.com/46716344/126729263-966ac94b-febc-406b-a141-55f901222364.png)

![image](https://user-images.githubusercontent.com/46716344/126729272-d6f1e93d-f387-4f13-92e2-530047c75e73.png)

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
