### ISSUE TITLE
caddy community

### ISSUE THREAD

**Issue by ScrumpyJack** [caddyserver/caddy#4252]
I ❤️ caddy2

While I appreciate that the maintainers would like to keep "Questions" away form this issue tracker, it seems like an uphill struggle as most people just like to use github issues for that sort of thing.

Anyway, for all that to work https://caddy.community needs to be up.

Is the host down?

🦄 ❯ host caddy.community
caddy.community has address 159.89.152.193
caddy.community has IPv6 address 2604:a880:2:d0::9df:b001
🦄 ❯ wget https://caddy.community
--2021-07-23 18:10:40--  https://caddy.community/
Resolving caddy.community... 2604:a880:2:d0::9df:b001, 159.89.152.193
Connecting to caddy.community|2604:a880:2:d0::9df:b001|:443... failed: Operation timed out.
Connecting to caddy.community|159.89.152.193|:443... failed: Operation timed out.

I assume caddy.community is a bulletin board?
Has someone started an IRC channel or some such, "official" or nor?

**Comment by mholt** [comment]
It's a known issue - the DigitalOcean droplet has lost connectivity. https://twitter.com/caddyserver/status/1418575951248732165

**Comment by francislavoie** [comment]
> I hear there's an unofficial Discord for Caddy talk, but I don't have the link handy right now.

https://discord.gg/VenHSzPZR6

The forums are definitely the preferred way to get help though, once it's back up.

Sorry for the inconvenience!
