### ISSUE TITLE
Confused by internal tls

### ISSUE THREAD

**Issue by a10kiloham** [caddyserver/caddy#4253]
Trying to setup a plain fileserver. Hostname is lenovo so I set up as file_server with tls internal. Chrome loads but says the intermediary CA Caddy certificate is insecure. The directions don't say anything else about how to configure. Is there something else I need to be doing to make https://lenovo work in my internal network?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
