### ISSUE TITLE
[question] admin error not use pkg/errors,  caller_key no effect 

### ISSUE THREAD

**Issue by rentiansheng** [caddyserver/caddy#4254]
- 1  admin error not use pkg/errors
https://github.com/caddyserver/caddy/blob/master/admin.go, admin handle logic error, use the golang system error not pkg/errors,  not implement format,  output log not  errorverbose field
- 2  caller_key no effect

zap   use caller_key, must be setting zap.AddCaller(), zap.AddCallerSkip(1) in zap.New function. 
but caddyserver  not found . 

https://github.com/caddyserver/caddy/blob/master/logging.go#L159

**Comment by mholt** [comment]
> 1 admin error not use pkg/errors
https://github.com/caddyserver/caddy/blob/master/admin.go, admin handle logic error, use the golang system error not pkg/errors, not implement format, output log not errorverbose field

What is missing from the error logs? Do you have a specific use case?

> zap use caller_key, must be setting zap.AddCaller(), zap.AddCallerSkip(1) in zap.New function.
but caddyserver not found .

The logs work just fine without this. What problem are you experiencing?

**Comment by rentiansheng** [comment]
- 1 
https://github.com/caddyserver/caddy/blob/master/admin.go#L451.  use fmt.Errorf. log info not errorVerbose


- 2 
![image](https://user-images.githubusercontent.com/3955934/127156548-e7c7c988-3a67-4d5c-84aa-bb56013f0c8c.png)

log not caller,stacktrace_key field

**Comment by mholt** [comment]
@rentiansheng admin.go L451 is a comment:

https://github.com/caddyserver/caddy/blob/c131339c5cda3a541223fde4a714aab55de13b9a/admin.go#L451

> log not caller,stacktrace_key field

I don't understand. You're probably not a native English speaker, so try using computer translation instead...
