### ISSUE TITLE
"auto_https disable_redirects" cause 502 bad gateway

### ISSUE THREAD

**Issue by vibbow** [caddyserver/caddy#4265]
Sample configuration

```
{
  auto_https disable_redirects
  default_sni your-domain.com
}


your-domain.com
{
  tls /etc/ssl/caddy/your-domain.com.crt /etc/ssl/caddy/your-domain.com.key {
    protocols tls1.0 tls1.3
    ciphers TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256  TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_3DES_EDE_CBC_SHA
  }

  header / Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"

  root * /usr/share/caddy
  file_server
}
```

Expected behaviour:

Both HTTP and HTTPS protocol should return default index file.

Actually behaviour:

HTTPS protocol works fine, but HTTP protocol returned 502 bad gateway.

Caddy version:

git tag v2.4.3, only modified `modules/caddytls/values.go` to enabled tls 1.0, 1.1
Compiled with go 1.16.6

**Comment by francislavoie** [comment]
`disable_redirects` also prevents Caddy from serving over HTTP. If you need HTTP to also serve the same content, make a site block that does it with `http://your-domain.com`

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by francislavoie** [comment]
Caddy only enables HTTP to serve redirects (and to handle ACME HTTP challenges). Caddy is an HTTPS server by default.

**Comment by vibbow** [comment]
@francislavoie @mholt 
I still think it's a bug.

If user only want to serve HTTP or HTTPS only, they should specific in the site address.

If user didn't specific protocol and give an valid config, caddy should server on both HTTP and HTTPS 
`auto_https disable_redirects` should only do as it says, stop auto redirects from HTTP to HTTPS.

**Comment by francislavoie** [comment]
No, this is absolutely the intended behaviour of Caddy.

Caddy will not assume the user wants HTTP, because its goal is to move the web to be HTTPS by default. If you want HTTP, you need to be explicit about it.

**Comment by vibbow** [comment]
Sure thing.

Maybe the option value or the user manual can be improve a bit to better explain the behaviour:

disable_redirects => no_http
or 
"disable only HTTP-to-HTTPS redirects (disable_redirects)" => "no serve HTTP by default."

**Comment by francislavoie** [comment]
This is really just a misunderstanding on your part. Caddy doesn't ever serve content over HTTP with Automatic HTTPS enabled (unless explicitly asked to) so the `disable_redirects` feature is accurate. It simply prevents HTTP->HTTPS redirects from being provisioned. That's it. If there's no redirects, then there's no HTTP server (except for capturing ACME HTTP challenge requests, like I mentioned).

**Comment by vibbow** [comment]
Oh, I see. This explains.

Thanks.
