### ISSUE TITLE
Invalid response at ACME challenge, the URL points to SWAG

### ISSUE THREAD

**Issue by raphaellueckl** [caddyserver/caddy#4269]
Command that I run: `sudo caddy reverse-proxy --from ripped.link --to 0.0.0.0:9000`

Result: The URL it uses for the challenge is returning a SWAG-Interface or something. https://ripped.link/.well-known/acme-challenge/NL4Yw3d-6W09RJK0FZzbDlYyfhkGCRKCc2X45UUWkzE

Problem: I want to use caddy as reverse proxy with https, but the certificate-issuance seems broken.

Log:

```2021/08/06 05:06:33.512 INFO    tls.issuance.acme.acme_client   trying to solve challenge       {"identifier": "ripped.link", "challenge_type": "http-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2021/08/06 05:06:34.960 ERROR   tls.issuance.acme.acme_client   challenge failed        {"identifier": "ripped.link", "challenge_type": "http-01", "status_code": 403, "problem_type": "urn:ietf:params:acme:error:unauthorized", "error": "Invalid response from https://ripped.link/.well-known/acme-challenge/NL4Yw3d-6W09RJK0FZzbDlYyfhkGCRKCc2X45UUWkzE [80.89.217.226]: \"<html>\\n    <head>\\n        <title>Welcome to your SWAG instance</title>\\n        <style>\\n        body{\\n            font-family: He\""}
2021/08/06 05:06:34.960 ERROR   tls.issuance.acme.acme_client   validating authorization        {"identifier": "ripped.link", "error": "authorization failed: HTTP 403 urn:ietf:params:acme:error:unauthorized - Invalid response from https://ripped.link/.well-known/acme-challenge/NL4Yw3d-6W09RJK0FZzbDlYyfhkGCRKCc2X45UUWkzE [80.89.217.226]: \"<html>\\n    <head>\\n        <title>Welcome to your SWAG instance</title>\\n        <style>\\n        body{\\n            font-family: He\"", "order": "https://acme-v02.api.letsencrypt.org/acme/order/130671497/14867960250", "attempt": 1, "max_attempts": 3}
2021/08/06 05:06:36.415 INFO    tls.issuance.acme.acme_client   trying to solve challenge       {"identifier": "ripped.link", "challenge_type": "tls-alpn-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2021/08/06 05:06:37.460 ERROR   tls.issuance.acme.acme_client   challenge failed        {"identifier": "ripped.link", "challenge_type": "tls-alpn-01", "status_code": 403, "problem_type": "urn:ietf:params:acme:error:unauthorized", "error": "Cannot negotiate ALPN protocol \"acme-tls/1\" for tls-alpn-01 challenge"}
2021/08/06 05:06:37.460 ERROR   tls.issuance.acme.acme_client   validating authorization        {"identifier": "ripped.link", "error": "authorization failed: HTTP 403 urn:ietf:params:acme:error:unauthorized - Cannot negotiate ALPN protocol \"acme-tls/1\" for tls-alpn-01 challenge", "order": "https://acme-v02.api.letsencrypt.org/acme/order/130671497/14867967370", "attempt": 2, "max_attempts": 3}
2021/08/06 05:06:39.141 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "ripped.link", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "[ripped.link] solving challenges: ripped.link: no solvers available for remaining challenges (configured=[tls-alpn-01 http-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/130671497/14867972870) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
```

**Comment by mholt** [comment]
I'm pretty sure this isn't a bug in Caddy, this looks like DNS pointing to the wrong address or something.

Thanks for your question, and we're glad that you're using Caddy! I'm pretty sure this isn't a bug in Caddy, this looks like DNS pointing to the wrong address or something.

Since this issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum at caddy.community](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding. If it turns out to be a bug, we can reopen this.

**Comment by raphaellueckl** [comment]
@mholt 

Thanks for answering. :)

I already searched for help here: https://community.letsencrypt.org/t/misleading-error-dns-problem-nxdomain-looking-up-a/155791/24

My server is definitely reachable, but the problem is, that authentication is failing. Are you really sure that this is not a bug within the application? I mean, I can go the extra route around the forum but not sure if I would just waste the time of the guys over there. Caddy should run without user-configured authentication I guess, at least for what I am doing with this reverse proxy command.

**Comment by francislavoie** [comment]
Yes, we're sure. An error like that means that Let's Encrypt is not reaching Caddy when making the ACME challenge verification request, and is instead reaching some different server. Make sure public DNS for your domain is properly configured such that points to your server running Caddy, and that you have properly forwarded/opened ports 80 and 443 to reach the server you're running Caddy on. Make sure there's no CDN in between intercepting requests either.

**Comment by raphaellueckl** [comment]
You guys were right, thanks for the heads up!

**Comment by gsouf** [comment]
@francislavoie does that mean that if I disable the CDN for the initial setup and I re-enable it once it's setup then it's not able to renew the certificate when the CDN is re-enabled?

**Comment by mholt** [comment]
@gsouf If the CDN is terminating TLS or not passing HTTP requests through exactly as it received them, then yes it will block certificate renewals unless you instead configure the DNS challenge.
