### ISSUE TITLE
Support for Hashicorp Consul as source of reverse proxy targets

### ISSUE THREAD

**Issue by cyr** [caddyserver/caddy#4272]
Consul is a service discovery service that, by default, will point out currently active services and endpoints. With support for tagging, this would be an excellent way to automate setting up reverse proxy entries, simply by looking at what the catalog says should be up.

**Comment by francislavoie** [comment]
This is somewhat supported via SRV with an address like `srv+http://internal.service.consul`

Could you be more specific about what this feature would look like for you if not that?

**Comment by cyr** [comment]
Sure!

In Consul you have a catalog of services available. Each service has its endpoint (usually the IP of the node it is on, and a port - but this can be different too). I am assuming you know this already, but just for context.

What I would like to be able to do is just point out Consul as a source of targets, and create a reverse proxy (with a config for how to actually present the host/domain-name) for each service, using the endpoints available as possible targets. Since Consul can change states at any time, this would require polling to ensure that Caddy is using the current state of Consuls services.

The main advantage of this, compared to using Consuls DNS-entries directly (which would work fine!), is that you won't have to manually add them per service. They would all be added dynamically.

An example config could look like this:

*.my.domain.com {
  consul consul.service.consul:8500 {
    filter_by_tag proxy_me active
    name {service_name}.my.domain.com
  }
}

In the above example, the service "my_app.service.consul" pointing to 10.0.1.1:80 would be made available at my_app.my.domain.com in caddy!

Obviously there would be other properties needed too, ACL tokens and such, but to capture the main idea, I hope this is helpful.

**Comment by francislavoie** [comment]
Okay - in that case that sounds like a better candidate for a plugin than something Caddy needs to support in its standard distribution.

A request handler could be implemented that does a query against Consul according to those rules you configured, then set a placeholder that could be used as the upstream address for `reverse_proxy`.

**Comment by mholt** [comment]
This would be cool, and I agree, best suited as a plugin. Anyone is welcome to write one.

**Comment by marco-m** [comment]
See also: https://github.com/Inpher/caddy-consul
