### ISSUE TITLE
Not a supported redir code type or not valid integer - breaking change from 2.3 to >=2.4

### ISSUE THREAD

**Issue by msencenb** [caddyserver/caddy#4277]
My caddyfile, which is used as a reverse proxy in front of my heroku app (I host customer websites and use Caddy to solve the Heroku/Let's Encrypt 100 domain limit):

```
https:// {
    log {
        output file /var/log/caddy/access.log
    }

    # A custom matcher to pick out any custom domains to redirect naked to www
    @customhost {
        host not_starts_with www.
        host not *wrestlingiq*
    }

    redir @customhost to https://www.{host}{uri}

    reverse_proxy https://production-wrestlingiq.herokuapp.com {
      header_up Host {http.reverse_proxy.upstream.hostport}
      header_up X-Real-IP {http.reverse-proxy.upstream.address}
      header_up X-Forwarded-Port {http.request.port}
      header_up X-Forwarded-Host {http.request.host}
    }

    tls matt@wrestlingiq.com {
      on_demand
    }
}
```

On Caddy 2.3.0, this works and loads correctly. On Caddy 2.4.0 and higher, it errors out with the following:

```
'redir': Caddyfile:12 - Error during parsing: Not a supported redir code type or not valid integer: 'https://www.{http.request.host}{http.request.uri}
```

I did notice the redirects had some [changes in the release notes](https://github.com/caddyserver/caddy/releases); however, they all seemed to be related to the file system. Looking at the [redir docs](https://caddyserver.com/docs/caddyfile/directives/redir), it sure looks like the way I'm doing it is no longer supported. 

I'm not sure if this should be considered a bug or if this should just be a breaking change. If it's the latter, I'd love to know how to handle my use case now that redir has changed to expect an integer, rather than potentially passing in a string. 

I did my best to search for a changelog or upgrade documentation for 2.4, but wasn't able to find any (and it's entirely possible I'm simply missing where to look for that). Apologies if this change is documented somewhere already!

Thanks for making Caddy, I've been loving working with it!

**Comment by mholt** [comment]
@msencenb 

> `redir @customhost to https://www.{host}{uri}`

You have an extra `to` token in there. Remove that.

**Comment by msencenb** [comment]
🤦 Sorry about that Matt. Thanks for the quick answer to my silly question!

**Comment by francislavoie** [comment]
This matcher doesn't seem right either:

```
    @customhost {
        host not_starts_with www.
        host not *wrestlingiq*
    }
```

You probably wanted something more like:

```
@customhost not host www.* *wrestlingiq*
```

But FYI, the `host` matcher does not expand `*` to more than one label, so this probably won't have the effect you intended. You'd probably need to use `header_regexp Host` instead:

```
@customhost not header_regexp Host (www\..*|.*wrestlingiq.*)
```

https://regex101.com/r/X7gaOU/2

**Comment by msencenb** [comment]
Thank you @francislavoie, I appreciate it.

I swapped over to the proper custom host matcher you mentioned and swapped in a new Caddy server running 2.4.3  to production this evening and it's running smoothly 🎉
