### ISSUE TITLE
Error during parsing: Wrong argument count or unexpected line ending after 'root'

### ISSUE THREAD

**Issue by kokizzu** [caddyserver/caddy#4281]
what's the proper configuration for new root? 
I've tried without `*` also has the same error
```
xxapi.xx.com, http://xxapi.xx.com {
        root * /home/xx/site/public
        proxy / 127.0.0.1:9090 {
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-For {remote}
                header_upstream X-Forwarded-Proto {scheme}
        }
}
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by kokizzu** [comment]
nevermind, got it '___')

```
xxapi.xx.com 

root * /home/xx/site/public
file_server
reverse_proxy 127.0.0.1:9090

```
