### ISSUE TITLE
Is there a release that contains symbol tables?

### ISSUE THREAD

**Issue by m1ch43l-p** [caddyserver/caddy#4292]
Hi,
not sure if this is the correct place for my question. (Please advise)
We are trying to monitor Caddy with Dynatrace. This requires Symbol tables in order to deep inspect the server. 
Using `nm` it seems that caddy binary does not contain these. 
Is there a release version, that does contain the symbol table?

Thank you
Michael

**Comment by francislavoie** [comment]
We build with the ldflags `-s -w` which strips them (the flags are documented here https://pkg.go.dev/cmd/link):

https://github.com/caddyserver/caddy/blob/9e333c39da785075e14d2a75887439f1887356d5/.goreleaser.yml#L62-L63

If you want to use `xcaddy` to make a build of Caddy, you can build `xcaddy` without those flags by changing this line:

https://github.com/caddyserver/xcaddy/blob/8c5d3f1cf635d27e9c1c6f9e62c2937dad8e34f4/builder.go#L115

**Comment by m1ch43l-p** [comment]
Thank you, that is very helpful especially because of the provided links!!!
