### ISSUE TITLE
JSON files are not found by `file_server`

### ISSUE THREAD

**Issue by PhilippMolitor** [caddyserver/caddy#4304]
My configuration:

```Caddyfile
myhost.com {
 handle_path /build/* {
    uri strip_prefix /build

    root * /srv/web_build
    file_server /* browse {
      root /srv/web_build
    }
  }
}
```

Caddy shows all files correctly everything is served correctly, only files ending in `.json` result in a 404.
`/build/build.html` works
`/build/build.json` (same file, copied) does not work

I did not find any documentation about this, nor any settings that might mitigate this behavior.

Seems like `strip_prefix`is stripping too much here...

**Comment by francislavoie** [comment]
```
 handle_path /build/* {
    uri strip_prefix /build
```

This is stripping the path twice, so `/build/build.json` becomes `.json` :scream: 

Just remove `uri strip_prefix`. The `handle_path` directive has built-in prefix stripping.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
