### ISSUE TITLE
Include reverse_procy upstream monitoring in Prometheus monitoring

### ISSUE THREAD

**Issue by rugk** [caddyserver/caddy#4309]
I know [there is a special API to see what upstreams are available](https://caddyserver.com/docs/api#get-reverse-proxyupstreams).

And I know and have setup [monitoring of caddy](https://caddyserver.com/docs/metrics).
Now I expected to also see/get the upstream data from Caddy into Prometheus (and from there in Grafana).

However, I see "only" these metrics are exposed:
![image|336x435](https://caddy-forum-uploads.s3.dualstack.us-east-1.amazonaws.com/original/2X/d/d77c4468a42caa432b4ca98451ce49cc0a775449.png)

So I'd like a way to get that data too in Prometheus.
As we/you can see, it is obviously available.

Potentially related: https://github.com/caddyserver/caddy/issues/4016

---

 More or less cross-posted [from the forum](https://caddy.community/t/how-to-monitor-whether-upstreams-are-active-with-prometheus/13348?u=rugk), where it was confirmed this feature is not available yet.

**Comment by farhan-ct** [comment]
@rugk 

I see from your posted photo here, there are various **caddy_http...** metrics. 

I am using Caddy v2.6.2 and I have setup metrics like below in Caddyfile

```
:2020 {
        metrics
}
```
and when I used curl in localhost to get the metrics,

`curl -s http://localhost:2020/metrics | grep caddy
`

![image](https://user-images.githubusercontent.com/90837918/207862425-7735a23c-5d09-478e-9968-9b11f420e6d0.png)

These are all I can see.

Could you please guide me on how to get the other ones?

Thank you!

**Comment by rugk** [comment]
I have no idea, I have not setup anything special.
