### ISSUE TITLE
Where is the internal pki root cert (for localhost) stored?

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/caddy#4312]
My buddy is using caddy for local certs and I see this when Caddy starts up:

```txt
root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
```

And Brave / Chrome can visit localhost on https, but `node` (on the same dev system) gets confused and issues certificate warnings rather than connecting.

There is a `NODE_EXTRA_CA_CERTS` ENV to define a path to additional certs... but I'm not sure where to tell it to point as I can't find any documentation for what "storage" refers to.

I'm deving on macOS.

**Comment by coolaj86** [comment]
I think I've found it:

```txt
~/Library/Application\ Support/Caddy/pki/authorities/local/
```

I guess the decision is made, but I'd suggest that this should have gone in `~/.config/caddy` or `~/.local/opt/caddy` or `~/.local/share/caddy` since this is a Unix CLI program, not a macOS graphical interface application.

Still interested to get a canonical listing for the other OSes and maybe figure out where this should go in the documentation (I couldn't find it).

**Comment by mholt** [comment]
Hey AJ, these locations are documented here: https://caddyserver.com/docs/conventions#data-directory

Ultimately though, TLS assets are stored in your configured storage device, which is not necessarily the file system (but is by default).

**Comment by coolaj86** [comment]
Thanks Matt.

> TLS assets are stored in your configured storage device, which is not necessarily the file system

Well said.
