### ISSUE TITLE
How to automate ssl with ingress?

### ISSUE THREAD

**Issue by ibalaji777** [caddyserver/caddy#4325]
I love caddy server and thanks to wholeteam 
I want to automate ssl who all are pointing My A record in their DNS,they should get ssl automatically instead of each time adding into configuration file.is this possible? I can't see related ingress documents.

**Comment by Mohammed90** [comment]
You're looking for the [On-Demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls) feature. 

This issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

**Comment by ibalaji777** [comment]
> You're looking for the [On-Demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls) feature.
> 
> This issue tracker is reserved for actionable development items, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!

Thank you so much for your guidance, where can I get caddy ingress docs?

**Comment by mholt** [comment]
What precisely do you mean by "ingress"?

Please ask your questions on our forum instead, so we can better help you: https://caddy.community

**Comment by ibalaji777** [comment]
> What precisely do you mean by "ingress"?
> 
> Please ask your questions on our forum instead, so we can better help you: https://caddy.community

@mhoolt i would like to deploy with kubernet ingress ,i loved caddy so much ,i tried caddy server but i need related docs caddy on demand tls in  kubernet ingress

**Comment by mholt** [comment]
You might be interested in tracking (or contributing to) https://github.com/caddyserver/ingress.

**Comment by ibalaji777** [comment]
@mholt Thank You so much

**Comment by ibalaji777** [comment]
@mholt ,could be use on demand tls in caddy ingress?
