### ISSUE TITLE
[Questions]: Why modules is not used sync.Map?

### ISSUE THREAD

**Issue by beihai0xff** [caddyserver/caddy#4326]
Hello, I am a new guy who is reading the caddy2 source code. 

My question is `modules` is a map and it uses a global readers–writer lock to ensure concurrency safety: 
```go
var (
	modules   = make(map[string]ModuleInfo)
	modulesMu sync.RWMutex
)
```
So Why not used sync.Map to make the implementation of the `modules` easier, like this:
```go
var modules = sync.Map{}
```
Is it a better solution?

**Comment by mholt** [comment]
Fair question. I chose a regular map because of what [the godoc for sync.Map](https://pkg.go.dev/sync#Map) says:

> The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.
> 
> The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

**Comment by beihai0xff** [comment]
> Fair question. I chose a regular map because of what [the godoc for sync.Map](https://pkg.go.dev/sync#Map) says:
> 
> > The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.
> > 
> > The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.
> 
> (tl;dr the `modules` map is not a high-contention variable)

Thanks!
