### ISSUE TITLE
Recieving binary data on some endpoint

### ISSUE THREAD

**Issue by prosperoking** [caddyserver/caddy#4327]
One of my endpoints started responding with binary data after update to v2.4.4. Don't really know what the issue may be worked fine on version v2.4.3

**Comment by Mohammed90** [comment]
You're running into #4314. The fix is already included in HEAD. Either build from master with xcaddy or rollback to 2.4.3 until the hotfix is released in 2.4.5.

**Comment by prosperoking** [comment]
okay, thanks
