### ISSUE TITLE
Case-sensitive issue in header_down of reverse proxy

### ISSUE THREAD

**Issue by nnnlog** [caddyserver/caddy#4330]
Three or four parameters of `header_down` use Regex, and one does simply overwriting.
Caddy did not simply make a case-sensitive distinction of the header key value when it overwrites it, but I experienced a case-sensitive distinction of the header key value when I used Regex.
I think it is not intended.

## Reproduction of issue.
```
example.com {
        reverse_proxy {
                to http://127.0.0.1:8000
                header_down Location (http://)(.*) https://$2
        }
}
```
The above setting replaces the `Location` header's value with https if the value starts with http. It worked only when it was a `Location`, not `location`.

```
example.com {
        reverse_proxy {
                to http://127.0.0.1:8000
                header_down Location https://example.com
        }
}
```
In comparison, the task of simply changing to `https://example.com` worked when the header was named `location`.

## Version
v2.4.5

**Comment by francislavoie** [comment]
Ah, yeah I see the problem. We're using a `map[string][]Replacement` for the replacements, where `string` is the header field name in the case that was configured. I think we need to call `http.CanonicalHeaderKey()` on `fieldName` in the code here, and/or probably use `hdr.Get()` and `hdr.Set()` instead or directly accessing the header map:

https://github.com/caddyserver/caddy/blob/46ab93be51754ac16bd7c59443e90481acf83022/modules/caddyhttp/headers/headers.go#L214-L248

**Comment by Khairil82** [comment]
Selamat

**Comment by mholt** [comment]
Thanks for the report! And thanks Francis for investigating.
