### ISSUE TITLE
file_server directive does not work for specific domain(s?)

### ISSUE THREAD

**Issue by Pepich** [caddyserver/caddy#4334]
Installed software and versions are at the bottom (If you think anything beyond caddy matters for this let me know then I will add the corresponding info).
Caddyfile is attached (renamed to Caddyfile.txt so that github will accept the file upload).
I omitted request log files for now as there's nothing useful in there (as far as I can tell), I can provide you with some example request logs if you want me to.

Using the given Caddyfile, I am unable to access any documents on the domain monkatos.org, as well as the subdomain.monkatos.org. Caddy will return the index.html upon requesting the website root, however any other requests returns an HTTP 200 OK with empty response (0 Bytes). This includes specifically requesting monkatos.org/index.html
The issue does not occur with any of the other domains mentioned in the Caddyfile, they behave as expected.

Example of the server responses:
![grafik](https://user-images.githubusercontent.com/12677178/132230706-b988b541-d892-4087-8fde-84b2ec8c5fed.png)

I can provide the files in the given directory, but they should be accessible through any of the domains that do work as well.
File permissions are as following:

```bash
root@server /var/www/monkatos.org # ll
total 24
drwxr-xr-x 1 root root    56 Sep  5 22:44 ./
drwxr-xr-x 1 root root   154 Sep  5 23:13 ../
drwxr-xr-x 1 root root     0 Sep  5 22:42 folder/
-rw-r--r-- 1 root root   407 Sep  5 22:16 index.html
-rw-r--r-- 1 root root 16869 Sep  5 22:16 monkatos.gif
root@server /var/www/monkatos.org # 
```

`folder` is an empty folder to test the `browse` argument, this also breaks when accessed through the monkatos.org domain (returns 200OK empty as well)

I tested this with different browsers (Firefox and Safari, as well as Safari on iOS), as well as on multiple devices (2 computers, 1 phone), the results are consistent between all of them.

I tried reordering the entries in the Caddyfile (putting monkatos on top/bottom), as well as any subset of the domains (e.g. Caddyfile with only downloads.pepich.de and monkatos.org, or with downloads+monkatos+fatjar, ...) - all of them produce the same result.

The issue seems to be specific to the domain, as they're all configured to access the exact same files.

The issue also occurs with https enabled, I disabled https and cloudflare proxying in the process of narrowing down the source of the issue. I have also tested the issue with both IPv4 and IPv6 connections and it persists.

In terms of reproduction steps, this is a bit difficult as the issue appears to only happen on a specific domain, if you want to reproduce the issue you can get in contact with me and I can set up a subdomain pointed to an address of your choice for testing purposes, and provide a tarball of the specific directory preserving file owner and permissions. The domains listed in the Caddyfile are configured to serve as specified.

[Caddyfile.txt](https://github.com/caddyserver/caddy/files/7116516/Caddyfile.txt)

Installed software:
Initially I had installed Caddy v2.4.5, then downgraded to `Caddy v2.4.4 h1:QBsN1jXEsCqRpKPBb8ebVnBNgPxwL50HINWWTuZ7evU=` - the issue occurs in both versions with no apparent difference in response or logs.

**Comment by francislavoie** [comment]
The issue is with your site address in your Caddyfile:

```
http://monkatos.org/ {
	...
}

http://subdomain.monkatos.org/ {
	...
}

http://downloads.pepich.de {
	...
}

http://fatjar.net {
	...
}
```

Notice how the ones not working have a `/` at the end.

When using a trailing slash, this is telling Caddy to use a path matcher in addition to the host matcher for the hostname. Path matching is exact in Caddy v2, so `/` only matches requests to _exactly_ `/` and nothing else. You _could_ use `/*` to match all requests, but best to just remove the `/` altogether.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
