### ISSUE TITLE
Compression breaks file_server browse template using httpInclude

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#4352]
I have modified the default file_server browse template to integrate it with a website, by using `httpInclude` to load blocks of HTML containing the header, footer and theme.  These files are hosted on the same Caddy instance, and it works well provided that compression is not enabled.  When compression is enabled, the file_server browser becomes garbage: it appears that raw compressed data is included in the HTML served to the client.

Here is my Caddyfile workaround:
```
@not_integ {
        # FIXME: workaround for compression breaking httpInclude in templates
        not path /integ/*
}
encode @not_integ zstd gzip
```

**Comment by bones-was-here** [comment]
Caddy version is 2.4.5 from the official package for Debian.

**Comment by bones-was-here** [comment]
The included paths are all relative, eg `{{ httpInclude "/integ/nav.html" }}` so maybe Caddy could assume the file is on the same host and skip compression in this case.

**Comment by francislavoie** [comment]
Interesting. Should be an easy fix, the internal HTTP request should set the `Accept-Encoding: identity` header to tell Caddy not to encode it.

https://github.com/caddyserver/caddy/blob/5fda9610f907482497a7b32abb2ab2f85a4e6906/modules/caddyhttp/templates/tplcontext.go#L162

**Comment by u5surf** [comment]
@francislavoie Hi, Can I work this issue?
It seems quite easy following the patch,
I’m not sure that would be necessary anywhere else.
```
diff --git a/modules/caddyhttp/templates/tplcontext.go b/modules/caddyhttp/templates/tplcontext.go
index 71886c9a..570967a7 100644
--- a/modules/caddyhttp/templates/tplcontext.go
+++ b/modules/caddyhttp/templates/tplcontext.go
@@ -160,6 +160,7 @@ func (c TemplateContext) funcHTTPInclude(uri string) (string, error) {
        }
        virtReq.Host = c.Req.Host
        virtReq.Header = c.Req.Header.Clone()
+       virtReq.Header.Add("Accept-Encoding", "identity")
        virtReq.Trailer = c.Req.Trailer.Clone()
        virtReq.Header.Set(recursionPreventionHeader, strconv.Itoa(recursionCount))

```

**Comment by francislavoie** [comment]
@u5surf yes, go ahead! Please also add a test to cover this if it's not too difficult.

**Comment by u5surf** [comment]
@francislavoie
 I wrote a unit test of the func `funcHTTPInclude`  using handler structure with `http.Handle` interface, but I feel it's different from covering this phenomenon.
Is there any generic tests or end to end tests about `templates` ?

**Comment by francislavoie** [comment]
Best to discuss this in a pull request! Go ahead and open one with your proposed changes!
