### ISSUE TITLE
file_server browse lists size of symlink instead of size of linked file

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#4353]
On our build server we have "-latest" symlinks that always point to the most recent builds (whose filenames include date stamps).  Users downloading builds want to know the size of the file they will download when they click, not the size of the symlink.  Some users have assumed the builds were broken because the symlink size is tiny.  

Previously we were using Apache, which shows the size of the linked file that will be downloaded.

Caddy version is 2.4.5 from the official package for Debian.

**Comment by francislavoie** [comment]
That should also be a pretty easy fix, if `isSymlink(f)` is true, then it can use `os.Stat` to get the real size of the file.

https://github.com/caddyserver/caddy/blob/5fda9610f907482497a7b32abb2ab2f85a4e6906/modules/caddyhttp/fileserver/browsetplcontext.go#L57

**Comment by HayatoShiba** [comment]
Hi, Excuse me, can I work on this?
I have never contributed to oss and I would like to fix this one!

**Comment by mholt** [comment]
Sure, go for it! We have [instructions in our contributing guide](https://github.com/caddyserver/caddy/blob/master/.github/CONTRIBUTING.md#how-to-make-a-pull-request-to-caddy) for how to make a pull request. It may then go through a few iterations of reviews. Good luck!

**Comment by HayatoShiba** [comment]
Thank you very much for your quick response!

**Comment by bones-was-here** [comment]
I see the correct size of the linked file, also 2.7.5 on debian.  Is the linked file inside the web root?

**Comment by Roan-V** [comment]
No, does that matter?

Root is set to a "files" folder
Symlinks to files somewhere else on the disk are put inside that folder
