### ISSUE TITLE
Linode DNS Provider using libdns

### ISSUE THREAD

**Issue by ocomsoft** [caddyserver/caddy#4355]
I am not sure where/how to submit this but I have implemented a DNS provider for Caddy 2 using libdns 

I am more than happy to help others out and add it to the "official" list. If there is some other way to submit these please let me know. 

https://github.com/ocomsoft/caddy2_linode

To be honest I pretty much took the namecheap repo and made it work. I can confirm it has worked successfully for me with Linode.

Have fun!

**Comment by mholt** [comment]
Hey @ocomsoft , thanks for sharing.

For the record, here are the instructions for implementing a new libdns provider: https://github.com/libdns/libdns/wiki/Implementing-providers

Basically, you'll want to open a PR to have this repo https://github.com/tosie/libdns-linode reviewed at https://github.com/libdns/libdns. After the review is finished, the PR will be closed and you'll push your code to https://github.com/libdns/linode (which will be created).

Then your Caddy module will be pushed to https://github.com/caddy-dns/linode.

You can then register it on the Caddy website by logging in and claiming the package at `github.com/caddy-dns/linode`.

And there you have it!

Will close this, but feel free to ask any more questions if you have them.
