### ISSUE TITLE
Reverse proxy debug log to error log

### ISSUE THREAD

**Issue by jjiang-stripe** [caddyserver/caddy#4360]
Hello!

While trying to debug some errors, I noticed that there's a log line in the reverse proxy that logs an error at the debug level: https://github.com/caddyserver/caddy/blob/f70a7578faa1ab9169bc05a121911bf33d7d3da3/modules/caddyhttp/reverseproxy/reverseproxy.go#L579-L584
It's not a huge deal, but it did take me some time to find because we don't have debug logs turned on by default. Is that log level intentional? I'm happy to submit a PR to update it an error level log, but figured I'd ask first :)

**Comment by mholt** [comment]
Oops! Will fix that in a moment. Thanks for pointing that out.

**Comment by francislavoie** [comment]
Honestly, I think this was `debug` on purpose. It can get _very_ noisy very fast. Also, the error may not necessarily actually be an error (`context.Canceled` for example). The error may also trigger the `lb_try_duration` logic, so it may not be an actual problem.

I think this should stay a debug log, _actual_ errors will bubble up to the HTTP handler chain and get logged there anyways.

**Comment by mholt** [comment]
That's a good point... @jjiang-stripe can you clarify how these specific logs helped you troubleshoot a problem?

**Comment by jjiang-stripe** [comment]
Ah yep that makes sense! I was actually debugging a `context.Canceled` (requests were timing out but we had 4-5 different proxies in the request path so it helped me figure out that the upstream proxy was setting a timeout on the request). On further thought, I think you're right that these errors shouldn't be logged though since the error would likely be something client-related (like `context.Canceled`) rather than Caddy.

**Comment by francislavoie** [comment]
@mholt you can close this once you've reverted it
