### ISSUE TITLE
Windows installer EXE doesn't run

### ISSUE THREAD

**Issue by JustinWebDev** [caddyserver/caddy#4362]
https://caddyserver.com/download
select the default "Windows amd64"
Download - Firefox says the file is 11MB
Save the file - it is 33MB on disk
try to launch the file any way - nothing happens

**Comment by mholt** [comment]
Caddy is a command line application, you have to use the command prompt to run it or specify arguments from the Windows properties dialog when running it. Please refer to https://caddyserver.com/docs/getting-started
