### ISSUE TITLE
Caddy one liner file-server does not work $ caddy file-server

### ISSUE THREAD

**Issue by AddictArts** [caddyserver/caddy#4367]
The main web page mentions a quick file server.

Running
```
% caddy file-server
```
The localhost web page is empty.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
