### ISSUE TITLE
How is Caddy EXE updated?

### ISSUE THREAD

**Issue by JustinWebDev** [caddyserver/caddy#4368]
There is no version info on the download page, no release notes that I can find.  How do I know when a new build is available so I know to download it?  Does Caddy update itself?

**Comment by francislavoie** [comment]
The best way to keep track of releases is to watch the repo. Click the "Watch" button at the top of the page, and choose the option to get notified on new releases. The releases tab will include the release notes.

Caddy doesn't update automatically. You may run the `caddy upgrade` command to fetch a new version of the executable. https://caddyserver.com/docs/command-line#caddy-upgrade
