### ISSUE TITLE
all: continuous benchmarking for CaddyServer

### ISSUE THREAD

**Issue by odeke-em** [caddyserver/caddy#4370]
Howdy CaddyServer maintainers. Thank you very much for all your thankless and awesome contributions and for making this critical project.

At Orijtech Inc, our mission is to bring high performance engineering to the doorstep of everybody. To that effect we've made a continuous benchmarking product "Bencher" https://bencher.orijtech.com/ which is accessible on the GitHub Marketplace in 2-clicks per https://github.com/marketplace/gobencher

With Bencher you won't have to sweat with the cumbersome ergonomics of setting up quiet machines, having to wait and to run benchmarks before and after the change, saving the results, then comparing and interpreting the results. We do all the heavy lifting for you and we are providing it to y'all for free.

See this sample of our fork of Caddy https://dashboard.github.orijtech.com/benchmark/766d78e85d74495fa8fd1eb439827b91
![image](https://user-images.githubusercontent.com/4898263/135826970-4fd285ad-b959-4f19-9db3-10b7f01c3b00.jpeg)

And you'll see results' graphs such for another project Entgo 
![image](https://user-images.githubusercontent.com/4898263/135827709-5611fa20-5087-4327-b5c0-8767f615715e.png)
And then its trends per dimension:
![image](https://user-images.githubusercontent.com/4898263/135827460-aebf330e-6763-420b-a58e-24035e97e9e2.jpeg)
![image](https://user-images.githubusercontent.com/4898263/135827477-0ed0a877-1816-4b2a-bcd1-1e23f205f059.jpeg)
![image](https://user-images.githubusercontent.com/4898263/135827489-5685b7c8-357f-43f5-b4f4-0ecfe8f78f98.jpeg)

Kindly cc-ing some of my colleagues @kirbyquerby @cuonglm

**Comment by mholt** [comment]
Thanks for proposing this, and for putting in the work of screenshots and such. I just don't think we need this, though. We have very few benchmarks, and they're for functions that hardly ever change. That's really nice that you provide it for free, though. We'll keep it in mind if we ever seriously get into more optimizations. But most of our optimizing work is once-and-done (or is too complex for simple benchmarks).

**Comment by odeke-em** [comment]
> Thanks for proposing this, and for putting in the work of screenshots and such. I just don't think we need this, though. We have very few benchmarks, and they're for functions that hardly ever change. That's really nice that you provide it for free, though. We'll keep it in mind if we ever seriously get into more optimizations. But most of our optimizing work is once-and-done (or is too complex for simple benchmarks).

Not a problem at all, thank you @mholt and keep up the good work with Caddy!
