### ISSUE TITLE
Caddy inconsistently normalizes IPv6-formatted IPv4 

### ISSUE THREAD

**Issue by ghost** [caddyserver/caddy#4381]
So this is probably a stupidly trivial issue but an odd issue none-the-less... I was playing with caddy and raw IP addresses; here's my config:

```
207.244.231.125:80 {
	import logto direct-ip
	root * /srv/www/207.244.231.125
	file_server browse {
		index index.html index.mp4
	}
}

[2605:a140:2045:1635::1]:80 {
	import logto direct-ip
	root * /srv/www/[2605:a140:2045:1635::1]
	file_server browse {
		index index.html index.mp4
	}
}

[::ffff:cff4:e77d]:80 {
	import logto direct-ip
	root * /srv/www/[::ffff:cff4:e77d]
	file_server browse {
		index index.html index.mp4
	}
}
```

So [::ffff:cff4:e77d] is equivalent to 207.244.231.125, however browsers treat it as a different origin so I wanted to mount a virtual host to it. However, with this config, requests for that host aren't affected by this configuration. A look with `caddy adapt --pretty` makes it clear what's going on:
![image](https://qzah.kitty.moe)

It appears caddy has normalized [::ffff:cff4:e77d] into 207.244.231.125 and merged the configuration. And so when a browser request comes in with `Host: [::ffff:cff4:e77d]`, there is no match. Caddy shouldn't normalize IPv4 addresses in IPv6 format, to IPv4, in order to be consistent with browsers.

Ironically, caddy doesn't normalize other formats (at least this one) while browsers do. But this is desirable.
![](https://3l1n.qonq.gq)

**Comment by francislavoie** [comment]
If you take your Caddyfile, run `caddy adapt --pretty` on it, adjust the JSON for the `host` matcher to your IPv6 address instead of that integer, then run that config with `caddy run --config caddy.json`, does it work as intended? If so, then we can probably call this a bug with the Caddyfile adapter, where it shouldn't transform the header matcher using the result of `ParseIP`.
