### ISSUE TITLE
reverse proxy restricts download bandwidth

### ISSUE THREAD

**Issue by JustinWebDev** [caddyserver/caddy#4385]
Caddy v2.4.5 on Windows 10 v21H1

I have a file server on the same machine as Caddy.  When uploading to the server (from across the Internet), upload maxes out around 40Mbps, though client uplink is >100Mbps and server download link is >100Mbps.  If I use Stunnel instead of Caddy, I get full speed.

```
myfiles.myserver.com:8443 {
	reverse_proxy :81
}
```

I've tried a few things with the Caddy config, but nothing made a diff.  The CPU runs high during the transfer, but still <50%.  Is Caddy (in this case) single-threaded (bound to 1 core)?

**Comment by mholt** [comment]
You'll need to get a profile to know the answers to those questions. http://localhost:2019/debug/pprof can help with this.

**Comment by mholt** [comment]
I've also used filebrowser and a similar Caddy config without noticable problems. It sounds like Francis has too. What happens if you access the resource on localhost instead of remotely?

**Comment by francislavoie** [comment]
My Windows machine is pretty beefy, Ryzen 3600, 32GB RAM, etc. So you just might be straight up bottlenecked by a weak CPU?

**Comment by mholt** [comment]
Or disk IO. There's a million things it could be at this point, and it's not likely to be Caddy. (if it is, might be a specific tuning in the configuration that is needed, but that's pretty rare; more likely something external that is slowing things down.)

I think more evidence will be needed that this is a Caddy problem before we can act on it. Feel free to drill down and find the bottleneck, then we can do something about if it's a Caddy problem.

**Comment by JustinWebDev** [comment]
I got over 540Mb/s using localhost, so that was throttled by the source disk.  I get >900Mb/s over the LAN.  No TLS with localhost.  Filebrowser is not the issue - that was a suggestion by Francis for comparison, right?  That test proves the bottleneck is in the Caddy piece.

My SSD can handle a 100Mb/s download.  Sure, my CPU is mediocre, but should I need a workstation-grade machine to run a reverse proxy?

Guess I'll have to run Stunnel just for this one service.  What a shame.

**Comment by mholt** [comment]
> Filebrowser is not the issue - that was a suggestion by Francis for comparison, right?

That was to try and see if the issue could be related to HFS or its configuration.

> That test proves the bottleneck is in the Caddy piece.

No, I don't think it does:

> When uploading to the server (from across the Internet), upload maxes out around 40Mbps

Yet you get 540 Mb/s on localhost and 900 Mb/s over the LAN. First, that's a huge difference and isn't surprising if public Internet speeds are variable and slower. Second, I'm suspicious that you're getting faster speeds on LAN than on localhost. This tells me something is wrong with your network configuration.

> Guess I'll have to run Stunnel just for this one service. What a shame.

Feel free, but that's kind of souring for those of us who volunteer our time to help you. We'd rather like to finish and find the problem rather than have our time investments be flushed down the drain.

**Comment by JustinWebDev** [comment]
I'd like to solve it, too, but I was kinda left with nothing to investigate (not knowing how and all the tools).  I do appreciate the help.  And interesting note about localhost speed - again, I wouldn't know where to start with that.

BUT, I did find out something:  I see this problem with Firefox.  I do not see it with Chromium Edge.  So, it is not purely a Caddy issue.  My apologies for concluding that prematurely.

I'll log an issue with Mozilla.  Do you have any idea what could be happening between Fx and Caddy, what would be suspicious?  Anything for the Caddy team to look at first?

**Comment by mholt** [comment]
That's very interesting. Thanks for the update. I have no knowledge as to how Firefox does downloads, they'd be able to help get the diagnostic information that would be needed to see where the bottleneck is.
