### ISSUE TITLE
Upgrade causes caddy service to stop working on alpine

### ISSUE THREAD

**Issue by superyuuki** [caddyserver/caddy#4404]
I installed caddy on alpine via apk add. Worked fine until i ran the caddy upgrade command, after which the rc-service caddy service stopped functioning correctly. Caddy started via run worked fine. I have an inkling that it may be changing the binary while running that could be causing this, as earlier when I manually tried to switch out a self compiled caddy bin into /usr/sbin and rebooted a similar issue occurred.

**Comment by francislavoie** [comment]
You'll need to be more specific. What do you mean by "stopped functioning correctly"? What behaviour do you see? What are in your logs?

**Comment by superyuuki** [comment]
Commands ran: caddy add-package github.com/mholt/caddy-l4, then reboot
Behavior seen: service did not start up. Attempting to manually start the service via rc-service relayed a success message but caddy did not remain up.
How am I running caddy: As a service. Running caddy manually via the cli works fine

**Comment by francislavoie** [comment]
There must be an error message when Caddy attempts to start. We really have nothing to go on without more information, actual log messages, etc.

Please _be specific_.
