### ISSUE TITLE
Caddy not filling Content-Type header

### ISSUE THREAD

**Issue by cucumberbob123** [caddyserver/caddy#4406]
I'm trying to use caddy to proxy two apps on my local machine to app.test and api.app.test. It's important I use a more specific subdomain for the API.
OS: 
`
ProductName:    macOS (Darwin)
ProductVersion: 12.0.1
BuildVersion:   21A559
`
Caddy version: `2.4.5_mac_amd_64`
I'm running it as `sudo`, since I get an error running it normally.
caddyfile:
`
localhost {
        reverse_proxy / localhost:3000
}
`
When I try to visit the page, I get a response, the SSL is valid, but since Caddy won't add the Content-Type header, javascript won't load.
What I've tried:
 - Using different versions of Caddy
 - Repopulating my mime database with `locate mime`
 
Others online seem to need `/etc/mime/types`, but I'm not sure if this applies to macOS.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
