### ISSUE TITLE
tls: json: unknown field "issuer"

### ISSUE THREAD

**Issue by FrancisLeigh** [caddyserver/caddy#4408]
Hello there, 
Version: caddy:2-alpine

I am running into an issue with my `base.json` configuration for the `tls` property
since a new caddy update.

### Error
```ruby
{"level":"info","ts":1636453448.0980191,"msg":"using provided configuration","config_file":"/etc/caddy/config.json","config_adapter":""}

{"level":"info","ts":1636453448.1002865,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}

run: loading initial config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: decoding module config: tls: json: unknown field "issuer"
```

### base.json
```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
          ],
          "logs": {}
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "subjects": [
              "[redacted].dev"
            ],
            "issuer": {
              "module": "internal"
            },
            "on_demand": true
          },
          {
            "issuer": {
              "module": "internal"
            }
          }
        ]
      }
    }
  }
}

```

Has the structure changed from the new update? I'm struggling to understand the caddy docs as i'm not too familiar with this product.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

See the docs structure for the `tls` app, `issuers` is an array of objects. https://caddyserver.com/docs/json/apps/tls/

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
