### ISSUE TITLE
2.4.6 regression: file_browser displays path unencoded

### ISSUE THREAD

**Issue by SlavikCA** [caddyserver/caddy#4409]
**Use case:**
I'm using Caddy to publish school lesson's videos & images via file_server. Here is config:

```
:80
bind 0.0.0.0

root * /var/www/html
file_server browse {
  hide "#snapshot" "@eaDir" *.db
}
```

In version 2.4.5 the name of current folder was displayed correctly on top of the page (the breadcrumb).

**Bug:**
However, in version 2.4.6 it is displayed unencoded. I suspect it caused by security patch and is probably needed. But can the path be correctly encoded and displayed in the UI?

The URL's are changed, too.

The page <title> is unencoded, too

Here are 2 screenshots of 2.4.5 vs 2.4.6:

## **Space in the name of the folder:**
![Space](https://user-images.githubusercontent.com/6293679/140973059-2e526513-fa41-40af-89f7-5b3084e41cf2.png)

## **Russian characters:**
![RussianChars](https://user-images.githubusercontent.com/6293679/140973096-72b615bb-6dfe-4ec1-baf9-e10cffe534ee.png)

**Comment by francislavoie** [comment]
I think this was caused by https://github.com/caddyserver/caddy/commit/33c70f418f780f8e9524c73fbf4bbdbdbb9d7500 /cc @mohammed90

**Comment by mohammed90** [comment]
Thanks for the report! Looking at it 👀
