### ISSUE TITLE
v2.4.6 shows garbage in CLI

### ISSUE THREAD

**Issue by JustinWebDev** [caddyserver/caddy#4414]
Win10 v21H1 x64
 example of garbage around the "INFO" string:
D:\BIN\caddy>caddy_windows_amd64.exe run
2021/11/10 18:00:11.064 ←[34mINFO←[0m   using adjacent Caddyfile

D:\BIN\caddy>caddy_windows_amd64.exe validate
2021/11/12 02:04:08.406 ←[34mINFO←[0m   using adjacent Caddyfile

**Comment by mholt** [comment]
You'll need to use a terminal that supports ANSI escapes.

**Comment by francislavoie** [comment]
In other words, use https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701, the new, modern, "command prompt" replacement.
