### ISSUE TITLE
headers: JSON strings deleted when setting response headers

### ISSUE THREAD

**Issue by hairyhenderson** [caddyserver/caddy#4418]
With the following `Caddyfile`, I expect there to be a response header with the value `Foo: {"foo": "bar"}`:

```
localhost

header Foo "{\"foo\":\"bar\"}"
respond "hello world"
```

But instead, I get:

```console
$ curl -I https://localhost
HTTP/2 200 
foo: 
server: Caddy
content-length: 11
date: Sun, 14 Nov 2021 15:18:34 GMT
```

It seems that any text between the `{}` is being lost, for example, `header Foo "hello{}world"` results in a response header of `Foo: helloworld`.

**Comment by hairyhenderson** [comment]
It's also worth noting that this isn't a `Caddyfile`-specific bug - the equivalent JSON config also fails:

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "localhost"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "headers",
                          "response": {
                            "set": {
                              "Foo": [
                                "{\"foo\":\"bar\"}"
                              ]
                            }
                          }
                        },
                        {
                          "body": "hello world",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```

**Comment by hairyhenderson** [comment]
It's being interpreted as a placeholder - escaping the first `{` (i.e. `\{`) makes this work. Still - is that expected behaviour? I’d expect either the string to be interpreted literally if it can’t resolve the placeholder, or some kind of error logged to tell me that the placeholder is invalid

**Comment by mholt** [comment]
Yeah, so this is kind of intentional, because you _can_ escape curly braces it makes it possible to have the flexibility of placeholders that don't always have values without rendering a raw literal placeholder, while also using curly braces by means of escaping. (See https://github.com/caddyserver/caddy/pull/4419#pullrequestreview-806469366.)

I'm open to changing this behavior so that escaping is not necessary, but I believe you'll lose the ability to use placeholders that aren't always set.

**Comment by francislavoie** [comment]
Since you closed the PR, I guess we can close the issue as well.

**Comment by hairyhenderson** [comment]
thanks @francislavoie - I meant to do this but totally missed it 😅
