### ISSUE TITLE
2.4.6: Inconsistent template rendering when having nested includes

### ISSUE THREAD

**Issue by triole** [caddyserver/caddy#4423]
First off thanks for this wonderful piece of software. Caddy is great.

**Problem Description**
I use caddy for some pretty complex markdown templating with nested includes. With caddy 2.4.5 everything was fine but with the latest version 2.4.6 rendering templates seems pretty inconsistent. Caddy renders different pages between page reloads. Sometimes the result looks good, sometimes the markdown file is put plain as it is into the final html leading to something like this:

```html
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    ---
title: My Title
tags:
    - tag1
    - tag2
    - tag3
---
# What a wonderful heading

And a lot of text...

<h1><p>My Title</p>
</h1>
<h1 id="what-a-wonderful-heading">What a wonderful heading</h1>
<p>And a lot of text...</p>


</body>

</html>
```

**Here is a simple version of my setup**

Caddyfile
```
:7777 {
	file_server
	templates
}
```

index.html
```html
<!DOCTYPE html>
<html>

<head>
</head>

<body>
    {{include "incl.html"}}
</body>

</html>
```

incl.html
```
{{$content := "markdown.md"}}
{{$p := include $content | splitFrontMatter}}
<h1>{{markdown $p.Meta.title}}</h1>
{{markdown $p.Body}}
```

markdown.md
```markdown
---
title: My Title
tags:
    - tag1
    - tag2
    - tag3
---
# What a wonderful heading

And a lot of text...
```

**How to reproduce**
Try loading the page several times (i.e. `curl http://localhost:7777`) and look into what you get. The different versions of output seem to be pretty evenly distributed.

**Comment by francislavoie** [comment]
@rockorager recently made some changes to template imports in https://github.com/caddyserver/caddy/pull/4321 which might be related.

@rockorager would you be able to look into this?

**Comment by mholt** [comment]
I was thinking the same thing. Must be related to that state that got moved around a bit.

**Comment by rockorager** [comment]
I will look into it this week!

**Comment by rockorager** [comment]
I have a fix [here](https://github.com/rockorager/caddy/tree/bug-funcInclude). @triole - can you try it out and make sure it solves your issue?

I was able to recreate it pretty easily thanks to your example so I think this should work for you, but want to double check. I added a new test for this case, also.

**Comment by triole** [comment]
I tested and tried a few other markdown templating setups. They all worked fine. The problem seems to be solved and I'd be happy to see the bug fix merged into the next release. 

Thanks for your quick reaction and the fix. Cheers.

**Comment by francislavoie** [comment]
I'd rather leave this open until the bug is merged. Thanks @triole!
