### ISSUE TITLE
Faster / seamless config update when adding new hosts to match and tls policies

### ISSUE THREAD

**Issue by dazoot** [caddyserver/caddy#4439]
We have a bunch of domains all pointing to the same `routes handle`.
We only add or remove domains to `routes match host` and to `tls automation policies subjects`.
(so the actual handle part remains unchanged)

So basically our config remains the same, just a host is added pointing to the same config.

The problem we have is that:
- it takes too long to make the update (our grace period is 15 seconds)
- it breaks / stops the current connections 

Would like to have a seamless add / remove host to an existing config, without interrputing existing connections or doing basically almost a cold restart.

Caddy Version:
```
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

**Comment by mholt** [comment]
Hmm, I think this is basically the same as #3143 - you want to change part of the config, which would require that the configs are mutable in memory while the server is live. :cold_sweat: It's a hard problem [I talked about somewhat in this presentation](https://www.youtube.com/watch?v=EhJO8giOqQ), but I'm open to ideas looking to make this possible.
