### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "\xbdh\xab+\x00\x00\x00"

### ISSUE THREAD

**Issue by dazoot** [caddyserver/caddy#4445]
Since we started serving some request behind nodejs i am seeing lots of errors like this in the log:

```
2021/11/25 13:49:30 Unsolicited response received on idle HTTP channel starting with "\xbdh\xab+\x00\x00\x00"; err=<nil>
```

Caddy version:
```
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

This is the addition we made to the Caddyfile redirecting some requests to a nodejs server:

```
    handle_path /tr/* {
        rewrite * /plugin/nzectrack/view{path}
        reverse_proxy localhost:12080 {
            lb_policy least_conn
            header_up Host {host}
            header_up X-Real-IP {http.request.remote.host}
            header_up X-Real-Host {host}
            header_down -Server
        }
    }
```

**Comment by dazoot** [comment]
I am using restify on the nodejs backend and if i specify in the response header `Connection: close`, i don't get the caddy error.

```js
res.writeHead(200, {'Content-Type': 'image/gif', 'Content-Length': 43, 'Connection': 'close' });
res.end(pixel, 'binary');
return next();
```

**Comment by francislavoie** [comment]
That error message comes from the Go stdlib. Basically it means that the upstream server either responded with data before the HTTP request was finished, or it continued to respond with data after it was meant to stop (already wrote the full content length's worth of bytes?)

Traefik shows the same error if the backend misbehaves: https://github.com/traefik/traefik/issues/3295. 

I'm not sure we can do anything about this, you'll just need to drill down and figure out what's going on. Maybe use wireshark or something between Caddy and your upstream to try to figure out what's going on?

**Comment by dazoot** [comment]
At least i would like the log to be more detailed and be able to suppress it.

**Comment by francislavoie** [comment]
I'm not sure we can really provide any more detail, because like I said, this comes straight from the Go stdlib, not from Caddy itself. We use the `http.Client` from Go and that's its internal behaviour.

If the error shows up not encoded, then there's not much we can do, because it means the stdlib directly printed the message to `stderr`. It comes from here: https://github.com/golang/go/blob/45bae64015975a4d7ede597a55397545571d8bc5/src/net/http/transport.go#L2242

**Comment by francislavoie** [comment]
Did you end up finding the problem? I'm sure it would be of interest of others if they find their way to this issue!

**Comment by dazoot** [comment]
I have posted above the "fix". I am sending `Connection: close` header from NodeJS backend and the error is gone.

**Comment by francislavoie** [comment]
Ah, okay 👍
