### ISSUE TITLE
Global option to apply directives to all sites?

### ISSUE THREAD

**Issue by ledlamp** [caddyserver/caddy#4456]
I didn't find a similar suggestion with a quick search.

So it seems if you want to apply settings to all sites, you have to duplicate it on each site either manually or using imports:
```
(common)  {
    log
    handle_errors {...}
    rate_limit {...}
    # etc
}

a.site {
   import common
   # site A conf
}

b.site {
   import common
   # site B conf
}

```

This means a little bit of boilerplate which I sometimes forget to type when adding new sites. It's also a bit inconvenient if you need to add common config after having added a large number of sites in many different files.

I think it would be a good idea to have a global options block where you can put directives to be applied to all sites. For example, I simply want to enable logging for all sites, but right now I have had to add `log` to each site. I'm going to have to replace all of them with imports if I want to add other stuff, such as a site-agnostic error handler to change caddy's default blank error pages, and a global rate limit.

**Comment by mholt** [comment]
Sharing/reusing config is where the native JSON config shines over Caddyfile.

But I'd be interested in proposals to see how this should be implemented, if we do that. I do worry that it makes the config more complicated though, which is why I haven't done this.

**Comment by francislavoie** [comment]
I personally see no problem with doing `import common` in each site if you need it. I don't like adding more implicit behaviour to config.

**Comment by francislavoie** [comment]
Closing as inactive. I don't think there's really any appetite for this right now, I think `import common` is sufficient.
