### ISSUE TITLE
Building Caddy v1

### ISSUE THREAD

**Issue by charliehoward** [caddyserver/caddy#4462]
Does anyone have instructions on how to install Caddy 1 on a Raspberry Pi as I can't get my setup working with version 2 and I need to reinstall my Pi and don't want to lose my setup?

**Comment by mholt** [comment]
I can't honestly condone deploying Caddy 1 anymore, so I can't help there (I haven't even tried building it in like two years); but what isn't working with Caddy 2? Please feel free to ask your help questions on our forum! https://caddy.community
