### ISSUE TITLE
feature request: API to get the adapted config

### ISSUE THREAD

**Issue by adamburgess** [caddyserver/caddy#4465]
As far as I understand it, to load a Caddyfile you have two options:
* use the command `caddy adapt` with a Caddyfile, get the JSON, then give that to the `/load` admin API
* use the `/load` admin API with `text/caddyfile` and it adapts and loads.

I would like to be able to do something like this:
* use a `/adapt`  API with `text/caddyfile` which adapts and returns the json, I then do any other transformations, and then post that to `/load`.

My use case: I have a bunch of Caddyfile configs, the syntax is nice, but I also would like to use https://github.com/mholt/caddy-l4 -- which doesn't yet have Caddyfile support.

So, I'd adapt the Caddyfiles to json, merge in some custom handlers for layer4, and then load that.

pros:
* nice endpoint
* means i dont need a caddy for the server and a caddy on a configuration service
* the code is basically already done

cons:
* why is this webserver spending cpu cycles doing something that doesn't need to be ran on the server

It didn't seem so hard to make so I copied some lines from `caddyconfig/load.go` and published it as an extension: https://github.com/adamburgess/caddy-admin-adapt

**Comment by francislavoie** [comment]
That seems like a reasonable thing to add. I don't see why not 👍

I think we'll want to make the endpoint also support passing the adapter name like `/adapt/json5` because I don't think all the adapters have defined mime types. It can definitely also handle `text/caddyfile` though if not in the URL.

**Comment by mholt** [comment]
Hm, yeah, I guess that would be useful in that case.

> why is this webserver spending cpu cycles doing something that doesn't need to be ran on the server

Run it locally then, instead of on a production server. Should get the same result if your server build is identical.

Pull requests welcome, it'll be a while before I can get around to this. But should be easy enough.

**Comment by mholt** [comment]
@adamburgess Why did you close this? (It did remind me that I need to work on this though.)

**Comment by mholt** [comment]
Implemented in #4846 -- @adamburgess do you want to try it?
