### ISSUE TITLE
`file_server` doesn't properly canonicalize when inside `handle_path`

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4466]
For example, given this config:

```
:8880 {
	handle_path /strip* {
		root * .
		file_server browse
	}
}
```

Making a request to `http://localhost:8880/strip` does not trigger a canonicalization redirect to `/strip/`, so the file browser ends up with broken relative links while on the `/strip` page (clicking on a file will go to `/file.txt` instead of `/strip/file.txt` as it should).

**Comment by mholt** [comment]
Wouldn't the correct config be `handle_path /strip/* {` ?

**Comment by francislavoie** [comment]
Not necessarily, you might want to be able to go to `/strip` and have it perform `file_server`'s built-in canonicalization redir. Obviously the workaround is to use `/strip/*` and add your own `redir /strip /strip/` but that's unintuitive and unfortunate.

**Comment by mholt** [comment]
@francislavoie Tbh that's what I'd do, I just don't know of an elegant solution otherwise. I do think a manual redirect is not a bad solution, personally. :man_shrugging:

**Comment by francislavoie** [comment]
We _might_ be able to look at the path and if it's literally `""` (empty string) then we could assume a rewrite happened to strip the prefix and we should redirect to `{orig_path}/`. I'll have to play around with it. Not 100% certain that's correct though but it might fix some cases.

**Comment by mholt** [comment]
I don't know if that would work (rewriting to an empty path?) and if it did, the implicit behavior around that kinda scares me :flushed: Maybe best to leave the config explicit for now. It's very easy and clear.

(Closing, but can continue discussion if needed.)

**Comment by francislavoie** [comment]
FWIW, I was right, the path is actually `""` at this point after `handle_path` strips the path prefix, so it's trivial to add a check for that, and I really can't think of any harmful side effects. If the path was `""` for any other reason and the code reaches the `browse` code (because it mapped to a directory on disk) and the original request _did not_ have a trailing slash, then I see no way for there to be a problem by just triggering a redirect to add the slash.
