### ISSUE TITLE
Question/Potential Issue About RespHeader Being Allowed to Set Location Header

### ISSUE THREAD

**Issue by orware** [caddyserver/caddy#4467]
I am not entirely sure if this is a problem or not, but I figured I'd share it in case it may be one.

I have an older, fairly simple PHP-based project that's mainly using PHP for some basic HTML templating type work and I was considering switching things to use Caddy's templating functionality instead.

I'm pretty sure I can achieve most of what I need to do with the existing Caddy template functionality, but one item that cropped up right away is that in the root directory of this project I have a simple redirect in place that works by using PHP's `header()` function to set the `Location` header similar to the following example from the PHP docs: https://www.php.net/manual/en/function.header.php

```php
<?php
header('Location: http://www.example.com/');
```

So I attempted to make use of the `.RespHeader` option provided in Caddy's templating option and I do see the header set when the pages loads, however I don't see the actual page location change at all (it ends up staying on that page without redirecting):

```go
{{.RespHeader.Set "Location" "http://www.example.com/"}}
```

I'm sure ideally these types of redirects are best to completed within the Caddyfile configuration...but I think in certain cases being allowed to use simple redirects like this could be a useful feature for the templating side of things. 

(I'll probably end up implementing something that runs on the client-side instead for this particular situation, but figured I'd share the scenario)

**Comment by mholt** [comment]
You also need to issue a redirect status code, 3xx. Not sure there's currently a way to do this with templates as it doesn't usually make much sense for the page's content to set its own status code. But if you view templates as a preprocessor like PHP, then I guess it does. Hmm.

**Comment by orware** [comment]
It looks like by default here on my end the status code being used is 302 in the PHP version when that parameter is not directly provided to the header function (I didn't review the PHP documentation for the function that thoroughly before writing my comments above, but I do see the additional parameter options for that PHP header function allowing for a specific status code to be provided too).

It's a thought to consider I suppose, but if I've been the only person that's asked about it, then it's probably not a big issue that needs addressing :-).

I should be able to do the same thing in JavaScript here on my end so it shouldn't be a big issue to work around.

Thank you for the quick reply!

**Comment by mholt** [comment]
It's probably not hard to add this capability, but you're right, I do think this is the first to request it. :)

The templates directive doesn't actually set the status code, though; whatever originates the content does. So if you're serving static files, then it's the static file server. If it's reverse proxy, then it's your backend. If it's the static response handler, then it's that. If you want to adjust this server-side, I would start at those places.

**Comment by mholt** [comment]
(If this feature is still needed, let me know; otherwise I'm going to defer until we see a real need for it.)

**Comment by orware** [comment]
No problem Matt! (We can table it for now until any others start clamoring for it ;-). Thank you!
