### ISSUE TITLE
Some questions about module programming

### ISSUE THREAD

**Issue by WienkeTl** [caddyserver/caddy#4469]
Hello, I love the convenience of caddy very much, so I want to implement some simple functions by myself and put them in a module. Unfortunately, the official documentation does not seem to be so comprehensive. In addition, I am a novice, so I encountered various difficult problems in the process. I hope the official can help me to solve the following problems so that I can get started as soon as possible and find them Extend the fun of caddy functions.

Before describing the problem I encountered, I first simulate the process of the module I defined:

Install xcaddy:

```
$ go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
```

Create a directory and initialize a module project:

```
$ mkdir gizmo
$ cd gizmo
$ go mod init gizmo
```

Write a gizmo.go:

```
package gizmo

func init() {
	caddy.RegisterModule(Gizmo{})
}

// Gizmo is an example; put your own type here.
type Gizmo struct {
}

// CaddyModule returns the Caddy module information.
func (Gizmo) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "foo.gizmo",
		New: func() caddy.Module { return new(Gizmo) },
	}
}
```

Execute in the root directory of the gizmo module project:

```
$ ~/go/bin/xcaddy build --with gizmo=$(pwd)
```

View the list of modules that have been built in the caddy binary:

```
$ ./caddy list-modules
```

**Question one:**

Looking at the module list, we can see that the `foo.gizmo` is a Non-standard modules. I want to change foo.gizmo into Standard modules, how can I solve it?

```
tls.stek.standard
  Standard modules: 83
foo.gizmo
  Non-standard modules: 1
```

**Question two:**

If I want to load the `foo.gizmo` module through caddy by default, instead of loading the module through Caddyfile, how can I implement the code?

```
localhost {
  gizmo       # Do not configure via caddyfile, but automatically load the gizmo by default
}
```

**Question three:**

If I want to adjust the order of `foo.gizmo` modules, I must configure it through Caddyfile. But I don't want to configure it through Caddyfile, but when the caddy program starts, let `foo.gizmo`  be automatically placed behind a certain module by default. How do I implement the code?

```
# I want to ignore the configuration of the caddyfile file, let the caddy binary program start automatically load the gizmo, and set the gizmo order
{
	order gizmo before map
}
localhost {
  gizmo
}
```

I'm still a novice, so I kindly ask the official to tell me how to solve it in a simple way? Thank you not only! I will gradually understand the advantages of the GO language, and slowly realize the happiness that programming brings me.

**Comment by francislavoie** [comment]
> Looking at the module list, we can see that the foo.gizmo is a Non-standard modules. I want to change foo.gizmo into Standard modules, how can I solve it?

No. Standard modules are "ones that come with Caddy without plugins". Non-standard means it was added in as a plugin. At runtime, there's no difference.

> If I want to load the foo.gizmo module through caddy by default, instead of loading the module through Caddyfile, how can I implement the code?

That's not possible. Caddy loads modules by being configured.

What are you trying to do? Maybe an HTTP handler module is not the right kind of module for what you're doing, maybe you want an app module?

Please read the architecture documentation to understand why Caddy works this way. https://caddyserver.com/docs/architecture

**Comment by mholt** [comment]
Hey @WienkeTl, it's great that you want to extend Caddy! What does your module do? How do you want it to work?

**Comment by francislavoie** [comment]
I'm not seeing anything actionable here at this point, so I'll close this. Feel free to comment again if you have further questions!
