### ISSUE TITLE
feature request: designate a key in the JSON structure for arbitrary metadata (Caddy will ignore)

### ISSUE THREAD

**Issue by jmellicker** [caddyserver/caddy#4471]
We're writing a Caddy configuration utility, and we'd like to store some metadata about each route in the Caddy JSON config (as a SPOT, to avoid maintaining a separate file or data store and eliminate the risk of the two getting out of sync).

Currently, we're putting metadata in the "@id" key with a character delimiter, but the string values are getting long and unwieldy, and I wonder if anyone else would find it useful to designate a key( maybe "`metadata`"?) in the Caddy JSON that users can nest whatever data desired, and that Caddy would ignore.

**Comment by mholt** [comment]
I thought about this when designing Caddy 2, but ultimately decided against it as it's more of a config format concern than a parsing concern IMO. You basically want comments in your JSON, yeah? You can use JSON-C, for example, there's even a config adapter for it: https://caddyserver.com/docs/config-adapters

**Comment by jmellicker** [comment]
Thanks @mholt! JSON-C or JSON-5 are great solutions, didn't think of that!
