### ISSUE TITLE
Digest Auth 

### ISSUE THREAD

**Issue by LinusT** [caddyserver/caddy#4472]
A feature request for Caddy 2 - support of Digest Auth 

Rationale: for protection of MITM attacks when forced to connect through corporate firewalls and/or having to rely on unencrypted HTTP (yes sometimes that is acceptable say in scenarios where actual content such as backups are already encrypted).

If not extending the basicauth directive is an option an alternative could be to implement a digestauth directive instead.

Should be validated for both webdav and fileserver.

**Comment by francislavoie** [comment]
Digest authentication has too many security disadvantages. I don't think we have any plans to implement it as a standard module in Caddy.

If you absolutely need it though, you can write your own plugin for Caddy to implement it: https://caddyserver.com/docs/extending-caddy

Feel free to reach out if you need help with writing the plugin.

**Comment by mholt** [comment]
Duplicate of #712

**Comment by LinusT** [comment]
Appologies I missed the already closed issue from v1.

Fair enough. Digest is not great. To some extent the issue is more a limitation with WebDAV since most desktop WebDAV clients do not support Cookies/Forms authentication and require Basic, Digest, NTLM or Kerberos. They cannot present the HTML login page with the login form. In all honesty I've not seen many clients that support NTLM or Kerberos either. Hence the least of all bad options with at least some MiTM protection.
