### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by veritem** [caddyserver/caddy#4484]
I've got this Nginx configuration   and would love to migrate to the caddy with an automatic HTTPS certificate
![image](https://user-images.githubusercontent.com/53856673/146436049-e02c69bb-9674-4349-89f8-ecd0a660dbed.png)

I've tried to check the documentation on how to do migration but nothing  helped me, any idea on how to do it.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by veritem** [comment]
Thanks! 

just submitted https://caddy.community/t/migrating-from-ngnx/14435
