### ISSUE TITLE
 case-sensitive causes error

### ISSUE THREAD

**Issue by huabin** [caddyserver/caddy#4490]
Hey,

I found an error, my `config.json` like this

```
sub.esdomain.com {
 tls email@email.com
 @staff_websocket {
  path /3367
  header Connection *Upgrade*
  header Upgrade websocket
 }
 reverse_proxy @staff_websocket localhost:37566
}
```

If a request is sent with header like `Connection *upgrade*`, it will return an error `TLS handshake error`.

**Comment by francislavoie** [comment]
Being discussed here: https://caddy.community/t/appending-tls-handshake-error-ws-tls/14474

This isn't a bug, it's simply how the `header` matcher works.
