### ISSUE TITLE
Caddy process locks up when attempting to use reload command

### ISSUE THREAD

**Issue by DillFrescott** [caddyserver/caddy#4495]
Sometimes it works fine, other times the entire process just gets stuck and doesn't actually reload. I have to kill the process and restart it to fix it.

Please see linked image:

https://i.imgur.com/Vf85nfi.png

**Comment by mholt** [comment]
What is your complete config? Usually this happens if you're proxying the admin endpoint. But I think we've seen a similar report before: https://caddy.community/t/api-getting-unresponsive/14219/12 - can you try to narrow it down more? Some tips I posted toward the end of that topic should help you identify the place where it hangs. (Add some `fmt.Println()` statements to the code.)

**Comment by DillFrescott** [comment]
https://bit.ly/3yPK75g

This is the json one I'm using as the default config.

---------------------------------

I used the command with caddy to convert a caddyfile to its native format. And I'm just using the output from that.

---------------------------------

If it helps, here is the native caddyfile with, again, addresses removed:

https://bit.ly/30QataG

**Comment by DillFrescott** [comment]
I should add that its running on Ubuntu 20.04

**Comment by DillFrescott** [comment]
It's a low powered virtual machine from oracle cloud. Could it be possible that its overloading the core?

**Comment by mholt** [comment]
Highly doubt it is, config reloads are cheap (unless there's thousands of certs to load but that's definitely not the case here).

Would you be able to try some of the debugging steps in the linked topic above? Adding some prints to the code, maybe looking at the debug/pprof endpoint, or using Ctrl+\ to see where it's hung.

**Comment by DillFrescott** [comment]
I'm really sorry but I have no idea how to do that. I know enough to write a basic caddyfile and use it to proxy but that's my extent of programming knowledge!

**Comment by mholt** [comment]
Ok, no worries. If you want to learn how to do this (it's very easy, I promise, you don't need to know how to code!) I'll be happy to guide you along.

**Comment by thorstenkramm** [comment]
I'm experiencing the same problem. 
My assumption is, the Caddy API does not accept any PUT, PUSH or DELETE requests if there is at least one active http connection. 
The issue can be provoked easily:

Start a very simple file server. I used this config:
```
https://download.example.com:9443 {
  root * /var/www/downloads
  file_server
  encode zstd gzip
  log {
	output file /tmp/caddy.log
  }
}
```

Create a large file to download
```
dd if=/dev/zero of=/var/www/downloads/large.file bs=1M count=256
```
Start caddy and download the file very slowly. That keeps the connection open.
```
curl https://download.example.com:9443/large.file -o /dev/null --limit-rate 1k
```

While the download is in progress, try 
```
caddy reload
```
It hangs until the connections is terminated. Pushing a new config is also not possible, for example
 
```
curl -X PUT "http://localhost:2019/config/apps/http/servers/srv0/routes/0/" \
	-H "Content-Type: application/json" \
	--data-binary @config.json
```
You will get a timeout.

**Comment by francislavoie** [comment]
@thorstenkramm that's because Caddy is waiting for all the active requests to complete so it can reload gracefully. You can configure the `grace_timeout` of the `http` server so that it will shut down forcefully earlier (default no timeout) https://caddyserver.com/docs/json/apps/http/grace_period/

**Comment by thorstenkramm** [comment]
@francislavoie Thanks for the hint. Makes sense. Using a short `grace_period` in the [global section](https://caddyserver.com/docs/caddyfile/options#grace-period) of the Caddyfile solved my problem. 👌

**Comment by francislavoie** [comment]
Closing as inactive
