### ISSUE TITLE
TLS support for the file-server command

### ISSUE THREAD

**Issue by espadrine** [caddyserver/caddy#4496]
When running `caddy file-server -p 8080`, we can connect to http://localhost:8080, but not to https://localhost:8080. That makes sense, since a single port cannot serve both HTTP and HTTPS.

However, it is inconvenient for testing static files locally, as more and more Web functionality is only available behind TLS, such as [CacheStorage](https://bugs.chromium.org/p/chromium/issues/detail?id=1026063#c3), it is more convenient to use TLS by default.

While I expect we can do that manually with a Caddyfile (although I couldn’t figure that out within 20 minutes), it would be convenient for the following to work:

1. Go to a folder with an index.html,
2. Enter `caddy file-server --listen :8080 --tls`,
3. Go to <https://[::1]:8080> and see the page.

**Comment by mholt** [comment]
`caddy file-server --domain localhost --listen :8080`

Isn't that all you need?,

**Comment by espadrine** [comment]
I had tried it but dismissed it initially because it gave me an error:

> file-server: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: permission denied

As you indicated it was the right path, I dug into it a bit more, and realized that I was making incorrect assumptions. Doing `caddy file-server --domain localhost --listen :8080` works. The sudo is important, because it will also open :80 for redirection.

Using sudo, it works when opening <https://localhost:8080>. It doesn’t work when opening <https://[::1]:8080> for some reason (Firefox yields a SSL_ERROR_INTERNAL_ERROR_ALERT), but at least I can move forward.

Thanks a lot, and merry Christmas!

**Comment by mholt** [comment]
Merry Christmas!

Yeah, that's all as expected. Port 80 is for [automatic HTTPS redirects](https://caddyserver.com/docs/automatic-https), and trying to load a site without SNI for a certificate using `localhost` (as is the case with [::1]) will yield a TLS alert. You have to use the same hostname as is on the certificate.
