### ISSUE TITLE
aborting with incomplete response	log spam

### ISSUE THREAD

**Issue by OmgImAlexis** [caddyserver/caddy#4500]
After starting caddy I've got 2 issues.

1. The logs are outputting to stdout even though I ran caddy with `start`.
2. Caddy is logging this error on every single page refresh for my site.

Am I doing something wrong or is this a caddy issue?
Is the fact I'm using server sent events causing this?

```
root@pine:~/config# caddy start
2021/12/31 20:06:57.520	INFO	using adjacent Caddyfile
2021/12/31 20:06:57.522	WARN	input is not formatted with 'caddy fmt'	{"adapter": "caddyfile", "file": "Caddyfile", "line": 6}
2021/12/31 20:06:57.523	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2021/12/31 20:06:57.523	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2021/12/31 20:06:57.523	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2021/12/31 20:06:57.524	INFO	http	enabling automatic TLS certificate management	{"domains": ["up-n-down.xyz"]}
2021/12/31 20:06:57.524	INFO	autosaved config (load with --resume flag)	{"file": "/root/.config/caddy/autosave.json"}
2021/12/31 20:06:57.524	INFO	serving initial configuration
2021/12/31 20:06:57.525	INFO	tls	cleaning storage unit	{"description": "FileStorage:/root/.local/share/caddy"}
2021/12/31 20:06:57.525	INFO	tls	finished cleaning storage units
2021/12/31 20:06:57.525	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc00053fc00"}
Successfully started Caddy (pid=43037) - Caddy is running in the background
root@pine:~/config# 2021/12/31 20:07:22.446	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
2021/12/31 20:07:24.765	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
2021/12/31 20:07:25.063	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
2021/12/31 20:07:25.325	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
2021/12/31 20:07:25.551	ERROR	http.handlers.reverse_proxy	aborting with incomplete response	{"error": "context canceled"}
```

My Caddyfile.
```Caddyfile
https://up-n-down.xyz

reverse_proxy 127.0.0.1:8080

header {
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    X-Xss-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "DENY"
    Content-Security-Policy "upgrade-insecure-requests"
    Referrer-Policy "strict-origin-when-cross-origin"
    Permissions-Policy: microphone=()
    Server "Yes?"
}
```

**Comment by mholt** [comment]
Yeah so I think this just means the response body was written partially and then the client closed the connection (that's usually what cancels a context, but other things can too sometimes).

https://github.com/caddyserver/caddy/blob/3fe2c73dd04f7769a9d9673236cb94b79ac45659/modules/caddyhttp/reverseproxy/reverseproxy.go#L722-L733

SSE could definitely be related, but aren't in and of themselves a problem.

We can reopen this if it's a bug (but the Go standard library does the same thing, so it's unlikely), further questions can be asked on our forum too: https://caddy.community. Happy new year!

**Comment by OmgImAlexis** [comment]
> Yeah so I think this just means the response body was written partially and then the client closed the connection (that's usually what cancels a context, but other things can too sometimes).

Is there anything I can do to avoid this? It seems anyone closing a tab on my site is going to cause this which will fill my logs coming from caddy.

Is caddy meant to still log to stdout even if it's started in background mode? That seems like a bug. To "fix" it I had to start a new bash session.

**Comment by francislavoie** [comment]
> Is caddy meant to still log to stdout even if it's started in background mode? That seems like a bug. To "fix" it I had to start a new bash session.

Yes, that's normal. You can do something like `bash -c 'caddy start'` if it bothers you. But log messages are important, best to not throw them away.

Better to run with `caddy run` as a service so that logs are sent to the journal, among many other advantages.

**Comment by OmgImAlexis** [comment]
I guess I had assumed caddy worked like most services and used /var/log/caddy for those logs when in background mode.

**Comment by Remonli** [comment]
It's better to have option to ignore such error.

**Comment by mholt** [comment]
Yeah, having more logic in the logging will only slow it down, which we surely don't want.

**Comment by francislavoie** [comment]
Forgot I wrote this up, but https://github.com/caddyserver/caddy/issues/4690; we won't implement an option for this specifically, but we may introduce a more generalized and configurable way to filter out logs.

**Comment by AlexZorzi** [comment]
@francislavoie could this spam be triggered by the website being too heavy and the client maybe having a slow connection, like on a mobile device. And every time the user moves around the website and the whole page wasn't fully loaded (assets like heavy images) this triggers an "aborting with incomplete response" ?

**Comment by mholt** [comment]
Potentially. The basic idea is that the client stops downloading (usually) before it is done, by closing the connection.
