### ISSUE TITLE
Reverse proxy sporadically 502 when empty curly braces are written on the same line in Caddyfile

### ISSUE THREAD

**Issue by cedric-sun** [caddyserver/caddy#4501]
## Environment

Windows 10 AMD64

Latest release from `https://caddyserver.com/download`.

  ```bash
./caddy_windows_amd64.exe version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```

I was reverse-proxying for a Vue project's webpack dev-server. All `*.example.com` are aliased to `localhost`.

## Replication

The following works great

```caddyfile
http://local0.example.com {
	reverse_proxy /* localhost:11451 {
		
	}
}
```

But when the curly braces are written on the same line:

```caddyfile
http://local0.example.com {
	reverse_proxy /* localhost:11451 {}
}
```

![](https://i.imgur.com/bBu5xn2.png)

Nearly half of the times client receives HTTP 502, while other requests return normally even with content.

For 502 ones, Caddy logs:

```
2022/01/03 09:00:21.737 ←[31mERROR←[0m  http.log.error  making dial info: upstream {}: invalid dial address : missing port in address   {"request": {"remote_addr": "127.0.0.1:57018", "proto": "HTTP/1.1", "method": "GET", "host": "local0.example.com", "uri": "/js/9.js", "headers": {"Accept": ["application/signed-exchange;v=b3;q=0.7,*/*;q=0.8"], "Accept-Encoding": ["gzip, deflate"], "Accept-Language": ["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6"], "Cookie": ["jguid=9244a986-f872-22a9-5f42-a6c13ebcf75e"], "Connection": ["keep-alive"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"], "Purpose": ["prefetch"], "Referer": ["http://local0.example.com/"], "If-None-Match": ["W/\"14323-gbbfEHkeFD7peaJ6qEGdT6QDbls\""]}}, "duration": 0, "status": 502, "err_id": "2famxsnvm", "err_trace": "reverseproxy.statusError (reverseproxy.go:886)"}
```

**Comment by mohammed90** [comment]
Writing the arguments of the `reverse_proxy` directive in this manner

> 
> ```
> http://local0.example.com {
> 	reverse_proxy /* localhost:11451 {}
> }
> ```
> 

forces the `reverse_proxy` directive to assume the second argument is another upstream. See the second example in the [documentation page](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#examples). There's no need for the curly braces if you're not utilizing any of the sub-directives. Braces on different lines define the beginning and end of a block. Braces within the same line define the use of a [placeholder](https://caddyserver.com/docs/caddyfile/concepts#placeholders). Any Caddy module may define their own placeholder, so it's hard to assume whether what's between the braces is a valid placeholder or plain upstream.

I'm going to close this, but further questions may be asked on the [community forum](https://caddy.community). Thanks for understanding!

**Comment by mohammed90** [comment]
After discussing it with the team, we decided to reject empty blocks when parsing.
