### ISSUE TITLE
php_fastcgi causes open redirect

### ISSUE THREAD

**Issue by Jimbolino** [caddyserver/caddy#4502]
I recently got a security scan by an external company, and they found open redirects on our domains.
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
I've traced the issue to the php_fastcgi configuration option.

```
$ curl -v http://localhost//example.com/%2F.. 2>&1 | grep Location
< Location: //example.com//../
```

**Comment by mohammed90** [comment]
> I recently got a security scan by an external company, and they found open redirects on our domains.
> https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
> I've traced the issue to the php_fastcgi configuration option.
> 
> ```
> $ curl -v http://localhost//example.com/%2F.. 2>&1 | grep Location
> < Location: //example.com//../
> ```

Recently fixed by #4499. You can test this by grabbing the CI build artifacts or build from HEAD.
