### ISSUE TITLE
Tip on using X-Forwarded-For on reverse_proxy

### ISSUE THREAD

**Issue by juliuswz** [caddyserver/caddy#4503]
Even though the current docs already warns about the incoming headers being passed to the backend, I think there needs to be some clarification about `X-Forwarded-For`. Recently a situation happened where a bot/crawler made several requests with the `X-Forwarded-For` header set to arbitrary values, it turns out that as the Caddy defaults to pass headers as they come to the backend it messed up all the statistics on the backend side.

Obviously there are ways to avoid this like using the `request_header -X-Forwarded-For` directive or passing `{remote_host}` through `header_up`. 

Maybe a hint or something could be included in the `reverse_proxy` section warning about this.

**Comment by francislavoie** [comment]
This feature has been merged in #4507, will land in the next release.
