### ISSUE TITLE
Is it possible to add a JA3 field in CaddyServer?

### ISSUE THREAD

**Issue by yumusb** [caddyserver/caddy#4504]
Is it possible to add a JA3 field in CaddyServer? 

More information at https://github.com/salesforce/ja3

Thanks.

**Comment by francislavoie** [comment]
I'm not sure I understand. I tried to read the README of that repo, but it's not clear what you're asking for.

**Comment by yumusb** [comment]
JA3 can better identify the type of visitor. (Machine access or real person). So we can use this to manage access rights.

**Comment by mholt** [comment]
Sounds interesting, but that's not enough information to implement anything. We can read the page you linked and nod and say "yeah that's cool" but if you want something done about it, we'll need to know precisely what you're looking for. "field in Caddyserver" (the name is "Caddy", btw) doesn't make any sense.

**Comment by mysticaltech** [comment]
Folks, this is extremely important for bots identification. Cloudflare offers it only with its premium "Bot Management for Enterprise" plan. See https://developers.cloudflare.com/bots/concepts/ja3-fingerprint/

Now, for Go, it would be easy to implement because already done; see https://github.com/dreadl0ck/ja3/blob/master/ja3s.go, and also https://github.com/sleeyax/ja3rp.

**Comment by mysticaltech** [comment]
And this does a great job at it for nginx https://github.com/phuslu/nginx-ssl-fingerprint.

**Comment by mysticaltech** [comment]
For instance, I need the value returned with the requests as a header, and this seemed like the king of special treats that only caddy gives. But yeah, if you were to consider this again in the future as a plugin would be great.

**Comment by francislavoie** [comment]
It's very unlikely we'll spend effort building a plugin for this. But anyone can write one: https://caddyserver.com/docs/extending-caddy

**Comment by yumusb** [comment]
ok, i will try to write. Thanks.

**Comment by mysticaltech** [comment]
@yumusb Look at the links I posted above. It's probably straightforward enough.

**Comment by deancn** [comment]
@mysticaltech  Thanks for you like our nginx-ssl-fingerprint repo.

Can pay attention to the Golang TLS lib issue. Once the issue is processed, I think everything will be easy. :)
https://github.com/golang/go/issues/32936

**Comment by mysticaltech** [comment]
Good to know, thanks @deancn and keep up the good work! 🙏

**Comment by rushiiMachine** [comment]
I made a caddy plugin for this!
When go's `ClientHelloInfo` adds `raw` it should simplify it a lot though :)
https://github.com/rushiiMachine/caddy-ja3

**Comment by mholt** [comment]
@rushiiMachine Very cool!!

> When go's ClientHelloInfo adds raw it should simplify it a lot though

Oh yeah, I think I tracked that issue.

Feel free to share this on our forum as well :) https://caddy.community -- and you can register it on our website so it can appear on our Download page.

**Comment by yumusb** [comment]
> I made a caddy plugin for this! When go's `ClientHelloInfo` adds `raw` it should simplify it a lot though :) https://github.com/rushiiMachine/caddy-ja3


cool

**Comment by mysticaltech** [comment]
@rushiiMachine Super good to hear, well done, thank you! Was thinking of using the nginx plugin just 2 days ago, what a coincidence 🙏

**Comment by josuebrunel** [comment]
Inspired by @rushiiMachine , I implemented a **ja3** and **ja4** plugin https://github.com/josuebrunel/caddy-ja3ja4
