### ISSUE TITLE
Rebuild binaries with new Go releases?

### ISSUE THREAD

**Issue by ongardie** [caddyserver/caddy#4510]
I have a security-related question. Caddy leverages a lot of code from Go's standard library that gets compiled into the static binary releases, and Caddy is also compiled with the Go compiler. The Go compiler and standard library are updated frequently, sometimes with security fixes or enhancements. Are the Caddy release binaries rebuilt (either manually or automatically) when there is a new Go release? What's the policy around that? How, technically, does it happen?

In case anyone else is wondering, the `go version` command can be used to identify the version of the compiler used to build an executable like `caddy`. For example:
```
$ ./caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
$ go version ./caddy  
./caddy: go1.17.5
```
This low-tech approach also seems to work for me, but YMMV:
```
$ strings ./caddy | grep ^go1 
go1.17.5
```

Thanks for developing Caddy!

**Comment by mholt** [comment]
I generally keep the build server updated (powering our download page) to always use the latest Go version, especially after relevant security releases, but today's release of 1.17.6 doesn't appear to be one of those so I haven't done so yet.

If you don't have Go installed, you can still get Caddy's Go version with `caddy build-info`:

```
$ caddy build-info
go_version: go1.17.5
go_os:      linux
go_arch:    amd64
path:       caddy
main:       caddy (devel) 
dependencies:
...
```

We can implement stronger dependency chain guarantees for higher-tier sponsors: https://github.com/sponsors/mholt

**Comment by ongardie** [comment]
Thanks for your quick reply, @mholt! That's good to know. If the build server is updated to a new Go release, does it generate new Caddy binaries right away or does it block until a new Caddy release?

**Comment by francislavoie** [comment]
Builds are cached, usually Matt will wipe the cache when upgrading versions if it's relevant from a security standpoint. From then on any requested build will build with the latest version.

**Comment by ongardie** [comment]
Gotcha, thanks @francislavoie.
