### ISSUE TITLE
Docs: please document how to migrate the `without` subdirective

### ISSUE THREAD

**Issue by simon04** [caddyserver/caddy#4512]
https://caddyserver.com/docs/v2-upgrade#proxy

> The `without` subdirective has been removed because rewrite hacks are no longer necessary in v2 thanks to improved matcher support.

I could not figure out how to migrate the following snippet from v1 to v2

```
proxy /prefix/ https://example.com/ {
    without /prefix
}
```

**Comment by mholt** [comment]
The words "rewrite hacks" are a link to how to perform rewrites in v2.

You can strip path prefixes using the `uri` directive: https://caddyserver.com/docs/caddyfile/directives/uri

Or `handle_path` which does this implicitly for you: https://caddyserver.com/docs/caddyfile/directives/handle_path

Hope that helps!
