### ISSUE TITLE
Feature Request: Add method subdirective to caddy file

### ISSUE THREAD

**Issue by zjean** [caddyserver/caddy#4523]
As stated [here](https://caddy.community/t/v2-rewrite-get-as-post-request/7252) it looks like the subdirective `method` is not yet available in Caddy v2 to be used in the Caddyfile.
Any plans on implementing it?

**Comment by francislavoie** [comment]
I opened a PR to add this #4528 

Nobody's asked for it since that issue you linked to, but it's extremely simple to implement so I went ahead and did it.

You can build from the PR branch and give it a shot!
