### ISSUE TITLE
caddy fmt overwrite should emit an error message

### ISSUE THREAD

**Issue by bt90** [caddyserver/caddy#4524]
Currently `caddy fmt --overwrite` fails rather silently if the file couldn't be modified:

```
user@vm:$ caddy fmt --overwrite /etc/caddy/Caddyfile
user@vm:$ echo $?
1
```

Could we add an error message? This would also follow other unix tools:

```
user@vm:$ mkdir /data
mkdir: cannot create directory '/data': Operation not permitted
```

**Comment by mholt** [comment]
Good point, we don't print the error message currently. We should do that.
