### ISSUE TITLE
404 when browsing folder containing symlink

### ISSUE THREAD

**Issue by langchr86** [caddyserver/caddy#4526]
I use the `browse` feature to publish a folder with yocto artifacts. This folder contains subfolders with symlinks to various files in the same folder. If I want to open a folder which contains symlinks I get a 404. 

I am using docker image version: 2.4.6

My Caddyfile:
~~~~~~
yocto.localhost {
  root * /var/www/yocto
  file_server {
    browse
  }
}
~~~~~~

This can be reproduced by simply creating a folder which contains a symlink to e.g. a file:

~~~~~~
cd /var/www/yocto
mkdir test
cd test
touch file
ln -s file link
~~~~~~

We now get a 404 when browsing to `yocto.localhost/test`.

The docker image with version 2.4.5 still works.

Maybe connected with: https://github.com/caddyserver/caddy/issues/1660

**Comment by francislavoie** [comment]
I think this has already been fixed. Could you please try a build from the master branch?
