### ISSUE TITLE
How to enable access log?

### ISSUE THREAD

**Issue by sup-uo** [caddyserver/caddy#4527]
Caddy version:2.4.6

Below is my Caddy file, edited and reloaded caddy, but no log file was generated.
------------------------------------------
news.abc.com {
        log {
        output file /var/log/caddy/access.log
}
        redir  https://www.facebook.com/news/learn-more/
}
------------------------------------------

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
