### ISSUE TITLE
Cannot build caddy with nginx-adapter for windows

### ISSUE THREAD

**Issue by artknight** [caddyserver/caddy#4539]
<img width="1470" alt="Screen Shot 2022-01-20 at 2 37 11 PM" src="https://user-images.githubusercontent.com/157762/150409929-b97ca602-9650-412c-90c3-5af208135be0.png">

**Comment by francislavoie** [comment]
FYI @mohammed90

This issue should probably be on the https://github.com/caddyserver/nginx-adapter repo instead.

**Comment by artknight** [comment]
@francislavoie Thank you! I am wondering if there is a guide or something on how to logically convert from nginx config to caddy? I am using Lucee ColdFusion with nginx setup and I am really loving what I have been reading about caddy do I am very eager to try it but can't seem to find good documentation/ guide on how to convert my setup. Any ideas?

**Comment by mholt** [comment]
Everyone wants a tutorial but no one will write a tutorial :frowning_face: 

If you want a lot of traffic to your blog, I'd encourage you to write a guide about it! :wink:

**Comment by artknight** [comment]
@mholt lol, I will definitely share my process to save someone else the headaches.. but for now I am that someone else :(
