### ISSUE TITLE
How long before expiry does Caddy renew certificates that are about to expire ?

### ISSUE THREAD

**Issue by drtech981** [caddyserver/caddy#4543]
I need to setup a cron job to rsync the certs issued by caddy to another directory, I need to know how long before a certificate expires does caddy renew the certificates ?

**Comment by francislavoie** [comment]
After it reaches 2/3 of its lifetime, Caddy will start to attempt renewals. So right now with ACME certs having 90 day lifetimes, after 60 days, or 30 days remaining.
