### ISSUE TITLE
[Urgent] Let's Encrypt revocations affecting your TLS certificates

### ISSUE THREAD

**Issue by hferradj** [caddyserver/caddy#4548]
I just received this email from LetsEncrypt, informing me that all the certificates issued by my caddy server will be revoked on the 28th of January, at 16:00 UTC.

```
Please immediately renew your TLS certificate(s) that were issued from
Let's Encrypt using the TLS-ALPN-01 validation method and the following
ACME registration (account) ID(s):

 11*****3

We've determined that an error made it possible for TLS-ALPN-01
challenges, completed before today, to not comply with certificate
issuance requirements. We have remediated this problem and will revoke
all unexpired certificates that used this validation method at 16:00 UTC
on 28 January 2022. Please renew your certificates now to ensure an
uninterrupted experience for your site visitors.

We apologize for any inconvenience this may cause. If you need support
in the renewal process, please comment on our forum post. Our staff and
community members are available to help:

https://community.letsencrypt.org/t/170449

Thank you,

The Let's Encrypt Team
```

I have caddy version 2.2.1 and the certificates are stored with the dynamodb module.

I am unsure how to re-issue the certificates and am a bit worried as it's affecting clients' custom domains in production.

Here is what my caddy config file looks like:

```
{
  "storage": {
    "module": "dynamodb",
    "table": "odjo_caddy_ssl_certificates"
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
              "match": [
                {
                  "path": [
                    "/health"
                  ]
                }
              ],
              "handle": [
                {
                  "body": "Im healthy!",
                  "handler": "static_response",
                  "status_code": 200
                }
              ]
            }
          ]
        },
        "srv1": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "handle": [
                {
                  "handler": "reverse_proxy",
                  "headers": {
                    "request": {
                      "set": {
                        "Host": [
                          "example.com"
                        ],
                        "X-Forwarded-For": [
                          "{http.request.remote.host}"
                        ],
                        "X-Forwarded-Host": [
                          "{http.request.host}"
                        ],
                        "X-Forwarded-Port": [
                          "{server_port}"
                        ],
                        "X-Forwarded-Proto": [
                          "{http.request.scheme}"
                        ]
                      }
                    }
                  },
                  "health_checks": {
                    "active": {
                      "timeout": 5000000000
                    }
                  },
                  "transport": {
                    "protocol": "http",
                    "tls": {}
                  },
                  "upstreams": [
                    {
                      "dial": "example.com:443"
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    },
    "tls": {
      "automation": {
        "policies": [
          {
            "issuer": {
              "email": "me@example.com",
              "module": "acme",
              "challenges": {
                "http": {
                  "disabled": true
                }
              }
            },
            "on_demand": true
          }
        ],
        "on_demand": {
          "ask": "https://example.com/system/caddy-domain-authorization-path"
        }
      }
    }
  },
  "logging": {
    "logs": {
      "": {
        "level": "INFO"
      }
    }
  }
}
```

Thank you

**Comment by mholt** [comment]
Caddy v2.4.2 and newer will automatically replace certificates that get revoked.

Easiest thing for you to do is just upgrade Caddy, and keep it up-to-date (after proper testing of course)!

**Comment by francislavoie** [comment]
> I have caddy version 2.2.1 and the certificates are stored with the dynamodb module.

Upgrade Caddy ASAP, versions of Caddy before 2.4.2 would not correctly automatically renew revoked certificates. See here for more details: https://community.letsencrypt.org/t/questions-about-renewing-before-tls-alpn-01-revocations/170449/21

Once you've updated, you won't need to take any action.

**Comment by hferradj** [comment]
Thank you so much :)

**Comment by sphr2k** [comment]
Unfortunately, this does not seem to work reliably. Two servers (Caddy v2.4.6) did not correctly recognize revoked certificates that need to be renewed.

**Comment by gbhrdt** [comment]
Same for me. Caddy 2.4.6 did not automatically renew revoked certificates.

**Comment by francislavoie** [comment]
@sphr2k @gbhrdt We'll need more details. Could you share your logs? How did you notice the problem?

**Comment by mholt** [comment]
It can take up to 4 days for the revocation to be recognized as it has to wait for the OCSP Staple to be halfway through its validity period. The cert will be acceptable until the Good OCSP response expires.

**Comment by b-reich** [comment]
> @sphr2k @gbhrdt We'll need more details. Could you share your logs? How did you notice the problem?

Firefox give you an error, that die cert is not longer valid.

**Comment by bmichotte** [comment]
As a workaround, I had to delete the files in `/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory` and restart caddy

**Comment by gbhrdt** [comment]
> @sphr2k @gbhrdt We'll need more details. Could you share your logs? How did you notice the problem?

Unfortunately I can not provide any logs as the Kubernetes Pod has already been removed. When it appears next time I will provide logs.

We noticed the problem when customers complained that opening their sites in Chrome, Firefox etc. yields SSL errors (cert revoked).

We solved it by removing the certificates from letsencrypt, they temporarily increased our rate limit after asked in the Community forums.

**Comment by francislavoie** [comment]
> Unfortunately I can not provide any logs as the Kubernetes Pod has already been removed.

You should probably persist/roll your logs somewhere in that case. That's not great.

**Comment by mholt** [comment]
Without logs, all we can do is guess, unfortunately.

**Comment by gbhrdt** [comment]
I just saw the latest CertMagic upgrade, as we are also Using OnDemand mode, I guess it might solve our issue in the next release: https://github.com/caddyserver/caddy/commit/599c81d753a1af8ffbb6d733321cc76f170c41e4

**Comment by mholt** [comment]
@gbhrdt Maybe. The comments on the commit suggest that there's still a bug (because I wrote the patch around midnight when I was way too tired, but I tried): https://github.com/caddyserver/certmagic/commit/9245be5a2f16135b9de55567682f49a2d343e1f0

**Comment by mholt** [comment]
This PR might have more luck: https://github.com/caddyserver/certmagic/pull/166

**Comment by sphr2k** [comment]
> @sphr2k @gbhrdt We'll need more details. Could you share your logs? How did you notice the problem?

I checked all our LE certificates which use the tls-apln-01. Here are our logs:

[caddy.log](https://github.com/caddyserver/caddy/files/7979049/caddy.log)

As you can see, the cert for the `mta-sts` subdomain was automatically replaced; for the `send` subdomain, I had to delete the existing cert to force caddy to issue a new one.

**Comment by mholt** [comment]
All known revocation-related issues with certs not getting renewed should be fixed in CertMagic v0.15.3: https://github.com/caddyserver/certmagic/releases/tag/v0.15.3

This has been tested in production with thousands of domains and is known to work.

Honestly, this feature was just a party trick (I still don't know of any other server that even tries to auto-renew revoked certificates) and it was just tricky to get it right to work in more intensive use cases.

**Comment by owenconti** [comment]
Hi @mholt, please forgive my dumb question:

What can I do to get CertMagic 0.15.3 running on my Caddy servers?

**Comment by mholt** [comment]
@owenconti Just build Caddy from the latest commit. You might find https://github.com/caddyserver/xcaddy helpful.

**Comment by owenconti** [comment]
@mholt ah, I didn't realize it was already updated in the Caddy repo. I'll try out the custom build now.

Is there an ETA for 2.4.5?

**Comment by mholt** [comment]
I hope to tag a pre-release of 2.5 this month :crossed_fingers:
