### ISSUE TITLE
Unable to acquire lock for localhost on Mac Monterey

### ISSUE THREAD

**Issue by tgadam** [caddyserver/caddy#4552]
I'm new to caddy so I apologize in advance if this issue is not in the correct format. Furthermore this is one of those pesky issues that I can't reliably reproduce but maybe someone else will have an idea how to fix it without needing the workaround I had to use.

When running caddy reverse-proxy after a fresh install via Homebrew on macOs Monterey and trying to use a higher port number in my case 3000 (for example `caddy reverse-proxy --from localhost:3000 --to localhost:3443`), I got an error:

```
2022/01/28 16:28:45.833	ERROR	tls	job failed	{"error": "localhost: obtaining certificate: unable to acquire lock 'issue_cert_localhost': decoding lockfile contents: EOF"}
```

After digging around in the storage unit folder locks directory (`/Users/adamt/Library/Application Support/Caddy/locks`), I saw a lock file. After deleting the lock file, and I re-ran the command it worked.

I'm unsure why this lockfile got generated and caused issues but I know it took me quite a while to figure out how to "fix" the issue. 

Below is the full log from the run and re-run that finally fixed it.
```
Adams-Teselagen-MacBook-Pro:~ adamt$ caddy reverse-proxy --from localhost:3000 --to localhost:3443
2022/01/28 16:28:45.672	WARN	admin	admin endpoint disabled
2022/01/28 16:28:45.673	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "proxy"}
2022/01/28 16:28:45.674	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc0003fe000"}
2022/01/28 16:28:45.829	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
2022/01/28 16:28:45.831	INFO	http	enabling automatic TLS certificate management	{"domains": ["localhost"]}
2022/01/28 16:28:45.832	INFO	autosaved config (load with --resume flag)	{"file": "/Users/adamt/Library/Application Support/Caddy/autosave.json"}
Caddy proxying https://localhost:3000 -> http://localhost:3443
2022/01/28 16:28:45.832	INFO	tls	cleaning storage unit	{"description": "FileStorage:/Users/adamt/Library/Application Support/Caddy"}
2022/01/28 16:28:45.832	INFO	tls	finished cleaning storage units
2022/01/28 16:28:45.832	INFO	tls.obtain	acquiring lock	{"identifier": "localhost"}
2022/01/28 16:28:45.833	ERROR	tls	job failed	{"error": "localhost: obtaining certificate: unable to acquire lock 'issue_cert_localhost': decoding lockfile contents: EOF"}
^C2022/01/28 16:29:24.246	INFO	shutting down	{"signal": "SIGINT"}
2022/01/28 16:29:24.247	WARN	exiting; byeee!! 👋	{"signal": "SIGINT"}
2022/01/28 16:29:24.250	INFO	tls.cache.maintenance	stopped background certificate maintenance	{"cache": "0xc0003fe000"}
2022/01/28 16:29:24.251	INFO	shutdown complete	{"signal": "SIGINT", "exit_code": 0}
```

After deleting the lock file `issue_cert_localhost.lock`, then I re-ran and it worked:

```
Adams-Teselagen-MacBook-Pro:~ adamt$ caddy reverse-proxy --from localhost:3000 --to localhost:3443
2022/01/28 16:34:17.205	WARN	admin	admin endpoint disabled
2022/01/28 16:34:17.205	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "proxy"}
2022/01/28 16:34:17.205	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc000436000"}
2022/01/28 16:34:17.205	INFO	tls	cleaning storage unit	{"description": "FileStorage:/Users/adamt/Library/Application Support/Caddy"}
2022/01/28 16:34:17.205	INFO	tls	finished cleaning storage units
2022/01/28 16:34:17.344	INFO	pki.ca.local	root certificate is already trusted by system	{"path": "storage:pki/authorities/local/root.crt"}
2022/01/28 16:34:17.344	INFO	http	enabling automatic TLS certificate management	{"domains": ["localhost"]}
2022/01/28 16:34:17.344	INFO	autosaved config (load with --resume flag)	{"file": "/Users/adamt/Library/Application Support/Caddy/autosave.json"}
Caddy proxying https://localhost:3000 -> http://localhost:3443
2022/01/28 16:34:17.345	INFO	tls.obtain	acquiring lock	{"identifier": "localhost"}
2022/01/28 16:34:17.367	INFO	tls.obtain	lock acquired	{"identifier": "localhost"}
2022/01/28 16:34:17.372	INFO	tls.obtain	certificate obtained successfully	{"identifier": "localhost"}
2022/01/28 16:34:17.372	INFO	tls.obtain	releasing lock	{"identifier": "localhost"}
2022/01/28 16:34:17.372	WARN	tls	stapling OCSP	{"error": "no OCSP stapling for [localhost]: no OCSP server specified in certificate"}
```

**Comment by francislavoie** [comment]
If you hard-killed Caddy (not a graceful shutdown) then it probably wasn't able to clean up the lock due to being in a bad state. We've made some fixes that are on the master branch to try and address this, it'll be included in the next release.

Removing the lock if it's stuck is the solution. But try to avoid killing Caddy without letting it shut down gracefully first.

**Comment by tgadam** [comment]
When you run `caddy reverse-proxy` from the command line how do you gracefully shutdown? I was just doing `Ctrl-C`

Also prior to running it on the higher port I tried running it on 443 and it immediately exited. I'm not sure if that exit was graceful.

**Comment by mholt** [comment]
The weird thing about these errors is the _empty_ lock file. Caddy lock files have JSON in them. So if they're empty, yeah, maybe a force-quit at just the wrong time...

**Comment by francislavoie** [comment]
By "force quit" I mean maybe shutting off your machine while Caddy was running or the system doing a SIGKILL or whatever. But yeah `Ctrl+C` (SIGTERM) is the right thing to do to do a graceful shutdown.

Anyways I don't really see anything actionable here, so I'll close this for now. If you see it happen again, please let us know.
