### ISSUE TITLE
`caddy fmt` won't overwrite Caddyfile with `--overwrite` flag

### ISSUE THREAD

**Issue by jant90** [caddyserver/caddy#4556]
When running `caddy fmt Caddyfile --overwrite` the prettified Caddyfile is printed to stdout but the Caddyfile is not actually overwritten.

**Comment by mohammed90** [comment]
The order of the command arguments isn't interchangeable. `--overwrite` may be present immediately after `fmt` or not, and then followed by the file path.
```
  caddy fmt [--overwrite] [<path>]
```
When you run `caddy fmt Caddyfile --overwrite`, the absence of `--overwrite` after `fmt` means the provided argument is to the path of the file, and it will ignore the last argument. The correct usage is `caddy fmt --overwrite Caddyfile`. Run `caddy help fmt` for the usage instructions.
