### ISSUE TITLE
multiple tls hostless server blocks support

### ISSUE THREAD

**Issue by binary-person** [caddyserver/caddy#4557]
whenever I try to have more than one tls hostless server block, the following error is thrown
```
adapt: cannot make a TLS automation policy from a server block that has a host-less address when there are other TLS-enabled server block addresses lacking a host
```

What is the reason behind disallowing more than one hostless server block?

Caddyfile:
```
{
  auto_https disable_redirects
  on_demand_tls {
    ask http://127.0.0.1:12345
  }
}

https://:443 {
  tls {
    on_demand
  }
  reverse_proxy 127.0.0.1:8080
}

https://:8443 {
  tls {
    on_demand
  }
  reverse_proxy 127.0.0.1:8081
}

http:// {
  respond / "server ok" 200
}
```

**Comment by mholt** [comment]
The code comments explain this as best I could at the time of writing this logic, in `tlsapp.go`:

```go
// first make sure this block is allowed to create an automation policy;
// doing so is forbidden if it has a key with no host (i.e. ":443")
// and if there is a different server block that also has a key with no
// host -- since a key with no host matches any host, we need its
// associated automation policy to have an empty Subjects list, i.e. no
// host filter, which is indistinguishable between the two server blocks
// because automation is not done in the context of a particular server...
// this is an example of a poor mapping from Caddyfile to JSON but that's
// the least-leaky abstraction I could figure out
if len(sblockHosts) == 0 {
	if serverBlocksWithTLSHostlessKey > 1 {
		// this server block and at least one other has a key with no host,
		// making the two indistinguishable; it is misleading to define such
		// a policy within one server block since it actually will apply to
		// others as well
		return nil, warnings, fmt.Errorf("cannot make a TLS automation policy from a server block that has a host-less address when there are other TLS-enabled server block addresses lacking a host")
	}
	if catchAllAP == nil {
		// this server block has a key with no hosts, but there is not yet
		// a catch-all automation policy (probably because no global options
		// were set), so this one becomes it
		catchAllAP = ap
	}
}
```

**Comment by francislavoie** [comment]
The question would be - why do you need two different ports? What runs on your upstream `:8081` port? Can you use request matchers in Caddy make it proxy to the right upstream? For example if the `:8081` upstream is for websockets, you can use a request matcher in your `:443` site to check headers to see if it's a websocket, and proxy it to the right backend.

**Comment by binary-person** [comment]
You are right, in that websocket scenario. However, there are other use cases that may require this kind of set up.

So because you cannot make two tls server blocks because of two tls automation policies, can you disable tls automation policy for one particular server block? (so user requests 443, caddy gets cert, then tls for 8443 works)

**Comment by mholt** [comment]
Sorry, I don't really understand your question. "Server blocks" from the Caddyfile don't exist in the JSON config.

**Comment by binary-person** [comment]
I'm talking about the server block here

> cannot make a TLS automation policy from a server block

In other words, can you disable the TLS automation policy specifically for port 8443, but have it use the tls certificates issued by port 443, so that this error can be avoided?

**Comment by mholt** [comment]
All "server blocks" already use the "same certificates." The problem is the Caddyfile does not map in an obvious way to the JSON in this situation, as the code comment explains. Try adapting a working Caddyfile to JSON and you'll see the difficulty.

**Comment by binary-person** [comment]
i see. miraculously, if i edit it in its json form, it doesn't complain about it at all. i guess i'll work with that approach from now on

**Comment by binary-person** [comment]
tls ondemand works for both port 443 and 8443 with the edited json.

As a helpful note to anyone working on a similar setup, you need to first adapt it to json (with one tls server block), then add in another `srv3` for your second tls server

**Comment by mholt** [comment]
> I see. miraculously, if i edit it in its json form, it doesn't complain about it at all. 

Yep, because using JSON directly takes the guesswork out of ambiguous conversions from the Caddyfile.

As always, using the native JSON config is sometimes the only way to achieve advanced or niche configurations. (Even if the Caddyfile can get you 90% of the way there.) Glad you figured it out!
