### ISSUE TITLE
feature: import/include statements in apps

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#4559]
@francislavoie , per our preliminary discussion in relationship to this https://github.com/greenpau/caddy-security/issues/45#issue-1122669395.

In short, a user has the following requirements:
1. ability to use `import` statements in apps
2. ability to "include"/"imbed" snippets from filesystem in the way described below

Currently, the `security` app [configurations](https://github.com/authp/authp.github.io/tree/main/assets/conf) follow the following format for `site1` through `siteN`. It becomes a very long, repeated config when dealing with a large number of sites.

```
{
	security {
		authentication portal site1_portal {
			...
		}

		authentication portal siteN_portal {
			...
		}

		authorization policy site1_guests_policy {
			...
		}

		authorization policy site1_users_policy {
			...
		}

		authorization policy siteN_guests_policy {
			...
		}

		authorization policy siteN_users_policy {
			...
		}
	}
}
```

The `authorization policy` configurations variate slightly. 

Per point 1, it would be great to be able to `import` snippets.

Per point 2, say I maintain a directory with all `authentication portal`. 

```
$ tail tmp/portals/*
==> tmp/portals/site1.config <==
authentication portal site1_portal {
  ...
}

==> tmp/portals/site2.config <==
authentication portal site2_portal {
  ...
}
```

and all `authorization policy`:

```
$ tail tmp/policies/*
==> tmp/policies/site1.config <==
authorization policy site1_users_policy {
  ...
}

==> tmp/policies/site2.config <==
authorization policy site2_users_policy {
  ...
}
```

I want to include/embed the portals and policies this way:

```
{
	security {
		include tmp/portals/*.config
		include tmp/policies/*.config
	}
}
```

---

Side note: perhaps I could add plugin-specific `include` and `snippet` directives 🤔 But I don't know how to best accomplish this from within an app. Also, I also don't know whether Caddyfile directives will make it through to JSON-based configs.

**Comment by francislavoie** [comment]
Actually I just tested this out and it works :thinking: 

Caddyfile adapt:
```
(snippet) {
	debug
}

{
    import snippet
}
```

Outputs this JSON:
```json
{"logging":{"logs":{"default":{"level":"DEBUG"}}}}
```

And this Caddyfile:

```
{
    import separate-file.txt
}
```

Where `separate-file.txt` is:

```
debug
```

Also outputs this JSON:
```json
{"logging":{"logs":{"default":{"level":"DEBUG"}}}}
```

So I think this is already working fine?

**Comment by greenpau** [comment]
@francislavoie , thank you for looking into this 👍 We will test and circle back, if running into issues.

**Comment by greenpau** [comment]
Works like a charm! 😄
