### ISSUE TITLE
Difficulty with using caddy with a server that serves both GRPC & HTTP

### ISSUE THREAD

**Issue by asalatkamal** [caddyserver/caddy#4560]
Hi!
I am having trouble with putting caddy in front of a server that is serving both http & grpc on a port.
With just grpc, it's working fine, but the minute I introduce http, I get bad gateway 502. What changes are necessary in the caddy file to support this or is it impossible?

**Comment by francislavoie** [comment]
I think grpc requires h2c (HTTP/2 over HTTP). You can configure your upstream with the `h2c://` scheme to enable this.

If you need further help, please ask your questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
