### ISSUE TITLE
Caddy API returns a 500 when trying to POST/GET an `id` that does not exist

### ISSUE THREAD

**Issue by Cpaczek** [caddyserver/caddy#4561]
As you can see here:
![image](https://user-images.githubusercontent.com/25715982/152636777-2a291eb4-9c1a-4fd2-91cd-3225606bd1e1.png)

Caddy is returning a 500 when trying to get an ID that does not exist.  This should be a 404 instead of a 500. We are trying to make a k8 operator which has a CreateOrUpdate function for specific routes meaning we need to check if an ID exists. It would be nice to have  404 instead of a 500.

**Comment by mholt** [comment]
Good idea. The `handleConfigID` handler could probably be modified to return `APIError` structs which specify the status code, rather than naked error values.
