### ISSUE TITLE
Cannot access to https://caddy.community

### ISSUE THREAD

**Issue by lefuturiste** [caddyserver/caddy#4562]
With firefox: Error with ssl
![image](https://user-images.githubusercontent.com/20988163/152647361-db6ddac0-0a23-4cb4-b9b2-d45ce6b3dcff.png)

With chromium: timeout

**Comment by francislavoie** [comment]
It's loading fine for me.

**Comment by mholt** [comment]
If you continue to have issues accessing it (from multiple ISPs) please let us know again.

**Comment by lefuturiste** [comment]
> If you continue to have issues accessing it (from multiple ISPs) please let us know again.

So I tried on another ISP and it worked fine. So I guess it's my ISP (mobile network). So weird. And it's reported as an HTTPS error, sometime as a timeout.

**Comment by francislavoie** [comment]
Still works fine for me, both on wifi and cellular :man_shrugging:
