### ISSUE TITLE
Add Markdown documentation

### ISSUE THREAD

**Issue by izzues** [caddyserver/caddy#4563]
Hey, thanks for the awesome project!

I'm interested in using Markdown as described [here](https://caddyserver.com/docs/caddyfile/directives/templates) and I'd like to know a little more about things like:

- What Markdown "dialects" are supported and what is the default? (What syntax constructs are supported?)
- Is it configurable at all?

Thanks  again!

**Comment by francislavoie** [comment]
> What Markdown "dialects" are supported and what is the default?

Caddy uses https://github.com/yuin/goldmark, so CommonMark, plus Github Flavored, plus footnotes, plus syntax highlighting (which uses Chroma https://github.com/alecthomas/chroma, so any of those languages).

> Is it configurable at all?

Not currently. What would you need to configure?

**Comment by izzues** [comment]
> What would you need to configure?

Thanks for the quick reply, that's a very satisfying answer for my use case already!

Other users might want to know whether you can disable or customize features (for instance, disable footnotes and use some alternative table syntax) and add plugins (to manipulate the AST). It would be helpful to know even if the docs just said "you can't do any of these". Just a few suggestions, though. Thanks again!

**Comment by izzues** [comment]
I just saw your PR with comments in a Go file. It would be nice to have that info on the website as well!

**Comment by francislavoie** [comment]
It is on the website: https://caddyserver.com/docs/modules/http.handlers.templates

It's the first link on the `templates` directive page. But I'll make that link more prominent.

**Comment by izzues** [comment]
Oops, sorry then, I wasn't not familiar with how this works. Really nice, though! Thanks again!
