### ISSUE TITLE
Remote_ip gets local ipv6 adresses with %eth0 (zone_id) but can't handle it

### ISSUE THREAD

**Issue by BitWuehler** [caddyserver/caddy#4567]
Hello together,
I run caddy in a docker container on a raspberry pi. At the moment i run it in the host network, because in a bridge network I got the docker ip back and that I can’t use to restrict access from out of the local network.
My caddy version is: 2.4.6

Thats the relevant part of my Caddyfile:
```
pihole.{$DOMAIN}:443 {
  tls {$EMAIL}
  @internalv6 {
    remote_ip fe80::/64
  }
  handle @internalv6 {
    uri replace / /admin/ 1
    reverse_proxy 192.168.178.3:81
  }
```
If I use it, I get this error back. Nothing else in the log in debug mode from interesst:
```
{"level":"error","ts":1644497213.9798095,"logger":"http.matchers.remote_ip","msg":"getting client IP","error":"invalid client IP address: fe80::9457:35e3:3b21:173e%eth0"}
```

Seems like caddy can't handle zone ids, but it is a normal behavior in `Scoped link local IPv6 addresses`. I found no way to disable the `zone_id`.
I have to mention, that I adressed the local adresses of the raspberry in my homenetwork with pihole, otherwise I accessed caddy with the global ipv6, what obviosly not works.

**Comment by BitWuehler** [comment]
Made my first pull request for the problem. Hopefully its good how I made. #4571

**Comment by mholt** [comment]
Thank you for your contribution!
