### ISSUE TITLE
Make `templates` pluggable

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4568]
Context: https://caddy.community/t/including-files-scripts/15050/4

Right now, the `templates` module is inflexible in that only functions the functions registered by Caddy itself are available.

A good refactor would be to make it possible to pass an optional array of modules in the `http.handlers.templates.functions.*` namespace which get invoked at `Provision()` time to register additional functions.

**Comment by Angg4r4** [comment]
Saya  sebagai pemula, bisakah untuk membantu saya membuat respon proxy yang tersedia di templat #4000 
[github-recovery-codes (3).txt](https://github.com/caddyserver/caddy/files/8563566/github-recovery-codes.3.txt)

**Comment by kroppt** [comment]
I am interested in working on this.

The `TemplateContext` is responsible for parsing and executing templates. It knows which functions are valid. It's a part of the `http.handlers.templates` module. That module then must get custom functions at `Provision` time for hand-off to that context.

Modules would be defined under `http.handlers.templates.functions` (e.g. `http.handlers.templates.functions.bash`) which allows for a definition of how to execute the function (e.g. call exec.Command with bash and the script filepath). Adding new function types can be done by adding a module under `http.handlers.templates.functions.*`, which can be added to a server as a Caddy plugin.

Is my understanding of the problem correct?

**Comment by francislavoie** [comment]
Yep, that's right!

I think you can use `caddy.GetModules("http.handlers.templates.functions")` to fetch a list of all the registered modules in that namespace, and if they conform to the right interface, you can load them in. 

https://github.com/caddyserver/caddy/blob/af7321511c960120d61cfd22e031f43071d5a9c2/modules.go#L202

That way, plugging in new functions would be zero-config, they would just added in if they're registered.

**Comment by mholt** [comment]
FYI for future searchers, this is probably being superseded by #5939.
