### ISSUE TITLE
Import snippet not working after bind

### ISSUE THREAD

**Issue by eslym** [caddyserver/caddy#4570]
Caddy Version: v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=

```
engshun@SHUN-LAPTOP:/etc/caddy$ cat Caddyfile
bind 127.0.0.1

(default_errors) {
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
    }
}

http:// {
        error * 418
        import default_errors
}
engshun@SHUN-LAPTOP:/etc/caddy$ caddy validate
2022/02/11 06:52:49.259 INFO    using adjacent Caddyfile
validate: adapting config using caddyfile: Caddyfile:11 - Error during parsing: File to import not found: default_errors
engshun@SHUN-LAPTOP:/etc/caddy$ 
```
but if i remove the bind
```
engshun@SHUN-LAPTOP:/etc/caddy$ cat Caddyfile
(default_errors) {
    handle_errors {
        respond "{http.error.status_code} {http.error.status_text}"
    }
}

http:// {
        error * 418
        import default_errors
}
engshun@SHUN-LAPTOP:/etc/caddy$ caddy validate
2022/02/11 06:53:23.044 INFO    using adjacent Caddyfile
2022/02/11 06:53:23.047 WARN    input is not formatted with 'caddy fmt' {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
2022/02/11 06:53:23.047 INFO    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server     {"server_name": "srv0", "http_port": 80}
2022/02/11 06:53:23.047 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0000c8000"}
2022/02/11 06:53:23.047 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc0000c8000"}
Valid configuration
engshun@SHUN-LAPTOP:/etc/caddy$ 
```

**Comment by francislavoie** [comment]
`bind` is a directive, it must go within a site block.

https://caddyserver.com/docs/caddyfile/concepts#structure

**Comment by eslym** [comment]
> `bind` is a directive, it must go within a site block.
> 
> https://caddyserver.com/docs/caddyfile/concepts#structure
> 
> The reason you get that specific error is because Caddy reads `bind` and `127.0.0.1` as being your site addresses (domain names), which means anything that follows is read as being part of that site block, but it's not valid to define a snippet _inside_ of a site block, so it breaks.

why cant globaly bind to only 1 ip? i need to have different instance bound to different ip on local for testing purpose, i checked on the cli there is no options to only listen to specific ip also

**Comment by mohammed90** [comment]
> > `bind` is a directive, it must go within a site block.
> > 
> > https://caddyserver.com/docs/caddyfile/concepts#structure
> > 
> > The reason you get that specific error is because Caddy reads `bind` and `127.0.0.1` as being your site addresses (domain names), which means anything that follows is read as being part of that site block, but it's not valid to define a snippet _inside_ of a site block, so it breaks.
> 
> why cant globaly bind to only 1 ip? i need to have different instance bound to different ip on local for testing purpose, i checked on the cli there is no options to only listen to specific ip also
> 
> **Update**
> i tested, if I want caddy only listen to specific ip then i will need to add bind to **every single site block**, this is very inconvenient

There will be `default_bind` global option in the Caddyfile in the next release. Implemented by @francislavoie in #4531.

**Comment by eslym** [comment]
> > > `bind` is a directive, it must go within a site block.
> > > https://caddyserver.com/docs/caddyfile/concepts#structure
> > > The reason you get that specific error is because Caddy reads `bind` and `127.0.0.1` as being your site addresses (domain names), which means anything that follows is read as being part of that site block, but it's not valid to define a snippet _inside_ of a site block, so it breaks.
> > 
> > 
> > why cant globaly bind to only 1 ip? i need to have different instance bound to different ip on local for testing purpose, i checked on the cli there is no options to only listen to specific ip also
> > **Update**
> > i tested, if I want caddy only listen to specific ip then i will need to add bind to **every single site block**, this is very inconvenient
> 
> There will be `default_bind` global option in the Caddyfile in the next release. Implemented by @francislavoie in #4531.

thanks, but i will be more glad if it is in the documentation

**Comment by francislavoie** [comment]
It will be with the release of v2.5.0

**Comment by bcookatpcsd** [comment]
Hey there.. 

Random human here.. sorry to necrobump.. 

https://caddyserver.com/docs/caddyfile/options#default-bind

Just spent a bunch of time trying to figure out why this doesn't work.. 

Nothing says.. "coming in 2.5.0" on the official docs.. 

The commit reads:

https://github.com/caddyserver/caddy/pull/4531/commits/4326d7bc5274e61527d86215c5b6c87c05758c2f

default_bind tcp4/0.0.0.0

that syntax is also not shown in the official docs.. 

Thank you for your time..

**Comment by francislavoie** [comment]
The commit where it was merged is https://github.com/caddyserver/caddy/commit/1b7ff5d76c7a3c67b6e0f9b51af78d1b227fdea3

The release notes https://github.com/caddyserver/caddy/releases/tag/v2.5.0-rc.1 do say:

> **Caddyfile:** [New `default_bind` global option](https://github.com/caddyserver/caddy/pull/4531) lets you specify the default interface all sockets should bind to.

Docs are currently not versioned, we did push the v2.5.0 changes to the docs site early. See https://github.com/caddyserver/website/issues/59
