### ISSUE TITLE
Consider shipping release tarball with vendored dependencies

### ISSUE THREAD

**Issue by illiliti** [caddyserver/caddy#4573]
For example, [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/vendor) does this by simply maintaining vendor directory. You can also setup CI to vendor dependencies into release tarball without needing to keep vendor directory within repository. Here is the command that can be used for this: `go mod vendor`

With vendored dependencies, i can build caddy from source without internet connection by using this command: `go build -mod=vendor`

**Comment by mholt** [comment]
I suppose we could do this, as long as it's only for a release asset.

**Comment by francislavoie** [comment]
This is done in https://github.com/caddyserver/caddy/pull/5403 :grinning: 

Sorry it took us so long, it was sorta tricky since we needed help from goreleaser upstream, then it just kinda fell off our TODO list.
