### ISSUE TITLE
Caddy 2.4.6 / Ubuntu 18.04 - Logging with Syslog, what facility, or how to route?

### ISSUE THREAD

**Issue by BlairMcClelland** [caddyserver/caddy#4575]
Hey guys, 

We are running Caddy 2.4.6 in a Linux VMs and are trying to get the logs output into Azure Log Analytics via rsyslog. I have added the facilities for all log levels for syslog, user, local0 through local7. And confirmed this via /etc/rsyslog.d/95-omsagent.conf

So far I have been able to confirm that the logs are going to /var/log/syslog, but have not been able to get these showing in Log Analytics. 

Is there something we are missing to get these running into say one of the local0-7 facilities?

```
{
	on_demand_tls {
		ask https://myaskapi.com/CaddyServer/VerifyDomainName
		interval 5s
		burst 5
	}
}

https:// {
	log
	tls {
		on_demand
	}
	reverse_proxy myreverseproxy.com {
		header_up Host {upstream_hostport}
		header_up X-Forwarded-Host {host}
	}
}

:8080 {
    respond "I am alive!" 200
}
```

Where the Caddy log message in var/log/syslog starts like..

```
Feb 15 03:32:31 caddyvm-vm-dev-1 caddy[3158]: {"level":"info","ts":1644895951.5908177,"logger":"http.log.access","msg":"handled request","request":{"remote_addr"
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
