### ISSUE TITLE
The config loader does not behave as expected

### ISSUE THREAD

**Issue by RussellLuo** [caddyserver/caddy#4577]
While trying the experimental [config loader](https://caddyserver.com/docs/json/admin/config/load/), I found some problems as below.

### 1. Dynamic config can only be loaded once.

With the following JSON config:

```json
{
	"admin": {
		"config": {
			"load_interval": "10s",
			"load": {
				"module": "http",
				"url": "http://localhost:8080/caddy-config"
			}
		}
	}
}
```

Here are the logs:

```bash
...
2022/02/16 13:00:39.536 INFO    dynamically-loaded config applied successfully
2022/02/16 13:00:39.536 INFO    reload config...
2022/02/16 13:00:39.536 INFO    stopping config load interval
...
```

Per the corresponding code:

https://github.com/caddyserver/caddy/blob/32aad909380f08a40389a33bfe788c8a35b1d850/caddy.go#L507-L513

The reason is obvious: the loading loop was terminated due to the cancel of ctx, which was triggered by the cleanup of old apps during the config reloading:

https://github.com/caddyserver/caddy/blob/32aad909380f08a40389a33bfe788c8a35b1d850/caddy.go#L285-L286

#### Possible solution

I think a possible solution is not to use `ctx.Done()` but to use a global channel (e.g. `stopCh`) instead for coordination. For example:

```go
// This group of variables pertains to the current configuration.
var (
	//...
	stopCh = make(chan struct{})  // added
)

// Stop stops running the current configuration.
// ...
func Stop() error {
	//...
	close(stopCh)  // added
	//...
}

// finishSettingUp should be run after all apps have successfully started.
func finishSettingUp(ctx Context, cfg *Config) error {
	//...
		if cfg.Admin.Config.LoadInterval > 0 {
			go func() {
				for {
					select {
					case <-timer.C:
						...
					case <-stopCh: // changed
						...
					}
				}
			}()
		}
	//...
}
```

### 2. `GET /config/` does not reflect the current config

With the initial JSON config mentioned above, we will get the following config even after the dynamic config is loaded:

```bash
$ curl localhost:2019/config/
{"admin":{"config":{"load":{"module":"http","url":"http://localhost:8080/caddy-config"},"load_interval":"10s"}}}
```

The reason is that `rawCfg` is not updated during reloading, which is fulfilled by using `unsyncedDecodeAndRun()`.

#### Possible solution

Maybe using `changeConfig()` instead of `unsyncedDecodeAndRun()` is the way to go:

```diff
- currentCfgMu.Lock()
- err := unsyncedDecodeAndRun(config, false)
- currentCfgMu.Unlock()
+ err := changeConfig(http.MethodPost, "/"+rawConfigKey, config, false)
```

As an additional benefit, no reloading will be triggered if there is no change in the config.

**Comment by mholt** [comment]
Hey thanks Russell.

What is the problem with (1), exactly? The timer is supposed to be stopped when the config is unloaded. Of course, if the new config also specifies dynamic loading, a new timer will be started.

As for (2), I will look into that more when I have more than a dashing second. Thank you again!

**Comment by RussellLuo** [comment]
> Of course, if the new config also specifies dynamic loading, a new timer will be started.

Oh, that's the point I was missing! I thought the dynamic loading mechanism is completely determined by the initial config. After enabling dynamic loading in the new config too, it works now. I think this is a clever and elegant design 💯 

BTW, is there any plan to add support for specifying dynamic reloading in Caddyfile?

**Comment by RussellLuo** [comment]
After some more thought, I'm afraid the timer is a little bit unnecessary in the current design, since the value from `<-ctx.Done()` will always be available after the old config is unloaded.

Therefore, if I'm not mistaken,  I think the current implementation:

https://github.com/caddyserver/caddy/blob/186fdba916a128fc2a837852d2ab04ac2efba413/caddy.go#L495-L516

may be functionally equivalent to the following simplified one?

```go
go func() {
	time.Sleep(time.Duration(cfg.Admin.Config.LoadInterval))
	loadedConfig, err := val.(ConfigLoader).LoadConfig(ctx)
	if err != nil {
		Log().Error("loading dynamic config failed", zap.Error(err))
		return
	}
	runLoadedConfig(loadedConfig)
}()
```

Please correct me if I'm wrong :)

**Comment by mholt** [comment]
If the config is reloaded before the timer or sleep expires, we need a way to cancel the timer or sleep. Sleep doesn't allow us to cancel it, meaning the goroutine will leak. The timer's channel API lets us select between that and a context's Done() channel to clean up the goroutine whether the timer expires or the config is reloaded, whichever comes first.

(I still need a moment to look into item (2) above.)

**Comment by RussellLuo** [comment]
Thanks for your kind explanation, Matt!

Now I think I understand the problem better — even though dynamic loading has been specified, it's still possible for users to change the config halfway by other means (e.g. via [API](https://caddyserver.com/docs/api)).

One more question here: is the `for {}` loop necessary? According to my understanding, I think maybe the first round is enough, since the send round — the case that the timer expired first — will always cancel the newly created timer and return immediately.

**Comment by mholt** [comment]
The [original change](https://github.com/caddyserver/caddy/pull/4246) didn't have a `for {}` loop. (See discussion in #4106.)

[After this discussion on the forum](https://caddy.community/t/how-does-load-interval-work/14202), I added the loop here: https://github.com/caddyserver/caddy/commit/7f364c777acfc1a0c8c3c62d9c3ad001fb1ea6df

But now that I look at it a second time, I'm not sure why a loop is necessary.

**Comment by RussellLuo** [comment]
> I am pretty sure it works without the loop. Would you have a chance to be able to verify?

Yes, I confirmed that it still works after I remove the `for {}` loop.

**Comment by RussellLuo** [comment]
Per the original problem on the forum:

> The configuration is never loaded again, after the initial load.

I think the root cause of the problem, as well as the current issue, is the misunderstanding of "dynamic loading". The feature is actually a **one-off dynamic loading** other than a **periodical dynamic reloading**, while the latter can be fulfilled by using a chaining mechanism — enabling "dynamic loading" in the new config.

**Comment by mholt** [comment]
I read "initial load" as the config loaded at startup, not the "first dynamic reload." So for some reason I assumed a loop was necessary. But it really doesn't make sense upon review.

**Comment by smebberson** [comment]
> The feature is actually a one-time dynamic loading other than a periodically dynamic reloading, while the latter can be fulfilled by using a chaining mechanism — enabling "dynamic loading" in the new config again.

@mholt and @RussellLuo, how is this achieved exactly?

Do I just need to make sure the following is present in the config that is loaded (using the forum example)?
```
"config": {
    "load_interval": "60s",
    "load": {
        "module": "http",
        "timeout": "10s",
        "url": "http://localhost:5000/caddy-config"
    }
}
```

**Comment by mholt** [comment]
@smebberson Yeah. Because when a new config is loaded, it replaces the old config. So if the new config doesn't specify a config loader, it will not load another config and thus stop the loop.

I wonder if it's too late to rename `load_interval` to `load_delay`. That might be more clear.

**Comment by smebberson** [comment]
Thanks. I think that name is much more appropriate.

**Comment by mholt** [comment]
@smebberson Done in bc447e3
