### ISSUE TITLE
Admin API: ETag on configuration

### ISSUE THREAD

**Issue by jhwz** [caddyserver/caddy#4578]
When updating Caddy configuration dynamically through the admin API, the usual flow for me is:
- Get the current configuration
- Figure out what changes need to be made to add this service to the config
- Make the changes and POST/PUT/PATCH them back to the Caddy API

This becomes an issue when multiple services are doing this at once, there is a chance for collisions. I would suggest adding an ETag header on the responses to GET requests. Initially, the ETag could just be the hash of the entire config but I guess you could compute the hash of sub-regions if there is a need.

This way, when an update is made you can optionally send the If-Match header to only apply the update if no changes have been made in the meantime and if a service receives 412 response, they know they need to re-fetch the config and try again.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#avoiding_mid-air_collisions

**Comment by mholt** [comment]
Thanks, I think this is a good suggestion.

**Comment by jhwz** [comment]
See https://github.com/caddyserver/caddy/pull/4579 for a basic implementation.

**Comment by mholt** [comment]
Forgot to close this; thanks for the cool new feature!
