### ISSUE TITLE
reverseproxy.go  just add HOST to http.Request.URL.Host

### ISSUE THREAD

**Issue by Wan9xy** [caddyserver/caddy#4595]
/modules/caddyhttp/reverseproxy/reverseproxy.go : fix If reverse_proxy upstream dial target is HTTP,when directRequest just add HOST to http.Request.URL.Host but no http.Request.Host,it makes when u have a proxy,but dial a DNS IP address.

**Comment by Wan9xy** [comment]
{ "admin": { "disabled": true }, "logging": { "logs": { "default": { "writer": { "output": "stderr" }, "level": "DEBUG" } } }, "apps": { "http": { "servers": { "hello": { "listen": [ "0.0.0.0:80" ], "routes": [ { "handle": [ { "handler": "rewrite", "uri": "/www.wan9.top/index.html" }, { "handler": "reverse_proxy", "transport": { "protocol": "http", "compression": false }, "upstreams": [ { "dial": "r78gkdchm.bkt.clouddn.com:80" } ], "headers": { "request": { "delete": [ "X-Forwarded-For", "X-Forwarded-Proto", "X-Forwarded-Port", "sec-fetch-site", "sec-fetch-mode", "sec-fetch-dest" ] } } } ] } ] } } } } }
It is my caddy‘s config,it can't work,upstream is google or baidu,it also,when i changed req.Host,it working
under my replay is the requset's log,Please have a look,thank u.

2022/02/24 02:07:54.813 DEBUG http.handlers.reverse_proxy upstream roundtrip {"upstream": "r78gkdchm.bkt.clouddn.com:80", "duration": 0.065652251, "request": {"remote_ip": "127.0.0.1", "remote_port": "61136", "proto": "HTTP/1.1", "method": "GET", "host": "0.0.0.0", "uri": "/www.wan9.top/index.html", "headers": {"User-Agent": ["PostmanRuntime/7.28.4"], "Postman-Token": ["1d1d723f-dbe6-4ace-b31d-f78d85978171"], "Accept": ["/"], "Accept-Encoding": ["gzip, deflate, br"], "X-Token": ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiZDBhMGRkNGMtMmFhNi00NTI0LWIxYmQtZGY0MDkwNjQ5NmQ1IiwiSUQiOjEsIlVzZXJuYW1lIjoiYWRtaW4iLCJOaWNrTmFtZSI6Iui2hee6p-euoeeQhuWRmCIsIkF1dGhvcml0eUlkIjoiMDAxIiwiQnVmZmVyVGltZSI6ODY0MDAsImV4cCI6MTY0NjAxMTk4MywiaXNzIjoicW1QbHVzIiwibmJmIjoxNjQ1NDA2MTgzfQ.SgUINL9ZgNAXRESDXvQyA2TDXhqlAVAmS5XdzIzTN_s"], "Want-To": ["tcp/r78gkdchm.bkt.clouddn.com:80"]}}, "headers": {"Server": ["openresty/1.13.6.2"], "Date": ["Thu, 24 Feb 2022 02:07:56 GMT"], "Content-Type": ["text/html"], "Content-Length": ["175"], "Connection": ["keep-alive"], "X-Error-Detail": ["domain not found"]}, "status": 404}

**Comment by francislavoie** [comment]
See https://github.com/caddyserver/caddy/pull/4594#issuecomment-1049485930
