### ISSUE TITLE
Change browse.html to use correct locale string

### ISSUE THREAD

**Issue by 12932** [caddyserver/caddy#4598]
For some reason, the current locale string for the date is hard-coded to American format.. why?

https://github.com/caddyserver/caddy/blob/186fdba916a128fc2a837852d2ab04ac2efba413/modules/caddyhttp/fileserver/browse.html#L458

This should be changed to use the browser's locale

**Comment by francislavoie** [comment]
What's the problem, exactly? According to the docs, that is what we're doing already.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#parameters

**Comment by 12932** [comment]
Unfortunately that doesn't seem to be the case on Google Chrome I have mine set to English (Australia), and it is sending the `accept-language` header like so `accept-language: en-AU,en;q=0.9,en-US;q=0.8` but still see the date in American format (MM/DD/YYYY), expected (DD/MM/YYYY). Reproducible in console aswell, so it may potentially be a bug or just not implemented in Chromium.

`Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)`

**Comment by francislavoie** [comment]
Looks like Chromium does have bugs: https://bugs.chromium.org/p/chromium/issues/list?q=tolocaledatestring+type%3Abug

So I don't think this is something we can really fix.
