### ISSUE TITLE
Gzip not working

### ISSUE THREAD

**Issue by oltreseba** [caddyserver/caddy#4604]
I'm trying to get gzip working and apparently i'm not able to do so.

I've tried these configurations:

```
sub.example.com {
  encode gzip zstd
  reverse_proxy http://127.0.0.1:18010
}
```

And 
```
sub.example.com {
 encode {
    gzip
    zstd
    minimum_length 0
    match {
    header Content-Type text/*
    header Content-Type application/json*
    header Content-Type application/javascript*
    header Content-Type application/xhtml+xml*
　 header Content-Type application/atom+xml*
    header Content-Type application/rss+xml*
    header Content-Type image/svg+xml*
    }
  }
  reverse_proxy http://127.0.0.1:18010
}
```

I've tried also other variations, but nothing seems to be working. The result is never compressed.

This is what i see from the inspector:
<img width="934" alt="Screenshot 2022-02-28 at 11 31 31 AM" src="https://user-images.githubusercontent.com/5563210/155967838-13663b43-d921-47c1-8aea-1f578834ab54.png">

Other info:
```
:~# caddy version
v2.4.1 h1:kAJ0JB5Xk5gPdTH/27S5cyoMGqD5lBAe9yZ8zTjVJa0=
```

We are using Debian 10.

**Comment by francislavoie** [comment]
Please upgrade to 2.4.6 and try again.

**Comment by oltreseba** [comment]
My bad, I added the encoding to the wrong server.

I confirm that everything is working as expected.
