### ISSUE TITLE
404 Being returned for basic file_server

### ISSUE THREAD

**Issue by ProjectInitiative** [caddyserver/caddy#4605]
Caddy 2.4.6

I have a basic HTTP server hosting some static files in /site/certs.

Caddyfile
```
http://IP, http://FQDN {
            root * /site/certs
            file_server browse
}
```

Everything works perfectly fine in 2.4.5. In 2.4.6, all requests return 404, when specifying the root path, or a direct path to a given file.

**Comment by ProjectInitiative** [comment]
Could possibly be related to changes made for https://github.com/caddyserver/caddy/pull/4407, but I am unsure.

**Comment by ProjectInitiative** [comment]
These are the two versions tested. I can try to directly from source.

v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
v2.4.5 h1:P1mRs6V2cMcagSPn+NWpD+OEYUYLIf6ecOa48cFGeUg=

**Comment by ProjectInitiative** [comment]
Building from source yields a 200 response code, but no file browser or direct paths

**Comment by ProjectInitiative** [comment]
I ended up trying on a new system clean build, everything works correctly, docker as well. Must have been a caching issue. Tried and compiled both versions and could not reproduce on the new system.

**Comment by mholt** [comment]
Ok. Thanks for thoroughly testing and for the update!
