### ISSUE TITLE
Despite auto_https is set to off Caddy seems to handle /.well-known/acme-challenge in a special way

### ISSUE THREAD

**Issue by tkaehn** [caddyserver/caddy#4612]
Despite auto_https is set to off Caddy seems to handle /.well-known/acme-challenge in a special way:
```
$ ./caddy version
v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=
```
```
$ cat Caddyfile 
{
	auto_https off
}

example.com:4433

tls crt.pem key.pem

respond "Hello World!"
```
```
$ ./caddy run
2022/03/04 18:22:38.632	INFO	using adjacent Caddyfile
2022/03/04 18:22:38.635	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2022/03/04 18:22:38.636	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0xc000226230"}
2022/03/04 18:22:38.637	WARN	tls	stapling OCSP	{"error": "no OCSP stapling for [example.com]: no OCSP server specified in certificate"}
[...]
2022/03/04 18:25:30.152	ERROR	tls.issuance.acme	looking up info for HTTP challenge	{"host": "example.com", "error": "no information found to solve challenge for identifier: example.com"}
2022/03/04 18:25:30.152	ERROR	tls.issuance.acme	looking up info for HTTP challenge	{"host": "example.com", "error": "no information found to solve challenge for identifier: example.com"}
```
The request and response:
```
GET /.well-known/acme-challenge/test HTTP/1.1
Host: example.com

HTTP/1.1 200 OK
Server: Caddy
Date: Fri, 04 Mar 2022 18:25:30 GMT
Content-Length: 12

Hello World!
```
```

**Comment by mholt** [comment]
I think things are working as expected. Even if Caddy isn't supposed to manage certificates for the sites defined in its config (that's what `auto_https` off means), it needs to be able to solve ACME challenges as part of a cluster.

If the log messages are what you're concerned about, you can disregard them in this case. They're harmless, just informational. (But we don't know whether it's an actual _error_ or just informational/debugging, so we print them at error level to be safe. Only the user can determine whether attention is actually warranted.)

**Comment by tkaehn** [comment]
Thanks for the info. I was indeed concerned about the error log. Because in my case there is no need to handle /.well-known/acme-challenge in a special way.
