### ISSUE TITLE
Proposal: About log level control

### ISSUE THREAD

**Issue by rentiansheng** [caddyserver/caddy#4619]
The level of the caddy log is currently fixed at startup , cannot be modified in the running state. 
use caddy create gateway. 
it brings some problems. 
It needs to restart the service frequently to adjust the log level, and the log content is too much.

problem scenario:
- Memory-dependent data reproduction problem, unable to restart or modify configuration files
- The problem does not appear until it has been running for a while.

I hope to expose the ability to control the log level in the log.
My idea is not to directly expose the api in the admin module, and to control it by the user to avoid malicious attacks.

Implementation: 
add a new method to caddy:
- SetLogLevel sets the basic method of logging

**Comment by mohammed90** [comment]
How is this not solvable by [making a `PATCH` request against the config path](https://caddyserver.com/docs/api#patch-configpath) of the logging level? Something like:

`curl -X PATCH -H "Content-Type: application/json" -d '<new level>' "http://localhost:2019/config/logging/logs/default/level"

Has this failed for you?

**Comment by francislavoie** [comment]
@rentiansheng Just wondering why you closed this? Did @mohammed90's answer clear things up for you?

**Comment by rentiansheng** [comment]
Some functions can be completed, but need to be adjusted. Now for security reasons, we have disabled the admin module.
admin is public API。

**Comment by francislavoie** [comment]
I don't understand what you're trying to say.

> security reasons, we have disabled the admin module. reason: admin is public API

The admin API binds to `localhost:2019` by default. That's not public. Only clients on the same machine as Caddy can access it. Are you running untrusted software that could arbitrarily make requests to Caddy?

You can definitely control access to the admin API. You could change the bind address to a unix socket if you prefer, and use linux permissions to lock that down. You could set up origin enforcement and use a special origin with a secret value that only your system would know.

> runtime reload log config, repoen file not safe, may be has error.

If the config has errors, Caddy doesn't load it. The original config stays running until the new config has started successfully. If it doesn't start successfully then the new config is thrown away and the original config continues to work as-is.

> I personally understand that other configuration here should not be changed except for level, but zap support change level。

What's the problem exactly? You _can_ change the log level by changing the config. Just configure the logging level in the `logging` config: https://caddyserver.com/docs/json/logging/

**Comment by rentiansheng** [comment]
describe project.  project developed by caddy. The module configuration of this gateway is managed by web ui, and then pushed to the gateway.
I would like to be able to manage log levels via API.

The current design is similar to https://caddyserver.com/docs/json/logging/, which is to reload the configuration of the logging module each time.


> I don't understand what you're trying to say.
> 
> > security reasons, we have disabled the admin module. reason: admin is public API
> 
> The admin API binds to `localhost:2019` by default. That's not public. Only clients on the same machine as Caddy can access it. Are you running untrusted software that could arbitrarily make requests to Caddy?

project extend admin.api.  There is a problem with my description, sorry.




> If the config has errors, Caddy doesn't load it. The original config stays running until the new config has started successfully. If it doesn't start successfully then the new config is thrown away and the original config continues to work as-is.
> 
> >

I am troubled by:
- Does the log output file need to be reopened?
- Will the overall module loading be more complicated?

**Comment by francislavoie** [comment]
Sorry, I think the language barrier is harming discussion here. I don't really understand what you're trying to say. I kinda have to make guesses as to what you mean.

> project extend admin.api.

I'm not sure I follow. Are you saying you're writing plugins for Caddy that add new admin API endpoints? I'm confused.

> Does the log output file need to be reopened?

No, writers are cached in a UsagePool https://pkg.go.dev/github.com/caddyserver/caddy/v2?tab=doc#UsagePool which persists their state across config reloads. If the new config uses the same writer, then it will be reused.

https://github.com/caddyserver/caddy/blob/c7d6c4cbb951f7db87fc5aebf8382aeeca6c9f1d/logging.go#L697

> Will the overall module loading be more complicated?

I think you should read https://caddyserver.com/docs/architecture if you haven't already. I'm not sure I understand your question here.

**Comment by rentiansheng** [comment]
sorry, i will use 
```
curl -X PATCH -H "Content-Type: application/json" -d '<new level>' "http://localhost:2019/config/logging/logs/default/level"
``` 
to change log level,  thank very much.
