### ISSUE TITLE
The best (and most efficient) way to store outbound traffic in a middleware

### ISSUE THREAD

**Issue by khash** [caddyserver/caddy#4624]
I'd like to write a middleware that collects bytes out for each request per host, as a middleware.

I've looked at the Prometheus module, and it seems it is using the golang Prometheus library, which uses a custom HTTP Handler to wrap the response writer and records the bytes written for this purpose.

Is this (writing a custom response writer) the best way to achieve this goal? And if so, how would I replace the response writer that's passed into my http handler with this custom one?

**Comment by francislavoie** [comment]
Are you just trying to count the amount of bytes, or actually do something with it?

Either way, yeah, an HTTP handler module that wraps the response writer is the way to go.

All you do is wrap the existing writer with your own, then pass that to the next handler in the chain, then any writes will go through yours as well as any other writer you wrapped or was wrapped around yours (depending on the order in which they ran).

Caddy sets up its own wrapper here https://github.com/caddyserver/caddy/blob/c8f2834b514f8bfb405c11be53d60a6cfc5228ca/modules/caddyhttp/responsewriter.go, which you could use as inspiration for your code. Notice `responseRecorder`'s `Write` counts the amount of bytes being written, so Caddy can log the response size.

**Comment by khash** [comment]
Thank you @francislavoie 
I wanted to get an aggregate of the bytes out for each host and managed to do it using a wrapper around the standard HTTP Response Writer.
