### ISSUE TITLE
Ability to terminate range requests

### ISSUE THREAD

**Issue by muety** [caddyserver/caddy#4626]
Following up on [my proposal in the forum](https://caddy.community/t/ability-to-terminate-range-requests/15336), I'd like to request an HTTP handler to terminate `Range` requests in case the reverse-proxied, upstream back-end service doesn't support such. Further description in the forum post.

Essentially, the handler would watch for a `Range` header in the request and, if no `Content-Range` is contained in the response or the response's status is different from `206 Partial Content`, the handler would slice the responses bytes according to the requested byte range.

I might want to look into this myself, but if someone else is interested, I'd also appreciate it!

**Comment by francislavoie** [comment]
As Matt said, I think this would likely fit better as a third-party plugin first. We tend to be careful what kind of features we add to the standard distribution of Caddy, to avoid bloat. This doesn't seem like the kind of feature that would have wide use, since it's a pretty specific need.

**Comment by mholt** [comment]
Yeah, I do think this would make a great HTTP handler module, but it's probably not a great fit for the standard distribution. Anyone is welcome to make this and list it on the Caddy website for download! :+1:
