### ISSUE TITLE
Cloning a request in a middleware, results in potentially wrong string replacement

### ISSUE THREAD

**Issue by khash** [caddyserver/caddy#4627]
In a custom middleware, I need to add something to the request context. As far as I can see, the only way to do that is to clone the request (simplified example):

```go
// we're in ServeHTTP of an http middleware and r is the http.Request
ctx, _ := context.WithValue(r.Context(), SomeKey, "extra info")
req := r.Clone(ctx)
// pass the request to the next middleware
```

This piece of "extra info" is now accessible down the chain to all of my other middlewares just fine.

However, if I change the `request.URI.Path` in another custom middleware, any downstream native `rewrite` middleware that uses the string replacer will still replace the placeholders with the original values of the request.

For example, using `{http.request.uri.path}` in a `rewrite` handler will use the original request URI path if the request is cloned, but will replace the strings correctly if I don't clone the request in the upstream middleware (but also lose my extra context value)

Looking at the code, I *think* this is down to when the `Replacer` is called and the values in its `static` map are populated. 

I was wondering if perhaps I'm not using the right method to add some info to the context for downstream middleware to use or perhaps there is something else wrong.

**Comment by khash** [comment]
Here is some more context I've managed to find and a hack to fix the issue for now:

If you change `request.URL.to` in a middleware, further rewrite handlers downstream will not replace `{http.request.uri.path}` correctly (they'll replace it with the original value of the request and not the changed one), **if** the request is cloned (they work find if you don't clone the request)

The hack that has fixed it for me is to call `Set` on the replacer after setting `requrst.URL.path`:

```go
r.URL.Path = to
repl := r.Context().Value(caddy.ReplacerCtxKey).(*caddy.Replacer)
repl.Set("http.request.uri.path", to)
```

**Comment by francislavoie** [comment]
You don't need to clone the request, you just need to use `req.WithContext(ctx)` instead. We do this in the `reverse_proxy` module:

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L793-L806

**Comment by khash** [comment]
Thank you @francislavoie. Using `WithContext` was my first approach and it suffers from the same issue. I've also tried `NewRequestWithContext` and that's also the same. I think the problem is not with the request, but with the timing of the call to `caddyhttp.PrepareRequest`. 

This function adds global and request placeholders into the `Replacer.static` as strings from the request. So while you're right that `URL` is a pointer to `url.URL`, the value of its constituents have been taken out and placed in `Replacer.static` as strings and not pointers.

**Comment by mholt** [comment]
Usually what you'd want to use is the request's Var map, with `GetVar` and `SetVar`: https://pkg.go.dev/github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp#SetVar

This way you don't need to copy the request or add to its context.

**Comment by khash** [comment]
Thank you @mholt for the reply. What I need to carry between middlewares is not a simple string (I used that to simplify the example) and therefore using the vars is not an option unless we serialize a data structure and store it on the vars as JSON and deserialize it further down, which seems excessive, given that the main underlying question here is the Replacer's static nature, living in a dynamic chain of middlewares that can modify the underlying data it needs to replace.

**Comment by mholt** [comment]
@khash Huh? The value is an `interface{}`, doesn't have to be a string.

**Comment by khash** [comment]
Ah! @mholt that's much better. I changed the way we use it from adding the value to the request context directly (which requires cloning of the context and therefore causes the string replacement issue) to use `SetVar` and `GetVar` which fixed the issue. Thank you! 

I still think there is a need for some fix or clarity around this issue (string replacer when request is cloned). While it is an edge case, it's very difficult to track down.

**Comment by mholt** [comment]
I'm not really sure where to document it though. I think that's just one of the caveats of using http.Request with Context, right? Where should the comment be that explains this? Other than here:

https://github.com/caddyserver/caddy/blob/3d616e8c6d65e5617f5a918d72fb1514c9c7144e/modules/caddyhttp/server.go#L583-L594
