### ISSUE TITLE
Root folder should not be checked when using external php sever

### ISSUE THREAD

**Issue by xorik** [caddyserver/caddy#4630]
Hi. When I have external php-fpm server, the root directory should not be checked
Example config:

```
example.com {
    root * /var/www/app
    php_fastcgi some-server:9000
}
```

Issue:
If caddy server doesn't have file `/var/www/app/index.php`, the external php server is never reached. I can workaround it by creating an empty file with this path, but it makes no sense.

Caddy version:
`v2.4.6 h1:HGkGICFGvyrodcqOOclHKfvJC0qTU7vny/7FhYp9hNw=`

**Comment by francislavoie** [comment]
No, that's completely correct. Caddy needs to know what files exist to properly rewrite the paths.

If you want to send all requests to your fastcgi upstream, then you're looking to use the `fastcgi` transport of the `reverse_proxy`.

See the docs for an explanation of how `php_fastcgi` works: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#expanded-form

**Comment by xorik** [comment]
Okay, thanks, I will try to figure out...

I basically need to rewrite anything to `index.php` to a JSON API, and I don't care about static files

**Comment by francislavoie** [comment]
Right, then you can do `rewrite * /index.php` and then use `reverse_proxy` with the `fastcgi` transport.

**Comment by xorik** [comment]
@francislavoie thanks, it works!

For anyone who's looking for solution:

        root * /app/public # Remote path

        rewrite * /index.php
        reverse_proxy * PHP_HOST:9000 {
            transport fastcgi {
                split .php
            }
        }
