### ISSUE TITLE
Unable to listen correct IP address

### ISSUE THREAD

**Issue by lonble** [caddyserver/caddy#4631]
I just want to start a local server behind a reverse proxy.
```
{
    auto_https off
}

http://127.0.0.1:80 {
    respond "hello"
}
```
```
$ ss -lnt
Netid  State   Recv-Q  Send-Q   Local Address:Port    Peer Address:Port Process 
tcp    LISTEN  0       128            0.0.0.0:22           0.0.0.0:*            
tcp    LISTEN  0       128               [::]:22              [::]:*            
tcp    LISTEN  0       4096                 *:80                 *:*            
```
Apparently it shouldn't listen `*`

**Comment by francislavoie** [comment]
The site address in the Caddyfile does not control what interfaces Caddy binds to. It controls which hostnames it will match. To configure the bind address, use the `bind` directive: https://caddyserver.com/docs/caddyfile/directives/bind

**Comment by lonble** [comment]
Thanks for your explanation. But such a mechanism can cause some problems. 
Binding to a unix socket does not require a port, which will cause the syntax check to fail. In the same way, if it is bound to the same port on different network interface, this problem will also occur.
But the truth is there is no conflict, not even ambiguity. A workaround might be to check the binding first, then the host.

```
http:// {
    bind unix//tmp/sock1
    respond "one"
}

http:// {
    bind unix//tmp/sock2
    respond "two"
}
```
```
run: adapting config using caddyfile: duplicate site address not allowed: 'http://' in [http://] (site block 2, key 0)
```

**Comment by mholt** [comment]
@lonble Ah yeah, that's one of the unfortunate trade-offs with the Caddyfile format: bind goes inside the site address, instead of surrounding it.

That edge case probably deserves some attention... but it's a separate issue from what this one is. Want to open a new issue for discussion?

**Comment by lonble** [comment]
I have described this in a new issue #4635


> @lonble Ah yeah, that's one of the unfortunate trade-offs with the Caddyfile format: bind goes inside the site address, instead of surrounding it.
> 
> That edge case probably deserves some attention... but it's a separate issue from what this one is. Want to open a new issue for discussion?
