### ISSUE TITLE
Inappropriate status code when host does not match

### ISSUE THREAD

**Issue by lonble** [caddyserver/caddy#4633]
When the host requested by the user does not match any host on the caddy server, caddy just returns `200 OK` and no body. This status code is confusing.
If there is no match, the server does not have a service enabled for this host, and it is appropriate to return `503 Service Unavailable`, as haproxy does.

**Comment by francislavoie** [comment]
That's intentional. Our philosophy on it is that "Caddy worked as configured". Caddy works as a blank slate. If you didn't configure it to handle that domain, then Caddy will just _do nothing_.

**Comment by mholt** [comment]
This is intentional.

[Status 503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) is an inappropriate error code for this:

> The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.
>
> Common causes are a server that is down for maintenance or that is overloaded. This response should be used for temporary conditions and the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) HTTP header should, if possible, contain the estimated time for the recovery of the service.

The scenario you're describing does not meet any of these criteria.
