### ISSUE TITLE
Binding to the same port on different network interfaces causes Caddyfile parsing to fail

### ISSUE THREAD

**Issue by lonble** [caddyserver/caddy#4635]
Binding to a unix socket does not require a port, while the same "address" will cause Caddyfile parsing to fail. In the same way, if it is bound to the same port on different network interface, this problem will also occur.
But the fact is there is no conflict, not even ambiguity. A workaround might be to check the bind first, then the address.

```
http:// {
    bind unix//tmp/sock1
    respond "one"
}

http:// {
    bind unix//tmp/sock2
    respond "two"
}
```
```
http:// {
    bind 127.0.0.1
    respond "127.0.0.1"
}

http:// {
    bind 12.34.56.78
    respond "12.34.56.78"
}
```
```
run: adapting config using caddyfile: duplicate site address not allowed: 'http://' in [http://] (site block 2, key 0)
```

**Comment by mholt** [comment]
Thanks, I was able to fix this -- I think. Tests are passing including some of my own Caddyfile configurations I tried out. Hopefully I didn't introduce any regressions. This area of the code is very particular... :grimacing:
