### ISSUE TITLE
Dynamic upstreams auto tls transport

### ISSUE THREAD

**Issue by hermandavid** [caddyserver/caddy#4646]
Returning SRV records with port 443 in does not auto enable HTTPS with the backend.

```
:8081 {
	reverse_proxy {
		dynamic srv "{http.request.host}" {
			resolvers 127.0.0.1:5353
		}
	}
}
```

**Comment by francislavoie** [comment]
Also because of how the transports are created/configured at provision-time, dynamic upstreams can't do both HTTP and HTTPS, you need to pick one.
