### ISSUE TITLE
Caddy localhost login?

### ISSUE THREAD

**Issue by jblevins1991** [caddyserver/caddy#4663]
The documentation in not clear at as to which credential I should be using to authenticate with caddy. Can someone point me in the right direction?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
