### ISSUE TITLE
SSLKEYLOGFILE / NSS Key Log Format support?

### ISSUE THREAD

**Issue by Manouchehri** [caddyserver/caddy#4668]
For diagnostics and troubleshooting (_not_ production), it's quite useful to be able to decrypt your own TLS traffic.

https://firefox-source-docs.mozilla.org/security/nss/legacy/key_log_format/index.html

It looks like Go's TLS package already supports this.

https://pkg.go.dev/crypto/tls#example-Config-KeyLogWriter

The usage would look like:

```sh
SSLKEYLOGFILE=keylog1.txt caddy
```

**Comment by francislavoie** [comment]
PRs welcome, if someone would like to take a crack at it.

We definitely should log a warning when this is turned on, to make it clear that security is actively being compromised.

Generally we're not fans of having behaviour controlled via environment variables.

Config for this would probably go in connection policies: https://caddyserver.com/docs/json/apps/http/servers/tls_connection_policies/ and as an option to the `tls` directive in the Caddyfile.

**Comment by mholt** [comment]
Implemented in #4808. Thanks @Manouchehri !

**Comment by mildsunrise** [comment]
To save some clicks to people who saw the title of the issue and missed/misunderstood the comment above:
Caddy does NOT support `SSLKEYLOGFILE`. Key logging is enabled exclusively through directives.

**Comment by mholt** [comment]
Thanks, yes -- I feel like an env var is too subtle/implicit for such a risky option.
