### ISSUE TITLE
Request: add placeholder substitution for file_server fields

### ISSUE THREAD

**Issue by brucejo75** [caddyserver/caddy#4671]
Problem: trying to use place holders in the `file_server`'s fields, e.g.:

```
    file_server {
      index "index.{host}.html"
    }
```

Does not substitute `{host}` with the host domain.

Request:add placeholder substitution for all `file_server` fields.

Thanks!

**Comment by u5surf** [comment]
@francislavoie @brucejo75 
Hi, I’d like to work on this issue.

We can replace {host} in indexPage into req.URL.Host(without port) or req.Host before following the sanitizing. 
https://github.com/caddyserver/caddy/blob/22d8edb984b9a0cbe5d205f823b455920464bb95/modules/caddyhttp/fileserver/staticfiles.go#L203

**Comment by francislavoie** [comment]
@u5surf Basically we just need to run `repl` on the `indexPage` value.

**Comment by PontianTown** [comment]
https://www.youtube.com/channel/UCjV2I8Eql9Ek7hnh2G6pdJw

**Comment by THtheokie888** [comment]
Cool like it
