### ISSUE TITLE
reverseproxy: Optimize SRVUpstreams.GetUpstreams and AUpstreams.GetUpstreams

### ISSUE THREAD

**Issue by RussellLuo** [caddyserver/caddy#4677]
## Rationale

- The current use of [time.Since](https://github.com/caddyserver/caddy/blob/22d8edb984b9a0cbe5d205f823b455920464bb95/modules/caddyhttp/reverseproxy/upstreams.go#L210)  is a little bit expensive, see https://github.com/golang/go/issues/17858.
- [sync.Map](https://pkg.go.dev/sync#Map) is very suitable as a cache.
    > The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

## Benchmarking

With [this change](https://github.com/RussellLuo/caddy/commit/905c565a8ddd4dd84d7c72df523323037ae58747) (currently only for AUpstreams.GetUpstreams), here are the benchmarking results on my Mac:

```bash
$ go test -bench=. -benchmem -cpu 2,4,8,16
goos: darwin
goarch: amd64
pkg: github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy
cpu: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
BenchmarkAUpstreams_GetUpstreams-2                       	11249152	       105.4 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreams-4                       	18434456	        66.22 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreams-8                       	18995061	        62.77 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreams-16                      	16984564	        66.92 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsNoTimeSince-2            	11774941	        90.24 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsNoTimeSince-4            	18706912	        62.09 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsNoTimeSince-8            	20414419	        59.88 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsNoTimeSince-16           	20247375	        55.86 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsSyncMapNoTimeSince-2     	14305203	        76.51 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsSyncMapNoTimeSince-4     	26708358	        45.77 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsSyncMapNoTimeSince-8     	23535303	        55.03 ns/op	      24 B/op	       1 allocs/op
BenchmarkAUpstreams_GetUpstreamsSyncMapNoTimeSince-16    	22130096	        46.85 ns/op	      24 B/op	       1 allocs/op
PASS
ok  	github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy	16.007s
```

---

**UPDATE**: I realized that my current implementation of [aaLookup.isFresh()](https://github.com/RussellLuo/caddy/blob/905c565a8ddd4dd84d7c72df523323037ae58747/modules/caddyhttp/reverseproxy/upstreams.go#L483-L485) is wrong. However, reintroducing `time.Now` (or `time.Since`) will offset the benefits of using `sync.Map`. Maybe a better way is to evict expired items in another goroutine.

**Comment by mholt** [comment]
Interesting, thanks for the links!

Maybe I'm reading the benchmarks wrong, but there doesn't seem to be much of a performance improvement? Maybe ~10 nanoseconds, but really worth it?

**Comment by RussellLuo** [comment]
Probably 20~30 nanoseconds faster if comparing `GetUpstreamsSyncMapNoTimeSince` with `GetUpstreams`. I thought `reverse_proxy` is typically a hot handler when Caddy is running, so its performance is worth notice.

But yeah, I admit that this will likely make the code more complicated. For example, to efficiently evict expired items in a separate goroutine, we might need an extra heap-like structure to keep the lookup items. Therefore, for now, I am not sure we should sacrifice simplicity in exchange for performance 😓

**Comment by mholt** [comment]
Just circling back around to this. I also kind of think that the minimal perf gains here are not worth the complexity. I really appreciate this kind of drilling down and profiling though, so definitely want to encourage this kind of work in the community. I think findings of all sorts -- vast improvements or minimal -- should be published. So, thank you for contributing!

I'll close this now though, feel free to continue discussion.
