### ISSUE TITLE
Compile error when add quic-go module

### ISSUE THREAD

**Issue by bolucat** [caddyserver/caddy#4711]
Hi, for the latest release [v2.5.0-rc.1](https://github.com/caddyserver/caddy/releases/tag/v2.5.0-rc.1), I have encountered some errors when compiling caddy using [xcaddy](https://github.com/caddyserver/xcaddy), but for the previous version this error doesn't occur, the information append below:

On Linux:
```bash
# go version go1.18.1 linux/amd64
go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
git clone -b v0.27.0 https://github.com/lucas-clemente/quic-go
env GOOS=linux GOARCH=amd64 $GOPATH/bin/xcaddy build HEAD --output ./caddy-linux-amd64 --with github.com/lucas-clemente/quic-go=$PWD/quic-go
```
The error showed when build failed:
```bash
Error:  /pkg/mod/github.com/caddyserver/caddy/v2@v2.5.0-rc.1.0.20220415175848-d230b330078b/listeners.go:187:68: undefined: quic.EarlySession
```
I don't know whether this problem occurs due to [lucas-clemente/quic-go](https://github.com/lucas-clemente/quic-go) or caddy itself, so I opened issue here, please help me check that, thanks for your help

**Comment by francislavoie** [comment]
Doing `--with github.com/lucas-clemente/quic-go=$PWD/quic-go` means that you're replacing the version of `quic-go` you're building with.

We're still on quic-go v0.26.0 in Caddy, but quic-go v0.27.0 renamed a few things, meaning some minor changes are needed in Caddy to match.

**Comment by bolucat** [comment]
Sorry, but I'm not trying to replace quic-go in caddy, I just need to add quic support in my use case, just like the configuration below:
```bash
.....
{
  servers {
    protocol {
      experimental_http3
    }
  }
}
.....
```
I have downgraded the quic-go version to meet the requirement in caddy, and no error occurs again, thanks for your help

**Comment by francislavoie** [comment]
You don't need to use `--with` at all then, Caddy comes with quic-go already.

**Comment by bolucat** [comment]
Thanks for your reminder, I didn't notice that, thanks again

**Comment by francislavoie** [comment]
Yeah - it's necessary, otherwise Caddy wouldn't compile, since it uses code from there to actually provide HTTP/3 support. It's not a situation where adding the lib causes Caddy to gain it or something. There's no compiler preprocessor stuff going on.
