### ISSUE TITLE
Automatic HTTPS does not get disabled despite providing TLS certificates. 

### ISSUE THREAD

**Issue by tomikaka22** [caddyserver/caddy#4712]
**Caddy is trying to obtain a certificate despite [the documentation](https://caddyserver.com/docs/automatic-https#activation) saying automatic HTTPS will be disabled when manually loading certificates.**

Example using caddyfile:

```
https://openmedia.vault {
   reverse_proxy 127.0.0.1:82
   tls /kezs/openmediavault.crt /kezs/openmediavault.key
}
```
**Caddy loads the certificates, I can access https://openmedia.vault correctly as I wanted, but in the Caddy logs it still shows it's trying to obtain a certificate:** 

```
{"level":"info","ts":1650229113.1035242,"msg":"serving initial configuration"}

{"level":"info","ts":1650229113.1045132,"logger":"tls","msg":"finished cleaning storage units"}

{"level":"info","ts":1650229113.1191037,"logger":"tls.obtain","msg":"acquiring lock","identifier":"openmedia.vault"}

{"level":"info","ts":1650229113.1589134,"logger":"tls.obtain","msg":"lock acquired","identifier":"openmedia.vault"}

{"level":"info","ts":1650229113.1718686,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["openmedia.vault"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}

{"level":"info","ts":1650229113.171905,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["openmedia.vault"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}

{"level":"error","ts":1650229114.2138488,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"openmedia.vault","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"openmedia.vault\": Domain name does not end with a valid public suffix (TLD)"}

```
I'm using a self built docker image with the caddy-maxmind-geolocation plugin. 
I'm using _"openmedia.vault"_ only locally, I have set the appropriate DNS records with AdguardDNS, this is not the issue and works as expected.

**Comment by mholt** [comment]
Hi, thanks for opening an issue. Can you please post the .crt file here? If it does not have the domain name used in your config in its SANs, it will not be valid so Caddy will not use it.

**Comment by tomikaka22** [comment]
Hi, thank you for the response, this was the issue precisely. I used a certificate for a different domain name entirely.
When using the correct cert Caddy does not try to obtain one.

On an unrelated note, I've realized `tls internal` would be perfect for my use case.
