### ISSUE TITLE
Thank you, Caddy

### ISSUE THREAD

**Issue by mcguirepr89** [caddyserver/caddy#4716]
I fixed the link on https://birdnetpi.com and added another on [the github](https://github.com/mcguirepr89/BirdNET-Pi) -- THANK YOU FOR CADDY

**Comment by mholt** [comment]
Wow, thanks for the nice comment! On behalf of myself and the maintainers, we really appreciate it. 😃 

I think birdnetpi is a pretty cool project, so I tweeted (ha) it: https://twitter.com/caddyserver/status/1516272611369492482

Hoping to use it someday once I can get my hands on a Raspberry Pi!
