### ISSUE TITLE
admin: Automated regression testing

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#4718]
I've always thought it would be really handy to be able to specify a test corpus so that any changes to the config have to pass the tests before the config can be applied. Or more pragmatically: apply the new config, run the tests, then roll back the config if the tests fail.

**Comment by francislavoie** [comment]
Sounds like a duplicate of https://github.com/caddyserver/caddy/issues/4537 kinda

**Comment by mholt** [comment]
Oh, yeah 🤦‍♂️ -- you're right, this is basically a dupe. My bad!
