### ISSUE TITLE
Wildcard trailing slash

### ISSUE THREAD

**Issue by blenderfreaky** [caddyserver/caddy#4719]
I'd like to match all paths `/example/*`, including `/example` without a trailing slash.

When using a matcher with a wildcard such as `/example/*` the link `/example` is not matched.
When using a matcher like `/example*` the link `/exampleOfAnotherLink` is also matched.

I could create a long named matcher like this:

```
@example {
    path /example /example/*
}
```

But that's a lot of extra lines and I'm matching a lot of different paths like this.

Is there a more compact way of matching `/example` and `/example/*` at the same time?

**Comment by francislavoie** [comment]
You can use the single-line matcher syntax:

```
@example path /example /example*
```

But otherwise, no, not currently. I did propose a solution for this in https://github.com/caddyserver/caddy/pull/4303 but it was shelved for now.
