### ISSUE TITLE
How  to install Caddy in MacOS M1 by static binaries using the download page 

### ISSUE THREAD

**Issue by caesarding07** [caddyserver/caddy#4722]
For some reason, I have to download the static binaries on the download page instead of release on GitHub. However, it is a document but not a .dmg or .sh as I suppose when I have downloaded, so could someone help me to use it? Thank you so much!

![XuQsQv](https://raw.githubusercontent.com/caesarding07/images/main/uPic/XuQsQv.png)
![e5fRUg](https://raw.githubusercontent.com/caesarding07/images/main/uPic/e5fRUg.png)

**Comment by francislavoie** [comment]
It's a binary. Just give it executable permissions and you're good to go. Run `chmod +x <filename>`. You can also rename the file to just `caddy` and move it to `/usr/local/bin` so you can run it from anywhere.

**Comment by francislavoie** [comment]
Oh, nevermind, looks like we already do:

![image](https://user-images.githubusercontent.com/2111701/164714011-3b4cf76d-a802-48bc-a43b-c84288490e10.png)

`arm64` is the build you want for M1.
