### ISSUE TITLE
Make "Server" header configurable

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#4727]
What's the opinion about the topic to make the "Server" header configurable.
Currently is the "Server" header hard coded and always send.

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/server.go#L146
Would you like to accept a PR which makes the "Server" header configurable?

```
server_name on (default)|off|"any string"
```

I think there was similar discussion on v1 I can't remember what the last decision was.

**Comment by francislavoie** [comment]
I don't see the argument for removing or changing it. There's no security or privacy benefit to removing it.

**Comment by git001** [comment]
okay

**Comment by mholt** [comment]
Can't you do this with the `header` directive? https://caddyserver.com/docs/caddyfile/directives/header

**Comment by git001** [comment]
I thought similar and it was possible.

```json
"handle": [
            {
                "handler": "headers",
                "response": {
                    "set": {
                        "Server":["MyServer"]
                    }
                }
            }]
```

**Comment by mholt** [comment]
It makes us sad though. We like to know how many / where Caddy instances are being deployed.

**Comment by git001** [comment]
full ack.

The problem is that some quite old "security" rules defines that the Server header should be removed or changed.
As @francislavoie already mentioned is this not a very usefull rule but you know old systems requires centuries to get adopted :sob:
