### ISSUE TITLE
php_fastcgi changes in 2.5.0

### ISSUE THREAD

**Issue by alcohol** [caddyserver/caddy#4733]
I ran into some `php_fastcgi` changes in 2.5.0 that seem [undocumented](https://github.com/caddyserver/caddy/releases/tag/v2.5.0) (not mentioned in highlighted nor notable). They impact how our application ( Symfony version 3.4.49, quite old _unfortunately_ ) perceives the environment and I am unsure if these changes were intentional or not.

### Reproduction

I created a simplified Docker-Compose setup that mimics our environment and sufficiently highlights the differences in behaviour.

Related gist with files for reproduction: https://gist.github.com/alcohol/abe25fb3ddd2e22c6f819fba60c323f7

Our application runs behind a proxy, so in short:

https caddy -> varnish -> http caddy -> fpm

But for reproduction, I simplified it to:

https caddy -> http caddy -> fpm

### Differences

The notable differences occur in the global `_SERVER` variable which Symfony uses to determine how it should generate routes and such for redirects.

#### In Caddy 2.4.6, the PHP global `_SERVER` variable contained the following relevant values:

> Note the absense of `SERVER_PORT` and `X_FORWARDED_HOST`

```
["HTTP_X_FORWARDED_FOR"]=>
string(21) "172.20.0.1, 127.0.0.1"
["HTTP_X_FORWARDED_PROTO"]=>
string(5) "https"
```

#### In Caddy 2.5.0, the `_SERVER` variable contained the following relevant values:

```
["HTTP_X_FORWARDED_FOR"]=>
string(9) "127.0.0.1"
["HTTP_X_FORWARDED_HOST"]=>
string(9) "localhost"
["HTTP_X_FORWARDED_PROTO"]=>
string(4) "http"
["SERVER_PORT"]=>
string(2) "80"
```

### Problem

When generating redirects, Symfony uses one or multiple of these values to determine if the generated redirect URI should have a http or https scheme, and whether or not it should add a port to the host.

Running behind 2.4.6 it would generate a redirect as follows for example:

```
Location: https://example.com/target
```

Running behind 2.5.0 it would generate a redirect as follows:

```
Location: http://example.com:443/target
```

Unfortunately I have yet to determine how exactly Symfony uses these variables and which change specifically is causing this issue. This is further complicated by the fact that we have quite an extensive custom configuration. I will update this issue with further findings as I continue to investigate.

**Comment by alcohol** [comment]
Well, I feel like a dum dum now. I just had to add `trusted_proxies private_ranges` to the `php_fastcgi` directive of our "backend" Caddy configuration. I completely blanked on the fact that it is basically a short-cut for `reverse_proxy`, so all those changes applied to `php_fastcgi` as well. We simply weren't trusting the forwarded headers from our own frontend proxies anymore.

**Comment by francislavoie** [comment]
Yep! That's right, `trusted_proxies` is your issue here. Glad you figured it out!
