### ISSUE TITLE
Feature Request: Present self-signed certificate until publicly-trusted cert is available

### ISSUE THREAD

**Issue by SeanDylanGoff** [caddyserver/caddy#4735]
Hello

First off, thank you for this awesome project!
As Whitestrake explained [here](https://caddy.community/t/letsencrypt-error-when-caddy-is-behind-cloudflare/14100/7), http-01 doesn't work for the first time behind CloudFlare. This puts us in the unfortunate position of having to accept downtime when migrating a website to our servers.

I think this could be prevented by having an option to use TLS internal as a fallback. That would mean that:

- http-01 would work through CloudFlare with Full Encryption (without "strict") without manual intervention
- no downtime would be caused while the certificate is not issued (or if renewal ever failed for whatever reason) - because CloudFlare could still terminate TLS as usual.

Of course this option should probably not be enabled by default as some users might prefer a hard fail when a cert is missing.

Would you consider to implement this feature? If not - would a PR be welcome?

**Comment by mholt** [comment]
You can already do this and I highly recommend it in your case. Just add an internal issuer to your automation policies. I thought I had an example in a wiki or docs or something, but in the original PR it's kind of here: https://github.com/caddyserver/caddy/pull/3862

```
tls {
	issuer zerossl
	issuer acme
	issuer internal
}
```

Something like that. Or if you're using the JSON, just add an `internal` issuer to the end of your list of issuers: https://caddyserver.com/docs/json/apps/tls/automation/policies/

Related: https://caddy.community/t/using-caddy-to-keep-certificates-renewed/7525?u=matt

**Comment by SeanDylanGoff** [comment]
@mholt Thanks for the tip, however I don't think that really solves the problem (at least in my tests it didn't):
To prevent downtime the fallback should not be used *if the other issuers fail*, but rather *before they succeed*.
Did I miss something?

**Comment by mholt** [comment]
Oh, I misunderstood then. I updated the issue title to better express what I understand you're asking for now.

**Comment by manigarg31** [comment]
Hi, are we expecting this feature anytime soon?

**Comment by francislavoie** [comment]
@manigarg31 we're not currently working on it. Please explain why you'd like this!

**Comment by mholt** [comment]
I can work on it this year probably; but yeah, the more details we have about requirements and use cases, the better.

**Comment by manigarg31** [comment]
We have a use case where we cannot provide certificates for all the websites since it will overload the certificate authority so we whitelist the domains for which we need the certificates. But we cannot block rest of the sites we still have to server those with test certificate which will give warning if user want to proceed they can go ahead.

**Comment by manigarg31** [comment]
> I can work on it this year probably; but yeah, the more details we have about requirements and use cases, the better.

We have a use case where we cannot provide certificates for all the websites since it will overload the certificate authority so we whitelist the domains for which we need the certificates. But we cannot block rest of the sites we still have to serve those with test certificate which will give warning if user want to proceed they can go ahead.

**Comment by manigarg31** [comment]
@mholt @francislavoie

**Comment by IndeedNotJames** [comment]
One thing I want to clarify:

http-01 behind Cloudflare does work just fine.

Cloudflare will proxy `http://example.com/.well-known/acme-challenge/example` as `http://` to `:80` on the configured upstream, not terminating tls, unlike any other uri.
This is specific to `/.well-known/acme-challenge/*` and, as far as I can tell, happens exclusively with `/.well-known/acme-challenge/*`.
Even if one enabled `always_use_https = true` ("Always Use HTTPS ") or set `ssl = "strict"` "Full (Strict)" in the zone settings.

**Comment by francislavoie** [comment]
> Also will be cool to specify in caddy configuration that in case the ask endpoint Is not reachable or available a fall back on selfsigned certs, until the endpoint recovers.

That's dangerous. What this would mean is that an attacker could cause your server to issue an infinite amount of certificates, filling up your storage, until it can't anymore. The attacker would just need to point a wildcard DNS record to your domain, then make requests for infinite subdomains to your server. That's one of the main purposes of `ask`, to mitigate that kind of attack. It should reject by default, otherwise that attack vector is open. 

> Will be cool also to have a Dynamic way to specify It via the Ask endpoint with on demand tls, the endpoint response could have some information about to which issuer list order etc to use

Hmm, that's a bit awkward. Issuers don't have any kind of identifier under the hood, it's just an array of issuer objects. So there's no way to actually tell Caddy after the config is loaded which way to order them. Unless we do add some identifier field on issuers. But that's not a precedent we have right now, really.

It would also mean having to specify a schema for the response returned from the ask endpoint. Right now, it's intentionally free-form in that we only read the status code. That means the upstream endpoint can respond however it wants (whatever's most convenient for your framework) and it should just work.

> We have a use case where we cannot provide certificates for all the websites since it will overload the certificate authority

How many domains are you planning to manage? Caddy's rate limit is set to 10 per 10 seconds. See https://caddyserver.com/docs/automatic-https#errors. Unless you're serving hundreds of thousands or millions, I don't see that as being a problem.

**Comment by mholt** [comment]
@francislavoie What if the self-signed cert was discarded after being used for that handshake?

This might be unacceptably slow, however... unless maybe we keep a single ephemeral key in memory.

**Comment by francislavoie** [comment]
Sure, but then you're trading storage for CPU cycles. The attacker could exhaust CPU resources from generating keys and issuing certs, instead of exhausting storage space. :man_shrugging:

**Comment by mholt** [comment]
That's why I'm thinking maybe we could keep a single ephemeral key in memory. The cert is pretty cheap after that.

**Comment by manigarg31** [comment]
> > Also will be cool to specify in caddy configuration that in case the ask endpoint Is not reachable or available a fall back on selfsigned certs, until the endpoint recovers.
> 
> That's dangerous. What this would mean is that an attacker could cause your server to issue an infinite amount of certificates, filling up your storage, until it can't anymore. The attacker would just need to point a wildcard DNS record to your domain, then make requests for infinite subdomains to your server. That's one of the main purposes of `ask`, to mitigate that kind of attack. It should reject by default, otherwise that attack vector is open.
> 
> > Will be cool also to have a Dynamic way to specify It via the Ask endpoint with on demand tls, the endpoint response could have some information about to which issuer list order etc to use
> 
> Hmm, that's a bit awkward. Issuers don't have any kind of identifier under the hood, it's just an array of issuer objects. So there's no way to actually tell Caddy after the config is loaded which way to order them. Unless we do add some identifier field on issuers. But that's not a precedent we have right now, really.
> 
> It would also mean having to specify a schema for the response returned from the ask endpoint. Right now, it's intentionally free-form in that we only read the status code. That means the upstream endpoint can respond however it wants (whatever's most convenient for your framework) and it should just work.
> 
> > We have a use case where we cannot provide certificates for all the websites since it will overload the certificate authority
> 
> How many domains are you planning to manage? Caddy's rate limit is set to 10 per 10 seconds. See https://caddyserver.com/docs/automatic-https#errors. Unless you're serving hundreds of thousands or millions, I don't see that as being a problem.

Here we are looking for hunderds of thousands of domains on regular basis.

**Comment by whizzygeeks** [comment]
> issuer zerossl
> 	issuer acme
> 	issuer internal

@mholt this doesnt work under https:// block seeing error  ->  automation policy from site block is also default/catch-all policy because of key without hostname, and the two are in conflict:  r{(*caddytls.ACMEIssuer)(0xc0001168c0), (*caddytls.ZeroSSLIssuer)(0xc00032a7b0), (*caddytls.InternalIssuer)(0xc00032a840)} != []certmagic.Issuer{(*caddytls>

**Comment by whizzygeeks** [comment]
> > Also will be cool to specify in caddy configuration that in case the ask endpoint Is not reachable or available a fall back on selfsigned certs, until the endpoint recovers.
> 
> That's dangerous. What this would mean is that an attacker could cause your server to issue an infinite amount of certificates, filling up your storage, until it can't anymore. The attacker would just need to point a wildcard DNS record to your domain, then make requests for infinite subdomains to your server. That's one of the main purposes of `ask`, to mitigate that kind of attack. It should reject by default, otherwise that attack vector is open.
> 
> > Will be cool also to have a Dynamic way to specify It via the Ask endpoint with on demand tls, the endpoint response could have some information about to which issuer list order etc to use
> 
> Hmm, that's a bit awkward. Issuers don't have any kind of identifier under the hood, it's just an array of issuer objects. So there's no way to actually tell Caddy after the config is loaded which way to order them. Unless we do add some identifier field on issuers. But that's not a precedent we have right now, really.
> 
> It would also mean having to specify a schema for the response returned from the ask endpoint. Right now, it's intentionally free-form in that we only read the status code. That means the upstream endpoint can respond however it wants (whatever's most convenient for your framework) and it should just work.
> 
> > We have a use case where we cannot provide certificates for all the websites since it will overload the certificate authority
> 
> How many domains are you planning to manage? Caddy's rate limit is set to 10 per 10 seconds. See https://caddyserver.com/docs/automatic-https#errors. Unless you're serving hundreds of thousands or millions, I don't see that as being a problem.

@francislavoie We are already using this arrangement in nginx with letsencrypt since rate limit is already enforced through domain validation. If user is not found in redis database internally kept self signed static certificate is used. It would have been risky in case ask url is not used in caddy. For overwhelming requests there is always a ratelimit and fail2ban .

**Comment by mholt** [comment]
@whizzygeeks You already opened a new issue to discuss this: https://github.com/caddyserver/caddy/issues/5627 -- please don't repeat and cause extra work.

**Comment by hialvaro** [comment]
Hi, I am interested in this feature. I'd really like Caddy to not generate a Let’sEncrypt/ZeroSSL certificate until the domain DNS are pointing to the host IP. In the meantime, caddy could have a self-signed certificate just as stated. Caddy could run every 5s or so a command like `ips, err := net.LookupIP("example.com")` in Go to check that the pointing IP is the correct one, maybe something should be needed to handle CNAME records. Once it is the same as the host, it could trigger the certificate generation. Until this does not happen, an internal self-signed certificate is used.

This would be useful when I am waiting for a customer to point their domain's DNS to my server (for a domain I don’t control) and I can’t be waiting for them to notify me to trigger the new domain generation. I don’t want to leave the ssl generation as is right now, as it will be exponentially growing in wait-time, this means that if the other person points it a day later, it could face minutes or hours of downtime until it points to the domain and the generation succeeds. If this was possible, I would be able to leave it and when the DNS points to the IP, caddy would automatically trigger the SSL certificate generation, making things much easier.

**Comment by mholt** [comment]
My mann @hialvaro , you actually want [On-Demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls).

**Comment by mholt** [comment]
Circling back on this, it seems like much of use cases described are better handled by On-Demand TLS.

I am still trying to understand how serving an invalid certificate that will generate warnings in browsers is helpful. It only trains users to click through warnings, which is the _last_ thing we want them to do.

I think I am inclined to shelve this feature request for now, but the discussion is welcome to continue as needed; if there's legitimate use cases that don't involve training users to bypass security warnings, we can reconsider this. :100:

**Comment by SeanDylanGoff** [comment]
> I am still trying to understand how serving an invalid certificate that will generate warnings in browsers is helpful. It only trains users to click through warnings, which is the _last_ thing we want them to do.

At least for my use-case this is a misunderstanding. I want to serve a self-signed certificate to CloudFlare, NOT to the user.
Without *any* certificate, CloudFlare will refuse to connect to the origin (Caddy), and because of this will not let the HTTP-1 Challenge through - preventing Caddy from getting a certificate. Thus Caddy will NEVER be able to get a certificate in such a situation unless the orange cloud is deactivated. But that is a manual process, and also leaks the origin IP, so not everyone wants to have to do that.

**Comment by mholt** [comment]
Ah, you mean Cloudflare is the client, not a proxy passing things through...

Still, I am certain this isn't the case:

> Without any certificate, CloudFlare will refuse to connect to the origin (Caddy), and because of this will not let the HTTP-1 Challenge through - preventing Caddy from getting a certificate. Thus Caddy will NEVER be able to get a certificate in such a situation unless the orange cloud is deactivated.

That just isn't true though.

I just did it again myself as a sanity check. Here's my setup:

- Domain hosted at Cloudflare, A record pointed at my machine
- Orange cloud (proxied)
- SSL/TLS mode set to "Full (strict)"

![image](https://github.com/caddyserver/caddy/assets/1128849/27f0e43e-ab58-45fa-8bca-00b69087d55c)

The logs are really long but some highlights:

```
2024/05/11 02:14:17.537 INFO    tls.issuance.acme       served key authentication       {"identifier": "test1.matt.example", "challenge": "http-01", "remote": "172.69.22.217:52786", "distributed": false}
2024/05/11 02:14:27.832 INFO    tls.issuance.acme.acme_client   authorization finalized {"identifier": "test1.matt.example", "authz_status": "valid"}
2024/05/11 02:14:27.832 INFO    tls.issuance.acme.acme_client   validations succeeded; finalizing order {"order": "https://acme-staging-v02.api.letsencrypt.org/acme/order/144436484/12345"}
2024/05/11 02:14:31.088 INFO    tls.obtain      certificate obtained successfully       {"identifier": "test1.matt.example", "issuer": "acme-staging-v02.api.letsencrypt.org-directory"}
```

HTTP challenge works great, first try, behind Cloudflare, proxied, with Full (strict) SSL/TLS.

**Comment by francislavoie** [comment]
@mholt this only works if you have redirect disabled in Cloudflare, which is on by default, I think https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/

**Comment by mholt** [comment]
@francislavoie So I found the page called "Edge Certificates" that has settings like that, and I don't remember ever visiting that page before, and it was disabled. (And the default min TLS version was 1.0, so...)
