### ISSUE TITLE
Customise the field names for logs.

### ISSUE THREAD

**Issue by ledzepp4eva** [caddyserver/caddy#4744]
Hey,

I was looking at configuring the logging in caddy to reflect https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html. For example taking request>remote_ip and using `client.ip` instead of `remote_ip` to store our logs in a  more consistent format.

However although we can customise what appears in the logs, we don't appear to be able to change the field names.

Is this a feature I'm not seeing or something that would need to be implemented?

For example:
```json
"request": {
    "remote_ip": "client.ip",
    "remote_port": "52783",
}
```

Becomes
```json
"request": {
    "client.ip": "client.ip",
    "client.port": "52783",
}
```

Thanks,
Liam

**Comment by francislavoie** [comment]
You can use this encoder: https://github.com/leodido/caddy-jsonselect-encoder

It _might_ be possible to add support for renaming fields with the `filter` encoder, but I think you'd probably be better served by that `jsonselect` plugin.

**Comment by mholt** [comment]
Woah, I don't remember seeing that one. Cool

**Comment by francislavoie** [comment]
Alright, got this little feature implemented: https://github.com/caddyserver/caddy/pull/4745
