### ISSUE TITLE
More clever HTTP-to-HTTPS redirects?

### ISSUE THREAD

**Issue by TobiX** [caddyserver/caddy#4750]
When deploying Caddy in internal networks, it is possible to access the HTTP port via a "short" hostname (if both the server and client have `search example.com` in their `resolv.conf`, the server `www.example.com` can be addressed via `http://www/`). Currently, Caddy will naively take the request host name and construct a https URL out of it (so it would redirect to `https://www/`), which will then fail since the certificate is only valid for the FQDN of the host.

Currently, I have to override this behaviour, for example with something like this:
```
http:// {
        redir https://www.example.com{uri} permanent
}
```

I wonder if Caddy could automatically detect this case and return a redirect to the FQDN? (I realize there might be a lot of corner cases which might make implementing this challenging...)

**Comment by francislavoie** [comment]
I think I'll close this, I don't think it's a good idea to read from `resolv.conf` for this. I think it's a pretty niche need, so probably best if you use a config like I suggested above to do it if you need it.
