### ISSUE TITLE
[Feature  Request] Add `protocol_min` and `protocol_max` for reverseproxy transport http second attempt

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#4752]
As discussed in #4747 I would like to propose a Feature  Request to add 3 fields to the reverse proxy for more fine grade configuration for the reverse proxy

- protocol_min
- protocol_max
- allow_insecure_tls_version

The discussion at #4747 makes it clear that it's a quite dangerous decision to allow older TLS Protocols but when the setup is in a closed environment are the risks for some people accepted.

I would like to create a new PR similar to #4748 but with added Caddyfile parsing and the additional field `allow_insecure_tls_version`

**Comment by francislavoie** [comment]
I'm not sure I see how that's any different. Like we've said, TLS 1.2 is 14 years old. We explicitly don't want to support anything older. Offering more config knobs to users for security protocols only gives users more ways to shoot themselves in the foot.

Here's a talk from a cryptographer about this (more specifically about JOSE/JWT, but the concepts of less config = better applies) https://www.youtube.com/watch?v=RijGNytjbOI
