### ISSUE TITLE
example of trusted_proxies 

### ISSUE THREAD

**Issue by guoard** [caddyserver/caddy#4758]
I want to use `trusted_proxies` in `reverse_proxy` directive for Cloudflare [ips](https://www.cloudflare.com/ips/).
Is this pattern correct?
```
reverse_proxy * localhost:8000 {
  trusted_proxies private_ranges 103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,2803:f800::/32
}
```

**Comment by francislavoie** [comment]
Close -- use spaces, not commas, to separate them.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
