### ISSUE TITLE
SCRIPT_NAME not passed to php-fpm gateway

### ISSUE THREAD

**Issue by Elegant996** [caddyserver/caddy#4788]
When using the `php_fastcgi` directive, the variable `SCRIPT_NAME` is not passed to the `php-fpm` gateway. This causes issues in certain scenarios such as when `/ping` is enabled through `php-fpm`. The result is that the gateway cannot properly construct the URI and `/ping` fails to return.

In order to restore proper functionality the below is required:

```
php_fastcgi /ping unix//run/php-fpm/php-fpm.sock {
    env SCRIPT_NAME {header.SCRIPT_NAME}
}
```

It may be prudent to include this in the `caddyfile.go` as part of the `php_fastcgi` directive so that the gateway is aware of the variable by default instead of requiring it each time `/ping` or similar is enabled on the matcher.

**Comment by francislavoie** [comment]
I'm confused. We _do_ set SCRIPT_NAME:

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L295

**Comment by Elegant996** [comment]
Yes, we do but give it a go in a demo. If you enable `ping` for `php-fpm` server and use a drop-in config such as:

```
[global]
daemonize = no

[www]
pm = dynamic
pm.max_children = 120
pm.start_servers = 12
pm.min_spare_servers = 6
pm.max_spare_servers = 18

listen = /run/php-fpm/php-fpm.sock

ping.path = /ping
```

You will find that that there is no `pong` return unless the `SCRIPT_NAME` variable is specified. Although this is `caddy`, [Fossil](https://www.fossil-scm.org/home/doc/trunk/www/scgi.wiki) had an interesting read for SCGI (FastCGI allows applies in this scenario) where it had to specified.

**Comment by francislavoie** [comment]
Likely because Caddy ends up rewriting to `index.php` because there's no `/ping` file that exists in your webroot. I bet if you create an empty file called `ping`, it will work.

**Comment by francislavoie** [comment]
I'm pretty sure this is just a misunderstanding of how `php_fastcgi` works. See https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#expanded-form, which explains the `try_files` logic.
