### ISSUE TITLE
"looking up info for HTTP challenge" Error   ...   "no information found to solve challenge for identifier"

### ISSUE THREAD

**Issue by shaulbarlev** [caddyserver/caddy#4799]
Hello.
I'm trying to set up caddy for use with Jellyfin. When trying to run it winds up erroring this for hours **(I replaced my personal info)**:
> 2022/05/18 20:07:36.815 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}

Things I'm 99% sure of, after testing of course:
1. Ports 443 and 80 are forwarded successfully (I had different errors before resolving this).
2. Caddy is allowed through the firewall (different errors before resolving this).

This is my caddyfile:
> {
email myemail@gmail.com
}
sub.domain.com {
	log {
		output file "C:\Program Files\Caddy\logs\jellyfin_access.log" {
			roll_size 1gb
			roll_keep 5
			roll_keep_for 720h
		}
	}
	reverse_proxy localhost:8096
}

This is what I get after I run:

> 2022/05/18 19:57:41.952 ←[34mINFO←[0m   using adjacent Caddyfile
2022/05/18 19:57:41.953 ←[33mWARN←[0m   Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies    {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
2022/05/18 19:57:41.958 ←[34mINFO←[0m   admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["//[::1]:2019", "//127.0.0.1:2019", "//localhost:2019"]}
2022/05/18 19:57:41.958 ←[34mINFO←[0m   tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0001dbdc0"}
2022/05/18 19:57:41.958 ←[34mINFO←[0m   http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2022/05/18 19:57:41.958 ←[34mINFO←[0m   http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2022/05/18 19:57:41.958 ←[34mINFO←[0m   tls     cleaning storage unit   {"description": "FileStorage:C:\\Users\\BARLEVSERV\\AppData\\Roaming\\Caddy"}
2022/05/18 19:57:41.959 ←[34mINFO←[0m   tls     finished cleaning storage units
2022/05/18 19:57:41.959 ←[34mINFO←[0m   http    enabling automatic TLS certificate management   {"domains": ["sub.domain.com"]}
2022/05/18 19:57:41.960 ←[34mINFO←[0m   autosaved config (load with --resume flag)      {"file": "C:\\Users\\BARLEVSERV\\AppData\\Roaming\\Caddy\\autosave.json"}
2022/05/18 19:57:41.960 ←[34mINFO←[0m   serving initial configuration
2022/05/18 19:57:41.969 ←[34mINFO←[0m   tls.obtain      acquiring lock  {"identifier": "sub.domain.com"}
2022/05/18 19:57:41.973 ←[34mINFO←[0m   tls.obtain      lock acquired   {"identifier": "sub.domain.com"}
2022/05/18 19:57:43.163 ←[34mINFO←[0m   tls.issuance.acme       waiting on internal rate limiter        {"identifiers": ["sub.domain.com"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "myemail@gmail.com"}
2022/05/18 19:57:43.164 ←[34mINFO←[0m   tls.issuance.acme       done waiting on internal rate limiter   {"identifiers": ["sub.domain.com"], "ca": "https://acme-v02.api.letsencrypt.org/directory", "account": "myemail@gmail.com"}
2022/05/18 19:57:43.920 ←[34mINFO←[0m   tls.issuance.acme.acme_client   trying to solve challenge       {"identifier": "sub.domain.com", "challenge_type": "tls-alpn-01", "ca": "https://acme-v02.api.letsencrypt.org/directory"}
2022/05/18 19:57:44.497 ←[34mINFO←[0m   tls     served key authentication certificate   {"server_name": "sub.domain.com", "challenge": "tls-alpn-01", "remote": "18.194.159.252:25188", "distributed": false}
2022/05/18 19:57:44.512 ←[34mINFO←[0m   tls     served key authentication certificate   {"server_name": "sub.domain.com", "challenge": "tls-alpn-01", "remote": "18.118.160.75:38814", "distributed": false}
2022/05/18 19:57:44.771 ←[34mINFO←[0m   tls     served key authentication certificate   {"server_name": "sub.domain.com", "challenge": "tls-alpn-01", "remote": "54.68.50.156:58910", "distributed": false}
2022/05/18 19:57:44.781 ←[34mINFO←[0m   tls     served key authentication certificate   {"server_name": "sub.domain.com", "challenge": "tls-alpn-01", "remote": "64.78.149.164:52148", "distributed": false}
2022/05/18 19:57:45.166 ←[34mINFO←[0m   tls.issuance.acme.acme_client   validations succeeded; finalizing order {"order": "https://acme-v02.api.letsencrypt.org/acme/order/549468526/89836169286"}
2022/05/18 19:57:46.843 ←[34mINFO←[0m   tls.issuance.acme.acme_client   successfully downloaded available certificate chains    {"count": 2, "first_url": "https://acme-v02.api.letsencrypt.org/acme/cert/04ee0fd1c7741d1b28c6e2eb0251f1fdde78"}
2022/05/18 19:57:46.845 ←[34mINFO←[0m   tls.obtain      certificate obtained successfully       {"identifier": "sub.domain.com"}
2022/05/18 19:57:46.845 ←[34mINFO←[0m   tls.obtain      releasing lock  {"identifier": "sub.domain.com"}
2022/05/18 20:00:30.302 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:00:30.303 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:00:30.742 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:00:30.742 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:01:46.981 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:01:46.981 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:01:47.435 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:01:47.436 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:07:36.365 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:07:36.366 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:07:36.815 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}
2022/05/18 20:07:36.815 ←[31mERROR←[0m  tls.issuance.acme       looking up info for HTTP challenge      {"host": "sub.domain.com", "error": "no information found to solve challenge for identifier: sub.domain.com"}

And this is the log file for the connections after this run:

> 2022/05/18 19:59:07.252	error	http.log.access.log0	handled request	{"request": {"remote_ip": "139.162.178.87", "remote_port": "41054", "proto": "HTTP/1.1", "method": "GET", "host": "sub.domain.com", "uri": "/.git/config", "headers": {"User-Agent": ["Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36 OPR/28.0.1750.40"], "Accept-Charset": ["utf-8"], "Accept-Encoding": ["gzip"], "Connection": ["close"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "server_name": "sub.domain.com"}}, "user_id": "", "duration": 0.3042118, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy", "Kestrel"], "Content-Length": ["0"], "Date": ["Wed, 18 May 2022 19:59:06 GMT"], "X-Response-Time-Ms": ["0"]}}
2022/05/18 20:00:30.743	error	http.log.access.log0	handled request	{"request": {"remote_ip": "91.199.212.132", "remote_port": "36014", "proto": "HTTP/1.1", "method": "GET", "host": "sub.domain.com", "uri": "/.well-known/acme-challenge/6XoagF_9BNMl25z4jCXGfzUPFTD1jZLeIcvh7TmcU4I", "headers": {"Connection": ["close"], "User-Agent": ["acme.zerossl.com/v2/DV90"], "Cache-Control": ["no-cache"], "Referer": ["http://sub.domain.com/.well-known/acme-challenge/6XoagF_9BNMl25z4jCXGfzUPFTD1jZLeIcvh7TmcU4I"], "Accept-Encoding": ["gzip"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4867, "proto": "", "server_name": "sub.domain.com"}}, "user_id": "", "duration": 0.0017499, "size": 0, "status": 404, "resp_headers": {"X-Response-Time-Ms": ["0"], "Content-Length": ["0"], "Date": ["Wed, 18 May 2022 20:00:30 GMT"], "Server": ["Caddy", "Kestrel"]}}
2022/05/18 20:01:47.441	error	http.log.access.log0	handled request	{"request": {"remote_ip": "91.199.212.132", "remote_port": "35852", "proto": "HTTP/1.1", "method": "GET", "host": "sub.domain.com", "uri": "/.well-known/acme-challenge/XLBWkwv8_aP5LFIdAHtukqSypcxXhLSLgXhPBuRNbuk", "headers": {"User-Agent": ["acme.zerossl.com/v2/DV90"], "Cache-Control": ["no-cache"], "Referer": ["http://sub.domain.com/.well-known/acme-challenge/XLBWkwv8_aP5LFIdAHtukqSypcxXhLSLgXhPBuRNbuk"], "Accept-Encoding": ["gzip"], "Connection": ["close"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4867, "proto": "", "server_name": "sub.domain.com"}}, "user_id": "", "duration": 0.005975, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy", "Kestrel"], "Content-Length": ["0"], "Date": ["Wed, 18 May 2022 20:01:47 GMT"], "X-Response-Time-Ms": ["0"]}}
2022/05/18 20:07:37.120	error	http.log.access.log0	handled request	{"request": {"remote_ip": "91.199.212.132", "remote_port": "44280", "proto": "HTTP/1.1", "method": "GET", "host": "sub.domain.com", "uri": "/.well-known/acme-challenge/5Pz8fujj1TSVL06a8cDPpeado0OcZRMGV2Jcvs-h7Kw", "headers": {"Cache-Control": ["no-cache"], "Referer": ["http://sub.domain.com/.well-known/acme-challenge/5Pz8fujj1TSVL06a8cDPpeado0OcZRMGV2Jcvs-h7Kw"], "Accept-Encoding": ["gzip"], "Connection": ["close"], "User-Agent": ["acme.zerossl.com/v2/DV90"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4867, "proto": "", "server_name": "sub.domain.com"}}, "user_id": "", "duration": 0.3046943, "size": 0, "status": 404, "resp_headers": {"Server": ["Caddy", "Kestrel"], "Content-Length": ["0"], "Date": ["Wed, 18 May 2022 20:07:36 GMT"], "X-Response-Time-Ms": ["0"]}

I'll greatly appreciate help with this.
Thank you :)

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
