### ISSUE TITLE
redirect the old url to new url using caddy 2

### ISSUE THREAD

**Issue by rupasrinunna** [caddyserver/caddy#4807]
My Project under Hybrid Cloud using i3 access ( tex-caddy & tex services). 
Working Mechanism : when browser hit the url it check for sso (single sign in option) then only user able to login the url.
Now domain change is happen in our project. New url is up & working fine.
Now i need to redirect old url to new url and skip the sso for this i need to use the caddy2.
How can redirect old to new with this https://caddyserver.com/docs/caddyfile/directives/redir.

I am looking for help

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
