### ISSUE TITLE
Caddy on Windows cannot access FastCGI on Linux

### ISSUE THREAD

**Issue by AndreKR** [caddyserver/caddy#4813]
How to reproduce:
* Have a php-fpm server on Linux, for example by running the official php-fpm Docker image:
```shell
docker run -d --name caddy-issue-test -p 1234:9000 php:7.4-fpm
docker exec -it caddy-issue-test /bin/bash
echo 'hello world' > foo.php
exit
```
* Create a Caddyfile (`192.168.0.1` is the host where the Docker daemon runs):
```text
:81
php_fastcgi 192.168.0.1:1234 {
	root /var/www/html
}
```
* Run `caddy run`
* Access http://localhost:81/foo.php in a browser.

Expected result:
"hello world" is displayed

Actual result:
"File not found." is displayed.

Further investigation shows that the reason for this is that Caddy prepends the given root with `C:` and converts the slashes:

![image](https://user-images.githubusercontent.com/1188538/170356226-922e4428-19da-4503-9c79-ee1bf339991a.png)

**Comment by francislavoie** [comment]
I don't really find this surprising. I don't see how Caddy could possibly know that it should use the path style of the other system. I do find it surprising that someone's trying this though!

We're using Go's stdlib for path operations, which is compiled to use the path style for the target OS. So Caddy for Windows will use Windows paths.

I don't really see a legitimate reason for mixing Windows and Linux this way. Either run Caddy in a docker container as well (so it's running in Linux as well) or run PHP in Windows.

**Comment by mholt** [comment]
Hm, yeah, I'm not sure why/how Caddy would know the target is on a completely different operating system. How do you do this with nginx or Apache?

**Comment by AndreKR** [comment]
It doesn't have to know, it could just pass on the path verbatim.

**Comment by mholt** [comment]
What do you mean "pass on the path verbatim" though? Arguably that's what Caddy is doing. The SCRIPT_FILENAME variable [MUST contain](https://www.php.net/manual/en/reserved.variables.server.php):

> The absolute pathname of the currently executing script. 

So Caddy is making the filename absolute and passing it through, as-is.

Have you tried setting the header manually?

**Comment by AndreKR** [comment]
Indeed that seems to be a feasible workaround:
```
:81
php_fastcgi 192.168.0.1:1234 {
	env SCRIPT_FILENAME /var/www/html/{file}
}
```
