### ISSUE TITLE
caddy doesn't want to listen with TLS

### ISSUE THREAD

**Issue by panekj** [caddyserver/caddy#4822]
Caddyfile
```
{
    debug
    auto_https disable_redirects
    log {
        output file /var/log/caddy/server.log
    }
}

https://marten.bobcat-delta.ts.net:8888 {
    reverse_proxy http://127.0.0.1:8887
}
```

`{"level":"debug","ts":1654082517.7955494,"logger":"http","msg":"starting server loop","address":"[::]:8888","http3":false,"tls":false}`

caddy 2.5.1

**Comment by mholt** [comment]
I think I have a working fix for this, but I am going to try to knock out #4779 while I'm at it.

**Comment by mholt** [comment]
@panekj Can you give the latest commits a try? Based on my testing it should be fixed now!

**Comment by panekj** [comment]
Haven't tried yet but perhaps having `tls` directive inside block could force TLS no matter what port/protocol it is?
e.g.:
```
matcher:8888 {
    tls
}
```

**Comment by mholt** [comment]
Thanks for testing the fix. The TLS directive already does that, but it's not needed as TLS is the default.

**Comment by mholt** [comment]
@panekj You'll need to build from the latest commits from source to get the fix. And you don't need `tls`.
