### ISSUE TITLE
reverse proxy: when timeout occurs Caddy responses as 502 Bad Gateway

### ISSUE THREAD

**Issue by dtelyukh** [caddyserver/caddy#4823]
When I use timeout limit in my Caddyfile and upstream server is slow, Caddy responses in such way:

`HTTP 502: net/http: timeout awaiting response headers`
`HTTP 502: dial tcp <some IP address>:443: i/o timeout`

I think, it should be 504 Gateway Timeout. Because HTTP code 504 means, that I should increase timeout limit.

**Comment by mholt** [comment]
Probably a good idea. Thanks @dtelyukh . Can you verify that #4824 resolves this for you?

**Comment by dtelyukh** [comment]
@mholt, thanks! It works good for me.
