### ISSUE TITLE
loading initial config: decoding request body: invalid character '*' looking for beginning of value

### ISSUE THREAD

**Issue by puzhengwu** [caddyserver/caddy#4833]
*.a.abc.com
gzip
reveres_proxy www.abc.com

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
