### ISSUE TITLE
Make reverse proxy TLS server name replaceable for SNI upstreams.

### ISSUE THREAD

**Issue by kresike** [caddyserver/caddy#4834]
The basic problem we're trying to solve here is the case when we're using dynamic upstreams to proxy many sites from multiple backends using HTTPS and SNI.

My relevant caddy config snippet:

```
:443 {
	reverse_proxy {
		dynamic srv {
			proto tcp
			service {host}
			name proxy.example.com
		}		
	}
}

```
The original problem is, that while caddy does allow (and does so out of the box) replacement of the Host header in the HTTP request sent upstream, it does not set the servername in the TLS client. This results in an error (421 in my case, reported by apache), looking something like below:
```
AH02032: Hostname backend01.example.com provided via SNI and hostname webpage01.example.com provided via HTTP have no compatible SSL setup
```
After implementing the fix, one can use the configuration snippet below to solve the issue:

```
:443 {
	reverse_proxy {
		dynamic srv {
			proto tcp
			service {host}
			name proxy.example.com
		}		
		transport http {
			tls_server_name {host}
		}
	}

}

```
This is a fairly simple fix, that I've already done. Will open a PR for it.

**Comment by mholt** [comment]
We pre-allocate the TLSConfig at Provision time for efficiency. The only known, correct solution is to generate a TLSConfig for every connection. We can do that, but I've hesitated due to the potential performance implications. It wouldn't be much, but I'd like to do it carefully.

**Comment by kresike** [comment]
Thanks for the review @mholt 
I need this done, so let me look into it, maybe I can come up with a better solution.

**Comment by mholt** [comment]
Ok, I'll be happy to review a PR. I might be interested in some profiles but we'll have to see!

**Comment by kresike** [comment]
@mholt please see my second solution. Not the prettiest code I've ever written but it should be loads better than the previous attempt.

**Comment by francislavoie** [comment]
I think it would be a mistake to allow both HTTP and HTTPS at the same time. The srv should only do one or the other, and configure Caddy with the appropriate transport accordingly.

**Comment by kresike** [comment]
Ok, I've thought about this a bit more, and I don't think there is any redesign needed. We can simply fix it using an if statement.

**Comment by kresike** [comment]
Added a small change that fixes this behaviour. A small price to pay is that HTTPS cannot be used on port 80 on the upstreams, which I think is better than messing up protocols.

**Comment by mholt** [comment]
@kresike The revised PR is looking much better! Thank you. Pretty close to merging it in.

**Comment by kresike** [comment]
The original issue is fixed, thanks @mholt for accepting my work.
I will move the TLS vs dynamic SRV upstreams question to another issue.

**Comment by mholt** [comment]
Thanks for the contribution!
