### ISSUE TITLE
reverse_proxy upstram

### ISSUE THREAD

**Issue by rainbow2019s** [caddyserver/caddy#4837]
I have a db in kubernetes,and I want visit by windows  client.
Caddyfile 
:3306 {
   reverse_proxy  mariadb-0.mariadb-headless.kube-public.svc.cluster.local:3306
}
but I can not access

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by francislavoie** [comment]
I see `mariadb` in there. Caddy is an _HTTP_ server. Databases don't use HTTP as a transport, they use TCP. You won't be able to proxy database connections with an HTTP server. You could use https://github.com/mholt/caddy-l4 though, but I don't think you're approaching this the right way.
