### ISSUE TITLE
The `fmt` warning was only added in v2.3.0 I believe.

### ISSUE THREAD

**Issue by DongSunshineBoy** [caddyserver/caddy#4840]
The `fmt` warning was only added in v2.3.0 I believe.

All this warning is saying is that we recommend you run `caddy fmt` on your config to clean up the syntax. It's not fool-proof, but it's a suggestion that maybe you should run it so that it has more consistent style.

> My configuration no longer works.

What do you mean? What no longer works? Any errors in your logs?

Warnings are not errors, they're just suggestions that something _might_ be wrong, but they can generally be ignored.

_Originally posted by @francislavoie in https://github.com/caddyserver/caddy/issues/4416#issuecomment-967485306_

**Comment by DongSunshineBoy** [comment]
I counter this problem, use bankspace in the every line config file last, maybe you are not use \r signal in the tail of code line.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
@DongSunshineBoy What did you do to make this new issue? Why didn't you just reply in the original issue?
