### ISSUE TITLE
Feature request: don't use TLS on certain dynamic upstream ports received in SRV records

### ISSUE THREAD

**Issue by kresike** [caddyserver/caddy#4842]
The problem I'm facing when using dynamic upstreams with SRV records is that the http transport module doesn't have any way of determining whether to use TLS for the upstream or not based on the port number received from the SRV record.
The current implementation allows us to either configure TLS and handle all ports as HTTPS or not configure TLS and that makes all upstream requests to go over HTTP.

I'm proposing a new configuration option that permits specifying an optional list of ports which will be contacted using HTTP even when TLS is configured.

Will submit a PR shortly.

**Comment by mholt** [comment]
Thanks for the issue and the PR!
