### ISSUE TITLE
localhost:80/api/user/ ok，localhost:80/api/user not ok，why

### ISSUE THREAD

**Issue by qwa567** [caddyserver/caddy#4844]
this is my Caddyfile

```
localhost:80 {
    route /api/* {
    	uri strip_prefix /api
    	reverse_proxy xxx.xxx.xx.xx:8080
    }
}
```

Have a friend Do you know why?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
