### ISSUE TITLE
Build with docker, can't manage Caddy with API

### ISSUE THREAD

**Issue by haonanor** [caddyserver/caddy#4851]
docker run -d -p 80:80 -p 443:443  -p 2019:2019\
    -v $PWD/Caddyfile:/etc/caddy/Caddyfile \
    -v $PWD/site:/srv \
    -v $PWD/data:/data \
    -v $PWD/config:/config \
    caddy

Here is my build command

Question
➜  caddy curl -X POST "http://localhost:2019/stop"
curl: (52) Empty reply from server
➜  caddy curl http://localhost:2019/config
curl: (52) Empty reply from server
➜  caddy

How should this be handled？
Thanks

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Caddy listens on `localhost:2019` by default, which means only requests from _inside_ the container can connect. You need to configure Caddy changing the admin endpoint to `0.0.0.0:2019`.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by haonanor** [comment]
thinks

**Comment by haonanor** [comment]
thanks
