### ISSUE TITLE
JSON type headers are filtered out when "import" directive is used

### ISSUE THREAD

**Issue by Inetol** [caddyserver/caddy#4862]
## Version
`v2.5.1 h1:bAWwslD1jNeCzDa+jDCNwb8M3UJ2tPa8UZFFzPVmGKs=`

## Caddyfile
There are more settings that are irrelevant and have been stripped out of the config.
```
...

# Snippet "headers"
(headers) {
    header {
        Report-To `{"endpoints":[{"url":"https://inetol.report-uri.com/a/d/g"}],"group":"core","include_subdomains":true,"max_age":31536000}`
        NEL `{"include_subdomains":true,"max_age":31536000,"report_to":"core"}`

        # Test header one
        X-Test-ONE `{"this":true,"that":0}`
    }
}

...

example.com {
    # Import "headers" snippet
    import headers

    # Add additional test header two
    header X-Test-TWO "\{\"this\":false,\"that\":1\}"

    respond / "Hi"
    root * /dev/null
    file_server
}
```

## Issue
When requesting this webpage, all headers should be displayed with the values assigned in the Caddyfile. However, all headers that are imported from a snippet/file and their values contain JSON will appear empty or malformed.

### Expected
```
HTTP/2 200 OK
nel: {"include_subdomains":true,"max_age":31536000,"report_to":"core"}
report-to: {"endpoints":[{"url":"https://inetol.report-uri.com/a/d/g"}],"group":"core","include_subdomains":true,"max_age":31536000}
x-test-one: {"this":true,"that":0}
x-test-two: {"this":false,"that":1}
content-length: 2
date: Tue, 05 Jul 2022 11:12:50 GMT
```

### Got
```
HTTP/2 200 OK
nel: 
report-to: ],"group":"core","include_subdomains":true,"max_age":31536000}
x-test-one: 
x-test-two: {"this":false,"that":1}
content-length: 2
date: Tue, 05 Jul 2022 11:12:50 GMT
```

## Annex
Related to this issue: #2063

**Comment by francislavoie** [comment]
I think we just need to adjust `import` to use `ReplaceKnown` (or whatever it's called) instead of `ReplaceAll` so that it only replaces `{args.*}` placeholders and leaves other things intact.

**Comment by francislavoie** [comment]
Okay I looked into it, it's not a bug with `import`, but rather a bug with the `header` directive's placeholder replacement.
