### ISSUE TITLE
`net.TCPConn.SetKeepAlivePeriod` on HTTP(S) listener

### ISSUE THREAD

**Issue by karmanyaahm** [caddyserver/caddy#4863]
`transport.http.keepalive_interval`  `defines how to communicate with the backend. Default is http`.
Something similar is needed for client (my mobile device) -> Caddy, because by default Go uses a 15-second interval, which is unnecessary traffic for a battery-powered device that could be optimized away.

Nginx and Apache both use the Linux default value, 2 hours.

I can attempt a PR soon.

Reference: https://caddy.community/t/tcp-keepalives-from-client-to-caddy-not-to-upstream/16466

**Comment by karmanyaahm** [comment]
Also from the forum post

> It sets both Idle time and Retry interval. The Ping amount remains at the system default. So when I set it to, say, 5 * time.Second, it waits for 5 seconds, pings and waits for another 5. And 8 more pings. I require more flexibility.

> Doing that requires system calls. Which we can do… but it’s a little more complicated.

I don't need that. In fact, I doubt many applications would, because most modern applications have their own keepalive system (such as websocket ping/pongs) built on top. Disabling/increasing the TCP keepalive time is what is important to prevent any more traffic than the application layer needs.

**Comment by mholt** [comment]
Going to close this issue since your PR was merged. It was merged into a feature branch that I expect will also be merged, and since this isn't actionable at this point, I will close it for now. Thanks for contributing!
