### ISSUE TITLE
Reverse proxy is 404 for google

### ISSUE THREAD

**Issue by istangheng** [caddyserver/caddy#4874]
version: v2.5.1 h1:bAWwslD1jNeCzDa+jDCNwb8M3UJ2tPa8UZFFzPVmGKs=

```
google.example.com {
        reverse_proxy https://www.google.com.hk {
                header_up X-Real-IP {remote}
                header_up X-Forwarded-For {remote}
                header_up User-Agent {>User-Agent}
                header_up Accept-Language zh-CN
                header_up Accept-Encoding identity
        }
}
```

I have added a DNS A record for this domain google.example.com, and this domain reverse proxy for google is always 404

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

For proxying to an HTTPS upstream, see the docs: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#https
