### ISSUE TITLE
About the problem that the performance of http3 is lower than that of http2.

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#4876]
My browser is Chrome102.
my os is windows 11.
my cpu is intel i5-6200u .

caddy version 2.5.1

https://github.com/librespeed/speedtest-go

speedtest-go version 1.1.5

When I used the caddy reverse proxy speedtest-go service, I found that the performance of using http3 was less than half that of http2.

https://www.rfc-editor.org/rfc/rfc9114.html

**Comment by masx200** [comment]
```
{
	debug
	local_certs
	auto_https disable_redirects
	email xxxxxxxxxxxxxxxxxxxxxx

	acme_dns xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

	servers {
		protocol {
			experimental_http3
		}
	}
}

https://xxxxxxxxxx:xxxx {
	tls {
		issuer acme
	}
	encode zstd gzip
	header {
		x-xss-protection 1;mode=block
		Content-Security-Policy upgrade-insecure-requests

		Strict-Transport-Security max-age=31536000

		X-Content-Type-Options nosniff

		X-Frame-Options DENY

		Referrer-Policy no-referrer-when-downgrade
	}
	reverse_proxy https://xxxxxxxx:xxxx {
		transport http {
			tls_insecure_skip_verify
			tls_server_name xxxxxxxxxxxxxxxxxxxx
		}

		trusted_proxies private_ranges
	}
}

```

**Comment by bt90** [comment]
Could you add more details? Is the backend running on the same host ad caddy? From where did you execute the test? What kind of OS/hardware is involved?

**Comment by mholt** [comment]
This isn't particularly surprising. H3 is mostly only faster for high latency links. Otherwise it's more complex in general.

I think http3 performance issues should be reported upstream though, since we just use the library: https://github.com/lucas-clemente/quic-go

**Comment by masx200** [comment]
This may be related to the fact that http3 consumes more cpu resources.

**Comment by masx200** [comment]
I have both backend services caddy and speedtest-go running on the same computer. my os is windows 11.
my cpu is intel i5-6200u .

My client is running on a Snapdragon 865 Android 12 phone, tested in LAN, using Chrome 102.


![IMG_20220710_085505](https://user-images.githubusercontent.com/34191203/178127427-3598c748-4d3b-46e1-933f-3d21fc810ecc.jpg)

![IMG_20220710_085455](https://user-images.githubusercontent.com/34191203/178127437-fb594275-2013-440a-8a8f-fd7bbe6806b3.jpg)

**Comment by mholt** [comment]
If you want to collect a profile, that would be helpful. We can't do much by guessing what might be slow. It could be a protocol issue, or it could be some inefficiencies in the library we're using. But again, I don't think that's particularly surprising as HTTP/3 only barely became standardized recently, and has only been a draft protocol. Optimizations are probably a lower priority.

**Comment by otbutz** [comment]
@marten-seemann is this something ticket worthy for quic-go or are those results to be expected?

**Comment by otbutz** [comment]
> Localhost performance is not at all indicative of real-world performance.

i agree but OP stated that his client is *not* on the same host:

> My client is running on a Snapdragon 865 Android 12 phone, tested in LAN, using Chrome 102.

So we end up with a very typical reverse proxy setup IMHO.

**Comment by masx200** [comment]
@otbutz  

service <-- (HTTP/2 via localhost) --> caddy <-- (HTTP/3 via LAN) --> client

**Comment by mholt** [comment]
@otbutz Are you sure? @masx200 also says:

> I have both backend services caddy and speedtest-go running on the same computer.

In any case, I do kind of agree with Marten here. HTTP/3 is known to use more CPU to reduce latency on the wire. LANs and localhost won't have latency, so yes it's more likely to bottleneck at CPU. I think this is just documenting a known fact of the protocol rather than an issue to be fixed.

However, you're welcome to collect an actual profile sometime and maybe contribute optimizations to the HTTP/3 lib?

(Closing, but feel free to continue discussions if needed.)

**Comment by otbutz** [comment]
I think Martin's objection was more directed against pure localhost tests, since HTTP/3 has a disadvantage here with a fixed MTU, as far as I'm not mistaken. But either way, it's an upstream issue if anything at all.

**Comment by zephyros-dev** [comment]
Just want to add that my previous speedtest with HTTP/2 almost saturate the bandwidth of Gigabit LAN cable network (~960mbps download/ 640mbps upload), but with the newer HTTP/3 version it falls down to about 200mbps for download/upload, so much more than half. After some digging I found this inside the caddy logs:
```
{"level":"info","ts":1664899232.3432162,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
```
I follow the recommendation to increase the Linux buffer size, and the results improved significantly (~840mbps download/ 440mbps upload). My stack is like this:
```
service <-- rootless podman network --> caddy <-- rootless podman port 80/443 binding --> (HTTP/3 via LAN) --> client
```
Not sure why the upload speed is so slow, but that's as far as I'm willing to investigate for now.

**Comment by mholt** [comment]
Yeah, the buffer size warning is critical if you want the best performance.

Also note that a WIP CL to the Go project will offer even more improvements to performance: https://github.com/lucas-clemente/quic-go/issues/3563

**Comment by bt90** [comment]
The current master might also be a bit faster with quic-go v0.29.0: https://github.com/lucas-clemente/quic-go/pull/3467#issuecomment-1176574094

**Comment by bt90** [comment]
@masx200 @zephyros-dev caddy 2.6.2 has been released with quic-go 0.29.1.

**Comment by mholt** [comment]
[quic-go 0.30](https://github.com/lucas-clemente/quic-go/releases/tag/v0.30.0) has some significant performance improvements, it looks like.

**Comment by bt90** [comment]
Also https://github.com/lucas-clemente/quic-go/pull/3524 which is scheduled for v0.31.0

**Comment by lxhao61** [comment]
> ```
> {
> 	debug
> 	local_certs
> 	auto_https disable_redirects
> 	email xxxxxxxxxxxxxxxxxxxxxx
> 
> 	acme_dns xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> 	servers {
> 		protocol {
> 			experimental_http3
> 		}
> 	}
> }
> 
> https://xxxxxxxxxx:xxxx {
> 	tls {
> 		issuer acme
> 	}
> 	encode zstd gzip
> 	header {
> 		x-xss-protection 1;mode=block
> 		Content-Security-Policy upgrade-insecure-requests
> 
> 		Strict-Transport-Security max-age=31536000
> 
> 		X-Content-Type-Options nosniff
> 
> 		X-Frame-Options DENY
> 
> 		Referrer-Policy no-referrer-when-downgrade
> 	}
> 	reverse_proxy https://xxxxxxxx:xxxx {
> 		transport http {
> 			tls_insecure_skip_verify
> 			tls_server_name xxxxxxxxxxxxxxxxxxxx
> 		}
> 
> 		trusted_proxies private_ranges
> 	}
> }
> ```

Configure the reverse_proxy module in this way to support HTTP/3? Or is it supported by version 2.5.1, [which is not supported by the current version](https://github.com/caddyserver/caddy/issues/5086)?

**Comment by francislavoie** [comment]
@lxhao61 I don't understand what you're trying to say. Please elaborate.

I'm not sure I understand why you're commenting here if you want to to discuss H3 transport support in `reverse_proxy`, that discussion should happen in the issue you linked, https://github.com/caddyserver/caddy/issues/5086
