### ISSUE TITLE
Caddy returns some HTML elements but no other ressources (0 bytes) (NodeJS served)

### ISSUE THREAD

**Issue by bacloud22** [caddyserver/caddy#4878]
Hi there,
I'm trying to serve a website running on Node ,this is to say all static files are served by Node.
It is really strange because the index page is served (HTML) but then other links are not served and also return 0 bytes.
Other resources (CSS, Scripts, and media) are not served (0 bytes).
Also it is to note, there is no CSP errors because requests are successful and not blocked.
There are no errors on server site too. This is my Caddy configuration:

```js
classifieds22 {
	reverse_proxy / classified-ads:3000
}
```

HTTPS is fine which is a blessing, so I can't be enough thankful for what you have been doing guys !!!!

**Comment by bacloud22** [comment]
the issue was with 

````js
classifieds22 {
	reverse_proxy /* classified-ads:3000
}
```

**Comment by francislavoie** [comment]
See the docs on request matchers: https://caddyserver.com/docs/caddyfile/matchers#syntax

You can omit the matcher altogether in your case.

**Comment by bacloud22** [comment]
Thanks a lot !!
