### ISSUE TITLE
Reverse Proxy fails Google Compute Cloud https healthcheck behind TCP load balancer

### ISSUE THREAD

**Issue by absorbb** [caddyserver/caddy#4886]
Caddy 2.5.2

I try to make Caddy handles all HTTPs in my Google Compute Cloud setup.
So i install caddy behind External TCP load balancer.

Our service relies on client IP. That is why i enable PROXY protocol for load balancer.
and setup https://github.com/mastercactapus/caddy2-proxyprotocol plugin
But once plugin enabled all request must use PROXY protocol that is why i set GCC https health check to use PROXY protocol too,
Problem is that health-check sends `PROXY UNKNOWN` header. and plugin sets client ip to empty value.
https://cloud.google.com/load-balancing/docs/health-checks#optional-flags-hc-protocol-http

Reverse Proxy fails with error:
`preparing request for upstream round-trip: invalid client IP address:`
and there is no way health-check will be passed.

**Comment by francislavoie** [comment]
That doesn't sound like a problem with Caddy, but with the proxy protocol plugin instead.
