### ISSUE TITLE
Custom error page when upstream no available

### ISSUE THREAD

**Issue by inliquid** [caddyserver/caddy#4887]
Hey!

I was able to configure a custom error page when upstream generates an error (say, 500 "Internal Server Error"). But it seems not possible to send a custom page, like `502.html` when upstream is not available. I have found old discussion on community forum saying that it's a limitation of current version. But maybe anything changed since that? Is it documented somewhere? Please advice.

**Comment by francislavoie** [comment]
You can definitely do this, with [`handle_errors`](https://caddyserver.com/docs/caddyfile/directives/handle_errors).

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by inliquid** [comment]
Before raising an issue I always google and look at docs, forums, whatsoever. In this particular case I looked at `caddy.community` using both discourse search engine and googled with `site:caddy.community <blabla>`. I don't have time to fill-in complete experience report just to answer if it's supported or not, and I don't want to share sensitive data which may compromise my project. As I said I found info that feature is not supported. At this moment `caddy` is basically an experiment and I still evaluating if we go for it or no. Mostly because I code in Go for years already and I feel a sympathy. But there are plenty of well-suited alternatives for every single "stupid" case with tons of examples, if documentation or support is a problem.

**Comment by mholt** [comment]
@inliquid I appreciate the effort you took to search the forum.

> As I said I found info that feature is not supported.

I just want to point out... did you notice that the docs page Francis linked to has an example (the very first one, in fact) that does exactly what you are asking? If it's not what you're asking, then we need you to fill out the help template on the forum because clearly we need more information to understand your question:

```
handle_errors {
	rewrite * /{err.status_code}.html
	file_server
}
```

**Comment by inliquid** [comment]
> (No upstream available is 503 btw. You can use a matcher -- also exhibited in the examples on that page -- to limit to just that status code if you want.)

Really?

```
>curl -v https://beta.my.site
*   Trying 1.1.1.1:443...
* Connected to beta.my.site (1.1.1.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1
* schannel: ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: beta.my.site
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< Server: Caddy
< Date: Thu, 14 Jul 2022 00:32:57 GMT
< Content-Length: 0
<
* Connection #0 to host beta.my.site left intact
```
Firefox:
![изображение](https://user-images.githubusercontent.com/6797881/178860297-b489fd6b-d919-4d14-b401-c11b1f12db0f.png)



> I just want to point out... did you notice that the docs page Francis linked to has an example (the very first one, in fact) that does exactly what you are asking? If it's not what you're asking, then we need you to fill out the help template on the forum because clearly we need more information to understand your question:

Maybe it's a question on how docs are structured. I was looking at this because I thought it's more relevant: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy
You can press `Ctrl-F` and look where it mentions `error`. Actually that's where my issue started from. 

Next I found this: https://caddy.community/t/caddy1-proxy-errors-page/6559/6

Which basically remained unanswered and is linked to the issue: https://github.com/caddyserver/caddy/issues/1447, and it's not clear whether it's solved or not and what should I do.

Showing error page when upstream not available is very basic thing and should be pretty simple to my understanding.

**Comment by mholt** [comment]
@inliquid What version of Caddy are you using? The latest version returns 503 when all upstreams are unavailable, instead of 502. Make sure to be using Caddy v2.5.2.

(Thanks for explaining your process. We appreciate it!)

**Comment by inliquid** [comment]
Version:
```
# caddy version
v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=

```
For installation I followed this instruction:
https://caddyserver.com/docs/install#debian-ubuntu-raspbian

>The latest version returns 503 when all upstreams are unavailable, instead of 502

What's the reasoning btw? For instance, Go's `http.TimeoutHandler` returns `http.ServiceUnavailable` 503 code when invoked handler timed out. I'm using my own timeout handler but I follow this convention, and Caddy returning 503 would bring a little mess.

**Comment by mholt** [comment]
@inliquid If you are getting a message in your Caddy logs that says "no upstreams available", then you should be seeing a 503 response. If you do not see that message in your logs, then it is likely that there is another reason you're getting a 502 instead.

**Comment by inliquid** [comment]
I see this (but apparently, there is no upstream available):

```
Jul 13 04:48:53 hostname caddy[7188]: {"level":"error","ts":1657676933.8304255,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:8443: connect: connection refused","request":{"remote_ip":"3.3.3.3","remote_port":"15229","proto":"HTTP/2.0","method":"GET","host":"beta.my.site","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Language":["ru,en;q=0.5"],"Referer":["https://beta.my.site/"],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0"],"Accept-Encoding":["gzip, deflate, br"],"Cookie":[],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["same-origin"],"Te":["trailers"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"beta.my.site"}},"duration":0.000994551,"status":502,"err_id":"ipsmvy3p7","err_trace":"reverseproxy.statusError (reverseproxy.go:1184)"}
```

**Comment by francislavoie** [comment]
"connection refused" means the upstream wasn't reachable. Are you certain you have something listening on that port? Are you doing this in Docker? 127.0.0.1 will only connect to services inside the same container if so (which there never will be since Caddy is the only thing in its own container)

**Comment by francislavoie** [comment]
To be clear, "upstream available" means that some health check (active or passive checks, see the docs) marked an upstream as unavailable. That will result in a `503 Service Unavailable`

If Caddy fails to connect altogether, then it will result in a `502 Bad Gateway`. In this case, the OS tells you right away that there's nothing listening on that port, so it fails instantly.

If Caddy fails to connect because of a timeout (e.g. connecting to a remote server and it can't be reached) then you'll see a `504 Gateway Timeout`.

**Comment by mholt** [comment]
That's a good point, I forgot that it might be necessary to enable some sort of health check.

**Comment by inliquid** [comment]
I don't understand what you are writing here. "Upstream" is stopped, dead, no processes, nothing listens on that port. That's what causes "connection refused" according to tcp/ip specs (sent RST in reply to SYN). 

Which healthchecks are you talking about? What timeout? It's "connection refused". 

There is no docker in that system.

**Comment by francislavoie** [comment]
See the docs: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing

Caddy keeps track of the health of your upstreams if you configure health checking, which is what determines whether an upstream is available. If it's marked unavailable, it won't be selected. If no upstream is available to try, then Caddy will emit a 503.

**Comment by inliquid** [comment]
I haven't configured any healthchecking, there is single reverse_proxy directive and that's basically it:
```
        reverse_proxy https://localhost:8443 {
                transport http {
                        tls_insecure_skip_verify
                }

                @error status 500 503 429 404
                handle_response @error {
                        root * /my/site/html
                        rewrite * /{rp.status_code}.html
                        file_server {
                                status {rp.status_code}
                        }
                }
        }
```

**Comment by mholt** [comment]
After looking at the code, it does seem that Francis is right, but it's subtle/nuanced.

We only emit "no upstreams available" if `upstream` and `proxyErr` are nil:

https://github.com/caddyserver/caddy/blob/7d1f7771c9961dc6607a6ac5894b9c3195c25fcf/modules/caddyhttp/reverseproxy/reverseproxy.go#L479-L483

Generally for this to happen, all the upstreams need to be marked as unavailable, because the load balancer chooses an upstream it knows to be "available". If the load balancer can't find any available upstreams and doesn't return any backend, then you'll hit that condition.

@inliquid I would recommend enabling a simple passive health check for now. Maybe there's precedent to return HTTP 503 even if health checking is disabled and no connection could even be established to any of the backends. That'd basically be us hard-coding a special case, which I try to avoid, but I dunno. Thoughts?

**Comment by inliquid** [comment]
It's more a question not about returning code, but how does `caddy` treat this case. In my view this is "no upstreams available" because, that's what happening on the ground - single configured backend is dead. As for codes, like I said I wouldn't use 503 in my app because it mixes with handler timeouts so I would probably configure it like this:
```
        handle_errors {
                root * /my/site/html
                rewrite * /maintenance.html
                file_server {
                        status 502
                }
        }
```

Not sure but should work?

**Comment by francislavoie** [comment]
Yeah, that should work.
