### ISSUE TITLE
SMTP Proxy Module?

### ISSUE THREAD

**Issue by infogulch** [caddyserver/caddy#4888]
I think it would be neat if Caddy could be used as a mail server reverse proxy that could handle all the TLS and maybe even the DNS configuration automatically.

Maybe it could be implemented as a Caddy 2 module. Matt from 2020 seems to agree with me on this issue on the maddy mail server repo:

[Automatic TLS with LetsEncrypt (comment)](https://github.com/foxcpp/maddy/issues/3#issuecomment-666012813)

> PS. I do think a mail server would make a fine Caddy 2 module

In this issue, the maddy maintainer lays out a path to implement this kind of configuration:

[Documentation for TLS certificates managed by Caddy](https://github.com/foxcpp/maddy/issues/296)

> Is it possible in theory/in practice for maddy to delegate dealing with certificates to caddy?

> caddy would need to implement SMTP and IMAP proxy functionality with support for some reverse proxy indication (e.g. HAProxy PROXY or Postfix's XCLIENT extensions). maddy would need to support the latter.

The implementation on maddy's side seems to be [getting along well](https://github.com/foxcpp/maddy/issues/369).

Are the Caddy-side requirements reasonable and feasible to implement as a Caddy 2 module?

**Comment by francislavoie** [comment]
Caddy at its core is just a configuration manager, basically.

For example, there's the https://github.com/mohammed90/caddy-ssh plugin which is a Caddy "app".

Caddy happens to ship with HTTP and TLS apps by default which is what people know it best for. But it can do anything, really.

I'm not really seeing anything actionable in this issue so I'll close it, but feel free to continue discussion.

**Comment by mholt** [comment]
Yes, Caddy would be very suitable for this!

**Comment by infogulch** [comment]
I would like to discuss the necessary implementation requirements and organization of this app.

PROXY is a standard for a 'dumb' proxy for TCP that provides the forwarded host with details about the upstream connection like IP protocol, address, and port -- as in [HTTP's `X-Forwarded-For`](https://en.wikipedia.org/wiki/X-Forwarded-For) -- while remaining agnostic to the application protocol. It does this by prepending each newly-opened stream with a one-time [^1] header containing these details, which the receiving application expects, parses, and trims before further interpreting its own protocol.

<details>
<summary>Notes from the document published by haproxy:

https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt</summary>
> Relaying TCP connections through proxies generally involves a loss of the
original TCP connection parameters such as source and destination addresses,
ports, and so on. Some protocols make it a little bit easier to transfer such
information. For SMTP, Postfix authors have proposed the XCLIENT protocol [1]
which received broad adoption and is particularly suited to mail exchanges.
For HTTP, there is the "Forwarded" extension [2], which aims at replacing the
omnipresent "X-Forwarded-For" header which carries information about the
original source address, and the less common X-Original-To which carries
information about the destination address.

> the protocol simply consists in an easily parsable header placed
by the connection initiator at the beginning of each connection. The protocol
is intentionally stateless in that it does not expect the sender to wait for
the receiver before sending the header, nor the receiver to send anything back
</details>

Perhaps a general implementation of PROXY protocol as its own app (like caddy-ssh mentioned above) would be a good first step. At the least we would want to be able to layer it with TLS. And honestly "PROXY" isn't the best name for this plugin.

After that there may still be use for an SMTP-specific extension that provides special support for mail-related proxying tasks. I'm not sure what tasks, exactly. Maybe signing outgoing emails for anti-spam validation? Maybe auto-configuring DNS? Something else? It would be awesome if this could be built into the fully-configured-by-default "automatic mail proxy", like how caddy blazed a similar trail for https.

[^1]: Tangentially, that might cause issues trying to proxy a QUIC-based client connection to a TCP backend.

**Comment by francislavoie** [comment]
The https://github.com/mholt/caddy-l4 app supports PROXY protocol.

And there's a PROXY protocol plugin for Caddy's HTTP server as well https://github.com/mastercactapus/caddy2-proxyprotocol

**Comment by infogulch** [comment]
Setting up a mailserver requires a lot of DNS configuration. Given the `dynamic_dns` module that automatically configures A/AAAA records, and the fact that caddy can perform the [DNS-01 challenge](https://caddyserver.com/docs/automatic-https#dns-challenge) with [various providers](https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148), would it be possible to write an app that automatically maintains these mail-related DNS records?

**Comment by mholt** [comment]
@infogulch Yes. That's what libdns can do for you: https://github.com/libdns

**Comment by ksylvan** [comment]
> The https://github.com/mholt/caddy-l4 app supports PROXY protocol.
> 
> And there's a PROXY protocol plugin for Caddy's HTTP server as well https://github.com/mastercactapus/caddy2-proxyprotocol

This is now in the Caddy core, yes? @francislavoie 

https://caddyserver.com/docs/json/apps/http/servers/listener_wrappers/proxy_protocol/

**Comment by francislavoie** [comment]
Yes proxy protocol is built in. L4 is still separate for the time being.

**Comment by ksylvan** [comment]
@francislavoie I'm trying to integrate Caddy as reverse proxy for a stack of Docker Compose containers providing smtp, imaps, etc., and a Web UI for Postfixadmin served from `mail.mydomain`, etc, along with Wordpress being served from `www.mydomain`

What's the easiest/best way to do this using Caddy?

**Comment by francislavoie** [comment]
A thread from 2 years ago is not an appropriate place to ask for help. Ask on the forums and fill out the help topic template.
