### ISSUE TITLE
Reverse order of Stop() and Cleanup() (context cancel)?

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#4891]
Currently when a config is unloaded (i.e. when config is reloaded or the process is exiting), Caddy stops all running apps (`Stop()`) _and then_ cancels the config's associated context (`cancelFunc()`, which runs `Cleanup()` for each module loaded in that context):

https://github.com/caddyserver/caddy/blob/7d1f7771c9961dc6607a6ac5894b9c3195c25fcf/caddy.go#L636-L645

I remember debating years ago when I designed Caddy 2 what the proper order should be here, or if there should even be a `Stop()` method on apps at all (since `Cleanup()` is cancelled anyway when the context is cancelled). However, it made sense to have a `Stop()` since we have a `Start()`, and I think may be beneficial to have two phases of unloading (kind of like how apps have 2 phases of loading: `Provision()` and then `Start()`). The order in which modules are "cleaned up" is arbitrary.

Since all modules other than Apps are guest modules of, or reliant upon, their App/host module, I wonder if it makes sense to call `Cleanup()` first, before unloading the top-level app modules.

For example, does it make sense to leave HTTP handlers running after their servers are stopped? Or should the HTTP server be stopped after all the handlers clean themselves up first?

A quick search in this repo indicates that you can count on 1 hand the number of modules that implement `Stop()` and the number of modules that implement `Cleanup()`.

Anyway, just wanted to put this braindump out there.

**Comment by mholt** [comment]
Meh, already having second thoughts.

Shutting down the HTTP server involves calling `http.Server.Shutdown()` which stops accepting new connections and gracefully closes existing connections. If we clean up the handlers before that, there's a chance the still-active connections could lose state that is needed to finalize them (for example).

I initially brought this up because I'm implementing an enhancement to the reverse_proxy module that will keep track of active connections (such as websockets or anything hijacked) and make sure they are gracefully terminated (if possible) and then closed when the server is shutting down. It seems elegant to do this in Cleanup(), but if the HTTP server has already terminated its listener in Stop(), then there'd be no way to send a Close frame after that... right?

I might be wrong. Maybe the connection is still active/non-idle, so the server hasn't closed it yet. In fact, I haven't been able to exhibit my hypothesized behavior yet.

So I guess I will close this, and leave the issue here merely to document my brief flirtation with this idea.

**Comment by francislavoie** [comment]
> I might be wrong. Maybe the connection is still active/non-idle, so the server hasn't closed it yet. In fact, I haven't been able to exhibit my hypothesized behavior yet.

I think since the connection is hijacked, it's detached from the server kinda. But I might misunderstand how that works under the hood.

**Comment by mholt** [comment]
True, you're right. I just mean that I'm surprised I can send a Close websocket frame over a listener that is in theory being closed.

**Comment by francislavoie** [comment]
But we're not actually closing the listener, aren't we? Cause of UsagePool etc.

**Comment by mholt** [comment]
If the new config does not use that port (for example), then the listener will be closed, yah.

**Comment by WeidiDeng** [comment]
> True, you're right. I just mean that I'm surprised I can send a Close websocket frame over a listener that is in theory being closed.

Actually when a tcp listener accepts a connection, that connection's life cycle has no relationship with the listening socket. Calling close on one of them wouldn't accept the other.

**Comment by mholt** [comment]
@WeidiDeng Right. To clarify, I'm saying that Caddy is closing the _listening socket_ and then after that we are trying to write to the TCP connection that is/was on that socket. But maybe I should add _"potentially"_ in there, since I have not verified that is the case. I haven't been able to see a test yet where the Close frame is not received by the client and backend, so. :man_shrugging:
