### ISSUE TITLE
unrecognized directive: header_up 

### ISSUE THREAD

**Issue by NathanC** [caddyserver/caddy#4898]
I'm trying to set `header_up` for my reverse proxy, but I'm getting `unrecognized directive: header_up` even though I'm directly following the guide.

This works (and properly loads when I restart caddy):
```
handle_path /foo {
	reverse_proxy 127.0.0.1:8001
}
```

But this fails when I restart caddy:
```
handle_path /foo {
	header_up X_FORWARDED_URI "/foo"
	reverse_proxy 127.0.0.1:8001
}
```

The error message is as follows: 
`run: adapting config using caddyfile: parsing caddyfile tokens for 'handle_path': /etc/caddy/Caddyfile:26  - Error during parsing: unrecognized directive: header_up - are you sure your Caddyfile structure (nesting and braces) is correct?`

I've tried with different header names and values, and I've also tried in a `handle` instead of `handle_path` block, and I get the same failure no matter what I try. Any idea what's going on?
	
I'm running on `Ubuntu 22.04` with Caddy Version = v2.5.2

**Comment by NathanC** [comment]
Aaand it was a user error, figured it out right after I posted this question 🙄. the `header_up` directive needs to be nested under reverse_proxy, like:
```
handle_path /foo {
	reverse_proxy 127.0.0.1:8001 {
		header_up X_FORWARDED_URI "/foo"
	}
}
```

Caddy is an awesome server, thanks for all your work on it!

**Comment by mholt** [comment]
Glad you figured it out! Yeah, it has to be in reverse_proxy. That's why it only appears on the reverse_proxy directive page.

If you want to manipulate headers outside of the proxy, you can use the `header` and `request_header` directives. (https://caddyserver.com/docs/caddyfile/directives/request_header)

**Comment by francislavoie** [comment]
FYI you shouldn't use underscores in your header names, the canonical way to write it is `X-Forwarded-Uri`. Also, you're not actually passing the entire URI in this case, you're just passing the prefix. So maybe you should use `X-Forwarded-Prefix` instead.
