### ISSUE TITLE
Documentation - "file_server { root ...}" - subdirective path must be absolute

### ISSUE THREAD

**Issue by thx1111** [caddyserver/caddy#4903]
At https://caddyserver.com/docs/caddyfile/directives/file_server:
>```
>file_server [<matcher>] [browse] {
>	root          <path>
>	...
>```
>...
>* **root** sets the path to the site root for just this file server instance, overriding any other. Default: {http.vars.root} or the current working directory.  ...

Setting a path, assuming it is relative to {http.vars.root}, as set in a preceding "root" directive, will lead to a "404" Page Not Found error.

The path for this `file_server` "root" subdirective must be an *absolute* path in the file system.  The path is *not* relative to any previous "root" directive, at {http.vars.root}, as might otherwise be supposed.  *This requirement for an absolute path is not clearly documented.*

Also, note that that reference to "any other" in the current documentation is confusing, rendering it meaningless.  What "other path" might that be - the paths described in the immediately following sentence, "{http.vars.root}" and "the current working directory"?  Or maybe some other path?  And, what exactly *is* the "current working directory"?  Is that "{http.vars.root}"?  Could it be the "home" directory of the `caddy` effective User ID?  If so, is `caddy` running as user "root"?  As user "caddy"?  As some other user?  In the end, we don't care about any of those questions.

Ask:
Revise the "root" subdirective description, to read:
>* **root** allows setting a file system *absolute* path to the site root for just this file server instance. ...

**Comment by francislavoie** [comment]
> The path is not relative to any previous "root" directive

If you use the `root` subdirective, it _overrides_ the one set with the `root` directive. They aren't combined in any way. The docs already say this.

But _yes_ it _can_ be relative, but it's relative to Caddy's working directory. What that is depends on how you're running Caddy. For example, if you run `cd /var/www/html` to change the working directory then run Caddy with `caddy run`, then paths will be relative to `/var/www/html`.

**Comment by thx1111** [comment]
> If you use the root subdirective, it overrides the one set with the root directive. They aren't combined in any way. The docs already say this.

@francislavoie No, the docs do *not* already say this.  That's the issue.

If you believe that the docs already say this, provide a citation.

I don't think that adding your comment to the "file_server { root ...}" subdirective description is an unreasonable burden on the documentation.  Obviously, I found the documentation unclear, and I misunderstood.

**Comment by francislavoie** [comment]
The word "override" means that no combining will happen, by definition.

**Comment by mholt** [comment]
@thx1111 To clarify, I think Francis means that "it overrides any other" means "it overrides any other ***site root***". And the way to set the site root is to use the `root` directive and/or set the `{http.vars.root}` variable, which is very thoroughly documented already: https://caddyserver.com/docs/caddyfile/directives/root

Francis is also right about it accepting either absolute or relative paths. Caddy does not care. It will resolve relative paths from the current working directory (take care if running Caddy as a service, as the current working directory is not always obvious if you don't explicitly specify it -- that's between you and your process manager).

We could probably amend the docs and say something like "any other site root" if that helps make it clearer.

**Comment by thx1111** [comment]
@francislavoie @mholt You are missing the point.
> To clarify, I think Francis means that "it overrides any other" means "it overrides any other site root". And the way to set the site root is to use the root directive and/or set the {http.vars.root} variable, which is very thoroughly documented already: https://caddyserver.com/docs/caddyfile/directives/root
>
>Francis is also right about it accepting either absolute or relative paths. Caddy does not care. It will resolve relative paths from the current working directory (take care if running Caddy as a service, as the current working directory is not always obvious if you don't explicitly specify it -- that's between you and your process manager).

Yes, quite.  And, if the documentation said exactly *that*, then the concepts would probably be understandable to many more people.  If you think that that's what the documentation was "trying" to say, then it should, instead, simply say *that*.

But, that is *not* what is said in the documentation.  The documentation says something else, in particular, using an ambiguous reference to "any other", which, as I have said, makes the phrase meaningless.

It is rather silly to assert that your writing means to another person what you might like to imagine it means.  And it is foolish to imagine that your readers share the same worldview, background, and interpretations as your own.  Some of the documentation is badly written, and being defensive about it is not going to make it any better.  And it certainly isn't such a challenge to simply fix it, rather than trying to nurse a bruised ego.  If people spent as much time simply editing bad writing, instead of defending it, life would be much easier for everyone.

>We could probably amend the docs and say something like "any other site root" if that helps make it clearer.

Y'all could probably amend the docs to say what you have said in this thread.  In fact, you could just do a little "cut and paste", instead of arguing about what the documentation "is suppose to mean", and save a few people hours of frustration and wasted time, trying to wrap their heads around the "Caddy Way".

Simply, "file_server { root ...}" can take one of two types of arguments: 1) a file system absolute path to the site root, or 2) a path relative to some probably unknown, effectively random, "moving target" path root - where option "2" is just a consequence of some bad programming.  Don't try to obfuscate it.  Perhaps I am being too polite, suggesting simply a change in the documentation, rather than calling-out what is essentially a programming bug.

In your similarly dismissive response to #4904, you fail to appreciate that running a program with a variable initial state is a bad idea at best - and just a demonstration of poor programming skills at worst.  Establishing a visible and certain initial state for a program is the purpose of a configuration file, such that the program is able to reliably perform predictable, repeatable tasks.  Allowing a *server* to operate based upon "the current [mystery] working directory" is *not that*.

You might prefer to not acquire a reputation similar to that of one  particularly polarizing and infamous opensource programmer, known for their own "Won't Fix - Works For Me" stance toward their users.

**Comment by mholt** [comment]
Ok, look, I'm not in charge of your current working directory. You'll have to figure that out.

I was fine with making changes to the docs based on your feedback until your post got accusatory, spiteful, and rude.

We'll still improve the docs, but I'm not going to prioritize this until the negativity I just consumed from reading your comments flushes out of my headspace.
