### ISSUE TITLE
Documentation - Caddy command line - may or may not attach a running instance - no warnings - undocumented

### ISSUE THREAD

**Issue by thx1111** [caddyserver/caddy#4904]
caddy 2.5.1

When an instance of `caddy` is running in the background with uid "caddy", and then, for instance, and especially, running `caddy environ`, this will create an entirely distinct instance of `caddy` and show only the environment derived for the user running `caddy environ`, whether the user is the "caddy" user, some other regular user, or "root", *without any warning*.

This behavior is not documented and usually not expected, since it is not uncommon for other servers to manage a single program instance.

Apparently, `caddy` distinguishes different running instances by uid - again, not documented.

Similarly, `caddy stop` may utterly fail to actually stop a running `caddy` instance:
```
caddy stop --config /etc/caddy/Caddyfile
 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
 WARN    failed using API to stop instance       {"error": "performing request: Post \"http://%20/stop\": dial unix /run/caddy/admin.socket: connect: permission denied"}
 stop: performing request: Post "http://%20/stop": dial unix /run/caddy/admin.socket: connect: permission denied
```

And yet, running `caddy stop` as "root" *will* work:
```
sudo caddy stop --config /etc/caddy/Caddyfile
 INFO    using provided configuration    {"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
```
This difference in result, dependent upon the user ID of the process, is a kind of inconsistency, not expected and not documented.  The result of `sudo caddy environ` depends upon the user ID, while the result of `sudo caddy stop --config ...` does *not* depend upon the user ID.  Here, the `caddy stop ...` command, running as user "root", acts upon the instance of `caddy` running as user "caddy", but the `caddy environ` command, running as user "root", instead, acts upon the instance of `caddy` running as user "root".

Asks:
1) Documentation - a) articulate, and b) provide examples of, this variability in `caddy` operation in the Command Line documentation.
2) Upgrade `caddy` to provide a) an "INFO" display on start of the effective User ID of *this* process itself, and b) automatically check for any *other* `caddy` instance already running, and then display a prominent "WARN" that there exists another instance of `caddy`, "Another instance of caddy is running as User whatever".

**Comment by mholt** [comment]
Thanks for sharing your feedback and opinions.

The [docs for `caddy environ`](https://caddyserver.com/docs/command-line#caddy-environ) say:

> Prints the environment as seen by caddy, then exits.

I don't think a warning is necessary. I suppose if there is confusion as to which `caddy` we're talking about, I would default to the simplest explanation: the current `caddy` process. We can probably clarify that in the docs though if that'd be helpful.

> Apparently, caddy distinguishes different running instances by uid - again, not documented.

Nope, Caddy makes no distinguishing between processes.

> And yet, running caddy stop as "root" will work:
>
> This difference in result, dependent upon the user ID of the process, is a kind of inconsistency, not expected and not documented. 

Well, yes, that is how Unix works. It is out of the scope of our documentation to teach people how their computers work. But I do recommend some of the excellent online resources for learning about Linux! That is how I learned about file permissions and such. The Unix permission model is very interesting and valuable to learn! I usually like this site: https://www.cyberciti.biz/faq/how-linux-file-permissions-work/

> The result of `sudo caddy environ` depends upon the user ID, while the result of `sudo caddy stop --config ...` does not depend upon the user ID.

It's irrelevant of "user id" -- `caddy stop` is specifically programmed to access the admin API of a running Caddy instance and send the `/stop` command to it. This is pretty clear from the docs:

> Gracefully stops the running Caddy process (other than the process of the stop command) and causes it to exit. It uses the [POST /stop](https://caddyserver.com/docs/api#post-stop) endpoint of the admin API to perform a graceful shutdown.

In fact, it's _very clear_ that this affects a separate Caddy process (by saying "other than the process of the stop command").

So, to conclude:

> Asks:
> 
> 1. Documentation - a) articulate, and b) provide examples of, this variability in caddy operation in the Command Line documentation.
> 2. Upgrade caddy to provide a) an "INFO" display on start of the effective User ID of this process itself, and b) automatically check for any other caddy instance already running, and then display a prominent "WARN" that there exists another instance of caddy, "Another instance of caddy is running as User whatever".

As for 1: like mentioned above, I think we're already pretty clear, though maybe we could mention that `caddy environ` is about the current Caddy process. (That's already the very normal, conventional default! Mentioning it will definitely be redundant, but if it's more clear, then sure, I guess it could be helpful.)

As for 2: There is no really good, cross-platform way to detect if another instance of Caddy is running. It would require scanning process lists (only works if the process has permission) or ports (if the other Caddy instance is even listening on a port) -- and then perhaps the entire file system to look for unix sockets (unless there's a way to find all UDS, but I don't know how to do that currently, or if we'd have permission).

Ultimately the Caddy process is bound by Linux permissions, and this is nothing unique to Caddy. Maybe there are sysadmin tools that can help you keep better track of processes, but that's not really Caddy's job.
