### ISSUE TITLE
caddyhttp.App Stop may not release all resources

### ISSUE THREAD

**Issue by WeidiDeng** [caddyserver/caddy#4908]
When http.App [stop](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/app.go#L411), it returns the first error encountered during shutdown. However, when using grace period, the most likely error will be context.DeadlineExceeded, thus preventing other servers and http3.servers (if any) to stop.

When shutdown, stdlib http.Server will [close listeners](https://github.com/golang/go/blob/master/src/net/http/server.go#L2858), it returns the first error encountered, but will proceed to close them all.

**Comment by mholt** [comment]
Thanks for pointing this out, @WeidiDeng! -- I'll get this fixed.
