### ISSUE TITLE
Fix lint warnings after upgrading CEL dependency

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#4915]
We are using some now-deprecated identifiers. I got the `ResultType()` replaced with `OutputType()`, now:

```
if checked.OutputType() != cel.BoolType {
```

and it seems to compile. I'm having trouble replacing `cel.Functions` with `cel.Function`. We used to have this as an argument to `cel.Program()`:

```
cel.Functions(
	&functions.Overload{
		Operator: placeholderFuncName,
		Binary:   m.caddyPlaceholderFunc,
	},
),
```

My understanding is we now need to use `cel.Function()` in `cel.NewEnv()`:

```
	env, err := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("request", httpRequestObjectType),
			decls.NewFunction(placeholderFuncName,
			 	decls.NewOverload(placeholderFuncName+"_httpRequest_string",
			 		[]*exprpb.Type{httpRequestObjectType, decls.String},
			 		decls.Any)),
		),
		cel.Function(placeholderFuncName, cel.SingletonBinaryImpl(m.caddyPlaceholderFunc)),
		cel.CustomTypeAdapter(m.ta),
		ext.Strings(),
		matcherLib,
	)
```

This compiles, but now I get a lot of errors in the tests that look like this:

```
    --- FAIL: TestMatchExpressionMatch/boolean_matches_succeed_for_placeholder_http.request.tls.client.subject (0.00s)
        celmatcher_test.go:402: MatchExpression.Provision() error = setting up CEL environment: function caddyPlaceholder must have at least one overload, wantErr false
```

I'm not sure how to fix this. @TristonianJones can you give me a hint? :D

We upgraded to v0.12 of the CEL library in https://github.com/caddyserver/caddy/commit/7991cd125083121dc9b5907bb2dcaca6b078b4a5. Godoc: https://pkg.go.dev/github.com/google/cel-go@v0.12.4/cel#Function

**Comment by mholt** [comment]
I think I figured it out! The tests pass now. I like that the protobuf dependency is now indirect.

**Comment by mholt** [comment]
@TristonianJones You may want to double-check my work :sweat_smile: 

- https://github.com/caddyserver/caddy/commit/ea8df6ff114299058593530d24fe244201525b9a
- https://github.com/caddyserver/caddy/commit/4fced0b6e15429dd51e6edc2c244f7af068ecf84

Not sure that I did any of it right, but especially not sure about file_request_map in that second commit.

**Comment by TristonianJones** [comment]
@mholt I'm on vacation at the moment, but will look early next week

**Comment by mholt** [comment]
No rush. Enjoy your vacation! Thanks!

**Comment by TristonianJones** [comment]
@mholt changes look good to me. I should expose the `cel.Type`'s `Kind` field so it's easier to do `switch` statements over the high-level `cel.Kind` when working with types.  I'm still working on a plan to remove all proto deps from the top-level, but hopefully the latest changes improve the ease of use and reduce external dependencies a bit.

**Comment by mholt** [comment]
Awesome. Thanks for checking and for your work on the package!
