### ISSUE TITLE
Is it possible to disable certificate validation

### ISSUE THREAD

**Issue by gcampionpae** [caddyserver/caddy#4917]
Hi there, 

I'm trying to start a specific site with a certificate that I give it the path to and it won't start the server since it doesn't recognize that certificate as being valid for that site and I was wondering if there is some way I can disable this validation or possibly force the server to serve the incorrect certificate for that site.

To be fair, the certificate is incorrect for the site becaise I'm trying to test SNI monitoring :)

Here's what the caddy file looks like:

```
{
	debug
	auto_https off
	local_certs
	log {
		level debug
	}
}
127.0.0.1:2015 {
	respond "Hello World!"
	tls C:\Users\gcampion\example.com.crt C:\Users\gcampion\example.com.key
}
example.com:2012 {
	respond "Hello World from example.com!"
	tls internal {
		protocols tls1.2 tls1.2
	}
}
```

What I want to do is serve the 127.0.0.1 with the same certificate that was generated for the example.com site.

**Comment by mholt** [comment]
What do you mean by "being valid"? The certificate has to be properly encoded and parseable, etc.

**Comment by gcampionpae** [comment]
The certificate is valid just not for the 127.0.0.1 domain, it was created for example.com. Since ithe certificate doesn't match, caddy refuses to use it for 127.0.0.1 despite having been specified in the caddyfile

**Comment by mholt** [comment]
Oh, yeah, the certificate will also need to have 127.0.0.1 in its SANs for Caddy to use it. (We're not really in the business of serving bad certs.)

**Comment by gcampionpae** [comment]
Ok, if there's no way to do it in caddy, I'll just have to use nginx, it's much easier to misconfigure 😂. I've got to say, Caddy is really awesome 👍😎

**Comment by mholt** [comment]
For once, I have no problem supporting the decision to use nginx, since that's a better choice for making bad/invalid TLS :laughing:
