### ISSUE TITLE
Migrate to `netip.Addr` type

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4927]
We can migrate to the new IP address type which should bring some performance and code quality improvements https://tip.golang.org/doc/go1.18#netip

We don't need this right away though, and may be a breaking change for certain Caddy APIs and config. Needs research and care.

**Comment by WilczynskiT** [comment]
I add changes in #4966. Sorry for the double pull requests, #4965 is to trash

**Comment by mholt** [comment]
@WilczynskiT Thanks for the PR!
