### ISSUE TITLE
Replace `strings.Index` usages with `strings.Cut` where possible

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4928]
We can now use the new `strings.Cut` function which should simplify some code. See https://tip.golang.org/doc/go1.18#strings

**Comment by Chi3f1991** [comment]
Yuppie

**Comment by Chi3f1991** [comment]
🔮

**Comment by chir4gm** [comment]
Hi, I tried my hand at this Issue, and have requested a PR.
I hope the simple changes suffice.

ps. Thank you for the efforts you have put into making this awesome web server!
