### ISSUE TITLE
how to hide subpath reverse_proxy 

### ISSUE THREAD

**Issue by lbbboy** [caddyserver/caddy#4944]
```
domain.com {
        reverse_proxy localhost:8082
}


reversed address
localhost:8082/web/static/index.htl

How to access directly without suffix
domain.com/web
```
I'm a rookie, I can't find a lot of ways to solve it, ask for help

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
