### ISSUE TITLE
caddy.fs: support tar archive

### ISSUE THREAD

**Issue by oliverpool** [caddyserver/caddy#4945]
Quoting https://github.com/caddyserver/caddy/pull/4909
> The first `caddy.fs` module I might implement (other than the unexported, implicitly-enabled, 2-liner osFS in this PR) is [`archiver.FileSystem()`](https://pkg.go.dev/github.com/mholt/archiver/v4#FileSystem) so that Caddy can serve files from zip/tar archives including transparently decompressing its contents!

I tried it and somehow failed since `archive/tar` does not provide a `Seeker` (https://github.com/mholt/archiver/issues/323).

I was able to workaround using https://github.com/nlepage/go-tarfs which loads all the entries into memory...

---

Here is my code, if anyone want to dig further:
```Caddyfile
{
	http_port 3002
	https_port 3003
	debug
}

http://localhost {
	file_server {
		fs tar /home/olivier/e/caddy-tarserver/data/file.tar
		precompressed gzip
	}
}
```

```go
package tarserver

import (
	"io/fs"
	"os"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/caddyconfig/caddyfile"
	"github.com/mholt/archiver/v4"
	tarfs "github.com/nlepage/go-tarfs"
)

func init() {
	caddy.RegisterModule(TarFS{})
}

type TarFS struct {
	fs.StatFS `json:"-"`
	Path      string
}

// CaddyModule returns the Caddy module information.
func (TarFS) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "caddy.fs.tar",
		New: func() caddy.Module { return new(TarFS) },
	}
}

var _ caddyfile.Unmarshaler = &TarFS{}
var _ caddy.Provisioner = &TarFS{}
var _ fs.StatFS = &TarFS{}

// UnmarshalCaddyfile implements caddyfile.Unmarshaler.
func (t *TarFS) UnmarshalCaddyfile(d *caddyfile.Dispenser) error {
	for d.Next() {
		if !d.Args(&t.Path) {
			// not enough args
			return d.ArgErr()
		}

		if d.NextArg() {
			// too many args
			return d.ArgErr()
		}
	}
	return nil
}
func (t *TarFS) Provision(ctx caddy.Context) error {
	return t.ProvisionArchiver(ctx) // switch to ProvisionTARFS for in-memory
}

func (t *TarFS) ProvisionArchiver(_ caddy.Context) error {
	afs, err := archiver.FileSystem(t.Path)
	if err != nil {
		return err
	}
	t.StatFS = afs.(fs.StatFS)

	return nil
}

func (t *TarFS) ProvisionTARFS(ctx caddy.Context) error {
	tf, err := os.Open(t.Path)
	if err != nil {
		return err
	}
	ctx.OnCancel(func() { tf.Close() })
	tfs, err := tarfs.New(tf)
	if err != nil {
		tf.Close()
		return err
	}
	t.StatFS = tfs.(fs.StatFS)

	return nil
}
```

**Comment by mholt** [comment]
Thank you for experimenting with this and sharing your results!

After looking into it myself a little more, I suspect using archive files for this isn't going to be very feasible (with current libraries, anyway -- I don't know if there's a way to seek without loading the whole thing into memory).

I'll close this issue since there's not much actionable on it, but I think it is valuable that you shared your results here.

I know quite a few users who would like to use this with cloud storage providers like S3, B2, etc. (Rclone libraries could probably help with this!) Would anyone like to take that on?

**Comment by sagikazarmark** [comment]
I've created one for S3: https://github.com/sagikazarmark/caddy-fs-s3

**Comment by oliverpool** [comment]
I just proposed an improvement of the Go stdlib, to better support io.FS without `Seek`: https://github.com/golang/go/issues/61791

This would allow supporting zip files quite easily (since the stdlib already provides a io.FS implementation).

**Comment by mholt** [comment]
Ohh yeah, that's really cool @oliverpool !! I saw some notifications come in on that but it's been a busy week with the new Caddy release (which I botched, heh).

I think your progress is exciting. I'll definitely be following it. Let me know if you could use help on the Caddy side of anything.
