### ISSUE TITLE
Add variable (system placeholder) that exposes time at the start of a request

### ISSUE THREAD

**Issue by rsolvang** [caddyserver/caddy#4955]
My [question on the community forum](https://caddy.community/t/templates-show-time-it-took-to-generate-page/16812) revealed that there is no variable (system placeholder) that provides the time at the start of a request. Having such a variable available would make it possible to calculate and print the time it took to generate a page, for no other reason than evoking those fuzzy '90s feelings :smirk:

**Comment by mholt** [comment]
Ahh silly me, there's already `{http.request.duration}` (and variant `duration_ms`) which tells you how long the request has been going for.
