### ISSUE TITLE
Custom error message string is not output anywhere

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#4969]
The `error` directive accepts a message argument, but this string doesn't appear in any of the placeholders listed here https://caddyserver.com/docs/json/apps/http/#servers/errors/routes nor does it appear in the response body when a `handle_errors` template is not used (a zero size response body is returned).

If I configure something like `error "Forums are down for maintenance" 503` the placeholder values are

`http.error.status_code` "503"
`http.error.status_text` "Service Unavailable"
`http.error.message` ""
`http.error.trace` "caddyhttp.StaticError.ServeHTTP (staticerror.go:110)"
`http.error.id` "6persmrad"

Versions: 2.5.2 and fe5f5dfd6aa2f48e92897327c9c7d8c8583a3d72

**Comment by mholt** [comment]
Hmm, that might be a documentation error (sadly, no pun intended). What is the value of the `{http.error}` placeholder for you?

But now that I look at things, I'm not sure which one was intended. Hmm. Yeah, lemme know what that is and we'll figure it out. (I haven't done much with this code since releasing v2, so I'm a bit rusty right now.)

**Comment by bones-was-here** [comment]
`{id=gmcagza9n} caddyhttp.StaticError.ServeHTTP (staticerror.go:110): HTTP 503: Forums are down for maintenance`  
or  
`{id=bzgr3trhn} caddyhttp.StaticError.ServeHTTP (staticerror.go:110): HTTP 503:` (if no custom message is configured)

It would be nice if there was a placeholder that contained the custom message when set, and the generic message otherwise.

**Comment by francislavoie** [comment]
> If I configure something like `error "Forums are down for maintenance" 503` the placeholder values are
>
>`http.error.message` `"caddyhttp.StaticError.ServeHTTP"`

Weirdly enough, I can't replicate this with `respond "{http.error.message}"` 🤔 I don't think we actually ever set that placeholder!

https://github.com/caddyserver/caddy/blob/fe5f5dfd6aa2f48e92897327c9c7d8c8583a3d72/modules/caddyhttp/server.go#L517-534

That said, I think we should add this line `repl.Set("http.error.message", handlerErr.Err.Error())` inside the `if` to populate that placeholder with the actual `HandlerError`'s message. Easy fix.

**Comment by bones-was-here** [comment]
I tested by editing the html error template to include all these placeholders.

**Comment by francislavoie** [comment]
I tried with a template too, and it resulted in an empty string. I don't see how `http.error.message` could have ever worked.

**Comment by bones-was-here** [comment]
I'm getting the empty string result when I test now.  The value of `http.error.trace` is  
"caddyhttp.StaticError.ServeHTTP (staticerror.go:110)" so I'm guessing I incorrectly noted the part before the space as being from `http.error.message`.

**Comment by francislavoie** [comment]
Great, thanks for confirming, that makes more sense.
