### ISSUE TITLE
[TLS][client_auth] Pass ssl_client_s_dn value

### ISSUE THREAD

**Issue by mpiot** [caddyserver/caddy#4970]
I try to implement x509 Client Authentication on a part of a project, adding:

```
    tls {
    	client_auth {
    		mode                 require_and_verify
    		trusted_ca_cert_file /etc/caddy/ca.crt
    	}
    }
```

Enable the validation from Caddy, by adding the client certificate we access the page, without we are rejected by Caddy. But with nginx or apache, the http server can pass trought astscgi params: `SSL_CLIENT_S_DN_Email` (Apache) or `$ssl_client_s_dn` (Nginx).

That permit to authenticate the user in the application.

Actually, I do not retrieve it ot other things that contains the identity filled in the certificate.

**Comment by francislavoie** [comment]
What exactly do you want to pass it to? Are you using `php_fastcgi`? In that case, use the `env` option to pass through whatever you want. There's a bunch of TLS placeholders you can use which have the values from the client cert https://caddyserver.com/docs/json/apps/http/#docs.

**Comment by mpiot** [comment]
@francislavoie thank you for your help, just a question about it, if I do `openssl x509 -in client.p12 -text -noout` it return to me:
`Subject: C = FR, O =My Organization, CN = user1, emailAddress = user1@myorg.fr`

But in Caddy when I use `{http.request.tls.client.subject}`, I've cometink like it:
`CN=user1,O=My Organization,C=FR,1.2.840.113549.1.9.1=#0c166c6f67626f6f6b40617669726f654564654ef545z

In my case, I would like to retrieve the `emailAddress` that is not present, and I don't know what is the values at the end ?

**Comment by mholt** [comment]
@mpiot The subject is currently a conglomeration of a `pkix.Name` fields such as CommonName, Organization, Locality/Country, SerialNumber, ExtraNames, etc. It's because the subject is a structure, not a string.

Email addresses are part of the SAN now. Try `client.san.emails`.

**Comment by mpiot** [comment]
@mholt thank you for your help, I've try it `{http.request.tls.client.san.emails.0}` but it return to me an empty string.

**Comment by mholt** [comment]
I'm not sure then. If you post the certificate file here we can help troubleshoot

**Comment by stronny** [comment]
https://oidref.com/1.2.840.113549.1.9.1
`1.2.840.113549.1.9.1=#0c166c6f67626f6f6b40617669726f654564654ef545z` this is `emailAddress` field, and I'm sure its value in some encoded form.

(sorry to necropost)

**Comment by mholt** [comment]
I think these values are different from SubjectAltName fields, and Caddy/CertMagic supports SubjectAltName, as the field you are referencing is deprecated.

**Comment by francislavoie** [comment]
We're pulling the info from certs using Go stdlib. Code is here:

https://github.com/caddyserver/caddy/blob/a7db0cfe55b524a34a310e852af6c9520134db10/modules/caddyhttp/replacer.go#L351

If you have specific improvements you'd like to be made, please open a new issue. PRs are welcome.

**Comment by stronny** [comment]
This is what I think happens.

1. A cert has an emailAddress field in its subject (not the SAN, Subject).
2. pkix.Name type doesn't support it natively.
3. Which doesn't matter anyway because Caddy doesn't parse the subject, it just relies on go's internal String method.

What I'd like doesn't matter here, I'm just providing context if you're interested in dealing with this issue in any way.

**Comment by mholt** [comment]
@stronny Yeah, I think that's what's going on. We aren't detecting it because we don't read Subject (deprecated), only SAN (current). Thank you :blush:
