### ISSUE TITLE
Propagate access logging config to implicit HTTP server from Auto HTTPS

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#4982]
If the Auto HTTPS routine creates an HTTP server to perform HTTP->HTTPS redirects, it doesn't inherit the logging config from the HTTPS server. It should, because it is a relevant request to log.

**Comment by Khourssa** [comment]
Hey, I've invested all my money on this website and we've blocked our account and lost our money. Please help. https://h5.otw60.com
