### ISSUE TITLE
Glob matcher for file names on the *filesystem*

### ISSUE THREAD

**Issue by iamjrock** [caddyserver/caddy#4988]
[Placeholder for a feature requested in this community discussion](https://caddy.community/t/matching-admin-with-filesystem-admin-index-md4-html).

`file_server, try_files, file, url, path_regexp` and other matchers are very powerful for matching requests and uri paths with wildcards/regex.

However they do not seem to accommodate regex/wildcards for file names on the caddy *filesystem*.

The closest is to this is the configuration for…

    ‘try_policy’: ‘first_exist|smallest_size|largest_size|most_recent_modified’

…because this hints at rules to select from multiple matching files on the filesystem, but it does not provide the flexible globbing available to request matching.

A suggested implementation approach from the community discussion linked above is:

> I think it would essentially mean some kind of first_glob policy; would be the same as first_exist but using [filepath.Glob()](https://pkg.go.dev/path/filepath#Glob) to match for files instead, returning the first result from that (if there’s multiple results then… result is kinda undefined).

The community discussion also explains one known use case.

It would be great if Caddy could do regex/wilcard/glob filesystem matching for this and similar use cases.

**Comment by mholt** [comment]
I think this would be more like a glob sort, i.e. use the configured filename pattern to get a list of files, then sort by one of those criteria.

**Comment by iamjrock** [comment]
So:

1) Glob search of filesystem
2) If only one file (not folders) matches, return that file
3) If more than one file matches, apply the try_files rules to select one of them:

first_exist|smallest_size|largest_size|most_recent_modified

Sound right?

**Comment by mholt** [comment]
Kind of, yeah.

This is a weird one. I've spent some time on this today, and I can't figure out what to do if a request comes in with a path of `/*` -- like, we don't want clients to be able to send glob patterns, right? So if the `{path}` placeholder is used in a `try_files` config, we'd need to treat that differently... like, we want the server admin/config to dictate when globbing is done, not clients.

I don't think it's a security concern as we'd never match files that are configured as hidden (i.e. a regular HTTP request to those files would still load them). But it could be surprising.

Part of me is thinking glob expansion might only be performed if there are no placeholders in the `try_files` config. Make sense? Any other ideas?

**Comment by francislavoie** [comment]
> Part of me is thinking glob expansion might only be performed if there are no placeholders in the try_files config.

That would actually make it useless, unfortunately. Placeholders are necessary, otherwise you can only rewrite to static locations.

**Comment by mholt** [comment]
@francislavoie You're mostly right, although I could see some specific cases where you want to rewrite just one file to another.

Feature implemented in #4993, if you could try it out @iamjrock that would be helpful. It worked for me but most importantly it must work for you!
