### ISSUE TITLE
serving static files as requested by the proxy with Docker

### ISSUE THREAD

**Issue by roukmoute** [caddyserver/caddy#4989]
Hi,

I have my Caddy running in a Docker.  
And I have [Zola](https://www.getzola.org/) running in a Docker too.

I try to redirect my `https://foo.bar` to static file that was generated by Zola:

```Caddyfile
foo.bar:443 {
	reverse_proxy Zola:8080 {
		@accel status 200
		handle_response @accel {
			root    * /public
			rewrite * /
			file_server
		}
	}
}
```

But it does not work, have you any idea?

How works path of `root`?  
Is it possible that this is a problem when everything is Dockerized?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
