### ISSUE TITLE
Cookie Placeholder

### ISSUE THREAD

**Issue by PythonLinks** [caddyserver/caddy#5000]
Here is the documentation for placeholders. 
https://caddyserver.com/docs/caddyfile/concepts#placeholders

In caddy 1, we could do {~cookie-name}
In caddy 2 the docs mention
{header.*} | {http.request.header.*}
Not quite clear how to index into the specific cookie. 
I did see one recent posting using the  {~cookie-name} approach, so I am going to try that, but clearer documentation would be helpful for those of us who are new to this. 

Thanks
Chris

**Comment by PythonLinks** [comment]
The template docs also mention. 
// {{.Cookie "cookiename"}}

Maybe the following will work:
{.Cookie "cookiename"}
But again it would be good if it were in the placeholder docs.

**Comment by francislavoie** [comment]
You opened lucky issue number #5000! 🎉

You can use the placeholder `{http.request.cookie.*}` where `*` is the cookie name.

You're right that we're missing a Caddyfile shortcut for that though, we should add that. It'll be `{cookie.*}`
