### ISSUE TITLE
Caddy2 is returning "page can’t be found" if i put /api/* path in root of CaddyFile

### ISSUE THREAD

**Issue by wonderbytes1** [caddyserver/caddy#5013]
i am very new with Caddy 2, I have two CaddyFile one of them work the other doesn't and the only difference they have is the path /api/* in root document. i dnt know if its a bug or its me but it is strange that adding path is breaking it 

the following CaddyFile works fine:
```

www.mydomain.com:443 {

root * /var/www

file_server

log {
    output file /var/log/caddy/access.log {
            roll_size 1mb
            roll_keep 4
            roll_keep_for 24h
    }
}
}

```
But the following doesn't, and i dont know what is wrong here.

```
www.mydomain.com:443 {

root /web/* /var/www

file_server

log {
    output file /var/log/caddy/access.log {
            roll_size 1mb
            roll_keep 4
            roll_keep_for 24h
    }
}
}
```

please any help would be appreciated

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

I'm not finding it clear what exactly you're trying to do.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
