### ISSUE TITLE
Redirection issue with multiple chained Caddy reverse proxy servers 

### ISSUE THREAD

**Issue by DrDoug88** [caddyserver/caddy#5014]
I am running 2 caddy servers for reverse proxying. One server is reachable from the external internet, and the other is on an internal vpn only accessible from vpn clients. I have 4 docker-based services running behind the internal vpn caddy server. DNS and TLS all work fine and correctly. This configuration is mostly derived from this article (https://caddy.community/t/use-caddy-for-local-https-tls-between-front-end-reverse-proxy-and-lan-hosts/11650)

Here are some example Caddyfiles:

External Internet-Reachable Caddyfile:
```
https://service1.externalinternet.com {
  reverse_proxy https://service1.vpn {
    header_up Host {http.reverse_proxy.upstream.host}
  }
}

https://service2.externalinternet.com {
  reverse_proxy https://service2.vpn {
    header_up Host {http.reverse_proxy.upstream.host}
  }
}

https://service3.externalinternet.com {
  reverse_proxy https://service3.vpn {
    header_up Host {http.reverse_proxy.upstream.host}
  }
}

https://service4.externalinternet.com {
  reverse_proxy https://service4.vpn {
    header_up Host {http.reverse_proxy.upstream.host}
  }
}
```
Internal VPN Caddyfile:
```
https://service1.vpn {
  reverse_proxy https://docker1 {
    trusted_proxies private_ranges
  }
}

https://service2.vpn {
  reverse_proxy https://docker2 {
    trusted_proxies private_ranges
  }
}

https://service3.vpn {
  reverse_proxy https://docker3 {
    trusted_proxies private_ranges
  }
}

https://service4.vpn {
  reverse_proxy https://docker4 {
    trusted_proxies private_ranges
  }
}
```
Based on this setup, everything is working correctly except for one service, service4. All 4 services require a login process. However, when accessing service4 from the outer Caddy instance, i.e. https://service4.externalinternet.com, it will redirect to https://service4.vpn after logging in. If I reload https://service4.externalinternet.com, then I am logged into service4 with external hostname, and I can proceed to navigate the site. The same behavior occurs when logging out of the site. It will redirect to https://service4.vpn rather than https://service4.externalinternet.com. 

If I add "header_up Host {header.X-Forwarded-Host}", i.e.:
```
https://service4.vpn {
  reverse_proxy https://docker4 {
    trusted_proxies private_ranges
    header_up Host {header.X-Forwarded-Host}
  }
}
```
to the reverse_proxy block of service4 on the internal VPN Caddy server, then everything works correctly when accessing via the external internet hostname - logging in/out will redirect to external internet-based hostname. However, when accessing service4 via the vpn, i.e. https://service4.vpn, it will redirect to https://docker4 rather than https://service4.vpn, when logging in/out. I can think of a few contrived ways to possibly handle this specific situation for service4, but is there a clean and correct way to handle this? I apologize for my ignorance on this matter, this is not an area of software engineering that I am entirely familiar with.

Thank you for all of the hard work put into Caddy, and thank you in advance for your time on this matter.

BTW, I created a profile on the caddy.community forum and attempted to post this, but since I just created the account over there, it has yet to receive approval. I would be happy to repost this over there if requested.

**Comment by francislavoie** [comment]
I approved the post on the forums https://caddy.community/t/redirection-issue-with-multiple-chained-caddy-reverse-proxy-servers/17050

**Comment by DrDoug88** [comment]
I just noticed. Thank you!
