### ISSUE TITLE
reverse_proxy does not take into account the variable values (from map)

### ISSUE THREAD

**Issue by Jiehong** [caddyserver/caddy#5021]
Hi,

I'm basically trying to map requests to path `/my_prefix/XXX/v1/rest/api/*` by stripping the beginning, but also extracting `XXX` and the endpath and reverse proxy it else where.

Here is a short Caddyfile I made:

```
*:8080 {
  @api {
    path /my_prefix/*
    vars_regexp my_path {path} ^/my_prefix/(.*)/rest/api/(.*)
  }

  handle @api {
    vars {
      xxx {re.my_path.1}
      sub_path {re.my_path.2}
    }

    map {vars.xxx} {my_number} {endpoint} {
      XXX 123 http://10.0.0.0:7777
      YYY 456 http://10.0.0.1:7777
      default no_number no_url:8080
    }

    rewrite * /{my_number}/v1/configurations/{vars.sub_path}
    respond "{path} and {endpoint}"
    # reverse_proxy {endpoint}
  }
}
```

Now, if I run this, and target `localhost:8080/my_prefix/XXX/rest/api/hello/there`, I get the correct response:

`/123/v1/configurations/hello/there and http://10.0.0.0:7777`, as expected.

But now, if I comment the `respond` line and uncomment the `reverse_proxy` line, I get the following in the logs:

```
{
  "level": "error",
  "timestamp": "2022-09-06T16:12:33.702Z",
  "logger": "http.log.error",
  "message": "dial http:: unknown network http:",
  "request": {
    "remote_ip": "172.21.0.1",
    "remote_port": "58358",
    "proto": "HTTP/1.1",
    "method": "POST",
    "host": "localhost:8080",
    "uri": "/my_prefix/XXX/rest/api/hello/there"
  },
  "duration": 0.0002784,
  "status": 502,
  "err_id": "6uxwc7f6c",
  "err_trace": "reverseproxy.statusError (reverseproxy.go:1184)"
}
```

If I remove `http:` from the `{endpoint}` in the map, then the ip/port are taken into account.

Is there a problem with `://` in the map variables or reverse_proxy? (I tried quoting the endpoints in the map, but it didn't help).

**Comment by mholt** [comment]
Yes, this is a known parsing issue, as stated in the docs:

> If the address is not a URL (i.e. does not have a scheme), then placeholders can be used

The scheme cannot be dynamic or variable, so placeholders cannot be used with a scheme. If the scheme uses TLS, then the TLS transport is set up ahead-of-time for efficiency.

**Comment by Jiehong** [comment]
@mholt 
Perhaps a better error message would be nice? if scheme and placeholders are detected, it should be logged better.

And if the scheme is being changed in reverse_proxy, it could also be logged better (aka it's not allowed)

**Comment by mholt** [comment]
> Perhaps a better error message would be nice? if scheme and placeholders are detected, it should be logged better.

I agree that would be nice. But I'm not sure how to do that? Placeholders aren't evaluated until runtime, so we don't know that there's a problem until then. Any ideas?

> And if the scheme is being changed in reverse_proxy, it could also be logged better (aka it's not allowed)

We do error in that case already:

https://github.com/caddyserver/caddy/blob/8cc8f9fddd2ea717633528322e1bef938bee2415/modules/caddyhttp/reverseproxy/caddyfile.go#L159-L166

**Comment by Jiehong** [comment]
@mholt : yes, I was referring to the runtime error.

Today, instead of saying `dial http:: unknown network http:` at runtime, it could detect that a scheme is present, and reuse the same error we get from the caddyfile load.

So that the error at load time from caddyfile, and the error at runtime would match.

Would parsing for an optional scheme at runtime be costly? (maybe just a string startsWith or something)

**Comment by mholt** [comment]
I don't think that it knows the scheme is present, that's the problem -- it's parsing it as a network type. It's a parsing ambiguity. If you want to propose a patch in the code, I'd be happy to review it! (The code is subtle though, would need tests.)
