### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alirf81** [caddyserver/caddy#5023]
I am using caddy with caddysecurity for authorization and the problem is that,
when the authorization is failed, it returns 500 Internal Server Error
`caddy                      | {"level":"debug","ts":1662544198.3610609,"logger":"http.handlers.replace_bearer","msg":"No Authorization Header"}`
`caddy                      | {"level":"debug","ts":1662544198.3611372,"logger":"security","msg":"token validation error","session_id":"gqt87sVjHgXhAQ3g4RBLJ4zJBGYGeZphQ9JfZzJ","request_id":"03ba1cdc-79ca-4dbf-abff-9ca32806e392","error":"no token found"}`
`caddy                      | {"level":"error","ts":1662544198.3611686,"logger":"http.handlers.authentication","msg":"auth provider returned error","provider":"authorizer","error":"user authorization failed: src_ip=10.23.5.107, src_conn_ip=10.23.5.107, reason: no token found"}`
`caddy                      | {"level":"debug","ts":1662544198.3612537,"logger":"http.log.error","msg":"not authenticated","request":{"remote_ip":"10.23.5.107","remote_port":"10381","proto":"HTTP/1.1","method":"GET","host":"10.23.9.30:8083","uri":"/v1/tenants-service/status","headers":{"Accept":["application/json"],"User-Agent":["PostmanRuntime/7.29.2"],"Postman-Token":["06f2bf91-0202-44eb-b09f-e726c57f25d5"],"Accept-Encoding":["gzip, deflate, br"],"Connection":["keep-alive"],"Cookie":[]}},"duration":0.000200842,"status":401,"err_id":"1pi16i8wb","err_trace":"caddyauth.Authentication.ServeHTTP (caddyauth.go:88)"}`
This is the log of caddy and it seems like it returned 401 error.
But what I see in my Postman is 500 Internal Server Error
How can I solve this?

**Comment by mholt** [comment]
It could be that some other part of your config is causing an internal error. Without any details we can't help you. If you remove caddy-security config and replace it with `error 401` and the 500 is still returned, try removing any `handle_errors`. If it _still_ returns 500, then let me know and we can re-open this as a potential bug in Caddy.

Otherwise, please open an issue with caddy-security and/or troubleshoot your config first.

**Comment by alirf81** [comment]
As I debugged, the issue is here:
https://github.com/caddyserver/caddy/blob/c19f2072379e18fbf3b2409ecd49ca023d62b882/modules/caddyhttp/caddyauth/caddyauth.go#L88
The auth provider `caddy-security` returns error and `caddy` tries to return unauthorized error here.
But after returning, "Internal Server Error" is written in ResponseWriter.
I tried to make it return `nil` and there is no "Internal Server Error".
`// return caddyhttp.Error(http.StatusUnauthorized, fmt.Errorf("not authenticated"))`
`errorR := caddyhttp.Error(http.StatusUnauthorized, fmt.Errorf("not authenticated"))`
`return nil`
In caddy log, there is nothing related to this error.
Do you have any idea ?

**Comment by mholt** [comment]
What is your full config? Please see my previous comment:

> It could be that some other part of your config is causing an internal error. Without any details we can't help you. If you remove caddy-security config and replace it with error 401 and the 500 is still returned, try removing any handle_errors. If it still returns 500, then let me know and we can re-open this as a potential bug in Caddy.

Please post sufficient information for us to reproduce the bug.
