### ISSUE TITLE
On demand TLS creates certificates for empty ask url 

### ISSUE THREAD

**Issue by tpetry** [caddyserver/caddy#5036]
When the `ask` option of the `on_demand_tls` directive is used, caddy has to ask whether the certificate can be created. To make the configuration more dynamic I didn't hardcode the url but use an environment variable. When the variable is defined everything works as expected, but when it is missing caddy behaves like the ask option not existing and creates any certificate.

As the ask option is a safety option I expected caddy to decline any request as the endpoint is empty. I don't know whether this is expected behavior. Is it a bug? Would it make sense to change the behavior in this case? Any other option which can be used to not generate certificates in this use-case? 

```
{
    admin off
    on_demand_tls {
        ask {env.ON_DEMAND_TLS_ASK}
    }
}
```

**Comment by mholt** [comment]
Good idea, fixed! It will return an error now if any placeholder is empty or unknown.

**Comment by tpetry** [comment]
What do you mean by returning an error? Does Caddy not start anymore because the config is declared invalid? Or is it handled like an endpoint returning an error code so no tls certificate is generated?

**Comment by mholt** [comment]
Yes, it's when the `tls` app is provisioned. So loading the config will return an error.
