### ISSUE TITLE
Route ordering is weird

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#5037]
As reported on the forum here: https://caddy.community/t/suggestions-for-simplifying-my-caddyfile/17135/2?u=matt -- the ordering of `handle` blocks is unexpected, and a little bit buggy.

The [`sortRoutes()` function](https://github.com/caddyserver/caddy/blob/20d487be573424e7647b5a157754f6e284554e23/caddyconfig/httpcaddyfile/directives.go#L383) is intended to sort HTTP handlers by the directive order, and then for multiple instances of the same directive, to sort them intelligently by their matchers. This is needed so that a directive -- especially a mutually-exclusive or terminal handler -- doesn't shadow another, making the other completely irrelevant. For example, if two `handle` blocks are configured, one matches on "/foo/*` and another on `/foo/bar` specifically, it's vital for the `/foo/bar` block to be ordered first, otherwise the first `/foo/*` block would always match and preclude the more specific one. So we sort by longest path matcher first if there is just one path to match. (More, and it's unclear to me what the proper logic should be.)

There's a bug in `sortRoutes()` here:

https://github.com/caddyserver/caddy/blob/20d487be573424e7647b5a157754f6e284554e23/caddyconfig/httpcaddyfile/directives.go#L418-L426

These `> 0` checks should be ` == 1`, since the idea is to only compare the lengths of the path matcher if there's a single path to match. (If there's more than 1, choosing the first one in the list seems too arbitrary, and again I'm not sure what should be done then.)

Additionally, this logic is perhaps not a "bug" but is at least not ideal:

https://github.com/caddyserver/caddy/blob/20d487be573424e7647b5a157754f6e284554e23/caddyconfig/httpcaddyfile/directives.go#L442-L449

That doesn't account for when one directive has a path matcher and the other does not (i.e. `iPathLen > 0` but `jPathLen == 0`). For example, if one has a path matcher of `/`, that is length 1, and the length of the path matcher for the other one would be 0. It doesn't really make sense to compare the lengths of different matchers or lack thereof.

The simple fix for that `if` statement is to turn the `&&` into `||` -- but I also think it makes more sense for the `if` statement to contain the _most specific_ case, which is where both directives have exactly 1 path to match. So I will probably refactor that code slightly so that the comparison of the length is inside the if.

**Comment by asb** [comment]
World you consider not sorting `handle` blocks at all? The simple of/elif interpretation of a series of handle directives is intuitive, and I'm not sure sorting in the special case of a path matcher is worth breaking that mental model.

**Comment by mholt** [comment]
I'd consider it, but only if I'm convinced there's so many edge cases that it turns out like playing whack-a-mole. Right now, I think the sorting we do (with the fix) _is_ important and useful.

**Comment by francislavoie** [comment]
The problem is that many users don't actually write their config in sensible orders. If we turned off the sorting then it would just move the "not obvious" behaviour from users who do write their config in a sensible order to those who don't.

**Comment by asb** [comment]
Thank you both for the feedback (and of course, for identifying and fixing the issue so quickly). I agree the if/else mental model mostly works, it's just this path sorting case that breaks it. Looking more closely, it seems nginx has similar logic with its location directive about preferring the longest path. I'd thought @francislavoie's reasoning would be true for the general case of directive sorting but perhaps not for `handle` directives - but given the nginx precedent, I think I'm wrong on that point.

I've had a go at documenting this https://github.com/caddyserver/website/pull/264

**Comment by asb** [comment]
I do think that given the more complex matchers supported by caddy vs the nginx location block there's probably more scope for confusion, particularly about the relative ordering of path-based matchers vs more complex ones where I can imagine some cases where the ordering could be surprising.

A global option to disable such reordering could make sense if that turns out to be an issue in practice. I'll file an issue on that if I run up against this kind of confusion again in practice.

**Comment by mholt** [comment]
Sure. If there's a legitimate confusion or frustration or inability to accomplish something because of our ordering logic and we can't fix it without breaking something else (i.e. trying to satisfy two opposed assumptions), then I'm open to making changes (maybe it's no reordering, maybe it's a global option to set the "mode", I dunno -- I'm kind of tired of new global options, heh)

**Comment by francislavoie** [comment]
You can just wrap stuff in a `route` to force the ordering, as an escape hatch. I don't think a global option makes sense for this.
