### ISSUE TITLE
`import` directive should not import dotfiles

### ISSUE THREAD

**Issue by cincodenada** [caddyserver/caddy#5048]
I'm attempting to import all files in a directory, as directed in the documentation:
```
import sites-enabled/*
```
But I'm running into errors because it's trying to include my editor's dotfiles, which are also in that directory.

Obviously I can clean up the dotfiles, or add a suffix to all the files I _do_ want to include or what have you, and you can argue about whether editing files in-place is good practice. But I would consider this a bug - standard shell globbing _doesn't_ include dotfiles, so it is surprising that Caddy's `import` statement does, and I don't see any way to avoid including dotfiles - these are globs, not regexes.

I'm not super familiar with Go, but I looked briefly at the code hoping that there was a flag or something, but it seems not. Python, for instance, has `glob.glob()` for shell-like file globbing (which doesn't include dotfiles) and `pathlib.Path.glob()` which does include dotfiles. I don't know if Go has anything similar, or if we'd just have to manually exclude any files that start with `.` after the fact.

In any case, I think globs in an include spec should be changed to not include dotfiles, you could include a config flag for backwards compatibility if desired, although I would be surprised if anyone is _intentionally_ including dotfiles.

Note this is a totally separate concern from issues like #2286, which are about _serving_ dotfiles - this is about _importing_ dotfiles as part of config parsing.

**Comment by francislavoie** [comment]
I'd suggest using an extension like `.conf` or something for your actual config files in that case, then importing with `import sites-enabled/*.conf`. I'm not sure special logic here is warranted, it might break a legitimate use for someone else.

**Comment by cincodenada** [comment]
I'm not looking for workarounds, I already listed those (including the suggested one) in my post.

I opened this issue because I think it is a misfeature at best: as I stated above, standard shell globbing doesn't include dotfiles, so this is unexpected behavior to most folks who know what globbing is. I would be surprised if someone was depending on including dotfiles for their config, but if we're concerned about that, we could add a config flag about it or something. It seems like a pretty unusual use case to me.

I just ran a test to double-check and confirmed that both Apache and Nginx, as expected, ignore dotfiles when gathering includes in their config files. I think Caddy should follow suit, in the interest of following the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). It's quite surprising to find that Caddy acts differently than the two other predominant Linux webservers, and I would argue differently than most Unix tools, in how it handles globbing.

**Comment by francislavoie** [comment]
Well argued. Fair enough. And sorry for missing that you mentioned the suffix idea already 👍

**Comment by ADawesomeguy** [comment]
I'd like to give implementing this a shot, where could I find the path selector in this case?

**Comment by mohammed90** [comment]
> I'd like to give implementing this a shot, where could I find the path selector in this case?

You'll be working in this range:

https://github.com/caddyserver/caddy/blob/821a08a6e39ed0e7c43b0271ccf126c194eb6339/caddyconfig/caddyfile/parse.go#L369-L410

**Comment by ADawesomeguy** [comment]
Alright, so would it make sense to just check for whether there's a `.` at the beginning of `importPattern` and if not then add a `[!.]` at the beginning to exclude hidden files and/or directories?

**Comment by ADawesomeguy** [comment]
```go
// ignore hidden files if not explicity specified
if !strings.HasPrefix(filepath.Base(importPattern), ".") || filepath.Base(importPattern) == "." || filepath.Base(importPattern) == ".." {
	globPattern = "[!.]" + globPattern
}
```
I'm thinking something like this should go after line 383.

**Comment by ADawesomeguy** [comment]
```go
// ignore hidden files if not explicity specified
if !strings.HasPrefix(filepath.Base(importPattern), ".") || filepath.Base(importPattern) == "." || filepath.Base(importPattern) == ".." {
	globPattern = "[!.]" + globPattern
}
```
I'm thinking something like this should go after line 383.

**Comment by cincodenada** [comment]
Hi @ADawesomeguy thanks for digging in here! I'm not a maintainer here but here's my thoughts:

Looking at the docs for [`filepath.Glob()`](https://pkg.go.dev/path/filepath#Glob) which uses the same rules as [`filepath.Match()`](https://pkg.go.dev/path/filepath#Match), I don't see an exclamation point in that spec, but it may be an undocumented alias for `^`? But reading the code, it appears that `globPattern` is an absolute path, so I don't think simply prefixing the pattern will work.

You could split off the basename, prefix it, and put it back together, but I am wary of modifying the pattern at all. I'm wary of attempting to modify user input in general, because it creates many possible edge cases. For example, suppose the user put something like `import/???` to import files with three characters. Even if we handled the path correctly, prefixing would result in `import subdir/[!.]???`, which would match only files with _four_ characters (one non-dot, then three others).

This is just an example off the top of my head - the general gist is, I think modifying the pattern is a fragile approach, and trying to anticipate and adjust for every possible thing a user might do like this is not a situation I like to be in as a programmer :)

Instead, I would suggest leaving the user input as-is, let it return any dotfiles it may find, and then process that list before we use it, filtering `matches` to remove any dotfiles. One advantage of this approach is also that if we wanted, we could also keep track of whether we excluded any dotfiles or not. This would allow emitting a log message of some kind warning that there we found but aren't including dotfiles (I'm not sure what kind of version checking exists, but it might be possible to do this only on the first run after an upgrade, to detect any possible situations where people have pre-existing configurations that were previously including dotfiles...possibly too complicated, however).

There are a couple places it would make sense to do the filtering - either right after making the list, or possibly in `doSingleImport`. Doing it right after making the list avoids any awkwardness deciding how to handle the no-matches case (what if we match _only_ dotfiles?), but `doSingleImport` already has several similar checks (we ignore and log if a directory is matched, for instance), and it could make sense to do this check in the same place.

A few other brief notes from thinking through this approach:
 - You would still need to inspect the user's pattern, to make sure it didn't _start_ with a dot (we want people to be able to explicitly `import subdir/.*`)
   - I think it is sufficient to just check if the pattern portion starts with a dot and disable the filtering if it does, but I haven't thought through this thoroughly

And a couple general considerations, depending on what the maintainers think here:
 - It might be useful to some sort of configuration option to restore the original behavior
   - Alternately, it could be off by default with an option to enable, maybe until the next major version?
 - We could add a special message in the zero-matches case where we matched (but excluded) dotfiles

**Comment by we-sell-bags** [comment]
You might also want to consider "~" as well as "." , 
which I have seen some platforms use to mark windows files as deleted in some file systems.

**Comment by cincodenada** [comment]
@mholt I think @we-sell-bags wasn't talking about the "home" tilde, but rather files like `exampledocument.txt~` which is a separate convention. I think it's more common in Windows, I'm familiar with it because some editors (including on Linux, e.g. kate, vim by default) do so for their auto-backup files. I'm not familiar with the wider use that @we-sell-bags references.

I think not including dotfiles is different from this because dotfiles are a nearly-universal standard in Unixy systems for marking a file as "hidden", and especially because most shells don't include dotfiles in their globbing. I'm not familiar with _any_ context that excludes tilde files from globbing.

As such I think excluding tilde files would be a more surprising and less intuitive behavior. My goal here is to make the globbing work like most people expect, which overlaps with but is much more contained than the larger problem of "guessing what files the user _actually_ wants to include", which is not a problem I think the import directive should try to solve.

**Comment by mholt** [comment]
Oh, I see. That's very unusual. :stuck_out_tongue: 

Let's start with dotfiles, then if anyone is actually hitting a snag with tilde files, we can address that after getting their report/use case.

**Comment by we-sell-bags** [comment]
it is more MS deliberate corruption of the standards.

you don't need to be running this on windows...... you only need to have windows kit exposed the directory. with R/W for that user.... also i have seen windows spam  all over a linux directory tree....

Personally I avoid it where possible , but running linux kit back end.. you get to see these things...

**Comment by simon04** [comment]
For a related change in Go see https://github.com/golang/go/commit/36dbf7f7e63f3738795bb04593c3c011e987d1f3: `//go:embed` excludes hidden files unless the pattern starts with `all:`

**Comment by francislavoie** [comment]
This is done as of https://github.com/caddyserver/caddy/pull/5320, this didn't get closed for some reason.
