### ISSUE TITLE
Security Issues found out thru TLS-Scanner

### ISSUE THREAD

**Issue by muller2002** [caddyserver/caddy#5055]
Hello,

i ran the [TLS Scanner](https://github.com/tls-attacker/TLS-Scanner) to check the security from my website.
The overall security is good, even in default configs. 

But there are some recommendations, i am unable to resolve. These are the recommendations made by the tool:

> The server is TLS version intolerant. There is a bug in your implementation. Update your software or contact the developers.
> The server is ALPN intolerant. There is a bug in your implementation. Update your software or contact the developers.
> The server does not reject invalid SNI names. If possible configure your server to use strict SNI and strict ALPN verification
> The server does not reject unsupported ALPN Strings. If possible configure your server to use strict ALPN verification
> Extended master secret extension is not supported. Enable support for the extended master secret
> Encrypt-then-MAC extension is not supported. Enable support for the Encrypt-then-MAC
> Secure renegotiation extension is disabled. Consider to enable secure renegotiation extension.
> The server does not reject invalid SNI names. If possible configure your server to use strict SNI verification

The first 3 (TLS Version intolerant, ALPN intolerant and invalid SNI names) are considered critical.
Is there a way to configure these away? or can these only be acomplished by changing/updating Caddy?

If you want to use the tool, installing is farely easy. If you want to scan my website, feel free to scan [marlena.app](marlena.app).

Thank you in advance

**Comment by mholt** [comment]
I don't really know what to make of that. Is there any more information?

What does "intolerant" and "invalid" and "unsupported" mean, exactly? Are there definitions of what these are testing?

For example, I would expect to see useful output with links to full documentation for each test, like this site: https://www.ssllabs.com/ssltest/analyze.html?d=marlena.app&s=188.34.176.176&hideResults=on

Your site gets an A+ from an industry standard testing tool, btw.
