### ISSUE TITLE
v2.6.0: HTTP/3 fails test on http3check.net

### ISSUE THREAD

**Issue by feld** [caddyserver/caddy#5069]
Is this normal that QUIC is shown to not be supported?

<img width="284" alt="image" src="https://user-images.githubusercontent.com/40271278/191805842-2e4b5ee8-4d89-4952-b44a-abbe225e6226.png">

**Comment by francislavoie** [comment]
I think this is fine, I think that website is checking for an older QUIC draft. Caddy supports the latest implementation which was ratified as RFC 9114, which is HTTP/3.

**Comment by mholt** [comment]
Yep, we don't support old draft versions anymore. Standardized HTTP/3 only.

**Comment by khanakia** [comment]
HTTP3 returns 404 on caddy version 2.6.0
Also when i browse the site Network Tab in Chrome Dev tools shows site was served over http2 not HTTP3

<img width="689" alt="Screenshot 2022-10-04 at 11 26 24 AM" src="https://user-images.githubusercontent.com/2174170/193745118-afdfe788-5f73-47ed-b9ad-98021a5ebb49.png">

**Comment by mholt** [comment]
@khanakia I'm not sure what that has to do with http3check.net. Please ask your question on our forum: https://caddy.community and fill out the help template with details, or if you think this is a bug, please open a new issue with enough information for us to minimally reproduce the bug from scratch.

**Comment by khanakia** [comment]
Thanks, Basically, as you see in the screenshot Http/3 returns 404 but when I check chrome dev tools it's working fine now pages are loading over the H3 protocol.

But curl with http3 returns 404

**Comment by mholt** [comment]
@khanakia Please post on the forum or open a new issue. Closed issues about something different are not an appropriate place to post questions like this.
