### ISSUE TITLE
Add retries to http loader

### ISSUE THREAD

**Issue by yroc92** [caddyserver/caddy#5070]
# Add retries to the http loader

## Context
Intermittently, we have Caddy instances booting up on new servers seeing the `net/http: TLS handshake timeout` error with the http loader in use. These failed connections are likely due to the fact that the http call made in `httploader.go` is the first connection made to the host and as such, the TLS handshake is being established for the first time. Perhaps it is too slow or something gets dropped during the handshake around the globe 🌍.

## Industry-standard solution
In distributed systems, such outages are expected. Retries with exponential backoffs are often the go-to solution to this problem.

## Proposed implementation
Let's leverage hashicorp's [go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) package, a light wrapper around `net/http`. We can use the defaults while modifying [Client.RetryMax](https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#Client) to be configurable in Caddy's config:
```
{
  // ... other http loader config fields
  "max_retries": 10 // default to 0
}
```
I'm happy to submit a pr for this solution as soon as possible.

**Comment by mholt** [comment]
Thanks for the proposal and PR Cory!
