### ISSUE TITLE
Weird Interactions between 103 Early Hints, Headers, and Reverse Proxy

### ISSUE THREAD

**Issue by leafac** [caddyserver/caddy#5074]
I started playing around with the `103 Early Hints` implementation in Caddy 2.6.1 and found some odd behavior.

**Summary**

If the `103 Early Hints` is generated by Caddy:

- Caddy doesn’t remove the headers that it should remove from the reverse proxy response.
- Caddy adds the `Link` headers that pertain to the `103 Early Hints` response even to the reverse proxy response.

If the `103 Early Hints` is generated by the underlying application:

- Caddy processes headers only to the `103 Early Hints` early response, not to the main response.

**Details**

_Base Case (No Headers; No `103 Early Hints`)_

Let the underlying application be a “Hello World.” Without loss of generality I’ll use Express.js. If you wish to follow along:

```console
$ npm install @leafac/caddy express
```

```javascript
// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.send("Hello World");
});
app.listen(3000);
```

Configure Caddy as a reverse proxy:

```caddyfile
# Caddyfile
localhost
reverse_proxy localhost:3000
```

And run the following in separate terminals:

```console
$ node index.mjs
$ npx @leafac/caddy run
$ curl -sv "https://localhost/" > /dev/null
```

```
< HTTP/2 200
< alt-svc: h3=":443"; ma=2592000
< content-type: text/html; charset=utf-8
< date: Fri, 23 Sep 2022 17:44:24 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< server: Caddy
< x-powered-by: Express
< content-length: 11
```

Note how Express.js & Caddy both generated identifying headers:

```
server: Caddy
x-powered-by: Express
```

---

_Adding & Removing Headers (Still no `103 Early Hints`)_

Change both the application & the Caddy configuration to add/remove custom headers:

```javascript
// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.header("Hello-From-Express", "true");
  res.send("Hello World");
});
app.listen(3000);
```

```caddyfile
# Caddyfile
localhost
header Hello-From-Caddy true
header -Server
header -X-Powered-By
reverse_proxy localhost:3000
```

Repeat the commands in different terminals:

```console
$ node index.mjs
$ npx @leafac/caddy run
$ curl -sv "https://localhost/" > /dev/null
```

```
< HTTP/2 200
< alt-svc: h3=":443"; ma=2592000
< content-type: text/html; charset=utf-8
< date: Fri, 23 Sep 2022 17:45:06 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< hello-from-caddy: true
< hello-from-express: true
< content-length: 11
```

Note how Caddy successfully added the `Hello-From-Express` & `Hello-From-Caddy`, and successfully removed the `Server` & `X-Powered-By` headers.

So far so good.

---

_Adding `103 Early Hints` with Caddy_

Change the Caddy configuration to include a `103 Early Hints`:

```caddyfile
# Caddyfile
localhost
header Hello-From-Caddy true
header -Server
header -X-Powered-By
route {
  header  Link "</style.css>; rel=preload; as=style"
  header  Link "</script.js>; rel=preload; as=script"
  respond 103
}
reverse_proxy localhost:3000
```

Repeat the commands in different terminals:

```console
$ node index.mjs
$ npx @leafac/caddy run
$ curl -sv "https://localhost/" > /dev/null
```

```
< HTTP/2 103
< alt-svc: h3=":443"; ma=2592000
< hello-from-caddy: true
< link: </script.js>; rel=preload; as=script
< HTTP/2 200
< alt-svc: h3=":443"; ma=2592000
< content-type: text/html; charset=utf-8
< date: Fri, 23 Sep 2022 17:41:52 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< hello-from-caddy: true
< hello-from-express: true
< link: </script.js>; rel=preload; as=script
< x-powered-by: Express
< content-length: 11
```

**At this point, I note two weird things:**

1. Caddy no longer removed the `X-Powered-By` header from the underlying application, even though it added the `Hello-From-Caddy` header, which indicates that it is processing headers.
2. Caddy adds the `Link` header even to the `200` response. It’s weird that the `Link` headers are **leaking** from the `route` in the Caddy configuration.

---

_Adding `103 Early Hints` with the Underlying Application_

Revert the Caddyfile to not add `103 Early Hints`:

```caddyfile
# Caddyfile
localhost
header Hello-From-Caddy true
header -Server
header -X-Powered-By
reverse_proxy localhost:3000
```

Change the underlying application to:

```javascript
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.socket.write(`HTTP/1.1 103 Early Hints
Link: </style.css>; rel=preload; as=style

`);
  res.header("Hello-From-Express", "true");
  res.send("Hello World");
});
app.listen(3000);
```

Repeat the commands in different terminals:

```console
$ node index.mjs
$ npx @leafac/caddy run
$ curl -sv "https://localhost/" > /dev/null
```

```
< HTTP/2 103
< alt-svc: h3=":443"; ma=2592000
< hello-from-caddy: true
< link: </style.css>; rel=preload; as=style
< HTTP/2 200
< content-type: text/html; charset=utf-8
< date: Fri, 23 Sep 2022 17:50:19 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< hello-from-express: true
< x-powered-by: Express
< content-length: 11
```

**At this point, I note another weird thing:** Caddy is only processing the headers for the `103 Early Hints`, and the main response goes through with no header processing.

---

Let me know if you want more detail on something. Also, let me know if I’m misunderstanding something about the intended behavior of `103 Early Hints`. And let me know if there’s something I can do to help.

And thanks for Caddy! It’s awesome!

**Comment by mholt** [comment]
> Caddy no longer removed the X-Powered-By header from the underlying application, even though it added the Hello-From-Caddy header, which indicates that it is processing headers.

Interesting. I'm just guessing but that's probably because header removal is a _deferred_ action by default (done right before the header is written), not an immediate change to the headers.

I'd need to look at the code but maybe 103 doesn't count as "the header is written" because it's like a pre-response.

> Caddy adds the Link header even to the 200 response. It’s weird that the Link headers are leaking from the route in the Caddy configuration.

I'm not sure what you mean by "leaking" -- do you mean that you expect the Link headers should _only_ be present in the 103 response?

RFC 8297 says:

> Typically, a server will include the header fields sent in a 103 (Early Hints) response in the final response as well.

So I think that is fine in this case.

> At this point, I note another weird thing: Caddy is only processing the headers for the 103 Early Hints, and the main response goes through with no header processing.

That one I'm not quite as sure about... would need to investigate.

**Comment by francislavoie** [comment]
> I'd need to look at the code but maybe 103 doesn't count as "the header is written" because it's like a pre-response.

"Deferred" means when the handler goes back up the chain, but that doesn't happen with a 103 until after the proxy writes its response because it's still on the way down the chain.

**Comment by mholt** [comment]
I forgot that the `headers` handler has its own responseWriterWrapper, which doesn't really account for 1xx responses:

https://github.com/caddyserver/caddy/blob/eead00f54a4b5d55292b2dcf5f1ec462c79207ad/modules/caddyhttp/headers/headers.go#L331-L335

Compare this to:

https://github.com/caddyserver/caddy/blob/eead00f54a4b5d55292b2dcf5f1ec462c79207ad/modules/caddyhttp/responsewriter.go#L177-L192

which does account for 1xx.

**Comment by mholt** [comment]
@leafac Thanks for the detailed and simplified reproducers. I was able to easily see the behavior you're talking about and understand it.

As you can see above, on the first call to WriteHeader() we'd always set `wroteHeader = true`, which would prevent any repeated header manipulations.

This restriction can be relaxed for 1xx responses. I even seem to remember thinking this when implementing 1xx but then something came up and I got distracted.

Anyway, that's why:

> Caddy no longer removed the X-Powered-By header from the underlying application, even though it added the Hello-From-Caddy header, which indicates that it is processing headers.

because the 103 response did the (deferred) header manipulations for that, then didn't for the final response; and

> At this point, I note another weird thing: Caddy is only processing the headers for the 103 Early Hints, and the main response goes through with no header processing.

because the (deferred) header manipulations only happened once.

Now we only set `wroteHeader = true` if the status is not in the 1xx range. See 7041970.

Please feel free to test out that commit and let us know!

**Comment by leafac** [comment]
> Thanks for the detailed and simplified reproducers. I was able to easily see the behavior you're talking about and understand it.

Thank **you** and @francislavoie for the amazing work on Caddy and for answering so quickly!

> I'm not sure what you mean by "leaking" -- do you mean that you expect the Link headers should _only_ be present in the 103 response?
> 
> RFC 8297 says:
> 
> > Typically, a server will include the header fields sent in a 103 (Early Hints) response in the final response as well.
>
> So I think that is fine in this case.

Oh, I didn’t know that 😅 Yeah, it’s fine. Thanks for teaching me 😁

> Please feel free to test out that commit and let us know!

I tested and confirmed that it fixed one of the remaining weird behaviors, but not the other:

It fixed the case in which `X-Powered-By: Express` was passing through.

It didn’t fix the case in which Caddy seems to not add headers to the 200 response.

<details>
<summary>For You Convenience Here’s the Test Scenario Again</summary>

```javascript
// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.socket.write(`HTTP/1.1 103 Early Hints
Link: </style.css>; rel=preload; as=style

`);
  res.header("Hello-From-Express", "true");
  res.send("Hello World");
});
app.listen(3000);
```

```caddyfile
# Caddyfile
localhost
header Hello-From-Caddy true
header -Server
header -X-Powered-By
reverse_proxy localhost:3000
```


```console
$ node index.mjs
$ npx @leafac/caddy run
$ curl -sv "https://localhost/" > /dev/null
```

</details>

Here’s the response I’m getting:

```
< HTTP/2 103 
< alt-svc: h3=":443"; ma=2592000
< hello-from-caddy: true
< link: </style.css>; rel=preload; as=style
< HTTP/2 200 
< content-type: text/html; charset=utf-8
< date: Sat, 24 Sep 2022 10:09:40 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< hello-from-express: true
< content-length: 11
```

Note that the 103 response includes `hello-from-caddy: true`, but the 200 response does not.

If I understand correctly, this contradicts the RFC recommendation that you mentioned above.

In fact, I suppose that to follow that recommendation Caddy could pick up the `Link` (and whatever other headers) generated by the application in the 103 response and replicate them in the subsequent 200 response. One could argue that this is the application’s responsibility, but it would a nice quality-of-life thing for Caddy to do.

**Comment by mholt** [comment]
@leafac So, I finally tried to reproduce this and I can't. Here's my config:

```
{
	debug
}

localhost {
	log
	header Hello-From-Caddy true
	header -Server # this is OK to leave in
	header -X-Powered-By
	route {
		header +Link "</style.css>; rel=preload; as=style"
		header +Link "</script.js>; rel=preload; as=script"
		respond 103
	}
	reverse_proxy localhost:3000
}

http://localhost:3000 {
	header x-powered-by backend
	respond "Backend!"
}

```

and here's my results:

```
$ curl -v "https://localhost"
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* SSL connection using TLSv1.3 / TLS13-AES128-GCM-SHA256
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.86.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 103 Early Hints
< Alt-Svc: h3=":443"; ma=2592000
< Hello-From-Caddy: true
< Link: </style.css>; rel=preload; as=style
< Link: </script.js>; rel=preload; as=script
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Alt-Svc: h3=":443"; ma=2592000
< Content-Length: 8
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 28 Sep 2022 20:21:55 GMT
< Hello-From-Caddy: true
< Link: </style.css>; rel=preload; as=style
< Link: </script.js>; rel=preload; as=script
< 
* Connection #0 to host localhost left intact
Backend!
```

Notice how the `Hello-From-Caddy` header appears in both responses.

(Also note that I made a mistake when I initially posted the release notes for using 103 Early Hints; `header` needs a `+` in front of the field name to _add_ the header, as opposed to _set_ the header. So I have changed `Link` to `+Link`)

**Comment by mholt** [comment]
I deleted a previous comment because I read your latest comment wrong and didn't replicate the setup faithfully.

I've been able to reproduce the latest behavior you're reporting, where the Hello-From-Caddy header disappears. I've confirmed that these lines:

https://github.com/caddyserver/caddy/blob/61822f129b9edbbc1ed2fd068d8e5ba919b5881d/modules/caddyhttp/reverseproxy/reverseproxy.go#L785-L788

are the culprit (by commenting them out). However when I remove those lines, way too many headers are printed.

Will try to come up with a solution that doesn't eat headers set by Caddy.

**Comment by mholt** [comment]
@leafac Ok, that might have been simple enough. Can you test https://github.com/caddyserver/caddy/pull/5091 to confirm whether that works for you?

**Comment by dunglas** [comment]
```

// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.socket.write(`HTTP/1.1 103 Early Hints
Link: </style.css>; rel=preload; as=style

`);
  res.header("Hello-From-Express", "true");
  res.send("Hello World");
});
app.listen(3000);
```

In this case, it's normal that the reverse proxy doesn't include the `Link` header in the 200 response, because the Express app doesn't either. This is a legit use case when finally the header is not needed in the 200 response. Caddy cannot (and shouldn't) override the behavior of the app here.

**Comment by leafac** [comment]
> @dunglas 
>
> In this case, it's normal that the reverse proxy doesn't include the `Link` header in the 200 response, because the Express app doesn't either. This is a legit use case when finally the header is not needed in the 200 response. Caddy cannot (and shouldn't) override the behavior of the app here.

Thanks for the information. It seems like you and @mholt understand things differently:

> @mholt 
>
> RFC 8297 says:
> 
> > Typically, a server will include the header fields sent in a 103 (Early Hints) response in the final response as well.

And if we’re to encourage people to follow this RFC recommendation, then Caddy would be in the perfect position to help out and copy the `Link` header from the 103 response into the 200 response. This way not all application developers have to learn about this RFC recommendation. Caddy already does something similar in spirit if Caddy is in charge of generating the 103 and the application generates the 200 (that is, Caddy adds the `Link` header to the 200 response) (my original message above for more on this).

---

@mholt:

I can confirm that #5091 fixes the issue. Here’s the response I’m getting in my experiment:

```
< HTTP/2 103 
< alt-svc: h3=":443"; ma=2592000
< hello-from-caddy: true
< link: </style.css>; rel=preload; as=style
< HTTP/2 200 
< alt-svc: h3=":443"; ma=2592000
< content-type: text/html; charset=utf-8
< date: Thu, 29 Sep 2022 13:53:39 GMT
< etag: W/"b-Ck1VqNd45QIvq3AZd8XYQLvEhtA"
< hello-from-caddy: true
< hello-from-express: true
< content-length: 11
```

Note that now the `Hello-From-Caddy` header is present in both the 103 as well as the 200 responses.

All of that done with a single variable change! Really impressive! 😁

Thank you very much! 👏

**Comment by dunglas** [comment]
> Caddy would be in the perfect position to help out and copy the Link header from the 103 response into the 200 response.

I think that this is a bad idea. The spec has been designed like that on purpose, to allow the app to change its mind after a long computation.

Ex:

1. Usually, you need this script file for this URL, the app adds the `Link` header to the 103 response
2. The browser receives the 103 response and starts downloading the file
3. The app does some computation and detects that the script is not needed for this specific result of the computation, so it doesn't include the `Link` header in the `200` response
4. The browser receives the final response, and cancels the downloading of the script (if it's still in progress)

If the reverse proxy automatically copies headers from the 103 response to the 200, it breaks this feature. If the app initiated the 103 response, the reverse proxy should assume that the app knows what it is doing and respects the spec.

Also, frameworks and programming languages will most likely automatically copy the headers in the 200 response while giving the way to remove them if needed. It's already the case for Go, and it's what's planned for PHP. The main issue in your example is that Node hasn't first-class support for 103 responses yet.

> Caddy already does something similar in spirit if Caddy is in charge of generating the 103 and the application generates the 200.

In this case, it makes total sense because Caddy is in charge of generating this header, the app doesn't know anything about it.

**Comment by leafac** [comment]
@dunglas: Fair enough. Thanks for teaching me these details of 103 responses that I didn’t know about.

With this settled, I think we’re ready to close the issue.

Thank you all for the fixes and the lessons 😁
