### ISSUE TITLE
How to disable http3(quic) protocol in caddy v2.6.X config /etc/caddy/Caddyfile file?

### ISSUE THREAD

**Issue by quaggalinux** [caddyserver/caddy#5075]
How to disable http3(quic) protocol in caddy v2.6.X config /etc/caddy/Caddyfile file?

Or how to define http3(quic) to use other UDP port then 443?

Because I used below global config in /etc/caddy/Caddyfile

{
http3_port 60443
}

but console command report error.

/usr/bin/caddy validate --config /etc/caddy/Caddyfile

2022/09/23 19:09:05.500	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": ""}
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:12: unrecognized global option: http3_port

**Comment by mholt** [comment]
Changing the advertised HTTP/3 port is under discussion at #4996.

You can disable HTTP/3 like so:

```
{
    servers {
        protocols h1 h2
    }
}
```

**Comment by zephyros-dev** [comment]
> There is no `http3_port` global option. Changing the advertised HTTP/3 port is under discussion at #4996.
> 
> You can disable HTTP/3 like so:
> 
> ```
> {
>     servers {
>         protocols h1 h2
>     }
> }
> ```
Is it possible to disable http/3 for some sites only? Per the documentation it doesn't seem possible, but maybe I'm missing something
https://caddyserver.com/docs/caddyfile/options#server-options
> Customizes [HTTP servers](https://caddyserver.com/docs/json/apps/http/servers/) with settings that potentially span multiple sites and thus can't be rightly configured in site blocks.

**Comment by francislavoie** [comment]
No, it's not possible, unless you use different ports per site. Protocols are server-wide.

**Comment by purple-emily** [comment]
@mholt I understand this issue is closed but can it be added as a feature?

All my services work amazingly except for grist. For some reason grist fails to open all documents and just hangs forever. I’ve nailed the issue down to h3. I want to disable h3 for grist only and leave it enabled for all my other services but as I understand this isn’t possible?

The above header snippet didn’t work either.

**Comment by mholt** [comment]
@purple-emily  the header configuration works. If you're having difficulty, try asking in our forums: https://caddy.community

**Comment by purple-emily** [comment]
@mholt you are right! I found you mentioning it in another issue and another person gave the same snippet so gave it another try. I had to clear all my cookies and site data and it absolutely works now. 

Thanks!
