### ISSUE TITLE
Can't setup a forward proxy because of caddy's host match mechanism

### ISSUE THREAD

**Issue by flyxl** [caddyserver/caddy#5092]
As desribed in this issue [The caddy2 version bahaves unexpectly](https://github.com/caddyserver/forwardproxy/issues/89):
Content of the above issue is pasted as following:

I'm trying to simply set up an https proxy which has a basic auth check and proxy everything to a http proxy listening on localhost.
In the Caddyfile, I write something like:
```
https://my.domain:31082 {
    route {
        forward_proxy {
            basic_auth user passwd
            upstream http://localhost:31081
        }
    }
}
```
However when I do curl -x https://user:passwd@my.domain:31082 https://whatever.site, it results in an error:1408F10B:SSL routines:ssl3_get_record:wrong version number. When I do curl -x https://user:passwd@my.domain:31082 http://whatever.site, it just return an empty 200 response even if the "whatever.site" does not exist.

-----------------------------

I dig into the caddy server code and find out that this related to how caddy matches a request to handler. Caddy server uses http Host header to match domains defined in config file. However, when it comes to forward proxy scenario, the request's Host is always the target host which is not your proxy's Host. The following is a typical proxy request
```
[root@VM_0_4_centos ~]# curl -x https://example.com httpbin.org/ip -v
> GET http://httpbin.org/ip HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.81.0
> Accept: */*
> Proxy-Connection: Keep-Alive
```
You can see in this case, the request Host header is httpbin.org while not example.com. When caddy server receives this request, it can't find any route of target host httpbin.org and then it just responses 200 to client.

**Comment by WeidiDeng** [comment]
Refer to [this fork](https://github.com/klzgrad/forwardproxy) for configuration, it's mostly compatible.

**Comment by mholt** [comment]
@WeidiDeng What does that fork do differently than the official https://github.com/caddyserver/forwardproxy? :monocle_face: 

Anyway, you're right in your analysis @flyxl -- but I'm going to leave this issue closed since I don't see anything actionable in this repo and I don't want to duplicate the discussion, so let's take the discussion to the plugin repository. Thanks!

**Comment by WeidiDeng** [comment]
@mholt main difference is detecting padding header which is used by [naiveproxy](https://github.com/klzgrad/naiveproxy) to add extra padding to normal http connect request. Example is more up to date.
