### ISSUE TITLE
max_buffer_size doesn't support go-humanize format

### ISSUE THREAD

**Issue by bt90** [caddyserver/caddy#5095]
I'm toying a bit with [OpenSpeedTest](https://github.com/openspeedtest/Speed-Test/issues/4#issuecomment-1229157193) and tried to tune the [max_buffer_size](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#max_buffer_size) option of the `reverse_proxy` directive. According to the docs go-humanize formats should be supported:

```
speed.example.com {

        reverse_proxy http://localhost:8086 {
                buffer_requests
                max_buffer_size 50MiB
        }
}
```

```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:112 - Error during parsing: invalid size (bytes): 50MiB
```

**Comment by mholt** [comment]
Oops, thanks for the report. Fixed in 2a8c458. Please feel free to try it out!
