### ISSUE TITLE
Firefox + HTTP/3 + Streaming Responses = Promises That Don’t Resolve

### ISSUE THREAD

**Issue by leafac** [caddyserver/caddy#5096]
Hi everyone,

I’m talking to you about this because I ran into this issue when I updated to Caddy 2.6.1, but maybe the issue is actually in Firefox 🤷

In any event, here’s what you need to reproduce:

```console
$ npm install @leafac/caddy express
```

```caddyfile
# Caddyfile
localhost
reverse_proxy localhost:4000
```

```javascript
// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.send(`fetch("/stream").then(() => {console.log("PROMISE RESOLVED")})`);
});
app.get("/stream", (req, res) => {
  let heartbeatTimeout;
  (function heartbeat() {
    res.write("\n");
    heartbeatTimeout = setTimeout(heartbeat, 15 * 1000);
  })();
  res.once("close", () => {
    clearTimeout(heartbeatTimeout);
  });
});
app.listen(4000);
```

Note how the server has two routes: `/`, which is just a “hello world”, and `/stream`, which streams a heartbeat (a new line) every 15 seconds while the connection is kept alive.

You may run this with:

```console
$ node index.mjs
$ npx @leafac/caddy run
```

Now go to Firefox (for what it’s worth, I’m on 105.0.1 in macOS), and try and get Firefox to load `https://localhost` with HTTP/3. You’ll know you succeed because the developer tools will show you the following:

<img width="1072" alt="Screen Shot 2022-09-29 at 20 10 19" src="https://user-images.githubusercontent.com/586813/193121434-48fd764d-4754-4722-8e2b-8ed6642337fc.png">

I’m not sure yet what makes browsers prefer HTTP/3 over HTTP/2, but here are some of the things that worked for me:

- “Disable Cache” under the Network tab in the developer tools.
- Restart the browser.
- Reload a bunch of times.
- Repeat…

If y’all know of a better way, please let me know!

Anyway, when you finally get it, go to the Console in the developer tools and run the command shown to you on the page: 

```javascript
fetch("/stream").then(() => {console.log("PROMISE RESOLVED")})
```

Note how the promise never gets resolved!

<img width="1072" alt="Screen Shot 2022-09-29 at 20 14 16" src="https://user-images.githubusercontent.com/586813/193122057-1a6d46d4-4a44-4c3b-8469-da93122eb9db.png">

What’s more, sometimes the requests don’t even show in the Network tab. Firefox really stopped playing ball…

---

Now, to show that this seems to be related to HTTP/3, change the Caddyfile to the following:

```caddyfile
# Caddyfile
{
  servers {
    protocols h1 h2
  }
}
localhost
reverse_proxy localhost:4000
```

Note how we’re **not** listing HTTP/3 among the protocols.

Restart Caddy.

This time Firefox will make the request and resolve the promise every time:

<img width="1072" alt="Screen Shot 2022-09-29 at 20 17 46" src="https://user-images.githubusercontent.com/586813/193122715-6eeb75e3-4b76-4d0f-93dc-97d3926fba8d.png">

---

Any insight is much appreciated, even if it’s “Caddy is doing everything right, go talk to the people at Firefox about it” 😁

Thank you very much!

**Comment by mholt** [comment]
You could try setting `flush_interval -1` in the reverse proxy; but if that doesn't work, then it might be a Firefox bug? I dunno. Does it happen on Chrome? What if you try that endpoint with `curl -v --http3` (more reliable)?

**Comment by leafac** [comment]
Oh, something I forgot to mention. @mholt, you probably already know this, but for other people who find this in the future: the `fetch()` promise is supposed to resolve as soon as the response headers are received, not when the whole response has been received. That’s why it’s sensible to expect the `fetch()` to resolve in a streaming response.

---

@mholt, thanks for pointing out `flush_interval`. I’ll give it a try and report back to you. I too thought it could be some buffering somewhere, but then I ruled it out because every other browser works fine (even when HTTP/3 is enabled).

Also, another question, if I may: The version of `curl` that comes with macOS doesn’t support the `--http3`. Do you install `curl` via Homebrew and force it to link (it’s a keg-only formula by default)? Or is there another trick that I don’t know of?

**Comment by mholt** [comment]
Yeah, let me know... I'm not sure otherwise.

For testing HTTP/3 with curl, I followed this guide: https://curl.se/docs/http3.html

(I also just recently opened a PR to update the Caddy part of those docs at the end. https://github.com/curl/curl/pull/9623)

**Comment by leafac** [comment]
I tried `flush_interval -1` and, as we expected, it didn’t change Firefox’s behavior.

<details>
<summary>For completeness, here’s the <code>Caddyfile</code></summary>
```caddyfile
# Caddyfile
localhost
reverse_proxy localhost:4000 {
  flush_interval -1
}
```
</details>

---

I then found https://everything.curl.dev/get/macos, by the author of curl, with recommends getting curl from Homebrew for the latest version. As it turns out, Homebrew’s version of curl is the latest, but doesn’t support HTTP/3 😐

---

I then found [Cloudflare’s formula for curl](https://github.com/cloudflare/homebrew-cloudflare/blob/acd80663ab6f1c43d4cd1f67517aed69fa3bf468/curl.rb) which is supposed to have HTTP/3 support. I tried to install it but ran into all sorts of compilation problems.

<details>

```
==> Cloning https://github.com/cloudflare/quiche.git
Updating /Users/leafac/Library/Caches/Homebrew/curl--quiche--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 06632d7 refactor processing undecrypted 0-RTT packets
Entering 'quiche/deps/boringssl'
/Users/leafac/Library/Caches/Homebrew/curl--quiche--git/quiche/deps/boringssl
==> Downloading https://curl.se/download/curl-7.81.0.tar.bz2
Already downloaded: /Users/leafac/Library/Caches/Homebrew/downloads/e72ab7b1e338d42542e13ed5b8f8b14c350c66b134332120232891bdc69176c1--curl-7.81.0.tar.bz2
Warning: curl 7.85.0 is available and more recent than version 7.81.0.
==> cargo build --release --package=quiche --features=ffi,pkg-config-meta,q
==> ./configure --prefix=/opt/homebrew/Cellar/curl/7.81.0 --with-ssl=/priva
==> make install
Last 15 lines from /Users/leafac/Library/Logs/Homebrew/curl/03.make:
                            sizeof(qs->scid), addr, addrlen, qs->cfg);
                                                                    ^
/private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include/quiche.h:254:14: note: 'quiche_connect' declared here
quiche_conn *quiche_connect(const char *server_name,
             ^
1 error generated.
make[1]: *** [vquic/libcurl_la-quiche.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vssh/libssh.c  -fno-common -DPIC -o vssh/.libs/libcurl_la-libssh.o
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vquic/vquic.c -o vquic/libcurl_la-vquic.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vtls/openssl.c -o vtls/libcurl_la-openssl.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vtls/vtls.c -o vtls/libcurl_la-vtls.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vssh/libssh.c -o vssh/libcurl_la-libssh.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/deps/boringssl/src/include/openssl -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/libssh2/1.10.0/include -isystem /opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -isystem /opt/homebrew/Cellar/rtmpdump/2.4+20151223_1/include -isystem /opt/homebrew/Cellar/libidn2/2.3.3/include -isystem /opt/homebrew/Cellar/libnghttp2/1.50.0/include -isystem /private/tmp/curl-20221002-93914-1x07uwt/curl-7.81.0/quiche/quiche/include -fvisibility=hidden -Qunused-arguments -Wno-pointer-bool-conversion -Os -Werror=partial-availability -c vtls/sectransp.c -o vtls/libcurl_la-sectransp.o >/dev/null 2>&1
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```

</details>

---

The instructions at https://curl.se/docs/http3.html look a bit too involved, so I decided not to pursue this route right now.

---

At this point I gave up on curl for now and decided to chalk up the problem as an issue in Firefox.

I’m closing this issue in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1793342

Thank you very much for your help!

**Comment by leafac** [comment]
@mholt: Yes, I saw that you were following the conversation at Firefox’s bug tracker.

My post there gives more detail, but in summary:

Caddy seems to add a `Content-Type` header to the HTTP/2 response, but not to the HTTP/3 response. Without a a `Content-Type` header, Firefox keeps waiting indefinitely for a certain amount of bytes to arrive so that it can try and sniff the content type.

I think that Firefox should have some kind of timeout on that process, and I proposed that to them.

At the same time, I think that Caddy should be consistent when it comes to the `Content-Type` header: either add it to both HTTP/2 & HTTP/3, or to neither.

I’m reopening the issue for you to consider this.

For the time being, I can set a `Content-Type` header in my application and reenable HTTP/3 in Caddy 👏 (It’s probably a good idea to specify the `Content-Type` anyway…)

**Comment by mholt** [comment]
Interesting, our handlers are the same no matter the http version. I wonder if there is a difference between what the quic-go server does from what the std lib server does.

**Comment by mholt** [comment]
@leafac Can you give us enough info to reproduce the content-type issue? I see you're reverse proxying but as we don't have your backend, can you reproduce it any other simple, self-contained way?

**Comment by leafac** [comment]
@mholt I’m reverse proxying to the Express application given in my first comment:

```javascript
// index.mjs
import express from "express";
const app = express();
app.get("/", (req, res) => {
  res.send(`fetch("/stream").then(() => {console.log("PROMISE RESOLVED")})`);
});
app.get("/stream", (req, res) => {
  let heartbeatTimeout;
  (function heartbeat() {
    res.write("\n");
    heartbeatTimeout = setTimeout(heartbeat, 15 * 1000);
  })();
  res.once("close", () => {
    clearTimeout(heartbeatTimeout);
  });
});
app.listen(4000);
```

If I can make it more convenient to run this, please let me know.

**Comment by francislavoie** [comment]
I'm surprised there's even a `Content-Type` header for H2. Caddy doesn't try to write `Content-Type` itself in the `reverse_proxy` scenario. It only adds it when you use `file_server` (or in some cases `respond` as well). So it's your app's responsibility to send that header.

**Comment by mholt** [comment]
@leafac I don't have a Node or Docker environment set up. It would be much faster if you can find a self-contained way to reproduce it. Can you just simulate the exact response with `respond` and `header` directives?

**Comment by mholt** [comment]
@francislavoie With the nuance that Go doesn't sniff MIME type if the Content-Type field is set to nil (`w.Header()["Content-Type"] = nil`). We disable this for the static file server.

But yeah, that's likely the culprit.

**Comment by leafac** [comment]
> @mholt:
>
> @leafac I don't have a Node or Docker environment set up. It would be much faster if you can find a self-contained way to reproduce it. Can you just simulate the exact response with `respond` and `header` directives?

I tried, but as far as I was able to ascertain the `respond` directive will always add the `Content-Type` header if there’s some content body. ([The documentation says the same.](https://caddyserver.com/docs/caddyfile/directives/respond)) That’s true even if you try to remove that header:

```caddy
localhost
header -Content-Type
respond "HELLO"
```

The `Content-Type` header won’t be added if the response has no content body:

```caddy
localhost
header -Content-Type
respond 200
```

But in that case a Caddy reverse proxy doesn’t add the `Content-Type` header either—not for HTTP/2, nor for HTTP/3. Perhaps the Go standard library notices that the response has no body and skips content sniffing… 🤷

In any case, if you really want me to I can try and find some other way to make this easier for you to reproduce, for example, I can try and translate my Express example into Go. But it appears to me that you and @francislavoie already know what’s going on, so perhaps I don’t need to 😬🤞

**Comment by leafac** [comment]
@mholt:

Yes!

With the configuration that you provided I can reproduce the issue: Google Chrome in HTTP/3 mode doesn’t receive the `Content-Type` header, and `curl -sv https://localhost > /dev/null` in HTTP/2 mode does receive it:

<img width="1920" alt="Screen Shot 2022-10-05 at 18 43 16" src="https://user-images.githubusercontent.com/586813/194126441-c1add461-23e8-491c-98d9-2db6d89961f3.png">

Thanks for the help! 😁

**Comment by mholt** [comment]
Awesome! Thanks.

@leafac So to clarify, Mozilla still has a bug in Firefox right? Meanwhile we will try to make the Content-Type header consistent between H1,H2 and H3.

@marten-seemann Would you have any ideas on this, maybe we can figure out how to implement the Go std lib behavior of content-type sniffing to maintain parity between std lib H1,H2 and quic-go's H3?

**Comment by leafac** [comment]
> @mholt:
>
> @leafac So to clarify, Mozilla still has a bug in Firefox right?

Hmmm 🤔 I think it’s a bug, but I don’t know if they’ll agree 🤷

Perhaps it’s their preference that a `fetch()` promise only resolves after content sniffing received enough bytes. Streaming responses better send a `Content-Type` in that case…

Or perhaps they’ll prefer to do what Google Chrome does…

**Comment by marten-seemann** [comment]
Thank you @mholt! I guess that means we’d have to block until the first 512 bytes of the response body are written, right?

I’m super busy at the moment, but I’d be happy to review a PR, if anyone wants to submit one.

**Comment by mholt** [comment]
@marten-seemann Nope, looks like it is called on the first `Write()` no matter its size: https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/http/server.go;l=375;drc=cbd931c9c2705e0e3a44c3b299ac2bd3369f5eb5;bpv=1;bpt=1 -- doesn't have to be a full 512 bytes.

I'm also super busy, ha. Maybe a volunteer would like to submit a PR? #Hacktoberfest?

**Comment by marten-seemann** [comment]
quic-go issue: https://github.com/lucas-clemente/quic-go/issues/3573

**Comment by leafac** [comment]
> @marten-seemann
>
> I guess that means we’d have to block until the first 512 bytes of the response body are written, right?

@mholt already answered you, but I want to point out that blocking while waiting for 512 bytes is what got us here in the first place. It seems to be what Firefox does, and [I think it’s a bad idea](https://bugzilla.mozilla.org/show_bug.cgi?id=1793342).

I believe that content-type sniffing should run in a best-effort basis, and not block anything along the way, be it the server, reverse proxy, or browser. It’s less surprising that way…

**Comment by marten-seemann** [comment]
@leafac That makes sense. I don't think we should block. Do you want to contribute a fix to quic-go? :)

**Comment by francislavoie** [comment]
Nice, https://github.com/quic-go/quic-go/releases/tag/v0.33.0 includes the fix for this I think, via https://github.com/quic-go/quic-go/pull/3715. It'll be included in Caddy's next release as of https://github.com/caddyserver/caddy/commit/8cb1bb4af30b880f981b1ae6fdb13e5944bfaefe. If anyone would like to test it by building from `master`, that'd be great!
