### ISSUE TITLE
Caddy serve static file if reverse_proxy is down

### ISSUE THREAD

**Issue by mahdix** [caddyserver/caddy#5100]
Hi,

I looked in the documents but couldn't find a solution for this. If the app at "reverse_proxy" is down, is it possible to serve a static file instead? (e.g. a file which contains "We are under maintenance please check back later...").

The documentation says Caddy can handle HTTP error status like 503 with custom handlers, but this is for the case that backend is down.

**Comment by mohammed90** [comment]
For failures of reverse-proxy upstream, look into response handlers within the reverse-proxy handler. The [`reverse_proxy` documentation](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#handle_response) lists an example that does exactly what you're asking for. Search for `Custom error page for errors from upstream` on the linked page.

For the next time, please ask in out [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
