### ISSUE TITLE
rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by rdwz** [caddyserver/caddy#5111]
> Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/
https://github.com/github/renaming

**Comment by mholt** [comment]
I don't really care what the branch is named, so if someone else does, we can change it if it won't break anyone/anything.

**Comment by ReillyBrogan** [comment]
> I don't really care what the branch is named, so if someone else does, we can change it if it won't break anyone/anything.

I believe github will setup the appropriate redirects so that nothing breaks.

**Comment by mholt** [comment]
Won't people's local clones break? They'd have to reconfigure their project repos I'm pretty sure, which would also likely break a lot of automated tooling?

**Comment by redwerkz** [comment]
> Renaming a branch will:
> 
> - Re-target any open pull requests
> - Update any draft releases based on the branch
> - Move any branch protection rules that explicitly reference the old name
> - Update the branch used to build GitHub Pages, if applicable
> - Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
> - Show a notice to contributors who git push to the old branch
> - Redirect web requests for the old branch name to the new branch name
> - Return a "Moved Permanently" response in API requests for the old branch name

![rename-default-branch-dialog](https://user-images.githubusercontent.com/8125196/193740599-8b99cf05-59db-4913-808e-9cb5fbc2cfb3.png)

from: https://github.com/github/renaming#renaming-existing-branches

**Comment by mholt** [comment]
I read that page, but it doesn't really answer my questions. It only says "Will not update your members' local environments."

**Comment by hairyhenderson** [comment]
I've been through lots of `master`->`main` renames over the past couple years, and as a maintainer of a bunch of public & private repos it's been quite smooth. As a contributor to lots of other projects it's also been quite straightforward. I've had one or two hiccups where a repo I hadn't pulled in over a year switched branches, but it only cost me a minute or two; as soon as I visited the repo in GitHub it was totally obvious.

So, from the perspective of whether it's prohibitively disruptive, I'd say not at all - no reason not to make the change.

**Comment by mholt** [comment]
That's good to know, thanks for sharing. However, I am particularly concerned how this will affect the Caddy plugin ecosystem specfically, as surely many build systems target the `master` branch and those automated tools and deployments will break, abnormally more so than with other projects.

**Comment by redwerkz** [comment]
just a reminder: all info and help has been given, but nothong happend
