### ISSUE TITLE
Possibility to modify ciphers for TLS1.3

### ISSUE THREAD

**Issue by Inetol** [caddyserver/caddy#5112]
## Why?
Ciphers can be modified only for TLS1.2, although this is enough for basic management it may not be enough and you may wish to configure TLS1.3 as well. An immediate example I could give would be in [SSL Labs](https://www.ssllabs.com) server testing, in order to have a perfect score you require [disabling ciphers shorter than 256 bit in length](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#cipher-strength).

## How?
*(I do not know whether it is possible since I do not understand nor use Go)*
To avoid breaking the current setup, I propose allowing TLS1.3 ciphers to be included along with TLS1.2 ciphers within the [tls ciphers](https://caddyserver.com/docs/caddyfile/directives/tls#ciphers) parameter. I am not a big fan of this idea because TLS1.2 or TLS1.3 could be left without ciphers if there are only ciphers for one protocol, so I propose another idea with more weight. Separate TLS1.2 from TLS1.3 of tls ciphers parameter;
```
#Caddyfile format

tls {
    ...

    ciphers {
        tls1_3 TLS_AES_256_GCM_SHA384 ...
        tls1_2 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 ...
    }
}
```
In case one parameter is not used, use the defaults or if the protocol is not enabled then ignore it. Again I don't know if this can be done in the first place or if it is desirable to do it this way, I hope for feedback as I think it may be useful.

**Comment by francislavoie** [comment]
It's not possible to modify ciphers for TLS 1.3. Go's stdlib does not allow it, and with good reason: https://words.filippo.io/dispatches/cipher-suite-ordering/
