### ISSUE TITLE
ASDF plugin fails to download the specific Caddy version!!

### ISSUE THREAD

**Issue by abhijit-kar** [caddyserver/caddy#5119]
Hi Team,

I love Caddy ❤️, and today I dumped Haproxy in favour of Caddy.

To ease my life I tried to install Caddy using an ASDF plugin, but it fails!

Command:
```elixir
asdf plugin-add caddy https://github.com/salasrod/asdf-caddy.git
echo "caddy 2.6.1" >> .tool-versions
asdf install
```

Yields:
```elixir
Downloading [caddy] from https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.1_mac_arm64.pem
https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.1_mac_arm64.tar.gz
https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.1_mac_arm64.tar.gz.sig to /var/folders/gt/kszxrnn10x1g8b60fcy1hm800000gn/T/asdf_XXXXXXXX.hTaBGfM9/caddy-2.6.1
curl: (3) URL using bad/illegal format or missing URL
```

N.B: Link to the issue create on ASDF plugin's page: [Original Issue](https://github.com/salasrod/asdf-caddy/issues/10)

P.S. Can't wait to introduce Souin & Authp to my Caddy setup!!

**Comment by abhijit-kar** [comment]
It’s for versioning tools locally!! [ASDF](https://asdf-vm.com/)

> `.tool-versions` to manage all your tools, runtimes and their versions in a single, sharable place.

**Comment by mholt** [comment]
I'm not sure how to help, this seems unrelated to any of the code within Caddy itself, so I'm going to close this. Probably try asking the ASDF developers and see if they can help!

**Comment by abhijit-kar** [comment]
Understood, thanks for taking your time to reply to my concern.

I'm aware that this request isn't a direct part of the Caddy code and I didn't mean to impose.

I thought it might have been on radar of the team or community, so I pointed it out.

Regardless, Caddy works flawlessly and can be installed easily via Homebrew, so no issues there.
