### ISSUE TITLE
Stop `stat`ing files in dir when request context is cancelled

### ISSUE THREAD

**Issue by abdusco** [caddyserver/caddy#5129]
I am using Caddy to serve a dir using `file_server` middleware. The directory is hosted on a network drive. So, `stat`ing files aren't really cheap, because each stat requires performing a network IO, and it adds up when listing a directory with hundreds of files.

Caddy doesn't pass down the request context to directory listing

https://github.com/caddyserver/caddy/blob/b4e28af953aa02fb44f88c155956488b1f473348/modules/caddyhttp/fileserver/browse.go#L85

This means if I close the tab before the page loads (before caddy finishes `stat`ing all files in directory), caddy keeps on stating and it slows down the disk access for everything else.

https://github.com/caddyserver/caddy/blob/b4e28af953aa02fb44f88c155956488b1f473348/modules/caddyhttp/fileserver/browse.go#L139-L148

It should check if context is cancelled, and stop doing needless disk IO.

**Comment by abdusco** [comment]
I feel like passing request context down to this method and bailing out if it's cancelled should work:

```golang
func (fsrv *FileServer) directoryListing(ctx context.Context, entries []fs.DirEntry, canGoUp bool, root, urlPath string, repl *caddy.Replacer) browseTemplateContext {
	filesToHide := fsrv.transformHidePaths(repl)

	var dirCount, fileCount int
	fileInfos := []fileInfo{}

	for _, entry := range entries {
		if err := ctx.Err(); err != nil {
			break // or return err?
		}
```

but I'm not sure about how this affects the performance:

```golang
files, err := dir.ReadDir(10000) // TODO: this limit should probably be configurable 
```

How does walking the dir with `filepath.WalkDir()` compare to this?

**Comment by abdusco** [comment]
Also, I can take over this issue and submit a PR with the solution I outlined above, unless you have something in mind.

**Comment by mholt** [comment]
@abdusco Yes, this sounds like a great idea. Would you like to submit a PR then? Your proposal above sounds like how I'd do it. (For some reason I didn't realize you could just check ctx.Err() to see if it was done, I always selected on ctx.Done() but checking the Err() is even easier!)

You could compare using WalkDir() if you want, I don't have a network drive setup handy to test with right now. I'd be curious which one is faster!

**Comment by abdusco** [comment]
Before the fix:

```golang
func (fsrv *FileServer) directoryListing(ctx context.Context, entries []fs.DirEntry, canGoUp bool, root, urlPath string, repl *caddy.Replacer) browseTemplateContext {
	filesToHide := fsrv.transformHidePaths(repl)

	var dirCount, fileCount int
	var fileInfos []fileInfo
	go func() {
		select {
		case <-ctx.Done():
			fsrv.logger.Error("listing cancelled")
		}
	}()
	for _, entry := range entries {
		// if err := ctx.Err(); err != nil {
		// 	break
		// }
		
		// ...
	}
	fsrv.logger.Error("listing finished")
```


```
2022/10/08 04:38:31.937 ERROR   http.handlers.file_server       listing cancelled
2022/10/08 04:38:59.884 ERROR   http.handlers.file_server       listing finished
```

Listing takes ~20s more.

After the fix:

```
2022/10/08 04:42:55.004 ERROR   http.handlers.file_server       listing finished
2022/10/08 04:42:55.007 ERROR   http.handlers.file_server       listing cancelled
```

**Comment by abdusco** [comment]
One more point of optimization, but it's not so straightforward: 

Ideally, `stat` should be performed lazily, and executed after we apply the pagination. However this breaks sorting by size & time, because we wouldn't have those info at hand.

**Comment by abdusco** [comment]
~~`filepath.WalkDir`~~ `fs.WalkDir` calls `dir.ReadDir(-1)` internally, so it wouldn't make any difference (or it would be even slower for dirs with >10000 items) if we refactor.

**Comment by mholt** [comment]
Ah, right, I think I knew that, but forgot.

Thank you for the fix.

I'd be open to paginating the browse listings, if possible. (Could be a future TODO)
