### ISSUE TITLE
Error during parsing: unrecognized servers option 'metrics' - when trying to enable metrics via caddyfile

### ISSUE THREAD

**Issue by jaredly** [caddyserver/caddy#5136]
I added
```
{
    servers {
        metrics
    }
}
```
to the top of my caddyfile, as directed in https://caddyserver.com/docs/metrics (there was no previous global config block), and then restarting caddy (`sudo systemctl restart caddy`) failed, with the following error log:
```
Oct 10 07:17:32 local-first caddy[266067]: {"level":"info","ts":1665404252.7558618,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Oct 10 07:17:32 local-first caddy[266067]: run: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:13 - Error during parsing: unrecognized servers option 'metrics'
Oct 10 07:17:32 local-first systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
```
Caddy version:
```
~$ caddy version
v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=
```

When I remove the global config block, it starts just fine.
Surprisingly, `curl http://localhost:2019/metrics` seems to still work, even with the configuration missing?

**Comment by mholt** [comment]
You'll need to upgrade Caddy, this was added in 2.6.

**Comment by jaredly** [comment]
Hi Matt :D and thanks for the info! Maybe we can add that to the docs page? https://github.com/caddyserver/website/pull/276

**Comment by mholt** [comment]
Sure. To clarify, metrics were made opt-in with 2.6 for performance reasons. (The admin metrics are still on by default because it's not as hot a path.)

**Comment by NiklasBeierl** [comment]
Is it possible that some subsequent release broke the `metrics` global setting? 
Minimal Caddyfile:
```shell
M ~ cat Caddyfile
{
  metrics
}

http://localhost:2000 {
  file_server {
    root .
  }
}
M ~ caddy adapt Caddyfile
2025/03/07 23:26:50.347 INFO    using adjacent Caddyfile
Error: Caddyfile:2: unrecognized global option: metrics
M ~ caddy --version                                                                                                                                                                                                                                                                    
v2.8.4
```

I have another complex caddy config that I unfortnuately can't share. It has  a `metrics` handler, which _generally_ works, but I only see two admin related metrics in prometheus: 

![Image](https://github.com/user-attachments/assets/4a7f2cc7-6ea5-4bb1-93c2-fc26cc9a376f)

When I add `metrics` to the global options, the complex file produces the same `Error: Caddyfile:17: unrecognized global option: metrics`. 

Given @mholt 's comment: 

> Sure. To clarify, metrics were made opt-in with 2.6 for performance reasons. (The admin metrics are still on by default because it's not as hot a path.)

I suspect that I am looking at a situation where the `metrics` global config is off, but I can't get it on because I am either misunderstanding the syntax or there is an issue with Caddyfile parsing / the docs.

**Comment by mohammed90** [comment]
@NiklasBeierl , this a 2-year old, closed issue. You're likely running a version older than 2.9.

**Comment by NiklasBeierl** [comment]
> [@NiklasBeierl](https://github.com/NiklasBeierl) , this a 2-year old, closed issue. You're likely running a version older than 2.9.

As the shell  excerpt details, I am using 2.8.4. Some projects prefer reopening old issues, some prefer opening new ones. Seeing you are pretty active on this project I guess opening new ones is preferred. Will do.

**Comment by mohammed90** [comment]
> > [@NiklasBeierl](https://github.com/NiklasBeierl) , this a 2-year old, closed issue. You're likely running a version older than 2.9.
> 
> As the shell excerpt details, I am using 2.8.4. Some projects prefer reopening old issues, some prefer opening new ones. Seeing you are pretty active on this project I guess opening new ones is preferred. Will do.

No need to open any issues. You need at least version 2.9.0 for that option.
