### ISSUE TITLE
Release notes: Add warning about removal of single-dash arg support

### ISSUE THREAD

**Issue by am97** [caddyserver/caddy#5137]
After upgrading to Caddy 2.6.1, one of my scripts unexpectedly broke because I used arguments with a single dash (I found out later that support was removed by https://github.com/caddyserver/caddy/pull/4565). I saw no warning in the release notes. Could you make an update to mention this breaking change ?

**Comment by mohammed90** [comment]
It was. It was mentioned in the 2.6.0 release notes, which is when it was first released. See the "Improved command line interface" section here:
https://github.com/caddyserver/caddy/releases/tag/v2.6.0

**Comment by mholt** [comment]
Sorry about that. Our website docs always used `--` but we couldn't control the output of `-h` before, which showed `-` which was inconsistent.
