### ISSUE TITLE
caddy's basicauth directive has two security design issue

### ISSUE THREAD

**Issue by chunklhit** [caddyserver/caddy#5138]
Precondition:  A CaddyFile content as below, then run 'caddy start'
`:2015 {
        root * cve
        basicauth /test/* {
                test $2a$14$oc7HAdS4HvynuCIW7tIMHuAABP2DmS47Hq2wTnnRrdqOcYm9cuRhO
        }
        file_server browse
}`

Issue 1: I submit the username/pwd after i click test directory.  My username/pwd info is base64  which is setted to request's head Authorization param.   Like below: Basic dGVzdDoxMjM0.  After Decode Base64 'dGVzdDoxMjM0', I get the Lain Text Password ‘1234’ 

Issue2: The login session never logout, even if the Caddy Service restart.

**Comment by francislavoie** [comment]
That's not a security issue, that's simply how Basic auth works.

https://en.wikipedia.org/wiki/Basic_access_authentication
