### ISSUE TITLE
Route incoming grpc based on package/service name

### ISSUE THREAD

**Issue by inliquid** [caddyserver/caddy#5142]
I looked through documentation, `caddy.community`, etc and from what I have learned it seems that `caddy` can just forward requests but not route them, f.e.:

```
localhost {
    reverse_proxy  h2c://localhost:50051
}
```

However what I would like to achieve is conditional routing depending on service, such as in this `nginx` config:
```
location /helloworld.Greeter {
 grpc_pass grpcs://dev;
 }
```

**Comment by mohammed90** [comment]
> from what I have learned it seems that caddy can just forward requests but not route them

What do you mean by this? How do you define the difference between route vs forward in your view?

Anyways, [gRPC method calls are specified via the path of the request](https://chromium.googlesource.com/external/github.com/grpc/grpc/+/HEAD/doc/PROTOCOL-HTTP2.md). It's more-or-less in this form: `/pkg.of.service.ServiceName/Method`. You can use the `path` or `path_regexp` matchers. Learn more about path matching [on the docs](https://caddyserver.com/docs/caddyfile/matchers).

This is more of a usage question than a bug, so please ask in [the forum (https://caddy.community)](https://caddy.community) in the future.

**Comment by francislavoie** [comment]
To clarify, you can do just this (inline path matchers, see the docs):

```
localhost {
	reverse_proxy /helloworld.Greeter h2c://localhost:50051
	reverse_proxy /helloworld.Foobar h2c://localhost:50051
}

```

**Comment by inliquid** [comment]
@francislavoie thanks! I think it might have sense to add to caddy docs.
