### ISSUE TITLE
rewrite isn't appending path as I would expect

### ISSUE THREAD

**Issue by wildfunctions** [caddyserver/caddy#5157]
I'm using 2.6.2 and have a reverse proxy setup

`faq.example.com {
	rewrite * /faq
	reverse_proxy localhost:8080 {
		header_up Host {upstream_hostport}
	}

	tls {
		on_demand
	}
	log {
		output file /var/log/caddy/access.log
	}
}`

From my understanding of rewrite, this should match and serve back the equivalent of localhost:8080/faq. However, it doesn't appear to be doing this for me. I'm just getting back a blank page (which is strange considering I didn't know my app was capable of this.)

I checked the logs and I don't see anything that outputs the final proxy target. Is there a setting to have the log print this final path after the rewrite? Seeing something like "localhost:8080/faq" would be reassuring.

The trouble appears specific to rewrite with an appended path. When I use query params, everything works fine.

`faq.example.com {
	rewrite * ?page=faq
	reverse_proxy localhost:8080 {
		header_up Host {upstream_hostport}
	}

	tls {
		on_demand
	}
	log {
		output file /var/log/caddy/access.log
	}
}`

The code above does correctly resolve to localhost:8080?page=faq, so I believe everything is working as expected except rewrite.

Edit: No idea why the editor code blocks are failing here?

**Comment by okayplanet** [comment]
This may be a different issue.

My webapp has js scripts like <script defer="defer" src="/static/js/main.41c90a9c.js"></script>
When I inspect them, they resolve to `faq.example.com/static/js/main.41c90a9c.js`, which make me wonder loading this means a journey through caddy again?

If they were rewritten as well to include the `/faq` path (Ex: target_url/faq/static/js/main.41c90a9c.js), then that would example why I'm seeing a blank page.

Does rewrite support full regex?

Maybe I want something like this:
`rewrite faq.example.com$ /faq`
Only add the `/faq` if the request is from faq.example.com... ignore example.com/static/js/main.41c90a9c.js

**Comment by francislavoie** [comment]
Relevant article about what you're trying to do: https://caddy.community/t/the-subfolder-problem-or-why-cant-i-reverse-proxy-my-app-into-a-subfolder/8575
