### ISSUE TITLE
caddy should print out why a specified tls certificate is ignored

### ISSUE THREAD

**Issue by tryge** [caddyserver/caddy#5163]
We just spent hours to find out that there was a difficult to spot typo in a SAN field in the certificate. caddy should just print out why it considers a certificate invalid for a domain as an ERROR message in the logs.

Personally I would even prefer that caddy doesn't start up if the specified certificates are invalid ( maybe a strict command line option or something like that?)

**Comment by francislavoie** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to us what is going on, so we'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! It will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1:

I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by tryge** [comment]
## 1. Environment

### 1a. Operating system and version

```
docker container, but doesn't really matter.
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.5.0 h1:eRHzZ4l3X6Ag3kUt8nj5IxATprhqKq/wToP7OHlXWA0=
```


### 1c. Go version (if building Caddy from source; run `go version`)
not built from source.


## 2. Description

### 2a. What happens (briefly explain what is wrong)

We explcitly specify a tls certificate, but caddy ignores it and generates a local certificate instead. 

### 2b. Why it's a bug (if it's not obvious)

I wouldn't necessarily say it's a but, but it's an issue and it would have saved us a lot of time.

First, the issue was not detected immediately as we swapped certificates, restarted caddy and the service was up, no error in the logs. Only later we got reports that the served certificates are invalid.

Instead of serving the certificates we specified, caddy chose to generate its own local certificates.

caddy does not print out any information about why it chooses to ignore the specified certificate. In our case a typo in one of the SAN fields (think `appl.example.com` instead of `app1.example.com`), but maybe the same behaviour happens for expired certificates, or certificates that are invalid in another way.


People in the past did have similar issues and opened a discussion and an issue, a log message indicating what the problem is would have helped them too and they probably wouldn't have had to consult with the community or create an issue here.

https://caddy.community/t/caddy-ignoring-provided-certificates/10754
https://github.com/caddyserver/caddy/issues/3422

### 2c. Log output

I had to edit the logs as they contain confidential information:
```
{"level":"info","ts":1666372035.0193973,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"debug","ts":1666372035.0198264,"logger":"tls.cache","msg":"added certificate to cache","subjects":["appl.example.com"],"expiration":1728730570,"managed":false,"issuer_key":"","hash":"1d7c74fa588691018956196ee1977a65a8e25caac50b2f347ea8d49899c0ffd8","cache_size":1,"cache_capacity":10000}
{"level":"warn","ts":1666372035.0198925,"logger":"http","msg":"automatic HTTP->HTTPS redirects are disabled","server_name":"srv0"}
{"level":"info","ts":1666372035.0212584,"logger":"pki.ca.local","msg":"root certificate trust store installation disabled; unconfigured clients may show warnings","path":"storage:pki/authorities/local/root.crt"}
{"level":"debug","ts":1666372035.021472,"logger":"http","msg":"starting server loop","address":"[::]:443","http3":false,"tls":true}
{"level":"info","ts":1666372035.0214856,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["app1.example.com"]}
{"level":"info","ts":1666372035.0215898,"msg":"autosaved config (load with --resume flag)","file":"caddy/autosave.json"}
{"level":"info","ts":1666372035.0216258,"msg":"serving initial configuration"}
{"level":"warn","ts":1666372035.0216293,"msg":"$HOME environment variable is empty - please fix; some assets might be stored in ./caddy"}
{"level":"info","ts":1666372035.0216665,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000255420"}
{"level":"info","ts":1666372035.0219302,"logger":"tls.obtain","msg":"acquiring lock","identifier":"app1.example.com"}
{"level":"info","ts":1666372035.0219364,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:./caddy"}
{"level":"info","ts":1666372035.021955,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1666372035.0235102,"logger":"tls.obtain","msg":"lock acquired","identifier":"app1.example.com"}
{"level":"debug","ts":1666372035.0242538,"logger":"tls.obtain","msg":"trying issuer 1/1","issuer":"local"}
{"level":"debug","ts":1666372035.0245502,"logger":"pki.ca.local","msg":"using intermediate signer","serial":"246812255572876370494047286846808067638","not_before":"2022-10-21 17:07:15 +0000 UTC","not_after":"2022-10-28 17:07:15 +0000 UTC"}
{"level":"info","ts":1666372035.0251002,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"app1.example.com"}
{"level":"info","ts":1666372035.0251079,"logger":"tls.obtain","msg":"releasing lock","identifier":"app1.example.com"}
{"level":"debug","ts":1666372035.025357,"logger":"tls.cache","msg":"added certificate to cache","subjects":["app1.example.com"],"expiration":1666415235,"managed":true,"issuer_key":"local","hash":"0213ebef9fc532aa5368ec53ca4d8fa00aea28f5723689aba773a24ba510adad","cache_size":2,"cache_capacity":10000}
```

**Comment by mholt** [comment]
@tryge Can you please be more specific, though, according to the bug report template's instructions? Domain names are not secret, and in order to improve on this we'll need the specific domain at hand and the specific typo too.

**Comment by tryge** [comment]
I'm not really sure what you mean with more specific. Unfortunately I can't share the domain names, they are *not* public and are confidential as they reveal to much about the environment we're working in (the SAN certificate contains a lot of domain names). They don't matter, and the specific typo itself doesn't matter as well. The problem is that caddy should write a message like:

`ERROR in configuration for "app1.example.com", the TLS certificate located in '/certs/app1.example.com.pem.combined' is invalid: subjects ["appl.example.com"] don't contain "app1.example.com"` 

or something like that (of course structured but I'm not writing json here).

Also, in my opinion caddy should exit immediately when it encounters a certificate that doesn't match or is invalid. (For example it does exit immediately when the certificate files cannot be found, how is that different from the certificate not being usable?)

I could use a certificate for something completely unrelated and caddy would happily ignore it and generate a local certificate instead. I will provide a tutorial soon, although it feels really superfluous as the issue feels painfully obvious to me.

**Comment by tryge** [comment]
After preparing the tutorial I also tried with version `v2.6.2` - and the behaviour is different! caddy does indeed serve the specified certificate **even though it's invalid** for the domain. I am not sure if it is really better to serve an invalid certificate, but the issue we experienced yesterday is not present anymore. Therefore, I'm closing this issue again. I am sorry for the trouble.

**Comment by mholt** [comment]
Ok. We could look into it but we'd need the real domain names and certs to assess.

**Comment by tryge** [comment]
You mean serving an invalid certificate? Easy to reproduce and no need for our confidential domain names:

Caddyfile
```
{
        debug
        https_port 8443
        auto_https off
        skip_install_trust
}

localhost.int:8443 {
        tls localhost.cert.pem localhost.key.pem
        reverse_proxy http://localhost:8080 {
                header_down Location http:// https://
        }
}
```

Extract into the same directory as the Caddyfile, use the following certificate and key:
[cert+key.zip](https://github.com/caddyserver/caddy/files/9890352/cert%2Bkey.zip)

Add `127.0.0.1 localhost.int` to your hosts file.

From the directory with the Caddyfile run:
`caddy run --config Caddyfile`

Then use curl:

```
curl -k -vvv https://localhost.int:8443
*   Trying 127.0.0.1:8443...
* Connected to localhost.int (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost.1nt
*  start date: Oct 22 05:44:24 2022 GMT
*  expire date: Oct 19 05:44:24 2032 GMT
*  issuer: CN=localhost.1nt
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x146013600)
> GET / HTTP/2
> Host: localhost.int:8443
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 502 
< alt-svc: h3=":8443"; ma=2592000
< server: Caddy
< content-length: 0
< date: Fri, 28 Oct 2022 16:46:14 GMT
< 
* Connection #0 to host localhost.int left intact
```

Notice that I am using `localhost.int` in the domain and `localhost.1nt` in the certificate, still caddy serves it to me although it is invalid for that domain.

**Comment by mholt** [comment]
@tryge Thanks for the details. I'd have to look when I'm not mobile to be sure, but we may be serving the cert "no matter what" whenever it is explicitly configured by the user, i.e. not an automated certificate. (This is useful for some niche applications of TLS.)
