### ISSUE TITLE
Get resource from upstream if unavailable

### ISSUE THREAD

**Issue by zishanj** [caddyserver/caddy#5165]
Suppose I have 2 servers, ServerA and ServerB with load balancing. If for some reason a specific file is unavailable on ServerB then it should retrieve it from upstream ServerA.

How can I accomplish this in Caddy?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

You can intercept `reverse_proxy` responses with `handle_response`. See the docs: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#intercepting-responses

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
