### ISSUE TITLE
[opentelemetry] add ability to contextualize span name

### ISSUE THREAD

**Issue by cdaguerre** [caddyserver/caddy#5171]
Since caddy is often the entry point to an application, it's generally the root span and it's name becomes the operation name of the entire trace. As a result, tools like Jaeger show a list of various operations that all have the same name.

It would be great if the span name could be customized on a "per request" basis with string interpolation in the span name, eg.

```
tracing {
  span '{request>uri}'
}
```
or even get the operation name from the upstream like this:
```
tracing {
  span '{response>headers>X-Trace-Operation-Name}'
}
```

**Comment by francislavoie** [comment]
/cc @andriikushch @cedricziel 

Sounds like we just need placeholder support for the span name. Is it possible to run the replacer at runtime, or must the span name be known at provision-time?

**Comment by cdaguerre** [comment]
Thanks for clarifying the syntax!

I don't know the first thing about Go but [this](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/tracing/tracer.go#L46) looks "provision-time".
Since the trace handler is the very first to be setup in the stack, it's probably also the last to handle the response, right?
It should take all other handler processing times into account and so on so my guess is yes...

For most frameworks operation naming in line with OpenTelemetry's semantic conventions can not be achieved through mere request manipulation and is probably much easier to handle at framework level then with request info manipulation on caddy level, hence the suggestion, although I'm not sure it's very clean ;)

**Comment by davidfrickert** [comment]
Any news on the implementation of this feature? Sounds quite interesting.

**Comment by francislavoie** [comment]
The Caddy maintainers don't use tracing or metrics ourselves, so we have very little incentive to spend time working on it. So we're asking for the community to help maintain those parts.

**Comment by davidfrickert** [comment]
Understandable.
I have a working solution for this, I can submit a PR.
