### ISSUE TITLE
HTTP_PROXY env not working

### ISSUE THREAD

**Issue by 8BitJonny** [caddyserver/caddy#5178]
### 1a. Operating system and version
Using the docker `caddy:2-alpine` image
```
Linux 4d5a25798135 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 Linux
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
```

### 2a. What happens (briefly explain what is wrong)
For a whole week now I'm trying to setup caddy as reverse proxy to proxy requests over tailscale into my private home network.
Over time my minimal reproducable case has evolved into using tinyproxy except of the tailscale proxy from the [userspace networking mode](https://tailscale.com/kb/1112/userspace-networking/) and also currently I'm testing everything from within the docker container itself. Thats why currently the caddy file binds to `http://172.17.0.2` except for an external domain.

I have gotten multiple successful curl requests by specifying the proxy
```sh
// using the tailscale proxy
ALL_PROXY=localhost:3128 curl http://100.81.184.38:3000 //or www.google.com if you don't have a tailscale node
```

But no matter if I use `ALL_PROXY` `http_proxy` or `HTTP_PROXY` I always fail to use the proxy through caddy. Help!

### 2c. Log output

```
http.log.error	dial tcp 100.81.184.38:3000: connect: connection refused	request": {"remote_ip": "172.17.0.2", "remote_port": "38404", "proto": "HTTP/1.1", "method": "GET", "host": "172.17.0.2", "uri": "/api", "headers": {"User-Agent": ["curl/7.83.1"], "Accept": ["*/*"]}}, "duration": 0.041261001, "status": 502, "err_id": "wv1ugcp6m", "err_trace": "reverseproxy.statusError (reverseproxy.go:1272)"}
```

### 2e. Related issues
I know that this seems similar to #1433 and I know that this issue ended because of no minimal reproduction case. Thats why I already put some work in, to put everything into a Dockerfile and Repo so it should be reproducible across machines

### 2d. Related Links
For the tailscale case, [this doc](https://tailscale.com/kb/1107/heroku/) is helpful because I have to use tailscale in [userspace networking mode](https://tailscale.com/kb/1112/userspace-networking/) because of my deployment server

## 3. Tutorial (minimal steps to reproduce the bug)
Reproduction Repo: https://github.com/8BitJonny/caddy-proxy-minimal-repro/tree/main with Docker.

This reproduction repo is setup to show my struggle to use caddy with a proxy, with two different proxies. You can run the docker container and reproduce it with the [tailscale](https://tailscale.com/) proxy or with the most minimal proxy using [tinyproxy](https://github.com/tinyproxy/tinyproxy)

Use the repo and run 
```sh
docker build -t caddy_proxy:latest .
docker run -ti -p 43890:43890 --env TAILSCALE_AUTHKEY=TailScale-ApiKey --name caddy caddy_proxy
```
to start the docker container. You'll only need the `TAILSCALE_AUTHKEY` env if you want to reproduce it with tailscale. Currently its setup for reproduction with tinyproxy and then the env won't be used.

And in the second terminal the following fails
```sh
docker exec -it caddy /bin/sh
curl http://172.17.0.2/api //This errors with either proxy successfully forwarding the request
```

**Comment by mholt** [comment]
Thanks for opening an issue.

To make sure I understand, you are expecting Caddy to honor the `HTTP_PROXY` environment variable when using Caddy's `reverse_proxy`? i.e. when the reverse proxy dials the backend, it should be honoring the `HTTP_PROXY` value? Is this documented in our docs somewhere? :thinking:

**Comment by 8BitJonny** [comment]
Yes, that was my expectation of it. I'm not that experienced in networking but through the tailscale documentation:
> Many widely used networking packages support these proxies already, generally by setting the ALL_PROXY and HTTP_PROXY environment variables

I thought maybe caddie doesn't support it directly but indirectly by using a network library under the hood that does support and react to these env vars.

And then I saw https://github.com/caddyserver/caddy/issues/1433 where everybody was talking about it as if Caddy was honoring these env vars. This plus the [caddy v1 -> v2 migration guide](https://caddyserver.com/docs/v2-upgrade#proxy) mentioning that 
> The v2 equivalent [of proxy] is reverse_proxy

I then assumed that it was in fact a valid way to pass a proxy value to caddy because you yourself, said in https://github.com/caddyserver/caddy/issues/1433 that you couldn't reproduce the issue and hence that Caddy honors the value of HTTP_PROXY, despite the docs never mentioning it anywhere.

**Comment by 8BitJonny** [comment]
But I mean, that is also a valid answer in and of itself. If you say, this is not a feature of Caddy anymore, then I can quite trying to get it to work like this and try a different approach 😄

**Comment by mholt** [comment]
I'm a bit confused, what in the v1->v2 upgrade guide says that the proxy uses HTTP_PROXY env var? :monocle_face: 

Anyway, it's not a feature I ever used, so if it worked, it was by accident. I'm not saying it shouldn't work, but in general, with v2, we don't use env vars because they're not flexible/powerful enough for what v2 requires.

I suppose this issue is more of a feature request than a bug report, then?

Anyone is welcome to contribute to this!
