### ISSUE TITLE
No joy in trying to reduce logging

### ISSUE THREAD

**Issue by cekvenich2** [caddyserver/caddy#5184]
I tried every Caddyfile possibility, this is current:

:80 {
        respond  "hello world"

        log { 
                level ERROR
        }

}

It keeps showing info and I don't want info. I just want no info. I tried "warn" with and wihout quotes, nothing will stop info from coming. Hints please.

{"level":"warn","ts":1667456805.4279904,"msg":"unable to determine directory for user configuration; falling back to current directory","error":"neither $XDG_CONFIG_HOME nor $HOME are defined"}
{"level":"info","ts":1667456805.4521344,"msg":"using provided configuration","config_file":"/root/Caddyfile","config_adapter":""}
{"level":"warn","ts":1667456805.4529335,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/root/Caddyfile","line":1}
{"level":"info","ts":1667456805.453468,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1667456805.4535627,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
{"level":"info","ts":1667456805.4536834,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001947e0"}
{"level":"info","ts":1667456805.4537046,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
{"level":"info","ts":1667456805.4537578,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:./caddy"}
{"level":"info","ts":1667456805.4537797,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1667456805.453855,"msg":"autosaved config (load with --resume flag)","file":"caddy/autosave.json"}
{"level":"info","ts":1667456805.4538615,"msg":"serving initial configuration"}
{"level":"warn","ts":1667456805.453864,"msg":"$HOME environment variable is empty - please fix; some assets might be stored in ./caddy"}

**Comment by francislavoie** [comment]
The `log` directive (within a site block) only configures access logs (i.e. individual requests and responses).

For runtime logs (everything else) you need to use the `log` _global option_. See the docs.

But either way, you really shouldn't be ignoring these logs. They're important to know when things go wrong, to help you debug. They're not that noisy. And your current logs are warning you about legitimate issues, you should fix those problems!

**Comment by mholt** [comment]
Here's a link :) Hope that helps! https://caddyserver.com/docs/caddyfile/options#log
