### ISSUE TITLE
What data is captured in request logs?

### ISSUE THREAD

**Issue by cskwrd** [caddyserver/caddy#5191]
Is there a list of all the possible data that can be logged about a request? At the time of asking, the [docs](https://caddyserver.com/docs/logging) show an example, but there is no indication if this is all of the data that can be logged.

Specifically, I am interested to know if the body of a request (if any) can be logged.

**Comment by francislavoie** [comment]
Yep, that structure in the docs is accurate as to the fields we log in the current version of Caddy.

Of course things like `headers` and `resp_headers` are flexible because that's dynamic.
