### ISSUE TITLE
caddy cannot connect UNIX php socket

### ISSUE THREAD

**Issue by vncloudsco** [caddyserver/caddy#5198]
we cannot connect to UNIX php socket. but when we change to TCP the software works?
Anyone know the cause and solution please?

**Comment by mholt** [comment]
Thanks for opening an issue! We'll look into this.

It's not immediately clear to me what is going on, so I'll need your help to understand it better.

Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Instructions -- please heed otherwise we cannot help you (help us help you!)

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222) Please enable debug and access logs.
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by vncloudsco** [comment]
Dear: @mholt 

this for detail 

## 1. Environment

### 1a. Operating system and version

```
Ubuntu 20.04
Linux caddy 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=```


### 1c. Go version (if building Caddy from source; run `go version`)

```
go version go1.19.3 linux/amd64

```


## 2. Description

We have changed the correct configuration about user caddy in php config, however we are not able to connect to Unix socket. We changed php listen Unix socket to tcp everything works. 

I don't know how to debug, please check the problem for me

**Comment by vncloudsco** [comment]
Dear: @mholt 
more info i built caddy from xcaddy via command

``` go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest ```

**Comment by francislavoie** [comment]
> I don't know how to debug, please check the problem for me

We can't "check the problem" without seeing your config, your logs, etc. Please provide those, as asked by the template.

**Comment by vncloudsco** [comment]
@francislavoie thank 
This config my php 7.4 fpm 
https://gist.github.com/vncloudsco/2164274668080ab5c805a5ca19664659#file-php-conf

This Caddy File sample

```
xxxxx.com {
        root * /home/caddy/web
        php_fastcgi unix//run/php/php7.4-fpm.sock
}
```

caddy.service file

```
# caddy.service
#
# For using Caddy with a config file.
#
# Make sure the ExecStart and ExecReload commands are correct
# for your installation.
#
# See https://caddyserver.com/docs/install for instructions.
#
# WARNING: This service does not use the --resume flag, so if you
# use the API to make changes, they will be overwritten by the
# Caddyfile next time the service is restarted. If you intend to
# use Caddy's API to configure it, add the --resume flag to the
# `caddy run` command or use the caddy-api.service file instead.

[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

```
affter run i have get erros 502

```
C:\Users\Admin>curl https://xxxxxx.com -I
HTTP/1.1 502 Bad Gateway
Alt-Svc: h3=":443"; ma=2592000
Server: Caddy
Date: Fri, 11 Nov 2022 10:08:31 GMT
```

My log 

```
{"level":"error","ts":1668161373.5068152,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"xxxxxxxxxxxxxx","remote_port":"64793","proto":"HTTP/1.1","method":"HEAD","host":"xxxxxxxxxxxxxx","uri":"/","headers":{"User-Agent":["curl/7.83.1"],"Accept":["*/*"]},"tls":{"resumed":false,"version":771,"cipher_suite":49195,"proto":"http/1.1","server_name":"xxxxxxxxxxxxxx"}},"user_id":"","duration":0.000684448,"size":0,"status":502,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}
{"level":"error","ts":1668161374.496733,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"xxxxxxxxxxxxxx","remote_port":"64796","proto":"HTTP/1.1","method":"HEAD","host":"xxxxxxxxxxxxxx","uri":"/","headers":{"User-Agent":["curl/7.83.1"],"Accept":["*/*"]},"tls":{"resumed":false,"version":771,"cipher_suite":49195,"proto":"http/1.1","server_name":"xxxxxxxxxxxxxx"}},"user_id":"","duration":0.000430105,"size":0,"status":502,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}

```
I really don't know how to debug them as caddy provides so little for connection debugging, this is all I have.

**Comment by francislavoie** [comment]
You only posted _access logs_, not Caddy's _runtime logs_.

Looks like you're running as a systemd service. You can find your runtime logs with the command 
mentioned here: https://caddyserver.com/docs/running#using-the-service

Are you sure the `caddy` user has permissions to use the unix socket file? Are you sure the file exists?

**Comment by vncloudsco** [comment]
@francislavoie 
This Caddy's runtime logs

```
Nov 11 10:27:31 caddy systemd[1]: Starting Caddy...
Nov 11 10:27:31 caddy caddy[64672]: caddy.HomeDir=/home/caddy
Nov 11 10:27:31 caddy caddy[64672]: caddy.AppDataDir=/home/caddy/.local/share/caddy
Nov 11 10:27:31 caddy caddy[64672]: caddy.AppConfigDir=/home/caddy/.config/caddy
Nov 11 10:27:31 caddy caddy[64672]: caddy.ConfigAutosavePath=/home/caddy/.config/caddy/autosave.json
Nov 11 10:27:31 caddy caddy[64672]: caddy.Version=v2.6.2 h1:wKoFIxpmOJLGl3QXoo6PNbYvGW4xLEgo32GPBEjWL8o=
Nov 11 10:27:31 caddy caddy[64672]: runtime.GOOS=linux
Nov 11 10:27:31 caddy caddy[64672]: runtime.GOARCH=amd64
Nov 11 10:27:31 caddy caddy[64672]: runtime.Compiler=gc
Nov 11 10:27:31 caddy caddy[64672]: runtime.NumCPU=1
Nov 11 10:27:31 caddy caddy[64672]: runtime.GOMAXPROCS=1
Nov 11 10:27:31 caddy caddy[64672]: runtime.Version=go1.19.3
Nov 11 10:27:31 caddy caddy[64672]: os.Getwd=/
Nov 11 10:27:31 caddy caddy[64672]: LANG=C.UTF-8
Nov 11 10:27:31 caddy caddy[64672]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Nov 11 10:27:31 caddy caddy[64672]: NOTIFY_SOCKET=/run/systemd/notify
Nov 11 10:27:31 caddy caddy[64672]: HOME=/home/caddy
Nov 11 10:27:31 caddy caddy[64672]: LOGNAME=caddy
Nov 11 10:27:31 caddy caddy[64672]: USER=caddy
Nov 11 10:27:31 caddy caddy[64672]: INVOCATION_ID=d615a27b0ae446b0b9d2ffa402fbfd74
Nov 11 10:27:31 caddy caddy[64672]: JOURNAL_STREAM=9:386082
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1283073,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"warn","ts":1668162451.1305594,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1374383,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1398687,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1401951,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1483393,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1488676,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details."}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1492245,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1495106,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1497438,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["caddy.manhtuong.net"]}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1535687,"msg":"autosaved config (load with --resume flag)","file":"/home/caddy/.config/caddy/autosave.json"}
Nov 11 10:27:31 caddy systemd[1]: Started Caddy.
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1595266,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000596930"}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1598568,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/home/caddy/.local/share/caddy"}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1608334,"logger":"tls","msg":"finished cleaning storage units"}
Nov 11 10:27:31 caddy caddy[64672]: {"level":"info","ts":1668162451.1618025,"msg":"serving initial configuration"}
Nov 11 10:28:10 caddy caddy[64672]: {"level":"error","ts":1668162490.9052246,"logger":"http.log.error","msg":"dialing backend: dial unix /run/php/php7.4-fpm.sock: connect: no such file or directory","request":{"remote_ip":"27.72.100.238","remote_port":"65170","proto":"HTTP/1.1","method":"HEAD","host":"caddy.manhtuong.net","uri":"/","headers":{"User-Agent":["curl/7.83.1"],"Accept":["*/*"]},"tls":{"resumed":false,"version":771,"cipher_suite":49195,"proto":"http/1.1","server_name":"caddy.manhtuong.net"}},"duration":0.000623229,"status":502,"err_id":"ihiypc5hy","err_trace":"reverseproxy.statusError (reverseproxy.go:1272)"}
```
the truth is I can't find any connection error messages. we just noticed the problem when convert Unix to TCP listing everything works great

**Comment by francislavoie** [comment]
Well there you go:

> `dialing backend: dial unix /run/php/php7.4-fpm.sock: connect: no such file or directory`

You'll need to make sure it does exist.

**Comment by vncloudsco** [comment]
@francislavoie 

that file absolutely exists. I will try restarting my server

**Comment by vncloudsco** [comment]
Dear: @francislavoie 
everything worked fine after i restarted my server, thanks for your support. i don't know what is the problem but i was able to run my software, thank you!

**Comment by KaKi87** [comment]
Hi,

I had the same issue, the file existed as well, rebooting wouldn't help, turns out it was a permission issue because I was running rootless : `sudo usermod -a -G www-data $USER` solved it.

Thanks
