### ISSUE TITLE
Output error log to file

### ISSUE THREAD

**Issue by vncloudsco** [caddyserver/caddy#5203]
I have a question, i noticed that the log when running caddy is not saved to file by default, if you want to check the log then we have to use journalctl command to view the log, 

so is there any way to solve this problem?

![image](https://user-images.githubusercontent.com/41409442/201352979-727ba0e4-9e0e-42f3-b9c6-df810056b81e.png)

**Comment by francislavoie** [comment]
Configure the `log` global option https://caddyserver.com/docs/caddyfile/options#log

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
