### ISSUE TITLE
Added Caddyserver to TechEmpower benchmark

### ISSUE THREAD

**Issue by joanhey** [caddyserver/caddy#5204]
Please review/optimize this PR
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7689

Thank you

**Comment by joanhey** [comment]
I have started frankephp, but first we need to add Caddyserver.
Perhaps the next week, I'll push frankenphp.

**Comment by joanhey** [comment]
Now we will test: caddy, h2o, and nginx, all using php-fpm.

Later frankenphp vs workerman and ngx-php.

**Comment by joanhey** [comment]
Please don't see the benchmark as a competition.

A benchmark is a very good tool to optimize the apps.
Thank you

**Comment by mholt** [comment]
Thanks for keeping us informed :)

(Closing, as nothing actionable for us to do.)

**Comment by joanhey** [comment]
![image](https://user-images.githubusercontent.com/249085/203611732-a4d90d21-872e-454b-ad1e-7ef8a760aec1.png)

https://www.techempower.com/benchmarks/#section=test&runid=03363299-b1b5-42e6-8ca5-6e0665be82c2&test=fortune&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-yelngf-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-sf

Nginx Unit failed in the last 2 runs, but have +100K req/s

When finish the run, I'll send you the link to the logs.

**Comment by francislavoie** [comment]
That latency one makes no sense. There's clearly a problem there.

**Comment by joanhey** [comment]
php, php-h2o and php-caddy use the same php-fpm config file. And the same php files.

**Comment by joanhey** [comment]
Clearly is NOT a problem with the bench.
Like I said before, a benchmark is a very good tool to check anomalies.

**Comment by francislavoie** [comment]
Benchmarks are not immune to flaws.

32ms latency on something on the same machine makes no sense at all.

Caddy setups with PHP-FPM in Docker that I have running in production respond in sub-millisecond time.

**Comment by joanhey** [comment]
The code is also not immune.
The bench it's working with all platforms, but only fail with Caddy ??

There are 3 servers for the bench:
* 1 with the server and app
* 1 with the database 
* 1 that is the client with Wrk

**Comment by joanhey** [comment]
I don't have anything with Caddyserver.
For me will be perfect, to have another fast server option to use.

**Comment by joanhey** [comment]
What I don't like are Fake Benchs and Bench Marketing.
I added Caddyserver after watch a fake bench about Caddy and Nginx.

I make benchmarks for more than 15 years, and normally for help the apps.

**Comment by joanhey** [comment]
Latency is dependent.
The latency is relative to the concurrent users and req/s.
With 100 req/s with 100 users, is low.
With more req/s the latency go higher.

**Comment by mholt** [comment]
> I added Caddyserver after watch a fake bench about Caddy and Nginx.

Where was that? I'd like to see.

Also, what version of Caddy are you using?

How can we reproduce your results?

**Comment by henrystivens** [comment]
Hi @mholt 

The results are provide for Techempower benchmark, are open source: 

https://www.techempower.com/benchmarks/#section=data-r21 [Round 21]

You can download from Github and run the tests:

https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by henrystivens** [comment]
The docker file for Caddy and other servers you cand find in PHP folder:

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/php

**Comment by joanhey** [comment]
The Fake bench:
https://blog.tjll.net/reverse-proxy-hot-dog-eating-contest-caddy-vs-nginx/

I created issues, and PRs. 
https://github.com/tylerjl/benchmarking-proxies/issues
https://github.com/tylerjl/benchmarking-proxies/pulls

But only appear the appendix from Caddy.

Ok
I'll add to a neutral benchmark.

**Comment by mholt** [comment]
@joanhey How is that a "fake bench"?

**Comment by joanhey** [comment]
I helped and help, a lot of fw and servers to fix this anomalies.
If you don't measure it, you can't know how to improve it.

And here was the worse welcome that I received never.

**Comment by joanhey** [comment]
Read the issues!!!
https://github.com/tylerjl/benchmarking-proxies/issues

**Comment by joanhey** [comment]
What version I'm using?
![image](https://user-images.githubusercontent.com/249085/203664567-7caae7af-e065-4f60-a5e7-f756eef9adf3.png)

**Comment by mholt** [comment]
Ok, the rude and demanding tone in this thread, along with posting multiple repeated small comments, is not acceptable behavior, so I'm locking this.
