### ISSUE TITLE
How  about  adding  the  support of   CHINA  SM2  algorithm in TSL   ?

### ISSUE THREAD

**Issue by 82pj** [caddyserver/caddy#5207]
https://gmssl.trustauth.cn/
![image](https://user-images.githubusercontent.com/76645090/202610810-b5a678e9-280f-4559-ab8e-1c173d3b9ce9.png)

**Comment by mholt** [comment]
Most technically useful English doc I could find: https://datatracker.ietf.org/doc/html/draft-yang-tls-tls13-sm-suites-02

@82pj You'd have to petition the Go standard library to adopt this algorithm: https://github.com/golang/go -- as we won't deviate from the standard crypto/tls package for TLS connections. Thanks for the feature request though!
