### ISSUE TITLE
Placeholder in error code only works with 2 parameters

### ISSUE THREAD

**Issue by TobiX** [caddyserver/caddy#5214]
When trying to use a placeholder in the `error` directive, Caddy seems to be confused if it should be a error code or error message.

Consider this Caddyfile (trying to implement https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/):
```
http://:8080

@custom_err header_regexp X-Code ^\d+$
# works
error @custom_err "ERR" {header.X-Code}
# doesn't work
#error @custom_err {header.X-Code}
respond "okay"

handle_errors {
        respond "{err.status_code} | {err.status_text} | {err.message}"
}
```

Test with:
`curl -v -H X-Code:503 http://localhost:8080/`

When using the 1-argument form of `error`, this returns code 500 (Caddy's default), but when using the 2-argument form, this correctly returns 503.

**Comment by mholt** [comment]
I think that's working as expected, right? If the sole argument is a status code, then it's treated as a status code: https://caddyserver.com/docs/caddyfile/directives/error

**Comment by TobiX** [comment]
Yeah, but it doesn't. If the sole argument doesn't "look" like a status code, it's treated as a message. And the `caddy adapt` output confirms that:
```diff
--- wrong.json  2022-12-07 17:37:00.807515968 +0100
+++ right.json  2022-12-07 17:37:19.035497796 +0100
@@ -19,8 +19,9 @@
                                                  ],
                                                  "handle": [
                                                          {
-                                                                 "error": "{http.request.header.X-Code}",
-                                                                 "handler": "error"
+                                                                 "error": "ERR",
+                                                                 "handler": "error",
+                                                                 "status_code": "{http.request.header.X-Code}"
                                                          }
                                                  ]
                                          },
```

I would have expected something like
```json
"handle": [
        {
                "handler": "error",
                "status_code": "{http.request.header.X-Code}"
        }
]
```

**Comment by mholt** [comment]
Oh, I get what you mean now. Thanks for clarifying.

That's probably because the Caddyfile adapter doesn't know at adapt-time whether the placeholder will adapt to a code or an error message. It's impossible to know, really. I think if you're not hard-coding the ambiguous values (which are only there for convenience anyway) you should probably use the more explicit / more verbose syntax.
