### ISSUE TITLE
[Feature request] in- and export certs

### ISSUE THREAD

**Issue by IngwiePhoenix** [caddyserver/caddy#5221]
While going on the search for some answers [for my question](https://caddy.community/t/controlling-certificate-management-for-vps-vpn-link/17864) I found out that Caddy's certification storage is a little tricky to find - at least, I think so.

So it'd be useful to have either an API or CLI method of retriving or adding certificates (i.e.: when moving servers or wanting to back up the certs for other reasons).

The DEB package stores them like so:
```
/var/lib/caddy/.local/share/caddy
|-- acme
|   |-- acme-staging-v02.api.letsencrypt.org-directory
|   |   `-- users
|   |       `-- default
|   |           |-- default.json
|   |           `-- default.key
|   |-- acme-v02.api.letsencrypt.org-directory
|   |   |-- challenge_tokens
|   |   `-- users
|   |       `-- default
|   |           |-- default.json
|   |           `-- default.key
|   `-- acme.zerossl.com-v2-dv90
|       `-- users
|           `-- caddy@zerossl.com
|               |-- caddy.json
|               `-- caddy.key
|-- certificates
|   `-- acme-v02.api.letsencrypt.org-directory
|       |-- birb.it
|       |   |-- birb.it.crt
|       |   |-- birb.it.json
|       |   `-- birb.it.key
|       `-- ingwie.me
|           |-- ingwie.me.crt
|           |-- ingwie.me.json
|           `-- ingwie.me.key
|-- locks
`-- ocsp
    |-- birb.it-35d50d53
    |-- birb.it-5e4a8635
    |-- ingwie.me-62663424
    `-- ingwie.me-f736987a

17 directories, 16 files
```

Having a somewhat easier way to find, retrive and/or store certificates would be pretty helpful.

```
caddy get-cert-key $domain
caddy get-cert-crt $domain

caddy set-cert $key $crt
```

Thanks for the awesome program and have a great day!

Kind regards,
Ingwie

**Comment by mholt** [comment]
The storage backend and location depends on the config, which is either a file or provided by the API.

If we did expose a CLI for this, we'd have to add a `--config` flag like other commands use, and it wouldn't be able to accept configurations from API, unless there's a running Caddy instance on the local machine it could `GET` the current config from via its API.

We'd need to decide whether it's more helpful to get the config of a new instance (via `--config`) or a currently-running instance (via API).

**Comment by IngwiePhoenix** [comment]
Closing this in favour of #5252

Using the existing admin HTTP api is probably more plausible.

Thank you anyway! :)

**Comment by bwesterb** [comment]
This would still be a very useful feature. It's not just the web server that requires TLS certificates, but also various other services, such as for instance e-mail (SMTP, IMAP, POP3).

**Comment by francislavoie** [comment]
@bwesterb you can use [`caddy storage export`](https://caddyserver.com/docs/command-line#caddy-storage) which was added somewhat recently. But of course that dumps all of storage.

Our recommendation is still to use _events_ too hook into when Caddy issues and renews certificates, in which case you can use your own script to copy the cert/key to where you need it (most useful when using filesystem storage, otherwise you'll need your own storage driver for your script). See https://caddyserver.com/docs/caddyfile/options#event-options
