### ISSUE TITLE
Have the hability to disable ipv6 in caddy

### ISSUE THREAD

**Issue by yodatak** [caddyserver/caddy#5223]
Hi i love caddy and want to use in corporate place but we got RHEL with ipv6 disabled so caddy don't run with a simple configuration
Nov 28 19:08:54 caddy[658449]: Error: loading initial config: loading new config: starting caddy administration endpoint: listen tcp [::1]:2019: socket: address family not supported by protocol

```
myhostnamehere:443 {
        # Another common task is to set up a reverse proxy:
        reverse_proxy https://localhost:8443

        tls /etc/pki/caddy/server.crt /etc/pki/caddy/private/server.key
}
```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Use the `bind` directive: https://caddyserver.com/docs/caddyfile/directives/bind

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
