### ISSUE TITLE
Caddy removes manually generated certificate / key

### ISSUE THREAD

**Issue by oviserv** [caddyserver/caddy#5224]
Caddy (v2.6.2) is used as a reverse proxy on a Docker server with the following Caddyfile:
```
git.intra.lan {
	tls /data/caddy/certificates/mijnintra/gitea_cert.pem /data/caddy/certificates/mijnintra/gitea_key.pem
	reverse_proxy http://giteaserver:3000
}

monitor.intra.lan {
	tls internal
	reverse_proxy http://grafana:3000
}

unifi.intra.lan {
	tls internal
	reverse_proxy https://unifi-controller:8443 {
		transport http {
			tls_insecure_skip_verify
		}
	}
}
```
The reverse proxy is fully operational and all three websites can be reached. The certificate / key for the `git.intra.lan` site have been generated manually with openssl. After startup the manually generated certificate / key are removed, log:
```
proxy_1  | {"level":"info","ts":1669609450.4014223,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
proxy_1  | {"level":"info","ts":1669609450.4020367,"msg":"[INFO] Deleting certificates/mijnintra/gitea_cert.pem because key is empty"}
```
After a restart Caddy refuses to start complaining that the certificate / key can not be found. Expected behaviour: manually specified certificates / keys are left untouched. Workaround: set read only permissions on the key and certificate file.

**Comment by francislavoie** [comment]
You should not be putting your own certs/keys in Caddy's storage location. That's a directory that Caddy manages itself.

**Comment by oviserv** [comment]
You're right, when specifying the cert/key location outside Caddy's storage location everything works fine. One suggestion: shouldn't Caddy log an error (or refuse to start) if manually specifying a cert/key in Caddy's storage location using the tls directive? The current behaviour was puzzling for me as a new Caddy user.

**Comment by francislavoie** [comment]
Maybe, but this is the first time I've ever seen anyone try this. I don't think it's an often-enough occurrence to bother with spending time to set up a check for this.

**Comment by mholt** [comment]
@oviserv Additionally:

> gitea_cert.pem because key is empty

The file was empty, so... I'm not sure it really deleted anything useful anyway?
