### ISSUE TITLE
[question] As the Caddy integrate quic-go to serve http3, Is there any way to catch quic-go's log 

### ISSUE THREAD

**Issue by youguys** [caddyserver/caddy#5228]
Hi,
       I'am using caddy to serve http3,  
       but something is wrong with the quic-go library, 
       is there any way to log quic-go library's log to caddy' log ?

**Comment by francislavoie** [comment]
The logs are already captured by Caddy's logger. You might want to enable `debug` level logging to get more detailed logs, though.

**Comment by mholt** [comment]
If they aren't in the debug logs, there might be an env var to have quic-go emit it's qlogs.
