### ISSUE TITLE
admin unix domain socket err

### ISSUE THREAD

**Issue by New2Niu** [caddyserver/caddy#5234]
when i config admin with uds, i reload(cmd) caddy ,here will stop old admin server, then will delete unix socket file? I can't connect by unix socket.
![image](https://user-images.githubusercontent.com/19551155/205922078-7ea772d7-40f8-4112-8b4e-d7d9df86fdfd.png)

**Comment by New2Niu** [comment]
2.6.0
2.6.1 fix it

**Comment by mholt** [comment]
We did patch some things related to unix sockets in 2.6.1, wouldn't hurt to try upgrading (to 2.6.2 while you're at it).

**Comment by New2Niu** [comment]
thanks
