### ISSUE TITLE
Wordpress site cannot access thro domain, but it's ok when using IP

### ISSUE THREAD

**Issue by fakebear** [caddyserver/caddy#5239]
caddyfile:
:80 {
        root * /var/www/html
        php_fastcgi unix///run/php/php7.4-fpm.sock {
                root /var/www/html
        }
        file_server
        encode zstd gzip
}
import sites/*

When using domain name with remote device, the browser show "Connectioin_reset"
**BUT, when I tried to use curl on the server. The domain name works fine.**
When using domain access and capture caddy log. Seems like it retry and retry to fetch / content.
	• 2022/12/07 06:20:45.051 info    http.log.access.log0    handled request {"request": {"remote_ip": "192.102.205.36", "remote_port": "22353", "proto": "HTTP/1.1", "method": "GET", "host": "e2803.onmypc.net", "uri": "/", "headers": {"Accept-Encoding": ["gzip, deflate"], "Accept-Language": ["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7"], "Connection": ["keep-alive"], "Purpose": ["prefetch"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"]}}, "user_id": "", "duration": 0.260985307, "size": 4096, "status": 200, "resp_headers": {"Vary": ["Accept-Encoding"], "Server": ["Caddy"], "Link": ["<http://192.210.136.136/index.php?rest_route=/>; rel=\"https://api.w.org/\""], "Content-Type": ["text/html; charset=UTF-8"], "Content-Encoding": ["gzip"]}}
	• 2022/12/07 06:20:46.268 info    http.log.access.log0    handled request {"request": {"remote_ip": "192.102.205.36", "remote_port": "41090", "proto": "HTTP/1.1", "method": "GET", "host": "e2803.onmypc.net", "uri": "/", "headers": {"Connection": ["keep-alive"], "Cache-Control": ["max-age=0"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Accept-Encoding": ["gzip, deflate"], "Accept-Language": ["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7"], "Upgrade-Insecure-Requests": ["1"]}}, "user_id": "", "duration": 0.158363608, "size": 4096, "status": 200, "resp_headers": {"Server": ["Caddy"], "Link": ["<http://192.210.136.136/index.php?rest_route=/>; rel=\"https://api.w.org/\""], "Content-Type": ["text/html; charset=UTF-8"], "Content-Encoding": ["gzip"], "Vary": ["Accept-Encoding"]}}
	• 2022/12/07 06:20:46.451 info    http.log.access.log0    handled request {"request": {"remote_ip": "192.102.205.36", "remote_port": "49324", "proto": "HTTP/1.1", "method": "GET", "host": "e2803.onmypc.net", "uri": "/", "headers": {"Cache-Control": ["max-age=0"], "Upgrade-Insecure-Requests": ["1"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Accept-Language": ["en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7"], "Connection": ["keep-alive"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35"], "Accept-Encoding": ["gzip, deflate"]}}, "user_id": "", "duration": 0.152912001, "size": 10817, "status": 200, "resp_headers": {"Vary": ["Accept-Encoding"], "Server": ["Caddy"], "Link": ["<http://192.210.136.136/index.php?rest_route=/>; rel=\"https://api.w.org/\""], "Content-Type": ["text/html; charset=UTF-8"], "Content-Encoding": ["gzip"]}}

When I use tcpdump to capture the net package:
![image](https://user-images.githubusercontent.com/723762/206123266-117fffe0-2eaf-4286-84d1-ff97c4b84f7d.png)

capture tcpdump on server:
![image](https://user-images.githubusercontent.com/723762/206123339-008bf886-f8de-4958-abb4-3b0f3256e464.png)

**Comment by Plorenzo** [comment]
Hi Ryan, you are not setting the domain name in the Caddyfile so it's normal that you can't access you backend with it. 

In any case this is very likely an issue with you configuration not with Caddy itself so please, ask your question in the [forum](https://caddy.community) as Github is used to track code issues. 

Also for next time if you spend a bit of time formatting properly your post it's much more likely that someone help you.

**Comment by francislavoie** [comment]
Couldn't have said it better myself, thanks @Plorenzo
