### ISSUE TITLE
Metrics Endpoint bind on different address

### ISSUE THREAD

**Issue by WoozChucky** [caddyserver/caddy#5241]
Hey there,

Is it possible to set the bind address of the metrics endpoint ? From what I've read in the docs, it exposes on localhost:2019/metrics.

I'm using Prometheus inside a docker container in another host (different from Caddy) and would like to access the metrics endpoint (i.e. 192.168.x.x:2019/metrics).

Is this even possible via some config parameter that I'm missing?

Thanks in advance.

**Comment by Plorenzo** [comment]
You can create a site block to expose it to request from any origin, something like:
```
:2020 {
	metrics
}
```

Next time, please ask your usage questions on the [community forum](https://caddy.community), as GitHub issues are for bugs and feature requests.

**Comment by WoozChucky** [comment]
> You can create a site block to expose it to request from any origin, something like:
> 
> ```
> 
> :2020 {
> 
> 	metrics
> 
> }
> 
> ```
> 
> 
> 
> Next time, please ask your usage questions on the [community forum](https://caddy.community), as GitHub issues are for bugs and feature requests.

Thank you and sorry about posting it here on GH!
