### ISSUE TITLE
Upgrade quic-go to v0.31.0

### ISSUE THREAD

**Issue by bt90** [caddyserver/caddy#5242]
This release greatly reduces allocations and should improve HTTP/3 performance: https://github.com/lucas-clemente/quic-go/pull/3609#issuecomment-1301799852

**Comment by mholt** [comment]
Thanks, done in [fac35db](https://github.com/caddyserver/caddy/commit/fac35db9dcbf23af7ffad885bf072e3fbbaa7e71)
