### ISSUE TITLE
Caddy not found

### ISSUE THREAD

**Issue by doylio** [caddyserver/caddy#5243]
I'm trying to install Caddy on Raspbian 11 (Bullseye) and I'm getting the following error:
```
E: Unable to locate package caddy
```

I've followed the directions on the docs and added the caddy repository to apt. 

I've also noticed that if you go to https://dl.cloudsmith.io/public/caddy/stable/deb/debian (the URL from the install section of the docs) it's returning a 404 right now.  Is there an issue distributing the package?

**Comment by IndeedNotJames** [comment]
Thanks for trying out Caddy!

If you want to browse the cloudsmith repo in your web browser, use https://cloudsmith.io/~caddy/repos/stable/packages/ not https://dl.cloudsmith.io/public/caddy/stable/deb/debian.

Furthermore, please make sure you run `apt update` after adding the cloudsmith repo.
You might have overlooked that line in the docs, it's right before `sudo apt install caddy` :)

So no, there isn't an issue distributing the package.
I double-checked just in case :)

If any usage questions arise, use the official Caddy forum at https://caddy.community.
The GitHub Issue Tracker is only for bugs and feature requests.
