### ISSUE TITLE
file-server: https on nonstandard port at localhost

### ISSUE THREAD

**Issue by esdnm** [caddyserver/caddy#5246]
strating file-server at localhost on a  nonstandard port via `-listen` and `-domain localhost` to get https on the file-server as a non root user fails due not having permission to bind on port 80 for http.

**Comment by esdnm** [comment]
Is it possible to have https on nonstandard port without also having a http server running?

**Comment by esdnm** [comment]
If it's possible, is it possible to redirect http connection to that https port to https?

**Comment by francislavoie** [comment]
Yes it's possible, but you need a config file.

```
{
    http_port 8080
    https_port 8443

    servers :8443 {
        listener_wrappers {
            http_redirect
            tls
        }
    }
}

localhost:8443 {
    root * /path/to/webroot
    file_server
}
```

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
