### ISSUE TITLE
[FR]: Allow to reverse proxy http to an https endpoint

### ISSUE THREAD

**Issue by samip5** [caddyserver/caddy#5251]
I would like the ability to do something like:

```
reverse_proxy http://<snip> {
        to https://repo.<snip>
}
```

This is to circument the issue with older OS'es that will not be able establish an https connection due to missing CRLfile for example and I think it would be useful.

**Comment by francislavoie** [comment]
I don't understand. You'll need to elaborate what you mean, exactly.

**Comment by mholt** [comment]
This can already be done, but you'll need to take care of configuring the Host header and ServerName used in the TLS handshake in case they differ:

- The Host header is passed through without changes, by default.
- The SNI is derived from the Host header, by default.

But it sounds like you want a forward proxy instead of a reverse proxy.

**Comment by samip5** [comment]
> I don't understand. You'll need to elaborate what you mean, exactly.

Okay, so let me try to explain better. I want to be able to request content from the remote https site via Caddy over HTTP and have Caddy handle the HTTPS connection to the remote site as it's not accessible via HTTP due to a forced redirect. Does this make sense?

Remote host -> HTTP -> Caddy -> HTTPS -> Remote site

**Comment by francislavoie** [comment]
You can already do that. See the docs:

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#https

**Comment by francislavoie** [comment]
That's just the proxy handler. Caddy will accept requests on either HTTP or HTTPS, and can proxy over HTTP or HTTPS.

**Comment by samip5** [comment]
I feel like we are still talking about different things.

Caddy's parser will not accept a config that has http reverse proxy with an https backend.

**Comment by francislavoie** [comment]
That statement doesn't make sense. Either you make a connection to the upstream over HTTP, or over HTTPS. You tried to configure the proxy to do both, which is what that error was telling you.

If you want Caddy to accept HTTP requests, then you configure your site with `http://`. And to proxy over HTTPS, you configure your proxy upstream with `https://`.

```
http://example.com {
	reverse_proxy https://your-upstream.com {
		header_up Host {upstream_hostport}
	}
}
```

**Comment by mholt** [comment]
@samip5 No, your config is proxying to both `http://<snip>` and `https://repo.<snip>`. Schemes can't be mixed in the same proxy because doing so is inefficient.

**Comment by samip5** [comment]
Oooh, now I see what I did wrong. I had omitted these from the start of the Caddyfile:

```
:62771

log
```

It would probably help to not omit things, but okay so it does work like I want it to. :)

**Comment by francislavoie** [comment]
Use `header_up Host {upstream_hostport}` instead so you don't need to repeat your hostname.
