### ISSUE TITLE
Feature Request: Certificate syncing/sharing

### ISSUE THREAD

**Issue by IngwiePhoenix** [caddyserver/caddy#5252]
I am struggling quite a lot with a setup which is the root cause for this feature request.

Basically: I have a VPS that will (for certain domains) act as a frontend to proxy requests to my home server, which is connected via VPN. Since I have assigned the same domain as a static DNS resolve on that homeserver, it always resolves to the network internal IP - the idea is that when I am at home, I don't need to take the extra hop via the external server, since I am on the exact same network.

The problem is that making the certificates work has been an absolute chore and it is still very broken. Hence, this feature request.

## What it should do

There is already a mechanism to "ask" for a TLS cert on a specified input - at least to ask if it should be created or not. I would like to see a similiar method where two Caddy instances may talk to each other to share certificates.

For instance:
```
1. Device makes a HTTPS request to server A
2. Server A asks Server B if the certificate already exists: GET $caddy_admin/cert/$domain/exists
3. If it exists, Server B replies with 200 OK - otherwise if not.
4. Server A now knows that Server B has the certificate bundle and asks for the individual parts: GET $caddy_admin/cert/$domain/(json, pem, key)
5. Server A now has the same certificate files as Server B, stores it, and uses it to serve Device's request.
```

## What it could look like
In my scenario, i would have this on my router:
```caddyfile
{
  exchange_tls via https://192.168.222.10:2019 # Server IP via VPN
}
```

On my server, I would probably use this:
```
{
  exchange_tls from 192.168.222.0/24 # Allow devices in this network to request certs
}
```

## What it can be used for
Using a single server to manage certificates and leaving the others to just using them (`global auto_https disable_certs`) would reduce the potential amount of redundant requests sent to Let's Encrypt (or other ACME provider, although I don't know any) and would allow Caddy-behind-Caddy to function more flawlessly.

I know this FR might be nieche and use-case specific in this situation, but since it came to my mind, I thought I'd share!

Thanks for this awesome software and kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
I wish it did...

https://caddy.community/t/storage-file-system-doesnt-actually-change-the-storage-location/18112

**Comment by francislavoie** [comment]
I replied on the forum topic - I'm pretty sure it's just a misunderstanding. Caddy definitely does coordinate when storage is shared.

**Comment by mholt** [comment]
Yes, this functionality already exists. Definitely make sure your storage is configured properly so that they use the _same_ storage.

**Comment by mholt** [comment]
(Kind of weird that it says closed as "not planned" even though it was planned and implemented a long time ago... anyway...)

**Comment by sunebeck** [comment]
There could still be a use-case for certificate syncing between Caddy instances that use the local file storage. I often have 3-4 Caddy instances spread around the world using the same certificates, and running a vault/consul seems overkill and sometimes more intended for a local network. Distributed storage might create another point of failure — reading from a file system is pretty robust. Currently I just cron+rsync certs between instances, but I think there could be race conditions.

Understand if it's not deemed to be within the scope of already-great Caddy, but would be cool if a Caddy could ask another Caddy if it might have the certificate.

**Comment by francislavoie** [comment]
The trouble with that is risk of misuse. If such an API endpoint existed to get private key + cert from another instance, then if access to the API endpoint is leaked (bad networking config) then the private keys leak. I think it's easier for it to be safe if you just use one of the many storage plugins.

**Comment by mholt** [comment]
That, and Raft/Paxos are quite complex.
