### ISSUE TITLE
UDP socket doesn't use SO_REUSEPORT

### ISSUE THREAD

**Issue by antage** [caddyserver/caddy#5255]
caddy version: 2.6.2
Linux 5.10, running in docker with --network=host.

I'm trying to run two instance of caddy on the same IP address.
When I use 80 (http_port) port only it works fine.
When I use 443 (https_port) port I got the following error for second instance:

```
Error: loading initial config: loading new config: http app module: start: listen udp aaa.bbb.ccc.ddd:443: bind: address already in use
```

I tried to disable http/3:

```
servers :80 {
    protocols h1
}
servers :443 {
    protocols h1 h2
    listener_wrappers {
        tls
    }
    strict_sni_host
}
```

but it doesn't help and I got the same error.

**Comment by francislavoie** [comment]
We're not using `SO_REUSEPORT` so that you can run two instances of Caddy, we're doing it so Caddy can reload its config while maintaining the same listeners across reloads.

I'm not sure I understand your goal here. Why two instances of Caddy?

**Comment by antage** [comment]
The goal of two instance is zero downtime restart (when config updates requires it, crashing, etc).

You say Caddy isn't using `SO_REUSEPORT`, but what is it?
https://github.com/caddyserver/caddy/blob/e10ed7b00d30cc91662949671f0051cd16da9222/listen_unix.go#L110

**Comment by francislavoie** [comment]
> when config updates requires it

You never need to restart Caddy for a config update. You should be reloading Caddy, which is a zero-downtime config change.

https://caddyserver.com/docs/getting-started#reloading-config

Typically, the only time you need to restart Caddy if you swap out the binary (i.e. upgrade Caddy, or add a plugin).

> You say Caddy isn't using `SO_REUSEPORT`, but what is it?

No, what I said is that we're not using `SO_REUSEPORT` _for the purpose_ of allowing two instances to be run concurrently. That's not something we test for or actively support. So what you're doing is not something we can recommend right now.

**Comment by antage** [comment]
Thanks for the explanation.

**Comment by mholt** [comment]
Although, I think something is odd if you've disabled http3 and it's still trying to bind to udp in the first place. If I have a chance I'll try to reproduce that.

**Comment by mholt** [comment]
Well... can't reproduce it. With your global options, the only ports used are TCP:

```
$ sudo netstat -tulpn | grep caddy
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      166499/caddy
tcp6       0      0 :::443                  :::*                    LISTEN      166499/caddy
tcp6       0      0 :::80                   :::*                    LISTEN      166499/caddy
```

It's quite possible that your Caddyfile is not what you think it is (or isn't being loaded like you think).

**Comment by antage** [comment]
@mholt I checked the problem in a clean environment and I can't reproduce it too. In production, I am using two ip-addresses. I think `servers :443` doesn't cover both ip-addresses and I have to use `servers ...` for each ip-address separately.

**Comment by mholt** [comment]
That's interesting. Can you demonstrate that behavior with a minimal Caddyfile?

**Comment by antage** [comment]
@mholt 

Caddyfile:
```
{
        default_bind 192.168.88.7
        servers :443 {
                protocols h1 h2
        }
}

192.168.88.7:443 {
        respond "OK"
}
```

Start caddy: `caddy run --adapter caddyfile --config Caddyfile`.

Open ports:
```
# ss -ntupl | grep 443
udp   UNCONN 0      0              192.168.88.7:443       0.0.0.0:*    users:(("caddy",pid=118834,fd=8))        
tcp   LISTEN 0      4096           192.168.88.7:443       0.0.0.0:*    users:(("caddy",pid=118834,fd=7))        
```

Caddyfile2:
```
{
        default_bind 192.168.88.7
        servers 192.168.88.7:443 {
                protocols h1 h2
        }
}

192.168.88.7:443 {
        respond "OK"
}
```

Start and open ports:
```
# ss -ntupl | grep 443                                                                                          ─╯
tcp   LISTEN 0      4096           192.168.88.7:443       0.0.0.0:*    users:(("caddy",pid=118916,fd=8))
```

**Comment by mholt** [comment]
(This is still on my TODO list, will reopen until I can get around to it.)

**Comment by IndeedNotJames** [comment]
Not sure if this isn't just intended behavior :thinking:

The global option `servers` has the following signature[^1]:

[^1]: https://caddyserver.com/docs/caddyfile/options

```
servers [<listener_address>] { }
```

And using `default_bind` overwrites that `listener_address`.

So instead of
```
{
	default_bind 127.0.0.1
	servers :443 {
		protocols h1 h2
	}
}

127.0.0.1:443 {
	respond "OK"
}
```

you would have to use `servers 127.0.0.1:443` (just like you already commented yourself!)

```
{
	default_bind 127.0.0.1
	servers 127.0.0.1:443 {
		protocols h1 h2
	}
}

127.0.0.1:443 {
	respond "OK"
}
```

Outputs of `caddy adapt` of those first two Caddyfiles:
```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            "127.0.0.1:443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "127.0.0.1"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "body": "OK",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```

and

```json
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            "127.0.0.1:443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "127.0.0.1"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "body": "OK",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ],
          "protocols": [
            "h1",
            "h2"
          ]
        }
      }
    }
  }
```

Note `apps.http.servers.srv0.listen` and `apps.http.servers.srv0.protocols`.

---

@antage Would you like something like `servers *:443` to wildcard match servers listening on port `:443`?

**Comment by francislavoie** [comment]
Ah yeah, I agree this is working as intended. 

Also, you can just use an empty `servers` to have it apply to all servers in your config without specifying the bind address.

**Comment by antage** [comment]
It may be useful to clarify in the documentation that `:443` is the same as `0.0.0.0:443` and it isn't something like `*:443`.

**Comment by francislavoie** [comment]
There's already a section that explains that:

> If you are using the bind directive or the default_bind global option, the listener_address MUST match the address bind address combined with the port of the site block, otherwise the settings won't be applied.

https://caddyserver.com/docs/caddyfile/options#server-options
