### ISSUE TITLE
forward_auth fils to set cookies

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#5256]
I wanna pass a cookie to an external auth service. Caddy fails to copy a cookie from the input request header.
caddy v2.6.2 

```bash
  # Auth gateway
  forward_auth http://iam:4456 {
    header_up Set-Cookie {http.request.cookie.*}
    uri /decisions
  }
```
My request:
```bash
curl -v https://site.com --cookie "Foo=Bar" -k
> GET / HTTP/2
> Host: site.com
> user-agent: curl/7.74.0
> accept: */*
> cookie: Foo=Bar
```

Caddy log output:
```bash
{"level":"info","ts":1671188625.8001063,"logger":"http.log.access","msg":"handled request",
"request":{"remote_ip":"XXX","remote_port":"55706","proto":"HTTP/2.0","method":"GET","host":"XXX","uri":"/",

"headers":{"User-Agent":["curl/7.74.0"],"Accept":["*/*"],"Cookie":[]}, <------- Empty Cookie Arr here !

"tls":{"resumed":false,"version":772, 
"cipher_suite":4865,"proto":"h2","server_name":"XXX"}},
"user_id":"","duration":0.01807467,"size":0,"status":0,
"resp_headers":{"Alt-Svc":["h3=\":443\"; ma=2592000"],"Server":["Caddy"]}}

```

**Comment by francislavoie** [comment]
Sensitive headers such as `Cookie` are stripped from the logs. You can reveal them by using the `log_credentials` server global option: https://caddyserver.com/docs/caddyfile/options#log-credentials

`Set-Cookie` is a _response_ header, not a _request_ header. It doesn't make sense to do `header_up Set-Cookie`, because that sets a _request_ header just before sending it upstream.

The `forward_auth` directive will passes through all requests headers unmodified (except for hop-by-hop headers, `Host`, and some `X-Forwarded-*` headers, as per the docs here https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults). There should be no need to use `header_up` in this case.

Also, use the `debug` global option to see exactly the headers Caddy sends up to your auth endpoint, in your logs.

**Comment by mholt** [comment]
I'm guessing that has less to do with Caddy and more to do with HTTP/HTTPS cookie boundaries set between the client and the application.

**Comment by francislavoie** [comment]
Yeah - make sure the cookie has the right domain attached to it. Caddy can't fix it for you if the browser isn't sending the cookie in the first place.

Also FWIW that's the first I've heard of Oathkeeper. Looks like they support forward auth in a pretty standard way. Would be cool if they'd add Caddy integration instructions to their docs. But I don't use it, so it would be great if you could reach out to them if you're willing to. They might be able to give pointers on how it should be set up.

**Comment by tetra12** [comment]
@mholt I disagree with you. Here's my situation and 3 requests below to prove that.

Req 1 (login) - 303 and returns 2 Cookies - `csrf_token_xxxxx` and `ory_kratos_session_yyy`

Req 2 (iam:4456) - main request -  upstream forward auth endpoint 

Req 3(iam:4456/decisions) - (302! instead of 200)  sub request - this performs a real forward auth IF `ory_kratos_cookie_yyy` is present. This redirects back to login with 302 since `Cookie` is NOT passed.

As you see :eyes:  from `Req3` below, `Cookie` is NOT copied to the req. Thus the `forward_auth` returns `302` instead of `200` and throws redirect to login page. Login page finds a `Cookie` and throws back to the `redirect_to` page, which is `/art/home` and the loop continues :face_with_spiral_eyes: 

Req 1:
```bash
{"level":"info","ts":1671478898.7144938,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"5.101.21.29","remote_port":"24591","proto":
"HTTP/2.0","method":"GET","host":"id.site.pro","uri":"/api/self-service/login/browser?aal=&refresh=&return_to=https%3A%2F%2Fapp.site.pro%2Fart%2
Fhome","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
;q=0.9"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Ch-Ua":["\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\""],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-User"
:["?1"],"Referer":["https://id.site.pro/"],"Sec-Fetch-Dest":["document"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Site":["same-site"],"Sec-Fetch-Mode":["navi
gate"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":["csrf_token_9ccee4c166bc22cfa673ebf1a3533624f5aade7f46e90ed38c31
63d47de0ab59=QTu2qBAjG0kb4vGomhXY76bijL8mTogbYOoGTyjLSvw=; ory_kratos_session=MTY3MTQ3ODg5NnxaQWxCRWg0M2ZyakM5YjM4VmstQlBLR0dQRFZLX01YdHhtdEhCMU9VM1VXSVU3ZGhE
YmFZVlFwdVVPQnJlMDFVbWxadjRlSnluOEdwY2ozdERkYXdpN3ZkY2RsblF2emkxb0JTTGhuRWtFcEs0SXNPWEh1cW5HcWl2WHZPeFlObUdicVZJVTB5OE5fT2c1Wks0V0tLeE1NcmJCbTRtZWdjUTRST3drR1
o3cHU2S0Jfd2lRdGVCVmY5LUVQZEV1RFFTOHNaWDVMcG5HSkZNLUVxRzZjM1Q0RWlGVjc2aXI5YzZwMDVpUDhpNGduV08zeFNvRTZnakJ6TWJqc1JsUVBNWFludjNySWdwT0w1fBFXuCCaaXnWGlP3TrPlkN-wsaQ2KGqTkhtBnEUkpJRW"],"Cache-Control":["max-age=0"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"id.site.pro"}},"user_id":"","duration":0.023803697,"size":65,"status":303,"resp_headers":{"Alt-Svc":["h3=\":443\"; ma=2592000"],"Cache-Control":["private, no-cache, no-store, must-revalidate"],"Content-Type":["text/html; charset=utf-8"],"Location":["https://app.site.pro/art/home"],"Vary":["Cookie"],"Date":["Mon, 19 Dec 2022 19:41:38 GMT"],"Content-Length":["65"],"Server":["Caddy"]}}
```

Req 2 : `{"level":"debug","ts":1671478899.5676546,"logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"iam:4456","total_upstreams":1}` 

Req 3: 
```bash
{"level":"debug","ts":1671478899.5965483,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"iam:4456","duration":0.028798244,"request":{"remote_ip":"5.101.21.29","remote_port":"25213","proto":"HTTP/2.0","method":"GET","host":"app.site.pro","uri":"/decisions","headers":{"Sec-Fetch-Site":["same-site"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Not?A_Brand\";v=\"8\", \"Chromium\";v=\"108\""],"Accept-Language":["en-US,en;q=0.9"],"Upgrade-Insecure-Requests":["1"],"X-Forwarded-Proto
":["https"],"X-Forwarded-Uri":["/art/home"],"Referer":["https://id.site.pro/"],"X-Forwarded-Method":["GET"],"X-Forwarded-Host":["app.site.pro"],"Sec-Fetch-User":["?1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"],"X-Forwarded-For":["5.101.21.29"],"Accept-Encoding":["gzip, deflate, br"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"app.site.pro"}},"headers":{"Content-Length":["102"],"Content-Type":["text/html; charset=utf-8"],"Location":["https://id.site.pro/login?return_to=https://app.site.pro/art/home"],"Date":["Mon, 19 Dec 2022 19:41:39 GMT"]},"status":302
```

my current Caddyfile:
```bash
app.site.pro {
  forward_auth iam:4456 {
    header_up Cookie {http.request.cookie.*}
    uri /decisions
    copy_headers X-Id-Token Authorization
  }

  reverse_proxy ddev:9000 {
    header_up Host {upstream_hostport}
  }
}
```
WHich doesn't work as well :roll_eyes:

**Comment by tetra12** [comment]
@francislavoie Check [here](https://github.com/ory/oathkeeper/discussions/1043) :eyes:

**Comment by tetra12** [comment]
@mholt @francislavoie See the pictures below? That's how my service WORKS without Caddy. Notice the Cookie passed to `/home`. This is a `localhost` deployment.

![valid-req](https://user-images.githubusercontent.com/45828526/208511230-2bbb8af1-5843-45fc-8f06-745b59ac4556.png)

![valid-cookie](https://user-images.githubusercontent.com/45828526/208511247-b1a9aebf-6bf3-407f-95dc-777933d1bb2f.png)

**Comment by francislavoie** [comment]
Remove this: `header_up Cookie {http.request.cookie.*}`

As I've said elsewhere, Caddy copies all headers to the upstream automatically. That line might actually be breaking the Cookie value.

Also, make sure to enable the `log_credentials` server global option, because the cookie is hidden from access logs by default.

Please show all your logs, in the order they appear, with `debug` enabled.

**Comment by tetra12** [comment]
@francislavoie Updated as per your requirements. 
1. Add debug
2. Add log_credentials
3. [caddy.log](https://github.com/caddyserver/caddy/files/10262544/caddy.log)

**Comment by francislavoie** [comment]
The cookie is set on your `id.neurodyne.pro` domain, not on your `dev.art.neurodyne.pro` domain. I don't think browsers will use cookies on a site on a domain that is one level deeper, for security reasons.

This isn't an issue with Caddy, the browser is simply not sending the cookie, because it's a different domain.

**Comment by tetra12** [comment]
@francislavoie Thanks for your explanations. I moved both app and auth endpoint to the same domain and used path switching. That fixed my issue and things are working fine with caddy's `forward_auth` :smiley:
