### ISSUE TITLE
For HTTP transport, tls_client_subject uses wrong format

### ISSUE THREAD

**Issue by Steve973** [caddyserver/caddy#5260]
For the HTTP transport, the tls_client_subject will use the wrong format if there are multiple OU values.

Observed:
cn=User Anonymous,ou=abc+ou=def+ou=ghi,o=some org,c=XX

Expected:
cn=User Anonymous,ou=abc,ou=def,ou=ghi,o=some org,c=XX

This seems to suggest that multiple OU values are being treated as if they are all part of the same RDN, and I am wondering how/why this is being determined.

I also noted that the order is being changed from the DN value in the certificate.  Shouldn't this value be *exactly* what the certificate contains?

I did not test this with other repeated attributes, and I did not test this for tls_client_issuer.

**Comment by mholt** [comment]
That placeholder simply returns the `pkix.Name` value of the Subject field in the cert. [It looks like](https://github.com/golang/go/blob/master/src/crypto/x509/pkix/pkix.go#L249) its `String()` method appends all the names to an `RDNSequence` which uses `+` as separators. It appears to be all spec-compliant with RFC 2253 Distinguished Names syntax. I don't know much more than that, so if you're expecting commas or a certain order to the values, I think you might have to ask the Go project about it. Maybe the RFC defines a certain order, I dunno.

Sorry I can't be of more help, it's a little beyond my pay grade :sweat_smile: (Closing but feel free to continue discussion if needed)

**Comment by Steve973** [comment]
It doesn't return what's in the certificate.  I can clearly demonstrate
that the returned value is different than the cert subject.  If I pull out
the subject of a cert I created, it looks like this:

C = XX, ST = Confusion, L = Somewhere, OU = first, OU = a002, OU = third,
OU = b004, O = example, CN = chunkbox

When I print what is returned from Caddy, it looks like this:

CN=chunkbox,OU=first+OU=a002+OU=third+OU=b004,O=example,L=Somewhere,ST=Confusion,C=XX

In the cert, the RDNs with the "OU" property are all separate RDNs.  The
value that I get from caddy puts them as properties into the same RDN.
That makes the cert subject DN and the subject DN I get back from caddy not
equivalent.
I have filed an issue with Go for that PKIX module.

**Comment by Steve973** [comment]
By the way, this ticket comment shows how to get the raw subject dn, which
is probably the better alternative.  Maybe you could modify Caddy to do it
this way:

https://github.com/golang/go/issues/27401#issuecomment-644681075

**Comment by mholt** [comment]
Ah interesting, that issue is saying it's an obsolete RFC, but Go is bound to it since it's documented that it follows that RFC specifically.

Thanks for the link; does that code produce the results you need? If so we can perhaps make this actionable and re-open it.

**Comment by Steve973** [comment]
I am going to dangerously assume that it does, but I don't have a Go
environment to test it out, and I am great with Java, but my Go experience
is only slightly better than nonexistent.  I'd like to help, here, but I'm
not sure what I could do.  I'm open to suggestions, however.

**Comment by Steve973** [comment]
Is anyone going to fix this?  It has been open for over a year.  I have been using Traefik (because of this particular bug), so this is no longer very relevant to me.  If you are not going to fix this issue, then feel free to close this ticket.

**Comment by mholt** [comment]
I think what happened is Christmas was a few days after the last comments, and then we got busy with other things that were a higher priority.

If you're not interested in using Caddy anyway, I don't see a need to prioritize this anymore, unless there's demand that this change be made. We can also prioritize patches for [sponsors](https://caddyserver.com/sponsor).
