### ISSUE TITLE
Basic-auth DDoS risk | QUESTION

### ISSUE THREAD

**Issue by alexandrestein** [caddyserver/caddy#5265]
Hello,

I implemented basic-auth to one of my system.

Password needs to be hashed/derived which prevent compromised server to reveal the user's password. 
That's a very good practice. 

But because of the HTTP basic-auth mechanism the server has to do the derivation (password are transfert in clear text) which is putting loads on the server.
It's very easy to build small app to try random credentials just to consume/steal CPU cycles from the system and potentially DDoS. And because it's random, the cache can't help.

I would advise 2 options:
- allow no hashing/derivation.
This may looks a bad idea but that's cheap and if server is not compromised that should not have any risk.
- use a fast hashing with salt just to prevent rainbow table (b3sum for example)
This give similar protection as bcrypt but much cheaper to compute which make the DDoS risk much smaller. 
If would agree with it I can work on the implementation. 

I would appropriate your feedback, please let me know what you think.

**Comment by mholt** [comment]
In general, DDoS is best mitigated by rate limits, a big CDN, and other access controls. Regardless of basic auth, it's always a good idea to limit the number of attempts someone can make at logging in.

You can use https://github.com/mholt/caddy-ratelimit for that, or a service like Cloudflare, etc. I don't think there's anything we need to implement here (and the proposed solutions are insecure). Thanks for opening an issue!
