### ISSUE TITLE
Support for headers from the static file in `file_server`

### ISSUE THREAD

**Issue by lukasbestle** [caddyserver/caddy#5267]
Apache has the [module `mod_asis`](https://httpd.apache.org/docs/current/mod/mod_asis.html) that sends static files "as is", including headers. This allows to define custom status codes or arbitrary headers directly in the file, for example in static caching use cases.

This feature could be integrated into `file_server`:

```
file_server {
	with_headers
}
```

**Comment by francislavoie** [comment]
That seems like a pretty niche usecase. I think this would probably be a better fit with a plugin to do this. I'm not sure we want to maintain this kind of functionality.

**Comment by lukasbestle** [comment]
Thank you for your quick reply. :)
