### ISSUE TITLE
Update from 2.5.2 to 2.6.2 breaks caddyfile 

### ISSUE THREAD

**Issue by rubinghv** [caddyserver/caddy#5268]
After updating my [docker container](https://hub.docker.com/_/caddy) from 2.5.2 to 2.6.2 it breaks the caddyfile with the following error: 

```
Error during parsing: authenticate is not a registered directive
```
I'm guessing some major things changed in `2.6` but would be helpful to be pointed in the right direction as I don't want to spend hours with trial and error here and I couldn't find any info on this error.

Here's my (redacted and shortened) caddyfile:

```
{
    order authenticate before respond
    order authorize before basicauth

    security {
        authorization policy organizrpolicy {
            set auth url organizr.domain.com
            # location: /config/www/organizr/data/config/config.php
            # name: organizrHash
            crypto key verify {ORGANIZR_KEY}
            # name: uuid (same location)
            crypto key token name {TOKEN_NAME}
            set token sources cookie header query
	    validate bearer header

            acl rule {
                comment allow admins only
                match iss Organizr
                match role Admin
                allow stop log info
            }
            acl rule {
              comment default deny
              match iss any
              deny log warn
            }

        }
    }
}

*.domain.com {
    tls {
        dns cloudflare "{CLOUDFLARE_TOKEN}"
    }

    @valheim host valheim.domain.com
	handle @server {
        reverse_proxy valheim:2456
    }

    @tv host tv.domain.com
	handle @tv {
        authorize with organizrpolicy
        reverse_proxy sonarr:8989
    }


    # Fallback for anything that wasn't matched by another handle block
    handle {
        respond "Nothing here :)"
    }

}
```

I've set it up with cloudflare, and organizr login helps gate access to any other subdomains

Any help would be appreciated, since I don't want to run an outdated version of caddy :) . Thanks!

**Comment by francislavoie** [comment]
Are you sure you built an image with the plugins you want? You need to use the builder image variant with a Dockerfile to do that.

This seems like a problem with either the way you built Caddy, or with the plugins you're trying to use, not a problem with Caddy itself.
