### ISSUE TITLE
plugins modifying CLI commands

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#5283]
@mholt , I am building a binary using the following file: https://github.com/greenpau/caddy-security/blob/main/cmd/authp/main.go

When I run the binary, `$ bin/authp -h`, I get the name inside output as `caddy` and a standard list of commands.

```
Usage:
  caddy [command]

Examples:
  $ caddy run
  $ caddy run --config caddy.json
  $ caddy reload --config caddy.json
  $ caddy stop

Available Commands:
  adapt          Adapts a configuration to Caddy's native JSON
  add-package    Adds Caddy packages (EXPERIMENTAL)
  build-info     Prints information about this build
  completion     Generate completion script
  environ        Prints the environment
  file-server    Spins up a production-ready file server
  fmt            Formats a Caddyfile
  hash-password  Hashes a password and writes base64
```

Is there a way to replace `caddy` with `authp` in the help output?

Also, is there a way to remove some of the commands from the list of "Available Commands"?

What is the way to add a new command to the list? For example, I am working on adding Consul-based identity store to auth portal. I want to add a set of commands that would validate the connectivity to the identity store, validate the integrity of the identity store itself, etc.

**Comment by francislavoie** [comment]
Why are you changing the binary name?

We could probably yoink the filename used by the user and insert that in the help doc instead, but I'm not sure I understand the motivation of renaming the binary.

**Comment by greenpau** [comment]
> Why are you changing the binary name?

@francislavoie , creates a standalone utility for a particular purpose. Similar to CoreDNS where `Caddyfile` is being renamed to `Corefile` and binary is `coredns`.

**Comment by greenpau** [comment]
> We could probably yoink the filename used by the user and insert that in the help doc instead

@francislavoie , that would be nice 👍

**Comment by mholt** [comment]
Even if the help text is changed, the application name is hard-coded as caddy elsewhere throughout.

FWIW, I'm not sure that renaming the binary is doing anyone a favor: users won't realize they are actually running Caddy, and that would be quite frustrating for me, as a user, if I found out I was running something other than what I thought I was.

**Comment by francislavoie** [comment]
The CoreDNS example isn't quite relevant anymore, because they're running on top of a heavily stripped down fork of Caddy v1. See https://github.com/coredns/caddy.

I agree with Matt, I don't think renaming the binary is the right approach.

**Comment by greenpau** [comment]
Also, is there a way to remove some of the commands from the list of "Available Commands"?

What is the way to add a new command to the list? For example, I am working on adding Consul-based identity store to auth portal. I want to add a set of commands that would validate the connectivity to the identity store, validate the integrity of the identity store itself, etc.

**Comment by mholt** [comment]
Commands can be added easily, yeah. See here for an example: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/fileserver/command.go#L34

Removing commands, not so much -- not without modifying the source, anyway. It sounds like you might want to just write your own `main()` function instead of using Caddy.

Otherwise, we typically recommend the convention where plugins just run as part of Caddy. That's least confusing for users in our experience.

**Comment by greenpau** [comment]
Thank you @francislavoie , @mholt ! All set!
