### ISSUE TITLE
Removing necessary Hop-by-Hop headers for Authelia Basic Authorization

### ISSUE THREAD

**Issue by Whitetigerswt** [caddyserver/caddy#5285]
Hi,

I've been banging my head against a wall all day trying to get Authelia's ```Proxy-Authorization``` header to work with Caddy. There are some instructions here: https://www.authelia.com/integration/proxies/introduction/#user-identification

However, after scouring the Internet and trying many things, I think the issue may lie in the following lines of Caddy:

https://github.com/caddyserver/caddy/blob/fcdbc69fabd14c6d0b1fe5c5e07490bf27d7f8bd/modules/caddyhttp/reverseproxy/reverseproxy.go#L1345
https://github.com/caddyserver/caddy/blob/fcdbc69fabd14c6d0b1fe5c5e07490bf27d7f8bd/modules/caddyhttp/reverseproxy/reverseproxy.go#L657

This header is removed from backend requests before being sent to Authelia. Without this header, it is pointless to send the authentication request, since it will clearly fail. The logging for Authelia shows this header is never received. I understand this header may be deprecated or may need to be removed from requests for various security reasons, but can an option be added to disable this functionality? 

This works fine with Traefik.

**Comment by francislavoie** [comment]
FYI @james-d-elliott maybe something to note in the docs for Caddy.

I think you could do `header_up Proxy-Authorization {header.Proxy-Authorization}` which should re-set the value so that it does get sent upstream.

**Comment by Whitetigerswt** [comment]
@francislavoie Thanks for the quick response! I added that to my Caddyfile and it is working now!

Maybe the correct solution would be for Authelia to not use the header. I thought about this, but there may be other software besides Authelia relying on this header (or another hop-by-hop header), so I thought it more appropriate to ask here. I think my initial request of "adding an option to disable the hop-by-hop removal" is already here, just a little obscure with how to do it.

**Comment by james-d-elliott** [comment]
This has been in the works for some while and is our solution to this. Basically we're allowing users to define this behavior and  we're going to support authorization via the basic scheme out of the box on non-legacy endpoints. It's a critical section of code so we're just taking a bit of time to get it right: https://github.com/authelia/authelia/pull/4296
