### ISSUE TITLE
conditional module usage/loading technique

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#5292]
@mholt , I am in the process of creating a plugin ([go-authcrunch-creds-aws-secrets-manager](https://github.com/greenpau/go-authcrunch-creds-aws-secrets-manager)) for a plugin ([caddy-security](https://github.com/greenpau/caddy-security)).

I want to use a technique similar to yours, e.g.

```

import (
	// plug in caddy-security modules here
	_ "go-authcrunch-creds-aws-secrets-manager"
)
```

If a user does not compile caddy with `go-authcrunch-creds-aws-secrets-manager` and Caddyfile contains instructions specific to the `go-authcrunch-creds-aws-secrets-manager`, then Caddyfile should be invalid.

In `caddy-security`, I want to use "aws-secrets-manager" conditionally ... what is the Golang technique to do it?

**Comment by greenpau** [comment]
The reason I want conditional loading is I don't want to enlarge `caddy` binary ... people might need only Consul KV store and not AWS Parameter store.

**Comment by mohammed90** [comment]
You can probably achieve that by hiding it behind a Go build tag, then use XCADDY with the env var `XCADDY_GO_BUILD_FLAGS` set with whatever Go build flags you desire.

**Comment by francislavoie** [comment]
Why don't you make it a guest module that is loaded by module ID? https://caddyserver.com/docs/extending-caddy#host-modules That's the intended way to implement plugins. Set up an Go interface that the plugins of that type should implement, add a spot in your main module to use something of that type. Use a namespace like `caddy-security.whatever-the-interface-is-named.aws-secrets-manager`

**Comment by greenpau** [comment]
@francislavoie , how does it work with an “app”? In my case, “caddy-security” is an app. There are also two plugins “authenticate” and “authorize”.

**Comment by mholt** [comment]
@greenpau Can you be more specific with your question? The docs page Francis linked to should answer your questions. App modules are no different than other modules, except that their namespace is empty string.

To make modules conditionally installed, they simply have to be in separate Go packages. I think Go will only compile in code that is used.

**Comment by francislavoie** [comment]
The same exact way. Everything is a module. That's the point of Caddy's architecture. An app is just a module that implements the app interface and is at the top-level namespace.

**Comment by greenpau** [comment]
For completeness, I have the following repos:

1. [`go-authcrunch-creds-aws-secrets-manager`](https://pkg.go.dev/github.com/greenpau/go-authcrunch-creds-aws-secrets-manager#pkg-index) has no `caddy` code at all. It provides interface.
2. [`caddy-security-creds-aws-secrets-manager`](https://github.com/greenpau/caddy-security-creds-aws-secrets-manager#caddyfile-usage) is a host module (per @francislavoie) that uses `go-authcrunch-creds-aws-secrets-manager`
3. `caddy-security` need to be use interface from `caddy-security-creds-aws-secrets-manager`, which in turn uses `Client` interface from `go-authcrunch-creds-aws-secrets-manager`

**Comment by francislavoie** [comment]
What I was suggesting is that you set up a generalized interface in `caddy-security` itself. Then you just plug in a package that has a module that implements that interface.

That's how Caddy itself works. HTTP handler directives are modules that implement `ServeHTTP`. Apps are modules that implement the App interface (i.e. `Start`, `Stop`, etc). Proxy transports are modular, i.e. HTTP and Fastcgi. The list goes on.

Your project shouldn't be any different. I think you're overthinking this.

**Comment by greenpau** [comment]
> What I was suggesting is that you set up a generalized interface in caddy-security itself. Then you just plug in a package that has a module that implements that interface.

@francislavoie , if I set up the interface in `caddy-security` itself, then the loading of `go-authcrunch-creds-aws-secrets-manager` becomes automatic, b/c of imports, i.e. all users of `caddy-security` will receive the build containing `go-authcrunch-creds-aws-secrets-manager`, whether they want it or not. I want the loading of the import of `go-authcrunch-creds-aws-secrets-manager` to be optional.

**Comment by mholt** [comment]
In Caddy, [we have a package called `standard`](https://github.com/caddyserver/caddy/blob/master/modules/standard/imports.go) that imports all the standard modules. You'll see that some even import further `standard` packages (like `caddyhttp/standard` which imports all of the standard HTTP modules for Caddy -- handlers and matchers, etc).

This way, someone can import the `caddy/v2` package without importing all the modules in the repo. They only get all the modules if they specifically import the `standard` package.

**Comment by francislavoie** [comment]
> @francislavoie , if I set up the interface in caddy-security itself, then the loading of go-authcrunch-creds-aws-secrets-manager becomes automatic, b/c of imports

No. The point is that you make a generalized interface like `SecretsManager` which has nothing to do with a specific vendor, put that in `caddy-security` in your config somewhere, like this:

```
	SecretsManagerRaw json.RawMessage `json:"secrets_manager,omitempty" caddy:"namespace=security.secrets-manager inline_key=provider"`
```

And then in your JSON config it might look like `{ "provider": "aws", ... }` (fill in with whatever other config knobs your AWS module needs, like API keys etc). In the Caddyfile it would be the same idea, `secrets_manager aws { ... }`

**Comment by mholt** [comment]
Thanks for the support @francislavoie ! :100:

I think we resolved this offline in a call. I'll close this, but feel free to continue discussions if needed. The forum is a good place for questions, and the issues are great if there's something actionable we need to do. :+1:
