### ISSUE TITLE
Cloudflare DNS validation with alias-domain

### ISSUE THREAD

**Issue by DaDattl** [caddyserver/caddy#5298]
Hi There,
First let me thank you for your great work here. Caddyserver is a really great tool!
I am only missing one specific feature in this tool. I am trying to verfy a ssl-cert using the CLOUDFLARE-Plugin with an alias domain.
Therefor I added at the not-supportet-registrar a "_acme-challenge.domain-A.com" cname to a cloudflare-registered-domain domain-B.com to validate certs using the cloudflare-api
> _acme-challenge.domain-A.com  cname  domain-B.com

Then I export the cloudflare-api-key for domain-B.com to the caddy-env and write an entry for domain-A.com in the Caddyfile

> domain-A.com {
>        reverse_proxy http://10.0.0.10:8080 {
>        }
>   tls {
>      dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN----FROM-domain-B.com}
>   }
> }

This is used if your dns provider doesn`t support a dns-api-validation also for security measures to not store the main-dns-api key on a webserver.

In eff.org this is described as "throwawaydomain".
> http://t.ly/jG3q

acme.sh calls it DNS-alias-mode and is used with "--challenge-alias" 
> acme.sh --issue -d  domain-A.com --challenge-alias domain-B.com  --dns dns_cf

posh-acme handels this with "-DnsAlias" that way:
> New-PACertificate domain-A.com' -AcceptTOS -Contact admin@example.com -DnsPlugin Route53 -PluginArgs $r53Params -DnsAlias domain-B.com -Verbose

I think, that this can be implemented very easily but I am no coder so I might be very wrong on that opinion :)
Could someone take a look at this? I will help with anything I am able to help on resolving this.

   Andreas

**Comment by francislavoie** [comment]
I think you're looking for https://caddyserver.com/docs/caddyfile/directives/tls#dns_challenge_override_domain
