### ISSUE TITLE
Templates directive, status code, and error handler 

### ISSUE THREAD

**Issue by jrschumacher** [caddyserver/caddy#5299]
After digging into this it seems that the TemplateContext doesn't pass the error when using the `handle_error` directive. Before diving in and adding this functionality will it be add a error context and pass that into the template context (in a similar way the OriginalRequestContext is passed)?

Alternatively, the entire error object may not be needed if we just expose the StatusCode to TemplateContext. Will this be possible?

```
handle_error {
  rewrite * error.html
  templates
  file_server
}
```

**Comment by mholt** [comment]
Thanks for opening an issue! So to make sure I get this straight, you need to get the status code, or an error, in a `handle_error` block, in your template context?

**Comment by jrschumacher** [comment]
I was hoping to drive the custom error page via templates rather than having multiple error pages.

**Comment by jrschumacher** [comment]
I think it's worth a discussion if the entire error is needed. As I think more about it the status code is needed but not sure if the error is a good idea as it could be a shiny footgun.

**Comment by francislavoie** [comment]
Maybe I don't understand the issue, but can't you get the error details with the placeholder function in templates?

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/templates/templates.go#L78

The placeholders you can use are documented here https://caddyserver.com/docs/json/apps/http/servers/errors/#routes
