### ISSUE TITLE
Enhancement: Support Kernel TLS (kTLS)

### ISSUE THREAD

**Issue by Forza-tng** [caddyserver/caddy#5305]
Would it make sense for Caddy to support Kernel TLS? It enables offloading of TLS handling to the kernel, avoiding some copy of data to/from user space. It can also be used to offload TLS operations to capable network cards, further reducing CPU usage on a busy server.

https://www.kernel.org/doc/html/latest/networking/tls.html#kernel-tls

https://www.kernel.org/doc/html/latest/networking/tls-offload.html

To check if a network card has support for TLS offloading
```
# ethtool -k eth0 | grep tls
tls-hw-tx-offload: off [fixed]
tls-hw-rx-offload: off [fixed]
tls-hw-record: off [fixed]
```

If I am not mistaken, it could also allow the use of HW crypto devices such as the CCP on all AMD Ryzen/EPYC CPUs.

An example from a dual core Ryzen 3000G
```
# grep ccp /proc/crypto
driver       : rsa-ccp
driver       : hmac-sha512-ccp
driver       : sha512-ccp
driver       : hmac-sha384-ccp
driver       : sha384-ccp
driver       : hmac-sha256-ccp
driver       : sha256-ccp
driver       : hmac-sha224-ccp
driver       : sha224-ccp
driver       : hmac-sha1-ccp
driver       : sha1-ccp
driver       : cbc-des3-ccp
driver       : ecb-des3-ccp
driver       : gcm-aes-ccp
driver       : xts-aes-ccp
driver       : cmac-aes-ccp
driver       : rfc3686-ctr-aes-ccp
driver       : ctr-aes-ccp
driver       : ofb-aes-ccp
driver       : cfb-aes-ccp
driver       : cbc-aes-ccp
driver       : ecb-aes-ccp
```

**Comment by IndeedNotJames** [comment]
Related: #4731

**Comment by mohammed90** [comment]
Dependent on upstream: golang/go#44506

**Comment by mholt** [comment]
Very difficult and unsafe to do currently. Linked issues explain why 👍

**Comment by francislavoie** [comment]
I'll close this for now because there's nothing actionable for us at this time until upstream implements it. We can reopen when they do.
