### ISSUE TITLE
Issue #3443 is present on "default_bind" directive on the latest stable

### ISSUE THREAD

**Issue by nem64** [caddyserver/caddy#5309]
Issue https://github.com/caddyserver/caddy/issues/3443 is present with the exact same symptoms but with the `default_bind` directive as well and on the latest stable. I basically want to bind Caddy only to specific interfaces, however only one address is bound to port 80 and the rest are on 443.

Caught this while wanting to use Caddy outside of docker as I couldn't just map addresses to internal ports anymore. Should be able to reproduce with any config but with the global `default_bind` directive set.

**Comment by francislavoie** [comment]
Please try with a build from master. We have some unreleased changes, and I feel like I might remember us fixing that recently.

That said, please post a minimally reproducible example. We need to be precise to properly understand the issue. Show the error message you get (if any), the config used, possibly some other commands to show the problem.

**Comment by nem64** [comment]
```
{
  default_bind [::1] 127.0.0.1 [2605:6400:30:f1ca::1] 104.244.78.176
}

https://example.com {
  respond "Test TLS"
}
```
```
$ curl -6 localhost -v
*   Trying ::1:80...
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 308 Permanent Redirect
< Connection: close
< Location: https://localhost/
< Server: Caddy
< Date: Mon, 16 Jan 2023 12:23:50 GMT
< Content-Length: 0
< 
* Closing connection 0

$ curl -4 localhost -v
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying 127.0.0.1:80...
* connect to 127.0.0.1 port 80 failed: Connection refused
*   Trying 127.0.1.1:80...
* connect to 127.0.1.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 80: Connection refused
```

```
$ caddy version
223cbe3d0b50487117c785f0755bb80a9ee65010 (10 Jan 23 05:08 UTC)
```

```
Linux localhost 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```

```
Distributor ID:    Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:    11
Codename:    bullseye
```

netstat shows caddy listening for port 80 only on `[::1]:80` while ignoring the rest. No errors on Caddy

**Comment by francislavoie** [comment]
Hmm. Okay so this is kinda tricky.

The purpose of `default_bind` right now is just to act as a default for the `bind` directive for each site block in the config.

If you adapt your config to JSON, you'll see it looks like this:

```
{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						"104.244.78.176:443",
						"127.0.0.1:443",
						"[2605:6400:30:f1ca::1]:443",
						"[::1]:443"
					],
					"routes": [
						{
							"match": [
								{
									"host": [
										"example.com"
									]
								}
							],
							"handle": [
								{
									"handler": "subroute",
									"routes": [
										{
											"handle": [
												{
													"body": "Test TLS",
													"handler": "static_response"
												}
											]
										}
									]
								}
							],
							"terminal": true
						}
					]
				}
			}
		}
	}
}
```

This makes sense, you told Caddy to listen on port 443 on those interfaces.

But the issue is the Automatic HTTPS procedure (which happens when Caddy is running) will add a new server to listen on port 80, and at this point, the Caddyfile doesn't exist anymore, it only knows the JSON config.

I'm not exactly sure what the right thing to do is. Maybe Automatic HTTPS should always take the bind addresses from the server listening on `443`? But what if a server is listening on more than one port at the same time, with different bind addresses? Then it becomes ambiguous.

This is a little stupid, but as a workaround, I think you can do this, to make sure there's a server that exists in the adapted JSON config which listens on port 80 with the bind addresses you specified:

```
{
	default_bind [::1] 127.0.0.1 [2605:6400:30:f1ca::1] 104.244.78.176
}

https://example.com {
	respond "Test TLS"
}

http:// {
}
```

**Comment by IndeedNotJames** [comment]
Very good point.
Not sure what would be the right thing either.

Your workaround using
```
http:// {
}
```
works, just tested it.

---

> Maybe Automatic HTTPS should always take the bind addresses from the server listening on `443`? But what if a server is listening on more than one port at the same time, with different bind addresses? Then it becomes ambiguous.

Not conflicting with your statement, but just wanted to add, that it's possible to add unix sockets to `default_bind`.
As far as I can tell, those don't redirect nor can't be used for challenges anyway.
But just something that came to my mind :thinking:

**Comment by francislavoie** [comment]
I think we should probably just document this edgecase in the `default_bind` docs, mentioning that it won't apply to a server created for HTTP->HTTPS redirects, and that setting up an empty `http://` site block can fix it.

**Comment by nem64** [comment]
Confirmed working, and I agree it should be added to the documentation

**Comment by francislavoie** [comment]
Added a note in caddyserver/website@af9bd2e5c33e533269d33aa7e02634d23cd0d509, it'll be live the next time we push an update to the website.

**Comment by mholt** [comment]
The more I look at this the more I do think it's pretty unintuitive... and wasn't something I had considered before...

> I'm not exactly sure what the right thing to do is. Maybe Automatic HTTPS should always take the bind addresses from the server listening on 443? But what if a server is listening on more than one port at the same time, with different bind addresses? Then it becomes ambiguous.

Yeah, this is tricky.

This might suck, but maybe we should find all the addresses that use the HTTPS port and add the host portion of each of those addresses to the auto-redir server. i.e. a server configured to listen on `"104.244.78.176:443", "127.0.0.1:443", "[2605:6400:30:f1ca::1]:443", "[::1]:443"` would result in the auto-redir server listening on `"104.244.78.176:80", "127.0.0.1:80", "[2605:6400:30:f1ca::1]:80", "[::1]:80"`.

I don't love it, but maybe worth looking into if someone wants to? If it works, I think I like it more than the current behavior. (Though I'm glad a workaround exists...)
