### ISSUE TITLE
Storage export/import CLI commands

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#5313]
In Caddy, the [storage](https://caddyserver.com/docs/json/storage/) can be configured with any module implementing the [`certmagic.Storage`](https://pkg.go.dev/github.com/caddyserver/certmagic#Storage) interface.

Currently, we don't have any mechanism in place for exporting storage for backup, or an import mechanism to migrate from one storage module to another, or from one server/deployment to another.

What we should do is add two new commands to Caddy, i.e. `caddy storage export` and `caddy storage import` (exact command name and flags TBD) to make this possible.

Details:

- The commands should take the `--config` as input to load the storage module.
- The commands should _not_ try to contact the admin API. We shouldn't add an admin API for accessing the storage, because that adds additional risk to leaking private keys and such.
- It would call `List()` on the storage module to get all the keys, then `Load()` them all.
- Exporting would produce a `.tar.gz` or similar, exact archive format TBD.
- It should be possible to pipe the output to a file, or to `stdout` (useful with Docker for example to write it out to a file on the host machine).
- Importing should take the same archive, either from file or from `stdin`.
- In the case of running as a systemd service, the command would need to be run as the `caddy` user to correctly access the files owned by that user, if the `file_system` storage module is used.

**Comment by g41797** [comment]
Hi 
I'd like to participate or discuss

**Comment by francislavoie** [comment]
Sure, PRs are always welcome. Feel free to ask questions.

**Comment by g41797** [comment]
- Is it really gfi?
- Timing/deadline - I am in the middle of https://github.com/gavv/httpexpect/issues/246
- Target - as far as I understand it's linux but in yml files i saw mac/windows


Also i tried to use link above ( https://caddyserver.com/docs/json/storage/) in order to understand meaning of 'storage' but it looks broken

And off the topic question - usage of Server-Sent Events by caddy applications

**Comment by francislavoie** [comment]
I don't know what you mean by "gfi".

No specific deadline. But don't overextend yourself.

Yes, Caddy works on every platform.

Yeah unfortunately our JSON config docs are a bit broken right now, our database is being flaky as of a couple days ago. We're working on it. I think if you wait 2 minutes it might return the docs 🤷‍♂️ but the docs are generated from code, so you can just look at `storage.go` to get an idea. The actual interfaces and the filesystem storage implementation is in `certmagic`, a separate repo.

Yeah SSE is completely unrelated to this. But https://mercure.rocks/ is plugin for Caddy which provides an SSE server, or Caddy can be configured to `reverse_proxy` to an SSE upstream.

**Comment by g41797** [comment]
gfi - good first issue [sorry]

some days ago I asked what's PR (my first thought was "why we are talking about public relations?")

I asked about platforms because testing:
now i am using fedora38 
also i can use Windows 10

but definitely i am not macos man

how do you test in all environments? 
is it possible to get assistance?

**Comment by mholt** [comment]
> how do you test in all environments?

When you push to a PR on GitHub, CI will run the tests for you on all three major platforms.

> is it possible to get assistance?

To an extent, yes we can help answer questions or provide some guidance.

**Comment by g41797** [comment]
I will be able to start after completion of the current project in early June

**Comment by Phrynobatrachus** [comment]
Apologies @g41797 do you mind if I swipe this instead please? I have a draft branch I got around to mostly fixing up. 

https://github.com/caddyserver/caddy/compare/master...Phrynobatrachus:caddy:import-export

**Comment by g41797** [comment]
no problem
go ahead
happy fixing

**Comment by mholt** [comment]
@Phrynobatrachus Cool, that's a good start. I think I'd probably want to put that in the `caddycmd` package though (the `cmd` folder), as it's purely a CLI utility, and not really anything to do with Caddy core. (Assuming nothing new needs to be exported. If so let me know.)

You should make a pull request!

**Comment by binayuchai** [comment]
Can you assign me this work ?

**Comment by mholt** [comment]
I think this is done actually. I'm not sure why merging #5532 didn't close this.
