### ISSUE TITLE
[YAML] module name 'zstd': module value cannot be null

### ISSUE THREAD

**Issue by rahilarious** [caddyserver/caddy#5318]
Config in YAML:
```---
apps:
  http:
    servers:
      srv0:
        listen:
          - ":443"
        routes:
          - match:
              - host:
                  - sub.example.com
          - handle:
              - handler: encode                                                                                  
                encodings:
                  gzip:
                    level: 9
                  zstd:
                prefer:
                  - zstd
                  - gzip
              - handler: file_server
          - terminal: true
...
```

### Problem:
The YAML adapter translates this line `zstd:` into JSON `"zstd": null` resulting in the error.

### Fix:
Translating it into `"zstd": {}` fixes it.
So either config adapter needs to not output it `null` or caddy needs to load module even if its null.

### Workaround:
For now I'm replacing it with this line which is basically JSON in yaml which defeats the purpose of using YAML config
```encodings: { gzip: {level: 9}, zstd: {} }```

**Comment by mholt** [comment]
I don't really know about YAML -- maybe someone else does, but it wouldn't surprise me if this is expected to be how YAML works.

Please open an issue at https://github.com/abiosoft/caddy-yaml instead.

**Comment by rahilarious** [comment]
I thought about opening issue there but since every YAML to JSON converter does it `null`, I filed bug her. Is it possible to load module it even if it is `null`?

**Comment by mholt** [comment]
No, if a module is null there is nothing to load.

**Comment by rahilarious** [comment]
Understandable. Thanks much for such an amazing project. Cant wait to put it in prod

**Comment by francislavoie** [comment]
I think it should be an empty object, not null. Not sure how to do an empty object in yaml though.

FYI, no browsers support zstd anyways, so only specialized HTTP clients might ever use zstd. You can probably just remove that without any worries, if you can't figure it out.

Also, be careful with the gzip level you pick. Higher levels have higher processing cost for marginally more compression performance (file size). Caddy's default is usually a good balance. If you change the level, make sure to benchmark it to make sure it doesn't harm performance (CPU load) and latency.
