### ISSUE TITLE
i want to use caddy inside my custome ssl

### ISSUE THREAD

**Issue by vahidalvandi** [caddyserver/caddy#5321]
I bought  new ssl   (Wildcard DV SSL - Wildcard) and in want to setup it in caady . please show me a sample

**Comment by vahidalvandi** [comment]
thank you but this forum not open for me !! have problem in ISP . Thank you for helping me here

**Comment by mholt** [comment]
@vahidalvandi Can you explain what you mean by "problem in ISP"? Are you not able to access the forum? In what region are you located?

You can use your wildcard in Caddy easily enough:

```
*.example.com

tls cert.pem key.pem
...
```

but Caddy can also generate a free wildcard certificate for you... and keep it renewed.

**Comment by vahidalvandi** [comment]
i live in iran

**Comment by mholt** [comment]
Ok, I'll see what we can do to make it accessible there.
