### ISSUE TITLE
Local certificates only lasts for a couple of days?

### ISSUE THREAD

**Issue by wouterverduin** [caddyserver/caddy#5324]
Hey guys,

Been using Caddy in docker for quite sometime now as reverse proxy for my external services. However lately been interested in also enabling local https for my not externally exposed services.

However; when i install the certificate in my certifcate stores in windows and/or android it trusts it for a couple of days but within a week its saying its insecure again on both devices. Am i missing something in my setup or is this certificate automatically reissued really fast in caddy?

Snippet from my caddyfile:

`nr.thuis {
 reverse_proxy 192.168.1.161:1880
 tls internal
}`

I am running caddy in docker (image: caddy) 

Would really appreciate any help!

**Comment by mholt** [comment]
Don't install the leaf or intermediate certificate into trust stores... The root lasts for 10 years. Install the root cert. 👍
