### ISSUE TITLE
Please keep the original ip_hash algorithm

### ISSUE THREAD

**Issue by since1986** [caddyserver/caddy#5340]
By reading the git history, I found that caddy has changed the hashing algorithm `func hostByHashing(pool []*Upstream, s string) *Upstream)` which brings some troubles to the joint use of caddy and caddy-l4, please refer to [this issue](https://github.com/mholt/caddy-l4/issues/94) for details. Is it possible to keep the old and new hash algorithms at the same time, instead of replacing the old with the new?

**Comment by francislavoie** [comment]
Why do you think the original is still needed? I don't understand. Shouldn't we just update caddy-l4 to match the new one?

**Comment by mholt** [comment]
The old algorithm was [flawed](https://github.com/caddyserver/caddy/pull/4724) (see [this also](https://github.com/caddyserver/caddy/pull/5229)); the new one is much better. I don't see any compelling reason to keep the old one.
