### ISSUE TITLE
Support ACME-CAA (RFC 8657)

### ISSUE THREAD

**Issue by rugk** [caddyserver/caddy#5343]
> Today, Let's Encrypt [announced](https://community.letsencrypt.org/t/enabling-acme-caa-account-and-method-binding/189588) that they are enabling an extension to DNS CAA records known as ACME-CAA ([RFC 8657](https://www.rfc-editor.org/rfc/rfc8657)). 

https://www.devever.net/~hl/acme-caa-live

The article goes into more detail there.

Basically you can specify `validationmethods` and an `accounturi` to limit the CA to issue only 
Since both are kinda managed by caddy if you use auto HTTPS and e.g. dynamic DNS management.

**Comment by mholt** [comment]
Yeah, I saw that -- very neat! Thanks for posting it here.

I don't think there's anything for Caddy to do though, as this spec is more relevant to ACME CAs more than ACME clients. As far as I can tell, the client doesn't need to do anything to "support" ACME-CAA; that's the server's job.

**Comment by rugk** [comment]
Well it needs to add the specific DNS record to limit the CA to only emit certs for that account or by that reason.
