### ISSUE TITLE
Support AEGIS in TLS 1.3

### ISSUE THREAD

**Issue by rugk** [caddyserver/caddy#5345]
> Two AEGIS algorithms have been added to the [IANA registry](https://www.iana.org/assignments/aead-parameters/aead-parameters.xhtml#:~:text=32-,AEAD_AEGIS128L,-%5Bdraft%2Dirtf) and will be supported in TLS 1.3. [AEGIS](https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/00/) is a new authenticated encryption algorithm that provides better performance and better practical security.

from the [Bulletproof TLS Newsletter](https://www.feistyduck.com/bulletproof-tls-newsletter/) 2022-12-29

---

So given caddy has a history of adapting new TLS changes, maybe that should be a thing to adopt. (`AEAD_AEGIS128L` and `AEAD_AEGIS256` as ciphers)

**Comment by mholt** [comment]
Thanks for the request!

We don't implement ciphers in this project, as we do not have the expertise to do so properly and with good performance. Ciphers will need to be implemented by the Go standard library. I'd recommend requesting this feature upstream: https://github.com/golang/go/issues/new/choose

**Comment by rugk** [comment]
Okay thanks, opened upstream issue at https://github.com/golang/go/issues/58724
