### ISSUE TITLE
caddy validate --envfile

### ISSUE THREAD

**Issue by joeworkman** [caddyserver/caddy#5346]
Is there a way to use caddy validate CLI and pass it --envfile? I get this error whenever I try to run it…

```
Error: loading tls app module: provision tls: provisioning automation policy 0: loading TLS automation management module: position 0: loading module 'acme': provision tls.issuance.acme: expanding email address '{env.EMAIL}': evaluated placeholder {env.EMAIL} is empty
```

**Comment by francislavoie** [comment]
There's no `--envfile` for the `validate` command currently, but it could certainly be added.

**Comment by amis-shokoohi** [comment]
I suppose we should check for `--envfile` flag in [`cmdValidateConfig`](https://github.com/caddyserver/caddy/blob/master/cmd/commandfuncs.go#L506), and if it exists then load the envs from file. Right?
```go
runCmdLoadEnvfileFlag := fl.String("envfile")

if runCmdLoadEnvfileFlag != "" {
	if err := loadEnvFromFile(runCmdLoadEnvfileFlag); err != nil {
		return caddy.ExitCodeFailedStartup,
			fmt.Errorf("loading additional environment variables: %v", err)
	}
}
```

I'd like to work on this. Would you please assign it to me?

**Comment by francislavoie** [comment]
Yep, that's the idea.

No need to assign the issue, feel free to open a PR!
