### ISSUE TITLE
caddy fmt --overwrite exit status 1

### ISSUE THREAD

**Issue by amis-shokoohi** [caddyserver/caddy#5349]
Why does `caddy fmt --overwrite` exit with status 1 after overwriting the config file?
```
Error: ../../Caddyfile:4: Caddyfile input is not formatted
exit status 1
```
Shouldn't it successfully exit [here](https://github.com/caddyserver/caddy/blob/master/cmd/commandfuncs.go#L560)?
```go
if fl.Bool("overwrite") {
	if err := os.WriteFile(formatCmdConfigFile, output, 0600); err != nil {
		return caddy.ExitCodeFailedStartup, fmt.Errorf("overwriting formatted file: %v", err)
	}
	return caddy.ExitCodeSuccess, nil
}
```

**Comment by francislavoie** [comment]
Yeah, you're right. That was a recent change from https://github.com/caddyserver/caddy/pull/5297 but the intent was to only change the exit code for the non-overwrite case, I think.

PR is welcome to fix it! Thanks for pointing that out.
