### ISSUE TITLE
Downtime on storage failure

### ISSUE THREAD

**Issue by notramo** [caddyserver/caddy#5352]
Caddy doesn't serve requests if it can't save new certificate to data dir.
In these cases, it should store the cert in memory. This means retrieving a new certificate each time the server is restarted, but still better than downtime.
This should be enabled with a command line switch.

**Comment by francislavoie** [comment]
I don't think I agree with that.

If the storage module is prone to downtime, then it's up to the storage module to implement resilience.

But since it's a requirement of the storage to have atomic locking to ensure operations aren't duplicated across instances, any downtime is a critical problem.

**Comment by mholt** [comment]
Also, frequently obtaining the same certificate will quickly run you into CA rate limits.

> Caddy doesn't serve requests if it can't save new certificate to data dir.

This isn't technically accurate. Caddy continues to serve sites even if it can't get or doesn't have a valid certificate for a site. It just can't complete TLS handshakes that require a specific certificate.

> This should be enabled with a command line switch.

We don't use command line for configuration. This makes configurations more portable and self-contained.
