### ISSUE TITLE
Dependency version inconsistency

### ISSUE THREAD

**Issue by Ben131-Go** [caddyserver/caddy#5355]
It is just a reminder of dependency version inconsistency introduced by replace directive used in `github.com/smallstep/certificates`.
## Dependency line:
github.com/caddyserver/caddy --> [github.com/smallstep/certificates](https://github.com/caddyserver/caddy/blob/master/go.mod#L20) --> [go.mozilla.org/pkcs7](https://github.com/caddyserver/caddy/blob/master/go.mod#L119) <br>
github.com/smallstep/certificates v0.23.0 --> github.com/smallstep/pkcs7 e1aab68<br>
<https://github.com/smallstep/certificates/blob/v0.23.0/go.mod#L160>

## Background
Repo `github.com/smallstep/certificates` at version `v0.23.0` uses replace directive to pin dependency `github.com/smallstep/pkcs7` to version `e1aab68`.<br>
According to [Go Modules wikis](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), `replace` directives in modules other than the `main module` are ignored when building the main module.
It means such replace usage in dependency's go.mod cannot be inherited when building main module. And it turns out that `caddyserver/caddy` indirectly relies on `go.mozilla.org/pkcs7@33d0574`, which is different from the pinned version `smallstep/certificates` needed.<br>
><https://github.com/caddyserver/caddy/blob/master/go.mod>(Line 119)
```Go
go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352 // indirect
```

><https://github.com/smallstep/certificates/blob/v0.23.0/go.mod>(line 44&160)
```Go
go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352
...
// use github.com/smallstep/pkcs7 fork with patches applied
replace go.mozilla.org/pkcs7 => github.com/smallstep/pkcs7 v0.0.0-20221024180420-e1aab68dda05
```
It seems that `github.com/smallstep/certificates` replaces `go.mozilla.org/pkcs7` for some patches applied in `github.com/smallstep/pkcs7`.
### 1. Bump the version of dependency `github.com/smallstep/certificates`
If it doesn't cause issues at the moment, you can wait `github.com/smallstep/certificates` to eliminate the use of the replace directive and then update it.

### 2. Add the same replace rule to your go.mod
```Go
replace go.mozilla.org/pkcs7 => github.com/smallstep/pkcs7 v0.0.0-20221024180420-e1aab68dda05
```
Tips: Introduce replace directive may break go install and it can not be inherited by downstream projects. So, this solution is not recommended.

**Comment by mohammed90** [comment]
Can you clarify what issue is this causing and how does adding the `replace` solve it? Is there a broken behavior?

As far as the suggestion goes, having a `replace` isn't an acceptable solution. It's probably better to take this upstream. That said, I don't see how github.com/smallstep/certificates is using the mozilla lib directly, so perhaps it's an indirect dependency.

**Comment by hslatman** [comment]
Here's why there's a dependency:

```console
$ go mod why go.mozilla.org/pkcs7
# go.mozilla.org/pkcs7
github.com/caddyserver/caddy/v2/modules/caddypki
github.com/smallstep/certificates/authority
github.com/smallstep/certificates/scep
go.mozilla.org/pkcs7
```

But there's no SCEP functionality exposed in Caddy ([not yet](https://github.com/caddyserver/caddy/issues/4020), at least), so it's unlikely there's any broken behavior.

**Comment by Ben131-Go** [comment]
Thanks for such quick reply! I just want to give a reminder of potential dependency inconsistency and it doesn't seem to have much impact at the moment. Sorry to bother!

**Comment by mohammed90** [comment]
Thank you, @hslatman, for the confirmation and the details. We'll close the issue based on the given reasoning.

@Ben131-Go, there's no inconsistency. The module dependency tree indeed depends on the Mozilla lib because the Go modules system does not apply the `replace` outside of the main module.
