### ISSUE TITLE
quic-go breaks caddy on go 1.20

### ISSUE THREAD

**Issue by assistcontrol** [caddyserver/caddy#5356]
The quic-go dependency is unfortunate, as it breaks caddy every time a new go version is released.

This issue has three requests:

1. Can you please bump quic-go to `v0.32.0`?
2. Can you add an instructional line to `xcaddy/README.md` showing the proper `xcaddy --with` line for replacing quic-go? Given that this needs to be done every single time a new go version comes out, it'd be handy to have it in xcaddy's README. However, I can't figure out what that incantation is, as I've tried every combination I can think of:

```
xcaddy ... --with github.com/lucas-clemente/quic-go@v0.29.2=github.com/lucas-clemente/quic-go@v0.32.0
[...]
go: github.com/lucas-clemente/quic-go@v0.29.2 (replaced by github.com/lucas-clemente/quic-go@v0.32.0): parsing go.mod:
        module declares its path as: github.com/quic-go/quic-go
                but was required as: github.com/lucas-clemente/quic-go
2023/02/03 16:52:06 [FATAL] exit status 1

xcaddy ... --with github.com/lucas-clemente/quic-go@v0.29.2=github.com/quic-go/quic-go@v0.32.0
go: github.com/quic-go/quic-go@v0.32.0 used for two different module paths (github.com/lucas-clemente/quic-go and github.com/quic-go/quic-go)
2023/02/03 16:53:03 [FATAL] exit status 1

xcaddy ... --with github.com/quic-go/quic-go@v0.29.2=github.com/quic-go/quic-go@v0.32.0
# github.com/lucas-clemente/quic-go/internal/qtls
/root/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.2/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-
Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration

xcaddy ... --with github.com/quic-go/quic-go@v0.29.2=github.com/lucas-clemente/quic-go@v0.32.0
# github.com/lucas-clemente/quic-go/internal/qtls
/root/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.2/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-
Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

3. Perhaps caddy should start using `github.com/quic-go/quic-go` instead of `github.com/lucas-clemente/quic-go`?

**Comment by francislavoie** [comment]
We're working on it. https://github.com/caddyserver/caddy/pull/5353

**Comment by francislavoie** [comment]
To clarify, you shouldn't try to build with the latest version of Go until we've validated it and merged a patch to support it.

As you've noticed, because of quic-go, we need to specifically upgrade that dependency to support the latest Go. We're dependent on them making a release. Sometimes they run into snags, sometimes we run into snags. Tis the reality of having dependencies.

**Comment by hairyhenderson** [comment]
> We're dependent on them making a release.

https://github.com/quic-go/quic-go/releases/tag/v0.32.0 😉

**Comment by francislavoie** [comment]
Yes @hairyhenderson, see https://github.com/caddyserver/caddy/pull/5353. We've bumped to that version and we're working on merging it.
