### ISSUE TITLE
Allow multiline strings syntax

### ISSUE THREAD

**Issue by undergroundwires** [caddyserver/caddy#5357]
## The problem

What I love with Caddy is how simple the syntax and getting everything done is. I migrated from nginx and Apache and never looked back. However, the lack of syntax for handling multilines ends up in ugly looking and harder to main Caddyfiles.

This was discussed on a few places but I did not see feature requests. We need this to be able to [respond with multiline strings](https://caddy.community/t/respond-with-multi-line-body/12730) and multiline headers (#2302).

The current efforts look like hack, not really self-documenting and does not always work as expected. The syntax is not intuitive.

Examples:

```caddyfile
	respond "/robots.txt" 200 {
		body "User-agent: *
Disallow: /" # 
		close
	}
```

Example above requires an indentation that breaks the natural flow of the code.

```caddyfile
Content-Security-Policy "default-src 'self'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; form-action 'self'; object-src 'none'; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content;"
```

Example above requires a a long line, looks ugly, harder to maintain and read. Having it multiline does not work (#2302).

## Needed solution

So two ways needs to be supported:

1. Newlines where `\n` will be preserved.
2. Newlines where `\n` will not be preserved.

## Alternative solution: yaml inspired syntax

I see that heredoc format was not the favorite #3802. But how about using a yaml like syntax?

**1. To preserve `\n`s we can use `|` and `|-`**

```caddyfile
body |-
  User-agent:
  Disallow:
```

**2. To not preserve `\n`s we can use `>` and `>-`**

We can have something like this:

```txt
Content-Security-Policy >-
	default-src 'self';
	img-src 'self' data:;
	script-src 'self' 'unsafe-inline';
	style-src 'self' 'unsafe-inline';
	form-action 'self';
	object-src 'none';
	frame-ancestors 'none';
	upgrade-insecure-requests;
	block-all-mixed-content;
```

**Comment by francislavoie** [comment]
That syntax wouldn't work because it would be ambiguous when it should end. The Caddyfile is not yaml-like. Arguments can continue on the same line. Take `respond`'s single-line syntax for example.

I still think the heredoc approach from #3802 is best, because there's a clear start and end delimiter. We could be a bit more creative about the start delimiter if `<<<` not popular, but honestly I think it's well understood so I think it's the most natural option.

@mholt is there any way I can convince you we should have heredoc syntax? :joy:

**Comment by mholt** [comment]
I don't understand -- Caddy strings already support line breaks. The syntax should parse properly, no?

```
"start
end"
```

**Comment by francislavoie** [comment]
The point is that it looks immensely ugly when indented.

```
example.com {
	handle {
		respond "this
truly
sucks" 200
	}
}
```

**Comment by undergroundwires** [comment]
I believe heredoc is completely fine and it would be also good to solve problem 2 i.e. linebreaking for cleaner code without preserving the newlines.

Other alternatives except using yaml could be:

Using `+` with double quotes e.g.

```
Content-Security-Policy "this" +
	"is" +
	"better"
```

Or using backslash `\`

```
Content-Security-Policy "this" \
	"is" \
	"better"
```

Sorry if these ideas are not a good match for how the back-end is written or the syntax is designed, I have not taken a deep look but I provide possible scenarios so we can keep have something to keep our config files clean.

This would also make Caddy more appealing to other users, i.e. self-marketing as no one likes to see configuration files with weird indentations or thousands of characters in same line.

**Comment by francislavoie** [comment]
Hmm, yeah I don't think those will work. And I don't think they're natural either.

Tokens are understood to be whitespace separated, with double-quotes/backticks acting as glue. If we added new syntax to glue the glue, that would be strange I think. It would mean after seeing that delimiter, the previous token would need to be modified. In the lexer, I don't think it makes sense to do "look-behind" to modify what came before. It's easier to lex forwards, by having a marker come before what's next.

I still prefer the heredoc syntax the most, with the end delimiter controlling how much whitespace is removed from the start of each line of content. It's a pretty well understood construct, many programming languages have it, including most shell languages. See https://en.wikipedia.org/wiki/Here_document. I borrowed the most from PHP for the syntax, specifically its support for indenting the end delimiter as per https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes.

**Comment by alex-bacart** [comment]
I'm also struggling with long headers in Caddyfile, especially CSP headers.
My approach is to use environment variables.

**Env file**
```env
# Environment variables allow to use line-breaks
CADDY_CSP="base-uri 'self'; default-src 'self';
style-src 'self' 'unsafe-inline'; img-src 'self';"
```

**Caddyfile**
```caddyfile
header {
	Content-Security-Policy: "{$CADDY_CSP}"
}
```

Hope it'll help somebody.

@francislavoie sorry for the off-topic question but I'm really curious why Caddyfile format has been created/chosen over YAML of some other "human-readable" format?

**Comment by francislavoie** [comment]
You can use YAML if you like, see https://caddyserver.com/docs/config-adapters. But Caddyfile is the most popular config language because it lets us provide all kinds of UX shortcuts to writing config.

To clarify, you can still do your header config without environment variables, but with the double-quote syntax you need to put the second line at the left gutter:

```
example.com {
	header {
		Content-Security-Policy "base-uri 'self'; default-src 'self';
style-src 'self' 'unsafe-inline'; img-src 'self';"
	}
}
```

With my heredocs proposal, it'll look like this:

```
example.com {
	header {
		Content-Security-Policy <<END
			base-uri 'self'; default-src 'self';
			style-src 'self' 'unsafe-inline'; img-src 'self';
			END
	}
}
```

**Comment by alex-bacart** [comment]
Thanks for your answer and a link! I just tested my approach and it didn't work neither in Chrome nor in Firefox. Browsers just ignore multiline headers and CSP configured in that way doesn't work at all. So I suppose your first code snippet would not work either - CURL request will show you the Content-Security-Policy header, but browser network panel won't and no rules from the policy would be applied.

**Comment by francislavoie** [comment]
Yeah, my understanding is that multi-line headers only work for HTTP 1.1, and not HTTP 2 or 3. So you should use a single line. You can use line wrapping in your editor to make it more convenient.
