### ISSUE TITLE
caddy OK with Firefox not with Chrome

### ISSUE THREAD

**Issue by SgtErnestBilko** [caddyserver/caddy#5358]
I am running Caddy 2.6.2 in docker (open ports 80, 443, 443 udp and 444) as a proxy server.  I'm testing so caddy and browser are both on the same lan.

Caddy works fine with Firefox on macos Monterey.

Chrome will not connect with message "This site cannot be reached".  Clicking the icon next to the address shows "Your connection to this site is not secure".  I have turned off safe browsing in settings > privacy & security > security as well as trying standard protection. 

Help with troubleshooting would be appreciated.

Thank you

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
