### ISSUE TITLE
caddyserver.com is down

### ISSUE THREAD

**Issue by cosmojg** [caddyserver/caddy#5365]
I am unable to connect to https://caddyserver.com/ whether I use Firefox or Chrome, whether I use my work or mobile Internet connection. Chrome reports: ERR_CONNECTION_REFUSED

See also: https://www.isitdownrightnow.com/caddyserver.com.html

**Comment by francislavoie** [comment]
It's working just fine for me.

**Comment by mholt** [comment]
It was intermittently down, depending on how many resources `snapd` (and I've seen this with `journald` too) decides to give up to other processes. We don't even use snap, I'm not sure why it's running or even installed. Ubuntu is losing its flavor to me.
