### ISSUE TITLE
Vulnerable to abuse if on-demand but limited subjects?

### ISSUE THREAD

**Issue by excid3** [caddyserver/caddy#5368]
I noticed Caddy was printing the vulnerability warning with my config.

```
YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place {"docs": "https://caddyserver.com/docs/automatic-https#on-demand-tls"}
```

Config:
```
"tls": {
  "automation": {
    "policies": [{
        "subjects": ["railshackathon.com"],
        "on_demand":true
      }]
  }
}
```

With a limited list of subjects, does this warning still apply? It seems like it should only apply if the subjects list is open to anything?

**Comment by IndeedNotJames** [comment]
You more or less discovered an edge-case.

Though the thing is, I don't quite see why you would want to use on-demand with a single non-wildcard subject anyway?

It just defers the issuance of that subject until you try to connect to it the first time, which will introduce some initial delay to that connection.

> With a limited list of subjects, does this warning still apply? It seems like it should only apply if the subjects list is open to anything?

If you mean by _limited_ something like `example.com` and not `*.example.com` then no, that warning does not apply and it could be omitted, yes.

**Comment by excid3** [comment]
I'm running a hosting service, so we're using on_demand because often times our customers haven't configured DNS yet when they add the domain to our application. We update the Caddy config immediately when they add a domain, and `on_demand` gives the customer time to update their DNS and we don't have any failures this way.

We do support wildcards, but we don't actually make those `on_demand` since they're using the API for authentication and don't need to delay that.

**Comment by francislavoie** [comment]
Yeah that's probably fine. We could loosen the warning to only show up if the automation policy isn't only non-wildcard domains.

**Comment by excid3** [comment]
Thanks! 👍
