### ISSUE TITLE
Pass only metrics/use custom port for metrics rather than admin API port

### ISSUE THREAD

**Issue by Cordtus** [caddyserver/caddy#5370]
Trying to scrape these metrics with Prometheus is proving very difficult. I have Caddy running in LXD container, the host machine cannot even access this port by default, and if I reverse proxy it to the host machine it works but my other server running Prometheus can't access it.

Is there already a way to do this? The documentation is not super clear around this... I just want to be abe to monitor some info like total requests, requests by IP, traffic metrics etc. Having these metrics per-domain would be even nicer.

**Comment by mholt** [comment]
You should track #3784 -- and I'll ping Dave for his wisdom on this one.

**Comment by Cordtus** [comment]
Apologies for the needless issue -- I figured out how to specify another path and use a domain for prometheus to scrape from. Separating metrics per-host is likely not useful anyway just looking through the actual metrics that are provided.
