### ISSUE TITLE
Support setting request headers for reverse-proxy command

### ISSUE THREAD

**Issue by damnever** [caddyserver/caddy#5376]
The one-line reverse-proxy command could be even better if it supports basic authentication like this:

```
caddy reverse-proxy --from :10000 --to http://user:pass@:20000
```

**Comment by francislavoie** [comment]
At that point, I'd argue you're better off using a Caddyfile and using `header_up Authorization` to set the credentials (base64 encode it ahead of time).

**Comment by damnever** [comment]
In my case, the one-line command is for temporary use in a safe environment.

**Comment by francislavoie** [comment]
The problem is `--to` is an upstream address (host+port, with scheme just as a hint to the transport options), not a URL. So using URL semantics like authentication is not supported in general. I don't think the added complexity is warranted, because we'd have to change our upstream address parsing code.

**Comment by damnever** [comment]
Another method is to add a command line option.

I am using `caddy run -config -` to work around this:
```bash
docker run --rm -p 10000:10000 library/caddy sh -c 'echo -e ":10000 {\n reverse_proxy :20000 {\n header_up Authorization \"Basic base64_encoded\"\n }\n}" | caddy run --adapter caddyfile --config -'
```

**Comment by mholt** [comment]
I'm also inclined to suggest a config file is the best answer here; but would a command line flag to set upgoing headers work for you?

**Comment by francislavoie** [comment]
I'd say a `--header-up "<field>: <value>"` option would be the way to go here. Maybe simply `--header` because it's probably very rare to need to set response headers in this case, and `--response-header` could be used for that later on if necessary.

**Comment by damnever** [comment]
An option to set headers sounds good to me.

**Comment by mholt** [comment]
`--header-up` is probably best (specific and consistent).

**Comment by francislavoie** [comment]
This will sorta depend on the work from https://github.com/caddyserver/caddy/pull/5379 otherwise we'd waste a bit of time setting up the type to accept multiple header values. With the cobra changes, we can just use `StringSliceP()` which is simpler.
