### ISSUE TITLE
Help problem /.well-known/acme-challenge/

### ISSUE THREAD

**Issue by salitis777** [caddyserver/caddy#5381]
Hello! Please write me, how I can write the request code to the configuration file: /var/snap/rocketchat-server/current/Caddyfile
to make the process work, my local path to get the certificate is: /var/www/letsencrypt/. 
i need to open a folder for sharing /.well-known/acme-challenge/
thank you!

I don't have enough knowledge, it gives such an error:

chat:~$ sudo certbot certonly --webroot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Please enter the domain name(s) you would like on your certificate (comma and/or
space separated) (Enter 'c' to cancel): xx.xxxx.xx
Requesting a certificate for xx.xxx.xx
Input the webroot for xxx.xxxxx.xx: (Enter 'c' to cancel): /var/www/letsencrypt

Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: xxx.xxxx.xx
  Type:   unauthorized
  Detail: xx.xx.xx.xx: Invalid response from https://xx.xxx.xx/.well-known/acme-challenge/UO87Fl5sgw_GpK772YHICOawg-DBAqilh1BUKrx7MO0: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" type=\"text/css\" class=\"__meteor-css__\" href=\"/ae2dbc3e8f9ef6251720fa82c0d"

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by francislavoie** [comment]
Caddy has ACME built-in, you don't need to use Certbot.

This doesn't seem like a problem with Caddy.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by salitis777** [comment]
thank's
sorry)
