### ISSUE TITLE
Question: configs in parent child folders

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#5387]
Sorry to ask a question on GitHub but am on mobile 

I have a use case where I need to server each user with a slightly different caddy config . 

Plus each users config needs to be changed independently of the other users configs. By having them in different folders it’s much easier to automate the caddy config changes because I don’t have to worry about merging the config. I can just replace it fully.

If I can have a folder per user with a caddy config then it’s better for me.

Is that possible ?  Sort of like Includes but for configs

**Comment by francislavoie** [comment]
See https://caddyserver.com/docs/caddyfile/directives/import

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
Like a shared hosting environment?

The Caddyfile supports importing other files including wildcards. Looks like Francis just posted a link above while I was typing this.

Just be aware that you need to trust your users and their configs if you're doing this. Good luck!

**Comment by gedw99** [comment]
https://caddyserver.com/docs/caddyfile/directives/import

It sort of helps to make things more manageable in terms of common config to be imported and used . 

This is an example of what I want to do.

Caddy start using the config in the Root folder.

Root folder
- caddyfile
- user A folder
  - caddyfile 
 - user B folder 
   - caddyfile
 

If it’s not possible I can just use a single caddy folder with subdomains per user.

then in the golang worker process, I will have to load the whole caddy file, merge the changes for User A subdomain and then output to the Caddy file ( and this replacing the whole caddy file but having only actually changed the config for User A.

I am using NATS to do a sort of command and control architecture so that I can send the config change to nats and the config worker running as an agent on each casdybseever gets the config change and updates that caddy’s config . 

If there is a smarter way to do command and control of many caddy servers and / or partial config updates please yell :)

**Comment by francislavoie** [comment]
Just do `import ./*/Caddyfile`

**Comment by gedw99** [comment]
Hey @francislavoie 

you beat me to the answer :)

I wrote about the system to allow config changes over time using NATS automation / Command and Control . Any comments ? Am still learning the Caddy Kung-Fu

**Comment by francislavoie** [comment]
See https://caddyserver.com/docs/architecture#managing-configuration

**Comment by gedw99** [comment]
I am also playing with the idea of using this NATS automation for updating the local store of the Caddy Security model that Paul Green developed. 

Any user added via any caddy instance would then be sent to NATS Server and synchronised with all the other caddy servers using Caddy Security .

**Comment by gedw99** [comment]
> See https://caddyserver.com/docs/architecture#managing-configuration

Oh Thank you. Looks like the solution
