### ISSUE TITLE
FileStorage:/var/empty/.local/share/caddy permission issue on 2.6.2

### ISSUE THREAD

**Issue by kaihendry** [caddyserver/caddy#5388]
Just checked on an old [voidlinux](https://voidlinux.org/) machine and Caddy was down because it could not write to an odd path `FileStorage:/var/empty/.local/share/caddy` which doesn't appear documented https://caddyserver.com/docs/conventions

Workaround:
```
[root@knuckles ~]# mkdir -p /var/empty/.local/share/caddy
[root@knuckles ~]# chown -R caddy /var/empty/.local/share/caddy
```

**Comment by francislavoie** [comment]
I don't think you used an official installation method. We can't support unofficial installations.

But that is documented. Your user's HOME is probably `/var/empty` for whatever reason.

**Comment by IndeedNotJames** [comment]
You probably don't want to use `/var/empty` for storing persistent data - such as Caddy's certificates.

Please note that voidlinux isn't officially supported and also not listed as community maintained at https://caddyserver.com/docs/install

I don't know what the usual policy with voidlinux package (or rather service) issues are, but I believe you might be better off reaching out to voidlinux' bug tracker or whatever they might be using.

As for what that path is, it seems to be `$HOME/.local/share/caddy`, just with Caddy's home directory set to `/var/empty`.

Will close this for now.

**Comment by kaihendry** [comment]
My $HOME is /var/lib/caddy though Caddy bizarrely doesn't print this on start, so I am not totally sure.

```
export HOME=/var/lib/caddy
ulimit -n ${MAX_OPEN_FILES:-8192}

exec chpst -u caddy caddy run ${OPTS} --config ${CONFFILE:-/etc/caddy/Caddyfile}
```

**Comment by francislavoie** [comment]
Caddy prints its environment when you add `--environ` to the run command.

**Comment by kaihendry** [comment]
Ah, `/var/empty/` is the default when home is unset. Ok got it, thank you.
