### ISSUE TITLE
Limit `a` dynamic upstream source to specific IP versions

### ISSUE THREAD

**Issue by xeruf** [caddyserver/caddy#5392]
As follow-up to https://github.com/caddyserver/caddy/pull/4470, I would like to have an `aaaa` source.

Here is the use-case:
- Caddy runs on an IPv4-accessible server, proxying to IPv6-accessible servers
- Rather than adding entries for each domain one by one, Caddy could just resolve the incoming domain to the right server, if I could restrict it to only use IPv6-servers

Currently, if I use an `a` dynamic upstream, it sometimes resolves to the IPv4, leading to complications.

**Comment by IndeedNotJames** [comment]
A few notes on that:
- I think calling the current dynamic module just "`a`" is misleading
- Changing the name of that dynamic module would be a breaking change
- The current implementation's [`Resolver.LookupIPAddr`](https://pkg.go.dev/net#Resolver.LookupIPAddr) returns a slice of resolved IPv4 and IPv6 addresses, which Caddy then load balances between, explaining your observed behavior ("it sometimes resolves to the IPv4")
- In your case, you could configure a health check to fall back to the working upstream (IPv6), if the resolved IPv4 isn't reachable or whatever
- Current implementation probably fails x% of times on hostnames that resolve dual stack with Caddy being on a IPv6-only (or IPv4-only) host
- [`Resolver.LookupIP`](https://pkg.go.dev/net#Resolver.LookupIP) is like `LookupIPAddr`, but allows one to specify which family to resolve for

**Comment by francislavoie** [comment]
We could probably just add a `versions` config to `a`, defaulting to both v4 and v6, but you could configure it to only v6 to ignore any IPv4 records.

**Comment by mholt** [comment]
> I think calling the current dynamic module just "a" is misleading

Yah, I just didn't want to call it `aaaaa`. That seemed a bit ridiculous :upside_down_face: 

The patch LGTM -- thank you!
