### ISSUE TITLE
Where do I put my Caddyfile?

### ISSUE THREAD

**Issue by serg06** [caddyserver/caddy#5395]
Hello! I've followed the tutorial and loaded my Caddyfile with `caddy reload --config Caddyfile`.

When I restart my PC, Caddy forgets my config and I have to run `caddy reload --config Caddyfile` again.

Is there any way to save the config and/or tell it which config to load on startup?

**Comment by francislavoie** [comment]
It depends on your installation method. See https://caddyserver.com/docs/running.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
