### ISSUE TITLE
Allow disabling of https auto redirect for specific hosts in Caddyfile

### ISSUE THREAD

**Issue by tracker1** [caddyserver/caddy#5410]
It would be nice to be able to simply disable the automatic http to https redirects for a single host in a Caddyfile.

**Comment by tracker1** [comment]
@francislavoie I still *WANT* https available... I just don't want to force redirect.

**Comment by francislavoie** [comment]
Make two site blocks. One with `http://` and one without (which is HTTPS)

**Comment by mholt** [comment]
@tracker1 To illustrate:

```
http://example.com {
   respond "Hello, plaintext"
}

https://example.com {
   respond "Hello encrypted"
}
```

Hope that helps :smiley:
