### ISSUE TITLE
Question - Directives order in caddyfile

### ISSUE THREAD

**Issue by Barnoux** [caddyserver/caddy#5411]
Hello everyone,

In the Caddyfile's directives. I know that there a default order of this directives that are hardcoded => https://caddyserver.com/docs/caddyfile/directives#directive-order

Does that mean that if we write the directives in a random order.it does not have an impact on the Caddy web server? 

Regards,

BBA

**Comment by francislavoie** [comment]
Correct. But order does matter in some places, like the order of your reverse_proxy upstreams matters for load balancing. But directives are sorted according to that order to make it harder to write configs that don't make sense.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by Barnoux** [comment]
Thanks,
Sorry next time i will go to https://caddy.community/ for this kinf of question 👍
