### ISSUE TITLE
HTTP 520 Origin Error on Headscale behind Caddy behind Cloudflare

### ISSUE THREAD

**Issue by Procsiab** [caddyserver/caddy#5412]
Hello there,
I'm posting this issue on Caddy's GitHub project page because it shows up only when deploying a specific version of this software, and never showed up before; however I do understand that after further investigation this discussion may be moved to the CLoudflare's forum or even to Headscale's GitHub page.
That being said, I'll do my best to explain the situation.

### Minimal working example
The following Caddyfile, served through the **Caddy 2.6.2** container image, works perfectly with **Cloudflare's strict TLS and Origin certificate** enabled in front of it, and **Headscale 0.20.0** behind it:
```Caddyfile
*.mydomain.stuff {
    tls  {
        dns cloudflare {env.CLOUDFLARE_API_TOKEN}
        client_auth {
            mode require_and_verify
            trusted_ca_cert_file /cert/origin-pull-ca.pem
        }
    }

    @headscale-app host vpn.mydomain.stuff

    handle @headscale-app {
        encode gzip
        reverse_proxy http://localhost:8080
    }
}
```

### Reproduce the issue

Among these three components, upon changing the Caddy container to version 2.6.3 (also tested with 2.6.4) the following happens:
- on the Headscale server, the following error is logged `INF The HTTP2 server was closed error=EOF`
- on the Tailscale clients (everyone of them) the following error is logged: `Received error: PollNetMap: Post "https://vpn.mydomain.stuff/machine/map": all connection attempts failed (HTTP: unexpected HTTP response: 301 Moved Permanently, HTTPS: unexpected HTTP response: 520 Origin Error)`

By stopping Caddy, and restarting it through the 2.6.2 container these errors disappear without the need of restarting the server nor the clients.

### Caddy debug logs

During the aforementioned unexpected behaviour on the clients and the server, using the `debug` level on the Caddy log only highlights the following lines, which do not ever show up if running the same minimal working example with Caddy <= 2.6.2:
```
2023-02-24T10:24:16.593275567+01:00 stderr F {"level":"debug","ts":1677230656.5929484,"logger":"http.stdlib","msg":"http: response.WriteHeader on hijacked connection from github.com/caddyserver/caddy/v2/modules/caddyhttp.(*responseRecorder).WriteHeader (responsewriter.go:191)"}
```

### Impact

New Headscale clients are unable to join the network, nor a left client event will be notified to 

### Only with Headscale?!

Apparently this issue with HTTP error 520 affects only the Headscale application: I also tried the Caddy versions 2.6.3 and 2.6.4 with Nextcloud, Vaultwarden, Grocy and Jellyfin, and all of them are working as usual, at least from what I could see from the log files and by functionally testing each specific application in the browser.

Moreover, by pausing Cloudflare altogether for the site mydomain.stuff and then restarting Caddy 2.6.4, Headscale works again. At that point is even possible to turn back on the Cloudflare features for the site and no more HTTP 520 errors appear on the Tailscale clients logs.

Note: by "pausing" Cloudflare I am referring to the option named "Pause Cloudflare for this site" in the site overview page, and not the option to just disable proxying for that site: I also tried to just disable Cloudflare's proxying for *.mydomain.stuff, but that does not solve the issue.

**Comment by francislavoie** [comment]
Would you be able to try doing a bisect to find the exact commit that broke it? You can look at https://github.com/caddyserver/caddy/compare/v2.6.2...v2.6.3 and build at commits in that range to see where it breaks.

**Comment by Procsiab** [comment]
I agree that this would make it more clear where to look for; however, it appears to be relatively time consuming: I will do my best to try the builds against those commits but I am assuming it will take several days, given the amount of my spare time (by the way, thanks for pointing out the change comparison, this saves me some time fiddling with GitHub).

Also, if you have any tips on how to speed up this process that would be awesome. Anyways, I'll update this thread when I'm done with this process.

**Comment by mholt** [comment]
Interesting, that debug log refers to a line that is gated by this condition:

```
if rr.stream || (100 <= statusCode && statusCode <= 199) {
```

meaning that the response recorder is either configured to stream (not buffer) responses, or the HTTP response is informational 1xx.

If you remove the `encode` directive does the error still happen?

**Comment by francislavoie** [comment]
Yeah - the idea of bisect is basically starts from the commit in the middle, if it works then it means the breakage came after. If it doesn't work, then the breakage came before. Then you try the commit in the middle of that half, and so on. Binary search. Should only take a few tries to find it. You can build with `xcaddy build <hash>`

**Comment by Procsiab** [comment]
### Solution (?)

Thanks for the help and the definetly useful tips to everybody. I was started to setting up my build environment with Go 1.19 and `xcaddy` ready to roll, when I saw @mholt suggestion to try and remove the `encode gzip` line from the example Caddyfile: that solved the issue, for both Caddy v2.6.3 and v2.6.4.

To be sure that's solved I restarted both the Caddy container and the Headscale application behind, and dropped the caches at Cloudflare's level.

I am still unsure why this came out from 2.6.3, however if you think this does not need further investigation I might as well close this issue. I am still willingful to go for the bisect and track down the exact commit, if that can still be prove useful.

**Comment by mholt** [comment]
Cool, that doesn't surprise me, as the encode module needs to wrap the response writer so it can count the size of the response (as well as read response headers, etc) and decide whether to encode it.

I wonder if @WeidiDeng might have a clue as to what is causing the issue; I know that there were recently some changes made to the ResponseRecorder / wrapper types. Knowing which commit could be useful still. If you want a good first guess, I might suggest c77a6bea66b30ea88cd991671bf67669c80ffcdd -- it's the most recent change to that code and might be relevant.

**Comment by WeidiDeng** [comment]
@Procsiab Can you provide a sample docker compose for headscale and client config or links to those? I'll try to replicate these problems.

**Comment by WeidiDeng** [comment]
Headscale appears to use [derp](https://github.com/juanfont/headscale/blob/c39085911f5c09f9ad2d0f5510f5a83cd4fd5b2e/derp_server.go#L97), a custom upgrade protocol, I'm thinking maybe because cloudflare added gzip accept to origin request when tailscale client request don't one.

[c77a6be](https://github.com/caddyserver/caddy/commit/c77a6bea66b30ea88cd991671bf67669c80ffcdd) changed how upgrade work, instead of writing directly to hijacked conn, we first allow http write header and status using http.ResponseWriter interface. And seeing how encode will [save status code](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/encode/encode.go#L194) and [flush it later](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/encode/encode.go#L265).

Caddy won't encode [websocket](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/encode/encode.go#L311), but caddy will gladly encode other protocols that require upgrade. But that's just my speculation.

**Comment by Procsiab** [comment]
@WeidiDeng unfortely I am not able to reproduce this in a test environment through a container compose file: I tried running a Headscale instance, Caddy proxy and two Tailscale clients inside the same network, however this meant that I had to use the embedded headscale DERP server and disable TLS altogether.
The origin error did not show up by using the `encode` directive.

The environment in which the issue occurs uses Podman as the container engine, then Hashicorp's Consul and Nomad for service discovery and orchestration; moreover, the worker node on which the services run, uses Podman and Nomad in a "rootless fashion". The following gist contains all the files I used to try and reproduce the issue on a local environment:
https://gist.github.com/Procsiab/ba202c312716091d9b0ee30dd6321532

I still have to attempt the deploy of a custom built image: I'm going to start from the commit you and @mholt suggested and update this discussion soon.

**Comment by WeidiDeng** [comment]
@Procsiab Can you provide relevant access logs (with sensitive information redacted, not just debug error logs)? With cloudflare and without cloudflare.

**Comment by Procsiab** [comment]
@WeidiDeng I created [this](https://gist.github.com/Procsiab/35dc58d66527ccf586a6ed2f5d4b99aa) other private gist containing the redacted access logs for the two following scenarios, both with Caddy v2.6.4 with `encode` present:
- _caddy_264_cloudflareon.log_: Cloudflare enabled, the error does appera on Tailscale clients and Headscale server
- _caddy_264_cloudflareoff.log_: Cloudflare paused for the site and Origin certificate disabled, the error does not appear

**Comment by WeidiDeng** [comment]
It as I thought, cloudflare added accept-encoding to origin request, I'll work on a fix.

**Comment by Procsiab** [comment]
Following up your advice regarding the bisect procedure, I compiled Caddy starting from the commit sugested by @mholt and @WeidiDeng and got the following results:
- c77a6bea66b30ea88cd991671bf67669c80ffcdd The issue does appear as observed for the releases 2.6.3 and 2.6.4
- 12bcbe2c4924ecbf6730fc340a7a4250bddcc9be (previous commit) The issue is not reproducible anymore
As @francislavoie pointed out, I used Go 1.19 and had no problem throughout the build process.

**Comment by WeidiDeng** [comment]
@Procsiab Can you build caddy with [https://github.com/caddyserver/caddy/pull/5419](this pr) merged?

Build caddy with (and any other plugin you may have)

```
xcaddy build \
    --with github.com/caddyserver/caddy/v2@fix-5412
```

**Comment by Procsiab** [comment]
@WeidiDeng I'm happy to report that with a Caddy container built off the `fix-5412` branch,  I cannot reproduce the issue anymore :tada:
