### ISSUE TITLE
Should Caddy be adding /'s to fs.FS paths?

### ISSUE THREAD

**Issue by esell** [caddyserver/caddy#5416]
While recently playing around with a Caddy module that operates in the `caddy.fs` namespace (https://github.com/sagikazarmark/caddy-fs-s3), I ran into an issue where sub-directory listings were not working. The details are in this issue: https://github.com/sagikazarmark/caddy-fs-s3/issues/26, but the short version is that Caddy was tacking on a `/` to the directory name, so when `fs.ValidPath()` was called it was failing as the documentation states "Paths must not start or end with a slash: “/x” and “x/” are invalid" (https://pkg.go.dev/io/fs@master#ValidPath). This doesn't happen at the root directory as that is passed as `.`.

There are a couple of work-arounds for this, but I was wondering: is this expected behavior from Caddy? If so, should it be changed/updated? My guess is if more folks start building out `caddy.fs` modules and use `fs.ValidPath()` they will run into the same problem.

**Comment by mholt** [comment]
@esell Great question!

When I wrote the [caddy-embed plugin](https://github.com/mholt/caddy-embed), which embeds your site into the binary and serves it with fs.FS, I encountered a similar issue:

https://github.com/mholt/caddy-embed/blob/6bbec9d65515ffdb40060d84255826f4fef6126c/module.go#L93-L97

Now that the file-server is using fs.FS for all file system access (including the default of the local disk, as we have a simple wrapper to make it an fs.FS:

https://github.com/caddyserver/caddy/blob/99d47050e97a8ccac2aad3bda46be46d4fec85ed/modules/caddyhttp/fileserver/staticfiles.go#L181-L183

https://github.com/caddyserver/caddy/blob/99d47050e97a8ccac2aad3bda46be46d4fec85ed/modules/caddyhttp/fileserver/staticfiles.go#L638-L651

), perhaps we should be doing something about the leading and trailing slashes in the file server itself.

The slashes obviously need to remain externally for the user-facing URLs, and we canonicalize the URLs (by default) for example redirecting to add a trailing slash for directory paths, or removing it for file paths; but it sounds like that when actually _using_ the fs.FS interfaces, we need to ensure those trailing slashes are always trimmed.

Sounds like a simple fix, if done carefully and in the right place(s). I hope just one place would be necessary.

Want to take a stab at a PR? :smiley:

**Comment by esell** [comment]
The `fs.ValidPath()` call is coming outside of Caddy. In this scenario [caddy-fs-s3](https://github.com/sagikazarmark/caddy-fs-s3) is utilzing a library called [s3fs](https://github.com/jszwec/s3fs) to do most of the heavy lifting. s3fs calls `fs.ValidPath()` at the start of the `fs.Stat()` implementation: https://github.com/jszwec/s3fs/blob/main/fs.go#L131, so it is a pretty frequent call.

I don't mind poking around the Caddy code to try and identify the right area for this "fix" to potentially go. I'll work on putting something together and submit it for review to get everyone's thoughts.

**Comment by esell** [comment]
This might be too simple, so I want to check with you @mholt and get your thoughts. 

What if we change https://github.com/caddyserver/caddy/blob/99d47050e97a8ccac2aad3bda46be46d4fec85ed/modules/caddyhttp/fileserver/staticfiles.go#L253

to

`filename := strings.TrimSuffix(caddyhttp.SanitizedPathJoin(root, r.URL.Path), "/")`  ?

I didn't think it made sense to fiddle with `caddyhttp.SanitizedPathJoin()` as it is used throughout Caddy, so the next option was directly modify `filename`. It doesn't appear to be used for URL related actions later on in the code, so I thought it was pretty safe. 

I made the change and did some basic tests using both the default `osFS` and [caddy-fs-s3](https://github.com/sagikazarmark/caddy-fs-s3) without issue.

If that works for you I can submit a PR.

**Comment by mholt** [comment]
@esell It would not surprise me if the correct solution was that simple :slightly_smiling_face: 

Yeah, I think that's the best way to do it. From looking at the code, I think path canonicalization redirects (adding `/` to dir paths, removing them for file paths) should still occur (they use the URL path value directly), but can you just verify that?

I think that's a great solution :smiley:
