### ISSUE TITLE
Building from website

### ISSUE THREAD

**Issue by Kani3D** [caddyserver/caddy#5429]
Hello,

im trying to build and download this: https://caddyserver.com/download?package=github.com%2Fcaddy-dns%2Fduckdns
but it does not stop building and i get a timeout after a couple of minutes.. Any help?
Tried different browsers and networks.

Thanks in advance.

**Comment by mholt** [comment]
Yes, sorry, it's due to a bug in the `go` command. Please notice the big red warning at the top of that page:

> ⚠️ Due to [multiple](https://github.com/golang/go/issues/56494) outstanding [bugs](https://github.com/golang/go/issues/53905) in the go command, we are aware the some downloads may hang or fail. In the meantime, you can download Caddy from [the latest release on GitHub](https://github.com/caddyserver/caddy/releases), or use [xcaddy](https://github.com/caddyserver/xcaddy) for custom builds. (Remember, this download page comes with no guarantees or SLAs.) Sorry for the inconvenience.
