### ISSUE TITLE
dns-01 challenge not attempted when {system.hostname} is specified in configuration

### ISSUE THREAD

**Issue by erikwb** [caddyserver/caddy#5432]
caddy version (built with only cloudflare-dns): 
```
v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=
```

Problem:
Caddy won't request the `dns-01` challenge type with ACME when the main block in Caddyfile is specified as `{system.hostname}.domain.com {`.

Working config:
```
{
	http_port 880
       https_port 443
}
foo.domain.com:443 {
   tls user@domain.com {
      dns cloudflare THE-API-KEY
      resolvers 1.1.1.1
   }
   reverse_proxy localhost:80
}
```

Nonworking config:
```
{
	http_port 880
       https_port 443
}
{system.hostname}.domain.com:443 {
   tls user@domain.com {
      dns cloudflare THE-API-KEY
      resolvers 1.1.1.1
   }
   reverse_proxy localhost:80
}
```

In the log for the working config, it attempts the dns-01 challenge type first.  In the nonworking config, it tries the tls-alpn-01 challenge and then the http-01 challenge in a loop.  In the case where it tries tls-alpn-01 or http-01, the {system.hostname} replacement is successfully happening and it is attempting to do these challenges against the correct hostname - I suspect the issue lies in some code that looks at the hostname to figure out what challenges are appropriate, but I have not dug into the source.

In debug logs for the nonworking example:
```
{"level":"debug","ts":1678645018.4961343,"logger":"http.acme_client","msg":"no solver configured","challenge_type":"dns-01"}
```

Please let me know if I can provide any additional detail or test anything.

**Comment by francislavoie** [comment]
Placeholders are not evaluated in every place in the config. In many cases, the config requires a static, unchanging value to work correctly. Placeholders imply that the value can be different depending on certain factors, at runtime.

Obviously the hostname isn't something likely to change at runtime, so it could certainly be argued that it should work. But this particular mechanism doesn't provide any guarantees that the value won't change.

So we don't invoke the replacer on domain names. We need to automate TLS issuance in the background, and to know to do that we need to have a particular _static_ domain name to manage a certificate for.

What you could do though, is use Caddyfile environment variables syntax which is replaced at config-adapt time (i.e. when the Caddyfile is transformed into JSON that Caddy actually runs with). The hostname is available as an env var as well on Linux, so you can do `{$HOSTNAME}` instead. See https://caddyserver.com/docs/caddyfile/concepts#environment-variables
