### ISSUE TITLE
php-fpm stuck request

### ISSUE THREAD

**Issue by root-aza** [caddyserver/caddy#5434]
Environment: https://github.com/root-aza/caddy-crash

## Nginx case:

```shell
make up-nginx
```

```shell
php app.php
```

Logs: 

![Screenshot 2023-03-15 at 15 10 25](https://user-images.githubusercontent.com/13816704/225255828-eb79ec0d-1db5-4463-a23b-4d00227c6465.png)

![Screenshot 2023-03-15 at 15 10 38](https://user-images.githubusercontent.com/13816704/225255880-adb134df-fc0f-4b6b-bde3-6dc180661d55.png)

ok, fpm gave 200

## Cady case:

```shell
make up-caddy
```

```shell
php app.php
```

Logs:

![Screenshot 2023-03-15 at 15 09 26](https://user-images.githubusercontent.com/13816704/225256482-4ef4f28f-c42d-47ec-b62d-a3586d0d4f78.png)
![Screenshot 2023-03-15 at 15 09 11](https://user-images.githubusercontent.com/13816704/225256606-1a62c85a-e671-4cfe-9a4f-1a6ebbb4633c.png)

wtf!? Fpm response with code 200 not found and and the client timed out

And if we talk about our internal service that runs on caddy, then fpm crashes with error code 0.
Now we are trying to reproduce this case locally so that you can reproduce it later.

**Comment by WeidiDeng** [comment]
It's a known problem for [2.6.4](https://github.com/caddyserver/caddy/issues/5420). We're working on a fix.
