### ISSUE TITLE
Include JSON adapter in base Caddy

### ISSUE THREAD

**Issue by stronny** [caddyserver/caddy#5448]
Hello again, this time I bring code, it's really trivial:

```go
package json_adapter

import (
        "github.com/caddyserver/caddy/v2/caddyconfig"
)

func init() {
        caddyconfig.RegisterAdapter("json", Adapter{})
}

type Adapter struct{}

func (Adapter) Adapt(body []byte, _ map[string]interface{}) (b []byte, w []caddyconfig.Warning, e error) {
        b = body
        return
}
```

Practical problems: JSONC and JSON5 adapters require custom builds and come with old caddy versions that give build time errors. Conceptually, it really doesn't make sense that Caddy can't read a JSON config, like, why?

**Comment by francislavoie** [comment]
You don't need an adapter for JSON. JSON is Caddy's native config language. Just omit `--adapter`.
