### ISSUE TITLE
How to delete all headers to upstream in reverse_proxy

### ISSUE THREAD

**Issue by heimoshuiyu** [caddyserver/caddy#5451]
Hi, In the docs <https://caddyserver.com/docs/caddyfile/directives/reverse_proxy> it said to delete all matching request, using a suffix match `header_up -Some-*`. I want to delete all headers so here is my Caddyfile

```Caddyfile
:9000 {
    reverse_proxy * http://127.0.0.1:9001 {
        header_up -*
    }
}
```

Then I run `curl -v http://127.0.0.1:9000` in command line, the output is

```textile
*   Trying 127.0.0.1:9000...
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

**Comment by heimoshuiyu** [comment]
After reading some code, I found that the correct way to write it should be `header_up -**`. I believe that the code did not handle the case where there is only one asterisk, and I will soon submit a small PR to fix this bug :)

**Comment by francislavoie** [comment]
Why would you want to do this? :thinking: that would certainly break things, many HTTP headers are _required_ to exist for the connection to be properly maintained.

**Comment by heimoshuiyu** [comment]
Because I don't want any extra headers sent by downstream to be received by upstream. I didn't realize that missing the required HTTP headers would break many programs... So, is there any way to include only specific headers to reach upstream?

**Comment by francislavoie** [comment]
Headers are harmless, unless there's some that you're particularly concerned about. It would be best if you just remove the particular headers you're concerned about, instead of removing them all.

**Comment by heimoshuiyu** [comment]
Yes, they are harmless. I want to remove headers out of privacy concerns. I'm worried that downstream HTTP programs or CDNs will add unknown headers, which may be used by upstream to analyze or track.

For example, Cloudflare adds headers like `cf-*` and `cdn-*`. Some browsers may add specific headers in certain cases. It's hard for me to find all these headers. In this case, upstream will know that I am using a CDN or a specific browser, which is something I want to avoid.

**Comment by francislavoie** [comment]
Why is that a concern? A reverse proxy is not a forward proxy. If you don't trust the software you're proxying to, then why are you proxying to it?

**Comment by heimoshuiyu** [comment]
Because upstream only accepts requests from certain regions, and I can't install a forward proxy on all clients. Therefore, using a reverse proxy is the only choice.

**Comment by mholt** [comment]
We could probably swap the order of add and delete so that delete comes first. Off the top of my head I can't think of a reason why you'd need delete to come last. Want to submit a PR for review?

**Comment by heimoshuiyu** [comment]
@mholt Sure! I apologize for missing your message earlier, but just a moment ago, I submitted a pull request.
