### ISSUE TITLE
Caddy still attempting to create autosave folder despite --resume not being set

### ISSUE THREAD

**Issue by udf2457** [caddyserver/caddy#5456]
According to [multiple](https://caddyserver.com/docs/command-line)  [places](https://caddyserver.com/docs/running#unit-files), in the docs, `--resume` is supposed to be the magic flag that enables autosaving.

Therefore, is it not quite reasonable to expect that starting `caddy` as follows:

`/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile --pidfile /custom/path/to/caddy.pid`

Would **_NOT_** enable autosaving ?

However, the logs still show `caddy` attempting to setup autosaving despite `--resume` not being set:

`
{"level":"error","ts":1679650316.620476,"msg":"unable to create folder for config autosave","dir":"/path/to/.config/caddy","error":"mkdir /path/to: read-only file system"}`

For the record, my Caddyfile:
```
{
	log default {
		output stdout
		format json
		include http.log.access admin.api
	}
	auto_https off
}

localhost
respond "Hello, world!"
```

**Comment by IndeedNotJames** [comment]
The docs you linked to state
> [...] the `autosave.json` which is [persisted](https://caddyserver.com/docs/json/admin/config/) by default.

Anyhow, you probably want to set `persist_config off` in the global options block.
See https://caddyserver.com/docs/caddyfile/options#persist-config

Next time, please ask your question in the official forum at https://caddy.community instead, as the GitHub issue tracker is intended for bug and feature requests only :)

**Comment by mholt** [comment]
Yep -- this is the correct behavior. (Thanks, @IndeedNotJames -- echoing your comment here.)

Persisting a config and resuming a config are two different things.

You cannot resume if a config was not persisted first. :wink:

**Comment by udf2457** [comment]
Not sure if I agree @mholt 

Certainly the way I read the docs was `--resume` was "API mode" and without `--resume` was "Caddyfile mode" which by definition is persisted due to the presence of a provided Caddyfile.

**Comment by mholt** [comment]
> Not sure if I agree @mholt

Don't agree with what, exactly?

To be clear, the docs say that autosaving a config is enabled by default. And that `--resume` will use the last-autosaved config.

Not really sure how to make it more clear...
