### ISSUE TITLE
cel-go deserializer.Deserialize undefined

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#5465]
Upon upgrading to using `2.6.4`, I am experiencing the following error when testing the package.

https://github.com/greenpau/caddy-trace/blob/d3a2ad6eb494a4e7e6d1fd162ffc496c3fe5e149/go.mod#L6

```
# github.com/google/cel-go/parser/gen
Error: ../../../go/pkg/mod/github.com/google/cel-go@v0.13.0/parser/gen/cel_lexer.go:276:32: deserializer.Deserialize undefined (type *antlr.ATNDeserializer has no field or method Deserialize)
Error: ../../../go/pkg/mod/github.com/google/cel-go@v0.13.0/parser/gen/cel_parser.go:164:32: deserializer.Deserialize undefined (type *antlr.ATNDeserializer has no field or method Deserialize)
```

**Comment by greenpau** [comment]
To address the above, I had to bump to the latest commit in `cel-go`

```
go get github.com/google/cel-go/parser@42f56a6c91ae3c2298ac276f7ed0f24a76822caf
```

**Comment by francislavoie** [comment]
Did you run `go mod tidy`? This doesn't seem like a problem on our end.

**Comment by greenpau** [comment]
> Did you forget to run go mod tidy? This doesn't seem like a problem on our end.

Nope. I did not forget it.

**Comment by mholt** [comment]
It's antlr again...

Try removing all lines from `go.mod` that contain `antlr`, save it, and run `go mod tidy` again.

**Comment by greenpau** [comment]
> It's antlr again...

@mholt, I solved it by aligning to `HEAD` of `cel-go`, but it becomes annoying 😅
