### ISSUE TITLE
Overwrite remote_ip with x-forwarded-for for ip_hash load-balancing

### ISSUE THREAD

**Issue by shufps** [caddyserver/caddy#5469]
Hi,

I've been researching for a couple of hours and still didn't find out if Caddy supports this or not.

My Caddy is behind another Reverse-Proxy (because it can't do `ip_hash` load-balancing :weary: ) but I can't simply swap it because it would require a lot of work that is not doable in a short timeframe.

I tried Nginx before but it doesn't support active health checks (except if paying for Plus).

After researching a lot I found out that Caddy is lightweight, has an appealing config file format and supports ip_hash.

Now I'm struggeling with the last problem - maybe a show-stopper, idk - that the load-balancer should use the IP from X-Forwarded-For as remote-ip before it is hashed.

I tried to set the X-Real-IP header to the X-Forwarded-For IP but it doesm't seem to work.

Somewhere else I found that the Log always shows the incoming headers, therefore always shows the IP of my other proxy, but according to the log, it's always the same upstream server that is selected. Therefore I assume that it's not working.

Any ideas if Caddy can do this?

Thx in advance!

**Comment by francislavoie** [comment]
Currently `ip_hash` only uses the remote address, I think.

With all the work we've done recently with `trusted_proxies` and built-in `client_ip` parsing (see https://github.com/caddyserver/caddy/pull/5104), it should be trivial to add another policy that can read from the client IP instead.

**Comment by francislavoie** [comment]
Alright, updated https://github.com/caddyserver/caddy/pull/5468 with the new `client_ip_hash` policy. Feel free to build from that PR to try it out :+1:

**Comment by shufps** [comment]
> Alright, updated #5468 with the new `client_ip_hash` policy. Feel free to build from that PR to try it out +1

Wow, thx! I'll test it right away 🥳

**Comment by shufps** [comment]
just in case you need a working Dockerfile (based on nonroot-image):

[Dockerfile.tar.gz](https://github.com/caddyserver/caddy/files/11137267/Dockerfile.tar.gz)

**Comment by shufps** [comment]
Almost there ... It seems the version prior to 2.7.0 can't choose which header to use for `ip_hash_client`, unfortunately :pleading_face: 

But I can change it in the code and try it with `X-Forwarded-For` or `Cf-Connecting-Ip`.

**Comment by shufps** [comment]
Hmm, this was the first I tried because I read it in the PR as comment.

But: 
```
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized global option: trusted_proxies
```

This is the hash I'm building:

```
commit 1785297f8134062d6ff5a779394914d862797520 (HEAD -> client_ip_hash, origin/query-lb-policy)
Author: Francis Lavoie <lavofr@gmail.com>
Date:   Sun Apr 2 08:41:18 2023 -0400

    Change query policy to join all the values
```

**Comment by francislavoie** [comment]
Those go within `servers` in global options. See the docs: https://caddyserver.com/docs/caddyfile/options#trusted-proxies

**Comment by shufps** [comment]
Oh, ok sorry :see_no_evil: 

I can confirm that it works :+1: What surprises me a bit that it tends to select one upstream server more often than others.

Buut there is one thing I'm not sure if if works as intended on ipv6 addresses.

Reason for my doubt is this:

```go
// A literal IPv6 address in hostport must be enclosed in square
// brackets, as in "[::1]:80", "[::1%lo0]:80".
//
// See func Dial for a description of the hostport parameter, and host
// and port results.
func SplitHostPort(hostport string) (host, port string, err error) {
...
```

In case of an IPv6, it doesn't have `[...]:port` format: 
```
"client_ip":"2a01:x:x:x::1",
```

Are you sure the SplitHostPort function really works with an IPv6?

**Comment by alwismt** [comment]
My caddy version is  `v2.6.4`, and i tried to do that and getting that error when i try to reload `caddy reload`, would mind telling me what's wrong? (I wanna get real client ip for rate limit)

```
2023/04/25 15:05:25.419	INFO	using adjacent Caddyfile
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': Caddyfile:5 - Error during parsing: unrecognized servers option 'client_ip_hash'
```

```
{
	servers {
		# all traffic come from cloudflare cdn
		trusted_proxies cloudflare
		client_ip_hash Cf-Connecting-Ip
	}
	order rate_limit first
}
sg4.sitefire.com {
	# forward request to golang backend
	reverse_proxy [::]:8080
	# limit reqs
	rate_limit {
		zone dynamic {
			# wanna add unique ip for per user
			key {client_ip_hash}
			events 100
			window 1m
		}
	}
	encode gzip
	# just for verify that client_ip_hash works or nor
	respond {client_ip_hash}
}
```

**Comment by francislavoie** [comment]
Yes, but `2.7.0` doesn't exist yet. So you need to build from `master`.
