### ISSUE TITLE
Doesn't seem possible to disable ALPN

### ISSUE THREAD

**Issue by stronny** [caddyserver/caddy#5470]
Hello again. Caddy's ALPN configuration is a part of TLS connection policy. I would like to be able to turn it off, which is to say, pass an empty uh... this thing to golang stdlib:
>	// NextProtos is a list of supported application level protocols, in
>	// order of preference. If both peers support ALPN, the selected
>	// protocol will be one from this list, and the connection will fail
>	// if there is no mutually supported protocol. If NextProtos is empty
>	// or the peer doesn't support ALPN, the connection will succeed and
>	// ConnectionState.NegotiatedProtocol will be empty.
>	NextProtos [][string](https://pkg.go.dev/builtin#string)

Unfortunately, I don't seem to be able to do this, because of this line (58):
https://github.com/caddyserver/caddy/blob/2b3046de36bad70bd7e48478c99a8a030fb35b98/modules/caddytls/connpolicy.go#L56-L59

Maybe allow passing null explicitly as value for `"alpn":` json key?

In any case it doesn't say in the documentation that empty array means default values:
https://caddyserver.com/docs/json/apps/http/servers/tls_connection_policies/alpn/

**Comment by mholt** [comment]
:thinking: Never had a request like this before. What's your use case? Eliminating ALPN breaks upgrades to the application layer.

**Comment by stronny** [comment]
Well, having ALPN breaks TLS if I don't know what is my next proto. My Caddy use case has little to do with HTTP and nothing to do with HTTP/2 or /3.

**Comment by mholt** [comment]
I mean, I suppose we could change the condition to `== nil`, but before we do, I still want to be sure I understand the use case. How do you use a TLS connection without ALPN? Or if it's not used, why not just have it be ignored instead?

**Comment by stronny** [comment]
I don't understand the question. What do you mean "how"? I use a TLS connection without a care in the world what the next proto is.

**Comment by stronny** [comment]
I'm not really secretive about the work I do, I can explain in detail if you wish, but I tend to keep things small in issues, because the problems tend to be sidetracked miles away from the root cause. The root cause here in my opinion is that golang's TLS library allows to disable server-side ALPN, while Caddy doesn't support it. I don't ask to change any defaults, or any established behaviour, I want to specifically configure my Caddy in a way that stdlib allows, supports and doesn't frown upon, if I'm not mistaken.

**Comment by mholt** [comment]
> I use a TLS connection without a care in the world what the next proto is.

I guess that's my question then: if you ignore ALPN, then why does it matter if it's set?

**Comment by stronny** [comment]
> I guess that's my question then: if you ignore ALPN, then why does it matter if it's set?

Matt, the server needs a correct list of all possible values the client may send if ALPN is enabled, otherwise it won't accept the connection. As I don't know this list, I can't configure it in a meaningful way, I need to disable it in order to allow the client to connect, where am I wrong?

**Comment by mholt** [comment]
I still don't really understand your use case, but would you mind doing a favor and changing the `len()` logic to `== nil` to see if that does what you need?

**Comment by stronny** [comment]
I'll be happy to explain further. As I've said I use Caddy as a universal TLS termination endpoint with built-in certificate management. Suppose there's an existing client-server communication in use -- I don't know, Postgres replication. Both the client and the server know the next protocols they want (we assume ALPN is in use, otherwise the example doesn't work). Client lists its protocols, server checks if there's an intersection with its protocols. Crucially, if there isn't one, server closes the connection and doesn't allow the client in -- that's how ALPN works.

Now I need to proxy this connection through Caddy. I can't realistically modify the client to require it to not send ALPN anymore. I can't realistically go through every such connection, list every protocol they use, and then maintain this list in the future, it's just too much of a hassle. Now we're at an impasse: the client sends ALPN list, but the server -- Caddy -- doesn't know what to do with it. Caddy will not accept the client's connection, unless the client happens to request http/1.1 and/or h2. As a side note, Caddy will accept h2 even if it can't serve it later in the handlers -- it manifests as an empty answer, and I believe you have had issues with this already.

There's a really simple test case: `$ openssl s_client -alpn something -connect ...`. Try to serve it without explicitly configuring `"alpn": ["something"]`.

As for testing new logic, I'm afraid it would be difficult for me. I'm not at all a golang developer. I was able to hack around, and even made my own plugin, but it took me several days to build Caddy with it. I can of course edit the file, but I don't know what to do with this edited file, and golang proficiency is not among my life goals. That said, I'll try to do it on Monday.

**Comment by francislavoie** [comment]
> As for testing new logic, I'm afraid it would be difficult for me. I'm not at all a golang developer. I was able to hack around, and even made my own plugin, but it took me several days to build Caddy with it. I can of course edit the file, but I don't know what to do with this edited file, and golang proficiency is not among my life goals. That said, I'll try to do it on Monday.

The simplest way is to use `xcaddy` to replace the main Caddy package itself with your local checked-out copy. See the README for examples https://github.com/caddyserver/xcaddy#custom-builds

```
$ xcaddy build \
    --with github.com/caddyserver/caddy/v2=../../my-caddy-fork
    --with github.com/some-other/plugin
```

**Comment by mholt** [comment]
@stronny If I push a patch to a branch, would you be able to test a CI artifact to ensure it meets your needs?

**Comment by stronny** [comment]
Thanks, Francis, that gives me an idea indeed.

Matt, I think I'll be able to test local modifications after all.

By the way, I have remembered one more quibble I had with hardcoded behaviour: Caddy stamps `Server: Caddy` header quite early in its handlers chain. Do you want me to open a separate issue for that?

**Comment by francislavoie** [comment]
> By the way, I have remembered one more quibble I had with hardcoded behaviour: Caddy stamps `Server: Caddy` header quite early in its handlers chain. Do you want me to open a separate issue for that?

This is intended and not going to change. See other issues for discussion about it if you feel the need to dig into it.

**Comment by stronny** [comment]
It's a hard thing to search for. I was only able to find this one: #3455. As far as I understand the intention is to make Caddy more visible on the internet?

**Comment by mholt** [comment]
The header is useful for surveys and for tracing a response through proxies, for example. I've used it a number of times to ensure I'm hitting my Caddy instance on the way out. It's not a security or privacy risk. (Google it as to why)

Anyway, @stronny could you please try the artifact being built at https://github.com/caddyserver/caddy/pull/5473 ?

**Comment by stronny** [comment]
> The header is useful for surveys and for tracing a response through proxies, for example.

I totally agree, I just object to it being hardcoded when I would prefer my proxy to not modify the response in ways I didn't ask it to. I might add that this thing came up with Caddy being a forward proxy, rather than a reverse one, so the internet won't see this header either way.

> It's not a security or privacy risk.

Never claimed it is.

> could you please try the artifact being built at #5473 ?

Will do soon, thanks.

**Comment by mholt** [comment]
> I just object to it being hardcoded when I would prefer my proxy to not modify the response in ways I didn't ask it to. 

The Server header is a "good neighbor" sort of thing, Internet etiquette you could say.

**Comment by stronny** [comment]
> The Server header is a "good neighbor" sort of thing, Internet etiquette you could say.

Etiquette is optional, not mandatory though. Other popular proxies allow customisation, or don't stamp their signature at all.

https://unix.stackexchange.com/questions/124137/change-apache-httpd-server-http-header
https://stackoverflow.com/questions/246227/how-do-you-change-the-server-header-returned-by-nginx
And I think `haproxy` doesn't bother altogether, though I can't check at the moment.

**Comment by mholt** [comment]
@stronny I don't really know what the issue is, you can still remove the header if you don't want it. It's easy enough with one line of config.

With nginx you have to recompile it AFAIK.

**Comment by stronny** [comment]
> you can still remove the header if you don't want it. It's easy enough with one line of config.

Ah, right, well the issue is I wasn't able to. The reverse_proxy handler can remove upstream's Server header, but it doesn't remove its own. I would like to leave upstream's header as is and remove Caddy's, and I have no idea how to do it.

> With nginx you have to recompile it AFAIK.

No, you can do `proxy_pass_header Server`.

> And yet we choose to be good citizens by default 🤷‍♂️

And I have no problems with that.

**Comment by mholt** [comment]
> No, you can do proxy_pass_header Server.

You're talking about the proxied header value; I'm talking about the source of originally adding it in the first place. AFAIK you have to recompile NGINX to disable the automatic setting of the Server header.

To remove the Server header in Caddy, simply do:

```
header -Server
```

Did the CI build work for you?

**Comment by stronny** [comment]
Right. I wasn't able to find where to download the CI build, so I went ahead and edited my local Caddy files. I've thrown in an extra line just to make sure the running code is indeed edited:

```golang
    // enable HTTP/2 by default
//    if len(pol.ALPN) == 0 {
    if pol.ALPN == nil {
      fmt.Printf("Overriding nil ALPN list")
      pol.ALPN = append(pol.ALPN, defaultALPN...)
    }
```

And it was indeed, as I was able to see this line in Caddy output. Unfortunately this does not achieve the desired effect of turning ALPN off, rather it made the ALPN list empty, while still requiring a match with the client (which is of course completely impossible now):

```
4731/57/90 69:36:49.696 ERROR   layer4  handling connection     {"remote": "1.2.3.4:5", "error": "tls: client requested unsupported application protocols ([xxx])"}
4731/57/90 69:36:55.890 ERROR   layer4  handling connection     {"remote": "1.2.3.4:6", "error": "tls: client requested unsupported application protocols ([h2])"}
4731/57/90 69:37:05.184 ERROR   layer4  handling connection     {"remote": "1.2.3.4:7", "error": "tls: client requested unsupported application protocols ([http/1.1])"}
```

I will try to dig around more, but my capability is a bit limited to do complex code research.

**Comment by stronny** [comment]
I was able to fix this with one more edit. The side effect I imagine would be Caddy unable to solve TLS-ALPN-01 challenges if the relevant route is explicitly configured with empty ALPN list.

```
- if !alpnFound {
+ if !alpnFound && len(cfg.NextProtos) > 0 {
```

To demonstrate that it's working, I have this in the relevant route:
```json
              "handle": [
                { "handler": "tls",
                  "connection_policies": [
                    {"alpn": []}
                  ]
                },
                { "handler": "proxy",
                  "upstreams": [
                    {
                      "dial": ["127.0.0.1:81"]
                    }
                  ]
                }
              ]
```

And when I do `$ openssl s_client -alpn xxx -connect ...`, I get my connection. If I then remove `connection_policies` altogether, or do `{"alpn": null}`, I get errors again. I conclude that ALPN check is disabled iff I set ALPN to an empty array in the JSON config.

**Comment by stronny** [comment]
As for `Server` header, I sense some annoyance in your tone, and it isn't really a big deal, so I'm ready to drop the issue at any time, but you are incorrect. I can elaborate if you wish, but once again, it isn't that important.

**Comment by stronny** [comment]
> Did the CI build work for you?

Matt, don't want to be booping you for no reason, but uh... any news here?

**Comment by mholt** [comment]
> but uh... any news here?

I'm on spring break with my family until after the holiday, that's all the news I have at the moment. If there is a more interesting update from me I will post about it here, I promise.

**Comment by stronny** [comment]
Oh hey, enjoy your time of course, have a fantastic vacation. It just felt lonely here all of a sudden is all.

**Comment by mholt** [comment]
@stronny I just applied your patch to the PR; please try it out.

> The side effect I imagine would be Caddy unable to solve TLS-ALPN-01 challenges if the relevant route is explicitly configured with empty ALPN list.

Are you OK with this side-effect? I imagine the HTTP server will never it hit it unless the user explicitly shoots themselves in the foot.

**Comment by francislavoie** [comment]
@mholt I don't think you ever opened a PR for your `nilcheck` branch :thinking:

**Comment by stronny** [comment]
> @stronny I just applied your patch to the PR; please try it out.

I've already tried this code, it works.

> Are you OK with this side-effect? I imagine the HTTP server will never it hit it unless the user explicitly shoots themselves in the foot.

I'm not entirely okay with this, but I'd rather have something mostly working than not working at all. I've been thinking about this in the mean time and I think I know how to make this all right, let me briefly explain.

If Caddy had an explicit ACME handler, I could then do a catch-all route matching by ALPN with a well-known value `acme-tls/1`, and consequently I wouldn't have to keep in mind that my actual SNI-matching routes have to deal with two completely separate use-cases, namely serving the challenge AND serving the traffic. Hope this makes sense.

**Comment by mholt** [comment]
> If Caddy had an explicit ACME handler, I could then do a catch-all route matching by ALPN with a well-known value acme-tls/1,

You mean in the caddy-l4 app?

That _may be_ a possibility without too much trouble... I haven't thought it through though. Could open an issue on caddy-l4 for further discussion I suppose.

If we're satisfied with this, then I'm willing to try it for Caddy 2.7 beta 1 -- but am also prepared to backpedal this if it introduces problems.

**Comment by stronny** [comment]
> You mean in the caddy-l4 app?

I suppose it doesn't make much sense in HTTP routes, yes. On the other hand, l4 imports much of its core functionality from Caddy proper, it isn't clear to me yet where this handler will make more sense to be honest.

> That _may be_ a possibility without too much trouble... I haven't thought it through though. Could open an issue on caddy-l4 for further discussion I suppose.

I may be able to try and come up with an independent solution, but I should refrain from making any promises.

> If we're satisfied with this, then I'm willing to try it for Caddy 2.7 beta 1 -- but am also prepared to backpedal this if it introduces problems.

Wouldn't it be possible to autotest these conditions?

**Comment by mholt** [comment]
> Wouldn't it be possible to autotest these conditions?

If we can come up with every possible scenario, sure -- but even tests won't inform us as to production scenarios. If only we had telemetry...

**Comment by stronny** [comment]
> If we can come up with every possible scenario, sure -- but even tests won't inform us as to production scenarios. If only we had telemetry...

Nothing beats proper beta testing of course, but many times kind of unit testing can catch many a pitfall. With ALPN there aren't that many things to test actually:
1. you send a proto server accepts -> success
2. you send a proto server doesn't accept -> fail
3. ALPN is disabled -> success

**Comment by mholt** [comment]
Sure, but I'm also referring to this behavior:

> The side effect I imagine would be Caddy unable to solve TLS-ALPN-01 challenges if the relevant route is explicitly configured with empty ALPN list.

so we can be sure where things do and don't work.

If you want to submit a PR with tests that'd be very welcomed.

**Comment by stronny** [comment]
> Sure, but I'm also referring to this behavior:
> so we can be sure where things do and don't work.

What helps is less automagic and more well-defined logic, but I can certainly see how having everything to "just work" can be very helpful to users.

> If you want to submit a PR with tests that'd be very welcomed.

I can't even test my own code, I'm pretty sure I will not be able to do this. I'm not a real developer.

**Comment by stronny** [comment]
Looking at the code, I'm not sure anymore any additional work is required. What should happen if I have this pseudoconf:

```
server {
  listen: ":443"
  routes: [
    match alpn "acme-tls/1" {
      nop
    }
    match sni "example.com" {
      alpn []
      reverse_proxy "127.0.0.1:8080"
    }
  ]
}
```

I can't check at the moment, but my hunch is Caddy will do the right thing, that is:
* if the request bears the correct nextproto, it will match the first route, be served the challenge response, and closed peacefully;
* if the request has any other nextproto, or none at all, AND if it has "example.com" servername, it will match the second route and be proxied as intended;
* otherwise, ( standard default behaviour, irrelevant for the purposes of this discussion )

Am I wrong?

PS. Checking myself before posting, I don't see a good way to match routes by SNI or ALPN "natively" (in the Caddy proper, it's possible in L4), but I suppose it can be done using `{http.request.tls.server_name}` and `{http.request.tls.proto}` placeholders perhaps?

**Comment by stronny** [comment]
> Connection policies can match by `sni`

This is a bit of a tangent we could go into, but I don't really think it will lead anywhere exciting.
