### ISSUE TITLE
Allow configuring DNS resolvers used by the internal acme_server to verify DNS challenges

### ISSUE THREAD

**Issue by itsxaos** [caddyserver/caddy#5476]
When the internal ACME server has to verify a `DNS-01` challenge, it goes through the system resolver using  `net.LookupTXT`. It would be nice to have the ability to configure a set of name servers / resolvers to use instead of the system resolver. This setting already exists for when Caddy is acting as an ACME *client* (see [here](https://caddyserver.com/docs/json/apps/tls/automation/policies/issuers/acme/#challenges/dns/resolvers)), so it stands to reason they might be useful on the server side, too.

In this case, it came up while I was trying to come up with a way to test the new DNS server plugin I'm writing.

I've had a quick look at how this would be implemented, and unfortunately it might not be entirely straight-forward. The smallstep library *does* allow overriding the resolvers it uses to verify challenges, but not for the method Caddy is using.

Caddy uses [`smallstep/certificates/acme/api.NewHandler`](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme/api#NewHandler) [here](https://github.com/caddyserver/caddy/blob/b6fe5d4b41d07e70a502ed58d40e8b0e75067db5/modules/caddypki/acmeserver/acmeserver.go#L159):
```go
acmeRouterHandler := acmeAPI.NewHandler(acmeAPI.HandlerOptions{
	CA:     auth,
	DB:     acmeDB,                            // stores all the server state
	DNS:    ash.Host,                          // used for directory links
	Prefix: strings.Trim(ash.PathPrefix, "/"), // used for directory links
})
```
This handler will create a default [`Client` ](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme#Client) (see [this file](https://github.com/smallstep/certificates/blob/3c76834807fb38ff4ca0ee3ab12c617fd808f7cf/acme/api/handler.go#L77)), which is implemented [here](https://github.com/smallstep/certificates/blob/3c76834807fb38ff4ca0ee3ab12c617fd808f7cf/acme/client.go) (as `client` in lowercase, somewhat confusing), and looks pretty simple:
```go
func (c *client) Get(url string) (*http.Response, error) {
	return c.http.Get(url)
}

func (c *client) LookupTxt(name string) ([]string, error) {
	return net.LookupTXT(name)
}

func (c *client) TLSDial(network, addr string, config *tls.Config) (*tls.Conn, error) {
	return tls.DialWithDialer(c.dialer, network, addr, config)
}
```
I think a new [`Client` ](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme#Client) would need to be implemented, with a different `LookupTxt`.

Then, the `acme_server` module [`Handler.Provision`](https://github.com/caddyserver/caddy/blob/b6fe5d4b41d07e70a502ed58d40e8b0e75067db5/modules/caddypki/acmeserver/acmeserver.go#L92) would need to switch from using [`smallstep/certificates/acme/api.NewHandler`](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme/api#NewHandler) (which is sort of half-deprecated anyway) to the recommended [`smallstep/certificates/acme/api.Route`](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme/api#Route) (or maybe it's  [`smallstep/certificates/api.Route`](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/api#Route)? very confusing!). If you check the docs you'll see that this method is configured differently: it "requires that all the acme components, authority, db, client, linker, and prerequisite checker [are] present in the context". [`smallstep/certificates/acme/NewContext`](https://pkg.go.dev/github.com/smallstep/certificates/acme@v0.23.2#NewContext) is provided to add these things into the context. But, from what I can tell, it's not a 1-to-1 translation from the [`HandlerOptions`](https://pkg.go.dev/github.com/smallstep/certificates@v0.23.2/acme/api#HandlerOptions) (the way it is configured currently) to the things you can put into the context.
Finally, it looks like this context needs to be glued onto every incoming `http.Request` somehow - I assume this is a common Go idiom.

**Comment by FRANCKBS** [comment]
EDITA MI ESTADO DE CUENTA DE 1 USD A 10,000.00 USD EN CUENTA REAL

**Comment by FRANCKBS** [comment]
element.style {
    null: ;
    undefined: ;
}
html *:not(body):not(span):not(a):not([style*=background-image]):not([style*=background-color]):not([style*=url]):not(figure):not(svg):not(img):not([class*=dialog]):not([id*=dialog]):not([class*=Dialog]):not([id*=Dialog]):not([role*=dialog]):not([class*=sub-items]):not([class=sbsb_b]):not(input):not(select):not(textarea):not(option):not([style*=background-position]):not([class*=menu]):not([class*=logo]):not([class*=Menu]):not([class*=Header]):not([class*=header]):not([role*=menuitem]):not([aria-labelledby*=menu]):not([class*=msg-overlay]):not([class*=dropdown-options]):not([class*=rsdc-dual-month]):not([class*=popup]):not([class*=bui-calendar__content]):not([class*=tooltip]):not(header):not([class*=playControls__control ]):not([class*=playControls__elements]):not([class=now-playing-bar-container]):not([class*=flowtip-flyout-modal]):not([data-tl-id=FeaturedTopNav-FeaturedTopNavFlyout]):not([for*=variant-swatcher-item-]):not([class*=masthead]):not([class*=fbDockChatTabFlyout]):not([role=banner]):not([class*=Footer_graphikFont_2aDKW]):not([class=css-kp204g]):not([class=nova-c-dropdown__body]):not([class*=nova-c-card__body]):not([class*=StoreNavDropdown--fullWidthLifestyleImgs]):not(dd):not([class*=jfk-radiobutton-radio]):not([class*=jfk-checkbox-checkmark]):not([class*=nova-c-modal__body]):not([class*=repeatControl]):not([class*=playbackTimeline__progressBackground]):not([class*=playbackTimeline__progressBar]):not([class=trb_nh_un_ulw]):not([class=trb_nh_uw]):not([class=trb_nh_lw]):not([class=trb_nh_sf]):not([class=uc-corpNav-flyout]):not([class*=js_global-nav-wrap]):not([class=container__3tWa1zW_F3ZU29BQPEWw9Q]):not([class*=ms-bg-color-white]):not([class=h-c-header__bar]):not([class=h-c-header__nested-nav-list]):not([class=glue-c-zippy__content-container]):not([class=fixed-tabs]):not([class*=nova-c-modal__footer--spacing-inherit]):not([class*=bigsearch-area]):not([id=hplogo]):not([class*=user-form-overlay]):not([class*=modal-overlay]):not([class*=rapid-nonanchor-lt]):not([class*=JPdR6b]):not([class*=wds-dropdown-level-2__content]):not([class*=wds-dropdown__content]):not([class*=wds-global-navigation]):not([class*=wds-global-navigation-wrapper]):not(artdeco-typeahead-deprecated-results-container):not([class*=dropdownMenu]):not([class*=search-result]):not([class*=dropdown]):not([class*=Dropdown]):not([role=navigation]):not([class=clearfix]):not([class*=navigation]):not([class*=Navigation]):not([class*=cookie]):not([class*=fixed]):not([class*=drop-]):not([class=variant-swatch]):not([class=level-one-list]):not([class*=sc-hd-ms-panel]):not([class*=sc-hd-ms-hover]):not([class*=sc-hd-panel]):not([class*=sc-hd-ms-full-ver]):not([class*=networknav__hovernav-wrapper]):not([class=icbu-simple-shopping-cart-panel]):not([class*=_icon]):not([class*=hamburger__bar]):not([class*=j-select-opts]):not([class*=J-search-suggest]):not([class=aside-floating]):not([class*=floating-account]):not([class=floating-w]):not([class=desktop-categoryContainer]):not([class=desktop-userActions]):not([class*=gws-flights-widgets-]):not([class*=ReactModal__Content--after-open]):not([class=nav-background-static]):not([role='img']):not([class*="planGrid__planLabel"]):not([class*="nf-loading-spinner"]):not([class=aajZCb]):not([class="sitemap screen-only"]) {
    border-color: rgba(255, 255, 255, 0.1) !important;
    outline: none !important;
    box-shadow: none !important;
    background-image: none !important;
    background: none !important;
    background-color: rgba(0, 0, 0, 0) !important;
}

html, body, body *:not(a):not(h1):not(h2):not(h3):not(h4):not(h5):not([class*="title"]):not([id*="title"]) {
    color: var(--text-color) !important;
}

**Comment by maraino** [comment]
@francislavoie we allow to change the resolver, but I'm not sure if it is exposed, let me check

**Comment by maraino** [comment]
I've checked and the way we do it is changing the default resolver:
```go
net.DefaultResolver.PreferGo = true
net.DefaultResolver.Dial = func(ctx context.Context, network, address string) (net.Conn, error) {
	return net.Dial(network, resolver)
}
```

**Comment by francislavoie** [comment]
Hmm, that has side effects. I guess wrapping `acme.Client` would probably be okay.

**Comment by maraino** [comment]
Yes, any custom implementation of the client interface will do it:
```go
type Client interface {
	Get(url string) (*http.Response, error)
	LookupTxt(name string) ([]string, error)
	TLSDial(network, addr string, config *tls.Config) (*tls.Conn, error)
}
```

For example, for the `Get`, you will need an `http.Client`, which transport is using a `net.Dialer` with a custom resolver.

**Comment by francislavoie** [comment]
Alright, took a crack at it. @itsxaos would you be willing to build from https://github.com/caddyserver/caddy/pull/5500 and try it out?

I haven't tested the code, just wrote this up real quick. @maraino if you're not too busy, a quick review would be appreciated :pray: I hope I understood the intent of the deprecations and change to context setup.

**Comment by itsxaos** [comment]
Great!
I checked it out and got it to work, but I had to specify the resolver with `udp/` as well as `:53`.
I put a couple comments on #5500 that should make it more ergonomic.
