### ISSUE TITLE
Caddy reverse proxy together with browser-sync

### ISSUE THREAD

**Issue by snizemic** [caddyserver/caddy#5478]
Hi to all. Has anyone ever tried to run caddy reverse proxy together with browser-sync? I have a simple caddy reverse proxy for local development because I need a working HTTPS connection. But if I start it with browser-sync the caddy reverse proxy works fine but the browser-sync does not refresh the browser after some changes.
Any idea, please?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
