### ISSUE TITLE
Invalid Certificate SAN (Subject Alternative Name) when trying to use internal local CA with External IP Addresses

### ISSUE THREAD

**Issue by Lan-Hekary** [caddyserver/caddy#5479]
Hello I am having an Issue with the Internal certificate generation for IP Addresses
I am using the latest caddy version v2.6.4 with no additional modules
All the logs down below is truncated and the IPs and Domains was replace with dummy values
The Server Internal IP is 10.0.0.128
The External IP I will mark as x.x.x.x
The Remote Machine IP is y.y.y.y
And Domain name replaced with my-domain.org

the simplest configuration that produce the error I am encountering is 
```
{
        debug
}

:443 {
        tls internal {
                on_demand
        }
        respond "Hello HTTPS \"{http.request.uuid}\" from {remote}" 203
}

:80 {
        respond "Hello \"{http.request.uuid}\" from {remote}" 203
}
```

In short I am trying to use the local internal CA to generate certificates for the main domain and any external IP as well
Not that this CA certificate is generated by caddy at the start and is trusted by the system and also I installed it on my local machine it's called root.crt

when I call `curl -v  https://x.x.x.x --cacert root.crt` from my local machine ( or other remote machine via SSH ) I get this response 
> curl: (60) SSL: no alternative certificate subject name matches target host name 'x.x.x.x'

And Caddy Logs :
```
{"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"10.0.0.128"}
{"logger":"tls.handshake","msg":"all external certificate managers yielded no certificates and no errors","remote_ip":"y.y.y.y","remote_port":"51584","sni":""}
{"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [10.0.0.128]: no OCSP server specified in certificate","identifiers":["10.0.0.128"]}
{"logger":"tls.cache","msg":"added certificate to cache","subjects":["10.0.0.128"],"expiration":1680623841,"managed":true,"issuer_key":"local","hash":"zhashz","cache_size":1,"cache_capacity":10000}
{"logger":"events","msg":"event","name":"cached_managed_cert","id":"ba9d93bb-e983-4fc0-91ee-a82bbc1dea06","origin":"tls","data":{"sans":["10.0.0.128"]}}
{"logger":"tls.handshake","msg":"loaded certificate from storage","remote_ip":"y.y.y.y","remote_port":"51584","subjects":["10.0.0.128"],"managed":true,"expiration":1680623841,"hash":"zhashz"}

{"logger":"tls.handshake","msg":"choosing certificate","identifier":"10.0.0.128","num_choices":1}
{"logger":"tls.handshake","msg":"default certificate selection results","identifier":"10.0.0.128","subjects":["10.0.0.128"],"managed":true,"issuer_key":"local","hash":"zhashz"}
{"logger":"tls.handshake","msg":"matched certificate in cache","remote_ip":"y.y.y.y","remote_port":"58764","subjects":["10.0.0.128"],"managed":true,"expiration":1680623841,"hash":"zhashz"}

```

Note that the identifier and SAN (Subject Alternative Name) is the Internal IP (10.0.0.128) of the server not the External(x.x.x.x)
And the Error with the TLS Handshake is that the target host name is x.x.x.x does not match the target on the certificate
caddy succeed in issuing the certificate but to the wrong IP. so the TLS fails and curl can't get a valid responde and I can't open the IP in my browser, I get ERR_CERT_COMMON_NAME_INVALID

when I call `curl -v  https://my-domain.org' --cacert root.crt`
I get a successful response from every machine I use and I can omit `--cacert root.crt` flag as long as I installed the root CA in the machine
Also Caddy Logs:
```
{"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"my-domian.org"}
{"logger":"tls.handshake","msg":"all external certificate managers yielded no certificates and no errors","remote_ip":"y.y.y.y","remote_port":"47028","sni":"my-domian.org"}
{"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [my-domian.org]: no OCSP server specified in certificate","identifiers":["my-domian.org"]}
{"logger":"tls.cache","msg":"added certificate to cache","subjects":["my-domian.org"],"expiration":1680623296,"managed":true,"issuer_key":"local","hash":"zhashz","cache_size":2,"cache_capacity":10000}
{"logger":"events","msg":"event","name":"cached_managed_cert","id":"850c0240-8874-42f5-9e76-de755a407cc7","origin":"tls","data":{"sans":["my-domian.org"]}}
{"logger":"tls.handshake","msg":"loaded certificate from storage","remote_ip":"y.y.y.y","remote_port":"47028","subjects":["my-domian.org"],"managed":true,"expiration":1680623296,"hash":"zhashz"}

{"logger":"tls.handshake","msg":"choosing certificate","identifier":"my-domian.org","num_choices":1}
{"logger":"tls.handshake","msg":"default certificate selection results","identifier":"my-domian.org","subjects":["my-domian.org"],"managed":true,"issuer_key":"local","hash":"zhashz"}
{"logger":"tls.handshake","msg":"matched certificate in cache","remote_ip":"y.y.y.y","remote_port":"35686","subjects":["my-domian.org"],"managed":true,"expiration":1680623296,"hash":"zhashz"}
```

in this case the identifier and SAN (Subject Alternative Name) is the domain name and caddy successfully issued a valid certificate and the host accpepted it.
I can even open the domain is browser and I won't get a TLS Warning.

So how can I tell caddy to issue the IP Certificate with External IP of my Server ?

also one Additional test I made is to call curl from the server itself.
when I call `curl -v  https://x.x.x.x' from the same server 
I get a successful response 

and Caddy logs:
```
{"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"x.x.x.x"}
{"logger":"tls.handshake","msg":"all external certificate managers yielded no certificates and no errors","remote_ip":"x.x.x.x","remote_port":"34742","sni":""}
{"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [x.x.x.x]: no OCSP server specified in certificate","identifiers":["x.x.x.x"]}
{"logger":"tls.cache","msg":"added certificate to cache","subjects":["x.x.x.x"],"expiration":1680622859,"managed":true,"issuer_key":"local","hash":"zhashz","cache_size":3,"cache_capacity":10000}
{"logger":"events","msg":"event","name":"cached_managed_cert","id":"c16e38f7-2d31-4baf-8100-bf30dcd55020","origin":"tls","data":{"sans":["x.x.x.x"]}}
{"logger":"tls.handshake","msg":"loaded certificate from storage","remote_ip":"x.x.x.x","remote_port":"34742","subjects":["x.x.x.x"],"managed":true,"expiration":1680622859,"hash":"zhashz"}

{"logger":"tls.handshake","msg":"choosing certificate","identifier":"x.x.x.x","num_choices":1}
{"logger":"tls.handshake","msg":"default certificate selection results","identifier":"x.x.x.x","subjects":["x.x.x.x"],"managed":true,"issuer_key":"local","hash":"zhashz"}
{"logger":"tls.handshake","msg":"matched certificate in cache","remote_ip":"x.x.x.x","remote_port":"34746","subjects":["x.x.x.x"],"managed":true,"expiration":1680622859,"hash":"zhashz"}
```

this is weird behavior, in this case it used the identifier and SAN of the external IP correctly and the issued certificate is valid

**Comment by francislavoie** [comment]
The problem is that clients don't send IP addresses in SNI, because the SNI spec explicitly states literal IP addresses can be used in SNI. See https://www.rfc-editor.org/rfc/rfc4366#section-3.1

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

This means that the only thing Caddy can do is guess the name to use, and that guess may be wrong. So for those specific IP addresses, you won't be able to use `on_demand` to manage them, because that's how on-demand works, it looks at the name in SNI.

You'll need to have Caddy issue certs for that hostname up-front, by making a site block with that IP address (and without `on_demand`).

**Comment by Lan-Hekary** [comment]
when I used `default_sni` with x.x.x.x
Caddy Logged
```
{"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"10.0.0.128"}
{"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"x.x.x.x"}
```
and the proceeded to use 10.0.0.128 anyway.
the Problem is that it didn't add it the SAN Field if I defined the `default_sni`

**Comment by Lan-Hekary** [comment]
> You'll need to have Caddy issue certs for that hostname up-front, by making a site block with that IP address (and without `on_demand`).".

when I tried this it worked correctly.

**Comment by francislavoie** [comment]
Correct, when using IP certs. That's just how it works, unfortunately. Which is why it's much better to use actual domains.

**Comment by Lan-Hekary** [comment]
OK, thanks.

just to be clear.
it only works if I use `default_sni` and a site block with IP.

if I use an IP site block without `default_sni` it does not work.
is this normal behavior ?

**Comment by francislavoie** [comment]
Yes, because SNI is empty otherwise.
