### ISSUE TITLE
[Question] Load balancing

### ISSUE THREAD

**Issue by Z3NTL3** [caddyserver/caddy#5480]
i've read: ``https://caddyserver.com/docs/caddyfile/directives/reverse_proxy``

And i dont see any directive for sticky sessions

Does caddyserver do sticky sessions by default if not what directive to use, because from the documentation there is nothing about it?

**Comment by francislavoie** [comment]
Look at the `lb_policy` options. The `cookie` and `ip_hash` policies are sticky.

**Comment by Z3NTL3** [comment]
```
reverse_proxy :5000 :3000 {
    lb_policy least_conn
    header_up  Cookie {cookie.*}
}
```somethig like this is enough right?

**Comment by francislavoie** [comment]
That won't be sticky, no. `least_conn` only looks at the current connection count of each upstream, it doesn't take into account cookies. You need to use the `cookie` policy to make it sticky.

Also, `header_up Cookie` is unnecessary (and incorrect in this case), all headers are sent upstream by default.

**Comment by Z3NTL3** [comment]
so
``lb_policy cookie``

And because i didnt define cookie name and secret, it will not create a cookie right? if nothing was initialized etc, bcs i only want to upstream cookie when they are present

**Comment by francislavoie** [comment]
It will set the cookie in the response headers. But the cookie value will not be secured with HMAC, which means users could tamper with it.

**Comment by Z3NTL3** [comment]
> It will set the cookie in the response headers. But the cookie value will not be secured with HMAC, which means users could tamper with it.

is there a way to define a hmac function which is using sha512 instead of the fasting sha256 hmac hasher
