### ISSUE TITLE
Some metrics are not available in v2.6.4

### ISSUE THREAD

**Issue by ailichev** [caddyserver/caddy#5481]
Hi,
I see some metrics are not available in v2.6.4. For example caddy_http_request_errors_total, caddy_admin_*. Can you please check.
These are the available metrics:
`# curl http://caddy/metrics
# HELP caddy_http_request_duration_seconds Histogram of round-trip request durations.
# TYPE caddy_http_request_duration_seconds histogram
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.005"} 1220
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.01"} 1223
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.025"} 1225
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.05"} 1225
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.1"} 1225
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.25"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.5"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="2.5"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="5"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="10"} 1226
caddy_http_request_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="+Inf"} 1226
caddy_http_request_duration_seconds_sum{code="200",handler="subroute",method="GET",server="srv0"} 1.650583487999999
caddy_http_request_duration_seconds_count{code="200",handler="subroute",method="GET",server="srv0"} 1226
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.005"} 0
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.01"} 0
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.025"} 0
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.05"} 0
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.1"} 1
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.25"} 1
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.5"} 1
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1"} 1
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="2.5"} 3
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="5"} 3
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="10"} 3
caddy_http_request_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="+Inf"} 3
caddy_http_request_duration_seconds_sum{code="404",handler="subroute",method="GET",server="srv0"} 3.9053925009999997
caddy_http_request_duration_seconds_count{code="404",handler="subroute",method="GET",server="srv0"} 3
# HELP caddy_http_request_size_bytes Total size of the request. Includes body
# TYPE caddy_http_request_size_bytes histogram
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="256"} 1225
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1024"} 1225
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="4096"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="16384"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="65536"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="262144"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1.048576e+06"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="4.194304e+06"} 1226
caddy_http_request_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="+Inf"} 1226
caddy_http_request_size_bytes_sum{code="200",handler="subroute",method="GET",server="srv0"} 157502
caddy_http_request_size_bytes_count{code="200",handler="subroute",method="GET",server="srv0"} 1226
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="256"} 0
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1024"} 0
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="4096"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="16384"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="65536"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="262144"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1.048576e+06"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="4.194304e+06"} 3
caddy_http_request_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="+Inf"} 3
caddy_http_request_size_bytes_sum{code="404",handler="subroute",method="GET",server="srv0"} 9669
caddy_http_request_size_bytes_count{code="404",handler="subroute",method="GET",server="srv0"} 3
# HELP caddy_http_requests_in_flight Number of requests currently handled by this server.
# TYPE caddy_http_requests_in_flight gauge
caddy_http_requests_in_flight{handler="subroute",server="srv0"} 1
# HELP caddy_http_requests_total Counter of HTTP(S) requests made.
# TYPE caddy_http_requests_total counter
caddy_http_requests_total{handler="subroute",server="srv0"} 1229
# HELP caddy_http_response_duration_seconds Histogram of times to first byte in response bodies.
# TYPE caddy_http_response_duration_seconds histogram
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.005"} 1223
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.01"} 1224
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.025"} 1225
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.05"} 1225
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.1"} 1225
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.25"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="0.5"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="2.5"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="5"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="10"} 1226
caddy_http_response_duration_seconds_bucket{code="200",handler="subroute",method="GET",server="srv0",le="+Inf"} 1226
caddy_http_response_duration_seconds_sum{code="200",handler="subroute",method="GET",server="srv0"} 0.9505403580000004
caddy_http_response_duration_seconds_count{code="200",handler="subroute",method="GET",server="srv0"} 1226
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.005"} 0
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.01"} 0
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.025"} 0
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.05"} 0
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.1"} 1
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.25"} 1
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="0.5"} 1
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1"} 1
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="2.5"} 3
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="5"} 3
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="10"} 3
caddy_http_response_duration_seconds_bucket{code="404",handler="subroute",method="GET",server="srv0",le="+Inf"} 3
caddy_http_response_duration_seconds_sum{code="404",handler="subroute",method="GET",server="srv0"} 3.898196497
caddy_http_response_duration_seconds_count{code="404",handler="subroute",method="GET",server="srv0"} 3
# HELP caddy_http_response_size_bytes Size of the returned response.
# TYPE caddy_http_response_size_bytes histogram
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="256"} 0
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1024"} 0
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="4096"} 1224
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="16384"} 1225
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="65536"} 1226
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="262144"} 1226
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="1.048576e+06"} 1226
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="4.194304e+06"} 1226
caddy_http_response_size_bytes_bucket{code="200",handler="subroute",method="GET",server="srv0",le="+Inf"} 1226
caddy_http_response_size_bytes_sum{code="200",handler="subroute",method="GET",server="srv0"} 2.843855e+06
caddy_http_response_size_bytes_count{code="200",handler="subroute",method="GET",server="srv0"} 1226
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="256"} 0
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1024"} 0
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="4096"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="16384"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="65536"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="262144"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="1.048576e+06"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="4.194304e+06"} 3
caddy_http_response_size_bytes_bucket{code="404",handler="subroute",method="GET",server="srv0",le="+Inf"} 3
caddy_http_response_size_bytes_sum{code="404",handler="subroute",method="GET",server="srv0"} 8583
caddy_http_response_size_bytes_count{code="404",handler="subroute",method="GET",server="srv0"} 3
# HELP caddy_reverse_proxy_upstreams_healthy Health status of reverse proxy upstreams.
# TYPE caddy_reverse_proxy_upstreams_healthy gauge
caddy_reverse_proxy_upstreams_healthy{upstream="cms:8000"} 1
caddy_reverse_proxy_upstreams_healthy{upstream="lms:8000"} 1
caddy_reverse_proxy_upstreams_healthy{upstream="mfe:8002"} 1
caddy_reverse_proxy_upstreams_healthy{upstream="minio:9000"} 1
caddy_reverse_proxy_upstreams_healthy{upstream="minio:9001"} 1
# HELP go_build_info Build information about the main Go module.
# TYPE go_build_info gauge
go_build_info{checksum="",path="",version=""} 1
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.352e-05
go_gc_duration_seconds{quantile="0.25"} 6.6721e-05
go_gc_duration_seconds{quantile="0.5"} 0.000111622
go_gc_duration_seconds{quantile="0.75"} 0.000128962
go_gc_duration_seconds{quantile="1"} 0.014174643
go_gc_duration_seconds_sum 0.018225762
go_gc_duration_seconds_count 39
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 22
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.20"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 7.713608e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.86302224e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.48265e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1.538303e+06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 8.64272e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 7.713608e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 5.955584e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.019904e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 40237
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 3.64544e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 1.6154624e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.680905996411219e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 1.57854e+06
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 2400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 15600
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 134560
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 179520
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 1.0524224e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 555678
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 622592
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 622592
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.7653384e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 8
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 3.27
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 10
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 4.5395968e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.68090419491e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.69298432e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1225
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0`

**Comment by francislavoie** [comment]
See the release notes: https://github.com/caddyserver/caddy/releases/tag/v2.6.0 metrics are now opt-in.

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by ailichev** [comment]
@francislavoie , I know that metrics are now opt-in. I've enabled them in Global configuration as described in documentation:
`# Global configuration
{
  servers {
    metrics
  }
}`
It seems this is not usage question. It looks like a bug, because the middleware metric caddy_http_request_errors_total is not available. The rest of the middleware metrics are available.

**Comment by hairyhenderson** [comment]
There are other issues tracking the label problem @william-will-angi (search for "Prometheus" and/or "metrics") - and if the ordering is a bug, please open a bug report about that

**Comment by francislavoie** [comment]
@william-will-angi I'm sure ordering is not a problem here. https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm
