### ISSUE TITLE
Can't access via IP address

### ISSUE THREAD

**Issue by YongChingShieh** [caddyserver/caddy#5483]
I use caddy automatic HTTPS, which cannot be accessed through IP addresses, such as http://ip or https://ip, only accessible through domain names. This is caddyfile

``` 
www.xxx.com  {
        # Set this path to your site's directory.
        root * /usr/share/caddy
        # Enable the static file server.
        file_server
        # Another common task is to set up a reverse proxy:
        # reverse_proxy localhost:8080
 @v2ray_websocket {
        path /proxy
        header Connection Upgrade
        header Upgrade websocket
    }
    reverse_proxy @v2ray_websocket localhost:8080
        # Or serve a PHP site through php-fpm:
        # php_fastcgi localhost:9000
}
```

**Comment by francislavoie** [comment]
That's normal. ACME issuers don't allow IP certs. And HTTPS clients verify that the name in the cert matches what it requested. If you make a request that doesn't match what the server has, then it doesn't work.

**Comment by Paradoxis** [comment]
@francislavoie I don't understand why this isn't a feature (or at least clearly documented). Why am I forced to use an ACME provider? The whole reason I personally use Caddy is for the automatic SSL magic without having to go through the effort of generating certs. 

I spent an hour debugging why my OpenSSL is broken, just to figure out that specifying an IP is not allowed. This really **does** seem like a bug to me. Either Caddy should generate a self-signed SSL cert (if configured to do so), or throw an error whilst validating the Caddyfile if the specified host is an IP address.

This current mode is very frustrating to deal with and should be reconsidered as a bug in my opinion

**Comment by francislavoie** [comment]
@Paradoxis you haven't shared any details about what you're trying. I can't help without making assumptions, and that's not a good use of our time or yours.

Please don't comment on long-since-closed issues.
Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by mholt** [comment]
@Paradoxis 

> Why am I forced to use an ACME provider? The whole reason I personally use Caddy is for the automatic SSL magic without having to go through the effort of generating certs.

You don't have to use an acme provider. If you put an IP address in your Caddyfile, Caddy will automatically provision its own certificate internally for it.
