### ISSUE TITLE
[Bug?] Caddy as reverse proxy forwards incorrect Content-Length header

### ISSUE THREAD

**Issue by nick-ge** [caddyserver/caddy#5485]
Dear Caddy maintainer,

I've found a minor issue: 
When Caddy, configured as a reverse proxy, receives a `GET` request with a `Content-Length` header specifying a size bigger than the actual body, it forwards this request without correcting the `Content-Length` header. This offers room for an attack vector named HTTP request smuggling. Furthermore, the behavior in such a scenario is also covered by the [latest RFC](https://www.rfc-editor.org/rfc/rfc9110#section-8.6-11) which expects to correct the header according the actual content size.

## Demo

Here a little demonstration of the problem. In short I've used the following setup:

- The [latest Caddy image](https://hub.docker.com/layers/library/caddy/2.6.4/images/sha256-5acae6b87b26a591d6d14ec2704b7f2cd94b888ad62af16a02356d3124198ede?context=explore) configured as a reverse proxy. Incoming requests are forwarded to a dummy backend. The configuration is down below.
- A dummy backend which simply prints out the received content.

Consider the following request:
```
GET / HTTP/1.1
Host: localhost
X-Project-ID: 132-poc_client
Connection: close
Content-Length: 100

3
abc
0
```

Here the `Content-Length` value does not match with the actual size of the content. Sending this request to the Caddy is accepted:
![image](https://user-images.githubusercontent.com/52545766/231141166-dbb0b527-25fd-41db-9194-89da992c069f.png)

This is what the backend has received from Caddy:
![image](https://user-images.githubusercontent.com/52545766/231141415-2d66eef2-85fb-4e37-9cb8-510fc6424f90.png)

As you can see, the wrong `Content-Length` header and the message body are forwarded. However, it is expected that the value of `Content-Length` is corrected according to the actual content.

### Impact

This could have severe impact because of request smuggling, in case Caddy would accept and transmit the `Transfer-Encoding` in addition to the wrong `Content-Length` header. However, I've tested that and Caddy correctly removes the wrong `Content-Length` in case both are available in a request:
![image](https://user-images.githubusercontent.com/52545766/231143619-1e49256d-0c1d-4eff-a4bc-e640273d5af6.png)

The request the backend has received:
![image](https://user-images.githubusercontent.com/52545766/231143725-5d4b2a73-e3c3-4bae-a993-b13399dd4a84.png)

However, I would consider the mentioned behavior still as a bug as the RFC [defines](https://www.rfc-editor.org/rfc/rfc9110#section-8.6-12) how to behave in those situations.

### Limit

This behavior seems flaky. Sometimes the body is sent along, sometimes no body was sent at all as in the screenshot below:
![image](https://user-images.githubusercontent.com/52545766/231142972-6943b0a0-f3b7-47b0-bdb7-a947fab9fcd2.png)

## Configuration files

Here are my configs:

Caddy's docker-compse:
```
---
version: "3.8"

services:

  poc_caddy:
    container_name: "poc_caddy"
    image: caddy:2.6.4
    ports:
      - "0.0.0.0:8105:80"
    volumes:
      - "./config/Caddyfile:/etc/caddy/Caddyfile:ro"
    networks:
      testbed:
        ipv4_address: 10.10.10.105

networks:
  testbed:
    external: true
```
Here a external network was used, which needs prior configuration. However, this is not needed.

Caddyfile:
```
# Configuration block for site 0.0.0.0:80
:80 {
	# Proxy to backend
	reverse_proxy http://backend:80
}
```

For the backend you can use simply every image. Just make sure you to name the container `backend` as stated in the Caddyfile and be attached in the same network as Caddy. From within the backend simply call netcat or something else.

If I am missing something, please let me know! Otherwise I am glad if a can contribute to your amazing project!

King regards
Nick

**Comment by francislavoie** [comment]
Caddy doesn't buffer the request body by default, so it has no way to know the real length of the request body. Request headers must be written before writing the body (when sending it upstream), so it's impossible to read the body to correct the length without buffering it. Caddy simply streams the body to the upstream with `io.Copy()`. It's the responsibility of the upstream app to check for correctness of the content length, since only it has the request body buffered (if it's an endpoint that supports buffering).

> This behavior seems flaky.

I don't understand. That doesn't make sense. Can you elaborate?

**Comment by nick-ge** [comment]
Hey @francislavoie,

thank you for your fast response. I see your point. This makes sense then.

>  I don't understand. That doesn't make sense. Can you elaborate?
This issue was related to my test setup, so never mind. Sorry about that.
