### ISSUE TITLE
Update file server JavaScript MIME type

### ISSUE THREAD

**Issue by aentwist** [caddyserver/caddy#5489]
## Description

The latest standard for JavaScript MIME type is defined by [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239.pdf), published in May 2022. The MIME type for JavaScript (and module files) is defined to be `text/javascript`.

> #### [6.1.1. text/javascript](https://www.rfc-editor.org/rfc/rfc9239.pdf#name-text-javascript)

<blockquote>

Additional information:

&nbsp;&nbsp;&nbsp;&nbsp;Deprecated alias names for this type:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;application/javascript, [...]

&nbsp;&nbsp;&nbsp;&nbsp;[...]

&nbsp;&nbsp;&nbsp;&nbsp;File extension(s): .js, .mjs
</blockquote>

See also [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript), which reflects this.

Both .js and .mjs should be served with MIME type `text/javascript`. Currently this does not seem to be the case.

## Requirements

- [ ] .js is served with `Content-Type: text/javascript`
- [ ] .mjs is served with `Content-Type: text/javascript`
- [ ] nothing else is served with `Content-Type` `text/javascript`, `application/javascript`, or others
- [ ] the encoding module, and any others that have it, drops out application/javascript

**Comment by mohammed90** [comment]
The MIME of a file isn't managed by Caddy directly. It's picked up from your system, e.g. [mailcap](https://utcc.utoronto.ca/~cks/space/blog/linux/UbuntuMailcapBasics) on Linux and registry entries on Windows. To start including special cases for them opens up a can of worms. It's best for the systems to update their MIME mapping database.

**Comment by mholt** [comment]
Yeah; great suggestion, but agreed the proper fix is not in Caddy.
