### ISSUE TITLE
listen tcp :80: bind: address already in use

### ISSUE THREAD

**Issue by hccz95** [caddyserver/caddy#5493]
### 1. What version of Caddy are you using (`caddy -version`)?

v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

custom built with `alidns` and `cloudflare`

### 2. What are you trying to do?

See Caddyfile following. I want to use `https://mydomain:9528/` to access a web service (`http://localhost:7500`) on my router.

### 3. What is your entire Caddyfile?

```Caddyfile
mydomain:9528 {
	tls {
		dns alidns {
			access_key_id xxxxxx
			access_key_secret xxxxxx
		}
	}
	reverse_proxy localhost:7500
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```bash
./caddy_linux_mipsle_custom run
```

### 6. What did you expect to see?

Successful access to `localhost:7500` on remote.

### 7. What did you see instead (give full error messages and/or log)?

```
root@Hiwifi:/plugins/crypt# ./caddy_linux_mipsle_custom run
2023/04/14 17:25:57.069 INFO    using adjacent Caddyfile
2023/04/14 17:25:57.103 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2023/04/14 17:25:57.108 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0x31fe960"}
2023/04/14 17:25:57.111 INFO    http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2023/04/14 17:25:57.115 INFO    http    enabling HTTP/3 listener        {"addr": ":9528"}
2023/04/14 17:25:57.115 INFO    tls     cleaning storage unit   {"description": "FileStorage:/root/.local/share/caddy"}
2023/04/14 17:25:57.116 INFO    failed to sufficiently increase receive buffer size (was: 176 kiB, wanted: 2048 kiB, got: 352 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2023/04/14 17:25:57.118 INFO    http.log        server running  {"name": "srv0", "protocols": ["h1", "h2", "h3"]}
2023/04/14 17:25:57.119 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0x31fe960"}
Error: loading initial config: loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use
```

In fact, the dashboard of my router is powered by nginx on **port 80**. But my Caddyfile does not involve port 80.

**Comment by IndeedNotJames** [comment]
`:80` is used for `http://` -> `https://` redirects.
See https://caddyserver.com/docs/automatic-https#effects
You can disable them using https://caddyserver.com/docs/caddyfile/options#auto-https

Also, in the future, please ask your question in the official forum at https://caddy.community instead.
This bug tracker is mostly meant for bug and feature requests -- not for usage questions :innocent:

**Comment by VuongNhatHien** [comment]
I simply run caddy stop and caddy start, everything works again!

**Comment by francislavoie** [comment]
@VuongNhatHien you should probably not be using `caddy start` in the first place. Check if your installation method ships Caddy as a service, in which case you should use that.
