### ISSUE TITLE
Not all metrics are available unless metrics are globally enabled

### ISSUE THREAD

**Issue by willwill96** [caddyserver/caddy#5501]
I have a repro available here: https://github.com/willwill96/caddy-metrics-issue-repro -- just docker build and run

With the following Caddyfile, I do not see any of the http middleware metrics (i.e. `caddy_http_requests_in_flight`):
```
{
    auto_https off
}

:3000 {
    metrics /metrics
    file_server
}
```

If I update to the following, it works as expected:

```
{
    auto_https off
    servers {
        metrics
    }
}

:3000 {
    metrics /metrics
    file_server
}
```

**Comment by IndeedNotJames** [comment]
Note that [`metrics` directive docs](https://caddyserver.com/docs/caddyfile/directives/metrics) explicitly state at the top of the page:

> Configures a Prometheus metrics exposition endpoint so the gathered metrics can be exposed for scraping. **Metrics must be [turned on in your global options](https://caddyserver.com/docs/caddyfile/options#metrics) first.**

>
