### ISSUE TITLE
How to add moudle in  download-page  ？

### ISSUE THREAD

**Issue by zuohuadong** [caddyserver/caddy#5502]
When I install "https://github.com/greenpau/caddy-git" ,  it appears: 

![image](https://user-images.githubusercontent.com/11203929/233225736-92200891-8018-4b37-92d4-4f74c1cc5593.png)

And this project hasn't had a PR merge for a long time.

I want to add my module, how do I add it?

see：

https://github.com/zuohuadong/caddy-git

**Comment by mholt** [comment]
This is a known problem, unfortunately. We have workarounds.

But I'm wondering why the big red banner explaining this is not showing for you?

![image](https://user-images.githubusercontent.com/1128849/233252998-def63655-73ae-44ce-84e5-711ebd25a6f0.png)

Make sure your cache is clear? (But we've had the banner for a long time now.)
