### ISSUE TITLE
Wildcard tls internal not working

### ISSUE THREAD

**Issue by marouamghar** [caddyserver/caddy#5511]
Basically, when using a domain for local networking, trying to set up tls internal with the wildcard domain doesn't work.
ex:
```
*.domain.test {
    tls internal
    @first host first.domain.test
    handle @first {...}
}
```
in the logs, it says *.domain.test is picked for automatic TLS certificate management, but when visiting the different hosts no certificate is added.
Are we obliged to use a DNS provider as tls issuer when using it with a wildcard doamin?

**Comment by francislavoie** [comment]
What do you mean by "no certificate is added"? What's in your logs, exactly? What do you see when you enable the `debug` global option?

**Comment by marouamghar** [comment]
For some reason, it wasn't working that time. I deleted all created config and started again, and it's able to correctly provide the wildcard cert to all websites specified there, so i think it's working as expected.
