### ISSUE TITLE
Caddy reverse proxy to docker container not working with iptables

### ISSUE THREAD

**Issue by learnerfulcrum** [caddyserver/caddy#5513]
Hi all,

Setup: 
- Caddy listening on 443/tcp on eth0 with public IP
- wg-easy is a docker-based web-ui for wireguard. It requires port 51821/tcp for HTTP interface and 51820/udp for actual wiregaurd traffic.
- wg-easy docker running on docker0 with the required ports exposed: (51821/tcp listening on 127.0.0.1 {don't want to expose the web-ui to the public} and 51820/udp listening on 0.0.0.0)

Situation:
- Caddy (listening on 443/tcp on eth0, public IP) proxies fine to services running on eth0 or loopback if I have the right iptables rules in the INPUT chain. 
- I can talk to wg-easy (without Caddy) over the internet as DOCKER-USER iptables chain allows all connections by default.

Issue:
- Caddy reverse proxy forwards connections to wg-easy (51821/tcp) when iptables INPUT chain policy is set to ACCEPT.
- This doesn't work anymore if I set the INPUT policy to DROP; even if I explicitly allow traffic to 443 using `iptables -I INPUT -s ALLOWED_IP -p tcp --dport 443 -j ACCEPT'. 

Goal:
- wg-easy HTTP interface is plain-text. I want to protect the web-ui traffic by using Caddy as an HTTPs reverse proxy. This works great when iptables INPUT policy is set to ACCEPT.
- I want this same solution to work with INPUT policy set to DROP.

**Comment by francislavoie** [comment]
This doesn't really seem like an issue with Caddy. It sounds like a Docker + iptables issue. I don't think we can really help with that. Caddy isn't doing anything special at all when dialing an upstream.
