### ISSUE TITLE
HTTP3 not working / listen UDP

### ISSUE THREAD

**Issue by alwismt** [caddyserver/caddy#5514]
I am encountering an issue with my Caddy installation.

```
caddy version
2943c41884278ec5fc44bcb55d2b9b088838cdc2+modified (24 Apr 23 16:36 UTC)
```

I have installed the latest release from GitHub using xcaddy and have noticed that HTTP3 does not work for `IPv4` and `IPv6`. When I try to access my website via IPv4 and IPv6 HTTP3 does not work. When I ran the command `netstat -tulpn | grep caddy`, it printed udp6 but no udp neither say LISTEN. tcp says LISTEN The output of this command is:

```
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      4397/caddy          
tcp6       0      0 :::80                   :::*                    LISTEN      4397/caddy          
tcp6       0      0 :::443                  :::*                    LISTEN      4397/caddy          
udp6       0      0 :::443                  :::*                                4397/caddy    
```

I have already opened the UDP port 443 from Digital Ocean and from Ubuntu UFW, but Caddy does not seem to be listening to UDP. Can you please guide me on how to tell Caddy to listen to UDP (IPv4 /IPv6) as well? My server is hosted on Digital Ocean.

When i do curl it’s not even work for http3

```sh
curl -I --http3 https://(domain goes here):443
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   460    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Alt-Svc: h3=":443"; ma=2592000
Cache-Control: max-age=300
Content-Length: 460
Content-Type: text/html; charset=utf-8
Date: Sun, 30 Apr 2023 21:01:50 GMT
Server: Caddy
```

Also that when I tried accessing the website via Chrome browser, it would not load via H3 no matter how much I reloaded it.

I appreciate any help you can provide

**Comment by IndeedNotJames** [comment]
Hi! :)

> I have installed the latest release from GitHub using xcaddy

No, you are using an unreleased version/commit, straight from the master branch.
It's probably fine, but I wanted to clarify that you aren't using a release.
No idea what `xcaddy` command you ran.

> When I ran the command `netstat -tulpn | grep caddy`, it printed udp6 but no udp neither say LISTEN. tcp says LISTEN The output of this command is:

`udp6` with `::` listens on IPv4 as well.
And `udp` simply does not report `LISTEN`. That's to be expected. No issues there :)



> When i do curl it’s not even work for http3

That's worrying.
Your command output you shared seems a bit mangled, though.

I'd recommend sharing the output of
```
curl -I --http3 https://(domain goes here):443 -v
```

You can also pass the `QUIC_GO_LOG_LEVEL=info` environment variable to `caddy` and check the logs, to see if any of your (new) requests show up in the stdout logs.

**Comment by francislavoie** [comment]
Cross-referencing, this was asked on the forums as well https://caddy.community/t/http3-not-working-udp/19793.

I recommend using `docker run -it --rm ymuski/curl-http3 curl -vs -D/dev/stdout -o/dev/null --http3 https://caddyserver.com` to test for HTTP/3 support, this seems to be the most reliable curl build I could find, and using Docker ensures it runs the same on any machine.

**Comment by mholt** [comment]
(Closing, unless this turns out to be a bug in Caddy, then we can reopen. Feel free to continue discussion!)
