### ISSUE TITLE
configuration setting for a loadbalancer and docs for embedding

### ISSUE THREAD

**Issue by ganeshkbhat** [caddyserver/caddy#5522]
I am trying to find the docs for 

1. the configuration settings for a loadbalancer using caddy. I have say 10 ports of mix of local 127.0.0.1:9001-9005 and remote 103.0.0.52 - 103.0.0.56
2. way to embed Caddy for usage into another project.

**Comment by mholt** [comment]
Hi, thanks for your questions! We typically leave this issue tracker reserved for actionable development items, and questions are more appropriate on our forums: https://caddy.community -- but I'll respond briefly here and close the issue, but we can continue discussion on the forums if necessary.

> the configuration settings for a loadbalancer using caddy. I have say 10 ports of mix of local 127.0.0.1:9001-9005 and remote 103.0.0.52 - 103.0.0.56

https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing


> way to embed Caddy for usage into another project.

In what way?

Typically what you'll do instead is embed the other project into Caddy, hence its modular [architecture](https://caddyserver.com/docs/architecture).
