### ISSUE TITLE
`://` in uri become `:/`

### ISSUE THREAD

**Issue by F-TD5X** [caddyserver/caddy#5524]
- Caddy: `v2.6.4`
- URI: `/https://example.org/foo/bar`
- Caddyfile:
```
localhost:80 {
        @real_endpoint path_regexp mypath /(\w+)(.*)
        rewrite @real_endpoint {re.mypath.1}{re.mypath.2}
        respond "{http.request.uri.path}"
}
```
```
localhost:80 {
        @real_endpoint path_regexp mypath /(\w+)(:/)(.*)
        rewrite @real_endpoint {re.mypath.2}
        respond "{http.request.uri.path}"
}
```

- response:
```
https:/example.org/foo/bar
```
```
:/
```
- logs:
```
2023/05/08 07:58:08.727 DEBUG   http.handlers.rewrite   rewrote request {"request": {"remote_ip": "127.0.0.1", "remote_port": "57001", "proto": "HTTP/1.1", "method": "GET", "host": "localhost", "uri": "/https://example.org/foo/bar", "headers": {"User-Agent": ["curl/7.87.1-DEV"], "Accept": ["*/*"]}}, "method": "GET", "uri": "https:/example.org/foo/bar"}
```

So the `://` in match group 2 to be like `:/`?

---

Also, `://` can't match `"://"`, but `:/` can match it as `":/"`. 🤔

--- 

So it may be something wrong of request handler? 
Or somewhere convert `////...` to `/`? If so, I think this behavior should update to docs, it's so easy to make mistakes.

**Comment by F-TD5X** [comment]
It seems caddy do convert `////...` to `/`.
Is it a designed behavior?

**Comment by francislavoie** [comment]
Yes, this is normal behaviour. We do path cleaning. You probably shouldn't pass a URL as a path, you should pass it as a query parameter instead. But you could use the `uri` directive's `path_regexp` replacement as a workaround, which doesn't clean after replacing: https://caddyserver.com/docs/caddyfile/directives/uri

**Comment by mholt** [comment]
For more info, see the release notes of Caddy 2.6: https://github.com/caddyserver/caddy/releases/tag/v2.6.0
