### ISSUE TITLE
match with "OR" option

### ISSUE THREAD

**Issue by git001** [caddyserver/caddy#5530]
there are several questions on the caddy community site to be able to use match blocks with `OR`.

How about to add the keyword `OR` into the mach logic [Request Matchers](https://caddyserver.com/docs/caddyfile/matchers) or could this be solved with the [expression](https://caddyserver.com/docs/caddyfile/matchers#expression) matcher?

**Comment by francislavoie** [comment]
The solution is to use the expression matcher. I gave a talk about this going in more detail https://youtu.be/QSerOHpMjgY?t=10m41s
