### ISSUE TITLE
`handle_errors` doesn't catch error codes omitted by `respond`

### ISSUE THREAD

**Issue by lemniskett** [caddyserver/caddy#5537]
Hi, my goal is to send a custom 403 page for files inside `private` directory, I have the following Caddyfile:
```
domain.tld {
  root * /var/www/html
  file_server
  handle_errors {
    rewrite * /{err.status_code}.html
  }
  @forbidden {
    path /private/*
  }
  respond @forbidden 403
}
```

My expectation is that `handle_errors` will act like a try catch exception and `respond` act like throw exceptions, so that Caddy will respond with the content of /403.html, but instead when I visit https://domain.tld/private/test.png Caddy respond with blank 403 page. 

Is this the intended behavior? if so, how can I achieve my goal?

**Comment by francislavoie** [comment]
This is intended. Use the `error` directive instead. http://localhost:8881/docs/caddyfile/directives/error
