### ISSUE TITLE
ETag headers explicitly set in configuration should be honored rather than overridden

### ISSUE THREAD

**Issue by charles-dyfis-net** [caddyserver/caddy#5546]
The mtime+size pattern used to calculate default etags by Caddy is only useful in situations where mtime is accurate. This isn't always the case: Some build systems (notably [Nix](https://nixos.org/)) coerce all times to 1970-01-01 for better reproducibility.

Right now, however, any etag that might be set by other configuration or modules is overwritten by the default mtime+size etag when caddy is serving requests. This makes Caddy deeply unreliable for serving files built with Nix, as it inaccurately instructs client browsers that contents are unchanged whenever subsequent builds have identical file sizes.

If the customer deploying caddy has a better identifier (such as the overall hash of the filesystem tree being served), they should be able to configure an ETag header using that identifier and let it be honored.

**Comment by mholt** [comment]
I see from your commit that it looks like you propose that if the Etag header is already set on the response, to use that, and only set an Etag if not present.

I think that seems reasonable. Want to make a PR?

**Comment by charles-dyfis-net** [comment]
> I think that seems reasonable. Want to make a PR?

Incoming momentarily!

> PS. How _are_ you setting the Etag header yourself?

I'm using Nix to generate my Caddy config file, just as I'm using it to generate the content being served. All content built by Nix has a hash included in its file location (`/nix/store/<hash>-<name>-<version>/...`), so one could extract the hash from the path, or hash the name of the directory itself, or do several other such things.
