### ISSUE TITLE
Consider dropping ETag, Last-Modified-Time generation for files where epoch <= mtime <= epoch+1

### ISSUE THREAD

**Issue by charles-dyfis-net** [caddyserver/caddy#5548]
#5547, as a fix for #5546, makes it _possible_ to override caddy's default ETag generation.

That said, I'd like to suggest considering making that ETag generation conditional in the first place.

Not letting clients do caching at all is a better failure mode than encouraging clients to cache things that aren't safely cacheable. When content doesn't have a meaningful mtime, generating an ETag off that mtime leads to absurd results (effectively, leaving file size as the only cache-invalidation key). As a special case, an mtime of 0 or 1 (as measured in seconds-since-UNIX-epoch) is clearly not meaningful.

On its own, the existing PR makes it possible for the administrator of a system where mtimes are not meaningful to instruct Caddy to do something different instead.

If we implemented a safeguard such as that proposed here in addition to that PR, then the default for administrators who failed to take the actions enabled by that PR would be less harmful -- more client requests, rather than clients using out-of-date data.

**Comment by mholt** [comment]
Does `header -Etag` and `header -Last-Modified` do what you're looking for?

**Comment by charles-dyfis-net** [comment]
Yes, it does, if one uses `defer` on the Etag one.

The tricky part -- the reason I filed this ticket -- is trying to reduce the pitfall left for users who don't realize that they need any such configuration or clause for correct out-of-the-box function.

**Comment by mholt** [comment]
The defer is automatic/implied with `-` (removal). :+1:
