### ISSUE TITLE
Question: How do I Generate a Self-signed Certificate using a domain name?

### ISSUE THREAD

**Issue by Gu-f** [caddyserver/caddy#5549]
I don't have a dns server available, so I appended a mapping to the hosts file for testing purposes.  
like this:  
192.168.89.51 test.mytestserver.dev  
So I want to use caddy to generate a self-signed certificate for test.mytestserver.dev  
But when I wrote the domain name in the caddyfile it applied for the publicly trusted certificate. for example through Let's Encrypt.  
But i want to generate by pki.ca.local....  
thanks

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

You're looking for `tls internal`. See the docs: https://caddyserver.com/docs/caddyfile/directives/tls

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
