### ISSUE TITLE
i can't have caddy serve files while requiring   upstream server  to authenticate 

### ISSUE THREAD

**Issue by david-macharia** [caddyserver/caddy#5566]
The problem is i need caddy to first check the file authorisation from the proxy_server and if the upstream server respond with the 200 status,it serve the file in the give root path else sends back an authenticated.can't get  the expression tap status 200

`:23010 {

 handle_path /cdn/* {
        rewrite * /media/authentication{path}
        reverse_proxy http://172.18.0.41:50000

     handle {
            @proxy200 {
                expression {http.response.status} == 200
            }

            respond @proxy200 "Authenticated!" 200
        }
             root * /home/david/resource-server/files
        file_server

 }

    root * /home/david/resource-server/files
    try_files {path}

    file_server
}`

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
