### ISSUE TITLE
Need help with serving the bundled script of React.js

### ISSUE THREAD

**Issue by pd-pranay** [caddyserver/caddy#5570]
Bundled script and css files keeps loading, script that resides inside the head tag of html file, @francislavoie Can you help me with the issue ?
Example: ( /assets/index.901dfab3.js)

`
# Dockerfile:
// Stage 1: Build React application 
...

// Stage 2: Serve React application with Caddy
FROM caddy:latest
COPY --from=build /app/frontend/dist /srv
`

`
# docker-compose.yml
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/caddy/Caddyfile:/etc/caddy/Caddyfile
`

`
# Below is the Caddyfile
{
    email ##@##.com
     # only for testing purpose
     acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
    servers {
        timeouts {
                read_body   2m
                read_header 2m
                write       2m
                idle        5m
        }
    }
}

test.example.com {
   # api
    handle /api/* {
        reverse_proxy backend_api:4000 {
            transport http {
                read_timeout 1m
                write_timeout 1m
            }
        }
    }
    # react app
    handle /* {
        root * /srv
        file_server 
        try_files {path} /index.html
    }
}
`

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
