### ISSUE TITLE
.local with internal acme server

### ISSUE THREAD

**Issue by BenjaminHae** [caddyserver/caddy#5571]
I use .local internaly and have setup an internal acme server to rollout tls certificates for my internal environment.

Currently, caddy uses the local PKI for all `.local` hosts. 

Is it possible to force the usage of my internal ca?

**Comment by francislavoie** [comment]
Yes, just configure your ACME server with the `tls` directive (the `ca` option): https://caddyserver.com/docs/caddyfile/directives/tls

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
