### ISSUE TITLE
Cannot enable older ciphers in both v2.6.4 and v2.7.0-beta.1

### ISSUE THREAD

**Issue by sunib** [caddyserver/caddy#5575]
I'm trying (but failing) to enable some of the 'older' ciphers as documented in the [tls directive](https://caddyserver.com/docs/caddyfile/directives/tls#ciphers).

I've tried both v2.6.4 and v2.7.0-beta.1, and both on a Windows (win11) and a Linux machine (EndavourOS).

The `Caddyfile`:

```
localhost:5009

tls {
	ciphers TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256
}

respond "Yes you have a connection"
```

And then running `nmap --script ssl-enum-ciphers -p 5009 localhost` which gives as output:
```
Starting Nmap 7.92 ( https://nmap.org ) at 2023-06-15 10:19 W. Europe Daylight Time
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00s latency).
Other addresses for localhost (not scanned): ::1
rDNS record for 127.0.0.1: kubernetes.docker.internal

PORT     STATE SERVICE
5009/tcp open  airport-admin
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|     compressors:
|       NULL
|     cipher preference: server
|   TLSv1.3:
|     ciphers:
|       TLS_AKE_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_AKE_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_AKE_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|     cipher preference: server
|_  least strength: A
```

Things I did:
* I've played a bit with it and I can only 'toggle' the three default ciphers. The others mentioned in the docs are accepted as settings but don't get outputted.
* I'm aware that I only should be able to influence tls v1.2, tls v1.3 has a fixed set of ciphers.
* I've tried to disable tls1.3 (does not make a difference)
* I've tried to make a deliberate typo in the by-default-disabled ciphers. That's picked up and throws an error.
* This also happens in a bigger Caddyfile which is running on a real domain: [ssllabs ssltest](https://www.ssllabs.com/ssltest) also does never show any of the older ciphers.

So I'm scratching my head on this one, any good other suggestions or did I find a bug?

**Comment by mholt** [comment]
I seem to believe that only ciphers matching the certificate's signature can be used. Does that help explain it?

**Comment by sunib** [comment]
Thank you for this good hint @mholt. The way I'm understanding it now is that the Cipher name reflects the key compatibility.

Pattern: `TLS_{KEY1}_{OPTIONAL_KEY2}_WITH_{HASH?}`

So in my example above:
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256

It made perfect sense that only the first two are shown since the default key in Caddy is not an RSA key.

In my specific situation, I have a great need for good support for old clients: so I've regenerated my certificate with rsa2048 (note for future readers that you need to remove the old certificate by hand). Some [background info](https://sectigostore.com/blog/ecdsa-vs-rsa-everything-you-need-to-know/#:~:text=Compared%20to%20RSA%2C%20ECDSA%20is,to%20the%20prime%20factorization%20method.) that helped me in making this choice. Given the arguments, as I understand them, I also fully agree that Caddy is not using RSA by default. But I do appreciate it's an option to be a bit more conservative.

It all works for me now. thanks for the help: this is not a bug (although it could make a very cool feature to throw a good error message when someone tries to configure an incompatible cipher).
