### ISSUE TITLE
arm64  docker  setting  gzip 

### ISSUE THREAD

**Issue by huanmengerkong** [caddyserver/caddy#5577]
msg=using provided configuration config_file=/etc/caddy/Caddyfile config_adapter=caddyfile
Error: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized directive: gzip

hudiej.com {
    gzip {
        level 1
        not   /images /videos
    }
    root /srv/test
    log /srv/logs/example_access.log
}

**Comment by huanmengerkong** [comment]
There are too many problems in arm docker. I suggest you clean it up.

**Comment by francislavoie** [comment]
You're using Caddy v1 syntax. Please review the docs. https://caddyserver.com/docs/caddyfile/directives/encode
