### ISSUE TITLE
Possible issue with parsing Caddyfile in 2.7.0-beta.1

### ISSUE THREAD

**Issue by LennartKoot** [caddyserver/caddy#5578]
We are currently trying out `v2.7.0-beta.1` of Caddy and are running into a problem where our Caddyfile now errors out, while on `v2.6.4` everything is working fine.

```
Error: adapting config using caddyfile: parsing caddyfile tokens for 'jwtauth': Caddyfile:7 - Error during parsing: unrecognized option: jwk_url
```

To check if there might be a problem with the plugins used itself, and not Caddy, we have tried some different builds of Caddy using `xcaddy` with a minimal Caddyfile using `jwtauth` and then running `caddy validate` on the file:

```
{
	order jwtauth before basicauth
}

localhost {
	jwtauth {
		jwk_url http://localhost/.well-known/jwks.json
	}
}
```

We have two plugins enabled, `ggicci/caddy-jwt` and `caddy-dns/azure`, and depending on how we build Caddy with xcaddy we get different results.

- `xcaddy build v2.6.4 --with github.com/ggicci/caddy-jwt --with github.com/caddy-dns/azure` -> OK
- `xcaddy build v2.7.0-beta.1 --with github.com/ggicci/caddy-jwt --with github.com/caddy-dns/azure` -> ERROR
- `xcaddy build v2.7.0-beta.1 --with github.com/ggicci/caddy-jwt` -> OK
- `xcaddy build v2.7.0-beta.1 --with github.com/caddy-dns/azure --with github.com/ggicci/caddy-jwt` -> ~~OK (different order)~~ BUILD ERROR

I would think that the order of importing plugins should not matter as they all handle their own directive. Am I missing something or did the new beta version introduce some bug in the parsing of a Caddyfile?

**Comment by LennartKoot** [comment]
We also ran into a similar problem as https://github.com/caddyserver/caddy/issues/5301 with the last command. Might the problem be related to that and Go not resolving dependencies correctly?

**Comment by LennartKoot** [comment]
I feel this is closed a bit quick. I don't understand why an outdated plugin would raise an error on a working plugin, in this case jwtauth. Can you shed some more light on that?

**Comment by francislavoie** [comment]
Go itself has bugs in the build tooling and dependency resolver. We've reported similar issues in the past. There's nothing we can do in Caddy itself. The only thing that can be done is adjusting the dependencies in the plugins themselves to resolve the dependency ambiguities.

**Comment by francislavoie** [comment]
FYI @kurokobo this is why I made those commits yesterday, to give you context. I'm still not able to build the azure plugin though, I think because the version of `azure-sdk-for-go` in use is much too old. That probably needs to be updated to the latest to fix the problem.

**Comment by LennartKoot** [comment]
Alright, thank you for the extra information and the quick replies!

**Comment by kurokobo** [comment]
Will check on this, give me some time please😌

**Comment by LennartKoot** [comment]
@kurokobo Awesome work, everything seems to be okay now!
