### ISSUE TITLE
Certificate cache is flushed when new config is loaded, causing downtime

### ISSUE THREAD

**Issue by LachlanArthur** [caddyserver/caddy#5589]
When a new config is sent to Caddy via the `/load` API endpoint, the certificate cache is immediately cleared and all certificates are reloaded from storage.

Any interim requests for sites that have not had their certificate loaded yet are immediately terminated with a TLS handshake error due to the missing certificate:

```json
{"level":"debug","ts":1687406195.5620813,"logger":"events","msg":"event","name":"tls_get_certificate","id":"d63de761-855f-4fcf-8ae4-c43e9178f045","origin":"tls","data":{"client_hello":{"CipherSuites":[49195,49199,49196,49200,52393,52392,49161,49171,49162,49172,156,157,47,53,49170,10,4865,4866,4867],"ServerName":"app.example.com","SupportedCurves":[29,23,24,25],"SupportedPoints":"AA==","SignatureSchemes":[2052,1027,2055,2053,2054,1025,1281,1537,1283,1539,513,515],"SupportedProtos":null,"SupportedVersions":[772,771],"Conn":{}}}}
{"level":"debug","ts":1687406195.5621786,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"app.example.com"}
{"level":"debug","ts":1687406195.562264,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"*.example.com"}
{"level":"debug","ts":1687406195.5622697,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"*.*.com"}
{"level":"debug","ts":1687406195.5622735,"logger":"tls.handshake","msg":"no matching certificates and no custom selection logic","identifier":"*.*.*"}
{"level":"debug","ts":1687406195.562279,"logger":"tls.handshake","msg":"all external certificate managers yielded no certificates and no errors","remote_ip":"141.101.69.95","remote_port":"24584","sni":"app.example.com"}
{"level":"debug","ts":1687406195.5622873,"logger":"tls.handshake","msg":"no certificate matching TLS ClientHello","remote_ip":"141.101.69.95","remote_port":"24584","server_name":"app.example.com","remote":"141.101.69.95:24584","identifier":"app.example.com","cipher_suites":[49195,49199,49196,49200,52393,52392,49161,49171,49162,49172,156,157,47,53,49170,10,4865,4866,4867],"cert_cache_fill":0.0001,"load_if_necessary":true,"obtain_if_necessary":true,"on_demand":false}
{"level":"debug","ts":1687406195.562434,"logger":"http.stdlib","msg":"http: TLS handshake error from 141.101.69.95:24584: no certificate available for 'app.example.com'"}
```

As we are running Caddy in a Docker Swarm of 12 nodes distributed across 3 regions, we needed a storage module. We tried MySQL and S3 before finally deciding on using a Docker volume backed by the rclone driver (to a B2 bucket), as this provided local caching on each node for fast reads.

The largest region in our swarm has 52 sites, so loading all their certificates from disk takes approximately 10-15 seconds. However, it was taking several minutes with the networked storage modules (S3, MySQL).

---

Caddy version: `v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=`

Modules:
- [lucaslorentz/caddy-docker-proxy/v2](https://github.com/lucaslorentz/caddy-docker-proxy)
- [caddy-dns/cloudflare](https://caddy-dns/cloudflare)
- [greenpau/caddy-security](https://greenpau/caddy-security)

<details>
<summary>Dockerfile</summary>

```Dockerfile
ARG CADDY_VERSION=2.6
FROM caddy:${CADDY_VERSION}-builder-alpine AS builder
RUN <<EOF
  set -eux;
  xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/greenpau/caddy-security \
  ;
EOF

FROM caddy:${CADDY_VERSION} AS caddy
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
CMD ["caddy", "docker-proxy"]
```
</details>

**Comment by LachlanArthur** [comment]
I just tried to replicate this on my home server, and the certificates load very quickly (0.5s to perform the entire `/load` call, which included reading 17 certificates).

There is likely some other issue causing the certificate reads to be very slow on our production servers.

Regardless of faster load time, I can still replicate the cache clearing issue.

I started a test Caddy instance with 50 sites, then used `ab` (Apache Benchmark) to hammer one of them and reloaded Caddy's config while the benchmark was running.

The requests begin to fail shortly after `enabling automatic TLS certificate management`.

<details>
<summary>Caddyfile</summary>

```Caddyfile
{
	debug
	acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
	skip_install_trust
}

(acme-cloudflare) {
	tls {
		issuer acme {
			dns cloudflare {env.CLOUDFLARE_API_TOKEN}
		}
	}
}

* {
	root * /config/_default
	tls internal
}

test-00.lach.la {
	log
	import acme-cloudflare
	respond "{host}"
}

test-01.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-02.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-03.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-04.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-05.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-06.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-07.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-08.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-09.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-10.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-11.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-12.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-13.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-14.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-15.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-16.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-17.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-18.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-19.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-20.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-21.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-22.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-23.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-24.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-25.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-26.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-27.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-28.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-29.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-30.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-31.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-32.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-33.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-34.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-35.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-36.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-37.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-38.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-39.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-40.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-41.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-42.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-43.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-44.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-45.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-46.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-47.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-48.lach.la {
	import acme-cloudflare
	respond "{host}"
}

test-49.lach.la {
	import acme-cloudflare
	respond "{host}"
}
```
</details>

<details>
<summary>Apache Bench output</summary>

```console
$ ab -c 10 -n 1000000 https://test-00.lach.la/

This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking test-00.lach.la (be patient)
SSL handshake failed (1).
008ECB68977F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1584:SSL alert number 80
SSL handshake failed (1).
008ECB68977F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1584:SSL alert number 80
[...]
```
</details>

[Caddy log](https://github.com/caddyserver/caddy/files/11833183/caddy.log) - trimmed from `admin.api received request /load` to `admin.api load complete`

**Comment by mholt** [comment]
> the certificate cache is immediately cleared and all certificates are reloaded from storage.

This is intentional. There is not really a way to do a config reload correctly without loading the certificates from storage (we have to pick up any changes from storage, and we can't rely on mod times).

I'm more concerned about the downtime you mention. There shouldn't be any downtime with a config reload -- there may be a period while certificates are unavailable until they are loaded, and this is a factor if your storage backend and machine are very slow to load certificates. [The very loud overwhelming majority of users](https://github.com/caddyserver/caddy/issues/1680) wanted the server to start even though usable certificates aren't available yet.

> We tried MySQL and S3 before finally deciding on using a Docker volume backed by the rclone driver (to a B2 bucket), as this provided local caching on each node for fast reads.
> The largest region in our swarm has 52 sites, so loading all their certificates from disk takes approximately 10-15 seconds. However, it was taking several minutes with the networked storage modules (S3, MySQL).

52 certificates is virtually nothing (many of our users load thousands of certs globally in just a few seconds). So, that does sound unusually slow. I don't think it's Caddy though: Caddy will load the certificates immediately and decode them. It's likely just slow infrastructure or it could be how the storage plugins are implemented, or both.

> We tried MySQL and S3 before finally deciding on using a Docker volume backed by the rclone driver (to a B2 bucket), as this provided local caching on each node for fast reads.

FYI: The most read-heavy thing the storage will do is load certificates, which are cached in memory.

Btw:

> `* {`

I'd need to double-check, but this might only match single-label domains, like `localhost`, not `example.com`, which would be `*.*`. Maybe double-check that that's working as expected. If not, try specifying a port instead; i.e. `:443`.

And you could probably combine your site blocks like so:

```
test-00.lach.la, 
test-01.lach.la,
...
test-49.lach.la {
	import acme-cloudflare
	respond "{host}"
}
```

With your level of infrastructure, I'd highly recommend [a sponsorship](https://github.com/sponsors/mholt) so that we can help you out in private where needed (I can't do much to help with redacted logs). We can work closer with a sponsorship to optimize your setup. For example, I suspect on-demand TLS could bring you valuable performance improvements if your storage can't go any faster.

**Comment by LachlanArthur** [comment]
Thanks for responding so quickly.

I agree with your points. I'll investigate the slow disk issue on our production servers.

So just to clarify, it's expected that Caddy will terminate TLS handshakes during the (very brief) period between reloading an unchanged config and the certificate being read from disk into the cache - even if that same certificate was in the cache previously?

The Caddyfile and log output in https://github.com/caddyserver/caddy/issues/5589#issuecomment-1602448341 aren't redacted (except for the log being trimmed to the relevant timeframe), it's exactly what I ran to verify the issue. I believe anyone should be able to replicate this downtime.

As an aside, using Caddy has been a pleasure, and reading through the source makes me want to learn Go.

**Comment by mholt** [comment]
> So just to clarify, it's expected that Caddy will terminate TLS handshakes during the (very brief) period between reloading an unchanged config and the certificate being read from disk into the cache - even if that same certificate was in the cache previously?

Hmm, yes and no.

When config is reloaded, the new server is started before the old one is stopped. The old one continues to serve requests until the new server is verified loaded and is ready to go. While this process doesn't wait for all the certificates to load, it does ensure that configuration is correct, listeners are ready, etc. And then the old server stops taking new requests and drains existing connections, while the new server starts accepting connections.

As far as I know, the vast majority of Caddy sites except for yours finish loading most if not all their certs into memory during this reload period, so by the time the new server starts taking requests, the certificates are already available in memory.

So, YES: in the sense that we don't block the reload for certificates to be decoded in memory.
But, NO: in the sense that storage backends aren't expected to be that slow.

Usually, when users have _lots_ of domains, they are using on-demand TLS, which defers cert loading until the first handshake that needs them. This is typically combined with the fact that they don't control those domains. You could potentially use on-demand TLS as a workaround, it's just not usually normal to use it when you control the domains.

Thanks for clarifying about redactions.

> As an aside, using Caddy has been a pleasure, and reading through the source makes me want to learn Go.

So glad to hear it :grin:

**Comment by mholt** [comment]
@LachlanArthur Could you try #5623 ? It should resolve your issue.

**Comment by LachlanArthur** [comment]
It's rock solid, no dropped handshakes at all during my local testing (>1k req/s while rapidly force-reloading the config).

Thank you so much!

**Comment by mholt** [comment]
Awesome, thanks! And no memory blowups?

**Comment by LachlanArthur** [comment]
Yeah, memory seems very stable - reloading the config in a tight loop doesn't cause any memory increase.

**Comment by mholt** [comment]
Excellent. Thanks so much for confirming. Will be merging that PR in a moment!
