### ISSUE TITLE
TLS health check on revers_proxy

### ISSUE THREAD

**Issue by chandrakanthkannam** [caddyserver/caddy#5590]
Hi Team, 

I have caddy running with version: `v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=` , and here is how the config looks, Caddyfile: 
```
reverse_proxy * https://<IP_address>:443 https://<IP_address>:443 {
  health_uri /
  health_port 8888
  health_timeout 10s
  health_status 200
  lb_policy uri_hash
  transport http {
    tls
    tls_insecure_skip_verify
    tls_except_ports 8888
  }
}
```

as you can see I'm using `reverse_proxy` module here to forward my incoming requests to the backend servers, the issue I'm facing is with the health checks to the backend, i have a health checker running on port `8888` and it needs to reached via http and not https, hence i used this config in `transport` block `tls_except_ports` hoping that connection would be non-tls, but still caddy tries to reach the health checker port via tls, here is a log snippet:

```
Jun 22 16:06:44 <backend> caddy[2247]: {"level":"info","ts":1687450004.2618585,"logger":"http.handlers.reverse_proxy.health_checker.active","msg":"HTTP request failed","host":"<IP_address>:8888","error":"Get \"https://<IP_address>:8888/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
```

can you please help me here if i'm missing something?

**Comment by francislavoie** [comment]
I see the problem, this is a legitimate bug.

**Comment by chandrakanthkannam** [comment]
Thank you @mholt  for pointing me to the community link, will have it saved for my future questions. 

Thank you very much @francislavoie for identifying it as a bug and having a fix out there, can't wait to upgrade the caddy version to the new one.

**Comment by mholt** [comment]
Thanks for catching something I overlooked, Francis.

And thanks for raising a question/issue @chandrakanthkannam :100:
