### ISSUE TITLE
encode * does not compress everything by default

### ISSUE THREAD

**Issue by AND51** [caddyserver/caddy#5593]
Hello!

This is my first bug report for Caddy. In short, `encode zstd gzip` which is equal to `encode * zstd gzip` does not encode everything. This is counterintuitive.

### 1a. Operating system and version
```
Ubuntu 22.04
```
### 1b. Caddy version (run `caddy version` or paste commit SHA)
This should be the latest version of Caddy:
```
v2.6.4
```

### 2a. What happens (briefly explain what is wrong)
Consider this situation. A htdocs folder with different files. A simple Caddyfile with `encode zstd gzip`. Well, if you request moon.gif, the response is not compressed. However, index.html will be compressed.
```bash
root@server:/srv/www# ls
moon.gif  index.html
root@server:/srv/www# cat /etc/caddy/Caddyfile
example.com {
  root * /srv/www
  file_server browse
  encode zstd gzip
}
root@server:/srv/www# wget -SO /dev/null https://example.com/moon.gif --compression=gzip
--2023-06-23 15:31:11--  https://example.com/
Resolving example.com (*****)... *****
Connecting to example.com (*****)|*****|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Alt-Svc: h3=":443"; ma=2592000
  Content-Length: 239851
  Content-Type: image/gif
  Etag: "rwpotn552j"
  Last-Modified: Fri, 23 Jun 2023 15:10:35 GMT
  Server: Caddy
  Date: Fri, 23 Jun 2023 15:24:20 GMT
Length: 239851 (234K) [image/gif]
Saving to: ‘/dev/null’

/dev/null                       100%[=======================================================>] 234,23K   231KB/s    in 1,0s    

2023-06-23 15:24:21 (231 KB/s) - ‘/dev/null’ saved [239851/239851]
```

### 2b. Why it's a bug (if it's not obvious)

The documentation states that omitting request matchers is the same as using a wildcard, so these two are equal:
```
encode zstd gzip
encode * zstd gzip
```
Source: See 'relevant links', source one.

With these, I expect the webserver to compress everything unconditionally. Obviously, Caddy compresses only certain file types.

It turns out that in the encode{}-block there is a directive "match" with some defaults. These defaults supersede my wish to encode everything, which I express with `encode * zstd gzip`. That's why I consider this a bug. In case that you don't agree, this is at least a contradiction within the documentation itself.

Source: See 'relevant links', source two.

### 2c. Log output
Not neccessary.

### 2d. Workaround(s)

In order to really compress everything, you must do this:
```
encode {
  zstd
  gzip 9

  match status 2xx
}
```
... or this (intentionally using long form):
```
encode {
  zstd
  gzip 9

  match {
    header Content-Type */*
  }
}
```

### 2e. Relevant links

"* to match all requests (wildcard; default)."
"If a matcher token is omitted, it is the same as a wildcard matcher (*)."
  ... see https://caddyserver.com/docs/caddyfile/matchers#syntax

"match is a response matcher. Only matching responses are encoded. The default looks like this: [code follows]"
... see https://caddyserver.com/docs/caddyfile/directives/encode#syntax

#

Some background information on this. On my server a cronjob regularly generates an animation, currently GIF (but I tried webp and APNG also). The server has a very poor upstream bandwidth. Moreover, the GIF is destined to be downloaded by mobile phones. Mobile phones often have low signal and/or poor bandwidth. All in all, this is a situation in which I try to sqeeuze the traffic as much possible. Formerly with Apache I simply did `SetOutputFilter DEFLATE`.
I agree that GIF, PNG, JPEG, etc. are compressed by nature. However, I am of the opinion that gzipping such content doesn't hurt and I don't like to be infantilized. It wastes very few cpu cycles. And even fewer cpu cycles once zstd becomes more popular.
Even if you do not agree with me, Caddy currently misses the opportunity to compress tar-files for example. Or any other content that is presumably not compressed (*.bmp, *.docx, ...). It will never be compressed as Caddys default only concentrates on `text/*`, `application/json javcascript xml` and `image/svg`.

**Comment by francislavoie** [comment]
This is working as intended.

The inline matcher argument is for _request_ matchers. Encoding does run for all requests. _But_, it does not encode all _responses_. The Content-Type header is a response header.

We set this to be a reasonable default because many types of content don't make sense to encode (e.g. images which are already compressed, video, etc). The `encode` directive documentation explains this. As you've found, you can configure `match` to change how this behaves.

**Comment by AND51** [comment]
Hi Francis,

wow, this was a prompt response. Thanks a lot!

> The inline matcher argument is for request matchers. Encoding does run for all requests. But, it does not encode all responses. 

Ah, you got me there. I didn't get to distinguish it in this depth, but you are right.


> We set this to be a reasonable default because many types of content don't make sense to encode [...]

Yeah, I already thought of that. However, there are many more file extensions that are naturally uncompressed but that are not covered by your 'reasonable defaults'. I mentioned a few examples to underline that including countless other, compressible content-types may outweigh the impact of some incompressible ones.

> The encode directive documentation explains this.

Perhaps this can be emphasized better in the documentation. Yes, there is written what `match`'s defaults are. But leaving out `match` does not abolish the defaults as one may think. Also, the two examples give the impression that a mere one-liner enables compression for all. Maybe, you can at least add a different example that plays around with the 'reasonable defaults' such as `minimum_length` or `match`? I think, the mere presence of a complete different example can help other quick-starters to become aware of that, too. (Well, I'm not a quick starter anymore. I use Caddy for almost two years now.)

> Those are strong words. We're not doing that at all. You have complete control to configure Caddy 

Excuse my wording, if it sounds too harsh. Believe me, this was not my intention. I used a dictionary for that phrase, because there is no good translation for "jemanden bevormunden". What I meant was that there are many places where Caddy comes with reasonable defaults, e. g. the used TLS settings, `log` output's defaults or the whole `php_fastcgi` directive. Almost everywhere you can overwrite or add configuration to meet your needs. But in this place, you need to "subtract" well-meant configuration which feels ... kind of uncomfortable.

**Comment by francislavoie** [comment]
> However, there are many more file extensions that are naturally uncompressed but that are not covered by your 'reasonable defaults'.

We had to draw a line somewhere. We decided to go with what is understood as compressible for the biggest usecase which are websites (HTML + CSS + JS + images). If you want to compress user uploaded content, that's up to you to expand upon.

> But leaving out match does not abolish the defaults as one may think.

Why would it? That's the point of a default. To be the default. I don't understand your reasoning here.

> Also, the two examples give the impression that a mere one-liner enables compression for all.

I don't think so. There's no text that would imply that.

> Maybe, you can at least add a different example that plays around with the 'reasonable defaults' such as `minimum_length` or `match`?

Yeah, we could certainly add more examples. If you want to contribute some, the source is at https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/directives/encode.md. PRs welcome.

> Excuse my wording, if it sounds too harsh. Believe me, this was not my intention. I used a dictionary for that phrase, because there is no good translation for "jemanden bevormunden".

No worries :blush: glad we cleared that up. I think "patronizing" would be a better fit for that intent, but I still don't like that word because it's still somewhat strong (sounds accusatory). No problem though, I understand your intent now.

> What I meant was that there are many places where Caddy comes with reasonable defaults, e. g. the used TLS settings, log output's defaults or the whole php_fastcgi directive. Almost everywhere you can overwrite or add configuration to meet your needs. But in this place, you need to "subtract" well-meant configuration which feels ... kind of uncomfortable.

I'd argue that's not really true either, e.g. `php_fastcgi` has `index off`, TLS defaults can be turned off with the `auto_https off` global option, etc. Those "subtract" from the default. But I do agree that having to turn off defaults feels gross, and it's something we're always wrestling with to make feel as nice as possible.

**Comment by mholt** [comment]
I mean, we could expand our default list. It's conservative to start with:

```go
// common text-based content types
enc.Matcher = &caddyhttp.ResponseMatcher{
	Headers: http.Header{
		"Content-Type": []string{
			"text/*",
			"application/json*",
			"application/javascript*",
			"application/xhtml+xml*",
			"application/atom+xml*",
			"application/rss+xml*",
			"image/svg+xml*",
		},
	},
}
```

Tar might be acceptable, but I feel like most tars are already compressed if they are intended to be compressed... and if they contain images or videos, we'll be wasting CPU cycles.
