### ISSUE TITLE
Using caddy creates ".step" directory in homedir

### ISSUE THREAD

**Issue by klausman** [caddyserver/caddy#5594]
I suspect this is caused by one of the smallstep libraries, but I have no idea what the purpose of the directory is, or if the library's API allows for caddy to inhibit it (or redirect it to a better name like the XDG stuff). At any rate, creating new dotfiles/dirs in user homedirs and disregarding XDG vars should not be a thing in 2023 --- especially for a server software that may not be able to write in its set home directory. I tried figuring out which library specifically creates the directory, but failed to find an actual mkdir/CreateDir call. Feel free to redirect me to the right upstream place.

Caddy version is v2.6.4.

**Comment by mholt** [comment]
Caddy honors XDG, I believe this is upstream.

@maraino Can you tell me how to configure smallstep to put its directory somewhere else? Or maybe we can just have it honor XDG as well?

**Comment by maraino** [comment]
You can define the STEPPATH environment variable.

This is now bothering me on a different project so it might change, probably requiring us to call a function instead of relying on an `init`.

**Comment by mholt** [comment]
Oh right, I think I knew about that but then forgot...

But yeah, if it does it at init, I'm not sure we can change it in code, since the order of init isn't really controllable.

Maybe if step libs could honor XDG vars, and/or remove it out of an init and make it configurable, that'd be ideal :100:

**Comment by maraino** [comment]
The certificates (PR#1493)[https://github.com/smallstep/certificates/pull/1493], well, some dependencies removed the automatic initialization of the STEPPATH, now our tools use `step.Init()` to do that. 

I don't think your code will hit any call to methods like `step.Path()`, but if it does, the method will try to initialize the environment automatically, if this automatic initialization fails the value returned will be `""`. I've only seen this failing in restricted systemd units.

Neither `step.Init()` nor `step.Path()` will create any directory. 

I want to release a new version this week, but for now, you can try @master or @v0.24.3-rc.5

**Comment by mholt** [comment]
Awesome, thank you! 2.7 will likely be tagged tomorrow, so I'll use rc.5 before the tag, unless the new version is ready. (No rush)

**Comment by mholt** [comment]
Now using rc.5 as of https://github.com/caddyserver/caddy/commit/e198c605bd68f4b3630e5fa1ae9f7ca5cac1a7d9.
