### ISSUE TITLE
The listener cannot run using abstract sockets

### ISSUE THREAD

**Issue by lxhao61** [caddyserver/caddy#5597]
For related information, see the link: https://github.com/caddyserver/caddy/commit/22927e278dc29c9d1804c20f483510ec569f23ed

**Comment by emilylange** [comment]
Thank you!

See #5596

**Comment by lxhao61** [comment]
Thanks! Thanks for the fix so quickly.

**Comment by lxhao61** [comment]
Thanks. With the fix, the problem is resolved.

**Comment by mholt** [comment]
Woohoo! Thanks for the report, @lxhao61 and for the fix, @emilylange :blush:
