### ISSUE TITLE
Wildcard certificates - Logs

### ISSUE THREAD

**Issue by n-rodriguez** [caddyserver/caddy#5600]
Hi there!

I've switched from Nginx to Caddy using this "template" : https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates and so far it's working great 👍 

Now I would like to add some logs to this config but nothing seems to work :/

Where should I put the `log` block?

Whatever I try I have a parsing error  : 

```sh
Jun 26 14:53:19 cloud caddy[1998992]: Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle': /etc/caddy/Caddyfile:59 - Error during parsing: parsing caddyfile tokens for 'route': /etc/caddy/Caddyfile:57 - Error during parsing: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:50 - Error during parsing: unrecognized subdirective log
```

Thank you!

**Comment by francislavoie** [comment]
You can't arbitrarily nest directives. The `log` directive must go top-level in a site. Logging can't be configured per route, but you may use the `skip_log` handler directive to skip logging certain requests if you need.
