### ISSUE TITLE
quic: need to pass a (maximally thinly wrapped) net.UDPConn to quic-go

### ISSUE THREAD

**Issue by marten-seemann** [caddyserver/caddy#5605]
quic-go defines an `OOBCapablePacketConn`: https://pkg.go.dev/github.com/quic-go/quic-go#OOBCapablePacketConn. These are all the functions that quic-go needs (in addition to what `net.PacketConn` provides) to enable a range of optimizations (setting DF to do DPLPMTUD, using GSO, reading ECN bits).

Caddy currently passes a `net.PacketConn` to quic-go: https://github.com/caddyserver/caddy/blob/119e8794bcbda80ca337c1bb6164718e1490cc4f/modules/caddyhttp/server.go#L528-L530

Apparently (in some cases?) this even means that we can't even set the receive buffer size (see https://caddy.community/t/beta-v2-7-0-beta-2-warns-send-buffer-size-during-startup/20326 and https://github.com/quic-go/quic-go/issues/3932).

**Comment by mholt** [comment]
Thanks! I actually think the assertion should succeed, as we already have a guard in place:

https://github.com/caddyserver/caddy/blob/119e8794bcbda80ca337c1bb6164718e1490cc4f/listeners.go#L836

**Comment by mholt** [comment]
When I add all 4 methods of `uic.OOBCapablePacketConn` to `fakeClosePacketConn`, I now get this error:

```
panic: interface conversion: *caddy.fakeClosePacketConn is not net.Conn: missing method Read
```

But I'm not sure where this is coming from (there's no stack trace). That's not from my code, is it?

**Comment by mholt** [comment]
Another update (sorry) --

I used a recover in `main()` to get the stack trace (phew), which leads me here:

```
func NewPacketConn(c net.PacketConn) *PacketConn {
	cc, _ := socket.NewConn(c.(net.Conn))
```

https://cs.opensource.google/go/x/net/+/refs/tags/v0.11.0:ipv4/endpoint.go;l=102-103

Which was called from here:

https://github.com/quic-go/quic-go/blob/0c54d416eeb10c489deae30a853dde4553e94e96/sys_conn_oob.go#L119-L127

@marten-seemann Is that expected?

**Comment by WeidiDeng** [comment]
@mholt To correctly set buffer size you need to set both receive (read) and send (write) buffer size. Currently caddy only implemented `SetReadBuffer` not `SetWriteBuffer`. (Discussed on slack).

@marten-seemann I'll see how to implement `quic.OOBCapablePacketConn` interface. Can you take some time to review [pr](https://github.com/quic-go/quic-go/pull/3915), it's been there for several days without any updates.

**Comment by mholt** [comment]
Aha, indeed! I think both of us misread the message and thought it was talking about the _receive buffer_, not the _send buffer_.
