### ISSUE TITLE
Option to force content-type or ignore header

### ISSUE THREAD

**Issue by MattsBos** [caddyserver/caddy#5607]
As mentioned on Discord:

I thought it was a good idea to manage my config on a GitHub repo and let Caddy get the config with the admin/load/config/http module. This does get the file correctly but hangs on the header due to an incorrect `content-type: plain/text` instead of being json.

Unfortunately we have no control over this content-type as it's dictated by GitHub.

Is there a possibility for these use-cases to either force the content-type in the config/http module or add an option to disable looking at the headers and default to json?

**Comment by mholt** [comment]
Thanks for the feature request. The patch has been pushed; you can now configure the `adapter` field of your HTTP loader.
