### ISSUE TITLE
`caddy validate` does not check if the Caddyfile exists

### ISSUE THREAD

**Issue by p0358** [caddyserver/caddy#5612]
I think this is pretty self-explanatory:
```
$ caddy adapt
Error: input file required when there is no Caddyfile in current directory (use --config flag)
$ caddy validate
Error: decoding config: unexpected end of JSON input
```

The `validate` command, unlike `adapt` misses check that assesses the file even exists in the first place. With that, the user may assume the file was read and that they have some syntax error they'll be endlessly looking for, even though that's not the problem...

Check for adapt exists here:
https://github.com/caddyserver/caddy/blob/dfe17c33efb1653c0dcbcb8238935e7c72d714dd/cmd/commandfuncs.go#L439-L442

Missing in this func:
https://github.com/caddyserver/caddy/blob/dfe17c33efb1653c0dcbcb8238935e7c72d714dd/cmd/commandfuncs.go#L506

Should be simple fix for someone who already has a dev environment setup to test it out before committing (hence I'm creating an issue and not PR)

**Comment by pistasjis** [comment]
I'm working on this

**Comment by shubmjagtap** [comment]
Hi @pistasjis are you still working on this issue ? Hi @p0358 I would love to solve this good first issue , can I ?

**Comment by pistasjis** [comment]
I've been on vacation so I haven't really had the motivation to work on it, but it's mostly complete. I have returned home though and I'll fix it some more later.

**Comment by shubmjagtap** [comment]
> I've been on vacation so I haven't really had the motivation to work on it, but it's mostly complete. I have returned home though and I'll fix it some more later.

if you are going to do it later , can i work on this now because nowadays im dedicating my time fully on open source contributions ( by which i can solve this issue asap ).
