### ISSUE TITLE
[Request/Question] Is it possible to reverse_proxy via HTTP (CONNECT) proxy?

### ISSUE THREAD

**Issue by erkexzcx** [caddyserver/caddy#5615]
Hello. I have some unusual request - would it be possible, using only Caddy, to perform `reverse_proxy` via HTTP/HTTPS proxy? Are there any add-ons that can do this?

My use case is that there is an isolated environment without direct access to the internet. I want to use Caddy to act as a reverse proxy for `hooks.slack.com`, so I can specify something like `https://slack.example.com/XXXXXXXXXXXXXXXXXXXXXXXX` as a webhook and be able to deliver messages to Slack, except the Caddy should be able to forward the request via HTTP/HTTPS proxy.

Currently I am using self-baked python script, hosted on the same server where Caddy is:
```
slack.example.com {
    reverse_proxy 127.0.0.1:1234
}
```

I was thinking if there is more elegant solution, so I can avoid having python script? Any ideas?

**Comment by mholt** [comment]
Does it work if you set the `HTTP_PROXY` and `HTTPS_PROXY` variables? I believe we support this now: https://github.com/caddyserver/caddy/pull/5369

You might need to try with the current beta.

**Comment by mohammed90** [comment]
> Hi @mholt,
> 
> I haven't tried this approach, because from my understanding, providing `HTTP_PROXY` and `HTTPS_PROXY` env variables would apply for **every** _domain_/`reverse_proxy` directive, while I would need only for one.
> 
> I understand that my request is relatively stupid and insanely rare, so it's fine if this is not doable or not considerable. Feel free to close this issue then. :v: 
> 

If you know the domains in advance, you can also set `NO_PROXY` to tell which domains not to proxy.

**Comment by mholt** [comment]
Amazing ^

I didn't know that :sweat_smile: Cool!

**Comment by mohammed90** [comment]
I believe this is answered, so I'll close the issue.
