### ISSUE TITLE
 net/http: too many 1xx informational responses

### ISSUE THREAD

**Issue by dup2** [caddyserver/caddy#5616]
Running caddy.Version=v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

with a simple reverse proxy configuration

```
{
  auto_https disable_redirects
}

sample.internal:8443 {
  bind 10.240.0.86

  tls /etc/caddy/ssl/server.crt /etc/caddy/ssl/server.key

  reverse_proxy http://localhost:4000 {
   header_down -Server
   header_up X-Real-IP {http.request.remote.host}
  }
}
```

where the upstream server is a nginx 1.22.1 gives me the following error:

`net/http: HTTP/1.x transport connection broken: net/http: too many 1xx informational responses`
`"err_trace":"reverseproxy.statusError (reverseproxy.go:1299)"`

The upstreams logs a single request  with 103 code and then also logs a closed keepalive connection afterwards.

The clients uses http2 (curl) and logs this:
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Connection #0 to host sample.internal left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

when connecting directly to the upstream, the request works. When putting another nginx instead of caddy with a simple proxy configuration, it also works.

Any hints on this? Is this supposed to work at all (http2 to the client, http1.1 to the upstream?)

**Comment by francislavoie** [comment]
That's coming from Go's stdlib: https://github.com/golang/net/blob/4fc2eb99735f9f5a10adbdb9db2727e45bc826c7/http2/transport.go#L2432

I couldn't tell you why this is happening though. You'll need to sniff the traffic between Caddy and your upstream to see what it's writing. Why is it sending many `1xx` status code responses?

**Comment by dup2** [comment]
Thanks @francislavoie for the hint. 

I checked the traffic between Caddy and the upstream nginx server.

The upstream gets a single request "GET /profile/sign_in HTTP/1.1" with X-Forwarded-For, X-Forwarded-Host, X-Forwarded-Proto, X-Real-IP set as expected.

The upstream responds with 

```
HTTP/1.1 103 Early Hints
Server: nginx/1.22.1
Date: Tue, 04 Jul 2023 14:59:49 GMT
Connection: keep-alive
Link: </vite/assets/_baseRest-f72c847a.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/_baseIsEqual-33a4471b.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/isSymbol-d6dafaa4.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/camelCase-fa37df39.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/toNumber-d6fc5e96.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/_commonjsHelpers-042e6b4d.js>; rel=modulepreload; as=script; crossorigin=anonymous

HTTP/1.1 103 Early Hints
Link: </vite/assets/jquery-ca6899e4.js>; rel=modulepreload; as=script; crossorigin=anonymous

....

HTTP/1.0 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Content-Type: text/html; charset=utf-8
Vary: Accept
ETag: W/"115ffdb9a9df0924c34cdab409327771"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _session=d0357bf7bece2cb2c1ec69c9c11d9fb7; path=/; HttpOnly; SameSite=Lax
X-Request-Id: 91900b3f4fb5ef67c639221bfd2751ea
X-Runtime: 0.053329
x-rack-cors: miss; no-origin
Content-Length: 8345

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
...
```

So basically a lot of early hints (some I have omitted, there are around 20) in the same response with keep-alive connection and then the HTML content of the page. The page contains these asset links like `<link rel="modulepreload" href="/vite/assets/isSymbol-d6dafaa4.js" as="script" crossorigin="anonymous">` for example

**Comment by francislavoie** [comment]
Interesting... shouldn't those just be one big `103 Early Hints` response? Why it is one per file?

/cc @dunglas apparently Go doesn't like it when there's _lots_ of Early Hints responses

**Comment by dunglas** [comment]
I'll take a look, but sending a lot of 1xx responses is probably not a good idea anyway. I suggest fixing the upstream application.

**Comment by francislavoie** [comment]
@dup2 are you using Nuxt? Make sure to turn off this option https://nuxt.com/docs/api/configuration/nuxt-config#writeearlyhints (it should be off by default on latest versions of Nuxt).

**Comment by mholt** [comment]
lol wow, the Go std lib says:

```go
const max1xxResponses = 5 // arbitrary bound on number of informational responses
```

Seems arbitrarily low to me :upside_down_face:

**Comment by dup2** [comment]
> I'll take a look, but sending a lot of 1xx responses is probably not a good idea anyway. I suggest fixing the upstream application.

hmm, this is a nginx server with a rails backend application - you mean that nginx should be fixing this issue on their side?

https://httpwg.org/specs/rfc8297.html seems to allow multiple: "a server might emit more than one 103 (Early Hints) response prior to sending a final response." so it seems this "arbitrary bound on number of informational responses" is just restricting it to a, well, arbitrary number..

**Comment by mholt** [comment]
More than a few and you have diminishing returns. More than a few is likely a bug.

In this case, they're just using 103s for Link/prefetch resources. This is supposed to improve performance. Sending many 103s doesn't improve performance, so that's a bug in the origin. They should send one 103 with multiple Links.

**Comment by francislavoie** [comment]
Without seeing your nginx config or your rails code, I don't know which one is the problem. But whichever one generates the `Link` headers should group them all up in one response, not in many responses.
