### ISSUE TITLE
Caddy reverse-proxy not working

### ISSUE THREAD

**Issue by j2yemi** [caddyserver/caddy#5618]
I have this configuration on Caddyfile

abc.com {

handle /auth/* {
reverse_proxy localhost:3000
}
handle /mbase/* {
reverse_proxy localhost:3000
}
handle /* {
reverse_proxy localhost:4200
}

}

When started only abc.com/admin works. The others predicates or paths show blanks or white page.

The same configuration on nginx works 
server {
        server_name  abc.com
        listen 80;
    location / {
            proxy_pass http://localhost:4200;
        }

    location /mbase/ {
           proxy_pass http://localhost:3000/;
}
location /auth/ {
proxy_pass http://localhost:3000/;
}

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
