### ISSUE TITLE
Caddy 2.7.0-beta.2: nested imports in handler broken (again)

### ISSUE THREAD

**Issue by aksdb** [caddyserver/caddy#5625]
I think the same problem problem existed before (#4914) but was supposed to be fixed. It actually worked in beta.1 but is now broken again. The following example fails:

```caddyfile
(responderWithStatus) {
	respond {args[0]} {args[1]}
}

(responder) {
	import responderWithStatus {args[0]} 202
}

http://127.0.0.1:8080 {
	handle {
		import responder "foobar"
	}
}
```

```
2023/07/10 12:25:30.379	INFO	using adjacent Caddyfile
Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle': Caddyfile:12 - Error during parsing: unrecognized directive: import - are you sure your Caddyfile structure (nesting and braces) is correct?, import chain: ['']
```

**Comment by mholt** [comment]
I wonder if @WeidiDeng might have an idea?

**Comment by tedtramonte** [comment]
Has the fix made it into a release yet? Using `caddy:2.7` as a base I'm getting this same error.

```
...
(organizr_auth) {
	reverse_proxy organizr:80 {
		...
	}
}

(authadmin) {
	import organizr_auth /api/v2/auth?group=0
}

(authsuperuser) {
	import organizr_auth /api/v2/auth?group=2
}

(authuser) {
	import organizr_auth /api/v2/auth?group=4
}
...
```

**Comment by francislavoie** [comment]
What "same error"? Please show your logs, etc. Not enough information here.

**Comment by tedtramonte** [comment]
Literally word for word the message in this issue. I would have opened a new issue if it was any different at all. I was just wondering if the docker image `caddy:2.7` was meant to resolve this or if a release is pending.

**Comment by francislavoie** [comment]
Are you sure you're actually running 2.7.2? Run `caddy version` in your container to check.

**Comment by hairyhenderson** [comment]
@tedtramonte the `caddy:2.7` image still points to 2.7.0-beta.2 - it'll take a bit before 2.7.2 is pushed.

**Comment by hairyhenderson** [comment]
if you look at https://hub.docker.com/_/caddy you'll see what the 2.7 tag points at.

**Comment by tedtramonte** [comment]
Thanks boss, just wasn't sure what the release cadence of the docker images was.
