### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by simon-fa** [caddyserver/caddy#5629]
Hello,

Since I've activated debug mode, I over flooded with these :

`{"level":"debug","ts":1689233379.6217337,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60067: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233379.6671865,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60068: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233379.6673255,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60069: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233379.6680357,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60071: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233379.6691372,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60070: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233379.6728482,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60072: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.6226926,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60076: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.668364,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60077: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.6687307,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60080: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.6688015,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60078: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.669358,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60079: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233396.670725,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60081: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.6233315,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60082: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.6686587,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60087: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.6687555,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60085: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.669339,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60083: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.6696358,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60084: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233413.6697736,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60086: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.6683407,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60091: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.7612143,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60093: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.761935,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60095: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.7623892,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60096: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.7629728,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60092: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233430.7633507,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60094: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6220186,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60098: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6658347,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60101: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6662624,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60099: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6670682,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60103: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6676826,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60100: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233447.6678112,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60102: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6241837,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60106: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6694276,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60111: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6695595,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60107: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6697352,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60109: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6699777,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60108: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233464.6703107,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60110: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6243577,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60115: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6685214,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60116: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6686733,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60117: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6691499,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60119: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6694312,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60120: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233481.6694822,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60118: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.6242485,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60124: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.668336,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60125: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.6693752,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60127: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.6695194,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60126: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.6696706,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60129: remote error: tls: unknown certificate"}
{"level":"debug","ts":1689233498.669729,"logger":"http.stdlib","msg":"http: TLS handshake error from 2.3.209.219:60128: remote error: tls: unknown certificate"}
`

What should I do ?
I use 2.7 beta 2 on api platform configuration.

**Comment by francislavoie** [comment]
That's normal. Those are bots/scrapers hitting your IP address without knowing your domain name. You can ignore them (turn off debug logging unless you need to look for something actively).

**Comment by simon-fa** [comment]
I'm looking for something actively, but I haven't found it yet 😅
