### ISSUE TITLE
caddy fmt can use a caddyfile arg ?

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#5635]
Regarding...

```sh
caddy fmt -d  
```

It night be good if we can pass in the caddyfile ?
If none passed in then it assumes it the default name.

```sh
caddy  fmt --config caddyfile-example -d
Error: unknown flag: --config
```

Then it matches the way validate works:
```sh
caddy validate --config caddyfile-example
```

**Comment by francislavoie** [comment]
Please review the help doc for the fmt command. It takes the file as an argument, not as a flag. So simply remove `--config`.

**Comment by gedw99** [comment]
@francislavoie 

Its does not tell me anything on help btw:

```sh
caddy fmt -h

Formats the Caddyfile by adding proper indentation and spaces to improve
human readability. It prints the result to stdout.

If --overwrite is specified, the output will be written to the config file
directly instead of printing it.

If --diff is specified, the output will be compared against the input, and
lines will be prefixed with '-' and '+' where they differ. Note that
unchanged lines are prefixed with two spaces for alignment, and that this
is not a valid patch format.

If you wish you use stdin instead of a regular file, use - as the path.
When reading from stdin, the --overwrite flag has no effect: the result
is always printed to stdout.

Usage:
  caddy fmt [flags]

Flags:
  -d, --diff        Print the differences between the input file and the formatted output
  -h, --help        help for fmt
  -w, --overwrite   Overwrite the input file with the results
```

**Comment by francislavoie** [comment]
Weird, okay. Probably got broken to not show arguments correctly when we switched CLI libraries. I'll look into that.

Anyways the docs here are accurate: https://caddyserver.com/docs/command-line#caddy-fmt

**Comment by mholt** [comment]
That'd be interesting... I'd be OK with that, but I want to make sure the web-formatted docs are rich enough; like right now we use markdown for code snippets, examples, lists, etc. They'd have to be translated into plain text (stripped of HTML and markdown, though) for the CLI.

**Comment by francislavoie** [comment]
For that benthos project they spent the time and effort to write code to do that for their own usecase. We _could_ do that, but I definitely don't have the time to put into to write a doc generator, even if it's not super complex.

I don't mind manually updating the website docs as we make changes to the CLI code because it's kinda part of the release routine to look at the commits since the last release and update the docs with any changes.
