### ISSUE TITLE
caddy with modified quic-go

### ISSUE THREAD

**Issue by MardenSSS** [caddyserver/caddy#5640]
Caddy now uses the quic-go source library to support HTTP3 services by default. Now I want to modify some content of quic-go and run the modified quic-go in caddy. How should I do it? Can you give me some help?

**Comment by francislavoie** [comment]
Use `xcaddy` to build with a replacement of the `github.com/quic-go/quic-go` package. See the `xcaddy` README for instructions https://github.com/caddyserver/xcaddy#custom-builds
