### ISSUE TITLE
An elegant way to get the request ID from code

### ISSUE THREAD

**Issue by mholt** [caddyserver/caddy#5649]
Right now if you want to get the request ID from code, you need to do something like:

```go
r.Context().Value(caddy.ReplacerCtxKey).(*caddy.Replacer).GetString("http.request.uuid")
```

The `caddyhttp` Replacer actually gets it this way:

```go
GetVar(req.Context(), "uuid").(*requestID)
```

but `requestID` is not an exported type. (And I don't think I want to export it.)

Additionally, the implementation of "the request ID" can change. Right now it's a UUIDv4 but I could see UUIDv7 or ULID being useful, for example. Someone else in a chat suggested we use Tracing Signals: https://opentelemetry.io/docs/specs/otel/overview/#tracing-signal

Any ideas on how we should make the request ID more easily accessible via code? And how to define what "the request ID" is, especially if multiple implementations become available?

**Comment by WeidiDeng** [comment]
```
GetVar(req.Context(), "uuid").(fmt.Stringer).String()
```

Didn't test it, but I think it will work. `requestID` does implement [`fmt.Stringer`](https://github.com/caddyserver/caddy/blob/a8cc5d1a7d9d80e12ab895beaf4eaed34cc6bded/modules/caddyhttp/replacer.go#L484) interface.

**Comment by francislavoie** [comment]
That does work! I tried it real quick with:
```diff
diff --git a/modules/caddyhttp/replacer.go b/modules/caddyhttp/replacer.go
index c58b56ed..745737af 100644
--- a/modules/caddyhttp/replacer.go
+++ b/modules/caddyhttp/replacer.go
@@ -157,7 +157,7 @@ func addHTTPVarsToReplacer(repl *caddy.Replacer, req *http.Request, w http.Respo
                                start := GetVar(req.Context(), "start_time").(time.Time)
                                return time.Since(start).Seconds() * 1e3, true // multiply seconds to preserve decimal (see #4666)
                        case "http.request.uuid":
-                               id := GetVar(req.Context(), "uuid").(*requestID)
+                               id := GetVar(req.Context(), "uuid").(fmt.Stringer)
                                return id.String(), true
                        case "http.request.body":
                                if req.Body == nil {
```

And `respond {http.request.uuid}` and it works.

And you're right, `caddy.ToString(GetVar(req.Context(), "uuid"))` also just works :+1:

Clever!

**Comment by mholt** [comment]
Huh, awesome! Maybe we don't need to do anything then.

**Comment by dtelyukh** [comment]
> ```
> GetVar(req.Context(), "uuid").(fmt.Stringer).String()
> ```
> 
> Didn't test it, but I think it will work. `requestID` does implement [`fmt.Stringer`](https://github.com/caddyserver/caddy/blob/a8cc5d1a7d9d80e12ab895beaf4eaed34cc6bded/modules/caddyhttp/replacer.go#L484) interface.
> 
> [`ToString`](https://github.com/caddyserver/caddy/blob/v2.7.3/replacer.go#L247) may also work and is simpler.

I use the same approach

**Comment by mholt** [comment]
Cool, thanks for the comment. So I think this is already doable. I will close this for future reference, and we can revisit this later if needed.
