### ISSUE TITLE
Need something like tls_insecure_skip_verify for on_demand_tls ask url

### ISSUE THREAD

**Issue by oleksandrl5** [caddyserver/caddy#5665]
As I can see on_demand_tls ask url not working with self signed certs or maybe I am doing something wrong?

**Comment by mholt** [comment]
That URL should be internal-only for both performance and privacy; TLS is not really necessary, but if used, it should be trusted.

**Comment by oleksandrl5** [comment]
can I use self signed cert between servers inside vpn?

**Comment by mholt** [comment]
Sure, you just have to install them into the trust store if you want to use them for on-demand TLS's 'ask' end point.

**Comment by oleksandrl5** [comment]
I also had problems with this, but I will re-read the docs

**Comment by mholt** [comment]
Installing a cert into your trust store isn't really in our docs because it's not related to Caddy; it's just how the network stack works on a computer. You can look up your OS's documentation to learn how to install a root cert.

**Comment by oleksandrl5** [comment]
Thank you for answer and for caddy. It works (: maybe make sense to have tls client auth in on_demand_tls ask url

**Comment by francislavoie** [comment]
> maybe make sense to have tls client auth in on_demand_tls ask url

I don't think so. It should be internal to your network generally, and if not it doesn't matter anyway because it's not really secret information.

**Comment by Neustradamus** [comment]
@oleksandrl5: Sorry I have no other possibility to contact you, can you check the ksmbd ticket that you have commented and look the proposed fix and comment the result in the ticket too? Thanks in advance.
