### ISSUE TITLE
Twice 'Server' header when using reverse proxy with gunicorn 

### ISSUE THREAD

**Issue by ZhymabekRoman** [caddyserver/caddy#5667]
Caddy version: [v2.7.0-beta.2](https://github.com/caddyserver/caddy/releases/tag/v2.7.0-beta.2) and [v2.6.4](https://github.com/caddyserver/caddy/releases/tag/v2.6.4)
Caddyfile:
```
:80 {
    handle_path /favicon.ico {
        root * ./static/favicon.ico
        file_server
    }

	route /* {
        reverse_proxy localhost:7080
    }
}
```
Curl `-v` response:
```
curl -v "http://127.0.0.1/"
*   Trying 127.0.0.1:80...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 6809
< Content-Type: text/html; charset=utf-8
< Date: Tue, 01 Aug 2023 09:02:01 GMT
< Server: Caddy
< Server: gunicorn
```

**Comment by mohammed90** [comment]
This is not a bug. It's by design. If you don't want the server headers, you can remove them, though not recommended as they're helpful for troubleshooting.

**Comment by francislavoie** [comment]
To clarify, every server or proxy that a request makes its way through _should_ add the Server header. It's a way to trace now the request was handled, to make sure your DNS and routing did what you expected it to do.

**Comment by ZhymabekRoman** [comment]
Okay, thanks for the answers.
