### ISSUE TITLE
Unable to compile after adding caddy-l4 plugin

### ISSUE THREAD

**Issue by lxhao61** [caddyserver/caddy#5673]
It is found that the source code before [5c51c1d](https://github.com/caddyserver/caddy/commit/5c51c1db2ce450a3fa003834097ad010b3844673) plus the caddy-l4 (default master branch) plug-in is compiled normally; but the source code of [5c51c1d](https://github.com/caddyserver/caddy/commit/5c51c1db2ce450a3fa003834097ad010b3844673)  and later plus the caddy-l4 (default master branch) plug-in is compiled incorrectly, and the error report is as follows:
![image](https://github.com/caddyserver/caddy/assets/24571146/6700f587-0e80-4710-ae4a-826bb43a2114)

**Comment by hslatman** [comment]
Hey @lxhao61,

You seem to have hit the same issue as me: https://github.com/caddyserver/caddy/issues/5674.

PR with fix: #5675

**Comment by lxhao61** [comment]
@hslatman 
seems like it.
Hope your fix works.

**Comment by lxhao61** [comment]
@hslatman @mholt 
Didn't succeed to fix the problem I found, the problem is still the same.
