### ISSUE TITLE
Custom Caddy build with module relying on `httpcaddyfile` doesn't compile

### ISSUE THREAD

**Issue by hslatman** [caddyserver/caddy#5674]
After upgrading to `v2.7.0` and running CI with Go 1.20.7, I get the following error:

```
Error: ../../../go/pkg/mod/github.com/caddyserver/caddy/v2@v2.7.0/caddyconfig/httpcaddyfile/httptype.go:358:24: string does not match ~[]E
```

Also see: https://github.com/hslatman/caddy-crowdsec-bouncer/actions/runs/5744901364/job/15572008214?pr=18#step:5:167

I see the same behavior on my mac.

The change seems to have been introduced in https://github.com/caddyserver/caddy/commit/5c51c1db2ce450a3fa003834097ad010b3844673.

**Comment by hslatman** [comment]
I've opened a PR with a fix: https://github.com/caddyserver/caddy/pull/5675

**Comment by francislavoie** [comment]
Hmm. I don't understand why this fails for you, doesn't fail for our CI.

**Comment by mholt** [comment]
Yeah, weird, it also works on my machine.
