### ISSUE TITLE
caddy upgrade not downloading latest release

### ISSUE THREAD

**Issue by RainmakerRaw** [caddyserver/caddy#5676]
As per the closed issue #5155, I seem to have encountering the same problem. I have Caddy v2.6.4 installed on two machines - Debian 11.7 (Bullseye) and also Oracle Linux 9.2. Both are arm64 releases. I originally installed Caddy using the system package manager pointed at the cloudsmith repos, following the guide in the Caddy docs. I then added Cloudflare DNS and @mholt's L4 plugin using `caddy add-package`. 

Having seen the announcement for the release of v2.7 I tried to upgrade with `sudo caddy upgrade`. The 'upgrade' proceeds without error, except that the version downloaded is still v2.6.4 on both systems. The package managers of those systems have v2.7 showing as available from the cloudsmith repo, but without the extra modules/packages that I need the upgrade proceeds OK and then the service fails to start due to my config depending on the Cloudflare DNS and L4 modules. 

Issuing `sudo caddy install-package ...` to remedy the issue once again re-downloads version 2.6.4 and I'm back to square one.

**Comment by francislavoie** [comment]
Yeah we haven't updated the build server to serve the latest version yet.

**Comment by RainmakerRaw** [comment]
Thank you for your speedy reply, @francislavoie. It's the first version I've needed to manually upgrade, so I wasn't sure on the procedure/timescales. Sorry for the bother.
