### ISSUE TITLE
v2.7.1: websockets randomly work or don't

### ISSUE THREAD

**Issue by xnaas** [caddyserver/caddy#5678]
Neither Caddy nor my web browser seem to provide any insight into this issue. Caddy logs show nothing relevant (perhaps I need to configure something more verbose/debuggy?) and my browser just Eventually™ says it can Never™ connect to wss://whatever after a long period of time.

---

It seems that in `v2.7.1` it's totally random whether websockets work for any given `reverse_proxy`.

For me: neither my [Send](https://github.com/timvisee/send) (ws for file uploads) nor [TeslaMate](https://github.com/adriankumpf/teslamate) (ws streams in map tiles at vehicle's location in real-time) websockets work. But [The Lounge](https://github.com/thelounge/thelounge)'s websockets work fine for me.

For a buddy: his The Lounge's websockets do not work at all.

---

For both of us: Everything works flawlessly upon rolling back to `v2.7.0-beta.2` (with the same Caddyfile that doesn't seem to work on `v2.7.1`). I don't know what change could cause this random behavior.

**Comment by francislavoie** [comment]
Confirmed, we accidentally broke websockets. Sorry about that. We'll make a v2.7.2 hotfix shortly :sweat:

**Comment by francislavoie** [comment]
Yes. I argued for it but we were too hasty.

**Comment by mholt** [comment]
We were in beta phase for about a month.

**Comment by ouuan** [comment]
> We were in beta phase for about a month.

I think the "too many things" means the things between beta.2 and the final release.

**Comment by mholt** [comment]
There was precisely 1 commit that I mistakenly thought was ready for release and intended for 2.7, but should have been pushed back for a later patch release.

Still, we're surprised our CI tests didn't catch some of these issues. I'll need to work on our test coverage.
