### ISSUE TITLE
Caddy v2.7.2 SIGSEGV quic-go

### ISSUE THREAD

**Issue by jmdilly** [caddyserver/caddy#5682]
Hello,

On v2.7.2 Caddy, the process crashes with the following backtrace : 
<img width="1848" alt="image" src="https://github.com/caddyserver/caddy/assets/48059109/e5974983-cdaf-44ce-939c-a9a81a529c65">

Caddy is running in Debian 11 LXC on Promox 8.

I had to downgrade to v2.6.4 which works fine.

**Comment by mholt** [comment]
Duplicate of #5680
