### ISSUE TITLE
Caddy Configuration Consulting about HTTP/2 Server Push

### ISSUE THREAD

**Issue by Chenpinji** [caddyserver/caddy#5683]
Hi! 
I'm using Caddy as a reverse proxy of my HTTP/2 origin server.  It's really convenient that Caddy supports HTTP/2 by default, however, my origin server has some assets to push and Caddy disabled the push stream (PUSH PROMISE FRAME) in the test. I have searched for reasons on RFC, it shows that "SETTINGS_ENABLE_PUSH (0x2): This setting can be used to disable server push (Section 8.2)". Therefore, I wonder how to set Caddy to enable the origin server push. Can Caddy handle PUSH PROMISE FRAME? It would help to give me some instructions, my configuration Caddyfile is below:
#######################################
https://www.xxxx.xxx, www.xxx.com{
	# Set this path to your site's directory.
	#root /var/www/html
	# Enable the static file server.
	#file_server
	# Another common task is to set up a reverse proxy:
	tls /path/to/fullchain.cer /path/to/cert.key
	reverse_proxy localhost:8443
	# Or serve a PHP site through php-fpm:
	# php_fastcgi localhost:9000
}
It should note that the normal HTTP/2 communication between client<->Caddy reverse proxy and Caddy reverse proxy <->origin server are all right. Caddy just cannot handle PUSH PROMISE. I'm looking forward to your kind reply, thank you!

**Comment by francislavoie** [comment]
Pretty sure you just need to enable the `push` directive: https://caddyserver.com/docs/caddyfile/directives/push

But FYI browsers are phasing out HTTP/2 Server Push in favour of 103 Early Hints. We'll probably deprecate `push` eventually.

**Comment by mholt** [comment]
Yep, was just about to say that. Thanks Francis

Closing now, since I think this is just a question about how to use Caddy, but feel free to ask more questions on our forums: https://caddy.community (or we can reopen if there is a bug)

**Comment by francislavoie** [comment]
On a second reading, I think you're asking about the proxy forwarding h2 pushes. AFAICT this is not supported in Go stdlib currently, see https://github.com/golang/go/issues/18594. Nothing we can do about it in Caddy unfortunately.

**Comment by Chenpinji** [comment]
Hello! I have read the documents many times about how to enable server push. I know that origin server can use Link Header to push the assets. Nevertheless, I want to initiate a PUSH PROMISE STERAM directly from my server to Caddy, and the result showed that Caddy disable the push stream by default. So, I'm curious about whether this is a configuration problem, or just Caddy doesn‘t implement how to handle the push stream?  Thanks! 



***@***.***
 
From: Francis Lavoie
Date: 2023-08-04 09:10
To: caddyserver/caddy
CC: Chenpinji; Author
Subject: Re: [caddyserver/caddy] Caddy Configuration Consulting about HTTP/2 Server Push (Issue #5683)
Pretty sure you just need to enable the push directive: https://caddyserver.com/docs/caddyfile/directives/push
But FYI browsers are phasing out HTTP/2 Server Push in favour of 103 Early Hints. We'll probably deprecate push eventually.

**Comment by mholt** [comment]
Oh. Gotcha gotcha. Sorry. Yeah, the Go std lib doesn't have a way to do that yet. Francis' linked issue looks like the relevant discussion / action-item.

**Comment by Chenpinji** [comment]
Yeah,  I got it! Thanks for the helpful and immediate reply!

best wishes 


***@***.***
 
From: Matt Holt
Date: 2023-08-04 09:27
To: caddyserver/caddy
CC: Chenpinji; Author
Subject: Re: [caddyserver/caddy] Caddy Configuration Consulting about HTTP/2 Server Push (Issue #5683)
Oh. Gotcha gotcha. Sorry. Yeah, the Go std lib doesn't have a way to do that yet. Francis' linked issue looks like the relevant discussion / action-item.

**Comment by Chenpinji** [comment]
OK, I got it! Thanks for the quick reply!



***@***.***
 
From: Francis Lavoie
Date: 2023-08-04 09:18
To: caddyserver/caddy
CC: Chenpinji; Author
Subject: Re: [caddyserver/caddy] Caddy Configuration Consulting about HTTP/2 Server Push (Issue #5683)
On a second reading, I think you're asking about the proxy forwarding h2 pushes. AFAICT this is not supported in Go stdlib currently, see golang/go#18594. Nothing we can do about it in Caddy unfortunately.
