### ISSUE TITLE
reverse_proxy upstream directive interprolation throwing `strconv.ParseUint`

### ISSUE THREAD

**Issue by jedmonds-tiplu** [caddyserver/caddy#5688]
Hey team,

We are currently facing an issue with the Caddy in our docker compose stacks, currently using the Caddy Docker Image pinned on version '2'.

We see the following in our logs: `Error during parsing: parsing caddyfile tokens for 'reverse_proxy': /etc/caddy/Caddyfile:26 - Error during parsing: invalid start port: strconv.ParseUint: parsing "6{http.regexp.port.1}"`

It appears that the Interpolation for the `Matcher` / `Upstream` is not functioning as intended.

Caddyfile:
```
*.sandbox.application.localhost {
	@sandboxPort {
		header_regexp port Host ^([0-9]{3})\.sandbox\.
	}

	handle @sandboxPort {
		reverse_proxy app:6{re.port.1}
	}

	handle {
		redir {scheme}://application.localhost
	}
}
```

As a quick fix, we have pinned our docker compose files to version 2.6.4 (where is issue is not present).

Regards

**Comment by mohammed90** [comment]
This is probably related to #4019. Can you download the CI build artifact and test it out? You can download it from [here](https://github.com/caddyserver/caddy/actions/runs/5760117333) or run `xcaddy build fix-args-replacer`.

**Comment by mohammed90** [comment]
The culprit is PR #5494 (75b690d248c7681dd974f6179c98a363af417a25). Now onto finding a fix.

**Comment by Lan-Hekary** [comment]
any ETA on the when this will be fixed ?

**Comment by francislavoie** [comment]
You can build from @mohammed90's PR if you need the fix right away. We don't have set timelines.
