### ISSUE TITLE
admin api unix socket permissions cause config reload to fail

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#5694]
When adding the new #4741 socket permissions to the admin unix socket, the file permissions are correctly applied, but reloading the config (using `systemctl reload caddy` with the systemd unit installed by the [debian package](https://caddyserver.com/docs/install#debian-ubuntu-raspbian)) fails because the permissions suffix is included in the socket address the config would be written to:  
`Error: sending configuration to instance: performing request: Post "http://127.0.0.1/load": dial unix /run/caddy/admin.sock|0660: connect: no such file or directory`

Caddyfile snippet:
```
# Global options first
{
        # /run/caddy is created by config in /etc/systemd/system/caddy.service.d/xon.conf
        admin unix//run/caddy/admin.sock|0660
```

The full filesystem path to the socket is `/run/caddy/admin.sock` as expected.

Edit: version is 2.7.2

**Comment by francislavoie** [comment]
Oooh yeah that's a fun detail. We need to add the address parsing to the reload command so that it strips away the un-needed bits (permissions). Thanks for opening the issue!

**Comment by emilylange** [comment]
Whoops, sorry, wasn't aware of that code path.
Will try to send a patch later today
