### ISSUE TITLE
templates: httpInclude fails in 2.7.2

### ISSUE THREAD

**Issue by bones-was-here** [caddyserver/caddy#5698]
We have HTML snippets included in our error handling and file browser templates, to add headers, footers, theming, etc without duplicating code manually (these snippet files are generated by hugo from HTML used in other areas of the site).  In 2.6.4 this works well, but upgrading to 2.7.2 causes the `httpInclude` to fail.  A blank white page with a 500 status is returned to the client, because the error can't be displayed properly since the error template fails to execute :) `"http.log.error","msg":"error handling handler error"`

The relevant error seems to be: `"error":"{id=6kgdatjc0} templates.(*Templates).executeTemplate (templates.go:425): HTTP 500: template: /integ/error.html:7:4: executing \"/integ/error.html\" at <httpInclude \"/integ/favicon.html\">: error calling httpInclude: interface conversion: interface is nil, not net.Conn","first_error":{"msg":"template: file_server.html:40:5: executing \"file_server.html\" at <httpInclude \"/integ/favicon.html\">: error calling httpInclude: interface conversion: interface is nil, not net.Conn","status":500,"err_id":"ichdvhnp7","err_trace":"fileserver.(*FileServer).serveBrowse (browse.go:130)"}}`

`httpInclude` is documented at https://caddyserver.com/docs/modules/http.handlers.templates
It looks like for our use case we could use `include` instead as these are static files.

**Comment by francislavoie** [comment]
Did this happen to be an HTTP/3 request which caused this? Does it do the same if you make an HTTP/1.1 or HTTP/2 request?

The clue is `interface is nil, not net.Conn`, this is similar to the problems we're facing with #5680, i.e. `hello.Conn` isn't set.

**Comment by mholt** [comment]
Ah yeah. In this case, it's probably from our use of ConnContext, which lets us get the underlying Conn of the request, which we use when calling ServeHTTP(), particularly when `r.TLS == nil`. I bet the upcoming patch will fix this.

**Comment by mholt** [comment]
I'm willing to bet this is fixed in 2.7.3; please try it out, and if not, we can re-open this.

**Comment by bones-was-here** [comment]
It's happening with HTTP/2 in 2.7.3.  Switching the template from `httpInclude` to `include` does work around it.

**Comment by mholt** [comment]
Hm, okay. Do you have a minimal reproducer we could use?

**Comment by bones-was-here** [comment]
Will this do? https://gitlab.com/xonotic/xonotic.org/-/blob/master/static/integ/error.html
Caddyfile:
```
handle_errors {
                root * /var/www/xonotic.org/HTML
                file_server
                rewrite * /integ/error.html
                templates
        }
```

**Comment by bones-was-here** [comment]
Looks like we do need `httpInclude` here, `include` only works in the main site and not when the template is used in a subdomain  with a different root (where the included files are only accessible via a `handle {}` block that changes the root for those files).

**Comment by mholt** [comment]
@bones-was-here Thanks, I was able to reproduce it with that information and have pushed a fix. It was very simple.

**Comment by bones-was-here** [comment]
Yes it's working, thanks!
