### ISSUE TITLE
caddy.community down?

### ISSUE THREAD

**Issue by letto4135** [caddyserver/caddy#5702]
Can't reach caddy.community, is the site down? Looking for the how-to-use-dns-provider-modules-in-caddy-2 post on how to do wildcard certs.

**Comment by francislavoie** [comment]
Yep, it's down. We tried to upgrade the VM and it broke Docker because reasons. Working on it. Should be back up shortly. Sorry!

**Comment by francislavoie** [comment]
It's back now.

**Comment by mholt** [comment]
That was my bad. I followed some instructions to get Docker out of the mire but the instructions looked like this:

![image](https://github.com/caddyserver/caddy/assets/1128849/0e5b024b-0ca8-4a93-9901-3e23b74ddda1)


So Francis saved the day.

**Comment by letto4135** [comment]
Sounds like good timing on trying to get to it, thanks folks!
