### ISSUE TITLE
Module for security and bots mitigation

### ISSUE THREAD

**Issue by microSoftware** [caddyserver/caddy#5726]
Looking for caddy module for security (sql injection, xss, and other various vulnerabilities). And also bot mitigation a la cloudflare.
I stumbled upon coraza which seem to be what i'm looking for. Have you used it? any feedback on it?

Do you know what other module i can install to increase the security of my application. I used caddy as a reverse proxy

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

All the plugins we know about are registered on https://caddyserver.com/download. Search there.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
