### ISSUE TITLE
Caddy returning empty 200 on known SNI unknown Host header

### ISSUE THREAD

**Issue by herkulessi** [caddyserver/caddy#5729]
When Caddy gets a request for a known SNI (which it has a Certificate for), but with an Host header naming an unknown host (which is NOT matching the SNI) Caddy will return an empty 200 response.

I do not know whether this is intended behavior, but it seems strange to me.

In case it matters, the Caddy in question is version `v2.7.3 h1:eMCNjOyMgB5A1KgOzT2dXKR4I0Va+YHCJYC8HHu+DP0=` and has the requesting Client/Proxy in it's trusted Proxies list.

**Comment by francislavoie** [comment]
Essentially, yes that's working as intended.

You can configure `strict_sni_host` in your server options to enforce that `Host` matches SNI. https://caddyserver.com/docs/caddyfile/options#server-options
