### ISSUE TITLE
can Caddy support multiple reverse proxies with command line ?

### ISSUE THREAD

**Issue by kkqy** [caddyserver/caddy#5737]
`caddy reverse-proxy --from example.com --to :9000`
this command setup only one reverse proxy whose domain is example.com .
but I need setup two or more reverse proxies , the one is abc.com to :7000, and another one is xyz.com to :8000 and so on.
I must write a caddy file as the config file ,but I want to use it by pure command line like below:
`caddy reverse-proxy abc.com|:7000 xyz.com|:8000`
but it can't support this yet.

Using caddy with command line is very convinient in docker's compose file ,but this way don't support multiple reverse proxies if my project has two or more sites.

**Comment by francislavoie** [comment]
No, for that you'll need a config file.

I don't think we plan on adding much more complexity to this command. It's just meant as a quick-and-dirty shortcut for local development. For anything more you're better off with a short Caddyfile.

If you absolutely must do it with one command, you can do it by piping Caddyfile text into the `caddy run -c-` command (`-` to mean stdin).

**Comment by kkqy** [comment]
> No, for that you'll need a config file.
> 
> I don't think we plan on adding much more complexity to this command. It's just meant as a quick-and-dirty shortcut for local development. For anything more you're better off with a short Caddyfile.
> 
> If you absolutely must do it with one command, you can do it by piping Caddyfile text into the `caddy run -c-` command (`-` to mean stdin).

solve my problem by `-c-`.
