### ISSUE TITLE
TLS 1.3 0-RTT Enabled by default

### ISSUE THREAD

**Issue by mgaller** [caddyserver/caddy#5754]
Release 2.7.3 highlights 

- Significant HTTP/3 performance improvements (upstream in quic-go) **including enabling 0-RTT**. Caddy users should notice significantly better throughput for HTTP/3. Thanks for the fantastic work, @marten-seemann!

Is this really the case that 0-RTT is default on ?
There are some security concerns on the internet and most advise not to turn this on.
If this is really on, this should at least be deactivatable.

**Comment by mholt** [comment]
0-RTT is generally safe AFAWK: https://blog.cloudflare.com/introducing-0-rtt/

The primary concern is replays, which should be managed by your application regardless. For example, if your application sends money, then you should not allow that request to be repeated, whether it's 0-RTT HTTP/3 or not.

My understanding is that 0-RTT has been carefully implemented into quic-go, but I'll let Marten comment on that since I don't know the details.

**Comment by marten-seemann** [comment]
I fully agree with @mholt.

> There are some security concerns on the internet and most advise not to turn this on.

Source? Especially for the server side (yes, a client needs to be careful, but that's not something that Caddy needs to worry about).

**Comment by mgaller** [comment]
I mean the replay attacks, but i think the server should still offer the option or at least it should be pointed out in the documentation that there is a risk there.

**Comment by marten-seemann** [comment]
There's no replay risk. It's the client's responsibility to defend against replays.

As an aside, browsers regularly retransmit non-idempotent (e.g. POST) requests, so I'm surprised people are that concerned about the replay-ability of 0-RTT.

**Comment by mholt** [comment]
If there's a legitimate attack vector demonstrated that is not the application's or client's responsibilities to mitigate, we can reopen this.

**Comment by Airtdschahn** [comment]
Dear Matt,

first at all thank you and Marten for your great work. I used nginx for over a decade, but after "experimenting" with Caddy, I never looked back at nginx. Caddy with rootless podman and systemd made my life "googol-times" easier.

- - I am running couple dozen WordPress sites with this environment, but WordPress "security culture" is not as well as Caddys.They are aware of the 0-RTT problem (https://core.trac.wordpress.org/ticket/58769), but it's WordPress 😅 and a fix / patch could be available in a few years (or a decade 😁). 

A 0-RTT turn off directive, like by nginx, would be awesome. I have forms on all WordPress sites,so now I have to turn off http/3 (and I would do anything and I mean really anything😆 to avoid switching back to nginx and certbot in containers).

Yours sincerely
Ercan

**Comment by marten-seemann** [comment]
How would the attack look like? The issue doesn't describe any details about the supposed attack.

**Comment by Airtdschahn** [comment]
Dear Marten,

damn you guys are fast😅. It is WordPress behavior not to check for the early-data header field, that I am afraid of. So even if Caddy sends a 425 respond, WordPress is not aware of it. If Caddy blocks the 0-RTT attempt, WordPress will automatically retry. With a malicious third-party in between them, it would be problematic.

I am sorry Marten, that I am not really good in this matter, but honest as a "bystander", I am/was afraid behause of all the articles about the security of 0-RTT.

Sincerely 
Ercan

**Comment by marten-seemann** [comment]
I'm confused now. Why is WordPress the client here? What kind of transaction is the one you're concerned about?

**Comment by Nurmagoz** [comment]
Reason to disable RTT-0:  

https://svs.informatik.uni-hamburg.de/publications/2018/2018-10-11-Sy-PETCON-Tracking_via_the_QUIC_Protocol.pdf

> Zero round-trip time secure connection establishment requires prefetched data which can be potentially abused for tracking

More details:

https://svs.informatik.uni-hamburg.de/publications/2019/2019-02-26-Sy-PET_Symposium-A_QUIC_Look_at_Web_Tracking.pdf

But if its enabled by default while user can have the ability to disable it within caddy, then thats still ok.

**Comment by francislavoie** [comment]
@Nurmagoz https://caddyserver.com/docs/caddyfile/options#0rtt
