### ISSUE TITLE
Use `sync.Pool` to reduce `lengthReader` allocations

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#5756]
In https://github.com/caddyserver/caddy/pull/5461 we introduced `lengthReader` to count the amount of bytes read from the request body.

We're allocating a new `lengthReader` on each request though (but only requests with a body, so not GETs). This is inefficient, it could be improved by using `sync.Pool` to reuse allocated `lengthReader` structs.

**Comment by perhapsmaple** [comment]
Hi @francislavoie, I would like to work on this issue. Are there any benchmarks that I can use to verify the performance impact of the change? Thanks!

**Comment by mholt** [comment]
You can write a [simple benchmark test](https://pkg.go.dev/testing) to measure allocations and such. :+1:

**Comment by shashank-priyadarshi** [comment]
Hi, is this issue being worked upon. I can take it up otherwise.

**Comment by francislavoie** [comment]
PRs are always welcome :+1:

**Comment by shashank-priyadarshi** [comment]
@perhapsmaple could you please let me know if you are still working on this? If not, can I please take this up!
