### ISSUE TITLE
Different response header for HEAD vs. GET request

### ISSUE THREAD

**Issue by steffenbusch** [caddyserver/caddy#5775]
## The problem I'm having:

I have an HTML file that uses the `templates` functionality and also sets a response header (for example the Content-Security-Policy). When an http HEAD request is issued against such HTML file, the response header is different compared to an http GET request. With an http HEAD request, the default value from the `header` directive is used.

But that should not happen according to my understanding.
> The HEAD method asks for a response identical to a GET request, but without the response body.

## Caddyfile

```
{
        http_port 80
        https_port 443
        skip_install_trust true
        debug

        servers :443 {
        }
        default_sni playground.stbu.net

        log debug_log {
                output file log/debug.log {
                        roll_size 10m
                        roll_keep_for 7d
                }
                format console {
                        time_format iso8601
                }
                level debug
                exclude http.log.access.log0
        }

}

https://playground.stbu.net {

        header {
                ?Content-Security-Policy "default-src 'none'; base-uri 'none'; form-action 'none';"
        }

        handle /template.html {
                root ./fileserver
                templates
                file_server
        }

        handle * {
                respond "It works"
        }

}
```

## Content of template.html

```
{{ $NONCE := uuidv4 -}}
{{ $CSP := printf "default-src 'none'; img-src 'self'; object-src 'none'; base-uri 'none'; script-src 'strict-dynamic' 'nonce-%s'; style-src 'strict-dynamic' 'nonce-%s'; frame-ancestors 'self'; form-action 'self'; block-all-mixed-content;" $NONCE $NONCE -}}
{{ .RespHeader.Set "Content-Security-Policy" $CSP -}}

<h1>Test</h1>
```

## Curl requests

GET request

```
$ curl --dump-header - https://playground.stbu.net/template.html
HTTP/2 200
alt-svc: h3=":443"; ma=2592000
content-security-policy: default-src 'none'; img-src 'self'; object-src 'none'; base-uri 'none'; script-src 'strict-dynamic' 'nonce-cfbf240c-17bf-428e-bed1-37c5e331de82'; style-src 'strict-dynamic' 'nonce-cfbf240c-17bf-428e-bed1-37c5e331de82'; frame-ancestors 'self'; form-action 'self'; block-all-mixed-content;
content-type: text/html; charset=utf-8
server: Caddy
content-length: 14
date: Tue, 22 Aug 2023 16:32:38 GMT

<h1>Test</h1>
```

The Content-Security-Policy is the one set by the template.html 👍 

Now, the HEAD request:

```
$ curl --head https://playground.stbu.net/template.html
HTTP/2 200
alt-svc: h3=":443"; ma=2592000
content-security-policy: default-src 'none'; base-uri 'none'; form-action 'none';
content-type: text/html; charset=utf-8
server: Caddy
content-length: 0
date: Tue, 22 Aug 2023 16:34:33 GMT
```

In this case it's not the Content-Security-Policy from template.html, but the one defined in the `header` directive, which says:
> Prefix with ? to set a default value for the field. The field is only written if it doesn't yet exist.

## Caddy Version

```
$ ./caddy version
v2.7.5-0.20230822022747-b69472cffd7c h1:NMG5LNyG1mTYmW+FkHygjkeNnDmOKRZQMuTGkGYuo8M=
```

Built with `xcaddy build fix-placeholder-time.now.http`

**Comment by mholt** [comment]
Ah, I can see why this is confusing, but I think this is expected.

Since the template is affecting the HTTP response headers, but templates are not evaluated when there is no body (because there is no body to evaluate the templates on), the change to the headers is not applied.

Since templates are dynamic and user-configured, I am not sure there is a way to guarantee that the headers would always be identical (because with templates, that implies the body -- the template output -- is identical).

I would suggest avoiding setting HTTP headers in your template if this functionality is important to you, as I think what you're asking the server to do is a bit unconventional/paradoxical as well: HEAD says, "don't give me a body," but template evaluation says, "evaluate this for the body".

**Comment by steffenbusch** [comment]
Hi @mholt, thanks for the swift feedback and understanding why this is confusing.

It would be great and maybe beneficial for others, if you could add 
>Since the template is affecting the HTTP response headers, but templates are not evaluated when there is no body (because there is no body to evaluate the templates on), the change to the headers is not applied.

to the documentation on https://caddyserver.com/docs/modules/http.handlers.templates with reference to `HEAD` requests regarding:
- `.RespHeader.Add`
- `.RespHeader.Del`
- `.RespHeader.Set`

I will be able to set up a workaround for my use case, which are hundreds of unit-tests / curl requests to various urls to verify that a certain header exists or is missing. So far, I have used `--head`, but I can easily change that to `GET` requests.

Thank you for your dedication and the incredible work you and your team put into Caddy.

**Comment by mholt** [comment]
Ok, yeah, we can probably make a note in the docs that templates are not evaluated when there is no body. :100: Thanks for the feedback! I'm glad you have found another way to do it :)

**Comment by steffenbusch** [comment]
Just stumbled again over this "issue" with `httpError` to test my custom error pages 😂

```html
# raise-403.html
<h1>A 403 error test</h1>
{{httpError 403}}
```
