### ISSUE TITLE
Surprising behavior with empty handle_response route

### ISSUE THREAD

**Issue by pkoenig10** [caddyserver/caddy#5776]
**Caddy version: v2.7.4 h1:J8nisjdOxnYHXlorUKXY75Gr6iBfudfoGhrJ8t7/flI=**

The `handle_response` [documentation](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#intercepting-responses) states:

> When a response handler is invoked, the response from the backend is not written to the client, and the configured handle_response route will be executed instead, and it is up to that route to write a response. If the route does not write a response, then request handling will continue with any handlers that are [ordered after](https://caddyserver.com/docs/caddyfile/directives#directive-order) this reverse_proxy.

Given this, I would expect a empty `handle_response` route to cause the request handling to continue with the next handler. But that doesn't appear to be the case. Furthermore, the behavior appears to be inconsistent and dependent upon the presence or absence of other directives.

## Reproductions

In all the examples below, I am making a request to `http://localhost`.

1. Given this Caddyfile, I'd expect the response to be handled by the `handle_response @ok` route and then continue to the `respond 299` directive. However the actual response is a 499.

    ```
    {
        auto_https off
        order respond after reverse_proxy
    }

    :80 {
        reverse_proxy example.com {
            header_up Host "example.com"

            @ok status 200
            handle_response @ok {
            }

            handle_response {
                respond 499
            }
        }

        respond 299
    }
    ```

2. If I add a useless directive to the `handle_response @ok` route, then that route is used as expected. The actual response here is a 299

    ```
    {
        auto_https off
        order respond after reverse_proxy
    }

    :80 {
        reverse_proxy example.com {
            header_up Host "example.com"

            @ok status 200
            handle_response @ok {
                skip_log
            }

            handle_response {
                respond 499
            }
        }

        respond 299
    }
    ```

2. If I remove the `handle_response` route, then I'd expect to continue to the `respond 299` directive. But the actual response here is the response from the upstream `exmaple.com` request. This is particularly surprsing since `copy_response` is not used anywhere.

    ```
    {
        auto_https off
        order respond after reverse_proxy
    }

    :80 {
        reverse_proxy example.com {
            header_up Host "example.com"

            @ok status 200
            handle_response @ok {
            }
        }

        respond 299
    }
    ```

**Comment by WeidiDeng** [comment]
Caddy will sort handler [directives automatically](https://caddyserver.com/docs/caddyfile/directives#directive-order)(`ordered after` is a link). Although in Caddyfile `respond` is after `reverse_proxy`, it's actually before `reverse_proxy` after sorting.

To force the behavior you wanted you need to use [`route`](https://caddyserver.com/docs/caddyfile/directives/route).

**Comment by francislavoie** [comment]
@WeidiDeng they are using the `order` global option though which is meant to get around that problem. I'm not convinced this is solved.

**Comment by WeidiDeng** [comment]
My bad 😅

**Comment by WeidiDeng** [comment]
Yeah, I can reproduce all three cases. It's definitely a bug.

**Comment by pkoenig10** [comment]
For context, my original configuration had another `reverse_proxy`  directive where the `respond 299` is in the example above. I just used `respond` to make the reproduction a bit more minimal. The ordering isn't really relevant to the issue I was experiencing - it's just there to make the reproduction work.

**Comment by francislavoie** [comment]
@WeidiDeng found that the cause is this:

https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L851-L855

We're not sure exactly what the fix will be though, because there was a reason for that code to exist.

**Comment by mholt** [comment]
That line initially came from this commit:

https://github.com/caddyserver/caddy/commit/538ddb85876001976fa0c76f10b912c0870fe6d7#diff-a248c9a1ec018edea8b377d155bc1df1a642bf79d00ababb5cdacc6b86c5733dR534-R552

I believe it did/does not make sense to intercept response handling if there are no routes configured to do anything with it. At the time, at least.

**Comment by pkoenig10** [comment]
I'm trying to do something similar to `forward_auth`. If the response is a 200 I want to fallthrough to the next handler, otherwise I want to handle it in some way. Is there a better or more idiomatic way to accomplish this?

Unfortunately there's no `not` response matcher, otherwise I could do something like
```
@not_ok not status 200
handle_response @not_ok {
    // handle errors
}
```

**Comment by francislavoie** [comment]
@mholt yeah I know; the history is handle response used to be overloaded in the Caddyfile to do both status code changes and routes but I felt that made no sense so I split it up in two but in JSON it's still overloaded so this condition is how that's split up. The fix is probably to change it to checking if the status is not empty, instead of checking if the routes are empty; that'll still split it up but allow empty routes to fall through _I think_ but I can't test the idea right now (I'm sick and in bed).

@pkoenig10 for forward auth you're probably always doing request header copying so that's why we didn't notice the problem earlier. You could just do a benign header copy as well to do what you're trying to do for now. Thankfully there's a workaround for your case. No need to document the bug when we plan to fix it.
