### ISSUE TITLE
Caddy reverse_proxy with Intel AMT Remote Desktop issue

### ISSUE THREAD

**Issue by vibbow** [caddyserver/caddy#5792]
I have a very rare use case for caddy.

I have a PC desktop with Intel AMT Remote Desktop feature enable, this feature exposed a web page in port 16993 and can remote view the desktop from the webpage.

![图片](https://github.com/caddyserver/caddy/assets/6408107/52c2be69-116b-4e4f-ac05-6fa2459796d3)

Now I'm using caddy to reverse proxy the Intel AMT webpage to public internet, so I can remotely turn on/off this PC.

```
my-super-secure-amt-management-domain.com {
        tls server.crt server.key

        reverse_proxy {
                to 192.168.188.50:16993

                transport http {
                        tls
                        tls_insecure_skip_verify
                }
        }
}
```

The problem is: the Remote Desktop feature only work once after caddy server start.

Once I disconnect and try connect again, it will failed. Restart web browser didn't help.

If I restart the caddy server, it will work again (and only once).

---
  
When the Remote Desktop connect is successful, I can't see any log related to "ws-redirection" or "Upgrade"

But when it failed, I can see the following access log

```
{
  "level": "error",
  "ts": 1693595069.701354,
  "logger": "http.log.access.log1",
  "msg": "handled request",
  "request": {
    "remote_ip": "hidden-ip",
    "remote_port": "4478",
    "client_ip": "hidden-ip",
    "proto": "HTTP/1.1",
    "method": "GET",
    "host": "my-super-secure-amt-management-domain.com",
    "uri": "/ws-redirection",
    "headers": {
      "Accept": [
        "*/*"
      ],
      "Accept-Language": [
        "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br"
      ],
      "Sec-Websocket-Extensions": [
        "permessage-deflate"
      ],
      "Authorization": [],
      "Upgrade": [
        "websocket"
      ],
      "User-Agent": [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0"
      ],
      "Sec-Websocket-Key": [
        "T6JsxoRoMC8ZljYf+eo8QA=="
      ],
      "Connection": [
        "keep-alive, Upgrade"
      ],
      "Sec-Fetch-Mode": [
        "websocket"
      ],
      "Sec-Fetch-Site": [
        "same-origin"
      ],
      "Pragma": [
        "no-cache"
      ],
      "Sec-Websocket-Version": [
        "13"
      ],
      "Origin": [
        "https://my-super-secure-amt-management-domain.com"
      ],
      "Sec-Fetch-Dest": [
        "empty"
      ],
      "Cache-Control": [
        "no-cache"
      ]
    },
    "tls": {
      "resumed": true,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "http/1.1",
      "server_name": "my-super-secure-amt-management-domain.com"
    }
  },
  "bytes_read": 0,
  "user_id": "",
  "duration": 0.006409585,
  "size": 0,
  "status": 400,
  "resp_headers": {
    "Date": [
      "Sat, 2 Sep 2023 02:53:13 GMT"
    ],
    "Content-Length": [
      "0"
    ],
    "Permissions-Policy": [
      "interest-cohort=()"
    ],
    "Referrer-Policy": [
      "no-referrer-when-downgrade"
    ],
    "X-Content-Type-Options": [
      "nosniff"
    ],
    "X-Frame-Options": [
      "sameorigin"
    ],
    "Alt-Svc": [
      "h3=\":443\"; ma=2592000"
    ]
  }
}
```

I know it's a very rare use case, and you may not have the environment to reproduce this issue.

I'm glad to provide any help to solve issue.

**Comment by vibbow** [comment]
My caddy version is:
v2.7.4 h1:J8nisjdOxnYHXlorUKXY75Gr6iBfudfoGhrJ8t7/flI=

It's installed from cloudsmith apt

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

Make sure to enable to debug global option to get more detailed logs.
