### ISSUE TITLE
celmatcher.go: cannot use func

### ISSUE THREAD

**Issue by greenpau** [caddyserver/caddy#5797]
@mholt , upgrading to 2.7.4. Please advise.

`go.mod` follows:

```
module github.com/greenpau/caddy-trace

go 1.20

require (
    github.com/caddyserver/caddy/v2 v2.7.4
    github.com/google/uuid v1.3.1
    go.uber.org/zap v1.25.0
)
```

```
$ go version
go version go1.20.7 linux/amd64
```

The test fail with the following errors:

```
BUILD| github.com/caddyserver/caddy/v2/modules/caddyhttp
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:462:9: cannot use func(eh parser.ExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *common.Error) {…} (value of type func(eh parser.ExprHelper, target *expr.Expr, args []*expr.Expr) (*expr.Expr, *common.Error)) as parser.MacroExpander value in return statement
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:479:13: eh.GlobalCall undefined (type parser.ExprHelper has no field or method GlobalCall)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:479:37: eh.Ident undefined (type parser.ExprHelper has no field or method Ident)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:479:66: cannot use matchArgs (variable of type []*expr.Expr) as []ast.Expr value in argument to eh.NewList
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:488:9: cannot use func(eh parser.ExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *common.Error) {…} (value of type func(eh parser.ExprHelper, target *expr.Expr, args []*expr.Expr) (*expr.Expr, *common.Error)) as parser.MacroExpander value in return statement
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:495:14: eh.GlobalCall undefined (type parser.ExprHelper has no field or method GlobalCall)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:495:38: eh.Ident undefined (type parser.ExprHelper has no field or method Ident)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:509:9: cannot use func(eh parser.ExprHelper, target *exprpb.Expr, args []*exprpb.Expr) (*exprpb.Expr, *common.Error) {…} (value of type func(eh parser.ExprHelper, target *expr.Expr, args []*expr.Expr) (*expr.Expr, *common.Error)) as parser.MacroExpander value in return statement
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:545:14: eh.GlobalCall undefined (type parser.ExprHelper has no field or method GlobalCall)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:545:38: eh.Ident undefined (type parser.ExprHelper has no field or method Ident)
     | ../../../../pkg/mod/github.com/caddyserver/caddy/v2@v2.7.4/modules/caddyhttp/celmatcher.go:545:38: too many errors
```

**Comment by mholt** [comment]
Am mobile currently, but what happens if you run go mod tidy and then run the tests?

**Comment by greenpau** [comment]
@mholt , the cleaning of cache and tidying does not help.

**Comment by mohammed90** [comment]
This commit from google/cel-go broke it:

https://github.com/google/cel-go/commit/0b8fcf3578818774b1b1a945797ba357173708ca

**Comment by francislavoie** [comment]
We didn't bump the dependency though did we? I'm confused.

**Comment by mohammed90** [comment]
> We didn't bump the dependency though did we? I'm confused.

Not an issue with Caddy nor the Go dep management. I am not able to replicate it. I've successfully built Caddy v2.7.4 with the caddy-trace module without issues.

@greenpau, make sure you don't upgrade cel-go accidentally to HEAD.

**Comment by greenpau** [comment]
@mohammed90 , thank you for looking into it! Yes, that was it. the cel-go v1.18 has the issue. I downgraded it to v1.17 and it is ok now. It was not at the HEAD, but rather latest release. The changes in v1.18 contain the changes to the signature you mentioned.

**Comment by mohammed90** [comment]
> @mohammed90 , thank you for looking into it! Yes, that was it. the cel-go v1.18 has the issue. I downgraded it to v1.17 and it is ok now. It was not at the HEAD, but rather latest release. The changes in v1.18 contain the changes to the signature you mentioned.

Thanks for the confirmation!

**Comment by francislavoie** [comment]
I don't understand how you upgraded CEL in the first place.

**Comment by greenpau** [comment]
> I don't understand how you upgraded CEL in the first place.

@francislavoie ,

```
go get -u
```

and it picked the latest `cel-go` version with the func signature changes.

**Comment by francislavoie** [comment]
Oh, I suggest you always use `go mod tidy`, after manually editing go.mod, don't use `go get -u`.

**Comment by mohammed90** [comment]
I'd go as far as saying only touch your direct deps; and let them (upstream) manage their deps (your transitive deps) because they know how those will impact the code, unless you really have to go out of your way to upgrade the transitive dependency because of an urgent need.

**Comment by mholt** [comment]
Thanks for investigating this, @mohammed90! And for the tip @francislavoie
