### ISSUE TITLE
Paths get mangled when using multiple caddy "layers"

### ISSUE THREAD

**Issue by tezlm** [caddyserver/caddy#5801]
Client -> caddy1 -> caddy2 -> host

caddy1's config file:

```
example.com {
    reverse_proxy caddy2
}
```

caddy2's config file:

```
http://example.com {
    reverse_proxy host
}
```

A request for `https://example.com/example%2fpath` will reach host as `https://example.com/example/path`

**Comment by mholt** [comment]
Is this reproducible using only Caddy 2?

(We don't support Caddy 1 anymore, so reproducing without Caddy 1 will be required if we are to fix a bug.)

**Comment by tezlm** [comment]
After some investigation, this doesn't seem to be a caddy problem. Sorry about that!

**Comment by tezlm** [comment]
After some investigation, this doesn't seem to be a caddy problem. Sorry about that!
