### ISSUE TITLE
Enhancement: file-server browser, allow for listing symlinks as symlinks 

### ISSUE THREAD

**Issue by Forza-tng** [caddyserver/caddy#5810]
Caddy currently resolves symlink targets and displays the target information in its directory listing.

I would like an option to show links as links to the destination instead of appearing as a real file.

Example:
```
a/
b/
foo.txt
bar.txt
baz.txt -> a/baz.txt
...
```
Clicking the link should still download the file as before.

**Comment by armadi1809** [comment]
@mholt would like to take a shot at this if you guys are still planning on implementing this feature. 

Just to get more context, we are here referring to the `caddy file-server` command right? Thank you.

**Comment by mohammed90** [comment]
Sure. Feel free to send a PR.

> we are here referring to the `caddy file-server` command right?

No, this is about the `browse` sub-directive in `file_server` handler, regardless of whether it's run through configuration file or the `caddy file-server` command.
