### ISSUE TITLE
Enhancement: Support dynamic ip ranges/ip lists for `client_ip` directive

### ISSUE THREAD

**Issue by tuzzmaniandevil** [caddyserver/caddy#5813]
The use case for this is to dynamically fetch a list of IP addresses that should be matched for each request, This could be used to block IP's or IP ranges based on some activity by an upstream server or a security scanning tool of some sort.

An example caddyfile might look like this:

```caddyfile
:80 {
  @denied client_ip dynamic my_custom_plugin
  abort @denied
}
```

This could possibly use the existing [IPRangeSource](https://github.com/caddyserver/caddy/blob/1e0dea59efc606f0eaec09993649930d12961bb9/modules/caddyhttp/ip_range.go#L51) interface that is available or a new interface might need to be introduced.

I'm happy to do the work and submit a PR but I would like to get feedback first to see if this is even a good idea.

I'm hoping to use this at my company, we are working on a couple Caddy plugins already.

**Comment by francislavoie** [comment]
Since that requires a plugin anyway, you could just make your own matcher plugin that sources the data however it wants. You don't need to specifically use the built in matcher. You can even copy the code for the client IP matcher as a basis and just rename it to avoid the conflict.

**Comment by mholt** [comment]
Yeah, I agree, this would be better as a plugin.

@tuzzmaniandevil Feel free to implement it! You can even just have it in your own repo and publish it to the Caddy website if you think it's generally useful.

> I'm hoping to use this at my company, we are working on a couple Caddy plugins already.

This is great! I'd love to know more about your company and your use case.

**Comment by tuzzmaniandevil** [comment]
Great thanks @francislavoie and @mholt for the advice and direction :-)

How would I go abot publishing the plugin to the Caddy website?

It's now available here:
https://github.com/tuzzmaniandevil/caddy-dynamic-clientip

**Comment by mholt** [comment]
Great! Just go to ["Account" on the Caddy website](https://caddyserver.com/account/) and after logging in you'll find a link to "Claim package" -- that'll do it :)
