### ISSUE TITLE
How to specify path for reverse proxy

### ISSUE THREAD

**Issue by yungd1plomat** [caddyserver/caddy#5817]
I'm using docker compose with asp net app and caddy
My config:
```Json
{
  "handle": [
    {
      "handler": "subroute",
      "routes": [
        {
          "handle": [
            {
              "handler": "reverse_proxy",
              "upstreams": [
                {
                  "dial": "constests:4000/contest/examplecontest"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "match": [
    {
      "host": [
        "examplecontest.com"
      ]
    }
  ],
  "terminal": true
}
```

I want that if a user goes to the examplecontest.com site it will be proxied through constests:4000/contest/examplecontest, but it doesn't seem to work.

It gives the error:
```Json 
"msg":"dial tcp: lookup contest/examplecontest: no such host"
"err_trace":"reverseproxy.statusError (reverseproxy.go:1248)"
```

How can this be fixed? The point is that I need to dynamically bind domains to a specific path via the api on the site

**Comment by francislavoie** [comment]
You need to use the `rewrite` handler.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
