### ISSUE TITLE
Error using caddy reverse proxy qbittorrent

### ISSUE THREAD

**Issue by MiniDay** [caddyserver/caddy#5821]
My usage environment: NAS machine+Docker

Caddy image: https://hub.docker.com/_/caddy
qbittorrent image: https://hub.docker.com/r/linuxserver/qbittorrent
qbittorrent web port: 8080

Both caddy and qbittorrent use the host network mode

caddy config:
```
:80 {
	reverse_proxy /qbit* localhost:8080
}
```

When I start Caddy using this configuration, I access the uri `/qbit` and return 404
I have also tried configurations like `reverse_proxy /qbit/ localhost:8080`, but it still doesn't work (return 404)

I saw the relevant configuration of nginx in this document: `https://github.com/qbittorrent/qBittorrent/wiki/NGINX-Reverse-Proxy-for-Web-UI`

So I tried starting an nginx container in Docker and copying these configurations into it. when using nginx, qbittorrent can be proxied normally.
The following is the complete configuration I tested
```
#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;

        location /qbit/ {
            proxy_pass         http://127.0.0.1:8080/;
            proxy_http_version 1.1;

            proxy_set_header   Host               127.0.0.1:8080;
            proxy_set_header   X-Forwarded-Host   $http_host;
            proxy_set_header   X-Forwarded-For    $remote_addr;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
```

I noticed that the configuration of nginx includes configurations such as x-forward, and the HTTP version is 1.1. Therefore, I have changed my caddy configuration as follows:
```
:80 {
	reverse_proxy /qbit* localhost:8080 {
		transport http {
			versions 1.1
		}
		header_up Host localhost:8080
	}
}
```

The final result is still not good, qbittorent still returns 404, The following is caddy's log.

```
{"level":"debug","ts":1694781305.6513753,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"localhost:8080","duration":0.001237124,"request":{"remote_ip":"::1","remote_port":"60390","client_ip":"::1","proto":"HTTP/1.1","method":"GET","host":"localhost:8080","uri":"/qbit/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Cache-Control":["max-age=0"],"X-Forwarded-For":["::1"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Sec-Fetch-Dest":["document"],"Upgrade-Insecure-Requests":["1"],"Accept-Encoding":["gzip, deflate, br"],"X-Forwarded-Proto":["http"],"Sec-Fetch-Site":["none"],"Accept-Language":["zh-CN,zh;q=0.9"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.81"],"Sec-Fetch-Mode":["navigate"],"Cookie":[],"X-Forwarded-Host":["nas.hamster3.cn"],"Sec-Ch-Ua":["\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Microsoft Edge\";v=\"116\""],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-User":["?1"]}},"headers":{"X-Content-Type-Options":["nosniff"],"X-Xss-Protection":["1; mode=block"],"Connection":["keep-alive"],"Content-Length":["9"],"Content-Security-Policy":["default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';"],"Content-Type":["text/plain; charset=UTF-8"],"Date":["Fri, 15 Sep 2023 12:35:05 GMT"],"Referrer-Policy":["same-origin"]},"status":404}
```

In addition, I have tried to search for a lot of information online, and I have tried the following, but none of them have worked

- https://caddy.community/t/qbittorrent-subdirectory/17337
- https://caddy.community/t/qbittorrent-and-caddy-reverse-proxy/16281
- https://caddy.community/t/qbittorrent-webui-and-caddy-v2/11084
- https://caddy.community/t/qbittorrent-web-ui-reverse-proxy-help/2569
- https://www.reddit.com/r/selfhosted/comments/13frpwv/how_to_set_up_reverse_proxy_for_qbittorrent_web/

My English is not good. This issue was written using translation software. If there is any offense, please forgive my rudeness

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by MiniDay** [comment]
Thank you for your help. I have now completed the configuration. The complete configurations available are as follows:
```
:80 {
	# qbittorrent
	redir /qbit /qbit/
	handle_path /qbit/* {
		reverse_proxy localhost:8080
	}
}
```
