### ISSUE TITLE
Usage of Address Validation Tokens and 0-RTT for HTTP/3 connections

### ISSUE THREAD

**Issue by John-Athan** [caddyserver/caddy#5822]
I am currently running a very basic caddy server (Version 2.7.4) that serves static files from a directory:
```
<my-domain> {
    root * ./www
    templates
    encode zstd gzip
    file_server
}
```

This is working great, and I see HTTP/3 being used by most clients.
However I would like to make use of the 0-RTT functionality enabled in [Version 2.7.3](https://github.com/caddyserver/caddy/releases/tag/v2.7.3)
```
Significant HTTP/3 performance improvements (upstream in quic-go) including enabling 0-RTT. Caddy users should notice significantly better throughput for HTTP/3. Thanks for the fantastic work, @marten-seemann!
```

I can only see 0-RTT being used by clients using the Firefox browser, though. Chromium-based clients will not try to send 0-RTT data for some reason. They will always do a full 1-RTT handshake before sending data, even when they could definitely use the 0-RTT packet type. 

The issue should be reproducible quite easily:
* Set up an instance of caddy 2.7.4 and make sure it is capable of serving HTTP/3 content
* Access any page served by that instance using Firefox. You should see HTTP/3 being used
* If you reload the page after the connection timed out, you should see 0-RTT packets being sent (e.g. via Wireshark)
* Now try the same thing using Google Chrome. You should see only full handshakes.

I also observed that, even though address validation tokens are sent after each successful reconnect, only Firefox uses these tokens during the next reconnect. Chromium-based browsers do not use the token at all.
 
Is there something I am overlooking, or is 0-RTT no supported on Chromium-based browsers yet?

**Comment by mholt** [comment]
Looks like it is not supported by Chrome yet. https://chromestatus.com/feature/5447945241493504

Thanks for asking! Let me know if there's any Caddy questions we can help with.

**Comment by John-Athan** [comment]
Thanks for your reply!
While the feature you are referring to is TLS 1.3's 0-RTT fuction, I was referring to the [0-RTT packets](https://datatracker.ietf.org/doc/html/rfc9000#section-17.2.3) as well as [address validation tokens ](https://datatracker.ietf.org/doc/html/rfc9000#name-address-validation-during-c)of the QUIC protocol. Sorry for not clarifying that!

Chrome is definitely capable of handling early data in HTTP/3, as it will happily connect to any of Google's own services using mentioned address validation tokens and 0-RTT packets.
I am not quite sure if this is an issue with Caddy, quic-go or Google Chrome. However, maybe it is worth looking into this because most browsers are Chromium-based and it would be a pity if we couldn't get 0-RTT running on them. 

I'm also open to diving deeper into this topic or providing information if required!

**Comment by francislavoie** [comment]
It's not an issue with Caddy specifically, we don't do anything specific with HTTP/3 other than plugging it into quic-go. Best if you ask there, but still it looks like it's simply an issue with Chrome not fully supporting the specific features you're looking for.
