### ISSUE TITLE
i write Hexonet DNS module for Caddy, how to add plugin module

### ISSUE THREAD

**Issue by orange-jacky** [caddyserver/caddy#5834]
https://github.com/tojjx/caddy-dns-hexonet
https://github.com/tojjx/libdns-hexonet

**Comment by mholt** [comment]
Awesome!! Thanks for contributing a plugin!

Took a quick look at the code and didn't see anything problematic at a glance. I've created repositories in the libdns and caddy-dns orgs and given you permission to publish to them.

Please push to those repos :) **Just make sure to update your go.mod for the new repo paths.**

You can then publish your plugin on caddyserver.com by creating an account and going to your dashboard, then clicking "Claim package"

Thanks again!

**Comment by orange-jacky** [comment]
I push it, and failed.

hexonet git:(main) git push -u origin main
remote: Permission to libdns/hexonet.git denied to orange-jacky.
fatal: unable to access 'https://github.com/libdns/hexonet.git/': The requested URL returned error: 403

**Comment by orange-jacky** [comment]
> Awesome!! Thanks for contributing a plugin!
> 
> Took a quick look at the code and didn't see anything problematic at a glance. I've created repositories in the libdns and caddy-dns orgs and given you permission to publish to them.
> 
> Please push to those repos :) **Just make sure to update your go.mod for the new repo paths.**
> 
> You can then publish your plugin on caddyserver.com by creating an account and going to your dashboard, then clicking "Claim package"
> 
> Thanks again!


I push it, and failed.

hexonet git:(main) git push -u origin main
remote: Permission to libdns/hexonet.git denied to orange-jacky.
fatal: unable to access 'https://github.com/libdns/hexonet.git/': The requested URL returned error: 403

hexonet git:(main) git remote -v
origin	https://github.com/libdns/hexonet.git (fetch)
origin	https://github.com/libdns/hexonet.git (push)

**Comment by mholt** [comment]
Make sure you accept the invitation first

**Comment by orange-jacky** [comment]
> Make sure you accept the invitation first

I didn't receive an invitation, can you invitation me again   my account is orange.jackylee@gmail.com
