### ISSUE TITLE
httpInclude through proxy with X-Forwarded-For

### ISSUE THREAD

**Issue by kai-tub** [caddyserver/caddy#5835]
As discussed in the forum, I am creating this issue to track the progress of the following discussion: https://caddy.community/t/file-server-httpinclude-with-x-forwarded-for/21087

TL;DR:

Goal: Allow the virtual request of `httpInclude` of a `file_server` to include a `RemoteAddr` so that a reverse proxy can set `X-Forwarded-For`.

Otherwise, the `X-Forwarded-For` header is not set and not included in the endpoint that processes the original `httpInclude` request, which is required for applications that trust this header and return different text data depending on its value.

**Comment by francislavoie** [comment]
For ref, the fix will need to be applied somewhere in here:

https://github.com/caddyserver/caddy/blob/a306c5f769d876adf1f93d350c8a523b2c3fe760/modules/caddyhttp/templates/tplcontext.go#L186

**Comment by AshwinKul28** [comment]
Hello, I can take this issue. I will work on it later today. thanks

**Comment by francislavoie** [comment]
@kai-tub could you try building from #5845 to confirm the fix? Thanks!

**Comment by kai-tub** [comment]
Hey, I can confirm that the issue is resolved with the PR requested in #5845  :tada: 
With the changes, my API that is called by the `httpInclude` request has now access to the `X-Forwarded-For` headers :)

Thank you both for working on the issue! :) 
I will let the PR auto-close the issue :)
