### ISSUE TITLE
Can't use TLS with legacy certs

### ISSUE THREAD

**Issue by djeikyb** [caddyserver/caddy#5839]
I'm trying to wrap a reverse proxy around a legacy server with a legacy cert

```
reverse_proxy https://10.1.1.100:443
```

But I get this error:

```
http.log.error	tls: failed to parse certificate from server: x509: invalid RDNSequence: invalid attribute value: invalid PrintableString
```

Now, when I use openssl or dotnet or python etc etc, I have a problem with the x509 extension "Subject Alternative Name" because someone hardcoded an ip address (fml). But! All these libraries accept the cert as well-formed and readable, and leave it to my code to decide if the san dns name is a deal breaker. Also, all these libs let me say "yeah, let's speak tls, but ignore the cert".

Caddy, and this is entirely golang's fault, refuses to interact with the server completely. Simply because someone six years ago issued a self-signed twenty year cert for an appliance with an underscore in the subject's CN.

There are [23 reports of similar issues](https://github.com/golang/go/issues?q=is%3Aissue+RDNSequence), and the golang team has so far decided this is a "won't fix / kick rocks" situation. Here are a few:

- https://github.com/golang/go/issues/62607
- https://github.com/golang/go/issues/36044
- https://github.com/golang/go/issues/21339

One of the issues suggests folks use a better library, [zman/zcrypto](https://github.com/zmap/zcrypto). I'm not sold on that particular lib, but it sure would be nice if Caddy could speak TLS even when some poor lost soul slips up and confuses `_` as something that could be printable.

**Comment by francislavoie** [comment]
We're not in the business of supporting old/broken/legacy protocols or certificates. The purpose of Caddy is to provide an easy to use server with modern, secure defaults. Supporting legacy stuff would be in conflict with that.

Feel free to fork Caddy and implement changes you need though. But we're not interested in changing Caddy to support this kind of usecase. Sorry.

**Comment by mholt** [comment]
@djeikyb I sympathize, but as Francis said, this is probably counter to our project's goals.

However, you can configure Caddy -- against all good judgment -- to ignore the server's TLS certificate with `tls_insecure_skip_verify` as shown here: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#tls_insecure_skip_verify

I've never seen that error before so I don't 100% know if it'll work for you, but it might be worth a shot -- just be aware that you're totally insecure, but it should allow you to at least connect if that's all you want.
