### ISSUE TITLE
Example HTTP/3 conf and Port change

### ISSUE THREAD

**Issue by Karthikdasari0423** [caddyserver/caddy#5866]
Hi Team,

I am very new to caddy and I have installed caddy in my Ubuntu machine.

I am planning to change my quic conf in caddy  conf file but unable to do. 

Could you please share example conf file and any info where can i change my listening port?

```
root@ubuntu:~# caddy version
v2.7.4 h1:J8nisjdOxnYHXlorUKXY75Gr6iBfudfoGhrJ8t7/flI=

```

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by Karthikdasari0423** [comment]
Hi @francislavoie 

Thank you.
