### ISSUE TITLE
Trusted proxies / authelia

### ISSUE THREAD

**Issue by wouterverduin** [caddyserver/caddy#5878]
Hi guys! I am attempting to setup authelia for trusted proxies.

Following the guidelines i have setup authelia and i am at the point of attempting to get authelia integrated with caddy. So far i have no error logs in authelia so i am assuming i am misunderstanding something with caddy and actualy not sure which direction to go from here... Hopefully you guys can help me!

What i got so far:

Caddy file:

```
(trusted_proxy_list) {
       ## Uncomment & adjust the following line to configure specific ranges which should be considered as trustworthy.
       trusted_proxies 192.168.1.1/24
}
auth.mydomain.com {
 reverse_proxy 192.168.1.50:9091 {
   import trusted_proxy_list
   }
 }
test.mydomain.com {
  forward_auth 192.168.1.50:9091 {
    uri /api/verify?rd=https://auth.mydomain.com
    copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
   }
 reverse_proxy 192.168.1.50:86
}
```

The logs throw me this error:

`{"level":"error","ts":1697033462.523886,"logger":"http.log.error","msg":"dial tcp 192.168.1.50:9091: connect: connection refused","request":{"remote_ip":"192.168.1.1","remote_port":"44042","client_ip":"192.168.1.1","proto":"HTTP/2.0","method":"GET","host":"test.mydomain.com","uri":"/","headers":{"Sec-Ch-Ua-Platform":["\"Windows\""],"Sec-Fetch-Mode":["navigate"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"117\", \"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"117\""],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Sec-Fetch-Dest":["document"],"Accept-Language":["nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"stock.wouterverduin.nl"}},"duration":0.000211788,"status":502,"err_id":"a7quzpb74","err_trace":"reverseproxy.statusError (reverseproxy.go:1248)"}
`

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
