### ISSUE TITLE
Can't pull caddy:2.7.5 on linux amd64

### ISSUE THREAD

**Issue by Zoey2936** [caddyserver/caddy#5882]
Log: 
```
2.7.5: Pulling from library/caddy 
docker: no matching manifest for linux/amd64 in the manifest list entries.
```

When looking on docker hub the tag 2.7.5 also has no linux/amd64 version

**Comment by francislavoie** [comment]
Please have patience. See https://github.com/caddyserver/caddy-docker/issues/324#issuecomment-1758956763

**Comment by Zoey2936** [comment]
Thanks, I will wait
