### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by iliyofksy** [caddyserver/caddy#5884]
Hi 

I'm trying to start Caddy on ECS fargate, I pulled the docker image with the latest tag, passed the Caddyfile, and then pushed the image into the ECR repository. The same image is running local but when I deploy it in ECS it throws this error:

`CannotPullContainerError: containerd: pull command failed: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1369f41] goroutine 1 [running]: main.(*puller).pullWithClient(0xc00066bbc0, {0x18dc8a0, 0xc0006424e0}, {0x18d6988, 0xc00039e000}, 0xc00034ef70, {0x18d6938, 0xc0004198c0}) /root/go/src/github.com/aws/two/puller/pull.go:198 +0x501 main.(*puller).Pull(0xc00066bbc0, {0x18dc8a0, 0xc000357d10}, 0xc00034ef70, {0x18d6938, 0xc0004198c0}) /root/go/src/github.com/aws/two/puller/pull.go:147 +0x2a7 main.(*puller).pullImage(0x18dc8a0?, {0x18dc8a0, 0xc000357d10}, 0xc00034ef70, {0x18d6938?, 0xc0004198c0?}) /root/go/src/github.com/aws/two/puller/pull.go:350 +0x47 main.main() /root/go/src/github.com/aws/two/puller/main.go:75 +0x587 : exit status 2`

Any suggestion or help would be really appreciated. Thanks

**Comment by francislavoie** [comment]
That doesn't look like it has anything to do with Caddy. That stack trace doesn't point to any Caddy code.

**Comment by mohammed90** [comment]
The error isn't from Caddy. It's from AWS' tool, Puller. Take it with this repo: https://github.com/aws/two.

**Comment by iliyofksy** [comment]
Thanks

**Comment by walidshaari** [comment]
can you post the ECS caddyserver task definition?
