### ISSUE TITLE
TLS handler: remove `terminal` from adapted JSON

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#5887]
Caddy: v2.7.5 (built from master)

**Background**: 
I use API to dynamically add/remove a large number of routes serving only ports 80 and 443. Caddy runs on a production server, which serves other services and thus must have a minimum viable config to boot. I need to use `path matching` with the `handle_path` directive to add more services, sitting on either HTTP(80) or HTTPS(443)

**Issue**:
For TLS connections, `caddy run/adapt`returns an adapted config, which has a list of path handlers. The last handler is terminated with the `"terminal": true` field. Adding new routes by appending that list with caddy API physically adds the route, which is, however is NOT served.

Interestingly, for HTTP routes, `terminal` directive is NOT added.

**Workaround**:
Run `caddy adapt > init.json` and manually remove the `"terminate": true` directives. Then run caddy with `caddy run -c init.json`.
This works fine, but requires manual work each time and is error prone.

Please rethink the use of this directive and remove it or implement another way to append dynamic routes on the active port  :pray: 

**Example**:
Caddyfile
```sh
{
  debug
}

// HTTP doesn't add the `terminal` field
:80 {
handle_path /hello {
  respond "Hello from localhost"
  }
}

// TLS adds `terminal`
my.example.com {
  handle_path /hello {
    respond "Hello from example.com"
  }
}
```
Adapted JSON
```json
{
  "logging": { "logs": { "default": { "level": "DEBUG" } } },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [":443"],
          "routes": [
            {
              "match": [{ "host": ["my.example.com"] }],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "subroute",
                          "routes": [
                            {
                              "handle": [
                                {
                                  "handler": "rewrite",
                                  "strip_path_prefix": "/hello"
                                }
                              ]
                            },
                            {
                              "handle": [
                                {
                                  "body": "Hello from example.com",
                                  "handler": "static_response"
                                }
                              ]
                            }
                          ]
                        }
                      ],
                      "match": [{ "path": ["/hello"] }]
                    }
                  ]
                }
              ],
              "terminal": true <--------------------------   That's the problem !!!!
            }
          ]
        },
        "srv1": {
          "listen": [":80"],
          "routes": [
            {
              "match": [{ "path": ["/hello"] }],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        { "handler": "rewrite", "strip_path_prefix": "/hello" }
                      ]
                    },
                    {
                      "handle": [
                        {
                          "body": "Hello from localhost",
                          "handler": "static_response"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    }
  }
}

```

**Comment by mholt** [comment]
`"terminal": true` is added only to separate the different site blocks of the Caddyfile, to ensure that if one is evaluated, no other blocks are. This is really important.

If you are using JSON config, and you do not have those requirements, you can simply remove the `"terminal": true` from your JSON configs.

I do not think it is a good idea to mix Caddyfile with JSON repeatedly. Maybe use the Caddyfile as a starting point and then tweak to your needs.

**Comment by francislavoie** [comment]
"terminal" isn't a directive, it's an option for the `subroute` handler which says "don't run routes after this one". This is added because a site block with a host matcher should be terminal; requests should not drop through to the routes of another site block, because that would cause confusing and bad behaviour.

The :80 site does not produce a subroute because there's no host matcher (you didn't provide a host) so it's a "catch all" route and doesn't need to be terminal because it's last anyway.

I don't understand what you think is a problem. This is normal and expected behaviour.
