### ISSUE TITLE
include template function with arguments

### ISSUE THREAD

**Issue by UweOhse** [caddyserver/caddy#5897]
The documentation for the include template function states:

      Includes the contents of another file and renders in-place.
      Optionally can pass key-value pairs as arguments to be accessed by the included file.

     {{include "path/to/file.html"}}  // no arguments
     {{include "path/to/file.html" "arg1" 2 "value 3"}}  // with arguments

How does one access these arguments?

**Comment by UweOhse** [comment]
You access "args1" as ".Args 0".

Could you please change the example to start with "arg0", and add a link to .Args?

**Comment by francislavoie** [comment]
Good point. #5898 should improve it :+1:
