### ISSUE TITLE
Feature: ADMIN Api based reload

### ISSUE THREAD

**Issue by Merith-TK** [caddyserver/caddy#5903]
This is an tiny edgecase in terms of features but I have an unique setup that allows for an small group of friends to alter an caddyfile system on `/workspace/caddy.conf`, this workspace folder is setup with docker so they do not have direct access to the rest of the system and only this folder, and the admin API. 

These people are tech illiterates so I was hoping to be able to just write an simple program to call the main `caddy` container api to just trigger an reload, 

The only problem I ran into is I cant force feed it an new config and have it overwrite whats already existing, *unless* i feed the config through the API after its already loaded,

meaning if I just use `import /workspace/caddy.conf` and then do all the work from there, I cant POST `/workspace/caddy.conf` to the API again, otherwise things just no longer exist such as this, where the `php` import is defined in the main config so they/I have an drop in *pre-setup* method for `php` using php-fpm docker 

`{"error":"adapting config using caddyfile adapter: /workspace/486net/caddy.conf:11 - Error during parsing: File to import not found: php, import chain: ['Caddyfile:1 (import)']"}`

but if I include `php` in the workspace config, it returns an `duplicate entry` error when defining PHP because the main config, *already loaded the bloody thing*

being able to just `curl "http://caddy:2019/reload` would solve this *entirely* (reload triggering an unload and loading of the config as if caddy just loaded or something akin to that) as I dont want them to have access to the host docker system.

**Comment by mholt** [comment]
There's only 1 config -- even if you have multiple files, they are combined into one. So a partial config load is also the same as a full reload (but reloads are very lightweight).

Is there a reason you can't just post the same config again to do the reload? Caddy doesn't really have the notion of config files. (The CLI abstracts them away from the API.)

**Comment by Merith-TK** [comment]
here is why
config load order
```
# /srv/caddy.conf
   (php) {
	@phpcheck path *.php
	php_fastcgi @phpcheck caddy-php:9000
}

import /srv/*/caddy.conf
```
```
# user access point config
domain.tld {
	reverse_proxy code-server:8443
}

## import alternative domain configs
import /workspace/caddy.conf
```

workspace/ has files that utilize the `php` import I created, 
if I were to just push `/workspace/caddy.conf` again, I get an error that is "php is undefined"

because it appears to be trying to load the config chain as if `/workspace/caddy.conf` (when pushed with the api), is the root of the config and does not allow it to utilize any existing imports further up the chain.

**Comment by francislavoie** [comment]
Right, you _must_ push the root of your config every time, there's no way around it. Like Matt said, there's no such thing as partial config reloads, and like I said, the Caddyfile is not kept in memory.

**Comment by mholt** [comment]
Closing, unless it becomes clear that there's something actionable here for us.

**Comment by Merith-TK** [comment]
Actionable thing for you
Add an `/reload` endpoint that can be called,
Caddy will store the location of the caddyfile if that is what is used in an var, and then just, act as if the user `/load`ed that file, 

That is legit what I am asking for, yall got caught up in the "why" I wanted this and were subjected to my terrible explanation of the convoluted cluster-fek that is my setup

**Comment by mholt** [comment]
You can do this with the `caddy reload` command already though. It loads your Caddyfile and POSTs it to the `/load` endpoint. :man_shrugging: If you can't run a command and have to use an HTTP request, you can still just call the `/load` endpoint with the contents of your Caddyfile...

**Comment by Merith-TK** [comment]
mholt, this is the third time here I am repeating myself

CaddyServer, and CodeServer, 
*are seperate docker containers*

Isolated islands that cannot interact beyond what I have specified.
The interaction that has been allowed, is Networking, and the folder `/workspace`

This means, that CodeServer, the container making the reload request, *cannot access* the master caddyfile which is required to reload the config as you described

As the Configs being loaded, contain `import xyz` lines that reference imports defined in the master caddyfile. Causing the API to refuse to load it as the import `php`, for example, has not been defined in the scope of the config I am pushing.

**Comment by francislavoie** [comment]
What we're saying is that's impossible and will never be possible.

You _must always_ push the root Caddyfile when reloading. You'll need to figure out a way to make that possible with your infrastructure.

**Comment by Merith-TK** [comment]
I see, probably what I will end up doing

I was getting caught up with yall saying "why not just do XYZ" when said XYZ was stated to not be applicable.
