### ISSUE TITLE
Reverse proxy - Client sent an HTTP request to an HTTPS server - what am I doing wrong?

### ISSUE THREAD

**Issue by rudeGit** [caddyserver/caddy#5904]
I am a caddy newbie with v2.7.3 on windows 11.

I have following simple CaddyFile:
```
localhost:2017 {
	respond "Goodbye, world! (localhost:2017)"
}

localhost:2016 {
	reverse_proxy localhost:2017
}
```

When I run it and issue following curl commands, I get the shown response.
```
C:\Users\foo>curl -k https://localhost:2017
Goodbye, world! (localhost:2017)

C:\Users\foo>curl -k https://localhost:2016
Client sent an HTTP request to an HTTPS server.
```

I am simply trying to test the reverse proxy without doing lot of extra work.

Not sure why I am getting "Client sent an HTTP request to an HTTPS server." and how to go about fix my configuration for it. I

**Comment by francislavoie** [comment]
`reverse_proxy localhost:2017` is making an HTTP request, but your `localhost:2017` server is listening for HTTPS requests. Change it to `https://localhost:2017` instead.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by rudeGit** [comment]
> `reverse_proxy localhost:2017` is making an HTTP request, but your `localhost:2017` server is listening for HTTPS requests. Change it to `https://localhost:2017` instead.
> 
> For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

It worked! Thank you. Will remember to ask the questions in community forums.
