### ISSUE TITLE
Feature Request: support docker service name as reverse proxy name

### ISSUE THREAD

**Issue by yangkequn** [caddyserver/caddy#5907]
Feature Request: Support Docker Service Name as Reverse Proxy Name in Caddy

Dear Caddy Development Team,

I hope this note reaches you well. Today, I'd like to discuss a potential enhancement for Caddy that, I believe, could substantially elevate its appeal and functionality, especially in comparison to its peers, most notably Traefik.

Over the years, Traefik has carved a niche for itself due to its seamless integration with Docker systems. One of the defining features that sets Traefik apart is its ability to use Docker service names as dynamic backends for reverse proxy configurations. This feature is particularly crucial for environments where Docker instance counts are dynamic, as it ensures smooth and uninterrupted service operation without the need for manual reconfiguration.

Imagine a scenario where containerized services are scaling up and down based on demand. With Traefik's approach, these services are immediately available for routing using their Docker service names, without any additional intervention. This level of automation not only optimizes resource usage but also greatly reduces the potential for human error.

Introducing a similar functionality in Caddy would be a significant milestone. By supporting Docker service names as reverse proxy names, Caddy would effectively bridge one of its few gaps in comparison to Traefik. For many users, this feature could be the compelling reason they need to consider migrating to or adopting Caddy. The appeal of a web server that can dynamically adjust to container orchestration systems is undeniable in our container-centric world.

Incorporating this feature would not only elevate Caddy's positioning in the market but also resonate strongly with the Docker community, demonstrating Caddy's commitment to catering to modern development and deployment paradigms.

I sincerely hope you'll consider this suggestion. The ever-evolving digital ecosystem requires tools that adapt and evolve in tandem, and this feature would undeniably affirm Caddy's place at the forefront of such innovation.

Thank you for your dedication to continuous improvement and for taking the time to consider this request.

Warm regards,

kq yang

**Comment by francislavoie** [comment]
Did you write this with ChatGPT? 😬

You already can proxy by service name, Caddy will be using the system DNS resolver which in a container includes Docker's own resolver.

But if you mean to proxy to more than one replica of a service, you should use https://github.com/lucaslorentz/caddy-docker-proxy
