### ISSUE TITLE
`acme_server` stopped working in 2.7.5 (provisioner not found)

### ISSUE THREAD

**Issue by smrqdt** [caddyserver/caddy#5911]
After updating to caddy 2.7.5, `acme_server` stopped working, the request for the directory endpoint always returns a 404 error.

minimal, reproducible example Caddyfile:
```Caddyfile
localhost
acme_server
```

Request from caddy 2.7.5 (tested from github releases, caddyserver.com and archlinux package):
```
% curlie https://localhost/acme/local/directory  
HTTP/2 404 
alt-svc: h3=":443"; ma=2592000
content-type: application/json
server: Caddy
content-length: 85
date: Mon, 23 Oct 2023 16:25:44 GMT

{
    "type": "notFound",
    "detail": "resource not found",
    "message": "provisioner  not found"
}
```

The problem also happens if a CA is specified for acme_server.

Before: response from caddy 2.7.4 (from github releases):

```
% curlie https://localhost/acme/local/directory  
HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
content-type: application/json
server: Caddy
content-length: 272
date: Mon, 23 Oct 2023 16:25:56 GMT

{
    "newNonce": "https://localhost/acme/local/new-nonce",
    "newAccount": "https://localhost/acme/local/new-account",
    "newOrder": "https://localhost/acme/local/new-order",
    "revokeCert": "https://localhost/acme/local/revoke-cert",
    "keyChange": "https://localhost/acme/local/key-change"
}
```

**Comment by mholt** [comment]
Hm, surprising.

@maraino -- I did upgrade smallstep/certificates from v0.24.3-rc.5 to v0.25.0. Do you know if that'd be the cause? I assumed -rc.5 was for the 0.25 release, but in hindsight, maybe it was just for the 24.3 release. and 0.25 had a bigger breaking change?

**Comment by maraino** [comment]
@mholt The biggest change was the migration to chi/v5, so I think this is the culprit:
https://github.com/caddyserver/caddy/blob/d6f86cccf5fa5b4eb30141da390cf2439746c5da/modules/caddypki/acmeserver/acmeserver.go#L29

Just append `/v5` there.

**Comment by maraino** [comment]
With the fix:
```
➜  caddy git:(master) ✗ curl -s https://localhost:8443/acme/local/directory | jq
{
  "newNonce": "https://localhost:8443/acme/local/new-nonce",
  "newAccount": "https://localhost:8443/acme/local/new-account",
  "newOrder": "https://localhost:8443/acme/local/new-order",
  "revokeCert": "https://localhost:8443/acme/local/revoke-cert",
  "keyChange": "https://localhost:8443/acme/local/key-change"
}
```

**Comment by francislavoie** [comment]
Oh, perfect! Thanks @maraino. Do you want to make a PR or should we?

**Comment by maraino** [comment]
Here it is https://github.com/caddyserver/caddy/pull/5913
