### ISSUE TITLE
reverse_proxy with fastcgi to git http-backend

### ISSUE THREAD

**Issue by HappyStriker** [caddyserver/caddy#5926]
Hey community,

Caddy is my primary server nowadays for almost everything, but there is one issue, that I could not solve yet:

How can I configure the reverse_proxy to connect via fastcgi to a git http-backend, so I can serve git repositories via Caddy?

Unfortunately I have not found any helpful resources on the web and I am not clever enough to combine the knowledge of the fastcgi documentation of caddy (1) with the example configuration for the apache webserver shown in the git http-backend documentation (2).

Thank you very much for your help!

1: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#the-fastcgi-transport
2: https://git-scm.com/docs/git-http-backend#Documentation/git-http-backend.txt-Apache2x

**Comment by mholt** [comment]
Good question, let me see if we can help once I'm back at the computer.

**Comment by francislavoie** [comment]
You might be looking for https://github.com/aksdb/caddy-cgi instead of fastcgi.

**Comment by mholt** [comment]
Sorry I got behind on things and didn't reply.

But yeah, it looks like git-http-backend doesn't support FastCGI, it's merely a CGI script, so the caddy-cgi plugin is also what I'd suggest.
