### ISSUE TITLE
Various breakages when formatting json heredocs

### ISSUE THREAD

**Issue by dbaynard** [caddyserver/caddy#5930]
I've hit various issues, with 2.7.5 and earlier versions of caddy, when it comes to heredocs.

`caddy fmt` introduces spacing which means the resulting file is invalid.

See the caddyfile in https://github.com/dbaynard/caddy-fmt-heredoc-example — I recommend you step through the commits.

0. Empty commit
1.  I created a sample, unformatted caddyfile, which works.

    ```Caddyfile
    	handle_path /never {
    		respond <<JSON
    		\{"response":"nope"\}
    		JSON 200
    	}
    	handle_path /json {
    		respond <<JSON
    		{"response":"nope"}
    		JSON 200
    	}
    ```

    The first appears to be returned as `text/plain`.

2. I adapted it, and it fails to load

    ```Caddyfile
    	handle_path /never {
    		respond <<JSON \{
    		"response":"nope"\}
    		JSON 200
    	}
    	handle_path /json {
    		respond <<JSON 
    		{"response":"nope"}
    		JSON 200
    	}
    ```

    Note the space at the end of the JSON for `/json`.

    ```console
    Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle_path': unrecognized directive: response - are you sure your Caddyfile structure (nesting and braces) is correct?, at Caddyfile:18
    ```

3. I removed the `handle_path` for `/nope` with escaped braces

```console
Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle_path': unrecognized directive: {"response":"nope"} - are you sure your Caddyfile structure (nesting and braces) is correct?, at Caddyfile:18
```

4. I removed the space after the heredoc market, and it's fine, again.

I tried with various different sigils, and saw no difference. In the repo, I have an example with a placeholder (that works correctly). And I have only tried the json formats.

Incidentally, the correct version of this would be helpful as an example.

**Comment by francislavoie** [comment]
Yeah, unfortunately `caddy fmt` doesn't handle heredocs at all right now. The problem is the Caddyfile lexer is completely separate code from the formatter. We'd have to re-implement heredoc lexing in the formatter as well, which is tedious. I want to rewrite the lexer to make it retain whitespace so that it can also be used for formatting, but that's a significant undertaking.

For now, unfortunately you'll need to avoid using `caddy fmt` if you're using heredocs.

**Comment by dbaynard** [comment]
Thanks for confirming. I'll skim the documentation — there may be a tweak I can make, and then I can close this.

**Comment by dbaynard** [comment]
Thanks — yes, I did know about that. As the docs on the respond directive says,

> If the body is non-empty, this directive sets the Content-Type header if it is not already set. The default value is text/plain; utf-8 unless the body is a valid JSON object or array, in which case it is set to application/json. For all other types of content, set the proper Content-Type explicitly using the header directive.

I thought this automatic detection was working correctly in the example with the non-escaped braces. Where I escaped the braces, I did need to add the header, contrary to the impression from the docs.

I only escaped the braces because in my example I had placeholders, and I initially thought there was an issue parsing the placeholder from the JSON (I reported a minimal repro; there is an example with a placeholder in the repro repo). Then I discovered caddy fmt was breaking the heredoc.

**Comment by francislavoie** [comment]
Ah I see, yeah it's not necessary to escape the JSON here. So your second handle-path should be what you use, and just avoid `caddy fmt` for now.

**Comment by francislavoie** [comment]
FYI @dbaynard, thanks to @bbaa-bbaa this should now be properly fixed :tada:

**Comment by dbaynard** [comment]
This is great — thanks @bbaa-bbaa 

caddyserver#352 will need a change — I can note the first caddy version for which this feature works?

**Comment by francislavoie** [comment]
We'll just remove the note from https://github.com/caddyserver/website/pull/352 when we release the next version.
