### ISSUE TITLE
vars referencing other vars are broken

### ISSUE THREAD

**Issue by aksdb** [caddyserver/caddy#5937]
The following Caddyfile worked fine in 2.6.4, but is broken in 2.7.5.

```
http://127.0.0.1:10000 {
        vars {
                foo "abc"
        }
        vars {
                bar "bla-{vars.foo}"
        }

        respond {vars.bar}
}
```

In 2.6.4 it still responded "bla-abc", in 2.7.5 it responds "bla-". So it apparently doesn't resolve the variables properly anymore.

**Comment by francislavoie** [comment]
The order of `vars` without matchers is not guaranteed. You should wrap them in a `route` if you need to have them be in a specific order.

See https://caddyserver.com/docs/caddyfile/directives#sorting-algorithm for more detail.

**Comment by aksdb** [comment]
Hmm, so it was sheer luck that it worked before. Damn. :-/

Do you think it would be feasible to build a "dependency tree" of vars or is what I am doing (vars referencing each other) too uncommon to bother?

**Comment by aksdb** [comment]
Regarding the one-line syntax:

Initially I had
```
vars {
  foo "abc"
  bar "bla-{vars.foo}"
}

That however didn't work even in the old version. Using two separate blocks solved this (in the real config I have more vars in each block).

I assumed back then that the `vars`-block is treated as a map, while multiple `vars`-blocks seemed to keep their order.

But actually ... might this be a "simple"(-ish) solution? That everything in the same `vars`-block retains its order?

**Comment by francislavoie** [comment]
> But actually ... might this be a "simple"(-ish) solution, to change the vars-blocks to retain the order of all vars within the same block?

Not possible, because JSON object keys do not maintain order. Caddyfile to JSON is inherently "lossy" in that sense.

The only way to guarantee they run in a certain order is by using separate handlers which are ordered in a certain way (either by making use of Caddyfile directive sorting if it works for you -- and it doesn't for your usecase, or with `route`).

**Comment by aksdb** [comment]
Well they *could* be in a slice instead of a map (basically a slice of key/value pairs), but it wouldn't be backwards compatible.
Unless the parser consideres both and can deal with maps _and_ key/value slices.

But any way ... since it's such a fringe case I will simply rework my config for that particular host to live in a large `route` block and it should be solved. :smiley:  Thanks!

**Comment by francislavoie** [comment]
Yeah maybe in Caddy v3 or something we might change `vars` to work differently. We'll see. But yeah for now `route` is the best option for you.
