### ISSUE TITLE
How to set the default logger programatically?

### ISSUE THREAD

**Issue by maxott** [caddyserver/caddy#5938]
I'm using Caddy as an embedded component in a service and would like to be able to set at least the default logger to the
zap logger the service has already configured by the time Caddy is started.

The primary reason for that is that setting up the logger in Caddy's config file is missing certain capabilities (primarily related to the encoder). But from management point of view, I want to avoid having to spread/duplicate logger configuration across multiple places (my service & Caddy config).

I guess the easiest place is to "extend" the `Log` function in `logging.go`. Being able to set the `defaultLogger` variable is most likely not going to work as it seems to be "recreated" in `setupNewDefault` based on its `CustomLog` settings - which lack what I need.

Or is there already a way to achieve that without any further code changes?

**Comment by francislavoie** [comment]
> The primary reason for that is that setting up the logger in Caddy's config file is missing certain capabilities

What do you mean, exactly? Couldn't we fix that instead? What are your needs?

This is sounding kinda like an [XY Problem](https://xyproblem.info/).

**Comment by mholt** [comment]
I'd be interested to know what about the encoder we could fix or improve to meet your needs. What are your requirements?

**Comment by maxott** [comment]
As for the XY Problem, I thought I already stated the problem - I'm using Caddy as an embedded component in a service and already have a configured zap logger by the time I initialise Caddy. Otherwise, I would need to ensure that the logger configuration from the service configuration is kept in sync with the caddy config file. Therefore, I was looking for a solution on how to also use that logger for Caddy.

As to what I'm missing:
* Setting `EncodeTime:TimeEncoder` in EncoderConfig 
  * not sure on how I could define that in JSON as `TimeEncoder` is a function
  * our 'primary' service is using `zapcore.ISO8601TimeEncoder`
* Adding `zap.WithCaller` to `zap.Builder`

I would really like to find a solution to this as I'm now having two different logging formats interspersed in the logs which complicates processing. Not a real show stopper, just an eye sore :)

Otherwise, I'm a very happy user!

**Comment by francislavoie** [comment]
You can set `TimeFormat` in the config, which sets up TimeEncoder. See https://github.com/caddyserver/caddy/blob/7e52db8280dcf855e77be6de5bccf7e8a173450c/modules/logging/encoders.go#L223-L260

We can add an option to enable `WithCaller`. 99% of the time it's not useful for users because the line numbers won't mean anything to them, which is why we didn't include it. But yeah, no harm in adding it as an option.

**Comment by francislavoie** [comment]
See https://github.com/caddyserver/caddy/pull/5944, I think this'll do what you need?

**Comment by maxott** [comment]
Thanks, that will allow me to solve my problem by duplicating logging information. 

I understand that the majority of folks are using Caddy as a "closed" application, configured by Caddy's own config file. And maybe, I'm the only one using it differently, but it can be used differently and having extension points, like providing one own's logger would make it even more useful.

In any case, thanks for the help.
