### ISSUE TITLE
Caddy sends old certificates to IOS devices

### ISSUE THREAD

**Issue by apmconectia** [caddyserver/caddy#5950]
Caddy sends old certificates to IOS devices randomly.

When connecting only via iPhone or iPad to caddy servers, it randomly presents an old version of the certificate.
You can start a session with the right certificate and then switches to an expired version.

Observed in several servers from caddy version v2.3.0 to v2.6.4
Probably related to IOS private relay.

The only solution it to completely restart caddy,  reload doesn't works.

**Comment by francislavoie** [comment]
Please update to the latest version of Caddy. We don't support old versions.

**Comment by mholt** [comment]
This happened for me on an old version of Caddy: https://twitter.com/mholt6/status/1671216222757847040

It doesn't happen anymore that I've seen. Be sure to upgrade and let us know if it continues.
