### ISSUE TITLE
caddy 2.7.5 fails to load or slow loads certificates from consul

### ISSUE THREAD

**Issue by dazoot** [caddyserver/caddy#5957]
We use caddy with tls consul for distributed certificates backend storage.

```
xcaddy build v2.7.5 --with github.com/caddy-dns/cloudflare --with  github.com/pteich/caddy-tlsconsul --with github.com/mholt/caddy-ratelimit --with github.com/caddyserver/replace-response
```

I am testing the new caddy 2.7.5.
We have about 90 certs in consul.
Certs are loaded `on_demand`.

The test i did is to bulk check the certs after caddy restart.

First couple of them (5 to 10) reply with a valid CERT.
The rest fail with no cert.

I can see the request sent by caddy to the `on_demand` script and the reply is `OK`, code 200. 
Plus the test works fine on caddy `2.6.5`.

The test i do is with openssl.

`openssl s_client -showcerts -servername HOSTNAME -connect IP:443`

Output is:
```
CONNECTED(00000003)
140646806118464:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../ssl/record/rec_layer_s3.c:1407:SSL alert number 80
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 202 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1701170887
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by francislavoie** [comment]
Enable the `debug` global option in Caddy. What's in your Caddy logs?

**Comment by dazoot** [comment]
```
is not allowed for server name cdn.nl.badabum.ro: decision func: on-demand rate limit exceeded
```

Removed the rate limit and all is good.

**Comment by Satyamkuamr** [comment]
Hello everyone you have any instragram account hacking tool please tal me

**Comment by khanakia** [comment]
@dazoot how did you remove the rate limit?

Do you mean commenting out this code `order rate_limit before basicauth` ?

**Comment by francislavoie** [comment]
@khanakia they were using `interval` and/or `burst` from https://caddyserver.com/docs/caddyfile/options#on-demand-tls and removed that. They weren't using the `rate_limit` plugin. Totally different thing.

**Comment by khanakia** [comment]
Ahh, I see thanks it worked now I just removed the `interval` and `burst`. Thanks 😄
