### ISSUE TITLE
allow use of env placeholder in tls certificates

### ISSUE THREAD

**Issue by acuteaura** [caddyserver/caddy#5962]
I'm using this directive to load certificates through systemd's `LoadCredential=` (reference [here](https://systemd.io/CREDENTIALS/)).

```
        tls "{env.CREDENTIALS_DIRECTORY}/cert.pem" "{env.CREDENTIALS_DIRECTORY}/cert.key"
```

Unfortunately, the placeholder does not seem to get resolved.

```
Dec 04 10:49:00 caddy[1517810]: Error: loading http app module: provision http: getting tls app: loading tls app module: provision tls: loading certificates: open {env.CREDENTIALS_DIRECTORY}/cert.pem: no such file or directory
```

**Comment by francislavoie** [comment]
FYI you can use `{$ENV}` syntax instead for now, since that's replaces at config-adapt time instead of at runtime, so no special support is needed for that to work.

But either way, no harm in adding this, and @mohammed90 already got to it quickly :blush: #5963
