### ISSUE TITLE
[BUG] JSON Caddyfile: env variables are not interpolated in basicauth

### ISSUE THREAD

**Issue by NightMachinery** [caddyserver/caddy#5964]
I recently converted my config from Caddyfile to JSON to use Layer4 forwarding. However, this part broke:
```
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "authentication",
                          "providers": {
                            "http_basic": {
                              "accounts": [
                                {
                                  "password": "{env.HASH}",
                                  "salt": "{env.SALT}",
                                  "username": "x"
                                }
                              ],
                              "hash": {
                                "algorithm": "scrypt"
                              },
                              "hash_cache": {}
                            }
                          }
                        }
                      ],
 ...
```

When I hardcode the env vars, everything works.

```
caddy version                                    
v2.7.5 h1:HoysvZkLcN2xJExEepaFHK92Qgs7xAiCFydN5x5Hs6Q=
```

**Comment by francislavoie** [comment]
Are you sure the env vars are actually set? How are you running Caddy?

`scrypt` is deprecated and will eventually be removed. It offers no real advantages over `bcrypt` and has much worse UX. See https://github.com/caddyserver/caddy/pull/4720

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by NightMachinery** [comment]
@francislavoie I am sure the env vars are set. Indeed, everything worked with a normal Caddyfile with this exact setup. I run caddy through `tmux zsh -c 'caddy ...'`.

I know `scrypt` is decrypted, but how is that relevant here? Leaking the `bcrypt` hash is also insecure.

I believe that this is not a usage question, it is either a bug or a feature request depending on what the intended behavior for the env var interpolation in this setting is.

**Comment by NightMachinery** [comment]
To make doubly sure, I stopped `caddy`, manually checked for the env vars on my interactive shell, and ran caddy from that same session. It still doesn't work.

There is a huge other issue though; the requests succeed for around a second when the server has just started, which suggests that the basic auth is in a race condition and the service is not secured in the initial seconds of the server launch.

**Comment by NightMachinery** [comment]
After more testing, this was my mistake. The server had a random failure rate (I don't know why), which I mistook for this bug. There is no security bug, and the env var interpolation works. Sorry.
