### ISSUE TITLE
Caddy on Windows (Cloudflare) Crashes Instantly

### ISSUE THREAD

**Issue by trevor68** [caddyserver/caddy#5977]
Hi,
I have made no changes to my system today, but came home to a paused caddy service which will not restart. 

Here is the complete caddy file. 

```
{
	acme_dns cloudflare 6RPwGdpFv__iBQt15sOBlrlMC7-7POQh2rF2_xF8
	email trevor@cannardy.com
}
vault.cannardy.com {
	log {
		output file C:\caddy\logs\vault_access.log {
			roll true # Rotate logs, enabled by default
			roll\_size\_mb 5 # Set max size 5 MB
			roll\_gzip false # Whether to compress rolled files
			roll\_local\_time true # Use localhost time
			roll\_keep 2 # Keep at most 2 log files
			roll\_keep\_days 7 # Keep log files for 7 days
		}
	}
	reverse_proxy localhost:8080
}
emby.cannardy.com {
	log {
		output file C:\caddy\logs\emby_access.log {
			roll true # Rotate logs, enabled by default
			roll\_size\_mb 5 # Set max size 5 MB
			roll\_gzip false # Whether to compress rolled files
			roll\_local\_time true # Use localhost time
			roll\_keep 2 # Keep at most 2 log files
			roll\_keep\_days 7 # Keep log files for 7 days
		}
	}
	reverse_proxy localhost:8096
}
media.cannardy.com {
	reverse_proxy localhost:5055
}
data.cannardy.com {
	reverse_proxy localhost:8888
}
xteve.cannardy.com {
	reverse_proxy locALHOST:8055
	rewrite / /web
}
photos.cannardy.com {
	reverse_proxy localhost:2342
}
books.cannardy.com {
	reverse_proxy localhost:8083 {
		header_up X-Scheme https
	}
}
sync.cannardy.com {
	reverse_proxy localhost:8384 {
		header_up Host localhost
	}
}
cloud.cannardy.com {
	rewrite /.well-known/carddav /remote.php/dav
	rewrite /.well-known/caldav /remote.php/dav

	header Strict-Transport-Security max-age=15552000;
	reverse_proxy localhost:8090
}
server.cannardy.com {
	reverse_proxy localhost:5005
}
stuff.cannardy.com {
	reverse_proxy localhost:6005
}
immich.cannardy.com {
	reverse_proxy localhost:2283 {
		header_up Host localhost
	}
}
```

The only way I can get the server to start without instantly crashing is to remove ALL sites from it, then it will start, with only this in the caddyfile. 

```
{
	acme_dns cloudflare 6RPwGdpFv__iBQt15sOBlrlMC7-7POQh2rF2_xF8
	email trevor@cannardy.com
}
```

All I can think of is maybe cloudflare is having a problem???

**Comment by francislavoie** [comment]
Show your Caddy logs.

Also I hope that's not your real CloudFlare API key, you should not leak that. If you did, please revoke and refresh it ASAP.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by trevor68** [comment]
Thanks, how should I go about getting logs when the server is crashing instantly, also it does not start at all now, even with only the cloudflare info.

**Comment by francislavoie** [comment]
Caddy always prints out logs to `stdout/stderr`. It's impossible that it crashes without logs unless the binary is corrupted.

**Comment by trevor68** [comment]
I’ve searched my W11 VM but I do not see any logs, even from when it was working. Your right though, replacing the exe fixed it so thanks for that

**Comment by francislavoie** [comment]
You should be running Caddy as a service on Windows, which allows you to configure where your logs are written. https://caddyserver.com/docs/running#windows-service

**Comment by trevor68** [comment]
Ah my bad, I used NSSM, I have gone back and set up logs now, thanks again.

**Comment by francislavoie** [comment]
Yeah NSSM also allows you to set log output files:

```
.\nssm.exe set caddy AppStdout C:\path\to\caddy\stdout.log
.\nssm.exe set caddy AppStderr C:\path\to\caddy\stderr.log
```

**Comment by climba03003** [comment]
I would like to say that the author is exposing his Cloudflare API Key.

@trevor68 If you are not meant to expose it, you should revoke the exposed one and generate a new one.
In the mean while, member of caddy can helps to remove the edit history and hide the API key.

**Comment by trevor68** [comment]
All good, thanks for the help
