### ISSUE TITLE
Add --envfile option to Caddy reload

### ISSUE THREAD

**Issue by soul-ride** [caddyserver/caddy#5987]
Hi,

Is it possible to add --envfile argument to "caddy reload" command?

I'm using envfile on start, however when I try to reload I'm getting errors (because variables in the config are not being parsed from file).
If I try to add --envfile option to "caddy reload" then I'm getting "Error: unknown flag: --envfile" error.

This is especially painful on Unix where Caddy is running as a service and documentation suggest to use reload instead of restart.

Thanks.

**Comment by francislavoie** [comment]
This doesn't really make sense because env vars should be defined at process startup. Also `caddy reload` uses the admin API to push a new config, and the admin API doesn't allow passing env vars, only a config.

If you do need to change env vars, you should restart Caddy.

**Comment by soul-ride** [comment]
@francislavoie if I correctly understand you, env vars are loaded at the _process_ level at the process startup and process should be restarted to pick up new values if they've changed (talking not about Caddy, but about any process running on Unix). Is it right?

I'm using separate env file to define all variables that can be changed, so it's easy to manage them outside of Caddyfile. Since they rarely change, I want to read that file only once when Caddy starts/reloads and not during runtime.

I don't want to parse them during runtime because I think that it may impact performance (at least a little bit). Let's say I have 50 vars defined in "vars {var1, var2,...}" directive in separate file which I import using "import" directive in Caddyfile. Since they are parsed at runtime and not once at the start, each request results in additional load because it should "unpack" all these 50 vars. Am I wrong that it will have some performance consequences?

Do you know if there is a way to accomplish this (e.g. define all vars in a separate file) without using _envfile_ and runtime variables?

[Feature request]
- Is it possible to prioritize what's defined in _envfile_ over system/process variables (or add some special flag for override) so when reload happens it reads values form _envfile_ and ignores what's defined in the process-level env vars? _(Howver, this approach is probably too complex and creates more problems than resolves)_
- Is it possible to add functionality to the Admin API to read & re-read _envfile_ (so it allows reloading instead of restarting)?
- OR just add an option to load separarte config with all variables defined there, which is parsed only at the start & reload and not during runtime.

Thanks in advance.

**Comment by francislavoie** [comment]
> I want to read that file only once when Caddy starts/reloads and not during runtime.

Reloads _are_ at runtime (of the process).

> Let's say I have 50 vars defined in "vars {var1, var2,...}" directive in separate file which I import using "import" directive in Caddyfile. Since they are parsed at runtime and not once at the start, each request results in additional load because it should "unpack" all these 50 vars. Am I wrong that it will have some performance consequences?

That would have very little impact. Nanoseconds at worst.

But `vars` can't be used everywhere in the config, only places the placeholder replacer is run (which is most places, but not all). 

> Do you know if there is a way to accomplish this (e.g. define all vars in a separate file) without using envfile and runtime variables?

You can use snippets which does allow you to use arguments with `import`.

Really, it depends what you're trying to use the variables for. You shouldn't use env vars for things that are likely to change often, they're mainly for secrets or constants.

Moving more things to env vars is wrong, you should be moving as much into your config as possible. The config is reloadable, env vars are not.

**Comment by mholt** [comment]
I would also say the performance impact is negligible. Actually env vars might be slower since they're stored as a list that has to be iterated, not as a table that can be looked up.

I'll close this but feel free to continue discussion if necessary.

**Comment by soul-ride** [comment]
So current behavior is as following:
- Start Caddy service with --envfile option `/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile --envfile /etc/caddy/env`
- Try to reload - `systemctl reload caddy` or `/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force`
- Get an error because env vars defined in envfile `/etc/caddy/env` are lost (because reload option do not support envfile command).

Real example:
- **/etc/caddy/env** file contains `PROXY_HOSTPORT="10.10.10.10:5050"` (IP was replaced).
- There is no _PROXY_HOSTPORT_ env var defined at the system level. Behavior would be the same even if define it (let's say we set it to `"localhost:5050"`.
- In **/etc/caddy/Caddyfile** there is a statement in reverse_proxy section: `to http://{$PROXY_HOSTPORT:"localhost:5050"}`
- Start Caddy service with additional option `--envfile /etc/caddy/env`
- Everything works nice and my reverse proxy points to **10.10.10.10:5050**
- Try to reload Caddy via `systemctl reload caddy` --> Get an error - **_Job for caddy.service failed_**
- Check actual error - `sudo journalctl -u caddy --no-pager | less +G` - **Error: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': parsing upstream 'http://"`localhost:5050`"': parsing upstream URL: parse "http://\"`localhost:5050`\"": invalid port ":5050\"" after host, at /etc/caddy/Caddyfile:65, at /etc/caddy/Caddyfile:83**
- As you can see, after reload it tries to connect to default _localhost:5050_ instead of what's defined in the envfile - _10.10.10.10:5050_.

It basically means that if you are using `--envfile` option to start Caddy, then you can not use `reload` option, and you are restricted to `restart` only.
If its not possible to add support of `--envfile` to the reload (e.g. admin API), then it probably worth to at least mention such restriction in the documentation. It's not expected behavior that `reload` will fail whenever you start Caddy with `--envfile` option.

Regarding possible workaround with vars and snippets - I wasn't able to define global-level `vars` or snippet which can be imported once and work in all sections of the config. It much easier to use env vars which are available globally across the Caddyfile and also can have default values. In my particular case I'm ok with restarting the service instead of reloading it. However, in general, I feel like current behavior is unexpected and should be fixed or documented.

**Comment by mholt** [comment]
I think I see what you're saying. `caddy reload` is its own process, separate from the process that was first started with `caddy run` which has the envfile loaded. `caddy reload` loads the Caddyfile and adapts it, and during that, it fails because the missing env var.

Now I'm trying to remember why `caddy reload` is adapting the config in the first place. Should that be the job of the original, already-running Caddy process? I am not sure there's a clear answer here, I can see arguments for both ways.

That said, it's not clear to me either how to go about updating the loaded envirnoment on the original Caddy process anyway. Do we append, overwrite, delete vars? (We don't know which ones came from an envfile, unless we remember, which I'm not inclined to use memory for... or add the complexity.)

If we add `--envfile` support to `caddy reload`, that may happen to help this particular use case, but if the adapted config still refers to new or updated env vars that the original Caddy process (the one that actually runs the config) doesn't have, it will do no good and worse yet, you might not even get an error about it.

I'd strongly recommend coupling env vars to the process 1:1. It gets messy otherwise no matter how you do it (unless there's truly an elegant proposal out there I haven't considered).

**Comment by francislavoie** [comment]
Well your problem here is that you're using `--envfile` with systemd. If you're using systemd then you should use a systemd config override instead: https://caddyserver.com/docs/running#overrides This way the env is set in the context of the reload command as well.

But yeah, the reload command doing the Caddyfile adapting is a problem when env vars are involved. It would be fine to support `--envfile` on the reload command to make the adapter work, but it will not update env values in the main process.

**Comment by soul-ride** [comment]
@francislavoie you are right that I'm using it in systemd, but I'm still doing what's described at https://caddyserver.com/docs/running#overrides.

systemctl edit caddy
```
# Service file is at /lib/systemd/system/caddy.service
# This file is at /etc/systemd/system/caddy.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile --envfile /etc/caddy/env
Restart=always
RestartSec=2
...
# ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
# ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force
...
```

Behavior is actually the same as if I was running it manually.

Apparently, I was getting error before because of the way I defined `to http://{$PROXY_HOSTPORT:"localhost:5050"}` directive. I changed it to `to {$PROXY_HOSTPORT:"http://localhost:5050"}`.

Now I do not get an error on reload. 
However, _reload_ command do not pick up new/updated variables from `/etc/caddy/env` and do not throw any warnings. So it basically fails (ignores env file) silently.

**Comment by francislavoie** [comment]
> but I'm still doing what's described

Not really, nowhere do the docs recommend to use `--envfile` with systemd. In fact, it specifically says to set env vars using overrides like that.

**Comment by soul-ride** [comment]
@francislavoie Docs do not and can not describe all functionality and all possible situations. There is an instruction in the doc describing how to do service override, there is --envfile argument in Caddy. I've just mixed them and got the result I reported here. From my point of view this behavior that is unobvious (and probably unexpected).
I'm not trying to argue here, I'm just reporting it. It's ok for me to use restart instead of reload. Ability to use --envfile is already awesome by itself, even if it requires restart instead of reload.

**Comment by francislavoie** [comment]
But again, why not just use systemd overrides to set your env vars? Then you _can_ use reload right now without any problems.

**Comment by soul-ride** [comment]
@francislavoie If you are talking about "Environment=" statement in the systemd file, then
It's easier to maintain and manage different configurations in separate env files (e.g. env.prod, env.dev, etc) dedicated only to the variables that may change. Also, I want to avoid mixing system-related stuff (service definition) and application stuff (configs and so on). I'm not ready to sacrifice simplicity of env files, restart is fast enough anyway. For example one of my vars is quite long CSP security header, it fits nice to env file, but I don't really see it in the service definition file.

I've just tested it, when I set some var in the "Environment=" statement in service override, **and then update it**, I still need to do Caddy restart. Neither "caddy reload" or "systemctl daemon-reload" helped to pick up new value. At least "caddy reload" didn't fallback to the default value in this case, what is good.

**Comment by mohammed90** [comment]
> If you are talking about "Environment=" statement in the systemd file, then
> It's easier to maintain and manage different configurations in separate env files (e.g. env.prod, env.dev, etc)

systemd has `EnvironmentFile` directive, see [here](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#EnvironmentFile=).

**Comment by soul-ride** [comment]
@mohammed90 thank you, didn't know about that. 

I've updated service override as provided below. `--envfile /etc/caddy/env` option is not really needed here but I just like to keep it. Now env vars are kept on "reload". If you change anything in your env file you still need to restart service though.

```
# Service file is at /lib/systemd/system/caddy.service
# This file is at /etc/systemd/system/caddy.service.d/override.conf
[Service]
EnvironmentFile=/etc/caddy/env
ExecStart=
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile --envfile /etc/caddy/env
Restart=always
RestartSec=2
```

Anyway, if it's possible to add `--envfile` option to `caddy reload` it would be nice and easier to configure & test. If it's too much of work, then I guess we found a suitable workaround (use "EnvironmentFile=" directive in the service definition and restart service when env file updated).

**Comment by mholt** [comment]
> Anyway, if it's possible to add --envfile option to caddy reload it would be nice and easier to configure & test.

The only reason I hesitate to do this is because, as explained above, it may be misleading that the running Caddy instance gets the new/updated environment, but this is not the case.
