### ISSUE TITLE
systemd service changes conf file from .json to caddyfile

### ISSUE THREAD

**Issue by pkkrusty** [caddyserver/caddy#5988]
I've had this happen twice now, so I thought I'd see if anyone is familiar with the issue and has a quick fix.

I was wondering why my certs weren't updating (I kept getting expiration notices and was sure I'd read that caddy renews certs with plenty of time to spare) and eventually tracked it down to my `/lib/systemd/system/caddy.service` file where I define the source of the config file.  I have changed it from Caddyfile to caddy.json in the same folder.
```
[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/caddy.json
ExecReload=/usr/bin/caddy reload --config /etc/caddy/caddy.json --force
TimeoutStopSec=5s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

Both times, the ExecStart and ExecReload lines revert to referring to the Caddyfile instead of the json file.

Maybe after a caddy version update it reverts? Haven't caught it a third time, so not sure when it changes.

**Comment by pkkrusty** [comment]
OK, saw that caddy just updated to 2.7.6 and did the sudo apt upgrade.  Can confirm that that action reverted my systemd service file to the default Caddyfile.

Is that normal behavior?

**Comment by francislavoie** [comment]
Yes, it's normal. You should not edit the systemd service file installed by your package manager directly, you should set an override. See https://caddyserver.com/docs/running#overrides.

If you plan on using the admin API for making config changes, you should switch to the `caddy-api.service` file instead https://caddyserver.com/docs/running#unit-files
