### ISSUE TITLE
Caddy Keeps Reloading Config in v2.7.5 due to skip_host order changing

### ISSUE THREAD

**Issue by outofsight** [caddyserver/caddy#5989]
Had to disable `--watch` because caddy suddenly started to continuously reload the config.

Further investigation shown this is due to the order of `skip_host` continuously changing, the first two hosts in the following code.

```
{
    "apps": {
        "http": {
            "http_port": 80,
            "https_port": 443,
            "servers": {
                "srv0": {
                    "listen": [
                        ":443"
                    ],
                    "logs": {
                        "logger_names": {
                            "*.mydomain.biz": "",
                            "mydomain.biz": "",
                            "mysite.mydomain.biz": "log0"
                        },
                        "skip_hosts": [
                            "wpad.mydomain.biz",
                            "wpad.lan.mydomain.biz",
                            "www.lan.mydomain.biz",
```

This happen in a custom image based on `caddy:2.7.5-builder-alpine` but `--with github.com/caddy-dns/cloudflare` and `--with github.com/caddyserver/ntlm-transport`.

**Comment by francislavoie** [comment]
Please share your actual config which reproduces this.

**Comment by francislavoie** [comment]
You can try https://github.com/caddyserver/caddy/pull/5990 to see if it fixes it for you

**Comment by outofsight** [comment]
I'll be happy to test but have no idea how :D

**Comment by francislavoie** [comment]
https://caddyserver.com/docs/build
