### ISSUE TITLE
wildcard prefix to virtual host

### ISSUE THREAD

**Issue by 91320113** [caddyserver/caddy#5991]
Hello,

I'm migrating some of services from apache to caddy and was looking for a wildcard domain with a prefix like:

```
new-*.yyy.zzz:443 {
     import common
     root /some/where/there
}

old-*:80 {
     import common
     root /some/where/here
}
```

I tried it on the latest version and found that caddy does not support it.

Thanks

**Comment by francislavoie** [comment]
Wildcards are only valid as the left-most label of a domain. This isn't a Caddy limitation, this is how DNS and certificates work.

**Comment by 91320113** [comment]
the certificate will still be generated as wildcard *.xxx.yyy and dns will still be *.xxx.yyy
and pointed somewhere while new-zzz.xxx.yyy still a valid wildcard domain for the certificate and dns.

There are no certificate nor dns limitations.

new-zzz.xxx.yyy = *.xxx.yyy

Its working on apache just fine, and technically it could work on caddy as well!

**Comment by francislavoie** [comment]
The difference is that Caddy uses the site address for determining the name to use for certificate issuance. If you don't use a name that's compatible with PKI/DNS infrastructure, then it can't do its job.

If all you need is to match hostnames with a pattern, then use this pattern https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates and use a `header_regexp Host` matcher.

**Comment by 91320113** [comment]
Indeed this what I was looking for.

Thank you for your prompt reply.
