### ISSUE TITLE
Notify when a request is done

### ISSUE THREAD

**Issue by EricFROL** [caddyserver/caddy#5996]
As title says, is there anyway to notify me via webhook or mail when a simple http request is done to server?

So getting into, for example, example.com, would trigger a webhook that notifies me somehow.

**Comment by francislavoie** [comment]
You'd be best off finding a plugin to do what you need or write your own. There's plugins like https://github.com/WingLim/caddy-webhook that you could use, or fork to do what you need.

**Comment by mholt** [comment]
Or ingest the logs. The access logs are written when the request is done.

**Comment by EricFROL** [comment]
Any advice on how to do that? Don't really know how to start... I know how to compile caddy with plugin, but no ideas

**Comment by mholt** [comment]
There might already be tools out there that ingest logs and let you do events based on the logs. I'm not well versed in that space but I'd be surprised if something doesn't already exist.

As a Caddy plugin, the docs are on that page. It steps you through building an HTTP handler, which is probably what you'd want. After the call to `next.ServeHTTP()` you'd want to do your own logic there.
