### ISSUE TITLE
Feature request : Add CSR in “cert_obtained” tls events

### ISSUE THREAD

**Issue by clauverjat** [caddyserver/caddy#5999]
Hi again,

## Which problem is this feature request solving?
Caddy can emit events[^1] about the certificate issuance. In particular a _cert_obtaining_ event is raised when a certificate is about to be obtained. It’d be nice if this event would include the Certificate Signing Request (CSR) corresponding to the certificate to be obtained.

For now  the event contains only the following data :
- renewal: Whether this is a renewal
- identifier: The name on the certificate
- forced: Whether renewal is being forced (if renewal)
- remaining: Time left on the certificate (if renewal)
- issuer: The previous or current issuer

## Why is this feature a useful, necessary, and/or important addition to this project?
This feature could be used to maintain a list of all CSRs generated by Caddy. This list can then be used to audit/monitor the Certificate Transparency logs. 

One might say that this is not needed since a _cert_obtained_ event will eventually be raised and such event contains the path to the certificate, so that the administrator can maintain a list of certificates instead of CSRs. However, there's a flaw in this approach: a CSR could be sent to the Certificate Authority, and a certificate issued, without triggering the cert_obtained event. This scenario might occur if the machine running Caddy fails, or, if there's a network issue between the CA and the Caddy server during the ACME issuance process. In such situations, the Certificate Transparency (CT) logs would record a certificate that the administrator cannot confirm as being issued in compliance with their security policy.

## What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

If you like living on the edge (which I think a lot of people like), you can hope for the best and wait for the _certificate_obtained_ event. 😅

For my usecase thought, I’ve once again patched the Caddy server. I have modified the ACMEIssuer Issue methods so that it sends the CSR before actually proceeding with the issuance. This works, but this is not a proper implementation of the feature. Here is the implementation : https://github.com/mithril-security/caddy/commit/b6404a7ec83ddbd589c5f824014293717fde63d9

[^1]: https://github.com/caddyserver/certmagic#events

**Comment by mholt** [comment]
Hmm... we can probably do that... the only thing to note is that if the event handler (if any) cancels the event, a CSR (and private key) has been generated already, for no reason. Not a big deal, I suppose.

If I implement this in a branch would you be willing to try it out?

**Comment by clauverjat** [comment]
> Hmm... we can probably do that... the only thing to note is that if the event handler (if any) cancels the event, a CSR (and private key) has been generated already, for no reason. Not a big deal, I suppose.

For my usecase, this is the behavior I want (and need to achieve my security goals).

> If I implement this in a branch would you be willing to try it out?

Yes, I'd be happy to

**Comment by mholt** [comment]
@clauverjat If you want to build from CertMagic master and try it out that'd be great :smiley:

**Comment by clauverjat** [comment]
Hi Matt,

I'd love to try it out. I am a bit busy at the moment though. I'll try to spend some time on it at the end of the week.

**Comment by clauverjat** [comment]
I just had a look at it. I am a bit confused, the patch you pushed is adding the CSR to the cert_obtained event which is emitted after the certificate is obtained. This might be useful for some usecases but we were discussing adding the CSR to the cert_obtaining event (which is emitted before contacting the CA). I think the confusion might be due to the title I put for the issue, sorry about that.

**Comment by mholt** [comment]
Ah... didn't realize that (after several months). I did just look at the title. I'll try to revisit again, we'll see when I have a chance.

**Comment by mholt** [comment]
There is one caveat now, because of incompatibilities with the ZeroSSL issuer, their CSR is different, so if we log the CSR before trying the ZeroSSL issuer (which is what you're asking for), we can't log the correct CSR because a new CSR is made when using ZeroSSL. I'm not really sure what to do about that...

**Comment by alexander-potemkin** [comment]
Given that Caddy doesn't seem like support event sending on certificate update out of the box (and recompilation doesn't really work if you are using Docker or would like to enjoy automatic update) - `ionotifywait` might be another [approach](https://superuser.com/questions/181517/how-to-execute-a-command-whenever-a-file-changes?page=1&tab=scoredesc#tab-top) to that problem.

**Comment by francislavoie** [comment]
> and recompilation doesn't really work if you are using Docker or would like to enjoy automatic update

See https://caddyserver.com/docs/build#docker

**Comment by alexander-potemkin** [comment]
> > and recompilation doesn't really work if you are using Docker or would like to enjoy automatic update
> 
> See https://caddyserver.com/docs/build#docker
> 
> Watching the filesystem for this is not ideal because of multi-issuer support, you need to take into account that the new cert may be from one of multiple configured issuers. Events take care of that because it publishes the path to the updated cert on disk and its associated data.

It is not ideal - for sure, but much better than to deal with anything like custom build on the production server!

I didn't know about Docker build option - thank you. Can't use it in prod though - have had enough issues with Docker build cache...

**Comment by francislavoie** [comment]
You build the image in your CD infrastructure, then push it to (staging first hopefully, then) prod. This is very normal stuff, this is how everyone does it.

**Comment by mholt** [comment]
I just avoid it by not using Docker for static binaries 🤷‍♂
