### ISSUE TITLE
writing: write tcp write: broken pipe error

### ISSUE THREAD

**Issue by 91320113** [caddyserver/caddy#6000]
Hello team,

I have many "writing: write tcp write: broken pipe" errors, not sure what's causing it.

All my services working fine, no issues just those errors lines in caddy logs!

Front caddy config: (192.168.0.22)
`
XXX.XXX.XXX {
reverse_proxy 192.168.0.71:80 {
                header_up X-Client-Real-IP {client_ip}
        }
}`

Front caddy log have errors like:
Aborting with incomplete response:
- writing: H3_REQUEST_CANCELLED
- writing: timeout: no recent network activity
- writing: http2: stream closed
- writing: NO_ERROR (remote): 85:Network blackhole detected

Back caddy config: (192.168.0.71)
`
:80 {
root * /test
}
`

Back caddy log:
`"level":"error","ts":1703328983.9558074,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":0.068549927,"request":{"remote_ip":"192.168.0.22","remote_port":"60470","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"Accept":["*/*"],"Accept-Charset":["*"],"Accept-Language":["en-US"],"Origin":["https://XXX.XXX.XXX"],"Cookie":[],"X-Forwarded-Proto":["https"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"],"X-Forwarded-Host":["XXX.XXX.XXX"],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"Accept-Encoding":["identity"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:60470: write: broken pipe"}
{"level":"error","ts":1703328984.1560416,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":0.083959782,"request":{"remote_ip":"192.168.0.22","remote_port":"60484","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"X-Forwarded-Host":["XXX.XXX.XXX"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"Accept-Charset":["*"],"X-Forwarded-Proto":["https"],"Accept":["*/*"],"Accept-Encoding":["identity"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"],"Origin":["https://XXX.XXX.XXX"],"Accept-Language":["en-US"],"Cookie":[],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"X-Client-Real-Ip":["XX.XX.XX.XX"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:60484: write: broken pipe"}
{"level":"error","ts":1703328984.177908,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":0.082106063,"request":{"remote_ip":"192.168.0.22","remote_port":"60492","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"Accept-Encoding":["identity"],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"Accept-Language":["en-US"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"Accept":["*/*"],"X-Forwarded-Host":["XXX.XXX.XXX"],"X-Forwarded-Proto":["https"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"],"Accept-Charset":["*"],"Origin":["https://XXX.XXX.XXX"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"Cookie":[]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:60492: write: broken pipe"}
{"level":"error","ts":1703328984.4199836,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":0.101776526,"request":{"remote_ip":"192.168.0.22","remote_port":"60498","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"Accept":["*/*"],"Accept-Charset":["*"],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"X-Forwarded-Proto":["https"],"Accept-Encoding":["identity"],"Cookie":[],"Origin":["https://XXX.XXX.XXX"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"],"Accept-Language":["en-US"],"X-Forwarded-Host":["XXX.XXX.XXX"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:60498: write: broken pipe"}
{"level":"error","ts":1703328984.4581146,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":0.067226898,"request":{"remote_ip":"192.168.0.22","remote_port":"60504","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"Accept-Charset":["*"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"Accept":["*/*"],"X-Forwarded-Proto":["https"],"Cookie":[],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"Accept-Encoding":["identity"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"X-Forwarded-Host":["XXX.XXX.XXX"],"Accept-Language":["en-US"],"Origin":["https://XXX.XXX.XXX"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:60504: write: broken pipe"}
{"level":"error","ts":1703329251.149386,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":72.496395107,"request":{"remote_ip":"192.168.0.22","remote_port":"47094","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"X-Forwarded-Host":["XXX.XXX.XXX"],"Accept":["*/*"],"Accept-Language":["en-US,en;q=0.9"],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"X-Forwarded-Proto":["https"],"Accept-Encoding":["gzip, deflate, br"],"Cookie":[],"X-Requested-With":["XMLHttpRequest"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:47094: write: broken pipe"}
{"level":"error","ts":1703330277.6869323,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","upstream":"unix//run/php/php7.4-fpm.sock","duration":12.755886243,"request":{"remote_ip":"192.168.0.22","remote_port":"56848","client_ip":"192.168.0.22","proto":"HTTP/1.1","method":"GET","host":"XXX.XXX.XXX","uri":"/index.php?XXXXXX","headers":{"Accept-Language":["en-US,en;q=0.9"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Sec-Fetch-Dest":["empty"],"Cookie":[],"X-Forwarded-Proto":["https"],"Referer":["https://XXX.XXX.XXX/?XXXXXX"],"X-Client-Real-Ip":["XX.XX.XX.XX"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"],"Sec-Fetch-Mode":["cors"],"Accept":["*/*"],"Sec-Ch-Ua-Mobile":["?0"],"Accept-Encoding":["gzip, deflate, br"],"X-Forwarded-Host":["XXX.XXX.XXX"],"Sec-Ch-Ua":["\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\", \"Google Chrome\";v=\"120\""],"X-Requested-With":["XMLHttpRequest"],"X-Forwarded-For":["XX.XX.XX.XX, 192.168.0.22"],"Sec-Fetch-Site":["same-origin"]}},"error":"writing: write tcp 192.168.0.71:80->192.168.0.22:56848: write: broken pipe"}`

**Comment by mohammed90** [comment]
This is harmless, as you're experiencing. This usually happens when the client disconnects without completing the handshake and the necessary components of a proper HTTP connection. Do you have a TCP-based health check service checking if Caddy is up? I've seen that with Hashicorp Consul health checks.

**Comment by 91320113** [comment]
Thank you @mohammed90 for your reply, Im not using a health check. 

Is there an option to suppress those errors since they are not actually an "errors" I believe they should be an "info" instead.

**Comment by mohammed90** [comment]
> Is there an option to suppress those errors since they are not actually an "errors" I believe they should be an "info" instead.

They should be concerning to you because they mean the client is not closing the connection properly/cleanly. It's harmless in in smaller numbers as it can mean the client closed the webpage/app in the middle of the loading request. However, in large numbers this is a form of an attack to exhaust your server. It's good to know about it.
