### ISSUE TITLE
Caddy tries to generate a certificate for subdomain of subdomain even if provide custom tls certificate

### ISSUE THREAD

**Issue by ElegantSoft** [caddyserver/caddy#6004]
my config file 
```
*.easy-orders.net {


tls path-to-cert.crt  path-to-key.key

}

```

I got error 
get certificate from issuer","identifier":"sub.sub2.easy.mydomain","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 429 urn:ietf:params:acme:error:rateLimited - Error creating new order :: too many certificates already issued for \"mydomain\". Retry after 2023-12-26T23:00:00Z: see https://letsencrypt.org/docs/rate-limits/"}

the expected behavior to not generate certificate and use my custom certificate

**Comment by mholt** [comment]
What are the SANs on your cert?

**Comment by mholt** [comment]
Closing due to lack of information and inactivity. We can reopen if the necessary information is presented so we can identify an issue.
