### ISSUE TITLE
wildcard cert

### ISSUE THREAD

**Issue by Y-A-K-E** [caddyserver/caddy#6006]
Caddy version:
v2.1.1 h1

Caddyfile:

```
{
	admin off
	#debug
}

(dnspod_token) {
    dns dnspod 10XXXX,dbXXXXXXXXXXXXXXXXXXX
}

rcon.getce.cn:443 {
        tls {
                import dnspod_token
        }
	reverse_proxy http://127.0.0.1:28080 
}


*.getce.cn {
	root  * /data/www/blog/public
	tls {
		import dnspod_token
	}
}

qqqq.getce.cn shop.getce.cn {
	root  * /data/www/wiki/public
	tls {
		import dnspod_token
	}
}

``` 

Caddy uses multiple certificates

`/var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory`

![Screenshot 2023-12-28 131436](https://github.com/caddyserver/caddy/assets/6988291/387fd318-aa2c-40a2-a483-6636e8bc070f)

qqqq.getce.cn /  shop.getce.cn  / rcon.getce.cn 
how to use `wildcard_.getce.cn`  cert?

**Comment by francislavoie** [comment]
Caddy v2.1.1 is an very old version and no longer supported. Please use the latest version 

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by francislavoie** [comment]
Caddy v2.1.1 is an very old version and no longer supported. Please use the latest version.

If you don't want Caddy to issue individual certs, you need to use a config pattern like this: https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
