### ISSUE TITLE
Disable buffering?

### ISSUE THREAD

**Issue by EricFROL** [caddyserver/caddy#6007]
Hello.
I want to run [Dozzle](https://github.com/amir20/dozzle) behind a revere proxy with Caddy.
To do it [I've read](https://dozzle.dev/guide/faq) that I need to disable buffering. How can I do that with Caddy?

Thank you.

**Comment by francislavoie** [comment]
Caddy doesn't do any buffering by default.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by EricFROL** [comment]
Alright, gonna do that. Thank you.
