### ISSUE TITLE
listen tcp :80: bind: permission denied although different port is defined

### ISSUE THREAD

**Issue by koh-osug** [caddyserver/caddy#6008]
I'm following the [tutorial](https://caddyserver.com/docs/quick-starts/reverse-proxy) but caddy tries to listen on port 80 although not instructed to do so:

> caddy reverse-proxy --from 127.0.0.200:7777 --to 127.0.0.201:7777
2023/12/30 10:22:42.488 WARN    admin   admin endpoint disabled
2023/12/30 10:22:42.488 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "proxy"}
2023/12/30 10:22:42.488 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0004b7100"}
2023/12/30 10:22:42.493 INFO    http    enabling HTTP/3 listener        {"addr": ":7777"}
2023/12/30 10:22:42.493 INFO    http.log        server running  {"name": "proxy", "protocols": ["h1", "h2", "h3"]}
2023/12/30 10:22:42.493 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc0004b7100"}
Error: loading new config: http app module: start: listening on :80: listen tcp :80: bind: permission denied

**Comment by francislavoie** [comment]
Caddy defaults to HTTPS when a hostname (in your case, an IP address), and therefore enables HTTP->HTTPS redirects on the default port. To disable this, prefix the from address with `http://` or use the `-r` flag to disable redirects.
