### ISSUE TITLE
caddy validate does not warn if certificate expired

### ISSUE THREAD

**Issue by yene** [caddyserver/caddy#6016]
hi,
one of our manual certificate expired and I didn't notice.
Would it be possible that `caddy validate` prints a warning if a loaded certificate is expired?

Thank you for your time.

**Comment by mholt** [comment]
I suppose that should be doable -- probably doesn't even need to be limited to `caddy validate`. Just if any cert is manually loaded that's expired, print a warning.

I don't imagine this is very common anymore, especially when using software like Caddy/CertMagic which excels at automating certs for you, but the patch is quick and easy: https://github.com/caddyserver/certmagic/commit/3dd8f7da62616b0bc0888511fae8057223f270a4
