### ISSUE TITLE
Feature Request: Write caddy logs to Unix socket

### ISSUE THREAD

**Issue by Monviech** [caddyserver/caddy#6023]
Hello,

I would really like to write caddy logs to a Unix socket on Unix like systems (for example on FreeBSD) instead of a file or a net socket.

Looking at this module: `modules/logging/netwriter.go` it could probably be turned into something like `modules/logging/unixwriter.go` that writes to a unix socket instead of a net socket.

An example unix socket of `syslog-ng` would be `/var/run/logpriv` or `/var/run/log`.

**My usecase:**

On the OPNsense Firewall, the `syslog-ng` on `FreeBSD` only allows the usage of a unix socket for logging, due to performance and safety reasons. Right now I'm logging to a file, parse it with a python script, call it with a custom API controller and send it to a custom UI view. It would be considerably tighter integrated if I could use the UNIX socket instead.

Thank you for reading this and all of your great work. :)

**Comment by francislavoie** [comment]
I think this should already work? Just use an address like `unix:/var/run/logpriv`. See https://caddyserver.com/docs/conventions#network-addresses

**Comment by mohammed90** [comment]
This is already supported and there's no need to change anything. You can give the [net](https://caddyserver.com/docs/caddyfile/directives/log#net) writer a [network address](https://caddyserver.com/docs/conventions#network-addresses) of the unix socket.

**Comment by Monviech** [comment]
Oops I really didn't see that, thank you a lot for the clarification @mohammed90 and @francislavoie

**Comment by Monviech** [comment]
For anybody reading this in the future:

Send caddy log to unix datagram socket (what I needed):
```
log {
        output net unixgram//var/run/logpriv
}
```

Send caddy log to unix stream socket:
```
log {
        output net unix//var/run/logpriv
}
```
