### ISSUE TITLE
Caddy seem to ignore tls issuer

### ISSUE THREAD

**Issue by vadella** [caddyserver/caddy#6024]
I'm setting up a simple internal intranet. I'm using FreeIPA as CA

I'm testing with this minimal Caddyfile

```
{
        cert_issuer acme https://ipa0.fabre.home.arpa/acme/directory {
                trusted_roots /etc/ipa/ca.crt
        }
        email maarten@fabre.be
        admin off
        debug
}
dashboard0.fabre.home.arpa {
        handle /health {
                respond "Hello, there!"
        }

        handle {
                respond "oops"
        }
}
```

But when I try to visit `dashboard0.fabre.home.arpa` I get a certificate issued by `Caddy Local Authority - ECC Intermediate`

When I check the logs `journalctl -xeu caddy.service`, I get these relevant lines:

```
{"level":"info","ts":1704584936.6655369,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"debug","ts":1704584936.665759,"logger":"http.auto_https","msg":"adjusted config","tls":{"automation":{"policies":[{"subjects":["dashboard0.fabre.home.arpa"]},{}]}},"http":{"servers":{"remaining_auto_https_redirects":{"listen":[":80"],"routes":[{},{}]},"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"subroute","routes":[{"group":"group2","handle":[{"handler":"subroute","routes":[{"handle":[{"body":"Hello, there!","handler":"static_response"}]}]}],"match":[{"path":["/health"]}]},{"group":"group2","match":[{"path":["/health"]}]},{"group":"group2","handle":[{"handler":"subroute","routes":[{"handle":[{"body":"oops","handler":"static_response"}]}]}]}]}],"terminal":true}],"tls_connection_policies":[{}],"automatic_https":{}}}}}
...
{"level":"info","ts":1704584936.6869292,"msg":"autosaved config (load with --resume flag)","file":"/var/lib/caddy/.config/caddy/autosave.json"}
```
and some logs lines where it tries to setup its own internal CA

But when I go and check in `/var/lib/caddy/.config/caddy/autosave.json` the TLS connection policies seems to be present:
``` json
{"admin":{"disabled":true},"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"handler":"subroute","routes":[{"group":"group2","handle":[{"handler":"subroute","routes":[{"handle":[{"body":"Hello, there!","handler":"static_response"}]}]}],"match":[{"path":["/health"]}]},{"group":"group2","handle":[{"handler":"subroute","routes":[{"handle":[{"body":"oops","handler":"static_response"}]}]}]}]}],"match":[{"host":["dashboard0.fabre.home.arpa"]}],"terminal":true}]}}},"tls":{"automation":{"policies":[{"issuers":[{"ca":"https://ipa0.fabre.home.arpa/acme/directory","email":"maarten@fabre.be","module":"acme","trusted_roots_pem_files":["/etc/ipa/ca.crt"]}]}]}}},"logging":{"logs":{"default":{"level":"DEBUG"}}}}
``` 

I can't seem to find the source of the inconsistency

OS: Debian Bookworm
caddy version: v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=

**Comment by mholt** [comment]
It could be because .home.arpa is a known internal domain. You could try moving the issuer config into the site block, because I'm trying to remember but I think we treat the global issuer as a public endpoint.

**Comment by vadella** [comment]
OK, that seemed to be the problem. This was not clear from the logs or the documentation

When I moved the config to the site block, I ran into another problem, but it seems I'm [not the first one](https://caddy.community/t/caddy-and-freeipa-dogtag-signature-of-type-es256-not-supported-try-again-with-rs256/21972/3)

**Comment by mohammed90** [comment]
> When I moved the config to the site block, I ran into another problem, but it seems I'm [not the first one](https://caddy.community/t/caddy-and-freeipa-dogtag-signature-of-type-es256-not-supported-try-again-with-rs256/21972/3)

You can tell Caddy to use a specific key type. See [here](https://caddyserver.com/docs/caddyfile/directives/tls#key_type).

**Comment by mholt** [comment]
Ah yeah, we need to improve the docs. I think part of the reason that isn't in there yet is because I'm not sure I'm completely satisfied with the current behavior but I also think it makes sense in general, I dunno. When I'm not mobile next week I need to find the previous issue where this was discussed.

**Comment by girlbossceo** [comment]
Wouldn't it be better for Caddy to just respect the explicitly defined local CA, even if the domain is an internal one?

**Comment by francislavoie** [comment]
Thing is, the CA was only defined locally and not "explicitly" for that site. Any per-site logic will win over global config. A `.home.arpa` hostname is "per-site". That's why the fix is to use the `tls` directive in the given site.
