### ISSUE TITLE
feature request: Set reverse_proxy tls_server_name when IP upstream

### ISSUE THREAD

**Issue by Chuckame** [caddyserver/caddy#6026]
## Problem
When the proxied app do its routing on SNI, then we can loose the SNI if the caddy instance is targetting an IP. As a workaround, I have to set manually the `tls_server_name` to the requested host.

```
sub.domain.tld {
	reverse_proxy https://<ip>:<port> {
		transport http {
			tls_server_name {host}
		}
	}
}
```

## Feature request
It would be great to automatically set `tls_server_name` to the requested nostname when the `reverse_proxy` upstream is an IP

**Comment by mohammed90** [comment]
You have a niche requirement that's very atypical. Usually upstream apps that are served with TLS expect their hostname and SNI to match. The chance of mismatch is typically a sign of misconfiguration. I disagree with the request.

**Comment by mholt** [comment]
Usually, a backend server only has a certificate for its own hostname or IP address, so we leave that the default behavior (no SNI when proxying to IP, or setting SNI to the hostname of the backend if used). It's also simpler and more expected. And more efficient.

The workaround config there is correct for your, admittedly more niche, use case. It's slightly less efficient since we can't reuse the TLS config for every request, but it gets the job done properly as far as I can tell.

Thanks for opening an issue! Feel free to continue discussion but I'll close this now.

**Comment by Chuckame** [comment]
Oh I forgot about certs for explicit ip address, so this feature request now makes no sense. 

@mohammed90 maybe it's a weird need, ok. But how are doing people like me when they want to expose some services through a tunnel? If the tunnel have its own ip, but serve other services that can be behind reverse proxy themselves and provide https directly, how users can be able to reach remote services using services' hostnames?

@francislavoie how to improve the performance as you said, by setting a static value?

**Comment by mholt** [comment]
Usually TLS is terminated at the proxy and the client (at the other end of the "tunnel") doesn't care about the servers proxied to after that, technically speaking.

> how to improve the performance as you said, by setting a static value? Is it just by having explicitly the hostname?

If the backend is serving a certificate for a specific hostname other than its address, then yes just write the hostname there for improved efficiency. Or just have it serve an IP cert (could be self-signed) and then you can remove the SNI setting altogether.

Is your proxy even traversing a public network?

**Comment by Chuckame** [comment]
You can see a bit of my infrastructure here : https://github.com/caddyserver/caddy/issues/6015#issue-2064057632

It's basically caddy > tunnel > caddy > app. 

The certificate is signed through ovh dns challenge for both caddy instances, so I don't know if I can sign a cert for an ip.
