### ISSUE TITLE
Applying for Wildcard certificates for multiple subdomains

### ISSUE THREAD

**Issue by linxic4** [caddyserver/caddy#6027]
How should I set it up so that Caddy can apply for a generic domain certificate? I have a total of 41 website, and each update will trigger the Let's Encrypt restriction. However, all I need to do is apply for one wildcard domain (example, *. example) to fully cover 41 domains.
I asked my friend and he recommended this to me, but I didn't understand it. https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates
Could you please guide me on how to set up Wildcard certificates
```
{

	acme_ca https://acme-v02.api.letsencrypt.org/directory
	acme_dns cloudflare 12345678901234567890
	email admin@example.com
	key_type p384
}
example.com {
	handle /api/* {
		reverse_proxy 127.0.0.1:65535
	}
	handle {
		file_server browse {
    		root /www/root
			hide .*
	    }
		@hidden path */.*
		respond @hidden 403
	}
}
1.example.com {
	reverse_proxy 127.0.0.1:10001
}
.
.
.
40.example.com {
	reverse_proxy 127.0.0.1:10040
}
```

**Comment by francislavoie** [comment]
What don't you understand? We think it's pretty clear.

**Comment by francislavoie** [comment]
You can't put `handle_errors` inside a `handle`, it must be top level. But you may put `handle` inside `handle_errors`. If you simply flip those two lines, it should work.
