### ISSUE TITLE
How to specify a custom 403/404 page for "respond"

### ISSUE THREAD

**Issue by linxic4** [caddyserver/caddy#6029]
This is my configuration document, but for some reason, the "respond" specified 403 cannot use "handle_error" defined parameters
```
example.com {
	handle_errors {
		rewrite * /{err.status_code}.html
		file_server
	}
	file_server browse {
		root * /srv/root
		hide .*
    }
	@hidden path */.*
	respond @hidden 403
}
```

**Comment by francislavoie** [comment]
Use https://caddyserver.com/docs/caddyfile/directives/error instead to trigger an error.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
