### ISSUE TITLE
Status command

### ISSUE THREAD

**Issue by lazee** [caddyserver/caddy#6033]
It would be nice to have a `status` command in the Caddy client, that will tell whether Caddy is running in the background or not. This would be a great addition to the `start`, `stop`, `reload` commands. 

I am working on a small dev tool that are using Caddy as one part of setting up an automated development environment. This tool would have great use for such a `status` functionality.

Finally, thank you so much for all the great work you guys put into Caddy. I Love it!

**Comment by lazee** [comment]
I forgot to mention, that I for now are using `caddy reload` to check whether I am able to reload the config or not. It fails if the daemon aren't running. But it would be much easier if I could just _ping_ the daemon with `status`. I am also looking into just pinging the Caddy endpoint as well, but it feels a little hacky, as my tool then are bound to knowing about internal Caddy configuration.

**Comment by francislavoie** [comment]
You can just do `curl http://localhost:2019/config` to check if it's running, i.e. the admin API is reachable. I'm not sure it would have much value to have a status command :thinking:

**Comment by mholt** [comment]
Yeah, I think I agree; `caddy status` would essentially run that curl command. I don't think it's a hack, it's how I expect you'd check to see if Caddy is running. (You don't even have to technically request the `/config/` endpoint, you could just ping the :2019 endpoint -- you'd get a 404 but that's still up)

Closing, but feel free to continue discussion if needed!

**Comment by lazee** [comment]
Thank you @francislavoie and @mholt. I can absolutely do that. The idea was more from at bash script perspective where I would be able to run code like : (pseudo) if [caddy status == running]; then caddy start; else caddy reload. But I can achieve that with some curl and grepping. Again, thank you.

**Comment by mholt** [comment]
Or just use the status code that curl exits with. If it's 0, Caddy is up. If... 7, I think, it's not. (Or just non-zero)

**Comment by kts** [comment]
Trying Caddy for the first time, I naturally tried `caddy status` to see if was running. I found this issue, so I now know I can do `curl http://localhost:2019/config/`, which is easy, but not if you don't know that that exists or what port its running on. Instead I was looking through `caddy -h` for something like `caddy status` until I went to Google which brought me here.

**Comment by CodyAdam** [comment]
I also found myself doing `caddy start` multiple times because I didn't know that caddy was already running which caused 2 or more instances of caddy listening to the same port. A `caddy status` or `caddy list` (to list all current caddy sessions) would improve developer experience a lot.

**Comment by mholt** [comment]
That would only even work if the same config was being loaded though (otherwise we don't know where to check the admin endpoint, and it can be spoofed anyway).

**Comment by dmaurino79** [comment]
Same as @kts kts. Searched -h for a status, then google and brought me here. I don't agree with the "wouldn't add value" statement from @francislavoie (with all due respect of course)

**Comment by mholt** [comment]
The more typical thing to do is to run `systemctl status caddy` (for example), since it's really the job of the process or service manager to tell you its status. `caddy status` would have the same problem as the other commands (`caddy reload`, etc.) in that it has to know which port is being used for the admin socket. 2019 is the default, but the correct answer anyone's guess unless we scan.

**Comment by atiris** [comment]
Why is checking status **so complicated**?

Simple `status` does not exists (and I believe that caddy would internally detect if it is running much easier than calling `curl` on localhost), `systemctl` shows it is loaded but not active. Last `log` is "Failed to start", but `curl` to localhost shows correct json... So, **it is running or not?** 

*I am frustrated by this. Would it really be such a burden to add a simple status, possibly with some parameter and information about the loaded caddyfile?*

My log:

```txt
root@prosrv:/opt/project14/development# caddy validate
2025/07/25 09:32:54.581 INFO    using adjacent Caddyfile
2025/07/25 09:32:54.581 INFO    using config from file  {"file": "Caddyfile"}
2025/07/25 09:32:54.583 INFO    adapted config to JSON  {"adapter": "caddyfile"}
2025/07/25 09:32:54.583 WARN    Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies    {"adapter": "caddyfile", "file": "Caddyfile", "line": 3}
2025/07/25 09:32:54.584 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc000508d00"}
2025/07/25 09:32:54.584 INFO    http.auto_https server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2025/07/25 09:32:54.584 INFO    http.auto_https enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2025/07/25 09:32:54.584 WARN    http.auto_https server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv1", "http_port": 80}
2025/07/25 09:32:54.585 INFO    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc000508d00"}
Valid configuration
root@prosrv:/opt/project14/development# systemctl status caddy
× caddy.service - Caddy
     Loaded: loaded (/lib/systemd/system/caddy.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2025-07-25 10:57:34 CEST; 38min ago
       Docs: https://caddyserver.com/docs/
   Main PID: 32459 (code=exited, status=1/FAILURE)
     Status: "loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already in use"
        CPU: 88ms

Jul 25 10:57:34 prosrv caddy[32459]: {"level":"info","ts":1753433854.672353,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
Jul 25 10:57:34 prosrv caddy[32459]: {"level":"info","ts":1753433854.6731656,"msg":"adapted config to JSON","adapter":"caddyfile"}
Jul 25 10:57:34 prosrv caddy[32459]: {"level":"info","ts":1753433854.6743011,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":>Jul 25 10:57:34 prosrv caddy[32459]: {"level":"warn","ts":1753433854.6744916,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic>Jul 25 10:57:34 prosrv caddy[32459]: {"level":"info","ts":1753433854.6745725,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":>Jul 25 10:57:34 prosrv caddy[32459]: {"level":"info","ts":1753433854.6749895,"msg":"maxprocs: No GOMAXPROCS change to reset"}
Jul 25 10:57:34 prosrv caddy[32459]: Error: loading initial config: loading new config: http app module: start: listening on :80: listen tcp :80: bind: address already i>Jul 25 10:57:34 prosrv systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Jul 25 10:57:34 prosrv systemd[1]: caddy.service: Failed with result 'exit-code'.
Jul 25 10:57:34 prosrv systemd[1]: Failed to start caddy.service - Caddy.
root@prosrv:/opt/project14/development# curl http://localhost:2019/config/
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"logs":{"def.....ame":"/var/log/caddy/landing.log","output":"file"}}}}}
root@prosrv:/opt/project14/development# 
```

**Comment by francislavoie** [comment]
@atiris You probably ran `caddy start` which runs Caddy _not_ with systemd but as a standalone process, which means when the systemd service tries to start, it can't because you already have the other Caddy process bound to port 80. Make sure to kill all Caddy processes first, _then_ start it with systemd. Never use `caddy start` if you plan to use systemd. Read https://caddyserver.com/docs/running#using-the-service
