### ISSUE TITLE
TLS connection policies

### ISSUE THREAD

**Issue by barmaxence** [caddyserver/caddy#6049]
Hello,

I don't understand why I get this log :
`server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS server_name=srv1 https_port=443`
I don't need to set any TLS connection policy.

(but in any case the server is working well)

Caddyfile
```
{
        admin :2019
        email contact@domain.me
        acme_dns <provider> <token>
        servers {
               metrics
        }
}

##### EXTERNAL #####

abc.domain.me:12443 {
        reverse_proxy abc:5000
}

def.domain.me:12443 {
        @public not {
                path /admin
                path /admin/*
        }
        route {
                reverse_proxy @public def:8080
                respond 401
        }
}

##### INTERNAL #####

ghi.sub.domain.me {
        reverse_proxy ghi:3000
}

jkl.sub.domain.me {
        reverse_proxy jkl:9090
}
```

Thanks

**Comment by francislavoie** [comment]
TLS connection policies are config that define how to perform TLS handshakes for incoming connections. They're necessary for your server to serve HTTPS.

This is part of Caddy's Automatic HTTPS functionality, connection policies get filled in automatically so that HTTPS works with minimal config.

**Comment by barmaxence** [comment]
Thx for your reply.
So since it's part of Caddy's Automatic HTTPS functionality, why this log is displayed ? Connection policies should be automatically and properly defined

**Comment by mholt** [comment]
This log indicates that everything is working normally. The Caddyfile adapter doesn't add TLS connection policies to the JSON because Automatic HTTPS does it implicitly, and this log is verifying that is happening, that's all.

Hopefully that helps answer your question :)

**Comment by francislavoie** [comment]
It's a log at `INFO` level. It's information to tell you about something Caddy is doing. It's normal.
