### ISSUE TITLE
reverse proxy: use the new CA providers

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#6063]
The PR #5784 introduces modular CA providers. The HTTP(S) transport of the reverse proxy module has a copy of the older approach which was removed in the PR #5784. Moreover, the PR included copying the `TLSConfig` struct with minor modifications to.

In the PR, I opted not to touch the reverse-proxy transport to minimize the impact and reduce the complexity of the PR by leaving it focused to the `caddytls` package. Now that the PR is merged, the reverse-proxy module can re-use the logic and introduced modules to have flexible source of certificate-authority pool. Implementing this means the reverse-proxy transport can trust certificates from, e.g., distributed certificate-authority providers shared over distributed storage or other Caddy instances.

One powerful use case of this is when a Caddy instance acts as an ACME server for the internal services, and other caddy instances serving as load-balancers will trust the same certificate authorities used by the caddy ACME server.

The change for this issue requires looking into, at least, the following parts of the `reverseproxy` package:

https://github.com/caddyserver/caddy/blob/b9c40e711115d35c2809313aeec42ab10fcd6914/modules/caddyhttp/reverseproxy/httptransport.go#L55-L57

https://github.com/caddyserver/caddy/blob/b9c40e711115d35c2809313aeec42ab10fcd6914/modules/caddyhttp/reverseproxy/httptransport.go#L502-L601

**Comment by armadi1809** [comment]
I have a question. I am trying to reuse the new `CA` struct created in the linked PR. However, the latest published version of caddy does not have it (yet) in its tls module. What would be the best approach to deal with this?

**Comment by mholt** [comment]
Thank you @armadi1809 !
