### ISSUE TITLE
Feature Request / Skill issue - Managed certificate SAN

### ISSUE THREAD

**Issue by Hacksore** [caddyserver/caddy#6070]
Hi is it possible to use the managed cert approach to generate a single cert with multiple SANs?

Current problem:
I have this config and it will generate multiple certs.

JSON:
```
{
  "apps": {
    "tls": {
      "certificates": {
        "automate": ["myapp.localhost", "localhost", "127.0.0.0"]
      },
      "automation": {
        "policies": [
          {
            "key_type": "rsa4096",
            "issuers": [{ "module": "internal" }]
          }
        ]
      }
    }
  }
}
```
command:
`caddy run --config caddy.json`

What I would like:
Having one cert for `myapp.localhost` with the following SANs:
```
localhost
127.0.0.0
```

Thanks in advanced for the support!

**Comment by mholt** [comment]
First I need to ask: why?

**Comment by Hacksore** [comment]
Well I've been trying to put together [this vite plugin](https://github.com/Hacksore/vite-plugin-caddy/tree/feat/use-caddy-for-cert-gen) with the goal to give vite "automagic" https for local development powered by caddy™.

Original tweet thread:
https://twitter.com/caddyserver/status/1751301437949374974

I've looked around the docs to see if it's possible but I don't think it is with the managed approach.

**Comment by francislavoie** [comment]
We don't issue multi-SAN certificates. https://github.com/https-dev/docs/blob/master/acme-ops.md#use-one-name-per-certificate

Caddy will issue individual certificates for each name, which is sufficient.

**Comment by Hacksore** [comment]
So maybe I keep the multi cert approach and then use SNI as a path forward, assuming it's doable in node/vite.

Closing the issue this as there is no support for my ask and unlikely to change.

Thanks again!

**Comment by mholt** [comment]
I guess I fail to see why multiple SANs per cert is needed? It's generally an anti pattern, and with automation like Caddy's, it doesn't matter if it's multiple certs.

**Comment by Hacksore** [comment]
AFAIK vite will only accept a [single keypair](https://vitejs.dev/config/server-options#server-https) and I want to access my locally running app from different names.

If the one cert contained SANs it would be super easy to implement but now the common names are spread across three certs.

SNI looks like a good alternative here though 🙏.
![image](https://github.com/caddyserver/caddy/assets/996134/3c983fbd-bf5f-40d9-bbf0-b549022793d5)

**Comment by mholt** [comment]
Huh, alright. So vite can serve multiple domains but can only accept one cert? Might be an area for vite to work on...

Anyway yeah, if you can hook into the handshake then that'll probably work I suppose.

**Comment by francislavoie** [comment]
Why do you need to use Caddy's certs in Vite? Why not just use Caddy as an HTTPS-terminating proxy and serve HTTP from Vite?

**Comment by Hacksore** [comment]
that's the current/first impl but I was experimenting with a different direction by letting caddy manage certs and import them into vite.

I might go back to TLS termination as that's way more ergonomic 😅.

**Comment by mholt** [comment]
Ah gotcha. (This is why I keep saying that cert management needs to be integrated into the server/app.)
