### ISSUE TITLE
Caddy stops working, service shows running but not responsive

### ISSUE THREAD

**Issue by jakanaka** [caddyserver/caddy#6072]
Caddy: v2.7.6 h1
OS: Ubuntu 22 LTS

It just stopped working idk why, stopped in a sense that running but not receiving request or not responding, there are a lot of these in the logs

![image](https://github.com/caddyserver/caddy/assets/92713678/5221899c-7f3d-489b-af69-cc5bc1505b71)

**Comment by mholt** [comment]
Can you please post the full logs as a text file (we can't really do anything useful with screenshots)

**Comment by mholt** [comment]
Sure, we can start with that. You can upload a txt file I think.

**Comment by mholt** [comment]
Thanks.

Huh, there's still no error message in that. It's all the end of a stack trace. I suspect a data race? Can you go back even further in the logs to get the actual error message?

**Comment by mholt** [comment]
Any server, whether it's apache or nginx or caddy, etc, has resource constraints by the OS. And the OS in turn has resource constraints. If you get flooded with traffic every server will crash because your OS will crash it. To mitigate DDoS you should use a CDN service like Cloudflare.

**Comment by mholt** [comment]
Yep, so busy servers will use a lot of threads, and you need to allow it in the OS.

**Comment by francislavoie** [comment]
Related: https://github.com/caddyserver/dist/issues/107

NPROC limits the processes for the entire `caddy` user. Are you running other programs under that user?
