### ISSUE TITLE
Doesn't follow symlinks

### ISSUE THREAD

**Issue by TobTobXX** [caddyserver/caddy#6076]
I've st up a simple caddy server to serve static files. This is the config:
```
example.org {
	root * /test/web
	file_server
}
```
Normal files work just fine, but there are some symlinks in this directory:
```
lrwxrwxrwx 1 root root    33 Jan 30 19:23 data.sqlite -> /home/lmp-crawler/web/data.sqlite
lrwxrwxrwx 1 root root    35 Jan 30 19:23 metadata.json -> /home/lmp-crawler/web/metadata.json
lrwxrwxrwx 1 root root    32 Jan 30 19:56 stores.css -> /home/lmp-crawler/web/stores.css
```
The caddy user can read these files, which I've confirmed using an interactive shell as caddy, but also:
```
-rw-r--r-- 1 lmp-crawler lmp-crawler 13414400 Jan 30 18:58 /home/lmp-crawler/web/data.sqlite
-rw-r--r-- 1 lmp-crawler lmp-crawler      356 Jan 30 19:22 /home/lmp-crawler/web/metadata.json
-rw-r--r-- 1 lmp-crawler lmp-crawler      269 Jan 30 19:22 /home/lmp-crawler/web/stores.css
```

There isn't much valuable info in the access log (or I don't understand how to make Caddy talk to me):
```json
{
  "level": "error",
  "ts": 1706641413.1153896,
  "logger": "http.log.access.log0",
  "msg": "handled request",
  "request": {
    "remote_ip": "<my IP>",
    "remote_port": "47892",
    "client_ip": "<server IP>",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "example.org",
    "uri": "/stores.css",
    "headers": {
      "User-Agent": [
        "curl/8.4.0"
      ],
      "Accept": [
        "*/*"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "example.org"
    }
  },
  "bytes_read": 0,
  "user_id": "",
  "duration": 0.000391132,
  "size": 0,
  "status": 403,
  "resp_headers": {
    "Server": [
      "Caddy"
    ],
    "Alt-Svc": [
      "h3=\":443\"; ma=2592000"
    ]
  }
}
```

Please help, Caddy won't tell me where the issue is.

Thanks.

**Comment by francislavoie** [comment]
You can add the `debug` global option to get more detailed logs. Add this at the top of your Caddyfile:

```
{
	debug
}
```

**Comment by TobTobXX** [comment]
Not a whole lot of additional info...
```json
{
	"level": "debug",
	"ts": 1706643764.961704,
	"logger": "http.log.error",
	"msg": "stat /lebensmittelpreise/web/stores.css: permission denied",
	"request": {
		"remote_ip": "2001:171b:2265:d1a0:ea48:d099:9015:f2b3",
		"remote_port": "34172",
		"client_ip": "2001:171b:2265:d1a0:ea48:d099:9015:f2b3",
		"proto": "HTTP/2.0",
		"method": "GET",
		"host": "lebensmittelpreise.ch",
		"uri": "/stores.css",
		"headers": {
			"User-Agent": [
				"curl/8.4.0"
			],
			"Accept": [
				"*/*"
			]
		},
		"tls": {
			"resumed": false,
			"version": 772,
			"cipher_suite": 4865,
			"proto": "h2",
			"server_name": "lebensmittelpreise.ch"
		}
	},
	"duration": 0.000289845,
	"status": 403,
	"err_id": "tyq3xxg1q",
	"err_trace": "fileserver.(*FileServer).ServeHTTP (staticfiles.go:282)"
}
```

**Comment by francislavoie** [comment]
Generally, `caddy` doesn't have access to read things in `/home` because it doesn't have `x` permission for `/home`.

Try moving your files to somewhere like `/srv` and symlinking to there instead.

**Comment by TobTobXX** [comment]
Hmm... I didn't know that you need the x bit on all the directories above.

I tried adding the +x bit to all of them recursively and it didn't work.

Then I followed your recommendation of storing the data in `/home` and now it works. Weird.

Is this inteded? Should I close the issue?

**Comment by francislavoie** [comment]
> I tried adding the +x bit to all of them recursively and it didn't work.

I strongly recommend _not_ doing that. It means any user on your system can see what files exist in all the home directories. There's a reason it's like that by default.

> Then I followed your recommendation of storing the data in `/home` and now it works. Weird.

Did you mean `/srv`?

> Is this intended? Should I close the issue?

It's how Linux works. It's not really a case of intention.

If you have it working now, yes, let's close.

**Comment by TobTobXX** [comment]
Yes I meant `/srv`.

Thanks for helping and sorry for opening an issue for that.

**Comment by francislavoie** [comment]
No worries.

For next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by literallylara** [comment]
I would like to expand on https://github.com/caddyserver/caddy/issues/6076#issuecomment-1917839509: In environments with systemd, the precise reason why Caddy has no access to `/home` is because of the [`ProtectHome=true`](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectHome=) setting in its unit file. This took me a while to figure out since the `caddy` user had the correct access permissions (verified by `su caddy -s /bin/bash -c 'test -r <file> && echo yes || echo no'`).
