### ISSUE TITLE
Add support for disabling ANSI color output

### ISSUE THREAD

**Issue by rgl** [caddyserver/caddy#6077]
Add support for disabling ANSI color output by default or with the [`NO_COLOR='1'` environment variable](https://no-color.org).

ANSI color output does not play well with capturing the output to a text file nor is well supported in Windows.

**Comment by francislavoie** [comment]
I think you mean the log level color for the console encoder?

You sound set `level_format upper` or `level_format lower`. See https://caddyserver.com/docs/caddyfile/directives/log#format-modules

On Windows though, you should use the new modem Windows Terminal, it supports color. Stop using the legacy Command Prompt which doesn't support color properly.

**Comment by rgl** [comment]
@francislavoie sorry, I forgot to mention that it was indeed for the console. but this is being used from vagrant/winrm/ps-remote-session, so I'm not really sure how to configure that whole stack to use a given terminal. even so, caddy should either not use ANSI, provide an easy way to disable ANSI, or check which terminal is being used, and only used ANSI if it knowns that terminal type actually supports ANSI.

I've failed to prevent `caddy validate` from showing ANSI using this `Caddyfile`:

```
{
	log {
		output discard
		format json {
			level_format lower
		}
	}
}
```

It keeps showing ANSI:

```console
> caddy validate --adapter caddyfile
2024/01/31 20:04:42.559 [34mINFO[0m   using adjacent Caddyfile
2024/01/31 20:04:42.560 [34mINFO[0m   using provided configuration    {"config_file": "Caddyfile", "config_adapter": ""}
2024/01/31 20:04:42.572 [34mINFO[0m   redirected default logger       {"from": "stderr", "to": "discard"}
Valid configuration
```

It seems `caddy validate` is using some other configuration. Because its honoring the `output discard` for some output lines.

Either way, I gave up, and I end-up removing the entire `log` section from the Caddyfile, and just pipe caddy to a cmdlet, which made caddy internal logic to disable ANSI, with:

```powershell
caddy validate --adapter caddyfile 2>&1 | Write-Host
```

But would appreciate an easier/obvious way to completely disable ANSI.

**Comment by francislavoie** [comment]
> It keeps showing ANSI:

That's because those logs are emitted _before_ the config is loaded (because it's logs about doing the config loading). It uses the default logger which has this behaviour.

**Comment by rgl** [comment]
And how do we modify that logger? :-)

Is there a caddy cli argument or environment variable?

**Comment by francislavoie** [comment]
There's no configuration for it.

In case you missed it: https://github.com/caddyserver/caddy/pull/6078

**Comment by mholt** [comment]
Yeah, that PR ^ should do what you want :)

**Comment by rgl** [comment]
Nice! `NO_COLOR` is being supported! Thank You! :-)

I'm not sure what to think about not being able to configure the root logger. I have a nagging feeling that, at least, we should have a way to force it to JSON (thinking about an hypothetical use-case: send caddy output directly to some kind of central logging system, which only understands JSON).

**Comment by mholt** [comment]
I'm not sure I understand; you _can_ configure the "root" logger with Caddy's config...

**Comment by rgl** [comment]
Oh, Yes, those lines. The ones emitted before the caddy configuration is loaded.

There is no actual problem. For this issue, the NO_COLOR PR that is linked is perfect :-)

I was only trying to talk about an hypothetical scenario, where not being able to configure the root logger (the one that emits the lines before the config is loaded) could be a nuisance. In such scenario, all the caddy stdout/stderr would be sent to a central logging system that only understands JSON and if it sees anything else, it would either ignore it or crash. In that scenario, it would probably be a bit more difficult to track why caddy wasn't starting. But, please forget about this. This was an halt-baked scenario. And, hopefully, a central logging system would not be that naïve.

**Comment by rgl** [comment]
Indeed, for caddy, the trick is to always trick into non-interactive mode. But that's not always simple to do. It depends on how the software stack (which we might not be able to configure} is setup until the point it actually calls caddy. Sometimes an interactive terminal exists, but that does not necessarily means there's a user interacting with caddy. But i digress. My point is, there should be a simple way to override or force non interactive mode, to use in those cases where caddy heuristics does a wrong choice. As a side note, for example, Debian apt has an environment variable to force non interactive mode.
