### ISSUE TITLE
Bug on named routes when trying to invoke from site blocks

### ISSUE THREAD

**Issue by Z3NTL3** [caddyserver/caddy#6090]
So basically at my ``Caddyfile`` I have defined some named routes. Beneath that I import site block configurations. However it results in something weird. When I do invoke any named route from within the block, it will invoke absolutely nothing. Which is unwanted..

**Caddyfile**
```go
&(err-handler) {
	header Content-Type text/html
	respond "{err.status_code}"
}

&(html-gotool) {
	header Content-Type text/html
	respond <<HTML
	<html>
	<title>go.mod</title>
	<meta
	name="go-import"
	content="simpaix.net/simpa git https://github.com/SimpaiX-net/simpa"
	>
	</html>
	HTML 200
}

import confs/*

```

**Site block**
```
simpaix.net {
	@gotool {
		query go-get=*
	}

	handle @gotool {
		invoke html-gotool
	}

	handle /engine {
		redir https://github.com/SimpaiX-net/simpa
	}

	route * {
		file_server {
			root /var/www/simpaix.net
			index index.htm
			pass_thru
		}
	}

	route * {
		error 404
	}

	handle_errors {
		invoke err-handler
	}
}

```

**Comment by francislavoie** [comment]
Please elaborate. What do you mean by "invokes nothing"? Show your logs (enable the debug global option). Show an example request with `curl -v`.

**Comment by Z3NTL3** [comment]
> Please elaborate. What do you mean by "invokes nothing"? Show your logs (enable the debug global option). Show an example request with `curl -v`.


It gave an error that it cant find static file server, however caddy has root access to the path on disk, so idunno how thats possible. Plus caddy group has full root

**Comment by Z3NTL3** [comment]
Btw @francislavoie I fixed it. Apparently there was nothing going wrong, the only thing that was going wrong was that it tried to serve over the exact match as the path locally on the disk. So thats working very correctly. So I added a rewrite directive.

However for the named routes part it is wrong, snippets work exactly but the named routes invoke doesnt embed the block into the handle error block.

So anyways, Caddy is legit one of the best and easy syntax server engine.

**Comment by Z3NTL3** [comment]
## ++ Addition:
Apparently there were nothing wrong at all. The reason named routes weren't working is because somehow on the request flowing chain, making it flow in that handle_errors and then in the named route made the rewrite vanish. It's not working perfectly fine with:


```
&(err_handler) {
	rewrite * /index.html
	templates
	file_server {
		root "/var/www/errors"
	}
}
```

```
simpaix.net {
	@gotool {
		query go-get=*
	}

	handle @gotool {
		invoke html_gotool
	}

	handle /engine {
		redir https://github.com/SimpaiX-net/simpa
	}

	route /* {
		file_server {
			root /var/www/simpaix.net
			index index.htm
		}
	}

	handle_errors {
		invoke err_handler
	}
}

```

Anyways caddy is awesome!

**Comment by Z3NTL3** [comment]
Just one question:
Because rewrite essentially performs an internal redirect, the Caddyfile adapter will not fold any subsequent, adjacent handlers into the same route if their matchers happen to be exactly the same.

Basically so it means that after a rewrite directive following chaining other handlers in the same route as rewrite is, will get rid of the modificated req URI within that chained handler?

**Comment by mholt** [comment]
Correct; if your rewrite affects your matchers, then do the matching first, and group the rest of the route together.

**Comment by francislavoie** [comment]
I'm not seeing anything actionable here.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
