### ISSUE TITLE
Better Caddyfile errors when a directive is used at top-level

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#6095]
A common mistake users make when writing their Caddyfile is that they'll place directives at the top-level scope (outside a site block) based on a misunderstanding of the [Caddyfile structure](https://caddyserver.com/docs/caddyfile/concepts#structure)

I've been thinking about ways to mitigate this in such a way that doesn't limit possible configurations.

I think what we could do during Caddyfile parsing, if we see a site address that matches a registered directive, we should return an error, explaining that directives must go within a site block. Unknown directives will not produce an error.

The downside to this is "what if the user wants to serve a domain literally called `handle` for some reason"? I think as long as we don't throw an error if they use `https://handle` (with a scheme), then there exists a valid escape-hatch and we don't need to worry about it.

For example, this Caddyfile would produce the following confusing error (because obviously `lb_policy` isn't a directive, why does Caddy think it is one?):

```
reverse_proxy localhost:9000 localhost:9001 {
    lb_policy first
}
```
```
Error: Caddyfile:2: unrecognized directive: lb_policy
```

An even worse example, this Caddyfile _doesn't_ produce an error because things within `handle` _are_ valid directives... but `handle` was parsed as a domain name:

```
handle {
	file_server
}
```

Both of those should produce an error like:

```
Error: Caddyfile:1: parsed 'handle' as a site address, but it is a known directive; directives must appear in a site block 
```

The exact wording of the error can be adjusted, I'm not sure how best to word it right now; open for discussion.

**Comment by mholt** [comment]
I support this.
