### ISSUE TITLE
Query rewrite operations

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#6096]
Currently, the only way we offer to rewrite the query part of the request URI is with the `rewrite` handler (when it has a `?` in the target), or with `uri replace` to perform replacements on the entire URI.

These options are limiting, because many query rewrite operations are difficult to perform with those.

For example, it's impossible (I can't think of a way) to remove a single query key from a request without knowing all the other possible query keys and re-including them all with `&key={query.key}` in the rewrite.

It's also unwieldy to replace a specific query key with another (one way is with `uri replace` but it's awkward and error-prone).

I think the solution is to add `uri query` which supports multiple different types of operations on queries, similarly to the [`header` directive](https://caddyserver.com/docs/caddyfile/directives/header) which has `+` and `-` and so on.

```
# add an additional `foo=bar` (even if there was already `foo=baz`)
uri query +foo bar

# overwrite `foo` with `foo=bar`
uri query foo bar

# delete `foo`
uri query -foo

# rename key `foo` to `bar`
uri query foo>bar

# set a default value (if the key is not already set)
uri query ?foo bar

# replace values in `foo`, changing `bar` to `baz`
uri query foo bar baz

# do multiple operations at once
uri query {
	foo bar
	bar baz
	-baz
}
```

We may or may not actually implement all these operations, but I think most of them would be very nice to have.

Should this be its own directive instead of being added to `uri`? To be discussed.

**Comment by mholt** [comment]
I really like this idea. As part of the `uri` directive, yeah.

**Comment by francislavoie** [comment]
I'll keep this open actually, until we have the `replace` operation implemented. /cc @armadi1809

**Comment by francislavoie** [comment]
I don't quite remember what that entails, so I'll let you make a decision on that, or you can ask specifically what we should include/keep

**Comment by mholt** [comment]
@armadi1809 Yes, I think that'd be great! Both fast substring replacements and regex replacements. Ideally for all params or just a named one. Feel free to use the headers directive as a starting point.
