### ISSUE TITLE
Caddy access logs log client errors at `"level": "ERROR"`

### ISSUE THREAD

**Issue by tgeoghegan** [caddyserver/caddy#6106]
Successfully serving an HTTP 404 response to a request will show up in Caddy access logs with `"level": "ERROR"`, despite the fact that the server hasn't made any error. See [this discussion thread](https://caddy.community/t/caddy-access-logs-log-client-errors-at-level-error/22711) on caddy.community for more details and discussion of some options for solutions.

**Comment by mholt** [comment]
What if I submit a PR for this and we can duke it out there, @francislavoie :smile:

**Comment by francislavoie** [comment]
@mholt that code is already being touched by a couple other PRs so there'll be merge conflicts. Probably best to wait for https://github.com/caddyserver/caddy/pull/6088 and https://github.com/caddyserver/caddy/pull/6082

**Comment by mholt** [comment]
It is a 1-line change AFAICT, so I just went ahead and did it real quick.
