### ISSUE TITLE
debian install error

### ISSUE THREAD

**Issue by millette** [caddyserver/caddy#6121]
```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' doesn't support architecture 'i386'
```

I verified and my apt source list is configured properly.

**Comment by francislavoie** [comment]
We don't make 32-bit builds of Caddy, sorry. You'll need to either [build Caddy yourself](https://caddyserver.com/docs/build) or find a more modern machine to run it on.

**Comment by millette** [comment]
apt install was working before, I'm on amd64 platform. Now apt update outputs that error. Should I report the problem at cloudsmith?

**Comment by mholt** [comment]
> I verified and my apt source list is configured properly.

If you've made _any_ changes to it other than the defaults (and our copy+paste instructions to set up the Cloudsmith repo) then I would be skeptical of this; yours is the only report we've had of the wrong arch being installed. :thinking:

**Comment by millette** [comment]
> Detected/provided for your OS/distribution, version and architecture:
> >>>>:
> >>>>: ... distro=pop  version=22.04  codename=jammy  arch=x86_64

**Comment by millette** [comment]
But if I'm the only one, I will eventually manage my way out of the problem :-) I wanted to signal it in case I wasn't the only one.

**Comment by mohammed90** [comment]
I faced this a few days ago with another project, so I assume there has been an update in apt. Apply this change in the file ` /etc/apt/sources.list.d/caddy-stable.list` to resolve it:

```
- deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main

deb [arch=amd64 signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
```

**Comment by mholt** [comment]
Thanks Mohammed. Yet again I realize I have no idea how anything works

**Comment by millette** [comment]
@mohammed90 @mholt _Who_ knows ;-)

Funny thing is, I didn't change my config

```
deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/pop jammy main
```

And now it "just works" again.

**Comment by francislavoie** [comment]
@millette it was resolved by Cloudsmith yesterday https://github.com/caddyserver/dist/issues/112#issuecomment-1979497301
