### ISSUE TITLE
feat: protect admin with JWT

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#6126]
Hi I've been using Caddy  in `dev` for a while and totally am happy :smile: with it. Now I'm planning to promote my service to `prod` and use API for dynamic route configuration.

My biggest concern is the lack of protection for `admin` endpoint :exploding_head: . That's a **HUGE** security hole and a major blocker for adopting `Caddy` in production as an `edge` service for many ppl.

I can make a contribution to deploy `JWKS` verification for `JWT` with the minimum deps. That will require `golang-jwt` and a little code.
@mholt  Would you accept such contribution :thinking:

**Comment by francislavoie** [comment]
You're meant to use https://caddyserver.com/docs/json/admin/remote/ to set up an admin endpoint for remote access, with client certs for auth. Unfortunately our docs for that are lacking right now, but @mholt can clarify.

**Comment by tetra12** [comment]
@francislavoie What I see on that link is probably a mock implementation for a REST auth. You normally have either:
1. Basic auth - adding a header with: "Authorization: Basic base64(username:password)"
2. JWT Bearer auth - - adding a header with: "Authorization: Bearer my-external-token"

The first method requires maintaining own list of users, e.g own entity provider with a database, which is not :no_entry_sign: a task for Caddy

The second method requires both 3-d party JWT token issue AND authentification. The simplest JWT auth is done with `JWKS`. I can contribute that, but it requires `golang-jwt` and probably more deps.

**Comment by mholt** [comment]
@tetra12 

> My biggest concern is the lack of protection for admin endpoint 🤯 . That's a HUGE security hole and a major blocker for adopting Caddy in production as an edge service for many ppl.

The admin endpoint _is_ protected, you just can't see it very easily by default.

We only bind to a loopback socket, so only local connections can be made. That even excludes Docker containers which are allowed to connect back to their host, since they come in over an internal LAN IP.

We also mitigate DNS rebinding attacks.

Additionally, CORS can optionally be enabled to allow access from a browser without letting just any web page access your API. Only the origins you permit will be allowed access (browsers enforce this by default).

Our remote admin endpoint, which Francis linked to, is secured using TLS mutual auth. Use that for secure remote connections. You can even customize access controls based on the client's key.

I'll close this, but the discussion can be continued if needed.

**Comment by tetra12** [comment]
@mholt It's a bad practice to close the ticket after the first response. You didn't even listen to my arguments. The question is not trivial and is not covered in your docs sufficient for understanding even by advanced programmers.

Okay, let's make it simple. HOW DO I SECURELY ACCESS ADMIN ENDPOINT FROM INTERNET ? :roll_eyes: 
If I have a team of 5 devs, how do I make sure that only MY user can access admin endpoint ?

**Comment by mholt** [comment]
@tetra12 Apologies. It's customary for us to close issues that we believe aren't actionable. I think currently we simply have a gap of understanding or communication. Discussion can still occur even when an issue is closed.

I agree we need to improve our docs with the remote admin endpoint.

Regarding [the `admin/remote` config structure](https://caddyserver.com/docs/json/admin/remote/):

> Okay, let's make it simple. HOW DO I SECURELY ACCESS ADMIN ENDPOINT FROM INTERNET ? 🙄
If I have a team of 5 devs, how do I make sure that only MY user can access admin endpoint ?

Use TLS mutual auth.

Do this by configuring the access controls in the linked config structure. You paste in one or more public keys and then describe the paths and methods that users identified by those public keys are allowed to access.

For example, you might collect a public key from each member of your dev team (or maybe they all share the same one, but that implies they also share the same private key, which is not ideal). You paste in those keys into the config, then maybe you just want them all to have access to the whole config, so you can give them a path of `/` and methods `GET`, `POST`, `PUT`, `PATCH`, and `DELETE`.

Then they connect using TLS client auth (which verifies they control the associated private key) and they can just use the admin endpoint as normal. No application layer logic is needed on the client side -- just configure the TLS client to connect with the private key.

Hopefully that helps
