### ISSUE TITLE
Constant reloading of configfile in 2.7.6

### ISSUE THREAD

**Issue by mzzsfy** [caddyserver/caddy#6129]
see https://github.com/caddyserver/caddy/issues/5789#issuecomment-1836823725 #5860

use caddyfile,I observed that the raw skip_hosts field was not sorted causing the configuration file to be reloaded

**Comment by francislavoie** [comment]
I'm not sure which field you mean. Please share example config.

PRs welcome if you know what must be changed.

**Comment by mholt** [comment]
When I'm at my computer I'll look to see if we're sorting that field before serializing

**Comment by mzzsfy** [comment]
I saw this #5989 #5990 and I don’t know why I still have this problem.
I am using the self-compiled version https://github.com/mzzsfy/Dockerfile/blob/main/caddy/Dockerfile. The compilation command is as follows
```shell
xcaddy build   --with github.com/caddy-dns/alidns
```
![image](https://github.com/caddyserver/caddy/assets/43053461/dc3522a7-05a7-4117-9df4-027d26804a57)

**Comment by mzzsfy** [comment]
The disordered string is
```text
"skip_hosts": [
"xxx.dev.xxx.com",
"xxx.uat.xxx.com",
"null.xxx.com"
],
```

**Comment by mholt** [comment]
Thanks, you beat me to it :joy:

**Comment by mzzsfy** [comment]
I'm sorry, I only saw #5789.

**Comment by Lizzardd** [comment]
Is this issue merged into the latest build?
I'm having the same issue, without changing any config its generating 3 different json files as can be seen from the md5
223131b43ff4f2fa2cf76163fd4ef879  05-41-1711086118.json
3ab44d8339e812917253e52be0ed25d2  05-42-1711086123.json
1af5f131ed39931ed0831691119f2bb4  05-42-1711086124.json

A diff shows it seems to be switching the order of our many domains, one file will have www first and the other 2nd, the 3rd file is a different domain that changes
I get 4 different md5s for the json file

**Comment by francislavoie** [comment]
Please try from the master branch. 2.7.6 is many months behind.

**Comment by Lizzardd** [comment]
I downloaded directly from caddy website, I assume that is from master?

**Comment by Lizzardd** [comment]
I've just tested a build off master and its still doing the same

**Comment by Lizzardd** [comment]
Tested off a master build and it seems ok now, will wait for a new 2.7.7 cut before deploying to our prod server
