### ISSUE TITLE
API: fail to update config with text/caddyfile

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#6131]
I'm trying to programmatically update `caddy` with a simple `http` call with a `caddyfile` as per [docs](https://caddyserver.com/docs/api). 
Getting `400` for the `text/caddyfile` data type:
```go
res, err := s.httpClient.Post(s.cfg.AdminURL, "text/caddyfile", byteBuffer)
if err != nil {
  return err
}
```
```sh
ERROR   admin.api       request error   {"error": "unacceptable content-type: text/caddyfile; 'application/json' required", "status_code": 400}
```
Config works fine for the `application/json` type.

Caddy: v2.7.6 (master)
Go: 1.22.0
OS: Ubuntu 22.04

**Comment by francislavoie** [comment]
What's `s.cfg.AdminURL` set to? You should use the `/load` endpoint: https://caddyserver.com/docs/api#post-load

**Comment by tetra12** [comment]
@francislavoie Yes, used an invalid URL. Thanks for spotting out :+1:
