### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by michealroberts** [caddyserver/caddy#6133]
Firstly, I came to Caddy after reading a lot of marketing hype around how easy it is to setup https for local development.

I'd like to say, it is anything but easy. The documentation really needs more step-by-step guides for different scenarios. Hey ho, onto the problem.

---

Essentially, no matter what I do, I see this error within Chrome:

```
Your connection is not private

...

NET::ERR_CERT_AUTHORITY_INVALID
```

Followed by:

```
This server could not prove that it is localhost; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.
```

This to me is because the certificate issued by Caddy does not contain a Common Name, as show here:

![CleanShot 2024-02-29 at 14 57 01](https://github.com/caddyserver/caddy/assets/84131395/e334da57-4373-47e1-9306-301a34bc83a1)

I cannot see anywhere where I can set this value?

However, I could be wrong. I can't easily debug the issue.

---

**Caddyfile**

```
{
	admin 0.0.0.0:3019
	http_port 3010

	log default {
		output stdout
		format json

		level warn
	}

	servers :3016 {
		listener_wrappers {
			http_redirect
			tls {
				on_demand
			}
		}
	}
}

https://localhost:3016 {
	encode zstd gzip
	log

	handle /api/* {
		reverse_proxy go:3000
	}

	handle /swagger/* {
		reverse_proxy go:3000
	}

	handle {
		root * /srv
		try_files {path} /index.html
		file_server
	}
}
```

---

**Attempts**

I have also tried checking that my Caddyfile is ok with `caddy fmt --overwrite`, I have also tried to load the configuration via the /load endpoint from the terminal:

```
curl "http://localhost:3019/load" -H "Content-Type: text/caddyfile" --data-binary @Caddyfile
```

No luck. So for me, after running around this issue for more than 6 hours now ... I am totally frustrated by Caddy. The documentation just isn't good enough. I can't follow what is wrong, and I can't reference what the issue is.

---

**Versions**

Caddy: v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
Chrome: Version 122.0.6261.69 (Official Build) (arm64)

**Comment by mholt** [comment]
What is in the logs? Caddy will try to install its root certificate into known trust stores, but not all trust stores are supported currently and you may have to install its root cert yourself if that's the case. The logs will reveal all.

**Comment by francislavoie** [comment]
I'm not sure how you're running Caddy or how you installed it. But you may need to run `sudo caddy trust --address localhost:3019` to have Caddy install its root cert in your system/browser trust stores.

**Comment by michealroberts** [comment]
@francislavoie Great, this works. Appreciate the heads up on this.

As a matter of documentation feedback, as I am completely new to Caddy - this wasn't immediately obvious in the "quick start" documentation. Would you accept an MR to amend the docs on this side?

**Comment by michealroberts** [comment]
@francislavoie e.g., From the documentation:

> For local HTTPS, Caddy automatically generates certificates and unique private keys for you. The root certificate is added to your system's trust store, which is why the password prompt is necessary. It allows you to develop locally over HTTPS without certificate errors.

This suggests that the root certificate is added to the trust store ... however, it is not.

**Comment by michealroberts** [comment]
Utilising caddy within a Dockerised environment, so the caddy:latest container as follows:

```yaml
  caddy: &caddy
    image: caddy:latest
    restart: unless-stopped
    container_name: observerly_nox_caddy
    ports:
      - "3019:3019" # Admin
      - "3010:3010" # HTTP
      - "3016:3016" # HTTPS
      
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
```

**Comment by mholt** [comment]
Ah, within a docker environment you're not on the same machine.

**Comment by michealroberts** [comment]
Yes, and I would argue that the documentation should make it clearer that this command:

```
sudo caddy trust --address localhost:2019
```

As opposed to this:

```
docker compose cp \
    caddy:/data/caddy/pki/authorities/local/root.crt \
    /tmp/root.crt \
  && sudo security add-trusted-cert -d -r trustRoot \
    -k /Library/Keychains/System.keychain /tmp/root.crt
```

Is what should be used.

---

My point is that none of these complications are documented, discussed or addressed. Correct me if I am wrong ...

**Comment by francislavoie** [comment]
Well arguably you shouldn't be exposing your admin endpoint outside of your container. That's the unusual part. And you usually don't also have Caddy installed on the host machine if you have Caddy running in Docker.

**Comment by michealroberts** [comment]
@francislavoie But I'm using the documented docker compose setup ... and I didn't have caddy installed on my host machine until advised to use the caddy trust command. 

I'm confused because whether utilising Docker or not, we need to add certs to our host machine's trust stores. This is what is missing from the documentation.

**Comment by francislavoie** [comment]
I don't follow. It's documented right here if you're using Docker: https://caddyserver.com/docs/running#local-https-with-docker

**Comment by michealroberts** [comment]
For me, that command did not work.

I can provide OS details and Docker version details if needed. I use OrbStack for container orchestration.

**Comment by francislavoie** [comment]
Okay, you didn't mention anywhere before that it didn't work.

Yes, more detail would be helpful. I don't have a Mac.
