### ISSUE TITLE
Is there any plan in the future to rewrite Caddy in Rust?

### ISSUE THREAD

**Issue by LordMoMA** [caddyserver/caddy#6136]

**Comment by francislavoie** [comment]
Absolutely not. Caddy is entirely dependent on the Go stdlib's HTTP and cryptography stack, and a bevy of other libraries that depend on the power offered by Go.

In addition, one of Caddy's strengths is the plugin ecosystem, if we were to switch languages we'd leave a majority of our users in the dark.

Using Go is _an advantage_, Caddy is not good in spite of Go, it's good _because_ of Go.

**Comment by mholt** [comment]
Rust is cool but offers few advantages over Go for our use case. Whereas Go offers many advantages over Rust for our use case.
