### ISSUE TITLE
Invalid status codes returned from reverse_proxy when used with replace-response

### ISSUE THREAD

**Issue by ImpostorKeanu** [caddyserver/caddy#6144]
I've been using the [replace-response module](https://github.com/caddyserver/replace-response) alongside `reverse_proxy` recently and observed incorrect status codes being returned from the proxy, e.g., the origin responded with a `404` and the proxy responds with a `200`.

```mermaid
flowchart
UA --> |Request| reverse_proxy --> |Request| Origin
Origin --> |404 Origin Response| reverse_proxy --> |200 Proxy Response| UA
```

After a bit of debugging, it looks like the call to [copyResponse](https://github.com/caddyserver/caddy/blob/8f8204708ac5f1dfdd0ffa7bcad1974ec54e18e9/modules/caddyhttp/reverseproxy/reverseproxy.go#L961) results in a flush action [here](https://github.com/caddyserver/caddy/blob/8f8204708ac5f1dfdd0ffa7bcad1974ec54e18e9/modules/caddyhttp/reverseproxy/streaming.go#L208), which causes a `200` status code to be written after `http.ResponseController.Flush` unwraps and writes to the replace-response's ~~[replaceWriter](https://github.com/caddyserver/replace-response/blob/a85d4ddc11d635c093074205bd32f56d05fc7811/handler.go#L194)~~  [caddyhttp.responseRecorder](https://github.com/caddyserver/replace-response/blob/a85d4ddc11d635c093074205bd32f56d05fc7811/handler.go#L146).

edit: I mistakenly thought I had streaming enabled, which is why I originally referenced `replaceWriter`.

A potential fix would be to check for an `Unwrap` method on the response writer alongside the base one in [reverseproxy.go](https://github.com/caddyserver/caddy/blob/8f8204708ac5f1dfdd0ffa7bcad1974ec54e18e9/modules/caddyhttp/reverseproxy/reverseproxy.go#L956). I've tested this locally but I'm not sure if it's the best solution. I'm also not entirely sure if this is even considered a bug. ~~I know that `flush_interval` is available as a configuration and I haven't tested if it solves the issue, but it definitely was not an obvious solution to the behavior if it is.~~

edit: Setting `flush_interval` does not seem to correct the issue.

```go
type unwrapper interface {
  Unwrap() http.ResponseWriter
}

func (h *Handler) finalizeResponse {
  //...
  // Line 955
  rw.WriteHeader(res.StatusCode)
  
  // Unwrap and write non-200 status code
  if rw, ok := rw.(unwrapper); res.StatusCode != http.StatusOK && ok {
	rw.Unwrap().WriteHeader(res.StatusCode)
  }

  if h.VerboseLogs {
	logger.Debug("wrote header")
  }

  err := h.copyResponse(rw, res.Body, h.flushInterval(req, res), logger)
  //...
}
```

**Comment by mholt** [comment]
Interesting! Thanks for the report and the possible solution(s). I'm a bit busy with my backlog right now but I'd welcome further work on this if anyone wants to contribute. And I can participate in discussion as well.

It does seem like we should write the status code from the upstream. Probably a bug.

I also don't loooove the unwrap solution but if it works, that's good to know. What about the flush interval tuning? Does that work?

**Comment by francislavoie** [comment]
Could you share an actual diff of your change? I'm not sure I follow exactly what you're proposing is changed.

**Comment by ImpostorKeanu** [comment]
Sure thing @francislavoie. I should've done that right off.

```diff
diff --git a/modules/caddyhttp/reverseproxy/reverseproxy.go b/modules/caddyhttp/reverseproxy/reverseproxy.go
index 1648b779..90c85a2e 100644
--- a/modules/caddyhttp/reverseproxy/reverseproxy.go
+++ b/modules/caddyhttp/reverseproxy/reverseproxy.go
@@ -911,6 +911,10 @@ func (h *Handler) reverseProxy(rw http.ResponseWriter, req *http.Request, origRe
        return h.finalizeResponse(rw, req, res, repl, start, logger)
 }
 
+type unwrapper interface {
+    Unwrap() http.ResponseWriter
+}
+
 // finalizeResponse prepares and copies the response.
 func (h *Handler) finalizeResponse(
        rw http.ResponseWriter,
@@ -954,6 +958,10 @@ func (h *Handler) finalizeResponse(
        }
 
        rw.WriteHeader(res.StatusCode)
+    if rw, ok := rw.(unwrapper); ok && res.StatusCode != http.StatusOK {
+        rw.Unwrap().WriteHeader(res.StatusCode)
+    }
+
        if h.VerboseLogs {
                logger.Debug("wrote header")
        }
```

**Comment by francislavoie** [comment]
Okay. So I think unwrapping is fine; see `http.ResponseController` in stdlib that does it as well via an anonymous interface assertion, could do it like that here.

But it feels weird that we're calling WriteHeader twice. Is there any way we can avoid that? Maybe that needs an explanation for why that's correct. I'm concerned it might break some edgecases.

**Comment by ImpostorKeanu** [comment]
> Thanks for the report and the possible solution(s).

My pleasure! Caddy is one of my favorite projects. It's a minor contribution, but it's honest work :smile: 

> What about the flush interval tuning? Does that work?

Tried a few different values (`1s`, `5s`) with no change @mholt ....

**Comment by ImpostorKeanu** [comment]
> But it feels weird that we're calling WriteHeader twice. Is there any way we can avoid that? Maybe that needs an explanation for why that's correct. I'm concerned it might break some edgecases, without having a full understanding of the consequences.

It's no doubt funky. It's actually hurting my brain haha

Currently, we're implicitly setting a status code to `http.rwUnwrapper`s through `http.ResponseController.Flush`.

I think the proposed fix calls `WriteHeader` once, just _on two writers_. The second writer is present only when the `http.rwUnwrapper` interface is satisfied and ensures that `Flush` doesn't have a chance to write the status code to it.

It looks like another workaround would be to pass a `http.Flusher` to the reverse proxy module since `http.rwUnwrapper` is lesser precedence, but module developers would need to keep this in mind:


[ResponseController](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/net/http/responsecontroller.go;l=38)

```go
func NewResponseController(rw ResponseWriter) *ResponseController {
	return &ResponseController{rw}
}

type rwUnwrapper interface {
	Unwrap() ResponseWriter
}

// Flush flushes buffered data to the client.
func (c *ResponseController) Flush() error {
	rw := c.rw
	for {
		switch t := rw.(type) {
		case interface{ FlushError() error }:
			return t.FlushError()
		case Flusher:
			t.Flush()
			return nil
		case rwUnwrapper:
			rw = t.Unwrap()
		default:
			return errNotSupported()
		}
	}
}
```

**Comment by mholt** [comment]
Hmm... typically what I seem to remember is that if a ResponseWriter wraps another one, a call to WriteHeader on the wrapper should also call WriteHeader on that which is wrapped. That way the unwrapping happens implicitly and every time.

**Comment by ImpostorKeanu** [comment]
If I'm tracking right, that does not appear to happen the case here.

I may be looking at the wrong thing, so here's a gif :)

[Screencast from 2024-03-03 10-53-37.webm](https://github.com/caddyserver/caddy/assets/11574161/6a7d4109-0145-4676-99d3-c310c4a64da1)

**Comment by WeidiDeng** [comment]
I wonder if there is a problem with `reverse_proxy` or the plugin itself. When flushing, 200 is written if no status code is set explicitly.

**Comment by mholt** [comment]
200 is Go standard lib's default status code, if no WriteHeader() call has been made yet. A possibility?

**Comment by WeidiDeng** [comment]
I think it's because we only called `WriteHeader` on the wrapped `http.ResponseWriter`, and that status is not written to the underlying response writer.

**Comment by WeidiDeng** [comment]
@ImpostorKeanu Can you try `xcaddy buiild fix-6144` to see if it's fixed.

**Comment by ImpostorKeanu** [comment]
Sorry for the delay on this. Checking now @WeidiDeng .

**Comment by ImpostorKeanu** [comment]
Fix looks good @WeidiDeng! Slick find on FlushError. Embarrassed that I didn't pick up on that. :smile:

**Comment by francislavoie** [comment]
Don't be embarrassed, it's super deep in the weeds. `ResponseController` allows for `FlushError()` now, which didn't exist in the interface prior to that. We just forgot to (didn't realize we needed to) implement that interface when switching to use `ResponseController`.

So you're confirming it fixes the issue for you? If so we can merge!
