### ISSUE TITLE
Automatic http to https redirect not working

### ISSUE THREAD

**Issue by phhoef** [caddyserver/caddy#6147]
I am running caddy (`caddy:latest`) in a docker container.
I've the following Caddyfile

```
{
    email   mymail@test.com
}

dev.test.com:3000 {
	reverse_proxy http://container1:3000
}

dev.test.com:8080 {
	reverse_proxy http://container2:8080
}

dev.test.com:9000 {
	reverse_proxy http://container3:9000
}

dev.test.com:9001 {
	reverse_proxy http://container4:9001
}

```

When I open `https://dev.test.com:3000` I get the correct content and a valid https connection.
But, when I open `http://dev.test.com:3000` I always see the following message
`Client sent an HTTP request to an HTTPS server.`

The response is the same, no matter if I send the request with a browser, curl or postman.
I would like to redirect the http request automatically to https.

From what I understood, this should work out of the box, but for some reason it doesn't.

**Comment by WeidiDeng** [comment]
Automatic http to HTTPS means when visiting http (default port 80) you get redirected to HTTPS (default port 443), not redirecting on the same port.

Use [`http_redirect`](https://caddyserver.com/docs/caddyfile/options#listener-wrappers) for this use case.

**Comment by phhoef** [comment]
Thanks @WeidiDeng, worked like a charm 😄
