### ISSUE TITLE
Autohttps gives wrong redirect for CONNECT requests

### ISSUE THREAD

**Issue by fbuetler** [caddyserver/caddy#6159]
If caddy is used as a forward proxy, e.g. with [forwardproxy](https://github.com/caddyserver/forwardproxy) and automatic HTTPS with automatic redirects to the HTTPS port is used (see Caddy JSON below) and a CONNECT request (to an HTTPS host) is issued, Caddy correctly returns a `308 Permanent Redirect` but to the wrong location.

```bash
➜ curl -v "https://example.com/" --proxy "http://localhost:9080" --proxy-insecure
* Host localhost:9080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:9080...
* Connected to localhost (::1) port 9080
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to example.com:443
> CONNECT example.com:443 HTTP/1.1
> Host: example.com:443
> User-Agent: curl/8.6.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 308 Permanent Redirect
< Connection: close
< Location: https://example.com/
< Server: Caddy
< Date: Fri, 08 Mar 2024 15:59:12 GMT
< Content-Length: 0
<
* CONNECT tunnel failed, response 308
* Closing connection
curl: (56) CONNECT tunnel failed, response 308
```
The location is given as `https://example.com/` (comparing with the original request, this exactly the same), but should actually be `https://localhost:9443`.

This is due to the logic in [AutoHTTPS module](https://github.com/caddyserver/caddy/blob/v2.7.6/modules/caddyhttp/autohttps.go#L437) taking the request host. Also, the port is wrong, I guess mostly due to [these lines](https://github.com/caddyserver/caddy/blob/v2.7.6/modules/caddyhttp/autohttps.go#L447-L448).

This makes clients automatically following redirects a problem, because they will bypass the proxy by doing it.

However, I am not sure if this can be solved cleanly, as obviously the host under which Caddy is living is not part of the request.

Caddy version: `v2.7.6`

Caddy config:
```json
{
    "admin": {
        "disabled": true,
        "config": {
            "persist": false
        }
    },
    "apps": {
        "http": {
            "http_port": 9080,
            "https_port": 9443,
            "servers": {
                "forward": {
                    "listen": [
                        ":9443"
                    ],
                    "routes": [
                        {
                            "handle": [
                                {
                                    "handler": "forward_proxy",
                                }
                            ]
                        }
                    ]
                }
            }
        }
    },
    "logging": {
        "logs": {
            "default": {
                "level": "DEBUG"
            }
        }
    }
}
```

**Comment by francislavoie** [comment]
I guess you'll need to turn off the redirects with https://caddyserver.com/docs/json/apps/http/servers/automatic_https/disable_redirects/ and then add your own `:80` server to handle the redirects. I don't think it makes sense for vanilla Caddy to take into account `CONNECT` stuff, it's out of scope.

**Comment by mholt** [comment]
I do wonder if we should at least consider CONNECT. It might not be hard. I can look into it later.

**Comment by fbuetler** [comment]
@mholt  @francislavoie At this point, I would like to express my appreciation for the caddy ecosystem. Overall, this is a great project and is extremely well designed and implemented. Also, the plugin system for *everything* is a brilliant idea and your presence with the community is unprecedented. It makes fun to dig through the source code and see that this is an amazingly engineered piece of software ❤️

**Comment by francislavoie** [comment]
Thanks for the kind words 😊

> Additionally, autohttps is pretty hard to get right with a forward proxy, as using a host matcher is not possible without restricting the hosts the forward proxy can be used for. Should I open a separate issue for that?

I'm not sure that's true? I thought the target upstream is passed as part of the HTTP line, not the Host header. Or do they have to match for some reason? I thought TLS-SNI should need to match the Host header.

Unfortunately yeah in the Caddyfile we don't have a way to explicitly add a domain to automate cert issuance for right now. Honestly it would be trivial to add, I haven't seen many usecases it would make sense yet, but this might be one of them if what you say is true. Anyway with JSON config you can certainly omit the host matcher and add the domain(s) you need to an explicit automation policy.

**Comment by fbuetler** [comment]
> Anyway with JSON config you can certainly omit the host matcher and add the domain(s) you need to an explicit automation policy.

Indeed, you are right and this is possible with JSON config and I manged to make it work:

```json
        "tls": {
            "certificates": {
                "automate": [
                    "localhost"
                ]
            },
        }
```

I missed the `automate certificate loader` in the [activation list](https://caddyserver.com/docs/automatic-https#activation) and was too much focused on the JSON routes.

**Comment by francislavoie** [comment]
Kinda sounds resolved to me, should we close?

**Comment by mholt** [comment]
Thanks for the kind feedback @fbuetler !

Sounds good to me, feel free to continue discussion if needed.
