### ISSUE TITLE
Ability to set `log_credentials` or `debug` on / off via an ENV var

### ISSUE THREAD

**Issue by ddl-ebrown** [caddyserver/caddy#6160]
Running Caddy in a container within k8s, it would be pretty useful to be able to toggle the `log_credentials` or `debug` setting with an ENV var like

```
debug {$DEBUG:off}
log_credentials {$LOG_CREDS:off}
```

However, since these settings don't have values, but are activated merely by their presence, there's no easy way to do this.

I think the change would be pretty simple to make at https://github.com/caddyserver/caddy/blob/c27425ef5d112bb71e8b7bf4abfb73464fbf869a/caddyconfig/httpcaddyfile/serveroptions.go#L170-L173 for instance... and I think it could be done in a backwards compatible way.

Thoughts?

**Comment by francislavoie** [comment]
You can just do this:

```
{
	{$LOG_CREDS}
}
```

set the var to `log_credentials` if you want it on, empty string otherwise.

**Comment by francislavoie** [comment]
We don't do switches like that, because "off" is the same as "no config at all". We don't want two ways to configure the same thing.
