### ISSUE TITLE
bug: fail to obtain ACME cert for masked subdomains

### ISSUE THREAD

**Issue by tetra12** [caddyserver/caddy#6166]
I use a mask for my subdomains like `*.<my-domain>.com` :point_up: 

This works fine and I can `ping` my masked domain as `foo.my-domain.com`, `bar.foo.my-domain.com`.

I can even serve a subdomain, which fits the mask, with `http` :smiley: 
```sh
// this works
http://admin.<my-domain>.com {
  reverse_proxy {}
}
```

However, when I try to serve `tls` for one of its names
```sh
// this doesn't work
admin.<my-domain>.com {
  reverse_proxy {}
}
```
```sh
could not get certificate from issuer","identifier":"admin.<my-domain>.com","issuer":"acme.zerossl.com-v2-DV90","error":" HTTP 400 urn:ietf:params:acme:error:invalidContact - A contact URL for an account was invalid",
```
This may be an ACME error from `Cert-Magic`. What could be a possible fix or a workaround? :roll_eyes:

**Comment by mohammed90** [comment]
> What could be a possible fix or a workaround?

ZeroSSL now requires an email address. This isn't an issue/bug with Caddy nor with certmagic.

**Comment by mholt** [comment]
Hmm although they shouldn't be requiring it yet AFAIK.

**Comment by mholt** [comment]
I just busted with them that an email are is not required yet.

What are your full logs? Caddy should also be trying Let's Encrypt.

**Comment by francislavoie** [comment]
See https://caddyserver.com/docs/automatic-https#errors. Caddy usually tries Let's Encrypt first then falls back to ZeroSSL, and continues to retry both if they still fail, while avoiding rate limits by slowing itself down.

**Comment by xatier** [comment]
Then back to my original question, is there a way to supply email via CLI flags when using Caddy with `reverse-proxy` mode?

On the acme vendors, it would be great if we can specify the vendor via a flag. Fail fast if the specified vendor returns an error.

**Comment by francislavoie** [comment]
No. You can see the supported flags by running `caddy help reverse-proxy`. If you need further customization, then use a Caddyfile. Those commands are just meant for quick-and-dirty servers for local use, not for a long-running server.

**Comment by mholt** [comment]
Closing due to... I think it's answered? But also unclear if there's a problem here. (Feel free to continue discussion if needed.)
