### ISSUE TITLE
There should be an easy way to hide the "Served with caddy" watermark with file_browser

### ISSUE THREAD

**Issue by VasilisThePikachu** [caddyserver/caddy#6167]
Yes, I know you can copy the template and remove the watermark by providing a template to ``browse`` ([source 1](https://caddyserver.com/docs/caddyfile/directives/file_server), [source 2](https://caddy.community/t/remove-foot-mark-served-with-caddy-and-file-manager/967))

However, it would still be nice to more easily be able to remove it. Avarage joe using my page to download a file probably does not need to know that I'm using caddy or even know what this mystical caddy thing is. Having an easy switch would be nice.

![image](https://github.com/caddyserver/caddy/assets/34938708/0abdad89-5771-4165-974b-518346fc1c5a)

**Comment by mholt** [comment]
But I worked hard on that template and making it easy to remove the credit would make me sad 😞 

(Community effort actually)

**Comment by VasilisThePikachu** [comment]
I- I feel kind of bad now....

Well I'm not saying it's bad, hell the temple is amazing. First time I saw it I was actually surprised since I was trying to replicate a setup by someone that used nginx which just looked plain.

Though having the option to hide the credit would be nice... Or at least change the graphic maybe

Point is... It looks a little ugly in certain situations. Depending on who your target audience for the site the watermark is just kind of filling space.

**Comment by mholt** [comment]
Ah :) Well, (don't feel bad) the more practical reason is that I don't really know of a good way to introduce a config setting that is dependent on the template (at least, not off the top of my head).

But part of it, too, is simply that I guess I am not convinced of the actual problem. (Which can still be solved by copy-paste-delete, done.)

I expect people who don't know what it is or means will simply ignore it...

**Comment by francislavoie** [comment]
I agree with Matt, the way to do this is to customize the template. Adding config surface for this seems wasteful.

The fact is, Caddy is an open source project, and it's Matt's full time job, funded entirely by sponsorships. Any kind of soft advertising is beneficial to the project, we need ways to get eyes on the project to hopefully get sponsorships.
