### ISSUE TITLE
feat: enable access log with wildcard

### ISSUE THREAD

**Issue by scratchmex** [caddyserver/caddy#6178]
If I want to enable access logs (which should be enabled by default IMO) for a wildcard matcher it doesn't work. I would need to put `log` directive on every domain.

I want an easy way of enabling access logs to all my services

I am happy to make a PR if we agree on an approach that aligns with caddy vision

## example
```
*.my.tld {
  log
}

service.my.tld {
  reverse_proxy 1.2.3.4:6767
  # log  << I don't want to have to put this on every service, even with snippets
}
```

output from `caddy adapt`

```json
{
    "apps": {
        "http": {
            "servers": {
                "srv0": {
                    "listen": [
                        ":443"
                    ],
                    "routes": [
                        {
                            "match": [
                                {
                                    "host": [
                                        "service.my.tld"
                                    ]
                                }
                            ],
                            "handle": [
                                {
                                    "handler": "subroute",
                                    "routes": [
                                        {
                                            "handle": [
                                                {
                                                    "handler": "reverse_proxy",
                                                    "upstreams": [
                                                        {
                                                            "dial": "1.2.3.4:6767"
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "terminal": true
                        },
                        {
                            "match": [
                                {
                                    "host": [
                                        "*.my.tld"
                                    ]
                                }
                            ],
                            "terminal": true
                        }
                    ],
                    "logs": {
                        "logger_names": {
                            "*.my.tld": ""
                        },
                        "skip_hosts": [
                            "service.my.tld"  <<< why default behavior is to have this?
                        ]
                    }
                }
            }
        }
    }
}
```

## related

- [Enable access logs globally on all sites using Caddyfile](https://caddy.community/t/enable-access-logs-globally-on-all-sites-using-caddyfile/14363)
- [Enable logging globally](https://caddy.community/t/enable-logging-globally/7996)

**Comment by francislavoie** [comment]
> which should be enabled by default IMO

It's easier to have opt-in config rather than opt-out config. Not everyone needs access logging, so it's best to have users opt-in.

I don't see the problem with adding `log` to each site. You can configure how the logs are written via global options, but you must enable access logging in each site. It's the same as having to enable `encode` in each site, `tls` in each site, etc. It's consistent.

The problem with adding a global option to blanket-enable logging is that we'll inevitably have someone later come and say "well I enabled it globally, but I want to turn it off for this _one site_, how do I do that?" and :roll_eyes: that's not a path we want to go down, we'd need another directive or whatever to allow an opt-out, etc. Just no. Enable it in each site you want it on for.

**Comment by mholt** [comment]
Thanks for the issue/feature request! I think Francis' reasoning is sound, and is typically what we abide by in this project (with few exceptions, like security defaults). Feel free to continue discussion if needed.
