### ISSUE TITLE
Google Chrome version 122.0.6261.129 (Official Release) (64-bit) can't make http3 connection to caddy server v2.7.6!

### ISSUE THREAD

**Issue by masx200** [caddyserver/caddy#6180]
Google Chrome version 122.0.6261.129 (Official Release) (64-bit) can't make http3 connection to caddy server v2.7.6!

```
{
	debug
	local_certs

	servers :443 {
		protocols h1 h2 h2c h3
	}

	servers :8443 {
		protocols h1 h2 h2c h3
	}
}

desktop-5rh4po7.manx-sun.ts.net , https://desktop-5rh4po7.manx-sun.ts.net:8443 {
	encode gzip
	tls internal

	reverse_proxy * http://localhost:8989 {
	}
}

```

```
请求网址:
https://desktop-5rh4po7.manx-sun.ts.net/speedtest.js
请求方法:
GET
状态代码:
200 OK

引荐来源网址政策:
strict-origin-when-cross-origin
Accept-Ranges:
bytes
Alt-Svc:
h3=":443"; ma=2592000
Cache-Control:
no-cache, no-store, no-transform, must-revalidate, private, max-age=0
Content-Length:
16965
Content-Type:
text/javascript; charset=utf-8
Date:
Tue, 19 Mar 2024 08:09:14 GMT
Expires:
Thu, 01 Jan 1970 08:00:00 CST
Last-Modified:
Fri, 08 Jul 2022 08:58:37 GMT
Pragma:
no-cache
Server:
Caddy
Vary:
Origin
X-Accel-Expires:
0
:authority:
desktop-5rh4po7.manx-sun.ts.net
:method:
GET
:path:
/speedtest.js
:scheme:
https
Accept:
*/*
Accept-Encoding:
gzip, deflate, br, zstd
Accept-Language:
zh-CN,zh;q=0.9
Referer:
https://desktop-5rh4po7.manx-sun.ts.net/
Sec-Ch-Ua:
"Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"Windows"
Sec-Fetch-Dest:
script
Sec-Fetch-Mode:
no-cors
Sec-Fetch-Site:
same-origin
User-Agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
```
![image](https://github.com/caddyserver/caddy/assets/34191203/0a46bc99-9851-4942-9440-18ab6c6e588c)

**Comment by masx200** [comment]
Firefox version 123.0.1 (64-bit) was able to successfully establish an HTTP3 connection with Caddy Server v2.7.6!

**Comment by masx200** [comment]
```
POST | https://desktop-5rh4po7.manx-sun.ts.net/backend/empty.php?r=0.5578345565892333



POST
	https://desktop-5rh4po7.manx-sun.ts.net/backend/empty.php?r=0.5578345565892333
状态
200
版本HTTP/3
传输20.97 MB（大小 0 字节）
Referrer 策略strict-origin-when-cross-origin
DNS 解析系统

	
access-control-allow-origin
	*
cache-control
	no-cache, no-store, no-transform, must-revalidate, private, max-age=0
content-length
	0
date
	Tue, 19 Mar 2024 08:08:58 GMT
expires
	Thu, 01 Jan 1970 08:00:00 CST
pragma
	no-cache
server
	Caddy
vary
	Origin
x-accel-expires
	0
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Alt-Used
	desktop-5rh4po7.manx-sun.ts.net
Connection
	keep-alive
Content-Encoding
	identity
Content-Length
	20971520
DNT
	1
Host
	desktop-5rh4po7.manx-sun.ts.net
Origin
	https://desktop-5rh4po7.manx-sun.ts.net/
Referer
	https://desktop-5rh4po7.manx-sun.ts.net/speedtest_worker.js?r=0.18684208809089708
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0

```

**Comment by mohammed90** [comment]
> Google Chrome version 122.0.6261.129 (Official Release) (64-bit) can't make http3 connection to caddy server v2.7.6!



> Firefox version 123.0.1 (64-bit) was able to successfully establish an HTTP3 connection with Caddy Server v2.7.6!

This indicates it's a Chrome "issue", not a Caddy "issue". The use of _issue_ is generous because there's no indicator of a bug. Browsers have their own criteria of when to use HTTP/3, and Chrome in particular is very picky.

I run Caddy on my servers, and I see Chrome (122.0.6261.129) uses h3 for 3 resources but uses h2 for the rest.

**Comment by masx200** [comment]
![image](https://github.com/caddyserver/caddy/assets/34191203/ce041611-5ec3-4a1b-abe8-861111404362)

**Comment by masx200** [comment]
After my test visits to https://quic.nginx.org/quic.html website, both Firefox and Chrome will open http3 connections!
Is this weird?

**Comment by masx200** [comment]
```
caddy  reverse-proxy --from https://localhost:11111 --to https://quic.nginx.org --debug --disable-redirects  --internal-certs  --change-host-header
```

**Comment by masx200** [comment]
![屏幕截图 2024-03-19 211944](https://github.com/caddyserver/caddy/assets/34191203/73b1d432-4347-4d05-bd66-26741d891fb3)
![屏幕截图 2024-03-19 212030](https://github.com/caddyserver/caddy/assets/34191203/f3d65c57-5f9c-4f59-90e3-0284b063f6f0)

**Comment by masx200** [comment]
After my test, using a caddy reverse proxy to access https://quic.nginx.org/quic.html websites from https://localhost:11111, Firefox will open http3 connections!
Chrome won't open http3 connections!After 3000 requests, it can be proved that the problem does exist!

**Comment by masx200** [comment]
![屏幕截图 2024-03-19 212846](https://github.com/caddyserver/caddy/assets/34191203/c20a8658-0584-4f1b-a811-a744a3debe66)
![屏幕截图 2024-03-19 212958](https://github.com/caddyserver/caddy/assets/34191203/09cbc0f4-f6cc-4d85-8118-05db53bb18c9)

**Comment by masx200** [comment]
I finally figured out why, because the server uses a self-signed certificate, Chrome won't upgrade to http3!

**Comment by mohammed90** [comment]
> I finally figured out why, because the server uses a self-signed certificate, Chrome won't upgrade to http3!

 To quote myself:

> Browsers have their own criteria of when to use HTTP/3, and Chrome in particular is very picky.
