### ISSUE TITLE
How to configure to support certificate hosting for non 80/433 ports freedomain/dnsexit.如何配置才能支持非80/433端口freedomain/dnsexit 的证书托管

### ISSUE THREAD

**Issue by LY1806620741** [caddyserver/caddy#6181]
caddy 不能在Termux中使用80/443端口，如何配置才能支持freedomain/dnsexit 的域名API，来自动续期。Caddy cannot use port 80/443 in Termux. How to configure it to support the domain name API of freedomain/dnsexit and automatically renew it

如果我的Termux不能使用80端口和433端口,如何申请ssl证书.How to apply for an SSL certificate if my termux cannot use ports 80 and 433

这看起来只能通过域名验证途径。This seems to only be possible through domain name verification（ACME DNS challenges？）.

这带来了新的复杂性，而不像caddy所说的那么简单能得到。因为域名续签需要修改域名绑定，需要支持不同域名提供网站的dns api。This brings new complexity, not as simple as Cady said it can be obtained. Because domain name renewal requires modifying domain name binding, it is necessary to support different domain names to provide website DNS APIs

所以请问要怎么支持[DNSExit](https://dnsexit.com/),别名[freedomain](https://freedomain.one/dns/ssl-api/).So, may I ask how to support [DNSExit](https://dnsexit.com/), alias [freedomain](https://freedomain.one/dns/ssl-api/).

caddy封装了大量的逻辑，当他出问题时，让我有点晕头转向了。Caddy encapsulated a lot of logic, and when he had a problem, it made me feel a bit dizzy and disoriented

**Comment by mholt** [comment]
I don't think there are currently [libdns](https://github.com/libdns) implementations for either DNSExit or Freedomain (and I'm not familiar with them). First thing to do would be to implement one/both of those (probably easy if they have an API), then a Caddy plugin is very very simple.

But yeah, if you can't use ports 80 and 443, then you need a DNS provider implementation. Once that is written then it's pretty trivial: just download Caddy with your DNS plugin and you can run it even on Termux.
