### ISSUE TITLE
Feature request: add the "ignore_loaded_certificates" option to caddyfile

### ISSUE THREAD

**Issue by lriley2020** [caddyserver/caddy#6190]
Looking through the forums, I have found another person with the same problem, but no conclusion seemed to be drawn from it. 
I have a cloudflare origin certificate that is valid for *.liamriley.me, which I load in my caddyfile to use for sites that use cloudflare. However, I still want to use caddy's managed auto https service for websites that don't use cloudflare, and the auto https functionality is disabled (as expected) for domains like xyz.liamriley.me that aren't using cloudflare. I can see that there is an option here for changing this behaviour in the json file: [https://caddyserver.com/docs/json/apps/http/servers/automatic_https/ignore_loaded_certificates/](https://caddyserver.com/docs/json/apps/http/servers/automatic_https/ignore_loaded_certificates/)
However, this option doesn't seem to be available in the caddyfile - is there any chance that it could be added for ease of use?
Thanks :)

**Comment by francislavoie** [comment]
It's here: https://caddyserver.com/docs/caddyfile/options#auto-https

**Comment by lriley2020** [comment]
Oops sorry, should've looked through docs more to find that myself! Ah well, at least I'm generating google results for other people searching with the same issue! I'll close this now. Thanks very much :)
