### ISSUE TITLE
I want to use HTTP2 protocol, but I don't need TLS

### ISSUE THREAD

**Issue by huddhudd** [caddyserver/caddy#6194]
I have such a need
I want to use HTTP2 protocol, but I don't need TLS

My requirements are high concurrency and low latency,. But I am not worried about safety issues.
At present, the data of the header is larger than that of the body, so the latency and traffic are very high. I want to use the HTTP2 protocol. But TLS will also increase latency and overhead

As a result, Nginx can no longer satisfy me. Can Caddy use it this way?

**Comment by mholt** [comment]
You can enable H2C (HTTP/2 over Cleartext). But only specialized clients support this (web browsers don't). https://caddyserver.com/docs/caddyfile/options#protocols
