### ISSUE TITLE
Faster non cryptographic hash for load balancing

### ISSUE THREAD

**Issue by jadidbourbaki** [caddyserver/caddy#6201]
I have changed the non cryptographic hash used by Caddy from fnv1 to xxhash, which is known to have better throughput than the FNV family of hashes (https://github.com/Cyan4973/xxHash). Was wondering if there is any comments on creating a PR for this change to the main caddy branch? Just a suggestion, looking to find ways to contribute to the caddy project. Love y'all's work. :-) 

https://github.com/jadidbourbaki/caddy/commit/de2a2f6dbc50b3ce59467dfa377a69216f9f18e3

**Comment by mholt** [comment]
Neat, I haven't heard about xxhash, but @cespare's library looks good to me. I like Caleb's work; he's a very talented developer so I'm sure it'll be a suitable dependency for our project.

Feel free to submit a PR :)
