### ISSUE TITLE
Question on sync.Pool for eTag and etag Hash function

### ISSUE THREAD

**Issue by jadidbourbaki** [caddyserver/caddy#6205]
I noticed this [comment](https://github.com/caddyserver/caddy/blob/master/admin.go#L973) originally added by this PR (https://github.com/caddyserver/caddy/commit/f259ed52bb3764ce4fd5d88f1712cb43247c2639). 

Just to confirm, is the ask here to make the [etag hasher](https://github.com/caddyserver/caddy/blob/master/admin.go#L949) be allocated through a sync.Pool? Is this an operation accessed through various go routines concurrently? Would love to try my hand at prototyping this just want to make sure I understand the ask.

Further, any interest on changing this hash function for eTags from fnv to the faster xxhash similar to the change for load balancing in reverse proxy?  I imagine the need for a faster hash is not that big in this case as reloading configurations is an off the critical path operation?

Thank you for your time, and I look forward to your input.

**Comment by WeidiDeng** [comment]
Personally, I'm against micro-optimization like this. Admin endpoints optimization is not a priority unless it's common enough in daily usage.

Changing hash function is a small enough change that I think is fine. Adding sync.Pool is not. There are better places to use sync.Pool,

**Comment by jadidbourbaki** [comment]
Thank you @WeidiDeng , I absolutely see where you're coming from here. There are definitely better places to use sync.Pool and this, being off the critical path, is probably not it. With regards to changing the hash function, if you are leaning towards it being a small enough change so as to not be an issue, I will put in a PR soon. :-)

**Comment by WeidiDeng** [comment]
Sure, prs are welcome.
