### ISSUE TITLE
Request: Cut new Go caddy version to address quic-go <0.42.0 CVE

### ISSUE THREAD

**Issue by BBKolton** [caddyserver/caddy#6210]
An older version of quic-go has a CVE issued for versions <0.42.0 https://github.com/advisories/GHSA-c33x-xqrf-c478

Thanks to 32f7dd44aea270fa6c50bbf80acf5b831fc6ffcd, caddy is already up-to-date with the latest quic-go, 0.42.0. However, it's not possible to upgrade quic-go in consumers of caddy, as the new quic-go version breaks caddy @v2.7.6. 

I humbly request that the maintainers cut a new version of caddy ASAP that includes the above referenced commit so that consumers of this repo can fix our CVE warnings :)

**Comment by mohammed90** [comment]
We're planning on cutting a release soon, though not specifically for this dep upgrade. Users who cannot wait for the release can build Caddy from HEAD or the commit 32f7dd44aea270fa6c50bbf80acf5b831fc6ffcd using `xcaddy`:

```
xcaddy build 32f7dd4
```

**Comment by BBKolton** [comment]
Thank you for the quick response! I'll use the commit you listed in the meantime. Do you have a rough estimate for when the release might be made?

**Comment by francislavoie** [comment]
See https://github.com/caddyserver/caddy/issues/6209#issuecomment-2032989895

**Comment by epelc** [comment]
For anyone trying to do this you can run the following:

```
go get github.com/caddyserver/caddy/v2@master
# update list of other deps
go mod tidy
# Pull in above repo update from caddy if you use vendoring
go mod vendor
```
