### ISSUE TITLE
why not change the type map[string]bool to map[string]struct{} in importgraph.go file

### ISSUE THREAD

**Issue by danish-mehmood** [caddyserver/caddy#6224]
i would like to propose a tiny code improvement, where we can change the **map[string]bool** type inside importgraph.go file to **map[string]struct{}** type and treat the nodes field of the **importGraph** struct just like a set.
![caddy](https://github.com/caddyserver/caddy/assets/35922417/6f0bdd65-4228-426f-a3f3-2a3c209e17c8)

**Comment by mohammed90** [comment]
What's the gain? The entire structure is internal

**Comment by danish-mehmood** [comment]
@mohammed90 you are absolutely right , didn't think too much about it

**Comment by mholt** [comment]
Without looking I don't remember the purpose of the `bool` -- if it's just for syntactic sugar, then sure, a `struct{}` could be used. This prevents an allocation. [I am not sure ](https://gist.github.com/davecheney/3be245c92b61e5045f75?permalink_comment_id=2671632#gistcomment-2671632)

Not sure if it matters here. Maybe on huuuuge Caddyfiles.

**Comment by danish-mehmood** [comment]
@mholt Yes it is a **syntactic sugar**, using the bool the author is trying to create a **quasi set**, **struct{}** would be better, just like you rightly said it prevents an unnecessary allocation. if you want me to make a change please comment, I would be happy to open a **pull request**.

**Comment by mholt** [comment]
I think the gain is minimal; I have no opinion either way. If a PR is created I'd probably be fine with it, but I'm OK with it as-is too.
