### ISSUE TITLE
Duplicate strings.Count in path matcher

### ISSUE THREAD

**Issue by hlidotbe** [caddyserver/caddy#6233]
Hi,

Unless I'm mistaken there's a redundant count in this check: 

https://github.com/caddyserver/caddy/blob/f4840cfeb85ac33d29a1ab88d474750041a98733/modules/caddyhttp/matchers.go#L457-L460

if it's indeed a mistake I'll do a PR ASAP.

**Comment by mholt** [comment]
Oh the second one is there in case the first one fails.

...

j/k. Would happily accept a PR. Thanks!
