### ISSUE TITLE
New Release Needed

### ISSUE THREAD

**Issue by pnegahdar** [caddyserver/caddy#6235]
When is the next release of caddy planned? Give the recent fixes merged for the http2 ddos, we're eager to update via the main channels (e.g. caddy-builder) without changing our pipelines to build from master. 

Thanks!

**Comment by johnzhanghua** [comment]
Yes, please.  

I have this govulncheck error using v2.7.6.

`Vulnerability #1: GO-2024-2682
    Denial of service via connection starvation in github.com/quic-go/quic-go
  More info: https://pkg.go.dev/vuln/GO-2024-2682
  Module: github.com/quic-go/quic-go
    Found in: github.com/quic-go/quic-go@v0.41.0
    Fixed in: github.com/quic-go/quic-go@v0.42.0
`

**Comment by mholt** [comment]
We're working on it :) I'm down to reviewing PRs for 2.8. My notification backlog is about 3 pages long.

**Comment by mohammed90** [comment]
Also, if appeasing the scanners with 0-CVEs is desired, consider Chainguard images:
https://images.chainguard.dev/directory/image/caddy/overview
