### ISSUE TITLE
IP passthrough issue

### ISSUE THREAD

**Issue by 9mlcy7** [caddyserver/caddy#6236]
Hello, I encountered an issue with passing the real client IP when using reverse proxy.
Problem: When the client accesses the Caddy server, and then Caddy reverse proxies to the upstream server, although I have already set the request headers, the upstream server's nginx still gets the Caddy server's local IP instead of the client's IP. I cannot modify the upstream server because it belongs to the client. I want to achieve a transparent pass-through effect, but failed.

Caddy version: v2.6.4 h1:2hwYqiRwk1tf3VruhMpLcYTg+11fCdr8S3jhNAdnPy8=

```
Caddyfile:
{
        auto_https off
        admin "0.0.0.0:2019"
}
http:// {
        route {
                reverse_proxy 192.168.0.121:1011 {
                        header_up X-Real-IP 192.168.0.105
                        header_up X-Forwarded-For 192.168.0.105
                        header_up X-Forwarded-Host 192.168.0.105
                        header_up Referer http://192.168.0.105
                }
        }
}
```

**Comment by mholt** [comment]
> the upstream server's nginx still gets the Caddy server's local IP instead of the client's IP.

In what way? The connection will always be coming from Caddy, nginx has to be reading the headers to get the IP...

(Closing, since I'm not sure this is a bug and it's not really actionable right now, but we can reopen if needed. Feel free to continue discussion.)

**Comment by mholt** [comment]
That might require extra config on nginx's side: https://gist.github.com/dublado/30494c771730437ee88209f168b9affd

**Comment by 9mlcy7** [comment]
Sorry to bother you again. If the service being reverse proxied by Caddy is a web service, and the service itself does not provide a specific method to retrieve the client IP but instead directly uses request.getRemoteAddr(), it will get the IP address of Caddy. In this situation, is it possible to change the Remote_IP that Caddy sends with the request?
