### ISSUE TITLE
Caddy ignoring system proxy when doing ACME requests

### ISSUE THREAD

**Issue by M0ustach3** [caddyserver/caddy#6238]
# Environment 
## OS
Tested with Alpine Caddy image (not the docker one, the fully-fledged Alpine OS)
## Caddy version
Tested with Alpine-packaged Caddy version 2.7.6. The following APKBUILD was used : [https://git.alpinelinux.org/aports/tree/community/caddy/APKBUILD?id=6761af060cbc7e59178f41076b7ff942f1b06097](https://git.alpinelinux.org/aports/tree/community/caddy/APKBUILD?id=6761af060cbc7e59178f41076b7ff942f1b06097)

# Description
## What is wrong
Hi all, thank you for your amazing work on Caddy.
I've been deploying a private PKI with Vault recently, and wanted to plug the ACME capabilities of Caddy to automate cert renewal.

The issue seems to be that, when requesting ACME certificates, Caddy doesn't seem to want to use the system-configured HTTP proxy and instead tries contacting the ACME server directly.

## Architecture
The current architecture is this : 

PKI (ACME SERVER) <-> Firewall 1 <-> Squid HTTP Proxy <-> Firewall 2 <-> Caddy webserver

## Log Output
On Caddy itself, you can't really see much, as the ACME process is doing fine. However, when you check on the Firewall 2 listed above, you can see that Caddy gets blocked :

![Caddy_ACME](https://github.com/caddyserver/caddy/assets/37956764/5a43ed10-8d70-42e8-9fbf-1816b9fae362)

## Related Issues
I found that there were several closed issues a few years ago (#1433 in 2017 and #5178 in 2022) but this was not really relevant, as these guys found out that the Squid Proxy was not used when setting the directive reverse_proxy in Caddy. This is not my case. I wasn't able to find any other user online that had a similar issue...

# Bug reproduction

The minimal setup for the reproduction of the bug would be :

## One firewall running whatever OS
I got OPNsense but won't matter much. Block absolutely everything except traffic to a fictive Squid HTTP proxy (which we'll name squid-001)

VM with Caddy installed. Proxy parameters set system-wide with something like this : 
```bash
export HTTP_PROXY="http://squid-001:3128"
export HTTPS_PROXY="http://squid-001:3128"
export FTP_PROXY="http://squid-001:3128"
export RSYNC_PROXY="http://squid-001:3128"

export http_proxy="http://squid-001:3128"
export https_proxy="http://squid-001:3128"
export ftp_proxy="http://squid-001:3128"
export rsync_proxy="http://squid-001:3128"

```

Have the following Caddyfile on your caddy server :
```
{
    acme_ca https://acme-compliant-server/v1/pki/issuer/Intermediate/acme/directory
}

goodhostname {
    file_server
}
```

# Suppositions for bug-resolutions
Not being a monster in Go myself, I don't really have a quick-fix to propose. I however have a good suspicion that even the upstream Go lib that actually makes the ACME requests ([https://github.com/mholt/acmez](https://github.com/mholt/acmez)) doesn't seem to also use proxies ? I was supposing that Go programs that used net/http automatically used system proxies but I suppose not ?

If this issue is more related to the ACME client project, feel free to close is !

Cheers,

Pablo

**Comment by francislavoie** [comment]
Can you try building from `master`? I think we've resolved that problem already.

**Comment by M0ustach3** [comment]
Hi @francislavoie , thanks for your quick response !

Turns out this was an issue with the OpenRC supervisor itself, not at all with Caddy.

For those like me who smashed their head with a similar issue, remember that you have to change/add the following line in your OpenRC config file /etc/rc.conf :

```
rc_env_allow="HTTP_PROXY HTTPS_PROXY http_proxy https_proxy"
```

That way, the service will inherit the correct environment variables, and Caddy will indeed use them to request ACME certificates.

I apologize for the Issue, this was not at all related to Caddy, closing it.
