### ISSUE TITLE
Feature Request: remote_host request matcher

### ISSUE THREAD

**Issue by dmke** [caddyserver/caddy#6244]
Similar to the `remote_ip` request matcher, I would like to see a `remote_host` matcher.

My use case is to restrict access to a resource, and grant only access to clients from certain IP addresses (e.g. PayPal). Currently, I need to keep track of [this website](https://www.paypal.com/us/cshelp/article/what-are-the-ip-addresses-for-live-paypal-servers-ts1056) and construct a `remote_ip` matcher from their IP ranges:

```Caddyfile
@paypal {
  remote_ip 64.4.240.0/21 64.4.248.0/22 66.211.168.0/22 91.243.72.0/23 173.0.80.0/20 185.177.52.0/22 192.160.215.0/24 198.54.216.0/23
}
```

This could be greatly simplified with a matcher, comparable to the `Require host` directive from Apache's [`mod_authz_host`](https://httpd.apache.org/docs/2.4/mod/mod_authz_host.html#reqhost).

```Caddyfile
@paypal {
  remote_host .paypal.com 
}
```

The lookup algorithm is described in the documentation as follows:

> ### Require host
> 
> The host provider allows access to the server to be controlled based on the host name of
> the remote client. When <code>Require host <var>host-name</var></code> is specified, then
> the request is allowed access if the host name matches.
> 
> A (partial) domain-name
> 
>     Require host example.org
>     Require host .net example.edu
> 
> Hosts whose names match, or end in, this string are allowed access. Only complete
> components are matched, so the above example will match `foo.example.org` but it will
> not match `fooexample.org`. This configuration will cause Apache to perform a double
> reverse DNS lookup on the client IP address, [...]. It will do a reverse DNS lookup
> on the IP address to find the associated hostname, and then do a forward lookup on
> the hostname to assure that it matches the original IP address. Only if the forward
> and reverse DNS are consistent and the hostname matches will access be allowed.

It would be beneficial if the (r)DNS lookups were to be cached (w.r.t. their TTL) within Caddy.

**Comment by dmke** [comment]
Of course there's a plugin for that :)

Thank you for the link, it looks like it *almost* does what I need (wildcard domains (i.e. `.paypal.com` / `*.paypal.com`) are not matched). But I can work with that.

**Comment by francislavoie** [comment]
Yeah - that plugin is what I recommend you use. You could fork it or make a PR against it to add that wildcard feature if you need. But I'm not sure how that would work, how do you do a DNS lookup for a wildcard? Not really a thing.
