### ISSUE TITLE
Caddy is not stopping

### ISSUE THREAD

**Issue by Arctomachine** [caddyserver/caddy#6246]
I am trying to stop background process.
I tried `caddy stop` from folder with caddyfile and `systemctl stop caddy`, but I still can access proxied site normally.
And `systemctl status caddy` shows it failed to start month ago.
Should I terminate process from htop or is there something else I missed?
![image](https://github.com/caddyserver/caddy/assets/29041820/fc896095-85f2-4244-8844-f85592eca26a)
![image](https://github.com/caddyserver/caddy/assets/29041820/0a4a0554-9865-4807-be05-14dd3c57ab22)

**Comment by mholt** [comment]
How did you run Caddy? What does `ps aux | grep caddy` show? What happens after you do `pkill caddy` (as root)?

**Comment by Arctomachine** [comment]
I ran it from caddyfile folder with `caddy start`.
Not tried to kill process. Will I be able to restart it safely after that when needed?
```
root     1176069  0.0  2.1 1269440 21648 ?       Sl   Feb28  10:05 caddy run --pingback 127.0.0.1:40263
root     1184380  0.0  2.8 1269184 28396 ?       Sl   Feb29   9:50 caddy run --pingback 127.0.0.1:36639
root     1889470  0.0  0.0   6744   708 pts/0    S+   17:29   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox caddy
```

**Comment by mholt** [comment]
You've got two caddy instances running :man_shrugging: Try `kill -9 1176069; kill -9 1184380` - that should get them both.

**Comment by Arctomachine** [comment]
Yes, it worked. And now stop works too
