### ISSUE TITLE
Placeholders do not work as upstream address for reverse_proxy

### ISSUE THREAD

**Issue by roger6106** [caddyserver/caddy#6254]
When using a placeholder as an address for reverse_proxy, it appears to prefix the domain name with a `/`.

This can be replicated with this simple caddyfile:

```
http://:1111

vars location https://www.yahoo.com
reverse_proxy {vars.location}
```

The console error shows:
> ERROR   http.log.error  dial tcp: lookup /www.yahoo.com: no such host   {"request": {"remote_ip": "::1", "remote_port": "51245", "client_ip": "::1", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:1111", "uri": "/", "headers": {"User-Agent": ["curl/8.4.0"], "Accept": ["*/*"]}}, "duration": 0.001612083, "status": 502, "err_id": "gndfwzj08", "err_trace": "reverseproxy.statusError (reverseproxy.go:1267)"}

As for why I can't use an alternative approach, the goal is to do some dev work that needs to reverse_proxy paths from various servers. Here's a simplified version of what I am trying to accomplish (using public sites for simplicity):

```
http://:1111

reverse_proxy http://www.yahoo.com {
	header_up Host www.yahoo.com

	@redirect status 3xx
	handle_response @redirect {
		@location vars_regexp location {rp.header.Location} (https?://[a-zA-Z0-9-.]+)(.*)
		reverse_proxy @location {re.location.1}
	}
}
```

Caddy --version is `v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A`

**Comment by francislavoie** [comment]
Upstream address _must not_ contain a scheme when using placeholders, it needs to be only the host & port. See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#upstream-addresses

> If the address is not a URL (i.e. does not have a scheme), then [placeholders](https://caddyserver.com/docs/caddyfile/concepts#placeholders) can be used, but this makes the upstream dynamically static, meaning that potentially many different backends act as a single, static upstream in terms of health checks and load balancing. We recommend using a [dynamic upstreams](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#dynamic-upstreams) module instead, if possible. When using placeholders, a port must be included (either by the placeholder replacement, or as a static suffix to the address).

**Comment by roger6106** [comment]
Thank you! I was sure there had to be a way. It was confusing me that it was trying to look up the domain with a slash in front.
