### ISSUE TITLE
Getting real ip on docker

### ISSUE THREAD

**Issue by cellulosa** [caddyserver/caddy#6257]
hi there, apologies I know this question came up before but I can't seem to get the real ip of clients when using caddy on docker (I'm on MacOS).

I have a fairly common simply setup, with caddy running on Docker as reverse-proxy for all domains running inside other docker containers. Some of these domains are publicly accessible (via Cloudflared), whereas others can only be accessed locally (local DNS rewrites with AdGuard Home pointing to the right machine). Everything is running with a simple `docker compose up` command and various custom `bridge` networks.

I set two "dummy" domains to test the readibility of the ips on both remote and local ips. I assume that if I hit the cloudflared domain, I should see my external ip; whereas if I hit the other, I should see my LAN ip.
However, in the first case I see Docker's cloudflared network ip, whereas in the second I see caddy's (retrieved with `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' caddy`).
(both `remote_ip` and `client_ip` are the same).

Any idea on what I might be doing wrong?

Here is my Dockerfile

```Dockerfile
FROM caddy:builder-alpine AS builder

RUN xcaddy build \
	--with github.com/caddy-dns/cloudflare \
	--with github.com/fvbommel/caddy-dns-ip-range

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

And my Caddyfile:

```Caddyfile
{
	email {$MY_EMAIL}
	servers {
		trusted_proxies dns cloudflared
	}
}

(access_log) {
	log {
		output file /data/log/caddy.log
	}
}

(cloudflare) {
	tls {
		dns cloudflare {$CLOUDFLARE_API_TOKEN}
		resolvers 1.1.1.1
	}
}

cloudflared-ip.{$MY_DOMAIN} {
	templates
	header Content-Type text/plain
	respond "{{.RemoteIP}}"
	encode zstd gzip
	import access_log
	import cloudflare
}

ip.{$MY_DOMAIN} {
	templates
	header Content-Type text/plain
	respond "{{.RemoteIP}}"
	encode zstd gzip
	import access_log
	import cloudflare
}
```

**Comment by francislavoie** [comment]
I've never used Docker on Mac, but it's very likely because the way Docker implements networking involves a TCP-layer proxy, so all connections' IP addresses look like they're coming from the Docker network itself.

**Comment by cellulosa** [comment]
Thank you, I created the [post here](https://caddy.community/t/getting-real-ip-on-docker-for-mac/23549) in case I resolve it and somebody else encounters this issue
