### ISSUE TITLE
Caddyfile support for On-Demand TLS permission modules

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#6260]
> We're missing Caddyfile support for permission modules here. We should try to get that in for 2.8.0. (If anyone's reading this, PRs welcome if you want a little task)

_Originally posted by @francislavoie in https://github.com/caddyserver/caddy/issues/6055#issuecomment-2068832660_

**Comment by mholt** [comment]
Thanks, took care of it!
