### ISSUE TITLE
caddy stream state handling issues

### ISSUE THREAD

**Issue by moyiun09** [caddyserver/caddy#6265]
Upon receiving an incorrect stream state transition sequence frame, Caddy aborts the stream but still forwards the request.

**env info**
caddy 2.7.6 ,ubuntu 20.04
```
client(h2) ---- caddy-proxy(h2/h1) --- server(h1)
```
client: 192.168.153.1
server: 192.168.153.128
caddy-proxy: 192.168.153.129
caddy conf:
```
{"apps":{"http":{"servers":{"srv0":{"listen":[":8013"],"routes":[{"match":[{"path":["/*"]}],"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"192.168.153.128:80"}]}]}],"protocols":["h1","h2c"]}}}}}
```
client sends an abnormal stream sequence to stream 1.
```
HEADERS() --- CONTINUATION() --- CONTINUATION(EH) --- HEADERS(EH) --- DATA(ES)
```
frames info:
```
{
  "<headers-frame-base-2:1>": {
    "headers_block": {
      ":method": "POST",
      ":scheme": "http",
      ":path": "/reqdid=11",
      ":authority": "localhost:8013"
    },
    "flags": [],
    "stream_id": "1"
  },
  "<continuation-frame-base-2:1>": {
    "headers_block": {
      "some-oterh-header": "some-other-value"
    },
    "flags": [],
    "stream_id": "1"
  },
  "<continuation-frame-base-1:1>": {
    "headers_block": {
      "some-header": "some-value"
    },
    "flags": [
      "EH"
    ],
    "stream_id": "1"
  },
  "<headers-frame-pool-1:1>": {
    "headers_block": {
      ":method": "POST",
      ":scheme": "http",
      ":path": "/flag",
      ":authority": "localhost:8013",
      "content-length": "10"
    },
    "flags": [
      "EH"
    ],
    "stream_id": "1"
  },
  "<data-frame-base-1:1>": {
    "data": "5\r\nBBBBB\r\n",
    "flags": [
      "ES"
    ],
    "stream_id": "1"
  }
}
```
For abnormal flow sequences in stream 1, caddy should end with RST.

**Abnormal behavior of caddy:**
caddy ended stream 1 with multiple RST Frames, but forwarded the request consisting of an abnormal sequence.
In this example, the latter complete request was selected and forwarded to the server.
![caddy-steam-trans](https://github.com/caddyserver/caddy/assets/62366932/3eb443c9-05f2-44c4-b191-ac76b52f41cb)

caddy log
```
2024/04/23 12:54:50.266	ERROR	http.log.error	stream error: stream ID 1; PROTOCOL_ERROR	{"request": {"remote_ip": "192.168.153.1", "remote_port": "64252", "client_ip": "192.168.153.1", "proto": "HTTP/2.0", "method": "POST", "host": "localhost:8013", "uri": "/reqdid=11", "headers": {"Some-Oterh-Header": ["some-other-value"], "Some-Header": ["some-value"]}}, "duration": 0.000886409, "status": 502, "err_id": "kmyhxqmbw", "err_trace": "reverseproxy.statusError (reverseproxy.go:1267)"}
```

**Comment by moyiun09** [comment]
Maybe requests are not always forwarded.
![caddy-stream-trans-2](https://github.com/caddyserver/caddy/assets/62366932/d2becbff-6dc3-4f1a-bf8c-6a882ba47c5b)

**Comment by mholt** [comment]
Thanks for the report (nice avatar btw). I'm not sure I fully understand with a quick glance (I'm not super familiar with HTTP/2 internals) but based on your reply, I'm not sure if anything is needed to be done?

HTTP/2 is actually implemented by the Go standard library, not us, so while we implement the proxy, if there is an issue with processing the actual HTTP/2 frames then maybe that should be filed with [Go](https://github.com/golang/go).

**Comment by moyiun09** [comment]
Thanks for the reply, stream processing should be done by the go/http2 standard library. I will do a test on go/http2.

**Comment by mholt** [comment]
Thanks! Let us know if there's a bug in our code though and we'll take a look.
