### ISSUE TITLE
A placeholder cannot be used to disable the admin interface

### ISSUE THREAD

**Issue by jpluscplusm** [caddyserver/caddy#6281]
#### Expectation

I expected to be able to use a placeholder, referencing an environment variable, to disable the admin interface. 

https://caddyserver.com/docs/caddyfile/options#admin says:

> Accepts placeholders

and

> If set to off, then the admin endpoint will be disabled.

#### Reproducer

```
$ cat Caddyfile.test
{
	http_port 8080
	auto_https off
	skip_install_trust
	admin {env.SOME_VAR}
}
:8080 {
	respond 200 "Success"
}
$ caddy validate --config Caddyfile.test
Valid configuration
$ SOME_VAR=off caddy run --config Caddyfile.test  
2024/04/28 23:01:29.023 INFO    using provided configuration    {"config_file": "Caddyfile.test", "config_adapter": ""}
Error: loading initial config: loading new config: starting caddy administration endpoint: listen tcp: lookup off on 1.1.1.1:53: no such host
```

#### Impact

This is a minor security annoyance when deploying to a remote hosting environment on which the interface will never be accessed (except maliciously by an intruder) but needs *not* to be disabled by hardcoding `admin off` in the Caddyfile. e.g. if the Caddyfile needs to be promoted, unchanged, from a testing environment in which the admin interface *is* required.

#### Versions

```
$ caddy version; uname -smv
v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=
Linux #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 21:12:19 +0000 x86_64
```

#### Related

#6280

**Comment by francislavoie** [comment]
You have to use the `{$ENV}` style: https://caddyserver.com/docs/caddyfile/concepts#environment-variables

**Comment by jpluscplusm** [comment]
> You have to use the `{$ENV}` style

I thought that style was only available inside a Caddyfile - how does the JSON-config-producing user control the setting through the environment, in the scenario I outlined?

**Comment by francislavoie** [comment]
Currently, you don't - you're right that's a limitation right now. But you quoted using a Caddyfile so that's my suggestion.

**Comment by jpluscplusm** [comment]
> that's a limitation right now.

Would you like me to open an issue tracking this?

**Comment by francislavoie** [comment]
If you're using JSON, then just set `admin.disabled` to true. https://caddyserver.com/docs/json/admin/
