### ISSUE TITLE
Caddy PKI without Root key

### ISSUE THREAD

**Issue by apollo13** [caddyserver/caddy#6290]
Hi, according to the docs the caddy pki can be configured like this:
```
{
	pki {
		ca local {
			root {
				format pem_file
				cert /path/to/root.pem
				key /path/to/root.key
			}
			intermediate {
				format pem_file
				cert /path/to/intermediate.pem
				key /path/to/intermediate.key
			}
		}
	}
}
```
if I am solely using the intermediate to issue certificates, then there is no reason to supply the root key. Would it be possible to allow configuration of caddy without a root key?

**Comment by mholt** [comment]
If there is no root, how can there be an intermediate? :thinking: I guess I don't fully understand what you're asking.

**Comment by apollo13** [comment]
The root exists but could be a public CA that issues me an intermediate certificate to use or the root exists in a HSM and as such the key is not exportable. So I can supply the cert which is public information but I cannot access the root private key (or simply don't want to give the caddy server access to it). Does that make sense?

**Comment by francislavoie** [comment]
As a workaround, you could set your `intermediate` as the `root` and then set `sign_with_root`.

**Comment by apollo13** [comment]
Hm have to check if that then return the correct chain with acme_server

**Comment by mholt** [comment]
Ok, gotcha, so the root exists, you're talking about just not loading it into the config.

We could probably work on making that possible.

**Comment by apollo13** [comment]
This simple diff makes it work for me.
```diff
diff --git a/modules/caddypki/crypto.go b/modules/caddypki/crypto.go
index 386ce629..24c04686 100644
--- a/modules/caddypki/crypto.go
+++ b/modules/caddypki/crypto.go
@@ -78,18 +78,21 @@ func (kp KeyPair) Load() (*x509.Certificate, crypto.Signer, error) {
                if err != nil {
                        return nil, nil, err
                }
-               keyData, err := os.ReadFile(kp.PrivateKey)
-               if err != nil {
-                       return nil, nil, err
-               }
-
                cert, err := pemDecodeSingleCert(certData)
                if err != nil {
                        return nil, nil, err
                }
-               key, err := certmagic.PEMDecodePrivateKey(keyData)
-               if err != nil {
-                       return nil, nil, err
+
+               var key crypto.Signer = nil
+               if kp.PrivateKey != "" {
+                       keyData, err := os.ReadFile(kp.PrivateKey)
+                       if err != nil {
+                               return nil, nil, err
+                       }
+                       key, err = certmagic.PEMDecodePrivateKey(keyData)
+                       if err != nil {
+                               return nil, nil, err
+                       }
                }
 
                return cert, key, nil
```

Now I was able to configure the acme server like this:
```
{
        http_port 8080
        https_port 8443

        skip_install_trust
	pki {
		ca caddy {
			name caddy
		}
		ca local {
			root {
				format pem_file
				cert /home/florian/sources/caddy/certs/ca.pem
			}
			intermediate {
				format pem_file
				cert /home/florian/sources/caddy/certs/intermediate.crt
				key /home/florian/sources/caddy/certs/intermediate.pem
			}
		}
	}
}

localhost {
	tls {
		issuer internal {
			ca caddy
		}
	}
	acme_server {
		ca local
	}
}
```

**Comment by mholt** [comment]
@apollo13 I think that would be okay. Want to submit a PR for review?

**Comment by apollo13** [comment]
Will do, not sure if I will manage writing the tests. This is the first time I am doing something with caddy at all -- might need some help there then. Out of curiosity, is the ca stuff pluggable? Ie could I write a plugin that would call out to another CA to issue the certs instead of providing caddy with the private keys?

**Comment by mholt** [comment]
Sure, we can help out. (Might just take us some time, heh, quite busy!)

> could I write a plugin that would call out to another CA to issue the certs instead of providing caddy with the private keys?

The `pki` app's job is literally to generate signing keys and issue certs. If your sites need certs from another CA, you can configure cert issuers: https://caddyserver.com/docs/caddyfile/options#cert-issuer

**Comment by apollo13** [comment]
> Sure, we can help out. (Might just take us some time, heh, quite busy!)

No worries.

> If your sites need certs from another CA, you can configure cert issuers: https://caddyserver.com/docs/caddyfile/options#cert-issuer

But those cannot be used from `acme_server`. Think of it like having your CA on a yubikey and then issuing certs via `acme_server` for the other caddy instances.
