### ISSUE TITLE
Certificate renewal checks only using ipv6 dns even if it times out.

### ISSUE THREAD

**Issue by balki** [caddyserver/caddy#6299]
When caddy is renewing certificates using dns challenge, it only uses ipv6 to check for DNS propagation. In my system, ipv6 is broken and cannot make any ipv6 requests.

```
dial tcp [2606:4700:4700::1111]:53: i/o timeout
```

Is it possible to have it fallback to next available dns server if one times out?

```
May 03 17:42:28 hostname caddy[393685]: {"level":"error","ts":1714772548.8694875,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"*.w.MYDOMAIN.COM","issuer":"acme.zerossl.com-v2-DV90","error":"[*.w.MYDOMAIN.COM] solving challenges: waiting for solver certmagic.solverWrapper to be ready: checking DNS propagation of \"_acme-challenge.w.MYDOMAIN.COM\": dial tcp [2606:4700:4700::1111]:53: i/o timeout (order=https://acme.zerossl.com/v2/DV90/order/TqCz5-8KlZPVkBrOYNv51g) (ca=https://acme.zerossl.com/v2/DV90)"}
```

**Comment by francislavoie** [comment]
Why is your system configured with an IPv6 DNS resolver then? Go's stdlib takes the list of resolves from your system's `resolv.conf`, pretty sure.

**Comment by balki** [comment]
It is coming from the network. Not explicitly configured. I am still trying to figure out how to remove that or get ipv6 working. For now If I disable ipv6 in the router, it works fine.

However caddy should also try all revolvers available and not keep re-trying the broken one. All other apps resolve fine and also caddy resolves correctly in some cases. E.g. it resolved fine when it tried to create the ACME TXT record but broken when trying to check if is propagated.

**Comment by francislavoie** [comment]
I think we might've already fixed that. Can you try with v2.8.0-beta.1?

**Comment by balki** [comment]
> I think we might've already fixed that. Can you try with v2.8.0-beta.1?

Tried with beta. Certificate renewal works fine now. Thanks!

**Comment by mholt** [comment]
Hurray! Thanks 👍

**Comment by francislavoie** [comment]
Thanks!

For ref, it was fixed in https://github.com/caddyserver/certmagic/pull/274, part of that being we `return true` after the first successful propagation check, instead of trying them all and failing if one fails.
