### ISSUE TITLE
Feature request: "Set-Cookie" manipulation in the response

### ISSUE THREAD

**Issue by teodorescuserban** [caddyserver/caddy#6319]
There are three things that ideally could be added:
- ability to change the domain of a specific or all `Set-Cookie`s (like [here](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_domain))
- ability to change the path of a specific or all `Set-Cookie`s (like [here](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_path))
- ability to chenge the flags of a specific or all `Set-Cookie`s (`Same-Site`, `HttpOnly`, `Secure`) (like [here](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cookie_flags))

I am not sure if this would be a separate module or part of the `reverse-proxy` standard module.
I attempted to make a module based on a trimmed-down `reverse-proxy` module but it looks like I need to level up a bit more before doing this successfully.

Thank you.

Opinions, @francislavoie @mholt ?

**Comment by francislavoie** [comment]
Can't you just use `header_down` to perform replacements?

**Comment by steffenbusch** [comment]
FYI: I recently accomplished the setting of flags (temporarily, until the upstream app was fixed) using [header_down](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#header_down) in `reverse_proxy`

```caddy
header_down Set-Cookie (.*) "$1; Secure"
```

**Comment by teodorescuserban** [comment]
Yes, I am using what @steffenbusch mentioned.
The issue is that if one or more cookies already have the `Secure` flag, I'll get the cookie to be double secured 😁 
Same goes for `HttpOnly`, while for `SameSite` it gets messy if the cookie already has `SameSite=Strict` and I want to change it to `SameSite=Lax`.
The path and domain are not important to me tbh, but I thought we might add them as well if we're doing it.

**Comment by mholt** [comment]
It sounds like you're looking for a middleware plugin that can manipulate that header in a Cookie-syntax-aware way, rather than treating it as an opaque string like most headers.

I agree this would make a good external plugin for now.

**Comment by teodorescuserban** [comment]
Well, in the end I have a working solution for all cases. It is a bit clunky, as I was not able to make the middle group optional to fix every flag in a single line but it works, so...
Happy to find out if there is any way to turn these into less lines instead of 6 without being too arcane.

```
8888: {
    reverse_proxy localhost:8889 {
        header_down -Server
        # remove the Secure flag from the cookie
        header_down Set-Cookie (.*)(?:\;\sSecure)(.*) "$1$2"
        # just to add it at the end
        header_down Set-Cookie (.*) "$1; Secure"

        # remove the HttpOnly flag from the cookie
        header_down Set-Cookie (.*)(?:\;\sHttpOnly)(.*) "$1$2"
        # just to add it at the end
        header_down Set-Cookie (.*) "$1; HttpOnly"

        # remove the SameSite flag from the cookie
        header_down Set-Cookie (.*)(?:\;\sSameSite=[A-Za-z]+)(.*) "$1$2"
        # just to set it at the end
        header_down Set-Cookie (.*) "$1; SameSite=Strict"
    }
}

**Comment by teodorescuserban** [comment]
Thank you for input, @mholt, what would be the best `order` to manipulate the response header, would `after reverse_proxy` or `before headers`.

The plugin should probably use `headers.CaddyfileHeaderOp` and draw inspiration from the `reverse_proxy`, `header_down` part, correct?

**Comment by francislavoie** [comment]
`after reverse_proxy` would never run because `reverse_proxy` is terminal. So it needs to be before it, but manipulate the response headers when going back up the chain (i.e. after next is called). Take a look at the source code for the `header` handler, specifically the "defer" mode.

**Comment by francislavoie** [comment]
I'll close this for now because I think a plugin is the best place for this for now. We can re-evaluate later if we find that there's enough demand for it to be included in Caddy itself.

**Comment by teodorescuserban** [comment]
> I'll close this for now because I think a plugin is the best place for this for now. We can re-evaluate later if we find that there's enough demand for it to be included in Caddy itself.

Is there a better place to pop in ideas like that? Maybe directly on caddy community? 

Thank you.
