### ISSUE TITLE
pflag error when compiling  -> bad result slice 

### ISSUE THREAD

**Issue by chemstar** [caddyserver/caddy#6323]
running
  xcaddy build --with github.com/caddy-dns/ionos

with
  go version go1.22.3 linux/amd64
  xcaddy version
  v0.3.2 h1:Y1QPKq97GrSG6ryMhGTw1g9GHH8wRmwnCzOcN+f+gCY=

results in
  go: github.com/caddy-dns/ionos@v1.0.1 requires
        github.com/caddyserver/caddy/v2@v2.6.4 requires
        github.com/spf13/pflag@v1.0.5: verifying go.mod: github.com/spf13/pflag@v1.0.5/go.mod: TileReader returned bad    result slice (tile/8/1/003 len=4096, want 8192)

any advice how to do a successfull build? thx

**Comment by steffenbusch** [comment]
Try with the most recent `xcaddy` version `v0.4.1 h1:OFN+aS9Yo1AO4x5bAHKlH5LkoxvAlZDLAk7OFGcWafk=`.
I just tried it on my VM using `go version go1.22.2 linux/arm64` and `xcaddy build --with github.com/caddy-dns/ionos` was successful.

**Comment by chemstar** [comment]
i've updated xcaddy and exec. go clean -modcache
all fine now. thank you
