### ISSUE TITLE
all:  Support the riscv64 platform

### ISSUE THREAD

**Issue by mengzhuo** [caddyserver/caddy#6331]
As riscv are growing popularity, we can now run Caddy on riscv64
```bash
go version go1.22.2 linux/amd64

cd cmd/caddy && GOARCH=riscv64 GOOS=linux go build 
./caddy version
224316eaecd6bffd38719e1e03e09f8fe51649e7 (20 May 24 19:14 UTC)
```

**Comment by mholt** [comment]
I don't know if there's anything special we need to do if it already builds for riscv64. Is there anything actionable here?

**Comment by mohammed90** [comment]
I checked, and we already build for riscv64 in our goreleaser and include it in GitHub releases. What are you missing?

**Comment by mengzhuo** [comment]
My bad, I didn't checked release page.
Thanks for support riscv user!
