### ISSUE TITLE
 Issue with Caddy Server Configuration for Domain

### ISSUE THREAD

**Issue by akshilshah** [caddyserver/caddy#6335]
Hello,

I'm experiencing an issue with my Caddy server configuration. Below is my current configuration:

```
hi.ioinfotech.com {
	root * /home/ubuntu/hosting/hi
	encode gzip
	file_server
}

```

![Screenshot 2024-05-22 at 10 49 52 PM](https://github.com/caddyserver/caddy/assets/13059766/bace0b0a-3241-473f-ad96-8268f877a500)

When I use this configuration, I encounter the following error:
Navigation to [Link](https://hi.ioinfotech.com/ ) shows blank page

Environment:
 - OS: Ubuntu
 - Caddy Version: v2.7.6 h1:w0NymbG2m9PcvKWsrXO6EEkY9Ru4FJK8uQbYcev1p3A=

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
