### ISSUE TITLE
Build amd64 and arm are broken

### ISSUE THREAD

**Issue by stnert** [caddyserver/caddy#6353]
After an update of a patch, I noticed that it broke the build of both. 

Just notifying for correction. 

Where was it affected? 

renovate/docker.io-caddy-2.x

![image](https://github.com/caddyserver/caddy/assets/48295298/1688d253-2f09-49f6-a53c-fed0fb2c10a1)

**Comment by francislavoie** [comment]
There's nothing broken, it's just in the queue to be built. https://doi-janky.infosiftr.net/view/all/builds It can take some time. It's out of our control.

**Comment by hypervtechnics** [comment]
@francislavoie is a delay this huge really expected? It has been three days now and there are already two new versions. I'd at least expect a note in the release notes saying something like "dear docker users, the docker image build is queued and the image will be available within the next x hours".

Especially for security fixes this might cause serious problems. Even the people who use e.g. the `-builder` tag to build caddy themselves are impacted then.

**Comment by mohammed90** [comment]
> dear docker users, the docker image build is queued and the image will be available within the next x hours\".

The thing is we don't have insight on Docker infrastructure that is not already public information, e.g. the link Francis shared. We did our dues by pushing the tag and image updates to Docker library repository.

> Especially for security fixes this might cause serious problems. Even the people who use e.g. the -builder tag to build caddy themselves are impacted then


I don't see how users of `-builder` are held back by anything. They can do `build v2.8.4` with the older image, and it'll produce the correct latest version.

If bleeding-edge, on-the-spot is a requirement, look into Chainguard images.

**Comment by mholt** [comment]
You'd have to take the speed of the process up with Docker. I'm sure on weekends their staff are probably taking time off as well.
