### ISSUE TITLE
Weighted Round-Robin strategy doesn't support zero values

### ISSUE THREAD

**Issue by sizovs** [caddyserver/caddy#6357]
Hi Caddy Team

Thanks for the great work. While trying to implement zero-downtime blue-green deployment, I stumbled upon a [forum thread](https://caddy.community/t/can-i-drain-sessions-from-an-upstream-server/20658/3) suggesting using weighted round-robin strategy with zero "weight" values to skip a server for new connections while allowing it to complete existing ones.

However, Caddy doesn't support zero values and fails with `"invalid weight value '0': weight should be non-zero and positive."` So the solution doesn't work, and the information is misleading. `¯\_(ツ)_/¯`

Question: Can we make Caddy support 0 values?

**Comment by sizovs** [comment]
I am closing this since simply removing the server from config followed by reload does the job.

**Comment by mholt** [comment]
Yeah, a weight of 0 means it would never be used... I figured just removing it would be more obvious.
