### ISSUE TITLE
regression in 2.8 file_server serving root index file

### ISSUE THREAD

**Issue by willnorris** [caddyserver/caddy#6358]
caddy 2.8 seems to be failing to serve a root `/index.html` page as I would expect.

# Reproduction case

Create index.html file: `echo Hello > index.html`

Create Caddyfile:
```
{
  debug
}

:8080 {
  file_server
  try_files {path} {path}/ =404
}
```

On caddy 2.7, http://localhost:8080/ will load the index.html page and serve "Hello".  On caddy 2.8, it returns an empty 404 error.  If there is a sub directory like http://localhost:8080/sub/ then the index page loads fine.  It is only for the root URL.

**Comment by mohammed90** [comment]
Do you think it's the same as #6352?

**Comment by willnorris** [comment]
ah, yes.  This definitely seems to be the same.  The same commit identified there, 6d97d8d87beb788d19a4084d07ec9157e5705b13, seems to be where the issue lies.  I'll close this as a dup of #6352 and see if I can help debug the issue over there.

**Comment by mholt** [comment]
Thanks so much for debugging this before I even had a chance to sit down to look at it! :smile:
