### ISSUE TITLE
Missing image for 2.8.4 on docker.io

### ISSUE THREAD

**Issue by rgaudin** [caddyserver/caddy#6366]
Releases [2.8.2](https://github.com/caddyserver/caddy/releases/tag/v2.8.2) and [2.8.4](https://github.com/caddyserver/caddy/releases/tag/v2.8.4) **are not available** on [Docker Hub](https://hub.docker.com/_/caddy/tags?page=&page_size=&ordering=&name=2.8.) although the _Release Published_ workflow [did run](https://github.com/caddyserver/caddy/actions/runs/9338218694) and mentions tag `2.8.4`…

**Comment by mohammed90** [comment]
Those are different. Images under `/_/caddy` are under the "official images" designation of Docker Hub, which require PRs made to the subject repository of Docker: https://github.com/docker-library/official-images/pull/16895. The "Release Published" workflow was used for triggering part of the flow, but that doesn't mean it's immediately reflected on the Docker Hub page.
