### ISSUE TITLE
How to build a custom image with PHP-FPM 7.2/7.3/7.4

### ISSUE THREAD

**Issue by msaustral** [caddyserver/caddy#6416]
Hi

How can we build a custom image with PHP-FPM 7.2/7.3/7.4 and caddy

**Comment by francislavoie** [comment]
You don't - you run them side by side in separate containers. I assume you're talking about Docker; Docker is designed to run a single process per container.

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
