### ISSUE TITLE
Documentation claims `basicauth` was renamed to `basic_auth` but this doesn’t work for me on 2.8.4

### ISSUE THREAD

**Issue by dpk** [caddyserver/caddy#6418]
[Docs:](https://caddyserver.com/docs/caddyfile/directives/basic_auth)

> Prior to v2.8.0, this directive was named `basicauth`, but was renamed for consistency with other directives.

```
[nix-shell:/var/service/caddy]$ caddy --version
2.8.4
```

Trying to use the name `basic_auth` gave me:

```
Error: adapting config using caddyfile: /var/nix-shell/caddy/Caddyfile:32: unrecognized directive: basic_auth
```

but `basicauth` worked.

**Comment by francislavoie** [comment]
What do you have if you run `caddy build-info`? I think that version number might be a lie somehow. You might need to reach out to the nix people about how they're packaging Caddy.

**Comment by mholt** [comment]
Yeah, that's not a genuine `caddy version` string. So it must have been modified, and it probably isn't actually that version. There should be a module checksum next to it.

**Comment by w-ap-admin** [comment]
I got exaclty the same issue with caddy 2.7.6:
With `basic_auth`:
```
/etc/caddy # caddy reload
2024/12/05 13:54:51.707 INFO    using adjacent Caddyfile
Error: adapting config using caddyfile: Caddyfile:73: unrecognized directive: basic_auth

```

With `basicauth`:
```
/etc/caddy # caddy reload
2024/12/05 13:59:56.686 INFO    using adjacent Caddyfile

```

**Comment by francislavoie** [comment]
@w-ap-admin that was done in 2.8.0+. Please upgrade to the latest, v2.8.4.
