### ISSUE TITLE
[file_server browse] missing favicon

### ISSUE THREAD

**Issue by trmdi** [caddyserver/caddy#6421]
For example, if you use duckdns and have visited www.duckdns.org, after that when you go to [file.example.duckdns.org](file.example.duckdns.org) the duck icon is shown like this:
![image](https://github.com/caddyserver/caddy/assets/11857205/22c3f75e-b439-4580-a0db-edb543da1f47)

I think we need to add the favicon tag.

**Comment by mohammed90** [comment]
We can't assume the favicon icon for the users, and embedding the Caddy icon is excessive. Unlike js/css libs, pointing at Caddy's favicon on our website would also be excessive and violates privacy of the users. You can set it yourself in 2 ways:

- place a favicon file at the root with the names `favicon.png` and `favicon.ico`

- customize the template by first exporting it with the command `caddy file-server export-template > template.html`, adjust it as you like, then use it in the `template` subdirective inside `browse`.

**Comment by mholt** [comment]
We could embed the Caddy icon (I'm not personally opposed to that), but I'm not sure people would want our icon shown on their site. It might confuse users when their tab shows a different icon than what belongs to the site they're visiting.

The more I think about it the more I think the favicon is working as expected.
