### ISSUE TITLE
"Encode" defaults compress already compressed font formats

### ISSUE THREAD

**Issue by jsheard** [caddyserver/caddy#6428]
The default matcher for `encode` currently includes `font/*`, matching every font format. However, the modern WOFF and WOFF2 web font formats are already internally compressed with zlib and brotli respectively, so compressing them again is likely a waste of CPU cycles. Would it make sense to refine the defaults down to only compress the "legacy" non-WOFF formats?

https://www.iana.org/assignments/media-types/media-types.xhtml#font

**Comment by mholt** [comment]
Hmm, we used to do that: https://github.com/caddyserver/caddy/commit/d3f23a8eeb3b0b7198ae4c06879227b467fcfaa6

@dunglas what do you think?

**Comment by dunglas** [comment]
I agree. We should exclude these ones.

**Comment by jsheard** [comment]
I believe the formats supported by browsers pre-WOFF were TTF, OTF, EOT and SVG, with these MIME types:

`
font/ttf
font/otf
application/vnd.ms-fontobject (EOT)
image/svg+xml (SVG fonts don't appear to have a more specific MIME type)
`

Caddy already has specific matchers for EOT and SVG so I think it would only need TTF and OTF to be added, unless I missed something.

**Comment by dunglas** [comment]
I opened https://github.com/caddyserver/caddy/pull/6432 to fix the issue. Would you mind double-checking the patch @jsheard?
