### ISSUE TITLE
Auth User ID not resolved when forwarding as a custom header

### ISSUE THREAD

**Issue by BrianLesko** [caddyserver/caddy#6434]
1. The {http.auth.user.id} placeholder does not resolve when using the header directive. Putting the placeholder in quotes does not change either. The header does resolve when using the respond directive.

2.  I want to pass the username after basic auth to my backend JS so that I know who the user is. (I need the user's email, which will be their basic auth user ID. 

3. I checked the default headers sent and there are no auth credentials passed since an update in 2017.

4. Here is my configuration:

:80
root * /home/lesko/website
file_server
header Access-Control-Expose-Headers "X-User-ID"

handle_path /submit* {
  basic_auth {
    user pass
  }
  header X-User-ID {http.auth.user.id}
  root * /home/lesko/website
  file_server {
    index request.html
  }
}

**Comment by mholt** [comment]
> The {http.auth.user.id} placeholder does not resolve when using the header directive. Putting the placeholder in quotes does not change either. The header does resolve when using the respond directive.

It does resolve, but the order the directives are evaluated matters: https://caddyserver.com/docs/caddyfile/directives#directive-order

See this article for more information: https://caddy.community/t/composing-in-the-caddyfile/8291

Basically, you can use `route` to force a custom order of handlers.
