### ISSUE TITLE
phpfastcgi should set SCRIPT_NAME to script + path

### ISSUE THREAD

**Issue by cdaguerre** [caddyserver/caddy#6437]
For PHP-FPM access logs to mean something (and not only show GET 200 /index.php), the FCGI parameter [`SCRIPT_NAME`](https://github.com/caddyserver/caddy/blob/f350e001b6319dd8833fbdb31ffb0ccadb2aa2e0/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L317) should include the request path.  

I'd be glad to open a PR, but I'm not sure that is compliant with the FCGI specification and that you'd be willing to merge it.

For anyone looking for a workaround, the following config does the trick:

```
php_fastcgi 127.0.0.1:9000 {
	env SCRIPT_NAME /index.php{http.request.orig_uri}
}
```

Also refer: https://github.com/php/php-src/issues/10116#issuecomment-2209045586

**Comment by francislavoie** [comment]
The CGI spec does not agree: 

> No `PATH_INFO` segment (see section 4.1.5) is included in the `SCRIPT_NAME` value.

https://tools.ietf.org/html/rfc3875#section-4.1.13
