### ISSUE TITLE
can't disable IPv4/IPv6 for dynamic reverse proxy from Caddyfile

### ISSUE THREAD

**Issue by hmoffatt** [caddyserver/caddy#6442]
As per the forum discussion at https://caddy.community/t/reverse-proxy-to-dynamic-ipv4-only/24773/3 , I found it's not possible to disable IPv4 or IPv6 in a `reverse_proxy` `dynamic a` block from the Caddyfile.

If I use
```
:9000 {
	reverse_proxy {
		dynamic a potoroo 8123 {
			versions ipv4
		}
	}
}
```

then I get a caddy.json which has `"versions":{"ipv4":true}}`, but Caddy still uses IPv6 if available. 

If I explicitly add `"ipv6":"false"` then it works, but this can't be set from the Caddyfile (that I'm aware of).

**Comment by mholt** [comment]
Good find, thanks. Anyone is welcome to work on this! :)

**Comment by armadi1809** [comment]
Is the expected logic here that when `ipv4` is specified in `versions` , we should automatically set `ipv6` to false or are we adding the ability for the users to set `ipv6`  (or `ipv4` for instance) to false via the caddy file?

**Comment by francislavoie** [comment]
Yeah if only one is on then it should assume the other is off.
