### ISSUE TITLE
Issues signing up at caddy.community?

### ISSUE THREAD

**Issue by nickali** [caddyserver/caddy#6445]
I know this isn't a bug with Caddy, but I'm not sure where else to post this.

I'm trying to sign up at https://caddy.community and I keep getting a "Something went wrong, perhaps this email is already registered, try the forgot password link" error. 

This is happening with the latest Safari and Chrome on macOS Sonoma 14.5 with no ad blockers.

Errors I see in the console:

Failed to load resource: the server responded with a status of 429 (): https://caddy.community/message-bus/d60d079304d848e0ab655c03908988dc/poll. Response:

```
[{"global_id":-1,"message_id":-1,"channel":"/__status","data":{"/latest":77770,"/delete":1,"/recover":0,"/destroy":0,"/site/banner":0,"/file-change":1,"/site/read-only":0,"/redirect_to_wizard":0,"/refresh_client":0,"/global/asset-version":2}}]
|
[]
|
```

<br>
POST https://caddy.community/u 500 (Internal Server Error) ajax.js:150. Response:

```
<!DOCTYPE html>
<html>
<head>
  <title>Oops - Error 500</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
    <h1>Oops</h1>
    <p>The software powering this discussion forum encountered an unexpected problem. We apologize for the inconvenience.</p>
    <p>Detailed information about the error was logged, and an automatic notification generated. We'll take a look at it.</p>
    <p>No further action is necessary. However, if the error condition persists, you can provide additional detail, including steps to reproduce the error, by posting a discussion topic in the site's feedback category.</p>
</body>
</html>
```
<br>
POST https://caddy.community/message-bus/d60d079…/poll 429 (Too Many Requests) message-bus.js:31 

Response:
```
Youâ€™ve performed this action too many times. Please wait 1 minute before trying again.
```

I happy to post it somewhere else if more appropriate.

**Comment by solracsf** [comment]
Server seems down.

![image](https://github.com/caddyserver/caddy/assets/12234510/7e83ca0d-60b2-4d78-93c7-2877570ced18)

**Comment by francislavoie** [comment]
I'm running the upgrade right now to see if it fixes registration. Hold on.

**Comment by francislavoie** [comment]
Upgrade is done. If you want to try to signup again.

**Comment by nickali** [comment]
Yup, working again! Thanks.
