### ISSUE TITLE
Feature Request: Add dynamic reference to host machines private IP address.

### ISSUE THREAD

**Issue by MrChadMWood** [caddyserver/caddy#6457]
It would be nice if a Caddyfile could get the private IP of the machine its hosted on. Then users could reference themselves in a private network without knowing the private IP ahead of time.

Something like this:
```
[server-ip] {
    import tls_config
    reverse_proxy /gitea/* 10.0.0.2:80 {
        without /gitea
    }
}
```

Where `[server-ip]` gets updated to be the current machines private IP (e.g., 10.0.0.1).

**Comment by mohammed90** [comment]
Sounds like you need a DNS server in your LAN that is pushed to users via DHCP. Then you can just use a domain name that resolves to the private IP address.

**Comment by francislavoie** [comment]
I'm not sure I understand why you need this. Can't you just do `http://` as your site address to accept connections from anywhere? What are you trying to do exactly? Please elaborate.

Also, `without` isn't a thing, I don't know where you got that (did you use LLMs? Don't, they halucinate Caddy config so much).

**Comment by mholt** [comment]
> It would be nice if a Caddyfile could get the private IP of the machine its hosted on.

On which interface? 127.*? 10.*? 192.168.*? There's no safe way to know this magically for sure, AFAIK.

I echo the above comments; and I'm still not 100% sure what the goal is or the utility, as I am not sure what this means:

> users could reference themselves in a private network without knowing the private IP ahead of time.

Closing for now, but feel free to continue the discussion if needed.

**Comment by MrChadMWood** [comment]
The scenario that I had in mind is, I'd place a Caddy reverse proxy in a private network, using it to centeralize traffic for different services on the network. If a service needs (for example) Gitlab, Prefect, or Customapp1, it reaches out to Caddy at `10.0.0.1/gitlab`, `10.0.0.1/prefect`, or `10.0.0.1/customapp1` respectively. Here, Caddy would be at `10.0.0.1`.

I considered this feature as a way to avoid needing to configure the Caddy file with the machines own private IP address. The private IP may change, and this would require re configuring the Caddy file.


> Sounds like you need a DNS server in your LAN that is pushed to users via DHCP.

I'll look into this, thanks for the feedback!

> On which interface? 127.? 10.? 192.168.*? There's no safe way to know this magically for sure, AFAIK.

I had not thought of this either, thank you.

**Comment by mholt** [comment]
You can already use the bind directive to specify the interface, and then use a are block with no hostname (just a port) to work for any hostname or ip on that interface.
