### ISSUE TITLE
Q: Caddy routing strategy ?

### ISSUE THREAD

**Issue by Softbox44** [caddyserver/caddy#6458]
Hi. I am planning to install a Caddy container and use it as a reverse Proxy pointing to around 10 other servers on the same (docker) host as Caddy. Is this going to cause chaos in the network traffic in and out of docker? Is it better to create a Docker Network for Caddy, add all the containers and ask Caddy to route within Docker?

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!

**Comment by Softbox44** [comment]
Appreciate your prompt reply and your helpful explanation.  And I will
follow your guidelines for questions. Thanks !
