### ISSUE TITLE
Caddy requires a full reboot to load new changes

### ISSUE THREAD

**Issue by miltuss** [caddyserver/caddy#6472]
Hello, I have to restart Caddy each time there is a change in the Caddyfile so that it can load the new instructions, but this temporarily interrupts all the services managed by Caddy, so it is not at all an adequate solution!

 How do I apply the new instructions without completely restarting Caddy each time?

**Comment by francislavoie** [comment]
Use `reload`, not `restart`. See https://caddyserver.com/docs/command-line#caddy-reload and https://caddyserver.com/docs/running#using-the-service
