### ISSUE TITLE
Defer not activated when using the `?` prefix for default header value inside a header block

### ISSUE THREAD

**Issue by borjapazr** [caddyserver/caddy#6473]
Hello 👋

I've been conducting some testing with the header directive and observed some discrepancies with the behavior of the `?` prefix when setting default values for headers. According to the documentation, using the `?` prefix inside a header block should enable the defer mechanism.

Example:
```plaintext
...
(security) {
	header {
		### Replace Server header
		Server "Example Server"

		...

		### Clickjacking protection
		?X-Frame-Options "SAMEORIGIN"
	}
}
...
```

In this example, by setting a default value for the `X-Frame-Options` header, the defer should be activated and, therefore, the `Server` header should overwrite all other set values since operations on the headers are deferred until the time when the response is written to the client. But that's not really the case. The above example causes two `Server` headers to be sent to the client, one with the value `Example Server` and one with the value set by the upstream service.

Instead, this works if I use `-` or `>` in any other header, for example:

```plaintext
...
(security) {
	header {
		### Replace Server header
		Server "Example Server"

		...

		### Clickjacking protection
		-X-Frame-Options "SAMEORIGIN"
	}
}
...
```

This results in the `Server` header value being set to `Example Server` overwriting the one that might be set by the upstream service.

Is there a bug with this or is the documentation not correct?

> [!NOTE]  
> This issue is detailed in the following post on the `Caddy Community`: https://caddy.community/t/repeated-server-header/24830/9

Thanks in advance 🙏

**Comment by francislavoie** [comment]
As per my reply to the community thread, I don't think there's a problem here, `require` and `deferred` effectively have the same effect, they both defer the operation to run on the way out. If `?` is used, `require` is set which has the same effect as `deferred`. In code:

```go
	if h.Response != nil {
		if h.Response.Deferred || h.Response.Require != nil {
			w = &responseWriterWrapper{
				ResponseWriterWrapper: &caddyhttp.ResponseWriterWrapper{ResponseWriter: w},
				replacer:              repl,
				require:               h.Response.Require,
				headerOps:             h.Response.HeaderOps,
			}
		} else {
			h.Response.ApplyTo(w.Header(), repl)
		}
	}
```
