### ISSUE TITLE
What is the Caddy equivalent of Nginx upstream directive?

### ISSUE THREAD

**Issue by reorx** [caddyserver/caddy#6474]
In Nginx, we write:
```
upstream backend {
    server backend1.example.com;
    server backend2.example.com;
    server backend3.example.com;
}

location = /vis {
    auth_request http://authserver:2077/api/auth/check_user;
    proxy_pass http://backend/vis/index.html;
}
location /vis {
    proxy_pass http://backend;
}
```

The advantage of defining an upstream group is to avoid repeating the server definitions when the upstream is used multiple times.

Here's the Caddyfile where I encountered this problem: 

```
:3080 {
    handle_path /vis {
        rewrite * /vis/index.html
        forward_auth http://authserver:2077 {
            uri /api/auth/check_user?redirect=1
        }
        reverse_proxy http://172.22.164.127:18000 http://172.22.164.130:18000 {
            header_up Host {upstream_hostport}
        }
    }
    reverse_proxy /vis/* http://172.22.164.127:18000 http://172.22.164.130:18000 {
        header_up Host {upstream_hostport}
    }
}
```

You can see that the upstream group `http://172.22.164.127:18000 http://172.22.164.130:18000` is written twice because `/vis` needs forward authentication and rewriting, while `/vis/*` does not. Therefore, I have to write two blocks to separate the logic.

This is merely an example to illustrate a potential situation where multiple upstreams may need to be used as a group multiple times. As a newcomer to Caddy, there may be other solutions that allow the reverse_proxy to be written only once. However, I believe there must be cases where the same upstream needs to be referenced multiple times. Even if there is only one upstream server, giving it a name to refer to is better for readability and maintainability.

**Comment by mholt** [comment]
Snippets can be used to repeat segments in the Caddyfile, maybe something like this:

```
(my-upstreams) {
   to backend1
   to backend2
}

...

reverse_proxy {
    import (my-upstreams)
}
```

**Comment by reorx** [comment]
That looks pretty good! The Snippets feature seems to be a more advanced and universal solution for code reuse and can definitely be considered the equivalent of the Nginx upstream directive.

Aside from this, are there any other improvements I can make to my Caddyfile?

**Comment by francislavoie** [comment]
You can probably just do this:

```
:3080 {
    handle /vis {
        rewrite * /vis/index.html
        forward_auth http://authserver:2077 {
            uri /api/auth/check_user?redirect=1
        }
    }
    reverse_proxy 172.22.164.127:18000 172.22.164.130:18000
}
```

**Comment by reorx** [comment]
@francislavoie sure, thanks for answering! Didn't know the cummunity forum before, I suggest you can facilitate [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) to guide new users like me to ask usage questions in the forum when creating issues.

**Comment by mholt** [comment]
We use canned responses instead of issue templates. One of them does point users to the forum, and sometimes we'll tell them later. It's better if we triage issues instead of leaving users to choose for themselves what is to be done. For example I wasn't sure at first if this issue was a feature request or a question to answer.
