### ISSUE TITLE
Global option for default lifetime of internally issued certificates

### ISSUE THREAD

**Issue by oprypkhantc** [caddyserver/caddy#6475]
Hey.

Currently, the lifetime of certificates issued with `internal` issuer defaults to hardcoded [12 hours of time](https://github.com/caddyserver/caddy/blob/3579815a6c099bfbcff0143f7a251a92b4fa4198/modules/caddytls/internalissuer.go#L196), but can be optionally configured in Caddyfile on [per-domain basis](https://caddyserver.com/docs/caddyfile/directives/tls#internal).

Normally, I don't touch any of Caddy's default settings as there's normally no need to do so. However, in this case, there's this issue: https://github.com/caddyserver/caddy/issues/5617. Every 12 hours that the certificates expire, the first time you open a domain, a Chromium browser will spit out a certificate expired error and you'll need to refresh the page. It gets annoying quick, and since Chromium doesn't want to fix this on their side, the most we can do is to increase the lifetime of certificates.

The problem is that right now the only option is to add this configuration to each domain separately. With multiple configs scattered through multiple repositories and 20+ domain names, it gets messy pretty quick. Which is why I'd love to have an option to configure the lifetime in the global part of the config, rather than per domain.

I understand that adding options for every use case is not a good idea; however, this seems to be a long standing issue that affects most end users of the Caddy's `internal` certificate issuer. And since it's been noted that Caddy would not want to change the default 12h to something larger, it'd seem like a global configuration option would be a good middle ground.

Of course, I'm willing to implement this myself if need to. Thank you.

**Comment by mholt** [comment]
I really am not convinced of the need to increase the leaf cert lifetimes because of a bug in a client, though. Like I have no desire to implement this. Global options incur a high complexity cost, unfortunately, because it needs to reconcile individual site configs too.

I'd suggest hounding Chrome(ium?) until they fix it.

**Comment by francislavoie** [comment]
Reminder that you can just use snippets to deduplicate config across sites: https://caddyserver.com/docs/caddyfile/concepts#snippets

**Comment by oprypkhantc** [comment]
@mholt I understand. I don't think Chrome will help here though; if you were unable to convince them it's worth fixing, neither will I :/

@francislavoie I'm aware and it's awesome that Caddy has snippets, but it still feels like a hack.

By the way, why the default lifetime is set to 12h and not something larger? I'm asking to understand why the documentation recommends against changing the lifetime :)

Thank you.

**Comment by oprypkhantc** [comment]
This affected a lot of developers, so I followed @francislavoie advice and we increases the lifetime of leaf certificates to 365d. I understand this is none of Caddy's concerns though, so I'll close the issue.

For anyone else reading, this is the config we used (and you also have to import the snippet in each of the addresses:

```
{
	local_certs
	pki {
		ca local {
			intermediate_lifetime 730d
		}
	}
}

(longer-certs) {
	tls {
		issuer internal {
			lifetime 365d
		}
	}
}
```
