### ISSUE TITLE
Accommodate `Policy` Changes in `github.com/pires/go-proxyproto`

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#6484]
The `go-proxyproto` module has [deprecated the `Policy`/`PolicyFunc`](https://github.com/pires/go-proxyproto/commit/b718e7ce4964b060fd3ccc090b58cb74e1857c32) in favor of the [`ConnPolicy` approach](https://github.com/pires/go-proxyproto/commit/f5e61e7b90329bdd7e3c690ad0e17c2940f41ef5). To avoid breakage once they remove the field, we need to adapt to the change. It should be fairly simple and not breaking the users.

**Comment by pi-prakhar** [comment]
@mohammed90 

Can i take this one up?

**Comment by mohammed90** [comment]
Sure, go for it.

**Comment by pi-prakhar** [comment]
@mohammed90 

i have created the pull request containing the necessary changes. #6485 
So let me know if any improvements have to be made or if any additional changes are required.

As this is my first ever open source contribution.
