### ISSUE TITLE
Question: Reverse tunneling to caddy behind a NAT

### ISSUE THREAD

**Issue by crabdancing** [caddyserver/caddy#6486]
My setup is as follows:
1. a VPS (ingress point)
2. A tunnel to transparently move incoming connections from my VPS to my (NAT) business network
3. Caddy (as a unified TLS frontend & reverse proxy)
4. local services on my business network

One of the constraints here is that I can't have the TLS encryption happen on the VPS, as that would in principle allow the VPS to spy on unencrypted traffic.

The problem is that every tunnel technology I've tried resets all IP address information about the connection. This is unacceptable, as the backend service can't block bruteforcing attempts or otherwise punish misbehavior based on IP address.

How do I set up a backend on the server such that clients can connect to the VPS as if the services were hosted there, and have them actually connect to a service on my business network, while still having a useful X-Forwarded-For / X-Real-IP that the services can use to identify the incoming connection? What protocol & service should I use on the VPS side?

**Comment by francislavoie** [comment]
Sounds like you're looking for something that supports PROXY protocol, i.e. prepend the original IP address as bytes in front of the TLS connection when forwarding it along. Caddy supports unwrapping this using [`listener_wrappers`](https://caddyserver.com/docs/caddyfile/options#listener-wrappers). I don't have any particular suggestions though. If at all viable, you can use https://github.com/mholt/caddy-l4 for this (i.e. put it in front, at the edge), it supports accepting and sending PROXY protocol.

**Comment by crabdancing** [comment]
Fair enough, thanks for the input. And sorry about that. I didn't realize you had a dedicated place for usage questions.
