### ISSUE TITLE
[Question] Host modules

### ISSUE THREAD

**Issue by Z3NTL3** [caddyserver/caddy#6494]
> The inline_key= part is only used if the module's name will be found inline with the module itself; this implies that the value is an object where one of the keys is the inline key, and its value is the name of the module. If omitted, then the field type must be a [caddy.ModuleMap](https://pkg.go.dev/github.com/caddyserver/caddy/v2?tab=doc#ModuleMap) or []caddy.ModuleMap, where the map key is the module name.

**Goal**
I try to understand exactly what is meant by the sentence above, for that, I'll explain step for step what I've understood from it. And I ask for a maintainer of Caddy to correct any misunderstanding.

**Trying to assume what is meant by the complete sentence**
I found this very confusing. We provide the ``namespace`` and Caddy looks up in that namespace for the specific module or modules. I get that part. However providing ``inline_key`` tells Caddy to only include modules within the namespace that have the inline key, and it's value being the module name. We know that in Caddy everything is standardized JSON. So if I have a host module with raw struct field:

``caddy:"namespace=http.handlers inline_key=handler"``, does that mean Caddy wile load all handlers in the given namespace only if they have a ``handler`` key.

For example

```go

type SomeMwHandler struct {
          Handler string `json:"handler"`
          ...
}
```

In Caddy config it's translated to:

```json

{"handler": "module_name"}
```

In the other hand, if ``inline_key`` is not used, Caddy will import everything that satisfies the specific ``namespace`` and in the RAW JSON it's provided as ``caddy.ModuleMap``: containing all modules that comfort the namespace ?

I just try to understand, but am I correct? I've gone through the source of Caddy itself, I think the plugin architecture is pretty cool, however for Host and App modules there can be more documentary and examples that explain it more comprehensively.

**Comment by Z3NTL3** [comment]
And another thing I found in the documentation of ``context.go``:

> // To load modules, a "namespace" key is required. For example, to load modules
// in the "http.handlers" namespace, you'd put: `namespace=http.handlers` in the
// Caddy struct tag.
//
// The module name must also be available. If the field type is a map or slice of maps,
// then key is assumed to be the module name if an "inline_key" is NOT specified in the
// caddy struct tag. In this case, the module name does NOT need to be specified in-line
// with the module itself.

So I think I was a bit correct, but now together with the last sentence, It's vague cuz it's saying the Raw field provided to ``LoadModule`` must be already filled with this example as ``caddy.ModuleMap``. Then how does ``http.handlers`` work, for me it was enough to just register it under the namespace, and ``http.handlers`` host module just magically has it's ``ProvidersRaw`` filled, but for ``http.authenticator.providers`` I have to provide my providers manually through ``Authenticator`` which is very unclear...

**Comment by francislavoie** [comment]
If the host module declares that the guest has an inline key, then users writing JSON config must have the inline key inside the JSON object to say which exact module this guest is. The module struct itself should not contain the inline key as a field, it gets stripped out when unmarshaling (i.e. in your SomeMwHandler example, remove the Handler field, it never gets used).

If a ModuleMap type is used instead by the host module as a field in its struct, then you don't have the module name inside the guest module object as an inline key, and instead the guest module's name is the key in the module map. In JSON, the ModuleMap is an object, and every key in that object is going to be a module name, and the values are the modules themselves. A module does not have to be an object type, for example look at HTTP matchers where the path matcher (MatchPath module) is a slice of strings. ModuleMap allows for this because the map keys are the module names so there's no necessity for an inline key to declare the name of the module.

ModuleMap only makes sense in a few key scenarios though, like when the order of configured modules does not matter (order would be preserved if it was an array of objects in JSON instead of a map), and when there should be only a single copy of a given module type. In practice, this means that you can't have two path matchers applied to one handler (because the key in the module map is unique, can only be used once), but since the path matcher is a slice of strings, you can have a single path matcher module with multiple path values; the path matcher will OR the values (so the first matching path will short circuit the matcher and return true for a match).

The Raw fields are basically meant to hold the raw JSON bytes temporarily while the config is being loaded, and once Provision is called then guest modules get loaded into another struct field in the host module, usually using the interface type for that namespace to assert that any guest modules actually implement the interface the host expects (HTTP handlers must have ServeHTTP as per the caddyhttp.MiddlewareHandler interface). See here:

https://github.com/caddyserver/caddy/blob/840094ac65c2c27dbf0be63478d36969a57ce7e0/modules/caddyhttp/routes.go#L90 

You can see that inside a route, you have HandlersRaw which has an inline key, and its type is a slice of JSON raw, meaning that the config must be an array of objects, and those objects must have a `handler` key whose value is the name of the module. Then if you read Provision, you see it calls ProvisionHandlers, which uses LoadModule to transform the raw JSON into a slice of module objects. LoadModule takes the field name to load from as an argument, then uses reflection to look at that fields tags to find out whether it should expect to read for an inline key, and if it finds and structs that don't have the inline key, it will throw an error because it can't determine what type of module to load.

Hopefully that helps, I'm on vacation on my phone right now so this was slow to type, not sure if that covers everything or not

**Comment by Z3NTL3** [comment]
```go
// Gizmo is an example; put your own type here.
type Gizmo struct {
	HandlersRaw caddy.ModuleMap `json:"handlers,omitempty" caddy:"namespace=http.authentication.providers"`
	Handlers map[string]caddyhttp.MiddlewareHandler `json:"-"`
}

// CaddyModule returns the Caddy module information.
func (Gizmo) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.gizmo",
		New: func() caddy.Module { return new(Gizmo) },
	}
}

func (g *Gizmo) Provision(ctx caddy.Context) error {
	// g.HandlersRaw = caddy.ModuleMap{
	// 	"http_basic": make(json.RawMessage, 0),
	// }
	mods, err := ctx.LoadModule(g, "HandlersRaw")
	if err != nil {
		fmt.Printf("err while loading %s\n", err)
		return err
	}

	v := mods.(map[string]any)

	fmt.Printf("mods: %+v %+v\n", mods, v["http_basic"])
	return nil
}
```

```mods: map[] <nil>```



```go
mods: map[http_basic:0xc00059de80] &{HashRaw:[] AccountList:[] Realm: HashCache:<nil> Accounts:map[] Hash:0x3274640 fakePassword:[36 50 97 36 49 52 36 88 51 117 108 113 102 47 105 71 120 110 102 49 107 54 111 77 90 46 82 90 101 74 85 111 113 73 57 80 88 50 80 77 52 114 83 53 108 107 73 75 74 88 100 117 76 71 88 71 80 114 116 54]}
``` 

Some tests^^

For me it was more logical that Caddy fills in all satisfying modules of the namespace, when the Raw is not filled in by the user. If it was filled in by the user, then only the module names provided by the user would be loaded.

**Comment by Z3NTL3** [comment]
That makes sense. I got an additional question if you don't mind.

Given this:

```go
// Gizmo is an example; put your own type here.
type Gizmo struct {
	HandlersRaw caddy.ModuleMap `json:"handlers,omitempty" caddy:"namespace=http.authentication.providers"`
	Handlers map[string]caddyhttp.MiddlewareHandler `json:"-"`
}

// CaddyModule returns the Caddy module information.
func (Gizmo) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.gizmo",
		New: func() caddy.Module { return new(Gizmo) },
	}
}

func (g *Gizmo) Provision(ctx caddy.Context) error {
	// g.HandlersRaw = caddy.ModuleMap{
	//	"http_basic": make(json.RawMessage, 0),
	// }
	mods, err := ctx.LoadModule(g, "HandlersRaw")
	if err != nil {
		fmt.Printf("err while loading %s\n", err)
		return err
	}

	v := mods.(map[string]any)

	fmt.Printf("mods: %+v %+v\n", mods, v["http_basic"])
	return nil
}
``` 

I get: 
```
empty map 
```

If I uncomment the commented parts I get:
```
mods: map[http_basic:0xc00059de80] &{HashRaw:[] AccountList:[] Realm: HashCache:<nil> Accounts:map[] Hash:0x3274640 fakePassword:[36 50 97 36 49 52 36 88 51 117 108 113 102 47 105 71 120 110 102 49 107 54 111 77 90 46 82 90 101 74 85 111 113 73 57 80 88 50 80 77 52 114 83 53 108 107 73 75 74 88 100 117 76 71 88 71 80 114 116 54]}
``` 

Means, that the Raw needs to be explicitly filled instead of that Caddy knows: Hey, the struct tag is given me a namespace, and the raw was not prefilled, thus I will return ``caddy.ModuleMap`` which is ``map[string]any`` and fill all modules in this namespace into the Raw field. Type asserting later to whatever namespace it is. 

But given the previous example, it didn't do that and I had to manually tell Caddy. If I just don't want Caddy loading all modules, then I can explicitly tell which modules I want like above, I would find that more comfortable. 

And how do ``http.handlers`` modules, magically plug into this namespace implicitly?

This is how I think due to somewhere in the doc, I've read that Caddy handles modules implicitly like how Go does with interfaces (and I know that Caddy means interfaces with namespace, Caddy can know what stuff that got plugged into it belongs to what namespace, then why was ``LoadModule``'s design not accomodated to this style.)

However IDK if I understood it all correctly, will not write a host module but only guest modules. I am a student and was fun digging into  a bit, just for fun.

I would appreciate any eloboration to my final question whenever you have time for it, and I am grateful for your answer to my first question regardless of being on vacation 😂, thnx.

Btw have great fun and a nice vacation!

**Comment by francislavoie** [comment]
Hmm well it depends what you passed as your JSON config for that module. What's the config you used? Can't really look at how a module runs in isolation without the config fed into it. With your commented bit, you're kinda mocking the config.

I'm not exactly sure what your goal is with that. What exactly are you trying to achieve?

**Comment by Z3NTL3** [comment]
Sorry but I very confused about Host modules:

```go
type Authentication struct {
	// A set of authentication providers. If none are specified,
	// all requests will always be unauthenticated.
	ProvidersRaw caddy.ModuleMap `json:"providers,omitempty" caddy:"namespace=http.authentication.providers"`

	Providers map[string]Authenticator `json:"-"`

	logger *zap.Logger
}

// CaddyModule returns the Caddy module information.
func (Authentication) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.authentication",
		New: func() caddy.Module { return new(Authentication) },
	}
}

// Provision sets up a.
func (a *Authentication) Provision(ctx caddy.Context) error {
	a.logger = ctx.Logger()
	a.Providers = make(map[string]Authenticator)
	mods, err := ctx.LoadModule(a, "ProvidersRaw")
	if err != nil {
		return fmt.Errorf("loading authentication providers: %v", err)
	}
	for modName, modIface := range mods.(map[string]any) {
		a.Providers[modName] = modIface.(Authenticator)
	}
	return nil
}
```

How does this work, but my example, which did the exact same, couldn't load without explicitly filling the Raw by myself (instead of that I expected Caddy to fill it in for me).

And look at this https://github.com/ggicci/caddy-jwt/blob/main/caddyfile.go#L82
it creates a complete new instance of the authentication namespace, and this user provided explicitly the raw, so how will Caddy manage to plug some already existing instance with this new provider added, cuz theyre seperated.

**Comment by Z3NTL3** [comment]
> Hmm well it depends what you passed as your JSON config for that module. What's the config you used? Can't really look at how a module runs in isolation without the config fed into it. With your commented bit, you're kinda mocking the config.
> 
> I'm not exactly sure what your goal is with that. What exactly are you trying to achieve?
> 
> Remember that ModuleMap only makes sense in a few rare scenarios, your default should be to use json.RawMessage

and btw i think im understanding the ``inline_key`` if i make my own host module is it ok for if it supports ``Caddyfile``, when unmarshalling Caddyfile tokens adding opaque ``inline_key`` not a part from the struct.

**Comment by Z3NTL3** [comment]
> That makes sense. I got an additional question if you don't mind.
> 
> Given this:
> 
> ```go
> // Gizmo is an example; put your own type here.
> type Gizmo struct {
> 	HandlersRaw caddy.ModuleMap `json:"handlers,omitempty" caddy:"namespace=http.authentication.providers"`
> 	Handlers map[string]caddyauth.Authenticator `json:"-"`
> }
> 
> // CaddyModule returns the Caddy module information.
> func (Gizmo) CaddyModule() caddy.ModuleInfo {
> 	return caddy.ModuleInfo{
> 		ID:  "http.handlers.gizmo",
> 		New: func() caddy.Module { return new(Gizmo) },
> 	}
> }
> 
> func (g *Gizmo) Provision(ctx caddy.Context) error {
> 	// g.HandlersRaw = caddy.ModuleMap{
> 	//	"http_basic": make(json.RawMessage, 0),
> 	// }
> 	mods, err := ctx.LoadModule(g, "HandlersRaw")
> 	if err != nil {
> 		fmt.Printf("err while loading %s\n", err)
> 		return err
> 	}
> 
> 	v := mods.(map[string]any)
> 
> 	fmt.Printf("mods: %+v %+v\n", mods, v["http_basic"])
> 	return nil
> }
> ```
> 
> I get:
> 
> ```
> empty map 
> ```
> 
> If I uncomment the commented parts I get:
> 
> ```
> mods: map[http_basic:0xc00059de80] &{HashRaw:[] AccountList:[] Realm: HashCache:<nil> Accounts:map[] Hash:0x3274640 fakePassword:[36 50 97 36 49 52 36 88 51 117 108 113 102 47 105 71 120 110 102 49 107 54 111 77 90 46 82 90 101 74 85 111 113 73 57 80 88 50 80 77 52 114 83 53 108 107 73 75 74 88 100 117 76 71 88 71 80 114 116 54]}
> ```
> 
> Means, that the Raw needs to be explicitly filled instead of that Caddy knows: Hey, the struct tag is given me a namespace, and the raw was not prefilled, thus I will return `caddy.ModuleMap` which is `map[string]any` and fill all modules in this namespace into the Raw field. Type asserting later to whatever namespace it is.
> 
> But given the previous example, it didn't do that and I had to manually tell Caddy. If I just don't want Caddy loading all modules, then I can explicitly tell which modules I want like above, I would find that more comfortable.
> 
> This is how I think due to somewhere in the doc, I've read that Caddy handles modules implicitly like how Go does with interfaces (and I know that Caddy means interfaces with namespace, Caddy can know what stuff that got plugged into it belongs to what namespace, then why was `LoadModule`'s design not accomodated to this style.)
> 
> However IDK if I understood it all correctly, will not write a host module but only guest modules. I am a student and was fun digging into a bit, just for fun.
> 
> I would appreciate any eloboration to my final question whenever you have time for it, and I am grateful for your answer to my first question regardless of being on vacation 😂, thnx.
> 
> Btw have great fun and a nice vacation!

Btw with this previous example I found out that it had nothing to do but with a wrong Caddyfile.

```

{
	debug
	order gizmo before respond
}

:2000 {
	basic_auth bcrypt {
		# Username "Bob", password "hiccup"
		Bob $2a$14$Zkx19XLiW6VYouLHR5NmfOFU0z2GTNmpkT/5qqR7hx4IjWJPDhjvG
	}
	gizmo
	respond "hi"
}
```

has to be: 
```go


{
	debug
	order gizmo before respond
	order gizmo after basic_auth
}

:2000 {
	basic_auth bcrypt {
		# Username "Bob", password "hiccup"
		Bob $2a$14$Zkx19XLiW6VYouLHR5NmfOFU0z2GTNmpkT/5qqR7hx4IjWJPDhjvG
	}
	gizmo
	respond "hi"
}
```

and now: 

```go
func (g *Gizmo) Provision(ctx caddy.Context) error {
	// g.HandlersRaw = caddy.ModuleMap{
	// 	"http_basic": make(json.RawMessage, 0),
	// }
	mods, err := ctx.LoadModule(g, "HandlersRaw")
	if err != nil {
		fmt.Printf("err while loading %s\n", err)
		return err
	}

	v := mods.(map[string]any)

	fmt.Printf("mods: %+v %+v\n", mods, v["http_basic"])
	return nil
}

```



Did successfully load the modules in the given namespace

**Comment by Z3NTL3** [comment]
So in scenerios where you have a Raw field of type ``caddy.ModuleMap`` and you're loading it, you can expect it to be filled with all modules in that namespace.

However the godoc, didn't tell that thoroughly:
```
// To load modules, a "namespace" key is required. For example, to load modules
// in the "http.handlers" namespace, you'd put: `namespace=http.handlers` in the
// Caddy struct tag.
//
// The module name must also be available. If the field type is a map or slice of maps,
// then key is assumed to be the module name if an "inline_key" is NOT specified in the
// caddy struct tag. In this case, the module name does NOT need to be specified in-line
// with the module itself.
```

**Comment by Z3NTL3** [comment]
"The module name must also be available. If the field type is a map or slice of maps, then key is assumed to be the module name if an "inline_key" is NOT specified in the caddy struct tag." --- As of my previous comment, it clearly did not have a module name in ``caddy.ModuleMap`` set beforehand, but Caddy did automatically fill it. This is not clearly stated in my opinion, cuz i was confused about how it functions.

**Comment by Z3NTL3** [comment]
Something else that made me confused about the way how Caddy's plugin system works is inspecting this code;
> https://github.com/ggicci/caddy-jwt/blob/main/caddyfile.go#L82

Is this intended use-case? Cuz the Caddy Architecture stated:
> "A module -- or any Caddy plugin -- gets "plugged in" to Caddy by adding an import for the module's package."

However if ``http.authentication.providers`` (Host module) get's plugged in then, there will be an instance of it, but the code example I've mentioned makes a new ``Authentication`` instance, how will two different instances of the Host module potentially plug. I think that is false usage right? 

Because of the lack of Host module examples, I did look into a bit open-source Caddy plugins and got more confused.

**Comment by mholt** [comment]
The difference looks like this:

Inline key:

```json
{
    "my_inline_key": "module_name",
    ...
}
```

Useful for keeping the name of the module together with the rest of its config.

In other cases, the module name might be an object key instead of an object value:

```json
"module_name": {
    ...
}
```

There's no "inline key" here because the module name appears as part of a parent object (usually a `map`) so what follows as the value is strictly the module's configuration.

**Comment by Z3NTL3** [comment]
> The difference looks like this:
> 
> Inline key:
> 
> ```json
> {
>     "my_inline_key": "module_name",
>     ...
> }
> ```
> 
> Useful for keeping the name of the module together with the rest of its config.
> 
> In other cases, the module name might be an object key instead of an object value:
> 
> ```json
> "module_name": {
>     ...
> }
> ```
> 
> There's no "inline key" here because the module name appears as part of a parent object (usually a `map`) so what follows as the value is strictly the module's configuration.

Thanks to clarify, can you also have a look at my latest question

**Comment by francislavoie** [comment]
Authenticator is the interface but, HTTPBasicAuth is the module. It has a module ID `http_basic`, as declared here:

https://github.com/caddyserver/caddy/blob/master/modules%2Fcaddyhttp%2Fcaddyauth%2Fbasicauth.go#L73

Then in the ModuleMap the key `http_basic` is used, knowing the namespace is `http.authentication.providers` so when the module is loaded, a lookup is made for `http.authentication.providers.http_basic` which will be found because the module was registered (in `init()` which always runs first-thing when the program starts before anything else).

**Comment by Z3NTL3** [comment]
Thanks for the clarification. When I inspected that, I was just like, hmmm. How does Caddy manage to comprise different instances of ``Authentication`` namespace/interface, when they both define different providers and how would they be arranged again into one singular instance.

Because I did also see developers making plugins for the ``Authenticator`` namespace/interface and what they just do in their ``parseCaddyfile`` function (Caddyfile support: ``RegisterHandlerDirective`` : ``has to return MiddlewareHandler``), to comfort that they'll use ``Authentication``. 

```go
return Authentication{
	ProvidersRaw: caddy.ModuleMap{
		"their_provider": caddyconfig.JSON(their_guestModuleStruct, nil),
	},
}, nil
```

Anyways, is there a way of arranging more providers into the first ``Authenticator`` instance programatically. I've inspected ``caddyconfig`` and ``caddyfile`` and could not find anything useful, only ``.Adapt`` however I think it just adapts given stuff to JSON and does not directly register it under Caddy.

**Comment by mholt** [comment]
> Anyways, is there a way of arranging more providers into the first Authenticator instance programatically, without creating more instances.

Every time a module is configured, a new instance is created. If you need to share state/data, you can use global vars or a [UsagePool](https://pkg.go.dev/github.com/caddyserver/caddy/v2#UsagePool).

**Comment by Z3NTL3** [comment]
I was a bit confused, but seem to realize now. I want you to follow my steps to see that the doc's for it can be improved, because I do believe it is not clearly documented. Which resulted in this whole Github issue.

It was just unclear for me how to make a guest module for ``http.authentication.providers``.  I know that I have to comfort ``caddyauth.Authenticator`` and I did. Then I see an ``Authentication`` type (Host module to ``http.authentication.providers`` and a guest to ``http.handlers``) accepts a ``ProvidersRaw``, and so I had to create an instance of ``Authenticator`` which comforts ``caddyauth.Authenticator`` and ``caddyhttp.MiddlewareHandler``. Manually providing my guest module in it's ``ProvidersRaw``, and I did all that in my own module's ``parseCaddyfile`` function.

Then to make a guest module for ``http.handlers``, it was already just enough for me to only satisfy ``caddy.Module``, ``caddy.Unmarshaler`` (for Caddyfile support) and ``caddyhttp.MiddlewareHandler`` that magically worked without me needing to create an instance of the Host module and providing my guest module in it's a HandlersRaw myself. So in constrast the difference was, while writing a guest module for ``http.authentication.providers`` I had to set up the ProvidersRaw, while with ``http.handlers`` it was enough to satisfy the namespace and I didn't need to provide any ``HandlersRaw`` my self

Like that part was the reason for my confusion. Please just try to follow my steps and I think that'll be clear for y'all too, and I think Caddy's plugin architecture is crazy nice however the difference between making a guest module for ``http.handlers`` and ``http.authentication.providers`` is weird to experience. Why does one Host module require me to provide it's instance with my guest explicitly set by my in ProvidersRaw while for ``http.handlers`` comforting the namespace and my ID were enough. I think the way guest modules for ``http.handlers`` seem to work are far more relaxing.

That's my review. My experience for making a guest module for ``http.handlers`` made me say: Caddy's plugin architecture is so unique and lit beyond any other standalone web server/ reverse proxy tool.

Hope I explained it better this time, so it's more clear what I mean

**Comment by francislavoie** [comment]
Yeah I agree auth modules are weird. Matt tried to design it to be pluggable by trying to make a generic Authentication wrapper which could take providers. Doing it that way isn't really necessary, you could write your own auth handler without Authentication if you want. The only thing the Authentication wrapper actually does as you can see here https://github.com/caddyserver/caddy/blob/b1986781740b2b7f546c6ce56496c5cc7145674d/modules/caddyhttp/caddyauth/caddyauth.go is loop over the list of configured providers then fill in some `http.auth.user.*` variables with the result. That's it.

But obviously, see https://github.com/caddyserver/caddy/blob/b1986781740b2b7f546c6ce56496c5cc7145674d/modules/caddyhttp/caddyauth/basicauth.go as a example of a complete and functional auth provider module.

**Comment by mholt** [comment]
Yeah, my initial thought was that it could be useful to have a central place for auth to go in a handler chain, with the added benefit of being able to allow multiple auth sources if needed. Then you don't have to deal with much of the HTTP stuff, making development of the actual auth component less risky and error-prone.

**Comment by Z3NTL3** [comment]
Everything is fine, but I think whenever is the right time, I would recommend providing more examples in the Docs to give a clearer view. Would be helpful to most people.

Now everything is being clear and set, I would like to express my feelings with Caddy again. This is an amazing project, far beyond anything else, even it's plugin architecture being so unique and elegant, is really dope. I've never had experienced writing Plugins with fun. Keep up the great work, and I am grateful for all your efforts for explaining everything!

My sincere greetings

**Comment by mholt** [comment]
Sounds good. Thanks for the feedback!
