### ISSUE TITLE
How to set up a reverse proxy for a non-local host, I didn't find any relevant examples in the official documentation

### ISSUE THREAD

**Issue by tcmagic021** [caddyserver/caddy#6497]
I'm facing an issue now, I want to set up a reverse proxy in Caddy that points to a non-local host, how should I do it?"
for example:
http://iot.a.com {
	# Set this path to your site's directory.
	#root * /usr/share/caddy

	# Enable the static file server.
	file_server

	# Another common task is to set up a reverse proxy:
	reverse_proxy 117.x.99.x:9080

	# Or serve a PHP site through php-fpm:
	# php_fastcgi localhost:9000
}

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
