### ISSUE TITLE
Jellyfin being reverse proxied through Caddy with Cloudflare challenge is failing to playback only on LAN

### ISSUE THREAD

**Issue by excaliburzarau** [caddyserver/caddy#6511]
Hello guys,

I have been having one of those weird issues that is currently not making sense to me and i have not been able to narrow the issue down.

So, I have my network web services being reverse proxied through Caddy with Cloudflare and all the services are working properly except for Jellyfin.
It is working as it should on every single device i have tested while using a VPN (Windows, Linux, Android, IpadOs). 

Now it comes the weird part. 

It also works as it is supposed to for every device i have tested (Windows, Linux, Android) while accesing the Jellyfin on LAN and reverse proxying the DNS with Caddy + Cloudflare, except for my Ipad, which navigates on the Jellyfin UI and when i starts to playback the video that i want to see, it just, does not play it back and it gives me an error. On the logs i have the error, Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate".

If i do the same but instead of putting the DNS on the IpadOs client, if i map it directly by IP and port, i works like a charm and it plays back.

I believe it might be a Caddy related issue. 
I am not sure of what i might be missing or if there is something that is aluding me but i am getting nuts with this.

If someone that already had this issue could point me in the right direction, i would really appreciate it.

Thank you all,
Best Regards

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
