### ISSUE TITLE
Certificates leak when using multiple bind directives

### ISSUE THREAD

**Issue by unidcml** [caddyserver/caddy#6522]
When running Caddy 2.8.4 with multiple bind directives, the server may respond with a certificate that is not intended for it.
```
example1.com {
     bind 127.0.0.1
     tls cert1.pem cert1.key
}

example2.com {
     bind 127.0.0.2
     tls cert2.pem cert2.key
}
```
Certificates were generated by these commands:
```bash
openssl req -x509 -newkey rsa:4096 -keyout cert1.key -out cert1.pem -sha256 -days 365 -nodes -subj "/CN=example1.com"
openssl req -x509 -newkey rsa:4096 -keyout cert2.key -out cert2.pem -sha256 -days 365 -nodes -subj "/CN=example2.com"
```
After connecting with the modified sni, curl receives a certificate from another site in response:
```bash
curl -v --insecure --resolve example1.com:443:127.0.0.2 https://example1.com
```
```
* Added example1.com:443:127.0.0.2 to DNS cache
* Hostname example1.com was found in DNS cache
*   Trying 127.0.0.2:443...
* Connected to example1.com (127.0.0.2) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=example1.com
*  start date: Aug 16 17:02:38 2024 GMT
*  expire date: Aug 16 17:02:38 2025 GMT
*  issuer: CN=example1.com
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://example1.com/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: example1.com]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: example1.com
> User-Agent: curl/8.5.0
> Accept: */*
>
< HTTP/2 200
< alt-svc: h3=":443"; ma=2592000
< server: Caddy
< content-length: 0
< date: Fri, 16 Aug 2024 17:14:44 GMT
<
* Connection #0 to host example1.com left intact
```

**Comment by mholt** [comment]
I might be missing something but that looks like the cert for example1 being returned for a connection to example1. What is the problem exactly?

**Comment by mholt** [comment]
I don't think the certificate logic cares about listeners, it's all the same server. Certificates are interface-agnostic (if you want that, get an IP certificate).

**Comment by mohammed90** [comment]
Keep in mind that the loopback interface almost always has quirks by the operating system. Don't trust loopback interfaces. Try something different.

**Comment by mholt** [comment]
I guess nginx does things differently. Good to know!

**Comment by DanielSidhion** [comment]
I found this issue while browsing for similar issues before creating #6856, and I'd like to ask you folks to reconsider if this is an actual issue in the scenario I describe in #6856.

It looks like if the same Caddy server is serving traffic on both internal and external interfaces, an external attacker might access an internal certificate through a well-crafted request. It seems it's "just" an info leak, but there could be interesting info on an internal certificate to give an attacker more insight into internal infrastructure.
