### ISSUE TITLE
reverseproxy does not forward body with chunked encoding

### ISSUE THREAD

**Issue by uniquefine** [caddyserver/caddy#6545]
I'm using Caddy v2.8.4 as a reverse proxy in front of a golang HTTP server.
The reverse proxy is configured without request buffering.

When a client sends PUT request where the body is sent with chunked encoding the upstream server receives the request with empty body.
If I send the same request directly to the server (bypassing caddy) the handler receives the body.

I think the problem is in this part of the reverse proxy:
https://github.com/caddyserver/caddy/blob/2028da4e74cd41f0f7f94222c6599da1a371d4b8/modules/caddyhttp/reverseproxy/reverseproxy.go#L579-L598

In my case `h.RequestBuffers == 0`, `req.ContentLength == 0` but `req.Body != nil`.
So in line 597 the body is overwritten with `nil` and never forwarded.

I'm not sure how to fix this while still keeping the workaround for golang/go#16036. But if you have suggestions I'd be happy to open a PR.

Also, I did not get a minimal reproducer running yet, please let me know if you think that is necessary.

**Comment by uniquefine** [comment]
Ah, sorry for the mistake. I meant `h.RequestBuffers == 0`. We have not configured any buffering so the condition is not met.

And because the first condition is not hit, the second condition `req.ContentLength == 0` is true and the body is overwritten.

**Comment by francislavoie** [comment]
Nice work tracing that! Thanks for pushing it along ☺️
