### ISSUE TITLE
"caddy add-package", "caddy remove-package",  "caddy list-modules" could have a JSON out param to aid with SBOM and other factors

### ISSUE THREAD

**Issue by gedw99** [caddyserver/caddy#6550]
We could add JSON out on ```caddy add-package``` , ```caddy remove-package``` and ```caddy list-modules --packages --versions``` commands, so that we can do solid automation, to help have a good SBOM practices.

I often do this so that I know whats inside at all times, and pipe it to a file as meta data for all systems.

JSON seems like the defecto format.

Its also  a good way to do higher level automations.

**Comment by mholt** [comment]
Yeah, I think I agree; I haven't intended those commands to automate builds, not in this way. There are better ways to do it with xcaddy.
