### ISSUE TITLE
Current OpenBSD Releases

### ISSUE THREAD

**Issue by anoduck** [caddyserver/caddy#6563]
Current releases of Caddy binary builds do not include a binary build for OpenBSD, and current releases of Caddy binary builds for xcaddy do not provide a binary build for OpenBSD either. Furthermore, using Caddy's website to perform a custom build of OpenBSD to acquire additional features fails as well. 

Why are binaries for OpenBSD only offered on the caddy website?

**Comment by mholt** [comment]
Because OpenBSD comprised, like, < 0.005% of downloads.

I'm guessing you use OpenBSD? (Congrats, you're one of very very few!)

**Comment by anoduck** [comment]
That low? To quote _The Princess Bride_, "That's inconceivable..."

I feel awesome being of an elite crowd.

**Comment by mholt** [comment]
Yeah it was super low. Actual counts were in the double digits.
