### ISSUE TITLE
Release cadence question

### ISSUE THREAD

**Issue by calvinbrewer** [caddyserver/caddy#6570]
Hello! I've noticed some bugs have been fixed over the past few months and have been merged into the main branch, however, the lastest release is 2.8.4 from June 2nd 2024. What is the release cadence for new versions?

**Comment by mholt** [comment]
We don't have a particular schedule, but I do want to focus on a new release after my presentation at API Platform Conference next week.

**Comment by francislavoie** [comment]
Nothing actionable here, just a question, so I'll close.
