### ISSUE TITLE
log format filter attributes  not work

### ISSUE THREAD

**Issue by ljianc** [caddyserver/caddy#6576]
when `encoder_module` is `filter `,Set the following attributes to report error
```
format <encoder_module> {
	message_key     <key>
	level_key       <key>
	time_key        <key>
	name_key        <key>
	caller_key      <key>
	stacktrace_key  <key>
	line_ending     <char>
	time_format     <format>
	time_local
	duration_format <format>
	level_format    <format>
}
```
demo code:
```	
log {
		format filter {
			resp_headers delete
			time_format wall_milli
		}
	}
```
run  `caddy adapt`
Error:
`Error: parsing caddyfile tokens for 'log': getting module named 'caddy.logging.encoders.filter.wall_milli': module not registered: caddy.logging.encoders.filter.wall_milli, at Caddyfile:26`

**Comment by mohammed90** [comment]
FYI, this is the correct format: https://caddyserver.com/docs/caddyfile/directives/log#filter

**Comment by ljianc** [comment]
> FYI, this is the correct format: https://caddyserver.com/docs/caddyfile/directives/log#filter

TKS，Found the problem, Need to use `wrap`，here is the correct ：
```
	log {
		format filter {
			resp_headers delete
			wrap json {
				time_format wall_milli
			}
		}
	}
```
