### ISSUE TITLE
header directive does not work

### ISSUE THREAD

**Issue by Orefa** [caddyserver/caddy#6579]
```powershell
.\caddy_windows_amd64.exe version
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=
```
`Caddyfile`
```
localhost {
    header /* {
		-server
	}
}
```
I want to hide the server information

access no matcher url e.g.  https://localhost/aaa/aaa

The response header will find the server information `server: Caddy`

**Comment by mohammed90** [comment]
The header operations are deferred until at least one handler acts on the request. This means having the `header` directive on its own without any other handler is a noop. Add a `respond` somewhere and you'll the header action.
