### ISSUE TITLE
forward_auth set ultimate response header

### ISSUE THREAD

**Issue by SteveLillis** [caddyserver/caddy#6580]
Hello,

I suspect I am missing something obvious.  My scenario is that the authentication proxy I am using with `forward_auth` sometimes returns a `Set-Cookie` header due to a refresh scenario.  I need the ultimate response for the request to include that Set-Cookie to the user, otherwise their cookie is not updated and they get a refresh scenario on every request.

I've tried variations on the below, but suspect I may be way off.

```
	forward_auth @requiresAuth host.docker.internal:5000  {
		uri /oauth2/check_auth
		copy_headers Authorization

		@authed status 2xx
		handle_response @authed {
			copy_response_headers {
				include Set-Cookie
			}
		}
	}
```

Could you please provide some guidance?

Thank you.

**Comment by francislavoie** [comment]
I think that's a design issue with the way you use cookies. Your cookie should not ever need to be updated. Your cookie should simply be a random identifier that you can use to do a lookup in your session storage to get the session state and whether their session is still valid.

That said, you can just do this, to do what you're asking:

```
		@authed status 2xx
		handle_response @authed {
			header Set-Cookie {rp.header.Set-Cookie}
		}
```

That said, I'm not sure how well that'll behave though because `forward_auth` itself has its own `handle_response` for that status under the hood so it might contend with it if you try to add your own. So you may need to use the long-form instead of `forward_auth`. See https://caddyserver.com/docs/caddyfile/directives/forward_auth#expanded-form

**Comment by SteveLillis** [comment]
@francislavoie 

Thanks for your quick reply.  I had success keeping the cookie on the response using your suggestion, but following the doc using `request_header` doesn't give the same result as `copy_headers` for the Authorization header.

Minimum repro:

```
reverse_proxy @requiresAuth host.docker.internal:5000 {
		method GET
		rewrite /oauth2/check_auth
		header_up X-Forwarded-Method {method}
		header_up X-Forwarded-Uri {uri}

		@authed status 2xx
		handle_response @authed {
			request_header Authorization {rp.header.Authorization}
		}
	}
```

Is there something special that I'm missing?

**Comment by francislavoie** [comment]
You can use `caddy adapt -p` to compare the resulting JSON config.

**Comment by SteveLillis** [comment]
@francislavoie 

Thanks again for your quick reply.  It appears that using `reverse_proxy` instead of `forward_auth` reorders the routes in the resulting config.  The actual content of the route blocks is the same, except for what was named `group5` for `forward_auth` is now named `group4` for `reverse_proxy`.

I will see what I can do to encourage Caddy to behave the same in both cases.  If you have any advice, it would be greatly appreciated.

**Comment by SteveLillis** [comment]
@francislavoie 

I've just clicked that the requests aren't going to my auth proxy because I _think_ the "upstreams" in `reverse_proxy <upstreams...> {`  and `forward_auth [<matcher>] [<upstreams...>] {` are different.  Is there documentation on translating between the two?

**Comment by francislavoie** [comment]
Wrap a `route` block around your directives to force a specific order. 

There's no functional difference between upstreams in forward_auth vs reverse_proxy. The forward_auth directive is simply a Caddyfile shortcut which produces the same JSON config you see.
