### ISSUE TITLE
Is it possible for Caddy to pass on brotli-compressed files?

### ISSUE THREAD

**Issue by nisbet-hubbard** [caddyserver/caddy#6586]
We are considering using Caddy in front of our Apache httpd server to take advantage of its support for post-quantum key exchange.

Since Caddy doesn’t do brotli, we’re hoping to let httpd handle compression and have Caddy simply pass on the compressed files. I’m wondering if this is a viable setup with Caddy?

**Comment by francislavoie** [comment]
Yes, with the file_server precompressed option: https://caddyserver.com/docs/caddyfile/directives/file_server#precompressed

**Comment by mholt** [comment]
Is this asking something different though? It seems you want Apache to compress on the fly, not to have Caddy serve precompressed files, but rather to pass through the encoded data in the proxy to the client, is that right?

**Comment by francislavoie** [comment]
Caddy isn't a caching proxy, so it doesn't matter. If the client has `br` in the `Accept-Encoding` header it sends, your Apache server should be serving brotli, and Caddy will just pass through the response as-is. There's nothing special that needs to happen in Caddy if your upstream is taking care of compression.
