### ISSUE TITLE
Websocket not support yet?

### ISSUE THREAD

**Issue by ssrlive** [caddyserver/caddy#6587]
I try to reverse proxy my special URI `/mypathbWrYWiWL/` as `Websocket`, but it always failed,
it do not send package to target server `http://127.0.0.1:12948` at all.

Here's my `Caddyfile`. What's wrong with it?

```caddy
mysite.com:443 {
    tls s@gmail.com
    encode gzip

    route /mypathbWrYWiWL/ {
        @websockets {
            header Connection *Upgrade*
            header Upgrade websocket
        }
        reverse_proxy @websockets http://127.0.0.1:12948
    }
    handle {
        reverse_proxy https://www.gov.cn {
            trusted_proxies 0.0.0.0/0
            header_up Host {upstream_hostport}
        }
    }
}
```

The similar settings for `nginx` will work fine:
```nginx
        location /mypathbWrYWiWL/ {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:12948;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $http_host;
        }
```

**Comment by francislavoie** [comment]
Websockets are supported. You don't need that `@websockets` matcher at all if you're matching by path.

Are you sure your URL is exactly `/mypathbWrYWiWL/` or is there sometimes something past that like `/mypathbWrYWiWL/foo` or without the trailing slash `/mypathbWrYWiWL`? If so then that matcher is incorrect, it might need to be `/mypathbWrYWiWL*` or `/mypathbWrYWiWL/*`.

All you really need is this (don't need the `route`, don't need the `@websockets` matcher):

```
reverse_proxy /mypathbWrYWiWL/* 127.0.0.1:12948
```
