### ISSUE TITLE
fuzz-replacer: Timeout in fuzz-replacer

### ISSUE THREAD

**Issue by mohammed90** [caddyserver/caddy#6589]
Detailed Report: https://oss-fuzz.com/testcase?key=6525188640931840

Project: caddy
Fuzzing Engine: libFuzzer
Fuzz Target: fuzz-replacer
Job Type: libfuzzer_asan_caddy
Platform Id: linux

Crash Type: Timeout (exceeds 60 secs)
Crash Address:
Crash State:
  fuzz-replacer
 
Sanitizer: address (ASAN)

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_caddy&revision=202406230612

Reproducer Testcase: [clusterfuzz-testcase-minimized-fuzz-replacer-6525188640931840.txt](https://github.com/user-attachments/files/17117733/clusterfuzz-testcase-minimized-fuzz-replacer-6525188640931840.txt)

The log is just ~2800 lines of this:
```
{"level":"error","ts":1727163709.3398857,"msg":"placeholder: failed to read file","file":".","working_dir":"/mnt/scratch0/clusterfuzz","error":"read .: is a directory"}
```

Issue on oss-fuzz tracker: [Issue 42536475](https://issues.oss-fuzz.com/issues/42536475)

**Comment by mohammed90** [comment]
I, honestly, don't know what to do with this one. The timeout is due to having to run against all `{file..}` in the file, and there's no way around either trying to open them for reading or calling `Stat`, and both consume same/more time. It boils down to "the user willingly shot their own foot". It's likely a WONTFIX.

**Comment by mholt** [comment]
I feel like this points to a fuzzer misconfiguration. Is fuzzing address parsing (at least, in this way) really that productive?

My intuition suggests we should be fuzzing things like placeholder evaluation... I don't know what else we really decode/parse/evaluate that is variable/untrusted.
