### ISSUE TITLE
Roadmap to 3.0?

### ISSUE THREAD

**Issue by bubnenkoff** [caddyserver/caddy#6592]
Hi! Is there any roadmap to 3.0?

Is there any plan to improve caddyfile syntax? Is/else blocks at least.

**Comment by francislavoie** [comment]
No plan currently. We're happy to continue improving Caddy v2 as it stands.

No, if/else will _never_ happen. It's not good design. It's fundamentally incompatible with how Caddy was designed anyway.

Request matchers are how you do conditions for HTTP routes: https://caddyserver.com/docs/caddyfile/matchers

**Comment by mholt** [comment]
I'm reminded about how NGINX used to have an article called "If is evil" -- and other pitfalls of NGINX configuration: https://news.ycombinator.com/item?id=37235738

Fortunately, if the Caddyfile isn't your thing, there are numerous other [config adapters](https://caddyserver.com/docs/config-adapters) available. And you could make your own!

We don't have plans for 3.0, and even if we did... we'd probably change our versioning scheme for reasons; but then we'd have to kind of fight Go's semver conventions. So it would be very difficult and inconvenient to advance the major version.
