### ISSUE TITLE
Expose route group name or tracing span ID via Prometheus labels

### ISSUE THREAD

**Issue by bohdan-shulha** [caddyserver/caddy#6597]
Hi there,

First of all, I would love to thank you for giving us such a nice and easy-to-use tool!

I am creating a PaaS based on the Docker Swarm and I need to display metrics on the user's dashboard.

As, by intention, customers may run multiple services (tens-hundreds) on a single Caddy instance, I need to group the data by, at least, the defined route group.

I propose adding the "group" label of the route to the Prometheus metric, like this:

```
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="listen_80",le="0.005",group="some_service_routes"} 78
```

I suspect that changes have to be made here: https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/metrics.go#L120

If you approve this request, I'd be happy to try to implement the change myself (I need this ASAP).

**Comment by bohdan-shulha** [comment]
I believe we can make another option "per handler group" like it is done with the "per_host" metrics.

https://github.com/caddyserver/caddy/pull/6531/files#diff-2da174736271113bb6626821a46fe1a3ad76614899e82f556779f4bc1f2f450aR43

**Comment by mholt** [comment]
Okay. Thanks for commenting!

**Comment by mohammed90** [comment]
> I have decided to go with custom metrics implementation specific to my SaaS.

Note that the merged PR embeds a custom registry. If you're bundling your app with Caddy, you can get the custom registry from the `caddy.Context` via the method `ctx.GetMetricsRegistry()`.
