### ISSUE TITLE
[suggestion] `https-redirect` listener wrapper for https requests sent to http listeners

### ISSUE THREAD

**Issue by MayCXC** [caddyserver/caddy#6607]
similar to `http-redirect` for http->https redirection, `https-redirect` could handle https->http, in the case of a navigation to something like `https://localhost:80/`. (then in many cases this would redirect back to https on port 443.)

would this feature be desirable? currently my browser shows me a ERR_SSL_PROTOCOL_ERROR when it sends a tls request to a caddy plaintext port. it would be nice to know the user always sees a webpage, no matter which incorrect combo of protocol/port they used.

**Comment by francislavoie** [comment]
Nope that can't work. If a client made an HTTPS request, it will not accept anything but a TLS handshake succeeding. Anything else at all (including HTTP) will result in an error. Clients _cannot_ trust anything the server sends it the TLS handshake fails.

**Comment by MayCXC** [comment]
got it, then is it not possible to serve TLS on the "wrong" port for just that request, to redirect it to http:// ? i imagined a tls wrapper that activates based on the bytes received, rather than deactivates like for http-redirect.

**Comment by francislavoie** [comment]
It would only work if the connection could have been successful and serve a trusted certificate.

Ultimately the fundamental issue is why was a URL crafted with HTTPS on the HTTP port? That doesn't make sense.

**Comment by MayCXC** [comment]
for me it was a similar case to what `https-redirect` is intended for, i had a config with custom ports, and a site generator that appended https to hyperlinks to them. so in this case, `https-redirect` could use a tls listener conditionally to serve a redirect if the wrong protocol was used. more of a "why not" feature. i want to implement it just to know that every request ends up at https://:tlsport , but of course only if there is interest.

**Comment by francislavoie** [comment]
> and a site generator that appended https to hyperlinks unconditionally

Then you should focus on fixing that. It should just use `//example.com` for links instead of `https://example.com` which uses the same scheme as the originating request. Or better, use only the path, no domain etc, for links within the site itself.
