### ISSUE TITLE
SSL_ERROR_INTERAL_ERROR_ALERT

### ISSUE THREAD

**Issue by panoskpv** [caddyserver/caddy#6612]
I have Caddy in docker and use certbot to automatically renew certificates outside this docker. Sometimes I get SSL_ERROR_INTERAL_ERROR_ALERT
when i try to reach one of the url one the protected urls getting "TLS handshake error from 192.168.13.1:51214: no certificate available for 'cloudflare-ech.com'" as error in caddy.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
