### ISSUE TITLE
Caddyfile placeholder for site address

### ISSUE THREAD

**Issue by bminer** [caddyserver/caddy#6615]
It is my understanding that there are [certain placeholders](https://caddyserver.com/docs/caddyfile/concepts#placeholders) that can be used anywhere in a Caddyfile and there are [HTTP placeholders](https://caddyserver.com/docs/json/apps/http/#docs) that are available within the context of an HTTP request.

Can we add another placeholder `{site}` that resolves to the [site address](https://caddyserver.com/docs/caddyfile/concepts#structure) of the site block? Crucially, it would *NOT* require the context of a HTTP request like `{http.request.host}` does.

For example, it would be nice to do this:

```caddyfile
(logfile) {
  log {site} {
    output file /var/log/caddy/access-{site}.log
  }
}
example.com {
  import logfile
}
```

rather than what I currently do:

```caddyfile
(logfile) {
  log {args[0]} {
    output file /var/log/caddy/access-{args[0]}.log
  }
}
example.com {
  import logfile example.com
}
```

Thoughts on this? I am happy to submit a PR if you think this is a good idea.

**Comment by francislavoie** [comment]
That can't work because a site block may have more than one site address. See https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by bminer** [comment]
@francislavoie - Makes sense. Was not a big deal anyway. Thanks for your feedback and for all of your hard work on this project!
