### ISSUE TITLE
One specific domain is not working with Caddy

### ISSUE THREAD

**Issue by stonetwig** [caddyserver/caddy#6618]
Hello,

I woke up this morning with some notifications from my server. It had run out of space for storing logs.
So I removed old logs freeing up space but I noticed that several of my sites weren't running. So I rebooted the entire server and now everything was down. I restarted each service but caddy wouldn't boot up.

So I started going over the caddy file, removing some old configuration and adding site by site back into it until I found the culprit.

`www.mysite.com: caching certificate: decoding certificate metadata: unexpected end of JSON input`

```
mysite.com, www.mysite.com {
	root * /var/www/html/mysite/_site/
	file_server
}
```

I mean, it has worked for over a year (domain just got renewed yesterday) and suddently it stopped working? As soon as I put this in, I have other static sites with the exact same content that works, it fails and that is the only error message I got.

Seems like a weird error to me, any help appreciated!

**Comment by francislavoie** [comment]
Unfortunately this is a known issue with our storage writer (in certmagic), which is now fixed and is rolling out in the next release.

The workaround is to wipe out Caddy's storage and let it reissue certificates. You didn't say but I assume you're running as a systemd service, so delete `/var/lib/caddy/.local/share/caddy` and restart Caddy.

**Comment by stonetwig** [comment]
Thank you for the fast response, weren't really expecting that!
But it worked fine when removing the folder and restarting the server.

Caddy is an awesome piece of software.

**Comment by derhuerst** [comment]
I have just run into this problem, too.
@francislavoie Any news when there will be a new caddy release including the fix?

**Comment by francislavoie** [comment]
Use v2.9.0-beta.3
