### ISSUE TITLE
Hostname based routing stops working with multiple Caddy instances running in separate Terminals

### ISSUE THREAD

**Issue by idavollen** [caddyserver/caddy#6626]
Setup:

1. with /etc/hosts, _dao.ciso.com, traefik.ciso.com and secure.ciso.com_ are configured with IP of _127.0.0.1_
2.  a local **wildcard** certificate _*.ciso.com_ for three localhost _dao.ciso.com, traefik.ciso.com_ and _secure.ciso.com_
3. having two separate Caddyfiles (see below), and run caddy command for them respectively in two separate Terminals

**Caddyfile1**:
```

secure.ciso.com {
	tls ./traefik/certs/public.crt ./traefik/certs/private.pem 
	log
    reverse_proxy localhost:3001 {
    }
}


```

**Caddyfile2:**
```

dao.ciso.com {
	tls ./traefik/certs/public.crt ./traefik/certs/private.pem 
	log
    reverse_proxy localhost:9998 {
    }
}


traefik.ciso.com {
	tls ./traefik/certs/public.crt ./traefik/certs/private.pem 
	log
	uri strip_prefix /authnz.ap
	reverse_proxy localhost:9999
}
```

if I run caddy start --config _Caddyfile1_ in one MacOS Terminal, and then open a new Terminal and run caddy start --config _Caddyfile2_, the firstly run caddy web server will intercept all http requests, not only for _https://secure.ciso.com_, but also _https://dao.ciso.com_ and _https://traefik.ciso.com_ unexpectedly, as a result, for both of them I've got blank pages. 

On the contrary, if I run caddy start --config Caddyfile2 in one MacOS Terminal, and then open a new Terminal and run caddy start --config Caddyfile1, the firstly run caddy web server will intercept all http requests, not only for https://dao.ciso.com and https://traefik.ciso.com, but also https://secure.ciso.com  unexpectedly, as a result, for which I've got a blank page. 

In brief, the firstly run caddy reverse proxy will intercept all https traffic against localhost although the incoming HTTP request header, **HOST** doesn't match the given Hostname in the Caddyfile file, which has resulted in malfunctioning of hostname based routing.

However, when I run a single caddy reverse proxy for Caddyfile2, the hostname based routing works well as expected, that is, requests for https://traefik.ciso.com is correctly routed to upstream 9999, and requests for https://dao.ciso.com is correctly routed to upstream 9998

**Comment by francislavoie** [comment]
You can't have two processes listening on the same ports. MacOS might be allowing it at the syscall level (which is super weird, other OSes will not) but only the first process will actually receive connections. There's nothing Caddy can do here. You need to either use different ports for each process, or put all your sites in the same config & Caddy process.
