### ISSUE TITLE
After updating `caddy-api.service` fails to start

### ISSUE THREAD

**Issue by josh-hemphill** [caddyserver/caddy#6630]
I can manually run `caddy run --environ --resume --envfile /etc/caddy/.env` and it runs fine. But the `caddy-api.service` exits with only the following:
```
Loaded: loaded (/usr/lib/systemd/system/caddy-api.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code) since Tue 2024-10-15 08:32:11 PDT; 1min 47s ago
       Docs: https://caddyserver.com/docs/
    Process: 3422 ExecStart=/usr/bin/caddy run --environ --resume --envfile /etc/caddy/.env (code=exited, status=203/EXEC)
   Main PID: 3422 (code=exited, status=203/EXEC)
        CPU: 7ms

Oct 15 08:32:11 git.hemphill.family systemd[1]: Starting caddy-api.service - Caddy...
Oct 15 08:32:11 git.hemphill.family systemd[1]: caddy-api.service: Main process exited, code=exited, status=203/EXEC
Oct 15 08:32:11 git.hemphill.family systemd[1]: caddy-api.service: Failed with result 'exit-code'.
Oct 15 08:32:11 git.hemphill.family systemd[1]: Failed to start caddy-api.service - Caddy.
```

**Comment by francislavoie** [comment]
What do you mean by "updating"? Show your systemd config. Are you sure `/usr/bin/caddy` exists and has the correct permissions?

**Comment by josh-hemphill** [comment]
Just ran package updates, and I assume caddy got updated. Running on Fedora, so there is SELinux, caddy's been running fine for months though. The only thing changed in the systemd service file is the `--envfile /etc/caddy/.env`:
```
[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --resume --envfile /etc/caddy/.env
TimeoutStopSec=5s
LimitNOFILE=1048576
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

I can run `sudo caddy run --environ --resume --envfile /etc/caddy/.env` and it runs just fine without errors.

**Comment by josh-hemphill** [comment]
It still fails when I remove `--envfile /etc/caddy/.env` and `daemon-reload`

**Comment by francislavoie** [comment]
You shouldn't be directly editing the systemd config shipped by the package. See https://caddyserver.com/docs/running#overrides on how to set up overrides.

Are you sure `/usr/bin/caddy` has the right permissions? See https://caddyserver.com/docs/running#selinux-considerations to make sure the binary is allowed by SELinux.

**Comment by josh-hemphill** [comment]
That was it, I think I have a binary with plugins and didn't set labels, sorry about that, not sure why it was working before though.🤔
