### ISSUE TITLE
Only {args.0} placeholders are supported in filenames

### ISSUE THREAD

**Issue by chmac** [caddyserver/caddy#6632]
I was happy to find #1396. But my setup didn't work. Eventually I tried swapping `{args[0]}` for `{args.0}` and it worked.

So to clarify, the following does not work for me:

```Caddyfile
(logging) {
        log {
                output file /var/log/caddy/{args[0]}.access.log {
                        roll_size 10mb
                }
        }
}
```

I get the following error:

    2024-10-15T19:55:41.474956+00:00 v caddy[163215]: Error: loading initial config: loading new config: setting up custom log 'log1': loading log writer module: loading module 'file': provision caddy.logging.writers.file: invalid filename for log file: unrecognized placeholder {args[0]}

It seems like the new args syntax isn't supported in this case. Maybe a note can be added to the docs to address this?

**Comment by francislavoie** [comment]
You're probably on too old a Caddy version. Make sure you're using the latest, v2.8.4.

**Comment by chmac** [comment]
Ah, I think you're right. I installed from Ubuntu and figured it would be current, but I guess it's a couple of versions old. Sorry for the spurious issue, thanks for the quick response.

**Comment by francislavoie** [comment]
Please follow our official installation instructions: https://caddyserver.com/docs/install#debian-ubuntu-raspbian, the version in distro-official repos is outdated and will remain outdated (we have no control).

**Comment by chmac** [comment]
Done, thanks a lot. Caddy has made my life a whole lot simpler. No more wrangling proxy config files in apache! 🧡
