### ISSUE TITLE
ResponseController.EnableFullDuplex errors with "feature not supported"

### ISSUE THREAD

**Issue by daaku** [caddyserver/caddy#6640]
Shouldn't calling `ResponseController.EnableFullDuplex` in a Caddy module be expected to work?:

https://pkg.go.dev/net/http#ResponseController.EnableFullDuplex

Currently it returns `feature not supported`. I'm working around it by guarding it with `req.ProtoAtLeast(2, 0)` since h2 is always full duplex anyway.

**Comment by francislavoie** [comment]
What Caddy version are you using? What Go version did you build with?

**Comment by daaku** [comment]
With Caddy `2.8.4` and `go1.23.2`.

**Comment by francislavoie** [comment]
Okay those versions are fine. I asked because for a time, that option in Caddy had a guard on the Go version since it was only added in one of the two versions Caddy supported at the time. But I realized after asking that, that you weren't using the Caddy option and rather calling itself from your code.

So yes you do need to check the HTTP protocol version before enabling that, that's how Go intended for it to be used. Or just don't, and have the config author enable it via the config.

**Comment by daaku** [comment]
> So yes you do need to check the HTTP protocol version before enabling that, that's how Go intended for it to be used.

Go supports FullDuplex with HTTP 1.1 as well. I can confirm this method works for h1/h2 with a normal http server. From the [docs](https://pkg.go.dev/net/http#ResponseController.EnableFullDuplex):

> For HTTP/1 requests, the Go HTTP server by default consumes any unread portion of the request body before beginning to write the response, preventing handlers from concurrently reading from the request and writing the response. Calling EnableFullDuplex disables this behavior and permits handlers to continue to read from the request while concurrently writing the response.

I think the wrapped `ResponseWriter` Caddy provides is missing this ability. I guess I'm wondering if this is known/intentional behavior, or a side effect of a missing [hidden interface](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/net/http/responsecontroller.go;l=129).

**Comment by francislavoie** [comment]
> Go supports FullDuplex with HTTP 1.1 as well.

I'm not sure what point you're trying to make. Yes, but you need to opt into it. And you should only attempt to opt in (in your own plugin code if that's what you're doing) when the protocol is v1, not v2+.

As I linked, Caddy's global option for enabling it does do this check so it only opts in if the request was v1 (i.e. `r.ProtoMajor == 1`).

> I think the wrapped `ResponseWriter` Caddy provides is missing this ability. I guess I'm wondering if this is known/intentional behavior, or a side effect of a missing [hidden interface](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/net/http/responsecontroller.go;l=129).

What do you mean? Show evidence.

**Comment by WeidiDeng** [comment]
> Go supports FullDuplex with HTTP 1.1 as well. I can confirm this method works for h1/h2 with a normal http server. From the [docs](https://pkg.go.dev/net/http#ResponseController.EnableFullDuplex):

It only works for h1, not for h2. Wonder how you tested it? The specific type implementing this method is `http.response`, `http2.responseWriter` or bundled `http.http2responseWriter` doesn't.

If you tried to enable it for http2/3 requests, this error is expected, as they are full duplex anyway. The interface isn't implemented by these `http.ResponseWriter`s either.

Stdlib provides a method for response wrappers to unwrap themselves to reveal the underlying types and call the relevant methods on them. And most common response writers in caddy implement this interface, so there is no so called hidden interface.

If you can show that this error occurs for http1 requests in your custom plugin, please post some relevant codes that prove your point. Also some config snippets would be appreciated.

**Comment by daaku** [comment]
> It only works for h1, not for h2. Wonder how you tested it? The specific type implementing this method is http.response, http2.responseWriter or bundled http.http2responseWriter doesn't.

You are correct, my test was incorrect. I tested h1 both times.

> If you tried to enable it for http2/3 requests, this error is expected, as they are full duplex anyway. The interface isn't implemented by these http.ResponseWriters either.

Seems like my workaround is actually how this should be implemented, and guarding with `req.ProtoAtLeast(2, 0)` is expected. IMHO seems odd the standard library doesn't allowing calling `EnableFullDuplex` on h2 since it technically works anyway.
