### ISSUE TITLE
Does Caddy support HTTP protocol fallback?

### ISSUE THREAD

**Issue by Matinal111** [caddyserver/caddy#6641]
The QUIC protocol is based on the UDP protocol for transmission, and the LSP providers in my area sometimes limit the speed of the UDP protocol so much that it is almost impossible to use it. Would it be possible for Caddy to automatically fallback to HTTP/2 when the HTTP/3 connection quality is poor to ensure connection stability and user experience?

**Comment by francislavoie** [comment]
It's not up to the server to do any kind of fallback like that, it's up to the client. HTTP/2 over UDP isn't a thing, so if the client connected over UDP, it's the client's responsibility to open a new connection over TCP if it notices poor performance. The server can't do anything (directly) to control how the client connects.
