### ISSUE TITLE
Panic after "update quic-go to v0.48.0" commit

### ISSUE THREAD

**Issue by mattxtaz** [caddyserver/caddy#6643]
Caddy regularly crashes for me after upgrading to commit a211c65, update quic-go to v0.48.0. The log shows:

```
panic: close of closed channel
github.com/quic-go/quic-go@v0.48.0/http3/server.go:289
github.com/quic-go/quic-go/http3.(*Server).serveListener.func1()
github.com/quic-go/quic-go@v0.48.0/http3/server.go:340 +0x128
created by github.com/quic-go/quic-go/http3.(*Server).serveListener in goroutine 115
github.com/quic-go/quic-go@v0.48.0/http3/server.go:333 +0x39
```

Reverting to the previous commit stops the crashes.

**Comment by mholt** [comment]
@marten-seemann FYI

(Graceful shutdown is hard. I assume this is related.)

**Comment by francislavoie** [comment]
@mattxtaz did you try c6f2979986d87d7236b132c687c8887c92248dd8 ? It's a followup which changes how we do graceful shutdown.

**Comment by mattxtaz** [comment]
Yes. Sorry I should have mentioned that. It crashes with that one too so that wasn't a fix in this case I'm afraid.

**Comment by WeidiDeng** [comment]
@mattxtaz Can you try `xcaddy build master --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@shutdown-fix`?

**Comment by mholt** [comment]
Weidi, I've gotta say, thanks for taking on so many of the challenging problems :+1: :100:

**Comment by WeidiDeng** [comment]
Just be sure, you are not reloading caddy at that moment right?

**Comment by mattxtaz** [comment]
> [@mattxtaz](https://github.com/mattxtaz) Can you try `xcaddy build master --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@shutdown-fix`?

I've just applied this fix and am now running master. This seems to work. I could reliably crash it before just refreshing a couple of web pages but it's been running for several minutes. I'll leave it running and keep an eye on it. Thank you for coming up with a patch so quickly!

I am not reloading caddy. All I was doing was restarting it, then refreshing a couple of web pages and it crashed within seconds.

**Comment by mattxtaz** [comment]
I've just experimented a little with restarting caddy. Sometimes it shuts down cleanly with exit code 0, other times it seems to time out waiting and shuts down with exit code 137 which causes podman to log that the container failed. Is that expected? But other than this, it appears that the crash I was reported looks fixed at the moment.

```
Oct 19 09:01:49 tao.xtaz.uk caddy[474553]: {"level":"info","ts":1729324909.3985527,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
Oct 19 09:01:49 tao.xtaz.uk caddy[474553]: {"level":"warn","ts":1729324909.398607,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
Oct 19 09:01:49 tao.xtaz.uk caddy[474553]: {"level":"info","ts":1729324909.3986526,"logger":"http","msg":"servers shutting down with eternal grace period"}
Oct 19 09:01:59 tao.xtaz.uk systemd[1103]: caddy.service: Main process exited, code=exited, status=137/n/a                                                               
Oct 19 09:01:59 tao.xtaz.uk systemd[1103]: caddy.service: Failed with result 'exit-code'.
```

Verses one that worked:

```
Oct 19 09:01:27 tao.xtaz.uk caddy[474378]: {"level":"info","ts":1729324887.230141,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}                             
Oct 19 09:01:27 tao.xtaz.uk caddy[474378]: {"level":"warn","ts":1729324887.2301776,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}                                       
Oct 19 09:01:27 tao.xtaz.uk caddy[474378]: {"level":"info","ts":1729324887.2302244,"logger":"http","msg":"servers shutting down with eternal grace period"}                                
Oct 19 09:01:27 tao.xtaz.uk caddy[474378]: {"level":"info","ts":1729324887.230502,"logger":"admin","msg":"stopped previous server","address":"localhost:2019"}                             
Oct 19 09:01:27 tao.xtaz.uk caddy[474378]: {"level":"info","ts":1729324887.2305396,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}         
```

**Comment by WeidiDeng** [comment]
@marten-seemann.

**Comment by WeidiDeng** [comment]
@mattxtaz What if you just caddy running using the previous commit and not restart it? Does caddy still crash?

**Comment by mattxtaz** [comment]
To confirm,

Commit 48ce47f caddy always restarts normally and never crashes.
Commit a211c65 caddy always crashes after refreshing a page a few times.
Commit c6f2979 caddy still crashes after refreshing a page a few times.
Commit 388c7e8 and --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@shutdown-fix caddy never crashes, problem is fixed/worked around.

All of this is after restarting Caddy (after a crash) and then refreshing some pages several times.

The other second problem I mentioned about error code 137 is a totally different problem, sorry if I confused things there. With that one,

Commit 48ce47f caddy always shuts down and restarts with error code 0.
Commit 388c7e8 and --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@shutdown-fix caddy  caddy sometimes shuts down with error code 0, and sometimes exits with error code 137 after 10 seconds.

I have not tried this with any other commits.

**Comment by WeidiDeng** [comment]
I see, so the only reason you restarted caddy is due to the crash with the reported error message, right?

The 137 is graceful shutdown timeout, and caddy is forcibly killed.

**Comment by francislavoie** [comment]
@mattxtaz would you be able to try it again with [f9d0171](https://github.com/quic-go/quic-go/pull/4707/commits/f9d01716d9f091963ffc334f874d392734db43ca)?

I think you can use this:

```
xcaddy build master --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@f9d0171
```

That would help @marten-seemann have confirmation that the patch is good to go, see https://github.com/quic-go/quic-go/pull/4707#issuecomment-2424982883

**Comment by mattxtaz** [comment]
@francislavoie , @marten-seemann I can confirm that running Caddy with this commit works. It's not crashing at all during page refreshes.

**Comment by JeDaYoshi** [comment]
> Can you try `xcaddy build master --with github.com/quic-go/quic-go=github.com/WeidiDeng/quic-go@shutdown-fix`?

I was running into the same issue, which is fixed by PR https://github.com/quic-go/quic-go/pull/4707.

**Comment by JeDaYoshi** [comment]
Unfortunately seems like the fix was not it.

```
Oct 22 20:49:59 srv caddy[1113237]: panic: close of closed channel
Oct 22 20:49:59 srv systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 22 20:49:59 srv systemd[1]: caddy.service: Failed with result 'exit-code'.
```

My server was running fine until now - the issue must lie somewhere else.
cc @marten-seemann @WeidiDeng

**Comment by francislavoie** [comment]
Are you sure you built correctly with the latest change @JeDaYoshi? Show `caddy build-info`.

**Comment by JeDaYoshi** [comment]
Oh, looks like for some reason it didn't pull the latest version on my most recent build after the PR was merged. Odd.

Apologies for the noise :)

**Comment by francislavoie** [comment]
Go's module proxy caches branch references, so if you used `master` it may have stayed on the previous commit for some time until the cache expires.
