### ISSUE TITLE
Increasing the limit for file_server

### ISSUE THREAD

**Issue by shock0572** [caddyserver/caddy#6644]
We're currently using Caddy to browse and search through its file server interface a series of debugging symbols.
Each one of the directories is over 13000 hashes per symbols and we're hitting this limitation:

https://github.com/caddyserver/caddy/blob/2cac3c5491e6428441ecf668cc4f5a86e67ed9b3/modules/caddyhttp/fileserver/browse.go#L148

would it be possible to increase it, maybe in the `file_server` directive, as an attribute of browse? (`max_limit`?)

```go
file_server {
    browse max_limit BIG_NUMBER
}
```

I know that they're reachable and they can be downloaded, but it would be cool if we could set that limit on our own

**Comment by francislavoie** [comment]
PRs welcome to make it configurable, should be trivial to implement.
