### ISSUE TITLE
Buffer size too small

### ISSUE THREAD

**Issue by Softbox44** [caddyserver/caddy#6652]
Hi. I am running Caddy as reverse proxy in a docker container and all works well. However, I am getting the following log message in Caddy container logs: 

`"msg": "failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."`

Do I need to be concerned? Should I change somehting in my settings?

many thanks

**Comment by mholt** [comment]
It's like the error message said -- does https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes answer your question?

**Comment by francislavoie** [comment]
Like Matt said, I think it's pretty self-explanatory. Nothing actionable for us here.

**Comment by Softbox44** [comment]
ok - I executed the commands on the host. Just thought I did somethjing wrong in Caddy.
Thanks guys!
