### ISSUE TITLE
php_fastcgi adds X-Forwarded-* headers

### ISSUE THREAD

**Issue by roman-khimov** [caddyserver/caddy#6653]
Caddy 2.8.4 acting as a simple PHP server serving Nextcloud instance (rewrites/other things omitted for simplicity):
```
example.com {
    root * /var/www
    file_server
    php_fastcgi unix//run/php/php8.2-fpm.sock {
        ...
    }
```
makes Nextcloud produce a big red warning about incorrect reverse proxy server configuration: "The reverse proxy header configuration is incorrect. This is a security issue and can allow attacker to spoof their IP address as visible to the Nextcloud" with a link to version-specific https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html (older Nextcloud versions can show some variations of this error). This error didn't happen with Caddy 2.4.3.

Notice, there are _zero_ proxies involved in this setting, I just need Caddy to serve some static content and run PHP scripts. Yet, trivial tests with a script from #3976 revealed that X-Forwarded-* headers are in fact added by Caddy anyway. Which becomes obvious after you check https://caddyserver.com/docs/caddyfile/directives/php_fastcgi (since now it's just some synonym of the mighty `reverse_proxy`, while this wasn't the case some versions ago), but it's not so obvious if you just look at the configuration file or overall scheme.

Of course, some
```
header_up -X-Forwarded-For
header_up -X-Forwarded-Host
```
quickly fix the problem, but my question is --- is it correct for Caddy to add any X-Forwarded-* to requests at all in this case? My expectation is that it shouldn't do this.

**Comment by roman-khimov** [comment]
It's not about spoofing risk. It's about the fact that Caddy pretends to be a reverse proxy where in fact it's not. Which makes third-party software freak out a little since it doesn't not expect this behavior and poor administrator trying to fix this either on Caddy side or app side (Nextcloud in this case). Even though he never wanted and does not have any reverse proxies and associated configurations. But OK, it's up to you.

**Comment by francislavoie** [comment]
But it is a reverse proxy. `php_fastcgi` is actually a `reverse_proxy` with the `fastcgi` transport.

**Comment by roman-khimov** [comment]
> But it is a reverse proxy. 

This is purely an implementation detail (and this wasn't the case some releases ago). I doubt I've seen any other server doing this in a similar configuration. If I had any `reverse_proxy` things in my config I wouldn't be asking these questions.

> The whole point of Caddy is to have good, secure defaults to reduce the amount of config users need

Well, I had to add some lines of configuration after the upgrade, wouldn't call this good defaults for this specific case.

**Comment by francislavoie** [comment]
It's not just an implementation detail. It simply is what it is, by definition. The fact that it passes the request over a different protocol than HTTP does not make it not a reverse proxy.

Good defaults implies that it's the right thing for 90%+ of cases. That is true for our implementation of proxy headers.

You just need to follow NextCloud's docs and configure `trusted_proxies` as per https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html.

**Comment by mholt** [comment]
> This is purely an implementation detail (and this wasn't the case some releases ago).

It's been this way since the beginning: The fastcgi functionality has _ALWAYS_ been a proxy to a FastCGI responder. In Caddy v2 (since its release almost 5 years ago now, in 2020), the FastCGI client is built into the `reverse_proxy` handler as a _transport_ module.

> Well, I had to add some lines of configuration after the upgrade, wouldn't call this good defaults for this specific case.

The "good defaults" are now requiring explicit authorization for trusting IPs that can have big implications.

**Comment by roman-khimov** [comment]
Can be simplified a bit: proxying (reverse included) to me is when processing HTTP request consists of performing another HTTP request, while `fastcgi` is a form of good old CGI which is executing some things locally to process an HTTP request. In the first case additional headers make sense (it's all HTTP), in the second they don't, there is no new HTTP request happening.

**Comment by roman-khimov** [comment]
Just some references in case anyone interested. FastCGI itself doesn't have any current specification, but historic one can be found at https://fastcgi-archives.github.io/FastCGI_Specification.html. It (as expected) just adds some new transport specifics and then largely relies on CGI 1.1:

> A Responder FastCGI application has the same purpose as a CGI/1.1 program: It receives all the information associated with an HTTP request and generates an HTTP response.

And CGI 1.1 has section 4.1.18 (https://www.rfc-editor.org/rfc/rfc3875#section-4.1.18):

> Meta-variables with names beginning with "HTTP_" contain values read from the client request header fields, if the protocol used is HTTP.
   ...
   The header data can be presented as sent by the client, or can be rewritten in ways which do not change its semantics.

There is no specific mentioning of server _adding_ a header that never existed in the original request, but if we're to look at the purpose of the protocol:

> The Common Gateway Interface (CGI) [22] allows an HTTP [1], [4] server and a CGI script to share responsibility for responding to
   client requests.  The client request comprises a Uniform Resource Identifier (URI) [11], a request method and various ancillary
   information about the request provided by the transport protocol.

it doesn't look like it was ever intended to happen (at least in any default scenario).

Not insisting on any interpretation of this, YMMV as usual.
