### ISSUE TITLE
`header` directive reordering is not intuitive and should perhaps be reversed like `vars`

### ISSUE THREAD

**Issue by segevfiner** [caddyserver/caddy#6668]
For example, with the `Caddyfile`:

```caddy
http:// {
	root * dist

	handle {
		try_files {path} /index.html
		file_server

		header {
			Cache-Control "public, no-cache"
			X-Content-Type-Options "nosniff"
			X-Frame-Options "DENY"
			Referrer-Policy "strict-origin-when-cross-origin"
		}

		header /favicon.ico {
			Cache-Control "public, max-age=3600"
		}

		header /assets/* {
			Cache-Control "public, max-age=31536000, immutable"
		}
	}
}
```

If you request `/assets/foo` you will get `Cache-Control "public, no-cache"` due to the reordering, non-intuitive, which is why `vars` ordering is reversed. I need to wrap the `header` part in `route` to make it work. Of course, there might be a better way to do this...

**Comment by mholt** [comment]
Have you seen [Composing in the Caddyfile](https://caddy.community/t/composing-in-the-caddyfile/8291#answering-the-question-4)? (Specifically the section I linked to, but check out the whole article.)

**Comment by segevfiner** [comment]
Yeah I read it before. Which is why I added `route` to get the order I want. What I'm suggesting is that maybe it makes sense to reverse the order in which Caddy reorders `header` directives like it does for `var` so this might not be needed for this case..

But that's a breaking change of course, and up to your preferences and taste. 👍

**Comment by francislavoie** [comment]
Alternatively, you can use the `?` syntax to only set a header if none already exists.

```
		header {
			?Cache-Control "public, no-cache"
			X-Content-Type-Options "nosniff"
			X-Frame-Options "DENY"
			Referrer-Policy "strict-origin-when-cross-origin"
		}

		header /favicon.ico {
			Cache-Control "public, max-age=3600"
		}

		header /assets/* {
			Cache-Control "public, max-age=31536000, immutable"
		}
```

**Comment by mholt** [comment]
Yeah, Francis' idea is good. You could probably just replace `handle {` with `route {` in your config above too.

Probably not going to change that at this point... thanks for opening an issue though! Feel free to continue discussion if needed.
