### ISSUE TITLE
Log sampling Caddyfile support

### ISSUE THREAD

**Issue by francislavoie** [caddyserver/caddy#6680]
Our logging stack has sampling support, but it's currently only usable via JSON config. We never wired up Caddyfile config for it.

https://github.com/caddyserver/caddy/blob/b28576396956b3e5642c9f7949b750e2d20b6441/logging.go#L307

We should add Caddyfile support. This should be easy, it should just be a new option added to the `log` directive called `sampling` added in this switch:

https://github.com/caddyserver/caddy/blob/b28576396956b3e5642c9f7949b750e2d20b6441/caddyconfig/httpcaddyfile/builtins.go#L1000

And it should take a block of options, i.e. `interval`, `first` and `thereafter`.

**Comment by nikonhub** [comment]
Hello. I'd like to work on this one :)

**Comment by francislavoie** [comment]
Go ahead, PRs welcome.
