### ISSUE TITLE
Porkbun API hostname change

### ISSUE THREAD

**Issue by oPisiti** [caddyserver/caddy#6685]
Hi!

Porkbun is in process of changing their API hostname from **porkbun.com** to **api.porkbun.com**.
The original still works, but will no longer be available starting from 2024-12-01 00:00:00 UTC, as seen in [API docs](https://porkbun.com/api/json/v3/documentation).

Would it be viable to make the modifications before the deadline?

**Comment by francislavoie** [comment]
It's already been updated. See https://github.com/libdns/porkbun/pull/10
