### ISSUE TITLE
Browse doesn't update file size on refresh with IMS

### ISSUE THREAD

**Issue by tcely** [caddyserver/caddy#6690]
https://github.com/caddyserver/caddy/blob/315715e90ffa25c4ad0d8a96e828dbdf6f638583/modules/caddyhttp/fileserver/browse.go#L131-L139

I was monitoring a job that was appending to a file in a directory I viewed before via Caddy. After the first time I checked for the new file, the size didn't appear to be growing.

I thought maybe my job had crashed, but it was still going and the output file was much larger than Caddy reported.

I checked the access log and saw the status 304 being returned to my browser request. I also noticed the If Modified Since value my browser sent was a few days ago.

There hasn't been a new file created in this directory after the output file for the job I started, so the modification time on the directory itself doesn't change. Caddy isn't checking that any of the files in the directory have been changed before returning 304 to the browser. A simple fix for this problem would be to produce new directory output when the IMS value is older than a few minutes.

**Comment by mohammed90** [comment]
We check the modification time as reported by the operating system for the requested resource. The resource is the directory. If the operating system doesn't update the modification time, it isn't a bug in Caddy. It's best to check why your OS doesn't update the modification time of the directory.

**Comment by tcely** [comment]
> If the operating system doesn't update the modification time, it isn't a bug in Caddy.

The directory modification time isn't supposed to be updated when a file inside of it is changed.

See: https://stackoverflow.com/a/3620704

This appears to be a bad assumption made by Caddy that only causes a new directory listing sometimes and causes stale data that really ought to be fresher.
