### ISSUE TITLE
Some sites missing theme when using socket activation

### ISSUE THREAD

**Issue by sharmay** [caddyserver/caddy#6693]
Host - Fedora coreos 41
Engine - Podman rootless

I was testing https://github.com/caddyserver/caddy/pull/6573

`~/.config/systemd/user/caddy.socket`

```
[Socket]
BindIPv6Only = both
ListenStream=80
ListenStream=443
ListenDatagram=443

[Install]
WantedBy=sockets.target
```

`Caddyfile` (poartial)
```
{
	auto_https disable_certs
	admin off
	default_bind fd/3 {
		protocols h1
	}
	default_bind fd/4 {
		protocols h1 h2
	}
	default_bind fdgram/5 {
		protocols h3
	}
}

https://homepage.example.com {
	import my_subnet_only
	import my_tls
	reverse_proxy homepage:3000
}
https://git.example.com {
	import my_tls
	reverse_proxy forgejo:3000
}

```

When  I visit homepage.example.com I a page without theme, No error in caddy log, no avc denied, no error in chrome. Here is screenshot.
![Image](https://github.com/user-attachments/assets/b06f2357-7339-42a5-ada6-7dcafe4bc314)

if  visit <server>:3000 I get properly themed page
![Image](https://github.com/user-attachments/assets/392e3e66-d5a0-4984-94e0-3306a2790f60)

I am seeing similar issue with paperless-ngx, jellyfin.

Only site which works correctly is git.example.com based on Forgejo, and home assistant.

What am I missing or how to debug this issue?

**Comment by francislavoie** [comment]
Check your browser's network tab, look at which requests are failing to return the correct content. I'm certain this doesn't have anything to do with socket activation.

Enable the `debug` global option, show your Caddy logs, show example `curl -v` requests for the failing URLs.

**Comment by sharmay** [comment]
curl -v is showing identical output.
I opened it in Firefox instead of chrome and page renders properly.
