### ISSUE TITLE
When the upstream address in reverse_proxy contains `labels` placeholder, the health check reports an error

### ISSUE THREAD

**Issue by GoodbyeNJN** [caddyserver/caddy#6695]
Suppose I have a Caddyfile that forwards incoming gateway connections to intranet machines.

```Caddyfile
*.example.com {
	reverse_proxy "{labels.2}.server.local" {
		health_uri /health
	}
}
```

But when I started caddy, its health check reported an error: `invalid use of placeholders in dial address for active health checks {"address": "", "error": "unrecognized placeholder {http.request.host.labels.2 }"}`

I located the following code. Perhaps it should refer to the logic of `fillDialInfo` and perform a similar ReplaceAll here? Please consider this.

https://github.com/caddyserver/caddy/blob/6028ff27fa8eb65ffc0770386cbf6a9ac9f50a48/modules/caddyhttp/reverseproxy/healthchecks.go#L312

https://github.com/caddyserver/caddy/blob/6028ff27fa8eb65ffc0770386cbf6a9ac9f50a48/modules/caddyhttp/reverseproxy/hosts.go#L103-L126

**Comment by francislavoie** [comment]
Active health checks are impossible with placeholders, because the placeholders require the HTTP request to fulfill, but active health checks are set up _outside of requests_ to run in the background continually.

You can use passive health checks though.
