### ISSUE TITLE
Template ".Req.URL" components are empty

### ISSUE THREAD

**Issue by alf5** [caddyserver/caddy#6696]
According to https://caddyserver.com/docs/modules/http.handlers.templates

`.Req.URL` should return "Scheme", "Port", etc...

I have a file `index.html`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Main</title>
  </head>
  <body>
      <h3>URL="{{.Req.URL}}"</h3>
      <h3>host="{{.Req.URL.Host}}"</h3>
      <h3>scheme="{{.Req.URL.Scheme}}"</h3>
      <h3>port="{{.Req.URL.Port}}"</h3>
  </body>
</html>
```

produces:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Main</title>
  </head>
  <body>
      <h3>URL="/"</h3>
      <h3>host=""</h3>
      <h3>scheme=""</h3>
      <h3>port=""</h3>
  </body>
</html>
```

The URL typed in the browser is "https://my.super-duper-site.com/" (i.e. its not localhost :) )

I believe this is a bug

**Comment by mholt** [comment]
From the [Go docs](https://pkg.go.dev/net/http#Request.URL):

>	// For server requests, the URL is parsed from the URI
>	// supplied on the Request-Line as stored in RequestURI.  For
>	// most requests, fields other than Path and RawQuery will be
>	// empty.

You probably want `{{.Host}}` and possibly `{{placeholder ...}}` if you want to access scheme and other variables (though, scheme is usually `https` due to Caddy's defaults).
