### ISSUE TITLE
[Feature request] Query placeholder that includes ?

### ISSUE THREAD

**Issue by uumas** [caddyserver/caddy#6705]
So basically just the current `{query}` placeholder but with the leading `?` included if the query isn't empty. Maybe called `{fullquery}` (`{http.request.uri.fullquery}`) or something like that.

Use case:
I want to redirect domain.tld/path to anotherdomain.tld, preserving query string if present. If I wanted tp preserve path too, I could user `{uri}` or I could use `?{query}` but then then the redirect would be to anotherdomain.tld? if there is no query.

**Comment by francislavoie** [comment]
Yeah good idea. Maybe `{prefixed_query}` would do? I think that name would properly explain the behaviour.
