### ISSUE TITLE
random redir, for A/B testing implementation

### ISSUE THREAD

**Issue by makinghappen** [caddyserver/caddy#6708]
to implement random redir (not using [reverse_proxy](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing)), I came up with such solution.

Is there a cleaner way to get pseudo-random entropy and select a random redirect host to redirect to?

```
{
 admin off
 auto_https off
}

http://:8080 {
 map {http.request.remote.port} {port_srv} {
    ~.*0$ "0"
    ~.*1$ "1"
    ~.*2$ "2"
    ~.*3$ "3"
    ~.*4$ "4"
    ~.*5$ "5"
    ~.*6$ "6"
    ~.*7$ "7"
    ~.*8$ "8"
    ~.*9$ "9"
    default "0"
 }

 map {port_srv}{http.request.remote.host} {redir_srv} {
    ~^[0-2].*[0-3]$ "srv1"
    ~^[0-2].*[4-6]$ "srv2"
    ~^[0-2].*[7-9]$ "srv3"
    ~^[3-5].*[0-3]$ "srv4"
    ~^[3-5].*[4-6]$ "srv5"
    ~^[3-5].*[7-9]$ "srv6"
    ~^[6-9].*[0-3]$ "srv7"
    ~^[6-9].*[4-6]$ "srv8"
    ~^[6-9].*[7-9]$ "srv9"
    default "srv10"
 }

#  respond "{http.request.remote.host} {http.request.remote.port} {port_srv} {redir_srv}"
 redir http://{redir_srv}.example.localhost:8080
}

http://srv1.example.localhost:8080 {
 respond "Server 1"
}
http://srv2.example.localhost:8080 {
 respond "Server 2"
}
http://srv3.example.localhost:8080 {
 respond "Server 3"
}
http://srv4.example.localhost:8080 {
 respond "Server 4"
}
http://srv5.example.localhost:8080 {
 respond "Server 5"
}
http://srv6.example.localhost:8080 {
 respond "Server 6"
}
http://srv7.example.localhost:8080 {
 respond "Server 7"
}
http://srv8.example.localhost:8080 {
 respond "Server 8"
}
http://srv9.example.localhost:8080 {
 respond "Server 9"
}
http://srv10.example.localhost:8080 {
 respond "Server 10"
}
```

**Comment by steffenbusch** [comment]
A couple of weeks ago, I created the "Extra Placeholders Caddy Plugin." Among the various placeholders it provides, `{extra.rand.float}` and `{extra.rand.int}` can be particularly useful in an expression matcher for scenarios like this:

```Caddyfile
:8080 {
    extra_placeholders {
        rand_int 1 100
    }

    @redirectToGoogle expression `{extra.rand.int} <= 25`
    redir @redirectToGoogle https://www.google.com

    @redirectToBing expression `{extra.rand.int} > 25 && {extra.rand.int} <= 50`
    redir @redirectToBing https://www.bing.com

    @redirectToYahoo expression `{extra.rand.int} > 50 && {extra.rand.int} <= 75`
    redir @redirectToYahoo https://www.yahoo.com

    @redirectToDuckDuckGo expression `{extra.rand.int} > 75`
    redir @redirectToDuckDuckGo https://www.duckduckgo.com
}
```

See also:
https://github.com/steffenbusch/caddy-extra-placeholders/tree/main#example-conditional-redirect-based-on-random-value

**Comment by makinghappen** [comment]
@steffenbusch looks nice, thank you, so indeed there is no native functionality in Caddy to implement this? Then, is there a chance that your plugin will be merged into the base?

**Comment by steffenbusch** [comment]
What prevents you from using the Caddy plugin as it is? Why must it be part of the core Caddy codebase?

One of Caddy's biggest advantages is its extensibility and its ecosystem of diverse plugins, each maintained by their respective authors. This modular approach ensures that the burden of maintaining specific functionality doesn't fall on the Caddy core maintainers, especially when plugins rely on external dependencies.

**Comment by francislavoie** [comment]
Yeah I'm not convinced it needs to be in Caddy either. Caddy was designed to be very pluggable.

FYI @steffenbusch you can omit the `expression` tokens in your example config, if your named matcher's first argument starts with a quoted token then it's assumed to be an expression. Slightly shorter.

**Comment by makinghappen** [comment]
@steffenbusch @francislavoie plugin is absolutely fine, I asked because it looked inconsistent to me that Caddy has load-balancing for reverse proxy, but does not have random redirect-based load balancing.

**Comment by francislavoie** [comment]
Caddy's default load balancing policy is random, but that's only to choose a random upstream. What you're trying to do is pretty unusual I think.
