### ISSUE TITLE
`reverse-proxy` : HTTP Keep-alives do not work if/when I leverage keep-alive configuration options in reverse-proxy

### ISSUE THREAD

**Issue by sarfarazahmad89** [caddyserver/caddy#6710]
Apologies for doing a rough brain dump here but if/when i set keepalive options in reverse proxy, they seem to be breaking underlying http.Transport's keepalive option (HTTP Keepalives) . I have tested this in action with tcpdump, but will attempt to dissect the code and update here if/when I find the bug. Unsetting the keepalive options, seems to be doing the trick. I had set 
```bash
-                keepalive 5m
-                keepalive_interval 15s
```

**Comment by mholt** [comment]
What do you mean by breaking it? (Sorry I didn't reply sooner.) Is this still a problem?

**Comment by mholt** [comment]
Okay thanks -- keep us posted!
