### ISSUE TITLE
Can Caddy Access Services Directly via HTTPS Without Separate Configurations?

### ISSUE THREAD

**Issue by sakezerto** [caddyserver/caddy#6723]
First of all, I am not very knowledgeable about computer technology, so please bear with me if I say something incorrect.

I would like to know if Caddy can achieve the following functionality:

For example,

>First, I have bound a domain name [aaa.bbb](url) to my server.

> Second, I have two services running on my server, one on [**port 7777**](url) and the other on [**port 8888**](url).

> I want to know if it is possible to use Caddy to access these services directly via https://aaa.bbb:7777 and https://aaa.bbb:8888 without needing separate configurations.

**Comment by mholt** [comment]
I think so? It kind of depends what you define as a single or sole configuration, versus separate. But a single Caddy instance can do that.
