### ISSUE TITLE
Caddy bricks itself on full filesystem requiring manual intervention

### ISSUE THREAD

**Issue by slatian** [caddyserver/caddy#6725]
Today I ran into an issue that broke caddy for me until I manually deleted its storage files.

Cause of the problem probably was that my servers filesystem was full for a few hours, which I resolved. Caddy ran fine until a later reboot of the server after a system update. Then caddy refused to start with the following relevant error log line:

```
{"level":"error","ts":"2024-12-03T21:38:43Z","logger":"tls","msg":"could not clean default/global storage","error":"unable to acquire storage_clean lock: context canceled"}
```

I'm currently using caddy `v2.8.4` as packaged in alpine linux edge, with the default file storage backend.

A manual and not very elegant `rm -r /var/lib/caddy/.local/share/caddy/` got rid of the problem, but caddy shouldn't brick itself like that in the first place.

**Comment by francislavoie** [comment]
Yes, versions of Caddy prior to v2.9.0 have known issues with its filesystem storage implementation. You can use the latest beta release for the fixes.
