### ISSUE TITLE
invalid configuration: unknown try policy first_exist_fallback

### ISSUE THREAD

**Issue by crrodriguez** [caddyserver/caddy#6726]
master branch, this config

http://foo.example.com http://example.local {
        bind unix//run/caddy/for-cloudflared|0222
        root * /srv/www/htdocs
        php_fastcgi unix//run/php-fpm/php.socket
        file_server
}

results in 

`Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 2: loading matcher modules: module name 'file': http.matchers.file: invalid configuration: unknown try policy first_exist_fallback`

**Comment by francislavoie** [comment]
Ah sorry, we missed a spot. Fixed in https://github.com/caddyserver/caddy/pull/6727
