### ISSUE TITLE
Caddy not renewing corrupt certificates

### ISSUE THREAD

**Issue by ahmedaslam047** [caddyserver/caddy#6730]
Caddy v2.4.8

Recently I received a complain from a client that its domain SSL certificate is not working. On looking into Caddy logs I found that certificate for that domain was corrupt. I was getting this error log:
`{"level":"debug","ts":1712046784.7053675,"logger":"http.stdlib","msg":"http: TLS handshake error from 122.194.52.110:4070: no matching certificate to load for dmarc.happyplankton.com: decoding certificate metadata: invalid character '}' after top-level value"}`

I removed certificate directory and hit domain URL in browser. New certificate was generated and worked fine.

**Question:** Isn't Caddy supposed to remove invalid/corrupt certificates and generate new instead?

Let me know if you need to see my configurations, will share them.

Regards,

**Comment by francislavoie** [comment]
This was a known issue prior to v2.9.0, it's fixed in the latest betas.
