### ISSUE TITLE
Header matcher case sensitivity

### ISSUE THREAD

**Issue by bytestream** [caddyserver/caddy#6731]
caddy version: 2.7.6

Is there a way to make the header match case insensitive? So that it will match both `Connection: upgrade` and `Connection: Upgrade`. I realise I could specify both (`OR` - https://caddyserver.com/docs/caddyfile/matchers#header) but I shouldn't need to specify every case `uPgrade` etc.

[From the docs](https://caddyserver.com/docs/caddyfile/matchers#named-matchers):
```
@ws {
  header Connection *Upgrade*
  header Upgrade websocket
}
reverse_proxy @ws localhost:6001
```

https://httpwg.org/specs/rfc9110.html#field.connection states that the connection options are case insensitive. For context, this issue origins from https://nginx.org/en/docs/http/websocket.html which specifies lowercase `upgrade` and then fails to match the above matcher.

**Comment by steffenbusch** [comment]
Have you tried `header_regexp` https://caddyserver.com/docs/caddyfile/matchers#header-regexp and use the `(?i)` inline modifier for case insensitive?

I would try this, but I am not sure if Caddy v2.7.6 already had this `header_regexp` feature.

```Caddyfile
@ws {
  header_regexp Connection (?i).*Upgrade.*
  header Upgrade websocket
}
reverse_proxy @ws localhost:6001
```

I have not tested this myself, but it could/should work

**Comment by mholt** [comment]
Yeah, if your clients send unpredictable headers, the regex would be my suggestion too. Thanks @steffenbusch !

**Comment by bytestream** [comment]
That works. Thanks @steffenbusch !
