### ISSUE TITLE
reverse_proxy: h2 websocket stuck if client needs to send the first message and encode is enabled

### ISSUE THREAD

**Issue by WeidiDeng** [caddyserver/caddy#6733]
With [this](https://github.com/caddyserver/caddy/commit/9c0c71e5774593e15a555d5c88de0af011e46394) merged, I noticed some of my websockets failed to connect while others succeed.

I disabled `encode` and found out now these requests connect successfully.

The problem is that client requests contain the header `accept-encoding: gzip, deflate, br, zstd`, which is wrapped

https://github.com/caddyserver/caddy/blob/9c0c71e5774593e15a555d5c88de0af011e46394/modules/caddyhttp/encode/encode.go#L155-L160

This response writer will write informational header immediately

https://github.com/caddyserver/caddy/blob/9c0c71e5774593e15a555d5c88de0af011e46394/modules/caddyhttp/encode/encode.go#L250-L252

During websocket upgrade, for http1, the upgrade will write `101` status,

https://github.com/caddyserver/caddy/blob/9c0c71e5774593e15a555d5c88de0af011e46394/modules/caddyhttp/reverseproxy/streaming.go#L122

which will be flushed to the client immediately.

However, for h2, although `FlushError` is called

https://github.com/caddyserver/caddy/blob/9c0c71e5774593e15a555d5c88de0af011e46394/modules/caddyhttp/reverseproxy/streaming.go#L111

response code is `200` same as any other status that indicates success. Because we want to determine if the response can be encoded, this code is stored and flushed later if there is any data from the upstream and we can be sure whether the response can be encoded

https://github.com/caddyserver/caddy/blob/9c0c71e5774593e15a555d5c88de0af011e46394/modules/caddyhttp/encode/encode.go#L262-L269

If the websocket transport a protocol that server sends response first, it is OK as that will cause the status and data to be sent. But if the client sends data first, it won't happen because the response will never be sent, and client thinks the handshake didn't finish.

For now, I created a matcher to ignore encoding for h2 websocket upgrade

```
@not_h2_ws not {
    header :protocol *
    method CONNECT
    protocol http/2
}
encode @not_h2_ws zstd gzip
```

But I think an elegant solution should be implemented.

**Comment by WeidiDeng** [comment]
I suppose I can manually unwrap the response writer until no more unwrap can be done. And use this unwrapped response writer instead. What do you think @mholt ?

**Comment by WeidiDeng** [comment]
h1 [rfc](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6), h2 [rfc ](https://datatracker.ietf.org/doc/html/rfc9113#name-the-connect-method) and h3 [rfc](https://datatracker.ietf.org/doc/html/rfc9114#name-the-connect-method) all states that `CONNECT` requests are used to establish a tunnel to the remote hosts and `200` means the connections is successful. The server should then forward the packets blindly between the client and the remote host.

In websockets over h2 scenario, this is also true. As in all cases where websockets are involved.

**Comment by bt90** [comment]
The h2 WebSocket requests aren't using the `Sec-WebSocket-Key` header which is probably the culprit here. see https://datatracker.ietf.org/doc/html/rfc8441#section-5

> Implementations using this extended CONNECT to bootstrap WebSockets
   do not do the processing of the `Sec-WebSocket-Key` and `Sec-WebSocket-
   Accept` header fields of [[RFC6455](https://datatracker.ietf.org/doc/html/rfc6455)] as that functionality has been
   superseded by the `:protocol` pseudo-header field.

**Comment by bt90** [comment]
Speaking of `Sec-WebSocket-Key` and `Sec-WebSocket-Accept`, I think we're missing the `:protocol` <-> header conversion for the backend?

**Comment by WeidiDeng** [comment]
`:protocol` is converted to `Upgrade` header.

I think for a non successful upgrade, `encode` is still useful, instead of bypassing it completely. Users may choose to display custom page.

**Comment by bt90** [comment]
> `:protocol` is converted to `Upgrade` header.

The problem is that the backend is still using HTTP/1.1 and therefore expects RFC 6455 compliance: https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.1

Since RFC 8441 has dropped those headers, we would have to handle them for the backend connection. That means we need to create a random key in the initial handshake request and strip all obsolete response headers from the handshake response.

**Comment by bt90** [comment]
Apaches mod_http2 does the same:

https://github.com/icing/mod_h2/blob/9f19b6e268198c5e8145bb36e196909c4c9a85df/mod_http2/h2_ws.c#L118-L151

**Comment by WeidiDeng** [comment]
That header is created. Why do you say it's not?

https://github.com/caddyserver/caddy/blob/57ae9c3107014c76d6758d6e5db3c2e8edf41654/modules/caddyhttp/reverseproxy/reverseproxy.go#L414

Anyway, that's not relevant in this issue.

**Comment by bt90** [comment]
My bad, missed it.
