### ISSUE TITLE
Caddyfile An error occurs when adding log configurations

### ISSUE THREAD

**Issue by puzhengwu** [caddyserver/caddy#6741]
2.8.4 + dns.providers.alidns

log {
    output file /var/log/caddy/log.log
        format json
}

caddy reload --config /etc/caddy/Caddyfile
2024/12/10 09:07:06.607 INFO    using config from file  {"file": "/etc/caddy/Caddyfile"}
2024/12/10 09:07:06.610 INFO    adapted config to JSON  {"adapter": "caddyfile"}
Error: sending configuration to instance: caddy responded with error: HTTP 400: {"error":"loading config: loading new config: loading http app module: decoding module config: http: json: cannot unmarshal array into Go struct field ServerLogConfig.servers.logs.logger_names of type string"}

**Comment by francislavoie** [comment]
You probably didn't restart Caddy after rebuilding the new version. The running Caddy is still your old version.
