### ISSUE TITLE
performance issues of reverse_proxy

### ISSUE THREAD

**Issue by J0rmo** [caddyserver/caddy#6751]
Caddy appears to have performance issues in terms of multi-threading with the use of multi-layer of reverse_proxy.
```
# caddy version
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=
```

---
# Server Side (Singapore)

Caddyfile
```
:8081 {
    file_server
    root * /opt/www
}

:8082 {
    reverse_proxy 127.0.0.1:8081
}

:8083 {
    reverse_proxy 127.0.0.1:8082
}

:8084 {
    reverse_proxy 127.0.0.1:8083
}
```
Prepare file for download
```
dd if=/dev/zero of=/opt/www/1000MiB bs=1M count=1000
```

---
# Client Side (Los Angeles)
1-thread download command
```
curl -o /dev/null http://host.domain:port/1000MiB
```
5-threads download command (monitor internet speed with command _vnstat -l_ )
```
echo 1 1 1 1 1 | xargs -n1 -P5 curl -s -o /dev/null http://host.domain:port/1000MiB
```

---
Results (Tried it many times)
```
Port    1-thread     5-threads
8081    ≈ 120Mbps    ≈ 300Mbps
8082    ≈ 100Mbps    ≈  60Mbps
8083    ≈ 100Mbps    ≈  16Mbps
8084    ≈ 100Mbps    ≈  16Mbps
```

**Comment by mholt** [comment]
Interesting; I'm not too surprised though. How many CPUs does your server in Singapore have?

**Comment by mohammed90** [comment]
It'd also be interesting to know the `ulimit` of the server. If it's running as systemd service, please share the unit file.

**Comment by J0rmo** [comment]
> Interesting; I'm not too surprised though. How many CPUs does your server in Singapore have?

1 Core Ryzen 5950X
1024MB RAM

The server's NIC is at 10Gbps

**Comment by J0rmo** [comment]
`# ulimit -a`
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3828
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3828
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
---
`# sysctl -p`
```
net.core.rmem_max = 2097152
net.core.wmem_max = 2097152
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
```
---
`# cat /lib/systemd/system/caddy.service`
```
# caddy.service
#
# For using Caddy with a config file.
#
# Make sure the ExecStart and ExecReload commands are correct
# for your installation.
#
# See https://caddyserver.com/docs/install for instructions.
#
# WARNING: This service does not use the --resume flag, so if you
# use the API to make changes, they will be overwritten by the
# Caddyfile next time the service is restarted. If you intend to
# use Caddy's API to configure it, add the --resume flag to the
# `caddy run` command or use the caddy-api.service file instead.

[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force
TimeoutStopSec=5s
LimitNOFILE=1048576
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

**Comment by J0rmo** [comment]
> It'd also be interesting to know the `ulimit` of the server. If it's running as systemd service, please share the unit file.


`# ulimit -a`
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3828
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 3828
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
---
`# sysctl -p`
```
net.core.rmem_max = 2097152
net.core.wmem_max = 2097152
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
```
---
`# cat /lib/systemd/system/caddy.service`
```
# caddy.service
#
# For using Caddy with a config file.
#
# Make sure the ExecStart and ExecReload commands are correct
# for your installation.
#
# See https://caddyserver.com/docs/install for instructions.
#
# WARNING: This service does not use the --resume flag, so if you
# use the API to make changes, they will be overwritten by the
# Caddyfile next time the service is restarted. If you intend to
# use Caddy's API to configure it, add the --resume flag to the
# `caddy run` command or use the caddy-api.service file instead.

[Unit]
Description=Caddy
Documentation=https://caddyserver.com/docs/
After=network.target network-online.target
Requires=network-online.target

[Service]
Type=notify
User=caddy
Group=caddy
ExecStart=/usr/bin/caddy run --environ --config /etc/caddy/Caddyfile
ExecReload=/usr/bin/caddy reload --config /etc/caddy/Caddyfile --force
TimeoutStopSec=5s
LimitNOFILE=1048576
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

**Comment by mholt** [comment]
Thanks for the details.

> Server side CPU load at 1%~5%,

That's pretty telling, Caddy isn't even getting scheduled much CPU time. If I could request one more bit of data from you: a [profile](https://caddyserver.com/docs/profiling) -- memory/heap, goroutine, and CPU profiles would be ideal!

> When I test 5-threads with 8083 port, the speed stabilizes at around 170Mbps for the first 30 seconds, then starts boosting over 300Mbps

I'm guessing kernel configuration is at play here, but profiles will give us more hints.

**Comment by J0rmo** [comment]
> That's pretty telling, Caddy isn't even getting scheduled much CPU time. If I could request one more bit of data from you: a [profile](https://caddyserver.com/docs/profiling) -- memory/heap, goroutine, and CPU profiles would be ideal!

[goroutine.txt](https://github.com/user-attachments/files/18207787/goroutine.txt)
[heap.txt](https://github.com/user-attachments/files/18207788/heap.txt)

No response when accessing CPU Profile using a browser. 
Downloading it using wget is sometimes unresponsive and sometimes prompts a 500 internal error.
```
--2024-12-20 16:04:03--  http://127.0.0.1:2019/debug/pprof/profile?seconds=1000
Connecting to 127.0.0.1:2019... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2024-12-20 16:04:03 ERROR 500: Internal Server Error.
```
```
--2024-12-20 16:10:28--  http://127.0.0.1:2019/debug/pprof/profile?seconds=1000
Connecting to 127.0.0.1:2019... connected.
HTTP request sent, awaiting response... ^C
```

**Comment by francislavoie** [comment]
You could try using Unix sockets for all the traffic between each step instead of TCP. Could lower overhead. Just use the `bind` directive to serve from a socket file. Each server can listen to both TCP and Unix socket at the same time (set two bind addresses)

**Comment by J0rmo** [comment]
> You could try using Unix sockets for all the traffic between each step instead of TCP. Could lower overhead. Just use the `bind` directive to serve from a socket file. Each server can listen to both TCP and Unix socket at the same time (set two bind addresses)

Yeah, It is work!

**Comment by mholt** [comment]
> No response when accessing CPU Profile using a browser.

What if you try for a shorter time, 1000s is over 15 minutes... try even just 30-60s.

**Comment by J0rmo** [comment]
> What if you try for a shorter time, 1000s is over 15 minutes... try even just 30-60s.

[cpu.zip](https://github.com/user-attachments/files/18213557/cpu.zip)

60s.lax.bin (client in Los Angeles)
`echo 1 1 1 1 1 | xargs -n1 -P5 curl -so /dev/null http://host.domain:8084/100MiB`

60s.sel.bin (client in Seoul)
`echo 1 1 1 1 1 | xargs -n1 -P5 curl -so /dev/null http://host.domain:8083/1000MiB`

> Do you mean that using unix sockets solves the performance degradation?

Yes, there are no performance issues with unix sockets.

Caddyfile
```
:8081 {
    bind 0.0.0.0 unix//dev/shm/8081.sock
    file_server browse
    root * /opt/www
}

:8082 {
    bind 0.0.0.0 unix//dev/shm/8082.sock
    reverse_proxy unix//dev/shm/8081.sock
}

:8083 {
    bind 0.0.0.0 unix//dev/shm/8083.sock
    reverse_proxy unix//dev/shm/8082.sock
}

:8084 {
    reverse_proxy unix//dev/shm/8083.sock
}
```

**Comment by mholt** [comment]
> Yes, there are no performance issues with unix sockets.

Aha, that is great. The problem is TCP connection overhead.

Profiles seem to verify this; very little CPU time and work being done by Caddy itself.

I would suggest using unix sockets, or tuning your kernel's TCP settings.

**Comment by francislavoie** [comment]
What were your performance numbers with Unix sockets?

I think it shows the slowness is in your system's network stack, not with Caddy, I guess.

**Comment by J0rmo** [comment]
> What were your performance numbers with Unix sockets?

## Client Side (Los Angeles, 1Gbps NIC)
```
Port    1-thread     5-threads
8081    ≈ 110Mbps    ≈ 270Mbps
8082    ≈ 100Mbps    ≈ 290Mbps
8083    ≈ 100Mbps    ≈ 280Mbps
8084    ≈ 100Mbps    ≈ 270Mbps
```
## Client Side (Seoul, 5Gbps NIC)
```
Port    1-thread     5-threads
8081    ≈ 310Mbps    ≈ 1.42Gbps
8082    ≈ 300Mbps    ≈ 1.42Gbps
8083    ≈ 320Mbps    ≈ 1.40Gbps
8084    ≈ 310Mbps    ≈ 1.40Gbps
```

**Comment by mholt** [comment]
Very good. Thanks for the data!
