### ISSUE TITLE
Chrome Unable to Access Caddy Reverse Proxy While Other Browsers Work

### ISSUE THREAD

**Issue by papandadj** [caddyserver/caddy#6754]
The Caddy reverse proxy configuration works correctly in Safari and Firefox, but fails to connect in Chrome.

## Current Configuration
```caddy
xxx.xxx.com {
    reverse_proxy http://localhost:9001
}
```

## version
v2.8.4

**Comment by papandadj** [comment]
My mobile Chrome can access the site. I also tested on another person's computer - only desktop Chrome cannot access while other browsers work fine.

**Comment by francislavoie** [comment]
Hi! Thanks for trying Caddy!

Please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
